- bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/HikvisionHandler.java
- bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/handler/IpCameraHandler.java
These changes fix an issue when a camera or NVR is busy and lumps multiple alarm events into the same http packet, or splits a single alarm across multiple packets. Now reads the content length header in the stream and handles accordingly as this was reported as causing issues on the forum. Refactor the alarm function to make future changes easier.
> [ipcamera] Improve Hikvision alarm reliability

- bundles/org.openhab.binding.hdpowerview/pom.xml
- bundles/org.openhab.binding.hdpowerview/src/main/feature/feature.xml
Identical change as in https://github.com/openhab/openhab-addons/pull/10333
> [hdpowerview] Change dependency group id to version available on Maven Central

- bundles/org.openhab.binding.enocean/src/main/resources/OH-INF/config/config.xml
- bundles/org.openhab.binding.enocean/src/main/resources/OH-INF/thing/AutomatedMeterSensor.xml
- bundles/org.openhab.binding.enocean/src/main/resources/OH-INF/thing/CentralCommand.xml
- bundles/org.openhab.binding.enocean/src/main/resources/OH-INF/thing/ClassicDevice.xml
- bundles/org.openhab.binding.enocean/src/main/resources/OH-INF/thing/Contact.xml
- bundles/org.openhab.binding.enocean/src/main/resources/OH-INF/thing/EnvironmentalSensor.xml
- bundles/org.openhab.binding.enocean/src/main/resources/OH-INF/thing/GenericThing.xml
- bundles/org.openhab.binding.enocean/src/main/resources/OH-INF/thing/HeatRecoveryVentilation.xml
- bundles/org.openhab.binding.enocean/src/main/resources/OH-INF/thing/LightSensor.xml
- bundles/org.openhab.binding.enocean/src/main/resources/OH-INF/thing/LightTemperatureOccupancySensor.xml
- bundles/org.openhab.binding.enocean/src/main/resources/OH-INF/thing/MeasurementSwitch.xml
- bundles/org.openhab.binding.enocean/src/main/resources/OH-INF/thing/MechanicalHandle.xml
- bundles/org.openhab.binding.enocean/src/main/resources/OH-INF/thing/MultiFunctionSmokeDetector.xml
- bundles/org.openhab.binding.enocean/src/main/resources/OH-INF/thing/OccupancySensor.xml
- bundles/org.openhab.binding.enocean/src/main/resources/OH-INF/thing/PushButton.xml
- bundles/org.openhab.binding.enocean/src/main/resources/OH-INF/thing/RockerSwitch.xml
- bundles/org.openhab.binding.enocean/src/main/resources/OH-INF/thing/Rollershutter.xml
- bundles/org.openhab.binding.enocean/src/main/resources/OH-INF/thing/RoomOperatingPanel.xml
- bundles/org.openhab.binding.enocean/src/main/resources/OH-INF/thing/TemperatureHumiditySensor.xml
- bundles/org.openhab.binding.enocean/src/main/resources/OH-INF/thing/TemperatureSensor.xml
- bundles/org.openhab.binding.enocean/src/main/resources/OH-INF/thing/Thermostat.xml
- bundles/org.openhab.binding.enocean/src/main/resources/OH-INF/thing/bridge.xml
> [enocean] Fix deprecated tag "required"

- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaBaseThingHandler.java
- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaElectricitySensorHandler.java
- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaValveHeatingSystemHandler.java
- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaZwaveHeatingSystemHandler.java
- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/model/SomfyTahomaDevice.java
> [somfytahoma] Improved handling of target temperature command

- bundles/org.openhab.persistence.influxdb/README.md
- bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/InfluxDBPersistenceService.java
- bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/InfluxDBConfiguration.java
- bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/InfluxDBMetadataUtils.java
- bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/ItemToStorePointCreator.java
- bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/RepositoryFactory.java
- bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/influx1/Influx1FilterCriteriaQueryCreatorImpl.java
- bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/influx1/InfluxDB1RepositoryImpl.java
- bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/influx2/Influx2FilterCriteriaQueryCreatorImpl.java
- bundles/org.openhab.persistence.influxdb/src/main/resources/OH-INF/config/config.xml
- bundles/org.openhab.persistence.influxdb/src/test/java/org/openhab/persistence/influxdb/internal/InfluxFilterCriteriaQueryCreatorImplTest.java
- bundles/org.openhab.persistence.influxdb/src/test/java/org/openhab/persistence/influxdb/internal/ItemToStorePointCreatorTest.java
Add option for using the metadata value as measurement name. Part of solution for #9556 
Signed-off-by: Johannes Ott <info@johannes-ott.net>
> [influxdb] Add option for using metadata value as measurement name

- bundles/org.openhab.binding.enocean/src/main/resources/OH-INF/thing/CentralCommand.xml
- bundles/org.openhab.binding.enocean/src/main/resources/OH-INF/thing/ClassicDevice.xml
- bundles/org.openhab.binding.enocean/src/main/resources/OH-INF/thing/GenericThing.xml
- bundles/org.openhab.binding.enocean/src/main/resources/OH-INF/thing/HeatRecoveryVentilation.xml
- bundles/org.openhab.binding.enocean/src/main/resources/OH-INF/thing/MeasurementSwitch.xml
- bundles/org.openhab.binding.enocean/src/main/resources/OH-INF/thing/Rollershutter.xml
- bundles/org.openhab.binding.enocean/src/main/resources/OH-INF/thing/Thermostat.xml
> [enocean] Do not set attr "required" for the param "senderIdOffset"

- bundles/org.openhab.binding.gpstracker/src/main/resources/OH-INF/thing/tracker.xml
Signed-off-by: Gabor Bicskei <gbicskei@gmail.com>
Converting received GPS accuracy from SI to Imperial resulted a value with decimal fraction (<1 yd) . When the state description is created from the thing (Create Equipment From Thing option) the default label pattern is taken from the binding. Using %d pattern threw a formatting exception. Changed to %.1f %unit%.
Fixes #10053
> [gpstracker] Support for military grade GPS accuracy (<1yd)

- bundles/org.openhab.binding.bsblan/README.md
The repository of the BSB-LAN device has been renamed, this PR updates the link to it.
> [bsblan] Updated the link to the BSB-LAN device repository in README.md

- bundles/org.openhab.binding.exec/src/main/feature/feature.xml
- bundles/org.openhab.binding.leapmotion/src/main/feature/feature.xml
- bundles/org.openhab.io.openhabcloud/src/main/feature/feature.xml
- bundles/org.openhab.persistence.dynamodb/src/main/feature/feature.xml
- bundles/org.openhab.persistence.influxdb/src/main/feature/feature.xml
- bundles/org.openhab.persistence.jdbc/src/main/feature/feature.xml
- bundles/org.openhab.persistence.jpa/src/main/feature/feature.xml
- bundles/org.openhab.persistence.rrd4j/src/main/feature/feature.xml
- bundles/org.openhab.transform.exec/src/main/feature/feature.xml
- bundles/org.openhab.voice.voicerss/src/main/feature/feature.xml
The groupId variable results in the wrong configfile GAV when building a single KAR with `karaf:kar` for an add-on.
> Fix broken configfile GAV with karaf:kar

- bundles/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/internal/SenseBoxAPIConnection.java
- Gracefully handle `JsonSyntaxException`
```
2021-03-17 10:55:02.872 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 1 column 4 path $
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224) ~[?:?]
at com.google.gson.Gson.fromJson(Gson.java:888) ~[?:?]
at com.google.gson.Gson.fromJson(Gson.java:853) ~[?:?]
at com.google.gson.Gson.fromJson(Gson.java:802) ~[?:?]
at com.google.gson.Gson.fromJson(Gson.java:774) ~[?:?]
at org.openhab.binding.sensebox.internal.SenseBoxAPIConnection.reallyFetchDataFromServer(SenseBoxAPIConnection.java:70) ~[?:?]
at …
```
> [sensebox] Gracefully handle JsonSyntaxException

- bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/PioneerAvrBindingConstants.java
- bundles/org.openhab.binding.pioneeravr/src/main/resources/OH-INF/thing/thing-types.xml
* Added support for Pioneer VSX-922 for auto-discovery
I've tested the model of Pioneer AVR I own and confirmed it works with this binding.
Signed-of-by: Nathan Prins <nathanprins@hotmail.com>
> [pioneeravr] Added support for Pioneer VSX-922 AVR

- bundles/org.openhab.binding.mihome/README.md
- bundles/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/XiaomiGatewayBindingConstants.java
- bundles/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/handler/XiaomiBridgeHandler.java
- bundles/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/socket/XiaomiBridgeSocket.java
- bundles/org.openhab.binding.mihome/src/main/resources/OH-INF/config/config.xml
[MiHome] Add a Bridge property for the network interface to be used for multicast traffic
This MR adds a property on the Bridge Thing to allow explicit configuration of the network interface name to which the MulticastSocket is bound.
When the computer running OpenHAB has more than one network interface configured (typically, a VLAN for your segregated IoT devices, and the other for your regular traffic like internet, OpenHAB panel access, etc), it could be that OpenHAB will attempt to listen for Multicast traffic of the Gateway on the wrong network interface. Depending on the OS the network interface chosen for binding the Multicast traffic depends on routing rules, default gateway or plain interface order (don't quote me on that). Couldn't find a specific document that describes the …
> [MiHome] Add a Bridge property for the network interface to be used for multicast traffic

- bundles/org.openhab.binding.openwebnet/pom.xml
Move to new openwebnet4j lib version 0.4.1 published on Maven Central instead of JCenter (Fixes #10395).
New groupId for the lib is `io.github.openwebnet4j`.
The new lib also Fixes #10298.
> [openwebnet] Move to io.github.openwebnet4j 0.4.1 from Maven Central

- bundles/org.openhab.voice.picotts/src/main/java/org/openhab/voice/picotts/internal/PicoTTSAudioStream.java
- bundles/org.openhab.voice.picotts/src/main/java/org/openhab/voice/picotts/internal/PicoTTSService.java
- bundles/org.openhab.voice.picotts/src/main/java/org/openhab/voice/picotts/internal/PicoTTSVoice.java
As an example that you can do this now that the classes got annotated with https://github.com/openhab/openhab-core/pull/2255.
> [picotts] Add null annotations

- CODEOWNERS
- bom/openhab-addons/pom.xml
- bundles/org.openhab.binding.mecmeter/NOTICE
- bundles/org.openhab.binding.mecmeter/README.MD
- bundles/org.openhab.binding.mecmeter/pom.xml
- bundles/org.openhab.binding.mecmeter/src/main/feature/feature.xml
- bundles/org.openhab.binding.mecmeter/src/main/java/org/openhab/binding/mecmeter/MecMeterBindingConstants.java
- bundles/org.openhab.binding.mecmeter/src/main/java/org/openhab/binding/mecmeter/MecMeterDeviceConfiguration.java
- bundles/org.openhab.binding.mecmeter/src/main/java/org/openhab/binding/mecmeter/handler/MecMeterHandler.java
- bundles/org.openhab.binding.mecmeter/src/main/java/org/openhab/binding/mecmeter/internal/MecMeterHandlerFactory.java
- bundles/org.openhab.binding.mecmeter/src/main/java/org/openhab/binding/mecmeter/internal/discovery/MecMeterDiscoveryParticipant.java
- bundles/org.openhab.binding.mecmeter/src/main/java/org/openhab/binding/mecmeter/internal/dto/MecMeterResponse.java
- bundles/org.openhab.binding.mecmeter/src/main/resources/OH-INF/binding/binding.xml
- bundles/org.openhab.binding.mecmeter/src/main/resources/OH-INF/thing/thing-types.xml
- bundles/pom.xml
This is a new binding for the din-rail power meter from MEC, see https://www.mec.at/produkte/#mecMeter.
> [mecmeter] Initial contribution of mecmeter binding

- bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/LGWebOSHandlerFactory.java
> [lgwebos] Fix Text Message Size Bug

- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/discovery/SomfyTahomaItemDiscoveryService.java
- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaBaseThingHandler.java
- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaBridgeHandler.java
- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/model/SomfyTahomaDevice.java
- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/model/SomfyTahomaRootPlace.java
- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/model/SomfyTahomaSetup.java
- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/model/SomfyTahomaSubPlace.java
Also include the place into the inbox label (discovery)
> [somfytahoma] New method to send a command to several devices in the same place

- bundles/org.openhab.binding.groheondus/src/main/resources/OH-INF/thing/thing-types.xml
The fields are used to login with username and password instead of a refreshToken.
They're therefore not required.
Signed-off-by: Florian Schmidt <florian.schmidt.welzow@t-online.de>
> [groheondus] Clarify if username/password fields are required

- bundles/org.openhab.binding.miio/src/main/resources/database/viomi.vacuum.v8.json
Viomi's property battery life seems to have a weird typo. The property's real name is `battary_life` instead of `battery_life`. Using the wrong name `battery_life` makes the other properties in the batch to be undefined: `"run_state","mode","err_state","battary_life","box_type"`
The correct name `battary_life` is already used in other projects like https://github.com/rytilahti/python-miio/blob/master/miio/viomivacuum.py#L316 or https://github.com/Hypfer/Valetudo/blob/0bed81ab4f0ddccdad044ce805dda3af8736eb96/lib/robots/viomi/ViomiValetudoRobot.js#L254
> [miio] Fix viomi's battary_life property

- bundles/org.openhab.binding.gpstracker/README.md
- bundles/org.openhab.binding.gpstracker/src/main/java/org/openhab/binding/gpstracker/internal/handler/TrackerHandler.java
Users were complaining about missing region channel triggering after OH restarts. Region channel triggering doesn't depend on binding's previous state anymore:
- In case a location message is received it will trigger the channel if based on the the new calculated distance the state differs from the previous state (now this includes the NULL state as well). So after an OH restart the linked switch will be updated even after the first location message
- In case the message is a transition (e.g. configured in OT application) the trigger event is forced regardless on any previous states
Fixes #6939
> [gpstracker] Forced channel triggering without previous state

- bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/handler/IpCameraHandler.java
Fixed a bug where the warning is given at the wrong time. Reported here on forum:
https://community.openhab.org/t/ipcamera-polling-period-is-ignored/119280
> [ipcamera] Fix warning wrongly when Image poll time is >9 seconds.

- bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/PioneerAvrBindingConstants.java
- bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/handler/AbstractAvrHandler.java
- bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/protocol/ParameterizedCommand.java
- bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/protocol/RequestResponseFactory.java
- bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/protocol/Response.java
- bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/protocol/SimpleCommand.java
- bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/protocol/StreamAvrConnection.java
- bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/protocol/avr/AvrCommand.java
- bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/protocol/avr/AvrConnection.java
- bundles/org.openhab.binding.pioneeravr/src/main/resources/OH-INF/thing/thing-types.xml
* Added channel for changing the active MCACC memory profile on Pioneer AVRs
The left widget is linked to the MCACC channel. The right widget shows the live data on the AVR display for confirmation.
Signed-off-by: Nathan Prins <nathanprins@hotmail.com>
> [pioneeravr] Added channel for changing MCACC Memory profile on AVR

- bundles/org.openhab.binding.lutron/README.md
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/radiora/RS232Connection.java
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/radiora/RS232MessageParser.java
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/radiora/RadioRAConnection.java
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/radiora/RadioRAConnectionException.java
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/radiora/RadioRAFeedbackListener.java
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/radiora/config/DimmerConfig.java
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/radiora/config/PhantomButtonConfig.java
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/radiora/config/RS232Config.java
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/radiora/config/SwitchConfig.java
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/radiora/handler/DimmerHandler.java
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/radiora/handler/LutronHandler.java
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/radiora/handler/PhantomButtonHandler.java
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/radiora/handler/RS232Handler.java
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/radiora/handler/SwitchHandler.java
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/radiora/protocol/ButtonPressCommand.java
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/radiora/protocol/LEDMapFeedback.java
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/radiora/protocol/LocalZoneChangeFeedback.java
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/radiora/protocol/RadioRACommand.java
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/radiora/protocol/RadioRAFeedback.java
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/radiora/protocol/SetDimmerLevelCommand.java
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/radiora/protocol/SetSwitchLevelCommand.java
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/radiora/protocol/ZoneMapFeedback.java
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/radiora/protocol/ZoneMapInquiryCommand.java
- bundles/org.openhab.binding.lutron/src/main/resources/OH-INF/thing/thing-types.xml
This update adds support for bridged RadioRA (classic) systems. A system is considered “bridged” when a Chronos System Bridge and Timeclock is used to integrate two RadioRA Systems in a single residence.
I also took the opportunity to add null annotations to the source files for the RadioRA part of the binding.
> [lutron] Add support for bridged RadioRA (classic) systems

- bundles/org.openhab.binding.enocean/README.md
This PR clarifies how to use the enocean binding with `ser2net`. Most of the setup guides for `ser2net` and `enocean` use `raw` as configuration parameter. 
Openhab however requires `telnet`, otherwise the binding will simply not work / stuck at `getting base id`.
By adding this sentence it makes it immediately clear that a different configuration for `ser2net` is required.
> [enocean] Update Enocean ser2net documentation

- bundles/org.openhab.binding.comfoair/README.md
This binding supports RS232 communication to ComfoAir 350 series, such as the ComfoAir 350 Luxe.
Zehnder has released a new ComfoAir Q-series. These units are confusingly named "ComfoAir Q350". They also offer an RJ45 jack, but use CAN bus signaling to communicate (*not* RS232).
There should be a message warning users about this, before they try to fit square pegs in round holes (such as I did, it was a frustrating experience).
> [comfoair] Update README.md

- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaBridgeHandler.java
> [somfytahoma] Avoid potentiel NPE

- bundles/org.openhab.binding.openthermgateway/README.md
- bundles/org.openhab.binding.openthermgateway/src/main/java/org/openhab/binding/openthermgateway/OpenThermGatewayBindingConstants.java
- bundles/org.openhab.binding.openthermgateway/src/main/java/org/openhab/binding/openthermgateway/internal/DataItemGroup.java
- bundles/org.openhab.binding.openthermgateway/src/main/resources/OH-INF/thing/channels.xml
- bundles/org.openhab.binding.openthermgateway/src/main/resources/OH-INF/thing/otgw.xml
Please see feature request #10198 
Added these new channels to the OpenTherm Gateway binding:
- Unsuccessful burner starts
- Burner starts
- Central heating pump starts
- Domestic hot water pump/valve starts
- Domestic hot water burner starts
- Burner hours
- Central heating pump hours
- Domestic hot water pump/valve hours
- Domestic hot water burner hours *
*\* the last one wasn't actually part of the feature request, but it is part of the same set of statistics/counters of the OpenTherm protocol (message id's 116 - 123) so I added it for the sake of completeness.*
Also fixed a copy/paste error on the diagnostics channel in the README.
> [openthermgateway] add new statistics channels

- bundles/org.openhab.binding.pushover/README.md
- bundles/org.openhab.binding.pushover/src/main/java/org/openhab/binding/pushover/internal/connection/PushoverAPIConnection.java
- bundles/org.openhab.binding.pushover/src/main/java/org/openhab/binding/pushover/internal/factory/PushoverHandlerFactory.java
- bundles/org.openhab.binding.pushover/src/main/java/org/openhab/binding/pushover/internal/handler/PushoverAccountHandler.java
- bundles/org.openhab.binding.pushover/src/main/resources/OH-INF/i18n/pushover.properties
- bundles/org.openhab.binding.pushover/src/main/resources/OH-INF/i18n/pushover_de.properties
- Added exception handling and synchronize method
Fixes #10376
> [pushover] Added exception handling and synchronize method

- bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/handler/RotelHandler.java
> [rotel] Fix handling of InterruptedException (Thread.sleep)

- bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/phonebook/Tr064PhonebookImpl.java
- Use `Util.getAndUnmarshalXML(...)` method to retrieve phonebook (the method supports timeout 5s and caching)
Fixes #10436
> [tr064] Use Util.getAndUnmarshalXML method to retrieve phonebook

- bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudClient.java
This removes the ResponseListener class and replaces it with lambda functions for the various Jetty response listeners. This seems to fix our duplicate onContent issue in #10470 , although i'm not at all clear why.
Fixes #10470
> [openhab-cloud] Fixes Jetty upgrade issue

- bundles/org.openhab.binding.dsmr/src/main/java/org/openhab/binding/dsmr/internal/DSMRHandlerFactory.java
- bundles/org.openhab.binding.dsmr/src/main/java/org/openhab/binding/dsmr/internal/discovery/DSMRBridgeDiscoveryService.java
- bundles/org.openhab.binding.dsmr/src/main/java/org/openhab/binding/dsmr/internal/discovery/DSMRI18nProviderTracker.java
- bundles/org.openhab.binding.dsmr/src/main/java/org/openhab/binding/dsmr/internal/discovery/DSMRMeterDiscoveryService.java
- bundles/org.openhab.binding.dsmr/src/main/java/org/openhab/binding/dsmr/internal/handler/DSMRBridgeHandler.java
- bundles/org.openhab.binding.dsmr/src/test/java/org/openhab/binding/dsmr/internal/discovery/DSMRMeterDiscoveryServiceTest.java
This simplifies the DSMRHandlerFactory code so it no longer needs to register and keep track of a discovery service for each bridge.
Also contains a few other improvements:
* more constructor injection
* add a few missing @NonNullByDefault on test classes
> [dsmr] Use ThingHandlerService for discovery

- bundles/org.openhab.binding.remoteopenhab/src/main/feature/feature.xml
- bundles/org.openhab.binding.velux/src/main/feature/feature.xml
- tools/static-code-analysis/checkstyle/ruleset.properties
This adds the configuration to get things working when the new sat check for the feature.xml would be merged, released and activated here. See https://github.com/openhab/static-code-analysis/pull/395
Depending on review comments on the sat pr there might be changes to this pr required. So it should not be merged before the sat pr is merged.
> Adds exceptions for KarafAddonFeatureCheck

- bundles/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/handler/ChromecastHandler.java
- Initialize connection to devices asynchronously to avoid slow initialization
```
2020-12-04 08:34:25.273 [WARN ] [core.thing.internal.ThingManagerImpl] - Initializing handler for thing 'chromecast:chromecast:cc4c584bfcc8ccd3ab25986161374e62' takes more than 5000ms.
```
> [chromecast] Initialize connection to devices asynchronously

- bundles/org.openhab.binding.pulseaudio/README.md
- bundles/org.openhab.binding.pulseaudio/pom.xml
- bundles/org.openhab.binding.pulseaudio/src/main/feature/feature.xml
- bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/PulseAudioAudioSink.java
- bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/PulseaudioBindingConstants.java
- bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/PulseaudioClient.java
- bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/PulseaudioHandlerFactory.java
- bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/cli/Parser.java
- bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/discovery/PulseaudioDiscoveryParticipant.java
- bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/handler/PulseaudioBridgeHandler.java
- bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/handler/PulseaudioHandler.java
- bundles/org.openhab.binding.pulseaudio/src/main/resources/OH-INF/thing/sink.xml
Add to the pulseaudio binding the capability to use "pulseaudio sink" as an "openhab sink" to output sound from openhab to a pulse audio server on the network.
You need to load module-simple-protocol-tcp sink in addition to the usual module-cli-protocol-tcp, and enable the sink in the thing configuration
Binding release : 
https://github.com/dalgwen/openhab-addons/releases/tag/3.1.0-SNAPSHOT-Audiosink
Closes #1895
> [pulseaudio] Add pulseaudio sink as openhab audio sink (#1895)

- .gitattributes
Added wildcards so that the rules apply to all .java and .xml files.
This makes sure line endings on windows system are properly converted when pulling/pushing and make sure the spotless check will pass both locally and remotely.
Closes #10472
> Fix .gitattributes (#10472)

- pom.xml
- tools/static-code-analysis/checkstyle/suppressions.xml
- Use SAT release version 0.11.1
- Added suppression for new OhInfXmlLabelCheck (PR https://github.com/openhab/static-code-analysis/pull/360)
- Rename "EshInfXmlCheck" to "OhInfXmlCheck"
Release notes:
https://github.com/openhab/static-code-analysis/releases/tag/0.11.0
https://github.com/openhab/static-code-analysis/releases/tag/0.11.1
Fixes https://github.com/openhab/openhab-core/issues/2196
Depends on #10518
> [static-code-analysis] Use SAT release version 0.11.1

- bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcConfiguration.java
- bundles/org.openhab.persistence.jdbc/src/main/resources/OH-INF/config/config.xml
- Added missing config parameters for sqltypes of IMAGE an PLAYER item types
> [jdbc] Added missing config parameters for sqltypes of IMAGE an PLAYER item types

- bundles/org.openhab.binding.netatmo/src/main/resources/OH-INF/thing/healthyhomecoach.xml
- bundles/org.openhab.binding.netatmo/src/main/resources/OH-INF/thing/station.xml
- bundles/org.openhab.binding.netatmo/src/main/resources/OH-INF/thing/thermostat.xml
> [netatmo] Fix the thresholds for the WifiStatus channel

- bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc2/NikoHomeControlCommunication2.java
Fixes missing power data if API sends fractional part.
> [nikohomecontrol] Fix energy meter

- bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/internal/handler/TadoZoneHandler.java
This PR eliminates the "handler disposed" warnings when OH is shutting down.
> [tado] Prevent "handler disposed" warnings on shutdown

- bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/VeluxBridge.java
- bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/slip/SClogin.java
- bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/slip/io/DataInputStreamWithTimeout.java
- bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/slip/io/SSLconnection.java
- bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/factory/VeluxHandlerFactory.java
- bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/handler/VeluxBindingHandler.java
- bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/handler/VeluxBridgeHandler.java
The Velux hub initialization and shutdown processes are very slow and deliberate. And sometimes when OH reloads the binding, it was possible for a newly created `VeluxBridgeHandler` instance's `.initialize()` method to be called before the prior `VeluxBridgeHandler` instance's `.dispose()` method had finished processing i.e. it was attempting to shut down and re-start the hub communication at the same time!
See this [forum post](https://community.openhab.org/t/velux-new-openhab2-binding-feedback-welcome/32926/1259?u=andrewfg)
Therefore this PR introduces the following fixes resp. improvements:
- The `.initialize()` / `.dispose()` methods now defer slow processes to scheduled tasks, so the OH caller thread returns faster.
- The `.initializeScheduled()` method now waits for the Future<> …
> [velux] Fix synchronisation of handler initialization and disposal

- bundles/org.openhab.binding.pulseaudio/README.md
The syntax for listing Pulseaudio sinks is with a space, not dash (two arguments).
Ref https://manpages.ubuntu.com/manpages/trusty/man1/pactl.1.html
> [pulseaudio] Fix typo in pactl list sinks example

- bundles/org.openhab.binding.modbus/README.md
- bundles/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/profiles/ModbusGainOffsetProfile.java
- bundles/org.openhab.binding.modbus/src/test/java/org/openhab/binding/modbus/internal/profiles/ModbusGainOffsetProfileTest.java
Corrects profile parameter name in docs, logging and code comments.
Correct parameter name is `pre-gain-offset`.  Functionally everything worked:
- https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/profiles/ModbusGainOffsetProfile.java#L56
- https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.modbus/src/main/resources/OH-INF/config/gainOffset.xml#L9
Related: https://github.com/openhab/openhab-addons/pull/9980
> [modbus] correct parameter names in docs, logs and code comments

- bundles/org.openhab.binding.teleinfo/README.md
This PR makes the following changes in the binding documentation:
* highlight rfc2217 support.
* outline that only `historical` mode of Linky telemeter is currently supported.
> [teleinfo] Update documentation

- bundles/org.openhab.binding.modbus.e3dc/src/main/java/org/openhab/binding/modbus/e3dc/internal/dto/EmergencyBlock.java
This fixes the wrong E3/DC Emergency Power Possible bit, reported in issue #10513.
Emergency Power Possible should refer to `EMS_AVAILABLE_BIT` according to the E3/DC Modbus documentation.
> [modbus-e3dc] Fixes wrong E3/DC Emergency Power Possible bit (#10513)

- bundles/org.openhab.binding.hpprinter/src/main/java/org/openhab/binding/hpprinter/internal/HPPrinterBinder.java
- bundles/org.openhab.binding.hpprinter/src/main/java/org/openhab/binding/hpprinter/internal/HPPrinterHandler.java
This PR eliminates the "handler was already disposed" warnings when OH is being shut down.
> [hpprinter] Prevent "handler disposed" warnings on shutdown

- bundles/org.openhab.transform.jinja/pom.xml
- bundles/org.openhab.transform.jinja/src/main/feature/feature.xml
Related to #10496 https://github.com/openhab/openhab-osgiify/pull/17 https://github.com/openhab/openhab-osgiify/pull/18
All dependencies for JinJava 2.5.0 were resolved by OSGIified versions declared in feature.xml for some reason. This way requires PRs to openhab-osgiify repository on each dependency update and this is very inconvenient. 
By this PR, dependencies used by Jinja Transformation are moved back to pom.xml. I left Jackson, Jsoup, commons-net and commons-lang3 in feature.xml, because they are used by other bundles and they have actual bundles in Maven repository.
Code review is required, because I have no experience in OSGi.
> [Jinja] Update JinJava version and embed dependencies #10496

- bundles/org.openhab.transform.jinja/src/main/java/org/openhab/transform/jinja/internal/JinjaTransformationService.java
- bundles/org.openhab.transform.jinja/src/test/java/org/openhab/transform/jinja/internal/JinjaTransformationServiceTest.java
Signed-off-by: Anton Kharuzhy <antroids@gmail.com>
The new JinJava 2.5.7 allows to handle missing map keys.
This PR enables validation and wraps FatalTemplateErrorsException into TransformationException, according to TransformationService contract.
Linked issue: #10496
> [jinja] Empty string result when binding is missing

- bundles/org.openhab.binding.avmfritz/README.md
- bundles/org.openhab.binding.avmfritz/src/main/resources/OH-INF/i18n/avmfritz_de.properties
This PR corrects a spelling error in the German translation (Rolladen with 2 instead of 3 l's) and adds the Becker BoxCTRL roller shutter drive to the list of tested devices.
There are no functional changes in this PR, just text changes.
> [avmfritz] Correct spelling error and add new device to list of tested devices

- bundles/org.openhab.binding.mqtt.espmilighthub/README.md
Created a new PR since I messed up the old one...
This PR aims to add documentation for the handling of group 0 / ALL group.
> [espmilighthub] Describe group 0 handling

- .github/ISSUE_TEMPLATE/config.yml
The URL is: https://crowdin.com/project/openhab-addons
> Fix Crowdin URL in issue template configuration

- bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/D2_50/D2_50.java
This change accepts a new message type which is sent by some air ventilation devices durin teach in. This is required for the search feature to detect these devices correctly.
Signed-off-by: David Schumann <david@dev-core.org>
This PR fixes the broken search for enocean air ventilation systems.
It's not yet clear to me what exactly the new message type contains in terms of information, but accepting the type restores the previous behavior where the search is fully detecting those devices. Packet details are in the related issue.
To ease debugging with other devices I added a debug log statement for other unknown message types
This PR has been successfully tested with Dimplex DL 50 devices.
> [enocean] Fix discovery of D2-50 devices

- bundles/org.openhab.binding.openweathermap/README.md
[openweathermap] DOC FIX FOR UVINDEX FORMATTING
Fixes #10629
The example for all UV items in the documentation is giving following formatting:
UV Index [%d]
this is giving warnings in the logfile:
Exception while formatting value '4.02' of item weather_owm_localCurrentUvindex with format '%d': d != java.math.BigDecimal
Doccumentation has been adapted to use the following formatting:
UV Index [%.1f]
> [openweathermap] updated string formatting example for UVindex

- bundles/org.openhab.binding.lametrictime/pom.xml
- bundles/org.openhab.binding.tellstick/src/main/feature/feature.xml
Fixes #10642
Related to https://github.com/openhab/openhab-core/pull/2292, https://github.com/openhab/openhab-distro/issues/1256
> Use activation-api 1.2.1_3

- bundles/org.openhab.binding.linuxinput/src/main/java/org/openhab/binding/linuxinput/internal/LinuxInputDiscoveryService.java
Small fixes for the linuxinput binding.
Descriptions for each commit are in the commit messages.
> [linuxinput] fixes to thing properties

- CODEOWNERS
- bom/openhab-addons/pom.xml
- bundles/org.openhab.automation.jsscripting/NOTICE
- bundles/org.openhab.automation.jsscripting/README.md
- bundles/org.openhab.automation.jsscripting/bnd.bnd
- bundles/org.openhab.automation.jsscripting/pom.xml
- bundles/org.openhab.automation.jsscripting/src/main/feature/feature.xml
- bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/ClassExtender.java
- bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/DebuggingGraalScriptEngine.java
- bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/GraalJSScriptEngineFactory.java
- bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/ModuleLocator.java
- bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/OpenhabGraalJSScriptEngine.java
- bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/ScriptExtensionModuleProvider.java
- bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/fs/DelegatingFileSystem.java
- bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/fs/PrefixedSeekableByteChannel.java
- bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/scriptengine/DelegatingScriptEngineWithInvocable.java
- bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/scriptengine/InvocationInterceptingScriptEngineWithInvocable.java
- bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/threading/ThreadsafeSimpleRuleDelegate.java
- bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/threading/ThreadsafeWrappingScriptedAutomationManagerDelegate.java
- bundles/org.openhab.automation.jsscripting/src/main/resources/META-INF/services/com.oracle.truffle.api.TruffleLanguage$Provider
- bundles/pom.xml
Parent PR to track all the changes required to get ES6+ support into OH. This supercedes #6399 and was reopened from #8441 
Remaining dependencies:
- ~~script module access (https://github.com/openhab/openhab-core/pull/1843)~~
- ~~engine identifier (blocks https://github.com/openhab/openhab-core/pull/1196) https://github.com/openhab/openhab-core/pull/1837~~
- ~~dependency tracking (https://github.com/openhab/openhab-core/pull/1884)~~
> [jsscripting] ES6+ Support

- bundles/org.openhab.binding.harmonyhub/README.md
Fixed what I believe were typos. Making similar adjustments to my setup allowed the Harmony integration to work for me.
> [harmonyhub] Update README.md

- bundles/org.openhab.binding.webthing/src/main/java/org/openhab/binding/webthing/internal/WebThingHandler.java
- bundles/org.openhab.binding.webthing/src/main/java/org/openhab/binding/webthing/internal/client/WebSocketConnectionImpl.java
- bundles/org.openhab.binding.webthing/src/test/java/org/openhab/binding/webthing/internal/client/WebthingTest.java
This is a bug fix for the new WebThing binding. 
It turned out that a WebThing will not be reconnected, if the WebThing network connection is crashed. The reason for this is the uninitialized variable instance variable webThingURI. Due  to the fact that this variable is null the reconnect code fails.
This merge request includes the changes to fix this. 
Furthermore unnecessary NonNull annotations has been removed
Signed-off-by: Gregor Roth <gregor.roth@web.de>
> [WebThing] binding bugfix: If WebThing network connection is crashed, WebThing will not be reconnected.

- bundles/org.openhab.persistence.mongodb/src/main/java/org/openhab/persistence/mongodb/internal/MongoDBPersistenceService.java
[MongoDB Persistence] Bugfixes and various improvements
I noticed the MongoDB persistence driver had several issues, with the biggest one being the completely broken query support.
Additionally, connection recovery to the database server was not working, either. 
Also, the indices were reordered to improve performance.
Last but not least some code style changed were introduced.
Please see the commits for detailed changes. I split the changes in small commits for easier review.
The changes were tested in my local openHAB snapshot instance, running in docker.
Prebuilt module:
[mongodb-persistence.zip](https://github.com/openhab/openhab-addons/files/6408092/mongodb-persistence.zip)
Fixes #10574
> [MongoDB Persistence] Fix error 500 and various improvements

- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/LightStateConverter.java
- bundles/org.openhab.binding.hue/src/test/java/org/openhab/binding/hue/internal/LightStateConverterTest.java
- Changed default color mode for color commands to XY
Fixes #10159 
> [hue] Changed default color mode for color commands to XY

- bundles/org.openhab.binding.shelly/README.md
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/ShellyBindingConstants.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyApiException.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyApiJsonDTO.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyDeviceProfile.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyHttpApi.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/coap/ShellyCoIoTProtocol.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/coap/ShellyCoIoTVersion1.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/coap/ShellyCoIoTVersion2.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/coap/ShellyCoapHandler.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/discovery/ShellyDiscoveryParticipant.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyBaseHandler.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyComponents.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyLightHandler.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/manager/ShellyManager.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/manager/ShellyManagerActionPage.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/manager/ShellyManagerCache.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/manager/ShellyManagerOtaPage.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/manager/ShellyManagerOverviewPage.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/manager/ShellyManagerPage.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/manager/ShellyManagerServlet.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/provider/ShellyChannelDefinitions.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/util/ShellyUtils.java
The PR includes
- Adaption of new checkstyle
- #10617 Vibration event for DW2
-
> [shelly] Vibration event for DW2

- bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/handler/InsteonNetworkHandler.java
This fixes a race condition where devices try to access insteonBinding before it's created. See https://community.openhab.org/t/losing-insteon-connectivity-on-reboot/121005
> [insteon] delay setting state of network to UNKNOWN

- bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/phonebook/Tr064PhonebookImpl.java
- Fixed wrong pattern to normalize phone numbers
Fixes #10529 
> [tr064] Fixed wrong pattern to normalize phone numbers

- bundles/org.openhab.binding.luxtronikheatpump/README.md
- bundles/org.openhab.binding.luxtronikheatpump/src/main/resources/OH-INF/thing/channels.xml
temperatureHotWaterTarget channel is writable
temperatureTargetHotWater_2  channel doesn't exist in the binding
Signed-off-by: Martin Kurgi <martinkurgi@gmail.com>
> [luxtronikheatpump] Update channel descriptions in README.md

- bundles/org.openhab.transform.jsonpath/pom.xml
Bump jsonpath dependency version
Signed-off-by: Alexander Falkenstern <alexander.falkenstern@gmail.com>
> Bump jsonpath dependency from 2.4.0 to 2.5.0

- bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc2/NhcMqttConnection2.java
Depends on openhab-core [#2348](https://github.com/openhab/openhab-core/pull/2348)
The recent upgrade of hivemq introduces hostname validation for secure connections by default. This breaks the nikohomecontrol binding.
This change uses a new flag introduced in the openhab-core PR for the mqtt transport to disable this behaviour.
It can only be merged after the openhab-core PR.
See also conversation on the [forum](https://community.openhab.org/t/niko-home-control-energymeter-returning-undef/120959/11).
> [nikohomecontrol] Switch off hostname validation.

- bundles/org.openhab.binding.bluetooth.airthings/src/main/java/org/openhab/binding/bluetooth/airthings/internal/AirthingsBindingConstants.java
- bundles/org.openhab.binding.bluetooth.generic/src/main/java/org/openhab/binding/bluetooth/generic/internal/BluetoothUnit.java
- bundles/org.openhab.binding.dsmr/src/main/java/org/openhab/binding/dsmr/internal/device/cosem/CosemQuantity.java
- bundles/org.openhab.binding.homematic/src/test/java/org/openhab/binding/homematic/internal/converter/ConvertFromBindingTest.java
- bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/converter/NumberItemConverter.java
- bundles/org.openhab.binding.http/src/test/java/org/openhab/binding/http/internal/converter/ConverterTest.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoBasicHandler.java
- bundles/org.openhab.binding.modbus.e3dc/src/test/java/org/openhab/binding/modbus/e3dc/dto/DataBlockTest.java
- bundles/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/profiles/ModbusGainOffsetProfile.java
- bundles/org.openhab.binding.modbus/src/test/java/org/openhab/binding/modbus/internal/profiles/ModbusGainOffsetProfileTest.java
- itests/itest-common.bndrun
- itests/org.openhab.binding.astro.tests/itest.bndrun
- itests/org.openhab.binding.avmfritz.tests/itest.bndrun
- itests/org.openhab.binding.feed.tests/itest.bndrun
- itests/org.openhab.binding.hue.tests/itest.bndrun
- itests/org.openhab.binding.max.tests/itest.bndrun
- itests/org.openhab.binding.modbus.tests/itest.bndrun
- itests/org.openhab.binding.nest.tests/itest.bndrun
- itests/org.openhab.binding.ntp.tests/itest.bndrun
- itests/org.openhab.binding.systeminfo.tests/itest.bndrun
- itests/org.openhab.binding.tradfri.tests/itest.bndrun
- itests/org.openhab.binding.wemo.tests/itest.bndrun
- itests/org.openhab.persistence.mapdb.tests/itest.bndrun
- tools/static-code-analysis/checkstyle/ruleset.properties
Depends on https://github.com/openhab/openhab-core/pull/2319
---
* Fix code/tests for upgrade
* Resolve runbundles
* Update Checkstyle ruleset for changed packages
> Upgrade Units of Measurement dependencies

- pom.xml
This is the version used in the feature provided by openhab-core.
Depends https://github.com/openhab/openhab-core/pull/2357
> Update Jackson version to 2.12.3

- bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/InfluxDBConfiguration.java
- bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/InfluxDBStateConvertUtils.java
- bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/InfluxDBVersion.java
- bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/InfluxRow.java
- bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/influx1/InfluxDB1RepositoryImpl.java
Fixes issue #10464
Problem was introduced in #9943 and it's reproducible with historical Influx1 data that was generated with addon version <3.0.0 that didn't store item tag in points.
Generated binary to test:
[org.openhab.persistence.influxdb-3.1.0-SNAPSHOT.zip](https://github.com/openhab/openhab-addons/files/6468951/org.openhab.persistence.influxdb-3.1.0-SNAPSHOT.zip)
> [influxdb] Fix issue #10464 Problem querying old historical data

- bundles/create_openhab_binding_skeleton.cmd
- bundles/create_openhab_binding_skeleton.sh
Currently spotless errors are occuring when I try to create a new binding with the skeleton scripts. Sure the root cause of this should be fixed, anyhow I think it's a bad smell to annoy new binding developers with this directly on their very first step.
> Ignore spotless errors on binding creation

- bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/json/request/ICloudAccountDataRequest.java
fixed: iCloud response invalid: null
changed: appVersion from 2.0 to 3.0
added: missing productType
Signed-off-by: Tom Blum <trinitus01@googlemail.com>
https://github.com/openhab/openhab-addons/issues/10699
> [icloud] iCloud response invalid: null

- bundles/org.openhab.binding.senechome/pom.xml
- bundles/org.openhab.binding.senechome/src/main/java/org/openhab/binding/senechome/internal/SenecHomeApi.java
- bundles/org.openhab.binding.senechome/src/main/java/org/openhab/binding/senechome/internal/SenecHomeHandler.java
Hello,
this PR shall fix Issue #10025 .
Some Senec Home Devices do respond with a broken JSON. One example
Good:
```json
"POWER_RATIO_L3": "u3_00000064",
"PV_MISSING": "u8_03",
"P_TOTAL": "fl_C2EA7EFB",
"STATE_INT": [
"u3_00000110",
"u3_00000110"
],
"TYPE": "u8_A0"
},
"ENERGY": {
"CAPTESTMODULE": [
"fl_00000000",
"fl_00000000",
"fl_00000000",
"fl_00000000"
],
"GUI_BAT_DATA_COLLECTED": "u8_01",
"GUI_BAT_DATA_CURRENT": "fl_BD8F5C29",
"GUI_BAT_DATA_FUEL_CHARGE": "fl_00000000",
```
Malformed:
```json
"POWER_RATIO_L3": "u3_00000064",
"PV_MISS",
"GUI_BAT_DATA_FUEL_CHARGE": "fl_00000000",
```
This was leading to an exception:
> 2021-04-30 19:58:54.904 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
> com.google.gson.JsonSyntaxException: …
> [SenecHome] Catch and ignore malformed JSON

- bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/converter/DimmerItemConverter.java
- bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/converter/NumberItemConverter.java
- bundles/org.openhab.binding.iaqualink/src/main/java/org/openhab/binding/iaqualink/internal/handler/IAqualinkHandler.java
- bundles/org.openhab.binding.icalendar/src/main/java/org/openhab/binding/icalendar/internal/logic/CommandTag.java
- bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/WLedHandler.java
- bundles/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/internal/NeeoItemValueConverter.java
- bundles/org.openhab.transform.scale/src/main/java/org/openhab/transform/scale/internal/ScaleTransformationService.java
The PercentType and QuantityType can also throw an IllegalArgumentException.
The MeasurementParseException is no longer thrown.
Related to https://github.com/openhab/openhab-core/pull/2365
> Fix build and improve exception handling

- bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/GroupThingHandler.java
fixes https://github.com/openhab/openhab-addons/issues/10320 ,
applies same  handling as for lights
> [deconz] make lightgroup switch off if brightness is set to 0

- bundles/org.openhab.binding.openweathermap/README.md
The default parameter in the binding is different from the current readme/docs.
(Also removed some trailing whitespaces, since i didn't deactivate it for this repo yet.)
See: https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/config/config.xml#L131
> [openweathermap] Add correct default parameter to Readme

- bundles/org.openhab.binding.homeconnect/src/main/resources/OH-INF/thing/thing-types.xml
To avoid the core framework updating automatically an item state while a
command is sent to this item but its handling by the binding is failing
or ignored
Fix #10700
> [homeconnect] Let the binding update item state when handling a command

- bundles/org.openhab.binding.linuxinput/src/main/java/org/openhab/binding/linuxinput/internal/evdev4j/EvdevDevice.java
- bundles/org.openhab.binding.linuxinput/src/main/java/org/openhab/binding/linuxinput/internal/evdev4j/jnr/EvdevLibrary.java
Previously only the basic keyboard buttons where handled.
Now all buttons known to Linux, or rather libevdev are reported.
Reported-in: https://community.openhab.org/t/linuxinput-binding-and-mouse-capture/122612
Reported-in: https://github.com/t-8ch/binding-linuxinput/issues/5
Signed-off-by: Thomas Weißschuh <thomas@t-8ch.de>
> [linuxinput] Handle all kinds of buttons

- bundles/org.openhab.binding.linuxinput/src/main/resources/OH-INF/thing/thing-types.xml
Previously there was a mismatch between the UIDs used by the handler and
the one actually registered from the XML-file.
This lead to channels not showing up in the UI.
(See https://github.com/openhab/openhab-webui/issues/406 )
Signed-off-by: Thomas Weißschuh <thomas@t-8ch.de>
> [linuxinput] use correct channelTypeUID for key-press channels

- bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/HomeConnectBindingConstants.java
- bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/AbstractHomeConnectThingHandler.java
- bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/HomeConnectCoffeeMakerHandler.java
- bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/HomeConnectCooktopHandler.java
- bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/HomeConnectDishwasherHandler.java
- bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/HomeConnectDryerHandler.java
- bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/HomeConnectHoodHandler.java
- bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/HomeConnectOvenHandler.java
- bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/HomeConnectWasherDryerHandler.java
- bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/HomeConnectWasherHandler.java
Use the provided planned time for a washing program to set the channel "remaining_program_time_state" when no program is active
Fix #10744
Fix #10703
> [homeconnect] Don't reset washer temp / spin speed when exiting from active program

- bundles/org.openhab.transform.map/README.md
Add simple white space escape example for MAP key
Signed-off-by: Ross Kennedy rossko@culzean.clara.co.uk
> [docs] MAP transformation text, add white space example

- bundles/org.openhab.binding.openwebnet/README.md
- bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/handler/OpenWebNetAutomationHandler.java
With this change after OH reboot position remains UNDEF since the binding does not know anymore the real position of the shutter. Users should move the shutter full UP/DOWN to re-synchronize with the real position again.
Fixes #10662 
Signed-off-by: Massimo Valla <mvcode00@gmail.com>
> [openwebnet] shutter position is set UNDEF after reboot

- bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/PulseAudioAudioSink.java
- bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/PulseaudioBindingConstants.java
- bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/handler/PulseaudioHandler.java
- bundles/org.openhab.binding.pulseaudio/src/main/resources/OH-INF/thing/sink.xml
This PR allows the Pulseaudio audio sink to disconnect after a configured period of being idle.
I use Pulseaudio with a Raspberry and a speaker to announce events via TTS and noticed that the speaker never goes to sleep and constantly produces high pitch noise.
After digging through the code the most obvious and simplest option was to disconnect immediately after a stream has finished. This worked initially but had a big drawback when issuing multiple "say" (TTS) commands in a row. There a new connection has been made for every "say" command which resulted in an overlap of the streams. This was not a problem previously because the same socket connection was used and the Pulseaudio server played this consecutively.
The solution I came up with is simple enough and works quite well. After …
> [pulseaudio] Add "idle timeout" to Pulseaudio audio sink

- bundles/org.openhab.binding.nikobus/src/main/resources/OH-INF/config/config.xml
Based on [feedback](https://community.openhab.org/t/nikobus-v2/80241/296) from some users it seems `required=true` should not be set for parameters that have a default value, as stated [here](https://community.openhab.org/t/nikobus-v2/80241/300), otherwise one can have problems when restarting OH.
> [nikobus] removed required=true for parameters with default value

- bundles/org.openhab.binding.ahawastecollection/src/main/java/org/openhab/binding/ahawastecollection/internal/AhaWasteCollectionHandler.java
Changed the loglevel to debug, if no collection times for an specific waste type was found.
Fixes #10786
> [ahawastecollection] Change loglevel from warn to debug

- bundles/org.openhab.binding.openwebnet/README.md
- bundles/org.openhab.binding.openwebnet/pom.xml
- bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/OpenWebNetBindingConstants.java
- bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/handler/OpenWebNetBridgeHandler.java
- bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/handler/OpenWebNetThermoregulationHandler.java
- bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/handler/OpenWebNetThingHandler.java
- bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/OpenWebNetHandlerFactory.java
- bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/discovery/OpenWebNetDeviceDiscoveryService.java
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusTempSensor.xml
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusThermostat.xml
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/channels.xml
- bundles/org.openhab.binding.openwebnet/src/test/java/org/openhab/binding/openwebnet/handler/OwnIdTest.java
This enhancement restores support for Thermoregulation for standalone thermostat (bus_thermostat) and external wireless temperature sensors (bus_temp_sensor).
Fixes #10702
Fixes #8582
> [openwebnet] add support for Thermoregulation (standalone thermostat and sensors)

- bundles/org.openhab.binding.smhi/src/main/java/org/openhab/binding/smhi/internal/SmhiConnector.java
Discovered an issue where the binding would crash and stop updating if there was something wrong in the json received from the api. This fix catches these exceptions and sets the thing temporarily OFFLINE until a valid response is received.
> [smhi] Catch exception that could cause binding to stop updating channels

- bundles/org.openhab.binding.venstarthermostat/README.md
- bundles/org.openhab.binding.venstarthermostat/pom.xml
- bundles/org.openhab.binding.venstarthermostat/src/main/java/org/openhab/binding/venstarthermostat/internal/VenstarThermostatBindingConstants.java
- bundles/org.openhab.binding.venstarthermostat/src/main/java/org/openhab/binding/venstarthermostat/internal/handler/VenstarThermostatHandler.java
- bundles/org.openhab.binding.venstarthermostat/src/main/java/org/openhab/binding/venstarthermostat/internal/model/VenstarAwayMode.java
- bundles/org.openhab.binding.venstarthermostat/src/main/java/org/openhab/binding/venstarthermostat/internal/model/VenstarAwayModeSerializer.java
- bundles/org.openhab.binding.venstarthermostat/src/main/java/org/openhab/binding/venstarthermostat/internal/model/VenstarInfoData.java
- bundles/org.openhab.binding.venstarthermostat/src/main/resources/OH-INF/thing/thing-types.xml
<[venstarthermostat] Add away mode channel in binding>
<This PR adds the Away Mode available via the thermostat local API to the Venstar thermostat binding. The Away Mode is a String channel. It allows the Away Mode to be seen in the UI and also changed as a setting with two options (away or home). It has been tested using the demo app in Eclipse IDE. https://openhab.jfrog.io/openhab/libs-pullrequest-local/org/openhab/addons/bundles/org.openhab.binding.venstarthermostat/3.1.0-SNAPSHOT/>
Closes #10707
> [venstarthermostat] Venstar thermostat away mode enhancement

- bundles/org.openhab.binding.gpio/README.md
- bundles/org.openhab.binding.gpio/src/main/java/org/openhab/binding/gpio/internal/configuration/GPIOInputConfiguration.java
- bundles/org.openhab.binding.gpio/src/main/java/org/openhab/binding/gpio/internal/handler/PigpioDigitalInputHandler.java
- bundles/org.openhab.binding.gpio/src/main/java/org/openhab/binding/gpio/internal/handler/PigpioDigitalOutputHandler.java
- bundles/org.openhab.binding.gpio/src/main/resources/OH-INF/thing/pigpio-remote.xml
*[gpio] Added parameter for pull up/down resistor for GPIO binding*
Changes:
- Added Pull Up/Down parameter to input GPIO pin configuration
- GPIO pin mode set with library constant instead of integer
- Updated README.md of binding (added information about new parameter)
- Improved README.md of binding with some additional info
- Also ran static code analysis
- Tested on my setup, no problems detected
Most of changes were implemeted by @sjoerdtakken ([Forum post](https://community.openhab.org/t/gpio-new-gpio-binding-for-oh3/113943/33), [His repo with changes](https://wordpressvonmorgen.dd-dns.de/pigpio/)), but not commited to this repo. 
Here is compiled version: [org.openhab.binding.gpio-3.1.0.zip](https://github.com/openhab/openhab-addons/files/6566972/org.openhab.binding.gpio-3.1.0.zip) …
> [gpio] Added parameter for pull up/down resistor and other improvements

- bundles/org.openhab.binding.radiothermostat/README.md
- bundles/org.openhab.binding.radiothermostat/src/main/java/org/openhab/binding/radiothermostat/internal/RadioThermostatBindingConstants.java
- bundles/org.openhab.binding.radiothermostat/src/main/java/org/openhab/binding/radiothermostat/internal/RadioThermostatConfiguration.java
- bundles/org.openhab.binding.radiothermostat/src/main/java/org/openhab/binding/radiothermostat/internal/handler/RadioThermostatHandler.java
- bundles/org.openhab.binding.radiothermostat/src/main/resources/OH-INF/thing/thing-types.xml
The goal of this PR is to add the ability for the binding to set the thermostat's clock automatically from the host's system time. This functionality is needed if the user does not connect their thermostat to the manufacturer's cloud service. It is also possible that the cloud service could be discontinued some day which would leave the user with no easy way to set the thermostat's clock.
> [radiothermostat] Add job to set thermostat clock automatically from the binding

- bundles/org.openhab.binding.pushover/README.md
- bundles/org.openhab.binding.pushover/src/main/java/org/openhab/binding/pushover/internal/config/PushoverAccountConfiguration.java
- bundles/org.openhab.binding.pushover/src/main/java/org/openhab/binding/pushover/internal/connection/PushoverAPIConnection.java
- bundles/org.openhab.binding.pushover/src/main/resources/OH-INF/config/config.xml
[pushover] Provides the ability to specify a timeout in the config, instead of using hardcoded 10 seconds.
Provides the ability to specify a timeout in the config, instead of using hardcoded 10 seconds. On slower devices, and when sending a message with images, 10 seconds can be too short. This leads to a Timeout Exception.
An additional config parameter is added "timeout", with default value 10.
[pushover.zip](https://github.com/openhab/openhab-addons/files/6604591/pushover.zip)
> [pushover] Provides the ability to specify a timeout in the config

- bundles/org.openhab.binding.rfxcom/README.md
- bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComUndecodedRFMessage.java
- bundles/org.openhab.binding.rfxcom/src/main/resources/OH-INF/thing/undecoded.xml
New subtypes have been added to the firmware, these are taken from the
RFXtrx SDK documentation.
> [rfxcom] New sub types for undecoded messages

- bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/connector/RFXComStreamReader.java
Without this, any message over 127 bytes reports a negative length and
fails the message start test, which puts the code out of sync with the
rfxcom leading to lots of errors, and eventually, complete loss of
connection.
> [rfxcom] Convert unsigned byte to int properly

- bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/handler/OpenWebNetEnergyHandler.java
- bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/handler/OpenWebNetThermoregulationHandler.java
This enhancement uses `scheduleWithFixedDelay` instead of `scheduleAtFixedRate` for periodically executed jobs.
It also solves other spotless warnings.
Fixes #10698
> [openwebnet] improve scheduler 

- bundles/org.openhab.binding.resol/src/main/java/org/openhab/binding/resol/handler/ResolThingHandler.java
- bundles/org.openhab.binding.resol/src/main/resources/OH-INF/thing/thing-types.xml
Correct the handling of Date and Time fields in Packets on the VBUS to make these channels available and fix #10684 
Further discussion is here: https://community.openhab.org/t/resol-binding-stopped-working-in-recent-nightly-builds/122371/7
There is a jar of the fixed binding here: https://github.com/ramack/openhab-addons/blob/resolReleases/bundles/org.openhab.binding.resol/target/org.openhab.binding.resol-3.1.0-SNAPSHOT.jar?raw=true
@EjvindHald confirmed the fix so we can merge this bugfix.
> [resol] correct handling of system date/time field

- bundles/org.openhab.binding.tivo/src/main/java/org/openhab/binding/tivo/internal/TiVoBindingConstants.java
- bundles/org.openhab.binding.tivo/src/main/java/org/openhab/binding/tivo/internal/handler/TiVoHandler.java
- bundles/org.openhab.binding.tivo/src/main/java/org/openhab/binding/tivo/internal/service/TivoStatusProvider.java
This PR fixes an issue with the Tivo binding while using the option to always keep the connection to the device open. The previous strategy was to keep the original socket connection open indefinitely. This works OK, but after several days the connection would die and the binding would not reconnect without restarting. Sometimes the device would not accept a new connection without being rebooted first. To alleviate these problems, the binding will now close and re-open the persistent connection every 12 hours .
> [tivo] Refresh persistent connection every 12 hours

- bundles/org.openhab.binding.epsonprojector/README.md
- bundles/org.openhab.binding.epsonprojector/src/main/resources/OH-INF/thing/thing-types.xml
Update configuration section in README to use tables per comments in the benqprojector PR.
> [epsonprojector] Update readme configuration section

- bundles/org.openhab.binding.rfxcom/README.md
- bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComRainMessage.java
- bundles/org.openhab.binding.rfxcom/src/main/resources/OH-INF/thing/rain.xml
In a recent [Firmware Update](http://blog.rfxcom.com/) to the RFXCOM family of transievers, support for the TFA 30.3233.1 rain sensor has been added.
The meter is identified as the subtype RAIN9. This leads to an error due to 9 being out of range of the enumerator mapping the subtypes to models/manufacturers in the configuration.
This PR adds the relevant entries to the message parser. I can confirm that the sensor is detected and works with these changes.
> [rfxcom] Add support for TFA 30.3233.1 rainmeter

- bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/LightThingHandler.java
This PR corrects a problem (#10774) in the binding that currently makes it unusable for window coverings because no reall bypass exists.
> [deconz] Set "ontime" option only if thing has got an ONTIME channel

- bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaVehicleHandler.java
This NPE causes the scheduled task to crash, so that the whole binding stops working.
> [tesla] Prevent NPE

- bundles/org.openhab.binding.gpio/README.md
- bundles/org.openhab.binding.gpio/src/main/java/org/openhab/binding/gpio/internal/GPIOBindingConstants.java
- bundles/org.openhab.binding.gpio/src/main/java/org/openhab/binding/gpio/internal/InvalidPullUpDownException.java
- bundles/org.openhab.binding.gpio/src/main/java/org/openhab/binding/gpio/internal/configuration/GPIOInputConfiguration.java
- bundles/org.openhab.binding.gpio/src/main/java/org/openhab/binding/gpio/internal/handler/PigpioDigitalInputHandler.java
- bundles/org.openhab.binding.gpio/src/main/java/org/openhab/binding/gpio/internal/handler/PigpioRemoteHandler.java
- bundles/org.openhab.binding.gpio/src/main/resources/OH-INF/thing/pigpio-remote.xml
Follow-up pull request to pull request #10782, changed usage of pullupdown parameter, instead of numeric parameter is now text parameter with "constants" OFF, DOWN, UP.
-  Signed off commits
-  Checked with mvn spotless:apply
-  Tested on my instance, no errors detected.
Signed-off-by: Martin <martin.dagarin@gmail.com>
> [gpio] Improved usability of pullupdown parameter on GPIO pin

- bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/client/HomeConnectEventSourceClient.java
- bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/client/HomeConnectEventSourceListener.java
- bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/client/HomeConnectStreamingRequestFilter.java
- bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/client/HttpHelper.java
An obsolete filter was used during the creation of an SSE client. The client used an incorrect authorization header.
Signed-off-by: Jonas Brüstel <jonas@bruestel.net>
> [homeconnect] Fix invalid authorization header during Server-Sent Events (SSE) client creation

- bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComInterfaceMessage.java
- bundles/org.openhab.binding.rfxcom/src/test/java/org/openhab/binding/rfxcom/internal/messages/RFXComInterfaceControlMessageTest.java
- bundles/org.openhab.binding.rfxcom/src/test/java/org/openhab/binding/rfxcom/internal/messages/RFXComInterfaceMessageTest.java
New firmware type reported from the community that's not in the SDK. Also,
we don't actually _use_ the firmware type or device type for anything, so
lets not crash if we don't match the bytes - lets just flag it unknown.
https://community.openhab.org/t/rfxcom-binding-unsupported-value/123615/12
> [rfxcom] Add firmware type, avoid crashing on unknown.

- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/discovery/MiIoDiscovery.java
avoid error
```
18:19:51.732 [ERROR] [internal.DiscoveryServiceRegistryImpl] - Cannot trigger scan for thing types '[miio:vacuum, miio:unsupported, miio:basic, miio:generic]' on 'MiIoDiscovery'!
java.lang.IllegalArgumentException: ID segment 'lumi.158d0001e09bdb' contains invalid characters. Each segment of the ID must match the pattern [\w-]*.
at org.openhab.core.common.AbstractUID.validateSegment(AbstractUID.java:98) ~[?:?]
at org.openhab.core.common.AbstractUID.<init>(AbstractUID.java:76) ~[?:?]
at org.openhab.core.common.AbstractUID.<init>(AbstractUID.java:59) ~[?:?]
at org.openhab.core.thing.UID.<init>(UID.java:57) ~[?:?]
at org.openhab.core.thing.ThingUID.<init>(ThingUID.java:47) ~[?:?]
at …
```
> [miio] fix discovery issue for devices with dot in ID

- bundles/org.openhab.binding.remoteopenhab/src/main/java/org/openhab/binding/remoteopenhab/internal/rest/RemoteopenhabRestClient.java
- bundles/org.openhab.binding.remoteopenhab/src/main/java/org/openhab/binding/remoteopenhab/internal/rest/RemoteopenhabStreamingRequestFilter.java
> [remoteopenhab] Avoid registering conflicting filters for SSE connection

- bundles/org.openhab.binding.ihc/README.md
- bundles/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/config/IhcConfiguration.java
- bundles/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/handler/IhcHandler.java
- bundles/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/ws/IhcClient.java
- bundles/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/ws/exeptions/IhcFatalExecption.java
- bundles/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/ws/exeptions/IhcTlsExecption.java
- bundles/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/ws/http/IhcConnectionPool.java
- bundles/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/ws/http/IhcHttpsClient.java
- bundles/org.openhab.binding.ihc/src/main/resources/OH-INF/thing/controller.xml
So far IHC controller have supported only TLSv1. As TLSv1 is already deprecated and upcoming IHC controller FW version will introduce support for TLSv1.2. This change introduce TLSv1.2 support for the binding. TLS version is selectable to be backward compatible for older controller versions.
Communication error handling is also improved e.g. because of wrong password or if Java environment doesn't support required TLS version. When fatal communication error occurs, binding will not hammer controller with retries as it need user actions.
> [ihc] Support for TLSv1.2

- bundles/org.openhab.binding.snmp/README.md
- bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/SnmpTargetHandler.java
- bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/config/SnmpChannelConfiguration.java
- bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/config/SnmpInternalChannelConfiguration.java
- bundles/org.openhab.binding.snmp/src/main/resources/OH-INF/thing/thing-types.xml
- bundles/org.openhab.binding.snmp/src/test/java/org/openhab/binding/snmp/internal/AbstractSnmpTargetHandlerTest.java
- bundles/org.openhab.binding.snmp/src/test/java/org/openhab/binding/snmp/internal/SnmpTargetHandlerTest.java
I wanted to get the SNMP binding to apply units to incoming data before applying to an Item. (It was also requested [here](https://community.openhab.org/t/i-cant-get-prefixes-to-work-with-dataamount-uom/101830/8)).
The change adds a configuration parameter to the number channel type which allows the user to specify what [UoM](https://www.openhab.org/docs/concepts/units-of-measurement.html) the numeric data coming from the SNMP target is in. This removes the need for users to specify a UoM on the Item the channel is linked to, or specify a different UoM of the same dimension to benefit from OpenHAB's automatic conversion.
The user specifies the UoM symbol for the channel in their thing configuration. On initialisation the binding attempts to convert this to a Unit known by OpenHAB. If this …
> [snmp] Apply UoM to number channels from an SNMP target

- bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/PercentageValue.java
Signed-off-by: Rogier Hofboer <rogier@hofboer.nl>
Configure mqtt.generic percentage channel value as 0..100
Fixes #10586
> [mqtt.generic] Percentage range fix

- bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/KodiDynamicCommandDescriptionProvider.java
- bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/KodiDynamicStateDescriptionProvider.java
- Added service references to `DynamicCommandDescriptionProvider` and `DynamicStateDescriptionProvider` to support publishing `ChannelDescriptionChangedEvent`s
Depends on https://github.com/openhab/openhab-core/pull/1505
> [kodi] Added support for publishing ChannelDescriptionChangedEvents

- bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/converter/ColorItemConverter.java
When parsing RGB values from a http channel state request (in the form "0,1,2") there is an error like this one:
> Failed processing result for URL http://esp32dev2/get/color: For input string: "114,69,40"
Even though the input string "114,69,40" is supposed to be valid.
Which stems from RefreshingUrlCache.java:processResult after calling ColorItemConverter:toState. In the toState function the input is matched against the regex TRIPLE_MATCHER ("(\d+),(\d+),(\d+)") and then the r, g and b channels are set by matcher.group. The problem is that matcher.group returns which match was found, thus matcher.group(0) refers to the first three-digit pattern matching TRIPLE_MATCHER. Then matcher.group(1) has nothing to return as there is only one three-digit group.
Instead I have moved to only using …
> [http] Fix parsing of Color RGB values

- bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/discovery/SqueezeBoxPlayerDiscoveryParticipant.java
- bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxNotificationListener.java
- bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxPlayerEventListener.java
- bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxPlayerHandler.java
- bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxServerHandler.java
~~This read-only channel allows determining whether a given player is
currently connected to the server. This is useful for players which are
e.g. regularly without power.~~
Approach changed: a lack of connection (e.g. due to network or power outages) is now mapped to the thing status.
> [squeezebox] Map player connection state to thing status

- bundles/org.openhab.binding.tr064/src/main/resources/OH-INF/thing/thing-types.xml
- Added representation property for Things
See https://community.openhab.org/t/tr-064-binding-inbox-notification-after-manual-adding-fritzbox/123977
> [tr064] Added representation property for Things

- bundles/org.openhab.binding.tivo/src/main/java/org/openhab/binding/tivo/internal/handler/TiVoHandler.java
- bundles/org.openhab.binding.tivo/src/main/java/org/openhab/binding/tivo/internal/service/TivoStatusProvider.java
This PR is a follow-on to #10824. It was discovered that after the connection refresh, the thing was showing as offline even though the connection was working. Please merge prior to the OH 3.1.0 final release if possible. @kaikreuzer
> [tivo] Fix thing staying offline after connection refresh

- bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/servlet/HomeConnectServlet.java
- bundles/org.openhab.binding.homeconnect/src/main/resources/assets/js/homeconnect.js
- bundles/org.openhab.binding.homeconnect/src/main/resources/templates/log-requests.html
Show response code in request details modal and JS code cleanup.
Enhancement: https://github.com/openhab/openhab-addons/issues/10695
Signed-off-by: Jonas Brüstel <jonas@bruestel.net>
> [homeconnect] Show response code in request details modal and JS code cleanup (#10695)

- bundles/org.openhab.binding.openwebnet/README.md
- bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/handler/OpenWebNetAutomationHandler.java
- bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/handler/OpenWebNetLightingHandler.java
- bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/discovery/BusGatewayUpnpDiscovery.java
Fixes #10883 
Changed ALL_DEVICES_REFRESH_INTERVAL to 60s to avoid lights/shutters status updates flooding at reboot.
Added UPnP discovery for MyHOME_Screen3,5.
Updated catalogue links in README
> [openwebnet] Fix messages flooding BUS on reboot

- bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/InfluxDBConstants.java
- bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/influx2/Influx2FilterCriteriaQueryCreatorImpl.java
- bundles/org.openhab.persistence.influxdb/src/test/java/org/openhab/persistence/influxdb/internal/InfluxFilterCriteriaQueryCreatorImplTest.java
Fixes bug in queries with InfluxDB 2.0 that had data migrated from InfluxDB 1.0 with old versions of the addon that didn't put item tag name.
In that case, the result contained several group keys and could give bad results, for example in sort queries like `deltaSince` that failed because sort was applied per series and not for all the results.
Completes work done on #10888 to cover all casuistic.
There isn't any open issue but the problem was commented on in that thread
https://community.openhab.org/t/influx-db2-openhab-3-1m5-deltasince-start-of-day-not-working-when-lines-without-item-name-in-database-from-openhab-2-5/123546/26
> [influxdb] Fix queries with InfluxDB 2.0 with data migrated from InfluxDB1 without item tags

- bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/BindingConstants.java
- bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/DeconzBaseThingHandler.java
- bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/LightThingHandler.java
- bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/SensorBaseThingHandler.java
- bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/SensorThermostatThingHandler.java
- Use `ChannelBuilder` created by `ThingHandlerCallback`
> [deconz] Use ChannelBuilder created by ThingHandlerCallback

- bundles/org.openhab.binding.irobot/src/test/java/org/openhab/binding/irobot/internal/handler/RoombaHandlerTest.java
Fix UnnecessaryStubbingException in RoombaHandlerTest.
Fixes #10954 and #10956
Signed-off-by: Florian Binder <fb@java4.info>
> [irobot] fix unstable test

- CODEOWNERS
- bom/openhab-addons/pom.xml
- bundles/org.openhab.binding.pushsafer/NOTICE
- bundles/org.openhab.binding.pushsafer/README.md
- bundles/org.openhab.binding.pushsafer/pom.xml
- bundles/org.openhab.binding.pushsafer/src/main/feature/feature.xml
- bundles/org.openhab.binding.pushsafer/src/main/java/org/openhab/binding/pushsafer/internal/PushsaferBindingConstants.java
- bundles/org.openhab.binding.pushsafer/src/main/java/org/openhab/binding/pushsafer/internal/actions/PushsaferActions.java
- bundles/org.openhab.binding.pushsafer/src/main/java/org/openhab/binding/pushsafer/internal/config/PushsaferAccountConfiguration.java
- bundles/org.openhab.binding.pushsafer/src/main/java/org/openhab/binding/pushsafer/internal/config/PushsaferConfigOptionProvider.java
- bundles/org.openhab.binding.pushsafer/src/main/java/org/openhab/binding/pushsafer/internal/connection/PushsaferAPIConnection.java
- bundles/org.openhab.binding.pushsafer/src/main/java/org/openhab/binding/pushsafer/internal/connection/PushsaferCommunicationException.java
- bundles/org.openhab.binding.pushsafer/src/main/java/org/openhab/binding/pushsafer/internal/connection/PushsaferConfigurationException.java
- bundles/org.openhab.binding.pushsafer/src/main/java/org/openhab/binding/pushsafer/internal/connection/PushsaferMessageBuilder.java
- bundles/org.openhab.binding.pushsafer/src/main/java/org/openhab/binding/pushsafer/internal/dto/Icon.java
- bundles/org.openhab.binding.pushsafer/src/main/java/org/openhab/binding/pushsafer/internal/dto/Sound.java
- bundles/org.openhab.binding.pushsafer/src/main/java/org/openhab/binding/pushsafer/internal/factory/PushsaferHandlerFactory.java
- bundles/org.openhab.binding.pushsafer/src/main/java/org/openhab/binding/pushsafer/internal/handler/PushsaferAccountHandler.java
- bundles/org.openhab.binding.pushsafer/src/main/resources/OH-INF/binding/binding.xml
- bundles/org.openhab.binding.pushsafer/src/main/resources/OH-INF/config/config.xml
- bundles/org.openhab.binding.pushsafer/src/main/resources/OH-INF/i18n/pushsafer.properties
- bundles/org.openhab.binding.pushsafer/src/main/resources/OH-INF/i18n/pushsafer_de.properties
- bundles/org.openhab.binding.pushsafer/src/main/resources/OH-INF/thing/thing-types.xml
- bundles/org.openhab.binding.pushsafer/src/test/java/org/openhab/binding/pushsafer/internal/actions/PushsaferActionsTest.java
- bundles/pom.xml
- Initial Contribution of Pushsafer Binding
Supersedes #9994
// CC @appzer
Signed-off-by: Pushsafer.com (Kevin Siml) <info@appzer.de>
> [pushsafer] Initial Contribution of Pushsafer Binding

- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/cloud/CloudConnector.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/cloud/MiCloudConnector.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoAbstractHandler.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoBasicHandler.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/transport/MiIoAsyncCommunication.java
* Improve matching the command responses to the sending channel
* Use newer method to get device list using `device_list_page`
* Adding the ability to send custom requests to cloud
* Adding the ability to send custom commands with additional elements in the json
> [miio] Add new custom refresh methods and improve response to channel matching

- bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/channels.xml
> [rotel] Semantics added to channel types

- bundles/pom.xml
- Readded deleted qbus bundle
This bundle has been deleted unintentionally from the POM in #10790. 
> [qbus] Readded deleted qbus bundle

- bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/type/HomematicTypeGeneratorImpl.java
This PR fixes a problem that was introduced with version openHAB 3.1.
> [homematic] Provide additional null pointer checks

- bundles/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/handler/IhcHandler.java
When connection from binding to IHC controller is open, but controller
is in programming state, things state is offline with special status to
indicate that binding can't send or receive any resource updates at the
moment. Things status check during command sending will prevent
unnecessary resource updates which will eventually fail and binding then
tries to restart the connection.
> [ihc] Improved command handling when controller is not ready

- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/AbstractHomekitPositionAccessoryImpl.java
Add support for setting TARGET_POSITION of Window Covering accessories from groups with a baseItem type
Closes #10812
Signed-off-by: Colin Keehan <github@colin.xyz>
> [homekit] Add support for group item type to window covering

- bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/AbstractOmnilinkHandler.java
- bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/AudioSourceHandler.java
- bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/ZoneHandler.java
> [OmniLink] Fix zone bypass/restore commands

- bundles/org.openhab.binding.miio/README.md
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/Conversions.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/MiIoBasicChannel.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoAbstractHandler.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoBasicHandler.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/transport/MiIoAsyncCommunication.java
- bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.bhf1.json
- bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.light.ceiling.json
- bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.light.ceiling2.json
- bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.light.ceiling4.json
- bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.light.color1.json
- bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.light.lamp1.json
- bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.light.light15.json
Main changes
* Introduce substitutions to allow to send commands containing current timestamp, deviceId or values from existing channels.
* Allow more complex conversions to use values from other channels (in this case used for yeelight rgb channel)
* Use generic way to call the asyncCommunication module
* Fix mapping of yeelights color channel
* Fix unit for yeelight delay
> [miio] Improve yeelight RGB with brightness, introduce substitutions

- bundles/org.openhab.binding.epsonprojector/README.md
- bundles/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/internal/EpsonProjectorCommandType.java
- bundles/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/internal/EpsonProjectorDevice.java
- bundles/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/internal/configuration/EpsonProjectorConfiguration.java
- bundles/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/internal/handler/EpsonProjectorHandler.java
- bundles/org.openhab.binding.epsonprojector/src/main/resources/OH-INF/thing/thing-types.xml
Previously the volume channel only supported projectors with a volume range of 0-20. At least one user in the community forum reported that their projector used a volume range of 0-40 and found that the binding would not work to control their volume. This PR adds the ability to configure the volume range for the user's projector (currently 0-20 and 0-40). The volume channel was changed to a dimmer type and the configured volume range of the projector will be mapped across the dimmer's 0-100% range.
> [epsonprojector] Add configurable volume channel range

- bundles/org.openhab.binding.mielecloud/src/main/java/org/openhab/binding/mielecloud/internal/config/servlet/ForwardToLoginServlet.java
- bundles/org.openhab.binding.mielecloud/src/main/java/org/openhab/binding/mielecloud/internal/util/EmailValidator.java
- bundles/org.openhab.binding.mielecloud/src/main/resources/org/openhab/binding/mielecloud/internal/config/pairing.html
- bundles/org.openhab.binding.mielecloud/src/test/java/org/openhab/binding/mielecloud/internal/util/EmailValidatorTest.java
Fixes #10927. 
Signed-off-by: Björn Lange <bjoern.lange@tu-dortmund.de>
> [mielecloud] Less strict e-mail validation

- bundles/org.openhab.binding.boschshc/README.md
Add addtional info for how to get the device id via log output
I couldn't find the file `OPENHAB_FOLDER/userdata/logs/openhab.log`, so i added alternative ways to get the log output.
> [boschshc] Update Readme.md

- bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/handler/HomematicThingHandler.java
- bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/handler/HomematicThingHandlerFactory.java
- bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/type/HomematicTypeGeneratorImpl.java
The set of available HM-MOD-EM-8 channels varies depending on the
function a given channel is configured to use, which is why for those
devices we can't determine a static ThingType, but instead must populate
the thing channels on initialization. The existing code already handled
that case, but missed registering channel types for the dynamically
generated channels, which is why those channels were not shown in main
UI.
(Original code introduced in #3140)
> [homematic] Fix UI enumeration of HM-MOD-EM-8 channels

- bundles/org.openhab.binding.enocean/src/main/resources/OH-INF/config/config.xml
- bundles/org.openhab.binding.enocean/src/main/resources/OH-INF/thing/ClassicDevice.xml
- bundles/org.openhab.binding.enocean/src/main/resources/OH-INF/thing/gernericChannels.xml
> [enocean] Standardize config URI

- bundles/org.openhab.binding.mqtt.generic/README.md
based https://www.openhab.org/blog/2018-12-16-mqtt-arrives-in-the-modern-openhab-2-x-architecture.html and
https://community.openhab.org/t/textual-vs-ui-driven-configuration/124198/28
Signed-off-by: Markus Storm <markus.storm@gmx.net>
> [mqtt] add .things example to bindings docs

- bundles/org.openhab.binding.kostalinverter/src/main/resources/OH-INF/config/SecondGeneration.xml
- bundles/org.openhab.binding.kostalinverter/src/main/resources/OH-INF/config/ThirdGeneration.xml
- bundles/org.openhab.binding.kostalinverter/src/main/resources/OH-INF/thing/PIKO1020.xml
- bundles/org.openhab.binding.kostalinverter/src/main/resources/OH-INF/thing/PIKOIQ100.xml
- bundles/org.openhab.binding.kostalinverter/src/main/resources/OH-INF/thing/PIKOIQ42.xml
- bundles/org.openhab.binding.kostalinverter/src/main/resources/OH-INF/thing/PIKOIQ55.xml
- bundles/org.openhab.binding.kostalinverter/src/main/resources/OH-INF/thing/PIKOIQ70.xml
- bundles/org.openhab.binding.kostalinverter/src/main/resources/OH-INF/thing/PIKOIQ85.xml
- bundles/org.openhab.binding.kostalinverter/src/main/resources/OH-INF/thing/PLENTICOREPLUS100WITHBATTERY.xml
- bundles/org.openhab.binding.kostalinverter/src/main/resources/OH-INF/thing/PLENTICOREPLUS100WITHOUTBATTERY.xml
- bundles/org.openhab.binding.kostalinverter/src/main/resources/OH-INF/thing/PLENTICOREPLUS42WITHBATTERY.xml
- bundles/org.openhab.binding.kostalinverter/src/main/resources/OH-INF/thing/PLENTICOREPLUS42WITHOUTBATTERY.xml
- bundles/org.openhab.binding.kostalinverter/src/main/resources/OH-INF/thing/PLENTICOREPLUS55WITHBATTERY.xml
- bundles/org.openhab.binding.kostalinverter/src/main/resources/OH-INF/thing/PLENTICOREPLUS55WITHOUTBATTERY.xml
- bundles/org.openhab.binding.kostalinverter/src/main/resources/OH-INF/thing/PLENTICOREPLUS70WITHBATTERY.xml
- bundles/org.openhab.binding.kostalinverter/src/main/resources/OH-INF/thing/PLENTICOREPLUS70WITHOUTBATTERY.xml
- bundles/org.openhab.binding.kostalinverter/src/main/resources/OH-INF/thing/PLENTICOREPLUS85WITHBATTERY.xml
- bundles/org.openhab.binding.kostalinverter/src/main/resources/OH-INF/thing/PLENTICOREPLUS85WITHOUTBATTERY.xml
Fixes using the kostalinverter binding together with the z-wave binding (#7090)
According to the [example in the documentation](https://www.openhab.org/docs/developer/bindings/config-xml.html#xml-structure-for-configuration-descriptions)  the kostalinverter binding seems to use an invalid format for the `config-description` URI. The value must consist of three parts separated by `:` and not just two.
The z-wave binding expects this format and crashes when an invalid one is given.
I verified the fix by building a new JAR and dropping it into my openHAB 3.1.0 instance.
This solution is similar to the one proposed in #7090, but I used the binding name as the first identifier and not already a name related to the config or thing itself.
> [kostalinverter] Fix using binding together with z-wave binding

- bundles/org.openhab.binding.fmiweather/src/main/java/org/openhab/binding/fmiweather/internal/AbstractWeatherHandler.java
- bundles/org.openhab.binding.fmiweather/src/test/java/org/openhab/binding/fmiweather/AbstractWeatherHandlerTest.java
In addition, tests added for static utility functions in AbstractWeatherHandler.
Resolves #11024.
> [fmiweather] Fix UNDEF observations in corner case situations.

- bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/discovery/SqueezeBoxPlayerDiscoveryParticipant.java
- bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxPlayer.java
- bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxPlayerHandler.java
- bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxPlayerState.java
- bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxServerHandler.java
Improve code readability a bit by
- using lambdas for anonymous listener instantiations
- decoding URL encoded responses earlier so the code can check against non-encoded responses
> [squeezebox] Cleanup / code simplification

- CODEOWNERS
- bundles/org.openhab.binding.volvooncall/README.md
- bundles/org.openhab.binding.volvooncall/doc/example.events.txt
- bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/VolvoOnCallBindingConstants.java
- bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/dto/HvBattery.java
- bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/dto/Status.java
- bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/handler/VehicleHandler.java
- bundles/org.openhab.binding.volvooncall/src/main/resources/OH-INF/thing/vehicle.xml
Add some convenience channels for charging status and handle the battery level carefully because the API can be misleading.
> [volvooncall] Extend battery channels

- bundles/org.openhab.binding.deconz/README.md
- bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/dto/GroupAction.java
- bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/GroupThingHandler.java
- bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/LightThingHandler.java
- bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/ThingConfig.java
- bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/config/config.xml
- bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/thing/group-thing-types.xml
- Changed default color mode for color commands to XY
See https://github.com/openhab/openhab-addons/issues/11031#issuecomment-883324344
Similar to https://github.com/openhab/openhab-addons/pull/10608
> [deconz] Changed default color mode for color commands to XY

- bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/generic/internal/MqttBindingConstants.java
- bundles/org.openhab.binding.mqtt.homeassistant/src/main/resources/OH-INF/config/homeassistant-channel-config.xml
- bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/generic/internal/MqttBindingConstants.java
- bundles/org.openhab.binding.mqtt.homie/src/main/resources/OH-INF/config/homie-channel-config.xml
> [homeassistant/homie] Standardize config URI

- bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcPostgresqlDAO.java
Signed-off-by: Riccardo Nimser-Joseph <github@nimric.de>
[jdbc] Select the proper schema when retrieving the item tables from PostgreSQL
JDBC persistence does not specify a (configurable) schema when the tables are created. Therefore, a schema other than 'public' may be used if the 'search_path' is configured in PostgreSQL. In this case the correct schema must be determined when the item tables are retrieved.
> [jdbc] Select the proper schema when retrieving the item tables

- bundles/org.openhab.binding.pushover/README.md
- bundles/org.openhab.binding.pushover/src/main/java/org/openhab/binding/pushover/internal/connection/PushoverConfigurationException.java
- bundles/org.openhab.binding.pushover/src/main/java/org/openhab/binding/pushover/internal/connection/PushoverMessageBuilder.java
- bundles/org.openhab.binding.pushover/src/main/resources/OH-INF/i18n/pushover.properties
- bundles/org.openhab.binding.pushover/src/main/resources/OH-INF/i18n/pushover_de.properties
- Added support to send an Image URL directly
Closes #9340
> [pushover] Add support to send an Image URL directly

- bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/HomeConnectBindingConstants.java
- bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/client/HomeConnectApiClient.java
- bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/client/model/AvailableProgram.java
- bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/AbstractHomeConnectThingHandler.java
- bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/HomeConnectHoodHandler.java
- bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/HomeConnectWasherHandler.java
Fix #10701
Also save in programs cache the unuspported program
> [homeconnect] Predefined temp / spin speeds options for unsupported washer programs

- bundles/org.openhab.binding.mqtt.espmilighthub/README.md
- bundles/org.openhab.binding.mqtt.espmilighthub/src/main/java/org/openhab/binding/mqtt/espmilighthub/internal/discovery/EspMilightHubDiscoveryService.java
- bundles/org.openhab.binding.mqtt.espmilighthub/src/main/java/org/openhab/binding/mqtt/espmilighthub/internal/handler/EspMilightHubHandler.java
- bundles/org.openhab.binding.mqtt.espmilighthub/src/main/resources/OH-INF/config/config.xml
Before these changes with RGB and dual white globes you could not use the color gradients from a color element to switch back to using white LEDs. This change allows a user threshold to be specified where low SATURATION values will change to using the real white LEDs instead of a pastel colour. This is a big improvement as the openHAB colour indicator would show white when the globe was not white.
PR also contains minor refactoring to fix some compiler warnings.
> [espmilight] Add color channels ability to trigger white LEDs

- bundles/org.openhab.binding.pushbullet/README.md
Documentation on when a note will be broadcast based on recipient value.
Related to #5982
> [pushbullet] Update README.md with recipient broadcast information

- CODEOWNERS
- bom/openhab-addons/pom.xml
- bundles/org.openhab.binding.orbitbhyve/NOTICE
- bundles/org.openhab.binding.orbitbhyve/README.md
- bundles/org.openhab.binding.orbitbhyve/pom.xml
- bundles/org.openhab.binding.orbitbhyve/src/main/feature/feature.xml
- bundles/org.openhab.binding.orbitbhyve/src/main/java/org/openhab/binding/orbitbhyve/internal/OrbitBhyveBindingConstants.java
- bundles/org.openhab.binding.orbitbhyve/src/main/java/org/openhab/binding/orbitbhyve/internal/OrbitBhyveConfiguration.java
- bundles/org.openhab.binding.orbitbhyve/src/main/java/org/openhab/binding/orbitbhyve/internal/OrbitBhyveHandlerFactory.java
- bundles/org.openhab.binding.orbitbhyve/src/main/java/org/openhab/binding/orbitbhyve/internal/discovery/OrbitBhyveDiscoveryService.java
- bundles/org.openhab.binding.orbitbhyve/src/main/java/org/openhab/binding/orbitbhyve/internal/handler/OrbitBhyveBridgeHandler.java
- bundles/org.openhab.binding.orbitbhyve/src/main/java/org/openhab/binding/orbitbhyve/internal/handler/OrbitBhyveSprinklerHandler.java
- bundles/org.openhab.binding.orbitbhyve/src/main/java/org/openhab/binding/orbitbhyve/internal/model/OrbitBhyveDevice.java
- bundles/org.openhab.binding.orbitbhyve/src/main/java/org/openhab/binding/orbitbhyve/internal/model/OrbitBhyveDeviceStatus.java
- bundles/org.openhab.binding.orbitbhyve/src/main/java/org/openhab/binding/orbitbhyve/internal/model/OrbitBhyveProgram.java
- bundles/org.openhab.binding.orbitbhyve/src/main/java/org/openhab/binding/orbitbhyve/internal/model/OrbitBhyveSessionResponse.java
- bundles/org.openhab.binding.orbitbhyve/src/main/java/org/openhab/binding/orbitbhyve/internal/model/OrbitBhyveSocketEvent.java
- bundles/org.openhab.binding.orbitbhyve/src/main/java/org/openhab/binding/orbitbhyve/internal/model/OrbitBhyveZone.java
- bundles/org.openhab.binding.orbitbhyve/src/main/java/org/openhab/binding/orbitbhyve/internal/net/OrbitBhyveSocket.java
- bundles/org.openhab.binding.orbitbhyve/src/main/resources/OH-INF/binding/binding.xml
- bundles/org.openhab.binding.orbitbhyve/src/main/resources/OH-INF/config/config.xml
- bundles/org.openhab.binding.orbitbhyve/src/main/resources/OH-INF/thing/bridge.xml
- bundles/org.openhab.binding.orbitbhyve/src/main/resources/OH-INF/thing/channels.xml
- bundles/org.openhab.binding.orbitbhyve/src/main/resources/OH-INF/thing/sprinkler.xml
- bundles/pom.xml
This is the binding for Orbit Bhyve irrrigation systems.
> [orbitbhyve] Initial contribution

- bundles/org.openhab.transform.javascript/README.md
- bundles/org.openhab.transform.javascript/conf/transform/js/readme/readme.js
- bundles/org.openhab.transform.javascript/conf/transform/readme.js
- bundles/org.openhab.transform.javascript/conf/transform/returntest.js
- bundles/org.openhab.transform.javascript/conf/transform/scale.js
- bundles/org.openhab.transform.javascript/conf/transform/sum.js
- bundles/org.openhab.transform.javascript/src/main/java/org/openhab/transform/javascript/internal/JavaScriptTransformationService.java
- bundles/org.openhab.transform.javascript/src/test/java/org/openhab/transform/javascript/internal/JavaScriptTransformationServiceTest.java
> [js-transform] Introduced support for additional parameters

- bundles/org.openhab.binding.unifi/README.md
- bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/model/UniFiController.java
- bundles/org.openhab.binding.unifi/src/main/resources/OH-INF/thing/thing-types.xml
This should fix: #8388 and #10935
This PR adds the following:
- Fixes the 404 error
- Sets a default value for the UniFi OS checkbox (false)
- Adds a bit of documentation
> [unifi] Fixed 404 error with reconnect and no default value set for UniFiOS Checkbox

- bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/AbstractHomeConnectThingHandler.java
> [homeconnect] Fix update of channels linked to program options

- bundles/org.openhab.binding.homeconnect/README.md
- bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/HomeConnectBindingConstants.java
- bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/AbstractHomeConnectThingHandler.java
- bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/HomeConnectWasherDryerHandler.java
- bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/HomeConnectWasherHandler.java
- bundles/org.openhab.binding.homeconnect/src/main/resources/OH-INF/thing/thing-types.xml
> [homeconnect] 2 channels added for washer appliance

- bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/discovery/AbstractMQTTDiscovery.java
- bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/internal/MqttBrokerHandlerFactory.java
The MQTT AbstractBrokerHandler produces erroneous logger warnings when OH is being shutdown for the EspMilight, HomeAssistant, and Homie, discovery services. See #10562 
I think that the problem is because of some or all of the following issues: 
1. The three respective discovery participant classes extend AbstractMQTTDiscovery, and that class may be calling `getDiscoveryService().unsubscribe()` although it might not already have called `getDiscoveryService().subscribe()`.
2. The MqttBrokerHandlerFactory discoveryTopics Map allows duplicate entries of the same listener in each topic's listenerList.
3. The MqttBrokerHandlerFactory subscribe method would re-subscribe the given listener/topic even if already subscribed.
4. The MqttBrokerHandlerFactory unsubscribe method would unsubscribe ALL …
> [mqtt] Discovery services shall not unsubscribe unless they have already subscribed

- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/robot/RRMapDraw.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/robot/RRMapFileParser.java
> [miio] add moppath & carpet area to robomap

- bundles/org.openhab.binding.homematic/README.md
Hi there,
Currently openHAB and the CCU are using different values for the same state of a rollershutter.
This is not part of the docs and could confuse new users.
There are already posts in the community about this with workarounds like proxy items.
Added information about this under Troubleshooting and listed some examples.
Signed-off-by: Michael Bredehorn michael@bredehorn.nrw (github: bredmich)
> [homematic] Added inverted info for rollershutters

- bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/handler/IpCameraHandler.java
- bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/onvif/OnvifConnection.java
Changes are to:
1. Fix a reported bug (via the forum) where a IndexOutOfBoundsException is thrown when the binding sends a PTZ request before ONVIF is fully connected.
2. Remove the use of sleep and to change to using threadpool.
3. Fixes a bug that can happen when a camera keeps sending ONVIF events even after the handler is destroyed.
> [ipcamera] Fix bugs, IndexOutOfBoundsException and remove sleep.

- bundles/org.openhab.binding.verisure/src/main/java/org/openhab/binding/verisure/internal/VerisureSession.java
- bundles/org.openhab.binding.verisure/src/main/java/org/openhab/binding/verisure/internal/handler/VerisureBridgeHandler.java
Fix for #10982 - Binding not working properly HANDLER_REGISTERING_ERROR.
Verisure has implemented 2FA and this PR w.o. the problems caused by that.
> [verisure] Fix Binding not working properly HANDLER_REGISTERING_ERROR

- bundles/org.openhab.binding.luxtronikheatpump/src/main/java/org/openhab/binding/luxtronikheatpump/internal/LuxtronikHeatpumpHandler.java
- bundles/org.openhab.binding.luxtronikheatpump/src/main/java/org/openhab/binding/luxtronikheatpump/internal/enums/HeatpumpChannel.java
- bundles/org.openhab.binding.luxtronikheatpump/src/main/resources/OH-INF/i18n/luxtronikheatpump_de.properties
- bundles/org.openhab.binding.luxtronikheatpump/src/main/resources/OH-INF/thing/channels.xml
- bundles/org.openhab.binding.luxtronikheatpump/src/main/resources/OH-INF/thing/thing-types.xml
Based on some feedback on the forum (https://community.openhab.org/t/migration-of-novelan-luxtronic-binding-to-openhab2/70743/118) we were able to figure out, that the socket parameter used to set the hot water target temperature actually was not fully correct.
The former implementation was based on the binding for OpenHAB2, so seems it had been "wrong" there already.
It seems the socket parameter `2` used to set the hot water target temperature actually sets a value called coverage heat pump ("Deckung WP") in the heat pump control, which seems to be a value related to the hot water target temperature.
The hot water target temperature seems to be set by parameter `105`, which automatically also updates parameter `2` to the same value. (While setting `2`, doesn't update `105`)
> [LuxtronikHeatpump] Fix/update channels for setting hot water target temperature

- bundles/org.openhab.binding.danfossairunit/README.md
- bundles/org.openhab.binding.danfossairunit/src/main/resources/OH-INF/thing/thing-types.xml
Changes:
- Use system default channel type for battery level.
- Add channel categories where applicable.
- Add missing channel descriptions.
- Fix two channel descriptions (also in README) as they are not 10-step.
Semantic tags postponed until further investigated and to avoid conflict with #11121.
> [danfossairunit] Add channel descriptions and categories

- bundles/org.openhab.binding.danfossairunit/README.md
- bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/DanfossAirUnit.java
- bundles/org.openhab.binding.danfossairunit/src/main/resources/OH-INF/thing/thing-types.xml
Fixes #9755
Change channel humidity#humidity to Number:Dimensionless to correctly express and format relative humidity as percent.
As effect, items tracking this channel can be seen in logs like:
[INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'DanfossHRV_Humidity' changed from 59.2 % to 59.6 %
As opposed to previous behaviour:
[INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'DanfossHRV_Humidity' changed from 59.2 to 59.6
With a properly defined item without any custom formatting:
`Number:Dimensionless DanfossHRV_Humidity "Relative humidity" <humidity> ["Measurement", "Humidity"] { channel = "danfossairunit:airunit:a2:humidity#humidity" }`
Sitemaps can format value correctly:
`Text item=DanfossHRV_Humidity`
Previously something like this was needed for Number item:
`Text …
> [danfossairunit] Change Humidity channel type from Number to Number:Dimensionless

- bundles/org.openhab.binding.zway/src/main/resources/OH-INF/config/bridge-config.xml
Hi,
when using the Z-Way binding there is a significant delay in receiving a new value as there are no events in the Z-Way API, but instead there is constant polling to detect change. For example the Z-Wave Frontend shows constant requests to ``/ZAutomation/api/v1/devices?since=[timestamp]`` as seen here:
As you can see by the timestamp in the request URL, they are being sent every 1-2 seconds, while the openHAB binding allows a polling interval from 60 seconds to the default 1 hour. Since the Z-Wave interface does such frequent polling I believe it is appropiate for openHAB to at least support the same. I am unsure whether the default 1 hour interval is appropiate, so I left it unchanged.
I have found #8264 mentioning the same thing, but there is no activity there.
Thank you.
> [zway] Change minimum polling interval to 1 second.

- bundles/org.openhab.binding.irobot/README.md
Minor documentation clarification originally described here https://community.openhab.org/t/irobot-9xx-on-openhab/17774/196 by original author. I had to spend some hours because I did not find the information buried in the thread initially.
Signed-off-by: kennetn <kennetn@gmail.com>
> [irobot] Minor readme corrections

- bundles/org.openhab.binding.icloud/README.md
Fix an extra space in the iCloud binding docs to make spacing consistent
> Make spacing consistent in iCloud binding rule example

- bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxServerHandler.java
> [squeezebox] Fixes volume parsing when volume string is a float

- bundles/org.openhab.binding.danfossairunit/README.md
- bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/Channel.java
- bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/DanfossAirUnit.java
- bundles/org.openhab.binding.danfossairunit/src/main/resources/OH-INF/thing/thing-types.xml
Fixes #10621
Binding can read fan speeds (in rpm) and read/control fan steps (in percent or steps). The channel used to control fan step (10 steps) is named "manual_fan_speed". This is misleading as it's actually a step.
I noticed when reconfiguring in files:
```
Dimmer DanfossHRV_Main_ManualFanSpeed <fan> (DanfossHRV) ["Control"] { channel = "danfossairunit:airunit:a2:main#manual_fan_speed" }
Number DanfossHRV_Main_SupplyFanSpeed <fan> (DanfossHRV) ["Measurement"] { channel = "danfossairunit:airunit:a2:main#supply_fan_speed" }
Number DanfossHRV_Main_ExtractFanSpeed <fan> (DanfossHRV) ["Measurement"] { channel = "danfossairunit:airunit:a2:main#extract_fan_speed" }
Dimmer DanfossHRV_Main_SupplyFanStep <fan> (DanfossHRV) …
```
> [danfossairunit] Renamed channel manual_fan_speed to manual_fan_step for consistency.

- bundles/org.openhab.binding.epsonprojector/README.md
- bundles/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/internal/EpsonProjectorCommandType.java
- bundles/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/internal/handler/EpsonProjectorHandler.java
Fix issue addressed by #11140 in epsonprojector binding.
> [epsonprojector] Fix equalsIgnoreCase issue

- bundles/org.openhab.binding.miio/README.base.md
- bundles/org.openhab.binding.miio/README.md
> [miio] Improve readme: restructure & map customizing feature

- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewShadeHandler.java
Fixes #11200
**BatteryStatus**
0 = No Status Available, 1 = Low, 2 = Medium, 3 = High, 4 = Plugged In
Type : enum (0, 1, 2, 3, 4)
> [hdpowerview] Fix low battery when no battery status available

- bundles/org.openhab.binding.hdpowerview/README.md
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/HDPowerViewBindingConstants.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/responses/Shades.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewShadeHandler.java
- bundles/org.openhab.binding.hdpowerview/src/main/resources/OH-INF/thing/thing-types.xml
- bundles/org.openhab.binding.hdpowerview/src/test/java/org/openhab/binding/hdpowerview/HDPowerViewJUnitTests.java
Fixes #11197
This adds a new signalStrength channel to the Hunter Douglas PowerView binding. See #11197
> [hdpowerview] Add new signal strength channel

- bundles/org.openhab.binding.bsblan/src/main/resources/OH-INF/thing/bridge.xml
- bundles/org.openhab.binding.bsblan/src/main/resources/OH-INF/thing/thing-types.xml
The main UI in OH3 seems to not show configuration parameters of Things when `groupName` is specified but the related `parameter-group` node is missing in the definition XML.
Could possibly be a change in behavior compared to the OH 2.5 (?) UI?
A similar issue has already been discussed here: [V2 vs V3 - Option Parameter not showing](https://community.openhab.org/t/solved-v2-vs-v3-option-parameter-not-showing/115685/3)
> [bsblan] Several configuration parameters are not visible in Main UI

- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/MieleApplianceHandler.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/MieleBridgeHandler.java
Fixes #8877
This is a MVP bugfix for broken support of things files.
This is an alternative solution to #8902 where protocol information is kept as a property instead of being added to configuration. This has the advantage of being transparent for users, i.e. no need to configure anything.
From code perspective protocol is kept as either **ZigBee** or **LAN** without introducing further protocol confusion by adding a third option (**Wi-Fi**) being mapped to LAN.
PR can be merged as-is for fixing the root cause, in which case I plan to provide another PR for simplifying and abstracting the protocol (as separate issue). In case of impatience from my side, I might also consider adding more commits into this PR. Let me know what you …
> [miele] Fix broken things file support.

- bundles/org.openhab.binding.hdpowerview/README.md
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/HDPowerViewBindingConstants.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewShadeHandler.java
- bundles/org.openhab.binding.hdpowerview/src/main/resources/OH-INF/thing/thing-types.xml
- bundles/org.openhab.binding.hdpowerview/src/test/java/org/openhab/binding/hdpowerview/HDPowerViewJUnitTests.java
- bundles/org.openhab.binding.hdpowerview/src/test/resources/duette.json
Fixes #11205
This adds a new channel **batteryLevel** of standard type _system.battery-level_ extracting as much data as possible from the Hunter Douglas PowerView Hub. This is quite limited as only three different values are available: low, medium or high. Previously it was only possible through channel **lowBattery** to deduct if level was either low or medium/high. In the future this channel could be improved by calculations taking voltage into consideration also.
Also fixes a regression from #11201 where "no status available" when **lowBattery** was ON would lead to **lowBattery** being reset to OFF.
> [hdpowerview] Add new battery level channel

- bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/PulseAudioAudioSink.java
- bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/handler/PulseaudioHandler.java
Fixes #11170 by introducing an intelligent Thread.sleep (getting the duration of the sound if possible, then wait the appropriate time for letting the sound play).
Also fix a minor issue with the last volume not propertly saved.
And fix some minor warnings by using final local variable.
Signed-off-by: Gwendal ROULLEAU <gwendal.roulleau@gmail.com>
[Link to jar](https://github.com/dalgwen/openhab-addons/releases/tag/3.2.0-SNAPSHOT_pulseaudio_11170)
> [pulseaudio] Fix playing time with pulseaudio sink (#11170)

- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoAbstractHandler.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/transport/MiIoAsyncCommunication.java
* Closing #11152
* Better identify communication threads
> [miio] Avoid shutting down shared executor service

- bundles/org.openhab.binding.homematic/src/test/java/org/openhab/binding/homematic/internal/communicator/virtual/ButtonDatapointTest.java
The test was disabled using a JUnit4 annotation, which didn't show any effect and thus our builds kept failing due to this unstable test.
https://github.com/openhab/openhab-addons/issues/10753
> Correctly disable unstable test

- bundles/org.openhab.binding.telegram/src/main/java/org/openhab/binding/telegram/internal/TelegramHandler.java
- bundles/org.openhab.binding.telegram/src/main/java/org/openhab/binding/telegram/internal/action/TelegramActions.java
+ Fixes a NPE causing action/rule to not complete, reported on forum here https://community.openhab.org/t/solved-telegram-sendtelegramanswer-works-but-error-in-log-file-null-in-xxx/126039/14
+ Possible fix for #11102 which is a SocketTimeoutException that causes an action to not complete.
+ Closes #11048 Where the order that channels are updated can causes rule complexity and prone to errors.
> [telegram] Fixes exceptions that stop rules/actions from finishing

- bundles/org.openhab.automation.groovyscripting/README.md
- bundles/org.openhab.automation.groovyscripting/pom.xml
For all bugfixes and improvements, see:
http://groovy-lang.org/changelogs/changelog-3.0.9.html
> [groovyscripting] Update Groovy to 3.0.9

- bundles/org.openhab.io.metrics/README.md
- bundles/org.openhab.io.metrics/pom.xml
- bundles/org.openhab.io.metrics/src/main/java/org/openhab/io/metrics/MetricsConfiguration.java
- bundles/org.openhab.io.metrics/src/main/java/org/openhab/io/metrics/MetricsExporter.java
- bundles/org.openhab.io.metrics/src/main/java/org/openhab/io/metrics/MetricsRestController.java
- bundles/org.openhab.io.metrics/src/main/java/org/openhab/io/metrics/exporters/InfluxMetricsExporter.java
- bundles/org.openhab.io.metrics/src/main/java/org/openhab/io/metrics/exporters/JmxMetricsExporter.java
- bundles/org.openhab.io.metrics/src/main/resources/OH-INF/config/config.xml
* Add Java Management Extensions (JMX) metrics exporter
* Use groups in metrics add-on configuration
* Improve null annotations
* Update documentation
---
Depends on https://github.com/openhab/openhab-core/pull/2486
> [metrics] Add Java Management Extensions (JMX) metrics exporter

- bundles/org.openhab.binding.hdpowerview/README.md
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/HDPowerViewWebTargets.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/config/HDPowerViewHubConfiguration.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewHubHandler.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewShadeHandler.java
- bundles/org.openhab.binding.hdpowerview/src/main/resources/OH-INF/thing/thing-types.xml
- bundles/org.openhab.binding.hdpowerview/src/test/java/org/openhab/binding/hdpowerview/HDPowerViewJUnitTests.java
Add Hub configuration option **hardRefreshBatteryLevel** for refreshing battery status more frequently.
Also, when battery data is missing or invalid, explicitly update channels to UNDEF. Previously, **lowBattery** and **batteryLevel** would be skipped, and **batteryVoltage** would be updated to 0 V.
Fixes #11259
> [hdpowerview] Add Hub configuration option hardRefreshBatteryLevel

- bundles/org.openhab.binding.somfytahoma/README.md
- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/SomfyTahomaBindingConstants.java
- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaBaseThingHandler.java
- bundles/org.openhab.binding.somfytahoma/src/main/resources/OH-INF/thing/channels.xml
This PR fixes two bugs relating to the Somfy Tahoma binding
- RSSI dynamic channel creation was not working since OH 3.x
- server side of the Somfy Tahoma cloud has started sending an empty value which was not interpretted correctly
> [somfytahoma] Fixed rssi channels creation & properties updating

- bundles/org.openhab.binding.homematic/README.md
- bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/virtual/ButtonVirtualDatapointHandler.java
- bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/handler/HomematicThingHandler.java
- bundles/org.openhab.binding.homematic/src/test/java/org/openhab/binding/homematic/internal/communicator/virtual/ButtonDatapointTest.java
HM devices provide not only 'long press' events, but also 'long
press continued' (sent in configured long press interval) and 'long
press released' events. So far, those events were swallowed in the
button datapoint handler.
Improve the situation by forwarding those events to the button trigger
channel, making them usable in e.g. rules that react on button long
presses.
> [homematic] Remove double press events and improve long press events for button trigger

- bundles/org.openhab.binding.telegram/README.md
- bundles/org.openhab.binding.telegram/src/main/java/org/openhab/binding/telegram/internal/TelegramBindingConstants.java
- bundles/org.openhab.binding.telegram/src/main/java/org/openhab/binding/telegram/internal/TelegramHandler.java
- bundles/org.openhab.binding.telegram/src/main/java/org/openhab/binding/telegram/internal/action/TelegramActions.java
- bundles/org.openhab.binding.telegram/src/main/resources/OH-INF/thing/thing-types.xml
This adds 4 event trigger channels that fire when messages or query callbacks are received, presenting the entire message as the payload for easier use in rules.
* `messageEvent` provides simplified message properties
* `messageRawEvent` provides the entire message object from the Telegram library
* `callbackEvent` provides simplified callback query properties
* `callbackRawEvent` provides the entire callback query object from the Telegram library
Additionally, a new overload to the `sendTelegramAnswer` action was added that allows you to provide the `callbackId` and `messageId` that would normally be retrieved by a lookup in the handler. This can be used to answer queries that were sent before openHAB restarted by saving the `callbackId` and `messageId` outside the binding, or to answer …
> [telegram] Add event channels and Answer overload

- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/FullyQualifiedApplianceIdentifier.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/MieleBindingConstants.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/discovery/MieleApplianceDiscoveryService.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/discovery/MieleMDNSDiscoveryParticipant.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/ApplianceStatusListener.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/CoffeeMachineHandler.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/DishWasherHandler.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/FridgeFreezerHandler.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/FridgeHandler.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/HoodHandler.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/MieleApplianceHandler.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/MieleBridgeHandler.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/OvenHandler.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/TumbleDryerHandler.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/WashingMachineHandler.java
- bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/channeltypes.xml
- bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/coffeemachine.xml
- bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/dishwasher.xml
- bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/fridge.xml
- bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/fridgefreezer.xml
- bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/hob.xml
- bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/hood.xml
- bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/oven.xml
- bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/tumbledryer.xml
- bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/washingmachine.xml
- bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/xgw3000.xml
- bundles/org.openhab.binding.miele/src/test/java/org/openhab/binding/miele/internal/FullyQualifiedApplianceIdentifierTest.java
Fixes #11242
Fixes #11243
Fixes #11252
This PR fixes issues related to protocol support and broken multicast support. This is a continuation of #11218 which was a quickfix, while this one is more in-depth and trying to fix root cause, but with full backwards configuration compatibility:
- Protocol specification is no longer parsed/interpreted, but simply concatenated with configured appliance ID's which unfortunately are without this. This makes it also forwards-compatible with any new protocol.
- Hardcoded ZigBee protocol for all handlers except oven has been fixed, so that actions for Wi-Fi devices will now work.
Also fixed multicast support which was broken by an XGW 3000 firmware upgrade in 2016. This fix is backwards compatible, …
> [miele] Fix multicast and multi-protocol support (ZigBee/Wi-Fi)

- bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/WakeOnLanPacketSender.java
- bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/handler/NetworkHandler.java
- bundles/org.openhab.binding.network/src/test/java/org/openhab/binding/network/internal/WakeOnLanPacketSenderTest.java
Added possiblity to send WOL Requests to configured Hostname, 
removed unnecessary unit from Timeout Annotation in WakeOnLanPacketSenderTest
Signed-off-by: Jonathan Saxen <jonathan@saxen.info>
The goal of this Pull request is to fix the Bug described in [#11196](https://github.com/openhab/openhab-addons/issues/11196)
> [Network] Add possiblity to send WOL Requests to configured Hostname

- bundles/org.openhab.binding.luxtronikheatpump/README.md
- bundles/org.openhab.binding.luxtronikheatpump/src/main/java/org/openhab/binding/luxtronikheatpump/internal/LuxtronikHeatpumpHandler.java
- bundles/org.openhab.binding.luxtronikheatpump/src/main/java/org/openhab/binding/luxtronikheatpump/internal/enums/HeatpumpChannel.java
- bundles/org.openhab.binding.luxtronikheatpump/src/main/resources/OH-INF/i18n/luxtronikheatpump_de.properties
- bundles/org.openhab.binding.luxtronikheatpump/src/main/resources/OH-INF/thing/channels.xml
- bundles/org.openhab.binding.luxtronikheatpump/src/main/resources/OH-INF/thing/thing-types.xml
The binding for luxtronik based heatpumps currently doesn't provider a channel for setting/reading the heating limit temperature ("Heizgrenze" in German).
This was requested on the forum: https://community.openhab.org/t/migration-of-novelan-luxtronic-binding-to-openhab2/70743/130?u=sgiehl
> [LuxtronikHeatpump] Adds additional setting for heating limit temperature

- bundles/org.openhab.binding.modbus/DEVELOPERS.md
As discussed in #8551. See comment from fwolter at Sep 23 2020.:
https://github.com/openhab/openhab-addons/issues/8551#issuecomment-697237105
> [modbus] DEVELOPERS.md: fix jamod dependency in demo app

- bundles/org.openhab.io.metrics/README.md
- bundles/org.openhab.io.metrics/src/main/java/org/openhab/io/metrics/MetricsRestController.java
The configuration PID is not defined so currently `org.openhab.io.metrics.MetricsRestController` is used.
Also added an example to the docs.
Fixes #11279
---
I went for a configuration PID similar to the persistence services so the `ConfigDispatcher` can also resolve the namespace to "org.openhab.metrics" if you use a `metrics.cfg` file and omit the namespace from settings keys (which does not work for bindings and several other addons) .
> [metrics] Fix configuration PID and add file based configuration example

- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/MieleApplianceHandler.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/OvenChannelSelector.java
Fixes #11286
See issue description. Channel **type** for ovens was not fully implemented, so would throw exception when item was linked.
> [miele] Fix IllegalArgumentException when using oven channel 'type'

- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueBridgeHandler.java
I just experienced my bridge being in INITIALIZING state, although the handler successfully returned from the `initialize()` method.
> [hue] Make sure bridge status is set when returning from initialize

- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/ExtendedDeviceStateUtil.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/MieleBindingConstants.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/ApplianceChannelSelector.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/CoffeeMachineChannelSelector.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/DishWasherHandler.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/DishwasherChannelSelector.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/ExtendedDeviceStateListener.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/FridgeChannelSelector.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/FridgeFreezerChannelSelector.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/HobChannelSelector.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/HoodChannelSelector.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/MieleApplianceHandler.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/OvenChannelSelector.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/TumbleDryerChannelSelector.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/WashingMachineChannelSelector.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/WashingMachineHandler.java
- bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/channeltypes.xml
- bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/dishwasher.xml
- bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/washingmachine.xml
- bundles/org.openhab.binding.miele/src/test/java/org/openhab/binding/miele/internal/ExtendedDeviceStateUtilTest.java
> [miele] Add new power and water consumption channels for dishwashers and washing machines

- pom.xml
This allows bnd to resolve multi release jar files.
A number of people have posted they have troubles adding dependancies on the forum with this error.
`Classes found in the wrong directory: {META-INF/versions/9/module-info.class=module-info}`
Issue about it is here:
https://github.com/bndtools/bnd/issues/2227
An alternative fix is to add the following into each bindings pom.xml
```
<properties>
<bnd.fixupmessages>"Classes found in the wrong directory"; is:=warning</bnd.fixupmessages>
</properties>
```
Not sure what the correct way to handle this is but these are two ways I have tested. The suggested way will mean any future people wont hit the error and can spend more time coding.
> Allow multi release JARs to resolve

- itests/org.openhab.binding.mielecloud.tests/src/main/java/org/openhab/binding/mielecloud/internal/handler/AbstractMieleThingHandlerTest.java
Increases the integration test timeout to avoid failures in the CI build, see #11283.
> [mielecloud] Increase timeout for integration tests

- bundles/org.openhab.automation.pidcontroller/src/main/java/org/openhab/automation/pidcontroller/internal/handler/PIDControllerTriggerHandler.java
> [pidcontroller] Improve logging

- bundles/org.openhab.binding.danfossairunit/src/main/resources/OH-INF/thing/thing-types.xml
- bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/thing/group-thing-types.xml
- bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/thing/light-thing-types.xml
- bundles/org.openhab.binding.dmx/src/main/resources/OH-INF/thing/channels.xml
- bundles/org.openhab.binding.feican/src/main/resources/OH-INF/thing/channels.xml
- bundles/org.openhab.binding.homeconnect/src/main/resources/OH-INF/thing/thing-types.xml
- bundles/org.openhab.binding.lghombot/src/main/resources/OH-INF/thing/thing-types.xml
- bundles/org.openhab.binding.linuxinput/src/main/resources/OH-INF/thing/thing-types.xml
- bundles/org.openhab.binding.mihome/src/main/resources/OH-INF/thing/channel.xml
- bundles/org.openhab.binding.milight/src/main/resources/OH-INF/thing/channels.xml
- bundles/org.openhab.binding.millheat/src/main/resources/OH-INF/thing/channels.xml
- bundles/org.openhab.binding.nikohomecontrol/src/main/resources/OH-INF/thing/thing-types.xml
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/channels.xml
- bundles/org.openhab.binding.playstation/src/main/resources/OH-INF/thing/thing-types.xml
- bundles/org.openhab.binding.qbus/src/main/resources/OH-INF/thing/thing-types.xml
- bundles/org.openhab.binding.sensibo/src/main/resources/OH-INF/thing/channels.xml
- bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/thing/device.xml
- bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/thing/sensor.xml
- bundles/org.openhab.binding.touchwand/src/main/resources/OH-INF/thing/switch.xml
- bundles/org.openhab.binding.wled/src/main/resources/OH-INF/thing/thing-types.xml
- bundles/org.openhab.binding.yeelight/src/main/resources/OH-INF/thing/channels.xml
There used to be the following "Default Tags" which are no longer used in the current semantic model:
* Lighting
* Switchable
* CurrentTemperature
* TargetTemperature
* CurrentHumidity
See:
* https://www.openhab.org/docs/developer/bindings/thing-xml.html#default-tags
* https://www.openhab.org/docs/tutorial/model.html#semantic-model
---
I also fixed this for the LIFX Binding in https://github.com/openhab/openhab-addons/pull/11309.
> Fix/remove outdated "Default Tags"

- bundles/org.openhab.binding.mail/README.md
- bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/internal/MailBuilder.java
- bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/internal/action/SendMailActions.java
- bundles/org.openhab.binding.mail/src/main/resources/OH-INF/i18n/mail.properties
- bundles/org.openhab.binding.mail/src/test/java/org/openhab/binding/mail/MailBuilderTest.java
**Background**
Previously e-mails sent by this binding could not be grouped into a "threaded view" in the user's email client, because the binding could not provide an e-mail "Reference" header (which is the key for message threading).
**Solution**
This PR allows one to (optionally) add e-mail headers such as, but not limited to, the "Reference" header.
**Example Rule**
```
rule "Send Mail with a Reference Header"
when
...
then
val mailer = getActions("mail","mail:smtp:xyz")
mailer.addHeader("Reference", "<unique-thread-identifier>")
mailer.sendMail("joe@abc.com", "message-subject", "message-text")
end
```
> [mail] Add support for e-mail headers

- bundles/org.openhab.binding.lifx/README.md
- bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/LifxBindingConstants.java
- bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/LifxChannelFactory.java
- bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/LifxChannelFactoryImpl.java
- bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/handler/LifxLightHandler.java
- bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/util/LifxMessageUtil.java
- bundles/org.openhab.binding.lifx/src/main/resources/OH-INF/i18n/lifx.properties
- bundles/org.openhab.binding.lifx/src/main/resources/OH-INF/i18n/lifx_nl.properties
- bundles/org.openhab.binding.lifx/src/main/resources/OH-INF/thing/channel.xml
- bundles/org.openhab.binding.lifx/src/main/resources/OH-INF/thing/colorhevlight.xml
- bundles/org.openhab.binding.lifx/src/main/resources/OH-INF/thing/colorirlight.xml
- bundles/org.openhab.binding.lifx/src/main/resources/OH-INF/thing/colorlight.xml
- bundles/org.openhab.binding.lifx/src/main/resources/OH-INF/thing/colormzlight.xml
- bundles/org.openhab.binding.lifx/src/main/resources/OH-INF/thing/tilelight.xml
- bundles/org.openhab.binding.lifx/src/main/resources/OH-INF/thing/whitelight.xml
Adds an 'abstemperature' channel to all Thing Types for controlling the absolute color temperature in Kelvin.
MultiZone lights also have 'abstemperaturezone' channels that allow for controlling the color temperature of a zone in Kelvin.
These channels make it easier to use the same color temperature with lights that have a different color temperature range.
Furthermore the channel type tags have been updated which simplifies using the generated items with the semantic model.
> [lifx] Add channels for controlling absolute color temperature in Kelvin

- bundles/org.openhab.binding.tplinksmarthome/README.md
- bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/TPLinkSmartHomeBindingConstants.java
- bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/TPLinkSmartHomeHandlerFactory.java
- bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/TPLinkSmartHomeThingType.java
- bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/device/BulbDevice.java
- bundles/org.openhab.binding.tplinksmarthome/src/main/resources/OH-INF/thing/EP10.xml
- bundles/org.openhab.binding.tplinksmarthome/src/main/resources/OH-INF/thing/EP40.xml
- bundles/org.openhab.binding.tplinksmarthome/src/main/resources/OH-INF/thing/KL125.xml
- bundles/org.openhab.binding.tplinksmarthome/src/main/resources/OH-INF/thing/KL135.xml
- bundles/org.openhab.binding.tplinksmarthome/src/main/resources/OH-INF/thing/channels.xml
- bundles/org.openhab.binding.tplinksmarthome/src/test/java/org/openhab/binding/tplinksmarthome/internal/device/BulbDeviceTest.java
> [tplinksmarthome] Added new devices EP10, EP40, KL125, and KL135

- bundles/org.openhab.binding.luxtronikheatpump/src/main/java/org/openhab/binding/luxtronikheatpump/internal/HeatpumpConnector.java
As reported on the forum some older heatpumps seem to serve less than 154 socket channels, causing a out of bounds error.
See https://community.openhab.org/t/migration-of-novelan-luxtronic-binding-to-openhab2/70743/132?u=sgiehl
> [Luxtronik] Fix possible out ouf bound error for older heatpumps

- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/ExtendedDeviceStateUtil.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/MieleBindingConstants.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/ApplianceChannelSelector.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/ApplianceStatusListener.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/CoffeeMachineChannelSelector.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/DishwasherChannelSelector.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/FridgeChannelSelector.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/FridgeFreezerChannelSelector.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/FridgeFreezerHandler.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/FridgeHandler.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/HobChannelSelector.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/HoodChannelSelector.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/MieleApplianceHandler.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/MieleBridgeHandler.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/OvenChannelSelector.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/TumbleDryerChannelSelector.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/WashingMachineChannelSelector.java
- bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/channeltypes.xml
Fix channels **supercool** and **superfreeze** for fridges/fridge-freezers.
Both channels were declared as read-only strings, but should have been writable switches, and are in fact handled as switches in handleCommand:
```
case SUPERCOOL: {
if (command.equals(OnOffType.ON)) {
result = bridgeHandler.invokeOperation(applianceIdentifier, modelID, "startSuperCooling");
} else if (command.equals(OnOffType.OFF)) {
result = bridgeHandler.invokeOperation(applianceIdentifier, modelID, "stopSuperCooling");
}
```
Furthermore, the channels were not updated according to current operation of the fridge/fridge-freezer. This fix enables two-way synchronization of the supercool/superfreeze state by using the **state** property.
See more details in linked issue.
Tested with fridge.
Initial sitemap: …
> [miele] Fix supercool/superfreeze for fridges/fridge-freezers

- bundles/org.openhab.binding.systeminfo/README.md
- bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/SysteminfoBindingConstants.java
- bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/handler/SysteminfoHandler.java
- bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/model/OSHISysteminfo.java
- bundles/org.openhab.binding.systeminfo/src/main/resources/OH-INF/thing/channels.xml
* Add 2 extra channels for tracking the Java heap sizes.
* Refactor to remove use of a apache.commons lib
* Clean up the readme and some logging.
Precompiled jar can be downloaded here:
http://pcmus.com/openhab/sysinfo/
> [systeminfo] Add 2 new channels for Java heap

- pom.xml
Update to latest Netty which has 2 security fixes in it.
https://netty.io/news/2021/09/09/4-1-68-Final.html
> Bump library netty.io to 4.1.68.Final

- bundles/org.openhab.binding.modbus.helioseasycontrols/README.md
There are two binding supporting different types of Helios ventilation systems. Cross referencing the bindings in their descriptions should help users identify the right binding for their device.
> [helioseasycontrols] reference heliosventilation binding

- bundles/org.openhab.binding.heliosventilation/README.md
There are two binding supporting different types of Helios ventilation systems. Cross referencing the bindings in their descriptions should help users identify the right binding for their device.
> [heliosventilation] reference modbus.helioseasycontrols binding

- CODEOWNERS
- bundles/org.openhab.binding.miele/README.md
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/ExtendedDeviceStateUtil.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/MieleBindingConstants.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/FridgeChannelSelector.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/FridgeFreezerChannelSelector.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/OvenChannelSelector.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/WashingMachineChannelSelector.java
- bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/channeltypes.xml
- bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/fridge.xml
- bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/fridgefreezer.xml
- bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/oven.xml
- bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/washingmachine.xml
- bundles/org.openhab.binding.miele/src/test/java/org/openhab/binding/miele/internal/ExtendedDeviceStateUtilTest.java
This PR improves channels provided by the binding in different ways.
- Changed type from **Number** to **Number:Temperature**.
- Now supports Unit of Measurement.
- Fixed descriptions for specific appliances. For example, previously target temperature channels were described as "Target temperature to be reached by the oven", but in fact applied also to fridge and washing machine.
- Special value 32768 °C is now correctly translated into **Undefined**.
- Added category **Temperature** for default icons.
For washing machines spinning speed was multiplied by 10. Probably mislead by description in response JSON:
```
{
"Name": "spinningSpeed",
"Value": 1600,
"Polling": 0,
"Metadata": {
"Filter": "true",
"description": "Spinning speed divided by 10!, 0x00 = without spinning, 0xFF = rinse …
```
> [miele] Temperature channel improvements: UoM, categories and descriptions

- bundles/org.openhab.binding.magentatv/src/main/java/org/openhab/binding/magentatv/internal/handler/MagentaTVControl.java
- bundles/org.openhab.binding.magentatv/src/main/java/org/openhab/binding/magentatv/internal/handler/MagentaTVHandler.java
- bundles/org.openhab.binding.magentatv/src/main/java/org/openhab/binding/magentatv/internal/network/MagentaTVPoweroffListener.java
This PR fixes a small bug, which didn't started the UPnP listener. This is used to catch the situation where the receiver is switch off with the physical power button
> [magentatv] Fix: Start UPNP listener to catch power off button, thing id in log

- bundles/org.openhab.binding.bsblan/src/main/java/org/openhab/binding/bsblan/internal/helper/BsbLanParameterConverter.java
- bundles/org.openhab.binding.bsblan/src/test/java/org/openhab/binding/bsblan/internal/helper/BsbLanParameterConverterTests.java
When using items of e.g. type `Number:Temperature` (e.g. for room temperature setpoint) changing the item's value is not possible because the internal conversion of the binding fails.
```
2021-09-08 21:55:00.715 [WARN ] [rnal.helper.BsbLanParameterConverter] - Command '23 °C' is not a valid number value
2021-09-08 21:55:00.718 [WARN ] [ernal.handler.BsbLanParameterHandler] - Channel 'number-value' is read only or conversion failed. Ignoring command
```
This change solves this issue.
> [bsblan] Support quantity types for "number-value" channel

- bundles/org.openhab.binding.automower/README.md
- bundles/org.openhab.binding.automower/src/main/java/org/openhab/binding/automower/internal/AutomowerBindingConstants.java
- bundles/org.openhab.binding.automower/src/main/java/org/openhab/binding/automower/internal/rest/api/automowerconnect/dto/MowerData.java
- bundles/org.openhab.binding.automower/src/main/java/org/openhab/binding/automower/internal/rest/api/automowerconnect/dto/Position.java
- bundles/org.openhab.binding.automower/src/main/java/org/openhab/binding/automower/internal/things/AutomowerCommand.java
- bundles/org.openhab.binding.automower/src/main/java/org/openhab/binding/automower/internal/things/AutomowerHandler.java
- bundles/org.openhab.binding.automower/src/main/resources/OH-INF/thing/thing-types.xml
This PR adds support for the GPS coordinates provided by the Husqvarna Automower Connect API.
When requested the latest 'Mower Data' via the API the last 50 GPS positions are also provided.
They can be useful to visualize the mower's path or identify his last position in case of an error.
Considering the large number of additional channels, this PR introduces also some channel groups to structure the channels and separate the GPS channels from the rest.
> [automower] Support for GPS coordinates provided by API

- bundles/org.openhab.binding.lgwebos/src/main/resources/OH-INF/config/config.xml
- bundles/org.openhab.binding.lgwebos/src/main/resources/OH-INF/i18n/lgwebos.properties
> [lgwebos] Fix a setting description

- bundles/org.openhab.binding.openwebnet/README.md
- bundles/org.openhab.binding.openwebnet/pom.xml
- bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/OpenWebNetBindingConstants.java
- bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/OpenWebNetHandlerFactory.java
- bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/actions/OpenWebNetCENActions.java
- bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/discovery/OpenWebNetDeviceDiscoveryService.java
- bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetBridgeHandler.java
- bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetEnergyHandler.java
- bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetScenarioHandler.java
- bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetThingHandler.java
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusAutomation.xml
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusCENPlusScenarioControl.xml
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusCENScenarioControl.xml
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusDimmer.xml
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusEnergyMeter.xml
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusOnOffSwitch.xml
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusThermoSensor.xml
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusThermoZone.xml
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/ZBAutomation.xml
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/ZBDimmer.xml
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/ZBOnOffSwitch.xml
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/ZBOnOffSwitch2Units.xml
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/channels.xml
This PR adds support for CEN/CEN+ scenarios (WHO=15/25) to the [openwebnet] binding.
With this addition BTicino BUS scenarios (WHO=15/25) can be detected and activated from OH3, enabling OH3 to work as a scenario manager for a BTicino installation, allowing for example to control other OH3-controlled devices from a bticino scenario button.
Configuration for new things and channel has been added to the add-on README.
Testing of this new addition by some users has been positive [as discussed here](https://community.openhab.org/t/openwebnet-adding-cen-cen-support-to-oh3/126882/).
Closes #11003.
> [openwebnet] added support for CEN/CEN+ scenarios (WHO=15/25)

- bundles/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/internal/handler/ZmBridgeHandler.java
There are situations when the binding updates the state options even if the options haven't changed. This results in an unnecessary reload of the page in Basic UI. With this change, the state options are updated only if they change.
> [zoneminder] Only update state options if they've changed

- bundles/org.openhab.binding.pjlinkdevice/src/main/java/org/openhab/binding/pjlinkdevice/internal/device/PJLinkDevice.java
Fixes authentication problems that have been [reported by itseogo on the OpenHAB Community](https://community.openhab.org/t/new-pjlink-binding-for-controlling-multiple-projector-brands-models/56608/47?u=nils.schnabel).
The problem was caused by an earlier compatibility fix that generally uppercased responses from the projector. This should not be done for the authentication nonce (which contains lowercase characters that have to be preserved).
The JAR should be available soon. 
[Here I guess](https://openhab.jfrog.io/native/libs-pullrequest-local/org/openhab/addons/bundles/org.openhab.binding.pjlinkdevice/3.2.0-SNAPSHOT/org.openhab.binding.pjlinkdevice-3.2.0-SNAPSHOT.jar) (needs to be validated after the build).
> [pjlinkdevice] fix authentication

- bundles/org.openhab.binding.verisure/src/main/java/org/openhab/binding/verisure/internal/VerisureSession.java
- bundles/org.openhab.binding.verisure/src/main/java/org/openhab/binding/verisure/internal/dto/VerisureBaseThingDTO.java
- bundles/org.openhab.binding.verisure/src/main/java/org/openhab/binding/verisure/internal/handler/VerisureBridgeHandler.java
Fix for #11396 - Runtime exception not caught causing periodic refresh to stop.
The binding does not handle a RuntimeException correctly which leads to that the binding stops to refresh, which this PR fixes.
Signed-off-by: Jan Gustafsson jannegpriv@gmail.com
> [verisure] Keep refreshing after RuntimeException

- .github/scripts/maven-build
- .github/workflows/ci-build.yml
* Checkout merged branches for pull requests
* Add support for incremental add-on builds to speed up PR builds
* Echo the mvn command used for builds
The incremental build should also work for initial add-on contributions and it will also build everything in just one Maven reactor instead of several which we had with Travis CI. It should also figure out add-on dependencies and dependants using the `-am` and `-amd` options.
> GitHub Actions workflow improvements

- bundles/org.openhab.binding.dwdunwetter/README.md
- Fixed broken link in documentation
> [dwdunwetter] Fixed broken link in documentation

- .github/scripts/maven-build
Fixes the issue that single add-on builds that fail are not marked as such in GitHub Actions.
See for instance this build which should have been marked as "Failure" instead of "Success": https://github.com/openhab/openhab-addons/actions/runs/1426422792
> Fix wrong build result when single add-on build fails

- itests/itest-common.bndrun
- itests/org.openhab.binding.feed.tests/itest.bndrun
- itests/org.openhab.binding.feed.tests/pom.xml
- itests/org.openhab.binding.mielecloud.tests/itest.bndrun
- itests/org.openhab.binding.mielecloud.tests/pom.xml
- itests/pom.xml
It is probably always a good idea to run the OSGi HTTP service on a random available port in itests.
So when this is always done it prevents future issues and removes a bit of duplication.
See also: https://github.com/openhab/openhab-addons/issues/11350
> Always run OSGi HTTP service on random port in itests

- bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/ComponentChannel.java
- bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/ComponentFactory.java
- bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Vacuum.java
Closes #8988
Automatically discovers vacuum robots running on Valetudo (RE) with enabled MQTT
> [mqtt.homeassistant] Implement Vacuum discovery for Homeassistant MQTT

- bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudService.java
- bundles/org.openhab.io.openhabcloud/src/main/resources/OH-INF/config/config.xml
- bundles/org.openhab.io.openhabcloud/src/main/resources/OH-INF/i18n/openhabcloud.properties
@wborn Thanks for adding support in your [i18n plugin](https://github.com/openhab/openhab-core/pull/2544#issuecomment-962652082) to translate other bundles too. Lets try if it is working like expected.
> [openhabcloud] Added default i18n properties file

- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/HueThingHandlerFactory.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/discovery/HueDeviceDiscoveryService.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueBridgeHandler.java
- bundles/org.openhab.binding.hue/src/main/resources/OH-INF/i18n/hue.properties
> [hue] Internationalization of discovery results

- bundles/org.openhab.binding.nuvo/README.md
- bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/NuvoBindingConstants.java
- bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/communication/NuvoConnector.java
- bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/handler/NuvoHandler.java
Signed-off-by: Brian O'Connell <boc-tothefuture@users.noreply.github.com>
fix[nuvo] fixes protocol errors when connecting via an MPS4
This fixes the error when using the Nuvo binding over IP through an MPS4 the binding would be disconnected over and over again.  The MPS4 will disconnect connections when requests are sent and no zones are on. The MPS4 sends a PING command every 10 seconds, this update listens for that ping and if a ping is not received in minute initiates a reconnection if the user has indicated they are using the MPS4.
This issue is noted by another user in the forum [here](https://community.openhab.org/t/nuvo-wha-grand-concerto-mpsv2-binding-disconnecting/119410)
> [nuvo] Fixes protocol errors when connecting via an MPS4

- bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Vacuum.java
While integrating the review comments, I did not remember that some
variable names are written as they are because they result from some
deserialization.
This small PR fixes this.
> [mqtt.homeassistant] Fix MQTT Vacuum serialization names

- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoAbstractHandler.java
- bundles/org.openhab.binding.miio/src/main/resources/OH-INF/binding/binding.xml
- bundles/org.openhab.binding.miio/src/main/resources/OH-INF/config/config.xml
- bundles/org.openhab.binding.miio/src/main/resources/OH-INF/i18n/miio.properties
> [miio] Initial i18n properties file for Xiaomi miio binding

- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueLightHandler.java
- bundles/org.openhab.binding.hue/src/test/java/org/openhab/binding/hue/internal/handler/HueLightHandlerTest.java
Fixes #11571
When **transitiontime** is omitted in the request sent to the bridge for LK Wiser Dimmer and Double Relay, they cannot be turned off. Please see linked issue for more details.
> [hue] Add workaround for LK Wiser products

- bundles/org.openhab.binding.phc/src/main/java/org/openhab/binding/phc/internal/handler/PHCBridgeHandler.java
- bundles/org.openhab.binding.phc/src/main/resources/OH-INF/thing/channel-types.xml
The overdue update / bug fix:
- Remove the advanced option from jrmTime channel group.
The error has probably crept in again with the last correction and newly added JRM things in OH3 no longer worked.
Link to the Community: https://community.openhab.org/t/phc-binding-throwing-exception-on-startup/111774/2
- Support multible commands in one received serial message.
Sometimes modules seem to send commands for several channels in one message.
Link to the Community: https://community.openhab.org/t/switch-from-peha-phc-to-new-automation-with-openhab2/61154/49
Signed-off-by: Jonas Hohaus <jh@gnlpf.net>
> [phc] Fix OH3 bug and add support for multible commands

- bundles/org.openhab.io.openhabcloud/pom.xml
- bundles/org.openhab.io.openhabcloud/src/main/feature/feature.xml
- bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudClient.java
Requires https://github.com/openhab/openhab-osgiify/pull/28
Aiming to resolve issues like openhab/openhab-cloud#134 . Common workaround seems to be to restart the bundle, see https://community.openhab.org/t/myopenhab-service-not-working/121711/5 and https://community.openhab.org/t/connection-to-myopenhab-broken/73808/80.
According to documentation (albeit for 2.x Socket IO version) [1], reconnection is responsibility of the user on connect_error events. Indeed, default implementation ([1.0.0](https://github.com/socketio/socket.io-client-java/blob/45fd4fbdd8401ea63c30f6bbda266afd99df751f/src/main/java/io/socket/client/Manager.java#L248-L253) and [1.0.1](https://github.com/socketio/socket.io-client-java/blob/89ef9d09cee799ffb85e0252bcaf1993f9d49af9/src/main/java/io/socket/client/Manager.java …
> [openhabcloud] reconnect on connection errors

- bom/openhab-core-index/pom.xml
- bom/runtime-index/pom.xml
- bom/test-index/pom.xml
Looks like only the POM dependencies are used by the indexer, so the JAR is unused and useless as this warning correctly indicates when you build them:
```
[WARNING] JAR will be empty - no content was marked for inclusion!
```
> Use POM packaging with index BOMs

- bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/Channel.java
- bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/DanfossAirUnitHandlerFactory.java
- bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/handler/DanfossAirUnitHandler.java
- bundles/org.openhab.binding.danfossairunit/src/main/resources/OH-INF/i18n/danfossairunit.properties
- bundles/org.openhab.binding.danfossairunit/src/main/resources/OH-INF/thing/thing-types.xml
Fixes #11578 
Signed-off-by: Jacob Laursen jacob-github@vindvejr.dk
Also fixes a namespace problem introduced by #11172
> [danfossairunit] Add default i18n properties file

- bundles/org.openhab.automation.jrubyscripting/pom.xml
It was missing the "Bundles" parts like used in other projects.
> [jrubyscripting] Fix Maven project name

- bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/handler/SamsungTvHandler.java
- bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/service/MainTVServerService.java
- bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/service/RemoteControllerService.java
Fixes #7055 
Fixes #7406
Signed-off-by: Jacob Laursen jacob-github@vindvejr.dk
Initially the binding will start RemoteControllerService in non-UPnP mode by calling **createNonUpnpService**.
When device is added, some additional services are started and RemoteControllerService is replaced by new UPnP instance from **createUpnpService**.
When device is removed, the binding would stop all services, including the RemoteControllerService - without restarting the non-UPnP service. This made it unable to detect when device would be added again.
This has been fixed by calling **checkCreateManualConnection** after stopping all services in order to go back to original state listening for devices being added - like after initialize(). See comment in linked issue for additional information.
Tested …
> [samsungtv] Fix reconnect after first connection to TV is lost

- bundles/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/controls/LxControl.java
- bundles/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/controls/LxControlFactory.java
- bundles/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/controls/LxControlSauna.java
- bundles/org.openhab.binding.loxone/src/test/java/org/openhab/binding/loxone/internal/controls/LxControlSaunaDoorTest.java
- bundles/org.openhab.binding.loxone/src/test/java/org/openhab/binding/loxone/internal/controls/LxControlSaunaDoorVaporizerTest.java
- bundles/org.openhab.binding.loxone/src/test/java/org/openhab/binding/loxone/internal/controls/LxControlSaunaTest.java
- bundles/org.openhab.binding.loxone/src/test/java/org/openhab/binding/loxone/internal/controls/LxControlTest.java
- bundles/org.openhab.binding.loxone/src/test/resources/org/openhab/binding/loxone/internal/controls/LoxAPP3.json
This is implementation of sauna controller per Loxone API description https://www.loxone.com/enen/kb/api/
Checked with my installation on GEN2 Miniserver.
Signed-off-by: Pawel Pieczul <pieczul@gmail.com>
> [loxone] Sauna controller implementation

- bundles/org.openhab.binding.monopriceaudio/README.md
- bundles/org.openhab.binding.monopriceaudio/src/main/resources/OH-INF/binding/binding.xml
- bundles/org.openhab.binding.monopriceaudio/src/main/resources/OH-INF/thing/channels.xml
In preparation to release a beta version of this binding to the marketplace which will support additional models, the mainline version is updated via this PR to better identify which models are supported. No functional changes are present in this PR, only documentation and name/label changes are made.
> [monopriceaudio] Clarify supported models and documentation

- bom/openhab-addons/pom.xml
Missing bundles in this BOM can cause issues like:
* Karaf feature projects building before bundle add-on projects completed
* Incremental build issues
* Other projects using the BOM having to manually add dependency management for these bundles
> Add missing bundles to openhab-addons BOM

- bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Vacuum.java
- bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/VacuumTests.java
[MQTT.Homeassistant] make the mqtt.vacuum compliant with the Specification
The mqtt.vacuum HA component has a Specification at https://www.home-assistant.io/integrations/vacuum.mqtt/
The goal of this PR is to make OpenHAB implementation compliant with the Specification, to be sure that any vacuum can be supported by Homeassistant integration out of the box.
I added support for legacy schema and all missing configuration attributes.
Unfortunately, time and usage status attributes are out of specification and they are specific for old valetudo versions only. So, I removed them from implementation. The new valetudo firmware should be supported by Homie binding. Any firmware specific mqtt messages can also be handled by generic mqtt binding.
> [MQTT.Homeassistant] make the mqtt.vacuum compliant

- pom.xml
This is the version used in the feature provided by openhab-core.
Depends on https://github.com/openhab/openhab-core/pull/2572
> Update Jackson version to 2.12.5

- bundles/org.openhab.voice.googletts/README.md
When the docs are generated any {{ }} constructs are substituted with variables causing the place holders to get lost.
As a result the docs are less easy to understand.
> [googletts] Fix place holders issue

- bundles/org.openhab.binding.nest/README.md
When the docs are generated any {{ }} constructs are substituted with variables causing the place holders to get lost.
As a result the docs are less easy to understand.
> [nest] Fix place holders issue

- bundles/org.openhab.binding.amplipi/README.md
- bundles/org.openhab.binding.amplipi/amplipi-api.yml
- bundles/org.openhab.binding.amplipi/src/gen/java/org/openhab/binding/amplipi/internal/model/Announcement.java
- bundles/org.openhab.binding.amplipi/src/gen/java/org/openhab/binding/amplipi/internal/model/GroupUpdateWithId.java
- bundles/org.openhab.binding.amplipi/src/gen/java/org/openhab/binding/amplipi/internal/model/MultiZoneUpdate.java
- bundles/org.openhab.binding.amplipi/src/gen/java/org/openhab/binding/amplipi/internal/model/SourceInfo.java
- bundles/org.openhab.binding.amplipi/src/gen/java/org/openhab/binding/amplipi/internal/model/SourceUpdateWithId.java
- bundles/org.openhab.binding.amplipi/src/gen/java/org/openhab/binding/amplipi/internal/model/ZoneUpdateWithId.java
- bundles/org.openhab.binding.amplipi/src/main/java/org/openhab/binding/amplipi/internal/AmpliPiConfiguration.java
- bundles/org.openhab.binding.amplipi/src/main/java/org/openhab/binding/amplipi/internal/AmpliPiGroupHandler.java
- bundles/org.openhab.binding.amplipi/src/main/java/org/openhab/binding/amplipi/internal/AmpliPiHandler.java
- bundles/org.openhab.binding.amplipi/src/main/java/org/openhab/binding/amplipi/internal/AmpliPiHandlerFactory.java
- bundles/org.openhab.binding.amplipi/src/main/java/org/openhab/binding/amplipi/internal/AmpliPiZoneHandler.java
- bundles/org.openhab.binding.amplipi/src/main/java/org/openhab/binding/amplipi/internal/audio/PAAudioSink.java
- bundles/org.openhab.binding.amplipi/src/main/java/org/openhab/binding/amplipi/internal/discovery/AmpliPiMDNSDiscoveryParticipant.java
- bundles/org.openhab.binding.amplipi/src/main/java/org/openhab/binding/amplipi/internal/discovery/AmpliPiZoneAndGroupDiscoveryService.java
This PR adds the possibility to find the AmpliPi on the local network through mDNS.
Additionally, it now acts as an audio sink, so that audio streams can be sent to it, which are then announced as a PA on all available zones (either with current volume or a specified volume level). This is a great feature for doing announcements in every room, such as doorbell, telephone call notifications etc.
> [amplipi] Add discovery and PA support

- bundles/org.openhab.binding.radiothermostat/README.md
- bundles/org.openhab.binding.radiothermostat/src/main/java/org/openhab/binding/radiothermostat/internal/dto/RadioThermostatTstatDTO.java
- bundles/org.openhab.binding.radiothermostat/src/main/java/org/openhab/binding/radiothermostat/internal/handler/RadioThermostatHandler.java
Fix #11625 
If the thermostat returned a JSON value for the set point that was not a whole number (not ending in .00), the JSON parsing would silently fail and prevent the thermostat channels from updating. The DTO was updated to parse these values as a Double instead of Integer.
Test build available here:
https://github.com/mlobstein/mlobstein-beta-test/raw/master/org.openhab.binding.radiothermostat-3.2.0-SNAPSHOT.jar
> [radiothermostat] Fix JSON thermostat data parsing error

- bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/discovery/AVMFritzUpnpDiscoveryParticipant.java
- bundles/org.openhab.binding.avmfritz/src/main/resources/OH-INF/thing/bridge-types.xml
- Added representation-property to bridge type definitions
> [avmfritz] Add representation-property to bridge type definitions

- bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/api/EnedisHttpApi.java
- bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/handler/LinkyHandler.java
> [linky] Few debug logs added

- bundles/org.openhab.transform.map/src/main/resources/OH-INF/i18n/transform.properties
- Fixed wrong i18n properties and added label of Profile
The i18n properties for Profiles were not created correctly in https://github.com/openhab/openhab-addons/pull/11574. Additional the label of the Profile was not added automatically.
> [transform][map] Fixed wrong i18n properties and added label of Profile

- bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/util/LifxThrottlingUtil.java
When the binding is stopped sleeping threads are interrupted by design.
By throwing the InterruptedException, it should be caught in LifxSelectorUtil.sendPacket (which is waiting for the packet interval to elapse), which will then abort sending a packet.
This prevents:
```
[ERROR] [lifx.internal.util.LifxThrottlingUtil] - An exception occurred while putting the thread to sleep : 'sleep interrupted'
```
> [lifx] Improve InterruptedException handling

- .github/workflows/ci-build.yml
This new version fixes a few regressions, see:
https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12316922&version=12350685
> Use Maven 3.8.4 in GHA CI builds

- CODEOWNERS
- bom/openhab-addons/pom.xml
- bundles/org.openhab.binding.anel/NOTICE
- bundles/org.openhab.binding.anel/README.md
- bundles/org.openhab.binding.anel/pom.xml
- bundles/org.openhab.binding.anel/src/main/feature/feature.xml
- bundles/org.openhab.binding.anel/src/main/java/org/openhab/binding/anel/internal/AnelConfiguration.java
- bundles/org.openhab.binding.anel/src/main/java/org/openhab/binding/anel/internal/AnelHandler.java
- bundles/org.openhab.binding.anel/src/main/java/org/openhab/binding/anel/internal/AnelHandlerFactory.java
- bundles/org.openhab.binding.anel/src/main/java/org/openhab/binding/anel/internal/AnelUdpConnector.java
- bundles/org.openhab.binding.anel/src/main/java/org/openhab/binding/anel/internal/IAnelConstants.java
- bundles/org.openhab.binding.anel/src/main/java/org/openhab/binding/anel/internal/auth/AnelAuthentication.java
- bundles/org.openhab.binding.anel/src/main/java/org/openhab/binding/anel/internal/discovery/AnelDiscoveryService.java
- bundles/org.openhab.binding.anel/src/main/java/org/openhab/binding/anel/internal/state/AnelCommandHandler.java
- bundles/org.openhab.binding.anel/src/main/java/org/openhab/binding/anel/internal/state/AnelState.java
- bundles/org.openhab.binding.anel/src/main/java/org/openhab/binding/anel/internal/state/AnelStateUpdater.java
- bundles/org.openhab.binding.anel/src/main/resources/OH-INF/binding/binding.xml
- bundles/org.openhab.binding.anel/src/main/resources/OH-INF/config/config.xml
- bundles/org.openhab.binding.anel/src/main/resources/OH-INF/thing/thing-types.xml
- bundles/org.openhab.binding.anel/src/test/java/org/openhab/binding/anel/internal/AnelAuthenticationTest.java
- bundles/org.openhab.binding.anel/src/test/java/org/openhab/binding/anel/internal/AnelCommandHandlerTest.java
- bundles/org.openhab.binding.anel/src/test/java/org/openhab/binding/anel/internal/AnelStateTest.java
- bundles/org.openhab.binding.anel/src/test/java/org/openhab/binding/anel/internal/AnelStateUpdaterTest.java
- bundles/org.openhab.binding.anel/src/test/java/org/openhab/binding/anel/internal/AnelUdpConnectorTest.java
- bundles/org.openhab.binding.anel/src/test/java/org/openhab/binding/anel/internal/IAnelTestStatus.java
- bundles/pom.xml
I re-wrote the binding for Anel NET-PwrCtrl devices which only exists for OH1 so far.
It is already tested by some users, see: https://community.openhab.org/t/anel-net-pwrctrl-binding-for-oh3/123378
There are also some unit tests for the core functionality.
The readme explains the usage and gives examples.
> [anel] Initial contribution of the Anel NET-PwrCtrl binding for OH3

- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/miot/MiotParser.java
> [miio] fix Error parsing miot data null for new miot devices

- bundles/org.openhab.binding.miio/README.md
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/Conversions.java
- bundles/org.openhab.binding.miio/src/main/resources/database/chuangmi.plug.212a01-miot.json
- bundles/org.openhab.binding.miio/src/test/java/org/openhab/binding/miio/internal/ConversionsTest.java
> [miio] add support for BT Gateway switch on chuangmi.plug.212a01

- bundles/org.openhab.io.homekit/pom.xml
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitGarageDoorOpenerImpl.java
homekit binding uses Java-HAP library that implements apple homekit protocol. 
as Java-HAP project had very long release cycles, @J-N-K  was creating in the past the openHAB specific releases in order to make latest features available to openHAB.
few months ago, Java HAP project made an official release that incorporates all the changes of @J-N-K  release as well as few minor improvements, e.g. fix of a typo. 
this PR switch OH to the official release of Java-HAP
> [homekit] switch to official Java HAP lib release

- bundles/org.openhab.binding.tplinksmarthome/src/main/resources/OH-INF/thing/KL125.xml
- bundles/org.openhab.binding.tplinksmarthome/src/main/resources/OH-INF/thing/KL135.xml
These are color bulbs and should have the color channel instead of the brightness channel.
Closes #11660
> [tplinksmarthome] Fixed invalid channels in KL125/KL135 definition.

- pom.xml
When the plugin dependency is managed you can also use the plugin without adding GAV parameters to commands.
E.g. it allows for using it with:
```
mvn i18n:generate-default-translations
```
Depends on https://github.com/openhab/openhab-core/pull/2544
> Add i18n-maven-plugin dependency

- bundles/org.openhab.binding.homewizard/src/main/java/org/openhab/binding/homewizard/internal/HomeWizardHandler.java
- bundles/org.openhab.binding.homewizard/src/main/java/org/openhab/binding/homewizard/internal/P1Payload.java
This commit is a bugfix fixes a crash in the HomeWizard add on that happens when the smart meter does not provide gas values. The crash was caused by the empty timestamp.
Signed-off-by: Daniël van Os <daniel@supercell.nl>
> [homewizard] Fix issue with missing gas values

- bundles/org.openhab.binding.nuvo/src/main/resources/OH-INF/thing/channels.xml
Update the thing label name so searching by the model name returns a thing result in the Add-On search page.
> [nuvo] Update thing label for better matching in Add-On search

- bundles/org.openhab.binding.radiothermostat/src/main/resources/OH-INF/thing/thing-types.xml
Update the thing label name so searching by the thermostat model name returns a thing result in the Add-On search page.
> [radiothermostat] Update thing label for better matching in Add-On search

- bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/AVMFritzBindingConstants.java
- bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/AVMFritzHandlerFactory.java
- bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/discovery/AVMFritzUpnpDiscoveryParticipant.java
- bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/Powerline546EHandler.java
- itests/org.openhab.binding.avmfritz.tests/src/main/java/org/openhab/binding/avmfritz/internal/discovery/AVMFritzDiscoveryServiceOSGiTest.java
- Exclude other Powerline products from discovery as only 546E is supported by the binding
See https://community.openhab.org/t/support-of-avm-fritz-powerline-540e/128672
> [avmfritz] Exclude other Powerline products from discovery

- bundles/org.openhab.binding.logreader/src/main/resources/OH-INF/thing/channels.xml
- Added pattern for DateTime channel types
> [logreader] Added pattern for DateTime channel types

- bundles/org.openhab.binding.chromecast/README.md
- bundles/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/discovery/ChromecastDiscoveryParticipant.java
- Added configuration flag to disable background discovery
> [chromecast] Added configuration flag to disable background discovery

- bundles/org.openhab.binding.homeconnect/README.md
- bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/HomeConnectBindingConstants.java
Allow to control oven via binding. It is now possible to control the oven without an additional agreement (start the program, etc.
Signed-off-by: Jonas Brüstel <jonas@bruestel.net>
> [homeconnect] Add oven control

- bundles/org.openhab.binding.sleepiq/src/3rdparty/java/org/openhab/binding/sleepiq/api/SleepIQ.java
- bundles/org.openhab.binding.sleepiq/src/3rdparty/java/org/openhab/binding/sleepiq/api/impl/SleepIQImpl.java
- bundles/org.openhab.binding.sleepiq/src/3rdparty/java/org/openhab/binding/sleepiq/api/model/TimeSince.java
- bundles/org.openhab.binding.sleepiq/src/main/java/org/openhab/binding/sleepiq/internal/SleepIQHandlerFactory.java
- bundles/org.openhab.binding.sleepiq/src/main/java/org/openhab/binding/sleepiq/internal/handler/SleepIQCloudHandler.java
Fixes #11696 
There are a lot of automatically applied formatting changes in `SleepIQImpl.java`. The relevant changes are at the bottom of the change list.
> [sleepiq] Use constructor injection for ClientBuilder

- bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/discovery/OpenWebNetDeviceDiscoveryService.java
- bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetBridgeHandler.java
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/i18n/openwebnet.properties
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/i18n/openwebnet_hu.properties
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/i18n/openwebnet_it.properties
This PR fixes #11582: while discovering devices on local bus the where parameter is now set correctly, not using normalizeWhere().
In addition this PR adds translations string for `it ` locale.
> [openwebnet] Fixes discovery of devices on local bus. Added it translation

- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewHubHandler.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewShadeHandler.java
- bundles/org.openhab.binding.hdpowerview/src/main/resources/OH-INF/i18n/hdpowerview.properties
Fixes #11702
Shade things are initially incorrectly marked as offline with communication error, even after receiving the first update from the bridge handler. Only after one minute are they marked as online again.
> [hdpowerview] Fix initialization of shade handler

- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitImpl.java
this PR:
- add listener to network changes and restart HomeKit bridge on changes. This will recover HomeKit bridge after network connection losses and IP address changes. this will fix the issue reported here https://community.openhab.org/t/oh3-homekit-bug-fails-after-network-down-up/
- make logger messages consistent with small letter.
> [homekit] restart HomeKit bridge on network changes

- bundles/org.openhab.binding.miio/README.md
- bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.airpurifier.vb2-miot.json
> [miio] Fix zhimi.airpurifier.vb2 channel unit

- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/IPBridgeHandler.java
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/protocol/lip/Monitoring.java
Update to ipbridge to explicitly enable the proper monitoring types for HomeWorks LIP connections at connection init time.
Closes #11604
> [lutron] Explicitly enable proper monitoring types for HomeWorks connections

- bundles/org.openhab.binding.hpprinter/src/main/java/org/openhab/binding/hpprinter/internal/api/HPProductUsageFeatures.java
- bundles/org.openhab.binding.hpprinter/src/main/java/org/openhab/binding/hpprinter/internal/api/HPStatus.java
- bundles/org.openhab.binding.hpprinter/src/main/resources/OH-INF/thing/channel-types.xml
This changes how both the status channels work. Originally, they referenced a hash table with the name of the status value. It seems more appropriate to have these as state description options as it would allow the statuses to be localised.
> [hpprinter] Change status channel from hash map values to state description options.

- bundles/org.openhab.binding.nzwateralerts/src/main/java/org/openhab/binding/nzwateralerts/internal/api/SmartWater.java
Small fix for smartwater.org.nz displaying a new image when water needs to be conserved (restriction season). This tweak will fix `UNDEF` (it should be `0`).
> [nzwateralerts] Fix smart water alert level.

- bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc2/NikoHomeControlCommunication2.java
Closes #11695
The sequence of on/off and brightness commands and status updates caused flickering with lamps on other binding channels following the binding channels. This fix adjusts the sequence to avoid setting the wrong brightness value for a short instance before setting the correct value.
> [nikohomecontrol] Fix dimmer control sequence

- bundles/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/protocol/PowerInformationResponseMessage.java
This fixes the issue that the 'power' channel would not update with the correct state because the number of pulses in the `PowerInformationResponseMessage` is signed instead of unsigned.
When the binding detected these strange readings it would normally log: "Circle (...) is in a kind of error state ...".
See also: https://community.openhab.org/t/plugwise-cirle-connected-to-pv-panel-gives-no-power-data-in-oh3/123001
> [plugwise] Fix 'power' channel not correctly updated with power production

- bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/scope/SharedCache.java
Add a very basic shared cache into the JS add-on to allow JS scripts to cache objects between runs and/or scripts.
Signed-off-by: Jonathan Gilbert <jpg@trillica.com>
> [jsscripting] Added simple Shared Cache into scope

- bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/dto/response/HueSuccessResponseStateChanged.java
- bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/rest/LightsAndGroupsTests.java
Fixes the following problem mentioned in #10691 :
- In HueSuccessResponseStateChanged.java the serializer for lists is missing, so when setting xy the response is missing that it changed xy
> Hueemulation: Fix xy change response

- CODEOWNERS
- bom/openhab-addons/pom.xml
- bundles/org.openhab.binding.dominoswiss/NOTICE
- bundles/org.openhab.binding.dominoswiss/README.md
- bundles/org.openhab.binding.dominoswiss/pom.xml
- bundles/org.openhab.binding.dominoswiss/src/main/feature/feature.xml
- bundles/org.openhab.binding.dominoswiss/src/main/java/org/openhab/binding/dominoswiss/internal/BlindConfig.java
- bundles/org.openhab.binding.dominoswiss/src/main/java/org/openhab/binding/dominoswiss/internal/BlindHandler.java
- bundles/org.openhab.binding.dominoswiss/src/main/java/org/openhab/binding/dominoswiss/internal/DominoswissBindingConstants.java
- bundles/org.openhab.binding.dominoswiss/src/main/java/org/openhab/binding/dominoswiss/internal/DominoswissConfiguration.java
- bundles/org.openhab.binding.dominoswiss/src/main/java/org/openhab/binding/dominoswiss/internal/DominoswissHandlerFactory.java
- bundles/org.openhab.binding.dominoswiss/src/main/java/org/openhab/binding/dominoswiss/internal/EGateHandler.java
- bundles/org.openhab.binding.dominoswiss/src/main/resources/OH-INF/binding/binding.xml
- bundles/org.openhab.binding.dominoswiss/src/main/resources/OH-INF/i18n/dominoswiss_de_DE.properties
- bundles/org.openhab.binding.dominoswiss/src/main/resources/OH-INF/thing/thing-types.xml
- bundles/pom.xml
Added new Binding "org.openhab.binding.dominoswiss" for a first initial commit of this binding
[dominoswiss][WIP] initial contribution
added new binding org.openhab.binding.dominoswiss for initial commit
This binding allows the controll of rollershutters, using an egate as gateway and dominoswiss radio receivers. The egate-gateway is connectet via ethernet to openhab and sends it's commands via radio to all rollershutters.
Announcement: https://community.openhab.org/t/announce-dominoswiss-binding/76503
Replaces Pull-Request https://github.com/openhab/openhab-addons/pull/9837
Jar-File for Testing:
https://github.com/Friesoch/org.openhab.binding.dominoswiss
> [dominoswiss] Initial contribution

- bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/ConvertedInputStream.java
- bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/PulseAudioAudioSink.java
Add a pass to reencode PCM sound in 16 bit, 44100 hz, 2 channels, before sending it to the pulseaudio audio sink, to play it correctly.
And I moved the MP3 reencoding code to a new class, alongside the new resampling.
Close #11630
> [pulseaudio] Add reencoding to play more audio formats (#11630)

- bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/handler/HomematicThingHandler.java
Issue described and tested in https://community.openhab.org/t/homematic-binding-channel-not-found-for-datapoint-errors-for-definitely-existing-channels/26209/113 
Fixes: #11214
Signed-off-by: Flole <flole@flole.de>
> [Homematic] Fix "Channel not found for Datapoint"-Errors

- bundles/org.openhab.persistence.jdbc/README.md
- bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcBaseDAO.java
- bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcTimescaledbDAO.java
- bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcConfiguration.java
Signed-off-by: Riccardo Nimser-Joseph <github@nimric.de>
[jdbc] Add support for TimescaleDB
JDBC persistence writes and reads item states to and from a number of relational database systems that support Java Database Connectivity (JDBC). Since the stored data are time-series, a specialized database can provide an accelerated performance.
> [jdbc] Add support for TimescaleDB (#11090)

- bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/AbstractMQTTThingHandler.java
- bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/handler/GenericMQTTThingHandler.java
- bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/internal/handler/GenericThingHandlerTests.java
This is a Patch Proposal for #9850. It is the "easy" variant of the fix; the major design flaws in classes `AbstractMQTTThingHandler` and `GenericMQTTThingHandler` (especially regarding availability topics) are not addressed.
A Unit Test is included.
> [mqtt] Fix availability topics subscription after Brige Restart

- bundles/org.openhab.transform.exec/src/main/resources/OH-INF/config/execProfile.xml
- bundles/org.openhab.transform.exec/src/main/resources/OH-INF/i18n/exec.properties
- bundles/org.openhab.transform.javascript/src/main/resources/OH-INF/config/javascriptProfile.xml
- bundles/org.openhab.transform.javascript/src/main/resources/OH-INF/i18n/js.properties
- bundles/org.openhab.transform.jinja/src/main/resources/OH-INF/config/jinjaProfile.xml
- bundles/org.openhab.transform.jinja/src/main/resources/OH-INF/i18n/jinja.properties
- bundles/org.openhab.transform.jsonpath/src/main/resources/OH-INF/config/jsonpathProfile.xml
- bundles/org.openhab.transform.jsonpath/src/main/resources/OH-INF/i18n/jsonpath.properties
- bundles/org.openhab.transform.regex/src/main/resources/OH-INF/config/regexProfile.xml
- bundles/org.openhab.transform.regex/src/main/resources/OH-INF/i18n/regex.properties
- bundles/org.openhab.transform.scale/src/main/resources/OH-INF/config/scaleProfile.xml
- bundles/org.openhab.transform.scale/src/main/resources/OH-INF/i18n/scale.properties
- bundles/org.openhab.transform.xpath/src/main/resources/OH-INF/config/xpathProfile.xml
- bundles/org.openhab.transform.xpath/src/main/resources/OH-INF/i18n/xpath.properties
- bundles/org.openhab.transform.xslt/src/main/resources/OH-INF/config/xsltProfile.xml
- bundles/org.openhab.transform.xslt/src/main/resources/OH-INF/i18n/xslt.properties
This makes the texts used by these add-ons translatable with Crowdin.
> Add default translations for transform add-ons

- bundles/org.openhab.persistence.dynamodb/src/main/resources/OH-INF/i18n/dynamodb.properties
- bundles/org.openhab.persistence.influxdb/src/main/resources/OH-INF/i18n/influxdb.properties
- bundles/org.openhab.persistence.jdbc/src/main/resources/OH-INF/i18n/jdbc.properties
This makes the texts used by these add-ons translatable with Crowdin.
> Add default translations for persistence add-ons

- bundles/org.openhab.binding.homematic/README.md
- bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/HomematicBindingConstants.java
- bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/common/HomematicConfig.java
- bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/AbstractHomematicGateway.java
- bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/client/BinRpcClient.java
- bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/client/RpcClient.java
- bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/client/XmlRpcClient.java
- bundles/org.openhab.binding.homematic/src/main/resources/OH-INF/thing/bridge.xml
The PR improves the connect and especially the re-connect handling to Homematic gateways through the following measures:
1. by using a global unique id for each bridge installation it is possible to use two or more OH installation with the same Homematic gateway in parallel.
2. the HmIP daemon normally need much longer than the HM daemon until it accepts event registration. Therefore a configurable retry mechanismn has been implemented.
> [homematic] Improve (re)connect handling to Homematic gateways

- bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/NikoHomeControlConstants.java
- bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc2/NhcAction2.java
- bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc2/NikoHomeControlCommunication2.java
Closes #11740
Virtual flags are now directly visible in OH, without needing a workaround of creating free start/stop actions in NHC.
> [nikohomecontrol] Added ability to directly use virtual flags as switches

- bundles/org.openhab.binding.ipcamera/README.md
- bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/DahuaHandler.java
- bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/Ffmpeg.java
- bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/Helper.java
- bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/HikvisionHandler.java
- bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/IpCameraBindingConstants.java
- bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/handler/IpCameraHandler.java
- bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/onvif/OnvifConnection.java
- bundles/org.openhab.binding.ipcamera/src/main/resources/OH-INF/thing/thing-types.xml
+ Add a new channel to Hikvision and Dahua things that allows you to get extra detail on smart alarms that the cameras have. This allows you to determine which line is crossed if the camera has multiple line crossing alarms setup and much more.
+ Bug fix for Dahua audio alarms as newer firmwares appear to use a different event code to older firmwares.
close #11391
> [ipcamera] Add new channel lastEventData for detailed extra data on alarms

- bundles/org.openhab.binding.knx/pom.xml
- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/AbstractKNXClient.java
- Upstream update of base library for KNX access from v2.4 to v2.5.
- Adapt AbstractKNXClient to new interface and replace calls of deprecated
methods.
Fixes #6849.
> [knx] Upgrade Calimero library to release 2.5.

- bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/discovery/BusGatewayUpnpDiscovery.java
Closes #11701 by changing 2 log messages to DEBUG level.
> [openwebnet] reduced log messages during UPnP bridge discovery

- bundles/org.openhab.binding.openwebnet/README.md
- bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/OpenWebNetBindingConstants.java
- bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/discovery/OpenWebNetDeviceDiscoveryService.java
- bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetScenarioHandler.java
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusCENPlusScenarioControl.xml
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusCENScenarioControl.xml
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusDryContactIR.xml
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/GenericDevice.xml
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/channels.xml
- bundles/org.openhab.binding.openwebnet/src/test/java/org/openhab/binding/openwebnet/internal/handler/OwnIdTest.java
This PR is an enhancement for the openwebnet binding to add support for Dry Contact and IR interfaces (WHO=25), like 3477 and F428.
Closes #11488.
This function is really useful to know the state of external systems via a dry contact, or to execute scenarios based on IR-detected movements (ON=presence, OFF=no presence). For example, if a dry contact interface is used to detect an intrusion on a window, this device can be used to know the status of the windows: opened / closed.
Community thread (Marketplace): https://community.openhab.org/t/openwebnet-binding-support-for-dry-contact-and-ir-interfaces-alpha/129775
> [openwebnet] Add support for Dry Contact and IR interfaces for WHO=25

- bundles/org.openhab.io.homekit/src/main/resources/OH-INF/i18n/homekit.properties
- bundles/org.openhab.io.hueemulation/src/main/resources/OH-INF/i18n/hueemulation.properties
- bundles/org.openhab.io.metrics/src/main/java/org/openhab/io/metrics/MetricsRestController.java
- bundles/org.openhab.io.metrics/src/main/resources/OH-INF/i18n/metrics.properties
- bundles/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/NeeoService.java
- bundles/org.openhab.io.neeo/src/main/resources/OH-INF/i18n/neeo.properties
This makes the texts used by these add-ons translatable with Crowdin.
> Add default translations for io add-ons

- bundles/org.openhab.transform.javascript/README.md
- bundles/org.openhab.transform.javascript/src/main/java/org/openhab/transform/javascript/internal/JavaScriptEngineManager.java
- bundles/org.openhab.transform.javascript/src/main/java/org/openhab/transform/javascript/internal/JavaScriptTransformationService.java
- bundles/org.openhab.transform.javascript/src/main/resources/OH-INF/config/javascriptProfile.xml
- bundles/org.openhab.transform.javascript/src/test/java/org/openhab/transform/javascript/internal/JavaScriptTransformationServiceTest.java
> [js-transform] inline java script support

- bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/GraalJSScriptEngineFactory.java
- bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/OpenhabGraalJSScriptEngine.java
- bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/fs/watch/JSDependencyTracker.java
- bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/fs/watch/JSScriptFileWatcher.java
This change modifies the 'new' GraalJS plugin to monitor `<openHAB-conf>/automation/js for scripts`, with libraries in `<openHAB-conf>/automation/js/node_modules` - as per NodeJS standard spec.
It also removes itself from monitoring the original `automation/jsr233/javascript/*` directories, and instead leaves this for Nashorn. This allows users to move scripts over to GraalJS from Nashorn one-by-one.
Note that this change **breaks any ES6+ scripts which are in automation/jsr233/javascript/\* directories**. These will need to be moved to `automation/js`.
Note also that this PR depends on https://github.com/openhab/openhab-core/pull/2593 which enables it to use it's own script directory.
Signed-off-by: Jonathan Gilbert <jpg@trillica.com>
> GraalJS now uses automation/js

- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/MieleBridgeHandler.java
Fixes #11781
Full requests and responses are logged as log level **DEBUG**. This makes log level **DEBUG** almost unusable as it's completely spammed with requests all the time. This pull request reduces log level to **TRACE**.
> [miele] Reduce log level to TRACE for request/response logging

- bundles/org.openhab.binding.omnikinverter/README.md
- bundles/org.openhab.binding.omnikinverter/src/main/java/org/openhab/binding/omnikinverter/internal/OmnikInverterBindingConstants.java
- bundles/org.openhab.binding.omnikinverter/src/main/java/org/openhab/binding/omnikinverter/internal/OmnikInverterMessage.java
- bundles/org.openhab.binding.omnikinverter/src/main/java/org/openhab/binding/omnikinverter/internal/handler/OmnikInverterHandler.java
- bundles/org.openhab.binding.omnikinverter/src/main/resources/OH-INF/thing/thing-types.xml
- bundles/org.openhab.binding.omnikinverter/src/test/java/org/openhab/binding/omnikinverter/internal/test/OmnikInverterMessageTest.java
Novel Addition: Add multiple channels for:
- input voltage for string 1,2, and 3
- input current for string 1, 2  and 3
- output power for feed 2 and 3 as well 
These data was always already in the network packet returned by the inverter, so no new retrieval code was necessary, only extra decoding of the binary packet coming from the inverter. 
For the reviewer:
>Please keep the following in mind:
> - Did you describe new features for the end user?
Is this other than the README.md?
> - Did you describe any noteworthy changes in usage for the end user?
Is this other than the README.md?
> - Was the documentation updated accordingly, e.g. the add-on README?
> [omnikinverter] feature: Add channels for voltage and current

- bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/api/WledApiV084.java
Because colours come from RGB values the controls were jumping to the colour that was set and then jumping to OFF as the binding was parsing the two values separately. This PR fixes it so the event.log only shows the channel getting the off state and not a HSB that is on, followed by an OFF.
> [wled] Fix two events being logged when light is off.

- bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/WLedConfiguration.java
- bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/WLedHandler.java
- bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/api/WledApiV084.java
- bundles/org.openhab.binding.wled/src/main/resources/OH-INF/thing/thing-types.xml
As discussed in the forum, it would be nice to have the state options for the channels "effects" and "palettes" sorted like they are in the WLED mobile app, i.e. the first option at the top and the rest alphabetically. This PR adds two thing options that allows to enable exactly that on both channels separately.
https://community.openhab.org/t/mainui-sorting-choices-provided-by-thing-channel/129883/5?u=lordjaxom
This allows for displaying the channels' state options in a sorted list in the various UIs without having to maintain that list manually by adding state option metadata to items.
> [wled] add configuration to sort state options of channels

- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewHubHandler.java
Fixes #11778
Regression of #11637
> [hdpowerview] Fix deprecated channels on reinitialization

- bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/AVMFritzBaseThingHandler.java
- bundles/org.openhab.binding.avmfritz/src/test/java/org/openhab/binding/avmfritz/internal/dto/AVMFritzDeviceListModelTest.java
- Fixed update of data for blinds
See https://community.openhab.org/t/avmfritz-support-for-han-fun-dect-ule-devices/38950/31
Has been introduced with https://github.com/openhab/openhab-addons/pull/11348.
> [avmfritz] Fixed update of data for blinds

- bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/AVMFritzBaseThingHandler.java
This is a bug fix for issue #11789. It prevents the AVMFritzBaseThingHandler from attempting to set the (non-existing) brightness channel for HAN-FUN blinds.
Signed-off-by: Ulrich Mertin <mail@ulrich-mertin.de>
> [avmfritz] Prevent attempt to set brightness of blinds

- bundles/org.openhab.binding.irobot/README.md
- bundles/org.openhab.binding.irobot/src/main/java/org/openhab/binding/irobot/internal/dto/MQTTProtocol.java
- bundles/org.openhab.binding.irobot/src/main/java/org/openhab/binding/irobot/internal/handler/RoombaHandler.java
Hello,
I bought a new iRobot Roomba i7. But I encountered the problem, the robot couldn't clean rooms nor zones defined in the iRobot app. See: #11340
I tested the code with the iRobot firmware 3.18.11 (currently up to date). The changes seem to work fine.
This PR replaces https://github.com/openhab/openhab-addons/pull/11413 as this PR has gone mad, don't know what happened.
@lolodomo This pull request contains the same changes as in 11413. Thanks a lot for your patience.
Regards,
Nuesel
> iRobot zone support added

- bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/WLedHandler.java
WLED has a global on/off as well as each lightglobe (aka segment) has an individual on/off control. This fixes an issue when the sleep timer has turned the global control OFF and you wish to turn one of the lights ON or you ask Google/Alexa to turn the light on. Google will reply the light has been turned on, yet the light stays off. This fix makes it behave as expected.
> [wled] Fix global OFF blocks lights turning on via the masterControls

- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoBasicHandler.java
> [miio] fix action channel miot for empty input with parameters

- bundles/org.openhab.binding.chromecast/README.md
- bundles/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromecastCommander.java
- bundles/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromecastStatusUpdater.java
[chromecast] Next Command Support
Add support for next command to chromecast binding, this is implemented by seeking to the end of the current track as there is no native next command.  This is the same implementation for next that the python library uses for chromecast, which is used by home assistant to achieve this functionality.
> [chromecast] Added support for next command

- bundles/org.openhab.binding.lgtvserial/src/main/java/org/openhab/binding/lgtvserial/internal/handler/LgTvSerialHandler.java
- bundles/org.openhab.binding.lgtvserial/src/main/java/org/openhab/binding/lgtvserial/internal/protocol/serial/LGSerialCommunicator.java
I tried to fix bugs mentioned in #8646 about the problems to be able to send command to LG tv through serial port.
In previous versions of openHab <=2.4 the binding runs succesfully and can send commands to tv. But after upgrading openHAB, it didn't work anymore.
After debugging original component, I detected two bugs.
1. channellinked function is never called, as mentioned for example in openHAB core repo #https://github.com/openhab/openhab-core/issues/1707 . Resulting in a null command because the commands list is empty. This is fixed in initalization as explained in the issue
2. reading from serial ports hangs the thread. After channel initalization, the binding sends a command to retrieve the status (for example, if the tv is powered on or off) and then, reads the serial port to get …
> [lgtvserial] Fixes #8646 - fix binding for recent openHab versions

- bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/OpenhabGraalJSScriptEngine.java
Lets try this again, Fixes #11801
> [jsscripting] Support non unix file paths

- itests/org.openhab.binding.astro.tests/itest.bndrun
- itests/org.openhab.binding.avmfritz.tests/itest.bndrun
- itests/org.openhab.binding.feed.tests/itest.bndrun
- itests/org.openhab.binding.hue.tests/itest.bndrun
- itests/org.openhab.binding.max.tests/itest.bndrun
- itests/org.openhab.binding.mielecloud.tests/itest.bndrun
- itests/org.openhab.binding.modbus.tests/itest.bndrun
- itests/org.openhab.binding.nest.tests/itest.bndrun
- itests/org.openhab.binding.ntp.tests/itest.bndrun
- itests/org.openhab.binding.systeminfo.tests/itest.bndrun
- itests/org.openhab.binding.tradfri.tests/itest.bndrun
- itests/org.openhab.binding.wemo.tests/itest.bndrun
- itests/org.openhab.persistence.mapdb.tests/itest.bndrun
- pom.xml
* Syncs the karaf.version so the new Maven plugin is used
* Resolves itest runbundles for the new runtime dependencies
---
Related to openhab/openhab-distro#1344
> Upgrade to Karaf 4.3.4

- bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/api/WledApiV084.java
Fixes a bug where the global on/off control is not reflected in each light/segments true state.
> [wled] Fix Global OFF not turning lights/segments off.

- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/HDPowerViewWebTargets.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewHubHandler.java
When triggering a scene or scene group, some shades will have new positions. These new positions are available in the hub immediately after triggering the scene or scene group, i.e. before the shades will reach those new positions.
Previously it would take up to one minute to have the positions refreshed. Now it will happen a few seconds after the scene or scene group has been triggered.
Fixes #11697
Before change:
```
2021-12-12 21:26:42.228 [INFO ] [openhab.event.ItemCommandEvent      ] - Item 'PowerViewHub_Scene_Office_Up' received command ON
2021-12-12 21:27:08.782 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Blind9_Position' changed from 100 to 0
```
After change:
```
2021-12-12 21:50:22.834 [INFO ] …
```
> [hdpowerview] Update positions after triggering scene/scene group

- pom.xml
PR made to the core repo that is also needed.
https://github.com/openhab/openhab-core/pull/2634
Nettys news/change log is here:
https://netty.io/news/2021/12/13/4-1-72-Final.html
Contains an update to log4j2 2.15.0 to fix security issue.
> Bump netty to 4.1.72.Final for log4j2 2.15.0 fix

- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/HDPowerViewWebTargets.java
Fixes #11856
Unfortunately #11534 has caused a regression in 3.2 since scene collection URL's were renamed in Hunter Douglas PowerView Hub v2.
This pull request is a limited version of #11853 fixing only the needed lines for Hub v1 compatibility and preserving scene group support for both Hub versions.
If there will be a branch for 3.2.x hotfixes, this PR would be a candidate.
> [hdpowerview] Fix support for PowerView Hub v1

- pom.xml
Reverts openhab/openhab-addons#11826
> Revert "Bump netty to 4.1.72.Final for log4j2 2.15.0 fix"

- bundles/org.openhab.binding.boschshc/src/main/resources/OH-INF/i18n/boschshc.properties
This makes more texts translatable which helps to prevent some translations from being removed in #11832.
> [boschshc] Add default translations

- bundles/org.openhab.binding.tellstick/pom.xml
- pom.xml
Bumping netty to 4.1.72.Final as it contains a log4j2 fix. This PR contains an extra line that allows telstick binding to compile with the newer Netty.
Core changes are also needed in separate PR here:
https://github.com/openhab/openhab-core/pull/2648
Christmas time here is nuts :) Merry Christmas to all...
> Bump netty to 4.1.72.Final for log4j2 fix TELSTICK FIXED

- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/discovery/MieleMDNSDiscoveryParticipant.java
- bundles/org.openhab.binding.miele/src/main/resources/OH-INF/i18n/miele.properties
Brought back some minor stashed refactoring done while investigating #11837, which was fixed by openhab/openhab-core#2635 and #11834:
- Added nullness annotations, and with that fixed: _Unsafe null type conversion (type annotations)_
- Fixed warning: _The import org.openhab.core.config.discovery.mdns.internal.MDNSDiscoveryService is never used_
- Fixed error handling problem that could lead to discovery result without any properties.
- Localized discovery result label.
- Simplified some code by having constants on left-side.
- Reduced nesting.
- Reduce log level from **error** to **warning** when failing to create discovery result.
> [miele] Refactor mDNS discovery

- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitCharacteristicFactory.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitHeaterCoolerImpl.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitLightSensorImpl.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitTemperatureSensorImpl.java
a characteristic can have min value, defined either by HAP standard or via openHAB configuration, different to 0.
the current implementation was returning 0 in case openHAB item state is null, independent of defined min value. 
this PR make sure that min value is returned in such cases.  
fix for https://github.com/openhab/openhab-addons/issues/9722
> [homekit] return min value of characteristic instead of 0

- bundles/org.openhab.binding.mystrom/src/main/java/org/openhab/binding/mystrom/internal/AbstractMyStromHandler.java
- bundles/org.openhab.binding.mystrom/src/main/java/org/openhab/binding/mystrom/internal/MyStromBulbHandler.java
- bundles/org.openhab.binding.mystrom/src/main/java/org/openhab/binding/mystrom/internal/MyStromPlugHandler.java
closes #10432
If the request to "http://[Switch IP]/api/v1/info" fails (not supported by first generatino of plug), it will not prevent the plug from working because it does not require any information. For the Bulb, the information "mac" is required. With this Thing, it will fail as before.
https://github.com/openhab/openhab-addons/issues/10432
https://community.openhab.org/t/mystrom-smart-plugs-with-firmware-2-68-not-work-in-oh3/124427/6
Signed-off-by: Frederic Chastagnol <fchastagnol@fredoware.ch>
> [myStrom] Request info is not supported by the first generation of plug

- bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/handler/NanoleafControllerHandler.java
- bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/handler/NanoleafPanelHandler.java
- bundles/org.openhab.binding.nanoleaf/src/main/resources/OH-INF/i18n/nanoleaf.properties
- bundles/org.openhab.binding.nanoleaf/src/main/resources/OH-INF/i18n/nanoleaf_de.properties
- do not go from INITIALIZING to OFFLINE and then ONLINE, but skip OFFLINE for panels, if the controller is ONLINE
- reduce logging to debug when receiving trigger events
- only update Thing configuration if necessary to avoid Thing updated events
- fix description of model types, which was outdated due to new models being available by now
Signed-off-by: Kai Kreuzer <kai.kreuzer@telekom.de>
> [nanoleaf] Various small enhancements

- bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/YeelightHandlerFactory.java
- bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/device/DeviceFactory.java
- bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/services/DeviceManager.java
- bundles/org.openhab.binding.yeelight/src/test/java/org/openhab/binding/yeelight/internal/YeelightHandlerFactoryTest.java
Hi,
this PR fixes discovery of ceiling3 devices, which are being recognized as standard ones - without the night mode feature.
Ceiling3 devices have night mode as well as ceiling1 devices...
Thanks.
Ondrej
> [yeelight] Fixed ceiling3 device being recognized as device without night mode

- bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/i18n/shelly.properties
- bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/i18n/shelly_de.properties
This fixes the comment showing up in the translations.
The code seems to use the 'message.discovery.failed' instead of 'discovery.failed'.
> [shelly] Fix comment in translations file

- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyHttpApi.java
This patch avoid a ClassCastException that prohibited the creation of sensor channels for a Shelly Sense device.
Fixes #11886
> [shelly] Small patch to avoid ClassCastException

- bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/model/Season.java
- bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/util/DateTimeUtils.java
- bundles/org.openhab.binding.astro/src/test/java/org/openhab/binding/astro/internal/util/DateTimeUtilsTest.java
Season timeleft calculated the wrong time at the end of the year, because the seasons it measures the time with are the seasons within the same year. So for times at the end of the year it computed against the season at the beginning of the year, resulting in negative number of days.
Also changed the time of timeLeft to actual days instead of quantity unit days. Because with the milliseconds internal resolution it will generate events each and every time this channel is updated as milliseconds change often.
Closes  #11859
> [astro] Fixed timeLeft calculation at the end of the year

- bundles/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromecastStatusUpdater.java
- Prevent errors in log when URI host is null
See https://github.com/openhab/openhab-core/issues/2494#issuecomment-970162025
```
2021-12-30 10:27:03.868 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.IllegalArgumentException: Invalid URI host: null (authority: null)
at org.eclipse.jetty.client.HttpClient.checkHost(HttpClient.java:521) ~[?:?]
at org.eclipse.jetty.client.HttpClient.newHttpRequest(HttpClient.java:506) ~[?:?]
at org.eclipse.jetty.client.HttpClient.newRequest(HttpClient.java:464) ~[?:?]
at org.eclipse.jetty.client.HttpClient.newRequest(HttpClient.java:453) ~[?:?]
at org.openhab.core.io.net.http.HttpUtil.executeUrlAndGetReponse(HttpUtil.java:212) ~[?:?]
at org.openhab.core.io.net.http.HttpUtil.downloadData(HttpUtil.java:43 …
```
> [chromecast] Prevent errors in log when URI host is null

- bundles/org.openhab.binding.icalendar/src/main/java/org/openhab/binding/icalendar/internal/handler/PullJob.java
> [iCalendar] Fix httpclient getting stuck with broken requests

- bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/config/config.xml
- bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/i18n/rotel.properties
- bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/channels.xml
Also reorder properties by running mvn i18n:generate-default-translations
> [rotel] Fix default properties

- bundles/org.openhab.binding.hdpowerview/README.md
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewShadeHandler.java
Fixes #11932
As natural evolution after:
- #11155
- #11201 
- #11206
- #11260
we should hard-refresh battery level also when receiving REFRESH command.
> [hdpowerview] Refresh battery level when receiving refresh command

- bundles/org.openhab.binding.cbus/src/main/java/org/openhab/binding/cbus/internal/CBusThreadPool.java
Fixes #11845
After changes in 3.2 to the ThreadPool implementation the return from getpool can no longer be cast to ThreadPoolExecutor.
Changing this to ExecutorService fixes this problem and the binding works again.
> [cbus] fix exception from threadpool at startup

- bundles/org.openhab.binding.luxtronikheatpump/src/main/java/org/openhab/binding/luxtronikheatpump/internal/LuxtronikHeatpumpHandler.java
Fixes an issue introduced with https://github.com/openhab/openhab-addons/pull/11860
The new "unknown" channels are all using the same channel type. When a new thing is created the channels are rebuilt based on the available channels. Before the channel id and the channel type were always the same. This fails for the new channels. 
This PR should fix this.
See https://github.com/openhab/openhab-addons/pull/11860#issuecomment-1003620849
> [LuxtronikHeatpump] fix channel type of newly defined unknown channels

- bundles/org.openhab.binding.hdpowerview/README.md
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/HDPowerViewWebTargets.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/responses/Survey.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewShadeHandler.java
Fixes #11942
Channel **signalStrength** was added by #11198 while #11933 refactored the _REFRESH_ command for shades to be relative to channel for requested item. The missing piece now is the **signalStrength** channel which currently cannot be refreshed on request.
This pull request makes the _REFRESH_ command for shades feature complete as each channel now has a dedicated method assigned for requesting a hard refresh for the item context.
Tested with both negative result:
```
2022-01-03 00:52:58.796 [TRACE] [rview.internal.HDPowerViewWebTargets] - JSON response = null
2022-01-03 00:52:58.800 [WARN ] [rnal.handler.HDPowerViewShadeHandler] - No response from shade 36321 survey
```
and positive result:
```
2022-01-03 00:54:21.764 …
```
> [hdpowerview] Support refresh command for signal strength channel

- bundles/org.openhab.binding.heos/README.md
The old reference to Denon HEOS CLI documentation was outdated and is not available anymore. Updating link to latest version.
Thanks for great work!
Michael
> [Denon HEOS] Update Denon CLI reference in plugin documentation

- bundles/org.openhab.persistence.dynamodb/NOTICE
- bundles/org.openhab.persistence.dynamodb/README.md
- bundles/org.openhab.persistence.dynamodb/pom.xml
- bundles/org.openhab.persistence.dynamodb/scripts/fetch_sdk_pom.xml
- bundles/org.openhab.persistence.dynamodb/src/main/feature/feature.xml
- bundles/org.openhab.persistence.dynamodb/src/main/java/org/openhab/persistence/dynamodb/internal/DynamoDBConfig.java
- bundles/org.openhab.persistence.dynamodb/src/main/java/org/openhab/persistence/dynamodb/internal/DynamoDBPersistenceService.java
- bundles/org.openhab.persistence.dynamodb/src/test/java/org/openhab/persistence/dynamodb/internal/BaseIntegrationTest.java
- bundles/org.openhab.persistence.dynamodb/src/test/java/org/openhab/persistence/dynamodb/internal/DynamoDBConfigTest.java
- Added NOTICE with all compiled dependencies. Dependencies listed in
feature.xml are omitted. Please review these.
- **NOTE:** jackson dependency is now provided by AWS SDK as a 'shaded' copy. We no longer use jackson feature provided in openhab. This will naturally increase dynamodb addon file size, by 0.8M (the whole openhab-addons.kar will be 272M, dynamodb jar 5.4M , compared to previous 4.6M). More info: https://aws.amazon.com/blogs/developer/the-aws-sdk-for-java-2-17-removes-its-external-dependency-on-jackson/
- Specifying the new `DefaultsMode` to make the SDK utilize latest
recommended parameters (`DefaultsMode.STANDARD`). Default otherwise would be `LEGACY` (historical parameters used by the java sdk specifically). `RetryMode` is also controlled by DefaultsMode,
so we no longer …
> [dynamodb] AWS SDK updated to 2.17.102

- bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/smarthome/SmartHomeDeviceStateGroupUpdateCalculator.java
It was recently discovered that during the refactoring from #6140 to #7969 I made a mistake that could lead to very frequent requests and high load on smarthome skills (ioBroker and openHAB). Since at least AWS hosted skills are paid per request this has the potential to cause high bills for the skill authors. I'm very sorry for that.
> [amazonechocontrol] fix refresh time for skill connected devices

- bundles/org.openhab.binding.plugwise/README.md
These linked pages seem to have been removed from the Plugwise website.
> [plugwise] Remove broken links from documentation

- bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcBaseDAO.java
- bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcDerbyDAO.java
- Fixed NPE when SQL query failed
In case of an error the `Yank.queryObjectArrays(..., ...)` method returns a `null` value.
> [jdbc] Fixed NPE when SQL query failed

- bundles/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/pro3/AtlonaPro3PortocolHandler.java
- bundles/org.openhab.binding.atlona/src/main/resources/OH-INF/config/config.xml
- bundles/org.openhab.binding.atlona/src/main/resources/OH-INF/i18n/atlona.properties
- bundles/org.openhab.binding.atlona/src/main/resources/OH-INF/thing/thing-types.xml
Fix misspelled word _atlona_ throughout the binding. No functional changes.
> [atlona] Correct spelling of atlona

- bundles/org.openhab.binding.tapocontrol/README.md
- bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/TapoDiscoveryService.java
- bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/constants/TapoThingConstants.java
- bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/structures/TapoDeviceInfo.java
- bundles/org.openhab.binding.tapocontrol/src/main/resources/OH-INF/i18n/tapocontrol.properties
- bundles/org.openhab.binding.tapocontrol/src/main/resources/OH-INF/thing/L510.xml
- bundles/org.openhab.binding.tapocontrol/src/main/resources/OH-INF/thing/L530.xml
- bundles/org.openhab.binding.tapocontrol/src/main/resources/OH-INF/thing/L920.xml
- bundles/org.openhab.binding.tapocontrol/src/main/resources/OH-INF/thing/P105.xml
- bundles/org.openhab.binding.tapocontrol/src/main/resources/OH-INF/thing/P110.xml
This PR fixes the "wrong device found" error for Tapo L510 and L530 Bulbs with Hardware Rev.2
Cause: Tapo renamed types from "L530_Series" to "L530"
Also implemented L920 LED-Lightstrip and P110 SmartPlug with basic functions.
> [tapocontrol] fix "device not found" with L510/L530 hw rev2 / add L920 and P110 things

- bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/internal/homie300/Property.java
- bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/internal/homie300/PropertyAttributes.java
- bundles/org.openhab.binding.mqtt.homie/src/main/resources/OH-INF/config/homie-channel-config.xml
- bundles/org.openhab.binding.mqtt.homie/src/main/resources/OH-INF/i18n/mqtt.properties
This adds support for DateTime channels to the mqtt homie binding, see https://homieiot.github.io/specification/#datetime
Relates to #10839
> [mqtt.homie] Add DateTime channel type to comply with MQTT Homie convention 3.x

- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/HDPowerViewBindingConstants.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/HDPowerViewWebTargets.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/Firmware.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/responses/FirmwareVersion.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/responses/FirmwareVersions.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/responses/Shades.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewHubHandler.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewShadeHandler.java
Fixes #11979
Add firmware information for hub and shade.
Hub:
- Firmware name.
- Main processor firmware version (revision, sub revision and build).
- Radio firmware version (revision, sub revision and build); **V2 Hub only**
Shade:
- Firmware version (revision, sub revision and build)
- Motor firmware version (revision, sub revision and build)
These properties can be useful information for users, but also prepares the binding for handling differences between firmware versions, for example supporting functionality which is only available in V2 Hub. This was almost necessary for #11857.
> [hdpowerview] Add firmware information properties for hub and shade

- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/HDPowerViewBindingConstants.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewHubHandler.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewShadeHandler.java
Fix comment from #11980 after pull request was merged: Use standard firmware property constant from core.
> [hdpowerview] Use standard firmware property constant

- bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/discovery/HomematicDeviceDiscoveryService.java
Bug fix for #11969
After restart of openHAB the scan duration for homematic devices is read from a variable which is initialized with a default value instead of using the configuration of the binding.
The scan duration is read directly from the configuration of the binding.
> [homematic] fixing incorrect scan duration after openHAB restart

- bundles/org.openhab.voice.googletts/src/main/java/org/openhab/voice/googletts/internal/GoogleTTSService.java
When google tts returns a wav file, it is now parsed to get correct informations about it.
(It is mandatory for playing it with, at least, the System speaker audio sink)
This is the fix for the issue [discuted here](https://community.openhab.org/t/oh3-google-tts-only-white-noise/112714).
[Snapshot release](https://github.com/dalgwen/openhab-addons/releases/tag/3.3.0-snapshot-googleTTS-fix_white_noise)
Close #10015
> [googletts] Use returned sound to get play informations

- bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/DanfossAirUnitBindingConstants.java
- bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/handler/DanfossAirUnitHandler.java
- bundles/org.openhab.binding.danfossairunit/src/main/resources/OH-INF/thing/thing-types.xml
Fixes #11991
This pull request was made for compliance with naming convention for properties in general and for specific property types in particular. Changes:
- **serialNumber** renamed from **Serial Number**.
- **modelId** renamed from **Unit Name**.
- **vendor** introduced.
Also fixed small issue with properties showing as **unknown** during startup.
There is a slight problem when upgrading to this version, but I wouldn't consider it a breaking change as it's only cosmetic. For things created from UI, there will be duplicate properties until thing is recreated.
For file-based configuration this problem is resolved by openHAB restart:
> [danfossairunit] Consolidate properties for compliance

- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/MieleBindingConstants.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/discovery/MieleApplianceDiscoveryService.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/MieleApplianceHandler.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/MieleBridgeHandler.java
Fixes #11996
This pull request provides minor changes for property improvements:
- **modelId** renamed from **model**.
- **vendor** introduced.
- **firmwareVersion** introduced.
- **connectionBaudRate** introduced.
> [miele] Consolidate properties for compliance

- bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/http/HttpResponseListener.java
RIght now error messages of the HTTP-Binding look like this:
```
Requesting 'https://api.corona-zahlen.org/districts/03251' (method='GET', content='null') failed: HttpConnectionOverHTTP@d01aa55::DecryptedEndPoint@3eee00d9{l=/XXXXXXX:XXXX,r=api.corona-zahlen.org/104.21.60.139:443,OPEN,fill=-,flush=-,to=599158/0}
```
with this change they look like this:
```
Requesting 'https://api.corona-zahlen.org/districts/03251' (method='GET', content='null') failed: java.io.EOFException: HttpConnectionOverHTTP@d01aa55::DecryptedEndPoint@3eee00d9{l=/XXXXXXX:XXXX,r=api.corona-zahlen.org/104.21.60.139:443,OPEN,fill=-,flush=-,to=599158/0}
```
Note the added `java.io.EOFException: `, which explains what kind of exception actually happened.
> [http] Provide meaningful error messages

- bundles/org.openhab.binding.jeelink/README.md
To me, as a OH-Noob, the documentation suggested that automatic discovery is supported . I tried to condense and clarify the documentation.
Fixes #11986
> [jeelink] Doc: Clarify thing discovery

- bundles/org.openhab.binding.publictransportswitzerland/src/main/resources/OH-INF/i18n/publictransportswitzerland.properties
I just ran `mvn i18n:generate-default-translations`
As requested here: https://github.com/openhab/openhab-addons/pull/8540#issuecomment-1008285454
> [publictransportswitzerland] Add missing default translation properties

- CODEOWNERS
- bundles/org.openhab.binding.mycroft/src/main/resources/OH-INF/i18n/mycroft.properties
As asked by @lolodomo in the [mycroft binding initial contrib merge request](https://github.com/openhab/openhab-addons/pull/11040#issuecomment-1009677928), this PR initialize the i18n default file.
(and by the way, reorder alphabetically the CODEOWNERS file)
> [mycroft] Init i18n

- bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/virtual/ButtonVirtualDatapointHandler.java
- bundles/org.openhab.binding.homematic/src/test/java/org/openhab/binding/homematic/internal/communicator/virtual/ButtonDatapointTest.java
HM-IP(W) devices seem to use a different format for long press handling.
(My) HM devices does this:
PRESS_CONT
PRESS_LONG
PRESS_CONT (N times for repetion)
PRESS_LONG_RELEASE
while (at least) HmIPW-DRI32 does this (as determined [here](https://community.openhab.org/t/homematic-binding-cant-set-value-for-datapoint-warning-for-master-parameter/42145/20)):
PRESS_LONG
PRESS_LONG_START
PRESS_LONG (N times for repetition)
PRESS_LONG_RELEASE
Add support for the HMIP format while keeping support for the HM format.
> [homematic] Fix long button press handling for HM-IP devices

- CODEOWNERS
As discussed in #12033 , the mentioned authors for the digitalstrom binding will no more contribute or review.
> [digitalstrom] Update CODEOWNERS

- bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/lib/manager/StructureManager.java
- bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/lib/manager/impl/DeviceStatusManagerImpl.java
- bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/lib/manager/impl/StructureManagerImpl.java
- bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/lib/structure/devices/deviceparameters/CachedMeteringValue.java
- bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/lib/structure/devices/deviceparameters/impl/DSID.java
- bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/lib/structure/devices/deviceparameters/impl/DSUID.java
- bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/lib/structure/devices/deviceparameters/impl/JSONCachedMeteringValueImpl.java
Fixes #11847
This should fix the issue introduced by DSS update to 1.19.2 while staying backwards compatible to older versions of DSS.
> [digitalstrom] Adoptions due to API changes in DSS Update 1.19.2

- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/HDPowerViewWebTargets.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/Firmware.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/responses/FirmwareVersion.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/responses/FirmwareVersions.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/responses/Survey.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewHubHandler.java
Fixes #12027 
Changes done:
1. Fix SAT warnings about missing `@NonNullByDefault` annotations on classes.
Next steps (in context of new PR):
1. Refactor error handling: Throw exception if contract is breached.
2. Consider separating deserialization classes so they are not exposed directly to handlers (with `@Nullable` when contract doesn't allow this). Or find other way to make sure handlers are not bloated with null handling which shouldn't be needed for valid responses.
> [hdpowerview] Fix SAT warnings

- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/AbstractHomekitAccessoryImpl.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitCharacteristicFactory.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitHeaterCoolerImpl.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitTemperatureSensorImpl.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitThermostatImpl.java
Apple HomeKit protocol  works internally with Celsius for temperature, so that we need to convert temperature in case openHAB is using Fahrenheit. this was already implemented for actual temperature values but not for temperature threshold and min/max values 
This PR add temperature conversion to thresholds and min/max values and fixes 
#11957
#10275
the existing methods convertFromCelsius and convertToCelsius are moved from abstract class to a factory so that they can be used from different places. 
these methods read binding setting "useFahrenheit" via OSGI service as settings could not be injected into factory or propagated to it easily. 
> [homekit] fix Fahrenheit conversion

- bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/influx2/Influx2FilterCriteriaQueryCreatorImpl.java
- bundles/org.openhab.persistence.influxdb/src/test/java/org/openhab/persistence/influxdb/internal/InfluxFilterCriteriaQueryCreatorImplTest.java
Fix issue #11878 
Optimizing a filter with limit 1 and time descending order for `| last()`
More discussion in the issue thread
> [influxdb] Fix previous item state performance issues

- bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/DebuggingGraalScriptEngine.java
- bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/OpenhabGraalJSScriptEngine.java
- bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/scriptengine/DelegatingScriptEngineWithInvocableAndAutocloseable.java
- bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/scriptengine/InvocationInterceptingScriptEngineWithInvocableAndAutoCloseable.java
Allows wrapped GraalJS scripts to also implement `AutoCloseable` so that they can be cleaned up when no longer used.
With https://github.com/openhab/openhab-core/pull/2681, fixes https://github.com/openhab/openhab-addons/issues/11952.
Note that these changes can be applied independently without issue, however both are required to fix the above issue.
Signed-off-by: Jonathan Gilbert <jpg@trillica.com>
> [jsscripting] Wrapped GraalJS ScriptEngines now also Autocloseable

- CODEOWNERS
I did a check for registered code owners who no longer exists as GitHub users. Only a single user hit came up. I have no background information about why he disappeared but can confirm that for the **hdpowerview** binding there has been no activity for a long time.
```
#!/usr/bin/python3
import requests
github_user = ''
github_token = ''
github_root = 'https://api.github.com'
file = open('CODEOWNERS', 'r')
lines = file.readlines()
file.close()
headers = {
'User-Agent': github_user,
'Authorization': 'token ' + github_token
}
for line in lines:
if line[0:9] == "/bundles/":
parsed_line = line.split()
for idx, val in enumerate(parsed_line):
if idx == 0:
binding = val
else:
user = val.lstrip('@')
if user == "openhab/add-ons-maintainers": …
```
> Remove non-existing users from CODEOWNERS

- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/HDPowerViewWebTargets.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/SurveyData.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/responses/Survey.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/discovery/HDPowerViewShadeDiscoveryService.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/exceptions/HubException.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/exceptions/HubInvalidResponseException.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/exceptions/HubMaintenanceException.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/exceptions/HubProcessingException.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewHubHandler.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewShadeHandler.java
- bundles/org.openhab.binding.hdpowerview/src/test/java/org/openhab/binding/hdpowerview/HDPowerViewJUnitTests.java
Fixes #12048
Changes:
- `JsonParseException` is wrapped in custom exception and not exposed directly to handlers.
- `HDPowerViewWebTargets` methods no longer return null objects, instead will throw exceptions.
- Custom exceptions are now inherited from `HubException` so callers can decide the granularity of the error handling.
Continuation of #12032
> [hdpowerview] Refactor exception handling

- itests/org.openhab.binding.mielecloud.tests/src/main/java/org/openhab/binding/mielecloud/internal/handler/MieleBridgeHandlerTest.java
The validation did not fail previously because it was broken and fixed in https://github.com/openhab/openhab-core/pull/2683
> [mielecloud] Fix tests by adding missing email configuration parameter

- itests/org.openhab.binding.astro.tests/itest.bndrun
- itests/org.openhab.binding.avmfritz.tests/itest.bndrun
- itests/org.openhab.binding.feed.tests/itest.bndrun
- itests/org.openhab.binding.hue.tests/itest.bndrun
- itests/org.openhab.binding.max.tests/itest.bndrun
- itests/org.openhab.binding.mielecloud.tests/itest.bndrun
- itests/org.openhab.binding.modbus.tests/itest.bndrun
- itests/org.openhab.binding.nest.tests/itest.bndrun
- itests/org.openhab.binding.ntp.tests/itest.bndrun
- itests/org.openhab.binding.systeminfo.tests/itest.bndrun
- itests/org.openhab.binding.tradfri.tests/itest.bndrun
- itests/org.openhab.binding.wemo.tests/itest.bndrun
- itests/org.openhab.persistence.mapdb.tests/itest.bndrun
- pom.xml
* Syncs the karaf.version so the new Maven plugin is used
* Resolves itest runbundles for the new runtime dependencies
---
Related to openhab/openhab-distro#1363
> Upgrade to Karaf 4.3.6

- bundles/org.openhab.binding.oppo/README.md
- bundles/org.openhab.binding.oppo/src/main/java/org/openhab/binding/oppo/internal/OppoBindingConstants.java
- bundles/org.openhab.binding.oppo/src/main/java/org/openhab/binding/oppo/internal/communication/OppoStatusCodes.java
- bundles/org.openhab.binding.oppo/src/main/java/org/openhab/binding/oppo/internal/handler/OppoHandler.java
fixes issue #12064 
In some configurations, the player sends unsolicited updates but the update message is an abbreviated code when compared to the longer response provided by the query command that must used in other configurations. The previous strategy to immediately call the query command upon receiving an unsolicited update was flawed in that the query command sometimes provided an outdated value. This PR fixes the issue for Play Mode and Disc Type by mapping the abbreviated unsolicited update code to the values provided by the query command. For Audio Type and Subtitle Type, a slight delay was added before calling the query command.
> [oppo] Fix Play Mode and Disc Type updates

- bundles/org.openhab.binding.androiddebugbridge/README.md
- bundles/org.openhab.binding.androiddebugbridge/src/main/feature/feature.xml
- bundles/org.openhab.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/AndroidDebugBridgeBindingConstants.java
- bundles/org.openhab.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/AndroidDebugBridgeDevice.java
- bundles/org.openhab.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/AndroidDebugBridgeDeviceException.java
- bundles/org.openhab.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/AndroidDebugBridgeDeviceReadException.java
- bundles/org.openhab.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/AndroidDebugBridgeHandler.java
- bundles/org.openhab.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/discovery/AndroidDebugBridgeDiscoveryService.java
- bundles/org.openhab.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/discovery/FireTVStickMDNSDiscoveryParticipant.java
- bundles/org.openhab.binding.androiddebugbridge/src/main/resources/OH-INF/thing/thing-types.xml
- Added mDNS discovery for Fire TV Stick
> [androiddebugbridge] Added mDNS discovery for Fire TV Stick

- bundles/org.openhab.binding.unifi/README.md
Add note for Unifi OS default port
> [unifi] Unifi OS Default-Port

- bundles/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/internal/VoiceRSSTTSService.java
- bundles/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/internal/cloudapi/CachedVoiceRSSCloudImpl.java
- bundles/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/internal/cloudapi/VoiceRSSCloudAPI.java
- bundles/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/internal/cloudapi/VoiceRSSCloudImpl.java
- bundles/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/tool/CreateTTSCache.java
- bundles/org.openhab.voice.voicerss/src/test/java/org/openhab/voice/voicerss/internal/CompatibleAudioFormatMatcher.java
- bundles/org.openhab.voice.voicerss/src/test/java/org/openhab/voice/voicerss/internal/VoiceRSSTTSServiceTest.java
This pull request adds support for WAV / PCM audio in all frequencies and bit depths supported by VoiceRSS.
Support for MP3, Ogg Vorbis and AAC was kept as it was (44.1 kHz, 16 bit) but could be extended based on this work.
The file-based cache was kept backwards compatible and only adds a format specifier to the file name if it is different from the default.
> [voicerss] Add support for WAV audio format

- bundles/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/internal/VoiceRSSTTSService.java
- bundles/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/internal/cloudapi/VoiceRSSCloudImpl.java
> [voicerss] Fix bad audio format code and use HTTPS URL instead of HTTP

- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/AbstractKNXClient.java
This PR fixes the `NullPointerException` that arises from *-control items when a `GroupValueRead` request is issued by the KNX side and openHAB tries to answer with the state known to the bound item.
The cause is the introduction of the secure layer in the calimero library version 2.5. The constructor of the `ProcessCommunicationResponder` now takes two arguments. A `KNXNetworkLink` instance and a `SecureApplicationLayer` instance. The security application layer must not be null, although this precondition is not enforced by the constructor of the `ProcessCommunicationResponder`.
This is the URL to the impacted build artefact:
https://openhab.jfrog.io/ui/native/libs-pullrequest-local/org/openhab/addons/bundles/org.openhab.binding.knx/3.3.0-SNAPSHOT/org.openhab.binding.knx-3.3.0-SNAPSHOT.ja …
> [knx] GroupRead / SendToKNX fails with NullPointerException #12040

- bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/fs/watch/JSDependencyTracker.java
- bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/fs/watch/JSFileWatcher.java
- bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/fs/watch/JSScriptFileWatcher.java
Fixes #11831 where `node_modules` is watched for scripts. This change prevents this subdir being watched (library changes are still watched elsewhere).
Signed-off-by: Jonathan Gilbert <jpg@trillica.com>
> [jsscripting] JS script engine no longer watches node_modules for scripts

- bundles/org.openhab.io.homekit/README.md
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/AbstractHomekitAccessoryImpl.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitCharacteristicFactory.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitHeaterCoolerImpl.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitTemperatureSensorImpl.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitThermostatImpl.java
if an Item associated with a temperature characteristic has a QuantityType
(of dimension Temperature) as its state, regardless of current unit,
use that to convert to celsius instead of any other configuration.
Note that this is only for supply values to HomeKit; commands coming from
HomeKit will still send a DecimalType with units according to the HomeKit-wide
useFahrenheit configuration.
> [homekit] use quantity type conversions for temperature characteristics

- bundles/org.openhab.binding.teleinfo/README.md
This PR improves documentation for Linky Standard TIC mode support (added in OH3.2).
> [teleinfo] improve documentation for Linky Standard TIC mode

- bundles/org.openhab.binding.hdpowerview/README.md
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/HDPowerViewBindingConstants.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/HDPowerViewHandlerFactory.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/HDPowerViewWebTargets.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/requests/RepeaterBlinking.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/responses/Repeater.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/responses/RepeaterData.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/responses/Repeaters.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/config/HDPowerViewRepeaterConfiguration.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/config/HDPowerViewShadeConfiguration.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/discovery/HDPowerViewDeviceDiscoveryService.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewHubHandler.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewRepeaterHandler.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewShadeHandler.java
- bundles/org.openhab.binding.hdpowerview/src/main/resources/OH-INF/i18n/hdpowerview.properties
- bundles/org.openhab.binding.hdpowerview/src/main/resources/OH-INF/i18n/hdpowerview_da.properties
- bundles/org.openhab.binding.hdpowerview/src/main/resources/OH-INF/thing/thing-types.xml
Fixes #12060
Add support for Hunter Douglas PowerView Repeaters.
Supporting the Repeater as a thing makes it possible to:
- Enable/disable blinking during commands. For example this can be used to disable at night when repeater is in a bedroom.
- Flash repeater LED's on request. For example this could be used in combination with a motion sensor to provide position lighting at night.
- See firmware version information.
- New thing type **repeater** created (with discovery support).
- Repeaters are polled every 5 minutes to synchronize "blink enabled" state when done from PowerView app or other integrations.
- When receiving repeater information, firmware information is also obtained and set as property.
- When **identify** channel is …
> [hdpowerview] Add support for repeaters

- bundles/org.openhab.binding.hdpowerview/README.md
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/CoordinateSystem.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/ShadePosition.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/database/ShadeCapabilitiesDatabase.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewShadeHandler.java
- bundles/org.openhab.binding.hdpowerview/src/test/java/org/openhab/binding/hdpowerview/HDPowerViewJUnitTests.java
- bundles/org.openhab.binding.hdpowerview/src/test/java/org/openhab/binding/hdpowerview/ShadePositionTest.java
Fixes https://github.com/openhab/openhab-addons/issues/12097
- Added support for a second rear blackout panel on shades with `capabilities:8` and `capabilities:9`
- Refactored the enum constant names for `PRIMARY_POSITION`, `SECONDARY_POSITION` etc.
- Added JUNIT tests for shades with `capabilities:8` and `capabilities:9`
> [hdpowerview] Added support for rear blackout panel

- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitImpl.java
homekit binding makes currently a full restart on network changes like IP address changes.
the full restart includes removing all openhab items from the list of homekit accessories and adding them again. basically, the start/stop methods for binding start/stop were re-used
this could lead in some case to config reset in home all, like reported here
https://community.openhab.org/t/homekit-no-response-error-on-all-openhab-items/118200/172
this PR reduces the stop logic to minimum and especially skip the removal of homekit accessories on stop.
the changes are following:
- slight rework on "start" function in order to remember the address the HomeKit was bound to
- replace call of the standard "stop" function copy the few needed step to onChange function
- add check to onChange function …
> [homekit] quick restart on network changes

- bundles/org.openhab.binding.tapocontrol/README.md
- bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/api/TapoDeviceConnector.java
- bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/api/TapoDeviceHttpApi.java
- bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/constants/TapoBindingSettings.java
- bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/constants/TapoErrorConstants.java
- bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/constants/TapoThingConstants.java
- bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/device/TapoDevice.java
- bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/device/TapoLightStrip.java
- bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/device/TapoSmartBulb.java
- bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/device/TapoSmartPlug.java
- bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/device/TapoUniversalDevice.java
- bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/helpers/TapoUtils.java
- bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/structures/TapoDeviceInfo.java
- bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/structures/TapoEnergyData.java
- bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/structures/TapoLightEffect.java
- bundles/org.openhab.binding.tapocontrol/src/main/resources/OH-INF/i18n/tapocontrol.properties
- bundles/org.openhab.binding.tapocontrol/src/main/resources/OH-INF/thing/P110.xml
- bundles/org.openhab.binding.tapocontrol/src/main/resources/OH-INF/thing/channels.xml
- bundles/org.openhab.binding.tapocontrol/src/test/java/org/openhab/binding/tapocontrol/internal/device/TapoUniversalDevice.java
Added "EnergyMonitoring" function for P110 SmartPlugs
Device will report:
* actual PowerUsage (Watt)
* today EnergyUsage (Wh)
* today Runtime (Time in seconds device was on today)
> [tapocontrol] now supports energy monitoring of P110 device

- bundles/org.openhab.binding.hdpowerview/README.md
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/builders/SceneChannelBuilder.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/builders/SceneGroupChannelBuilder.java
- bundles/org.openhab.binding.hdpowerview/src/test/java/org/openhab/binding/hdpowerview/SceneChannelBuilderTest.java
- bundles/org.openhab.binding.hdpowerview/src/test/java/org/openhab/binding/hdpowerview/SceneGroupChannelBuilderTest.java
Fixes #12140
Fix old quirk where stateless items needed to be defined with `autoupdate="false"`. This is instead accomplished by [Auto Update Policy](https://www.openhab.org/docs/developer/bindings/thing-xml.html#auto-update-policies) **veto**.
> [hdpowerview] Fix autoupdate quirk for scene/scene group items

- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewHubHandler.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewShadeHandler.java
Fixes #12071 - please see this issue for further details.
This pull request fixes a concurrency issue and optimizes the status transitions for shades to come online as fast as possible:
- A five second initial delay in requesting shade data has been removed. It probably existed because of next problem:
- Bridge could receive data before shade things were initialized. This would cause them to come **ONLINE** prematurely, thus go back to **UNKNOWN** when being initialized. After this there would be a one minute delay in coming **ONLINE** again after next data poll.
Example of transitions for a single shade after the changes:
```
2022-01-24 23:28:01.835 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing …
```
> [hdpowerview] Optimize initialization of shades

- bundles/org.openhab.automation.jrubyscripting/pom.xml
Upgrades jruby version to 9.3.3.0, which was released on the 19th of January 2022
https://www.jruby.org/2022/01/19/jruby-9-3-3-0.html
> [jrubyscripting] Upgrade jruby version to 9.3.3.0

- bundles/org.openhab.binding.radiothermostat/src/main/java/org/openhab/binding/radiothermostat/internal/handler/RadioThermostatHandler.java
Apply logic to the fan_status channel for some thermostats that don't properly report that the fan is on during heating or cooling. Any time the thermostat status is heating (1) or cooling (2), the fan status will be reported as 1. When the thermostat status is off (0), the fan_status will be reported from the json data.
fixes #12144
> [radiothermostat] Workaround for incorrectly reported fan state

- bundles/org.openhab.automation.groovyscripting/src/main/java/org/openhab/automation/groovyscripting/internal/GroovyScriptEngineFactory.java
This change adds `conf/automation/groovy` to the `GroovyScriptEngineFactory`-classpath
It enables you to create own classes under that path, which can be imported in jsr223-groovy-scripts
The jsr223-path is **not used**, because the `GroovyClassLoader` takes care of the evaluation of the files.
Example from https://community.openhab.org/t/groovy-scripts-how-to-import-another-groovy-file/105447/17
The following works, when you place your packages under **conf/automation/groovy/**
`$ cat conf/automation/groovy/mytest/Util.groovy `
```groovy
package mytest
class Util {
public static String getHello() {
return "Hello world!"
}
}
```
`$ cat conf/automation/jsr223/test.groovy`
```groovy
import mytest.Util   // <-------- HERE IT IS
import org.slf4j.Logger
import org.slf4j.LoggerFactory
def …
```
> [groovyscripting] add conf/automation/groovy to the classpath

- bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/JRubyScriptEngineConfiguration.java
The `rubylib` addon configuration is supposed to alter the $LOAD_PATH but currently it doesn't. As a result, personal libraries located in RUBYLIB path won't be found. Currently a workaround is applied in the helper library to parse RUBYLIB and add the paths into $LOAD_PATH. 
However, GUI users who opt not to use the helper library will not be able to load personal libraries based on the `rubylib` search path.
This PR remedies this situation by updating `$LOAD_PATH` within the addon.
> [jrubyscripting] Apply RUBYLIB configuration to $LOAD_PATH

- bundles/org.openhab.binding.mqtt.generic/README.md
- bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/ChannelConfig.java
- bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/handler/GenericMQTTThingHandler.java
- bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/ValueFactory.java
Fix #10117 
The current documentation uses lower case color_mode which will cause an error. This PR updates the docs to use upper case. Furthermore, the default of "HSB" is assumed when color_mode is empty or not specified. This fixes the bug in the GUI when the user accepts the default color_mode.
> [mqtt.generic] Fix default configuration and docs for color_mode

- bundles/org.openhab.binding.enocean/README.md
- bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/D2_05/D2_05_00_NodON.java
- bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/EEPType.java
- bundles/org.openhab.binding.enocean/src/main/resources/OH-INF/thing/Rollershutter.xml
For NODONs in Wall Modules SIN-2-2-00 and SIN-2-1-0x it is already possible to adjust the repeater mode. For NODONs roller-shutter (SIN-2-RS-01) this wasn't possibly with openhab so far - this series of commits enables the repeater mode setting in openhab also for NODONs roller-shutter modules, the same way it is done for the other two in Wall Modules.
Correctness also tested physically with some of the roller-shutter modules in my own house.
> [enocean] enable usage of Nodon roller-shutter repeater mode

- bundles/org.openhab.binding.mqtt.generic/README.md
Add availabilityTopics to the documentation for mqtt.generic. This was discussed in https://community.openhab.org/t/mqtt-lwt-things-definition-availability-topic/103065/27
> [mqtt.generic] Include availabilityTopic in the binding docs

- bundles/org.openhab.binding.hdpowerview/README.md
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/HDPowerViewWebTargets.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/requests/ShadeJog.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewShadeHandler.java
- bundles/org.openhab.binding.hdpowerview/src/main/resources/OH-INF/i18n/hdpowerview.properties
- bundles/org.openhab.binding.hdpowerview/src/main/resources/OH-INF/i18n/hdpowerview_da.properties
- bundles/org.openhab.binding.hdpowerview/src/main/resources/OH-INF/thing/thing-types.xml
Fixes #12174
Add a command for identifying a shade by jogging it.
Extends #12138 to have more than one command and provides same functionality for shades as introduced for repeaters in #12061.
> [hdpowerview] Add shade identify command

- bundles/org.openhab.binding.mqtt.generic/README.md
- bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/internal/action/MQTTActions.java
Resolve #10762
This PR adds variants of publishMQTT that accept byte array instead of String.
> [mqtt] publishMQTT Action accepts a bytearray payload

- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/sensors/LightLevelHandler.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/sensors/TemperatureHandler.java
- Fixed setting wrong values for ledindication configuration
This leads to offline devices after enabling config validation before thing initialization.
> [hue] Fixed setting wrong values for ledindication configuration

- bundles/org.openhab.voice.voicerss/README.md
- bundles/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/internal/VoiceRSSAudioStream.java
- bundles/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/internal/VoiceRSSTTSService.java
- bundles/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/internal/VoiceRSSVoice.java
- bundles/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/internal/cloudapi/CachedVoiceRSSCloudImpl.java
- bundles/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/internal/cloudapi/VoiceRSSCloudAPI.java
- bundles/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/internal/cloudapi/VoiceRSSCloudImpl.java
- bundles/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/tool/CreateTTSCache.java
Make the tool independent of core openHAB
Fix the parsing of the command arguments.
Allow to provide optional audio codec and format.
Null annotations added on most of the classes
> [voicerss] Fix and enhance the external tool to prefill the cache

- bundles/org.openhab.binding.mqtt/src/main/resources/OH-INF/i18n/mqtt.properties
- bundles/org.openhab.binding.mqtt/src/main/resources/OH-INF/i18n/mqtt_de.properties
- bundles/org.openhab.binding.mqtt/src/main/resources/OH-INF/i18n/mqtt_hu.properties
- bundles/org.openhab.binding.mqtt/src/main/resources/OH-INF/i18n/mqtt_it.properties
It was discovered in #12152 that the i18n properties file names were wrong. As a result, it hasn't benefited from the translated files. This PR fixes the file name and also include the new entries that were added in #12152
> [mqtt] Fix translation file names

- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/HDPowerViewWebTargets.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/exceptions/HubShadeTimeoutException.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewHubHandler.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewShadeHandler.java
- bundles/org.openhab.binding.hdpowerview/src/main/resources/OH-INF/i18n/hdpowerview.properties
Fixes #12180
Improvements:
- Shades unknown to the hub are marked as **OFFLINE**/**GONE** and not polled (with HTTP code 403/404 as result).
- Shade request timeouts are handled consistently by throwing a dedicated exception. Previously each caller had to check an attribute within the returned object, which most callers didn't.
- Shade request timeout when polling positions is logged as **info**, not **warning**, as this is a quite common scenario.
- Battery-related channels are updated immediately after performing a battery refresh query.
> [hdpowerview] Improve error handling for unknown shades and timeouts

- bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/handler/AbstractBrokerHandler.java
- bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/handler/BrokerHandler.java
BrokerHandler::connectionStateChanged() was being called twice upon each connection, resulting in updateState() and channel triggers being called twice. Furthermore, the birthMessage added in #12152 got published twice when a clientID is configured.
This is because connectionStateChanged is called by `MqttBrokerConnection` as its connection observer, as registered in https://github.com/openhab/openhab-addons/blob/97db73938d37d60a31755681e84d979e2e023777/bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/handler/AbstractBrokerHandler.java#L109
So the additional call to connectionStateChanged in here is redundant: https://github.com/openhab/openhab-addons/blob/97db73938d37d60a31755681e84d979e2e023777/bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt …
> [mqtt] Remove redundant call to connectionStateChanged upon connection

- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitImpl.java
as discussed https://github.com/openhab/openhab-addons/pull/12072#issuecomment-1029225393
it could happen that on very fast network changes the onChange method get called before the previous "onChange" method has finished the homekit bridge restart.  this could lead to reset of homekit configuration in home app
this PR adds synchronized to ensure that only only one onChange is executed at the same time. The notification is done in openhab core via SafeCaller thread so that synchronized will not block openhab core
> [homekit] make network onChange method synchronized

- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/discovery/WemoLinkDiscoveryService.java
- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoBaseThingHandler.java
- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoCoffeeHandler.java
- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoCrockpotHandler.java
- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoDimmerHandler.java
- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoHandler.java
- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoHolmesHandler.java
- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoInsightHandler.java
- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoLightHandler.java
- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoMakerHandler.java
- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/http/WemoHttpCall.java
- itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/discovery/test/WemoLinkDiscoveryServiceOSGiTest.java
- itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/handler/test/WemoHandlerOSGiTest.java
- itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/handler/test/WemoLightHandlerOSGiTest.java
- itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/handler/test/WemoMakerHandlerOSGiTest.java
Continuation of #12101:
- Service subscription consolidated in base class (removing a lot of duplicate code).
- Fix status wrongly set to **ONLINE** when exception is thrown.
- Fix exception thrown from `handleCommand()` - set status **OFFLINE** instead.
- Rework error handling for `WemoHttpCall`: Duplicated logging moved inside and throws exception rather than returning null.
- Decrease log level from **error** to **warning** for communication errors and avoid warning every minute while a device is offline.
- Improve reliability of GENA events by renewing subscriptions automatically.
Review notes:
- Reading commit by commit might be helpful to understand the process/distinct steps.
> [wemo] Improve GENA subscription reliability and error handling

- bundles/org.openhab.binding.siemensrds/README.md
The binding requires an API key on the Siemens Climatix IC cloud server. This server exists primarily for supporting Original Equipment Manufacturing (OEM) customers who use the Climatix range of HVACR control products. However the Climatix IC cloud server is also used for supporting private customers using the RDS range of residential smart thermostats. But Siemens customer support people are often unaware of the latter fact, so when you ask them for the API key for the RDS smart thermostat range, their first reaction might often be to say you are talking nonsense!
This PR is an update to the ReadMe that a) explains the above, and b) advises the user to not accept that 'nonsense' answer, and to persist in requesting the proper key.
Signed-off-by: Andrew Fiddian-Green …
> [siemenrds] Update in ReadMe about getting an API key

- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewHubHandler.java
This is small improvement for:
- Eliminating risk of breaking shade and scene/scene group/automation updates in case of bad firmware response.
- Updating firmware versions when binding is restarted or reconfigured.
> [hdpowerview] Eliminate risk of bad firmware response breaking shade/scene updates

- bundles/org.openhab.binding.wemo/src/main/resources/OH-INF/config/config.xml
- bundles/org.openhab.binding.wemo/src/main/resources/OH-INF/i18n/wemo.properties
- bundles/org.openhab.binding.wemo/src/main/resources/OH-INF/thing/thing-types.xml
Fix entries in inbox for already configured devices, and reduce redundancy in thing-type XML definitions by introducing a shared `config-description` for UDN.
> [wemo] Fix already configured devices in inbox

- bundles/org.openhab.binding.mqtt.generic/README.md
- bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/AbstractMQTTThingHandler.java
- bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/ChannelState.java
- bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/handler/GenericMQTTThingHandler.java
- bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/handler/GenericThingConfiguration.java
- bundles/org.openhab.binding.mqtt.generic/src/main/resources/OH-INF/thing/generic-thing.xml
Resolve #10632, Resolve #10226 by adding transformationPattern option for Thing's availabilityTopic.
De-duplicated the transformation string parsing routine, so that all transformationPattern[Out] get parsed by the same code.
> [mqtt.generic] Support transformationPattern for thing's availabilityTopic

- bundles/org.openhab.binding.danfossairunit/src/main/resources/OH-INF/thing/thing-types.xml
Fixes #12216
Fix entries in inbox for already configured units.
> [danfossairunit] Fix already configured units in inbox

- bundles/org.openhab.voice.googlestt/src/main/java/org/openhab/voice/googlestt/internal/GoogleSTTService.java
Emit correct recognition events, SpeechStartEvent/SpeechStopEvent are not used in the core.
> [googlestt] emit correct recognition events

- bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcBaseDAO.java
- bundles/org.openhab.persistence.jdbc/src/test/java/org/openhab/persistence/jdbc/db/JdbcBaseDAOTest.java
- Fixed ClassCastException for `ColorItem` / `HSBType`
Fixes #12218 
> [jdbc] Fixed ClassCastException for ColorItem / HSBType

- CODEOWNERS
> [Wemo] add @jlaur as code-owner

- bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/virtual/DisplayTextVirtualDatapoint.java
- bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/model/HmDatapoint.java
- bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/type/HomematicTypeGeneratorImpl.java
The RPC protocol doesn't provide this value, so it always was made up
more or less arbitrarily. Since the UI now uses this value for
validation purposes, there are cases where valid values can not be
entered due to this step size (particularly for datapoints with more
than 1 decimal digit).
See #12183 for a concrete breakage example.
Fixes #12183
> [homematic] Remove state description step size handling

- bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/JRubyScriptEngineFactory.java
This PR fixes a bug where the classes in the openhab's script default scope is not usable within Jruby because they are   Java classes.
This PR converts the java classes into their jruby counterpart
This issue was discussed here: https://github.com/boc-tothefuture/openhab-jruby/issues/482
This jar can be used to test this PR: https://github.com/jimtng/openhab-addons/releases/download/v0.1/org.openhab.automation.jrubyscripting-3.3.0-SNAPSHOT.jar
@boc-tothefuture
> [jrubyscripting] convert presets from java class to ruby class

- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/database/ShadeCapabilitiesDatabase.java
- bundles/org.openhab.binding.hdpowerview/src/test/java/org/openhab/binding/hdpowerview/ShadePositionTest.java
Two users have reported that Capabilities:1 shades are 'TiltOnClosed' and not 'TiltAnywhere'.
> [hdpowerview] Fix for capabilities:1 shades

- bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/thing/channel-types.xml
Also fix few categories to use only official categories
> [openweathermap] Semantics added to channel types

- bundles/org.openhab.binding.mqtt.homie/src/test/java/org/openhab/binding/mqtt/homie/internal/handler/ThingChannelConstants.java
I plan on doing some more work in this binding, but want to clean up
the tests a bit first so I have less distraction while writing new tests.
These constants seem to be copy/pasted from the mqtt.generic binding
tests, and then never used.
> [mqtt.homie] remove unused constants in tests

- bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/handler/InsteonNetworkHandler.java
This prevents the null analysis from inferring null values when printing to a Console.
Related to openhab/openhab-core#2742
> [insteon] Prevent null values from being inferred when printing to console

- bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/channels.xml
> [hue] Semantics added to channel types

- bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/netutils/WebSocketConnection.java
Fixes #12247
Avoid excessive logging at **DEBUG** level when receiving messages for devices unknown to openHAB (i.e. not configured).
> [deconz] Reduce log level for messages received for unconfigured devices

- bundles/org.openhab.binding.omnilink/README.md
- bundles/org.openhab.binding.omnilink/pom.xml
- bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/OmnilinkBindingConstants.java
- bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/AudioSourceHandler.java
- bundles/org.openhab.binding.omnilink/src/main/resources/OH-INF/thing/bridge.xml
This also removes an unused trigger channel definition that was in
OmnilinkBindingConstants.java.
Related-to [openhab-distro#1367](https://github.com/openhab/openhab-distro/pull/1367)
> [OmniLink] Refactor parts of code

- bundles/org.openhab.binding.tplinksmarthome/README.md
- bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/Commands.java
- bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/Connection.java
- bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/TPLinkSmartHomeHandlerFactory.java
- bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/TPLinkSmartHomeThingType.java
- bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/device/BulbDevice.java
- bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/device/LightStripDevice.java
- bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/handler/SmartHomeHandler.java
- bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/handler/TPLinkSmartHomeActions.java
- bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/model/SetLightState.java
- bundles/org.openhab.binding.tplinksmarthome/src/main/resources/OH-INF/i18n/tplinksmarthome.properties
- bundles/org.openhab.binding.tplinksmarthome/src/main/resources/OH-INF/thing/KL400.xml
- bundles/org.openhab.binding.tplinksmarthome/src/main/resources/OH-INF/thing/KL430.xml
- bundles/org.openhab.binding.tplinksmarthome/src/test/java/org/openhab/binding/tplinksmarthome/internal/device/DeviceTestBase.java
- bundles/org.openhab.binding.tplinksmarthome/src/test/java/org/openhab/binding/tplinksmarthome/internal/device/LightStripDeviceTest.java
- bundles/org.openhab.binding.tplinksmarthome/src/test/java/org/openhab/binding/tplinksmarthome/internal/handler/SmartHomeHandlerTest.java
- bundles/org.openhab.binding.tplinksmarthome/src/test/resources/org/openhab/binding/tplinksmarthome/internal/model/kl430_set_brightness.json
- bundles/org.openhab.binding.tplinksmarthome/src/test/resources/org/openhab/binding/tplinksmarthome/internal/model/kl430_set_brightness_response.json
- bundles/org.openhab.binding.tplinksmarthome/src/test/resources/org/openhab/binding/tplinksmarthome/internal/model/kl430_set_color.json
- bundles/org.openhab.binding.tplinksmarthome/src/test/resources/org/openhab/binding/tplinksmarthome/internal/model/kl430_set_color_response.json
- bundles/org.openhab.binding.tplinksmarthome/src/test/resources/org/openhab/binding/tplinksmarthome/internal/model/kl430_set_colortemperature.json
- bundles/org.openhab.binding.tplinksmarthome/src/test/resources/org/openhab/binding/tplinksmarthome/internal/model/kl430_set_colortemperature_response.json
- bundles/org.openhab.binding.tplinksmarthome/src/test/resources/org/openhab/binding/tplinksmarthome/internal/model/kl430_set_on.json
- bundles/org.openhab.binding.tplinksmarthome/src/test/resources/org/openhab/binding/tplinksmarthome/internal/model/kl430_set_on_response.json
Closes #8709
Additional:
Added action to send and receive json commands to a tplink device.
This can be used for test purposes or to run commands not available through channels.
Changed retry getting values 5 times before setting the device offline..Reduced socket time out to 2 seconds as it normally should react quickly and if it times out it tries again.
> [tplinksmarthome] Added KL430 lightstrip support

- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewRepeaterHandler.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewShadeHandler.java
Fix recent regression because of misunderstanding: https://github.com/openhab/openhab-addons/pull/12061#discussion_r791120507
This pull request reverts:
- Repeater: d7e10c565a16ca40d8f04c386312449aeb5b878d
- Shade: 7626a88cabbc5337106cc0a8373be57d6fdfc711 (last change)
The logic is actually needed. The problem can be reproduced by configuring an invalid IP address for the bridge. This causes the bridge to be correctly marked as **OFFLINE**, but the shade/repeater things will be left in status **UNKNOWN**, when they should in fact also be **OFFLINE** with **BRIDGE_OFFLINE**.
> [hdpowerview] Fix regression when bridge is offline while initializing child things

- bundles/org.openhab.io.homekit/pom.xml
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitImpl.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitCharacteristicFactory.java
update to the latest java-hap library. 
the new java-hap release includes few bug fixes as well as support for new accessories like television, which can be made available to openhab. 
full change log https://github.com/hap-java/HAP-Java/releases/tag/hap-2.0.1
this PR only upgrades the library and makes following changes, required by the new release:
- add homekit category which was hard-coded previously in the hap library
- change rotation speed from int to double, which was wrong in previous hap lib. according to apple spec it must be double/float
plus small fix for bridge null check mentioned here https://github.com/openhab/openhab-addons/pull/12072#discussion_r792966654
> [homekit] update java hap library

- bundles/org.openhab.binding.danfossairunit/src/main/resources/OH-INF/i18n/danfossairunit.properties
- bundles/org.openhab.binding.danfossairunit/src/main/resources/OH-INF/thing/thing-types.xml
Related to #12262 
Use system channel types where possible:
- Relative humidity
- Outdoor temperature
Please note that openHAB needs to be restarted after updating the binding with new channel type id's.
See also: #11121
> [danfossairunit] Use system channel types for humidity and outdoor temperature

- bundles/org.openhab.binding.sonyprojector/src/main/resources/OH-INF/thing/channels.xml
> [sonyprojector] Fix tags for channel type powerstate

- bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/thing/channel-types.xml
> [openweathermap] Cleanup semantic tags

- bundles/org.openhab.binding.fronius/pom.xml
- bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/FroniusCommunicationException.java
- bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/FroniusHandlerFactory.java
- bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/FroniusHttpUtil.java
- bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/handler/FroniusBaseThingHandler.java
- bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/handler/FroniusBridgeHandler.java
- bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/handler/FroniusMeterHandler.java
- bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/handler/FroniusOhmpilotHandler.java
- bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/handler/FroniusSymoInverterHandler.java
- bundles/org.openhab.binding.fronius/src/main/resources/OH-INF/thing/bridge.xml
* HTTP Requests to the Fronius controller sometimes time out, causing the thing and bridge to go offline. This PR implements retry with delay to mitigate this issue.
* Synchronize access to the executeUrl command used to access Fronius controller which is used both by the bridge and the things. This avoids simultaneous requests to Fronius especially when multiple bridges are configured.
* Refactor the thinghandler (service) registration to use OpenHAB's built in mechanism. Remove disposed handlers from the bridge so that they are no longer refreshed.
* Trigger a refresh when a thing is added. This avoids a lengthy UNKNOWN state when the refresh interval is long.
> [fronius] Fix communication errors by retrying failed http requests

- bundles/org.openhab.binding.bluetooth.airthings/src/main/java/org/openhab/binding/bluetooth/airthings/internal/AbstractAirthingsHandler.java
Fixes #9862
Signed-off-by: Pawel Switalski <switalski.pw@gmail.com>
> [bluetooth.airthings] Catch all exceptions in a scheduled task to prevent future executions from being suppressed

- bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/DaikinWebTargets.java
- bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/BasicInfo.java
- bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/ControlInfo.java
- bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/EnergyInfoDayAndWeek.java
- bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/EnergyInfoYear.java
- bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/InfoParser.java
- bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/SensorInfo.java
- bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/airbase/AirbaseBasicInfo.java
- bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/airbase/AirbaseControlInfo.java
- bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/airbase/AirbaseModelInfo.java
- bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/airbase/AirbaseZoneInfo.java
- bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/discovery/DaikinACUnitDiscoveryService.java
- bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/handler/DaikinAcUnitHandler.java
- bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/handler/DaikinAirbaseUnitHandler.java
- bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/handler/DaikinBaseHandler.java
The Daikin thing often goes OFFLINE with COMMUNICATION_ERROR due to its HTTP request timing out. I tried increasing the time out to 10-15 seconds but that didn't help. It seems that the Daikin wifi adapter just choke from time to time.
* This PR implements retry with delay to mitigate this issue, which may fix #8373
* Some minor refactoring was done to organise the exception and thing status handling.
* Use urldecode/urlencode in InfoParser
* Operate on urldecoded string in AirbaseZoneInfo. Changed the separator from `%3b` to `;`
* A minor bug fix done in AirbaseZoneInfo to prevent out of bounds array access.
* Refactor url params handling to use Jetty's Request.param() instead of manually composing it
* Remove HttpUtil fallback
I understand that there is technical debt to be paid:
* The …
> [daikin] Fix communication errors by retrying failed http requests

- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitChangeListener.java
in the past homekit binding was updating configuration even for non-homekit items. 
this PR ensures that only items with homekit metadata gets marked as dirty for homekit binding. 
i also made the logging messages in this class consistent, starting with capital letter
> [homekit] mark item dirty only if it has homekit metadata

- bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/automation/AbsoluteDateTimeTriggerHandler.java
- bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/automation/TimerTriggerHandler.java
This prevents NPEs and a compilation issue when openhab/openhab-core#2763 is merged.
> [hueemulation] Provide non-null context to TriggerHandlerCallback

- bundles/org.openhab.binding.hdpowerview/README.md
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/HDPowerViewBindingConstants.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/HDPowerViewWebTargets.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/Color.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/requests/RepeaterColor.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/responses/RepeaterData.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewRepeaterHandler.java
- bundles/org.openhab.binding.hdpowerview/src/main/resources/OH-INF/i18n/hdpowerview.properties
- bundles/org.openhab.binding.hdpowerview/src/main/resources/OH-INF/thing/thing-types.xml
Fixes #12307
Add support for setting repeater LED color and brightness. The PowerView app has a few pre-defined colors, but this PR makes it possible to freely select any RGB color.
> [hdpowerview] Add support for setting repeater LED color and brightness

- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitChangeListener.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitImpl.java
there are many reports (almost since 2 years) about missing "user" entry in homekit.json which leads to repairing need. this issue was difficult to reproduce and often disappeared after some time. 
finally the root cause found  - different storage caches.
2 classes write to homekit.json storage:
- HomekitChangeListener writes number of accessories and configuration version 
- HomekitAuthInfoImpl writes "user" entry after device pairing
on binding start both classes got their own Storage instance via StorageService.getStorage("homekit.json") call. 
however, JsonStorageService.getStorage reads homekit.json every time into a new cache object (map) 
https://github.com/openhab/openhab-core/blob/44da7a4e0ee0b7b1f33c49f3f13f6cf9c2747058/bundles/org.openhab.core.storage.json/src/main/java/org/open …
> [homekit] fix "No Response" issue due missing pairing information

- bundles/org.openhab.binding.zoneminder/README.md
- bundles/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/internal/handler/ZmBridgeHandler.java
Binding wasn't handling the case where ZoneMinder is installed on the web server root directory.
> [zoneminder] Properly handle when zm installed on root directory

- bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/ChannelState.java
- bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/mapping/SubscribeFieldToMQTTtopic.java
- bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/mapping/MqttTopicClassMapperTests.java
- bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/internal/handler/HomieThingHandler.java
fixes #10711
technically this code is in mqtt.generic, but it's only used by Homie.
in particular, if an incoming string doesn't match an enum, this will now
just ignore the value instead of raising an exception to be caught somewhere inside
of Hive MQTT, and eventually timing out and logging that mandatory topics weren't
received, instead of logging a pointer to the actual problem. this makes it so that
if there's a homie $datatype openhab doesn't understand (like duration), it will be
able to get to the point of just choosing a string channel
also did some minor debug logging cleanup for mqtt:
* fixed a typo
* when logging homie device name from the thing handler, use the config deviceid,
since we likely don't have the attributes from MQTT yet
> [mqtt.homie] handle exceptions parsing attributes

- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewHubHandler.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewRepeaterHandler.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewShadeHandler.java
@jlaur @lolodomo @andrewfg If you set the Thing status of the bridge and the child Things to UNKNOWN in `initialize()` like in this PR, the framework takes care of the statuses of the child Things.
I tested this code and the behavior is now, after enabling the Bridge it will stay in UNKNOWN and will eventually turn to OFFLINE when the service is not reachable. The child Things will change to BRIDGE_OFFLINE. I couldn't test the ONLINE transition.
> [hdpowerview] Let the framework change the child Thing statuses

- bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/discovery/DanfossAirUnitDiscoveryService.java
- bundles/org.openhab.binding.danfossairunit/src/test/java/org/openhab/binding/danfossairunit/internal/DanfossAirUnitTest.java
Fix two issues:
```
[INFO] openhab-addons\bundles\org.openhab.binding.danfossairunit\src\main\java\org\openhab\binding\danfossairunit\internal\discovery\DanfossAirUnitDiscoveryService.java:[85,53] Unsafe interpretation of method return type as '@NonNull' based on the receiver type 'java.util.Enumeration<java.net.@NonNull NetworkInterface>'. Type 'java.util.Enumeration<E>' doesn't seem to be designed with null type annotations in mind
[INFO] openhab-addons\bundles\org.openhab.binding.danfossairunit\src\test\java\org\openhab\binding\danfossairunit\internal\DanfossAirUnitTest.java:[43,40] Unsafe interpretation of method return type as '@NonNull' based on substitution 'T=org.openhab.binding.danfossairunit.internal.@NonNull CommunicationController'. Declaring type 'org.mockito.Mockito' doesn't …
```
> [danfossairunit] Fix null annotation issues

- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/HDPowerViewWebTargets.java
Related to #10454.
Fix regression from #12323 - missed this SAT warning:
`An instanceof check is being performed on the caught exception.  Create a separate catch clause for this exception type.`
> [hdpowerview] Fix SAT warning

- .github/workflows/ci-build.yml
- pom.xml
This adds Java 17 to the GitHub Actions CI build matrix so we can make sure the build keeps working with both Java 11 and Java 17. It also updates the required Java version range used by the enforcer plugin so it is also possible to build with the supported Java versions.
> Add Java 17 to GHA CI build matrix

- bundles/org.openhab.binding.somfytahoma/README.md
- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/SomfyTahomaBindingConstants.java
- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/SomfyTahomaHandlerFactory.java
- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/discovery/SomfyTahomaItemDiscoveryService.java
- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaRainSensorHandler.java
- bundles/org.openhab.binding.somfytahoma/src/main/resources/OH-INF/i18n/somfytahoma.properties
- bundles/org.openhab.binding.somfytahoma/src/main/resources/OH-INF/thing/rainsensor.xml
This PR adds support for the Rain sensor thing as requested here:
https://github.com/openhab/openhab-addons/issues/11987
> [somfytahoma] added support for the Rain sensor thing

- bundles/org.openhab.binding.bluetooth.govee/src/main/java/org/openhab/binding/bluetooth/govee/internal/GoveeModel.java
- bundles/org.openhab.binding.bluetooth.govee/src/test/java/org/openhab/binding/bluetooth/govee/internal/GoveeModelTest.java
This patch enables detection of my Govee H5102, which identifies as "GVH5102_77E9", not "Govee H5102..", as expected in GoveeModel.
> [govee] fix Govee H5102 detection

- bundles/org.openhab.binding.openwebnet/README.md
- bundles/org.openhab.binding.openwebnet/pom.xml
- bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/OpenWebNetBindingConstants.java
- bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/OpenWebNetHandlerFactory.java
- bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetAutomationHandler.java
- bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetBridgeHandler.java
- bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetEnergyHandler.java
- bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetLightingHandler.java
- bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetScenarioHandler.java
- bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetThermoregulationHandler.java
- bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetThingHandler.java
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/i18n/openwebnet.properties
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/i18n/openwebnet_it.properties
This PR solves some issues related to Things synchronization when the associated bridge is initialized, for example at boot,  when it is re-enabled or when it reconnects to a BTicino gateway. In systems with many Things configured (+100), not all were synchronized properly and put ONLINE/OFFLINE.
Fixes: #11627. Fixes #11972. Fixes #11974.
It also fixes #11965: USB rollershutters blocked when a REFRESH command was sent to them.
openwebnet4j lib updated to latest: 0.7.1
Several tests performed successfully by power users on real systems with many Things configured (+100 things).
> [openwebnet] Fix Things synchronization at boot / reconnect

- itests/org.openhab.binding.modbus.tests/src/main/java/org/openhab/binding/modbus/tests/AbstractModbusOSGiTest.java
This workaround fixes the modbus itests.
See: https://ci.openhab.org/job/openHAB-Addons/640
It seems that the methods that were added to the `BaseThingHandler` in openhab/openhab-core#2773 have caused some class loading issues when creating mocks of ThingHandlers in the modbus itests:
```
java.lang.NoClassDefFoundError: org/openhab/core/thing/type/ChannelTypeUID
at org.mockito.codegen.ModbusPollerThingHandler$MockitoMock$1698831298.<clinit>(Unknown Source)
at jdk.internal.reflect.GeneratedSerializationConstructorAccessor6.newInstance(Unknown Source)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
at org.objenesis.instantiator.sun.SunReflectionFactoryInstantiator.newInstance(SunReflectionFactoryInstantiator.java:48)
at …
```
> [modbus] Add workaround to fix itests

- bundles/org.openhab.binding.somfytahoma/README.md
- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/discovery/SomfyTahomaItemDiscoveryService.java
This PR changes the severity of unsuported devices logging so it does not flood the log file.
Discussed here: https://github.com/openhab/openhab-addons/issues/12213
> [somfytahoma] changed the severity of unsuported devices logging

- bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/NukiHandlerFactory.java
- bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/dataexchange/NukiApiServlet.java
- bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/handler/AbstractNukiDeviceHandler.java
- bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/handler/NukiOpenerHandler.java
- bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/handler/NukiSmartLockHandler.java
Fixed bug mentionend in https://community.openhab.org/t/new-openhab2-binding-for-nuki-smart-locks/25940/186.
When user changes configuration property (unlatch in this case), openhab calls `initialize()` on Thing, but since configuration was only loaded in constructor, any changes user made will not take effect until openhab restart or reinstallation of binding.
I've also added logging of request received from bridge when handling callback, since I noticed some weird `NullpointerException`s in my logfile which were probably caused by invalid request, but without seeing the data sent it's hard to debug.
> [nuki] Fixed configuration reload on initialization

- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/InsightParser.java
- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoInsightHandler.java
- bundles/org.openhab.binding.wemo/src/test/java/org/openhab/binding/wemo/InsightParserTest.java
Fixes #12105
Continuation of #12120
Refactoring: Parsing of WeMo Insight Switch data string has been extracted to separate class:
- Improved robustness: Number of provided values is no longer fixed/assumed.
- Improved robustness: Non-numeric values could throw `NumberFormatException`.
- Reduced redundancy: Each conversion if only written once (in private methods).
- Unit tests are provided.
> [wemo] Refactor Insight Switch parser

- bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/JRubyScriptEngineConfiguration.java
Found a small issue when dealing with empty or erroneous data. Avoid injecting require statement when the script name is empty.
> [jrubyscripting] Filter out empty require options

- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewHubHandler.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewRepeaterHandler.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewShadeHandler.java
- bundles/org.openhab.binding.hdpowerview/src/main/resources/OH-INF/i18n/hdpowerview.properties
This PR is based on #12330.
@jlaur @andrewfg I made the following changes:
- Change the Thing status detail of the *bridge* to COMMUNICATION_ERROR. It was BRIDGE_OFFLINE, which is only intended for *child* Things showing they cannot go online, because their bridge is offline.
- Remove the configuration validation. This is done also for textual configuration from OH 3.3.0 on by using the XML constraints.
- Remove the check in the Things' `initialize()` if the Bridge type is correct. The UI doesn't let you configure a wrong type and the syntax of the .things file doesn't let you specify a wrong type either, because you can't even configure the binding ID for child Things. For example, use a Bridge of the LCN binding and configure a shade. The child Thing definition is ignored by the …
> [hdpowerview] Remove unnecessary init checks and fix Thing status detail 

- bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/handler/IpCameraHandler.java
These changes fix an issue reported on the forum here and some general bugs I noticed whilst looking over the users logs and the code:
https://community.openhab.org/t/ipcamera-blank-imageurl-channel/133457/14
Changes are:
1. Doorbird is not ONVIF so this stops the binding trying to connect with ONVIF.
2. Digest was reporting to the camera to `keep alive` the connection right before the binding closed the connection right before making a new connection. This appears to throw off the camera which only allows a single connection at a time for some Doorbird cameras.
3. When a non 200 OK reply came in like a 500 busy error code, the binding was trying to still capture a snapshot.
> [ipcamera] Fix Digest bug and Doorbird fixes.

- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/WemoUtil.java
- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoBaseThingHandler.java
- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoCoffeeHandler.java
- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoCrockpotHandler.java
- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoDimmerHandler.java
- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoHandler.java
- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoHolmesHandler.java
- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoLightHandler.java
- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoMakerHandler.java
- Consolidate host initialization/caching in `WemoBaseThingHandler`.
- Simplify usage of `getWemoURL` and remove redundant error handling.
> [wemo] Simplify getWemoURL usages in handlers

- bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/DeconzDynamicStateDescriptionProvider.java
- bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/DeconzBridgeHandler.java
Fix one (only remaining) compiler warning:
**DeconzDynamicStateDescriptionProvider.java:**
```
[WARNING] openhab-addons\bundles\org.openhab.binding.deconz\src\main\java\org\openhab\binding\deconz\internal\DeconzDynamicStateDescriptionProvider.java:[62,55] Potential null pointer access: this expression has a '@Nullable' type
```
And two compiler info:
**DeconzBridgeHandler.java:**
```
[INFO] openhab-addons\bundles\org.openhab.binding.deconz\src\main\java\org\openhab\binding\deconz\internal\handler\DeconzBridgeHandler.java:[178,24] Unsafe null type conversion (type annotations): The value of type 'java.util.@NonNull Optional<org.openhab.binding.deconz.internal.dto.@NonNull BridgeFullState>' is made accessible using the less-annotated …
```
> [deconz] Fix compiler warning

- bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/PulseAudioAudioSource.java
- bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/handler/PulseaudioBridgeHandler.java
- bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/handler/PulseaudioHandler.java
@lolodomo this is a small change to ensure the bg task for the source stops if no more streams are open.
I don't know how this can happen but it happened for me once.
Also includes a fix for null pointer exception that is raised when you have a Sink/Source with the register of the openHAB Sink/Source option enabled, and it is not offline (disconnected from the pulseaudio server).
I discover this earlier when I change the speaker for a new one, a Jabra I bought from amazon warehouse.
> [pulseaudio] fix null pointer exception and ensure source bg task stops

- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoCoffeeHandler.java
- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoCrockpotHandler.java
- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoDimmerHandler.java
- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoHandler.java
- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoHolmesHandler.java
- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoLightHandler.java
- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoMakerHandler.java
- itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/handler/test/WemoHandlerOSGiTest.java
- itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/handler/test/WemoLightHandlerOSGiTest.java
- itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/handler/test/WemoMakerHandlerOSGiTest.java
Fixes #12415
Previously transitions for a turned off device would be:
```
2022-03-04 22:11:46.481 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'wemo:insight:insight1' changed from UNINITIALIZED (HANDLER_MISSING_ERROR) to INITIALIZING
2022-03-04 22:11:46.505 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'wemo:insight:insight1' changed from INITIALIZING to ONLINE
2022-03-04 22:11:57.366 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'wemo:insight:insight1' changed from ONLINE to ONLINE (CONFIGURATION_PENDING): UPnP device is not registered yet.
```
Now:
```
2022-03-04 22:25:21.030 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'wemo:insight:insight1' changed from UNINITIALIZED (HANDLER_MISSING_ERROR) …
```
> [wemo] Fix thing status transitions

- bundles/org.openhab.binding.rfxcom/README.md
- bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComFanMessage.java
- bundles/org.openhab.binding.rfxcom/src/main/resources/OH-INF/thing/fan_lucci_dc.xml
- bundles/org.openhab.binding.rfxcom/src/main/resources/OH-INF/thing/fan_novy.xml
Add support for speed for the regular Lucciair DC Fan
See also: https://community.openhab.org/t/rfxcom-add-on-support-for-lucciair-dc-speed-1-to-6/131625
> [rfxcom] Support for Lucciair DC Speed

- bundles/org.openhab.binding.fronius/README.md
Add the documentation for the channels that were added in #10757
> [fronius] Add the new channels to the documentation

- .github/workflows/ci-build.yml
- README.md
* Add error annotations only in Java 11 matrix build to prevent duplicates
* Make sure Java 11 build is not cancelled when Java 17 build fails so it can add annotations by using `fail-fast: false`
* Use changed files only for incremental PR builds so a full build is done for changes merged into 'main' branch
* Add GHA build status badge
> GHA CI build workflow improvements

- bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/type/HomematicTypeGeneratorImpl.java
Sometimes invalid default values ended up in the default value for a channel of a thing type. Initializing the thing would fail completely complaining that it is not an allowed option. This patch makes sure those values are actually valid and attempts to correct them if they are invalid.
This fixes a regression introduced by the core now checking validity of values even from text-based configs.
> [homematic] Fix invalid default values ending up in the thing type

- bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/CcuGateway.java
The CCU does not accept exponential notation in TCL scripts.
Fix #12301
> [homematic] Prevent the use of exponential notation

- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitCharacteristicFactory.java
this is especially important if you use the same item for both
TargetTemperature and HeatingThresholdTemperature characteristics,
since the former was already doing unit conversion for min/max.
> [homekit] do unit conversion for min/max heating/cooling temps

- bundles/org.openhab.binding.pushover/README.md
I have requested openHAB as a featured integration for pushover via support and it got accepted.
So we are listed on their website now and have a cloneable application.
(This is basically just a prefilled website form including the openHAB logo.)
Therefore i added a little paragraph including the clone url.
Signed-off-by: Jerome Luckenbach <github@luckenba.ch>
> [pushover] Add featured integration paragraph

- itests/org.openhab.binding.astro.tests/itest.bndrun
- itests/org.openhab.binding.avmfritz.tests/itest.bndrun
- itests/org.openhab.binding.feed.tests/itest.bndrun
- itests/org.openhab.binding.hue.tests/itest.bndrun
- itests/org.openhab.binding.max.tests/itest.bndrun
- itests/org.openhab.binding.mielecloud.tests/itest.bndrun
- itests/org.openhab.binding.modbus.tests/itest.bndrun
- itests/org.openhab.binding.nest.tests/itest.bndrun
- itests/org.openhab.binding.ntp.tests/itest.bndrun
- itests/org.openhab.binding.systeminfo.tests/itest.bndrun
- itests/org.openhab.binding.tradfri.tests/itest.bndrun
- itests/org.openhab.binding.wemo.tests/itest.bndrun
- itests/org.openhab.persistence.mapdb.tests/itest.bndrun
- pom.xml
This brings the build tools to the same versions as in core.
See: https://github.com/openhab/openhab-core/pull/2836
> bump compiler tooling

- CODEOWNERS
The mielecloud.tests dir is missing from the CODEOWNERS file.
> Add mielecloud.tests to CODEOWNERS file

- CODEOWNERS
- bom/openhab-addons/pom.xml
- bundles/org.openhab.binding.prowl/NOTICE
- bundles/org.openhab.binding.prowl/README.md
- bundles/org.openhab.binding.prowl/pom.xml
- bundles/org.openhab.binding.prowl/src/main/feature/feature.xml
- bundles/org.openhab.binding.prowl/src/main/java/org/openhab/binding/prowl/internal/ProwlBindingConstants.java
- bundles/org.openhab.binding.prowl/src/main/java/org/openhab/binding/prowl/internal/ProwlConfiguration.java
- bundles/org.openhab.binding.prowl/src/main/java/org/openhab/binding/prowl/internal/ProwlHandler.java
- bundles/org.openhab.binding.prowl/src/main/java/org/openhab/binding/prowl/internal/ProwlHandlerFactory.java
- bundles/org.openhab.binding.prowl/src/main/java/org/openhab/binding/prowl/internal/action/ProwlActions.java
- bundles/org.openhab.binding.prowl/src/main/resources/OH-INF/binding/binding.xml
- bundles/org.openhab.binding.prowl/src/main/resources/OH-INF/i18n/prowl.properties
- bundles/org.openhab.binding.prowl/src/main/resources/OH-INF/thing/thing-types.xml
- bundles/pom.xml
This is the binding for the Prowl (https://www.prowlapp.com) iOS push service.  
It has been written from scratch and therefore it is not based on the original 1.x Prowl binding.  
It has no other purpose than sending push messages to iOS devices.
> [prowl] Initial contribution

- bundles/org.openhab.binding.mail/src/test/java/org/openhab/binding/mail/MailBuilderTest.java
- bundles/org.openhab.binding.mail/src/test/resources/attachment.txt
When a URL attachment is used a check is done if an InputStream to the URL can be opened to see if it is valid.
Because the openHAB website was used the test would fail when the website has issues:
```
[ERROR]  org.openhab.binding.mail.MailBuilderTest.withURLAttachmentReturnsMultiPartEmail  Time elapsed: 10.391 s  <<< ERROR!
org.apache.commons.mail.EmailException: Invalid URL set:http://www.openhab.org
at org.openhab.binding.mail.MailBuilderTest.withURLAttachmentReturnsMultiPartEmail(MailBuilderTest.java:77)
Caused by: java.io.IOException: Server returned HTTP response code: 520 for URL: http://www.openhab.org
at org.openhab.binding.mail.MailBuilderTest.withURLAttachmentReturnsMultiPartEmail(MailBuilderTest.java:77)
```
It will now use a file URL instead so it no longer depends on a …
> [mail] Fix unstable MailBuilderTest

- bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/handler/AbstractBrokerHandler.java
- bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/handler/BrokerHandler.java
- bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/internal/MqttBrokerHandlerFactory.java
- bundles/org.openhab.binding.mqtt/src/test/java/org/openhab/binding/mqtt/handler/BrokerHandlerTest.java
- bundles/org.openhab.binding.mqtt/src/test/java/org/openhab/binding/mqtt/internal/MQTTTopicDiscoveryServiceTest.java
The MqttService was used to keep track of the system MQTT brokers.
Since there are none the dependency can be removed.
Related to: openhab/openhab-core#2842
See also: #12157
> [mqtt] Remove MQTT system broker leftovers

- bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/PulseAudioAudioSource.java
Use thread safe collection for storing the source pipe output references.
Also added a forced disconnection after the 3 consecutive IOExceptions while reading the socket input to force a reconnection.
Possible fix for https://github.com/openhab/openhab-addons/issues/12432.
@lolodomo can you try to reproduce the error with this version?
> [pulseaudio] source: use thread safe collection and force reconnection

- bundles/org.openhab.binding.renault/src/main/java/org/openhab/binding/renault/internal/api/Constants.java
Signed-off-by: Doug Culnane <doug@culnane.net>
I and 2 other users have had connection errors. See: (https://community.openhab.org/t/betatest-renault-ze-services-binding/72226/190?u=doug_culnane)
The API key has changed which it does every year apparently... So I used the new key that the python developers have extracted:
https://github.com/hacf-fr/renault-api/commit/03f4dbd9f27dc84aa748510892fbb3f55eed0f1d
This worked on my installation.
I will submit a pull request with this as a configuration variable with the default being the current key.  This will allow easier updating of running systems in the future.
> [renault] API key update.

- bundles/org.openhab.binding.openwebnet/README.md
- bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/OpenWebNetBindingConstants.java
- bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetThermoregulationHandler.java
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusThermoCentralUnit.xml
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/channels.xml
Enhance OpenWebNet binding to support thermoregulation with 4/99 zone central unit, e.g. BTicino 3550 model.
The Central Unit provides some information on the on-board display:
- at least one probe in OFF mode (WHAT = AT_LEAST_ONE_PROBE_OFF)
- at least one probe in PROTECTION mode (WHAT = AT_LEAST_ONE_PROBE_ANTIFREEZE)
- at least one probe in MANUAL mode (WHAT = AT_LEAST_ONE_PROBE_MANUAL)
- a generic FAILURE was detected on the system (WHAT = FAILURE_DISCOVERED)
For each case a specific read-only channel was added.
> [openwebnet] handle Thermo Central Unit monitoring messages

- bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/slip/io/Connection.java
- bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/slip/io/DataInputStreamWithTimeout.java
- bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/slip/io/Poller.java
- bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/handler/VeluxBridgeHandler.java
Potentially fixes #12327
This PR addresses the issues discussed in #10454 and #12327 in a further attempt to solve the KLF200 'zombie state' problem.
Two things have been improved..
- Added an isDisposing flag so that the binding can shut down faster if it was already in a zombie state.
- Refactored the code that reads messages from the KLF200 to handle `InterruptedException` , `ExecutionException`, and `IOException` more properly and completely.
> [velux] Improve shutdown exception handling

- bundles/org.openhab.binding.openwebnet/README.md
- bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetBridgeHandler.java
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/GenericDevice.xml
Fixed `generic_device` thing-type (used when a BTicino device cannot be recognized) and added a time limit to devices refresh at boot/reconnect.
> [openwebnet] fixed generic_device thing-type, improved refresh at boot

- bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetThermoregulationHandler.java
Thermo things are refreshed 2 times at boot/reconnect, first from bridge then from Thermo handler (in bridgeStatusChanged()).
See issue https://github.com/openhab/openhab-addons/issues/12490
> [openwebnet] removed (duplicate) refreshDevice() at bridgeStatusChanged

- bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/Locations.java
Previous PR reduced http request rate/load by enabling incremental updates from the PlugwiseHA API. This PR fixes a situation that was overlooked in that PR. This bug made it impossible to set the thermostat for a zone.
> [plugwiseha] Fix Zone thermostat not updating

- bundles/org.openhab.binding.openwebnet/pom.xml
- bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetThermoregulationHandler.java
Objective:
Enhance OpenWebNet binding to support thermoregulation with 4/99 zone central unit, e.g. BTicino 3550 model.
Changelog
- fix read setTemp (MANUAL mode) at startup
- fix read mode (OFF/PROTECTION/WEEKLY/SCENARIO/MANUAL) at startup
- fix https://github.com/openhab/openhab-addons/issues/12401
- fix https://github.com/openhab/openhab-addons/issues/12417
It requires Own4j version 0.8.1
> [openwebnet] fixing support for central unit

- bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaSSOHandler.java
According to https://github.com/timdorr/tesla-api/issues/548, step 4 from https://tesla-api.timdorr.com/api-basics/authentication is not required anymore (and effectively not working). This PR removes this access token exchange and thus fixes the broken authentication flow.
Fixes #12516
> [tesla] Adapt access token handling to changes in Tesla API

- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/KNXBindingConstants.java
- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/KNXTypeMapper.java
- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/channel/AbstractSpec.java
- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/channel/ListenSpecImpl.java
- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/AbstractKNXClient.java
- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/CustomKNXNetworkLinkIP.java
- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/DeviceInspector.java
- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/SerialClient.java
- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/config/BridgeConfiguration.java
- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/config/DeviceConfig.java
- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/config/IPBridgeConfiguration.java
- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/config/SerialBridgeConfiguration.java
- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/factory/KNXHandlerFactory.java
- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/AbstractKNXThingHandler.java
- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/DeviceConstants.java
- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/DeviceThingHandler.java
- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/IPBridgeThingHandler.java
- bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/channel/KNXChannelTypeTest.java
- bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/dpt/KNXCoreTypeMapperTest.java
added NonNullByDefault annotations
rename functions and local variables not matching the naming scheme
> [knx] Reduce compiler warnings

- bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/connector/telnet/DenonMarantzTelnetConnector.java
- bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/xml/adapters/StringAdapter.java
Remove usage of org.apache.commons.lang3.StringUtils per #7722
> [denonmarantz] Remove Apache StringUtils

- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/DeviceUtil.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/MieleGatewayCommunicationController.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/discovery/MieleApplianceDiscoveryService.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/ApplianceChannelSelector.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/ApplianceStatusListener.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/CoffeeMachineChannelSelector.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/CoffeeMachineHandler.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/DiscoveryListener.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/DishWasherHandler.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/DishwasherChannelSelector.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/FridgeChannelSelector.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/FridgeFreezerChannelSelector.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/FridgeFreezerHandler.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/FridgeHandler.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/HobChannelSelector.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/HoodChannelSelector.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/HoodHandler.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/MieleApplianceHandler.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/MieleBridgeHandler.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/OvenChannelSelector.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/OvenHandler.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/TumbleDryerChannelSelector.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/TumbleDryerHandler.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/WashingMachineChannelSelector.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/WashingMachineHandler.java
- bundles/org.openhab.binding.miele/src/main/resources/OH-INF/i18n/miele.properties
This pull request contains various fixes and optimizations for the Miele@home binding. These issues were discovered by analyzing the code, backed up by manual testing as proof. See also #12504 for findings. Please read this PR commit by commit for better understanding.
- Appliance configuration is now validated: Missing or empty UID will now result in status **OFFLINE** with **CONFIGURATION_ERROR**.
- Appliances removed from bridge (i.e. non-existent appliances) are now marked as **OFFLINE** with **GONE**. Previously they were marked as **ONLINE**.
- An unneeded call to the Miele gateway every 15 seconds has been removed. This call received a payload of almost 6 KB.
- Appliance handlers are no longer notified about updates for other appliances. Everything was broadcasted and each handler …
> [miele] Fix configuration validation and optimize performance

- bundles/org.openhab.binding.openthermgateway/src/main/java/org/openhab/binding/openthermgateway/handler/OpenThermGatewayHandler.java
- bundles/org.openhab.binding.openthermgateway/src/main/java/org/openhab/binding/openthermgateway/internal/OpenThermGatewayCallback.java
- bundles/org.openhab.binding.openthermgateway/src/main/java/org/openhab/binding/openthermgateway/internal/OpenThermGatewaySocketConnector.java
- bundles/org.openhab.binding.openthermgateway/src/main/resources/OH-INF/thing/openthermgateway.xml
This PR addresses one potential issue, and makes a few slight improvements as follows..
- As described in #12457 there was a risk of sending new commands before the gateway had finished processing prior commands. Now all commands are pipelined via a FIFO queue to prevent that.
- Added a Thing Property to display the OpenTherm Gateway identification / version string.
- Now a `logger.warn()` message is reported if the gateway watchdog timer triggers a self reset.
- Improved `logger.trace()` reporting of messages read from / written to, the OpenTherm Gateway.
- Bumped the binding version property.
Closes #12457
> [openthermgateway] Various improvements

- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/MieleGatewayCommunicationController.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/MieleHandlerFactory.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/MieleApplianceHandler.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/MieleBridgeHandler.java
Resolves #12544
Replaces custom implementation in binding with the framework's Jetty HTTP client.
Additionally fails faster in case of HTTP failures instead of trying to parse invalid response content (e.g. HTML) as JSON.
> [miele] Use framework's HTTP client

- bundles/org.openhab.binding.pulseaudio/README.md
As seen [on the community forum](https://community.openhab.org/t/pulseaudio-thing-initialization-during-startup-to-early-and-therefore-causing-an-exception/134657) by a user encountering an issue, the configuration file example in the pulseaudio README has an error with the parameter activateSimpleProtocolSink
> [pulseaudio] Fix misconfiguration example in README

- bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/JRubyScriptEngineFactory.java
Remove hard coded list of scoped global variables and use a more generic criteria. This will allow introduction of other / new scoped variables whose names are not already in the hard coded list.
> [jrubyscripting] Accept generic global variable names

- bundles/org.openhab.binding.networkupstools/src/test/java/org/openhab/binding/networkupstools/internal/nut/NutApiTest.java
- bundles/org.openhab.binding.networkupstools/src/test/resources/org/openhab/binding/networkupstools/internal/nut/var_get_commands.txt
- bundles/org.openhab.binding.networkupstools/src/test/resources/org/openhab/binding/networkupstools/internal/nut/var_list_commands.txt
On Windows the `PrintWriter` used in the `NutConnector` adds different line endings causing some tests to fail.
--- 
Do you know if NUT can handle Windows line endings @Hilbrand? If not, the implementation should be fixed instead.
> [networkupstools] Fix NutApiTest failing on Windows

- bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/handler/HomematicThingHandler.java
- bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/model/HmDatapoint.java
HM config datapoint values on some devices can be out of their valid
range in some cases, particularly if they are unused by the device
currently. Since openhab-core now validates attempts to update
configuration by the thing handlers, make sure we always send a valid
configuration even for those affected datapoints.
One example for such behaviour is HmIPW-DRBL4, which has multiple datapoints which depend on each other:
- POWERUP_JUMPTARGET can have values OFF, ON, OFF_DELAY, ON_DELAY
- POWERUP_ONDELAY_VALUE, POWERUP_ONDELAY_UNIT are only used if POWERUP_JUMPTARGET has value ON_DELAY
- likewise, POWERUP_OFFDELAY_VALUE and POWERUP_OFFDELAY_UNIT are only used if POWERUP_JUMPTARGET has value OFF_DELAY
- if e.g. the POWERUP_JUMPTARGET is OFF, e.g. POWERUP_ONDELAY_VALUE might stay …
> [homematic] Validate datapoint values before writing to config

- bundles/org.openhab.voice.marytts/src/main/java/org/openhab/voice/marytts/internal/MaryTTSAudioStream.java
With this fix, MaryTTS creates the correct wav header for the audio inputstream (audioformat is now assigned before we use it in the method 'getWavHeaderInputStream')
This bug was detected [in a community post](https://community.openhab.org/t/pulseaudio-as-sink-is-playing-back-way-to-fast/129349/6), and the sound was playing too fast.
I made [a snapshot release](https://github.com/dalgwen/openhab-addons/releases/tag/3.3.0_SNAPSHOT-marytts_wav_header).
> [marytts] Fix incorrect WAV header for some voices

- bundles/org.openhab.binding.senechome/src/main/java/org/openhab/binding/senechome/internal/SenecHomeHandler.java
Looks like the new generation of SenecIES power storage systems, which are using LiPo technology, provide additional data in the JSON array.
This data is not available in the old generation, which lead to missing data, when asking for a key and in further null pointer exceptions when going deeper in the data structure.
Therefore making a trivial check to detect the new generation of devices and skip the troubling section entirely.
CON: The section of items would not be updated. A to-do is of course to split the old and new generation into separate models of devices.
Fixes https://github.com/openhab/openhab-addons/issues/11606
Also-By: Erwin Guib <eguib@web.de>
Signed-off-by: Thomas Karl Pietrowski <thopiekar@gmail.com>
Signed-off-by: Korbinian Probst <kp.droid.dev@gmail.com>
> [senechome] Avoid null pointer errors

- bundles/org.openhab.binding.openthermgateway/src/main/java/org/openhab/binding/openthermgateway/internal/OpenThermGatewayBindingConstants.java
- bundles/org.openhab.binding.openthermgateway/src/main/java/org/openhab/binding/openthermgateway/internal/OpenThermGatewayHandlerFactory.java
The binding now outputs a warning message in the log if trying to create a legacy `otgw` Thing type.
> [openthermgateway] Log warning if trying to create a legacy Thing type

- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/AbstractKNXClient.java
> [knx] handle exceptions during initial read

- bundles/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/internal/discovery/EpsonProjectorDiscoveryService.java
- bundles/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/internal/discovery/MulticastListener.java
Fix an issue with the Epson binding creating erroneous inbox items when AMX discovery beacon packets from other devices (GlobalCache, etc) are received. The code was improved to ignore non Epson discovery beacon packets and will handle multiple Epson projectors on the network properly (thread safe).
First discovered in this post: https://community.openhab.org/t/is-the-epson-projector-binding-abandoned/107769/82
> [epsonprojector] Fix discovery service to prevent erroneous inbox items

- bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaVehicleHandler.java
I just experienced a deadlock situation due to this synchronization here.
The `BaseThingHandler` does a synchronize on `this` within `updateState()` - this means that handler implementations must not do the same, if they also use other kinds of locks. 
Since the method in question is only called at a define interval from a job within the binding, the synchronization is not necessary at this place. Therefore removing it should fix the deadlock situations.
> [tesla] Remove synchronization to avoid deadlocks

- bundles/org.openhab.transform.map/src/main/java/org/openhab/transform/map/internal/MapTransformationService.java
- bundles/org.openhab.transform.map/src/test/java/org/openhab/transform/map/internal/MapTransformationServiceTest.java
Related to https://github.com/openhab/openhab-core/pull/2821
This is the reference implementation for using the new `TransformationConfigurationRegistry`. The localization tests can be omitted as this is covered by tests in the core component.
For configurations stored in the `transform` directory this is fully backward compatible to the old implementation.
> [transform.map] Refactor service to use TransformationConfigurationRegistry

- bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosXMLParser.java
- bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/discovery/ZonePlayerDiscoveryParticipant.java
- bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/handler/ZonePlayerHandler.java
- bundles/org.openhab.binding.sonos/src/test/java/org/openhab/binding/sonos/internal/SonosXMLParserTest.java
Transform the found model name into a valid thing type ID  when trying 
to match a thing type
This could avoid an `IllegalArgumentException` thrown by the discovery
service when new models will be introduced on the market.
Should be compatible with Bubble UPnP Server which modifies the model
name
A message is now logged for unsupported Sonos models.
> [sonos] Discovery of unsupported models without exception

- bundles/org.openhab.binding.tapocontrol/README.md
This PR adds a note to the TapoControl documentation on the requirement for the P110 to successfully complete an NTP request prior to it exposing its power and energy data to the binding.
> [TapoControl] Added guidance for internet isolation of P110

- bundles/org.openhab.binding.omnilink/README.md
- bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/OmnilinkHandlerFactory.java
- bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/action/OmnilinkActions.java
- bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/OmnilinkBridgeHandler.java
- bundles/org.openhab.binding.omnilink/src/main/resources/OH-INF/i18n/omnilink.properties
- bundles/org.openhab.binding.omnilink/src/main/resources/OH-INF/thing/bridge.xml
> [OmniLink] Fix daylight savings when setting date/time

- bundles/org.openhab.binding.upnpcontrol/src/main/java/org/openhab/binding/upnpcontrol/internal/queue/UpnpEntryRes.java
According to the UPnP standard, res should always contain protocolInfo. Some devices do not respect this standard in their AVTransport implementation. To avoid null pointer exceptions, take care of this special case.
> [upnpcontrol] Fix null pointer exception for invalid protocolInfo

- bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/handler/NuvoHandler.java
The binding has a typo in detecting grand concerto systems - I noticed this because my clock was not being set correctly.  This PR fixes the typo and also adds debug logging to determine if a GC is detected or not.
> [nuvo] Fix Nuvo Grand Concerto Detection

- bundles/org.openhab.binding.mail/pom.xml
- bundles/org.openhab.binding.mail/src/3rdparty/java/javax/activation/PatchedMailcapCommandMap.java
- bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/internal/SMTPHandler.java
Originally by @J-N-K fixed in smarthomej/addons
https://github.com/smarthomej/addons/pull/254
Reported on the forum.
https://community.openhab.org/t/mail-binding-errors-sending-mail-unsupporteddatatypeexception-text-plaijn-charset-utf-8/130365
The reason is that the standard implementation uses a context class loader to get the mime type handlers and tries to load the handlers from there. Under some circumstances this is the class loader of the activation bundle which does doesn't have the com.sun.mail packages available, leading to an javax.activation.UnsupportedDataTypeException: text/plain; charset=UTF-8 exception.
Fixes #11838
Also Signed-off-by: Jan N. Klug <jan.n.klug@rub.de>
> [mail] Fix UnsupportedDataTypeException

- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/WemoBindingConstants.java
- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/WemoHandlerFactory.java
- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/WemoUtil.java
- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoBaseThingHandler.java
- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoCoffeeHandler.java
- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoCrockpotHandler.java
- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoDimmerHandler.java
- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoHandler.java
- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoHolmesHandler.java
- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoInsightHandler.java
- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoLightHandler.java
- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoMakerHandler.java
- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoMotionHandler.java
- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoSwitchHandler.java
- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/http/WemoHttpCall.java
- itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/handler/test/WemoInsightHandlerTest.java
- itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/test/GenericWemoOSGiTest.java
Fixes #12615
After losing and recovering network connectivity, the WeMo UPnP devices are lost and not automatically rediscovered. This PR fixes that by starting discovery when participant is no longer registered. After device has successfully been rediscovered, subscriptions are renewed.
This issue seems to go all the way back to:
https://community.openhab.org/t/could-not-make-http-call-to-wemo-binding-does-not-rediscover-after-starting/53783/4
> [wemo] Fix UPnP resubscription after lost network connection

- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoBaseThingHandler.java
Additional optimization after #12648.
For each request to be made to a WeMo device, up to seven requests are made prior to the actual request in order to determine the correct port. In most cases the port from the descriptor is the right one, so by verifying this one first, we can avoid some unneeded traffic and perform the real call faster.
The port scanning approach origins from #6253 and is left intact as only the port **order** is changed.
> [wemo] Optimize port detection

- bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/handler/ICloudDeviceHandler.java
This minor patch fixes an issue when the device response status code is 203.
This seems to work, but I don't know if this is enough/acceptable. Devices reports 203 status sometimes when they are online, sometimes when they are offline. However there seems to be another status code (201) for offline devices.
I couldn't find any info online what these status codes mean, nor any other reported value which can indicate the real status of an iCloud device.
Closes #12501
> [icloud] Fix ONLINE state when device response status is 203

- .gitignore
This is sometimes added by IntelliJ when importing a project.
> Add .gradle to .gitgnore

- bundles/org.openhab.binding.ipp/pom.xml
- bundles/org.openhab.binding.logreader/pom.xml
- bundles/org.openhab.voice.marytts/pom.xml
This brings commons-io in-line with version in core.
Exclusion of `sun.nio.ch.*` is safe because it is only needed for classes available since 2.9.0 (which is above the version used before)
> Bump commons-io

- bundles/org.openhab.binding.orbitbhyve/src/main/java/org/openhab/binding/orbitbhyve/internal/handler/OrbitBhyveBridgeHandler.java
This PR fixes a rare bug when the bridge sets the sprinkler's status to ONLINE/OFFLINE even if the sprinkler is disabled.
> [orbitbhyve] do not update status of a disabled sprinker

- bundles/org.openhab.binding.goecharger/README.md
- bundles/org.openhab.binding.goecharger/src/main/resources/OH-INF/thing/thing-types.xml
category before state in thing-types.xml (Fixes #12661)
remove warning within readme.md
Signed-off-by: Reinhard Plaim <reinhardplaim@gmail.com>
> [goecharger] fix issue with category

- bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/HomeConnectBridgeHandler.java
> [homeconnect] Ignore disabled things

- bundles/org.openhab.binding.openweathermap/README.md
Removed first section from README.
These are not rendered in the online documentation and make the inline documention (More...) of the binding inside OH error out and show the raw text.
Signed-off-by: Mark Herwege [mark.herwege@telenet.be](mailto:mark.herwege@telenet.be)
> [openweathermap] Update README.md

- CODEOWNERS
> Update KNX code owner

- bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/handler/OpenWeatherMapOneCallHandler.java
Signed-off-by: Hans Böhm <h.boehm@gmx.at>
This fixes an issue where the last alert in the API response is always ignored. Also discussed in [the forum](https://community.openhab.org/t/openweathermap-new-one-call-api/101419/45).
> [openweathermap] Fix display of alert data

- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/channelhelper/EventChannelHelper.java
> [netatmo] Give access to video only when video is available

- bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/http/HttpResponseListener.java
- bundles/org.openhab.binding.http/src/test/java/org/openhab/binding/http/internal/http/HttpResponseListenerTest.java
- bundles/org.openhab.binding.http/src/test/resources/simplelogger.properties
Until now, the http binding did only regard the `HTTP/200 OK` response code as successful, all the other 2xx codes were treated as failed. This behaviour made it impossible to work with non-trivial REST APIs that may return "HTTP/201 Created" or "HTTP/204 No Content".
I thought about simply extending the switch-case with all to other 2xx constant from `HttpStatus`, but that felt cumbersome. I am not really happy that the switch now only has one case and a default left, but I kept it this way (instead of dissolving it into the outer `if-elseif-else`) to keep the possibility for future special-handling of specific return codes.
I also removed that content null check, because `getContent()` never returns null; it always returns a byte-array (which may has the length 0).
Fixes #11369
> [http] Support all 2xx response codes

- bundles/org.openhab.binding.knx/README.md
- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/channel/KNXChannelType.java
- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/KNXCoreTypeMapper.java
- bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/dpt/KNXCoreTypeMapperTest.java
Items with dimensions (QuantityType) are now translated and can be sent to the
KNX bus. This requires the correct DPT to be specified in the channel
definition. Fixes #10706.
> [knx] Allow sending items with units to KNX bus.

- bundles/org.openhab.binding.openwebnet/README.md
- bundles/org.openhab.binding.openwebnet/pom.xml
- bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/OpenWebNetBindingConstants.java
- bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/OpenWebNetHandlerFactory.java
- bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/discovery/OpenWebNetDeviceDiscoveryService.java
- bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetAuxiliaryHandler.java
- bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetBridgeHandler.java
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusAux.xml
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/channels.xml
- bundles/org.openhab.binding.openwebnet/src/test/java/org/openhab/binding/openwebnet/internal/handler/OwnIdTest.java
This PR adds initial Auxiliary (AUX) message support to the binding (WHO=9) for sending AUX messages.
This PR closes #11515.
This PR adds support for sending Auxiliary (AUX) WHO=9 messages to the Open Web Net binding.
With this addition BTicino BUS AUX (WHO=9) messages can be sent from OH3 allowing, for example, to control alarm systems of a BTicino installation.
Configuration for new things and channels has been added to the add-on README.
Tested on BTicino/Legrand bulgrar-alarm unit 3486
> [openwebnet] Add support for  sending Auxiliary (AUX) commands/messages to the bus (WHO=9)

- bundles/org.openhab.binding.elroconnects/src/main/java/org/openhab/binding/elroconnects/internal/util/ElroConnectsUtil.java
Thing names longer than 15 characters caused a index out of bound exception when syncing the name with the name in the elro system.
> [elroconnects] Correct error for long thing names

- bundles/org.openhab.binding.lutron/src/main/resources/OH-INF/thing/thing-types.xml
> [lutron] Fix item-type tag value for channel type buttonpress

- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/DishWasherHandler.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/WashingMachineHandler.java
This is another iteration #11417 regarding extended device state.
A wrong assumption about the minimum amount of data being available in **ExtendedDeviceState** has been revealed after receiving data from an older appliance model.
Accordingly, logging has been fixed to more accurately describe this issue and log level has been reduced to **DEBUG**.
> [miele] Fix logging for appliances where consumption data is not supported

- bundles/org.openhab.binding.nest/README.md
- bundles/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/sdm/api/PubSubAPI.java
- bundles/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/sdm/api/SDMAPI.java
By default, the Google OAuth API returns the refresh token only on the first authorization. On subsequent authorizations using the same Client ID and Secret, Google does not return the refresh token in the access token response. This causes the binding to fail on the first refresh of the access token after a reauthorization.
This affects the SDM and Pub/Sub APIs. However, the failure is more spectacular with the Pub/Sub API as it causes the binding to repeatedly do a pub/sub request against the Google API every 20-40 msec.
This PR adds a new query parameter (prompt=consent) to the URL used to get the authorization code. This parameter causes Google to always return the refresh token in the authorization response (via `oAuthService.getAccessTokenResponseByAuthorizationCode`).
In addition, …
> [nest] Fix for missing refresh token after reauthorization

- bundles/org.openhab.binding.goecharger/src/main/java/org/openhab/binding/goecharger/internal/api/GoEStatusResponseV2DTO.java
- bundles/org.openhab.binding.goecharger/src/main/java/org/openhab/binding/goecharger/internal/handler/GoEChargerBaseHandler.java
Also avoid the thing to remain in state UNKNOWN if the decoding of the JSON response is failing.
Fix #12719
> [goecharger] Fix compatibility with go-eCharger V3

- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/database/ShadeCapabilitiesDatabase.java
Add type 38 shade to capabilities database
> [hdpowerview] Add Silhouette Duolite (shade type 38) to capabilities database

- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/i18n/openwebnet.properties
As requested [in this other PR](https://github.com/openhab/openhab-addons/pull/12483#issuecomment-1075576483), this new PR adds default translations to the openwebnet binding.
Translations to other languages will be completed using crowdin.
> [openwebnet] add default translations

- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/WeatherApi.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/discovery/NetatmoDiscoveryService.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/DeviceCapability.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/WeatherCapability.java
> [netatmo] Avoid requesting favorite stations when not needed

- bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/handler/InsteonDeviceHandler.java
Added as a defensive measure to ensure that commands are ignored if the device is offline.
> [insteon] ignore commands if device is not online

- bundles/org.openhab.binding.mqtt/src/test/java/org/openhab/binding/mqtt/handler/BrokerHandlerTest.java
Disable test that causes all full builds to fail.
Hopefully it can be brought back at some point, but so far I have not succeeded in understanding exactly how it broke, and how it's intended to work. All three `statusUpdated` invocations set `ThingStatus.OFFLINE`.
Related to: #12784
> [mqtt] Disable broken test

- bundles/org.openhab.voice.watsonstt/src/main/java/org/openhab/voice/watsonstt/internal/WatsonSTTService.java
Watson sdk is able to reuse the previous token or get one new when needed, with this changes we don't reinitialize the sdk on each call to take advantage of it.
> [watsonstt] reuse token

- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/ShadePosition.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/database/ShadeCapabilitiesDatabase.java
- bundles/org.openhab.binding.hdpowerview/src/test/java/org/openhab/binding/hdpowerview/ShadePositionTest.java
In this [post](https://github.com/jlaur/hdpowerview-doc/issues/1#issuecomment-1133774105) @jlaur pointed out a naming inconsistency concerning the two types of secondary shade -- namely regular secondary shades vs. Duolite blackout secondary shades.
In this PR the method names have been refactored so that methods and fields for both types of secondary shades include the word 'secondary' in them. No functionality has been changed; this is only done to improve clarity of the code.
> [hdpowerview] Change method names to match documentation

- itests/org.openhab.binding.mqtt.homie.tests/src/main/java/org/openhab/binding/mqtt/homie/HomieImplementationTest.java
CI builds are often (but not always) failing because of test `parseHomieTree`.
```
TEST org.openhab.binding.mqtt.homie.HomieImplementationTest#parseHomieTree() <<< ERROR: 
Expected: is "false"
but: was null
java.lang.AssertionError: 
Expected: is "false"
but: was null
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
at org.openhab.binding.mqtt.homie.HomieImplementationTest.parseHomieTree(HomieImplementationTest.java:303)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at …
```
> [mqtt.homie] Disable unstable test

- bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/handler/IpCameraHandler.java
- bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/servlet/StreamOutput.java
This PR fixes a bug only effecting Doorbird cameras. Reported in the forum and also confirmed by the user that it fixes the issue. See here:
https://community.openhab.org/t/ipcamera-doorbird-camera-things-going-offline-not-getting-back-online/134207/12
> [ipcamera] Doorbird online/offline bug fix

- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/CommonInterface.java
Wait for the thing being initialized properly by the thing manager
before considering it as an active children for the bridge.
Fix #12809
> [netatmo] Fix getActiveChildren

- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/coap/ShellyCoapJSonDTO.java
This fixes #12831, a problem on CoAP messages for Plug-S and Bulb. This missing handling caused an exception preventing channel updates.
> [shelly] Fix CoAP message parsing for Plug-S and Bulb

- bundles/org.openhab.binding.roku/README.md
- bundles/org.openhab.binding.roku/src/main/resources/OH-INF/i18n/roku.properties
- bundles/org.openhab.binding.roku/src/main/resources/OH-INF/thing/roku.xml
Add missing Power On option to Remote Button drop down for Roku TV.
Discussed in the community here: https://community.openhab.org/t/roku-binding-power-for-tvs/136223
> [roku] Add PowerOn option to Remote Button channel

- bundles/org.openhab.binding.helios/src/main/java/org/openhab/binding/helios/internal/HeliosHandlerFactory.java
#12721 was unfortunately merged without working build (spotless check failed).
> [helios] Fix build

- bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/influx1/Influx1FilterCriteriaQueryCreatorImpl.java
- bundles/org.openhab.persistence.influxdb/src/test/java/org/openhab/persistence/influxdb/internal/InfluxFilterCriteriaQueryCreatorImplTest.java
Bugfix for using itemnames beginning with numbers or having retention namnes beginning with numbers
Also solves if using old db where retention was named default wich is now a influxQL keyword
Resolves #9790
Resolves #10398
Added doubleqoutes for retention and table name as documentation for influxQL states
https://docs.influxdata.com/influxdb/v1.8/query_language/spec/#identifiers
> [influxdb] Fix for influxdbv1 retention and table names containing keywords or special chars

- bundles/org.openhab.binding.tado/pom.xml
The POM listed two dependencies for libraries, Gson and Jetty, which are included from core already. Therefore they didn't track core versions, and had to be upgraded manually:
- **gson:** 2.8.3 -> 2.8.9 (in core)
- **jetty-client:** 9.4.12 -> 9.4.46 (in core)
Running `mvn dependency:tree` before removal (relevant parts extracted):
```
[INFO] --- maven-dependency-plugin:3.1.1:tree (default-cli) @ org.openhab.binding.tado ---
[INFO] org.openhab.addons.bundles:org.openhab.binding.tado:jar:3.3.0-SNAPSHOT
[INFO] +- com.google.code.gson:gson:jar:2.8.3:compile
[INFO] +- org.eclipse.jetty:jetty-client:jar:9.4.12.v20180830:compile
[INFO] |  +- org.eclipse.jetty:jetty-http:jar:9.4.12.v20180830:compile
[INFO] |  |  \- org.eclipse.jetty:jetty-util:jar:9.4.12.v20180830:compile
[INFO] |  \- …
```
> [tado] Remove strict version dependencies for Gson/Jetty and upgrade

- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/database/ShadeCapabilitiesDatabase.java
Add shutters (shade type 66 / capabilities class 5) to capabilities database. And change model names to functional description texts.
> [hdpowerview] Add shutters (shade type 66) to capabilities database

- bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc1/NhcMessageBase1.java
- bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc1/NhcMessageCmd1.java
- bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc1/NikoHomeControlCommunication1.java
- bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc2/NikoHomeControlCommunication2.java
These are a few small fixes extracted from [PR #11963]( https://github.com/openhab/openhab-addons/pull/11963):
- Make trigger type items act on off in the NHC system
- Fix gson serialization for empty values
- Fix some null pointer warnings
> [nikohomecontrol] Nhc fixes

- bundles/org.openhab.transform.scale/src/main/java/org/openhab/transform/scale/internal/ScaleTransformationService.java
- bundles/org.openhab.transform.scale/src/test/java/org/openhab/transform/scale/internal/ScaleTransformServiceTest.java
See #12433 
@openhab/add-ons-maintainers It would be nice if this could be merged before the 3.3 release as we would like to remove the `org.openhab.core.transform.AbstractFileTransformationService` from core after the release
> [transform.scale] Refactor service  to use configuration registry

- bundles/pom.xml
See: https://github.com/openhab/openhab-addons/pull/12772#issuecomment-1145179643
> Exclude embedded module-info.class recursively

- bundles/org.openhab.binding.hdpowerview/src/test/java/org/openhab/binding/hdpowerview/AutomationChannelBuilderTest.java
- bundles/org.openhab.binding.hdpowerview/src/test/java/org/openhab/binding/hdpowerview/HDPowerViewJUnitTests.java
This pull request contains two test improvements, each committed separately:
- Avoid logging to console from test run (*). This was made possible by openhab/openhab-core#2982. Previous attempt is described [here](https://github.com/openhab/openhab-addons/pull/12061#issuecomment-1014879948), but required **mockito-inline** for static mocks. The console output was originally introduced by #11853.
- Fix warnings about redundant null checks. This might have been a regression from #12049.
*: The output looked like this:
```
[INFO] Running org.openhab.binding.hdpowerview.AutomationChannelBuilderTest
[main] WARN  o.o.b.h.i.b.AutomationChannelBuilder - Scheduled event '1' references scene '1', but no scenes are loaded
[main] WARN  o.o.b.h.i.b.AutomationChannelBuilder - Scheduled event '1' …
```
> [hdpowerview] Fix output to console from tests and eliminate warnings

- bundles/org.openhab.binding.orbitbhyve/src/main/java/org/openhab/binding/orbitbhyve/internal/model/OrbitBhyveDevice.java
Fixes #12871 
Removes `restrictedFrequency`, as the binding doesn't use it.
> [orbitbhyve] Eliminate JsonSyntaxException when restricted_frequency is null in json response

- bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/handler/NikoHomeControlActionHandler.java
- bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/handler/NikoHomeControlBridgeHandler.java
- bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/handler/NikoHomeControlEnergyMeterHandler.java
- bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/handler/NikoHomeControlThermostatHandler.java
- bundles/org.openhab.binding.nikohomecontrol/src/main/resources/OH-INF/i18n/nikohomecontrol.properties
- bundles/org.openhab.binding.nikohomecontrol/src/main/resources/OH-INF/i18n/nikohomecontrol_fr.properties
- bundles/org.openhab.binding.nikohomecontrol/src/main/resources/OH-INF/i18n/nikohomecontrol_nl.properties
- bundles/org.openhab.binding.nikohomecontrol/src/main/resources/OH-INF/thing/thing-types.xml
There is a large [PR #11963](https://github.com/openhab/openhab-addons/pull/11963) with new functionality for the Niko Home Control binding that has been open, waiting for review, for a while.
One of the things that got fixed there is an annoying bug. Things did not get initialized properly as the bridge status was already set before the bridge initialization finished. This small PR isolates this fix. I hope that makes it quicker to at least get this fix merged.
> [nikohomecontrol] Do not set thing status before end of initialization

- bundles/org.openhab.binding.benqprojector/README.md
- bundles/org.openhab.binding.benqprojector/src/main/java/org/openhab/binding/benqprojector/internal/BenqProjectorBindingConstants.java
- bundles/org.openhab.binding.benqprojector/src/main/java/org/openhab/binding/benqprojector/internal/discovery/BenqProjectorDiscoveryService.java
- bundles/org.openhab.binding.benqprojector/src/main/java/org/openhab/binding/benqprojector/internal/discovery/MulticastListener.java
- bundles/org.openhab.binding.benqprojector/src/main/java/org/openhab/binding/benqprojector/internal/handler/BenqProjectorHandler.java
- bundles/org.openhab.binding.benqprojector/src/main/resources/OH-INF/i18n/benqprojector.properties
Add discovery service to automatically locate BenQ projectors on the local network.
> [benqprojector] Add discovery service

- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/coap/ShellyCoapJSonDTO.java
- bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/i18n/shelly.properties
> [shelly] Fix CoAP message parsing 

- bundles/org.openhab.binding.elroconnects/src/main/java/org/openhab/binding/elroconnects/internal/devices/ElroConnectsDeviceCxsmAlarm.java
- bundles/org.openhab.binding.elroconnects/src/main/java/org/openhab/binding/elroconnects/internal/devices/ElroConnectsDeviceEntrySensor.java
- bundles/org.openhab.binding.elroconnects/src/main/java/org/openhab/binding/elroconnects/internal/devices/ElroConnectsDeviceGenericAlarm.java
- bundles/org.openhab.binding.elroconnects/src/main/java/org/openhab/binding/elroconnects/internal/devices/ElroConnectsDeviceMotionSensor.java
- bundles/org.openhab.binding.elroconnects/src/main/java/org/openhab/binding/elroconnects/internal/devices/ElroConnectsDevicePowerSocket.java
- bundles/org.openhab.binding.elroconnects/src/main/java/org/openhab/binding/elroconnects/internal/devices/ElroConnectsDeviceTemperatureSensor.java
- bundles/org.openhab.binding.elroconnects/src/main/java/org/openhab/binding/elroconnects/internal/handler/ElroConnectsAccountHandler.java
- bundles/org.openhab.binding.elroconnects/src/main/java/org/openhab/binding/elroconnects/internal/handler/ElroConnectsBridgeHandler.java
- bundles/org.openhab.binding.elroconnects/src/main/java/org/openhab/binding/elroconnects/internal/handler/ElroConnectsDeviceHandler.java
- bundles/org.openhab.binding.elroconnects/src/main/resources/OH-INF/i18n/elroconnects.properties
- Set thing status UNKNOWN in initialize before launching long running init
- Implement bridgeStatusChanged
> [elroconnects] Set thingStatus earlier in initialize

- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/discovery/NetatmoDiscoveryService.java
While previous behavior seemed to work, it made the weather station child of a home, being inconsistant with ModuleType description and expected API calls (e.g. calls to measurement channels were broken).
On netatmo side, this dependency exists but is partially reflected in API calls structure, most of them still being based on initial organization (before the introduction of homes for energy and security purpose).
> [netatmo] Correct Discovery service

- bundles/org.openhab.binding.roku/src/main/java/org/openhab/binding/roku/internal/RokuBindingConstants.java
- bundles/org.openhab.binding.roku/src/main/java/org/openhab/binding/roku/internal/handler/RokuHandler.java
The '/query/active-app' endpoint now reports an id of 562859 instead of -1 when on the Roku Home screen. This change will revert the id back to -1 so that the Active App channel's drop down can correctly report when the Roku is on the home screen.
> [roku] Fix reporting of Roku Home app

- bundles/org.openhab.binding.neohub/README.md
- bundles/org.openhab.binding.neohub/src/main/java/org/openhab/binding/neohub/internal/NeoHubBindingConstants.java
- bundles/org.openhab.binding.neohub/src/main/java/org/openhab/binding/neohub/internal/NeoHubHandler.java
From early 2022 Heatmiser introduced NeoHub firmware that has the ability to enable / disable the NeoHub `portNumber` 4242. If this port is disabled the OpenHAB binding cannot connect and the binding will report a *"Connection Refused"* warning in the log. In prior firmware versions the port was always enabled. But in the new firmware the port is initially enabled on power up but if no communication occurs for 48 hours it is automatically disabled. Alternatively the Heatmiser mobile App has a setting (Settings | System | API Access | Legacy API Enable | On) whereby the port can be permanently enabled.
In this PR when the handler `initialize()` method is called, we try to 'ping' the NeoHub. And if the ping fails with *"Connection Refused"* it sets the Bridge status as offline / …
> [neohub] Workaround for 'Legacy API Disabled' problem

- bundles/org.openhab.binding.ecobee/README.md
- bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/handler/EcobeeSensorThingHandler.java
The new Smart Thermostat Premium provides the following capabilities:
```
{
"id": "ei:0",
"name": "Dining Room",
"type": "thermostat",
"inUse": true,
"capability": [
{
"id": "1",
"type": "temperature",
"value": "705"
},
{
"id": "2",
"type": "humidity",
"value": "50"
},
{
"id": "3",
"type": "occupancy",
"value": "false"
},
{
"id": "4",
"type": "airQualityAccuracy",
"value": "unknown"
},
{
"id": "5",
"type": "airQuality",
"value": "unknown"
},
{
"id": "6",
"type": "vocPPM",
"value": "unknown"
},
{
"id": "7",
"type": "co2PPM",
"value": "unknown"
},
{
"id": "8",
"type": "airPressure",
"value": "unknown"
}
]
}
```
> [ecobee] Add support for the Smart Thermostat Premium

- bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/handler/PulseaudioHandler.java
- bundles/org.openhab.binding.pulseaudio/src/main/resources/OH-INF/thing/source.xml
I made some mistakes when implementing the AudioSource describing the supported formats, I just realize it while testing a new keyword spotter with different bit depths and endianness.
This pr fixes it.
Reference here: https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/SupportedAudioFormats/
> [pulseaudio] Fix source format options

- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/HDPowerViewWebTargets.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/responses/Survey.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewShadeHandler.java
While preparing for #12928 I encountered an issue with refreshing signal strength (introduced in #11944). Signal strength is refreshed in the Hub by this request:
```
http://<hub>/api/shades/<shadeId>?survey=true
```
However, the response is a survey which does not include **signalStrength** itself. Therefore an additional request must be made to fetch the new value:
```
http://<hub>/api/shades/<shadeId>
```
This pull request fixes this issue so that new value is obtained immediately instead of waiting for next poll (up to one minute).
> [hdpowerview] Fix signalStrength channel update after REFRESH command

- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitOHItemProxy.java
As reported here, some hue light expect all 3 value (hue, saturation and brightness) even if only one value got update
see investigation here
https://community.openhab.org/t/how-to-configure-homekit-light-with-colour/136137/33?u=yfre
this was already the case for hue and saturation changes but not for brightness. 
this fix ensure that all 3 values are always sent for item of type color. 
> [homekit] fix issue with some hue lights, e.g. xiaomi

- bundles/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/GardenaSmartImpl.java
- bundles/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/GardenaSmartWebSocket.java
- bundles/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/GardenaSmartWebSocketListener.java
- bundles/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/exception/GardenaException.java
- bundles/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/handler/GardenaAccountHandler.java
Fixes #10516
Fixes #11474
Fixes #10455
Fixes #12481 
* Memory leaks were caused by not properly synchonizing the calls when a connection closes
* The binding restarted a single websocket more than once
* This led to performance issues of the whole Openhab system when the binding was running for some time
* Make use of the synchronized keyword to ensure a websocket is only restarted once
* Only restart the websocket that was closed, instead of re-initializing the whole binding
> [gardena] Fix handling of websocket connection losses that causes memory leaks

- bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/InsteonBinding.java
- bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/handler/InsteonDeviceHandler.java
- bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/handler/InsteonNetworkHandler.java
This fixes https://github.com/openhab/openhab-addons/issues/12903
> [insteon] set device offline if it doesn't exist in the plm/hub database

- bundles/org.openhab.binding.nikohomecontrol/README.md
- bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/NikoHomeControlBindingConstants.java
- bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/NikoHomeControlHandlerFactory.java
- bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/handler/NikoHomeControlBridgeHandler.java
- bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/handler/NikoHomeControlBridgeHandler1.java
- bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/handler/NikoHomeControlBridgeHandler2.java
- bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/handler/NikoHomeControlThermostatHandler.java
- bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/NhcControllerEvent.java
- bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/NhcEnergyMeter.java
- bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/NhcThermostat.java
- bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/NikoHomeControlCommunication.java
- bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/NikoHomeControlConstants.java
- bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc2/NikoHomeControlCommunication2.java
- bundles/org.openhab.binding.nikohomecontrol/src/main/resources/OH-INF/i18n/nikohomecontrol.properties
- bundles/org.openhab.binding.nikohomecontrol/src/main/resources/OH-INF/thing/thing-types.xml
Depends on [PR #12885](https://github.com/openhab/openhab-addons/pull/12885)
The focus of this PR is now solely on improving thermostats:
- Thermostats now also have string channels. These make it easier to map the inputs and outputs without rules (as all assistants use string channels). The old (numeric) channels have been declared advanced.
- A few bugs with thermostats have been fixed.
> [nikohomecontrol] Bug fixes and improvements to thermostats

- bundles/org.openhab.binding.gardena/README.md
- bundles/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/model/dto/Device.java
> [gardena] Fix compiler warnings

- bundles/org.openhab.binding.orbitbhyve/src/main/java/org/openhab/binding/orbitbhyve/internal/handler/OrbitBhyveBridgeHandler.java
This WebSocketException during the scheduled job execution causes the scheduled ping job to fail. This PR catches WebSocketException during the scheduled ping job execution (and at other points in the binding where it's thrown).
```
2022-06-07 21:12:35.605 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception:
org.eclipse.jetty.websocket.api.WebSocketException: Session closed
at org.eclipse.jetty.websocket.common.WebSocketSession.outgoingFrame(WebSocketSession.java:350) ~[?:?]
at org.eclipse.jetty.websocket.common.WebSocketRemoteEndpoint.uncheckedSendFrame(WebSocketRemoteEndpoint.java:322) ~[?:?]
at org.eclipse.jetty.websocket.common.WebSocketRemoteEndpoint.blockingWrite(WebSocketRemoteEndpoint.java:109) ~[?:?]
at …
```
> [orbitbhyve] Handle WebSocketException to prevent scheduled ping job failure

- bundles/org.openhab.binding.orbitbhyve/src/main/java/org/openhab/binding/orbitbhyve/internal/handler/OrbitBhyveBridgeHandler.java
Prevent ClassCastExceptions, such as this one.
```
2022-06-14 18:08:11.322 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception:
java.lang.ClassCastException: class org.openhab.binding.orbitbhyve.internal.handler.OrbitBhyveSprinklerHandler cannot be cast to class org.openhab.binding.orbitbhyve.internal.handler.OrbitBhyveSprinklerHandler (org.openhab.binding.orbitbhyve.internal.handler.OrbitBhyveSprinklerHandler is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @518e9bf9; org.openhab.binding.orbitbhyve.internal.handler.OrbitBhyveSprinklerHandler is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @70909aa8)
at …
```
> [orbitbhyve] Avoid ClassCastExceptions when accessing thing handler

- bundles/org.openhab.binding.oppo/README.md
The format for ser2net configuration has changed to a YAML file for ser2net versions 4.0 and above.
The existing documentation provides an example ser2net configuration for the old ser2net version, and this PR includes an example for the newer YAML format.
This PR simply adds an example yaml block showing a working ser2net connection with the Oppo Bluray player.
I've not included a JAR link because there is no code change, just a documentation addition.
> [oppo] Documentation - Add example for configuring ser2net version 4 and above

- CODEOWNERS
- bom/openhab-addons/pom.xml
- bundles/org.openhab.voice.actiontemplatehli/NOTICE
- bundles/org.openhab.voice.actiontemplatehli/README.md
- bundles/org.openhab.voice.actiontemplatehli/pom.xml
- bundles/org.openhab.voice.actiontemplatehli/src/main/feature/feature.xml
- bundles/org.openhab.voice.actiontemplatehli/src/main/java/org/openhab/voice/actiontemplatehli/internal/ActionTemplateConfiguration.java
- bundles/org.openhab.voice.actiontemplatehli/src/main/java/org/openhab/voice/actiontemplatehli/internal/ActionTemplateInterpreter.java
- bundles/org.openhab.voice.actiontemplatehli/src/main/java/org/openhab/voice/actiontemplatehli/internal/ActionTemplateInterpreterConfiguration.java
- bundles/org.openhab.voice.actiontemplatehli/src/main/java/org/openhab/voice/actiontemplatehli/internal/ActionTemplateInterpreterConstants.java
- bundles/org.openhab.voice.actiontemplatehli/src/main/java/org/openhab/voice/actiontemplatehli/internal/configuration/ActionTemplateConfiguration.java
- bundles/org.openhab.voice.actiontemplatehli/src/main/java/org/openhab/voice/actiontemplatehli/internal/configuration/ActionTemplateGroupTargets.java
- bundles/org.openhab.voice.actiontemplatehli/src/main/java/org/openhab/voice/actiontemplatehli/internal/configuration/ActionTemplatePlaceholder.java
- bundles/org.openhab.voice.actiontemplatehli/src/main/resources/OH-INF/config/config.xml
- bundles/org.openhab.voice.actiontemplatehli/src/main/resources/OH-INF/i18n/actiontemplatehli.properties
- bundles/org.openhab.voice.actiontemplatehli/src/test/java/org/openhab/voice/actiontemplatehli/internal/ActionTemplateInterpreterTest.java
- bundles/pom.xml
NOTE: This interpreter was renamed from 'opennlphli' to 'actiontemplatehli' to avoid confusion.
This add-on adds an human language interpreter powered by openNLP that allows the user to define their own actions to read from items or send commands to them. Also supports to configure a  fallback interpreter, so you can use this one just to complement another.
Aims to be compatible with all languages and assumes the action templates are written in the configured openHAB language.
Supported feature list and samples are provided on the readme.
I hope that the community find it useful, for me is a solution for the custom commands I wanted to add to the standard interpreter.
> [actiontemplatehli] Initial contribution

- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/HDPowerViewWebTargets.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/discovery/HDPowerViewDeviceDiscoveryService.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewHubHandler.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewRepeaterHandler.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewShadeHandler.java
Some minor stashed refactoring:
- `HDPowerViewWebTargets` is initialized by `initialize()`, so can be assumed as non-null where used.
- Use `Duration` for maintenance period logic for better readability.
- Slightly improve logging of response.
> [hdpowerview] Refactor null-handling, maintenance period, response logging

- bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/handler/OpenUVBridgeHandler.java
- bundles/org.openhab.binding.openuv/src/main/resources/OH-INF/i18n/openuv.properties
This pull request is aimed to solve issue #12932 .
It helps the binding auto reconnect on two known server issues, when db is not available, and when a good apikey fails due to....wrong behaviour of the server.
If these errors are detected, the bridge goes offline for five minutes, then tries to reconnect.
> [openuv] Enhance server side error handling

- bundles/org.openhab.binding.ahawastecollection/src/test/java/org/openhab/binding/ahawastecollection/internal/AhaCollectionScheduleTest.java
These tests use the real website which causes unwanted load, network connections and test failures.
See: https://github.com/openhab/openhab-addons/actions/runs/2529936944
```
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 4.109 s <<< FAILURE! - in org.openhab.binding.ahawastecollection.internal.AhaCollectionScheduleTest
[ERROR] org.openhab.binding.ahawastecollection.internal.AhaCollectionScheduleTest.testGetValuesForRegion  Time elapsed: 3.294 s  <<< ERROR!
org.jsoup.UnsupportedMimeTypeException: Unhandled content type. Must be text/*, application/xml, or application/*+xml
at org.openhab.binding.ahawastecollection.internal.AhaCollectionScheduleTest.testGetValuesForRegion(AhaCollectionScheduleTest.java:42)
[ERROR] …
```
> [ahawastecollection] Disable AhaCollectionScheduleTest

- bundles/org.openhab.binding.danfossairunit/src/main/resources/OH-INF/i18n/danfossairunit.properties
One string missing and one string no longer referenced. By coincidence the texts are the same.
> [danfossairunit] Update default translations

- bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/IndegoController.java
Offline/communication error description should include HTTP code, but actually was set to "The login credentials are wrong or another client is connected to your Indego account".
> [boschindego] Fix communication error description on failed HTTP call

- bundles/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/handler/GardenaAccountHandler.java
Fixes #13001
This PR adds code safety checks to prevent ClassCastException from being thrown, and adds logging so that potential cases where that exception might have occurred will be logged (and as such this PR might be superseded at some point in the future).
> [gardena] Eliminate ClassCastException (quick fix)

- bundles/org.openhab.binding.wundergroundupdatereceiver/src/main/java/org/openhab/binding/wundergroundupdatereceiver/internal/WundergroundUpdateReceiverHandler.java
- bundles/org.openhab.binding.wundergroundupdatereceiver/src/main/java/org/openhab/binding/wundergroundupdatereceiver/internal/WundergroundUpdateReceiverHandlerFactory.java
- bundles/org.openhab.binding.wundergroundupdatereceiver/src/test/java/org/openhab/binding/wundergroundupdatereceiver/internal/WundergroundUpdateReceiverDiscoveryServiceTest.java
- bundles/org.openhab.binding.wundergroundupdatereceiver/src/test/java/org/openhab/binding/wundergroundupdatereceiver/internal/WundergroundUpdateReceiverServletTest.java
> [wundergroundupdatereceiver] Bugfix: Check whether the thing is managed before adding newly discovered parameters as channels.

- bundles/org.openhab.binding.dali/README.md
- bundles/org.openhab.binding.dali/src/main/java/org/openhab/binding/dali/internal/DaliBindingConstants.java
- bundles/org.openhab.binding.dali/src/main/java/org/openhab/binding/dali/internal/DaliHandlerFactory.java
- bundles/org.openhab.binding.dali/src/main/java/org/openhab/binding/dali/internal/handler/DaliDeviceHandler.java
- bundles/org.openhab.binding.dali/src/main/java/org/openhab/binding/dali/internal/handler/DaliDt8DeviceHandler.java
- bundles/org.openhab.binding.dali/src/main/java/org/openhab/binding/dali/internal/handler/DaliserverBridgeHandler.java
- bundles/org.openhab.binding.dali/src/main/java/org/openhab/binding/dali/internal/protocol/DaliAddress.java
- bundles/org.openhab.binding.dali/src/main/java/org/openhab/binding/dali/internal/protocol/DaliStandardCommand.java
- bundles/org.openhab.binding.dali/src/main/resources/OH-INF/i18n/dali.properties
- bundles/org.openhab.binding.dali/src/main/resources/OH-INF/thing/thing-types.xml
This PR adds support for DALI DT8 devices. These are devices supporting customizable color temperature and/or single-channel (as opposed to the 3-channel solution already implemented) RGB color controls.
This PR adds two new thing-types:
- `dali.device-dt8`
- `dali.group-dt8`
These are largely identical to the already existing `dali.device` and `dali.group`, with the addition of two new channels, one for controlling RGB color, and another for controlling color temperature.
This PR also fixes some issues in DALI device addressing:
- Group addressing was broken, effectively only group 0 could be addressed.
- Uppermost bit of short (6bit) addresses was removed, so effectively only devices 0-31 could be addressed.
- Reading state from group addresses does not work in general, because multiple …
> [dali] Implement DT8 (single-channel RGB & color temperature) device type

- bundles/org.openhab.automation.pidcontroller/README.md
- bundles/org.openhab.automation.pidcontroller/src/main/java/org/openhab/automation/pidcontroller/internal/handler/PIDController.java
- bundles/org.openhab.automation.pidcontroller/src/main/java/org/openhab/automation/pidcontroller/internal/handler/PIDControllerTriggerHandler.java
This feature allows the PID controller parameters to be updated and OpenHAB to be restarted without losing the current controller state.
This is especially important for systems with a long response time. For example it might take up to a day for an underfloor heating
controller to stabilise after losing state and having to build up the integrator value from zero.
In case the controller instance has configured OpenHAB items for the integral part, derivative part and error inspectors, then we can query the previous value from the persistance layer for these items and restore them during the controller startup.
I have been using this successfully for about 4 months now during the last heating season.
> [pidcontroller] Implement previous state recovery on startup

- bundles/org.openhab.binding.boschindego/README.md
- bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/BoschIndegoBindingConstants.java
- bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/IndegoController.java
- bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/dto/Battery.java
- bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/dto/Garden.java
- bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/dto/response/OperatingDataResponse.java
- bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/exceptions/IndegoUnreachableException.java
- bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/handler/BoschIndegoHandler.java
- bundles/org.openhab.binding.boschindego/src/main/resources/OH-INF/i18n/boschindego.properties
- bundles/org.openhab.binding.boschindego/src/main/resources/OH-INF/thing/thing-types.xml
Introduce new channels:
- batteryVoltage
- batteryLevel
- lowBattery
- batteryTemperature
- gardenSize
- gardenMap
Binding is now also able to detect whether device is online, so it will be marked as offline when unreachable. This is based on **/operatingData** which will directly communicate with the device, whereas **/state** returns data even when device has been turned off for several days.
Fixes #12938
Fixes #13017
JAR: https://drive.google.com/file/d/1pWVrOl-QcKf3zeHuqizhV1VDpXecxizC/view?usp=sharing
> [boschindego] Add battery and garden channels (including map)

- bundles/org.openhab.binding.enigma2/src/main/resources/OH-INF/i18n/enigma2.properties
They would also get added by Crowdin, see https://github.com/openhab/openhab-addons/pull/13074.
> [enigma2] Remove FIXMEs from translations

- bundles/org.openhab.binding.dsmr/src/main/java/org/openhab/binding/dsmr/internal/handler/DSMRMeterHandler.java
Subchannels were created by appending the key. However this was done inside a loop and if multiple updates were needed they would be appended to the channel name, instead of taking the channel name each time.
Reported on https://community.openhab.org/t/no-power-failure-logs-in-dsmr/137116
> [dsmr] Fix incorrect deriving of sub channel names when updating channels

- bundles/org.openhab.binding.miele/README.md
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/MieleBindingConstants.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/CoffeeMachineHandler.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/DishWasherHandler.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/MieleApplianceHandler.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/OvenChannelSelector.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/OvenHandler.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/TumbleDryerHandler.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/WashingMachineHandler.java
- bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/channeltypes.xml
Improve switch channels **stop** and **switch**:
- **stop:** Fix auto-update policy as this channel is stateless and used only to trigger a stop action.
- **switch:** Reflect appliance state and by that eliminate the need for manually switching on before being able to switch off, and vice versa.
Fixes #13069
> [miele] Fix auto-update for stop channel and synchronize switch channel with appliance state

- itests/org.openhab.binding.tradfri.tests/itest.bndrun
This fixes the build as jmdns got updated in openhab/openhab-core#3029.
> [tradfri] Update jmdns bundle in itest

- bundles/org.openhab.binding.groupepsa/src/main/java/org/openhab/binding/groupepsa/internal/rest/api/GroupePSAConnectApi.java
- Handle `JsonSyntaxException` when parsing error messages
```
2022-07-04 17:58:42.363 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226) ~[?:?]
at com.google.gson.Gson.fromJson(Gson.java:963) ~[?:?]
at com.google.gson.Gson.fromJson(Gson.java:928) ~[?:?]
at com.google.gson.Gson.fromJson(Gson.java:877) ~[?:?]
at com.google.gson.Gson.fromJson(Gson.java:848) ~[?:?]
at org.openhab.binding.groupepsa.internal.rest.api.GroupePSAConnectApi.checkForError(GroupePSAConnectApi.java:154) ~[?:?]
at …
```
> [groupepsa] Handle 'JsonSyntaxException' when parsing error messages

- bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/IndegoController.java
- bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/handler/BoschIndegoHandler.java
Fixes #13085:
- **First issue:** Double authentication because two jobs are started at the same time, and each of them need to authenticate. Solved by mutual exclusion of calls to `getSerialNumber()` which is used to verify session and construct URL's.
- **Second issue**: Cutting times fetched twice because of a concurrency issue within `refreshState()`, where cutting times are fetched when state changes. This will always happen on startup, and at the same time another job is scheduled for fetching cutting times immediately and then hourly. Solved by skipping call when not having a previous state. In this situation the scheduled job will fetch cutting times regularly.
> [boschindego] Fix duplicated calls during initialization

- bundles/create_openhab_binding_skeleton.cmd
- bundles/create_openhab_binding_skeleton.sh
Hi. I tried to start working on a new binding on the weekend, and it wouldn't build in Eclipse, because it couldn't find the 3.3.0 SNAPSHOTS. I have never run a `mvn install` against 3.3.0-SNAPSHOT, so it make sense that the base is not in my m2 repo.
After a little bit of digging, I found that all the bundles had moved to 3.4.0-SNAPSHOT, but my binding was still on 3.3.0-SNAPSHOT because it was created by this skeleton shell script.
This PR should solve that in future for anyone else that encounters this issue.
> Update OH version in skeleton scripts

- pom.xml
Generated Swagger/OpenAPI code can be messy resulting in a lot of compiler warnings obscuring more important compiler warnings.
Fixes #12498
> Hide compiler warnings for generated code

- bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/internal/SMTPHandler.java
Originally fixed in smarthomej/addons by @J-N-K 
https://github.com/smarthomej/addons/pull/378
The fix in https://github.com/smarthomej/addons/pull/254 and https://github.com/openhab/openhab-addons/pull/12568 was not sufficient for multipart messages as they contain a DataHandler for each body part. The command map was only set for the outer mime part, not for the body parts.
Also Signed-off-by: Jan N. Klug [jan.n.klug@rub.de](mailto:jan.n.klug@rub.de)
> [mail] Fix sending HTML/Multipart mails

- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitImpl.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitAccessoryFactory.java
fix 2 potentail NPE
- first one happens if addon is deployed on new and not configured openhab installation. in this case "settings" can be null
- second one can happen if homekit accessory type is missing, wrong or incomplete. reported here
https://community.openhab.org/t/homekit-binding-stops-working-after-upgrading-to-oh-3-3-0/137302
> [homekit] fix potential null pointer exceptions

- bundles/org.openhab.binding.dali/src/main/java/org/openhab/binding/dali/internal/handler/DaliDt8DeviceHandler.java
This PR fixes a small bug in the recently introduced DALI DT8 support:
When querying the current color temperature from a DALI DT8 device (e.g. after changing it or due to a refresh command), the OpenHAB DALI binding would currently query the actual current color temperature. If this happens while the device is still fading between two temperatures, a value somewhere between the start and target values is returned. This makes OpenHAB behave somewhat erratic (sliders jumping to unexpected positions), and we've even experienced some cases (with up/down buttons instead of sliders) where the color temperature could not be changed apart from a very limited range.
This PR changes the behavior to query the target color temperature (for some reason referred to as "temporary color temperature" in …
> [dali] Use correct command argument to query current color temperature

- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewHubHandler.java
Firmware version properties are now only updated:
- On binding initialization.
- Once per day.
- After hub communication errors (which might be due to firmware upgrade).
Fixes #13154
> [hdpowerview] Fix excessive firmware version updates

- bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/handler/KM200SwitchProgramServiceHandler.java
Fix for KM100 with Firmware 04.08.02
With KM100 and firmware 04.08.02 some negativeSwitch having the value "on". As this is not expected, the binding is throwing an exception. I added a condition on an existing if clause, so there is just a warning and the binding is working again.
> [km200] check if negativeSwitch is "on" and positiveSwitch is "off. If so: just

- bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/IndegoController.java
- bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/exceptions/IndegoInvalidResponseException.java
With smart mowing disabled and channel **nextCutting** linked, binding would go **OFFLINE** with **COMMUNICATION_ERROR**.
This happened because server in this case returns empty response with HTTP code 204 ("No Content"), which would throw `IndegoInvalidResponseException`. This is now being directly handled so that deserialization or other errors will still be handled correctly as errors.
Same fix applied for channel **lastCutting** for the specific case of a brand new mower without any cuts yet.
Tested with smart mowing enabled as well as disabled. When disabled, channel **nextCutting** will be updated to **UNDEF**.
Regression of #12989
Fixes #13163
> [boschindego] Fix communication error when smart mowing is disabled

- bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/type/HomematicTypeGeneratorImpl.java
For some Homematic devices the default values can be higher than the allowed maximum value or less than the allowed minimum value (e.g. 0 for "not set"). 
Default values that are higher than the maximum value were alreaday allowed. With this fix also default values that are less than  the minimum value are allowed.
Unfortunately, this means that the range of allowed values has to be increased.
Resolves #13097
> [homematic] Allow default value that is less than allowed minimum

- bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/handler/BoschIndegoHandler.java
Schedule additional update right after next planned cutting. This ensures a faster/immediate update in case the next cutting will be postponed (for example due to weather conditions). Previously this update could take up to one hour.
Tested and finally confirmed to work correctly after four days of waiting time - it was scheduled to mow at 10:00, and immediately hereafter the next scheduled time was updated:
```
2022-07-26 10:00:01.797 [TRACE] [oschindego.internal.IndegoController] - GET request for https://api.indego.iot.bosch-si.com/api/v1/alms/xxxxxxxx/predictive/nextcutting
2022-07-26 10:00:01.841 [TRACE] [oschindego.internal.IndegoController] - JSON response: '{
"mow_next" : "2022-07-29T10:00:00+02:00"
}'
2022-07-26 10:00:01.844 [DEBUG] [.internal.handler.BoschIndegoHandler] - …
```
> [boschindego] Refresh cutting times right after next planned cutting

- bundles/org.openhab.binding.haywardomnilogic/src/main/java/org/openhab/binding/haywardomnilogic/internal/handler/HaywardBridgeHandler.java
Add http timeout retry which made significant improvement in communication stability with Hayward server.
https://community.openhab.org/t/hayward-omnilogic-pool-automation-binding/104105/80
https://drive.google.com/file/d/1mrxhJXxRY5Qaty1996hfTCB--L9grr9u/view?usp=sharing
> [haywardomnilogic] Add http timeout retry

- bundles/org.openhab.binding.boschindego/README.md
- bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/DeviceStatus.java
- bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/config/BoschIndegoConfiguration.java
- bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/handler/BoschIndegoHandler.java
- bundles/org.openhab.binding.boschindego/src/main/resources/OH-INF/i18n/boschindego.properties
- bundles/org.openhab.binding.boschindego/src/main/resources/OH-INF/thing/thing-types.xml
Location is now plotted on the received map:
Location is received as coordinates on the map with the state response, which is the most frequent and least expensive call. With default configuration coordinates are therefore received every three minutes.
The map itself is now only requested:
- On binding initialization.
- Once per day.
- After detecting that mower is no longer in "learning lawn" state.
As a result we now have more usable data (current location plotted on map) with fewer calls.
Configuration parameter **cuttingTimeMapRefresh** has been renamed back to **cuttingTimeRefresh** as it no longer has any influence on map refresh. This is a change to #13040 which is also for 3.4.
Completes #13017
> [boschindego] Plot location on map

- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/HDPowerViewBindingConstants.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/HDPowerViewWebTargets.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/HubFirmware.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/Times.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/UserData.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/responses/UserDataResponse.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewHubHandler.java
Resolves #13173 by adding the following hub properties:
- Serial number
- MAC address
- Hub name
In the future serial number or MAC address can potentially replace host as representation property.
Example:
> [hdpowerview] Add additional hub properties

- bundles/org.openhab.binding.boschindego/README.md
- bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/DeviceStateAttribute.java
- bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/DeviceStatus.java
- bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/IndegoController.java
- bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/dto/response/DeviceStateResponse.java
- bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/handler/BoschIndegoHandler.java
- bundles/org.openhab.binding.boschindego/src/main/resources/OH-INF/i18n/boschindego.properties
- bundles/org.openhab.binding.boschindego/src/main/resources/OH-INF/thing/thing-types.xml
- bundles/org.openhab.binding.boschindego/src/test/java/org/openhab/binding/boschindego/internal/DeviceStatusTest.java
This pull request implements a balanced way of using the API in order to provide faster updates and reduced load when fast updates are not needed. In addition, position tracking is now automatically requested when mower is active. This allows for updating the map with a frequency as high as six seconds between refreshes.
Some details:
- The most expensive call, `/operatingData` (contacting the robot), was previously called every three minutes (with default configuration). This has now been changed to every six hours when idle and every two minutes when active or charging. For a mower running one hour every day and charging 30 minutes, this **reduces** the number of calls per day from 480 to 49 while at the same time providing faster updates. It also fixes an issue with the display being …
> [boschindego] Provide faster channel updates

- bundles/org.openhab.binding.neohub/README.md
The ReadMe file did not mention of the auto discovery process for finding Neohub's.
This PR rectifies that.
> [neohub] Describe auto discovery in ReadMe

- bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/IndegoController.java
- bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/dto/response/ErrorResponse.java
- bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/exceptions/IndegoInvalidCommandException.java
- bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/exceptions/IndegoTimeoutException.java
- bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/handler/BoschIndegoHandler.java
When sending a command which is rejected by the device, the thing would be marked as **OFFLINE** with **COMMUNICATION_ERROR** until the next _operatingData_ request which could take as long as six hours.
This pull request fixes this by:
- Logging a warning without changing thing status.
- Updating channel **errorcode** with any error code received. Please note that for now this is updated in the existing errorcode channel. After next state update, this error code will be reset.
Additionally, PUT/POST response payloads are now logged (with TRACE level) and GET response payload is now also logged in case of HTTP failure.
Fixes #13218
After temporary disruptions like 429 ("Too Many Requests"), revert back to previous "real" online status based on ability to reach the device. In other words: …
> [boschindego] Fix thing marked as offline when device is reachable

- bundles/org.openhab.binding.boschindego/README.md
Fix regression of the documentation within #13192, since Markdown [footnotes](https://www.markdownguide.org/extended-syntax/#footnotes) seems to be unsupported by the openHAB documentation rendering.
> [boschindego] Fix footnotes

- bundles/org.openhab.binding.tapocontrol/README.md
- bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/constants/TapoThingConstants.java
- bundles/org.openhab.binding.tapocontrol/src/main/resources/OH-INF/i18n/tapocontrol.properties
- bundles/org.openhab.binding.tapocontrol/src/main/resources/OH-INF/thing/P115.xml
This PR now added the Tapo P115 smart-socket to tapocontrol.
Also fixed thing configuration warning occured since OH3.3
> [tapocontrol] included P115 smart-socket

- bundles/org.openhab.automation.jrubyscripting/README.md
- bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/JRubyScriptEngineConfiguration.java
- bundles/org.openhab.automation.jrubyscripting/src/main/resources/OH-INF/config/config.xml
- bundles/org.openhab.automation.jrubyscripting/src/main/resources/OH-INF/i18n/jruby.properties
this avoids unecessary downloads and overwrites, or even more importantly
errors if the GEM_HOME is not writable by the openhab user.
> [jrubyscripting] check if gems are installed before installing them

- bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/DaikinWebTargets.java
- bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/Enums.java
This supersedes #13206 and fix the transition from ECO to NORMAL, as reported in https://community.openhab.org/t/daikin-the-channel-specialmode-can-be-read-but-not-modified-from-oh-both-2-5-12-and-3-1/125561/16
> [daikin] Fix changing specialmode from ECO to NORMAL

- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/AbstractHomekitPositionAccessoryImpl.java
it was getting the state as a decimal type, not a percent type, so
it was getting 1 instead of 100.
> [homekit] fix window coverings based on groups of  rollershutters

- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitAccessoryFactory.java
given:
```
Group eThermostat { homekit="Thermostat" }
Number:Temperature Thermostat_AmbTemp (eThermostat) { homekit="CurrentTemperature" }
Number:Temperature Thermostat_SetTemp (eThermostat) { homekit="TargetTemperature" }
Group gThermostatZoneContacts
// in reality there are multiple thermostats and multiple of these groups,
// so that a rule on members of gThermostatZoneContacts can find the related
// thermostat to turn it off when a window is open
Group:Contact:OR(OPEN,CLOSED) gWindows (eThermostat, gThermostatZoneContacts)
Contact Window_Contact (gWindows) { homekit="ContactSensor" }
```
When constructing the Thermostat accessory for eThermostat, detects the
Window_Contact as a mandatory characteristic, because it's a base accessory
in a nested group. This leads to lots of warnings …
> [homekit] fix collecting characteristics that don't belong to a complex accessory

- bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/handler/SonosMediaInformation.java
- bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/handler/ZonePlayerHandler.java
- bundles/org.openhab.binding.sonos/src/test/java/org/openhab/binding/sonos/internal/SonosMediaInformationTest.java
> [sonos] Added support of RadioApp music service

- bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/handler/ZonePlayerHandler.java
- bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/i18n/sonos.properties
- bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/channels.xml
> [sonos] Ignore TRANSITIONING device state when updating channels

- bundles/org.openhab.binding.broadlinkthermostat/README.md
> [broadlinkthermostat] Fix parameter name in README

- bundles/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/GardenaSmartImpl.java
- bundles/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/GardenaSmartWebSocket.java
The connection tracker does not start after some websocket connections are disconnected. Therefore, every 2 minutes some API requests are sent to Gardena. This can lead to the message 429 limit exceeded after a few days/weeks.
> [gardena] Fixed connection tracker

- bundles/org.openhab.binding.konnected/src/main/java/org/openhab/binding/konnected/internal/KonnectedBindingConstants.java
- bundles/org.openhab.binding.konnected/src/main/java/org/openhab/binding/konnected/internal/discovery/KonnectedUPnPServer.java
- bundles/org.openhab.binding.konnected/src/main/java/org/openhab/binding/konnected/internal/handler/KonnectedHandler.java
- bundles/org.openhab.binding.konnected/src/main/resources/OH-INF/config/config.xml
- bundles/org.openhab.binding.konnected/src/main/resources/OH-INF/i18n/konnected.properties
This PR will allow for things to be manually added, and for the address of the konnected panel to be updated.
Before this change there is no configuration for the address of the konnected panel. If a panel is manually added the thing is not functional, and there is a null pointer exception on initialization.
I renamed the fields `ipAddress` and `host` to `baseUrl` for clarity. The field contains a URL, and not an IP address. I'm not sure if this breaks backwards compatibility, but recreation of the konnected things is anyway needed for openhab version 3.4.0.
> [Konnected] Adding base URL to config to allow for manually adding thing

- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/data/NetatmoConstants.java
> [netatmo] Support one decimal for pressure values

- bundles/org.openhab.binding.serial/src/main/resources/OH-INF/i18n/serial.properties
- bundles/org.openhab.binding.serial/src/main/resources/OH-INF/thing/thing-types.xml
> [serial] Allow custom baudrate and add option 2400

- bundles/org.openhab.binding.automower/README.md
- bundles/org.openhab.binding.automower/src/main/java/org/openhab/binding/automower/internal/bridge/AutomowerBridge.java
- bundles/org.openhab.binding.automower/src/main/java/org/openhab/binding/automower/internal/bridge/AutomowerBridgeConfiguration.java
- bundles/org.openhab.binding.automower/src/main/java/org/openhab/binding/automower/internal/bridge/AutomowerBridgeHandler.java
- bundles/org.openhab.binding.automower/src/main/resources/OH-INF/i18n/automower.properties
- bundles/org.openhab.binding.automower/src/main/resources/OH-INF/i18n/automower_de.properties
- bundles/org.openhab.binding.automower/src/main/resources/OH-INF/i18n/automower_fr.properties
- bundles/org.openhab.binding.automower/src/main/resources/OH-INF/i18n/automower_hu.properties
- bundles/org.openhab.binding.automower/src/main/resources/OH-INF/thing/thing-types.xml
The Automower Connect API Authentication does not work anymore as they moved to a new authentication method (AppKey and AppSecret) - adopted. 
Fix #12980
Signed-off-by: Boris Krivonog [boris.krivonog@inova.si](mailto:boris.krivonog@inova.si)
> [automower] Adapt login due to Husqvarna API change

- bundles/org.openhab.binding.automower/src/main/java/org/openhab/binding/automower/internal/bridge/AutomowerBridge.java
Automower binding stops updating after ~24h because access token expires after 86399s and token was not checked for expiration.
> [automower] Refresh token if it's expired

- bundles/org.openhab.binding.hydrawise/README.md
- bundles/org.openhab.binding.hydrawise/src/main/java/org/openhab/binding/hydrawise/internal/handler/HydrawiseAccountHandler.java
- bundles/org.openhab.binding.hydrawise/src/main/java/org/openhab/binding/hydrawise/internal/handler/HydrawiseControllerHandler.java
- bundles/org.openhab.binding.hydrawise/src/main/resources/OH-INF/thing/channel-types.xml
Fixes a concurrent modification exception, cleans up handler on dispose, fixes totally broken last contact channel
Fixes #13094
> [Hydrawise] concurrent error

- bundles/org.openhab.binding.goecharger/README.md
- bundles/org.openhab.binding.goecharger/src/main/java/org/openhab/binding/goecharger/internal/GoEChargerBindingConstants.java
- bundles/org.openhab.binding.goecharger/src/main/java/org/openhab/binding/goecharger/internal/api/GoEStatusResponseV2DTO.java
- bundles/org.openhab.binding.goecharger/src/main/java/org/openhab/binding/goecharger/internal/handler/GoEChargerV2Handler.java
- bundles/org.openhab.binding.goecharger/src/main/resources/OH-INF/i18n/goecharger.properties
- bundles/org.openhab.binding.goecharger/src/main/resources/OH-INF/thing/thing-types.xml
This PR fixes #13104 and adds the transaction / trx api key to the binding.
> [goecharger] Add transaction api key

- bundles/org.openhab.binding.fineoffsetweatherstation/README.md
- bundles/org.openhab.binding.fineoffsetweatherstation/src/main/java/org/openhab/binding/fineoffsetweatherstation/internal/FineOffsetWeatherStationBindingConstants.java
- bundles/org.openhab.binding.fineoffsetweatherstation/src/main/java/org/openhab/binding/fineoffsetweatherstation/internal/handler/FineOffsetSensorHandler.java
- bundles/org.openhab.binding.fineoffsetweatherstation/src/main/resources/OH-INF/i18n/fineoffsetweatherstation.properties
- bundles/org.openhab.binding.fineoffsetweatherstation/src/main/resources/OH-INF/thing/gateway.xml
- bundles/org.openhab.binding.fineoffsetweatherstation/src/main/resources/OH-INF/thing/sensor.xml
for discussion see here: https://community.openhab.org/t/fine-offset-weather-station-binding-beta-and-discussion/134167/80
> [fineoffsetweatherstation] Add channel for the sensors battery voltage

- bundles/org.openhab.transform.jinja/pom.xml
Updated jinjava library used by jinja transformation to 2.6.0 version (released 2021-10), from 2.5.7 (released 2021-04)
Changes compared to 2.5.7 version, from https://github.com/HubSpot/jinjava/releases
```
2021-10-29 Version 2.6.0 ([Maven Central](https://search.maven.org/artifact/com.hubspot.jinjava/jinjava/2.6.0/jar))
Create interface for object truth values
Catch concurrent modification in for loop
Add Originating Exception Message For A TemplateSyntaxException
Throw a template error when attempting to divide by zero
Make unixtimestamp behave the same as System.currentTimeMillis()
handle null argument in range function
Track Current Processed Node In The Context
Add Base 64 encode and decode filters
2021-09-03 Version 2.5.10 ([Maven …
```
> [transformation.jinja] Update jinjava to 2.6.0 from 2.5.7

- bundles/org.openhab.binding.bluetooth.bluez/src/main/java/org/openhab/binding/bluetooth/bluez/internal/BlueZBluetoothDevice.java
- bundles/org.openhab.binding.bluetooth.bluez/src/main/java/org/openhab/binding/bluetooth/bluez/internal/BlueZPropertiesChangedHandler.java
- bundles/org.openhab.binding.bluetooth.bluez/src/main/java/org/openhab/binding/bluetooth/bluez/internal/events/BlueZEventListener.java
- bundles/org.openhab.binding.bluetooth.bluez/src/main/java/org/openhab/binding/bluetooth/bluez/internal/events/ServiceDataEvent.java
- bundles/org.openhab.binding.bluetooth.generic/src/main/java/org/openhab/binding/bluetooth/generic/internal/GenericBluetoothHandler.java
- bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/BeaconBluetoothHandler.java
- bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/ConnectedBluetoothHandler.java
- bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/notification/BluetoothScanNotification.java
Bluetooth low energy allows broadcasters to advertise not only their presence but also `Service Data`. In `Service Data`, data of a Bluetooth Service's Characteristic can be advertised. Doing so allows a central like openHAB to receive data from a Bluetooth device without the need to connect to it. This helps to reduce power consumption on the peripheral.
[Supplement to the Bluetooth Core Specification](https://www.bluetooth.org/DocMan/handlers/DownloadDoc.ashx?doc_id=282152), 1.11 SERVICE DATA, page 19
The aim of this pull request is to add basic support of `Service Data` to openHAB so that a temperature/humidity sensor broadcasting its value as `Service Data` is supported.
I'm curious what you think about this idea in general @cpmeister and also on how I suggest to implement it. Input …
> [bluetooth] Add support for service data

- bundles/org.openhab.binding.mail/README.md
Corrected action names, see [forum discussion](https://community.openhab.org/t/javascript-cannot-attach-file-to-email/121024/25?u=mherwege)
> [mail] Correct action names

- bundles/org.openhab.binding.wemo/README.md
- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/discovery/WemoDiscoveryParticipant.java
<!--
Thanks for contributing to the openHAB project!
Please describe the goal and effect of your PR here.
Pay attention to the below notes and to *the guidelines* for this repository.
Feel free to delete any comment sections in the template (starting with "<!--").
This just adds the wemo outdoor plug identification so that it is picked up as a plug by the wemo binding. 
I have tested this with my outdoor plug.
> [wemo] Add Wemo Outdoor plug

- bundles/org.openhab.binding.nobohub/src/main/java/org/openhab/binding/nobohub/internal/NoboHubBindingConstants.java
- bundles/org.openhab.binding.nobohub/src/test/java/org/openhab/binding/nobohub/internal/model/SerialNumberTest.java
Minor improvement which gives more properties to detected things, which
should make a little easier for users with these devices to identify them.
Information from https://www.hjemmeautomasjon.no/forums/topic/267-nob%C3%B8-energy-control/?&page=7
> [nobohub] Add more component types with serial numbers.

- bundles/org.openhab.binding.hdpowerview/README.md
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/BatteryKind.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/responses/Shades.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewShadeHandler.java
- bundles/org.openhab.binding.hdpowerview/src/test/java/org/openhab/binding/hdpowerview/HDPowerViewJUnitTests.java
- bundles/org.openhab.binding.hdpowerview/src/test/resources/org/openhab/binding/hdpowerview/shades.json
As explained in #13321 the batteryKind field in ShadeData indicates if the battery channels are required.
This PR makes the battery channels visible (or not) depending on the value of the batteryKind field.
Resolves #13321
> [hdpowerview] Battery channels visible only when required

- bundles/org.openhab.binding.konnected/src/main/java/org/openhab/binding/konnected/internal/gson/KonnectedModuleGson.java
- bundles/org.openhab.binding.konnected/src/main/java/org/openhab/binding/konnected/internal/handler/KonnectedHandler.java
- bundles/org.openhab.binding.konnected/src/main/resources/OH-INF/thing/thing-types.xml
I was hitting a race condition when adding zones. The status seems to be missing from the panel's json response right after new configuration is pushed to the panel and the panel restarts. The was causing a NullPointerException.
> [Konnected] Fixed null pointer exception on state update with missing state

- bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jItem.java
- bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java
- bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/charts/RRD4jChartServlet.java
Using the pool prevents exceptions like:
```
java.nio.channels.ClosedByInterruptException: null
at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:199) ~[?:?]
at sun.nio.ch.FileChannelImpl.endBlocking(FileChannelImpl.java:162) ~[?:?]
at sun.nio.ch.FileChannelImpl.size(FileChannelImpl.java:388) ~[?:?]
at org.rrd4j.core.RrdNioBackend.<init>(RrdNioBackend.java:94) ~[?:?]
at org.rrd4j.core.RrdNioBackendFactory.open(RrdNioBackendFactory.java:163) ~[?:?]
at org.rrd4j.core.RrdBackendFactory.getBackend(RrdBackendFactory.java:521) ~[?:?]
at org.rrd4j.core.RrdDb.<init>(RrdDb.java:627) ~[?:?]
at org.rrd4j.core.RrdDb.of(RrdDb.java:500) ~[?:?]
at org.openhab.persistence.rrd4j.internal.RRD4jPersistenceService.getDB(RRD4jPersistenceService.java:323) ~[?:?]
at …
```
> [rrd4j] Use RrdDbPool to prevent ClosedByInterruptException

- bundles/org.openhab.binding.konnected/README.md
- bundles/org.openhab.binding.konnected/src/main/resources/OH-INF/thing/thing-types.xml
Bugfix for issue when adding channels with the default zone configured. The thing get into an invalid config state when adding a channel with the default zone selected. The only way to add channel for the default zone is to add a channel for a different zone, then go back and edit it to the default value.
The cause is that the zone parameter was marked as required and had a default.
The default value did not make sense to me, so I removed it.
> [Konnected] Removed defaults for zone configuration parameter from the channels

- bundles/org.openhab.persistence.jdbc/README.md
- bundles/org.openhab.persistence.jdbc/pom.xml
- bundles/org.openhab.persistence.jdbc/src/main/feature/feature.xml
See
- https://dev.mysql.com/doc/relnotes/connector-j/8.0/en/
- https://mvnrepository.com/artifact/mysql/mysql-connector-java/8.0.30
Tested by installing compiled bundle as well as mysql-connector into addons directory:
```
openhabian@openhabian:/usr/share/openhab/addons $ ll *mysql* *jdbc*
-rw-r--r-- 1 openhabian openhab 2.4M Jul  1 05:18 mysql-connector-java.jar
-rw-r--r-- 1 openhabian openhab 296K Aug 10 22:26 org.openhab.persistence.jdbc-3.4.0-SNAPSHOT.jar
```
Then checking in database that items are persisted after the upgrade.
> [jdbc] Upgrade MySQL JDBC driver to 8.0.30

- bundles/org.openhab.voice.mimictts/src/main/java/org/openhab/voice/mimic/internal/InputStreamAudioStream.java
- bundles/org.openhab.voice.mimictts/src/main/java/org/openhab/voice/mimic/internal/MimicTTSService.java
- bundles/org.openhab.voice.mimictts/src/main/java/org/openhab/voice/mimic/internal/dto/VoiceDto.java
Using POST method instead of GET allows longer request size.
(with get method, the request fails when the text is too long)
Also, using InputStreamResponseListener avoid keeping the response in-memory before sending it to the audiosink
> [mimictts] Use http method POST instead of GET

- bundles/org.openhab.binding.hccrubbishcollection/src/main/java/org/openhab/binding/hccrubbishcollection/internal/API.java
The API URL has changed. This has been updated in the binding. Built, tested and working fine with current milestone of OH.
> [hccrubbishcollection] Update API URL

- bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/communication/NuvoStatusCodes.java
- bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/handler/NuvoHandler.java
Fix two minor issues:
1. When thing is provisioned from the UI, the port config item was populated with a default value. This caused the MPS4 flag to be set erroneously even when using serial port connections.
2. For serial port connections, the thing was always showing as ONLINE even when the serial port was not actually connected to the amplifier.
> [nuvo] Fix MPS4 flag and online status reporting

- bundles/org.openhab.binding.remoteopenhab/src/main/java/org/openhab/binding/remoteopenhab/internal/handler/RemoteopenhabBridgeHandler.java
The received command (REFRESH) is transmitted as a REFRESH command to
the remote item.
> [remoteopenhab] Handle REFRESH command as any command

- bundles/org.openhab.binding.remoteopenhab/src/main/java/org/openhab/binding/remoteopenhab/internal/handler/RemoteopenhabBridgeHandler.java
Re-use the same pattern as defined in class DateTimeTyoe.
Allows the support of 0 to 9 digits after the seconds.
> [remoteopenhab] Fix the pattern to parse DateTime

- bundles/org.openhab.binding.konnected/README.md
- bundles/org.openhab.binding.konnected/src/main/java/org/openhab/binding/konnected/internal/handler/KonnectedHandler.java
Fixing a bug where the configured onValue for the channel was ignored when sending a status to the panel. The onValue configuration was only considered when receiving a status from the panel. Honoring the onValue configuration is important when using the standard relay boards recommended by Konnected that are low triggered.
> [Konnected] Taking configured onValue into account when sending status to actuator

- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/database/ShadeCapabilitiesDatabase.java
- bundles/org.openhab.binding.hdpowerview/src/test/java/org/openhab/binding/hdpowerview/ShadePositionTest.java
Resolves #13320 
Hunter Douglas has introduced its Generation 3 hubs. And the documentation for Gen 3 includes information (among many other things) about the Shade Capabilities. See screenshot below. Until now the OH binding uses an unofficial Capabilities database that has been based on detective work and trial and error. The Gen 3 official information confirms that 8 out of the 10 Capabilities in OH are indeed correct, but it also indicates that two of the existing Capabilities are reversed, and that one additional Capabilities entry is missing.
This PR swaps Capabilities 3 and 4 to match the Gen 3 official information. And it adds the so far missing Capabilities 10 the binding.
> [hdpowerview] Correct shade capabilities information

- bundles/org.openhab.binding.velux/README.md
- bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/VeluxBindingConstants.java
- bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/handler/VeluxBridgeHandler.java
- bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/handler/VeluxHandler.java
- bundles/org.openhab.binding.velux/src/main/resources/OH-INF/i18n/velux.properties
- bundles/org.openhab.binding.velux/src/main/resources/OH-INF/thing/channels.xml
- bundles/org.openhab.binding.velux/src/main/resources/OH-INF/thing/rollershutter.xml
- bundles/org.openhab.binding.velux/src/main/resources/OH-INF/thing/window.xml
In #12618 we added support for a vane position channel on venetian style blinds. And in that PR the respective `vanePosition` channel was created statically for ALL types of shutters and blinds regardless of whether the actual shutter/blind does physically support vanes. This could be confusing for users who have shutters / blinds that do not support vanes.
In this PR the binding queries each shutter/blind in the hub, and if that device actually supports vanes, then the binding will create a `vanePosition` channel dynamically.
Resolves #13260
PS many thanks to @pacive, @splatch, @lolodomo and @jlaur for support via the community forum..
https://community.openhab.org/t/dynamically-created-channel-not-showing-up-in-main-ui/138150
> [velux] Vane position channel is visible when required

- bundles/org.openhab.binding.fineoffsetweatherstation/src/main/java/org/openhab/binding/fineoffsetweatherstation/internal/domain/Measurand.java
As discovered in https://community.openhab.org/t/fine-offset-weather-station-binding-discussion/134167/112, the current binding produces warnings b/c of missing measurands.
This PR fixes these warnings by:
* fixing the PIEZO_GAIN10 measurand
* skipping the RAIN_PRIO measurand
* skipping the RCSATION measurand
> [fineoffsetweatherstation] Fix measurands

- bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcBaseDAO.java
After upgrading mysql-connector to 8.0.30 this exception was thrown: `class java.time.LocalDateTime cannot be cast to class java.sql.Timestamp`
The problem was introduced with 8.0.23 - more details here:
https://dev.mysql.com/blog-archive/support-for-date-time-types-in-connector-j-8-0/
Regression of #13242
> [jdbc] Fix date cast exception
