openhab/openhab-addons

itests/org.openhab.binding.feed.tests/itest.bndrun
itests/org.openhab.binding.hue.tests/itest.bndrun
itests/org.openhab.binding.max.tests/itest.bndrun
itests/org.openhab.binding.mielecloud.tests/itest.bndrun
itests/org.openhab.binding.modbus.tests/itest.bndrun
itests/org.openhab.binding.nest.tests/itest.bndrun
itests/org.openhab.binding.ntp.tests/itest.bndrun
itests/org.openhab.binding.systeminfo.tests/itest.bndrun
itests/org.openhab.binding.tradfri.tests/itest.bndrun
itests/org.openhab.binding.wemo.tests/itest.bndrun

Related to openhab/openhab-core#2482

Resolve runbundles for XStream upgrade

---

bundles/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/security/LxWsSecurity.java
bundles/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/security/LxWsSecurityHash.java
bundles/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/security/LxWsSecurityToken.java

Added support for SHA-256, without this the recent Miniserver update will reject to assign authentication tokens.
Signed-off-by: Pawel Pieczul <pieczul@gmail.com>

[loxone] Support for SHA-256

---

bundles/org.openhab.binding.melcloud/README.md

I tested several different things. And finally "heatpumpdevice" worked

[melcloud] Fix thing type id in documentation

---

bundles/org.openhab.binding.netatmo/pom.xml
bundles/org.openhab.binding.telegram/pom.xml
bundles/org.openhab.persistence.influxdb/pom.xml
pom.xml

This makes it easier to change the lib version in the future and brings two bindings into using the same version.
Link for the change log of the library:
https://square.github.io/okhttp/changelog_3x/

[telegram] [influxdb] Update okhttp3 lib

---

bundles/org.openhab.binding.systeminfo/pom.xml
bundles/org.openhab.binding.systeminfo/src/main/feature/feature.xml
bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/model/OSHISysteminfo.java
itests/org.openhab.binding.systeminfo.tests/itest.bndrun
itests/org.openhab.binding.systeminfo.tests/pom.xml

Upgrades OSHI from 4.5.2 to 5.8.2.
For all OSHI fixes and improvements, see:
https://github.com/oshi/oshi/blob/master/CHANGELOG.md#580-2021-07-18-581-2021-08-22-582-2021-09-05

[systeminfo] Upgrade OSHI dependency for latest fixes/improvements

---

bundles/org.openhab.binding.modbus/README.md

[modbus] Fix link to modbus developer documentation

---

bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/MieleBindingConstants.java
bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/discovery/MieleApplianceDiscoveryService.java
bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/CoffeeMachineHandler.java

[miele] Fix coffee machine auto-discovery.

---

bundles/org.openhab.persistence.influxdb/README.md

[influxdb] Add info that it's no good idea to override the item tag via metadata

---

bundles/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/handler/MyQAccountHandler.java

thanks to @lolodomo  for pointing this out, this fixes an issue where httpclient cookies for an entire OH instance could be wiped out .  This scopes the cookie deletion to just the MyQ auth URL . 

[myq] Fixes a serious issue that could wipe out all OH cookies 

---

bundles/org.openhab.binding.darksky/README.md

- Added hint about Dark Sky API deprecation

[darksky] Added hint about Dark Sky API deprecation

---

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoHandlerFactory.java
bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/cloud/CloudConnector.java

[miio] force start cloudconnector after credentials are updated

---

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoCommand.java
bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoQuantiyTypes.java
bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/SavedDeviceInfoDTO.java
bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/Utils.java
bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/CommandParameterType.java
bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/cloud/CloudConnector.java
bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/cloud/MiCloudConnector.java
bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoAbstractHandler.java

Improve behaviour after config changes and restarts
Misc changes:
* Add 2 missing commands
* Added hectopascal unit
* Fix url
* typo's

[miio] Save last msgId and misc minor updates

---

bundles/org.openhab.binding.tibber/src/main/java/org/openhab/binding/tibber/internal/handler/TibberHandler.java

Signed-off-by: Stian Kjoglum <stiankj@online.no>
Enhancement to enable websocket reconnect as part of query loop. Also made adjustments to logging behaviour.

[tibber] Modified Websocket connectivity/reconnect

---

bundles/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/protocol/xml/InputWithPresetControlXML.java

[yamahareceiver] Handle 'No Preset' tuner preset response properly

---

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoSendCommand.java
bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/transport/MiIoAsyncCommunication.java

[miio] sending device in MiIoSendCommand

---

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoBasicHandler.java

[miio] Support contact type in basic channel json

---

bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/discovery/OpenUVDiscoveryService.java

Fix #11480
Signed-off-by: Laurent Garnier <lg.hc@ree.fr>

[openuv] Internationalization of discovery result

---

bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/discovery/OpenWeatherMapDiscoveryService.java
bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/i18n/openweathermap.properties
bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/i18n/openweathermap_de.properties
bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/i18n/openweathermap_fr.properties

[openweathermap] Internationalization of discovery results

---

bundles/org.openhab.binding.weathercompany/src/main/java/org/openhab/binding/weathercompany/internal/discovery/WeatherCompanyDiscoveryService.java
bundles/org.openhab.binding.weathercompany/src/main/resources/OH-INF/i18n/weathercompany.properties

[weathercompany] Internationalization of discovery result

---

bundles/org.openhab.binding.vigicrues/src/main/resources/OH-INF/i18n/vigicrues.properties
bundles/org.openhab.binding.vigicrues/src/main/resources/OH-INF/i18n/vigicrues_fr.properties
bundles/org.openhab.binding.vigicrues/src/main/resources/OH-INF/thing/thing-types.xml

Allows translating the binding strings with Crowdin.

[vigicrues] Add default translations to properties file

---

bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/discovery/TradfriDiscoveryParticipant.java
bundles/org.openhab.binding.tradfri/src/main/resources/OH-INF/i18n/tradfri.properties

[tradfri] Internationalization of discovery results

---

bundles/org.openhab.binding.weathercompany/src/main/java/org/openhab/binding/weathercompany/internal/WeatherCompanyHandlerFactory.java
bundles/org.openhab.binding.weathercompany/src/main/java/org/openhab/binding/weathercompany/internal/discovery/WeatherCompanyDiscoveryService.java

[weathercompany] Fix internationalization of discovery service

---

bundles/org.openhab.binding.hue/src/main/resources/OH-INF/i18n/hue.properties
bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/LightLevelSensor.xml

- Fixed unicode character in translation

[hue] Fixed unicode character in translation

---

bundles/org.openhab.binding.twitter/src/main/resources/OH-INF/i18n/twitter.properties

[twitter] Extend properties file with all default translations

---

bundles/org.openhab.binding.mail/src/main/resources/OH-INF/i18n/mail.properties
bundles/org.openhab.binding.mail/src/main/resources/OH-INF/thing/thing-types.xml

[mail] Extend properties file with all default translations

---

bundles/org.openhab.binding.openuv/src/main/resources/OH-INF/i18n/openuv.properties

[openuv] Add missing entries to the default properties file

---

bundles/org.openhab.binding.weathercompany/src/main/resources/OH-INF/i18n/weathercompany.properties

[weathercompany] Add missing entries to the default properties file

---

bundles/org.openhab.binding.kodi/src/main/resources/OH-INF/i18n/kodi.properties

[kodi] Add missing entries to the default properties file

---

bundles/org.openhab.binding.avmfritz/src/main/resources/OH-INF/i18n/avmfritz.properties
bundles/org.openhab.binding.avmfritz/src/main/resources/OH-INF/i18n/avmfritz_de.properties
bundles/org.openhab.binding.avmfritz/src/main/resources/OH-INF/thing/channel-types.xml

- Add missing entries to the default properties file

[avmfritz] Add missing entries to the default properties file

---

bundles/org.openhab.binding.feed/src/main/resources/OH-INF/i18n/feed.properties

[feed] Added default i18n properties file

---

bundles/org.openhab.binding.logreader/src/main/resources/OH-INF/i18n/logreader.properties

[logreader] Added default i18n properties file

---

bundles/org.openhab.binding.icalendar/src/main/resources/OH-INF/i18n/icalendar.properties

[icalendar] Added default i18n properties file

---

bundles/org.openhab.binding.chromecast/src/main/resources/OH-INF/i18n/chromecast.properties

[chromecast] Added default i18n properties file

---

bundles/org.openhab.binding.ojelectronics/src/main/java/org/openhab/binding/ojelectronics/internal/services/RefreshGroupContentService.java
bundles/org.openhab.binding.ojelectronics/src/main/java/org/openhab/binding/ojelectronics/internal/services/RefreshService.java

This is a bugfix for #11531 
Now the extention do not stop working if the server throw not an HTTP-Code 200.

[ojelectronics] Fixing server timeout is stopping the extension

---

bundles/org.openhab.voice.googletts/src/main/resources/OH-INF/i18n/googletts.properties

[googletts] Added default i18n properties file

---

bundles/org.openhab.transform.map/src/main/resources/OH-INF/i18n/transform.properties

For Transformation Services we do not have bundle related information to be translated. They are not configured as `@ConfigurableService`. The name is taken from the feature file.

[transform][map] Added default i18n properties file

---

bundles/org.openhab.voice.voicerss/src/main/resources/OH-INF/i18n/voicerss.properties

[voicerss] Add default translations to properties file

---

bundles/org.openhab.binding.meteoblue/src/main/resources/OH-INF/i18n/meteoblue.properties
bundles/org.openhab.binding.meteoblue/src/main/resources/OH-INF/i18n/meteoblue_fr.properties
bundles/org.openhab.binding.meteoblue/src/main/resources/OH-INF/thing/thing-types.xml

[meteoblue] Add default translations to properties file

---

bundles/org.openhab.binding.remoteopenhab/src/main/java/org/openhab/binding/remoteopenhab/internal/RemoteopenhabHandlerFactory.java
bundles/org.openhab.binding.remoteopenhab/src/main/java/org/openhab/binding/remoteopenhab/internal/discovery/RemoteopenhabDiscoveryParticipant.java
bundles/org.openhab.binding.remoteopenhab/src/main/java/org/openhab/binding/remoteopenhab/internal/discovery/RemoteopenhabDiscoveryService.java
bundles/org.openhab.binding.remoteopenhab/src/main/java/org/openhab/binding/remoteopenhab/internal/exceptions/RemoteopenhabException.java
bundles/org.openhab.binding.remoteopenhab/src/main/java/org/openhab/binding/remoteopenhab/internal/handler/RemoteopenhabBridgeHandler.java
bundles/org.openhab.binding.remoteopenhab/src/main/java/org/openhab/binding/remoteopenhab/internal/handler/RemoteopenhabThingHandler.java
bundles/org.openhab.binding.remoteopenhab/src/main/java/org/openhab/binding/remoteopenhab/internal/rest/RemoteopenhabRestClient.java
bundles/org.openhab.binding.remoteopenhab/src/main/resources/OH-INF/i18n/remoteopenhab.properties

Allows translating the remote openHAB binding strings with Crowdin.

[remoteopenhab] Add all default translations to properties file

---

bundles/org.openhab.binding.nikobus/src/main/java/org/openhab/binding/nikobus/internal/handler/NikobusRollershutterModuleHandler.java

As also discussed [here](https://community.openhab.org/t/nikobus-v2/80241/324), an option to set rollershutter's position (in %) was added. Since Nikobus's rollerhutter module does not provide positioning information, required movement is calculated based on estimated position.

[nikobus] added option to set rollershutter position

---

bundles/org.openhab.binding.windcentrale/src/main/java/org/openhab/binding/windcentrale/internal/config/MillConfig.java
bundles/org.openhab.binding.windcentrale/src/main/java/org/openhab/binding/windcentrale/internal/handler/WindcentraleHandler.java
bundles/org.openhab.binding.windcentrale/src/main/resources/OH-INF/i18n/windcentrale.properties
bundles/org.openhab.binding.windcentrale/src/main/resources/OH-INF/i18n/windcentrale_nl.properties

+eliminate remaining sat warnings

[windcentrale] Add default translations

---

bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/json/request/ICloudAccountDataRequest.java

fixed: iCloud response invalid: null
Signed-off-by: Tom Blum <trinitus01@googlemail.com>
https://community.openhab.org/t/icloud-binding-communication-error/122131/81

[icloud] iCloud response invalid: null (second time)

---

bundles/org.openhab.binding.souliss/src/main/resources/OH-INF/thing/thing-types.xml

fix T14 typical - must be switch instead of trigger
Signed-off-by: Luca Calcaterra <calcaterra.luca@gmail.com>

[Souliss] Fix T14 Typical

---

itests/org.openhab.binding.astro.tests/itest.bndrun
itests/org.openhab.binding.avmfritz.tests/itest.bndrun
itests/org.openhab.binding.feed.tests/itest.bndrun
itests/org.openhab.binding.hue.tests/itest.bndrun
itests/org.openhab.binding.max.tests/itest.bndrun
itests/org.openhab.binding.mielecloud.tests/itest.bndrun
itests/org.openhab.binding.modbus.tests/itest.bndrun
itests/org.openhab.binding.nest.tests/itest.bndrun
itests/org.openhab.binding.ntp.tests/itest.bndrun
itests/org.openhab.binding.systeminfo.tests/itest.bndrun
itests/org.openhab.binding.tradfri.tests/itest.bndrun
itests/org.openhab.binding.wemo.tests/itest.bndrun
itests/org.openhab.persistence.mapdb.tests/itest.bndrun

Depends on https://github.com/openhab/openhab-core/pull/2573

Resolve runbundles for UoM dependency upgrades

---

bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/phonebook/PhonebookActions.java
bundles/org.openhab.binding.tr064/src/main/resources/OH-INF/config/phonebookProfile.xml
bundles/org.openhab.binding.tr064/src/main/resources/OH-INF/i18n/tr064.properties
bundles/org.openhab.binding.tr064/src/main/resources/OH-INF/thing/thing-types.xml

[tr064] Added default i18n properties file

---

CODEOWNERS

Signed-off-by: Anton Kharuzhy <publicantroids@gmail.com>

[MQTT.Homeassistant] added myself to CODEOWNERS

---

.github/openhab-compile-problems.json
.github/workflows/ci-build.yml

Let's test the GHA annotations for errors also in this repo!
Similar to openhab/openhab-core#2543

Report SAT Errors with GHA Annotations

---

itests/org.openhab.binding.astro.tests/itest.bndrun
itests/org.openhab.binding.avmfritz.tests/itest.bndrun
itests/org.openhab.binding.feed.tests/itest.bndrun
itests/org.openhab.binding.hue.tests/itest.bndrun
itests/org.openhab.binding.max.tests/itest.bndrun
itests/org.openhab.binding.mielecloud.tests/itest.bndrun
itests/org.openhab.binding.modbus.tests/itest.bndrun
itests/org.openhab.binding.nest.tests/itest.bndrun
itests/org.openhab.binding.ntp.tests/itest.bndrun
itests/org.openhab.binding.systeminfo.tests/itest.bndrun
itests/org.openhab.binding.tradfri.tests/itest.bndrun
itests/org.openhab.binding.wemo.tests/itest.bndrun
itests/org.openhab.persistence.mapdb.tests/itest.bndrun
pom.xml

https://github.com/bndtools/bnd/wiki/Changes-in-6.1.0
Related to openhab/openhab-core#2583

Update bnd to 6.1.0

---

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/robot/StatusType.java

[miio] add new vacuum status codes

---

bundles/org.openhab.binding.kaleidescape/README.md

Fix incorrect word in player ui documentation.

[kaleidescape] Fix incorrect word in player ui documentation.

---

bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoHandler.java

[wemo] Fix receiving empty binary state during poll

---

bundles/org.openhab.binding.tivo/README.md

Minor cleanup and update/clarification to tivo README.md

[tivo] Minor update and cleanup README.md

---

bundles/org.openhab.binding.miio/README.base.md
bundles/org.openhab.binding.miio/README.md
bundles/org.openhab.binding.miio/pom.xml
bundles/org.openhab.binding.miio/src/main/feature/feature.xml
bundles/org.openhab.binding.miio/src/main/resources/OH-INF/binding/binding.xml
bundles/org.openhab.binding.miio/src/main/resources/OH-INF/i18n/miio.properties

Improve binding desciption so it easier to recognise for which devices it is appliable

[miio] Improve binding description

---

bundles/org.openhab.binding.chromecast/src/main/resources/OH-INF/thing/thing-types.xml

- Added pattern for DateTime channel types

[chromecast] Added pattern for DateTime channel types

---

bundles/org.openhab.binding.miio/src/main/resources/OH-INF/thing/vacuumThing.xml
bundles/org.openhab.binding.ntp/src/main/resources/OH-INF/thing/thing-types.xml

[miio/ntp] Fix wrong "Date" channel category

---

bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/OpenUVHandlerFactory.java
bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/discovery/OpenUVDiscoveryService.java
bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/handler/OpenUVBridgeHandler.java

[openuv] Fix internationalization of discovery result

---

bundles/org.openhab.binding.systeminfo/README.md

Fix the Sitemap and Thing example. 
Signed-off-by: Daniel Lienert <daniel@lienert.cc>

[systeminfo] Fix Thing and Sitemap example

---

bundles/org.openhab.binding.mqtt/src/main/resources/OH-INF/i18n/mqttbroker.properties

Without these English defaults Crowdin would remove German translations.
See: https://github.com/openhab/openhab-addons/pull/11712/

[mqtt] Add missing English translations

---

bundles/org.openhab.voice.pollytts/src/main/resources/OH-INF/i18n/pollytts.properties

This is the only remaining voice add-on which isn't yet translatable with Crowdin.

[pollytts] Add default translations properties file

---

bundles/org.openhab.binding.hue/README.md
bundles/org.openhab.binding.tradfri/README.md
bundles/org.openhab.binding.tradfri/src/main/resources/OH-INF/thing/thing-types.xml

Fixes: #11736
Change URL from https://www.nxp.com/documents/user_manual/JN-UG-3091.pdf to https://www.nxp.com/docs/en/user-guide/JN-UG-3091.pdf.

Fix link to JN-UG-3091.pdf #11736

---

itests/org.openhab.binding.nest.tests/itest.bndrun

Related to https://github.com/openhab/openhab-core/pull/2599

Resolve runbundles for Whiteboard downgrade

---

bundles/org.openhab.binding.urtsi/src/main/resources/OH-INF/binding/binding.xml
bundles/org.openhab.binding.urtsi/src/main/resources/OH-INF/i18n/urtsi.properties

- Fixed leading spaces in translations

[urtsi] Fixed leading spaces in translations

---

bundles/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/handler/MyQLampHandler.java

[myq] Fix for controlling lights

---

bundles/org.openhab.automation.jsscripting/pom.xml
bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/GraalJSScriptEngineFactory.java

[jsscripting] Update library and change config PID 

---

bundles/org.openhab.automation.jsscripting/src/main/resources/OH-INF/i18n/jsscripting.properties

This add-on recently also became configurable with #11656.

[jsscripting] Add default translations

---

bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/OpenhabGraalJSScriptEngine.java

[jsscripting] Support non unix file paths

---

bundles/create_openhab_binding_skeleton.cmd
bundles/create_openhab_binding_skeleton.sh

Update OH version to 3.3.0 in skeleton scripts

---

bundles/org.openhab.binding.touchwand/README.md

Getting rid of some mixed content warnings in the website builds again.

[touchwand] Secure url's for the readme

---

bundles/org.openhab.automation.jrubyscripting/pom.xml

Upgrade jruby version to 9.3.2.0
Also added an optional resolution to jakarta.annotation

[jrubyscripting] Upgrade jruby to 9.3.2.0

---

bundles/org.openhab.automation.jrubyscripting/README.md

[jrubyscripting] Update version to 9.3.2 in README.md

---

bundles/org.openhab.automation.jsscripting/README.md

Example fixed

---

bundles/org.openhab.binding.tradfri/src/main/resources/OH-INF/config/config.xml
bundles/org.openhab.binding.tradfri/src/main/resources/OH-INF/i18n/tradfri.properties

- Fix UTF-8 characters in i18n properties file

[tradfri] Fix UTF-8 characters in i18n properties file

---

bundles/org.openhab.binding.ecotouch/README.md
bundles/org.openhab.binding.ecotouch/src/main/java/org/openhab/binding/ecotouch/internal/EcoTouchConnector.java
bundles/org.openhab.binding.ecotouch/src/main/java/org/openhab/binding/ecotouch/internal/EcoTouchHandler.java
bundles/org.openhab.binding.ecotouch/src/main/java/org/openhab/binding/ecotouch/internal/EcoTouchTags.java
bundles/org.openhab.binding.ecotouch/src/main/resources/OH-INF/thing/thing-types.xml

This is the requested follow-up PR of #10981.

[ecotouch] Fix description of nviSollKuehlen and coolEnableTemp being writable

---

bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/ChannelState.java

Add additional logging information when command is not supported by type.

[MQTT] Add additional logging information

---

bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/OpenAPIUtils.java

Fixes https://github.com/openhab/openhab-addons/issues/11869

[nanoleaf] Reduce to debug logging in case of communication problems

---

bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/handler/DanfossAirUnitHandler.java

Fixes #11304
When working on #11172 I uncovered some network reliability issues with this binding. Some were fixed, but during my tests I noticed a distinct scenario still not working correctly (not a regression, it never did): When the CCM module is unreachable during the handler's `initialize` method, the binding will stay offline forever.
Binding will try once to connect in order for fetch unit name and serial number. If this fails, the polling job will not be scheduled and the binding is essentially dead.
Tests performed:
- Restart openHAB while CCM module is unplugged. Thing will remain **OFFLINE** until CCM module is connected, then will go **ONLINE**, properties will be initialized and channels will start to update …

[danfossairunit] Fix inability to recover from network issues on initialization

---

bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/discovery/YeelightDiscoveryService.java
bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/device/DeviceFactory.java
bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/enums/DeviceType.java
bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/services/DeviceManager.java

Signed-off-by: Vlado Ilic <kakonema@gmail.com>

[Yeelight] Add color4 bulb

---

bundles/org.openhab.binding.remoteopenhab/src/main/resources/OH-INF/i18n/remoteopenhab.properties

Result of mvn i18n:generate-default-translations

[remoteopenhab] Reorder default translation properties

---

bundles/org.openhab.binding.powermax/src/main/resources/OH-INF/i18n/powermax.properties
bundles/org.openhab.binding.powermax/src/main/resources/OH-INF/thing/ip.xml
bundles/org.openhab.binding.powermax/src/main/resources/OH-INF/thing/serial.xml

Also run mvn i18n:generate-default-translations

[powermax] Add few missing default translation properties

---

bundles/org.openhab.binding.dali/src/main/java/org/openhab/binding/dali/internal/protocol/DaliFrame.java

Signed-off-by: Robert Schmid <r.schmid@outlook.com>
This fixes an out-of-range bug that prevented DALI frames from being created.
(The counter variable that helps in copying bytes from a list into an array in reverse order should be 1 in the first loop iteration.)
This bug was introduced when I incorporated change requests as part of my original PR for the binding, and I somehow missed to test this afterwards.
With this fix, the binding works as expected. 😅 
Happy new year!

[dali] Fix frame packing

---

bundles/org.openhab.binding.wolfsmartset/src/main/java/org/openhab/binding/wolfsmartset/internal/dto/GetParameterValuesDTO.java
bundles/org.openhab.binding.wolfsmartset/src/main/java/org/openhab/binding/wolfsmartset/internal/handler/WolfSmartsetUnitThingHandler.java

Signed-off-by: Bo Biene <openhab.github@biene.eu>
Fix for #11930

[wolfsmartset] Fix NullPointerException when updating values

---

bundles/org.openhab.binding.harmonyhub/pom.xml
bundles/org.openhab.binding.harmonyhub/src/main/java/org/openhab/binding/harmonyhub/internal/HarmonyHubBindingConstants.java
bundles/org.openhab.binding.harmonyhub/src/main/java/org/openhab/binding/harmonyhub/internal/discovery/HarmonyHubDiscoveryService.java
bundles/org.openhab.binding.harmonyhub/src/main/java/org/openhab/binding/harmonyhub/internal/handler/HarmonyHubHandler.java

see https://community.openhab.org/t/things-discovered-but-already-configured/130807/12 for a discussion.  

[harmonyhub] Adds a RepresentationProperty to discovery to avoid duplicate inbox entries

---

bundles/org.openhab.automation.jsscripting/README.md

Fixed path to JS-Joda github page to be formatter as external links by simply deleting the preceding "#"

[jsscripting] Fixed links to JS-Joda

---

itests/org.openhab.binding.mielecloud.tests/src/main/java/org/openhab/binding/mielecloud/internal/handler/AbstractMieleThingHandlerTest.java
itests/org.openhab.binding.mielecloud.tests/src/main/java/org/openhab/binding/mielecloud/internal/handler/CoffeeDeviceThingHandlerTest.java
itests/org.openhab.binding.mielecloud.tests/src/main/java/org/openhab/binding/mielecloud/internal/handler/CoolingDeviceThingHandlerTest.java
itests/org.openhab.binding.mielecloud.tests/src/main/java/org/openhab/binding/mielecloud/internal/handler/DishWarmerDeviceThingHandlerTest.java
itests/org.openhab.binding.mielecloud.tests/src/main/java/org/openhab/binding/mielecloud/internal/handler/DishwasherDeviceThingHandlerTest.java
itests/org.openhab.binding.mielecloud.tests/src/main/java/org/openhab/binding/mielecloud/internal/handler/DryerDeviceThingHandlerTest.java
itests/org.openhab.binding.mielecloud.tests/src/main/java/org/openhab/binding/mielecloud/internal/handler/HobDeviceThingHandlerTest.java
itests/org.openhab.binding.mielecloud.tests/src/main/java/org/openhab/binding/mielecloud/internal/handler/HoodDeviceThingHandlerTest.java
itests/org.openhab.binding.mielecloud.tests/src/main/java/org/openhab/binding/mielecloud/internal/handler/OvenDeviceThingHandlerTest.java
itests/org.openhab.binding.mielecloud.tests/src/main/java/org/openhab/binding/mielecloud/internal/handler/RoboticVacuumCleanerDeviceThingHandlerTest.java
itests/org.openhab.binding.mielecloud.tests/src/main/java/org/openhab/binding/mielecloud/internal/handler/WashingDeviceThingHandlerTest.java
itests/org.openhab.binding.mielecloud.tests/src/main/java/org/openhab/binding/mielecloud/internal/handler/WineStorageDeviceThingHandlerTest.java

[mielecloud] Fix mockito concurrency issues in integration tests

---

bundles/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/internal/EpsonProjectorCommandType.java
bundles/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/internal/EpsonProjectorDevice.java
bundles/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/internal/enums/ErrorMessage.java

[epsonprojector] Fix projector error message display

---

bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcBaseDAO.java

- Add mime data to restored image
Closes #11148

[jdbc] Add mime data to restored image

---

bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcPersistenceService.java

- Do not create table on 'query', only on 'store'
Closes #10201
Closes #11526

[jdbc] Do not create table on 'query', only on 'store'

---

bundles/org.openhab.binding.yamahamusiccast/src/main/java/org/openhab/binding/yamahamusiccast/internal/YamahaMusiccastBindingConstants.java
bundles/org.openhab.binding.yamahamusiccast/src/main/java/org/openhab/binding/yamahamusiccast/internal/YamahaMusiccastBridgeHandler.java
bundles/org.openhab.binding.yamahamusiccast/src/main/java/org/openhab/binding/yamahamusiccast/internal/YamahaMusiccastConfiguration.java
bundles/org.openhab.binding.yamahamusiccast/src/main/java/org/openhab/binding/yamahamusiccast/internal/YamahaMusiccastHandler.java
bundles/org.openhab.binding.yamahamusiccast/src/main/java/org/openhab/binding/yamahamusiccast/internal/YamahaMusiccastHandlerFactory.java
bundles/org.openhab.binding.yamahamusiccast/src/main/java/org/openhab/binding/yamahamusiccast/internal/YamahaMusiccastStateDescriptionProvider.java
bundles/org.openhab.binding.yamahamusiccast/src/main/java/org/openhab/binding/yamahamusiccast/internal/dto/DeviceInfo.java
bundles/org.openhab.binding.yamahamusiccast/src/main/java/org/openhab/binding/yamahamusiccast/internal/dto/DistributionInfo.java
bundles/org.openhab.binding.yamahamusiccast/src/main/java/org/openhab/binding/yamahamusiccast/internal/dto/Features.java
bundles/org.openhab.binding.yamahamusiccast/src/main/java/org/openhab/binding/yamahamusiccast/internal/dto/PlayInfo.java
bundles/org.openhab.binding.yamahamusiccast/src/main/java/org/openhab/binding/yamahamusiccast/internal/dto/PresetInfo.java
bundles/org.openhab.binding.yamahamusiccast/src/main/java/org/openhab/binding/yamahamusiccast/internal/dto/RecentInfo.java
bundles/org.openhab.binding.yamahamusiccast/src/main/java/org/openhab/binding/yamahamusiccast/internal/dto/Response.java
bundles/org.openhab.binding.yamahamusiccast/src/main/java/org/openhab/binding/yamahamusiccast/internal/dto/Status.java
bundles/org.openhab.binding.yamahamusiccast/src/main/java/org/openhab/binding/yamahamusiccast/internal/dto/UdpMessage.java

[yamahamusiccast] Fix license headers

---

bundles/org.openhab.binding.yamahamusiccast/NOTICE

On request of maintainer(s) via previous [PR 11880](https://github.com/openhab/openhab-addons/pull/11880)

[yamahamusiccast] Adding NOTICE

---

bundles/org.openhab.binding.androiddebugbridge/src/main/feature/feature.xml
bundles/org.openhab.binding.gpio/src/main/feature/feature.xml
bundles/org.openhab.binding.mielecloud/src/main/feature/feature.xml
bundles/org.openhab.binding.omnilink/src/main/feature/feature.xml
bundles/org.openhab.binding.qbus/src/main/feature/feature.xml

- Remove license header in feature file

Remove license header in feature file

---

bundles/org.openhab.binding.tesla/README.md
bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaAccountHandler.java
bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaSSOHandler.java

[tesla] Clarify and update how refresh tokens can be obtained

---

bundles/org.openhab.binding.innogysmarthome/src/main/java/org/openhab/binding/innogysmarthome/internal/client/InnogyClient.java
bundles/org.openhab.binding.innogysmarthome/src/test/java/org/openhab/binding/innogysmarthome/internal/client/InnogyClientTest.java

This pull request fixes issue #11741, see #11741 for more details.

[innogysmarthome] VariableActuators are now recognized again (#11741)

---

bundles/org.openhab.binding.mqtt.homeassistant/README.md

I got most of this information from https://community.openhab.org/t/oh3-tasmota-via-mqtt-autodiscovery/111630.
IMO at least the gist of it should be in the documentation to help others.
Should I also link the forum? Did I get everything right?

[mqtt] Add documentation about using auto discovery with Tasmota

---

.github/PULL_REQUEST_TEMPLATE.md

Also update jfrog URL, proofreading and improve readability.

PR template: Update marketplace URL; add notes about rebase/labels/update.lst

---

bundles/org.openhab.binding.ipp/src/main/java/org/openhab/binding/ipp/internal/IppBindingConstants.java
bundles/org.openhab.binding.ipp/src/main/java/org/openhab/binding/ipp/internal/discovery/IppPrinterDiscoveryParticipant.java
bundles/org.openhab.binding.ipp/src/main/java/org/openhab/binding/ipp/internal/factory/IppHandlerFactory.java
bundles/org.openhab.binding.ipp/src/main/java/org/openhab/binding/ipp/internal/handler/IppPrinterHandler.java
bundles/org.openhab.binding.ipp/src/main/resources/OH-INF/thing/thing-types.xml

- Added representation property and code improvements

[ipp] Added representation property and code improvements

---

bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/database/ShadeCapabilitiesDatabase.java

Added shade type 18 to database. 

[hdpowerview] update shade database

---

bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcBaseDAO.java
bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcDerbyDAO.java
bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcH2DAO.java
bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcHsqldbDAO.java
bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcPostgresqlDAO.java
bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcSqliteDAO.java
bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/dto/ItemVO.java
bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcMapper.java
bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcPersistenceService.java
bundles/org.openhab.persistence.jdbc/src/test/java/org/openhab/persistence/jdbc/db/JdbcBaseDAOTest.java
bundles/org.openhab.persistence.jdbc/src/test/java/org/openhab/persistence/jdbc/internal/JdbcPersistenceServiceTest.java

- Implement `ModifiablePersistenceService` interface for MySQL and MariaDB
See https://github.com/openhab/openhab-core/issues/2618

[jdbc] Implement 'ModifiablePersistenceService' interface

---

bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcBaseDAO.java
bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcMapper.java
bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcPersistenceService.java
bundles/org.openhab.persistence.jdbc/src/test/java/org/openhab/persistence/jdbc/db/JdbcBaseDAOTest.java

- Removed check if item exists to allow to truncate data for clean-ups
Successor of #11922
See https://github.com/openhab/openhab-core/pull/2668#discussion_r785317340

[jdbc] Removed check if item exists to allow to truncate data for clean-ups

---

bundles/org.openhab.binding.yamahamusiccast/src/main/resources/OH-INF/i18n/yamahamusiccast.properties

[yamahamusiccast] Add missing default translation properties

---

bundles/org.openhab.binding.electroluxair/src/main/resources/OH-INF/i18n/electroluxair.properties

[electroluxair] Add missing default translation properties

---

bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/KM200Device.java
bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/KM200HandlerFactory.java
bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/discovery/KM200GatewayDiscoveryService.java
bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/handler/KM200GatewayHandler.java
bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/handler/KM200SwitchProgramServiceHandler.java

1. This binding requires the installation of JCE. It is needed for the encryption/decription of the communication. I've added a check if JCE is installed because a lot of people is not reading the docu and wundering why this binding is not working. See:
https://community.openhab.org/t/binding-request-buderus-web-gateway/2575/525
2. Removed some warnings

[km200] Added JCE check and removed some warnings

---

bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaVehicleHandler.java

[tesla] Fix NPE when Thing configuration changes

---

bundles/org.openhab.automation.jsscripting/README.md

[jsscripting] changedSince returns a boolean, not a Number

---

bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueBridgeHandler.java
itests/org.openhab.binding.modbus.tests/src/main/java/org/openhab/binding/modbus/tests/ModbusDataHandlerTest.java

- Fixed build by improve config handling
See https://github.com/openhab/openhab-core/pull/2682 and https://github.com/openhab/openhab-core/pull/2699

Fixed build by improve config handling

---

bundles/org.openhab.voice.picotts/README.md

[picotts] Added new chapter for configuration in documentation

---

bundles/org.openhab.voice.pollytts/README.md

[pollytts] Small changes in configuration in documentation

---

bundles/org.openhab.voice.googletts/README.md

[googletts] Configuration example via text file in documentation

---

CODEOWNERS
bom/openhab-addons/pom.xml
bundles/org.openhab.voice.porcupineks/NOTICE
bundles/org.openhab.voice.porcupineks/README.md
bundles/org.openhab.voice.porcupineks/pom.xml
bundles/org.openhab.voice.porcupineks/src/main/feature/feature.xml
bundles/org.openhab.voice.porcupineks/src/main/java/org/openhab/voice/porcupineks/internal/PorcupineKSConfiguration.java
bundles/org.openhab.voice.porcupineks/src/main/java/org/openhab/voice/porcupineks/internal/PorcupineKSConstants.java
bundles/org.openhab.voice.porcupineks/src/main/java/org/openhab/voice/porcupineks/internal/PorcupineKSService.java
bundles/org.openhab.voice.porcupineks/src/main/resources/OH-INF/config/config.xml
bundles/org.openhab.voice.porcupineks/src/main/resources/OH-INF/i18n/porcupineks.properties
bundles/pom.xml

This voice service allows you to use the PicoVoice product Porcupine as your keyword spotter in openHAB.

[porcupineks] Keyword Spotter, initial contribution

---

bundles/org.openhab.voice.pollytts/README.md

[pollytts] Fix typo in documentation

---

bundles/org.openhab.voice.voicerss/README.md
bundles/org.openhab.voice.voicerss/src/main/resources/OH-INF/config/config.xml
bundles/org.openhab.voice.voicerss/src/main/resources/OH-INF/i18n/voicerss.properties

[voicerss] Updated documentation (config, voices)

---

bundles/org.openhab.voice.googletts/README.md
bundles/org.openhab.voice.mactts/README.md
bundles/org.openhab.voice.marytts/README.md
bundles/org.openhab.voice.picotts/README.md
bundles/org.openhab.voice.pollytts/README.md
bundles/org.openhab.voice.voicerss/README.md

[TTS services] Enhance doc to explain how to setup default voice

---

bundles/org.openhab.voice.voicerss/README.md

[voicerss] Mention where to find configuration settings

---

bundles/org.openhab.voice.pollytts/README.md

[pollytts] Mention where to find configuration settings

---

CODEOWNERS

[voicerss] Declare myself as code maintainer

---

bundles/org.openhab.voice.porcupineks/README.md

[porcupineks] Enhanced documentation

---

bundles/org.openhab.voice.googlestt/NOTICE

add library to NOTICE file
@lolodomo

[googlestt] add library to NOTICE file

---

bundles/org.openhab.voice.porcupineks/NOTICE
bundles/org.openhab.voice.porcupineks/README.md
bundles/org.openhab.voice.porcupineks/pom.xml

add library to NOTICE file and update to porcupine 2.1
@lolodomo

[porcupineks] add library to NOTICE file and update to porcupine 2.1

---

bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/WemoBindingConstants.java
bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/WemoHandlerFactory.java
bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoBaseThingHandler.java
bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoHandler.java
bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoInsightHandler.java
bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoMotionHandler.java
bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoSwitchHandler.java
itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/handler/test/WemoInsightHandlerTest.java

Fixes #12105
Review notes:
- First commit contains **no logic/code changes**, just extraction/separation. Method `onValueReceived()` was copied into each handler and the parts not concerning that handler were removed.
- This is a work-in-progress, but code is ready to be merged at any time to reduce potential conflicts with other ongoing work and to keep review process manageable.
- Next steps will be some actual refactoring of `onValueReceived()`, see linked issue for details.

[wemo] Separate handlers for Insight, Motion and Socket/Light Switch

---

bundles/org.openhab.voice.googlestt/README.md
bundles/org.openhab.voice.googlestt/src/main/java/org/openhab/voice/googlestt/internal/GoogleSTTConstants.java
bundles/org.openhab.voice.googlestt/src/main/java/org/openhab/voice/googlestt/internal/GoogleSTTService.java

Documentation enhanced to explain how to setup the default STT.

[googlestt] Adjust service label for consistency with TTS services.

---

bundles/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/internal/VoiceRSSTTSService.java
bundles/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/internal/cloudapi/CachedVoiceRSSCloudImpl.java
bundles/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/internal/cloudapi/VoiceRSSCloudAPI.java
bundles/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/internal/cloudapi/VoiceRSSCloudImpl.java

Also fix few typos
Also small changes regarding log levels and exception handling

[voicerss] Hide the API key when logging API URL

---

bundles/org.openhab.binding.mqtt.generic/src/main/resources/OH-INF/thing/channels.xml

[mqtt.generic] Rename channel label from Percentage Value to Dimmer

---

bundles/org.openhab.automation.jsscripting/README.md
bundles/org.openhab.automation.jsscripting/pom.xml

[jsscripting] Updates to latest openhab-js library

---

bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitCharacteristicFactory.java

recent regression from handling QuantityType

[homekit] handle NULL/UNDEF for temperature characteristics

---

bundles/org.openhab.automation.jsscripting/src/main/resources/node_modules/@jsscripting-globals.js

See https://github.com/openhab/openhab-js/issues/50

[jsscripting] Append the ruleID or file name to the logger when console logging

---

bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/LifxProduct.java

Allows for discovering all the new LIFX products and their features.
See: https://github.com/LIFX/products/blob/master/products.json

[lifx] Add support for new LIFX products

---

bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/handler/DaikinAcUnitHandler.java
bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/handler/DaikinAirbaseUnitHandler.java

[daikin] Fix NPE when setting Airbase zones on startup

---

bundles/org.openhab.binding.mqtt/README.md
bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/handler/BrokerHandler.java
bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/handler/BrokerHandlerConfig.java
bundles/org.openhab.binding.mqtt/src/main/resources/OH-INF/thing/thing-types.xml

Support birth and shutdown message for OpenHAB MQTT to complete the LWT feature. Resolve #12104

[mqtt] Add birth and shutdown message

---

bundles/org.openhab.binding.playstation/README.md

Hello,
I am a complete newbie at this and it was really difficult to understand how to obtain the user credential with the provided instructions.
I hope this additional info will make it easier for others.

[playstation] Clarified the part to obtain configuration info

---

bundles/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/internal/VoiceRSSTTSService.java
bundles/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/tool/CreateTTSCache.java

[voicerss] Null annotations added on the main service class

---

bundles/org.openhab.binding.hdpowerview/README.md

Update discovery notes and examples after these latest changes:
- #12061
- #11637
- #11534
- #11206
- #11198
- #11155

[hdpowerview] Update README after latest changes

---

bundles/org.openhab.binding.tibber/src/main/java/org/openhab/binding/tibber/internal/handler/TibberHandler.java

Signed-off-by: Stian Kjoglum <stiankj@online.no>
Enhancement for websocket re-econnectivity & fix item/channel response.
Closes #11711.

[tibber] Enhancement for websocket re-econnectivity & fix item/channel response

---

CODEOWNERS
bom/openhab-addons/pom.xml
bundles/org.openhab.binding.herzborg/NOTICE
bundles/org.openhab.binding.herzborg/README.md
bundles/org.openhab.binding.herzborg/pom.xml
bundles/org.openhab.binding.herzborg/src/main/feature/feature.xml
bundles/org.openhab.binding.herzborg/src/main/java/org/openhab/binding/herzborg/internal/Bus.java
bundles/org.openhab.binding.herzborg/src/main/java/org/openhab/binding/herzborg/internal/BusHandler.java
bundles/org.openhab.binding.herzborg/src/main/java/org/openhab/binding/herzborg/internal/CurtainConfiguration.java
bundles/org.openhab.binding.herzborg/src/main/java/org/openhab/binding/herzborg/internal/CurtainHandler.java
bundles/org.openhab.binding.herzborg/src/main/java/org/openhab/binding/herzborg/internal/HerzborgBindingConstants.java
bundles/org.openhab.binding.herzborg/src/main/java/org/openhab/binding/herzborg/internal/HerzborgHandlerFactory.java
bundles/org.openhab.binding.herzborg/src/main/java/org/openhab/binding/herzborg/internal/SerialBus.java
bundles/org.openhab.binding.herzborg/src/main/java/org/openhab/binding/herzborg/internal/SerialBusConfiguration.java
bundles/org.openhab.binding.herzborg/src/main/java/org/openhab/binding/herzborg/internal/SerialBusHandler.java
bundles/org.openhab.binding.herzborg/src/main/java/org/openhab/binding/herzborg/internal/dto/HerzborgProtocol.java
bundles/org.openhab.binding.herzborg/src/main/resources/OH-INF/binding/binding.xml
bundles/org.openhab.binding.herzborg/src/main/resources/OH-INF/thing/thing-types.xml
bundles/pom.xml

Supports Herzborg curtain motors over RS-485 network.
Initial contribution.
Signed-off-by: Pavel Fedin <pavel_fedin@mail.ru>

[herzborg] Herzborg binding

---

bundles/org.openhab.transform.jinja/README.md

[jinja] Update README.md

---

bundles/org.openhab.binding.ojelectronics/src/main/java/org/openhab/binding/ojelectronics/internal/services/SignInService.java

This fixes error #11531 if the server returns an error while signing in. In this case it is a issue with the connection or the server and not with the username or password.

    [ojelectronics]    Fixing Issue if server returns not 200 while signing in

---

bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/netutils/WebSocketConnection.java

[deconz] Prevent Null Pointer Exception if socket connection is broken

---

bundles/org.openhab.voice.porcupineks/src/main/java/org/openhab/voice/porcupineks/internal/PorcupineKSService.java

Fixes file bundle extraction on Windows and null pointer exception

[porcupineks] fix file bundle extraction on Windows and null pointer exception 

---

bundles/org.openhab.binding.exec/src/main/java/org/openhab/binding/exec/internal/ExecWhitelistWatchService.java
bundles/org.openhab.binding.hpprinter/src/main/java/org/openhab/binding/hpprinter/internal/HPPrinterHandler.java
bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/handler/LifxLightHandler.java
bundles/org.openhab.binding.luxtronikheatpump/src/main/java/org/openhab/binding/luxtronikheatpump/internal/LuxtronikHeatpumpHandler.java
bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/MiIoDatabaseWatchService.java
bundles/org.openhab.binding.surepetcare/src/main/java/org/openhab/binding/surepetcare/internal/handler/SurePetcareBaseObjectHandler.java
bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/handler/utils/ExtendedBaseBridgeHandler.java
bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/handler/utils/ExtendedBaseThingHandler.java
bundles/org.openhab.transform.exec/src/main/java/org/openhab/transform/exec/internal/ExecTransformationWhitelistWatchService.java
bundles/org.openhab.transform.javascript/src/main/java/org/openhab/transform/javascript/internal/TransformationScriptWatcher.java

Related to https://github.com/openhab/openhab-core/pull/2735

adjustments after changing null-annotations for updating properties

---

bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/LightThingHandler.java
bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/SensorBaseThingHandler.java
bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/i18n/deconz.properties

Fixes #12244
Please see linked issue for details.

[deconz] Fix unreachable lights and sensors being marked as GONE

---

bundles/org.openhab.binding.fronius/README.md
bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/api/MeterRealtimeBodyDataDTO.java

Add support for Fronius Smart Meter 65A
Link to the feature request: https://community.openhab.org/t/oh3-and-fronius-binding/109565/14

[fronius] Add support for Fronius Smart Meter 65A

---

bundles/org.openhab.binding.feican/src/main/resources/OH-INF/thing/channels.xml

[feican] Add semantic tags on channel color_temperature

---

bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/thing/sensor.xml

[shelly] Category added to channel type sensorHumidity

---

bundles/org.openhab.binding.max/src/main/resources/OH-INF/thing/thing-types.xml

[max] Use defined semantic tags

---

bundles/org.openhab.binding.hydrawise/src/main/java/org/openhab/binding/hydrawise/internal/handler/HydrawiseControllerHandler.java

[hydrawise] Support unused zones

---

bundles/org.openhab.binding.bigassfan/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.cbus/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.cm11a/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.dmx/src/main/resources/OH-INF/thing/channels.xml
bundles/org.openhab.binding.enocean/src/main/resources/OH-INF/thing/channels.xml
bundles/org.openhab.binding.enocean/src/main/resources/OH-INF/thing/gernericChannels.xml
bundles/org.openhab.binding.freebox/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.innogysmarthome/src/main/resources/OH-INF/thing/channels.xml
bundles/org.openhab.binding.lifx/src/main/resources/OH-INF/thing/channel.xml
bundles/org.openhab.binding.lutron/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.mihome/src/main/resources/OH-INF/thing/channel.xml
bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/channels.xml
bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/thing/lights.xml
bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/thing/relay.xml
bundles/org.openhab.binding.smartthings/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.souliss/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.velbus/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.wemo/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.wled/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.yeelight/src/main/resources/OH-INF/thing/channels.xml

Also replace unknwon category DimmableCT by ColorLight
Fix #12263

Replace unknown category DimmableLight by Light

---

bundles/org.openhab.binding.lifx/src/main/resources/OH-INF/thing/channel.xml

[lifx] Cleanup semantic tags

---

bundles/org.openhab.binding.dmx/src/main/resources/OH-INF/thing/channels.xml

[dmx] Fix tags for channel color_temperature

---

bundles/org.openhab.binding.souliss/src/main/resources/OH-INF/thing/thing-types.xml

[souliss] Fix semantic tags

---

bundles/org.openhab.binding.souliss/src/main/resources/OH-INF/thing/thing-types.xml

Related to #12262 
Follow-up #12269

[souliss] Remove tags from channel type power

---

bundles/org.openhab.binding.sagercaster/src/main/resources/OH-INF/thing/thing-types.xml

[sagercaster] Cleanup semantic tags

---

bundles/org.openhab.binding.vigicrues/src/main/resources/OH-INF/thing/thing-types.xml

[vigicrues] Cleanup semantic tags

---

bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/thing/group-thing-types.xml
bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/thing/light-thing-types.xml

[deconz] Cleanup semantic tags

---

bundles/org.openhab.binding.millheat/src/main/resources/OH-INF/thing/channels.xml

[millheat] Cleanup semantic tags

---

bundles/org.openhab.binding.airquality/src/main/resources/OH-INF/thing/thing-types.xml

[airquality] Cleanup semantic tags

---

bundles/org.openhab.binding.omnilink/src/main/resources/OH-INF/thing/lock.xml

[omnilink] Removed tags from channel type lock_switch

---

itests/org.openhab.binding.modbus.tests/src/main/java/org/openhab/binding/modbus/tests/ModbusDataHandlerTest.java

Fixed modbus integration tests
Closes #12278

Fixed modbus integration tests

---

bundles/org.openhab.binding.amplipi/src/main/java/org/openhab/binding/amplipi/internal/AmpliPiBindingConstants.java
bundles/org.openhab.binding.amplipi/src/main/java/org/openhab/binding/amplipi/internal/AmpliPiGroupHandler.java
bundles/org.openhab.binding.amplipi/src/main/java/org/openhab/binding/amplipi/internal/AmpliPiUtils.java
bundles/org.openhab.binding.amplipi/src/main/java/org/openhab/binding/amplipi/internal/AmpliPiZoneHandler.java
bundles/org.openhab.binding.amplipi/src/main/resources/OH-INF/thing/thing-types.xml

Add support for `IncreaseDecreaseType` commands for zone and group volumes.
https://github.com/openhab/openhab-addons/issues/12291

[amplipi] Add support for incremental volume control

---

bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcMapper.java

- Catch exception in case of connection to database failed during activation of service
See https://github.com/openhab/openhab-core/issues/2630

[jdbc] Catch exception in case of connection to database failed during activation of service

---

bundles/org.openhab.binding.daikin/README.md
bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/discovery/DaikinACUnitDiscoveryService.java

This PR makes it possible to disable background discovery, and adds a note in the documentation on how to achieve it.

[daikin] Add the ability to disable background discovery

---

bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/connection/OpenWeatherMapConnection.java
bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/handler/AbstractOpenWeatherMapHandler.java

- Call `Thread.currentThread().interrupt()` on `InterruptedException`

[openweathermap] Call Thread.currentThread().interrupt() on InterruptedException

---

bundles/org.openhab.voice.googlestt/src/main/java/org/openhab/voice/googlestt/internal/GoogleSTTService.java

Do not force close background task.
@lolodomo, for reference, this is the change I was talking about in the VoskSTT PR https://github.com/openhab/openhab-addons/pull/12249#discussion_r807709755

[googlestt] lazy abort

---

bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/HDPowerViewWebTargets.java

[hdpowerview] Interrupt current thread on InterruptedException

---

bundles/org.openhab.voice.watsonstt/src/main/java/org/openhab/voice/watsonstt/internal/WatsonSTTService.java

Do not force close background task.
@lolodomo, for reference, this is the change I was talking about in the VoskSTT PR https://github.com/openhab/openhab-addons/pull/12249#discussion_r807709755

[watsonstt] lazy abort

---

bundles/org.openhab.binding.bluetooth.airthings/src/main/resources/OH-INF/i18n/bluetooth.properties
bundles/org.openhab.binding.bluetooth.am43/src/main/resources/OH-INF/i18n/bluetooth.properties
bundles/org.openhab.binding.bluetooth.bluegiga/src/main/resources/OH-INF/i18n/bluetooth.properties
bundles/org.openhab.binding.bluetooth.bluez/src/main/resources/OH-INF/i18n/bluetooth.properties
bundles/org.openhab.binding.bluetooth.blukii/src/main/resources/OH-INF/i18n/bluetooth.properties
bundles/org.openhab.binding.bluetooth.daikinmadoka/src/main/resources/OH-INF/i18n/bluetooth.properties
bundles/org.openhab.binding.bluetooth.enoceanble/src/main/resources/OH-INF/i18n/bluetooth.properties
bundles/org.openhab.binding.bluetooth.generic/src/main/resources/OH-INF/i18n/bluetooth.properties
bundles/org.openhab.binding.bluetooth.govee/src/main/resources/OH-INF/i18n/bluetooth.properties
bundles/org.openhab.binding.bluetooth.roaming/src/main/resources/OH-INF/i18n/bluetooth.properties
bundles/org.openhab.binding.bluetooth.ruuvitag/src/main/resources/OH-INF/i18n/bluetooth.properties

This will allow for translating the Bluetooth Binding in Crowdin.

[bluetooth] Add missing default translations

---

bundles/org.openhab.binding.flicbutton/src/main/resources/OH-INF/i18n/flicbutton.properties

[flicbutton] Add missing i18n translations properties

---

bundles/org.openhab.binding.boschindego/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.digiplex/src/main/resources/OH-INF/thing/bridge.xml
bundles/org.openhab.binding.folding/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.ihc/src/main/resources/OH-INF/thing/channels.xml
bundles/org.openhab.binding.ihc/src/main/resources/OH-INF/thing/controller.xml
bundles/org.openhab.binding.mqtt.generic/src/main/resources/OH-INF/thing/channels.xml
bundles/org.openhab.binding.nibeheatpump/src/main/resources/OH-INF/thing/SMO40.xml
bundles/org.openhab.binding.nibeheatpump/src/main/resources/OH-INF/thing/f1x45.xml
bundles/org.openhab.binding.nibeheatpump/src/main/resources/OH-INF/thing/f1x55.xml
bundles/org.openhab.binding.nibeheatpump/src/main/resources/OH-INF/thing/f470.xml
bundles/org.openhab.binding.nibeheatpump/src/main/resources/OH-INF/thing/f750.xml
bundles/org.openhab.binding.satel/src/main/resources/OH-INF/thing/partition.xml
bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/thing/relay.xml
bundles/org.openhab.binding.spotify/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.venstarthermostat/src/main/resources/OH-INF/thing/thing-types.xml

Remove some of the empty XML tag "description"

---

bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/NetworkBindingConfiguration.java
bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/NetworkBindingConfigurationListener.java
bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/PresenceDetection.java
bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/SpeedTestConfiguration.java
bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/WakeOnLanPacketSender.java
bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/dhcp/DHCPPacketListenerServer.java
bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/handler/SpeedTestHandler.java
bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/utils/LatencyParser.java
bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/utils/NetworkUtils.java
bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/utils/PingResult.java
bundles/org.openhab.binding.network/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.network/src/test/java/org/openhab/binding/network/internal/PresenceDetectionTest.java
bundles/org.openhab.binding.network/src/test/java/org/openhab/binding/network/internal/WakeOnLanPacketSenderTest.java
bundles/org.openhab.binding.network/src/test/java/org/openhab/binding/network/internal/dhcp/DHCPTest.java
bundles/org.openhab.binding.network/src/test/java/org/openhab/binding/network/internal/toberemoved/cache/ExpiringCacheAsyncTest.java
bundles/org.openhab.binding.network/src/test/java/org/openhab/binding/network/internal/toberemoved/cache/ExpiringCacheHelper.java
bundles/org.openhab.binding.network/src/test/java/org/openhab/binding/network/internal/utils/LatencyParserTest.java

Adressing some SAT complains and removed a reference to Apache StringUtils.

[network] Adressing issue #11503

---

bundles/org.openhab.binding.flicbutton/src/main/java/org/openhab/binding/flicbutton/internal/discovery/FlicSimpleclientDiscoveryServiceImpl.java
bundles/org.openhab.binding.flicbutton/src/main/java/org/openhab/binding/flicbutton/internal/handler/FlicButtonEventListener.java
bundles/org.openhab.binding.flicbutton/src/main/java/org/openhab/binding/flicbutton/internal/handler/FlicDaemonBridgeHandler.java

SAT is right. :slightly_smiling_face: 
See: https://github.com/openhab/static-code-analysis/issues/431

[flicbutton] Fix SAT `@NonNull` findings

---

bundles/org.openhab.binding.mielecloud/src/main/java/org/openhab/binding/mielecloud/internal/config/servlet/CreateBridgeServlet.java
bundles/org.openhab.binding.mielecloud/src/test/java/org/openhab/binding/mielecloud/internal/webservice/sse/ExponentialBackoffWithJitterTest.java
bundles/org.openhab.binding.netatmo/pom.xml
bundles/org.openhab.binding.tr064/pom.xml
bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/rest/ScheduleTests.java
bundles/org.openhab.transform.javascript/src/test/java/org/openhab/transform/javascript/internal/JavaScriptTransformationServiceTest.java
itests/org.openhab.binding.mielecloud.tests/src/main/java/org/openhab/binding/mielecloud/internal/config/ConfigFlowTest.java
itests/org.openhab.binding.mielecloud.tests/src/main/java/org/openhab/binding/mielecloud/internal/util/ReflectionUtil.java
pom.xml

* Adds --add-opens to the maven-surefire-plugin config required for deserialization using Gson/XStream
* Upgrades plugin dependencies to JDK 17 compatible versions
* Replaces some reflection that no longer works on JDK 17
* Fixes issues when mocking Random
* Run Nashorn dependant tests only on JDK < 15

Fix Java 17 compilation and test issues

---

bundles/org.openhab.voice.voskstt/README.md
bundles/org.openhab.voice.voskstt/src/main/resources/OH-INF/config/config.xml

I realize the binaries for this architectures were not included when I tryed to run it on raspberry OS.
They are available on the vosk-api github release page so I've added them, now it works perfect on my raspberry pi 4.
Also changed the default value for model preload to false, which seems more logical.

[voskstt] add linux arm and linux aarch64 binaries 

---

bundles/org.openhab.binding.novafinedust/src/main/resources/OH-INF/thing/thing-types.xml

[novafinedust] Fix RFC2217 serial port in configuration

---

bundles/org.openhab.binding.upnpcontrol/src/test/java/org/openhab/binding/upnpcontrol/internal/handler/UpnpRendererHandlerTest.java

- Fix build after DecimalType changes (see https://github.com/openhab/openhab-core/pull/2596)

Fix build after DecimalType changes

---

bundles/org.openhab.binding.souliss/src/main/java/org/openhab/binding/souliss/internal/handler/SoulissT31Handler.java
bundles/org.openhab.binding.souliss/src/main/resources/OH-INF/thing/thing-types.xml

Signed-off-by: Luca Calcaterra calcaterra.luca@gmail.com

[souliss] fix t31 fire and system statuses

---

bundles/org.openhab.binding.ipobserver/src/main/resources/OH-INF/thing/thing-types.xml

[ipobserver] Cleanup semantic tags

---

bundles/org.openhab.binding.openuv/README.md

Gaël, I've included a working configuration and added few notes as discussed and agreed here: https://community.openhab.org/t/new-warn-in-log-since-fresh-3-0-1/119012/3

[openuv] Update README.md

---

bundles/org.openhab.automation.jrubyscripting/README.md
bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/JRubyScriptEngineConfiguration.java
bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/JRubyScriptEngineFactory.java
bundles/org.openhab.automation.jrubyscripting/src/main/resources/OH-INF/config/config.xml
bundles/org.openhab.automation.jrubyscripting/src/main/resources/OH-INF/i18n/jruby.properties

* Add a `require` configuration option to insert a require statement at the beginning of user scripts, primarily to make it easier for GUI users to utilise the jruby helper library.
* Fix a bug in the config.xml with misplaced `advanced` element

[jrubyscripting] Add auto-require scripts option

---

bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/discovery/TradfriDiscoveryParticipant.java
bundles/org.openhab.binding.tradfri/src/main/resources/OH-INF/thing/thing-types.xml
itests/org.openhab.binding.tradfri.tests/src/main/java/org/openhab/binding/tradfri/internal/discovery/TradfriDiscoveryParticipantOSGITest.java

[tradfri] use serial as discovery representation property instead of host

---

bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/handler/FroniusBaseThingHandler.java

Fronius binding is broken due to https://github.com/openhab/openhab-core/pull/2596

[fronius] Fix DecimalType constructor change

---

bundles/org.openhab.voice.porcupineks/src/main/java/org/openhab/voice/porcupineks/internal/PorcupineKSConstants.java
bundles/org.openhab.voice.porcupineks/src/main/java/org/openhab/voice/porcupineks/internal/PorcupineKSService.java

This pr:
* fixes the service name 
* fixes the extraction of the build in keywords in windows
* adds missed modified method

[porcupineks] fix build-in keywords on windows, fix service name and add missed modified

---

bundles/org.openhab.binding.deutschebahn/src/main/java/org/openhab/binding/deutschebahn/internal/DeutscheBahnHandlerFactory.java
bundles/org.openhab.binding.deutschebahn/src/main/java/org/openhab/binding/deutschebahn/internal/DeutscheBahnTimetableHandler.java
bundles/org.openhab.binding.deutschebahn/src/test/java/org/openhab/binding/deutschebahn/internal/DeutscheBahnTimetableHandlerTest.java

Closes #12235
Changed handler to allow passing an custom scheduler for test cases, to fix timing issues in test cases.

[deutschebahn] Fixed timing issue in test case

---

bundles/org.openhab.binding.deutschebahn/src/main/java/org/openhab/binding/deutschebahn/internal/DeutscheBahnTimetableHandler.java
bundles/org.openhab.binding.deutschebahn/src/test/java/org/openhab/binding/deutschebahn/internal/DeutscheBahnTimetableHandlerTest.java
bundles/org.openhab.binding.deutschebahn/src/test/java/org/openhab/binding/deutschebahn/internal/timetable/TimetablesV1ImplTestHelper.java
bundles/org.openhab.binding.deutschebahn/src/test/resources/timetablesDataDifferentOrder/plan/8000226/210816/09.xml

[deutschebahn] Fixed order of stops

---

itests/org.openhab.binding.astro.tests/itest.bndrun
itests/org.openhab.binding.avmfritz.tests/itest.bndrun
itests/org.openhab.binding.feed.tests/itest.bndrun
itests/org.openhab.binding.hue.tests/itest.bndrun
itests/org.openhab.binding.max.tests/itest.bndrun
itests/org.openhab.binding.mielecloud.tests/itest.bndrun
itests/org.openhab.binding.modbus.tests/itest.bndrun
itests/org.openhab.binding.nest.tests/itest.bndrun
itests/org.openhab.binding.ntp.tests/itest.bndrun
itests/org.openhab.binding.systeminfo.tests/itest.bndrun
itests/org.openhab.binding.tradfri.tests/itest.bndrun
itests/org.openhab.binding.wemo.tests/itest.bndrun
itests/org.openhab.persistence.mapdb.tests/itest.bndrun

Depends on openhab/openhab-core#2786

Resolve runbundles for Xtext upgrade

---

bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/dto/SensorState.java
bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/SensorBaseThingHandler.java

For feature description see #12412 
Signed-off-by: Johannes Ott <mail@johannes-ott.net>

[deconz] Add support for lowbattery flag from state response

---

bundles/org.openhab.binding.ambientweather/pom.xml
bundles/org.openhab.binding.ambientweather/src/main/feature/feature.xml

Discussed in https://github.com/openhab/openhab-addons/pull/11153#issuecomment-904545669

[ambientweather] Update socket.io dependency used by ambientweather

---

bundles/org.openhab.binding.millheat/src/main/java/org/openhab/binding/millheat/internal/dto/DeviceDTO.java
bundles/org.openhab.binding.millheat/src/main/java/org/openhab/binding/millheat/internal/model/Heater.java

[millheat] Possibly wrong use of isHoliday instead of canChangeTemp

---

bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/PulseaudioClient.java
bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/handler/PulseaudioBridgeHandler.java
bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/handler/PulseaudioHandler.java

Fix bridge/thing status update
Also update log levels
Fix #12419
Fix #12424

[pulseaudio]  Fix exception handling when connecting

---

bundles/org.openhab.binding.omnilink/pom.xml
bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/OmnilinkBindingConstants.java
bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/OmnilinkBridgeHandler.java

[OmniLink] Bump jomnilink

---

bundles/org.openhab.binding.androiddebugbridge/README.md

Added working compatibility mention with Freebox Pop Player.

[andoiddebugbridge] Update README

---

bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/SomfyTahomaBindingConstants.java
bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/discovery/SomfyTahomaItemDiscoveryService.java
bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaAwningHandler.java
bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaVenetianBlindHandler.java

This PR improves the compatibility with Somfy Connectivity Kit and compatibility with venetian blinds and awnings.
Discussed here: https://github.com/openhab/openhab-addons/issues/12426

[somfytahoma] improved compatibility with Somfy Connectivity Kit

---

bundles/org.openhab.binding.fronius/README.md

See: https://community.openhab.org/t/fronius-symo-goes-offline/134119/7

[fronius] Add a note about enabling Night Mode on the device

---

bundles/org.openhab.binding.ipp/pom.xml
bundles/org.openhab.binding.ipp/src/main/java/org/openhab/binding/ipp/internal/handler/IppPrinterHandler.java

Updates cups4j to 0.7.8 and syncs the cups4j dependencies.

[ipp] Update cups4j and dependencies

---

bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcBaseDAO.java
bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/utils/StringUtilsExt.java

- Fixed parameter ordering while storing values

[jdbc] Fixed parameter ordering while storing values

---

bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/ValueCache.java

A few minor tweaks of the value cache.

[danfossairunit] Minor value cache tweaks

---

bundles/org.openhab.binding.icalendar/src/main/java/org/openhab/binding/icalendar/internal/logic/BiweeklyPresentableCalendar.java

According to section 3.6.1 of RFC 5545 :
```For cases where a "VEVENT" calendar component specifies a "DTSTART" property with a DATE value type but no "DTEND" nor "DURATION" property, the event's duration is taken to be one day. For cases where a "VEVENT" calendar component specifies a "DTSTART" property with a DATE-TIME value type but no "DTEND" property, the event ends on the same calendar date and time of day specified by the "DTSTART" property.```
Currently icalendar binding just ignores calendar entries if they have no DTEND defined.

[icalendar] Adding ability to handle events without DTEND

---

bundles/org.openhab.binding.androiddebugbridge/README.md
bundles/org.openhab.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/AndroidDebugBridgeDynamicCommandDescriptionProvider.java
bundles/org.openhab.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/AndroidDebugBridgeHandler.java
bundles/org.openhab.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/AndroidDebugBridgeHandlerFactory.java

- Added DynamicCommandOptionsProvider to populate 'start-package' Channel
This feature adds support for starting a package from the UI.

[androiddebugbridge] Added DynamicCommandOptionsProvider to populate 'start-package' Channel

---

bundles/org.openhab.binding.modbus/src/main/resources/OH-INF/i18n/modbus.properties
bundles/org.openhab.binding.modbus/src/main/resources/OH-INF/thing/thing-data.xml

- Fixed minor spelling mistake

[modbus] Fixed minor spelling mistake

---

bundles/org.openhab.binding.yamahamusiccast/README.md

[yamahamusiccast] Update README.md

---

bundles/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/protocol/xml/InputWithPresetControlXML.java

Remove usage of org.apache.commons.lang3.ArrayUtils and org.apache.commons.lang3.StringUtils per #7722

[yamahareceiver] Remove Apache commons libraries

---

bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/discovery/SomfyTahomaItemDiscoveryService.java

This PR improves the compatibility with the Somfy Connectivity Kit by adding suppor for the DynamicLight variant.

[somfytahoma] Improved compatibility with the Somfy Connectivity Kit

---

bundles/org.openhab.binding.novafinedust/src/main/java/org/openhab/binding/novafinedust/internal/sds011protocol/SDS011Communicator.java
bundles/org.openhab.binding.novafinedust/src/main/java/org/openhab/binding/novafinedust/internal/sds011protocol/messages/SensorMeasuredDataReply.java

[novafinedust] Fix measurement parsing overflow

---

bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitCharacteristicFactory.java

this PR adds support for Dimmer item type for the rotation speed and fixes the issue reported here 
#12456 

[homekit] fix Fan Rotation Speed. add support for dimmer

---

bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaAccountHandler.java
bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaSSOHandler.java
bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaVehicleHandler.java

[tesla] Set the token creation time as it is no longer provided in the response

---

bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/discovery/OpenUVDiscoveryService.java
bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/handler/OpenUVBridgeHandler.java
bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/handler/OpenUVReportHandler.java

Time channels where always UNDEF.

[openuv] Fix time channels not being updated

---

bundles/org.openhab.automation.pidcontroller/README.md
bundles/org.openhab.automation.pidcontroller/src/main/java/org/openhab/automation/pidcontroller/internal/PIDControllerConstants.java
bundles/org.openhab.automation.pidcontroller/src/main/java/org/openhab/automation/pidcontroller/internal/handler/PIDController.java
bundles/org.openhab.automation.pidcontroller/src/main/java/org/openhab/automation/pidcontroller/internal/handler/PIDControllerTriggerHandler.java
bundles/org.openhab.automation.pidcontroller/src/main/java/org/openhab/automation/pidcontroller/internal/type/PIDControllerTriggerType.java
bundles/org.openhab.voice.watsonstt/src/main/java/org/openhab/voice/watsonstt/internal/WatsonSTTService.java

@lnagel "tomorrow" is now :) Sorry for the delay.

[pidcontroller] Add ability to limit the I-part

---

bundles/org.openhab.binding.benqprojector/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.caddx/src/main/resources/OH-INF/thing/bridge.xml
bundles/org.openhab.binding.comfoair/src/main/resources/OH-INF/config/config.xml
bundles/org.openhab.binding.digiplex/src/main/resources/OH-INF/thing/bridge.xml
bundles/org.openhab.binding.epsonprojector/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.heliosventilation/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.herzborg/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.kaleidescape/src/main/resources/OH-INF/config/config.xml
bundles/org.openhab.binding.monopriceaudio/src/main/resources/OH-INF/thing/channels.xml
bundles/org.openhab.binding.nuvo/src/main/resources/OH-INF/thing/channels.xml
bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/ZBGateway.xml
bundles/org.openhab.binding.oppo/src/main/resources/OH-INF/thing/channels.xml
bundles/org.openhab.binding.proteusecometer/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.serial/src/main/resources/OH-INF/thing/thing-types.xml

Related to openhab/openhab-core#2798

Don't limit serial port options

---

bundles/org.openhab.binding.amazondashbutton/src/main/resources/OH-INF/i18n/amazondashbutton.properties
bundles/org.openhab.binding.digitalstrom/src/main/resources/OH-INF/i18n/digitalstrom.properties
bundles/org.openhab.binding.pixometer/src/main/resources/OH-INF/i18n/pixometer.properties

Fix unexpected leading space in default translations

---

bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/handler/KM200ThingHandler.java

[km200] Cleanup semantic tags

---

itests/org.openhab.binding.modbus.tests/src/main/java/org/openhab/binding/modbus/tests/AbstractModbusOSGiTest.java

This fixes the issue of the integration tests sometimes failing because channels have not yet been linked causing item state to remain null.

[modbus] Make tests more stable

---

bundles/org.openhab.binding.knx/README.md

[knx] Minor wording changes to documentation

---

bundles/org.openhab.binding.spotify/README.md

[spotify] Remove duplicate text and some spelling errors 

---

bundles/org.openhab.binding.knx/README.md
bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/KNXBindingConstants.java
bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/SerialClient.java
bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/config/SerialBridgeConfiguration.java
bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/SerialBridgeThingHandler.java
bundles/org.openhab.binding.knx/src/main/resources/OH-INF/i18n/knx.properties
bundles/org.openhab.binding.knx/src/main/resources/OH-INF/thing/serial.xml

CEMI frame format is used by newer serial devices like kBerry.
Calimero library can be configured to use CEMI instead of default EMI.
Followup on #10407. Relates to #4026.

[knx] Add option to use CEMI frame format for serial devices.

---

bundles/org.openhab.binding.sonos/README.md
bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosBindingConstants.java
bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/discovery/ZonePlayerDiscoveryParticipant.java
bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/i18n/sonos.properties
bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/Five.xml
bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/RoamSL.xml

[sonos] Support added for models Five and Roam SL

---

bundles/org.openhab.io.homekit/README.md

readme updated missing " in Valve description

[homekit]typo in valve accessorie readme

---

bundles/org.openhab.transform.map/src/test/java/org/openhab/transform/map/internal/MapTransformationServiceTest.java

(transform.map] Fix tests on Windows

---

bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/discovery/AVMFritzDiscoveryService.java
bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/AVMFritzBaseBridgeHandler.java

[avmfritz] Do not create a thing type UID using an empty ID

---

bundles/org.openhab.binding.irobot/src/test/java/org/openhab/binding/irobot/internal/handler/RoombaHandlerTest.java

[irobot] Fix failing test (fix thing UID)

---

bundles/org.openhab.binding.luftdateninfo/src/test/java/org/openhab/binding/luftdateninfo/internal/mock/ThingMock.java

[luftdateninfo] Fix tests (fix thing UID and thing type UID)

---

bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/discovery/ZonePlayerDiscoveryParticipant.java

[sonos] Avoid empty thing (type) ID in discovery

---

bundles/org.openhab.binding.omnilink/README.md

[OmniLink] Remove extraneous newlines

---

bundles/org.openhab.binding.renault/README.md
bundles/org.openhab.binding.renault/src/main/java/org/openhab/binding/renault/internal/RenaultConfiguration.java
bundles/org.openhab.binding.renault/src/main/java/org/openhab/binding/renault/internal/api/Constants.java
bundles/org.openhab.binding.renault/src/main/java/org/openhab/binding/renault/internal/api/MyRenaultHttpSession.java
bundles/org.openhab.binding.renault/src/main/resources/OH-INF/i18n/renault.properties
bundles/org.openhab.binding.renault/src/main/resources/OH-INF/thing/thing-types.xml

The API key changes once a year apparently... This causes a communication error and a quick API Code update patch.  I have moved the API key from constants to config. This allows it to be updated with the new value without a re-compile.  I have documented this in the README.
I also updated the charge limit rule to better cope with NULL values in the ChargeMode.
Signed-off-by: Doug Culnane <doug@culnane.net>

[renault] API key to configuration parameter and rule update.

---

bundles/org.openhab.binding.prowl/README.md
bundles/org.openhab.binding.prowl/src/main/java/org/openhab/binding/prowl/internal/ProwlHandler.java
bundles/org.openhab.binding.prowl/src/main/java/org/openhab/binding/prowl/internal/action/ProwlActions.java
bundles/org.openhab.binding.prowl/src/main/resources/OH-INF/i18n/prowl.properties
bundles/org.openhab.binding.prowl/src/main/resources/OH-INF/i18n/prowl_fr.properties
bundles/org.openhab.binding.prowl/src/main/resources/OH-INF/i18n/prowl_it.properties

This PR adds the message priority setting feature as requested here: #10967

[prowl] added the message priority setting feature

---

bundles/org.openhab.binding.dwdunwetter/README.md
bundles/org.openhab.binding.dwdunwetter/README_de.md
bundles/org.openhab.binding.dwdunwetter/src/main/resources/OH-INF/i18n/dwdunwetter.properties
bundles/org.openhab.binding.dwdunwetter/src/main/resources/OH-INF/i18n/dwdunwetter_de.properties
bundles/org.openhab.binding.dwdunwetter/src/main/resources/OH-INF/thing/thing-types.xml

This PR updates the docs to be more clear about which CellID to choose for the binding to work correctly.
It also updates the German README and the description in the Thing configuration.
Those changes were made out of the motivation that I had problems with the binding because of I used a CellID that was not supported, the docs were not clear enough about that point.

[dwdunwetter] Update docs to clarify CellID selection

---

bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/action/OmnilinkActions.java

Fix small regression in #12546 for consistency between JS/DSL actions and documentation - mentioned [here](https://github.com/openhab/openhab-addons/pull/12546#issuecomment-1107915103)

[omnilink] Fix name of DSL rule action

---

bundles/org.openhab.binding.androiddebugbridge/README.md

Comma's are missing + Thing name example added

(androiddebugbridge) Update README.md

---

bundles/org.openhab.binding.iaqualink/src/main/java/org/openhab/binding/iaqualink/internal/handler/IAqualinkHandler.java

[iaqualink] Fix issue using manual pool IDs

---

bundles/org.openhab.binding.jellyfin/src/main/resources/OH-INF/i18n/jellyfin.properties

[jellyfin] Add default translations

---

bundles/org.openhab.binding.groupepsa/src/main/resources/OH-INF/i18n/groupepsa.properties

[groupepsa] Add default translations

---

bundles/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/handler/FreeboxHandler.java

[freebox] Ignore disabled things

---

bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/handler/PowermaxBridgeHandler.java

[powermax] Ignore disabled things

---

bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/handler/OpenWeatherMapAPIHandler.java

[openweathermap] Ignore disabled things

---

bundles/org.openhab.binding.boschshc/README.md
bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/BoschSHCBindingConstants.java
bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/BoschSHCHandlerFactory.java
bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/camera/CameraHandler.java
bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/cameranotification/CameraNotificationService.java
bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/cameranotification/CameraNotificationState.java
bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/cameranotification/dto/CameraNotificationServiceState.java
bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/privacymode/PrivacyModeService.java
bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/privacymode/PrivacyModeState.java
bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/privacymode/dto/PrivacyModeServiceState.java
bundles/org.openhab.binding.boschshc/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/services/cameranotification/CameraNotificationStateTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/services/privacymode/PrivacyModeStateTest.java

- add thing definitions for indoor security camera 360 and outdoor
security camera Eyes
- implement services for privacy mode and camera notifications
- implement camera handler
- add unit tests
- update documentation
closes #12666
Signed-off-by: David Pace <dev@davidpace.de>

[boschshc] Support Bosch Smart Home Cameras (#12666)

---

bundles/org.openhab.binding.amazonechocontrol/README.md

- The bug that alexa reminds twice was fixed
- Fixed spacing to unify the `README`
--> Only changes in Docs
Signed-off-by: Felix Schneider <fs@felix-schneider.org>

[AmazonEchoControl]: Docs: Remove old bug warning & adjust spacing

---

bundles/org.openhab.binding.vesync/src/main/resources/OH-INF/i18n/vesync.properties

[vesync] Add default translations

---

bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/handler/OpenUVBridgeHandler.java
bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/handler/OpenUVReportHandler.java
bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/json/OpenUVResult.java

[openuv] adressing issue #12688

---

bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/channelhelper/EventChannelHelper.java

[netatmo] Do not ignore updated events (same timestamp)

---

bundles/org.openhab.binding.ihc/src/main/resources/OH-INF/thing/channels.xml
bundles/org.openhab.binding.ism8/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.paradoxalarm/src/main/resources/OH-INF/thing/partition.xml
bundles/org.openhab.binding.paradoxalarm/src/main/resources/OH-INF/thing/zone.xml
bundles/org.openhab.binding.souliss/src/main/resources/OH-INF/thing/thing-types.xml

Fix case for item-type tag value (channel definition)

---

bundles/org.openhab.binding.knx/src/main/resources/OH-INF/thing/device.xml

[knx] Fix item-type value for channel type datetime-control

---

bundles/org.openhab.binding.automower/src/main/resources/OH-INF/thing/thing-types.xml

[automower] Fix item-type value for channel type positionType

---

bundles/org.openhab.binding.oceanic/src/main/resources/OH-INF/thing/channel-types.xml

[oceanic] Fix item-type value for channel types reserve and flow

---

bundles/org.openhab.automation.jsscripting/README.md

Signed-off-by: Daniel Lienert <daniel+github@lienert.cc>

[jsscripting] DOCS: Add missing bracket

---

bundles/org.openhab.binding.gree/README.md

Mention that Sinclair devices using the Gree protocol are supported as well (EWPE smart).

[gree] mention in README.md that Sinclair devices are supported as well

---

bundles/org.openhab.binding.haywardomnilogic/src/main/java/org/openhab/binding/haywardomnilogic/internal/HaywardThingHandler.java
bundles/org.openhab.binding.haywardomnilogic/src/main/resources/OH-INF/thing/bow.xml
bundles/org.openhab.binding.haywardomnilogic/src/main/resources/OH-INF/thing/heater.xml

[haywardomnilogic] Fix item-type value for channel types waterflow and

---

bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/handler/KM200ThingHandler.java

[km200] Fix item type for dynamic channel type

---

bundles/org.openhab.binding.openthermgateway/src/main/java/org/openhab/binding/openthermgateway/handler/OpenThermGatewayHandler.java

[openthermgateway] Fix missing transition from offline to online

---

bundles/org.openhab.binding.webthing/src/main/java/org/openhab/binding/webthing/internal/channel/Channels.java
bundles/org.openhab.binding.webthing/src/main/java/org/openhab/binding/webthing/internal/link/TypeMapping.java

[webthing] Fix item type for dynamic channel

---

bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/SecurityApi.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/data/NetatmoConstants.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/PresenceCapability.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/SecurityCapability.java

Signed-off-by: Sven Strohschein <sven.strohschein@gmail.com>
Pull request to fix the floodlight switch modes for the outdoor camera. See issue #12741 for more information.
Fixes #12741

[netatmo] Floodlight switch repaired

---

bundles/org.openhab.binding.goecharger/README.md
bundles/org.openhab.binding.goecharger/src/main/resources/OH-INF/i18n/goecharger.properties
bundles/org.openhab.binding.goecharger/src/main/resources/OH-INF/thing/thing-types.xml

Fixes #12735
Signed-off-by: Reinhard Plaim <reinhardplaim@gmail.com>

[goecharger] Add powerAll to thing-types

---

bundles/org.openhab.binding.sensibo/src/main/java/org/openhab/binding/sensibo/internal/handler/SensiboSkyHandler.java

[sensibo] Fix tags for target temperature channel types built

---

bundles/org.openhab.voice.porcupineks/src/main/resources/OH-INF/config/config.xml
bundles/org.openhab.voice.porcupineks/src/main/resources/OH-INF/i18n/porcupineks.properties

[porcupineks] Fix description of the sensitivity parameter

---

bundles/org.openhab.voice.voskstt/src/main/resources/OH-INF/config/config.xml
bundles/org.openhab.voice.voskstt/src/main/resources/OH-INF/i18n/voskstt.properties

[voskstt] Update the description of the preloadModel parameter

---

bundles/org.openhab.binding.dsmr/src/main/java/org/openhab/binding/dsmr/internal/device/cosem/CosemObjectType.java

DSMR identifier cosem objects should be parsed as hex values

---

README.md

- Also put command in blocks to make them stand out more in the readme.

Updated readme, added how to generate i18n en properties file/kar files/use -pl option

---

bundles/org.openhab.binding.fineoffsetweatherstation/src/main/resources/OH-INF/thing/gateway.xml

[fineoffsetweatherstation] Align XML with default translations

---

bundles/org.openhab.binding.netatmo/src/main/resources/OH-INF/config/config.xml
bundles/org.openhab.binding.netatmo/src/main/resources/OH-INF/i18n/netatmo.properties

[netatmo] Add translations for config parameters

---

bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/discovery/NetatmoDiscoveryService.java

[netatmo] Discovery using current value of readFriends parameter

---

bundles/org.openhab.binding.bigassfan/README.md

https://community.openhab.org/t/bigassfan-haiku-no-longer-working-with-new-firmware/136134

[bigassfan] Add warning about new incompatible firmware

---

bundles/org.openhab.binding.netatmo/README.md
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/AuthenticationApi.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/config/BindingConfiguration.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/ApiBridgeHandler.java
bundles/org.openhab.binding.netatmo/src/main/resources/OH-INF/binding/binding.xml
bundles/org.openhab.binding.netatmo/src/main/resources/OH-INF/i18n/netatmo.properties
bundles/org.openhab.binding.netatmo/src/main/resources/OH-INF/i18n/netatmo_it.properties

[netatmo] Removing feature restriction from binding configuration

---

pom.xml

Upgrade directory-maven-plugin from 0.3.1 to 1.0

---

bundles/org.openhab.voice.porcupineks/src/main/java/org/openhab/voice/porcupineks/internal/PorcupineKSService.java

In order to allow the service to be called by concurrent dialog processors, the boolean used for controlling the execution should be moved to the method scope, similar to what we did in other voice services.

[porcupineks] concurrency fix

---

bundles/org.openhab.binding.jellyfin/pom.xml
bundles/org.openhab.binding.jellyfin/src/main/java/org/openhab/binding/jellyfin/internal/handler/JellyfinServerHandler.java

Fix error when multiple sessions for same device are returned by the server. 
Also update the sdk dependencies, I should have done it when I updated the library before the initial merge.

[jellyfin] fix multiple sessions for device and update deps

---

bundles/org.openhab.binding.netatmo/README.md

[Netatmo] Enhancement of documentation

---

itests/org.openhab.binding.avmfritz.tests/itest.bndrun
itests/org.openhab.binding.hue.tests/itest.bndrun
itests/org.openhab.binding.wemo.tests/itest.bndrun

Resolve itests after jUPnP upgrade

---

bundles/org.openhab.binding.elroconnects/src/main/resources/OH-INF/i18n/elroconnects.properties
bundles/org.openhab.binding.elroconnects/src/main/resources/OH-INF/thing/thing-types.xml

[elroconnects] Fix thing type description

---

bundles/org.openhab.binding.irobot/src/test/java/org/openhab/binding/irobot/internal/handler/RoombaHandlerTest.java
bundles/org.openhab.binding.paradoxalarm/src/test/java/main/Main.java
itests/org.openhab.binding.avmfritz.tests/itest.bndrun
itests/org.openhab.binding.feed.tests/itest.bndrun
itests/org.openhab.binding.hue.tests/itest.bndrun
itests/org.openhab.binding.max.tests/itest.bndrun
itests/org.openhab.binding.mielecloud.tests/itest.bndrun
itests/org.openhab.binding.modbus.tests/itest.bndrun
itests/org.openhab.binding.mqtt.homeassistant.tests/itest.bndrun
itests/org.openhab.binding.mqtt.homie.tests/itest.bndrun
itests/org.openhab.binding.nest.tests/itest.bndrun
itests/org.openhab.binding.ntp.tests/itest.bndrun
itests/org.openhab.binding.systeminfo.tests/itest.bndrun
itests/org.openhab.binding.tradfri.tests/itest.bndrun
itests/org.openhab.binding.wemo.tests/itest.bndrun
itests/org.openhab.persistence.mapdb.tests/itest.bndrun

Depends on https://github.com/openhab/openhab-core/pull/2982
Supersedes #12813 
@wborn I created a new PR which seems to solve all issues on my local build when the linked core changes are applied (I can't check dynamodb due to the missing native lib issue).

Fix issues with tests after core-changes

---

bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/handler/InsteonDeviceHandler.java

This solves an issue I noticed in my log file there were instances where devices would go back online when the network was offline. This solves that issue.

[insteon] set device to offline if network is not online after initialization

---

bundles/org.openhab.binding.herzborg/src/main/resources/OH-INF/i18n/herzborg.properties

[herzborg] Default translations

---

bundles/org.openhab.io.imperihome/src/main/resources/OH-INF/i18n/imperihome.properties

[imperihome] Default translations

---

bundles/org.openhab.binding.mybmw/src/main/java/org/openhab/binding/mybmw/internal/handler/MyBMWProxy.java
bundles/org.openhab.binding.mybmw/src/main/java/org/openhab/binding/mybmw/internal/utils/BimmerConstants.java
bundles/org.openhab.binding.mybmw/src/test/java/org/openhab/binding/mybmw/internal/handler/AuthTest.java

[mybmw] bugfix x-user-agent

---

itests/org.openhab.binding.astro.tests/itest.bndrun
itests/org.openhab.binding.avmfritz.tests/itest.bndrun
itests/org.openhab.binding.feed.tests/itest.bndrun
itests/org.openhab.binding.hue.tests/itest.bndrun
itests/org.openhab.binding.max.tests/itest.bndrun
itests/org.openhab.binding.mielecloud.tests/itest.bndrun
itests/org.openhab.binding.modbus.tests/itest.bndrun
itests/org.openhab.binding.mqtt.homeassistant.tests/itest.bndrun
itests/org.openhab.binding.mqtt.homie.tests/itest.bndrun
itests/org.openhab.binding.nest.tests/itest.bndrun
itests/org.openhab.binding.ntp.tests/itest.bndrun
itests/org.openhab.binding.systeminfo.tests/itest.bndrun
itests/org.openhab.binding.tradfri.tests/itest.bndrun
itests/org.openhab.binding.wemo.tests/itest.bndrun
itests/org.openhab.persistence.mapdb.tests/itest.bndrun
pom.xml

https://github.com/bndtools/bnd/wiki/Changes-in-6.3.0
Related to openhab/openhab-core#2991

Update bnd to 6.3.0

---

bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/NikoHomeControlBindingConstants.java
bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/NikoHomeControlHandlerFactory.java
bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/discovery/NikoHomeControlBridgeDiscoveryService.java
bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/discovery/NikoHomeControlDiscoveryService.java
bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/handler/NikoHomeControlActionHandler.java
bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/handler/NikoHomeControlBridgeHandler.java
bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/handler/NikoHomeControlBridgeHandler1.java
bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/handler/NikoHomeControlBridgeHandler2.java
bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/handler/NikoHomeControlEnergyMeterHandler.java
bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/handler/NikoHomeControlThermostatHandler.java
bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/NhcAction.java
bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/NhcEnergyMeter.java
bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/NhcThermostat.java
bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/NikoHomeControlDiscover.java
bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc1/NikoHomeControlCommunication1.java
bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc2/NhcAction2.java
bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc2/NhcDevice2.java
bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc2/NhcEnergyMeter2.java
bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc2/NhcThermostat2.java
bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc2/NikoHomeControlCommunication2.java

Improvements to discovery (split out from PR #11963 ):
- Use ThingHandlerService for device discovery
- Discovery multiple bridges in local network
- Add representation property
- Update names when name changes in NHC system, so discovery has latest name

[nikohomecontrol] Discovery improvements

---

bundles/org.openhab.binding.vigicrues/src/main/resources/OH-INF/i18n/vigicrues.properties

[vigicrues] Reorder translations entries

---

bundles/org.openhab.binding.weatherunderground/src/main/resources/OH-INF/i18n/weatherunderground.properties

[weatherunderground] Reorder translations entries

---

bundles/org.openhab.binding.xmltv/src/main/resources/OH-INF/i18n/xmltv.properties
bundles/org.openhab.binding.xmltv/src/main/resources/OH-INF/thing/thing-types.xml

[xmltv] Add few missing translations and reorder the entries

---

bundles/org.openhab.persistence.dynamodb/pom.xml

Add AARCH64 native lib to dynamodb

---

bundles/org.openhab.binding.ntp/src/main/resources/OH-INF/i18n/ntp.properties
bundles/org.openhab.binding.ntp/src/main/resources/OH-INF/thing/thing-types.xml

[ntp] Align XML description and default translations

---

bundles/org.openhab.binding.sagercaster/src/main/resources/OH-INF/i18n/sagercaster.properties

[sagercaster] Reorder translations entries

---

bundles/org.openhab.binding.renault/src/main/resources/OH-INF/i18n/renault.properties

[renault] Reorder translations entries

---

bundles/org.openhab.binding.lametrictime/src/main/resources/OH-INF/i18n/lametrictime.properties

[lametrictime] Add missing default translations

---

bundles/org.openhab.binding.upnpcontrol/src/main/java/org/openhab/binding/upnpcontrol/internal/handler/UpnpHandler.java

Set thing status to UNKNOWN before long running init jobs

[upnpcontrol] Set thingStatus UNKNOWN in intialize

---

bundles/org.openhab.binding.luxom/src/main/resources/OH-INF/i18n/luxom.properties
bundles/org.openhab.binding.luxom/src/main/resources/OH-INF/thing/thing-types.xml

[luxom] Add missing default translations

---

bundles/org.openhab.binding.sonyprojector/src/main/resources/OH-INF/i18n/sonyprojector.properties
bundles/org.openhab.binding.sonyprojector/src/main/resources/OH-INF/thing/ethernet.xml
bundles/org.openhab.binding.sonyprojector/src/main/resources/OH-INF/thing/serial.xml
bundles/org.openhab.binding.sonyprojector/src/main/resources/OH-INF/thing/serialoverip.xml

[sonyprojector] Align XML description and default translations

---

bundles/org.openhab.binding.elroconnects/src/main/java/org/openhab/binding/elroconnects/internal/util/ElroConnectsUtil.java

[elroconnects] Fix array out of bound exception

---

bundles/org.openhab.binding.sncf/src/main/resources/OH-INF/config/config.xml
bundles/org.openhab.binding.sncf/src/main/resources/OH-INF/i18n/sncf.properties
bundles/org.openhab.binding.sncf/src/main/resources/OH-INF/thing/bridge.xml
bundles/org.openhab.binding.sncf/src/main/resources/OH-INF/thing/station.xml

[sncf] Align XML description and default translations

---

bundles/org.openhab.binding.groupepsa/README.md

- Fix syntax of documentation and minor spelling improvements

[groupepsa] Fix syntax of documentation and minor spelling improvements

---

bundles/org.openhab.binding.automower/src/main/resources/OH-INF/i18n/automower.properties

[automover] Update default translations

---

bundles/org.openhab.binding.amazondashbutton/src/main/resources/OH-INF/binding/binding.xml
bundles/org.openhab.binding.amazondashbutton/src/main/resources/OH-INF/i18n/amazondashbutton.properties

[amazondashbutton] Update default translations

---

bundles/org.openhab.binding.netatmo/README.md
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/action/RoomActions.java
bundles/org.openhab.binding.netatmo/src/main/resources/OH-INF/i18n/netatmo.properties

[netatmo] Rework room actions

---

bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/ApiBridgeHandler.java

[netatmo] Make the grant servlet always available

---

bundles/org.openhab.binding.senechome/src/main/java/org/openhab/binding/senechome/internal/SenecSystemStatus.java

- [senechome][SenecSystemStatus] adding missins state battery diagnosis

[Senechome] add state battery diagnosis

---

bundles/org.openhab.binding.hdpowerview/src/main/resources/OH-INF/i18n/hdpowerview.properties

[hdpowerview] Update default translations

---

bundles/org.openhab.automation.jsscripting/README.md
bundles/org.openhab.automation.jsscripting/pom.xml

@jlaur 
This is my PR to bump the openhab-js version.
Unfortunately I was not able to push to the original PR of digitaldan.
Fixes #12943 
Closes #12729 

[jsscripting] Upgrade openhab-js to version 2.0.0

---

bundles/org.openhab.binding.globalcache/src/main/java/org/openhab/binding/globalcache/internal/handler/GlobalCacheHandler.java

If network issues occur, it's possible for `readLine` to return null, which causes a NPE and kills the command processor job. This PR prevents that from occurring.
```
2022-05-19 17:57:27.650 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception:
at org.openhab.binding.globalcache.internal.handler.GlobalCacheHandler$CommandProcessor.readReplyFromDevice(GlobalCacheHandler.java:564) ~[?:?]
at org.openhab.binding.globalcache.internal.handler.GlobalCacheHandler$CommandProcessor.run(GlobalCacheHandler.java:502) ~[?:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
at …
```

[globalcache] Fix NPE when reading reply from device

---

bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/SerialClient.java

Fixes a regression introduced by upgrading Calimero library to 2.5.

[knx] FT12: List available serial ports if port cannot be opened

---

bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/channelhelper/PresenceChannelHelper.java

Resolves #12910, corrects a bug introduced in #12851

[netatmo] Presence camera channels missing

---

bundles/org.openhab.binding.livisismarthome/src/main/java/org/openhab/binding/livisismarthome/internal/handler/LivisiDeviceHandler.java
bundles/org.openhab.binding.livisismarthome/src/test/java/org/openhab/binding/livisismarthome/internal/handler/LivisiDeviceHandlerTest.java

Resolved #12968, see #12968 for more information.

[livisismarthome] Button trigger channels are triggered on restart #12968

---

bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/KNXCoreTypeMapper.java

Signed-Of-By: Karel Goderis <karel.goderis@me.com>

[knx] Fix #12926

---

bundles/org.openhab.binding.groupepsa/src/main/resources/OH-INF/i18n/groupepsa.properties
bundles/org.openhab.binding.groupepsa/src/main/resources/OH-INF/thing/thing-types.xml

- Fixed Channel definition for battery voltage

[groupepsa] Fixed Channel definition for battery voltage

---

bundles/org.openhab.binding.dmx/README.md

[dmx] Update README.md

---

bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxServerHandler.java

[squeezebox] Fix NumberFormatException when parsing status message

---

bundles/org.openhab.binding.netatmo/README.md

[netatmo] Document extensible channels

---

bundles/org.openhab.binding.knx/src/main/resources/OH-INF/thing/serial.xml

Starting with openHAB 3.3, the framework enforces using serial
ports which are detected by the system by default. This feature
is now disabled for the KNX addon to allow using symlinks to
ports as well.
Refers-to: openhab/openhab-core#3014

[knx] Allow all port names for serial interfaces

---

bundles/org.openhab.binding.netatmo/README.md

[netatmo] Additional examples for home and camera

---

bundles/org.openhab.persistence.dynamodb/README.md

Reverts openhab/openhab-addons#13025

Revert "Trying to fix the documentation build"

---

bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/data/NetatmoConstants.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/providers/NetatmoChannelTypeProvider.java
bundles/org.openhab.binding.netatmo/src/main/resources/OH-INF/i18n/netatmo.properties

[netatmo] Localized label/pattern for dynamic channel types

---

bundles/org.openhab.binding.remoteopenhab/src/main/java/org/openhab/binding/remoteopenhab/internal/rest/RemoteopenhabRestClient.java

Related to openhab/openhab-core#2983

[remoteopenhab] Avoid unexpected log for ALIVE SSE message

---

bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/Ffmpeg.java

Passwords with special characters were not encoded and so the full URL failed. Adding password now also URL encoded.

[ipcamera] Added URL encoding fix for passwords that contains special characters.

---

bundles/org.openhab.binding.boschindego/README.md
bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/BoschIndegoBindingConstants.java
bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/BoschIndegoHandlerFactory.java
bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/IndegoController.java
bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/config/BoschIndegoConfiguration.java
bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/dto/response/PredictiveLastCuttingResponse.java
bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/dto/response/PredictiveNextCuttingResponse.java
bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/handler/BoschIndegoHandler.java
bundles/org.openhab.binding.boschindego/src/main/resources/OH-INF/i18n/boschindego.properties
bundles/org.openhab.binding.boschindego/src/main/resources/OH-INF/thing/thing-types.xml

Fixes #12986
Additionally:
- Add missing description for channel type **mowed**.

[boschindego] Add channels for last/next cutting time

---

README.md

Update i18n command version number

---

bundles/org.openhab.binding.boschindego/README.md
bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/DeviceStatus.java
bundles/org.openhab.binding.boschindego/src/main/resources/OH-INF/i18n/boschindego.properties
bundles/org.openhab.binding.boschindego/src/main/resources/OH-INF/thing/thing-types.xml

Fixes #13033
Mentioned [here](https://github.com/openhab/openhab-addons/pull/13034#issuecomment-1172880287) and verified.

[boschindego] Add support for SpotMow status code

---

bundles/org.openhab.binding.iaqualink/src/main/java/org/openhab/binding/iaqualink/internal/api/IAqualinkClient.java

Currently the binding throws a gson parsing error early in the poll process rendering it completely broken.

[iaqualink] Fix to work with recent API changes to the iAqualink cloud service

---

bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/IndegoController.java
bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/handler/BoschIndegoHandler.java

[boschindego] Optimize coexistence with mobile app/other clients

---

bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/IndegoController.java
bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/handler/BoschIndegoHandler.java

Small fix for #13040 as specialized text for unreachable device was missing, so it would should "Gateway timeout" where it should show "Device is unreachable".

[boschindego] Add missing specialized text for unreachable device

---

bundles/org.openhab.binding.goecharger/README.md
bundles/org.openhab.binding.goecharger/src/main/java/org/openhab/binding/goecharger/internal/api/GoEStatusResponseBaseDTO.java
bundles/org.openhab.binding.goecharger/src/main/java/org/openhab/binding/goecharger/internal/api/GoEStatusResponseDTO.java
bundles/org.openhab.binding.goecharger/src/main/java/org/openhab/binding/goecharger/internal/api/GoEStatusResponseV2DTO.java
bundles/org.openhab.binding.goecharger/src/main/java/org/openhab/binding/goecharger/internal/handler/GoEChargerBaseHandler.java
bundles/org.openhab.binding.goecharger/src/main/java/org/openhab/binding/goecharger/internal/handler/GoEChargerHandler.java
bundles/org.openhab.binding.goecharger/src/main/java/org/openhab/binding/goecharger/internal/handler/GoEChargerV2Handler.java

energy (nrg) need to be double for V2
(tested with version 053.4 (Beta)
Signed-off-by: Reinhard Plaim <reinhardplaim@gmail.com>

[goecharger] fix data type for energy (nrg)

---

bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/internal/handler/TadoHomeHandler.java

See: https://github.com/openhab/static-code-analysis/issues/438#issuecomment-1179543954

[tado] Fix the last remaining SAT issue

---

bundles/org.openhab.io.hueemulation/src/main/resources/OH-INF/i18n/hueemulation.properties

These were generated using https://github.com/openhab/openhab-core/pull/2966.

[hueemulation] Add default translations for module types

---

bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/database/ShadeCapabilitiesDatabase.java

Fixes #13109 
Added support for shade types 31 and 33

[hdpowerview] Add support for shade types 31 and 33

---

CODEOWNERS
bom/openhab-addons/pom.xml
bundles/org.openhab.binding.mcd/NOTICE
bundles/org.openhab.binding.mcd/README.md
bundles/org.openhab.binding.mcd/pom.xml
bundles/org.openhab.binding.mcd/src/main/feature/feature.xml
bundles/org.openhab.binding.mcd/src/main/java/org/openhab/binding/mcd/internal/McdBindingConstants.java
bundles/org.openhab.binding.mcd/src/main/java/org/openhab/binding/mcd/internal/McdHandlerFactory.java
bundles/org.openhab.binding.mcd/src/main/java/org/openhab/binding/mcd/internal/handler/McdBridgeConfiguration.java
bundles/org.openhab.binding.mcd/src/main/java/org/openhab/binding/mcd/internal/handler/McdBridgeHandler.java
bundles/org.openhab.binding.mcd/src/main/java/org/openhab/binding/mcd/internal/handler/SensorThingConfiguration.java
bundles/org.openhab.binding.mcd/src/main/java/org/openhab/binding/mcd/internal/handler/SensorThingHandler.java
bundles/org.openhab.binding.mcd/src/main/java/org/openhab/binding/mcd/internal/util/Callback.java
bundles/org.openhab.binding.mcd/src/main/java/org/openhab/binding/mcd/internal/util/Listener.java
bundles/org.openhab.binding.mcd/src/main/java/org/openhab/binding/mcd/internal/util/SensorEventDef.java
bundles/org.openhab.binding.mcd/src/main/resources/OH-INF/binding/binding.xml
bundles/org.openhab.binding.mcd/src/main/resources/OH-INF/i18n/mcd.properties
bundles/org.openhab.binding.mcd/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.mcd/src/test/java/org/openhab/binding/mcd/internal/handler/SensorThingHandlerTest.java
bundles/org.openhab.binding.mcd/src/test/java/org/openhab/binding/mcd/internal/util/SensorEventDefTest.java
bundles/pom.xml

Signed-off-by: Simon Dengler 
This contribution adds the MCD Binding to the project.
No changes to previously existing bindings have been made.
Fixes #12201

[mcd] Initial contribution

---

CODEOWNERS
bom/openhab-addons/pom.xml
bundles/org.openhab.voice.mimictts/NOTICE
bundles/org.openhab.voice.mimictts/README.md
bundles/org.openhab.voice.mimictts/pom.xml
bundles/org.openhab.voice.mimictts/src/main/feature/feature.xml
bundles/org.openhab.voice.mimictts/src/main/java/org/openhab/voice/mimic/internal/MimicConfiguration.java
bundles/org.openhab.voice.mimictts/src/main/java/org/openhab/voice/mimic/internal/MimicTTSService.java
bundles/org.openhab.voice.mimictts/src/main/java/org/openhab/voice/mimic/internal/MimicVoice.java
bundles/org.openhab.voice.mimictts/src/main/java/org/openhab/voice/mimic/internal/dto/VoiceDto.java
bundles/org.openhab.voice.mimictts/src/main/resources/OH-INF/config/config.xml
bundles/org.openhab.voice.mimictts/src/main/resources/OH-INF/i18n/mimic_en.properties
bundles/org.openhab.voice.mimictts/src/main/resources/OH-INF/i18n/mimictts.properties
bundles/org.openhab.voice.mimictts/src/main/resources/OH-INF/i18n/mimictts_fr.properties
bundles/pom.xml

Add a voice service for Mimic (version 3+) TTS from Mycroft AI. 
Mimic (version 3) is the brand new Text-To-Speech software designed for the Mycroft vocal assistant.
It is a great improvement from the older versions.
Mimic can be used as a standalone server, and as such it exposes an API that this TTS service makes use of.
This bundle is NOT a standalone, it requires Mimic to run somewhere on your computer/network
[Community discussion on the marketplace](https://community.openhab.org/t/mimic-text-to-speech/137040)

[mimictts] Initial contribution

---

bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/handler/RotelHandler.java

[rotel] Fix handling of balance command feedback

---

bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/handler/OpenUVBridgeHandler.java
bundles/org.openhab.binding.openuv/src/main/resources/OH-INF/i18n/openuv.properties

[openuv] Adding scheduled reconnection on timeout

---

bundles/org.openhab.binding.onkyo/README.md
bundles/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/OnkyoModel.java
bundles/org.openhab.binding.onkyo/src/main/resources/OH-INF/i18n/onkyo.properties
bundles/org.openhab.binding.onkyo/src/main/resources/OH-INF/i18n/onkyo_de.properties
bundles/org.openhab.binding.onkyo/src/main/resources/OH-INF/thing/ht-rc440.xml

Definitions for HT-RC440 added
Signed-off-by: Markus Michels <markus7017@gmail.com>

[onkyo] HT-RC440 added

---

bundles/org.openhab.binding.venstarthermostat/src/main/java/org/openhab/binding/venstarthermostat/internal/handler/VenstarThermostatHandler.java

My ColorTouch thermostat has a newer firmware, which, from the OpenHab logs & experimenting with the REST API directly, I've observed to reject any POSTs to the settings endpoint that include the `schedule` parameter when the thermostat is currently in AWAY mode, regardless of the value passed for `schedule`.  This had the effect of preventing the OpenHab binding from un-setting away mode.
This is likely to be the same problem encountered by other users on this forum thread: https://community.openhab.org/t/venstar-binding-not-working/123780/4
This PR splits out the method used to perform thermostat settings updates, so that _only_ the value being changed is sent to the thermostat.  By avoiding the `schedule` parameter from being included at all when changing `away`, this ensures that the …

[venstarthermostat] Split away and schedule settings calls (resolves bug exiting away mode)

---

CODEOWNERS

Add myself as code owner after almost complete rewrite (#12905).

Add myself as code owner for Bosch Indego binding

---

bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/InsteonBinding.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/handler/InsteonNetworkHandler.java

Prior to this change the Insteon network was set to ONLINE before it should have been.

[insteon] set network to ONLINE after driver is initialized

---

bundles/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/handler/MyQAccountHandler.java

[myq] Catch json parsing errors when getting login token.

---

bundles/org.openhab.binding.rotel/README.md

[rotel] Updated doc for c8 and c8+ models

---

bundles/org.openhab.binding.epsonprojector/README.md
bundles/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/internal/EpsonProjectorBindingConstants.java
bundles/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/internal/discovery/EpsonProjectorDiscoveryService.java
bundles/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/internal/discovery/MulticastListener.java
bundles/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/internal/handler/EpsonProjectorHandler.java
bundles/org.openhab.binding.epsonprojector/src/main/resources/OH-INF/i18n/epsonprojector.properties

This PR contains several small improvements and formatting changes for epsonprojector similar to those that were done for benqprojector in PR #12866.

[epsonprojector] several small improvements and formatting changes

---

bundles/org.openhab.binding.atlona/README.md
bundles/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/AtlonaHandlerCallback.java
bundles/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/AtlonaHandlerFactory.java
bundles/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/StatefulHandlerCallback.java
bundles/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/discovery/AtlonaDiscovery.java
bundles/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/handler/AtlonaCapabilities.java
bundles/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/net/SocketChannelSession.java
bundles/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/net/SocketSession.java
bundles/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/net/SocketSessionListener.java
bundles/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/pro3/AtlonaPro3Capabilities.java
bundles/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/pro3/AtlonaPro3Config.java
bundles/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/pro3/AtlonaPro3Constants.java
bundles/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/pro3/AtlonaPro3Handler.java
bundles/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/pro3/AtlonaPro3PortocolHandler.java
bundles/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/pro3/AtlonaPro3Utilities.java

This PR fixes an NPE that occurs when the Thing is disabled and openhab calls dispose() on shutdown. Also fix a large number of warnings.

[atlona] Fix NPE on shutdown when Thing disabled

---

bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/DaikinWebTargets.java

[daikin] Fix switching specialmode to NORMAL

---

bundles/org.openhab.binding.nibeheatpump/README.md
bundles/org.openhab.binding.nibeheatpump/contrib/NibeGW/Arduino/NibeGW/Config.h
bundles/org.openhab.binding.nibeheatpump/contrib/NibeGW/Arduino/NibeGW/Debug.h
bundles/org.openhab.binding.nibeheatpump/contrib/NibeGW/Arduino/NibeGW/NibeGW.ino
bundles/org.openhab.binding.nibeheatpump/contrib/NibeGW/Arduino/NibeGW/NibeGw.cpp
bundles/org.openhab.binding.nibeheatpump/contrib/NibeGW/Arduino/NibeGW/NibeGw.h

Also added:
- telnet debug support (UDP debug removed)
- new configuration model
- OTA update support for PRODINo ESP32 Ethernet v1 board

[nibeheatpump] Added PRODINo ESP32 Ethernet v1 board support

---

bundles/org.openhab.persistence.influxdb/README.md

added a paragraph about configuring InfluxDB Settings in Web-UI

Added how to configure InfluxDB Persistance via Web-UI

---

bundles/org.openhab.binding.mystrom/README.md
bundles/org.openhab.binding.mystrom/src/main/java/org/openhab/binding/mystrom/internal/AbstractMyStromHandler.java
bundles/org.openhab.binding.mystrom/src/main/java/org/openhab/binding/mystrom/internal/MyStromBindingConstants.java
bundles/org.openhab.binding.mystrom/src/main/java/org/openhab/binding/mystrom/internal/MyStromConfiguration.java
bundles/org.openhab.binding.mystrom/src/main/java/org/openhab/binding/mystrom/internal/MyStromHandlerFactory.java
bundles/org.openhab.binding.mystrom/src/main/java/org/openhab/binding/mystrom/internal/MyStromPIRHandler.java
bundles/org.openhab.binding.mystrom/src/main/resources/OH-INF/i18n/mystrom.properties
bundles/org.openhab.binding.mystrom/src/main/resources/OH-INF/thing/thing-types.xml

- [mystrom] Added API Token to configuration
- [mystrom] Added Motionsensor as new thing
This patch includes a new API field for all myStrom devices like the Plug, Motionsensor etc, to provide a secure way to communicate with the devices.
In addition, a new device has been added to the binding, the myStrom Motionsensor.

[myStrom] Added Motionsensor and API Token

---

bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/handler/SonosMediaInformation.java
bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/handler/ZonePlayerHandler.java
bundles/org.openhab.binding.sonos/src/test/java/org/openhab/binding/sonos/internal/SonosMediaInformationTest.java
bundles/org.openhab.binding.sonos/src/test/java/org/openhab/binding/sonos/internal/SonosXMLParserTest.java
bundles/org.openhab.binding.sonos/src/test/resources/OPML.xml

[sonos] Unit tests added for OPML request parsing

---

bundles/org.openhab.binding.intesis/README.md
bundles/org.openhab.binding.intesis/src/main/java/org/openhab/binding/intesis/internal/IntesisHandlerFactory.java
bundles/org.openhab.binding.intesis/src/main/java/org/openhab/binding/intesis/internal/handler/IntesisHomeHandler.java
bundles/org.openhab.binding.intesis/src/main/resources/OH-INF/thing/thing-types.xml

[intesis] Add RSSI channel to intesisHome and fixed some NPEs

---

bundles/org.openhab.binding.mielecloud/src/main/java/org/openhab/binding/mielecloud/internal/config/exception/BridgeCreationFailedException.java
bundles/org.openhab.binding.mielecloud/src/main/java/org/openhab/binding/mielecloud/internal/config/servlet/CreateBridgeServlet.java
itests/org.openhab.binding.mielecloud.tests/src/main/java/org/openhab/binding/mielecloud/internal/config/servlet/CreateBridgeServletTest.java

Adapt mielecloud binding to `Inbox` API changes from https://github.com/openhab/openhab-core/pull/2981 and fix potential problems from #13150.

[mielecloud] Adapt to inbox api changes

---

bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/LinkyHandlerFactory.java
bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/api/EnedisHttpApi.java

[linky] Adding TrustAllTrustManager to solve certificate error

---

bundles/org.openhab.automation.jrubyscripting/README.md

using the core ScriptTransformationService. See https://github.com/openhab/openhab-addons/pull/13255 for prior discussion on this.

[jrubyscripting] document how to use Ruby in a transformation

---

bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/discovery/LutronMdnsBridgeDiscoveryService.java

Adds mDNS discovery support for the new RadioRA 3 Processor.

[lutron] Add mDNS discovery for RadioRA 3 processor

---

bundles/org.openhab.binding.mystrom/README.md

Hi there,
I recently made contribution to the myStrom binding, I just noticed a mistake in the readme file.
Sorry about that.
Signed-off-by: Stefan Navratil <stefan@navratil.ch>

[myStrom] Corrected readMe, mystrompir is not a bulb.

---

bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/JRubyScriptEngineConfiguration.java

fixes https://github.com/boc-tothefuture/openhab-jruby/issues/634;
regression from https://github.com/openhab/openhab-addons/pull/13151

[jrubyscripting] avoid polluting environment when auto-installing gems

---

bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/dto/ColorControlModel.java
bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/dto/HeatingModel.java
bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/AVMFritzBaseThingHandler.java
bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/hardware/FritzAhaWebInterface.java
bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/hardware/callbacks/FritzAhaSetColorCallback.java
bundles/org.openhab.binding.avmfritz/src/test/java/org/openhab/binding/avmfritz/internal/dto/AVMFritzDeviceListModelTest.java
bundles/org.openhab.binding.avmfritz/src/test/java/org/openhab/binding/avmfritz/internal/dto/ColorControlModelTest.java
bundles/org.openhab.binding.avmfritz/src/test/java/org/openhab/binding/avmfritz/internal/dto/HeatingModelTest.java

- Use "setunmappedcolor" command for color control of bulbs
- Added INCREASE/DECREASE commands for brightness/color Channels
Closes #12427

[avmfritz] Allow to set every userdefined color

---

bundles/org.openhab.binding.konnected/README.md

I attempted creating a things file from the example, and it did not work. I fixed the issues that I found, and I renamed some elements to make the example less ambiguous.

[Konnected] Fixed example thing. Made names less ambiguous

---

bundles/org.openhab.binding.jablotron/README.md
bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/handler/JablotronBridgeHandler.java
bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/handler/JablotronJa100FHandler.java
bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/model/ja100f/JablotronGetThermoDevicesData.java
bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/model/ja100f/JablotronGetThermoDevicesResponse.java
bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/model/ja100f/JablotronThermoDevice.java

This PR adds thermometers support for the JA100F alarms.

[jablotron] Added thermometers support for JA100F alarms

---

bundles/org.openhab.binding.linky/README.md

[linky] Docker specificities

---

bundles/org.openhab.binding.velux/src/main/resources/OH-INF/i18n/velux.properties

Change to channel label as requested [here](https://github.com/openhab/openhab-addons/pull/13271#discussion_r967803388)

[velux] Correction to channel label

---

bundles/org.openhab.binding.groupepsa/README.md
bundles/org.openhab.binding.groupepsa/src/main/java/org/openhab/binding/groupepsa/internal/GroupePSAHandlerFactory.java
bundles/org.openhab.binding.groupepsa/src/main/java/org/openhab/binding/groupepsa/internal/things/GroupePSAHandler.java
bundles/org.openhab.binding.groupepsa/src/test/java/org/openhab/binding/groupepsa/internal/things/GroupePSAHandlerTest.java

- Consider TimeZoneProvider to build states for time-stamp channels

[groupepsa] Consider TimeZoneProvider to build states for time-stamp channels

---

bundles/org.openhab.automation.jsscripting/README.md
bundles/org.openhab.automation.jsscripting/pom.xml

@jlaur
This updates the openhab-js library in the JS Scripting Add-On to version 2.0.3.
Have a look at the openhab-js CHANGELOG to see what's changed: https://github.com/openhab/openhab-js/blob/main/CHANGELOG.md.

[jsscripting] Update openhab-js to 2.0.3

---

bundles/org.openhab.voice.voskstt/pom.xml
bundles/org.openhab.voice.voskstt/src/main/java/org/openhab/voice/voskstt/internal/VoskSTTService.java

Update Vosk sdk version.
Also handle UnsatisfiedLinkError exceptions, I was facing those on recent versions of the docker based Debian container as libatomic lib is not present any more and the exception was not handled properly.

[vosk] Upgrade sdk and handle UnsatisfiedLinkError exceptions

---

bundles/org.openhab.binding.amazondashbutton/src/main/feature/feature.xml

See https://github.com/openhab/openhab-core/pull/3049

Adapt to core-changes (added JNA to tp)

---

bundles/org.openhab.binding.openwebnet/README.md

Improved README for AUX and ENERGY things configurations, including examples for Alarm configuration via AUX

[openwebnet] improved README for AUX and ENERGY

---

bundles/org.openhab.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/AndroidDebugBridgeDevice.java
bundles/org.openhab.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/AndroidDebugBridgeHandler.java

Fix get current package and get MAC address adb commands.
Supersedes https://github.com/openhab/openhab-addons/pull/12850

[androiddebugbridge] Fix get current package and get MAC address.

---

CODEOWNERS
bom/openhab-addons/pom.xml
bundles/org.openhab.binding.ecowatt/NOTICE
bundles/org.openhab.binding.ecowatt/README.md
bundles/org.openhab.binding.ecowatt/pom.xml
bundles/org.openhab.binding.ecowatt/src/main/feature/feature.xml
bundles/org.openhab.binding.ecowatt/src/main/java/org/openhab/binding/ecowatt/internal/EcowattBindingConstants.java
bundles/org.openhab.binding.ecowatt/src/main/java/org/openhab/binding/ecowatt/internal/EcowattHandlerFactory.java
bundles/org.openhab.binding.ecowatt/src/main/java/org/openhab/binding/ecowatt/internal/configuration/EcowattConfiguration.java
bundles/org.openhab.binding.ecowatt/src/main/java/org/openhab/binding/ecowatt/internal/exception/EcowattApiLimitException.java
bundles/org.openhab.binding.ecowatt/src/main/java/org/openhab/binding/ecowatt/internal/handler/EcowattHandler.java
bundles/org.openhab.binding.ecowatt/src/main/java/org/openhab/binding/ecowatt/internal/restapi/EcowattApiResponse.java
bundles/org.openhab.binding.ecowatt/src/main/java/org/openhab/binding/ecowatt/internal/restapi/EcowattDaySignals.java
bundles/org.openhab.binding.ecowatt/src/main/java/org/openhab/binding/ecowatt/internal/restapi/EcowattHourSignal.java
bundles/org.openhab.binding.ecowatt/src/main/java/org/openhab/binding/ecowatt/internal/restapi/EcowattRestApi.java
bundles/org.openhab.binding.ecowatt/src/main/resources/OH-INF/binding/binding.xml
bundles/org.openhab.binding.ecowatt/src/main/resources/OH-INF/i18n/ecowatt.properties
bundles/org.openhab.binding.ecowatt/src/main/resources/OH-INF/thing/thing-types.xml
bundles/pom.xml

This binding uses the Ecowatt API to expose clear signals to adopt the right gestures and to ensure a good supply of electricity for all in France.
Close #13351

[ecowatt] Initial contribution

---

bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/discovery/HomeAssistantDiscovery.java

Similar to https://github.com/openhab/openhab-core/issues/2436, we want to have consistent ordering of data in JSONDB. This is fixing the jsondb order for mqtt.homeassistant discovery results, specifically, the "topics" property.
Example of such unwanted ordering of topics before this PR:
```diff
diff --git a/jsondb/org.openhab.core.config.discovery.DiscoveryResult.json b/jsondb/org.openhab.core.config.discovery.DiscoveryResult.json
index de0ee1f..098e178 100644
--- a/jsondb/org.openhab.core.config.discovery.DiscoveryResult.json
+++ b/jsondb/org.openhab.core.config.discovery.DiscoveryResult.json
@ -1383,8 +1383,8 @@
"sensor/RETRACTED-seq",
"sensor/RETRACTED-tx",
"sensor/RETRACTED-tempc",
-          "sensor/RETRACTED-accz",
"sensor/RETRACTED-pres",
+          "sensor/RETRACTED-accz", …
```

[mqtt.homeassistant] Stable jsondb discovery result

---

bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/discovery/HomeAssistantDiscovery.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/discovery/HomeAssistantDiscoveryTests.java

Simplifies labels for discovered things, more readable and compact
Real life examples of unreadable labels before this PR
- `"RuuviTag (Sensor, Sensor, Sensor, Sensor, Sensor, Sensor, Sensor, Sensor, Sensor, Sensor)"` for https://ruuvi.com/ discovered via MQTT via [OpenMQTTGateway](https://docs.openmqttgateway.com/)
- `""OpenMQTTGateway_2 (Switch, Sensor, Switch, Switch, Sensor, Switch, Switch, Switch, Sensor, Sensor, Switch, Sensor, Switch, Sensor, Sensor, Sensor)"` for internal diagnostic sensors and switches for ESP32 running [OpenMQTTGateway](https://docs.openmqttgateway.com/)

[mqtt.homeassistant] More readable label for discovered things

---

bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudClient.java
bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudService.java

Improved logging for openhabcloud addon:
- Sensor sensitive secrets from logging statements
- log error reason even without debug level
- more diagnostic logging, e.g. Socket.io ping/pong and HTTP calls
In addition,
- removed dead code (was included in the original contribution from @kaikreuzer ) https://github.com/openhab/openhab-addons/commit/f85d2bbaaec89848ee05d8c638e70d45bbca5858
- abort correctly on case of invalid URL for example (also longstanding bug?) https://github.com/openhab/openhab-addons/commit/885aacea5929093d0fd43b727c2430a643bff822
https://community.openhab.org/t/openhab-cloud-connection-stops-working-does-not-try-to-reconnect/133608/17
**Precompiled versions** for openHAB 3.2.0 and 3.3.0-SNAPSHOT: https://github.com/ssalonen/openhab2-addons/releases?q=openhabcloud&expand …

[openhabcloud] improved logging for troubleshooting purposes

---

bundles/org.openhab.automation.jrubyscripting/pom.xml

https://www.jruby.org/2022/09/13/jruby-9-3-8-0

[jrubyscripting] Update to JRuby 9.3.8.0

---

bundles/org.openhab.binding.kvv/README.md
bundles/org.openhab.binding.kvv/src/main/java/org/openhab/binding/kvv/internal/DepartureResult.java
bundles/org.openhab.binding.kvv/src/main/java/org/openhab/binding/kvv/internal/KVVBindingConstants.java
bundles/org.openhab.binding.kvv/src/main/java/org/openhab/binding/kvv/internal/KVVBridgeConfig.java
bundles/org.openhab.binding.kvv/src/main/java/org/openhab/binding/kvv/internal/KVVBridgeHandler.java
bundles/org.openhab.binding.kvv/src/main/java/org/openhab/binding/kvv/internal/KVVStopHandler.java
bundles/org.openhab.binding.kvv/src/main/resources/OH-INF/i18n/kvv.properties
bundles/org.openhab.binding.kvv/src/main/resources/OH-INF/thing/bridge.xml

The underlying API does no longer work so it is replaced. An API key is no longer necessary.
Users need to replace the `stopId` in there station thing configuration. See README.md for details.

[KVV] Replace underlying API

---

bundles/org.openhab.binding.ecowatt/README.md
bundles/org.openhab.binding.ecowatt/src/main/resources/OH-INF/i18n/ecowatt.properties
bundles/org.openhab.binding.ecowatt/src/main/resources/OH-INF/thing/thing-types.xml

[ecowatt] Shorter labels for channel options

---

CODEOWNERS

Adding myself as a second code owner for several bindings.

Added a second code owner

---

bundles/org.openhab.binding.touchwand/src/main/java/org/openhab/binding/touchwand/internal/TouchWandBridgeHandler.java
bundles/org.openhab.binding.touchwand/src/main/java/org/openhab/binding/touchwand/internal/TouchWandWebSockets.java

The optional port parameter applied to websocket connection as well allow the binding to connect also to a non default port

[touchwand] Add port configuration to websocket

---

bundles/org.openhab.binding.solarmax/src/main/resources/OH-INF/i18n/solarmax.properties

[solarmax] Add default translations

---

bundles/org.openhab.binding.nuki/README.md

command numbers where changed, see lines 80 and following -> adjusted the example and reorderd the commands

[nuki] updated example to match frontdoor_lockstates

---

bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/LcnModuleHandler.java
bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/common/VariableValue.java
bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/converter/Converter.java
bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/converter/ValueConverter.java
bundles/org.openhab.binding.lcn/src/test/java/org/openhab/binding/lcn/internal/subhandler/LcnModuleRvarSetpointSubHandlerTest.java
bundles/org.openhab.binding.lcn/src/test/java/org/openhab/binding/lcn/internal/subhandler/LcnModuleVariableSubHandlerTest.java

[lcn] Improve logging

---

bundles/org.openhab.binding.androiddebugbridge/README.md
bundles/org.openhab.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/discovery/AndroidTVMDNSDiscoveryParticipant.java
bundles/org.openhab.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/discovery/FireTVStickMDNSDiscoveryParticipant.java

Add mDNS discovery participant for android tv.

[androiddebugbridge] Add mDNS discovery for android tv

---

bundles/org.openhab.binding.bluetooth.ruuvitag/pom.xml

Fixed by bumping support library fi.tkgwf.ruuvi:ruuvitag-common
https://github.com/Scrin/ruuvitag-common-java/releases/tag/v1.0.2

[bluetooth.ruuvitag] Correctly parse NA temperature & acceleration

---

bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/EaseeBindingConstants.java
bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/connector/WebInterface.java

[easee] Fix binding not working after Easee cloud API has been unavailable

---

bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/SecurityApi.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/CommonInterface.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/CameraCapability.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/SecurityCapability.java

Lowers the number of request to this API.
Prevents the home to turn back itself to ONLINE when the ping has failed.
Resolves #13486 

[netatmo] Handling camera ping timeouts

---

bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/discovery/NetatmoDiscoveryService.java

[netatmo] Handle properly UNKNOWN module types in discovery

---

bundles/org.openhab.binding.netatmo/README.md
bundles/org.openhab.binding.netatmo/src/main/resources/OH-INF/i18n/netatmo.properties
bundles/org.openhab.binding.netatmo/src/main/resources/OH-INF/thing/channels.xml

[netatmo] Fix the description of the new channel request-count

---

bundles/org.openhab.binding.fineoffsetweatherstation/README.md

* fix typo
* link community thread
* add note for derived values

[fineoffsetweatherstation] Fix README.md

---

bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/SecurityApi.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/data/NetatmoConstants.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/SecurityCapability.java

Following the merge of #13489, @lolodomo identified a potential edge case that could lead to miss some events.
Discussed [here](https://github.com/openhab/openhab-addons/pull/13489#issuecomment-1271441821)

[netatmo] Ensure all events are retrieved since they are buffered

---

bundles/org.openhab.binding.nuvo/README.md
bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/NuvoBindingConstants.java
bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/handler/NuvoHandler.java
bundles/org.openhab.binding.nuvo/src/main/resources/OH-INF/i18n/nuvo.properties
bundles/org.openhab.binding.nuvo/src/main/resources/OH-INF/thing/channels.xml

This is a follow up to #12042. In the previous PR, the ability for album art to be loaded into the physical keypads was added. In this PR, an Image channel was added so that the album art can also be displayed in an openHAB UI widget.

[nuvo] Add Image channel for album art

---

bundles/org.openhab.voice.voskstt/src/main/java/org/openhab/voice/voskstt/internal/VoskSTTService.java

Fixes https://github.com/openhab/openhab-addons/issues/13423.
It was caused by me when updating the sdk. 
As a summary of what happened, support for arm and arm64 (meaning vosk binaries) is not included in the vosk maven package, so last time I grabbed them from the GitHub release page of the project. This time I forgot to updated those files, causing the problem. 
Also changes the vosk internal log level to suppress unwanted info messages.
Sorry for taking so long to realize what the problem was.

[voskstt] fix sdk update and disable internal info logs

---

bundles/org.openhab.binding.gce/src/main/java/org/openhab/binding/gce/internal/GCEHandlerFactory.java
bundles/org.openhab.binding.gce/src/main/java/org/openhab/binding/gce/internal/handler/Ipx800DeviceConnector.java
bundles/org.openhab.binding.gce/src/main/java/org/openhab/binding/gce/internal/handler/Ipx800v3Handler.java
bundles/org.openhab.binding.gce/src/main/java/org/openhab/binding/gce/internal/model/PortData.java

Avoiding dynamic creation of channels when channels already exists.
Plus some small code improvements.
Solves #13522 

[gce] Avoid conflicts with things file defined

---

bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/handler/ZonePlayerHandler.java

[sonos] New codec id 61 for Dolby Atmos

---

bundles/org.openhab.persistence.influxdb/README.md

At a link for further information what to do in a persist file.

[influxdb] Update README.md

---

CODEOWNERS
bom/openhab-addons/pom.xml
bundles/org.openhab.binding.tplinkrouter/NOTICE
bundles/org.openhab.binding.tplinkrouter/README.md
bundles/org.openhab.binding.tplinkrouter/pom.xml
bundles/org.openhab.binding.tplinkrouter/src/main/feature/feature.xml
bundles/org.openhab.binding.tplinkrouter/src/main/java/org/openhab/binding/tplinkrouter/internal/TpLinkRouterBindingConstants.java
bundles/org.openhab.binding.tplinkrouter/src/main/java/org/openhab/binding/tplinkrouter/internal/TpLinkRouterConfiguration.java
bundles/org.openhab.binding.tplinkrouter/src/main/java/org/openhab/binding/tplinkrouter/internal/TpLinkRouterHandler.java
bundles/org.openhab.binding.tplinkrouter/src/main/java/org/openhab/binding/tplinkrouter/internal/TpLinkRouterHandlerFactory.java
bundles/org.openhab.binding.tplinkrouter/src/main/java/org/openhab/binding/tplinkrouter/internal/TpLinkRouterTelenetListener.java
bundles/org.openhab.binding.tplinkrouter/src/main/java/org/openhab/binding/tplinkrouter/internal/TpLinkRouterTelnetConnector.java
bundles/org.openhab.binding.tplinkrouter/src/main/resources/OH-INF/binding/binding.xml
bundles/org.openhab.binding.tplinkrouter/src/main/resources/OH-INF/i18n/tplinkrouter.properties
bundles/org.openhab.binding.tplinkrouter/src/main/resources/OH-INF/thing/channel-group-types.xml
bundles/org.openhab.binding.tplinkrouter/src/main/resources/OH-INF/thing/thing-types.xml
bundles/pom.xml

This is the initial commit for the tplinkrouter binding.
I've made this binding to be able to activate/deactivate my WiFi network from openhab so currently only WiFi can be monitored and controlled.
The binding uses a telnet connection to communicate with the router. The code managing the telnet connection is mostly taken from the denonmarantz binding.

[tplinkrouter] Initial contribution

---

bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudService.java

We have recently added  gz and br encoding to the main UI.  Unfortunately the cloud binding does not pass this along as the default jetty client tries to decode this for you silently.  This removes jetty default encodings,  as streams should be untouched until they reach the web client.   See https://github.com/openhab/openhab-webui/pull/1521
Ping @ghys

[openhabcloud] Remove content encoding when proxing.

---

bundles/org.openhab.transform.map/README.md
bundles/org.openhab.transform.map/conf/transform/map/doorstatus_fallback.map
bundles/org.openhab.transform.map/src/main/java/org/openhab/transform/map/internal/MapTransformationService.java
bundles/org.openhab.transform.map/src/test/java/org/openhab/transform/map/internal/MapTransformationServiceTest.java

[MAP] Adds fallback to original value when input not found

---

bundles/org.openhab.binding.netatmo/README.md

[netatmo] more precision in doc where to find the refresh token

---

bundles/org.openhab.binding.jellyfin/pom.xml

Upgrade sdk; fixes json parse error on sessions endpoint when transcoding reason is present which breaks the refresh mechanism of the binding.

[jellyfin] upgrade sdk, fixes json parse error

---

bundles/org.openhab.binding.netatmo/README.md

[netatmo] Extend example with things for energy stuff

---

bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/NumberValue.java
bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/values/ValueTests.java

Just have to use the newer toInvertibleUnit method that allows the dimension to change.

[mqtt] support mired<->Kelvin unit conversion

---

bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/console/NetatmoCommandExtension.java

[netatmo] Console command completion

---

bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/console/SomfyTahomaCommandExtension.java

[somfytahoma] Console command completion

---

bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/console/HueCommandExtension.java

[hue] Console command completion

---

bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/console/LinkyCommandExtension.java

[linky] Console command completion

---

bundles/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/console/FreeboxCommandExtension.java

[freebox] Console command completion

---

bundles/org.openhab.automation.jrubyscripting/pom.xml

Some security and minor bug fixes. 
https://www.jruby.org/2022/10/24/jruby-9-3-9-0.html

[jrubyscripting] Update to JRuby 9.3.9.0

---

bundles/org.openhab.binding.mielecloud/src/main/java/org/openhab/binding/mielecloud/internal/config/MieleCloudConfigService.java

Adds the missing resource unregistration discovered by @jlaur in #13612.

[mielecloud] Fix missing web resource unregistration

---

bundles/org.openhab.binding.kaleidescape/README.md
bundles/org.openhab.binding.kaleidescape/src/main/resources/OH-INF/binding/binding.xml
bundles/org.openhab.binding.kaleidescape/src/main/resources/OH-INF/i18n/kaleidescape.properties

Update readme introduction and binding name/description. No functional changes.

[kaleidescape] update README

---

bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/data/NetatmoConstants.java

[netatmo] No restriction on max value for rain quantity

---

bundles/org.openhab.binding.vigicrues/src/main/java/org/openhab/binding/vigicrues/internal/api/ApiHandler.java

[vigicrues] Fix few code analysis findings

---

bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/dto/HevCycleState.java
bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/dto/Packet.java
bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/fields/HSBK.java
bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/fields/MACAddress.java
bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/util/LifxThrottlingUtil.java

[lifx] Fix all code analysis findings

---

bundles/org.openhab.binding.sagercaster/README.md
bundles/org.openhab.binding.sagercaster/src/main/java/org/openhab/binding/sagercaster/internal/SagerCasterBindingConstants.java
bundles/org.openhab.binding.sagercaster/src/main/java/org/openhab/binding/sagercaster/internal/caster/SagerWeatherCaster.java

[sagercaster] Fix all code analysis findings

---

bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/server/Utils.java
bundles/org.openhab.binding.mercedesme/src/test/java/org/openhab/binding/mercedesme/ConfigurationTest.java

* Make sure IPv4 is used with default callback URL
* Use a more reasonable timeout
Fixes #13531

[mercedesme] Fix unstable ConfigurationTest

---

bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/servlet/HomeConnectServlet.java
bundles/org.openhab.binding.homeconnect/src/main/resources/assets/js/homeconnect.js
bundles/org.openhab.binding.homeconnect/src/main/resources/templates/bridges.html

The simulated Home Connect environment cannot currently be used (https://developer.home-connect.com/simulator). The test environment always expects a valid "redirect URI", although according to the documentation it is optional.
I reported the bug a few months ago but unfortunately didn't get a reply. That's why I created this pull request.

[homeconnect] Fix login for simulator environment

---

bundles/org.openhab.binding.paradoxalarm/src/main/java/org/openhab/binding/paradoxalarm/internal/communication/CommunicationState.java
bundles/org.openhab.binding.paradoxalarm/src/main/java/org/openhab/binding/paradoxalarm/internal/discovery/ParadoxDiscoveryService.java
bundles/org.openhab.binding.paradoxalarm/src/main/java/org/openhab/binding/paradoxalarm/internal/handlers/EntityBaseHandler.java
bundles/org.openhab.binding.paradoxalarm/src/main/java/org/openhab/binding/paradoxalarm/internal/handlers/ParadoxIP150BridgeHandler.java
bundles/org.openhab.binding.paradoxalarm/src/main/java/org/openhab/binding/paradoxalarm/internal/handlers/ParadoxPanelHandler.java
bundles/org.openhab.binding.paradoxalarm/src/main/java/org/openhab/binding/paradoxalarm/internal/handlers/ParadoxPartitionHandler.java
bundles/org.openhab.binding.paradoxalarm/src/main/java/org/openhab/binding/paradoxalarm/internal/handlers/ParadoxZoneHandler.java
bundles/org.openhab.binding.paradoxalarm/src/main/java/org/openhab/binding/paradoxalarm/internal/model/Entity.java
bundles/org.openhab.binding.paradoxalarm/src/main/java/org/openhab/binding/paradoxalarm/internal/model/ParadoxPanel.java
bundles/org.openhab.binding.paradoxalarm/src/main/java/org/openhab/binding/paradoxalarm/internal/model/Partition.java
bundles/org.openhab.binding.paradoxalarm/src/main/java/org/openhab/binding/paradoxalarm/internal/model/Zone.java
bundles/org.openhab.binding.paradoxalarm/src/test/java/main/Main.java

Fixes #13640
Handle multiple panels (fixes #13640)
With this patch worked with 2 pannels connected but should work with unlimited number of panels.
P.S.: @theater I asigned to myself, you did enough already! :wink:

[paradoxalarm] Handle multiple panels

---

bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/JRubyScriptEngineFactory.java

simply just don't overwrite any constants that already exist
refs https://github.com/openhab/openhab-core/pull/3113

[jrubyscripting] don't manually filter presets.

---

CODEOWNERS

[easee] Add author in CODEOWNERS

---

CODEOWNERS

[mercedesme] Add author in CODEOWNERS

---

bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/Constants.java
bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/config/AccountConfiguration.java
bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/server/Utils.java
bundles/org.openhab.binding.mercedesme/src/test/java/org/openhab/binding/mercedesme/ConfigurationTest.java

[mercedesme] New API Migration

---

CODEOWNERS

[vesync] Add author in CODEOWNERS

---

bundles/org.openhab.binding.tibber/src/main/java/org/openhab/binding/tibber/internal/TibberBindingConstants.java
bundles/org.openhab.binding.tibber/src/main/java/org/openhab/binding/tibber/internal/handler/TibberHandler.java
bundles/org.openhab.binding.tibber/src/main/java/org/openhab/binding/tibber/internal/handler/TibberPriceConsumptionHandler.java

Closes #13648 
Signed-off-by: kjoglum <stiankj@online.no>

[tibber] Updates for breaking API changes

---

bundles/org.openhab.binding.lcn/README.md
bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/common/PckGenerator.java

[lcn] Fix setting of variables

---

bundles/org.openhab.binding.systeminfo/README.md

Signed-off-by: Mark Herwege mark.herwege@telenet.be
Closes #12059

[Systeminfo] Add comment on temperature readings on Windows

---

bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/console/JdbcCommandExtension.java

[jdbc] Console: Fix NoSuchElementException when there are no tables

---

bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcPostgresqlDAO.java

Fixes #13121 which is a regression of #11922.
JAR for testing: [org.openhab.persistence.jdbc-3.4.0-SNAPSHOT.jar](https://drive.google.com/file/d/1c8AVsDhoPX7MzWPndVZ73hPhe8uGdq51/view?usp=sharing)

[jdbc] Fix PostgreSQL query for storing timestamps

---

CODEOWNERS
bundles/org.openhab.automation.jsscripting/src/main/resources/node_modules/@jsscripting-globals.js

Fixes https://github.com/openhab/openhab-addons/issues/12646.
@jpg0 @digitaldan Can one of you please review?

[jsscripting] Fix the `console.trace` polyfill to log a stack trace & Stringify JS `Error`

---

bundles/org.openhab.binding.telegram/src/main/java/org/openhab/binding/telegram/internal/action/TelegramActions.java

Escapes the "_" in the message. Solves issue #11691

[Telegram] Can't send message with underscore character

---

bundles/org.openhab.binding.nuvo/README.md

Minor edits to README file to update rules examples.

[nuvo] update rules examples in README

---

bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/channel/KNXChannelTypeTest.java
bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/dpt/KNXCoreTypeMapperTest.java
bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/handler/KNXBridgeBaseThingHandlerTest.java
bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/i18n/KNXTranslationProviderTest.java

Since JUnit Jupiter test classes and methods do not need to be `public`.
It is recommended to omit the `public` modifier.
See https://junit.org/junit5/docs/current/user-guide/#writing-tests-classes-and-methods
> "Class and method visibility
> Test classes, test methods, and lifecycle methods are not required to be `public`, but they must not be `private`.
> 
> It is generally recommended to omit the `public` modifier for test classes, test methods, and lifecycle methods unless there is a technical reason for doing so (...)"
Signed-off-by: Thomas Traude <t-riggs@gmx.net>

[knx] Remove obsolete public modifier in tests

---

bundles/org.openhab.binding.qolsysiq/src/main/java/org/openhab/binding/qolsysiq/internal/client/dto/action/AlarmActionType.java

[qolsysiq] Fixes ENUM Typo

---

bundles/org.openhab.binding.openwebnet/README.md
bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/discovery/OpenWebNetDeviceDiscoveryService.java

[openwebnet] Thermo: zone/CU address set correctly during discovery

---

bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcDerbyDAO.java
bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcH2DAO.java
bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcHsqldbDAO.java
bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcSqliteDAO.java

Fixes #13816
Analogue to #13745
Regression of #11922
JAR for testing: [org.openhab.persistence.jdbc-3.4.0-SNAPSHOT.jar](https://drive.google.com/file/d/1ThK5_l1TDKpvVDkns72311XNBmxmXqYF/view?usp=sharing)

[jdbc] Fix Derby/H2/HSQLDB/SQLite queries for storing timestamps

---

bundles/org.openhab.binding.plugwiseha/README.md

Fixed 2 typos to make 2 attributes work

[plugwiseha] Fix typos in README examples

---

bundles/org.openhab.automation.groovyscripting/README.md
bundles/org.openhab.automation.groovyscripting/pom.xml

Updates Groovy from 3.0.9 to 3.0.13.
For all bugfixes and improvements, see:
* https://groovy-lang.org/changelogs/changelog-3.0.10.html
* https://groovy-lang.org/changelogs/changelog-3.0.11.html
* https://groovy-lang.org/changelogs/changelog-3.0.12.html
* https://groovy-lang.org/changelogs/changelog-3.0.13.html

[groovyscripting] Update Groovy to 3.0.13

---

bundles/org.openhab.binding.nibeheatpump/contrib/NibeGW/Arduino/README.md

Documentation: This is a Readme file with all the hardware hints and compilation requirements discissed in issue #13780

[nibeheatpump] Readme for NibeGW for Arduino with Hardware and compilation hints

---

bundles/org.openhab.binding.tibber/README.md
bundles/org.openhab.binding.tibber/src/main/java/org/openhab/binding/tibber/internal/handler/TibberHandler.java
bundles/org.openhab.binding.tibber/src/main/java/org/openhab/binding/tibber/internal/handler/TibberPriceConsumptionHandler.java

Nothing fancy, just some minor checkstyle fixes

[tibber] Fix checkstyle warnings

---

bundles/org.openhab.binding.webexteams/src/main/java/org/openhab/binding/webexteams/internal/WebexAuthServlet.java
bundles/org.openhab.binding.webexteams/src/main/java/org/openhab/binding/webexteams/internal/WebexTeamsHandler.java
bundles/org.openhab.binding.webexteams/src/main/resources/templates/account.html

* add null checks
* fix/improve account.html
Signed-off-by: Tom Deckers <tom@ducbase.com>

[webexteams] Fix re-authentication for person accounts

---

itests/org.openhab.binding.tradfri.tests/itest.bndrun

Depends on https://github.com/openhab/openhab-core/pull/3147

[tradfri] Resolve runbundles for Californium upgrade

---

pom.xml

Related to openhab/openhab-core#3163

Sync Jackson to 2.12.7

---

bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/ApiBridgeHandler.java

[netatmo] Improve bridge status messages in case of service outage

---

bundles/org.openhab.binding.ahawastecollection/src/main/java/org/openhab/binding/ahawastecollection/internal/AhaWasteCollectionHandler.java
bundles/org.openhab.binding.ahawastecollection/src/main/java/org/openhab/binding/ahawastecollection/internal/AhaWasteCollectionHandlerFactory.java
bundles/org.openhab.binding.ahawastecollection/src/test/java/org/openhab/binding/ahawastecollection/internal/AhaWasteCollectionHandlerTest.java

[ahawastecollection] Fixed unstable test

---

bundles/org.openhab.binding.tr064/README.md
bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/phonebook/Tr064PhonebookImpl.java
bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/soap/CallListType.java
bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/soap/SOAPValueConverter.java
bundles/org.openhab.binding.tr064/src/test/java/org/openhab/binding/tr064/internal/phonebook/PhonebookProfileTest.java

Nothing fanyc, just fixed some SAT warnings. I left one for the Test, it is partly annotated, so i assume i cannot improve that ;-)

[TR064] Fix SAT warnings

---

bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitCommandExtension.java

just the sub-commands.
since the show command is already a "search", I didn't feel it's super important to implement on that

[homekit] implement basic command completion

---

bundles/org.openhab.binding.livisismarthome/src/main/java/org/openhab/binding/livisismarthome/internal/client/GsonOptional.java
bundles/org.openhab.binding.livisismarthome/src/main/java/org/openhab/binding/livisismarthome/internal/client/LivisiClient.java
bundles/org.openhab.binding.livisismarthome/src/main/java/org/openhab/binding/livisismarthome/internal/client/URLConnectionFactory.java
bundles/org.openhab.binding.livisismarthome/src/main/java/org/openhab/binding/livisismarthome/internal/handler/LivisiBridgeHandler.java
bundles/org.openhab.binding.livisismarthome/src/main/java/org/openhab/binding/livisismarthome/internal/manager/DeviceStructureManager.java
bundles/org.openhab.binding.livisismarthome/src/main/java/org/openhab/binding/livisismarthome/internal/manager/FullDeviceManager.java
bundles/org.openhab.binding.livisismarthome/src/test/java/org/openhab/binding/livisismarthome/internal/client/URLCreatorTest.java
bundles/org.openhab.binding.livisismarthome/src/test/java/org/openhab/binding/livisismarthome/internal/handler/LivisiBridgeHandlerTest.java
bundles/org.openhab.binding.livisismarthome/src/test/java/org/openhab/binding/livisismarthome/internal/handler/LivisiDeviceHandlerTest.java

Minor checkstyle fixes. Could not find away to use the org.slf4j.Logger in the Test classes and left it as is.

[livisismarthome] Fix checkstyle

---

itests/org.openhab.binding.astro.tests/itest.bndrun
itests/org.openhab.binding.avmfritz.tests/itest.bndrun
itests/org.openhab.binding.feed.tests/itest.bndrun
itests/org.openhab.binding.hue.tests/itest.bndrun
itests/org.openhab.binding.max.tests/itest.bndrun
itests/org.openhab.binding.mielecloud.tests/itest.bndrun
itests/org.openhab.binding.modbus.tests/itest.bndrun
itests/org.openhab.binding.mqtt.homeassistant.tests/itest.bndrun
itests/org.openhab.binding.mqtt.homie.tests/itest.bndrun
itests/org.openhab.binding.nest.tests/itest.bndrun
itests/org.openhab.binding.ntp.tests/itest.bndrun
itests/org.openhab.binding.systeminfo.tests/itest.bndrun
itests/org.openhab.binding.tradfri.tests/itest.bndrun
itests/org.openhab.binding.wemo.tests/itest.bndrun
itests/org.openhab.persistence.mapdb.tests/itest.bndrun
pom.xml

Upgrade bnd to 6.4.0

---

bundles/org.openhab.transform.scale/src/test/java/org/openhab/transform/scale/internal/ScaleTransformServiceTest.java

[transform/scale] Make unit tests compatible with Windows

---

bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/config/BridgeConfiguration.java
bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/config/DeviceConfig.java
bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/config/IPBridgeConfiguration.java
bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/AbstractKNXThingHandler.java
bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/DeviceThingHandler.java
bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/IPBridgeThingHandler.java
bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/SerialBridgeThingHandler.java

Take over initialization logic from KNX IP gateway for serial gateway. 
Properly re-initialize serial gateway after configuration changes done in UI.
Fixes #13892.

[knx] Improve handling of serial gateways

---

bundles/org.openhab.binding.goecharger/src/main/java/org/openhab/binding/goecharger/internal/GoEChargerBindingConstants.java

[goecharger] Consider correct channel ID (maxCurrentTemp)

---

itests/org.openhab.binding.mielecloud.tests/src/main/java/org/openhab/binding/mielecloud/internal/config/servlet/ForwardToLoginServletTest.java

Code change provided by @BjoernLange
Fix #12627 

[mielecloud] Fix integration tests

---

bundles/org.openhab.binding.mqtt.generic/README.md

Also change parameter name for color mode,
Change color example to fit to the real parameters.
Signed-off-by: Udo Hartmann <udo1toni@gmail.com>

[mqtt.generic] Change color example

---

bundles/org.openhab.automation.jsscripting/src/main/resources/OH-INF/i18n/jsscripting.properties

[jsscripting] Update add-on name in default translation

---

bundles/org.openhab.binding.flicbutton/README.md
bundles/org.openhab.binding.foobot/README.md
bundles/org.openhab.binding.fsinternetradio/README.md
bundles/org.openhab.binding.haywardomnilogic/README.md
bundles/org.openhab.binding.hdpowerview/README.md
bundles/org.openhab.binding.heos/README.md
bundles/org.openhab.binding.http/README.md
bundles/org.openhab.binding.jellyfin/README.md

Fixes #13882
Regression of #13866

Fix alignment/indentation in documentation

---

bundles/org.openhab.binding.wolfsmartset/README.md

Update link to current document from Wolf download center. Fixes #13995.

[wolfsmartset] Fix link to external documentation

---

bundles/org.openhab.persistence.jdbc/pom.xml
bundles/org.openhab.persistence.jdbc/src/main/feature/feature.xml
bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcConfiguration.java

The current version of org.xerial/sqlite-jdbc does not support aarch64 (e.g. openhabian 64bit).
This PR updates this dependency to the latest version and fixes #14002 .
I've tested this on my own raspi and it seems to work just fine with this version.

[jdbc] Update org.xerial/sqlite-jdbc to 3.40.0.0

---

bundles/org.openhab.binding.shelly/README.md

[shelly] Remove broken images

---

bundles/org.openhab.binding.bluetooth.airthings/src/main/java/org/openhab/binding/bluetooth/airthings/internal/AbstractAirthingsHandler.java
bundles/org.openhab.binding.bluetooth.airthings/src/main/java/org/openhab/binding/bluetooth/airthings/internal/AirthingsBindingConstants.java
bundles/org.openhab.binding.bluetooth.airthings/src/main/java/org/openhab/binding/bluetooth/airthings/internal/AirthingsDiscoveryParticipant.java
bundles/org.openhab.binding.bluetooth.airthings/src/main/java/org/openhab/binding/bluetooth/airthings/internal/AirthingsWaveGen1Handler.java
bundles/org.openhab.binding.bluetooth.airthings/src/main/java/org/openhab/binding/bluetooth/airthings/internal/AirthingsWaveMiniHandler.java
bundles/org.openhab.binding.bluetooth.airthings/src/main/java/org/openhab/binding/bluetooth/airthings/internal/AirthingsWavePlusHandler.java

removed forbidden unit package
null annotations
checkstyle
Part of multiple PR's for bluetooth bundles. Can me merged independent

[bluetooth.airthings] null annotations

---

bundles/org.openhab.binding.bluetooth.blukii/src/main/java/org/openhab/binding/bluetooth/blukii/BlukiiBindingConstants.java
bundles/org.openhab.binding.bluetooth.blukii/src/main/java/org/openhab/binding/bluetooth/blukii/handler/BlukiiHandler.java
bundles/org.openhab.binding.bluetooth.blukii/src/main/java/org/openhab/binding/bluetooth/blukii/internal/BlukiiHandlerFactory.java

null annotations
Part of multiple PR's for bluetooth bundles. Can be merged independent.

[bluetooth.blukii] null annotations

---

.github/workflows/ci-build.yml
itests/org.openhab.binding.astro.tests/itest.bndrun
itests/org.openhab.binding.avmfritz.tests/itest.bndrun
itests/org.openhab.binding.feed.tests/itest.bndrun
itests/org.openhab.binding.hue.tests/itest.bndrun
itests/org.openhab.binding.max.tests/itest.bndrun
itests/org.openhab.binding.mielecloud.tests/itest.bndrun
itests/org.openhab.binding.modbus.tests/itest.bndrun
itests/org.openhab.binding.mqtt.homeassistant.tests/itest.bndrun
itests/org.openhab.binding.mqtt.homie.tests/itest.bndrun
itests/org.openhab.binding.nest.tests/itest.bndrun
itests/org.openhab.binding.ntp.tests/itest.bndrun
itests/org.openhab.binding.systeminfo.tests/itest.bndrun
itests/org.openhab.binding.tradfri.tests/itest.bndrun
itests/org.openhab.binding.wemo.tests/itest.bndrun
itests/org.openhab.persistence.mapdb.tests/itest.bndrun

Fix build / Resolve itests

---

bundles/org.openhab.binding.nanoleaf/README.md
bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/handler/NanoleafControllerHandler.java

see https://github.com/openhab/openhab-core/pull/3129
It should be noted I don't have nanoleaf, so I have not tested this.

[nanoleaf] Handle and provide QuantityType for color-temperature-abs channel

---

bundles/org.openhab.binding.awattar/pom.xml
bundles/org.openhab.binding.electroluxair/pom.xml
bundles/org.openhab.binding.fineoffsetweatherstation/pom.xml
bundles/org.openhab.binding.flicbutton/pom.xml
bundles/org.openhab.binding.groupepsa/pom.xml
bundles/org.openhab.binding.herzborg/pom.xml
bundles/org.openhab.binding.jellyfin/pom.xml
bundles/org.openhab.binding.luxom/pom.xml
bundles/org.openhab.binding.mybmw/pom.xml
bundles/org.openhab.binding.mycroft/pom.xml
bundles/org.openhab.binding.prowl/pom.xml
bundles/org.openhab.binding.publictransportswitzerland/pom.xml
bundles/org.openhab.binding.smsmodem/pom.xml
bundles/org.openhab.binding.solarmax/pom.xml
bundles/org.openhab.binding.sonnen/pom.xml
bundles/org.openhab.binding.vesync/pom.xml
bundles/org.openhab.binding.wundergroundupdatereceiver/pom.xml
bundles/org.openhab.binding.yamahamusiccast/pom.xml
pom.xml

Most of these add-ons were merged after the XSD location in all other POMs were updated.

Use HTTPS in pom.xml where possible

---

bundles/org.openhab.io.homekit/pom.xml
bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitAuthInfoImpl.java

[homekit] implement List-Pairings method

---

bundles/org.openhab.binding.knx/README.md
bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/channel/WriteSpecImpl.java
bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/ReadDatapoint.java
bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/KNXCoreTypeMapper.java
bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/factory/KNXHandlerFactory.java
bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/IPBridgeThingHandler.java

[knx] Fix SAT warnings

---

bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/AirVisualNodeHandlerFactory.java
bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/config/AirVisualNodeConfig.java
bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/discovery/AirVisualNodeDiscoveryService.java
bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/dto/DateAndTime.java
bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/dto/MeasurementsInterface.java
bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/dto/NodeDataInterface.java
bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/dto/PowerSavingTime.java
bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/dto/PowerSavingTimeSlot.java
bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/dto/airvisual/Measurements.java
bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/dto/airvisual/NodeData.java
bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/dto/airvisual/PowerSaving.java
bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/dto/airvisual/Settings.java
bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/dto/airvisual/Status.java
bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/dto/airvisualpro/Measurements.java
bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/dto/airvisualpro/PowerSaving.java
bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/dto/airvisualpro/ProNodeData.java
bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/dto/airvisualpro/SensorLife.java
bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/dto/airvisualpro/SensorMode.java
bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/dto/airvisualpro/Settings.java
bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/dto/airvisualpro/Status.java
bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/handler/AirVisualNodeHandler.java

added null annotations, some very minor refactoring.
Left one `UnusedPrivateField` warning that allready existed. It is part of json/dto and might be essential in request/response model binding.
Edit: I thik it is ready for a review. Maybe not merge it so short before 3.4.0 as it does not solve bugs (but tries to prevent them) a JAR is available here: https://1drv.ms/u/s!AnMcxmvEeupwjpdU8sz_NrUHNz7Diw?e=DN2WPo

[airvisualnode] Add null annotations

---

bundles/org.openhab.binding.tplinksmarthome/README.md

Signed-off-by: Tim Harper <timcharper@gmail.com>

[tplinksmarthome] Document sending raw commands to devices

---

bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcMapper.java

Reported in the forum:
https://community.openhab.org/t/openhab-3-4-release-discussion/142257/115
Fixes #14053
Regression of #13544

[jdbc] Fix IllegalArgumentException on service activation

---

bundles/org.openhab.binding.velux/README.md

Updated Discovery instructions as after KLF200 is auto discovered and configured discovery of scenes and actuators need to be manually triggered.
This is a documentation update.

[velux] Updated Discovery instructions for scenes and actuators

---

bundles/org.openhab.binding.bluetooth.ruuvitag/src/main/java/org/openhab/binding/bluetooth/ruuvitag/internal/RuuviTagBindingConstants.java

Very minor checkstyle.
Part of multiple PR's for bluetooth bundles.

[bluetooth.ruuvitag] minor checkstyle

---

bundles/org.openhab.binding.bluetooth.am43/src/main/java/org/openhab/binding/bluetooth/am43/internal/AM43Configuration.java
bundles/org.openhab.binding.bluetooth.am43/src/main/java/org/openhab/binding/bluetooth/am43/internal/command/AM43Command.java
bundles/org.openhab.binding.bluetooth.am43/src/main/java/org/openhab/binding/bluetooth/am43/internal/data/ControlAction.java
bundles/org.openhab.binding.bluetooth.am43/src/main/java/org/openhab/binding/bluetooth/am43/internal/data/Direction.java
bundles/org.openhab.binding.bluetooth.am43/src/main/java/org/openhab/binding/bluetooth/am43/internal/data/OperationMode.java

Removed forbidden package and added null annotations. Part of multiple PR's for bluetooth bundles. Can be merged seperately.

[bluetooth.am43] null annotations

---

bundles/org.openhab.binding.bluetooth.daikinmadoka/src/main/java/org/openhab/binding/bluetooth/daikinmadoka/handler/DaikinMadokaHandler.java
bundles/org.openhab.binding.bluetooth.daikinmadoka/src/main/java/org/openhab/binding/bluetooth/daikinmadoka/internal/DaikinMadokaConfiguration.java
bundles/org.openhab.binding.bluetooth.daikinmadoka/src/main/java/org/openhab/binding/bluetooth/daikinmadoka/internal/model/commands/DisableCleanFilterIndicatorCommand.java
bundles/org.openhab.binding.bluetooth.daikinmadoka/src/main/java/org/openhab/binding/bluetooth/daikinmadoka/internal/model/commands/GetCleanFilterIndicatorCommand.java
bundles/org.openhab.binding.bluetooth.daikinmadoka/src/main/java/org/openhab/binding/bluetooth/daikinmadoka/internal/model/commands/GetEyeBrightnessCommand.java
bundles/org.openhab.binding.bluetooth.daikinmadoka/src/main/java/org/openhab/binding/bluetooth/daikinmadoka/internal/model/commands/GetFanspeedCommand.java
bundles/org.openhab.binding.bluetooth.daikinmadoka/src/main/java/org/openhab/binding/bluetooth/daikinmadoka/internal/model/commands/GetIndoorOutoorTemperatures.java
bundles/org.openhab.binding.bluetooth.daikinmadoka/src/main/java/org/openhab/binding/bluetooth/daikinmadoka/internal/model/commands/GetOperationHoursCommand.java
bundles/org.openhab.binding.bluetooth.daikinmadoka/src/main/java/org/openhab/binding/bluetooth/daikinmadoka/internal/model/commands/GetOperationmodeCommand.java
bundles/org.openhab.binding.bluetooth.daikinmadoka/src/main/java/org/openhab/binding/bluetooth/daikinmadoka/internal/model/commands/GetPowerstateCommand.java
bundles/org.openhab.binding.bluetooth.daikinmadoka/src/main/java/org/openhab/binding/bluetooth/daikinmadoka/internal/model/commands/GetSetpointCommand.java
bundles/org.openhab.binding.bluetooth.daikinmadoka/src/main/java/org/openhab/binding/bluetooth/daikinmadoka/internal/model/commands/GetVersionCommand.java
bundles/org.openhab.binding.bluetooth.daikinmadoka/src/main/java/org/openhab/binding/bluetooth/daikinmadoka/internal/model/commands/ResetCleanFilterTimerCommand.java
bundles/org.openhab.binding.bluetooth.daikinmadoka/src/test/java/org/openhab/binding/bluetooth/daikinmadoka/handler/DummyThing.java
bundles/org.openhab.binding.bluetooth.daikinmadoka/src/test/java/org/openhab/binding/bluetooth/daikinmadoka/internal/MadokaMessageTest.java
bundles/org.openhab.binding.bluetooth.daikinmadoka/src/test/java/org/openhab/binding/bluetooth/daikinmadoka/internal/UartProcessorTest.java

null annotations
checkstyle
other SAT warnings
Part of multiple PR's for bluetooth bundles. This may be merged independent.
Some warnings (compile and sat) are left as is. If those need to be fixed, i need some guidance, but i think it can be left alone (for now).

[bluetooth.daikinmadoka] null annotations

---

bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/MieleHandlerFactory.java
bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/DishwasherHandler.java

Rename handler to fix case and make consistent with corresponding channel selector.

[miele] Rename handler to fix case

---

bundles/org.openhab.binding.knx/README.md

add color channel to knx binding docu

[knx] Add color channel to knx binding docu

---

bundles/org.openhab.binding.deconz/README.md
bundles/org.openhab.binding.deconz/pom.xml
bundles/org.openhab.binding.deconz/src/main/feature/feature.xml
bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/binding/binding.xml
bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/i18n/deconz.properties

[deconz] Simplify binding name

---

bundles/org.openhab.binding.luxtronikheatpump/README.md

Loxwiki has moved into the Atlassian cloud: https://loxwiki.atlassian.net/wiki/spaces/LOX/pages/1622769957/Planung+bersiedelung+zu+loxwiki.atlassian.net

[luxtronikheatpump] Update URL to Loxwiki

---

bundles/org.openhab.io.homekit/README.md

Adds a few solutions to common problems configuration the homekit addon.

[homekit] Add additional troubleshooting steps for homekit

---

bundles/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromecastStatusUpdater.java

[chromecast] Fix for NPE when playerState is null

---

bundles/org.openhab.binding.astro/src/test/java/org/openhab/binding/astro/internal/calc/MoonCalcTest.java

- Adds accuracy tests to the Astro binding
Resolves: https://github.com/openhab/openhab-addons/issues/14074

[astro] Add moon accuracy tests

---

pom.xml

* Switch to version used by openhab-core
* Apply patch from openhab/openhab-core#2359 for upgrading dependency on plexus

Upgrade maven-javadoc-plugin to release 3.2.0

---

bundles/org.openhab.binding.bsblan/src/main/java/org/openhab/binding/bsblan/internal/api/BsbLanApiCaller.java
bundles/org.openhab.binding.bsblan/src/main/java/org/openhab/binding/bsblan/internal/configuration/BsbLanBridgeConfiguration.java
bundles/org.openhab.binding.bsblan/src/main/java/org/openhab/binding/bsblan/internal/handler/BsbLanBridgeHandler.java
bundles/org.openhab.binding.bsblan/src/main/java/org/openhab/binding/bsblan/internal/helper/BsbLanParameterConverter.java

Minor refactoring:
- add null annotation
- checkstyle

[bsblan] Minor SAT fixes

---

bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/watch/JRubyScriptFileWatcher.java
bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/fs/watch/JSScriptFileWatcher.java

Related to https://github.com/openhab/openhab-core/pull/3255

[scripting] Adjust to core changes

---

bundles/org.openhab.binding.knx/pom.xml
bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/KNXBindingConstants.java
bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/BusMessageListener.java
bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/config/DeviceConfig.java
bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/IPBridgeThingHandler.java
bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/SerialBridgeThingHandler.java
bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/i18n/KNXTranslationProvider.java

[knx] Fix javadoc errors

---

bundles/org.openhab.persistence.influxdb/README.md

See
https://community.openhab.org/t/influxdb-persistence-doesnt-work-with-s sl/35409/10?u=florian-h05.

[influxdb] Add docs for usage of self-signed certs

---

bundles/org.openhab.binding.wundergroundupdatereceiver/src/test/java/org/openhab/binding/wundergroundupdatereceiver/internal/WundergroundUpdateReceiverDiscoveryServiceTest.java

Related to https://github.com/openhab/openhab-core/pull/3241
Changes here are necessary because the test relied on a fixed order of the channels in the returned list. This change makes the test more robust.
As a side-note: I'm a bit astonished to see thing type upgrade code in the handler because my impression was that the policy is not to allow such code.

Fix build after core changes

---

bundles/org.openhab.binding.gree/src/main/resources/OH-INF/i18n/gree.properties
bundles/org.openhab.binding.gree/src/main/resources/OH-INF/i18n/gree_de.properties
bundles/org.openhab.binding.gree/src/main/resources/OH-INF/i18n/gree_hu.properties

[gree] Remove unneeded i18n entry addon.gree.label

---

bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/MeasureCapability.java

Bringing a solution to issue #14256.
This solution is not the best but takes in account observations made in issue #13015.

[Netatmo] Preserving outside temperature minimal ranges for dynamic channels

---

bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitImpl.java

a regression caused during the final changes of #13877

[homekit] fix restarted on network interface change

---

bundles/org.openhab.binding.tibber/src/main/java/org/openhab/binding/tibber/internal/handler/TibberHandler.java

The server might send an unexpected JSON result. Due to not properly checking the json properties, a NPE is thrown.
4.0.0 JAR: https://1drv.ms/u/s!AnMcxmvEeupwjqVJMTcLNSI-WqtArA?e=PzGWNC
Fixes: https://github.com/openhab/openhab-addons/issues/14267

[tibber] Fix NPE on server issues

---

bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyBaseHandler.java

[shelly] Cancel the init job when the thing handler is disposed

---

bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/InfluxDBPersistenceService.java

[influxdb] Fix re-connection issues

---

bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueBridgeHandler.java

[hue] Get scenes for groups without 10 minutes delay

---

bundles/org.openhab.binding.souliss/README.md

fixed some typos and add UDP warning

[souliss] Update README.md

---

bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/LGWebOSHandlerFactory.java

[lgwebos] Create WEB socket client using OH core method

---

bundles/org.openhab.binding.tapocontrol/README.md
bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/api/TapoDeviceConnector.java
bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/api/TapoDeviceHttpApi.java
bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/constants/TapoBindingSettings.java
bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/constants/TapoThingConstants.java
bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/device/TapoDevice.java
bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/device/TapoSmartPlug.java
bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/helpers/PayloadBuilder.java
bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/structures/TapoChild.java
bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/structures/TapoChildData.java
bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/structures/TapoSubRequest.java
bundles/org.openhab.binding.tapocontrol/src/main/resources/OH-INF/i18n/tapocontrol.properties
bundles/org.openhab.binding.tapocontrol/src/main/resources/OH-INF/thing/P300.xml
bundles/org.openhab.binding.tapocontrol/src/main/resources/OH-INF/thing/channels.xml

[TapoControl] Adding P300 to the list of supported equipments

---

bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/fs/watch/JSScriptFileWatcher.java

Depends on https://github.com/openhab/openhab-core/pull/3369

[jsscripting] Fix JSScriptFileWatcher not ignoring correct directory

---

bundles/org.openhab.binding.solarmax/README.md
bundles/org.openhab.binding.solarmax/src/main/java/org/openhab/binding/solarmax/internal/SolarMaxConfiguration.java
bundles/org.openhab.binding.solarmax/src/main/java/org/openhab/binding/solarmax/internal/SolarMaxHandler.java
bundles/org.openhab.binding.solarmax/src/main/java/org/openhab/binding/solarmax/internal/connector/SolarMaxConnector.java
bundles/org.openhab.binding.solarmax/src/main/resources/OH-INF/i18n/solarmax.properties
bundles/org.openhab.binding.solarmax/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.solarmax/src/test/java/org/openhab/binding/solarmax/internal/connector/SolarmaxConnectorFindCommands.java

Closes #14365
Signed-off-by: Jamie Townsend <jamie_townsend@hotmail.com>

[solarmax] Support configurable Device Address

---

bundles/org.openhab.binding.openthermgateway/src/main/java/org/openhab/binding/openthermgateway/internal/GatewayCommandCode.java

[openthermgateway] Changed command code from ST to SC for SetClock

---

bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/handler/KM200GatewayHandler.java

[km200] Fix initialization warning: "tried updating the thing status although the handler was already disposed."

---

bundles/org.openhab.binding.cbus/src/main/java/org/openhab/binding/cbus/handler/CBusCGateHandler.java
bundles/org.openhab.binding.cbus/src/main/java/org/openhab/binding/cbus/handler/CBusNetworkHandler.java

[cbus] Fix exceptions due to invalid thing status updates

---

bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/kostalinverter/internal/thirdgeneration/ThirdGenerationHandler.java

[kostalinverter] Fix exception due to invalid thing status update

---

bundles/org.openhab.binding.semsportal/src/main/java/org/openhab/binding/semsportal/internal/PortalHandler.java

[semsportal] Fix exception due to invalid thing status update

---

bundles/org.openhab.binding.weathercompany/src/main/java/org/openhab/binding/weathercompany/internal/handler/WeatherCompanyBridgeHandler.java
bundles/org.openhab.binding.weathercompany/src/main/java/org/openhab/binding/weathercompany/internal/util/ExceptionUtils.java

- Remove dependency on org.apache.commons

[weathercompany] Remove org.apache.common

---

bundles/org.openhab.binding.smartmeter/src/main/java/org/openhab/binding/smartmeter/internal/SmartMeterHandler.java
bundles/org.openhab.binding.smartmeter/src/main/java/org/openhab/binding/smartmeter/internal/helper/SerialParameter.java

[smartmeter] Remove org.apache.common

---

bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaEventEndpoint.java
bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaVehicleHandler.java

[tesla] Normalize thread names and avoid a possible IAE

---

bundles/org.openhab.binding.pentair/src/main/java/org/openhab/binding/pentair/internal/config/PentairIPBridgeConfig.java
bundles/org.openhab.binding.pentair/src/main/java/org/openhab/binding/pentair/internal/config/PentairSerialBridgeConfig.java

[pentair] Remove org.apache.common

---

bundles/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/discovery/OnkyoUpnpDiscoveryParticipant.java

[onkyo] Remove org.apache.common

---

bundles/org.openhab.binding.omnikinverter/src/main/java/org/openhab/binding/omnikinverter/internal/OmnikInverter.java

[omnikinverter] Remove org.apache.common

---

bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/KM200Device.java

[km200] Remove org.apache.commons

---

bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosXMLParser.java
bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/util/StringUtils.java

Follow up to https://github.com/openhab/openhab-addons/pull/14438
- forgotten null annotations 
- removed last org.apache.common import

[sonos] Fix remaining org.apache.common

---

bundles/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/config/NibeUplinkConfiguration.java

[nibeuplink] Remove org.apache.common

---

bundles/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/stick/CommandUtil.java
bundles/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/stick/SerialConnection.java

[elerotransmitterstick] Remove apache.commons

---

bundles/org.openhab.binding.sleepiq/README.md
bundles/org.openhab.binding.sleepiq/src/main/java/org/openhab/binding/sleepiq/internal/SleepIQBindingConstants.java
bundles/org.openhab.binding.sleepiq/src/main/java/org/openhab/binding/sleepiq/internal/handler/SleepIQDualBedHandler.java
bundles/org.openhab.binding.sleepiq/src/main/resources/OH-INF/i18n/sleepiq.properties
bundles/org.openhab.binding.sleepiq/src/main/resources/OH-INF/thing/thing-types.xml

Add 4 new channels for detailed sleep time breakdown.
Signed-off-by: Mark Hilbush [mark@hilbush.com](mailto:mark@hilbush.com)

[sleepiq] Add new channels

---

bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/LinkyHandlerFactory.java

[linky] Call createHttpClient with a SslContextFactory parameter

---

bundles/org.openhab.binding.remoteopenhab/src/main/java/org/openhab/binding/remoteopenhab/internal/RemoteopenhabHandlerFactory.java

[remoteopenhab] Call createHttpClient with a SslContextFactory parameter

---

bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaBridgeHandler.java

[somfytahoma] Call createHttpClient with a SslContextFactory parameter

---

bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/VolvoOnCallHandlerFactory.java
bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/api/VocHttpApi.java
bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/handler/VolvoOnCallBridgeHandler.java

A different name for each bridge thing creating a HTTP client.

[volvooncall] Adjust thread name for HTTP client

---

bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/SerialClient.java

Fixes #13683, kBerry module: thing status misleading

[knx] FT12: Autodetect cEMI on Weinzierl devices

---

bundles/org.openhab.binding.upnpcontrol/src/main/java/org/openhab/binding/upnpcontrol/internal/audiosink/UpnpAudioSinkReg.java
bundles/org.openhab.binding.upnpcontrol/src/main/java/org/openhab/binding/upnpcontrol/internal/handler/UpnpHandler.java
bundles/org.openhab.binding.upnpcontrol/src/main/java/org/openhab/binding/upnpcontrol/internal/handler/UpnpRendererHandler.java
bundles/org.openhab.binding.upnpcontrol/src/main/java/org/openhab/binding/upnpcontrol/internal/handler/UpnpServerHandler.java
bundles/org.openhab.binding.upnpcontrol/src/main/java/org/openhab/binding/upnpcontrol/internal/queue/UpnpEntryQueue.java

- Avoiding imports purely for javadoc links
- Fix links to class methods

[upnpcontrol] Fix javadoc links

---

bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/UniFiThingHandlerFactory.java

[unifi] Use createHttpClient

---

bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/TapoControlHandlerFactory.java

[tapocontrol] Use createHttpClient

---

bundles/org.openhab.binding.somneo/src/main/java/org/openhab/binding/somneo/internal/SomneoBindingConstants.java
bundles/org.openhab.binding.somneo/src/main/java/org/openhab/binding/somneo/internal/SomneoHandlerFactory.java

[somneo] Use createHttpClient

---

bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/Tr064HandlerFactory.java

[tr064] Use createHttpClient

---

bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/HttpBindingConstants.java
bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/HttpHandlerFactory.java

[http] Use createHttpClient

---

bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/DaikinBindingConstants.java
bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/DaikinHttpClientFactoryImpl.java

[daikin] Use createHttpClient

---

bundles/org.openhab.binding.nibeheatpump/contrib/NibeGW/Arduino/NibeGW/NibeGW.ino

Set the correct field when changing verbose level.

[nibeheatpump] nibegw: Fix setting debug verboseLevel

---

bundles/org.openhab.binding.neohub/src/main/java/org/openhab/binding/neohub/internal/NeoHubHandler.java
bundles/org.openhab.binding.neohub/src/main/java/org/openhab/binding/neohub/internal/NeoHubHandlerFactory.java
bundles/org.openhab.binding.neohub/src/main/java/org/openhab/binding/neohub/internal/NeoHubWebSocket.java
bundles/org.openhab.binding.neohub/src/test/java/org/openhab/binding/neohub/test/NeoHubProtocolTests.java

[neohub] Use createWebSocketClient

---

bundles/org.openhab.binding.upnpcontrol/src/main/java/org/openhab/binding/upnpcontrol/internal/handler/UpnpRendererHandler.java

Fixes switching on shuffle also switching only playing a single song on.

[upnpcontrol] fix shuffle switch also switching only play one

---

bundles/org.openhab.automation.jsscripting/pom.xml

CHANGELOG: https://github.com/openhab/openhab-js/blob/v4.1.0/CHANGELOG.md#410

[jsscripting] Upgrade openhab-js to 4.1.0

---

itests/org.openhab.automation.jsscriptingnashorn.tests/itest.bndrun
itests/org.openhab.binding.astro.tests/itest.bndrun
itests/org.openhab.binding.avmfritz.tests/itest.bndrun
itests/org.openhab.binding.avmfritz.tests/src/main/java/org/openhab/binding/avmfritz/internal/handler/AVMFritzThingHandlerOSGiTest.java
itests/org.openhab.binding.feed.tests/itest.bndrun
itests/org.openhab.binding.hue.tests/itest.bndrun
itests/org.openhab.binding.max.tests/itest.bndrun
itests/org.openhab.binding.mielecloud.tests/itest.bndrun
itests/org.openhab.binding.modbus.tests/itest.bndrun
itests/org.openhab.binding.mqtt.homeassistant.tests/itest.bndrun
itests/org.openhab.binding.mqtt.homie.tests/itest.bndrun
itests/org.openhab.binding.nest.tests/itest.bndrun
itests/org.openhab.binding.ntp.tests/itest.bndrun
itests/org.openhab.binding.systeminfo.tests/itest.bndrun
itests/org.openhab.binding.tradfri.tests/itest.bndrun
itests/org.openhab.binding.wemo.tests/itest.bndrun
itests/org.openhab.persistence.mapdb.tests/itest.bndrun

Resolve itests after core changes

---

bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/KNXCoreTypeMapper.java
bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/DeviceThingHandler.java

Fixes #6970.
Carryover from smarthomej/addons#162.
Also-by: Jan N. Klug github@klug.nrw
@J-N-K Is the commit message / credit ok for you? I added you to the sign-off using an Also-by statement.
Refs: https://github.com/openhab/openhab-addons/issues/14502

[knx] Fix DPT 3.007 (Control Dimming) for non -control channels

---

bundles/org.openhab.binding.knx/README.md

Carryover from smarthomej/addons#73.
Also-by: Jan N. Klug github@klug.nrw
Refs: #14502

[knx] Improve documentation for DPT 1.009

---

bundles/org.openhab.binding.exec/src/main/java/org/openhab/binding/exec/internal/ExecWhitelistWatchService.java

[exec] Fix whitelist not read

---

itests/org.openhab.automation.jsscriptingnashorn.tests/itest.bndrun
itests/org.openhab.binding.astro.tests/itest.bndrun
itests/org.openhab.binding.avmfritz.tests/itest.bndrun
itests/org.openhab.binding.hue.tests/itest.bndrun
itests/org.openhab.binding.max.tests/itest.bndrun
itests/org.openhab.binding.mielecloud.tests/itest.bndrun
itests/org.openhab.binding.modbus.tests/itest.bndrun
itests/org.openhab.binding.mqtt.homeassistant.tests/itest.bndrun
itests/org.openhab.binding.mqtt.homie.tests/itest.bndrun
itests/org.openhab.binding.nest.tests/itest.bndrun
itests/org.openhab.binding.ntp.tests/itest.bndrun
itests/org.openhab.binding.systeminfo.tests/itest.bndrun
itests/org.openhab.binding.tradfri.tests/itest.bndrun
itests/org.openhab.binding.wemo.tests/itest.bndrun
itests/org.openhab.persistence.mapdb.tests/itest.bndrun

Related to openhab/openhab-core#3421

Resolve itest runbundles for JUPnP upgrade

---

bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/influx2/InfluxDB2RepositoryImpl.java

Fixes a regression introduced in #14304

[influxdb] Fix query for InfluxDB2

---

bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaEventEndpoint.java
bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaVehicleHandler.java

[tesla] Stop the WebSocket client when disposing the thing handler

---

bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/servlet/CameraServlet.java
bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/servlet/IpCameraServlet.java

Fixes the folowing errors:
```
HTTP ERROR 500 java.lang.IllegalStateException: !asyncSupported: NotAsync:org.ops4j.pax.web.service.spi.servlet.OsgiInitializedServlet@536b0858
URI:	/ipcamera/192168493/ipcamera.jpg
STATUS:	500
MESSAGE:	java.lang.IllegalStateException: !asyncSupported: NotAsync:org.ops4j.pax.web.service.spi.servlet.OsgiInitializedServlet@536b0858
SERVLET:	org.openhab.binding.ipcamera.internal.servlet.CameraServlet
CAUSED BY:	java.lang.IllegalStateException: !asyncSupported: NotAsync:org.ops4j.pax.web.service.spi.servlet.OsgiInitializedServlet@536b0858
Powered by Jetty:// 9.4.50.v20221201
```
See:
* https://community.openhab.org/t/openhab-4-0-snapshot-discussion/142322/226
* https://groups.google.com/g/ops4j/c/E9p7tPydPmo
* …

[ipcamera] Make sure created Servlet supports async

---

bundles/org.openhab.binding.androiddebugbridge/README.md

Update docs of androiddebugbridge
* Use code fence for intents
* Fix Item type of awake-state
* Pretty print JSON and add Netflix
Not tested, as no code was changed.

[androiddebugbridge] Update docs of androiddebugbridge

---

bundles/org.openhab.transform.rollershutterposition/src/main/resources/OH-INF/addon/addon.xml

Add missing addon.xml from #13259.

[transform.rollershutterposition] Add missing addon.xml

---

bundles/org.openhab.binding.shelly/README.md

Remove the unused headings for generation 2. There is probably a manual missing for gen 2, but while this is the case the headlines can be removed
Signed-off-by: Felix Schneider <fs@felix-schneider.org>

[shelly] Remove unused headings

---

bundles/org.openhab.binding.solaredge/src/main/java/org/openhab/binding/solaredge/internal/config/SolarEdgeConfiguration.java

- Remove dependency on org.apache.commons

[solaredge] Remove org.apache.common

---

bundles/org.openhab.binding.tibber/src/main/java/org/openhab/binding/tibber/internal/handler/TibberHandler.java

Enhancement to allow binding to check for potential change in subscription URL at every reconnect attempt, not just at initial startup.

[tibber] Query for subscription url every reconnect attempt

---

bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/manager/ShellyManagerServlet.java

Using Whiteboard annotations seems to fix this issue.

[shelly] Fix missing /shelly/manager

---

bundles/org.openhab.voice.voskstt/pom.xml

Upgrade vosk to lastest version.
Tested on 4.0.0.M1.

[voskstt] Upgrade library

---

bundles/org.openhab.voice.watsonstt/pom.xml

Upgrade library and dependencies.
Tested on 4.0.0.M1.

[watsonstt] Upgrade library

---

bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/influx2/InfluxDB2FilterCriteriaQueryCreatorImpl.java
bundles/org.openhab.persistence.influxdb/src/test/java/org/openhab/persistence/influxdb/internal/InfluxFilterCriteriaQueryCreatorImplTest.java

Fixes #14593 
Most likely caused by upgrading the dependencies as the code itself did not change in that respect.

[influxdb] Fix "empty range" exception when querying InfluxDB2

---

bundles/org.openhab.binding.hue/src/test/java/org/openhab/binding/hue/internal/handler/HueLightHandlerTest.java

Fix tests after openhab/openhab-core#3434

[hue] Fix color tests after HSBType changes

---

bundles/org.openhab.binding.tradfri/src/test/java/org/openhab/binding/tradfri/internal/TradfriColorTest.java

Fix tests after openhab/openhab-core#3434
See https://ci.openhab.org/job/openHAB-Addons/1013/

[tradfri] Fix color tests after HSBType changes

---

bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetThermoregulationHandler.java

[openwebnet] Thermo: Fix wrong parameter in .getChannel

---

bundles/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/NibeUplinkBindingConstants.java
bundles/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/callback/AbstractUplinkCommandCallback.java
bundles/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/command/GenericStatusUpdate.java
bundles/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/command/Login.java
bundles/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/command/NibeUplinkCommand.java
bundles/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/command/UpdateSetting.java
bundles/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/connector/CommunicationStatus.java
bundles/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/connector/UplinkWebInterface.java
bundles/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/handler/NibeUplinkHandler.java
bundles/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/handler/UplinkBaseHandler.java
bundles/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/model/ChannelGroup.java
bundles/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/model/DataResponseTransformer.java
bundles/org.openhab.binding.nibeuplink/src/main/resources/OH-INF/i18n/nibeuplink.properties

added some additional null checks, removed some obsolete null checks. simplified some code sections.
This should not change the way this binding works in general.

[nibeuplink] Fix NPEs, minor refactoring

---

itests/org.openhab.binding.nest.tests/src/main/java/org/openhab/binding/nest/internal/wwn/dto/WWNDataUtil.java
itests/org.openhab.binding.nest.tests/src/main/java/org/openhab/binding/nest/internal/wwn/dto/WWNGsonParsingTest.java
itests/org.openhab.binding.nest.tests/src/main/java/org/openhab/binding/nest/internal/wwn/handler/WWNAccountHandlerTest.java
itests/org.openhab.binding.nest.tests/src/main/java/org/openhab/binding/nest/internal/wwn/handler/WWNCameraHandlerTest.java
itests/org.openhab.binding.nest.tests/src/main/java/org/openhab/binding/nest/internal/wwn/handler/WWNSmokeDetectorHandlerTest.java
itests/org.openhab.binding.nest.tests/src/main/java/org/openhab/binding/nest/internal/wwn/handler/WWNStructureHandlerTest.java
itests/org.openhab.binding.nest.tests/src/main/java/org/openhab/binding/nest/internal/wwn/handler/WWNThermostatHandlerTest.java
itests/org.openhab.binding.nest.tests/src/main/java/org/openhab/binding/nest/internal/wwn/handler/WWNThingHandlerOSGiTest.java
itests/org.openhab.binding.nest.tests/src/main/java/org/openhab/binding/nest/internal/wwn/test/WWNTestAccountHandler.java
itests/org.openhab.binding.nest.tests/src/main/java/org/openhab/binding/nest/internal/wwn/test/WWNTestApiServlet.java
itests/org.openhab.binding.nest.tests/src/main/java/org/openhab/binding/nest/internal/wwn/test/WWNTestServer.java

* Fix SAT issues
* Start Jetty Server in same thread to improve stability
* Cleanup some code

[nest] Cleanup test code

---

bundles/org.openhab.binding.kostalinverter/README.md

Example code had a missing '"' in the second gen. devices.
doesn't matter that much here, but in the official openHAB site the sytax highlighting makes the mstake very promiment :-)
Signed-off-by: Markus Thur <markusthur@tutes.de>

[kostalinverterbinding] change in README.md 

---

bundles/org.openhab.voice.googlestt/pom.xml

Upgrade library and dependencies.
Splitted from #14649 .

[googlestt] Upgrade library

---

bundles/org.openhab.automation.jsscripting/README.md

This has the add-on docs consistent with the main docs.
Signed-off-by: Richard Koshak <rlkoshak@gmail.com>

[jsscripting] Standardize on `js` for SCRIPT

---

bundles/org.openhab.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/AndroidDebugBridgeDevice.java

Fixes for the screen state channel, tested on chrome cast with android 12.

[androiddebugbridge] Fix screen state channel on Android 12

---

bundles/org.openhab.voice.rustpotterks/src/main/java/org/openhab/voice/rustpotterks/internal/RustpotterKSService.java

As discussed in #14649 seems unnecessary, removed in case it causes problems.

[rustpotterks] Remove unnecesary thread sleep call

---

bundles/org.openhab.binding.mqtt.espmilighthub/src/main/java/org/openhab/binding/mqtt/espmilighthub/internal/EspMilightHubBindingConstants.java
bundles/org.openhab.binding.mqtt.espmilighthub/src/main/java/org/openhab/binding/mqtt/espmilighthub/internal/handler/EspMilightHubHandler.java

also refactor a bit so that the thing will work even if the bridge gets added and removed, etc.

[mqtt.espmilighthub] Use availability topic to set thing status

---

bundles/org.openhab.binding.deconz/README.md

Follow-up to #14622
Not complete, just more...

[deconz] Add more example things/items

---

bundles/org.openhab.binding.netatmo/README.md
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/action/RoomActions.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/NAObject.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/NAThing.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/config/HomeConfiguration.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/config/NAThingConfiguration.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/CommonInterface.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/CameraCapability.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/CapabilityMap.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/EnergyCapability.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/HomeCapability.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/PersonCapability.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/SecurityCapability.java
bundles/org.openhab.binding.netatmo/src/main/resources/OH-INF/config/config.xml
bundles/org.openhab.binding.netatmo/src/main/resources/OH-INF/i18n/netatmo.properties

This enhancement let the user configure a single home instead of two (security, energy).
While doing it, I think I solved issue #12764 - and understood the origin of this uncommon bug.
Backward compatibility is preserved.

[Netatmo] Add the capability to have a single home

---

bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/addon/addon.xml

Declaed <connection>local in addon.xml

[openwebnet] Declare connection in addon.xml

---

bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/handler/YeelightHandlerBase.java
bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/device/DeviceBase.java
bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/device/connection/WifiConnection.java

Fixing an issue with having connection active after disposing thing. This will fix https://github.com/openhab/openhab-addons/issues/14635

[Yeelight] Fix disconnect method

---

bundles/org.openhab.binding.atlona/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.benqprojector/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.epsonprojector/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.kaleidescape/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.monopriceaudio/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.nuvo/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.oppo/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.oppo/src/main/resources/OH-INF/i18n/oppo.properties
bundles/org.openhab.binding.roku/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.tivo/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.vizio/src/main/resources/OH-INF/addon/addon.xml

Declare connection type in addon.xml for bindings where I am listed as code owner.

Declare connection in multiple bindings addon.xml

---

bundles/org.openhab.binding.globalcache/README.md

Add link to macOS port of iConvert.

[globalcache] Add link to macOS iConvert GC port in docs

---

bundles/org.openhab.binding.ambientweather/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.bigassfan/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.doorbird/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.ecobee/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.globalcache/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.sleepiq/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.squeezebox/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.weathercompany/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.zoneminder/src/main/resources/OH-INF/addon/addon.xml

Add connection element to addon.xml for bindings I maintain.

Add connection element to addon.xml

---

bundles/org.openhab.binding.zway/README.md

Update the description of Z-Way Binding

[zway] Fix broken links in README

---

bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/SerialTransportAdapter.java
bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/DPTUnits.java
bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/ValueEncoder.java
bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/i18n/MockedLocaleProvider.java

cleanup.
- replace replaceAll by replace (as no regex needed)
- compare enum values with ```==``` instead ```.equals```

[knx] Code cleanup

---

bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/BoschSHCDeviceHandler.java
bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/BoschSHCHandler.java
bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/BoschHttpClient.java
bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/BridgeHandler.java
bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/LongPolling.java
bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/climatecontrol/ClimateControlHandler.java
bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/shuttercontrol/ShutterControlHandler.java
bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/discovery/ThingDiscoveryService.java
bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/serialization/GsonUtils.java
bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/serialization/LoggerExclusionStrategy.java
bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/BoschSHCSystemService.java
bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/dto/BoschSHCServiceState.java
bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/humiditylevel/dto/HumidityLevelServiceState.java
bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/roomclimatecontrol/dto/RoomClimateControlServiceState.java
bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/smokedetectorcheck/SmokeDetectorCheckState.java
bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/temperaturelevel/dto/TemperatureLevelServiceState.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/bridge/BridgeHandlerTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/bridge/dto/LongPollResultTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/services/batterylevel/BatteryLevelTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/services/dto/BoschSHCServiceStateTest.java

This commit fixes several compiler warnings as well as several Checkstyle, FindBugs, PMD and Sonar issues.
* instantiate loggers consistently
* add missing logger calls
* add chained exceptions to logger calls
* provide central Gson instance that does not serialize or deserialize loggers
* avoid catching NullPointerExceptions
* extract methods where cyclomatic complexity was too high
* remove unnecessary null check in combination with instanceof
* rename local variables that shadow fields
* add missing `@NonNull` and `@Nullable` annotations

[boschshc] Code Enhancements

---

bundles/org.openhab.binding.doorbird/README.md

Add documentation for doorbird audio sink added in #14122

[doorbird] Add audio sink information to README

---

bundles/org.openhab.binding.fsinternetradio/README.md

Added device "Technisat VIOLA 2 C IR" as an supported radio

[fsinternetradio] Add device "Technisat VIOLA 2 C IR" as an supported radio

---

bundles/org.openhab.binding.zway/README.md

Update the description of Z-Way Binding

[zway] Add a link to detailed instruction on Z-Wave.Me Support site

---

bundles/org.openhab.binding.knx/src/main/resources/OH-INF/config/channelConfig.xml
bundles/org.openhab.binding.knx/src/main/resources/OH-INF/i18n/knx.properties

Carryover from smarthomej/addons#257.
Reference: #14502
Also-by: Jan N. Klug <github@klug.nrw>

[knx] Improve config description for GAs

---

bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/LightThingHandler.java
bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/SensorThingHandler.java
bundles/org.openhab.binding.dmx/src/test/java/org/openhab/binding/dmx/internal/handler/ColorThingHandlerTest.java
bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/ValueDecoder.java
bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/ValueEncoder.java
bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/dpt/DPTTest.java
bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/ChannelStateTests.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/JSONSchemaLightTests.java
bundles/org.openhab.binding.tradfri/src/test/java/org/openhab/binding/tradfri/internal/TradfriColorTest.java
bundles/org.openhab.binding.webthing/src/test/java/org/openhab/binding/webthing/internal/link/WebthingChannelLinkTest.java

see openhab/openhab-core#3479
may be merged as separate commits without squashing

Adapt to ColorUtil changes in core

---

bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/CommonInterface.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/AlarmEventCapability.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/CameraCapability.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/HomeCapability.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/HomeSecurityThingCapability.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/PersonCapability.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/PresenceCapability.java

[Netatmo] Fix duplicate id on single home

---

bundles/org.openhab.binding.ecowatt/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.freebox/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.lgwebos/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.linky/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.netatmo/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.powermax/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.somfytahoma/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.sonyprojector/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.weatherunderground/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.voice.voicerss/src/main/resources/OH-INF/addon/addon.xml

Done for bindings I am maintaining or contributing.

Declare connection on few bindings

---

bundles/org.openhab.binding.tapocontrol/pom.xml
bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/api/TapoDeviceConnector.java
bundles/org.openhab.binding.tapocontrol/src/main/resources/OH-INF/addon/addon.xml

I guess a regression has been introduced in PR #14596.
Due to the "gap" between request, child devices were not queried, thus unknown, thus doing nothing (outlets of a powerstrip were ineffective).
Signed-off-by: Gaël L'hopital [gael@lhopital.org](mailto:gael@lhopital.org)

[Tapocontrol] Restore child device querying

---

itests/org.openhab.binding.mielecloud.tests/src/main/java/org/openhab/binding/mielecloud/internal/config/ConfigFlowTest.java
itests/org.openhab.binding.mielecloud.tests/src/main/java/org/openhab/binding/mielecloud/internal/util/AbstractConfigFlowTest.java
itests/org.openhab.binding.mielecloud.tests/src/main/java/org/openhab/binding/mielecloud/internal/util/WebsiteCrawler.java

Fix and re-enable the failing integration tests that were previously disabled in #14762.

[mielecloud] Fix failing integration tests

---

bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/RoomCapability.java

Delayed initialization of the HomeEnergyCapability

[Netatmo] Fix remaining warnings at Room startup

---

bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/dpt/DPTTest.java

Adapt tests due to openhab/openhab-core#3542.
Test is now less strict, it can be merged independently.

[knx] Adapt to ColorUtil changes in core

---

bundles/org.openhab.binding.folderwatcher/README.md
bundles/org.openhab.binding.folderwatcher/pom.xml
bundles/org.openhab.binding.folderwatcher/src/main/java/org/openhab/binding/folderwatcher/internal/FolderWatcherBindingConstants.java
bundles/org.openhab.binding.folderwatcher/src/main/java/org/openhab/binding/folderwatcher/internal/FolderWatcherHandlerFactory.java
bundles/org.openhab.binding.folderwatcher/src/main/java/org/openhab/binding/folderwatcher/internal/api/S3Actions.java
bundles/org.openhab.binding.folderwatcher/src/main/java/org/openhab/binding/folderwatcher/internal/api/auth/AWS4SignerBase.java
bundles/org.openhab.binding.folderwatcher/src/main/java/org/openhab/binding/folderwatcher/internal/api/auth/AWS4SignerForAuthorizationHeader.java
bundles/org.openhab.binding.folderwatcher/src/main/java/org/openhab/binding/folderwatcher/internal/api/util/BinaryUtils.java
bundles/org.openhab.binding.folderwatcher/src/main/java/org/openhab/binding/folderwatcher/internal/api/util/HttpUtils.java
bundles/org.openhab.binding.folderwatcher/src/main/java/org/openhab/binding/folderwatcher/internal/config/S3BucketWatcherConfiguration.java
bundles/org.openhab.binding.folderwatcher/src/main/java/org/openhab/binding/folderwatcher/internal/handler/FtpFolderWatcherHandler.java
bundles/org.openhab.binding.folderwatcher/src/main/java/org/openhab/binding/folderwatcher/internal/handler/LocalFolderWatcherHandler.java
bundles/org.openhab.binding.folderwatcher/src/main/java/org/openhab/binding/folderwatcher/internal/handler/S3BucketWatcherHandler.java
bundles/org.openhab.binding.folderwatcher/src/main/resources/OH-INF/i18n/folderwatcher.properties
bundles/org.openhab.binding.folderwatcher/src/main/resources/OH-INF/thing/thing-types.xml

Added support for monitoring of AWS S3 buckets

[Folderwatcher] AWS S3 buckets monitoring support

---

bundles/org.openhab.binding.bluetooth.radoneye/src/main/java/org/openhab/binding/bluetooth/radoneye/internal/AbstractRadoneyeHandler.java

These modifiers are out of order with the JLS suggestions.

[bluetooth.radoneye] Fix modifier order

---

bundles/org.openhab.binding.vesync/src/main/java/org/openhab/binding/vesync/internal/handlers/VeSyncDeviceMetadata.java

These modifiers are out of order with the JLS suggestions.

[vesync] Fix modifier order

---

bundles/org.openhab.binding.automower/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.nikobus/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.regoheatpump/src/main/resources/OH-INF/addon/addon.xml

Adds connections details for add-ons I maintain and/or use.

Add more connection details to add-ons

---

bundles/org.openhab.transform.map/src/main/java/org/openhab/transform/map/internal/MapTransformationService.java
bundles/org.openhab.transform.scale/src/main/java/org/openhab/transform/scale/internal/ScaleTransformationService.java

Fixes #14823 
The wrong key was used in the `cachedTransformations` map. Instead of the correct localized UID from the registry the provided transformation function was used.

[map][scale] Fix localization

---

bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/IndegoController.java

[boschindego] Fix Java 11 backport

---

bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/TeslaChannelSelectorProxy.java
bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaAccountHandler.java
bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaSSOHandler.java
bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaVehicleHandler.java

[tesla] Cleanup code

---

bundles/org.openhab.binding.knx/doc/dpt.txt

Carryover from smarthomej/addons#107.
Update to match current implementation in KNX binding and Calimero ### 2.5.1.
Also-by: Jan N. Klug <github@klug.nrw>
Refs: #14502

[knx] Add list of DPTs documenting implementation status

---

bundles/org.openhab.binding.elroconnects/src/main/resources/OH-INF/addon/addon.xml

Related to openhab/openhab-core#3563

[elroconnect] Redeclare addon connection

---

bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/LightThingHandler.java
bundles/org.openhab.binding.deconz/src/test/resources/org/openhab/binding/deconz/windowcovering.json

Fixes #14826
if the REST interface from deconz provides a 'lift' value to show the current position of the roller shutter, it will be used. Otherwise, the 'bri' value will be used.

[deconz] Update the roller shutter status

---

bundles/org.openhab.binding.remoteopenhab/src/main/resources/OH-INF/addon/addon.xml

See openhab/openhab-core#3563 and https://github.com/openhab/openhab-core/issues/3555#issuecomment-1513488233 and https://github.com/openhab/openhab-addons/pull/14813#discussion_r1167470570

[remoteopenhab] Declare connection

---

bundles/org.openhab.binding.astro/src/main/resources/OH-INF/addon/addon.xml

[astro] Redeclare connection

---

bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/addon/addon.xml

See openhab/openhab-core#3563 and https://github.com/openhab/openhab-core/issues/3555#issuecomment-1513488233

[sonos] Redeclare connection

---

bundles/org.openhab.transform.vat/src/main/resources/OH-INF/addon/addon.xml

[transform.vat] Declare connection

---

bundles/org.openhab.binding.insteon/src/main/resources/OH-INF/addon/addon.xml

[insteon] Add connection details

---

bundles/org.openhab.transform.rollershutterposition/README.md

[rollershutterposition] Correct documentation

---

bundles/org.openhab.binding.robonect/src/main/resources/OH-INF/config/config.xml
bundles/org.openhab.binding.robonect/src/main/resources/OH-INF/i18n/robonect.properties

* Add allowed pattern to description
* Increase allowed duration to 12h - thats what the web gui allows
fixes #6142

[robonect] Improve job type configuration

---

bundles/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/AirQualityException.java
bundles/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/api/ApiBridge.java
bundles/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/api/Appreciation.java
bundles/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/api/dto/AirQualityData.java
bundles/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/api/dto/AirQualityResponse.java
bundles/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/api/dto/ResponseRoot.java
bundles/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/discovery/AirQualityDiscoveryService.java
bundles/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/handler/AirQualityBridgeHandler.java
bundles/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/handler/AirQualityStationHandler.java

Raised by #14601 
Also removed some dead code.

[AirQuality] Enhance API error handling

---

bundles/org.openhab.transform.exec/src/main/java/org/openhab/transform/exec/internal/ExecTransformationWhitelistWatchService.java

Reported on the german openHAB forum.

[transform.exec] Fix service whitelisting

---

bundles/org.openhab.persistence.jdbc/pom.xml

Complete #14874, unfortunately I missed a file when staging Git changes.

[jdbc] Upgrade MySQL Connector/J to 8.0.33

---

bundles/org.openhab.binding.ventaair/src/main/resources/OH-INF/thing/channels.xml

[ventaair] Fix typo Dimenionsless in channel definition

---

bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.denonmarantz/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.evcc/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.heos/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.irobot/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.livisismarthome/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.pioneeravr/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.pushbullet/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.pushsafer/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.samsungtv/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.twitter/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.yamahamusiccast/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.yamahareceiver/src/main/resources/OH-INF/addon/addon.xml

Declare addon connection for a few bindings

---

bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/dto/Color.java
bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewRepeaterHandler.java

Deprecated by openhab/openhab-core#3479

[hdpowerview] Refactor usage of deprecated HSBType.getRGB

---

bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/SerialTransportAdapter.java
bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/ValueDecoder.java
bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/dpt/DPTTest.java

Correct handling of Y parameter for DPT 242.600.
Add back to back tests for DPT 232.600 and 242.600, testing color conversion from raw bytes to HSB and back to Calimero color representation as String.

[knx] Fix decoding of DPT 242.600 and add tests

---

bundles/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/internal/SenseBoxAPIConnection.java

- Fix NPE after parsing invaid data
```
2023-04-25 11:20:54.645 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.NullPointerException: Cannot invoke "org.openhab.binding.sensebox.internal.dto.SenseBoxData.setStatus(org.openhab.core.thing.ThingStatus)" because "parsedData" is null
at org.openhab.binding.sensebox.internal.SenseBoxAPIConnection.reallyFetchDataFromServer(SenseBoxAPIConnection.java:75) ~[?:?]
at org.openhab.binding.sensebox.internal.handler.SenseBoxHandler.lambda$0(SenseBoxHandler.java:106) ~[?:?]
at org.openhab.core.cache.ExpiringCache.refreshValue(ExpiringCache.java:101) ~[?:?]
at org.openhab.core.cache.ExpiringCache.getValue(ExpiringCache.java:72) ~[?:?]
at org.openhab.core.cache.ExpiringCacheMap.get(ExpiringCacheMap.jav …
```

[sensebox] Fix NPE after parsing invalid data

---

bundles/org.openhab.binding.feican/src/main/java/org/openhab/binding/feican/internal/Commands.java

Use new class ```ColorUtil``` which has recently been added to core in openhab/openhab-core#3479.
```convertColorPercentToByte``` is not longer needed. It has been using a statement ```...divide(BigDecimal.valueOf(100), 2, RoundingMode.HALF_UP).byteValue();``` which can be found in several bindings and but probably does not exactly behave as intended. It rounds the BigDecimal with behavior HALF_UP, keeping *2* scales behind the decimal point and then ignores the scales by using byteValue. If HALF_UP is intended, scales should be set to 0.

[feican] Use new core class ColorUtil for RGB conversion

---

bundles/org.openhab.binding.hue/src/main/feature/feature.xml
bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/HueBindingConstants.java
bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/discovery/HueBridgeMDNSDiscoveryParticipant.java
bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/discovery/HueBridgeUPNPDiscoveryParticipant.java
itests/org.openhab.binding.hue.tests/itest.bndrun

[hue] Restore UPnP discovery for old bridges

---

bundles/org.openhab.binding.folderwatcher/src/main/java/org/openhab/binding/folderwatcher/internal/api/S3Actions.java
bundles/org.openhab.binding.folderwatcher/src/main/java/org/openhab/binding/folderwatcher/internal/handler/S3BucketWatcherHandler.java

Fixing S3 thing status in case of connectivity issues that happened after thing entered ONLINE status. 
This will also remove exception in case bucket is empty.

[Folderwatcher] AWS S3 bucket thing status fix

---

bundles/org.openhab.binding.anthem/README.md
bundles/org.openhab.binding.anthem/src/main/java/org/openhab/binding/anthem/internal/AnthemBindingConstants.java
bundles/org.openhab.binding.anthem/src/main/java/org/openhab/binding/anthem/internal/handler/AnthemCommand.java
bundles/org.openhab.binding.anthem/src/main/java/org/openhab/binding/anthem/internal/handler/AnthemCommandParser.java
bundles/org.openhab.binding.anthem/src/main/java/org/openhab/binding/anthem/internal/handler/AnthemHandler.java
bundles/org.openhab.binding.anthem/src/main/java/org/openhab/binding/anthem/internal/handler/AnthemUpdate.java
bundles/org.openhab.binding.anthem/src/main/java/org/openhab/binding/anthem/internal/handler/PropertyUpdate.java
bundles/org.openhab.binding.anthem/src/main/java/org/openhab/binding/anthem/internal/handler/StateUpdate.java
bundles/org.openhab.binding.anthem/src/main/resources/OH-INF/i18n/anthem.properties
bundles/org.openhab.binding.anthem/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.anthem/src/main/resources/OH-INF/update/instructions.xml
bundles/org.openhab.binding.anthem/src/test/java/org/openhab/binding/anthem/internal/handler/AnthemCommandParserTest.java

Adds a new channel for sending custom commands.
Refactors the parser to eliminate handler callbacks.
Adds parser tests.

[anthem] Add channel, refactor parser, add tests

---

bundles/org.openhab.binding.groupepsa/src/main/java/org/openhab/binding/groupepsa/internal/bridge/GroupePSABridgeHandler.java

[groupepsa] Remove the access token when the thing is removed

---

bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/HomeConnectBridgeHandler.java

[homeconnect] Remove the access token when the thing is removed

---

bundles/org.openhab.binding.ecowatt/src/main/java/org/openhab/binding/ecowatt/internal/handler/EcowattHandler.java
bundles/org.openhab.binding.ecowatt/src/main/java/org/openhab/binding/ecowatt/internal/restapi/EcowattRestApi.java

[ecowatt] Remove the access token when the thing is removed

---

bundles/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/handler/MyQAccountHandler.java

[myq] Remove the access token when the thing is removed

---

bundles/org.openhab.binding.livisismarthome/src/main/java/org/openhab/binding/livisismarthome/internal/handler/LivisiBridgeHandler.java

[livisismarthome] Remove the access token when the thing is removed

---

bundles/org.openhab.binding.hydrawise/src/main/java/org/openhab/binding/hydrawise/internal/handler/HydrawiseAccountHandler.java

[hydrawise] Remove the access token when the thing is removed

---

bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/servlet/CameraServlet.java

Fixing self reported issue [14908](https://github.com/openhab/openhab-addons/issues/14908).

[ipcamera] Fix orphan ffmpeg process after stopping stream URL

---

bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/handler/EcobeeAccountBridgeHandler.java

[ecobee] Delete oauth service and access token when thing removed

---

bundles/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/handler/MyQAccountHandler.java

[myq] Small change in handleRemoval

---

bundles/org.openhab.binding.hydrawise/src/main/java/org/openhab/binding/hydrawise/internal/handler/HydrawiseAccountHandler.java

[hydrawise] Small change in handleRemoval

---

bundles/org.openhab.binding.groupepsa/src/main/java/org/openhab/binding/groupepsa/internal/bridge/GroupePSABridgeHandler.java

[groupepsa] Small change in handleRemoval

---

bundles/org.openhab.binding.ecowatt/src/main/java/org/openhab/binding/ecowatt/internal/handler/EcowattHandler.java
bundles/org.openhab.binding.ecowatt/src/main/java/org/openhab/binding/ecowatt/internal/restapi/EcowattRestApi.java

[ecowatt] Change in handleRemoval

---

bundles/org.openhab.binding.automower/src/main/java/org/openhab/binding/automower/internal/bridge/AutomowerBridgeHandler.java

[automower] Remove the access token when the thing is removed

---

bundles/org.openhab.binding.webexteams/src/main/java/org/openhab/binding/webexteams/internal/WebexTeamsHandler.java

[webexteams] Remove the access token when the thing is removed
