bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/handler/IpCameraHandler.java, bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/onvif/OnvifConnection.java, bundles/org.openhab.binding.ipcamera/src/main/resources/OH-INF/thing/thing-types.xml
+ Fixes multiple bugs that stop cameras from successfully re-connecting to ONVIF if the connection fails due to connection dropouts or a cameras automatic reboot etc.
+ Allows more than 9 cameras on Hikvision NVR's as per a request on the forum to increase the limit.
+ Fix bug where ffmpeg is still tried to be used, after the cameras settings are edited to stop using this feature.
+ Fix bug to allow all camera types to choose to use ffmpeg for snapshot creating to make further testing easier, or a user on the forum has an ONVIF camera that has no snapshot url.
Jar can be downloaded from:
Signed-off-by: Matthew …
=> [ipcamera] Fix ONVIF fails to reconnect

bundles/org.openhab.binding.konnected/src/main/java/org/openhab/binding/konnected/internal/handler/KonnectedHandler.java
Before this change the binding would only send the zone configuration to the panel if the channel for that zone was linked to an item. This would cause the settings pushed on the creation of a new channel to not contain the new channel. Settings are not pushed when channels are linked. The result is that zones may or may not be correctly provisioned.
This change remove the check to see if a channel is linked before provisioning the zone.
The diff looks bigger than what it is. It's mostly just changing the indentation after removing the conditional.
=> [Konnected] Configure zone on panel even if the channel is not yet linked

bundles/org.openhab.binding.radiothermostat/src/main/java/org/openhab/binding/radiothermostat/internal/handler/RadioThermostatHandler.java
It could be that my thermostat is beginning to fail since it has started randomly returning -1 instead of the actual temperature. This change will cause a polling update with invalid data to be ignored so it will not update the channels. As a result, the temperature graphs will no longer look like this:
=> [radiothermostat] Ignore updates if thermostat data is invalid

bundles/org.openhab.binding.miio/src/main/resources/database/cgllc.airmonitor.s1.json
[miio] Qingping Air Monitor (cgllc.airmonitor.s1) support is broken #13258
1.  Custom refresh command for "battery" was defined . The device with "4.1.8_9999" firmware version does not allowed to obtain this information by this way which prevents to obtain other values. The solution should work for both old firmware (the battery information would be requested as before) and it does not prevent the device with new firmware from sending other values (I checked it).
fix #13258
=> [miio] Qingping Air Monitor (cgllc.airmonitor.s1) support is broken

bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Sensor.java, bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/SensorTests.java
see reference in code comment, but a measurement sensor is assumed to be numeric, even if it doesn't have a unit
=> [mqtt.homeassistant] sensors with a state_class are numeric

bundles/org.openhab.binding.mercedesme/README.md
Typo in readme leads to 
- unrecognized configuration parameter and
- custom IP address cannot be set manually
This error wasn't recognized because IP autodetection seems to work in most of the cases.
Observed by [Community](https://community.openhab.org/t/mercedes-me-binding/136852/47)
=> [mercedesme] Fix typo in readme:  callbackIP config parameter 

bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api1/Shelly1CoapServer.java, bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/handler/TradfriGatewayHandler.java, itests/org.openhab.binding.tradfri.tests/itest.bndrun, itests/org.openhab.binding.tradfri.tests/src/main/java/org/openhab/binding/tradfri/internal/handler/TradfriHandlerOSGiTest.java
* Fixes deprecated API usages
* Resolves itest runbundles
Depends on openhab/openhab-core#3085
=> Update Shelly and Tradfri bindings for upgrade to Californium 2.7.3

bundles/org.openhab.binding.openweathermap/README.md, bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/config/OpenWeatherMapAPIConfiguration.java, bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/connection/OpenWeatherMapConnection.java, bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/config/config.xml, bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/i18n/openweathermap.properties
Fix for OpenWeatherMap OneCall API version 3.0
https://community.openhab.org/t/openweathermap-onecall-invalid-api-key/138296/14
#13314
=> [openweathermap] onecall api version - property for setting API version to use.

bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/PulseAudioAudioSink.java, bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/PulseAudioAudioSource.java, bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/PulseaudioSimpleProtocolStream.java, bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/cli/Parser.java, bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/handler/PulseaudioHandler.java
Bug description: 
When the pulseaudio server is shutdown and relaunched, the socket is dead. But the audiosink connection doesn't properly reset the next time it is needed. The isIdle boolean prevents this disconnection/reconnection by checking if it's in use before effectively disconnecting (and of course it's in use, because we are trying to use it when we see that the connection is broken...)
Additionnally, isIdle is not in a try catch block for the pulseaudio sink : so exception within an operation doesn't free the boolean.
Actually, isIdle seems not even relevant : we should always honnor the disconnection request, even if an operation is running (disconnection requests occur when we get I/O exception, or when shutting down the bridge/thing).
This PR remove the isIdle boolean. …
=> [pulseaudio] Apply real disconnection when needed

bundles/org.openhab.binding.radiothermostat/src/main/java/org/openhab/binding/radiothermostat/internal/handler/RadioThermostatHandler.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/handler/VeluxBridgeHandler.java
Resolves #13383
As reported in issue #13383 the bridge thing does not indicate offline status when when the communication fails.
In this PR the bridge thing status will change to offline when the communication fails, and return to online when it is restored.
=> [velux] Bridge status shows offline when communication fails

bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitOHItemProxy.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitTaggedItem.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/AbstractHomekitPositionAccessoryImpl.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/BooleanItemReader.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitCharacteristicFactory.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitGarageDoorOpenerImpl.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitLightbulbImpl.java
this is a theme, and I've extracted a helper method and applied it to several
other locations as well
example, I have a double-sliding door, with two contact sensors
in the alarm system, defined as:
```
Group:Contact:AND(CLOSED,OPEN) DeckDoor_Contact "Deck Door [%s]" <door> (gExteriorDoors, gWarningVisibility_Contact, gDoor, lMainFloor, gInflux) { homekit="ContactSensor" [instance=2] }
Contact DeckNDoor_Contact "Deck Door North" <door> (gInflux, DeckDoor_Contact, gGreatContacts) { channel="dscalarm:zone:46c52f35:zone11:zone_status" }
Switch DeckNDoor_Tamper "Deck Door North Tamper [%s]" <warning> (gTamper, gWarningVisibility_Switch) { channel="dscalarm:zone:46c52f35:zone11:zone_tamper" }
Contact DeckSDoor_Contact "Deck Door South" <door> (gInflux, DeckDoor_Contact, gGreatContacts) { …
```
=> [homekit] allow group items of the correct type anywhere that type is needed

bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/ColorValue.java, bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/ChannelStateTests.java
Range is 0..255, not 0..250.
rgb -> hsv -> rgb still isn't perfect, but it's better. In particular, I found this when using HSBType.BLUE in a test, and it was coming out as 0,0,250 in RGB. It now comes out as a proper 0,0,255.
=> [mqtt.generic] fix range of RGB values

bundles/org.openhab.binding.remoteopenhab/src/main/java/org/openhab/binding/remoteopenhab/internal/rest/RemoteopenhabRestClient.java
=> [remoteopenhab] Optimize filtering of ALIVE events

bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/api/TapoCloudConnector.java, bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/constants/TapoBindingSettings.java
When authenticating to the TP-Link cloud, the TapoCloudConnector uses a hard-coded UUID as a client identifier.  All client share the same token, therefore the API server believes the same client is repeatetly authenticating, and blocks it with an "API Rate limit exceeded (-20004)" error.
This PR removes the static terminal UUID and replaces it with a random UUID generated at login.  It has been discussed at https://community.openhab.org/t/tapocontrol-control-tapo-smart-wifi-devices-with-openhab/118389/201 and has been running on my OpenHAB server for ~12h without issue.
A compiled .jar is available at https://github.com/poggs/openhab-addons/releases/tag/fix-13465
=> [tapobridge] Fix API Rate limit exceeded error

bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/JRubyScriptEngineFactory.java
pass the actual class objects through, and post-process in Ruby, to avoid the rescue nil -- and by extension, any issues with visibility into private objects from JRuby.
=> [jrubyscripting] clean up assignment of class objects

bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/action/RoomActions.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/ApiBridgeHandler.java
Correcting issue by late loading of the capability.
Resolves #13403 
=> [netatmo] Room-Thing offline after restart

bundles/org.openhab.binding.nuki/README.md, bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/handler/AbstractNukiDeviceHandler.java
This fixes #13088:
When migrating from old version of binding, nukiId stored as hexadecimal number must be converted to decimal format used in newer versions. To detect whether the current nukiId is decimal or hexadecimal the binding used pattern which assumed all hexadecimal nukiIds are exactly 8 hex digits (A-F,0-9) long.
This turned out not to be true as some users reported their nukiId being only 7 hex digits long and it's corresponding decimal value being 8 digits, which triggered migration and the decimal nukiId was incorrectly converted as a hex number to decimal again, resulting in binding using invalid nukiId and not working.
Since we can't really tell with 100% certainty whether the nukiId is hexadecimal or not (it can be either hexadecimal number wihtout any A-F digits or just …
=> [nuki] Fixed nukiId migration for devices with shorter nukiId (#13088)

bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/Ffmpeg.java, bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/HttpOnlyHandler.java, bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/handler/IpCameraHandler.java, bundles/org.openhab.binding.ipcamera/src/main/resources/OH-INF/thing/thing-types.xml
These changes will auto re-start the FFmpeg based audio and motion alarms which previously would not start if the camera re-connected to wifi, camera rebooted, or the thing was paused and un-paused. Now the binding will start the alarms back to what they were previously set to.
Closes #11672
Jar can be downloaded from:
=> [ipcamera] FFmpeg based alarms will now auto restart if stopped

bundles/org.openhab.binding.luxtronikheatpump/README.md, bundles/org.openhab.binding.luxtronikheatpump/src/main/java/org/openhab/binding/luxtronikheatpump/internal/ChannelUpdaterJob.java, bundles/org.openhab.binding.luxtronikheatpump/src/main/java/org/openhab/binding/luxtronikheatpump/internal/LuxtronikHeatpumpBindingConstants.java, bundles/org.openhab.binding.luxtronikheatpump/src/main/java/org/openhab/binding/luxtronikheatpump/internal/discovery/LuxtronikHeatpumpDiscovery.java
This PR adds an discovery class to the LuxtronikHeatmap binding.
As such heat pumps seem not to be discoverable using upnp or mdns (at least not the one I own), the discovery currently looks through the IPs in the current IPv4 subnet and tries connecting to the socket using port 8889 and 8888.
If the answer can be parsed the heat pump will be addable as thing using the heat pumps type as name.
Most parts of the discovery are based on / copied from the detection of `LGHomBot`, which is doing similar steps for discovery.
=> [LuxtronikHeatpump] Adds discovery service

bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcBaseDAO.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcDerbyDAO.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcH2DAO.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcHsqldbDAO.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcMariadbDAO.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcMysqlDAO.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcPostgresqlDAO.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcSqliteDAO.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcTimescaledbDAO.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcConfiguration.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcMapper.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/utils/DbMetaData.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/utils/StringUtilsExt.java, bundles/org.openhab.persistence.jdbc/src/test/java/org/openhab/persistence/jdbc/db/JdbcBaseDAOTest.java
Some reviewer notes:
- Where previously `NullPointerException` could be thrown, this has been replaced by explicit `UnsupportedOperationException`.
- To limit scope I have left things which could have been refactored further. For example, I have left logging of "filter='true'" since filter is now non-null.
- I couldn't figure out how to work around the hamcrest matcher generating _"Unsafe null type conversion (type annotations): The value of type 'org.hamcrest.Matcher<org.openhab.core.types.@NonNull State>' is made accessible using the less-annotated type 'org.hamcrest.Matcher<? super org.openhab.core.types"_ from `assertThat`, so switched to `assertEquals` although I prefer the constraint-based assert model.
Fixes #13428
=> [jdbc] Fix warnings and apply null annotations

bundles/org.openhab.binding.ecowatt/src/main/resources/OH-INF/i18n/ecowatt.properties, bundles/org.openhab.binding.ecowatt/src/main/resources/OH-INF/thing/thing-types.xml
=> [ecowatt] Fix a typo in a channel description

bundles/org.openhab.binding.nuki/README.md, bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/NukiHandlerFactory.java, bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/handler/AbstractNukiDeviceHandler.java, bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/handler/NukiOpenerHandler.java, bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/handler/NukiSmartLockHandler.java
Disabled migration warning for read-only things (created from textual config) so that users can use hexadecimal nukiIds in .things files.
Added documentation for all configuration parameters (not only for those editable in UI) and updated textual configuration example.
=> [nuki] Disabled warning for things created from textual config

bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/cache/UniFiControllerCache.java, bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/handler/UniFiPoePortThingHandler.java, bundles/org.openhab.binding.unifi/src/main/resources/OH-INF/i18n/unifi.properties
*  Fix bug to detect PoE ports when first port is not PoE port. The binding assumed either all ports or no ports were PoE, and asssumed if port 0 was not PoE none was PoE. However, some switches have ports starting at port 5 to be PoE. Therefor changed code to just test each port if it is PoE.
* Set PoE thing offline if no data could be found . This would better reflect the PoE thing status if there is a problem with either the data from the api or a configuration problem (like invalid port number).
=> [unifi] Detect all PoE ports, and set PoE thing offline if no data could be found

bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudClient.java
this change is to address the following issue
https://github.com/openhab/openhab-addons/issues/13209
=> [openhabcloud] sleepSocketIO(long delay) halts entire io.socket thread #13210

bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcBaseDAO.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcDerbyDAO.java, bundles/org.openhab.persistence.jdbc/src/test/java/org/openhab/persistence/jdbc/db/JdbcBaseDAOTest.java
Minor refactoring:
- Optimize datetime conversions by avoiding multiple steps, for example `LocalDateTime` -> `Instant` -> epoch -> `Instant` -> `ZonedDateTime`. This will now be converted directly from `LocalDateTime` to `ZonedDateTime`.
- Eliminate redundant method after this.
- Introduce tests for all supported types.
Based on findings after #13382 and #13425.
=> [jdbc] Consolidate and optimize datetime conversions

bundles/org.openhab.io.homekit/README.md
Remove the wrong naming „binding“ in installation section
=> [homekit] small correction in README

bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/AbstractMQTTThingHandler.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/handler/HomeAssistantThingHandler.java
HASS registers availability topics before calling start(), so the AbstractMQTTThingHandler was never subscribing/starting the availability channel(s). So do so in start() of the base class.
I checked other implementations, and either they already handle re-registering availabilityTopics in their start() (GenericMQTTThingHandler), or they don't use availabilityTopics at all from the base class and manage it themselves (Homie).
Note that this shows up as newly-added HASS things not having a problem (because the components aren't discovered until after the ThingHandler is started), but if you restart OpenHAB or disable/enable the thing, the channels (and components) are cached, thus how availabilityTopics are known before starting.
=> [mqtt.homeassistant] ensure availability topics get subscribed

bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/action/NetworkActions.java
Add static methods in actions to make them available in DSL rules.
Failed with `'sendWakeOnLanPacketViaMac' is not a member of 'org.openhab.core.thing.binding.ThingActions'`.
Discussed here: https://community.openhab.org/t/solved-wake-on-lan-in-oh3-not-working-not-a-member-of-org-openhab-core-thing-binding-thingactions/132476/9
=> [network] Fix wake-on-lan functions in DSL rules

bundles/org.openhab.persistence.jpa/README.md, bundles/org.openhab.persistence.jpa/pom.xml, bundles/org.openhab.persistence.jpa/src/main/java/org/openhab/persistence/jpa/internal/JpaConfiguration.java, bundles/org.openhab.persistence.jpa/src/main/java/org/openhab/persistence/jpa/internal/JpaHistoricItem.java, bundles/org.openhab.persistence.jpa/src/main/java/org/openhab/persistence/jpa/internal/JpaPersistenceService.java, bundles/org.openhab.persistence.jpa/src/main/java/org/openhab/persistence/jpa/internal/StateHelper.java, bundles/org.openhab.persistence.jpa/src/main/java/org/openhab/persistence/jpa/internal/model/JpaPersistentItem.java, bundles/org.openhab.persistence.jpa/src/main/java/org/openhab/persistence/jpa/internal/package-info.java, bundles/org.openhab.persistence.jpa/src/main/resources/OH-INF/config/config.xml, bundles/org.openhab.persistence.jpa/src/main/resources/OH-INF/i18n/jpa.properties
* Adds a dynamic package import so JDBC drivers on the classpath can be used
* Upgrades OpenJPA from 2.4.0 to 3.2.2
* Upgrades Derby JDBC driver from 10.11.1.1 to 10.16.1.1
* Adds config.xml and ConfigurableService annotation so add-on can be configured using the UI
* Adds null annotations on all classes
* Prevent NPEs and some code cleanup
See also:
* https://openjpa.apache.org/builds/3.2.2/apache-openjpa/RELEASE-NOTES.html
* https://community.openhab.org/t/jpa-with-mysql-or-mariadb/138679
Fixes #13375
=> [jpa] Add dynamic import, upgrade dependencies, add UI config

bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/handler/IpCameraHandler.java, bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/servlet/CameraServlet.java
Fixes a bug reported on the forum here:
https://community.openhab.org/t/ipcamera-new-ip-camera-binding/42771/2786
Fixes for these bugs:
+ ipcamera.mjpeg won't open multiples when the port for the cameras stream is not 80
+ All in use mjpeg streams stop when the camera is offline and a new stream is opened.
+ Removes a wrong WARN for generic cameras that were getting an ONVIF error when restarting.
Jar can be downloaded from:
=> [ipcamera] Fix ipcamera.mjpeg won't open multiples when port not 80

bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitTaggedItem.java
I.e. if it's set from a Ruby script
=> [homekit] Allow Long type in configuration for numbers

bundles/org.openhab.binding.caddx/src/main/java/org/openhab/binding/caddx/internal/handler/CaddxBridgeHandler.java
Signed-off-by: Georgios Moutsos <georgios.moutsos@gmail.com>
After a binding restart the things could not be found in the Hashmap because the keys were BigDecimal.
The keys were added in the hasmap with a decimal place e.g.: 1.0
BigDecimal.equals checks for the value and the precision. The result is that 1 <> 1.0 and the Hashmap lookups failed.
=> [caddx] Correct status initialization of the things after a restart

bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitTaggedItem.java
this helps to auto-configure if the binding is providing the necessary info
metadata config still overrides
=> [homekit] get min/max/step values from state description if possible

bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/EaseeBindingConstants.java, bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/model/CustomResponseTransformer.java
This bug was reported by the community.
https://community.openhab.org/t/easee-binding/135492/58
The binding tries to parse a decimal value as integer but fails as it should be parsed as double instead.
=> [easee] Fix number conversion error

bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/AbstractKNXClient.java, bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/factory/KNXHandlerFactory.java, bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/AbstractKNXThingHandler.java, bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/IPBridgeThingHandler.java, bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/i18n/KNXTranslationProvider.java, bundles/org.openhab.binding.knx/src/main/resources/OH-INF/i18n/knx.properties, bundles/org.openhab.binding.knx/src/main/resources/OH-INF/i18n/knx_de.properties, bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/i18n/KNXTranslationProviderTest.java, bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/i18n/MockedLocaleProvider.java, bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/i18n/MockedTranslationProvider.java
- introduce localization of error messages
- add new strings for common exceptions
- provide helper functions for translation
- add test cases
=> [knx] Improve localization

bundles/org.openhab.binding.tibber/README.md, bundles/org.openhab.binding.tibber/src/main/java/org/openhab/binding/tibber/internal/TibberBindingConstants.java, bundles/org.openhab.binding.tibber/src/main/java/org/openhab/binding/tibber/internal/handler/TibberHandler.java, bundles/org.openhab.binding.tibber/src/main/java/org/openhab/binding/tibber/internal/handler/TibberPriceConsumptionHandler.java, bundles/org.openhab.binding.tibber/src/main/resources/OH-INF/i18n/tibber.properties, bundles/org.openhab.binding.tibber/src/main/resources/OH-INF/thing/thing-types.xml
Allows users to build rules based on tomorrow's electricity cost.
Should be rewritten if https://github.com/openhab/openhab-core/pull/3000 is accepted in one or another form some time in the future. Until then, this PR helps.
=> [tibber] Add channel for tomorrows prices and timestamps as JSON array

bundles/org.openhab.binding.benqprojector/src/main/java/org/openhab/binding/benqprojector/internal/BenqProjectorDevice.java
Fixes very minor issue by catching the NumberFormatException that is thrown if queryInt() receives a non-numeric response from the projector. I have seen this very rarely, but when it occurs (due to noisy serial line, cosmic rays, buggy projector firmware, etc.) a warning is logged by updateChannelState(). With the change the NumberFormatException will be caught and logged to the debug log instead.
=> [benqprojector] Log invalid number when expecting numeric response from projector

bundles/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/internal/EpsonProjectorDevice.java
Fixes same issue as #13549 but in the epsonprojector binding.
=> [epsonprojector] Log invalid number when expecting numeric response from projector

bundles/org.openhab.binding.gce/src/main/java/org/openhab/binding/gce/internal/GCEBindingConstants.java, bundles/org.openhab.binding.gce/src/main/java/org/openhab/binding/gce/internal/handler/Ipx800DeviceConnector.java, bundles/org.openhab.binding.gce/src/main/java/org/openhab/binding/gce/internal/handler/Ipx800v3Handler.java, bundles/org.openhab.binding.gce/src/main/java/org/openhab/binding/gce/internal/model/M2MMessageParser.java, bundles/org.openhab.binding.gce/src/main/java/org/openhab/binding/gce/internal/model/StatusFileInterpreter.java
The linkChannel and unlinkChannel methods are not called for file based items linked to channels.
This lead the binding to be unreactive to input channels.
Some code enhancement :
Check if channel is linked before sending updates.
Removed as much usage to @NonNullByDefault({}) and @Nullable than possible.
=> [gce] File based items are not updated

bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/api/WledApiV0110.java
These changes fix a reported issue where the wrong preset or playlist loads.
closes #13249
A working JAR can be downloaded here:
https://openhab.jfrog.io/artifactory/libs-pullrequest-local/org/openhab/addons/bundles/org.openhab.binding.wled/3.4.0-SNAPSHOT/org.openhab.binding.wled-3.4.0-SNAPSHOT.jar
=> [wled] Fix presets and playlists won't load the correct position.

bundles/org.openhab.binding.tibber/src/main/java/org/openhab/binding/tibber/internal/handler/TibberHandler.java
Bug fix for websocket reconnect after Tibber server failure.
Closes #13417.
Signed-off-by: kjoglum <stiankj@online.no>
=> [tibber] Fix Websocket reconnect after server failure

bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/handler/NuvoHandler.java
Address bug from MR that added NuvoNet source capability to OH (#12042). Fixes errors that occur if the binding processes NuvoNet events intended for NuvoNet sources not handled by openHAB.
=> [nuvo] Ignore NuvoNet events for sources not managed by openHAB

bundles/org.openhab.automation.jsscripting/README.md, bundles/org.openhab.automation.jsscripting/pom.xml
Fixes #13563.
@jlaur Maybe you could review?
=> [jsscripting] Upgrade openhab-js to 2.0.4

bundles/org.openhab.binding.netatmo/README.md, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/data/ModuleType.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/console/NetatmoCommandExtension.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/discovery/NetatmoDiscoveryService.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/ApiBridgeHandler.java
=> [netatmo] Console command to show all devices/modules ids

bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/Debouncer.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitChangeListener.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitImpl.java
If you have many instances, it can take a while. So stop all the instances in parallel. Also, fix a race condition where the update debouncer might get called again after being stopped, because the change listener was deregistered _after_ the debouncer was stopped.
=> [homekit] improve bundle deactivation time

bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/database/ShadeCapabilitiesDatabase.java
Added support for yet another shade variety.
=> [hdpowerview] Support for Duette and Applause Skylift shades

bundles/org.openhab.io.homekit/README.md, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitTaggedItem.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitCharacteristicFactory.java
allow Number or Dimmer items, and mired or Kelvin units.
Dependent on https://github.com/openhab/openhab-core/pull/3108 and https://github.com/hap-java/HAP-Java/pull/167
=> [homekit] increase flexibility of ColorTemperature

bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueBridgeHandler.java
After saving bridge configuration and reinitializing the bridge, all dynamic properties (serial number, firmware version etc.) were lost:
Related to #13586
=> [hue] Reinitialize bridge properties after configuration change

bundles/org.openhab.binding.meater/README.md, bundles/org.openhab.binding.meater/src/main/java/org/openhab/binding/meater/internal/MeaterBindingConstants.java, bundles/org.openhab.binding.meater/src/main/java/org/openhab/binding/meater/internal/console/MeaterCommandExtension.java
Example session:
```
openhab> openhab:meater showIds
API bridge: MEATER Cloud REST API
- ID: aaa (ambient temperature: 22.1)
- ID: bbb (ambient temperature: 22.1)
- ID: ccc (ambient temperature: 21.9)
- ID: ddd (ambient temperature: 21.9)
```
Fixes #13599
=> [meater] Add console extension for showing IDs

bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/console/PowermaxCommandExtension.java
=> [powermax] Console command completion

bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/console/LGWebOSCommandExtension.java
=> [lgwebos] Console command completion

bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/HikvisionHandler.java, bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/handler/IpCameraHandler.java
This fixes a bug reported on the forum here:
https://community.openhab.org/t/ipcamera-new-ip-camera-binding/42771/2796
It was caused by the lowPriorityRequests having only 1 element. When the camera did not support any alarm inputs (common for a camera to have none) the binding would remove the request, then later on as lowPriorityRequests was empty it would fetch the list again which added it back in. This caused an endless WARN messages in the logs.
Jar can be downloaded from:
=> [ipcamera] Fix multiple WARNs when HIK camera does not support alarm inputs

bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/NumberValue.java, bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/SensorTests.java
So that other pieces of openhab can know what unit it's going to be, without it having a value yet. Importantly, any necessary conversion that need to be applied to the other portion of the state description - min, max, and step.
=> [mqtt] set the proper unit in the state description

bundles/org.openhab.binding.hdpowerview/README.md, bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/console/HDPowerViewCommandExtension.java
Example session:
```
openhab> openhab:hdpowerview showIds
API bridge: PowerView Hub
- Shades:
- ID: 23137 (Gardin 7)
- ID: 24076 (Gardin 10)
- ID: 32544 (Gardin 6)
- ID: 58120 (Gardin 2)
- ID: 34896 (Gardin 5)
- ID: 5868 (Gardin 8)
- ID: 38196 (Gardin 1)
- ID: 46532 (Gardin 3)
- ID: 42949 (Gardin 4)
- ID: 36137 (Gardin 11)
- ID: 24927 (Gardin 9)
- Repeaters:
- ID: 17805 (Repeater soveværelse)
```
Fixes #13614
=> [hdpowerview] Add console extension for showing IDs

bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/connection/HueTlsTrustManagerProvider.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueBridgeHandler.java, bundles/org.openhab.binding.hue/src/main/resources/OH-INF/i18n/hue.properties
=> [hue] Check HTTPS connection (download of PEM certificate)

bundles/org.openhab.binding.boschshc/README.md, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/AbstractPowerSwitchHandler.java, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/BoschSHCBindingConstants.java, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/BoschSHCDeviceHandler.java, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/BoschSHCHandler.java, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/BoschSHCHandlerFactory.java, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/plug/PlugHandler.java, bundles/org.openhab.binding.boschshc/src/main/resources/OH-INF/thing/thing-types.xml, bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/AbstractBoschSHCDeviceHandlerTest.java, bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/AbstractPowerSwitchHandlerTest.java, bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/AbstractSHCHandlerTest.java, bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/lightcontrol/LightControlHandlerTest.java, bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/plug/PlugHandlerTest.java
* add thing definition with ID "smart-plug-compact"
* add constant for thing type UID
* extract abstract implementation for devices with power switch and energy monitoring
* let in-wall switch handler and smart plug handler extend the abstract implementation
* register new handler
* add method with boolean parameter to fetch initial state actively
* make BoschSHCDeviceHandler abstract
* add documentation
* add unit tests
closes #13528
Signed-off-by: David Pace <dev@davidpace.de>
=> [boschshc] Support for Compact Smart Plugs (#13528)

bundles/org.openhab.binding.paradoxalarm/src/main/java/org/openhab/binding/paradoxalarm/internal/handlers/ParadoxIP150BridgeHandler.java
* Change static config field in the main bridge handler to non-static (fixes #13628)
Signed-off-by: Konstantin Polihronov <polychronov@gmail.com>
=> [paradoxalarm] Fix issue that the config of paradox bridge handler gets overwritten when there are more than one bridge

bundles/org.openhab.binding.linuxinput/README.md, bundles/org.openhab.binding.linuxinput/src/main/java/org/openhab/binding/linuxinput/internal/LinuxInputHandler.java
As reported in https://community.openhab.org/t/linuxinput-binding-and-mouse-capture/122612/8 the binding would not properly handle channels for keys unknown by libevdev.
Fall back to the numeric event codes in this case.
=> [linuxinput] handle keys not known by libevdev

bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/deserialization/NAPushType.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/SecurityCapability.java
Also fix few findings by code analysis
=> [netatmo] eventBuffer in SecurityCapability should not be static

bundles/org.openhab.binding.mqtt.generic/README.md
`color_mode` is not recognized as a channel parameter, instead, `colorMode` is
=> [mqtt.generic] Update README.md

bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/converter/type/QuantityTypeConverter.java, bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/type/MetadataUtils.java
Current versions of the Homematic CCU are using "% rH" resp. "% rF% (for german language as unit for humidity on some devices.
Fix #13553
=> [homematic] Some HM devices are using relative humidity (% rH/rF) as units

bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/Utils.java
The Easee API was recently changed. Instead of one common date/time format the API now provides dates in different formats. The parser now supports boths formats and detects the correct format by checking the length of the provided date string.
=> [easee] adopted date parser due to changes in easeeAPI

bundles/org.openhab.binding.kostalinverter/README.md, bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/kostalinverter/internal/secondgeneration/SecondGenerationHandler.java
[kostalinverter] Fix for the Kostal inverter binding to work with different firmware releases regarded to PIKO 10-20 V. 221004
This is the next version regarded to Closed PR #13464
Hi, lolodomo
The changes of code regarded to jsonDxsEntriesResponse in CallURL is for to have some FW versions to deliver the very same value as other versions does. ( 0.000000 instead of null )
Regarded to httpClient do I have a problem with as I think some FW-versions or maybe even HW-versions of inverter ( proberly not same as above, and mine works for both these issues ). Some causes the binding to get hanging after random time ( hours , days ) I have not been able to find the reason to that behavior, only the solution, a guess is about something like "Closed Channel Exception", but I have not been able to …
=> [kostalinverter] Fix for the Kostal inverter binding to work with different firmware releases regarded to PIKO 10-20 V. 221004

bundles/org.openhab.binding.verisure/src/main/java/org/openhab/binding/verisure/internal/VerisureSession.java
Avoid registering several times the same device status listener.
It is called by the thing handler each time the bridge status changed to ONLINE.
This bug was reported by @ulfwin while discussing a similar problem within the Tellstick binding: PR #13479 
=> [verisure] Avoid updates duplication after communication errors

bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/JSRuntimeFeatures.java, bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/OpenhabGraalJSScriptEngine.java, bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/scriptengine/InvocationInterceptingScriptEngineWithInvocableAndAutoCloseable.java, bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/threading/ThreadsafeTimers.java, bundles/org.openhab.automation.jsscripting/src/main/resources/node_modules/@jsscripting-globals.js
Fixes #13594.
This PR reimplements the polyfills for the standard JS timers (`setTimeout` and `setInterval`) in the Java layer of the binding to conform standard JS.
This brings several improvements:
- Usage of `TimerImpl` from core is no longer required; instead the scheduler is accessed directly
- Mapping of ScheduledFutures to unique Integers to conform standard JS that returns a `timeoutId` or `intervalId` when the according funtion is run. FYI: Standard JS shares the same pool of integers for both, the binding does therefore the same.
- Scheduled jobs created by the polyfills are named by using the loggername, the type (`timeout` or `interval`) and the id (an Integer).
- All scheduled jobs created by the polyfills are automatically cancelled when the rule is unloaded to avoid having …
=> [jsscripting] Reimplement timer polyfills to conform standard JS

bundles/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/internal/TellstickHandlerFactory.java, bundles/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/internal/core/TelldusCoreBridgeHandler.java, bundles/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/internal/discovery/TellstickDiscoveryService.java, bundles/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/internal/handler/TelldusDevicesHandler.java, bundles/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/internal/live/TelldusLiveBridgeHandler.java, bundles/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/internal/live/TelldusLiveDeviceController.java, bundles/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/internal/live/xml/TellstickNetDevice.java, bundles/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/internal/live/xml/TellstickNetSensor.java, bundles/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/internal/local/TelldusLocalBridgeHandler.java, bundles/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/internal/local/TelldusLocalDeviceController.java
Fix #13453
Do not register the same device handler many times as listener in the bridge handler
Unregister the device handler from the bridge handler when disposing device handler
HTTP timeout set to 15s
Remove the retry mechanism related to the timeout
Check HTTP status code
Fix discovery service unregistration
Log statistics about request/refresh durations and number of timeouts/errors
Change logging in case of exception
Also change few logs level (remove usage of logger.error)
Execute one refresh at bridge initialization and not 2
Small enhancement of the bridge/things status management
implement discovery service unregistration
Fix few code analysis findings
=> [tellstick] Avoid updates duplication after communication errors

bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcBaseDAO.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcMysqlDAO.java
Fix this notice on startup:
_Loading class \`com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary._
This was introduced when Connector/J was upgraded to 8.0 years ago:
https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-api-changes.html
Fixes #11157
=> [jdbc] Fix MySQL deprecation notice on startup

bundles/org.openhab.automation.jsscripting/README.md, bundles/org.openhab.automation.jsscripting/pom.xml
Follow up PR for #13623.
@jlaur 
After testing my relatively small JS codebase changes with the latest SNAPSHOT of the add-on as well as on my production system (on 3.4.0.M3) to also test the new version on older versions of the add-on (it is possible to manually upgrade the library with npm), and rereading my documentation changes I decided to merge https://github.com/openhab/openhab-js/pull/169 without review. (I know, not so nice, but time is short and changes are not so big).
A new version is released now and is waiting to be included in the add-on!
=> [jsscripting] Update openhab-js version to 2.1.0

bundles/org.openhab.binding.groheondus/pom.xml, bundles/org.openhab.binding.groheondus/src/main/feature/feature.xml
* Upgrade commons-text to 1.10.0 (prevents CVE-2022-42889)
* Upgrade commons-lang3 to 3.12.0
* Remove commons-text, wrap from feature because it is embedded into the bundle
=> [groheondus] Upgrade dependencies

bundles/org.openhab.binding.kodi/src/main/resources/OH-INF/config/config.xml
=> [kodi] Fix bridge initialization when parameter `group` is not configured

bundles/org.openhab.binding.squeezebox/src/main/resources/OH-INF/thing/thing-types.xml
=> [squeezebox] Fix bridge initialization when parameter `quoteList` is not configured

bundles/org.openhab.persistence.jdbc/README.md, bundles/org.openhab.persistence.jdbc/pom.xml, bundles/org.openhab.persistence.jdbc/src/main/feature/feature.xml, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcConfiguration.java
See https://mariadb.com/kb/en/mariadb-connector-j-release-notes/
JAR: [org.openhab.persistence.jdbc-3.4.0-SNAPSHOT.jar](https://drive.google.com/file/d/1sXgSImDMgCzVfCIzz_idAL8e7XdP4aUr/view?usp=sharing)
To test, place this file in the addons directory and rename it to `mariadb-java-client.jar`:
https://repo1.maven.org/maven2/org/mariadb/jdbc/mariadb-java-client/3.0.8/mariadb-java-client-3.0.8.jar
Testing this is quite important as the previous version was more than six years old.
Related forum thread: https://community.openhab.org/t/jdbc-persistence-with-tableuserealitemnames-and-tableiddigitcount-0/40552/18
=> [jdbc] Upgrade MariaDB JDBC driver to 3.0.8

bundles/org.openhab.binding.boschshc/README.md, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/AbstractBatteryPoweredDeviceHandler.java, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/BoschSHCBindingConstants.java, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/BoschSHCHandler.java, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/BoschHttpClient.java, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/BridgeHandler.java, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/dto/DeviceServiceData.java, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/dto/Fault.java, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/dto/Faults.java, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/dto/LongPollResult.java, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/motiondetector/MotionDetectorHandler.java, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/thermostat/ThermostatHandler.java, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/twinguard/TwinguardHandler.java, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/wallthermostat/WallThermostatHandler.java, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/windowcontact/WindowContactHandler.java, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/BoschSHCService.java, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/batterylevel/BatteryLevel.java, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/batterylevel/BatteryLevelService.java, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/dto/BoschSHCServiceState.java, bundles/org.openhab.binding.boschshc/src/main/resources/OH-INF/thing/thing-types.xml, bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/AbstractBatteryPoweredDeviceHandlerTest.java, bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/AbstractPowerSwitchHandlerTest.java, bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/AbstractSHCHandlerTest.java, bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/bridge/BoschHttpClientTest.java, bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/motiondetector/MotionDetectorHandlerTest.java, bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/thermostat/ThermostatHandlerTest.java, bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/twinguard/TwinguardHandlerTest.java, bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/wallthermostat/WallThermostatHandlerTest.java, bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/windowcontact/WindowContactHandlerTest.java, bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/services/batterylevel/BatteryLevelTest.java
This change adds support for obtaining the battery state for the following devices:
* Motion Detector
* Thermostat
* Twinguard
* Wall Thermostat
* Window/Door Contact
The following changes were made:
* Add channel type definition for battery levels
* Add battery level channels to Motion Detector, Thermostat, Twinguard, Wall Thermostat and Window/Door Contact
* Add constant for battery level channel in BoschSHCBindingConstants
* Implement abstract handler and service for battery-powered devices
* Let appropriate devices inherit the abstract implementation
* Add missing super calls in initializeServices() methods
* Rename existing getServiceURL() to getServiceStateURL() in HTTP client
* Add methods to retrieve service states without the suffix "/state" in the URL
* Rename DeviceStatusUpdate …
=> [boschshc] Support obtaining battery states

bundles/org.openhab.binding.monopriceaudio/README.md
This PR updates the README to clarify the supported thing types. It also adds a link to the OH Marketplace version of the binding that provides support for additional thing types. The intent is to inform users who may not otherwise know about the marketplace version and hopefully get some feedback about the beta functionality.
=> [monopriceaudio] Update README

bundles/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/handler/HusdataHandler.java, bundles/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/handler/IpHusdataHandler.java, bundles/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/handler/IpRego6xxHeatPumpHandler.java, bundles/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/handler/Rego6xxHeatPumpHandler.java, bundles/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/handler/SerialHusdataHandler.java, bundles/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/handler/SerialRego6xxHeatPumpHandler.java, bundles/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/protocol/IpRegoConnection.java, bundles/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/protocol/RegoConnection.java, bundles/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/protocol/SerialRegoConnection.java, bundles/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/rego6xx/AbstractLongResponseParser.java, bundles/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/rego6xx/AbstractResponseParser.java, bundles/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/rego6xx/Checksum.java, bundles/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/rego6xx/CommandFactory.java, bundles/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/rego6xx/ErrorLine.java, bundles/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/rego6xx/ErrorLineResponseParser.java, bundles/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/rego6xx/Rego6xxProtocolException.java, bundles/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/rego6xx/RegoRegisterMapper.java, bundles/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/rego6xx/ResponseParser.java, bundles/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/rego6xx/ResponseParserFactory.java, bundles/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/rego6xx/ShortResponseParser.java, bundles/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/rego6xx/StringResponseParser.java, bundles/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/rego6xx/ValueConverter.java, bundles/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/rego6xx/WriteResponse.java
If for some reason HP response fails to properly parse, i.e. `java.lang.NumberFormatException: For input string: "##"` exception is not handled and scheduler is not re-triggered (polling stops). Also fixed build warnings.
Signed-off-by: Boris Krivonog [boris.krivonog@inova.si](mailto:boris.krivonog@inova.si)
=> [regoheatpump] fixed polling stops problem if there is an unhandled runtime exception

bundles/org.openhab.persistence.jdbc/README.md, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/ItemTableCheckEntry.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/ItemTableCheckEntryStatus.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/console/JdbcCommandExtension.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcBaseDAO.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcMapper.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcPersistenceService.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcPersistenceServiceConstants.java
This introduces some basic tools for verifying integrity of persisted items and corresponding tables.
```
openhab> openhab:jdbc
Usage: openhab:jdbc tables list [all] - list tables (all = include valid)
Usage: openhab:jdbc tables clean [<itemName>] [force] - clean inconsistent items (remove from index and drop tables)
openhab> openhab:jdbc tables list
Table     Row count  Item                  Status
--------  ---------  --------------------  ----------------------
Item0281      54217  WiserSocket1_Voltage  Item missing
Item0283          0  NotFound              Item and table missing
Item0284          0  NotFound2             Table missing
blah              1                        Orphan table
openhab> openhab:jdbc tables clean
Cleaning up all inconsistent items...
WiserSocket1_Voltage …
```
=> [jdbc] Add console maintenance commands

bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Climate.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Vacuum.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/config/ChannelConfigurationTypeAdapterFactory.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/config/ConnectionDeserializer.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/discovery/HomeAssistantDiscovery.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/exception/ConfigurationException.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/exception/UnsupportedComponentException.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/handler/HomeAssistantThingHandler.java, bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/AbstractHomeAssistantTests.java, bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/AbstractComponentTests.java, bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/AlarmControlPanelTests.java, bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/ClimateTests.java, bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/CoverTests.java, bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/FanTests.java, bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/HAConfigurationTests.java, bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/LockTests.java, bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/SensorTests.java, bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/SwitchTests.java, bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/VacuumTests.java, bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/discovery/HomeAssistantDiscoveryTests.java, bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/handler/HomeAssistantThingHandlerTests.java
Fixes #13517
Possibly resolves #9711 and #12295 as well.
The implementation does not handle updating discovery topics -- when the content is not exactly the same. Example of real life scenario documented in #13517 with OpenMQTTGateway. To be honest, I am not sure if there are other kind of situations when we might hit this error.
This fix ensures that conflicting channels are first removed, and only then we add new channels. This means that more recent discovery data always overrides older... at least when it comes to channels.
=> [mqtt.homeassistant] Fix binding crash when home assistant discovery topics update with content

bundles/org.openhab.binding.evcc/src/main/java/org/openhab/binding/evcc/internal/EvccHandler.java, bundles/org.openhab.binding.evcc/src/main/java/org/openhab/binding/evcc/internal/api/EvccAPI.java, bundles/org.openhab.binding.evcc/src/main/java/org/openhab/binding/evcc/internal/api/dto/Loadpoint.java, bundles/org.openhab.binding.evcc/src/main/java/org/openhab/binding/evcc/internal/api/dto/Result.java, bundles/org.openhab.binding.evcc/src/main/java/org/openhab/binding/evcc/internal/api/dto/Status.java
Fixes #13646.
This PR fixes an issue, where evcc changed their API to return a float instead of an int for `vehicleCapacity`, but the DTO expected an int and parsing the JSON response failed.
To avoid such issues in the future, all JSON response fields that might be changed to float in the future now use float instead of int.
Furthermore, the usage of double was replaced by float, as the higher precision of double is not required.
@pauxus I will also publish this bugfix to the addon marketplace, so that you can update the binding ASAP. See https://community.openhab.org/t/evcc-binding-electric-vehicle-charging-control/135209.
@andig FYI: This fixes https://github.com/evcc-io/evcc/issues/5035.
=> [evcc] Fix data type issues in DTO

bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/api/TapoDeviceConnector.java, bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/api/TapoDeviceHttpApi.java, bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/constants/TapoThingConstants.java, bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/device/TapoBridgeHandler.java, bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/device/TapoDevice.java, bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/helpers/PayloadBuilder.java, bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/structures/TapoBridgeConfiguration.java, bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/structures/TapoDeviceConfiguration.java, bundles/org.openhab.binding.tapocontrol/src/test/TapoDiscoveryService.java, bundles/org.openhab.binding.tapocontrol/src/test/java/org/openhab/binding/tapocontrol/internal/device/TapoBridgeHandler.java, bundles/org.openhab.binding.tapocontrol/src/test/java/org/openhab/binding/tapocontrol/internal/structures/TapoBridgeConfiguration.java
* fixed configuration error
* improved response logging and error handling
This PR fixes error reading configuration with integer values.
Configuration handling revised
Also tracing of sent and received http request was enhanced, because some unkown communication errors will occur sometimes. 
It has been discussed at [https://community.openhab.org/t/tapocontrol-control-tapo-smart-wifi-devices-with-openhab/118389/216](https://community.openhab.org/t/tapocontrol-control-tapo-smart-wifi-devices-with-openhab/118389/216).
A compiled jar is available at [https://github.com/wildcs/oh3_tapocontrol/tree/a82bd00a65c9fbcabbfa377258ebdffd3b649032](url)
=> [tapocontrol] Fix configuration error

bundles/org.openhab.automation.jsscripting/pom.xml, bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/OpenhabGraalJSScriptEngine.java, bundles/org.openhab.automation.jsscripting/src/main/resources/node_modules/@jsscripting-globals.js
The community reported several cases where JS Scripting was not working due to some issue with the injection of the global script.
This issue seems to only occur on armv7l (e.g. Raspberry Pi 32bit) and OpenJDK 11.0.16.
Investigation showed that the occurrence of the problem depends on the GraalJS version, so we have to downgrade the version. (FYI: The version was upgraded in https://github.com/openhab/openhab-addons/pull/13582.)
See https://community.openhab.org/t/js-scripting-all-scripts-stop-working-when-upgrading-to-3-4-0-m4/140837.
I have verified that JS Scripting is now properly working on my Raspberry Pi 3B:
- `uname -a`:
```
Linux homeberrypi 5.10.103-v7+ #1529 SMP Tue Mar 8 12:21:37 GMT 2022 armv7l GNU/Linux
```
- `java --version`:
```
openjdk 11.0.16 2022-07-19
OpenJDK Runtime …
```
=> [jsscripting] Fix failure on some platforms & JDKs

bundles/org.openhab.binding.ecobee/README.md, bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/EcobeeBindingConstants.java, bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/dto/thermostat/ExtendedRuntimeDTO.java, bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/dto/thermostat/RuntimeDTO.java, bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/handler/EcobeeThermostatBridgeHandler.java, bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/handler/EcobeeUtils.java, bundles/org.openhab.binding.ecobee/src/main/resources/OH-INF/i18n/ecobee.properties, bundles/org.openhab.binding.ecobee/src/main/resources/OH-INF/thing/thing-types.xml
The Ecobee Smart Thermostat Premium returns the following additional runtime parameters: 
```
"runtime": {
...
"actualVOC": 1045, 
"actualCO2": 738,
"actualAQAccuracy": 4,
"actualAQScore": 73,
...
}
```
This PR creates the associated channels for them.
=> [ecobee] Add air quality channels for Ecobee Smart Thermostat Premium

bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/handler/NuvoHandler.java
Fix bug caused due to review changes for #13658... The system_buttonpress channel was not populating and always displaying UNDEF.
=> [nuvo] fix system_buttonpress not populating

bundles/org.openhab.persistence.jdbc/pom.xml, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/console/JdbcCommandExtension.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/dto/ItemsVO.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcMapper.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcPersistenceService.java
This refactoring upgrades Yank and changes behavior in order to have exceptions thrown instead of silently swallowed and logged. The moves the responsibility for handling and logging exceptions to the callers.
Additionally SQL errors will now be displayed in the console when occurring after executing a command.
Also fixed: Last remaining SAT warning about `hashCode()` implementation.
This shows how the logging appears before and after the changes.
```
2022-11-14 22:17:43.759 [DEBUG] [persistence.jdbc.internal.JdbcMapper] - JDBC::storeItemValue: item=TestItem (Type=StringItem, State=string2, Label=New Item, Category=) state=string2 date=null
2022-11-14 22:17:43.760 [DEBUG] [.openhab.persistence.jdbc.dto.ItemVO] - JDBC:ItemVO tableName=Item0001; newTableName=null; 
2022-11-14 22:17:43.760 …
```
=> [jdbc] Improve error handling

bundles/org.openhab.binding.networkupstools/src/main/resources/OH-INF/i18n/networkupstools.properties, bundles/org.openhab.binding.networkupstools/src/main/resources/OH-INF/thing/channels.xml
Add state option display string for my APC UPS that is reporting an alarm indicating the battery needs replacing.
=> [networkupstools] Add missing status

bundles/org.openhab.binding.miio/README.md, bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.light.ceiling.json, bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.light.ceiling2.json, bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.light.ceiling4.json
The majority of brightness channels were already converted to dimmer. This PR applies same to a few remaining brightness channels like nightlight and/or ambient
close: #9936
=> [miio] Fix dimming channels for several yeelights

bundles/org.openhab.persistence.jdbc/README.md, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcMapper.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/console/JdbcCommandExtension.java
Reloading can be useful after manual index/schema changes in order to refresh the internal **item name -> table name** map.
Related to #13661
=> [jdbc] Add console command for reloading index/schema

bundles/org.openhab.binding.harmonyhub/src/main/java/org/openhab/binding/harmonyhub/internal/discovery/HarmonyHubDiscoveryService.java, bundles/org.openhab.binding.harmonyhub/src/main/java/org/openhab/binding/harmonyhub/internal/handler/HarmonyHubHandler.java
Publishing as draft until I have run some additional tests and observed reliability for at least some days:
Main issue fixed:
```
2022-11-11 23:51:29.461 [WARN ] [.core.thing.binding.BaseThingHandler] - Handler HarmonyHubHandler of thing harmonyhub:hub:home tried updating channel currentActivity although the handler was already disposed.
2022-11-11 23:51:29.462 [WARN ] [.core.thing.binding.BaseThingHandler] - Handler HarmonyHubHandler tried updating thing harmonyhub:hub:home although the handler was already disposed.
```
Fixes #13701
=> [harmonyhub] Fix reliability issues

bundles/org.openhab.persistence.jdbc/README.md, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcConfiguration.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcMapper.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/dto/ItemsVO.java, bundles/org.openhab.persistence.jdbc/src/main/resources/OH-INF/config/config.xml
Items are by default prefixed with `item` and the items management table is named `items`.
When migrating from the MySQL Persistence Service, users are advised to use `tableNamePrefix=Item` in configuration, but it is not mentioned that they need to manually rename the items management table from `Items` to `items`. Failing to do so will result in a new empty `items` table being created alongside the existing `Items` table. This is counter-intuitive.
This pull request introduces a configuration option to set the name of the items management table, so existing `Items` table from a migration can be used as is. This eases the migration and adds more flexibility as any desired name can be configured, instead of the items management table name being hardcoded.
Fixes #9637
=> [jdbc] Make itemsManageTable configurable

bundles/org.openhab.binding.dscalarm/README.md
Fix broken link to external PDF document in README.
=> [dscalarm] Fix broken link in README

bundles/org.openhab.binding.mqtt.espmilighthub/README.md
Fix wrong format of the textual example as it was not allowing state updates to change openHAB controls when following the old format. Reported on forum here:
https://community.openhab.org/t/mqtt-binding-with-espmilight-mostly-working-not-getting-updates-in-openhab-when-using-remote/141153/7
=> [mqtt.espmilighthub] Fix wrong textual example formats in readme

bundles/org.openhab.automation.jsscripting/pom.xml
This fixes the maven build, that fails because webpack-cli version 5.0.0 doesn’t properly process the given entrypoint. Instead, webpack tries to use the entrypoint from openhab-js‘ webpack config file.
cc @J-N-K
=> [jsscripting] Fix maven build

bundles/org.openhab.automation.jsscripting/README.md, bundles/org.openhab.automation.jsscripting/pom.xml, bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/GraalJSScriptEngineFactory.java, bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/GraalJSScriptServiceUtil.java, bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/JSRuntimeFeatures.java, bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/JSScriptServiceUtil.java, bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/OpenhabGraalJSScriptEngine.java, bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/threading/ThreadsafeTimers.java
This PR reimplements the openHAB Core API for creating timers to make this also threadsafe.
As discussed on the forum https://community.openhab.org/t/js-scripting-why-are-we-deprecated-createtimer/140748, the `setTimeout` and `setInterval` methods do not provide the functionality that advanced users need, and to avoid that those users and users coming from Rules DSL leave JS Scripting because of this missing API, we have to provide thread-safe access to it.
Furthermore,  `JSScriptServiceUtil` was introduced to provide easy access from to script services provided by core. This replaces the usage of the `JSScriptServiceUtil` from the Rules DSL parts of core and therefore reduces dependency on a part that might become an addon in the future.
openhab-js is also upgraded to 2.1.1.
Use the …
=> [jsscripting] Reimplement timer creation method of `ScriptExecution`

bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcBaseDAO.java, bundles/org.openhab.persistence.jdbc/src/test/java/org/openhab/persistence/jdbc/internal/db/JdbcBaseDAOTest.java
=> [jdbc] Fix date filter to be inclusive

CODEOWNERS
Unfortunately I do not have the resources (and equipment) anymore to act as maintainer of this add-on; and therefore have to resign from this
role.
Signed-off-by: Patrik Gfeller <patrik.gfeller@gmail.com>
=> iCloud Binding - Maintainer change

bundles/org.openhab.automation.jsscripting/pom.xml, bundles/org.openhab.automation.jsscripting/src/main/feature/feature.xml
Working with the UI, I noticed that the JS Scripting addon there is actually called _JSScripting_ (without the space).
This PR should correct this.
=> [jsscripting] Fix add-on name in feature/pom

bundles/org.openhab.binding.ipcamera/README.md, bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/HikvisionHandler.java, bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/InstarHandler.java, bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/IpCameraBindingConstants.java, bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/MyNettyAuthHandler.java, bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/handler/IpCameraHandler.java, bundles/org.openhab.binding.ipcamera/src/main/resources/OH-INF/thing/thing-types.xml
Changes made:
+ Add Person, Vehicle and Animal Object detection alarms for new Instar cameras that support this ability.
+ Add support for setting up the alarm server on new Instar range of cameras.
+ Add support for changes in Instar alarm codes in their newer range.
+ Add a method to stop ONVIF from connecting if a camera has an issue by setting onvifPort=0
+ Add compatability fix/work around for cameras that do not surround a realm in quotes.
Jar can be RIGHT HAND CLICKED and downloaded from:
=> [ipcamera] Improve support for newer 2k+ Instar cameras

bundles/org.openhab.binding.nanoleaf/README.md
This is broken in the readme here and causes our https://next.openhab.org website build to fail for some time now.
=> [Nanoleaf] Fix logo in Readme (and website build)

bundles/org.openhab.persistence.jdbc/README.md, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcMapper.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcPersistenceService.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/console/JdbcCommandExtension.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcBaseDAO.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcDerbyDAO.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcPostgresqlDAO.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/dto/Column.java
This pull request provides tools for detecting and repairing database schema inconsistencies which may have accumulated over time, when many things changed since tables were created. For example:
- Migration from MySQL persistence where `DATETIME` was used for the time column, whereas this is now `TIMESTAMP(3)`.
- Bugfixes extending or otherwise changing column types, for example #10542 and #9394.
- Manual corrections which are inconsistent with the JDBC types.
```
openhab> openhab:jdbc schema check
Table        Item         Issue
-----------  -----------  ----------------------------------------------------------------
Anyone_Home  Anyone_Home  Column name 'time' expected, but is 'Time'
Anyone_Home  Anyone_Home  Column type 'TIMESTAMP(3)' expected, but is 'DATETIME'
Anyone_Home …
```
=> [jdbc] Add console command for checking/repairing schema integrity

bundles/org.openhab.io.homekit/README.md, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitImpl.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitTaggedItem.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/AbstractHomekitPositionAccessoryImpl.java
home app never sends "STOP" but always sends the target position, e.g. 100% or 0% for fully open or closed blinds. 
Rollershutter in openHAB and some device do support stop. 
this PR adds emulation of stop if user click on blind icons in the home app while blinds is moving. 
report and discussion here
https://community.openhab.org/t/oh3-rollershutter-and-apple-homekit/112376/31
this PR also fix one potential NPE and a typo in the docu "light -> lighting"
=> [homekit] support stop for blinds

bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitTaggedItem.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitCharacteristicFactory.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitTemperatureSensorImpl.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitThermostatImpl.java
otherwise if your step is 1.0 in fahrenheit, then your values will get rounded to 1.0 celsius, and you might not even notice you've lost precision in the Home app.
=> [homekit] make sure to convert step values to Celsius

bundles/org.openhab.persistence.jdbc/README.md, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcMapper.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcPersistenceService.java
This is a small follow-up to #13544 and #13737 since the combination of these features and an invalid configuration can potentially be dangerous.
Consider this case:
- **Configuration:** `itemsManageTable=items`; `tableNamePrefix=Item`; `tableUseRealItemNames=false`; `tableIdDigitCount=4`, `rebuildTableNames=true`
- **Tables:** `Items`, `Item1`, `Item4`, `Item5`
This is logically considered as a migration _from_ real names _to_ indexed scheme with prefixes and sequential numbers, since index (items manage table) is not found. As a result:
- Index table `items` is created.
- Item1 is renamed to Item0001 and indexed as item name "Item1".
- Item4 is renamed to Item0002 and indexed as item name "Item4".
- Item5 is renamed to Item0003 and indexed as item name "Item5".
- Items is renamed to …
=> [jdbc] Add safety valve for suspicious migrations

bundles/org.openhab.automation.jrubyscripting/README.md, bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/JRubyScriptEngineConfiguration.java
This allows the gem version specifications with multiple specifiers such as:
gems=`gem1= >= 2.0.0; < 3`. The version specifiers are separated by a semicolon.
This is backwards compatible so multiple gems are still comma separated: gems=`gem1=>1.0.0 ; < 2, gem2=~>2.0, othergem=>=7.5.0; < 8`
=> [jrubyscripting] Allow multiple version specifiers for gems

bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/messages/ERP1Message.java
Setting senderId for MSC RORG and set rorg to Unknown when there is no mach with the supported(handled) RORG types.
Fixes #13786
=> [enocean] Fix messages with MSC RORG

bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/OpenhabGraalJSScriptEngine.java
Fixes https://github.com/openhab/openhab-addons/issues/12577.
When a `.js` script file was changed and reloaded by openHAB, a memory leak in the JS Scripting add-on lead to an openHAB crash after some time.
This PR finally fixes the memory leak causing this.
I found the memory leak after reproducing the issue and taking several heap snapshots. Analyzation of the heap snapshots has shown, that a extremely high number of GraalJS related objects without a GC root existed in the heap. 
Looking after `OpenhabGraalJSScriptEngine` in the heap snapshot, I noticed that there were also numerous instances of the engine, which were not cleaned by GC because they were referenced by `com.oracle.truffle.host.HostObject`.
Research on the web lead me to reading …
=> [jsscripting] Fix memory leak that crashes openHAB

bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/InstarHandler.java, bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/handler/IpCameraHandler.java, bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/onvif/OnvifConnection.java
This PR contains 1 bug fix in the ONVIF connecting code that was causing issues with Instar and possibly other brands as well. The Host http header was blank.
The rest of the changes are to provide support for a newer 2k range of cameras that have a different API implemented in them.
Jar can be RIGHT HAND CLICKED and downloaded from:
=> [ipcamera] Instar API updates for new 2k+ range

bundles/org.openhab.binding.unifi/README.md, bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/handler/UniFiClientThingHandler.java, bundles/org.openhab.binding.unifi/src/main/resources/OH-INF/thing/thing-types.xml
In order to fully support UoM, the uptime channel type is migrated from `Number` to `Number:Time`.
With this change, the unit "s" is automatically appended in logs etc. when not otherwise specified.
Fixes #13826
=> [unifi] Migrate uptime channels to Number:Time

bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/type/HomematicTypeGeneratorImpl.java
For dimmers, the 1.0 max value sent by CCU was already converted to percent values in the item state description. Do the same thing also for roller shutters.
Previously, the item state description looked e.g. like this:
```
{
"link": "http://server:8080/rest/items/BathroomBlindsLevel",
"state": "100",
"stateDescription": {
"minimum": 0.0,
"maximum": 1.0,
"pattern": "%d %%",
"readOnly": false,
"options": [
]
},
"editable": true,
"type": "Rollershutter",
"name": "BathroomBlindsLevel",
"label": "Level",
"category": "Blinds",
"tags": [
"Point"
],
"groupNames": [
]
}
```
... which is obviously wrong. Both `ITEM_DIMMER` and `ITEM_ROLLERSHUTTER` use `PercentTypeConverter` when converting item commands to CCU values, which is dividing the value by 100, so in both cases the maximum value in the …
=> [homematic] Fix min/max values for rollershutters

bundles/org.openhab.binding.resol/pom.xml, bundles/org.openhab.binding.resol/src/main/java/org/openhab/binding/resol/handler/ResolThingHandler.java, bundles/org.openhab.binding.resol/src/main/resources/OH-INF/thing/thing-types.xml
Controllers (for example the SKSR 1/2/3) on the VBUS transmitting fields of type WeekTime did not work as decribed in #13447 which is fixed by this PR.
The resol-vbus-java library used by this binding was also improved for this controller in the meantime, that's why this PR integrates an upgrade to the latest version of this lib.
A compiled version of this code change can be found [here](https://github.com/ramack/openhab-addons/blob/51dd67d764f11084cb904aeabf7a02cb52f4791e/bundles/org.openhab.binding.resol/target/org.openhab.binding.resol-3.4.0-SNAPSHOT.jar?raw=true) and @paicl01 tested it successfully.
=> [resol] Fix handling of WeekTime fields on vbus

bundles/org.openhab.binding.androiddebugbridge/README.md, bundles/org.openhab.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/AndroidDebugBridgeConfiguration.java, bundles/org.openhab.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/AndroidDebugBridgeDevice.java, bundles/org.openhab.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/AndroidDebugBridgeHandler.java, bundles/org.openhab.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/discovery/AndroidDebugBridgeDiscoveryService.java, bundles/org.openhab.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/discovery/AndroidTVMDNSDiscoveryParticipant.java, bundles/org.openhab.binding.androiddebugbridge/src/main/resources/OH-INF/i18n/androiddebugbridge.properties, bundles/org.openhab.binding.androiddebugbridge/src/main/resources/OH-INF/thing/thing-types.xml
Device "ChromeCast with Google TV" was recently updated to android 12.
I found out that volume channel is not working anymore (neither should work on android 11), it is due the 'media' cli removal on android 11.
This PR aims to fix the volume channel for both versions (just tested on android 12).
Regards!
=> [androiddebugbridge] Fix volume channel for android 11/12

bundles/org.openhab.binding.wundergroundupdatereceiver/README.md
Fix spelling
Fixes the addendum in #13577 
Signed-off-by: Daniel Demus <daniel-github@demus.dk>
=> [wundergroundupdatereceiver] Use html entities in normal body otherwise they are parsed as tags

CODEOWNERS
I forgot to add myself to the codeowners file, sorry.
=> [smsmodem] Add codeowners

bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcSqliteDAO.java
Follow-up to #13662 so the console command now also supports SQLite.
See https://community.openhab.org/t/hildebrand-glowmarkt-api-binding/139091/20
Related to #13661
=> [jdbc] Fix console command 'tables' for SQLite

CODEOWNERS
This seems to have been forgotten as part of #10332.
=> [groupepsa] Add missing code owner

bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcPostgresqlDAO.java
PostgreSQL implementation was missed in #13734
Discovered by @edman007 in relation to another JDBC issue: https://github.com/openhab/openhab-addons/issues/13775#issuecomment-1336535956
Fixes #9906
=> [jdbc] Fix date filter to be inclusive (PostgreSQL)

bundles/org.openhab.automation.jsscripting/bnd.bnd, bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/GraalJSScriptEngineFactory.java, bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/OpenhabGraalJSScriptEngine.java
See https://github.com/openhab/openhab-core/pull/2883#issuecomment-1336442359 for discussion.
The new MIME types (especially the `graaljs` alias) are introduced to enhance working with JS Scripting in the `SCRIPT` transformation profile (https://github.com/openhab/openhab-core/pull/2883, docs https://github.com/openhab/openhab-docs/pull/1940).
Furthermore, this catches a potential NPE (it occured sometimes during testing due to reloading bundles I think) which I never experienced in production.
Also, I fiexed the syntax problems in the bndtools file.
I will provide the JS Scripting add-on docs for usage of the `SCRIPT` transformation soon, they will come with the openhab-js version bump to the add-on (for the docs, see https://github.com/openhab/openhab-js/pull/190).
@J-N-K FYI
@wborn …
=> [jsscripting] Add an alternative MIME type/alias

bundles/org.openhab.binding.keba/README.md
Fix documentation to correct item type for state item
Should fix https://github.com/openhab/openhab-addons/issues/13679
Fix documentation to correct item type for state item
=> [keba] Correct item type for state item in readme.md

bundles/org.openhab.automation.jsscripting/src/main/resources/node_modules/@jsscripting-globals.js
Fixes a problem, where toString polyfills of objects were ignored:
- Accept `toString` polyfills on objects and do not `JSON.stringify` them (some classes in the openhab-js library will introduce toString polyfills for string serialization).
- Refactor the log message formatting to ease understanding & readibility.
Perform various log statements to check my changes:
```javascript
var item = {
a: 'x',
b: 'y'
}
console.log(item);
var arr = ['hello', 'world', 5, item];
console.log(arr);
console.log(undefined, 7, null);
console.log(function () {
console.log("Hello world")
})
console.log(new RegExp(/ab+c/, 'i'))
console.log('Hello', 'Florian', 5, arr, item)
```
=> [jsscripting] Refactor log formatting & Respect toString polyfills

bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/AbstractMQTTThingHandler.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/DiscoverComponents.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/AbstractComponent.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/handler/HomeAssistantThingHandler.java
To mitigate issue https://github.com/openhab/openhab-addons/issues/13657 (common thread pool exhaustion when combining parallel streams with synchronization or locks)
All the parallel streams are anyways hitting resource contention / bottleneck since they all leads to `MqttBrokerConnection` `subscribe` or `unsubscribe` which is having `synchronized` block with `subscribers` of that broker connection. [*] 
On the surface things looks like they are asynchronous (based on `CompletableFuture` an all) but only the lowest level operations seem to be asynchronous, and in mid-levels we have this synchronization and locking behavour currently.
I would argue typical users have only single `MqttBrokerConnection`, raising the question whether the parallel streams bring any true benefit really.
[*] It …
=> [mqtt] Avoid parallel streams with common thread pool to avoid deadlocks

bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/OpenhabGraalJSScriptEngine.java
In recent PR #13824, I added closing the context when the engine is closed, but core seems to have problems with that.
It logs: "[ERROR] [ipt.internal.ScriptEngineManagerImpl] - Error removing ScriptEngine java.lang.IllegalStateException: The Context is already closed."
Using the reproduce strategy from #13824, I can confirm that the change of this PR does not bring back the memory leak!
=> [jsscripting] Fix "Error removing engine" because context is already closed

bundles/org.openhab.binding.nanoleaf/README.md, bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/handler/NanoleafPanelHandler.java
Signed-off-by: Stefan Höhn <stefan.hoehn@nfon.com>
adds LONG_PRESSED touch detection to the panels.
=> [nanoleaf] add LONG_PRESSED tap detection

bundles/org.openhab.binding.nanoleaf/README.md, bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/NanoleafBindingConstants.java, bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/handler/NanoleafControllerHandler.java, bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/layout/NanoleafLayout.java, bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/layout/PanelState.java, bundles/org.openhab.binding.nanoleaf/src/main/resources/OH-INF/i18n/nanoleaf.properties, bundles/org.openhab.binding.nanoleaf/src/main/resources/OH-INF/thing/lightpanels.xml
Fix the visual state channel name.
Also:
- Better name (from "state" to "visual state") of the (new, not released yet) channel
- Better logs which has helped us debug the problem
- Some more information on when it will work in the README
Discussed on https://community.openhab.org/t/state-and-layout-are-unreliable/141798/19
Signed-off-by: Jørgen Austvik <jaustvik@acm.org>
=> [Nanolaef] Visual State Bugfix

bundles/org.openhab.binding.insteon/README.md
The I/O Linc has a feature to match or invert the status of the contact with its control messages. The binding was written expecting the messages to be inverted. This is the opposite of how insteon recommends setting up the garage kit, and not described well by the original "Note" at the bottom of the section. Updated the instructions to specify the input is OFF when linking in order to invert the messages, and changed the note to better describe what happens if you don't. All based off of my own experience with the sensor: https://community.openhab.org/t/insteon-io-linc-garage-door-contact-slow-update/141469
=> [insteon] Binding Documentation: Updated I/O Linc Section

bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/handler/AstroThingHandler.java
Formatter should get Date object.
Closes #13871
=> [astro] Fix IllegalArgumentException in debug message

bundles/org.openhab.binding.siemensrds/src/main/java/org/openhab/binding/siemensrds/internal/RdsDataPoints.java, bundles/org.openhab.binding.siemensrds/src/main/java/org/openhab/binding/siemensrds/internal/RdsHandler.java, bundles/org.openhab.binding.siemensrds/src/main/java/org/openhab/binding/siemensrds/points/BasePoint.java, bundles/org.openhab.binding.siemensrds/src/test/java/org/openhab/binding/siemensrds/test/TestRdsData.java, bundles/org.openhab.binding.siemensrds/src/test/resources/datapoints_full_set.json, bundles/org.openhab.binding.siemensrds/src/test/resources/datapoints_full_set_new.json
Fixes #13887
As described in #13887 the binding would fail if the thermostat did not use an optional feature.
Furthermore, unfortunately, during the creation and testing of this PR it was discovered that the name of the JUnit test class 'RdsTestData' was such that the respective tests were not actually being run during the GitHub CI Build process. And since the tests were never being run, it had not been noticed that those tests would have been failing anyway, because of a) the test JSON files were encoded using the ANSI character set instead of UTF-8, and b) some of the JUnit 'assertEquals' tests were failing due to changes in the mean-time to the way that QuantityType UoM values were being handled in the binding and/or the OH core classes.
This PR fixes the following things..
1. The …
=> [siemensrds] Binding no longer fails if thermostat does not use optional features

itests/org.openhab.binding.mielecloud.tests/src/main/java/org/openhab/binding/mielecloud/internal/handler/AbstractMieleThingHandlerTest.java
When comparing the integration tests of the mielecloud binding to the ones of the nest binding I saw that things are removed after each integration test run. This PR adds this behavior to the mielecloud integration tests, hoping that this is a cause for them failing in the CI build. Also see #12627.
=> [mielecloud] Integration test fixes: remove things after each integration test

bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/Ffmpeg.java, bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/InstarHandler.java, bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/handler/IpCameraHandler.java
Had a user report that a Unifi protect camera does not get detected as OFFLINE by the binding as the base station/hub/bridge stays online whilst the camera itself does a reboot. FFmpeg hangs if the stream stops midway so this fix will check if the thread is still working when it is needed. Also hard coded URLS in for newer range Instar cameras.
Reported via forum here:
https://community.openhab.org/t/ipcamera-streams-not-automatically-updating-cached/141223/15
Jar can be RIGHT HAND CLICKED and `save link as` to get around the jfrog login from:
=> [ipcamera] Add a check to see if FFmpeg is frozen for mjpeg creation

bundles/org.openhab.binding.miele/README.md, bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/DishwasherChannelSelector.java, bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/MieleApplianceHandler.java, bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/OvenChannelSelector.java, bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/TumbleDryerChannelSelector.java, bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/WashingMachineChannelSelector.java, bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/channeltypes.xml
Migrate channels **duration**, **elapsed** and **finish** from `DateTime` to `Number:Time` since they represent an amount of time, not a specific point in time.
This is a breaking change requiring UI things to be recreated and linked items for these channels to be recreated. Persistence of these channels is unlikely, but would also break. Rules would need adaptation. Therefore I will provide a note in openhab-distro. After recreation of items, the default display format is the same, so UI's should be unaffected. openhab/openhab-distro#1435 prepared.
See also #13316 where related channels were fixed to represent a point in time.
Additional details are available in the linked issue.
Fixes #13840
=> [miele] Migrate time channels from DateTime to Number:Time

bundles/org.openhab.binding.nanoleaf/src/test/java/org/openhab/binding/nanoleaf/internal/layout/NanoleafLayoutTest.java
Because it breaks windows builds
Signed-off-by: Jørgen Austvik <jaustvik@acm.org>
=> [nanoleaf] Don't set read only temp file in test

bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/JRubyScriptEngineFactory.java
This appears to fix an incompatibility introduced after M5, more details available [here](https://github.com/boc-tothefuture/openhab-jruby/pull/659).  To be honest, I am not sure why the order of these calls matter or what changed between M5 and now to make the order matter? 
Because the resolution is so unclear (at least to me) @ccutrer and @jimtng can you verify this doesn't break anything on your end? 
The other changes are from running spotless:apply
=> [jrubyscripting] Reverses order of class imports and ScriptEngine puts calls

bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitImpl.java
See https://github.com/openhab/openhab-addons/pull/13877#issuecomment-1345533019
=> [homekit] Simplify start level handling

bundles/org.openhab.binding.nanoleaf/README.md
next.openhab.org website isn't building because of a wrong includeded image in nanoleaf binding based on the build errors.
A quick merge would be apprecieated.
Also we should check this a bit deeper for current nanoleaf contributions.
This is the second time i have to fix a build caused from the nanonleaf readme.
(Picture uploaded as `png` but referenced as `jpg`.)
I will try to have an eye on this too but would appreciate, if @openhab/add-ons-maintainers would also do so.
=> [Nanoleaf] Fix wrong image and website build (again)

bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcPersistenceService.java
`NullPointerException` was thrown because items manage table was not provided.
Regression of #13737
Fixes #13911
=> [jdbc] Fix console command 'tables clean'

bundles/org.openhab.binding.miele/README.md, bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/channeltypes.xml
Fixes #13929
Exposed by openhab/openhab-core#3143, thus 3.4 regression as a result.
=> [miele] Fix dimension for powerConsumption channel

bundles/org.openhab.binding.nest/README.md
=> [nest] Add missing enable SDM API configuration step to README.md

bundles/org.openhab.binding.miele/README.md
Update examples in documentation - which was missing in #13841.
=> [miele] Fix examples after migration of time channels

bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/handler/NanoleafPanelHandler.java
Panel ids are sometimes returned as BigInteger
We haven't been able to understand why this happens somewhere and somewhere not, but this is an sledgehammer attempt to fix it quickly to unblock users, and then we will try to understand it later.
Discussions:
https://community.openhab.org/t/java-lang-classcastexception-class-java-math-bigdecimal-cannot-be-cast-to-class-java-lang-integer/142035/16 https://community.openhab.org/t/nanoleaf-binding-oh3-stabilization-update/116300/61
Signed-off-by: Jørgen Austvik <jaustvik@acm.org>
=> [nanoleaf] Bugfix: Handle non-integer panel ids

bundles/org.openhab.automation.jsscripting/README.md
The table is not properly rendered when reading the documentation in Main UI.
=> [jsscripting] Fix broken event object table

bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java
Catch exceptions thrown by getDB(..) and print the name of the affected database file. This allows to identify a broken rrd4j file.
During testing of the M6 milestone I got stacktraces like this in my log:
```
[WARN ] [ore.internal.scheduler.SchedulerImpl] - Scheduled job '<unknown>' failed and stopped
java.lang.IndexOutOfBoundsException: null
at java.nio.Buffer.checkIndex(Buffer.java:693) ~[?:?]
at java.nio.DirectByteBuffer.getInt(DirectByteBuffer.java:758) ~[?:?]
at org.rrd4j.core.ByteBufferBackend.readInt(ByteBufferBackend.java:130) ~[?:?]
at org.rrd4j.core.RrdPrimitive.readInt(RrdPrimitive.java:38) ~[?:?]
at org.rrd4j.core.RrdInt.get(RrdInt.java:35) ~[?:?]
at org.rrd4j.core.Archive.<init>(Archive.java:45) ~[?:?]
at …
```
=> [rrd4j] Error handling for broken rrd4j files

bundles/org.openhab.binding.weatherunderground/README.md, bundles/org.openhab.persistence.rrd4j/README.md
Some add-ons use `---` separators which causes issues when rendering the documentation in Main UI.
Fixes #13953
=> Prevent Markdown rendering issues in Main UI

bundles/org.openhab.binding.wundergroundupdatereceiver/README.md
A 😕 shows where it shouldn't:
See: https://www.openhab.org/addons/bindings/wundergroundupdatereceiver/
=> [wundergroundupdatereceiver] Prevent 😕 showing in documentation

bundles/org.openhab.persistence.mapdb/README.md
No docs showed for this add-on in Main UI because there is not even a README.md for this useful persistence service. :roll_eyes: 
It's also missing from https://www.openhab.org/addons/ which makes it also hard to discover.
These docs are based on the original OH1 documentation which did contain some info on its advantages and limitations.
=> [mapdb] Add some documentation

bundles/org.openhab.binding.hydrawise/src/main/java/org/openhab/binding/hydrawise/internal/handler/HydrawiseControllerHandler.java
=> [hydrawise] fixes null pointer error for some sprinkler controllers

bundles/org.openhab.persistence.mapdb/README.md
Here are a few small documentation tweaks on top of #13964.
=> [mapdb] Fix "a" typo and use "-" for bullets in docs

bundles/org.openhab.binding.yamahamusiccast/README.md, bundles/org.openhab.binding.yamahareceiver/README.md
This doc improvement tries to avoid future issue like #10838.
=> [yamaha] README: Recommend correct binding for specific model

bundles/org.openhab.binding.draytonwiser/src/main/resources/OH-INF/i18n/draytonwiser.properties, bundles/org.openhab.binding.draytonwiser/src/main/resources/OH-INF/thing/thing-types.xml, bundles/org.openhab.binding.hue/README.md, bundles/org.openhab.binding.miele/README.md, bundles/org.openhab.binding.mielecloud/README.md, bundles/org.openhab.binding.mihome/README.md, bundles/org.openhab.binding.openwebnet/README.md, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/OpenWebNetBindingConstants.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/discovery/OpenWebNetDeviceDiscoveryService.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/discovery/UsbGatewayDiscoveryService.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetBridgeHandler.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/config/OpenWebNetZigBeeBridgeConfig.java, bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/binding/binding.xml, bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/i18n/openwebnet.properties, bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/ZBAutomation.xml, bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/ZBDimmer.xml, bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/ZBGateway.xml, bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/ZBOnOffSwitch.xml, bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/ZBOnOffSwitch2Units.xml, bundles/org.openhab.binding.plugwise/README.md, bundles/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/handler/PlugwiseStickHandler.java, bundles/org.openhab.binding.plugwise/src/main/resources/OH-INF/binding/binding.xml, bundles/org.openhab.binding.plugwise/src/main/resources/OH-INF/config/config.xml, bundles/org.openhab.binding.plugwise/src/main/resources/OH-INF/i18n/plugwise.properties, bundles/org.openhab.binding.plugwise/src/main/resources/OH-INF/thing/circleplus.xml, bundles/org.openhab.binding.plugwise/src/main/resources/OH-INF/thing/stick.xml, bundles/org.openhab.binding.plugwiseha/README.md, bundles/org.openhab.binding.tacmi/README.md, bundles/org.openhab.binding.tradfri/README.md, bundles/org.openhab.binding.wemo/README.md
Name was changed some years ago from ZigBee to [Zigbee](https://en.wikipedia.org/wiki/Zigbee). Maybe it's time to adapt.
See also:
- openhab/org.openhab.binding.zigbee#785
=> Fix Zigbee name stylization

bundles/org.openhab.binding.pioneeravr/README.md, bundles/org.openhab.voice.mactts/README.md, bundles/org.openhab.voice.marytts/README.md, bundles/org.openhab.voice.picotts/README.md, bundles/org.openhab.voice.voicerss/README.md
Using these Markdown tweaks a small intro will show in Main UI instead of emptiness and a "more" button:
There's also https://github.com/openhab/openhab-webui/pull/1587 for UI add-ons.
=> Show add-on intros in Main UI

bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/provider/ShellyChannelDefinitions.java
This is an attempt to fix the `NullPointerException` mentioned in #13961 and introduced by #13520.
This is completely untested since I do not have any Shellys or have any experience with this binding. So the fix is purely technical and based on the call stack and quick code analysis by looking at the merged PR.
However, when `profile.settings.extSwitch != null && profile.settings.extSwitch.input0 != null && idx == getInteger(profile.settings.extSwitch.input0.relayNum)` would evaluate to `false`, the next parameters for `addChannel()` won't have any significance as the method will just return:
https://github.com/openhab/openhab-addons/blob/4871d6dab197e2e6aabc3d1dfb7d5864eac1fc63/bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/provider/ShellyChannelDefin …
=> [shelly] Fix NullPointerException

bundles/org.openhab.binding.knx/pom.xml, bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/dpt/KNXCoreTypeMapperTest.java
Calimero 2.5.1 was recently released and brings a few fixes needed for further development of KNX data secure feature.
=> [knx] Upgrade Calimero library to release 2.5.1

bundles/org.openhab.persistence.rrd4j/pom.xml
RRD4J base library was updated.
See changes here:
https://github.com/rrd4j/rrd4j/compare/3.8.1...3.8.2
Typically I would not recommend an update shortly before a planned release, but in this case there might be a reason to do it: The interesting part is the update of log4j from 2.17.0 to 2.19.0.
@openhab/add-ons-maintainers Can you pls check if we have a log4j problem here? Log4j 2.7.0 used by the older rrd4j 3.8.1 is affected by the known log4j issue, see https://logging.apache.org/log4j/2.x/security.html
=> [rrd4j] Upgrade base library from 3.8.1 to 3.8.2

bundles/org.openhab.persistence.jdbc/README.md, bundles/org.openhab.persistence.jdbc/pom.xml, bundles/org.openhab.persistence.jdbc/src/main/feature/feature.xml, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcConfiguration.java
See:
- https://dev.mysql.com/doc/relnotes/connector-j/8.0/en/news-8-0-31.html
- https://mvnrepository.com/artifact/com.mysql/mysql-connector-j/8.0.31
Previous upgrade: #13242
=> [jdbc] Upgrade MySQL Connector/J to 8.0.31

bundles/org.openhab.binding.bluetooth.roaming/src/main/java/org/openhab/binding/bluetooth/roaming/internal/RoamingBridgeHandler.java
Very minor checkstyle fix. Part of multiple PR's for bluetooth bundles. Can be merged seperately.
=> [bluetooth.roaming] checkstyle

bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/GraalJSScriptEngineFactory.java, bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/OpenhabGraalJSScriptEngine.java, bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/scriptengine/InvocationInterceptingScriptEngineWithInvocableAndAutoCloseable.java
Fixes #13950.
Completes a few minor improvements and fixes that were left over from #13924:
- Make sure to also unlock the `ReentrantLock` on exceptions from all synchronized `ScriptEngine` methods
- Fix the wrong implementation of `createScriptEngine`
For more details, please have a look at the commits (messages).
This shouldn't change the behaviour of the addon, but anyway I tested this (not extensively), works fine.
@J-N-K I've fixed the `createScriptEngine` implementation.
@jpg0 I made sure that all exceptions are handled and the lock is removed. I also call the `super` methods from their overrides.
=> [jsscripting] Minor fixes & improvements

bundles/org.openhab.binding.dali/README.md, bundles/org.openhab.binding.dali/src/main/java/org/openhab/binding/dali/internal/handler/DaliDt8DeviceHandler.java
adds an example of usage of the channel to the README, and simplifies one method call
follow-up to #14021, applying analogous changes to feedback received on similar PRs for other bindings.
=> [dali] tweak color temperature abs QuantityType fix

bundles/org.openhab.binding.bluetooth.bluez/src/main/java/org/openhab/binding/bluetooth/bluez/internal/BlueZBluetoothDevice.java, bundles/org.openhab.binding.bluetooth.bluez/src/main/java/org/openhab/binding/bluetooth/bluez/internal/DeviceManagerWrapper.java, bundles/org.openhab.binding.bluetooth.bluez/src/main/java/org/openhab/binding/bluetooth/bluez/internal/events/ServiceDataEvent.java, bundles/org.openhab.binding.bluetooth.bluez/src/test/java/org/openhab/binding/bluetooth/bluez/internal/BlueZEventTest.java
Signed-off-by: Leo Siepel [leosiepel@gmail.com](mailto:leosiepel@gmail.com)
- null annotations
- checkstyle
- 
Part of multiple PR's for bluetooth bundles. Can me merged independent 
I see some unused methods, but not sure if they can be removed or if they are part of some (yet to be planned) overhaul/expansion.
=> [bluetooth.bluez] null annotations and checkstyle

bundles/org.openhab.binding.keba/README.md
=> [keba] Fix unit in example for power channel

bundles/org.openhab.binding.fineoffsetweatherstation/README.md, bundles/org.openhab.binding.fineoffsetweatherstation/src/main/resources/OH-INF/thing/gateway.xml
A community member realized, that the used unit for rain-rate was wrong (https://community.openhab.org/t/fine-offset-weather-station-binding-discussion/134167/153) Rain rate is measured in mm/h and so it is not a `VolumetricFlowRate` but a `Speed`.
Additionally, I added some details to the doc.
=> [fineoffsetweatherstation] Fix QuantityType for rain-rate

bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/handler/NanoleafControllerHandler.java
This is a bugfix/enhancement to make sure the caching of the layout (to save it from being recalculated) works better:
- Only save previous layout if indeed painted
- Only save layout from the layout update, not the display state
- Recalculate anyway if current state is null
Signed-off-by: Jørgen Austvik <jaustvik@acm.org>
=> [nanoleaf] More robust caching of layout

CODEOWNERS, bom/openhab-addons/pom.xml, bundles/org.openhab.automation.jsscriptingnashorn/NOTICE, bundles/org.openhab.automation.jsscriptingnashorn/README.md, bundles/org.openhab.automation.jsscriptingnashorn/pom.xml, bundles/org.openhab.automation.jsscriptingnashorn/src/main/feature/feature.xml, bundles/org.openhab.automation.jsscriptingnashorn/src/main/java/org/openhab/automation/jsscriptingnashorn/internal/NashornScriptEngineFactory.java, bundles/org.openhab.automation.jsscriptingnashorn/src/main/java/org/openhab/automation/jsscriptingnashorn/internal/package-info.java, bundles/org.openhab.automation.jsscriptingnashorn/src/test/java/org/openhab/automation/jsscriptingnashorn/NashornScriptEngineFactoryTest.java, bundles/pom.xml, itests/org.openhab.automation.jsscriptingnashorn.tests/NOTICE, itests/org.openhab.automation.jsscriptingnashorn.tests/itest.bndrun, itests/org.openhab.automation.jsscriptingnashorn.tests/pom.xml, itests/org.openhab.automation.jsscriptingnashorn.tests/src/main/java/org/openhab/automation/jsscriptingnashorn/ScriptScopeOSGiTest.java, itests/org.openhab.automation.jsscriptingnashorn.tests/src/main/resources/OH-INF/automation/jsr223/scopeFailure.nashornjs, itests/org.openhab.automation.jsscriptingnashorn.tests/src/main/resources/OH-INF/automation/jsr223/scopeWorking.nashornjs, itests/pom.xml
This add-on allows you to use your older ECMAScript 5.1 code on newer Java versions until the code is migrated to ECMAScript 2021+. It should only be installed for providing backwards compatibility. When writing new code it is preferred to do this using ECMAScript 2021+ for which support is provided by installing the [JavaScript Scripting](https://www.openhab.org/addons/automation/jsscripting/) add-on.
This add-on uses a standalone [Nashorn Engine](https://github.com/openjdk/nashorn) to run ECMAScript 5.1 code. The Nashorn Engine was pre-installed in openHAB 2 and openHAB 3 because it was part of Java. Since Java 15 the Nashorn Engine has been removed from Java.
---
This PR is based on the [JavaScript Scripting (Nashorn) Marketplace …
=> [jsscriptingnashorn] JavaScript Scripting Nashorn Automation 

bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java
I have seen a discussion about warning messages from rrd4j in the 3.4 release discussion thread.
https://community.openhab.org/t/openhab-3-4-release-discussion/142257/130
The current log may look like this:
> Failed to open rrd4j database ‘...’ (java.lang.IllegalStateException)
This not really helpful for identifying the root cause, as rrd4j library uses ```llegalStateException``` at many different places, but with specific error messages.
So we should make use of the method ```getMessage()```. ```toString()``` will actually print class name and message (if available).
This will it make easier to understand issues being reported.
(should IMHO also be cherry picked for potential 3.4.x patch release)
=> [rrd4j] Improve logging of exceptions thrown by getDB

bundles/org.openhab.binding.nuvo/README.md, bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/communication/NuvoCommand.java, bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/handler/NuvoHandler.java
For zones that are configured into a source group, the changing of the source in one zone causes the amplifier to change the selected source in all other zones of that group. However no updates for the other zones are reported by the serial protocol and thus the other group members will now show incorrect information for the source channel.
To address this, the configuration for each zone is retrieved at startup and a map object to track group membership information is populated. When any source channel changes in a zone, the new code will check if that zone is in a group and if so update the source channel for the other zones in the group.
=> [nuvo] Auto update source channel for grouped zones

bundles/org.openhab.binding.bluetooth.generic/src/main/java/org/openhab/binding/bluetooth/generic/internal/BluetoothUnit.java, bundles/org.openhab.binding.bluetooth.generic/src/main/java/org/openhab/binding/bluetooth/generic/internal/CharacteristicChannelTypeProvider.java, bundles/org.openhab.binding.bluetooth.generic/src/main/java/org/openhab/binding/bluetooth/generic/internal/GenericBluetoothHandler.java, bundles/org.openhab.binding.bluetooth.generic/src/test/java/org/openhab/binding/bluetooth/generic/internal/BluetoothUnitTest.java
Signed-off-by: Leo Siepel [leosiepel@gmail.com](mailto:leosiepel@gmail.com)
null annotations
checkstyle.
=> would be good to remove the forbidden units package, but it depends on changes in core. I could not find if they are added yet. 
=> i see several warnings that i'm unable to fix yet (circular dependency with other classes)
Would be cool if i get some advice in how to fix those remaining issues.
Part of multiple PR's for bluetooth bundles. Can be merged independent.
=> [bluetooth.generic] null annotations and SAT warnings

bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewHubHandler.java, bundles/org.openhab.binding.hdpowerview/src/main/resources/OH-INF/i18n/hdpowerview.properties
Related to #11637 after the introduction of scene groups and automations in addition to scenes. This required the use of channel groups for separating these three groups of dynamic channels.
Channel names before release 3.2:
- **Scene:** `1`
Channel names from release 3.2:
- **Scene:** `scenes#1`
- **Scene Group:** `sceneGroups#1`
- **Automation:** `automations#1`
=> [hdpowerview] Remove deprecated scene channels

bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/ConfigStore.java, bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/rest/CommonSetup.java, bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/rest/ItemUIDtoHueIDMappingTests.java, bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/upnp/UpnpTests.java
Alexa currently fails to discover devices which have an internal hue id greater than 255. This appears to be due to the value of the uniqueid which is not in the format described in the hue API when the value exceeds 255.
[Reports of issue and fix tested](https://community.openhab.org/t/oh3-hue-emulation-bug/139875)
=> [hueemulation] Fix for Alexa failing to discover all devices.

README.md
update i18n example command line to ```3.4.0```
For me it makes more sense to use the stable version ```3.4.0```, even if we are on snapshot.
```4.0.0-SNAPSHOT``` would work as well, but always fetch a lot of artifacts.
=> Update i18n command version number

bundles/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/discovery/ChromecastDiscoveryParticipant.java
When ipv6 is configured on the network, Chromecast devices will randomly return ipv4 and/or multiple ipv6 addresses during mdns discovery. As a result of this, the discovered ip address keeps changing which would trigger a thingUpdated call which will then call dispose/initialize, causing the thing to go offline/online.
I'm experiencing this issue and it's also reported in https://community.openhab.org/t/openhab-3-4-release-discussion/142257/98
=> [chromecast] Fix constant disconnections

bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/ControlInfo.java, bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/InfoParser.java, bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/airbase/AirbaseControlInfo.java, bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/airbase/AirbaseModelInfo.java, bundles/org.openhab.binding.daikin/src/test/java/org/openhab/binding/daikin/internal/api/AirbaseControlInfoTest.java, bundles/org.openhab.binding.daikin/src/test/java/org/openhab/binding/daikin/internal/api/ControlInfoTest.java
Adds support for the Alira X and maybe more devices.
Before  devices reported the fan movement in an API parameter `f_dir` that holds combined values for horizontal/vertical moment. This changes alse supports devices that have this movement parameter split into `f_dir_lr` (horizontal) and `f_dir_ud` (vertial).
I added several tests to the parsing of both seperated and combined parameters.
Also fix some very minor checkstyle while at it.
Create a jar for testing on 3.4.0: https://1drv.ms/u/s!AnMcxmvEeupwjp1-KSBYK96ylDpC7A?e=7nxdWo
=> [daikin] Add support for Alira X

bundles/org.openhab.voice.watsonstt/pom.xml
Related to #14088
Triggered by openhab/openhab-core#2994 (where Gson was upgraded to 2.9.1)
JAR for testing: [org.openhab.voice.watsonstt-4.0.0-SNAPSHOT.jar](https://drive.google.com/file/d/1lhTouRY6mKC19BNcJLBTsSRd78oDdOuK/view?usp=sharing)
(I have not been able to test this myself)
=> [watsonstt] Upgrade Gson to 2.9.1

bundles/org.openhab.binding.bluetooth.generic/pom.xml
Related to #14088
Triggered by openhab/openhab-core#2994 (where Gson was upgraded to 2.9.1)
JAR for testing: [org.openhab.binding.bluetooth.generic-4.0.0-SNAPSHOT.jar](https://drive.google.com/file/d/17JRGVtrmlAbVdi69tCplgGRB-UUxkcd_/view?usp=sharing)
(I have not been able to test this myself)
=> [bluetooth.generic] Upgrade Gson to 2.9.1

bundles/org.openhab.binding.dbquery/pom.xml
Related to #14088
Triggered by openhab/openhab-core#2994 (where Gson was upgraded to 2.9.1)
Previous upgrade: #12798
JAR for testing: [org.openhab.binding.dbquery-4.0.0-SNAPSHOT.jar](https://drive.google.com/file/d/1kGMMl0ogFpqUTMoapzB9lFfA_aHEsVmA/view?usp=sharing)
(I have not been able to test this myself)
=> [dbquery] Upgrade Gson to 2.9.1

bundles/org.openhab.persistence.influxdb/pom.xml
Related to #14088
Triggered by openhab/openhab-core#2994 (where Gson was upgraded to 2.9.1)
Previous upgrade: #12772
JAR for testing: [org.openhab.persistence.influxdb-4.0.0-SNAPSHOT.jar](https://drive.google.com/file/d/1j8avqdE3sWtfXoq-n0Nus1NLZvk53PwF/view?usp=sharing)
(I have not been able to test this myself)
=> [influxdb] Upgrade Gson to 2.9.1

bundles/org.openhab.automation.groovyscripting/README.md, bundles/org.openhab.automation.groovyscripting/pom.xml
Updates Groovy from 3.0.13 to 4.0.7.
For Groovy 4.0 release notes, see:
https://groovy-lang.org/releasenotes/groovy-4.0.html#releasenotes
=> [groovyscripting] Update Groovy to 4.0.7

bundles/org.openhab.binding.bondhome/src/main/java/org/openhab/binding/bondhome/internal/api/BondDeviceType.java, bundles/org.openhab.binding.bondhome/src/main/java/org/openhab/binding/bondhome/internal/api/BondHttpApi.java, bundles/org.openhab.binding.bondhome/src/main/java/org/openhab/binding/bondhome/internal/discovery/BondDiscoveryService.java, bundles/org.openhab.binding.bondhome/src/main/java/org/openhab/binding/bondhome/internal/handler/BondDeviceHandler.java, bundles/org.openhab.binding.bondhome/src/main/resources/OH-INF/i18n/bondhome.properties
I just got a bond bridge today. I tried to use the binding and ran into several fatal errors that stopped the binding from functioning:
1. When I changed the IP of the bridge the binding would fail connecting to the old address. An error in the translation file caused an exception when calling setBridgeOffline(),
2. In my bridge, I set up a 'Light' aka 'LT' item and this is apparently not supported by BondDeviceType. This caused the discovery service to fail when the BondDevice with a null 'type' was encountered.
3. The list of actions in one or more BondDevice objects contained null entries that would cause an NPE in deleteExtraChannels()
=> [bondhome] Fix fatal Null Pointer errors

bundles/org.openhab.binding.mqtt/src/main/resources/OH-INF/thing/thing-types.xml
The documentation and java code set the default for `shutdownRetain` to true, but the thing-types.xml sets it to false. I came across a bug when I didn't specify `shutdownRetain` in my mqtt bridge config, and it appears to have been set to false, when I expected it to default to true. This resulted in an unexpected behaviour.
The workaround is to explicitly set `shutdownRetain` to true in the thing config, until this PR is merged.
=> [mqtt] Fix shutdownRetain default value

itests/org.openhab.binding.mqtt.homeassistant.tests/itest.bndrun, itests/org.openhab.binding.mqtt.homie.tests/itest.bndrun, itests/org.openhab.binding.nest.tests/itest.bndrun, pom.xml
This is the version used in the feature provided by openhab-core.
Depends on openhab/openhab-core#3284
=> Update Jackson version to 2.14.1

bundles/org.openhab.automation.jsscripting/pom.xml, bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/OpenhabGraalJSScriptEngine.java
- Remove `org.ow2.asm` from dependency, as it is not required by GraalJS since 20.3.0
- Remove `org.graalvm.js`/js-launcher dependency, as we don't need the JavaScript command line interpreter
- ~Disable Nashorn compatiblity mode as it's additional functionality is not used by openhab-js and very unlikely used by any user.~ Don't disable Nashorn compat mode as the library relies on some Nashorn accessors: https://github.com/oracle/graaljs/blob/master/docs/user/NashornMigrationGuide.md#accessors.
- **Enable new ECMAScript-2022 features like private properties for classes**
**Note: I also wanted to upgrade to GraalJS 22.3.0, but it is failing with the same error message as on OpenJDK 11 on armv7l, so we cannot upgrade :cry:** 
I have tested this change on these system/JDK combinations and …
=> [jsscripting] Upgrade to ECMAScript 2022 & Dependency improvements

bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/OpenhabGraalJSScriptEngine.java
Performance is improved by caching parts of the global code that is injected into each new script, see https://github.com/openhab/openhab-addons/pull/14113/commits/e4c95471fba2416a2c3da8b4f07640638048c9cf.
Currently, only the `@jsscripting-globals.js` is cached, but if you disable the injection of globals into UI scripts inside the UI's settings, you can see the effect of this code caching: scripts are extremely fast evaluated, even on my Pi 3 the evaluation time is nearly zero.
For some background, see:
- https://www.graalvm.org/22.0/reference-manual/embed-languages/#code-caching-across-multiple-contexts
- https://www.graalvm.org/sdk/javadoc/
I would like to also cache the library code, but I am not sure how to do this while keeping the ability to reload the library during runtime of the …
=> [jsscripting] Improve performance & reduce memory usage

bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/UniFiController.java, bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/UniFiControllerRequest.java, bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/cache/UniFiCache.java, bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/cache/UniFiControllerCache.java, bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/cache/UniFiDeviceCache.java, bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/dto/UnfiPortOverrideJsonObject.java, bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/dto/UniFiDevice.java, bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/dto/UniFiPortTuple.java, bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/dto/UniFiSwitchPorts.java, bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/util/UnfiPortOverrideJsonElementDeserializer.java, bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/handler/UniFiBaseThingHandler.java, bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/handler/UniFiControllerThingHandler.java, bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/handler/UniFiPoePortThingHandler.java, bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/handler/UniFiThingDiscoveryService.java, bundles/org.openhab.binding.unifi/src/main/resources/OH-INF/i18n/unifi.properties
- It seems to throw an exception when updating internal cache. It can happen if you have a switch that has both PoE ports and other PoE ports or data in the port override.
- Fixed logout, should be POST instead of GET.
- Fixed typo in channel-type.config.unifi.poeEnable.mode.option.pasv24 should be without appending v.
- Removed compiler warnings.
=> [unifi] Fix PoE bug with combination of other data/ports

bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/channeltypes.xml
Add some categories and semantic tags where missing and obvious.
=> [miele] Add categories and semantic tags

bundles/org.openhab.automation.jsscripting/pom.xml, bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/GraalJSScriptEngineFactory.java, bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/OpenhabGraalJSScriptEngine.java, bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/ScriptExtensionModuleProvider.java, bundles/org.openhab.automation.jsscripting/src/main/resources/OH-INF/config/config.xml, bundles/org.openhab.automation.jsscripting/src/main/resources/OH-INF/i18n/jsscripting.properties
For previous discussion see #14113.
This PR extends the code caching to the version of the openHAB JavaScript library (openhab-js) that is included in the JS Scripting addon.
A new configuration option is introduced to allow the user to disable usage of the internal openhab-js library and instead load it from the file system.
~**Note: I am currently not super happy with the description and the label of that new configuration option, I would like to get some feedback on them.**~
Code caching of the openhab-js injection brings great performance improvements as the evaluation of the pretty large openhab-js codebase takes some time. 
Note: it is not possible to cache the `Object.assign(this, require("openhab");` therefore I had to take the way of creating an injection script at openhab-js. …
=> [jsscripting] Cache openhab-js injection to improve performance

bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/server/DataPointBool.java, bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/server/DataPointLongValue.java, bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/server/DataPointValue.java, bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/server/KnxNetFrame.java
Reduce number of warnings, mainly using ```"constant".equals(var)``` instead of ```var.equals("constant")```. This is considered to be better, as "constant".equals(null) is null-safe and always returns false. (Though it should not make a difference, we have the annotation ```NonNullByDefault``` in place for the parameters).
Adding ```final``` makes the tool recognize the byte Arrays as constants (though it is not really a constant, but constant ref to a modifiable buffer).
=> [ism8] Fix SAT warnings

bundles/org.openhab.automation.jsscripting/README.md, bundles/org.openhab.automation.jsscripting/pom.xml, bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/DebuggingGraalScriptEngine.java, bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/OpenhabGraalJSScriptEngine.java
- Fixes the regression from https://github.com/openhab/openhab-addons/pull/14135#issuecomment-1369231126, that `require('openhab');` does not work anymore when it is not installed in node_modules
- Fixes the cached openhab-js injection: did not work because of wrong webpack commandline args in the pom (wrong entrypoint)
- Log a stacktrace on a `IllegalArgumentException` to allow the user to find the line of JS code where he passed a wrong argument
@digitaldan This is the fix.
=> [jsscripting] Fix regressions from #14135 & Log stack on `IllegalArgumentException`

bundles/org.openhab.binding.bondhome/README.md, bundles/org.openhab.binding.bondhome/src/main/feature/feature.xml, bundles/org.openhab.binding.bondhome/src/main/java/org/openhab/binding/bondhome/internal/BondHomeBindingConstants.java, bundles/org.openhab.binding.bondhome/src/main/java/org/openhab/binding/bondhome/internal/api/BondDeviceType.java, bundles/org.openhab.binding.bondhome/src/main/resources/OH-INF/binding/binding.xml, bundles/org.openhab.binding.bondhome/src/main/resources/OH-INF/i18n/bondhome.properties, bundles/org.openhab.binding.bondhome/src/main/resources/OH-INF/thing/Light.xml
Follow up to #14103 
Implement the missing device type for 'Light' in BondDeviceType and add the appropriate thing definition.
=> [bondhome] Implement missing 'Light' device type

bundles/org.openhab.binding.neohub/src/main/java/org/openhab/binding/neohub/internal/NeoHubException.java, bundles/org.openhab.binding.neohub/src/main/java/org/openhab/binding/neohub/internal/NeoHubHandler.java, bundles/org.openhab.binding.neohub/src/main/java/org/openhab/binding/neohub/internal/NeoHubSocket.java, bundles/org.openhab.binding.neohub/src/main/java/org/openhab/binding/neohub/internal/NeoHubSocketBase.java, bundles/org.openhab.binding.neohub/src/main/java/org/openhab/binding/neohub/internal/NeoHubWebSocket.java, bundles/org.openhab.binding.neohub/src/test/java/org/openhab/binding/neohub/test/NeoHubJsonTests.java, bundles/org.openhab.binding.neohub/src/test/java/org/openhab/binding/neohub/test/NeoHubProtocolTests.java
Resolves #13829
As mentioned in #13829 the bridge sporadically goes offline (due to 'Null or invalid response'), and it remains offline until the next polling cycle produces a valid response, whereupon it goes online again.
Apparently the reason for this is that there is a bug in the NeoHub, whereby it does indeed sporadically produce empty response packages!!
Note: the NeoHub does produce a response so it **is** technically online, however the response is empty, so the binding has no data to update the channels.
The issue is being discussed on the [HeatMiser Developer portal](https://dev.heatmiser.com/t/neohub-produces-sporadic-empty-responses/485), and it seems the solution (work around) is to simply repeat the command immediately so the NeoHub produces a non empty response. …
=> [neohub] Recover faster if NeoHub produces empty responses

bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/rest/mocks/DummyMetadataRegistry.java
Fixes #14153.
This fixes the Hue Emulation tests (and in consequence the full addons build) after core change https://github.com/openhab/openhab-core/pull/3298.
For the implementation used in the test, just have a look at the linked core PR.
/cc @jlaur
=> [hueemulation] Fix tests after core change

pom.xml
Related to #14154, see https://github.com/openhab/openhab-addons/pull/14154#issuecomment-1371319055
=> Exclude 3rdparty directories from license header generation

bundles/org.openhab.binding.ecobee/src/main/resources/OH-INF/thing/thing-types.xml
Resolves #8029 
This binding has a lot of channels. Even though many are advanced, the number of visible channels still can be overwhelming, especially to new users. This PR adds more advanced channels to reduce the clutter of channels that are likely to not be used by most users.
=> [ecobee] Make more channels advanced

bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/DummyHomekitAccessory.java
lol I'm surprised they've worked as well as they have in the past. basically only the AccessoryInformationService was getting exposed before, accidentally. now we really do publish the full set of original characteristics, just with dummy values.
=> [homekit] properly expose services from dummy accessories

bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/handler/ZonePlayerHandler.java
Contained URL is now HTTPS instead of HTTP before.
=> [sonos] Correct identification of tuneIn started from Alexa

bundles/org.openhab.binding.mycroft/src/main/java/org/openhab/binding/mycroft/internal/MycroftHandlerFactory.java, bundles/org.openhab.binding.souliss/src/main/java/org/openhab/binding/souliss/internal/handler/TypicalCommonMethods.java
Fix incorrectly formatted license headers detected by `mvn license:format`.
Related to #14154
=> Fix incorrectly formatted license headers

bundles/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromecastAudioSink.java, bundles/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromecastCommander.java, bundles/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromecastEventReceiver.java
When the app running on the ChromeCast was stopped by switching the ON/OFF stop channel, the binding tried to stop the app without checking if it actually runs. Because the app wasn;t running, it gives an error and the thing goes offline.
This PR adds a check, and also restructured the class a bit.
Also when a command was givfen to play media by URL, but the URL was invalid or could not be loaded by the ChromeCast, the thing went offline for ~10 seconds. That mechanism is also change so that the Thing only goes offline when there is an actuall IOException, in other case it logs a warning about unplayable url.
3.4.1 Test JAR is here: https://1drv.ms/u/s!AnMcxmvEeupwjp4ILqWfPxAy7qJh4g?e=43fQde
Fixes: …
=> [chromecast] Fix thing go offline after stop command

bundles/org.openhab.binding.doorbird/src/main/java/org/openhab/binding/doorbird/internal/DoorbirdHandlerFactory.java, bundles/org.openhab.binding.doorbird/src/main/java/org/openhab/binding/doorbird/internal/api/DoorbirdAPI.java, bundles/org.openhab.binding.doorbird/src/main/java/org/openhab/binding/doorbird/internal/audio/ConvertedInputStream.java, bundles/org.openhab.binding.doorbird/src/main/java/org/openhab/binding/doorbird/internal/audio/DoorbirdAudioSink.java, bundles/org.openhab.binding.doorbird/src/main/java/org/openhab/binding/doorbird/internal/handler/DoorbellHandler.java
Add audiosink capability to a doorbird thing.
You can play WAV file, it will be converted on the fly to the ULAW format.
Also tested with TTS service, and it works, provided that the TTS service gives a AudioStream wich support mark/reset operation (this is the case if the InputStream is build from an intermediary file)
@mhilbush, as discussed some month ago, it is quite functionnal, although the quality is not fantastic.
I used it during halloween with success... With a rule sending a demon laugh when detecting movement.
The look on the kids worth the hours passed on it 😇
=> [doorbird] Add audiosink

bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/EcobeeBindingConstants.java, bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/api/EcobeeApi.java, bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/dto/thermostat/DateDeserializer.java, bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/dto/thermostat/InstantDeserializer.java, bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/dto/thermostat/LocalDateTimeDeserializer.java, bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/dto/thermostat/RuntimeDTO.java, bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/dto/thermostat/ThermostatDTO.java, bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/dto/thermostat/WeatherDTO.java, bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/dto/thermostat/WeatherForecastDTO.java, bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/handler/EcobeeThermostatBridgeHandler.java, bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/handler/EcobeeUtils.java
The Ecobee API returns all date/time fields formatted as "yyyy-MM-dd HH:mm:ss". Most of those date/times are in UTC time, however a couple are in local time. This PR correctly handles both cases by:
- introducing a Gson DateDeserializer that handles the dates when they're in UTC time
- introduces a new method that handles the dates when they're in local time
Reference: https://community.openhab.org/t/ecobee-binding-v2/97733/225
Signed-off-by: Mark Hilbush [mark@hilbush.com](mailto:mark@hilbush.com)
=> [ecobee] Fix issue with UTC and local dates

bundles/org.openhab.automation.jrubyscripting/README.md, bundles/org.openhab.binding.amazondashbutton/README.md, bundles/org.openhab.binding.digitalstrom/README.md, bundles/org.openhab.binding.dwdunwetter/README.md, bundles/org.openhab.binding.homematic/README.md, bundles/org.openhab.binding.mihome/README.md, bundles/org.openhab.binding.modbus/README.md, bundles/org.openhab.binding.nibeuplink/README.md, bundles/org.openhab.binding.powermax/README.md, bundles/org.openhab.binding.rfxcom/README.md, bundles/org.openhab.binding.russound/README.md, bundles/org.openhab.binding.solaredge/README.md, bundles/org.openhab.binding.sonyaudio/README.md, bundles/org.openhab.binding.tacmi/README.md, bundles/org.openhab.binding.teleinfo/README.md, bundles/org.openhab.binding.velux/README.md, bundles/org.openhab.binding.wolfsmartset/README.md, bundles/org.openhab.binding.yamahareceiver/README.md, bundles/org.openhab.io.homekit/README.md, bundles/org.openhab.transform.jinja/README.md, bundles/org.openhab.transform.regex/README.md, bundles/org.openhab.transform.scale/README.md, bundles/org.openhab.transform.xpath/README.md, bundles/org.openhab.voice.googlestt/README.md
Reduce number of SAT warnings in README.md files, see global analysis report.
Targets "checkstyle" "MarkdownCheck", previously showing 45 findings.
=> Fix Markdown warnings in README.md

bundles/org.openhab.binding.squeezebox/README.md, bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/SqueezeBoxBindingConstants.java, bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/discovery/SqueezeBoxPlayerDiscoveryParticipant.java, bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxNotificationListener.java, bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxPlayerEventListener.java, bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxPlayerHandler.java, bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxServerHandler.java, bundles/org.openhab.binding.squeezebox/src/main/resources/OH-INF/thing/thing-types.xml
Resolves #13353 
Added channels for the following:
- albumartist
- trackartist
- band
- conductor
- composer
=> [squeezebox] Add new channels for additional tags

bundles/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/GardenaSmartWebSocket.java
On server timeouts, it's possible for multiple minutes to elapse between receiving the last pong on the old connection and attempting to send the next ping on the new connection. If that time span exceeded 5 minutes, the binding went into a minutely reconnection loop, because it never attempted to send a ping anymore, which led to lastPong not being updated anymore.
To fix this, replace the timing dependent timestamp handling by a simple counter which counts how many consecutive ping attempts didn't receive an answer, and closing the connection after 5 unsuccessful ping attempts. That new counter is now also reset whenever the connection is restarted.
Fixes #14188
=> [gardena] Fix server ping timeout logic

bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/handler/HomematicThingHandler.java
When changing an enum value in the configuration, we used the wrong data type: while the value in the OH config is a string (the 'option value' - see HomematicThingHandler::getValueForConfiguration), internally we use an integer (the 'option index'), so we have to do the option value -> option index conversion when applying the new value. This especially was a problem for HM-MOD-EM-8 devices, which check the CHANNEL_FUNCTION enum value as part of their initialization routine. When disabling/enabling them after changing the CHANNEL_FUNCTION enum value, they went offline, because their initialization failed due to a NumberFormatException (via
HomematicThingHandler::doInitializeInBackground -> HmChannel::checkForChannelFunctionChange ->
HmChannel::getCurrentFunction)
=> [homematic] Fix updating enum config values

bundles/org.openhab.voice.mimictts/README.md, bundles/org.openhab.voice.mimictts/src/main/java/org/openhab/voice/mimic/internal/AutoDeleteFileAudioStream.java, bundles/org.openhab.voice.mimictts/src/main/java/org/openhab/voice/mimic/internal/MimicConfiguration.java, bundles/org.openhab.voice.mimictts/src/main/java/org/openhab/voice/mimic/internal/MimicTTSService.java, bundles/org.openhab.voice.mimictts/src/main/resources/OH-INF/config/config.xml, bundles/org.openhab.voice.mimictts/src/main/resources/OH-INF/i18n/mimictts.properties, bundles/org.openhab.voice.mimictts/src/main/resources/OH-INF/i18n/mimictts_fr.properties
Fix :
- ssml not working
- add an option to store the audio on a file before sending it to openhab. It enables audiosink based on the audio servlet to play the sound (the servlet requires the getClonedStream method, unavailable with a pure streaming approach). The files are stored in the user data directory and deleted as soon as possible (stream close detection).
- fix error with voice name not encoded
Thanks [rotec52](https://community.openhab.org/t/mimic-text-to-speech/137040/9?u=dalgwen) for spotting it and providing solution.
=> [mimictts] Fix ssml and playing from audiosinks using the audio servlet

bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/GreeBindingConstants.java, bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/GreeException.java, bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/discovery/GreeDeviceFinder.java, bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/handler/GreeAirDevice.java
- Fix checkstyle
- Allow wider range of temperatures
Previously the binding limits the setpoint temperature from 16-30. As devices have different operating range, it would be better to have a wider allowed range and adjust it with sitemap minValue/ maxValue according to your specific device.
Tested and confirmed. Devices gracefully ignore temperatures outside of the operating range. So regressions or device mallfunction is not to be expected.
Fixes: https://github.com/openhab/openhab-addons/issues/14207
=> [gree] Allow wider temperature range

bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/MieleBridgeHandler.java
The main intention here was to fix some [MulticastSocket](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/net/MulticastSocket.html) deprecation warnings after upgrading to Java 17 - see description in #14198. However, while testing the refactoring needed for this, I came across some other issues that I have fixed as well:
- The multicast listener thread did not allow to be properly interrupted and thus would keep running after stopping or uninstalling the binding. I noticed this when replacing the JAR a few times and ended up with multiple threads in different versions running simultaneously.
- The conversion from byte buffer to `String` was not correct and the resulting string was filled up with trailing null-bytes. This could be seen in logs with log level **trace**, …
=> [miele] Improve multicast implementation

bundles/org.openhab.binding.gree/src/main/resources/OH-INF/thing/thing-types.xml
Fix comment: https://github.com/openhab/openhab-addons/pull/14217#issuecomment-1382716371
=> [gree] Fix thing-type min state

bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java
- Avoid IAE thrown in constructor of `FetchRequest` called by `createFetchRequest` method (e.g. invalid start/end time given)
- Enable requesting future time ranges including boundary values via REST API
See https://github.com/rrd4j/rrd4j/blob/85183713741c648b88926ed3085c4dd87fd9016f/src/main/java/org/rrd4j/core/FetchRequest.java
=> [rrd4j] Avoid IAE thrown if e.g. invalid start/end time given

bundles/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/lacrosse/LaCrosseTemperatureSensorHandler.java, bundles/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/lacrosse/LgwSensorHandler.java, bundles/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/lacrosse/Tx22ReadingConverter.java, bundles/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/util/StringUtils.java
- Fixes the rain channel having a wrong value (divide instead of multiply)
- Removes dependency of apache.commons.
Allready tested openHAB 3.4.2 jar here: https://1drv.ms/u/s!AnMcxmvEeupwjqVCE_YtH3yeZG5hXA?e=a1d7Hv
Fixes: https://github.com/openhab/openhab-addons/issues/10358
=> [jeelink] Fixed wrong TX22 rain value

bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/MqttChannelTypeProvider.java
I was getting the following errors in my log every time I tried to open a thing in MainUI shortly after booting:
```
2023-01-10 18:47:37.961 [ERROR] [internal.JSONResponseExceptionMapper] - Unexpected exception occurred while processing REST request.
java.lang.ArrayIndexOutOfBoundsException: Index 4052 out of bounds for length 4052
at java.util.HashMap.valuesToArray(HashMap.java:973) ~[?:?]
at java.util.HashMap$Values.toArray(HashMap.java:1050) ~[?:?]
at java.util.ArrayList.addAll(ArrayList.java:670) ~[?:?]
at org.openhab.core.thing.type.ChannelTypeRegistry.getChannelTypes(ChannelTypeRegistry.java:57) ~[?:?]
```
I was able to track it down to the MqttChannelTypeProvider. I presume that some component is just spamming a discover topic with the same config over and over, so the `types` …
=> [mqtt] fix thread concurrency issue with type provider

bundles/org.openhab.binding.nuvo/README.md, bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/NuvoBindingConstants.java, bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/handler/NuvoHandler.java
Publish the ALLOFF event to all button channels for use in source rules. ALLOFF is sent by the amplifier 5 minutes after all zones are switched off.
Also follow-up to #14012. Add the missing feature that will update the other group zone's source channel when a source channel receives a command.
=> [nuvo] Publish ALLOFF event for use in source rules

bundles/org.openhab.binding.evcc/README.md, bundles/org.openhab.binding.evcc/src/main/java/org/openhab/binding/evcc/internal/EvccBindingConstants.java, bundles/org.openhab.binding.evcc/src/main/java/org/openhab/binding/evcc/internal/EvccHandler.java, bundles/org.openhab.binding.evcc/src/main/java/org/openhab/binding/evcc/internal/api/dto/Loadpoint.java, bundles/org.openhab.binding.evcc/src/main/java/org/openhab/binding/evcc/internal/api/dto/Result.java, bundles/org.openhab.binding.evcc/src/main/java/org/openhab/binding/evcc/internal/api/dto/Status.java, bundles/org.openhab.binding.evcc/src/main/resources/OH-INF/i18n/evcc.properties, bundles/org.openhab.binding.evcc/src/main/resources/OH-INF/thing/thing-types.xml
Fixes #14231.
evcc changed the API with version 0.111.0, see https://github.com/evcc-io/evcc/discussions/5522.
This API change breaks the binding:
> - all indexes become 1-based (instead of 0-based for REST and 1-based for MQTT)
> - SoC becomes Soc
I have also added a new channel for the home battery's capacity which is a new value available over the API.
=> [evcc] Adjust to breaking API change & Add new channel

bundles/org.openhab.binding.openwebnet/README.md
Updated section on shutter position with info on the automatic calibration's reliance on the actuator's automatic stop message, and that for older actuator's manual setting of shutterRun is required.
=> [openwebnet] Updated section in README on shutter position with info on the automatic calibration

bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcPostgresqlDAO.java
This patch adds "upsert" behavior for PostgreSql >= 9.5, overwriting the previously stored value instead of raising an exception, when an existing timestamp is provided in a PUT request to the persistence endpoint.
This is the default behavior in the parent JdbcBaseDAO (and thus MySQL since it does not override it) and is equivalent to MySQL: `ON DUPLICATE KEY UPDATE VALUE`
see: https://www.postgresql.org/docs/9.5/sql-insert.html
This is only applied if the PostgreSQL version is >= 9.5, therefore it should not change the behavior for installations with legacy versions and should be backwards compatible with those versions.
Since `ModifiablePersistenceService` was only recently implemented, I would not consider it a breaking change either, rather than implementing consistent behavior …
=> [jdbc] Perform upsert on conflict like the default for MySQL (PostgreSQL >=9.5)

bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/communication/RotelConnector.java, bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/communication/RotelIpConnector.java, bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/communication/RotelSerialConnector.java, bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/communication/RotelSimuConnector.java
Previous code was not working in Java 17.
A thread should not be started after being interrupted.
Fix #14264
=> [rotel] Fix reader thread handling

bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/ComponentChannel.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/AbstractComponent.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Vacuum.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/config/dto/AbstractChannelConfiguration.java
openHAB doesn't have the concept of "enabled by default", since _everything_ is technically "disabled" until you link it to an item. It seems devices use disabled by default on less common entities, such as zigbee2mqtt marking a binary_sensor as a "backup" method to an update entity for when an update is available, or a sensor as a "backup" method to a select entity. So in that case, just hiding these channels unless the user clicks "Show Advanced" seems to map best.
=> [mqtt.homeassistant] Mark disabled by default components as advanced channels

bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/ComponentFactory.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/DeviceTrigger.java, bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/AbstractComponentTests.java, bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/DeviceTriggerTests.java
A bit more work for this one, since this is the first trigger channel in the HASS binding
=> [mqtt.homeassistant] add support for DeviceTrigger component

bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/WemoBindingConstants.java, bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/WemoHandlerFactory.java, bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoBaseThingHandler.java, bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoCoffeeHandler.java, bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoCrockpotHandler.java, bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoDimmerHandler.java, bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoHandler.java, bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoHolmesHandler.java, bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoInsightHandler.java, bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoLightHandler.java, bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoMakerHandler.java, bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoMotionHandler.java, bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoSwitchHandler.java, itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/handler/test/WemoHandlerOSGiTest.java, itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/handler/test/WemoInsightHandlerTest.java
Fixes #14162.
Tested on my system for a few weeks now and didn't see any blocked threads since. Also my system in general is now stable and responsive after running for more than a week without restarts.
JARs for testing:
- [org.openhab.binding.wemo-3.4.2-SNAPSHOT.jar](https://drive.google.com/file/d/1q_RcE8JnqDQeJI6c5RkGcDZuP8Uyo_Qc/view?usp=sharing)
- [org.openhab.binding.wemo-4.0.0-SNAPSHOT.jar](https://drive.google.com/file/d/1ASIeKW1wopgw0Ac9DQiRwyY1yi-cUgEG/view?usp=sharing)
=> [wemo] Fix stability issues

bundles/org.openhab.binding.unifi/README.md, bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/UniFiBindingConstants.java, bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/UniFiVoucherChannelConfig.java, bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/UniFiController.java, bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/cache/UniFiControllerCache.java, bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/cache/UniFiVoucherCache.java, bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/dto/UniFiSite.java, bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/dto/UniFiVoucher.java, bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/util/UniFiVoucherInstanceCreator.java, bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/handler/UniFiSiteThingHandler.java, bundles/org.openhab.binding.unifi/src/main/resources/OH-INF/config/config.xml, bundles/org.openhab.binding.unifi/src/main/resources/OH-INF/thing/thing-types.xml
This PR adds support for creating guest wifi hotspot vouchers. The PR adds channels to the site thing for showing the next available hotspot voucher and triggering generation for new hotspot vouchers. Channel configuration paramaters allow tailoring the specifications of the vouchers generated.
=> [unifi] Guest wifi vouchers

bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudClient.java, bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudService.java
=> [openhabcloud] Reconnection Fixes

bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/handler/ChannelActuatorPosition.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/things/VeluxProductPosition.java
In #13212 we implemented the new API calls, but it seems that Somfy devices do not support use of this new API.
So this PR reverts to the old API calls for Somfy devices
=> [velux] Do not use new API on Somfy devices

bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaAccountHandler.java
If an account reaches the threshold of failed api calls, it is set to OFFLINE.
Once this happens, it will immediately go to OFFLINE again every time that it becomes back ONLINE.
This causes the vehicle to stay online and thus leads to vampire drain.
This PR resets the counter, so that the Thing stays ONLINE until the threshold is reached again.
This fix might quality as a backport to 3.4.x.
=> [tesla] Fix account going offline every few seconds

bundles/org.openhab.binding.orbitbhyve/src/main/java/org/openhab/binding/orbitbhyve/internal/model/OrbitBhyveDevice.java
Fixes #14307 
The binding throws a NumberFormatException when parsing the Json object returned from the "devices" API endpoint. The field is defined as an `int` in the DTO, but the B-Hyve API can return either 
```
“wifi_version”:0
```
or something like
```
“wifi_version”:“1.4.0”
```
The `wifi_version` is not used in the binding, nor do I see any reason why it might be used in the future. So from my perspective the easiest thing to do is to just delete it from the DTO.
I believe this should be a candidate to cherry-pick if there's another 3.4.x patch release.
=> [orbitbhyve] Fix for NumberFormatException when parsing json object

bundles/org.openhab.binding.mielecloud/src/main/resources/OH-INF/addon/addon.xml
Fix i18n tags in addon.xml so binding name and description displays correctly in binding list.
=> [mielecloud] Fix i18n in addon.xml

bundles/org.openhab.binding.jeelink/src/main/resources/OH-INF/addon/addon.xml, bundles/org.openhab.binding.nanoleaf/src/main/resources/OH-INF/addon/addon.xml, bundles/org.openhab.binding.pushbullet/src/main/resources/OH-INF/addon/addon.xml, bundles/org.openhab.binding.velux/src/main/resources/OH-INF/addon/addon.xml
Related to #14310 
It looks like there were only 4 others.
=> [i18n] Fix incorrect i18n tags in addon.xml

bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/connection/HueBridge.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/exceptions/EmptyResponseException.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueBridgeHandler.java
=> [hue] Handle unexpected empty response from API

bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcMapper.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcPersistenceService.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcPostgresqlDAO.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/dto/Column.java
It should fix https://github.com/openhab/openhab-addons/issues/12315 
This patch fixes two issues in the PostgreSQL implementation of the JDBC service addon:
The  closest equivalent type to [MySQL](https://dev.mysql.com/doc/refman/8.0/en/datetime.html) `TIMESTAMP` is `TIMESTAMPTZ`in [PostgreSQL](https://www.postgresql.org/docs/current/datatype-datetime.html)  (`timestamp with time zone`).
With TIMESTAMPTZ, PostgreSQL converts the input timestamp to UTC, stores the UTC timestamp, and converts back to the timezone of the session on query time. Exactly what [MySQL does](https://dev.mysql.com/doc/refman/8.0/en/datetime.html) with `TIMESTAMP`.
In contrast, the PG `TIMESTAMP` type (the default we had up to now) discards any time zone information in the input timestamp and thus stores local time …
=> [jdbc] working version of PG schema check and TIMESTAMPTZ as default to match MySQL

bundles/org.openhab.binding.telegram/src/main/java/org/openhab/binding/telegram/internal/action/TelegramActions.java
Commit 1d23c32 broke sending underscore character in messages #14204
This PR reverts commit 1d23c32 and fix #14204.
Signed-off-by: Daniel Schröter d.schroeter@gmx.de
=> [telegram] Invalid escape of underscore character when sending messages (Revert "Solves issue #11691 (#13758)")

bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/communication/NuvoConnector.java, bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/handler/NuvoHandler.java
This PR fixes a long-standing bug when using the Essentia G amplifier. After all zones are switched off, the amplifier will go into a low power mode after 5 minutes. Once in this mode a command from the biding to turn on any zone will not be processed by the amplifier unless it is sent more than once. To fix this problem, the binding will track when the low power mode is entered and then repeat any zone on commands twice to force the amplifier to wake and process the command.
=> [nuvo] Fix Essentia G standby mode wake-up

bundles/org.openhab.binding.rfxcom/README.md, bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComFanMessage.java
Small Improvement to the NOVY Fan support in RFXCOM Binding.
Added MOOD_LIGHT support in the CommandString
Snapshot to be found at: https://1drv.ms/u/s!AqvjAJaugtJEkoUaP3lEvOeGJmXofw?e=wGZSWJ
Signed-off-by: Frank Croket [Frank.Croket@outlook.com](mailto:frank.croket@outlook.com)
=> [RFXCOM] add MOOD_LIGHT for NOVY Fan

pom.xml, tools/static-code-analysis/spotbugs/suppressions.xml
Findbugs can't properly handle `if (foo instanceof Bar bar)`. The same suppression is done in core.
=> Fix findbugs instanceof pattern matching

bundles/org.openhab.binding.airquality/src/main/resources/OH-INF/addon/addon.xml
Previously in binding.xsd:
```xml
<xs:element name="description" type="xs:string" minOccurs="0"/>
```
In addon.xsd:
```xml
<xs:element name="description" type="xs:string"/>
```
This had the following consequence:
```
2023-02-03 22:04:49.015 [WARN ] [ig.xml.osgi.XmlDocumentBundleTracker] - The XML document '/OH-INF/addon/addon.xml' in module 'org.openhab.binding.airquality' could not be parsed: The node 'description' is missing!
---- Debugging information ----
message             : The node 'description' is missing!
class               : org.openhab.core.addon.xml.internal.AddonInfoXmlResult
required-type       : org.openhab.core.addon.xml.internal.AddonInfoXmlResult
converter-type      : org.openhab.core.addon.xml.internal.AddonInfoConverter
path                : /addon
line number …
```
=> [airquality] Add missing binding description

bundles/org.openhab.binding.mail/README.md, bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/internal/action/SendMailActions.java
Keep old names for backward compatibility (DSL rule).
Actions names are now consistent over all rule engines.
=> [mail] Make actions names for DSL rules consistent with documentation

bundles/org.openhab.binding.unifi/README.md, bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/handler/UniFiClientThingHandler.java, bundles/org.openhab.binding.unifi/src/main/resources/OH-INF/thing/thing-types.xml
In order to support UoM, the **rssi** channel type is migrated from `Number` to `Number:Power`.
=> [unifi] Add UoM support for RSSI channel

bundles/org.openhab.binding.boschshc/src/main/resources/OH-INF/addon/addon.xml, bundles/org.openhab.binding.ecotouch/src/main/resources/OH-INF/addon/addon.xml, bundles/org.openhab.binding.gpio/src/main/resources/OH-INF/addon/addon.xml, bundles/org.openhab.binding.haywardomnilogic/src/main/resources/OH-INF/addon/addon.xml, bundles/org.openhab.binding.playstation/src/main/resources/OH-INF/addon/addon.xml, bundles/org.openhab.binding.surepetcare/src/main/resources/OH-INF/addon/addon.xml
According to XSD:
```xml
<xs:element name="author" type="xs:string" minOccurs="0">
<xs:annotation>
<xs:documentation>The organization maintaining the add-on (e.g. openHAB). Individual developer names should be avoided. 
</xs:documentation>
</xs:annotation>
</xs:element>
```
=> Remove obsoleted author tags in addon.xml

bundles/org.openhab.binding.lgwebos/README.md, bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/LGWebOSBindingConstants.java, bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/LGWebOSHandlerFactory.java, bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/handler/LGWebOSConfiguration.java, bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/handler/LGWebOSHandler.java, bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/handler/LGWebOSTVSocket.java, bundles/org.openhab.binding.lgwebos/src/main/resources/OH-INF/config/config.xml, bundles/org.openhab.binding.lgwebos/src/main/resources/OH-INF/i18n/lgwebos.properties
Add support for TLS which is required by latest firmware.
TLS is supported also by older firmware versions, and therefore it's enabled by default. An advanced configuration parameter is provided to manually turning it off in case of compatibility problems.
JARs for testing:
- [org.openhab.binding.lgwebos-3.4.2-SNAPSHOT.jar](https://drive.google.com/file/d/1x1LHMD_nDeiM-Xzgzv1c_-5Q3mDAkS5f/view?usp=sharing)
- [org.openhab.binding.lgwebos-4.0.0-SNAPSHOT.jar](https://drive.google.com/file/d/1QvYL4R41UCawuQJvlTuj_cJOrwo4kDAg/view?usp=sharing)
Fixes #14309
=> [lgwebos] Add TLS support

CODEOWNERS, bundles/org.openhab.binding.snmp/README.md, bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/SnmpBindingConstants.java, bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/SnmpHandlerFactory.java, bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/SnmpService.java, bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/SnmpServiceImpl.java, bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/SnmpTargetHandler.java, bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/config/SnmpChannelConfiguration.java, bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/config/SnmpInternalChannelConfiguration.java, bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/config/SnmpTargetConfiguration.java, bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/types/SnmpAuthProtocol.java, bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/types/SnmpChannelMode.java, bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/types/SnmpDatatype.java, bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/types/SnmpPrivProtocol.java, bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/types/SnmpProtocolVersion.java, bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/types/SnmpSecurityModel.java, bundles/org.openhab.binding.snmp/src/main/resources/OH-INF/i18n/snmp.properties, bundles/org.openhab.binding.snmp/src/main/resources/OH-INF/thing/thing-types.xml, bundles/org.openhab.binding.snmp/src/test/java/org/openhab/binding/snmp/internal/AbstractSnmpTargetHandlerTest.java, bundles/org.openhab.binding.snmp/src/test/java/org/openhab/binding/snmp/internal/NumberChannelTest.java, bundles/org.openhab.binding.snmp/src/test/java/org/openhab/binding/snmp/internal/SnmpTargetHandlerTest.java, bundles/org.openhab.binding.snmp/src/test/java/org/openhab/binding/snmp/internal/StringChannelTest.java, bundles/org.openhab.binding.snmp/src/test/java/org/openhab/binding/snmp/internal/SwitchChannelTest.java, bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/handler/SysteminfoHandler.java
- bug: improve test stability (https://github.com/smarthomej/addons/pull/148)
- enhancement: add support for UoM (https://github.com/smarthomej/addons/pull/140)
- bug: fix misleading error message (https://github.com/smarthomej/addons/pull/134)
- bug: fix initialization exceptions (https://github.com/smarthomej/addons/pull/118)
- enhancement: Add support for SNMPv3 (https://github.com/smarthomej/addons/pull/19)
- enhancement: add opaque value handling
=> [snmp] Upgrades and enhancements

bundles/org.openhab.binding.fineoffsetweatherstation/src/main/java/org/openhab/binding/fineoffsetweatherstation/internal/service/GatewayQueryService.java
This fix ensures, that the `ReentrantLock::unlock` method is only called, when the Thread is owning the lock.
resolves: #14322
=> [fineoffsetweatherstation] Fix java.lang.IllegalMonitorStateException

bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/LifxProduct.java
Allows for discovering the new downlights (PID 121, 122) and their features.
See: https://github.com/LIFX/products/blob/master/products.json
=> [lifx] Add support for newer downlights

bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetThermoregulationHandler.java
Set default value for channel at startup.
This should fix https://github.com/openhab/openhab-addons/issues/12600.
=> [openwebnet] fix wrong startup value for channel failureDiscovered

bundles/org.openhab.binding.evcc/src/main/java/org/openhab/binding/evcc/internal/EvccHandler.java, bundles/org.openhab.binding.evcc/src/main/java/org/openhab/binding/evcc/internal/api/dto/Loadpoint.java
Fixes #14293.
* Fixes wrong DTO for the `activePhases` channel
* Fixes wrong units for vehicle and battery capacity channels
* Fixes wrong getter used for `batteryPrioritySoC` channel
All these fixes are for evcc 0.111.1, this PR is a follow-up for #14245 to fix the leftovers.
The user who reported the linked issue verified that the fix is working for the intended evcc version.
=> [evcc] Fixes & Adjust to more breaking changes from evcc 0.111.x

bundles/org.openhab.automation.jsscripting/bnd.bnd, bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/OpenhabGraalJSScriptEngine.java
Addon part of https://github.com/openhab/openhab-js/issues/98.
This PR extends the target type mapping inside the JS Scripting addon to also translate the following openhab-js classes to their native openHAB Java counterparts when passing to Java methods:
- openhab-js `Item` -> `org.openhab.core.items.Item`
- openhab-js `Quantity` -> `org.openhab.core.library.types.QuantityType`
Regarding the updated bnd file: I hope I did the right (if I understood the docs correctly I did), but would be nice if one could have a look and verify that it is correct what I did.
Use the following script to test:
```javascript
// Check JS-Item -> openHAB Item translation
actions.BusEvent.sendCommand(items.Temperature, "0 °C")
// Check JS-Quantity -> openHAB QuantityType translation
var QuantityType = …
```
=> [jsscripting] Extend mapping of openhab-js classes to native openHAB counterparts

bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/JRubyScriptEngineFactory.java, bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/watch/JRubyDependencyTracker.java, bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/watch/JRubyGemWatchService.java, bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/watch/JRubyLibWatchService.java, bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/watch/JRubyScriptFileWatcher.java, bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/watch/JRubyWatchService.java, bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/fs/watch/JSDependencyTracker.java, bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/fs/watch/JSScriptFileWatcher.java, bundles/org.openhab.binding.exec/src/main/java/org/openhab/binding/exec/internal/ExecWhitelistWatchService.java, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/MiIoDatabaseWatchService.java, bundles/org.openhab.transform.exec/src/main/java/org/openhab/transform/exec/internal/ExecTransformationWhitelistWatchService.java, itests/org.openhab.automation.jsscriptingnashorn.tests/itest.bndrun, itests/org.openhab.binding.astro.tests/itest.bndrun, itests/org.openhab.binding.avmfritz.tests/itest.bndrun, itests/org.openhab.binding.feed.tests/itest.bndrun, itests/org.openhab.binding.hue.tests/itest.bndrun, itests/org.openhab.binding.max.tests/itest.bndrun, itests/org.openhab.binding.mielecloud.tests/itest.bndrun, itests/org.openhab.binding.modbus.tests/itest.bndrun, itests/org.openhab.binding.mqtt.homeassistant.tests/itest.bndrun, itests/org.openhab.binding.mqtt.homie.tests/itest.bndrun, itests/org.openhab.binding.nest.tests/itest.bndrun, itests/org.openhab.binding.ntp.tests/itest.bndrun, itests/org.openhab.binding.systeminfo.tests/itest.bndrun, itests/org.openhab.binding.tradfri.tests/itest.bndrun, itests/org.openhab.binding.wemo.tests/itest.bndrun, itests/org.openhab.persistence.mapdb.tests/itest.bndrun
Depends on https://github.com/openhab/openhab-core/pull/3004
=> Adapt addons to core watch service changes

bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetLightingHandler.java
Removed the variable used to check if switch state has changed. 
Now for each light switch update `updateState()` is correctly called on switch channel
Fixes #14102
=> [openwebnet] light switch updates are now triggered

itests/org.openhab.binding.modbus.tests/src/main/java/org/openhab/binding/modbus/tests/ModbusPollerThingHandlerTest.java, itests/org.openhab.binding.nest.tests/src/main/java/org/openhab/binding/nest/internal/wwn/handler/WWNThingHandlerOSGiTest.java, itests/org.openhab.binding.ntp.tests/src/main/java/org/openhab/binding/ntp/test/NtpOSGiTest.java, itests/org.openhab.binding.systeminfo.tests/src/main/java/org/openhab/binding/systeminfo/test/SysteminfoOSGiTest.java, itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/test/GenericWemoOSGiTest.java
Thing initialization in core is now more strict, therefore some tests need to be adapted.
=> Fix build after core-changes

bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/GraalJSScriptEngineFactory.java, bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/OpenhabGraalJSScriptEngine.java, bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/fs/watch/JSDependencyTracker.java
Depends on https://github.com/openhab/openhab-core/pull/3372
=> [jsscripting] Fix node_modules handling

bundles/org.openhab.binding.knx/pom.xml, bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/SerialClient.java, bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/SerialTransportAdapter.java, bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/factory/KNXHandlerFactory.java, bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/SerialBridgeThingHandler.java, bundles/org.openhab.binding.knx/src/main/resources/META-INF/services/tuwien.auto.calimero.serial.spi.SerialCom
~This is still work in progress.~
The goal is to remove dependency on  gnu.io.rxtx and to user openHAB SerialTransport.
Two steps are necessary:
* remove our code in the KNX binding (easy, only used to show available com ports)
* remove the transitive dependency imported with the Calimero library.
Calimero introduced a new way to handle pluggable serial transport classes via the java.util.ServiceLoader in release 2.5.1.
This is in principle working and I was able to connect to our serial communication classes,
~*but* Serviceloader fails once we reload the KNX plugin. I could not get this fixed, so right now openHAB needs a restart to reload the KNX plugin! Any suggestions welcome....~
Calimero seems to change the interface again, after 2.5.1 ~this was removed. I need to have a look how to …
=> [knx] Replace gnu.io dependency with serial transport

bundles/org.openhab.io.imperihome/src/main/java/org/openhab/io/imperihome/internal/model/device/RgbLightDevice.java, bundles/org.openhab.io.imperihome/src/main/java/org/openhab/io/imperihome/internal/processor/ItemProcessor.java, bundles/org.openhab.io.imperihome/src/main/java/org/openhab/io/imperihome/internal/util/StringUtils.java
- Remove dependency on org.apache.commons
=> [imperihome] Remove org.apache.common

bundles/org.openhab.binding.upnpcontrol/src/main/java/org/openhab/binding/upnpcontrol/internal/queue/UpnpEntry.java, bundles/org.openhab.binding.upnpcontrol/src/main/java/org/openhab/binding/upnpcontrol/internal/util/StringUtils.java, bundles/org.openhab.binding.upnpcontrol/src/main/java/org/openhab/binding/upnpcontrol/internal/util/UpnpXMLParser.java
- Remove dependency on org.apache.commons
=> [upnpcontrol] Remove org.apache.common

bundles/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/GardenaSmartImpl.java, bundles/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/handler/GardenaAccountHandler.java
OH core method expects a name length between 4 and 20.
Avoid a possible IllegalArgumentException.
=> [gardena] Adjust thread name for WEB clients (avoid IAE)

bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/DeconzBridgeHandler.java
=> [deconz] Adjust thread name for web socket client

bundles/org.openhab.binding.mycroft/src/main/java/org/openhab/binding/mycroft/internal/MycroftHandler.java
=> [mycroft] Adjust thread name for web socket client

bundles/org.openhab.binding.onebusaway/src/main/java/org/openhab/binding/onebusaway/internal/config/ApiConfiguration.java, bundles/org.openhab.binding.onebusaway/src/main/java/org/openhab/binding/onebusaway/internal/config/ChannelConfig.java, bundles/org.openhab.binding.onebusaway/src/main/java/org/openhab/binding/onebusaway/internal/config/RouteConfiguration.java, bundles/org.openhab.binding.onebusaway/src/main/java/org/openhab/binding/onebusaway/internal/config/StopConfiguration.java
=> [onebusaway] Remove org.apache.common

bundles/org.openhab.binding.phc/src/main/java/org/openhab/binding/phc/internal/PHCHelper.java, bundles/org.openhab.binding.phc/src/main/java/org/openhab/binding/phc/internal/handler/PHCBridgeHandler.java, bundles/org.openhab.binding.phc/src/main/java/org/openhab/binding/phc/internal/util/StringUtils.java, bundles/org.openhab.binding.phc/src/test/java/org/openhab/binding/phc/internal/util/StringUtilsTest.java
Provided some tests for the padding, rest is untested, minor refactoring from only from code perspective
=> [phc] Remove import org.apache.common

bundles/org.openhab.binding.upnpcontrol/src/main/java/org/openhab/binding/upnpcontrol/internal/audiosink/UpnpAudioSinkReg.java, bundles/org.openhab.binding.upnpcontrol/src/main/java/org/openhab/binding/upnpcontrol/internal/discovery/UpnpControlDiscoveryParticipant.java, bundles/org.openhab.binding.upnpcontrol/src/main/java/org/openhab/binding/upnpcontrol/internal/handler/UpnpHandler.java, bundles/org.openhab.binding.upnpcontrol/src/main/java/org/openhab/binding/upnpcontrol/internal/handler/UpnpRendererHandler.java, bundles/org.openhab.binding.upnpcontrol/src/main/java/org/openhab/binding/upnpcontrol/internal/handler/UpnpServerHandler.java, bundles/org.openhab.binding.upnpcontrol/src/main/java/org/openhab/binding/upnpcontrol/internal/util/StringUtils.java
Follow up to https://github.com/openhab/openhab-addons/pull/14439
- Fogotten null annotation
- Removed not used imports (where allready there)
- Some checkstyle warnigns (where allready there)
=> [upnpcontrol] Multiple codestyle fixes

bundles/org.openhab.binding.neato/src/main/java/org/openhab/binding/neato/internal/handler/NeatoHandler.java
=> [neato] Remove org.apache.common

bundles/org.openhab.binding.yioremote/src/main/java/org/openhab/binding/yioremote/internal/YIOremoteDockHandler.java
Avoid a memory leak with web socket client not being stopped.
Also handle properly the case of the thing handler being quickly disposed.
=> [yioremote] Stop the web socket client when disposing thing handler

bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/handler/NanoleafControllerHandler.java
=> [nanoleaf] Stop the HTTP client when disposing the thing handler

bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/api/EcobeeApi.java, bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/api/EcobeeAuth.java, bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/handler/EcobeeSensorThingHandler.java, bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/handler/EcobeeThermostatBridgeHandler.java, bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/util/ExceptionUtils.java, bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/util/StringUtils.java
=> [ecobee] Remove org.apache.commons

bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/KNXCoreTypeMapper.java
Fixed in Calimero 2.4.
Carryover from smarthomej/addons#104.
Also-by: Jan N. Klug <github@klug.nrw>
=> [knx] Remove workaround for DPT 14

bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/KM200BindingConstants.java, bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/handler/KM200ThingHandler.java
This PR removes unused configuration URI/description. This was prepared but never used. See users comments: [137906](https://community.openhab.org/t/km200-warning-at-startup/137906)
=> [km200] removed unused configuration URIs

bundles/org.openhab.binding.goecharger/src/main/java/org/openhab/binding/goecharger/internal/handler/GoEChargerV2Handler.java
There was missing "break" preventing commands to be sent correctly.
=> [goecharger] Fix command sending

CODEOWNERS, bom/openhab-addons/pom.xml, bundles/org.openhab.transform.rollershutterposition/NOTICE, bundles/org.openhab.transform.rollershutterposition/README.md, bundles/org.openhab.transform.rollershutterposition/pom.xml, bundles/org.openhab.transform.rollershutterposition/src/main/feature/feature.xml, bundles/org.openhab.transform.rollershutterposition/src/main/java/org/openhab/transform/rollershutterposition/internal/RollerShutterPositionConstants.java, bundles/org.openhab.transform.rollershutterposition/src/main/java/org/openhab/transform/rollershutterposition/internal/RollerShutterPositionProfile.java, bundles/org.openhab.transform.rollershutterposition/src/main/java/org/openhab/transform/rollershutterposition/internal/RollerShutterPositionProfileFactory.java, bundles/org.openhab.transform.rollershutterposition/src/main/java/org/openhab/transform/rollershutterposition/internal/config/RollerShutterPositionConfig.java, bundles/org.openhab.transform.rollershutterposition/src/main/resources/OH-INF/config/rollerShutterPosition.xml, bundles/org.openhab.transform.rollershutterposition/src/main/resources/OH-INF/i18n/rollershutter.properties, bundles/pom.xml
This transform will emulate setting of absolute position for rollershutters which only support Up/Down/Stop commands.  By specifying the time it takes for the rollershutter to fully extend or close, the transform will estimate the time it will take for the rollershutter to move to an absolute position.
=> [rollershutterposition] Initial contribution

bundles/org.openhab.binding.netatmo/README.md, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/AuthenticationApi.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/EnergyApi.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/RestManager.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/SecurityApi.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/data/NetatmoConstants.java, bundles/org.openhab.binding.netatmo/src/main/resources/OH-INF/thing/channels.xml
Solves issue #14458 
Removes the usage of "app.netatmo.net" since api now holds these entry points.
I think it was the origin of malfunction of floodlight (to be controlled by somebody who has one).
=> [Netatmo] Floodlight issue on Presence Camera

bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/handler/EcobeeUtils.java
Correcting rounding of setHold values so we have 0.1°F tolerance instead of 1°F.  Makes it easier to use in °C
Signed-off-by: Bevan Watkiss <darthbevis@gmail.com>
=> [ecobee] Increase temperature precision to decimal

bundles/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/PlugwiseMessageProcessor.java, bundles/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/PlugwiseUtils.java, bundles/org.openhab.binding.plugwise/src/test/java/org/openhab/binding/plugwise/internal/PlugwiseUtilsTest.java
=> [plugwise] Remove org.apache.common

bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/KNXTypeMapper.java, bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/channel/TypeDimmer.java, bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/channel/TypeRollershutter.java, bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/AbstractKNXClient.java, bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/KNXCoreTypeMapper.java, bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/factory/KNXHandlerFactory.java, bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/AbstractKNXThingHandler.java, bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/DeviceThingHandler.java, bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/IPBridgeThingHandler.java, bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/channel/KNXChannelTypeTest.java
Carryover from smarthomej/addons#13 and smarthomej/addons#46, smarthomej/addons#60.
Also-by: Jan N. Klug <github@klug.nrw>
Refs: #14502
=> [knx] Improve thread safety, null-analysis

bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/ChannelState.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/ColorValue.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/DateTimeValue.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/ImageValue.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/LocationValue.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/NumberValue.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/OnOffValue.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/OpenCloseValue.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/PercentageValue.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/RollershutterValue.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/TextValue.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/Value.java, bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/ChannelStateTests.java, bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/internal/handler/GenericThingHandlerTests.java, bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/values/ValueTests.java, bundles/org.openhab.binding.mqtt.homie/src/test/java/org/openhab/binding/mqtt/homie/internal/handler/HomieThingHandlerTests.java
fixes #12150
Previously, Value.update would parse the command, _and_ update the cached
value with that command. Which means that when sending a command towards
MQTT (instead of processing an update from MQTT), the cached value was
unintentionally updated. This prevented the REFRESH command from returning
the most recent value received from the device.
Separating the two concerns also makes the test more obvious what they are
testing, and vastly simplified a kludgy workaround that RollershutterValue
was using to be able to process Commands that aren't States.
I've tested this in my local openhab installation to confirm that an MQTT channel with separate state and command topics, where the state topic does not change after sending a command, the item is set to autoupdate, I can now use …
=> [mqtt.generic] separate command parsing from cached value updating

bundles/org.openhab.binding.sleepiq/src/main/resources/OH-INF/thing/thing-types.xml, bundles/org.openhab.binding.sleepiq/src/main/resources/OH-INF/update/instructions.xml
Add thing type instructions for updating thing with new channels.
This is a follow up to PR #14447, which added 4 new channels.
Signed-off-by: Mark Hilbush [mark@hilbush.com](mailto:mark@hilbush.com)
=> [sleepiq] Add thing type update instructions

bundles/org.openhab.binding.velux/README.md
Resolves #14404
As stated in Issue #14404 a user found the binding documentation concerning the `inverted` parameter to be confusing.
So this PR adds further information to the readme file to better explain the meaning of the `inverted` parameter.
Note: this PR includes all the changes from #14371 in order to (hopefully) avoid a merge conflict.
=> [velux] Update documentation

bundles/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/NeeoService.java
It seems that Pax Web nowadays checks that the Servlet names are unique.
See: [ServletModel.addServletModel](https://github.com/ops4j/org.ops4j.pax.web/blame/f3350d3bc942109505d17497a8a23900f3abe7c3/pax-web-spi/src/main/java/org/ops4j/pax/web/service/spi/model/ServerModel.java#L1443-L1459)
Fixes #14545
=> [neeo] Fix Servlet exceptions due to non-unique names

bundles/org.openhab.automation.jrubyscripting/pom.xml
This is a major version upgrade from 9.3.x, raising the compatibility level up from Ruby 2.6 to Ruby 3.1
=> [jrubyscripting] Upgrade JRuby to 9.4.2.0

bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/D2_05/D2_05_00.java
Fix #14528
Change condition in function getPositionData in EEP D2_05_00 to check data at offset 1 and size 7 instead offset 0 and size 8.
According the enocean documentation visible [here](http://tools.enocean-alliance.org/EEPViewer/profiles/D2/05/00/D2-05-00.pdf), the section `CMD 4 - Reply Position and Angle` the first bit is not used, so the validation should not evaluate it.
=> [enocean] Bugfix - condition in getPositionData function of EEP D2_05_00

bundles/org.openhab.binding.danfossairunit/src/main/resources/OH-INF/thing/thing-types.xml, bundles/org.openhab.binding.danfossairunit/src/main/resources/OH-INF/update/instructions.xml
Follow-up to #14030
Made possible by openhab/openhab-core#3330
Requires also openhab/openhab-core#3391
=> [danfossairunit] Add instruction for channel removal

bundles/org.openhab.binding.bsblan/pom.xml, bundles/org.openhab.binding.bsblan/src/main/java/org/openhab/binding/bsblan/internal/helper/BsbLanParameterConverter.java
- Replaced the org.apache.commons with the unbescape package.
Not tested, just technicall change. Should work as this package has been used in several other bindings as replacement for `unescapeHtml4`
=> [bsblan] Remove org.apache.commons

bundles/org.openhab.binding.dlinksmarthome/README.md, bundles/org.openhab.binding.dlinksmarthome/src/main/java/org/openhab/binding/dlinksmarthome/internal/DLinkSmartHomeDiscoveryParticipant.java, bundles/org.openhab.binding.dlinksmarthome/src/main/java/org/openhab/binding/dlinksmarthome/internal/handler/DLinkMotionSensorHandler.java, bundles/org.openhab.binding.dlinksmarthome/src/main/java/org/openhab/binding/dlinksmarthome/internal/motionsensor/DLinkMotionSensorCommunication.java, bundles/org.openhab.binding.dlinksmarthome/src/main/java/org/openhab/binding/dlinksmarthome/internal/motionsensor/DLinkMotionSensorConfig.java, bundles/org.openhab.binding.dlinksmarthome/src/main/resources/OH-INF/i18n/dlinksmarthome.properties, bundles/org.openhab.binding.dlinksmarthome/src/main/resources/OH-INF/thing/thing-types.xml
Following the shutdown of the mydlink Home service, the devices have a tendency to become unresponsive after a few days.
This change performs a daily reboot of the device to keep it responsive.
Discovery has also been changed to avoid using ipv6 addresses which don't seem to work. The change is based on  a change made to the Chromecast binding. The binding previously had a problem in that it would occasionally switch to using an ipv6 address and go offline, rebooting daily increases the chance it ends up with an ipv6 address.
=> [dlinksmarthome] Reboot device daily following shutdown of cloud service

.github/PULL_REQUEST_TEMPLATE.md
This helps to prevent some frustration between contributors/maintainers.
=> Instruct contributors to always use "main" branch for PRs

bundles/org.openhab.automation.groovyscripting/README.md, bundles/org.openhab.automation.groovyscripting/pom.xml, bundles/org.openhab.automation.groovyscripting/src/main/java/org/openhab/automation/groovyscripting/internal/GroovyScriptEngineFactory.java, itests/org.openhab.automation.groovyscripting.tests/NOTICE, itests/org.openhab.automation.groovyscripting.tests/itest.bndrun, itests/org.openhab.automation.groovyscripting.tests/pom.xml, itests/org.openhab.automation.groovyscripting.tests/src/main/java/org/openhab/automation/groovyscripting/SlurperOSGiTest.java, itests/org.openhab.automation.groovyscripting.tests/src/main/resources/OH-INF/automation/jsr223/json-slurper.groovy, itests/org.openhab.automation.groovyscripting.tests/src/main/resources/OH-INF/automation/jsr223/xml-slurper.groovy, itests/org.openhab.automation.groovyscripting.tests/src/main/resources/OH-INF/automation/jsr223/yaml-slurper.groovy, itests/pom.xml
Updates Groovy from 4.0.7 to 4.0.9.
https://groovy-lang.org/changelogs/changelog-4.0.8.html
https://groovy-lang.org/changelogs/changelog-4.0.9.html
Adds dependencies and service loader config so JSON, XML and YAML can be more easily parsed using the `JsonSlurper`, `XmlSlurper` and `YamlSlurper`.
=> [groovyscripting] Update Groovy to 4.0.9 and support slurpers

bundles/org.openhab.binding.bluetooth.radoneye/README.md, bundles/org.openhab.binding.bluetooth.radoneye/src/main/java/org/openhab/binding/bluetooth/radoneye/internal/AbstractRadoneyeHandler.java, bundles/org.openhab.binding.bluetooth.radoneye/src/main/java/org/openhab/binding/bluetooth/radoneye/internal/RadoneyeConfiguration.java, bundles/org.openhab.binding.bluetooth.radoneye/src/main/java/org/openhab/binding/bluetooth/radoneye/internal/RadoneyeDataParser.java, bundles/org.openhab.binding.bluetooth.radoneye/src/main/java/org/openhab/binding/bluetooth/radoneye/internal/RadoneyeHandler.java, bundles/org.openhab.binding.bluetooth.radoneye/src/main/resources/OH-INF/i18n/bluetooth.properties, bundles/org.openhab.binding.bluetooth.radoneye/src/main/resources/OH-INF/thing/radoneye.xml, bundles/org.openhab.binding.bluetooth.radoneye/src/test/java/org/openhab/binding/bluetooth/radoneye/RadoneyeParserTest.java
This PR will add support for the v2.x.x firmware to the RadonEye binding, by using other UUIDs for this version.
An additional change is the removing the `Optional<>` from the configuration.
Without a configuration the binding is missing the needed address to connect to the device.
Therefore the configuration is mandatory and not an optional field.
=> [bluetooth.radoneye] Support for RadonEye with v2.x.x firmware

bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/discovery/DanfossAirUnitDiscoveryService.java, bundles/org.openhab.binding.danfossairunit/src/main/resources/OH-INF/addon/addon.xml, bundles/org.openhab.binding.danfossairunit/src/main/resources/OH-INF/i18n/danfossairunit.properties
Discovery result uses old (hardcoded) label "Danfoss HRV" rather than "Danfoss Air Unit":
Now discovery result and manually added thing are unified as "Danfoss Air Unit" and localization support for discovery result has been added.
Also categorized binding as "local".
=> [danfossairunit] Unify thing labels

bundles/org.openhab.binding.renault/src/main/java/org/openhab/binding/renault/internal/api/MyRenaultHttpSession.java, bundles/org.openhab.binding.renault/src/main/java/org/openhab/binding/renault/internal/api/exceptions/RenaultAPIGatewayException.java, bundles/org.openhab.binding.renault/src/main/java/org/openhab/binding/renault/internal/handler/RenaultHandler.java
The Renault API returns HTTP 502 if the lock status is not supported.   In which case this feature is disabled so that the binding does not repeat unnecessary log warnings and requests.
However there have been occasions where the battery status API returned HTTP 502 temporarily.  This disabled the battery status feature which is supported.  The battery level is then not updated until the RenaultCar "thing" is re-initialized.
This PR disables lock status on HTTP 502 but not other features.
=> [renault] Improve handling of HTTP 502 responses from Renault API

bundles/org.openhab.binding.benqprojector/src/main/java/org/openhab/binding/benqprojector/internal/discovery/MulticastListener.java, bundles/org.openhab.binding.bigassfan/src/main/java/org/openhab/binding/bigassfan/internal/handler/BigAssFanHandler.java, bundles/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/internal/discovery/MulticastListener.java, bundles/org.openhab.binding.globalcache/src/main/java/org/openhab/binding/globalcache/internal/discovery/MulticastListener.java, bundles/org.openhab.binding.globalcache/src/main/java/org/openhab/binding/globalcache/internal/handler/GlobalCacheHandler.java
While it occurs very rarely, it's possible for `NetworkInterface.getByInetAddress` to return null. This PR prevents the NPE in all bindings where this call is used.
Reported on forum [here](https://community.openhab.org/t/globalcache-binding-error-upgrade-from-openhab-3-2-to-3-4-2/145214).
Signed-off-by: Mark Hilbush [mark@hilbush.com](mailto:mark@hilbush.com)
=> Fix NullPointerException when getting network interface name

CODEOWNERS, bom/openhab-addons/pom.xml, bundles/org.openhab.transform.vat/NOTICE, bundles/org.openhab.transform.vat/README.md, bundles/org.openhab.transform.vat/pom.xml, bundles/org.openhab.transform.vat/src/main/feature/feature.xml, bundles/org.openhab.transform.vat/src/main/java/org/openhab/transform/vat/internal/VATTransformationConstants.java, bundles/org.openhab.transform.vat/src/main/java/org/openhab/transform/vat/internal/VATTransformationService.java, bundles/org.openhab.transform.vat/src/main/java/org/openhab/transform/vat/internal/config/VATConfig.java, bundles/org.openhab.transform.vat/src/main/java/org/openhab/transform/vat/internal/profile/VATTransformationProfile.java, bundles/org.openhab.transform.vat/src/main/java/org/openhab/transform/vat/internal/profile/VATTransformationProfileFactory.java, bundles/org.openhab.transform.vat/src/main/resources/OH-INF/addon/addon.xml, bundles/org.openhab.transform.vat/src/main/resources/OH-INF/config/vatProfile.xml, bundles/org.openhab.transform.vat/src/main/resources/OH-INF/i18n/vat.properties, bundles/pom.xml
This simple transformation adds VAT (Value-Added Tax) to a given input amount.
Its main purpose is to conveniently let the provided profile add VAT when linking an item to a channel without requiring any configuration. However, it can also be used for display purposes only, although in this case the rate must be configured.
One use-case is to eliminate the need for any built-in VAT logic in bindings providing electricity prices, thereby reducing redundancy.
Advantages:
- Automatic rate according to country in openHAB regional settings (no configuration needed).
- Consolidates VAT calculation in one centralized place.
- Potentially eliminates custom VAT calculations in bindings.
- Not dependent on any online service.
Limitations:
- Only standard rate supported, no specialized types of VAT. …
=> [transform.vat] Initial contribution

bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/discovery/YeelightDiscoveryService.java, bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/device/DeviceFactory.java, bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/services/DeviceManager.java
Added support of a new LED strip light (strip6). This issue was mentioned https://community.openhab.org/t/yeelight-new-stripe-model/118764
It looks very much like original stripe and has the following capabilities:
strip6
{ "ip": "X.X.X.X", "port": 55443, "capabilities": { "id": "0x00000000175f6828", "model": "strip6", "fw_ver": "20", "support": "get_prop set_default set_power toggle set_bright set_scene cron_add cron_get cron_del start_cf stop_cf set_name set_adjust adjust_bright set_ct_abx adjust_ct adjust_color set_rgb set_hsv set_music udp_sess_new udp_sess_keep_alive udp_chroma_sess_new", "power": "on", "bright": "100", "color_mode": "1", "ct": "3524", "rgb": "7864244", "hue": "147", "sat": "53", …
=> [yeelight] Add sptrip6 device

bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/ChannelStateTests.java
Fix tests after openhab/openhab-core#3434
See https://ci.openhab.org/job/openHAB-Addons/1013/
=> [mqtt] Fix color tests after HSBType changes

bundles/org.openhab.binding.vizio/src/main/java/org/openhab/binding/vizio/internal/console/VizioCommandExtension.java, bundles/org.openhab.binding.vizio/src/main/java/org/openhab/binding/vizio/internal/handler/VizioHandler.java
Fixes #14621 
Refactoring done by #14429 did not consider the httpClient used by the pairing process. This PR refactors the pairing console code to use the handler's httpClient that was configured to accept the TV's self signed SSL certificate.
=> [vizio] Refactor pairing process to use handler's httpClient

bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/watch/JRubyScriptFileWatcher.java
~Depends on https://github.com/openhab/openhab-core/pull/3451~
The original NPE bug is fixed entirely within https://github.com/openhab/openhab-core/pull/3451 so this PR no longer depends on it. 
Somewhat related though is to filter the file types that are added to the watch list, so that the filewatcher won't try to load files with other extensions within the `automation/ruby` (sub)directory.
=> [jrubyscripting] Filter files that are added to the watch list

bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/MqttChannelStateDescriptionProvider.java
=> [mqtt.generic] Don't log state description from provider when not found

bundles/org.openhab.binding.boschshc/README.md, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/BoschSHCDeviceHandler.java, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/BoschSHCHandler.java, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/BoschHttpClient.java, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/BridgeHandler.java, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/dto/PublicInformation.java, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/discovery/BridgeDiscoveryParticipant.java, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/discovery/ThingDiscoveryService.java, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/BoschSHCSystemService.java, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/batterylevel/BatteryLevelService.java, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/dto/BoschSHCServiceState.java, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/smokedetectorcheck/SmokeDetectorCheckState.java, bundles/org.openhab.binding.boschshc/src/main/resources/OH-INF/i18n/boschshc.properties, bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/bridge/BoschHttpClientTest.java, bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/discovery/BridgeDiscoveryParticipantTest.java, bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/discovery/ThingDiscoveryServiceTest.java
#14195 [boschshc] Bridge discovery is implemented via mDNS, local IP addresses are checked. If a GET returns the public SHC information,
then this shcIpAddress is reported as a discovered bridge.
Devices are always discovered after successful pairing, but a manual scan is also possible.
=> [boschshc] Bridge and Device Discovery

bundles/org.openhab.binding.openwebnet/README.md, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/OpenWebNetBindingConstants.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetAlarmHandler.java, bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/i18n/openwebnet.properties, bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/channels.xml
This enhancement resets zones' alarm state when alarm system is (re-)armed. 
A new state NONE is added to `CHANNEL_ALARM_ZONE_ALARM_STATE` definition.
Fixes #14305
=> [openwebnet] Reset zones' alarm state channel when system is armed

.github/scripts/maven-build
When an add-on is removed a partial build fails and instead a full build should be done.
See: https://github.com/openhab/openhab-addons/pull/14675#issuecomment-1484020311
Tested in my fork using https://github.com/wborn/openhab-addons/pull/9.
=> Trigger full build when add-on is removed

bundles/org.openhab.binding.kaleidescape/README.md, bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/communication/KaleidescapeConnector.java, bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/communication/KaleidescapeFormatter.java, bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/handler/KaleidescapeHandler.java, bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/handler/KaleidescapeMessageHandler.java, bundles/org.openhab.binding.kaleidescape/src/test/java/org/openhab/binding/kaleidescape/internal/KaleidescapeFormatterTest.java
Replace StringEscapeUtils.unescapeHtml4() with basic Java methods to address #7722. Also a couple very minor tweaks that I have had pending for some time now.
=> [kaleidescape] Remove Apache StringEscapeUtils

bundles/org.openhab.binding.benqprojector/src/main/java/org/openhab/binding/benqprojector/internal/discovery/MulticastListener.java, bundles/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/internal/discovery/MulticastListener.java, bundles/org.openhab.binding.globalcache/src/main/java/org/openhab/binding/globalcache/internal/discovery/MulticastListener.java
Replace deprecated `MulticastSocket` methods `setInterface` and `joinGroup`.
I believe these are the bindings that need to be changed: globalcache, benqprojector, epsonprojector, lcn.
Note I did not change lcn because the model is different than gc, benq, and epson. I was afraid I would break something, and I have no way to test my changes.
=> Replace deprecated MulticastSocket methods

bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/JSONSchemaLight.java
https://github.com/openhab/openhab-addons/pull/12238 was merged after JSON Schema Light was implemented, and changed some assumptions. this commit adjusts to the changed interface
=> [mqtt.homeassistant] fix JSON Schema lights

CODEOWNERS
Thank you, Stefan & Christian! Welcome David!
This update of the code owner reflects the changes of the last years.
Thank you @stefan-kaestle for the initial code contribution of the binding and only with the great contributions & time invest from @coeing the code was accepted for the openhab main branch.
Of cause focus changes and Christian was [Looking for developers](https://github.com/stefan-kaestle/openhab2-addons/issues/114) already back in 2021.
And now a new, but very experienced Java developer joined. David provided already many good pull requests and pushes the code quality and SmartHomeController tests to a new level and is now a new code owner. Therefore, a warm welcome @david-pace !
=> [boschshc] updated boschshc code owner

bundles/org.openhab.binding.tapocontrol/README.md, bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/constants/TapoThingConstants.java, bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/device/TapoLightStrip.java, bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/device/TapoSmartBulb.java, bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/device/TapoUniversalDevice.java, bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/structures/TapoDeviceInfo.java, bundles/org.openhab.binding.tapocontrol/src/test/java/org/openhab/binding/tapocontrol/internal/device/TapoUniversalDevice.java, bundles/org.openhab.binding.tapocontrol/src/test/java/org/openhab/binding/tapocontrol/internal/structures/TapoDeviceInfo.java
Fix for L920 lightstrip when sending colour values with decimals (server reported error -1008)
Also updated the doc with actual channels listed for L920 in README.
NOTE: Problem may be inherent in bulb implementation as code is duplicated. Detected throgh sitemap in Android sitemap.
=> [tapocontrol] Color values must be int, not decimal

bundles/org.openhab.automation.groovyscripting/README.md, bundles/org.openhab.automation.groovyscripting/pom.xml
Updates Groovy from 4.0.9 to 4.0.11.
This fixes a few bugs including a memory leak, see:
http://groovy-lang.org/changelogs/changelog-4.0.10.html
http://groovy-lang.org/changelogs/changelog-4.0.11.html
=> [groovyscripting] Update Groovy to 4.0.11

bundles/org.openhab.binding.solarwatt/README.md, bundles/org.openhab.binding.solarwatt/src/main/java/org/openhab/binding/solarwatt/internal/SolarwattBindingConstants.java, bundles/org.openhab.binding.solarwatt/src/main/java/org/openhab/binding/solarwatt/internal/SolarwattHandlerFactory.java, bundles/org.openhab.binding.solarwatt/src/main/java/org/openhab/binding/solarwatt/internal/discovery/SolarwattDevicesDiscoveryService.java, bundles/org.openhab.binding.solarwatt/src/main/java/org/openhab/binding/solarwatt/internal/domain/model/SmartHeater.java, bundles/org.openhab.binding.solarwatt/src/main/java/org/openhab/binding/solarwatt/internal/factory/EnergyManagerDevicesFactory.java, bundles/org.openhab.binding.solarwatt/src/main/resources/OH-INF/i18n/solarwatt.properties, bundles/org.openhab.binding.solarwatt/src/main/resources/OH-INF/thing/thing-types.xml
The [EGO Smart Heater](https://www.ego-seibert.de/produkte/pseudo-sub1/smart-heater) screw-in heater stores excess photovoltaic energy fully automatically as hot water. These changes add support for this device to the solarwatt binding.
The test version of the binding can be found [here](https://openhab.jfrog.io/ui/native/libs-pullrequest-local/org/openhab/addons/bundles/org.openhab.binding.solarwatt/4.0.0-SNAPSHOT/).
=> [solarwatt] Add smart heater device support

bundles/org.openhab.automation.jsscripting/README.md, bundles/org.openhab.automation.jsscripting/pom.xml
- Upgrades openhab-js to 4.2.1, which brings enhancements and important bugfixes and adjusts to a breaking change in openHAB Core. 
- Notes that JS Scripting is based on GraalJS.
For changes, see https://github.com/openhab/openhab-js/blob/v4.2.1/CHANGELOG.md#421.
=> [jsscripting] Bump openhab-js to 4.2.1

bundles/org.openhab.binding.sensibo/src/main/java/org/openhab/binding/sensibo/internal/handler/SensiboSkyHandler.java, bundles/org.openhab.binding.sensibo/src/main/java/org/openhab/binding/sensibo/internal/util/StringUtils.java, bundles/org.openhab.binding.sensibo/src/test/java/org/openhab/binding/sensibo/internal/util/StringUtilsTest.java
Created some tests, not all is tested, minor refactoring from code perspective
=> [sensibo] Remove org.apache.common

bundles/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/GardenaSmartImpl.java
If an exception occurs during httpClient.start(), webSocketClient remained null, which led to another (then unhandled) exception being thrown by dispose(), called in the exception handler.
With the new initialization order it's ensured webSocketClient is not null at dispose() time, thus allowing proper propagation of the exception thrown at HTTP startup.
=> [gardena] Improve GardenaSmartImpl initialization order

bundles/org.openhab.binding.astro/README.md, bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/action/AstroActions.java, bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/handler/SunHandler.java
This is enhancement of Astro binding. There is added getTotalRadiation to AstroActions allowing the user to get total radiation of the sun at the requested instant. The documentation of the Astro binding is updated as well. The proposed enhancement is tested and works also in the previous version 3.4.2.
=> [astro] Add getTotalRadiation to AstroActions 

itests/org.openhab.binding.mielecloud.tests/src/main/java/org/openhab/binding/mielecloud/internal/config/ConfigFlowTest.java
See #13938 
As they always fail and therefore CI builds fail.
=> Disable mielecloud tests

bundles/org.openhab.binding.yeelight/README.md, bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/discovery/YeelightDiscoveryService.java, bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/device/DeviceFactory.java, bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/enums/DeviceType.java, bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/services/DeviceManager.java
Added support of a ceiling lights YLXD41YL (ceiling11) and YLXD76YL (ceil26).
Capabilities are same as ceiling1
ceiling1
`
{'ip': '192.168.112.65', 'port': 55443, 'capabilities': {'id': '0x0000000007e7f54d', 'model': 'ceiling1', 'fw_ver': '193', 'support': 'get_prop set_default set_power toggle set_bright set_scene cron_add cron_get cron_del start_cf stop_cf set_ct_abx set_name set_adjust adjust_bright adjust_ct', 'power': 'on', 'bright': '100', 'color_mode': '2', 'ct': '3500', 'rgb': '0', 'hue': '0', 'sat': '0', 'name': ''}}
`
ceil26
`
{'ip': '192.168.112.108', 'port': 55443, 'capabilities': {'id': '0x0000000015627cc9', 'model': 'ceil26', 'fw_ver': '18', 'support': 'get_prop set_default set_power toggle …
=> [Yeelight] Support of ceil26 and ceiling11 devices

bundles/org.openhab.binding.ekey/README.md, bundles/org.openhab.binding.ekey/src/main/java/org/openhab/binding/ekey/internal/EkeyConfiguration.java, bundles/org.openhab.binding.ekey/src/main/java/org/openhab/binding/ekey/internal/api/EkeyUdpPacketReceiver.java, bundles/org.openhab.binding.ekey/src/main/java/org/openhab/binding/ekey/internal/handler/EkeyHandler.java, bundles/org.openhab.binding.ekey/src/main/resources/OH-INF/i18n/ekey.properties, bundles/org.openhab.binding.ekey/src/main/resources/OH-INF/i18n/ekey_de.properties, bundles/org.openhab.binding.ekey/src/main/resources/OH-INF/thing/thing-types.xml
This adds a new configuration parameter sourceIp.
It's required when using NAT (e.g. in Kubernetes deployments).
While the binding verifies that the packet source ip is equal to the ipAddress this will fail.
With NAT the packet source ip is the ip of your host.
Without that feature it's not working within kubernetes deployments
https://github.com/openhab/openhab-addons/issues/14599
=> [eKey] Add sourceIp in cases of NAT (Kubernetes deployments)

bundles/org.openhab.binding.ism8/src/main/resources/OH-INF/addon/addon.xml, bundles/org.openhab.binding.knx/src/main/resources/OH-INF/addon/addon.xml, bundles/org.openhab.binding.networkupstools/src/main/resources/OH-INF/addon/addon.xml, bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/addon/addon.xml, bundles/org.openhab.binding.tankerkoenig/src/main/resources/OH-INF/addon/addon.xml
=> Declare connection on few bindings

bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/discovery/ThingDiscoveryService.java
- fix door/window contact device model (`SWD` instead of `WRC2`)
- fix in-wall light switch device model (`BSM` instead of `PSM`)
- fix thing type of `BWTH` (should be a wall thermostat, not a thermostat)
- add association for `PSM` (smart plug)
- add association for `LEDVANCE_LIGHT` (smart light bulb)
- add association for `TRV` (thermostat)
Closes #14672
=> [boschshc] Enhance device associations in discovery

bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/AbstractKNXClient.java, bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/ValueDecoder.java, bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/ValueEncoder.java, bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/DeviceThingHandler.java, bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/IPBridgeThingHandler.java, bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/SerialBridgeThingHandler.java, bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/dpt/DPTTest.java
Correct the rounding behavior.
See also openhab/openhab-core#3479.
Refs. #12643
Some additional fixes for compilation and SAT warnings that were recently introduced.
=> [knx] Improve rounding when encoding DPT 232.60000

bundles/org.openhab.binding.windcentrale/src/main/java/org/openhab/binding/windcentrale/internal/WindcentraleDiscoveryService.java, bundles/org.openhab.binding.windcentrale/src/main/java/org/openhab/binding/windcentrale/internal/handler/WindcentraleAccountHandler.java, bundles/org.openhab.binding.windcentrale/src/main/java/org/openhab/binding/windcentrale/internal/listener/ThingStatusListener.java
This makes the binding automatically discover windmills when the account goes online so users do not have to manually trigger a scan during initial setup.
=> [windcentrale] Discover windmills when account goes online

bundles/org.openhab.voice.mimictts/src/main/resources/OH-INF/addon/addon.xml
It seems to have been copied over from macOS TTS without properly updating all details.
=> [mimictts] Fix addon.xml info

bundles/org.openhab.binding.renault/src/main/java/org/openhab/binding/renault/internal/RenaultConfiguration.java, bundles/org.openhab.binding.renault/src/main/resources/OH-INF/thing/thing-types.xml
The API key used in the Renault binding to access the MyRenault services changes sometimes...  This can be updated in the bindings configuration to repair communication of existing installations.
This PR updates the default key to the new one for new installations.
=> [renault] update default Kamereon API Key

bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetLightingHandler.java
This fix is needed to avoid "block" dimmers when two consecutive OFF commands are received: when a ON command is then received, the brightness remains 0 anyway.
The cause being that `brightnessBeforeOff` is wrongly set to 0 when the second OFF is received.
See: https://community.openhab.org/t/openwebnet-bticino-legrand-binding-beta-4-0-0-0-4-1-0-0/129775/72?u=massi
Fixes #14785.
=> [openwebnet] Fix for dimmer blocked after two OFF are received

bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/ColorValue.java, bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/ChannelStateTests.java, bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/AbstractComponentTests.java, bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/DefaultSchemaLightTests.java, bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/JSONSchemaLightTests.java, bundles/org.openhab.binding.tradfri/src/test/java/org/openhab/binding/tradfri/internal/TradfriColorTest.java, bundles/org.openhab.binding.webthing/src/test/java/org/openhab/binding/webthing/internal/link/WebthingChannelLinkTest.java
Adapt tests due to https://github.com/openhab/openhab-core/pull/3542.
To be merged after core change.
This PR fixes the broken tests after core change for now, but especially the tests checking for double valued numbers should be changed to allow small differences between colors (e.g. a deviation of 0.5% due to color conversions),
=> [mqtt][tradfri][webthing] Adapt to ColorUtil changes in core

bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/discovery/HueBridgeNupnpDiscovery.java, bundles/org.openhab.binding.hue/src/main/resources/OH-INF/addon/addon.xml, itests/org.openhab.binding.hue.tests/src/main/java/org/openhab/binding/hue/internal/discovery/HueBridgeNupnpDiscoveryOSGITest.java
Fixes #14852 
Regression of #11842
=> [hue] Fix NUPnP discovery

bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/BoschIndegoBindingConstants.java, bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/IndegoController.java, bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/IndegoDeviceController.java, bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/IndegoTypeDatabase.java, bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/discovery/IndegoDiscoveryService.java, bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/dto/response/DevicePropertiesResponse.java, bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/dto/serialization/InstantDeserializer.java, bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/handler/BoschAccountHandler.java, bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/handler/BoschIndegoHandler.java, bundles/org.openhab.binding.boschindego/src/main/resources/OH-INF/thing/thing-types.xml
Adds some useful properties like Bosch bare tool number, model name and firmware version.
Use the model name as thing label from discovery.
Resolves #14828
=> [boschindego] Add device properties

bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/servlet/IpCameraServlet.java
[IP camera] on OH4 has the same servlet issue that was fixed by PR #14554.  This PR uses that PR as a template to fix the issue in the IPcamera binding.  (That issue being that only one camera was able to stream.) This was tested locally on OH4M2 and it works.  Also the referenced PR worked with [neeo] and this used that PR as a template.
Signed-off-by: Bob Eckhoff  <katmandodo@yahoo.com>
=> [ipcamera] Fix servlet exceptions due to non unique names

bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Climate.java
the min/max from the config are specifically only for the set point. i.e. for a heater in winter when the heater is off, it may have a set point range of 65-104°F, but if it's off for an unoccopied room the ambient temperature might drop far below 65
=> [mqtt.homeassistant] don't set range on current temp channel

bundles/org.openhab.persistence.jdbc/README.md, bundles/org.openhab.persistence.jdbc/src/main/feature/feature.xml, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcConfiguration.java
Release notes:
- https://dev.mysql.com/doc/relnotes/connector-j/8.0/en/news-8-0-32.html
- https://dev.mysql.com/doc/relnotes/connector-j/8.0/en/news-8-0-33.html
Fixes vulnerabilities from dependencies:
- [CVE-2022-3510](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-3510)
- [CVE-2022-3509](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-3509)
- [CVE-2022-3171](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-3171)
Library:
- https://mvnrepository.com/artifact/com.mysql/mysql-connector-j/8.0.33
Tested by installing compiled bundle as well as mysql-connector into addons directory:
```
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        24-04-2023     21:21        2481560 mysql-connector-j.jar …
```
=> [jdbc] Upgrade MySQL Connector/J to 8.0.33

bundles/org.openhab.binding.sleepiq/src/main/java/org/openhab/binding/sleepiq/internal/api/dto/SleepDataSession.java, bundles/org.openhab.binding.sleepiq/src/main/java/org/openhab/binding/sleepiq/internal/api/impl/GsonGenerator.java, bundles/org.openhab.binding.sleepiq/src/main/java/org/openhab/binding/sleepiq/internal/api/impl/typeadapters/LocalDateTypeAdapter.java
This type adapter was mistakenly deleted when I migrated the 3rd party code to openHAB in PR #14180
Also fix name of json object in `SleepDataSession` dto.
=> [sleepiq] Restore type adapter for LocalDate

bundles/org.openhab.persistence.mapdb/src/main/java/org/openhab/persistence/mapdb/internal/MapDbPersistenceService.java, itests/org.openhab.persistence.mapdb.tests/src/main/java/org/openhab/persistence/mapdb/MapDbPersistenceServiceOSGiTest.java
Fixes #14899 
The serialization was done synchronously. Calls to GSON are time-consuming and should therefore be done asynchronously to allow `.store` to return fast.
=> [mapdb] Make serialization asynchronous

CODEOWNERS
mraepple was the original contributor of the nanoleaf addon but hasn't been active for around 2 years now. Keeping him part of the codeowners leads to him being asked as a reviewer for every PR while he never responded for that in the past. 
I am still grateful that he originally created the addon but I would now like to take him out of the codeowners.
=> Nanoleaf codeowners change

bundles/org.openhab.binding.ecovacs/README.md, bundles/org.openhab.binding.ecovacs/src/main/java/org/openhab/binding/ecovacs/internal/api/impl/EcovacsApiImpl.java, bundles/org.openhab.binding.ecovacs/src/main/resources/devices/supported_device_list.json
If a new device is released within our release cycle, getting the description for that device into the binding was impossible for users before. With this change, they can create an override file in their installation (with contents we'll need to supply to them), which serves as a stop-gap solution until the next OH release.
Additionally, add the definition for the device that triggered this change to the supported device list.
=> [ecovacs] Allow loading device descriptions from a user file

bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/handler/NanoleafPanelHandler.java, bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/layout/shape/HexagonCorners.java, bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/layout/shape/Point.java, bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/layout/shape/Shape.java, bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/layout/shape/SingleLine.java
Use new class ```ColorUtil``` which has recently been added to core in https://github.com/openhab/openhab-core/pull/3479.
```HsbType::getRGB()``` has been replaced since it has been deprecated.
=> [nanoleaf] Use new core class ColorUtil for RGB conversion

bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/HueBindingConstants.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/discovery/HueBridgeMDNSDiscoveryParticipant.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/discovery/HueBridgeNupnpDiscovery.java, itests/org.openhab.binding.hue.tests/src/main/java/org/openhab/binding/hue/internal/discovery/HueBridgeNupnpDiscoveryOSGITest.java
With #14871 NUPnP is now working again, which reintroduces overlapping discovery mechanisms - see https://github.com/openhab/openhab-addons/pull/14871#issuecomment-1530142059
For mDNS, `service.getName()` returns "Philips Hue - XXXXXX" where XXXXXX is the last 6 characters of the serial number. This is connected to `service.getQualifiedName()` which is "Philips Hue - XXXXXX._hue._tcp.local.".
There is no reason for including these characters in the label. The full serial number is already visible just below - even two times:
Therefore this PR aligns the label with the label of NUPnP discovery.
This eliminates the problem of the discovery result label changing back and forth:
- Philips Hue - XXXXXX (192.168.0.251)
- Philips Hue (192.168.0.251)
=> [hue] Fix discovery label consistency

bundles/org.openhab.binding.tesla/README.md, bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/TeslaBindingConstants.java, bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/TeslaChannelSelectorProxy.java, bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaAccountHandler.java, bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaVehicleHandler.java, bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/protocol/VehicleData.java
Fixes https://github.com/openhab/openhab-addons/issues/14894
The Tesla API has removed most endpoints that the binding was using for querying vehicle data.
The only one left is an aggregated call to fetch all data at once.
This PR does the necessary changes.
In my tests, all seems to work well. If enough people report that it works for them as well, this would be a candidate to backport to 3.4.x.
=> [tesla] Adapt binding to changed API from Tesla backend

bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/discovery/ICloudDeviceDiscovery.java, bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/handler/ICloudDeviceHandler.java, bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/handler/dto/json/response/ICloudDeviceInformation.java, bundles/org.openhab.binding.icloud/src/test/java/org/openhab/binding/icloud/TestICloud.java
Lately users discover problems with changes in the device ID in the iCloud API.
See discussion here https://community.openhab.org/t/icloud-binding-communication-error/122131/597
I saved the device data json before and after this change happened.
Each device has three IDs in the json:
id, baUUID, deviceDiscoveryId
Currently we use id to identify devices. This id has changed lately (back and forth and now again, see discussion). That's why openhab identfies these devices as new and put them into the inbox. The other IDs did not change - at least between my two files. So we have some chances that changing the binding to use one of the other IDs this problem could be solved.
This PR changes the binding to use deviceDiscoveryId instead of id. As fallback it uses the device name, since old …
=> [iCloud] Fix things reappearing in inbox

bundles/org.openhab.binding.solarwatt/README.md
to reflect support with regards to newer/other solarwatt products.
This modifies the readme to support users to choose the correct binding for their device as some questions popped up in this discussion [https://community.openhab.org/t/solarwatt-new-binding-for-solarwatt-energy-manager/116452](https://community.openhab.org/t/solarwatt-new-binding-for-solarwatt-energy-manager/116452)
=> [solarwatt] Update README.md

bundles/org.openhab.binding.openwebnet/README.md, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/OpenWebNetBindingConstants.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetAlarmHandler.java, bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/i18n/openwebnet.properties, bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusAlarmZone.xml, bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/channels.xml, bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/update/update.xml
**Description:**
This PR allows to show a time stamp when an alarm zone event occurs on Bticino/Legrand Alarm systems such as an Intrusion or a Tampering This PR closes #14535
**Test**
Tested on BTicino/Legrand bulgrar-alarm unit 3486
=> [openwebnet] Add a time stamp when an alarm zone event occurs

bundles/org.openhab.voice.googlestt/src/main/java/org/openhab/voice/googlestt/internal/GoogleSTTService.java
=> [googlestt] Dispose oAuth2 service

bundles/org.openhab.voice.googletts/src/main/java/org/openhab/voice/googletts/internal/GoogleCloudAPI.java, bundles/org.openhab.voice.googletts/src/main/java/org/openhab/voice/googletts/internal/GoogleTTSService.java
=> [googletts] Dispose oAuth2 service

bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/handler/NuvoHandler.java
The publishing of the ALLOFF event to the source channels does not work properly in #14248. The legacy channel id 'button_press' needs to be used when updating the channel state.
=> [nuvo] Fix ALLOFF event to source button channels

bundles/org.openhab.binding.openwebnet/README.md, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetAutomationHandler.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetBridgeHandler.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetThingHandler.java, bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/i18n/openwebnet.properties
Impreved shutterRun parameter automatic calibration by subtracting some fiexd (500ms) and relative (2%) timing to the measured shutter run time. Updated README section to explain better shutterRun calibration.
This should fix #14215.
=> [openwebnet] Improve shutterRun calibration

bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java
Related to #14888 #14900
This is completely untested.
=> [rrd4j] Write asynchronously to database

bundles/org.openhab.persistence.dynamodb/src/main/java/org/openhab/persistence/dynamodb/internal/DynamoDBPersistenceService.java, bundles/org.openhab.persistence.dynamodb/src/main/java/org/openhab/persistence/dynamodb/internal/DynamoDBQueryUtils.java, bundles/org.openhab.persistence.dynamodb/src/test/java/org/openhab/persistence/dynamodb/internal/BaseIntegrationTest.java
Changes in openhab/openhab-core#3481 broke this service due to a breaking API change in NumberItem class (constructor).
Related to openhab/openhab-core#3600
=> [dynamodb] Changes required after API changes in core framework

bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/AuthorizationController.java, bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/AuthorizationListener.java, bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/AuthorizationProvider.java, bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/IndegoController.java, bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/IndegoDeviceController.java, bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/handler/BoschAccountHandler.java, bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/handler/BoschIndegoHandler.java, bundles/org.openhab.binding.boschindego/src/main/resources/OH-INF/i18n/boschindego.properties
This refactoring addresses some issues:
- When a bridge thing is removed, the corresponding OAuth2 token will now be deleted.
- When authorization fails (for example when renewing token), the bridge will now change status to **OFFLINE** with proper authorization failure description, and as a consequence child things will have status detail `BRIDGE_OFFLINE` rather than the authorization failure description.
- Reinitialization of bridge things would cause authorization to fail for child things. This is now fixed.
Follow-up to #14745
=> [boschindego] Refactor OAuth2 implementation

bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/SysteminfoHandlerFactory.java, bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/SysteminfoThingTypeProvider.java, bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/handler/SysteminfoHandler.java, itests/org.openhab.binding.systeminfo.tests/src/main/java/org/openhab/binding/systeminfo/test/SysteminfoOSGiTest.java
This is one of two reference implementations for the use of dynamic type providers.
=> [systeminfo] Use AbstractStorageBasedTypeProvider

bundles/org.openhab.automation.jsscripting/src/main/resources/OH-INF/addon/addon.xml
This was not possible because the config description was missing in the addon.xml.
=> [jsscripting] Allow configuring from add-on page

bundles/org.openhab.automation.jsscripting/README.md, bundles/org.openhab.automation.jsscripting/pom.xml, bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/GraalJSScriptEngineFactory.java, bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/OpenhabGraalJSScriptEngine.java, bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/fs/watch/JSDependencyTracker.java, bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/fs/watch/JSScriptFileWatcher.java
- Minor code improvements
- Add target type mapping for JS-Joda Instant to `java.time.Instant`.
- Upgrade openhab-js to 4.3.0 (see https://github.com/openhab/openhab-js/blob/v4.3.0/CHANGELOG.md).
I've tried adding for other JS-Joda classes as well, but that's not possible because they don't have unique properties that can be used to identify them.
=> [jsscripting] Add type translation for `Instant` & Minor improvements

bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/InfluxDBPersistenceService.java, bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/InfluxDBRepository.java, bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/influx1/InfluxDB1RepositoryImpl.java, bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/influx2/InfluxDB2RepositoryImpl.java, bundles/org.openhab.persistence.influxdb/src/test/java/org/openhab/persistence/influxdb/ItemToStorePointCreatorTest.java
See title. This will be needed to store forecasts or retrospectivly added data.
=> [influxdb] Implement ModifiablePersistenceService

bundles/org.openhab.binding.harmonyhub/src/main/java/org/openhab/binding/harmonyhub/internal/HarmonyHubDynamicTypeProvider.java, bundles/org.openhab.binding.harmonyhub/src/main/java/org/openhab/binding/harmonyhub/internal/HarmonyHubHandlerFactory.java, bundles/org.openhab.binding.harmonyhub/src/main/java/org/openhab/binding/harmonyhub/internal/handler/HarmonyDeviceHandler.java, bundles/org.openhab.binding.harmonyhub/src/main/java/org/openhab/binding/harmonyhub/internal/handler/HarmonyHubHandler.java
This is the second of two reference implementations for the use of dynamic type providers.
=> [harmonyhub] Use AbstractStorageBasedTypeProvider

bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitCharacteristicFactory.java, bundles/org.openhab.io.homekit/src/main/resources/OH-INF/addon/addon.xml, bundles/org.openhab.io.hueemulation/src/main/resources/OH-INF/addon/addon.xml, bundles/org.openhab.io.imperihome/src/main/resources/OH-INF/addon/addon.xml, bundles/org.openhab.io.metrics/src/main/resources/OH-INF/addon/addon.xml, bundles/org.openhab.io.neeo/src/main/resources/OH-INF/addon/addon.xml, bundles/org.openhab.io.openhabcloud/src/main/resources/OH-INF/addon/addon.xml, pom.xml
New static code analysis tools package has been released, lifting the versions of
PMD from 6.39.0 to 6.53,
SpotBugs from 4.7.0 to 4.7.3,
Checkstyle from 8.45.1 to 10.6.0;
and to adapt to schema changes in OH 4.0.
Looking at the check results, there is one substantial difference between 0.13 and 0.14, see the comparison below:
- pmd UnusedPrivateMethod is reduced by ~100 
- (EmptyControlStatement replaces several Empty* rules, this is intended)
Refs: openhab/openhab-core#3599
=> Upgrade SAT to 0.14

bundles/org.openhab.persistence.jdbc/src/main/resources/OH-INF/addon/addon-derby.xml, bundles/org.openhab.persistence.jdbc/src/main/resources/OH-INF/addon/addon-h2.xml, bundles/org.openhab.persistence.jdbc/src/main/resources/OH-INF/addon/addon-hsqldb.xml, bundles/org.openhab.persistence.jdbc/src/main/resources/OH-INF/addon/addon-mariadb.xml, bundles/org.openhab.persistence.jdbc/src/main/resources/OH-INF/addon/addon-mysql.xml, bundles/org.openhab.persistence.jdbc/src/main/resources/OH-INF/addon/addon-postgresql.xml, bundles/org.openhab.persistence.jdbc/src/main/resources/OH-INF/addon/addon-sqlite.xml
JDBC defines several add-ons with different add-on ids. Therefore separate addon.xml files are needed (one for each id)
=> [jdbc] Fix addon-info

bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/discovery/HueBridgeNupnpDiscovery.java
Related to #14871, #14918
Resolves #14852
=> [hue] Fix `NullPointerException` in NUPnP discovery

bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/handler/AccountHandler.java, bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/server/CallbackServer.java
=> [mercedesme] Remove the access token when the thing is removed

bundles/org.openhab.binding.mqtt.espmilighthub/README.md, bundles/org.openhab.binding.mqtt.espmilighthub/src/main/java/org/openhab/binding/mqtt/espmilighthub/internal/handler/EspMilightHubHandler.java
Added the extra needed steps to the readme file and also helpful thing status messages to guide a user on what is now needed after PR #13800
Without doing extra setup steps, the last PR has caused all the things to stay on initializing status as the connected MQTT message that is needed never gets received.
=> [mqtt.espmilighthub] Fix things do not come ONLINE if MQTT Client Status Topic not supplied.

bundles/org.openhab.binding.bluetooth.airthings/README.md, bundles/org.openhab.binding.bluetooth.airthings/src/main/java/org/openhab/binding/bluetooth/airthings/internal/AirthingsWavePlusHandler.java
Related to https://github.com/openhab/openhab-core/pull/3608
Note: Existing configurations must be changed to use the new dimension `RadiationSpecificActivity ` instead of `Density`.
=> [airthings] Adapt channels to new dimention for Radon measurements

itests/org.openhab.binding.modbus.tests/src/main/java/org/openhab/binding/modbus/tests/AbstractModbusOSGiTest.java, itests/pom.xml
Builds for #15010 somehow do not complete. This is a try to do it separately.
Re-enable itests for modbus.
After core change ```CoreItemFactory``` ctor requires a ```UnitProvider```.
From itests the class ```TestUnitProvider``` is not visible, so I tried a mockup.
Jenkins results need to be reviewed.
=> Re-enable itests after core change

bundles/org.openhab.binding.surepetcare/src/main/java/org/openhab/binding/surepetcare/internal/SurePetcareAPIHelper.java
Fixes #15046
JAR for testing:
- [org.openhab.binding.surepetcare-3.4.5-SNAPSHOT.jar](https://drive.google.com/file/d/1DVc7WXm2Ec7ft57snXHf20hkbX0RIxc_/view?usp=sharing)
- [org.openhab.binding.surepetcare-4.0.0-SNAPSHOT.jar](https://drive.google.com/file/d/12GFJzvpmUk4hpv6Bf-hUytxYNe-yDPsi/view?usp=sharing)
=> [surepetcare] Adapt blocked user agent

bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/ValueDecoder.java
The custom function to handle DPT 10.001 incorrectly handled the exception when a value that is not in the format "EEE, HH:MM:SS" was fed into the function. It now correctly handles "HH:MM:SS" data sent by KNX actors
Signed-Off-By: Karel Goderis <karel.goderis@me.com>
=> [knx] Fix DPT 10.001 handling

bundles/org.openhab.binding.opengarage/src/main/java/org/openhab/binding/opengarage/internal/OpenGarageHandler.java, bundles/org.openhab.binding.opengarage/src/main/resources/OH-INF/i18n/opengarage.properties, bundles/org.openhab.binding.opengarage/src/main/resources/OH-INF/thing/thing-types.xml
The current implementation logs vehicle status of `3` as a `WARN`. This PR proposes we change the behavior and support not available which is inline with the [OpenGarage firmware](https://github.com/OpenGarage/OpenGarage-Firmware/blob/8fab4c65a1b2b9b8b57659c1ddd3ba0f9b26816b/OpenGarage/defines.h#L78).
I believe this change is an improvement. Thanks for all of the great work on openHAB! 
N/A - this add-on does not have tests.
=> [opengarage] Add support for vehicle status not available.

bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/BoschHttpClient.java, bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/bridge/BoschHttpClientTest.java
=> [boschshc] Upgrade to REST API version 3.2

bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/KM200Cryption.java, bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/KM200Device.java
The oldest device seems to cause some trouble for this binding as it queries the attribute /gateway/registrations, which leads to an inconsistency in the gateway answers. This prevents the binding to move forward into the initialized mode.
Solving the old [bug report](https://community.openhab.org/t/km200-km50-100-200-gateway-uninitialized-handler-initializing-error/107615).
=> [km200] Fix support for older MB-LAN (=KM200, version 1.0) by avoiding query of an unsupported attribute.

bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/influx1/InfluxDB1RepositoryImpl.java, bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/influx2/InfluxDB2RepositoryImpl.java
As reported on the forum (https://community.openhab.org/t/oh4-m2-m3-influxdb-restoreonstartup-fails-timeout-exceptions-in-startup-logs/146915)the influx persistence service does not properly handle exceptions. 
This does NOT fix the reported issue, but it prevents the persistence service from crashing and flooding the log with stack traces. The original issue seems to be a connection issue where the socket times out.
=> [influxdb] Handle exceptions gracefully

bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java, bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/console/RRD4jCommandExtension.java
Console commands added to detect and remove RRD files associated with items that no longer exist.
=> [rrd4j] Add console commands to check and clean RRD files

bundles/org.openhab.binding.robonect/src/main/java/org/openhab/binding/robonect/internal/RobonectBindingConstants.java, bundles/org.openhab.binding.robonect/src/main/java/org/openhab/binding/robonect/internal/RobonectHandlerFactory.java, bundles/org.openhab.binding.robonect/src/main/java/org/openhab/binding/robonect/internal/handler/RobonectHandler.java, bundles/org.openhab.binding.robonect/src/test/java/org/openhab/binding/robonect/internal/handler/RobonectHandlerTest.java
Fixes #15001
Related to #9429
Because of this:
https://github.com/openhab/openhab-addons/blob/ccab566172da7e3e86b39ab5dfab6471959e3959/bundles/org.openhab.binding.robonect/src/main/java/org/openhab/binding/robonect/internal/RobonectClient.java#L160-L183
I refactored the code to create a custom HTTP client to not mess with the `AuthenticationStore` of the shared HTTP client.
JARs:
- [org.openhab.binding.robonect-3.4.5-SNAPSHOT.jar](https://drive.google.com/file/d/1wpeK-9pDoFNJJcz34qGG3s8MEL7nWGjk/view?usp=sharing)
- [org.openhab.binding.robonect-4.0.0-SNAPSHOT.jar](https://drive.google.com/file/d/1X052s8OREsJ2W35sIeuWBFAkpmG8h9xn/view?usp=sharing)
=> [robonect] Fix `NullPointerException` on reinitialization

bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java
Fixes #15054 
Storage retry is now tried immediately, not scheduled. This should prevent having the "next" value being stored before the current one.
=> [rrd4j] Improve timestamp handling

bundles/org.openhab.binding.helios/src/main/java/org/openhab/binding/helios/internal/HeliosHandlerFactory.java, bundles/org.openhab.binding.helios/src/main/java/org/openhab/binding/helios/internal/handler/HeliosHandler221.java
Fixes https://github.com/openhab/openhab-distro/issues/1546
Signed-Off-By: Karel Goderis <karel.goderis@me.com>
=> [Helios] Fix error handling + migrate to the injected JAX-RS ClientBuilder

bom/openhab-addons/pom.xml, bundles/org.openhab.persistence.inmemory/NOTICE, bundles/org.openhab.persistence.inmemory/README.md, bundles/org.openhab.persistence.inmemory/pom.xml, bundles/org.openhab.persistence.inmemory/src/main/feature/feature.xml, bundles/org.openhab.persistence.inmemory/src/main/java/org/openhab/persistence/inmemory/internal/InMemoryPersistenceService.java, bundles/org.openhab.persistence.inmemory/src/main/resources/OH-INF/addon/addon.xml, bundles/org.openhab.persistence.inmemory/src/test/java/org/openhab/persistence/inmemory/internal/InMemoryPersistenceTests.java, bundles/pom.xml
As discussed in https://github.com/openhab/openhab-core/pull/3597 sometimes a "short-term" persistence service should be available. This adds a volatile persistence service (unfortunately using "volatile" is not possible because it can't be used in package names) with a configurable number of entries per item. When the maximum number of entries is reached, the earliest is removed. This makes it especially useful for storing forecasts and similar data that is populated at runtime and does not need to survive restarts.
=> [inmemory] Initial contribution

bundles/org.openhab.automation.jsscriptingnashorn/src/main/resources/OH-INF/addon/addon.xml
See #15125 
The addon-id was wrong (the same as for `jsscripting`), leading to wrong responses of the add-on service when both are installed.
=> [jsscriptingnashorn] Fix addon.xml

bundles/org.openhab.binding.yamahamusiccast/src/main/java/org/openhab/binding/yamahamusiccast/internal/YamahaMusiccastHandler.java
The volumeDB channel did not accept DecimalType commands because it attempted to cast any commands to QuantityType and then call `.floatValue()` on it. I'm not sure why I did it this way when adding that channel, this PR fixes the problem.
=> [yamahamusiccast] Fix DecimalType commands for volumeDB channel

itests/org.openhab.automation.groovyscripting.tests/itest.bndrun, itests/org.openhab.automation.jsscriptingnashorn.tests/itest.bndrun, itests/org.openhab.binding.astro.tests/itest.bndrun, itests/org.openhab.binding.avmfritz.tests/itest.bndrun, itests/org.openhab.binding.feed.tests/itest.bndrun, itests/org.openhab.binding.hue.tests/itest.bndrun, itests/org.openhab.binding.max.tests/itest.bndrun, itests/org.openhab.binding.mielecloud.tests/itest.bndrun, itests/org.openhab.binding.modbus.tests/itest.bndrun, itests/org.openhab.binding.mqtt.homeassistant.tests/itest.bndrun, itests/org.openhab.binding.mqtt.homie.tests/itest.bndrun, itests/org.openhab.binding.nest.tests/itest.bndrun, itests/org.openhab.binding.ntp.tests/itest.bndrun, itests/org.openhab.binding.systeminfo.tests/itest.bndrun, itests/org.openhab.binding.tradfri.tests/itest.bndrun, itests/org.openhab.binding.wemo.tests/itest.bndrun, itests/org.openhab.persistence.mapdb.tests/itest.bndrun
With openhab/openhab-core#3355 the dependencies changed.
=> Resolve itest runbundles

bundles/org.openhab.binding.androidtv/pom.xml
Updates bouncycastle dependency from jdk15on to jdk18on and bumps version to 1.75 (current)
Replaces #15137
=> [androidtv] Updates BouncyCastle to jdk18on and 1.75

bundles/org.openhab.binding.androidtv/src/main/java/org/openhab/binding/androidtv/internal/protocol/googletv/GoogleTVMessageParser.java, bundles/org.openhab.binding.androidtv/src/main/java/org/openhab/binding/androidtv/internal/protocol/shieldtv/ShieldTVMessageParser.java
Adjusts exception logging for the MessageParsers so they provide the offending message for troubleshooting purposes.  Also adjusts both to be info level logging as failures in the MessageParsers are significant and should be reported.
=> [androidtv] Normalized exception logging for both MessageParsers

bundles/org.openhab.binding.ipcamera/README.md, bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/IpCameraDiscoveryService.java, bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/onvif/OnvifDiscovery.java
This PR fixes the issue reported here that most likely is an access issue caused by the use of docker. Closes #14500 
It restricts the binding to only search the network that openHAB has setup as the primary address so if one of your networks causes issues the binding will no longer try to search using all internal networks, but only the selected one.
The PR also improves the discovery of cameras that do not reply with an ONVIF xaddress and will try to discover the brand from the cameras login page.
This pull request will automatically be built and available under the following links if anyone wants to test:
https://openhab.jfrog.io/ui/native/libs-pullrequest-local/org/openhab/addons/bundles/
https://openhab.jfrog.io/ui/native/libs-pullrequest-local/org/openhab/addons/bundles/org.openhab.b …
=> [ipcamera] Fix discovery crashes when networks have access rights issues in docker

bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosAudioSink.java
=> [sonos] Support for more audio streams through the HTTP audio servlet

bundles/org.openhab.binding.intesis/README.md, bundles/org.openhab.binding.intesis/src/main/java/org/openhab/binding/intesis/internal/IntesisBindingConstants.java, bundles/org.openhab.binding.intesis/src/main/java/org/openhab/binding/intesis/internal/api/IntesisHomeHttpApi.java, bundles/org.openhab.binding.intesis/src/main/java/org/openhab/binding/intesis/internal/config/IntesisBoxConfiguration.java, bundles/org.openhab.binding.intesis/src/main/java/org/openhab/binding/intesis/internal/config/IntesisHomeConfiguration.java, bundles/org.openhab.binding.intesis/src/main/java/org/openhab/binding/intesis/internal/handler/IntesisBoxHandler.java, bundles/org.openhab.binding.intesis/src/main/java/org/openhab/binding/intesis/internal/handler/IntesisHomeHandler.java, bundles/org.openhab.binding.intesis/src/main/resources/OH-INF/thing/thing-types.xml
Signed-off-by: Hans-Jörg Merk [github@hmerk.de](mailto:github@hmerk.de)
=> [intesis] Add configurable polling interval

bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcTimescaledbDAO.java
The db type in jdbc:<dbtype>://... will be replaced from timescaledb to postgresql.
When the host/service is named timescaledb too (could happen easily on kubernetes), this will be replaced as well so the connection url isn't correct anymore.
With this change it couldn't happen that the connection url is modified erroneous. 
The change was already build locally and run on my production environment without any errors.
=> [jdbc] stabilize timescale db type replacement

CODEOWNERS, bundles/org.openhab.binding.mail/README.md, bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/internal/MailBindingConstants.java, bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/internal/MailCountChannelType.java, bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/internal/MailHandlerFactory.java, bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/internal/POP3IMAPHandler.java, bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/internal/ServerSecurity.java, bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/internal/config/POP3IMAPConfig.java, bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/internal/config/POP3IMAPContentChannelConfig.java, bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/internal/config/POP3IMAPMailCountChannelConfig.java, bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/internal/config/SMTPConfig.java, bundles/org.openhab.binding.mail/src/main/resources/OH-INF/i18n/mail.properties, bundles/org.openhab.binding.mail/src/main/resources/OH-INF/thing/thing-types.xml, bundles/org.openhab.binding.mail/src/test/java/org/openhab/binding/mail/internal/MailBuilderTest.java, tools/static-code-analysis/checkstyle/suppressions.xml
Originally contributed as https://github.com/smarthomej/addons/pull/131 and https://github.com/smarthomej/addons/pull/159.
This adds content processing to the IMAP and POP3 things. The content can be pre.processed before it is written to a channel.
=> [mail] Add mail content processing

bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/i18n/energidataservice.properties, bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/thing/channel-types.xml
Fix small regression from #14376 noticed when translating texts.
=> [energidataservice] Remove obsoleted texts and update description

bundles/org.openhab.binding.hydrawise/src/main/java/org/openhab/binding/hydrawise/internal/api/graphql/HydrawiseGraphQLClient.java
The Hydrawise API can return sometimes return a non JSON response during service outages, like when they are updating their software.  This treats this as a connection error and allows the client to try the poll again.
Fixes #15170
=> [hydrawise] Fixes occasional connection issues

bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/handler/KaleidescapeMessageHandler.java
Fixes issue where the image channel would work in sitemaps viewed in a browser but not in the openHAB android app.
=> [kaleidescape] Fix image channel MIME type

bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/handler/NuvoHandler.java
Fixes issue where the image channel would work in sitemaps viewed in a browser but not in the openHAB android app.
=> [nuvo] Fix image channel MIME type

bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/ConvertedInputStream.java, bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/PulseAudioAudioSink.java, bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/PulseaudioHandlerFactory.java, bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/handler/PulseaudioHandler.java
Following some rewrite with openhab/openhab-core#3461
- Makes the process method a little bit asynchronous, and uses the new 'complete' system to signal core that the sound is fully played.
- Supports more stream class (and not only the arbitrary FixedLengthAudioStream)
- Use Disposable to get rid of deletable resource used by stream.
Implementation remark : I do not use AudioSinkSync or AudioSinkAsync as a base class because the PulseAudioAudioSink already extends another class. Separing concern does not seem a good idea as it breaks the symetry with AudioSource.
=> [pulseaudio] Make the process method asynchronous

bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/SqueezeBoxAudioSink.java
Squeezebox audio sink supporting more audio streams, with the help of the HTTP audio servlet new capabilities.
Related to openhab/openhab-addons#15113
=> [squeezebox] Support for more audio streams through the audio servlet

bundles/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromecastAudioSink.java, bundles/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/action/ChromecastActions.java, bundles/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/factory/ChromecastHandlerFactory.java, bundles/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/handler/ChromecastHandler.java
Following some rewrite with openhab/openhab-core#3461
Fix volume change/restoration and temporary files handling by using the new core capabilities.
In order to do this properly (by using an async base class), I also separated audiosink in its own class.
=> [chromecast] Support for more audio streams through the audio servlet

bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/threading/ThreadsafeTimers.java, bundles/org.openhab.automation.jsscripting/src/main/resources/node_modules/@jsscripting-globals.js
Fixes #15182.
This implements NodeJS/WebAPI-like parameter handling for the `setTimeout` and `setInterval` polyfills as documented in the [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/API/setTimeout).
=> [jsscripting] Implement NodeJS-like parameter handling for timer polyfills

bundles/org.openhab.binding.amplipi/src/main/java/org/openhab/binding/amplipi/internal/audio/PAAudioSink.java
=> [amplipi] Support for more audio streams through the HTTP audio servlet

bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/KodiAudioSink.java, bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/handler/KodiHandler.java
Kodi audio sink supporting more audio streams, with the help of the HTTP audio servlet new capabilities.
Also (slightly) better volume restoration from openHAB.
Note : The previous system for volume restoration (inside kodi binding) doesn't seem to work. It seems to try to guess when play ends by waiting for state that doesn't happen, and/or for not enough time ?
Plus, when openHAB tried to handle volume, both of them modified it at different time, leading to a mess. I added a boolean to avoid conflict.
So I replace it with the sound duration analysis from the servlet.
It's better but it is not reliable either, because Kodi keep requesting the stream again and again, resetting the time we consider as the "start".
=> [kodi] Support for more audio streams through the HTTP audio servlet

bundles/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromecastAudioSink.java
Rethrow a wrapped exception instead of only logging, like the other audio sinks.
Asked by @lolodomo in [this review](https://github.com/openhab/openhab-addons/pull/15180#discussion_r1257173983)
=> [chromecast] Harmonize exception processing

bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/AirMediaSink.java
Signed-off-by: Laurent Garnier <lg.hc@free.frf>
=> [freeboxos] Align audio sink to freebox binding

bundles/org.openhab.voice.voicerss/README.md, bundles/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/internal/VoiceRSSRawAudioStream.java, bundles/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/internal/VoiceRSSTTSService.java, bundles/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/internal/cloudapi/CachedVoiceRSSCloudImpl.java, bundles/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/internal/cloudapi/VoiceRSSCloudAPI.java, bundles/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/internal/cloudapi/VoiceRSSCloudImpl.java, bundles/org.openhab.voice.voicerss/src/test/java/org/openhab/voice/voicerss/internal/VoiceRSSTTSServiceTest.java
=> [voicerss] Add LRU cache

bundles/org.openhab.binding.allplay/src/main/java/org/openhab/binding/allplay/internal/AllPlayAudioSink.java
=> [allplay] Support for more audio streams through the HTTP audio servlet

bundles/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/FreeboxAirPlayAudioSink.java
=> [freebox] Support for more audio streams through the HTTP audio servlet

bundles/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/OnkyoHandlerFactory.java, bundles/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/handler/OnkyoAudioSink.java, bundles/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/handler/OnkyoHandler.java, bundles/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/handler/OnkyoUpnpHandler.java
=> [onkyo] Support for more audio streams through the HTTP audio servlet

bundles/org.openhab.binding.telegram/src/main/java/org/openhab/binding/telegram/internal/action/TelegramActions.java
This PR will now log when a camera is asking for Digest auth as the binding only support BASIC. A number of users have been calling it a bug here so this PR will just make it 100% clear what the cause is:
closes #9792
=> [Telegram] Log when cameras do not support BASIC auth support.

bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/EaseeBindingConstants.java
API base URL has changed and old URL will be switched off by end of August 2023.
see https://developer.easee.cloud/docs/integrations-30
=> [easee] Adopt API base URL due to changes

bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java
=> [rrd4j] Improve event handling

bundles/org.openhab.binding.androidtv/README.md, bundles/org.openhab.binding.androidtv/src/main/java/org/openhab/binding/androidtv/internal/console/AndroidTVCommandExtension.java
Adds a CLI interface for the androidtv binding.
Resolves #15143
=> [androidtv] Adds CLI Interface

bundles/org.openhab.binding.androidtv/src/main/java/org/openhab/binding/androidtv/internal/protocol/googletv/GoogleTVConnectionManager.java, bundles/org.openhab.binding.androidtv/src/main/java/org/openhab/binding/androidtv/internal/utils/AndroidTVPKI.java
This is mostly for debugging protocol issues on remote devices when they can not be reproduced locally.
Automates the PKI process for shim.  
Adds Trusted CA Certificate functions to AndroidTVPKI
=> [androidtv] Moves Shim PKI to AndroidTVPKI and adds Trusted CA Certificate functions

bundles/org.openhab.voice.rustpotterks/pom.xml
Hi openHAB maintainers, I discovered a couple of days ago a miscalculation on the gain normalizer that made the feature inconsistent. I had to release a new library version.
Already tested over the latest snapshot.
=> [rustpotterks] Upgrade library, fixes gain normalizer

bundles/org.openhab.binding.openwebnet/README.md, bundles/org.openhab.binding.openwebnet/pom.xml, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetBridgeHandler.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/config/OpenWebNetBusBridgeConfig.java, bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/i18n/openwebnet.properties, bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusGateway.xml
This enhancement PR adds a `dateTimeSynch` configuration parameter to `bus_gateway` Things to  synchronise date and time of slave elements on the SCS BUS using openHAB timestamp.
If this parameter is set to `true` the handler will send time-date synchronisation commands on the BUS when the timestamp received from the gateway differs by more than 1 minute from that of openHAB. 
This enhancement is useful if the BUS gateway is not syncronized with Internet time servers and with daylight saving time changes.
Feature has been tested successfully with one community user.
Fixes #12018
=> [openwebnet] add date time synchronization feature for bus_gateway Things

bundles/org.openhab.binding.telegram/src/main/java/org/openhab/binding/telegram/internal/TelegramHandler.java
Updates from channels were ignored (see also https://community.openhab.org/t/telegram-bot-does-not-receive-messages-from-the-channel/101913/3).
Use channelPost() API to get channel message. lastName, firstName, username can be null.
https://openhab.jfrog.io/artifactory/libs-pullrequest-local/org/openhab/addons/bundles/org.openhab.binding.telegram/4.0.0-SNAPSHOT/org.openhab.binding.telegram-4.0.0-SNAPSHOT.jar
=> [Telegram] Support processing of channel messages

bundles/org.openhab.binding.openwebnet/README.md, bundles/org.openhab.binding.openwebnet/pom.xml, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/discovery/OpenWebNetDeviceDiscoveryService.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetBridgeHandler.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetThermoregulationHandler.java, bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/i18n/openwebnet.properties, bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusThermoCentralUnit.xml, bundles/org.openhab.binding.openwebnet/src/test/java/org/openhab/binding/openwebnet/internal/handler/OwnIdTest.java
This PR adds support for 4-zones Thermo Central Units, like BTicino model N4695 in addition to the 99-zone Central Unit.
Changes have been made to support its WHERE address format (#0#1) and device discovery to distinguish between 99-zone and 4-zone CU.
This PR also updates the dependency to the openwebnet4j lib to its latest version: 0.10.0
Changes have been tested positively with some users in the community.
This PR fixes issue #14444.
=> [openwebnet] Thermo: add support for 4-zones CU

bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/Ffmpeg.java, bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/InstarHandler.java, bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/handler/IpCameraHandler.java, bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/onvif/OnvifConnection.java
TAPO branded cameras require the xAddr port to be different from the port used for the rest of ONVIF comms. Currently this is blocking events/alarms from working on those cameras.
This PR is mostly the same proven code shuffled around to allow the port to be parsed and changed based on what xAddr the camera is requesting the traffic to be sent to.
closes #14738
I also put a fix in for Instar cameras.
closes #14363
This pull request will automatically be built and available under the following links if anyone wants to test:
https://openhab.jfrog.io/ui/native/libs-pullrequest-local/org/openhab/addons/bundles/
https://openhab.jfrog.io/ui/native/libs-pullrequest-local/org/openhab/addons/bundles/org.openhab.binding.ipcamera/4.0.0-SNAPSHOT/org.openhab.binding.ipcamera-4.0.0-SNAPSHOT.jar …
=> [ipcamera] FIX: TAPO branded cameras require xAddr port to be different

bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetThermoregulationHandler.java
To support older configurations for CU with where="0" this change is needed after recent changes (PR #15111 )
=> [openwebnet] Backward support for CU configurations with where="0"

bundles/org.openhab.binding.androidtv/src/main/java/org/openhab/binding/androidtv/internal/protocol/googletv/GoogleTVConnectionManager.java, bundles/org.openhab.binding.androidtv/src/main/java/org/openhab/binding/androidtv/internal/protocol/googletv/GoogleTVMessageParser.java
As seen in #15153 when the GoogleTV protocol stack has an unrecoverable error it causes a loop of login/fail/repeat.  These errors are unrecoverable by the end user and require developer intervention.  Rather than run up the CPU and flood the log, we need to take that thing offline completely.  This triggers the handler to dispose entirely when that message comes in to avoid an endless loop.  
To note, this should NOT close #15153, this only fixes the log flooding issue, not the actual issue that caused the failure in the first place.
=> [androidtv] Fixes log flooding from protocol error

bundles/org.openhab.automation.jrubyscripting/README.md, bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/JRubyScriptEngineConfiguration.java, bundles/org.openhab.automation.jrubyscripting/src/main/resources/OH-INF/config/config.xml, bundles/org.openhab.automation.jrubyscripting/src/main/resources/OH-INF/i18n/jruby.properties
so that the helper library compatible with 4.0.0.M3+ will be used
See also https://github.com/openhab/openhab-jruby/issues/84
=> [jrubyscripting] loosen default gem version constraint

bundles/org.openhab.binding.openwebnet/pom.xml, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetThermoregulationHandler.java
This is a cumulative PR to primarly fix handling of Thermo Central Unit state channels `atLeastOneProbeX ` that were not updated correctly.
Thanks to a refactoring it also fixes other smaller issues related to thermo Central Unit channels.
The PR has been tested with one community user and with some simulated integration tests.
Lib openwebnet4j bumped to version 0.10.1.
Fixes #15103
Fixes #14449
Fixes #12599
=> [openwebnet] Fix update of Thermo Central Unit atLeastOneProbeX channels and refactoring

bundles/org.openhab.binding.openwebnet/README.md
Current sitemap configuration suggested on README does not work with  AUX items. in the past a user pointed out that the aux had a problem  with sitemaps. I confirm that   when the item is set as Switch on sitemap it does not work, in fact programmatically the aux command is defined as StringType.
https://community.openhab.org/t/openwebnet-bticino-legrand-binding-beta-4-0-0-0-4-1-0-0/129775/30?u=giovanni_fabiani
Finally a solution has been found 
The rest remains unchanged
Tested on Bticino Alarm unit 3486
closes #15254
=> [openwebnet] Fix README for Sitemap AUX configuration  to the correct mapping

bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java
Fixes #15270 
The reason is that newly created RRD files are initialized with a timestamp of (now-1). When a lot of files are created, it may take longer than a second and the timestamp of the event and the timestamp of the creation are the same. I have now increased the start time offset to one step size (usually 10s).
=> [rrd4j] Fix database start time

bundles/org.openhab.binding.androidtv/src/main/java/org/openhab/binding/androidtv/internal/AndroidTVHandler.java
As reported on the forum, if the device is physically offline for a prolonged time the developer sidebar on the UI can have a log flood event.  This adds an additional check to make sure we aren't updating the thing status unless it actually changes.
Example flood:
```
* openhab/things/androidtv:googletv:E89EB43854BA/status
ThingStatusInfoEvent
{"status":"OFFLINE","statusDetail":"NONE","description":"GoogleTV: Error opening SSL connection. Check log."}
* openhab/things/androidtv:googletv:E89EB43854BA/status
ThingStatusInfoEvent
{"status":"OFFLINE","statusDetail":"NONE","description":"GoogleTV: Error opening SSL connection. Check log."}
* openhab/things/androidtv:googletv:E89EB43854BA/status
ThingStatusInfoEvent
{"status":"OFFLINE","statusDetail":"NONE","description":"GoogleTV: Error …
```
=> [androidtv] Fix log flood when physical device is not online

bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/handler/GenericMQTTThingHandler.java, bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/internal/handler/ThingChannelConstants.java
=> [mqtt] Dynamically change accepted item-type for Number channels

bundles/org.openhab.binding.nuvo/README.md, bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/NuvoBindingConstants.java, bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/communication/NuvoEnum.java, bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/handler/NuvoHandler.java
The main goal of this PR is to accomplish a minor refactoring by standardizing the use of the Zone/Source enum instead of numeric string keys that were inconsistently implemented.
One small new feature is included that improves the utility of the `favorite` channel in each zone. In additional to the 12 built-in zone favorites, any favorites specified by the user for an openHAB NuvoNet source (visible in the physical keypad) are also displayed and can be selected by the `favorite` channel.
=> [nuvo] Include NuvoNet source favorites in zone `favorite` channel

bundles/org.openhab.voice.googletts/src/main/java/org/openhab/voice/googletts/internal/GoogleTTSService.java
Fix #15303
It is not allowed to clear an unmodified hash set.
=> [googletts] Avoid UnsupportedOperationException during dispose

bundles/org.openhab.binding.plex/src/main/java/org/openhab/binding/plex/internal/handler/PlexApiConnector.java, bundles/org.openhab.binding.plex/src/main/java/org/openhab/binding/plex/internal/handler/PlexServerHandler.java
Addresses #15304 
Test build: https://github.com/mlobstein/openhab-addons/releases/download/4.0/org.openhab.binding.plex-4.1.0-SNAPSHOT.jar
@morph166955 
@aronbeurskens
=> [plex] Use https for local connections

bundles/org.openhab.binding.hue/doc/readme_v2.md, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/connection/Clip2Bridge.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/dto/clip2/Button.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/dto/clip2/LightLevel.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/dto/clip2/Resource.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/Clip2BridgeHandler.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/Clip2ThingHandler.java
This PR fixes a number of issues raised since the initial release of API v2 support as follows:
1. Shortly before merging #13570 we discussed in this [thread](https://github.com/openhab/openhab-addons/pull/13570#discussion_r1241265369) some potential open issues concerning the handling of GO_AWAY events sent by the Hue bridge server. This PR resolves those issues.
2. When multiple HTTP PUT commands are sent over parallel HTTP2 streams, the Hue Bridge server will sometimes get confused, and return an HTML error. This PR resolves that issue by serializing the PUT commands.
3. A user reported a bug in the start up behaviour of  button trigger channels [here](https://community.openhab.org/t/philips-hue-clip-2-api-v2-discussion-thread/142111/166). When the binding is started up, it would …
=> [hue] Fix reconnection, parallel commands, trigger channels, and light level formula

bundles/org.openhab.binding.shelly/README.md, bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/ShellyBindingConstants.java, bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyApiResult.java, bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyHttpClient.java, bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiClient.java, bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiJsonDTO.java, bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiRpc.java, bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2RpcSocket.java, bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/discovery/ShellyThingCreator.java, bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyBaseHandler.java, bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/thing/shellyGen2_relay.xml
- Shelly Plus/Pro (Gen2) implement HTTP Digest Auth when enabled "password protected device". Previously the auth response was sent as part of the posted http data. Firmware 1.0beta 3+ now requires to implement it conforming to the RFC as http "Authorization: Digest" header attribute. Security improvement: Do not include Basic Auth on /shelly for Gen 1+2 and /rpc for Gen2 to avoid exposing the password
- Set API connect and request timeout to 10sec
- Delete script when disabling BLU Gateway support in thing config
- Fix switching thing status when firmware upgrade is progressing
- Fix group names for Shelly Plus 2
=> [shelly] Fix Plus/Pro Auth support

bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/lib/serverconnection/impl/HttpTransportImpl.java
Fixes #15318
Reverts #14402
This is a quick fix reintroducing the usage of `org.apache.commons.lang3.StringUtils`.
See https://github.com/openhab/openhab-addons/pull/14402/files#diff-df9f8b976479b842550bcc37488539b40345f2ebe59da2a572b1a2728e5b11a8
=> [digitalstrom] Fix `StringIndexOutOfBoundsException`

bundles/org.openhab.automation.jsscripting/pom.xml
It was found out that a recent change to the webpack config for the library injection bundle heavily affected performance of the evaluation of the cached injection.
openhab-js 4.5.1 fixes that regression and one minor bug, see https://github.com/openhab/openhab-js/blob/v4.5.1/CHANGELOG.md#451.
=> [jsscripting] Upgrade openhab-js to fix cached library injection

bundles/org.openhab.binding.millheat/src/main/java/org/openhab/binding/millheat/internal/handler/MillheatAccountHandler.java
Increase mill heat cloud service timeout to 30 seconds to possibly avoid unnecesary comm errors
=> [millheat] Increase http comm timeout to 30 seconds

bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/Clip2ThingHandler.java
=> [hue] Reintroduce LK Wiser dimmer work-around for API v2

bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/handler/EnOceanBaseActuatorHandler.java, bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/handler/EnOceanBaseSensorHandler.java, bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/handler/EnOceanBridgeHandler.java, bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/handler/EnOceanClassicDeviceHandler.java, bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/transceiver/EnOceanTransceiver.java
Fixes #15328
Regression of #14023
For testing:
- [org.openhab.binding.enocean-4.1.0-SNAPSHOT.jar](https://drive.google.com/file/d/1yetaCELUpnrf0Z_rVwgjBmijpVRrL_bJ/view?usp=sharing)
- [org.openhab.binding.enocean-4.1.0-SNAPSHOT.kar](https://drive.google.com/file/d/1fMZRVKLJbgS3XbXk6DPTIDpXRqSFbksE/view?usp=sharing)
=> [enocean] Fix disposal of running tasks

bundles/org.openhab.binding.mystrom/README.md, bundles/org.openhab.binding.mystrom/src/main/java/org/openhab/binding/mystrom/internal/MyStromBindingConstants.java, bundles/org.openhab.binding.mystrom/src/main/java/org/openhab/binding/mystrom/internal/MyStromPlugHandler.java, bundles/org.openhab.binding.mystrom/src/main/resources/OH-INF/i18n/mystrom.properties, bundles/org.openhab.binding.mystrom/src/main/resources/OH-INF/thing/thing-types.xml, bundles/org.openhab.binding.mystrom/src/main/resources/OH-INF/update/instructions.xml, bundles/org.openhab.binding.mystrom/src/main/resources/OH-INF/update/update.xml
=> [myStrom] Add energy consumption since last API call channel for MyStrom Plug

bundles/org.openhab.binding.allplay/README.md
Users should not be directed to the archived openhab1-addons issue tracker.
=> [allplay] Fix issue tracker link in documentation

bundles/org.openhab.binding.renault/src/main/java/org/openhab/binding/renault/internal/api/Car.java, bundles/org.openhab.binding.renault/src/main/java/org/openhab/binding/renault/internal/api/MyRenaultHttpSession.java
As requested the HTTP != 200 responses are set to debug logging level.  This cleans up the init log of the binding for cars that do not support lock status.
Details of this request are here;
https://community.openhab.org/t/betatest-renault-ze-services-binding/72226/240?u=doug_culnane
=> [renault] Small logging improvements.

bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/GraalJSScriptEngineFactory.java
Fixes casting String to Boolean error when using file base configuration:
In my setup, I'm configuring the jsscripting automation via a file based .cfg file: `OPENHAB_CONF/services/jsscripting.cfg`. This config file is read as String, which leads to the ClassCastException:
```
...
Caused by: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Boolean (java.lang.String and java.lang.Boolean are in module java.base of loader 'bootstrap')
at org.openhab.automation.jsscripting.internal.GraalJSScriptEngineFactory.modified(GraalJSScriptEngineFactory.java:101) ~[?:?]
at org.openhab.automation.jsscripting.internal.GraalJSScriptEngineFactory.<init>(GraalJSScriptEngineFactory.java:71) ~[?:?]
... 103 more
```
I have looked up how …
=> [jsscripting] Fix incorrect cast

bundles/org.openhab.binding.mikrotik/src/main/java/org/openhab/binding/mikrotik/internal/util/Converter.java, bundles/org.openhab.binding.mikrotik/src/test/java/org/openhab/binding/mikrotik/internal/util/ConverterTest.java
Fixes https://github.com/openhab/openhab-addons/issues/15100
Since routerOs 7.10 the returned dateformat has changed. This PR ads old/new format detection and parsing. 
Test jar 4.x here : https://1drv.ms/u/s!AnMcxmvEeupwjq5eM322cplpF5bAaQ?e=0UZZ4e
Tests confirmed the fix
=> [microtik] Fix changed date format in firmware v7.10

itests/itest-common.bndrun
This prevents ZipException stacktraces when running the itests on JDK 17.0.8 or newer.
Related to:
* openhab/openhab-core#3718
* openhab/openhab-core#3747
=> Disable "Improved ZIP64 Extra Field Validation" in itests

bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/Tr064RootHandler.java, bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/soap/SOAPConnector.java, bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/soap/SOAPValueConverter.java
In case of multiple root things the auth store (results and digests) was cleared for all clients instead of only removing the failed auth result or old authentication.
Also fixes TAM list request.
=> [tr064] Fix clearing of auth (results)

bundles/org.openhab.persistence.jdbc/README.md, bundles/org.openhab.persistence.jdbc/pom.xml, bundles/org.openhab.persistence.jdbc/src/main/feature/feature.xml, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcConfiguration.java
Replaces #15022
Release notes:
- [3.42.0.0](https://github.com/xerial/sqlite-jdbc/releases/tag/3.42.0.0)
- [3.41.2.2](https://github.com/xerial/sqlite-jdbc/releases/tag/3.41.2.2)
- [3.41.2.1](https://github.com/xerial/sqlite-jdbc/releases/tag/3.41.2.1)
- [3.41.0.1](https://github.com/xerial/sqlite-jdbc/releases/tag/3.41.0.1)
- [3.41.0.0](https://github.com/xerial/sqlite-jdbc/releases/tag/3.41.0.0)
- [3.40.1.0](https://github.com/xerial/sqlite-jdbc/releases/tag/3.40.1.0)
Fixed vulnerabilities:
- [CVE-2023-32697](https://nvd.nist.gov/vuln/detail/CVE-2023-32697)
Artifacts:
- https://mvnrepository.com/artifact/org.xerial/sqlite-jdbc/3.42.0.0
- [org.openhab.persistence.jdbc-4.1.0-SNAPSHOT.jar](https://drive.google.com/file/d/1QzvLhmUC75J8VLn9w3v2wF4KsEmeoYso/view?usp=sharing)
=> [jdbc] Upgrade SQLite JDBC driver to 3.42.0.0

bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcBaseDAO.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcDerbyDAO.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcPostgresqlDAO.java
Fixes:
```
[WARNING] openhab-addons\bundles\org.openhab.persistence.jdbc\src\main\java\org\openhab\persistence\jdbc\internal\db\JdbcDerbyDAO.java:[252,66] Potential null pointer access: The method getEndDate() may return null
[WARNING] openhab-addons\bundles\org.openhab.persistence.jdbc\src\main\java\org\openhab\persistence\jdbc\internal\db\JdbcBaseDAO.java:[547,66] Potential null pointer access: The method getBeginDate() may return null
[WARNING] openhab-addons\bundles\org.openhab.persistence.jdbc\src\main\java\org\openhab\persistence\jdbc\internal\db\JdbcBaseDAO.java:[552,66] Potential null pointer access: The method getEndDate() may return null
[WARNING] openhab-addons\bundles\org.openhab.persistence.jdbc\src\main\java\org\openhab\persistence\jdbc\internal\db\JdbcPostgresqlDAO.java:[265 …
```
=> [jdbc] Fix null annotation warnings

bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaBridgeHandler.java
This PR fixes the issue discussed here https://community.openhab.org/t/nullpointerexception-while-initializing-somfytahoma-bridge/148752
=> [somfytahoma] fix NPE in case that HttpClient fails to start

bundles/org.openhab.binding.feed/pom.xml
This addresses CVE-2021-33813
See: http://www.jdom.org/news/index.html
=> [feed] Upgrade jdom2 to 2.0.6.1

bundles/org.openhab.binding.paradoxalarm/src/main/java/org/openhab/binding/paradoxalarm/internal/communication/EvoCommunicator.java, bundles/org.openhab.binding.paradoxalarm/src/main/java/org/openhab/binding/paradoxalarm/internal/model/PanelType.java
Root cause is that EVOHD and EVO192 have much more zones which are stored in a different memory map model. They should be treated the same way. The root cause was a wrong if that treats EVOHD as EVO48/96.
Fix is simple and can be downported to 3.x if decided by the maintainers.
fixes #10572
=> [paradoxalarm] Fix Paradox EVOHD zone parsing fail #10572

bundles/org.openhab.persistence.dynamodb/src/test/java/org/openhab/persistence/dynamodb/internal/BaseIntegrationTest.java, bundles/org.openhab.persistence.dynamodb/src/test/java/org/openhab/persistence/dynamodb/internal/TestComplexItemsWithDifferentStateTypesTest.java, itests/org.openhab.binding.mqtt.ruuvigateway.tests/src/main/java/org/openhab/binding/mqtt/ruuvigateway/MqttOSGiTest.java, itests/org.openhab.binding.mqtt.ruuvigateway.tests/src/main/java/org/openhab/binding/mqtt/ruuvigateway/RuuviGatewayTest.java
There should be no difference between running tests on your own PC or on a build server. The ruuvigateway tests always fail for me during parallel builds due to its unrealistic timing.
=> Remove build server specific timing from dynamodb and ruuvigateway

bundles/org.openhab.binding.hue/src/main/resources/OH-INF/i18n/hue.properties
Related to #15460
Usages:
https://github.com/openhab/openhab-addons/blob/fef05c33220bc368fd9d0166dc403410f21aa880/bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/Clip2BridgeHandler.java#L470-L471
https://github.com/openhab/openhab-addons/blob/fef05c33220bc368fd9d0166dc403410f21aa880/bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/Clip2BridgeHandler.java#L494-L495
https://github.com/openhab/openhab-addons/blob/fef05c33220bc368fd9d0166dc403410f21aa880/bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/Clip2BridgeHandler.java#L687-L688
Documentation: https://www.openhab.org/javadoc/latest/org/openhab/core/thing/i18n/thingstatusinfoi18nlocalizationservice
=> [hue] Fix exception text in bridge status description

bundles/org.openhab.transform.bin2json/src/main/java/org/openhab/transform/bin2json/internal/Bin2Json.java, bundles/org.openhab.transform.exec/src/main/java/org/openhab/transform/exec/internal/profiles/ExecTransformationProfile.java, bundles/org.openhab.transform.jinja/src/main/java/org/openhab/transform/jinja/internal/profiles/JinjaTransformationProfile.java, bundles/org.openhab.transform.jsonpath/src/main/java/org/openhab/transform/jsonpath/internal/JSonPathTransformationService.java, bundles/org.openhab.transform.jsonpath/src/main/java/org/openhab/transform/jsonpath/internal/profiles/JSonPathTransformationProfile.java, bundles/org.openhab.transform.map/src/main/java/org/openhab/transform/map/internal/profiles/MapTransformationProfile.java, bundles/org.openhab.transform.regex/src/main/java/org/openhab/transform/regex/internal/profiles/RegexTransformationProfile.java, bundles/org.openhab.transform.regex/src/test/java/org/openhab/transform/regex/internal/AbstractTransformationServiceTest.java, bundles/org.openhab.transform.scale/src/main/java/org/openhab/transform/scale/internal/profiles/ScaleTransformationProfile.java, bundles/org.openhab.transform.xpath/src/main/java/org/openhab/transform/xpath/internal/profiles/XPathTransformationProfile.java, bundles/org.openhab.transform.xpath/src/test/java/org/openhab/transform/xpath/internal/AbstractTransformationServiceTest.java, bundles/org.openhab.transform.xslt/src/main/java/org/openhab/transform/xslt/internal/profiles/XSLTTransformationProfile.java, bundles/org.openhab.transform.xslt/src/test/java/org/openhab/transform/xslt/internal/AbstractTransformationServiceTest.java
instanceof matching and multiline strings
Similar to what we did in core a few month ago. Note that this breaks compatibilty to Java 11.
=> [transform] Use Java 17 features

bundles/org.openhab.binding.daikin/README.md, bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/DaikinWebTargets.java, bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/ControlInfo.java, bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/Enums.java, bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/handler/DaikinAcUnitHandler.java
Daikin BRP069A81 adapter uses mode=1 for its AUTO mode. This PR makes the binding adaptively uses the correct mode=0 or mode=1 depending on what the adapter reports back.
Resolve #15375
=> [daikin] Support BRP069A81 adapter

bundles/org.openhab.binding.dwdunwetter/src/main/java/org/openhab/binding/dwdunwetter/internal/dto/DwdWarningsData.java
XMLInputFactory: Disable properties IS_SUPPORTING_EXTERNAL_ENTITIES and SUPPORT_DTD which allow injecting external entities.
I quickly tested the addon with this change, still got the current warning and did not see any warning/info log messages.
=> [dwdunwetter] Handle possible XXE injection

bundles/org.openhab.binding.radiothermostat/README.md, bundles/org.openhab.binding.radiothermostat/src/main/java/org/openhab/binding/radiothermostat/internal/RadioThermostatBindingConstants.java, bundles/org.openhab.binding.radiothermostat/src/main/java/org/openhab/binding/radiothermostat/internal/RadioThermostatHandlerFactory.java, bundles/org.openhab.binding.radiothermostat/src/main/java/org/openhab/binding/radiothermostat/internal/handler/RadioThermostatHandler.java
Clear the remote temp and message area values in the thermostat when dispose() is called. Also minor refactoring to use immutable list/set convenience methods.
=> [radiothermostat] Disable Remote Temp and Message Area on shutdown

bundles/org.openhab.binding.monopriceaudio/src/main/java/org/openhab/binding/monopriceaudio/internal/handler/MonopriceAudioHandler.java
Fix race condition that occurs during reconnect when the binding disconnects before the initial status query responses are received. The polling job will still determine when the amplifier is no longer responding and set the thing status appropriately.
=> [monopriceaudio] Fix reconnect error race condition

bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/dto/AlertModel.java
Lately my Fritz!Box with Fritz!OS 7.56 sends empty alert state tags (`<state/>`) instead of a zero value (`<state>0</state>`) for **some** blinds, resulting in a NullPointerException when the binding tries to interpret the value. I fixed this by performing null checks before numerical operations take place.
=> [avmfritz] Fix NPE when Fritz!Box sends empty alert state element

bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/connection/Clip2Bridge.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/dto/clip2/Resources.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/Clip2BridgeHandler.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/Clip2ThingHandler.java, bundles/org.openhab.binding.hue/src/main/resources/OH-INF/i18n/hue.properties
When sending a command to an unreachable bulb this **warning** was logged:
```
[WARN] Command 'OFF' for thing 'hue:device:home:innr3', channel 'hue:device:home:innr3:switch' failed with error 'Unexpected HTTP status '207''.
```
This has been changed to log level **information** with the errors provided in the response:
```
[INFO] Command 'OFF' for thing 'hue:device:home:innr3', channel 'hue:device:home:innr3:switch' succeeded with errors: device (light) has communication issues, command (.on.on) may not have effect
```
Or this, in case of multiple errors:
```
[INFO] Command 'ON' for thing 'hue:device:home:traadfri_color_bulb2', channel 'hue:device:home:traadfri_color_bulb2:color' succeeded with errors: device (light) has communication issues, command (.on.on) may not have effect; device …
```
=> [hue] Fix and improve error logging and status descriptions for API v2

bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/EaseeBindingConstants.java, bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/model/ChargerOpState.java, bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/model/CustomResponseTransformer.java
Since Easse has introduced new status values (7+8) to map different states related to authentication it is now much easier to determine start/stop status.
=> [easee] simplified determination of start/stop status due to recent API changes

bundles/org.openhab.binding.fronius/README.md
=> [fronius] fix powerflowchannelpakku documentation

bundles/create_openhab_binding_skeleton.cmd, bundles/create_openhab_binding_skeleton.sh
Fixed the bug where you could not compile since the parrent OpenHAB version was wrong in the build conf. The issue was caused by a wrong version in the template.
Would fix #15588
=> 15588-build_fix_for_new_binding

bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/common/HomematicConfig.java, bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/message/XmlRpcRequest.java, bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/message/XmlRpcResponse.java, bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/parser/DisplayOptionsParser.java, bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/virtual/BatteryTypeVirtualDatapointHandler.java, bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/virtual/ButtonVirtualDatapointHandler.java, bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/converter/type/AbstractTypeConverter.java, bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/converter/type/QuantityTypeConverter.java, bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/discovery/eq3udp/Eq3UdpRequest.java, bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/handler/HomematicThingHandler.java, bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/handler/SimplePortPool.java, bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/misc/MiscUtils.java, bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/type/MetadataUtils.java, bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/type/HomematicThingTypeExcluder.java, bundles/org.openhab.binding.homematic/src/test/java/org/openhab/binding/homematic/internal/converter/ConvertFromBindingTest.java, bundles/org.openhab.binding.homematic/src/test/java/org/openhab/binding/homematic/internal/converter/ConvertToBindingTest.java
- Fixes some build warnings
- Fixes some checkstyle
- Removes forbidden package
Test jar 4.x: https://1drv.ms/u/s!AnMcxmvEeupwjqVmDjS6MTGKtfRFQQ?e=K9vt0o
=> [homematic] checkstyle fixes

bundles/org.openhab.binding.chatgpt/src/main/java/org/openhab/binding/chatgpt/internal/ChatGPTModelOptionProvider.java
Fixes https://github.com/openhab/openhab-addons/issues/15575
=> [chatgpt] Fix config option provider to only become active for chatgpt things

bundles/org.openhab.binding.lghombot/src/main/java/org/openhab/binding/lghombot/internal/CameraUtil.java, bundles/org.openhab.binding.lghombot/src/main/java/org/openhab/binding/lghombot/internal/LGHomBotConfiguration.java
=> [lghombot] Fix checkstyle

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/Conversions.java, bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.light.color1.json
Fix reported brightness for yeelight when powered off. This will fix wrong power switch visualization in the OH UI.
related to issue:
https://community.openhab.org/t/miio-and-yeelight-rgb-bulbs-behavior/135788/9
=> [miio] fix reported brightness for yeelight

bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/MieleApplianceHandler.java
This allows for example to automate turning off a washing machine when entering the laundry room. This will unlock it, so that the door can be opened without stopping the appliance manually first.
This change applies to dishwashers, tumble dryers and washing machines.
Resolves #15619
=> [miele] Interpret more states as appliance being switched on

bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/api/DatahubTariffFilterFactory.java, bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/config/config.xml, bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/i18n/energidataservice.properties
Add filter for the grid company [Aal Elnet](https://www.aal-elnet.dk/).
=> [energidataservice] Add filter for Aal Elnet

bundles/org.openhab.binding.dwdunwetter/src/main/java/org/openhab/binding/dwdunwetter/internal/dto/DwdWarningDataAccess.java, bundles/org.openhab.binding.dwdunwetter/src/main/java/org/openhab/binding/dwdunwetter/internal/dto/DwdWarningsData.java, bundles/org.openhab.binding.dwdunwetter/src/main/resources/OH-INF/addon/addon.xml, bundles/org.openhab.binding.dwdunwetter/src/test/java/org/openhab/binding/dwdunwetter/internal/dto/DwdWarningsDataAccessTest.java, bundles/org.openhab.binding.dwdunwetter/src/test/java/org/openhab/binding/dwdunwetter/internal/dto/DwdWarningsDataTest.java
- Fixed https://github.com/openhab/openhab-addons/issues/14691
- Add some unit tests
- Add country tag to addons.xml
Used it for a couple of days and had no problem.
Test jar 4.1.0 here: https://1drv.ms/u/s!AnMcxmvEeupwjrMmX76PHq61-JUHFQ?e=K0E0TR
=> [dwdunwetter] Improve server problem handling 

bundles/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/internal/local/dto/TellstickLocalDeviceDTO.java, bundles/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/internal/local/dto/TellstickLocalSensorDTO.java
=> [tellstick] Fix local bridge handler update

bundles/org.openhab.binding.oppo/README.md, bundles/org.openhab.binding.oppo/src/main/java/org/openhab/binding/oppo/internal/handler/OppoHandler.java
Update the state of the 'Player' channel so that the button status and its corresponding action in the UI widget will correctly reflect whether the device is in a playing or paused state.
Also some logger updates that haven been pending for a while now.
=> [oppo] Update Play/Pause status to Player channel widget

bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/handler/KaleidescapeMessageHandler.java
Update the state of the 'Player' channels so that the button status and its corresponding action in the UI widget will correctly reflect whether the device is in a playing or paused state.
=> [kaleidescape] Update Play/Pause status to Player channel widget

bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/data/NetatmoConstants.java, bundles/org.openhab.binding.netatmo/src/main/resources/OH-INF/i18n/netatmo.properties
Manually picked from e252e993048247106046695a4819f319ce5baf99 in #15590 in order to fix this key in Crowdin faster and cause less translation regressions (see for example #15653)
See https://github.com/openhab/openhab-addons/pull/15587#discussion_r1337245481.
=> [netatmo] Fix typo in I18N key

bundles/org.openhab.binding.energidataservice/pom.xml
Dependency to Gson 2.10 is no longer needed after Gson has been upgraded from 2.9 to 2.10 in openhab/openhab-core#3817.
This reduces the resulting JAR by almost 300 kB.
=> [energidataservice] Remove Gson 2.10 dependency

bundles/org.openhab.binding.freeboxos/pom.xml
Dependency to Gson 2.10 is no longer needed after Gson has been upgraded from 2.9 to 2.10 in openhab/openhab-core#3817.
=> [freeboxos] Remove Gson 2.10 dependency

bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/CacheManager.java, bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/DatahubTariff.java, bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/action/EnergiDataServiceActions.java, bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/api/DatahubTariffFilter.java, bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/handler/EnergiDataServiceHandler.java, bundles/org.openhab.binding.energidataservice/src/test/java/org/openhab/binding/energidataservice/internal/action/EnergiDataServiceActionsTest.java
While working on #15636, I was reminded about code duplication that increased the risk of bugs due to the potential mixing of variables, such as through copy-and-paste errors.
=> [energidataservice] Refactor to eliminate code duplication

bundles/org.openhab.binding.enphase/NOTICE, bundles/org.openhab.binding.enphase/README.md, bundles/org.openhab.binding.enphase/pom.xml, bundles/org.openhab.binding.enphase/src/main/feature/feature.xml, bundles/org.openhab.binding.enphase/src/main/java/org/openhab/binding/enphase/internal/EnphaseHandlerFactory.java, bundles/org.openhab.binding.enphase/src/main/java/org/openhab/binding/enphase/internal/EnvoyConfiguration.java, bundles/org.openhab.binding.enphase/src/main/java/org/openhab/binding/enphase/internal/discovery/EnphaseDevicesDiscoveryService.java, bundles/org.openhab.binding.enphase/src/main/java/org/openhab/binding/enphase/internal/discovery/EnvoyDiscoveryParticipant.java, bundles/org.openhab.binding.enphase/src/main/java/org/openhab/binding/enphase/internal/dto/EntrezJwtDTO.java, bundles/org.openhab.binding.enphase/src/main/java/org/openhab/binding/enphase/internal/exception/EnphaseException.java, bundles/org.openhab.binding.enphase/src/main/java/org/openhab/binding/enphase/internal/exception/EntrezConnectionException.java, bundles/org.openhab.binding.enphase/src/main/java/org/openhab/binding/enphase/internal/exception/EntrezJwtInvalidException.java, bundles/org.openhab.binding.enphase/src/main/java/org/openhab/binding/enphase/internal/exception/EnvoyConnectionException.java, bundles/org.openhab.binding.enphase/src/main/java/org/openhab/binding/enphase/internal/exception/EnvoyNoHostnameException.java, bundles/org.openhab.binding.enphase/src/main/java/org/openhab/binding/enphase/internal/handler/EntrezConnector.java, bundles/org.openhab.binding.enphase/src/main/java/org/openhab/binding/enphase/internal/handler/EnvoyBridgeHandler.java, bundles/org.openhab.binding.enphase/src/main/java/org/openhab/binding/enphase/internal/handler/EnvoyConnector.java, bundles/org.openhab.binding.enphase/src/main/java/org/openhab/binding/enphase/internal/handler/EnvoyConnectorWrapper.java, bundles/org.openhab.binding.enphase/src/main/java/org/openhab/binding/enphase/internal/handler/EnvoyEntrezConnector.java, bundles/org.openhab.binding.enphase/src/main/resources/OH-INF/addon/addon.xml, bundles/org.openhab.binding.enphase/src/main/resources/OH-INF/i18n/enphase.properties, bundles/org.openhab.binding.enphase/src/main/resources/OH-INF/thing/thing-types.xml
Adds support for newer Envoy software version that currently is not supported by the binding.
See also https://community.openhab.org/t/new-binding-enphase-envoy-solar-system-gateway/44449/113
=> [enphase] Add Entrez/JWT support for newer software versions of Envoy

bundles/org.openhab.voice.googletts/README.md
I had some struggles with setting up google TTS, got it to work eventually and now update the README to help users in the future.
This commit includes updating the information, including necessary tips, formatting und some minor details
=> [Google TTS] Update README.md

bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/handler/ZonePlayerHandler.java, bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/channels.xml
Adds Dolby Digital Plus 2.0 and a second codec ID for Dolby Digital 2.0.
Resolves #15643
=> [sonos] Add Dolby Digital Plus 2.0 and fix Dolby Digital 2.0

bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiRpc.java, bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2RpcSocket.java
If the client is not stopped it will not be garbage collected because the ShutdownThread keeps a reference to the client so it can be stopped on shutdowns.
See: https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-websocket/websocket-client/src/main/java/org/eclipse/jetty/websocket/client/WebSocketClient.java#L420-L433
=> [shelly] Always try to stop WebSocketClient

bundles/org.openhab.automation.jythonscripting/README.md, bundles/org.openhab.automation.jythonscripting/src/main/resources/OH-INF/addon/addon.xml
=> [jythonscripting] Add a note not to use jython

bundles/org.openhab.persistence.jdbc/pom.xml
The dependency change in #15659 caused slf4j to be embedded into the bundle.
As a result the bundle no longer uses Pax Logging so it cannot find an SLF4J provider and logs the following when it is installed:
```
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
```
=> [jdbc] Fix logging not working

bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyDeviceProfile.java
For the Shelly UNI a small fix needs to be applied to the JSON that is received form the device. When two or more temperature sensors are attached, the array is not sorted and the sensor "1" is first, causes the string replacement to fail.
With this patch all tree possible variants are checked, so that the JSON fix is applied for all possible sortings.
Note: The Shelly UNI supports only up to three DS18B20.
Here is the build artifact:
https://openhab.jfrog.io/artifactory/libs-pullrequest-local/org/openhab/addons/bundles/org.openhab.binding.shelly/4.1.0-SNAPSHOT/org.openhab.binding.shelly-4.1.0-SNAPSHOT.jar
Installed and tested on my local system - Shelly gets `ONLINE` and all three DS18B20 are detected and working.
Note: This is my first pull request, I hope I'll got everything correct.
=> [shelly] Fix UNI support up to three DS18B20 sensors

bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/ValueEncoder.java
In the old implementation the datatype was implemented with byte 0-255. 
The DPT 251.600 is defined with 0-100%, change this from byte to PercentType.
Signed-off-by: Marco Müller <marco@ms-mueller.ch>
=> [knx] Bugfix problem with DPT 251.600

bundles/org.openhab.persistence.jdbc/README.md, bundles/org.openhab.persistence.jdbc/pom.xml, bundles/org.openhab.persistence.jdbc/src/main/feature/feature.xml, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcConfiguration.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcH2DAO.java, bundles/org.openhab.persistence.jdbc/src/main/resources/OH-INF/config/config.xml, bundles/org.openhab.persistence.jdbc/src/main/resources/OH-INF/i18n/jdbc.properties, features/openhab-addons-external/src/main/resources/conf/jdbc.cfg
Upgrades H2 database from 1.4.191 to 2.2.224.
Add the `;NON_KEYWORDS=VALUE` configuration option at the end of your H2 JDBC URL because the add-on uses 'value' (which is also a keyword) as column name, e.g.: `jdbc:h2:./testH2;NON_KEYWORDS=VALUE`
Also fixes some queries used by the command extension because H2 always uses upper case table names.
For the change log, see:
https://h2database.com/html/changelog.html
For migration notes, see:
https://h2database.com/html/migration-to-v2.html
Fixes #13115
---
I also wrote a small migration script using Bash to migrate databases from H2 1.4  to H2 2.2:
```bash
#!/usr/bin/env bash
set -eo pipefail
if [ $# -eq 0 ]; then
echo "This script migrates an H2 1.4 database to H2 2.2"
echo
echo "Usage: ./$(basename "$0") <h2-1.4-database.mv.db>"
echo …
```
=> [jdbc] Upgrade H2 to 2.2.224

bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaVehicleHandler.java
While the app can't go lower than 5A, the API allows setting values down to 0A, and at least going to 2-3A can make sense if you want to put excess solar power into the car without also drawing some from the grid.
Due to the overhead this causes it can be wasteful, so keep logging the warning about going below 5A. Leave the limiting/validation of values >32A up to the API, not this addon.
=> [tesla] Remove the minimum 5A charge current limit

bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/api/DatahubTariffFilterFactory.java
Update filters with discount tariffs for these grid companies:
- Aal Elnet
- Dinel
- Sunds Net
- Tarm Elværk Net
Additionally fix filter for Ikast El Net.
=> [energidataservice] Add discount tariffs for Aal Elnet, Dinel, Sunds Net and Tarm Elværk Net

bundles/org.openhab.binding.tesla/README.md, bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/TeslaChannelSelectorProxy.java, bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/protocol/DriveState.java, bundles/org.openhab.binding.tesla/src/main/resources/OH-INF/i18n/tesla.properties, bundles/org.openhab.binding.tesla/src/main/resources/OH-INF/thing/channels.xml, bundles/org.openhab.binding.tesla/src/main/resources/OH-INF/thing/model3.xml, bundles/org.openhab.binding.tesla/src/main/resources/OH-INF/thing/models.xml, bundles/org.openhab.binding.tesla/src/main/resources/OH-INF/thing/modelx.xml, bundles/org.openhab.binding.tesla/src/main/resources/OH-INF/thing/modely.xml, bundles/org.openhab.binding.tesla/src/main/resources/OH-INF/update/instructions.xml
With this enhancement, the routing targets of the cars can be injected into OH.
Main idea is that the car itself knows best when it will arrive at a given destination, e.g. at home, which information can then be used to determine when best to start the tea kettle or the garage doors.
The idea was shamelessly stolen from a YouTube video by Reed ( https://youtu.be/1BfPoeJru_c?si=Q7WAvHo25-16y7jA&t=170 ), whereupon I discovered that Home Assistant supports said routing targets, but the OpenHAB binding does not (yet).
=> [tesla] Add channels for active routing

bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/Clip2ThingHandler.java
This fixes two issues:
- `REFRESH` command not working. This means, for example, that state will be missing after linking first item to a channel.
- Under specific circumstances (such as a thing migrated from API v1), refresh would be skipped when a device comes online, for example after being unreachable.
Fixes #15735
Fixes #15669
=> [hue] Fix channel refresh (API v2)

bundles/org.openhab.binding.hue/doc/readme_v2.md
Under demo.items the button-last-event channel was of the Number type. I have changed this to String. In the channels for devices section this was already corrected but is not 'live' yet?
=> [hue] Update readme_v2.md

bundles/org.openhab.binding.modbus.e3dc/src/main/resources/OH-INF/thing/power-channel-types.xml
State pattern with Percent as default for QuantityType:Dimensionless.
See https://community.openhab.org/t/e3dc-binding-strange-unit-for-powerplant-battery-soc-thing/149480
=> [e3dc] State pattern with Percent as default for QuantityType:Dimensionless

bundles/org.openhab.voice.googletts/src/main/java/org/openhab/voice/googletts/internal/GoogleCloudAPI.java
Fixes #15746
JARs for testing:
- [org.openhab.voice.googletts-4.0.4-SNAPSHOT.jar](https://drive.google.com/file/d/1s_g1XnpMKN81Fr5CiY4Lkn356RHJmxP6/view?usp=sharing)
- [org.openhab.voice.googletts-4.1.0-SNAPSHOT.jar](https://drive.google.com/file/d/1E-GSiHmtNlV3q_I_YK4wT4nGJ1NPCBCe/view?usp=sharing)
=> [googletts] Fix authentication after communication error

bundles/org.openhab.binding.boschindego/README.md
Update documentation only
none
=> [boschindego] Add note that batteryVoltage is not populated correctly

bundles/org.openhab.binding.miele/README.md, bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/MieleBindingConstants.java, bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/DishwasherChannelSelector.java, bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/DishwasherHandler.java, bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/MieleApplianceHandler.java, bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/MieleBridgeHandler.java, bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/WashingMachineChannelSelector.java, bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/WashingMachineHandler.java, bundles/org.openhab.binding.miele/src/main/resources/OH-INF/i18n/miele.properties, bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/channeltypes.xml, bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/dishwasher.xml, bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/washingmachine.xml, bundles/org.openhab.binding.miele/src/main/resources/OH-INF/update/instructions.xml
This removes channel `powerConsumption` and adds channel `energyConsumption` to rectify an old mistake.
This is a bit overdue and should probably have been done in #13930, in hindsight. This is a breaking change requiring users to relink items to the new channels. I doubt there are many users though. I will create a note for that in openhab-distro.
I tried first to do a backwards compatible deprecation (see first commit), but I think this drags too much technical debt along than can be justified, so would prefer to just take the bull by the horns now.
Additionally sets state description pattern unit to **litre** for water consumption as default unit m³ makes no sense for dishwashers and washing machines.
The upgrade will only happen after two minutes. I'm not sure if this is a known and …
=> [miele] Rename channel `powerConsumption` to `energyConsumption` and set display unit to litres for `waterConsumption`

bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/virtual/StateContactVirtualDatapointHandler.java
The HomeMaticIP series includes, among other things, numerous different window and door contacts. The corresponding binding "homematic" from this repo establishes a connection to the headquarters of this product series (via an API). However, this only provides the current status (open or closed) for these sensors as a string, which is difficult to process. For example, for further integration via Openhab to Amazon Alexa, a special conversion rule is required (necessary for each sensor).
For this reason, a virtual controller was built into the add-on, which converts the strings from the API into a normal data channel (ON or OFF). This currently checks whether it is the `HMIP-SWDO` model and then adds the corresponding data channel. However, in recent years there have been significantly …
=> [homematic] Expansion of virtual data channel for all window/door contacts

bundles/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/internal/NeeoApi.java
Removes double NEEO in thread name.
Before:
```
"OH-httpClient-neeo-NEEO-713af1e8-1-2054" Id=2054 in TIMED_WAITING on lock=java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@31527da5
"OH-httpClient-neeo-NEEO-713af1e8-1-2060" Id=2060 in TIMED_WAITING on lock=java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@31527da5
"OH-httpClient-neeo-NEEO-713af1e8-1-2061" Id=2061 in RUNNABLE (running in native)
```
After:
```
"OH-httpClient-neeo-713af1e8-1-2250" Id=2250 in RUNNABLE (running in native)
"OH-httpClient-neeo-713af1e8-1-2252" Id=2252 in TIMED_WAITING on lock=java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@669e2414
"OH-httpClient-neeo-713af1e8-1-2256" Id=2256 in RUNNABLE (running in native)
```
Resolves #15777
=> [neeo] Removes extra NEEO from thread name

bundles/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/handler/MyQAccountHandler.java
While looking for code deduplication i found this not used method. Removed it, so it is not going to be used in the future, instead core.StringUtils can be used.
=> [myq] cleanup regarding to core StringUtils

bundles/org.openhab.persistence.jdbc/README.md, bundles/org.openhab.persistence.jdbc/pom.xml, bundles/org.openhab.persistence.jdbc/src/main/feature/feature.xml, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcConfiguration.java
Release notes:
- https://dev.mysql.com/doc/relnotes/connector-j/8.1/en/news-8-1-0.html
Library:
- https://mvnrepository.com/artifact/com.mysql/mysql-connector-j/8.1.0
Tested by installing compiled bundle as well as `mysql-connector-j-8.1.0` into addons directory as `mysql-connector.jar`.
Previous upgrade: #14874
=> [jdbc] Upgrade MySQL Connector/J to 8.1.0

bundles/org.openhab.binding.ambientweather/pom.xml, bundles/org.openhab.binding.ambientweather/src/main/feature/feature.xml, bundles/org.openhab.binding.dbquery/pom.xml, bundles/org.openhab.binding.mercedesme/pom.xml, bundles/org.openhab.binding.volumio/pom.xml, bundles/org.openhab.io.openhabcloud/pom.xml, bundles/org.openhab.io.openhabcloud/src/main/feature/feature.xml, bundles/org.openhab.persistence.influxdb/pom.xml
Release notes:
- https://github.com/stleary/JSON-java/releases/tag/20230618
- https://github.com/stleary/JSON-java/releases/tag/20231013
Fixed vulnerabilities:
- [CVE-2023-5072](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-5072)
Library:
- https://mvnrepository.com/artifact/org.json/json/20231013
See also [dependabot alerts](https://github.com/advisories/GHSA-rm7j-f5g5-27vv/dependabot).
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/douglascrockford/JSON-java/releases">org.json:json's releases</a>.</em></p>
<blockquote>
<h2>20231013</h2>
<table>
<thead>
<tr>
<th>Pull Request</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr>
<td><a href="https://redirect.github.com/douglascrockford/JSON-java/issues/793">#793</a></td>
<td>Reverted …
=> Upgrade json to 20231013

bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/KaleidescapeBindingConstants.java, bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/handler/KaleidescapeHandler.java
Upon binding connection, register a message in the Kaleidescape server's syslog per page 61 in the control protocol manual.
https://www.kaleidescape.com/wp-content/uploads/kaleidescape-system-control-protocol-reference-manual.pdf
=> [kaleidescape] Register connection in Kaleidescape System log

bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/handler/ZonePlayerHandler.java, bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/i18n/sonos.properties, bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/channels.xml
Adds Dolby TrueHD 5.1 for non-Atmos streams
Normalizes dolbyAtmos to Atmos to align with the rest of the codecs (which don't have a dolby marker).
Resolves #15830
=> [sonos] Add TrueHD5.1 and normalize Atmos

bundles/org.openhab.binding.vigicrues/src/main/java/org/openhab/binding/vigicrues/internal/handler/VigiCruesHandler.java
```
2023-11-01 18:01:35.424 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.initialize()' on 'org.openhab.binding.vigicrues.internal.handler.VigiCruesHandler@55e3d5fd': Cannot invoke "java.util.List.stream()" because "stationDetails.stations" is null
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "stationDetails.stations" is null
at org.openhab.binding.vigicrues.internal.handler.VigiCruesHandler.discoverAttributes(VigiCruesHandler.java:132) ~[?:?]
at org.openhab.binding.vigicrues.internal.handler.VigiCruesHandler.initialize(VigiCruesHandler.java:99) ~[?:?]
at jdk.internal.reflect.GeneratedMethodAccessor37.invoke(Unknown Source) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Delegating …
```
=> [vigicrues] NPE when API does not provide station details

bundles/org.openhab.binding.pilight/src/main/java/org/openhab/binding/pilight/internal/discovery/PilightBridgeDiscoveryService.java
If there were multiple network interfaces and the DatagramSocket.receive timed out an exception was thrown and the remaining network interfaces were not considered anymore.
=> [pilight] Fix background discovery

bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/converter/type/AbstractTypeConverter.java, bundles/org.openhab.binding.homematic/src/test/java/org/openhab/binding/homematic/internal/converter/BaseConverterTest.java, bundles/org.openhab.binding.homematic/src/test/java/org/openhab/binding/homematic/internal/converter/ConvertFromBindingTest.java
This is a fix for #15597 
Instead of raising an exception if an empty value is received from the binding now a NULL values is return. This is incompatible but i think this is the best solution for the problem.
=> [homematic] Adjust handling empty values in AbstractTypeConverter

bundles/org.openhab.binding.androiddebugbridge/README.md, bundles/org.openhab.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/AndroidDebugBridgeConfiguration.java, bundles/org.openhab.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/AndroidDebugBridgeDevice.java, bundles/org.openhab.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/AndroidDebugBridgeHandler.java, bundles/org.openhab.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/AndroidDebugBridgeHandlerFactory.java, bundles/org.openhab.binding.androiddebugbridge/src/main/resources/OH-INF/i18n/androiddebugbridge.properties, bundles/org.openhab.binding.androiddebugbridge/src/main/resources/OH-INF/thing/thing-types.xml
Hello,
This PR introduces an option to reset the adb connection after a configurable number of consecutive timeouts. It seems to solve an issue I was occasionally having after letting the device (Chomecast with Google TV) sleeping for a while.
Also adds support for the INCREASE and DECREASE command to the volume channel which were incorrectly handled before.
I have also moved the load  of the adb keys from the static context to the activate method of the thing handler.
Hope everything is in place, best regards.
=> [androiddebugbridge] Reconnect on max timeouts and improve volume channel

bundles/org.openhab.binding.sonnen/README.md, bundles/org.openhab.binding.sonnen/src/main/resources/OH-INF/thing/thing-types.xml, bundles/org.openhab.binding.sonnen/src/main/resources/OH-INF/update/instructions.xml
Also adapt the documentation and drop the batteryFeedIn in the documentation, which is not part of the binding.
Fix #15365 / https://github.com/openhab/openhab-addons/issues/15365
The binding define different things/channels in "Number:Energy" but these are regular "W" entries in the binding. So "Number:Power" is the right channel type. This fix should avoid the warnings in the log, that the binding try to put a "W" into the "Number:Energy" item: `Failed to update item 'Sonnen_Battery_Consumption' because '721 W' could not be converted to the item unit 'kWh'`
=> [sonnen] Fix channel types, Energy should be Power

bundles/org.openhab.binding.mycroft/src/main/java/org/openhab/binding/mycroft/internal/api/dto/MessageRecognizerLoopRecordBegin.java, bundles/org.openhab.binding.mycroft/src/main/java/org/openhab/binding/mycroft/internal/api/dto/MessageRecognizerLoopRecordEnd.java, bundles/org.openhab.binding.mycroft/src/main/java/org/openhab/binding/mycroft/internal/api/dto/MessageRecognizerLoopUtterance.java, bundles/org.openhab.binding.mycroft/src/main/java/org/openhab/binding/mycroft/internal/api/dto/MessageSpeak.java, bundles/org.openhab.binding.mycroft/src/main/java/org/openhab/binding/mycroft/internal/api/dto/MessageVolumeDecrease.java, bundles/org.openhab.binding.mycroft/src/main/java/org/openhab/binding/mycroft/internal/api/dto/MessageVolumeIncrease.java, bundles/org.openhab.binding.mycroft/src/main/java/org/openhab/binding/mycroft/internal/api/dto/MessageVolumeMute.java, bundles/org.openhab.binding.mycroft/src/main/java/org/openhab/binding/mycroft/internal/api/dto/MessageVolumeUnmute.java
Some minor checkstyle fixes for gson fields
=> [mycroft] gson checkstyle fixes

bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/BluetoothUtils.java, bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/discovery/internal/BluetoothDeviceSnapshot.java, bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/discovery/internal/BluetoothDiscoveryService.java
Some minor cleanup of warnings, code analysis / performance.
No functional change
=> [bluetooth] Cleanup

bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/api/rest/PlayerManager.java, bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/ActivePlayerHandler.java
It can happen (when using webhooks) that a poll is sent when the player is not reachable.
This leads to an npe : 
```
2023-10-27 08:35:00.680 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.IllegalArgumentException: path is null
at org.apache.cxf.jaxrs.impl.UriBuilderImpl.doPath(UriBuilderImpl.java:549) ~[?:?]
at org.apache.cxf.jaxrs.impl.UriBuilderImpl.path(UriBuilderImpl.java:544) ~[?:?]
at org.openhab.binding.freeboxos.internal.api.rest.RestManager.buildUri(RestManager.java:59) ~[?:?]
at org.openhab.binding.freeboxos.internal.api.rest.RestManager.get(RestManager.java:73) ~[?:?]
at org.openhab.binding.freeboxos.internal.api.rest.RestManager.getSingle(RestManager.java:77) ~[?:?]
at …
```
=> [Freeboxos] npe when updating inactive Player

bundles/org.openhab.binding.doorbird/src/main/java/org/openhab/binding/doorbird/internal/action/DoorbirdActions.java, bundles/org.openhab.binding.doorbird/src/main/java/org/openhab/binding/doorbird/internal/api/DoorbirdAPI.java, bundles/org.openhab.binding.doorbird/src/main/java/org/openhab/binding/doorbird/internal/handler/DoorbellHandler.java, bundles/org.openhab.binding.doorbird/src/main/java/org/openhab/binding/doorbird/internal/listener/DoorbirdUdpListener.java
Added some local null checks to prevent warnings and a static var name fix.
=> [doorbird] Warning and SAT cleanup

bundles/org.openhab.binding.folderwatcher/README.md
myFTPFolder and localFolder have  been mixed up in the description.
=> [folderwatcher] Fix mistake in README.md

bundles/org.openhab.binding.sensorcommunity/src/main/resources/OH-INF/thing/thing-types.xml, bundles/org.openhab.binding.sensorcommunity/src/test/java/org/openhab/binding/sensorcommunity/internal/NumberTest.java
State pattern for dB, Percent and Microgram/m3 added 
- to avoid "one" unit for Dimensionless units Percent and dB
- set Microgram / m3 as default particulate measure display
=> [sensorcommunity] State pattern for dB, Percent and Microgram/m3 added

bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/discovery/ThingDiscoveryService.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/types/LightType.java
Some devices report "Window covering controller" instead of "Window covering device". They are controlled in the same way.
=> [deconz] Support window covering controller

bundles/org.openhab.binding.luxtronikheatpump/README.md, bundles/org.openhab.binding.luxtronikheatpump/src/main/resources/OH-INF/thing/channels.xml
=> [luxtronikheatpump] Fix control signal circulating pump

bundles/org.openhab.binding.mqtt.espmilighthub/README.md
Add "MQTT Client Status Messages Mode setting" to ESP Config..
=> [mqtt.espmilighthub] Update README.md

bundles/org.openhab.transform.vat/src/main/java/org/openhab/transform/vat/internal/profile/VATTransformationProfile.java
Implement `TimeSeriesProfile` introduced by openhab/openhab-core#3597.
Tested with #15864
=> [transform.vat] Add support for time series

bundles/org.openhab.binding.energidataservice/README.md, bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/handler/EnergiDataServiceHandler.java
Implement time series support introduced by openhab/openhab-core#3597.
This is transparent to users, no matter if persistence is configured or not. If persistence is configured, future prices will now also be persisted when they become available. It is recommended to configure persistence strategy `forecast` to avoid redundant updates. This has been added to the documentation. One noticeable change when looking at persisted timestamps:
Previously - last three persisted spot prices:
```csv
2023-11-09 19:00:00.005, 0.9290125275
2023-11-09 20:00:00.010, 0.77621246375
2023-11-09 21:00:00.028, 0.74480003375
```
Now:
```csv
2023-11-09 21:00:00.000, 0.74480003375
2023-11-09 22:00:00.000, 0.73518753
2023-11-09 23:00:00.000, 0.69323753375
```
As seen in the UI per 2023-11-09 with the VAT Profile …
=> [energidataservice] Add support for persisting historical and upcoming prices

bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/ChannelState.java
Added the topic name in order to make it easier to debug messages like:
`2023-11-08 17:20:02.313 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Incoming payload 'null' not supported by type 'NumberValue'`
I can't test this properly since I'm on 4.0.3 and I'm not sure how to compile this because it has other dependencies....
=> [mqtt] Add Topic Name for Incoming Payload Not Supported

bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/InfluxDBPersistenceService.java, bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/influx2/InfluxDB2RepositoryImpl.java
Fixes #15614 
Especially for InfluxDB2 the connection check was not properly implemented. It only checked if a connections was ever successfully established. Since we removed the full crash when a write error occured, this lead to a situation where a broken connection was not detected. A ping is now implemented and also a failed write results in a disconnect.
=> [influxdb] Improve connection handling

bundles/org.openhab.binding.bondhome/src/main/java/org/openhab/binding/bondhome/internal/api/BPUPListener.java, bundles/org.openhab.binding.bondhome/src/main/java/org/openhab/binding/bondhome/internal/api/BondHttpApi.java, bundles/org.openhab.binding.bondhome/src/main/java/org/openhab/binding/bondhome/internal/discovery/BondDiscoveryService.java, bundles/org.openhab.binding.bondhome/src/main/java/org/openhab/binding/bondhome/internal/handler/BondBridgeHandler.java
I am seeing occasional spurious warning messages from bondhome in my openhab.log like this:
This PR changes almost all warn() logging calls to trace() or debug() to prevent these messages from being logged.
=> [bondhome] Suppress warning messages

bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/NAHomeStatus.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/deserialization/NAObjectMap.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/CommonInterface.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/EnergyCapability.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/HomeCapability.java
Resolves #15858
While analyzing this issue, I identified that errored module handled at home level was partial. Fixed.
Strengthened getOpt
=> [netatmo] Enhance errored modules handling

bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewRepeaterHandler.java
Now, this is awkward.
I did some additional tests in context of #15880, and didn't seem to receive the correct color state. For some reason I never discovered this problem before, probably because I mostly used the same color for my tests which was not affected that much.
Technically this is not a regression of #15880. This bug was introduced with the initial contribution of repeater support in #12308. Nevertheless, I have set the label to keep only #15880 in the release notes.
=> [hdpowerview] Fix color state update

bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/virtual/ButtonVirtualDatapointHandler.java, bundles/org.openhab.binding.homematic/src/test/java/org/openhab/binding/homematic/internal/communicator/virtual/ButtonDatapointTest.java
Depending on device configuration and used central [1], HM devices may indicate long press repetition either by a single PRESS_CONT event or by a PRESS_CONT + PRESS_LONG combination. In the latter case, make sure to not generate a LONG_REPEATED trigger channel event for both PRESS_CONT and PRESS_LONG, but instead keep LONG_REPEATED generation to the PRESS_CONT handling.
[1] I'm not sure what a real CCU is doing, but for Homegear, a configured long press timeout of less than 1s generates only PRESS_CONT, while a timeout of more than 1s generates PRESS_CONT + PRESS_LONG ... see [2].
[2] https://github.com/Homegear/Homegear-HomeMaticBidCoS/blob/master/src/BidCoSPeer.cpp#L1711-L1716
=> [homematic] Fix duplication of LONG_REPEATED events for HM devices

bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/JSONSchemaLight.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/LightColorMode.java
also adds a color_mode channel if color temp is possible, so you can know how the bulb is behaving
=> [mqtt.homeassistant] Support color temp on JSON schema lights

bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/ComponentChannel.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/AbstractComponent.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/AlarmControlPanel.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Camera.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Climate.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Cover.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/DefaultSchemaLight.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/DeviceTrigger.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Fan.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/JSONSchemaLight.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Lock.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Number.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Select.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Sensor.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Vacuum.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/config/dto/AbstractChannelConfiguration.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/handler/HomeAssistantThingHandler.java, itests/org.openhab.binding.mqtt.homeassistant.tests/src/main/java/org/openhab/binding/mqtt/homeassistant/HomeAssistantMQTTImplementationTest.java
Channels from such components will not have a group. this is now done by zigbee2mqtt for the "default" component of a device, such as the light. HASS encourages this as of release 2023.8
Fixes #15634
=> [mqtt.homeassistant] handle null component name

bundles/org.openhab.binding.bluetooth.bluez/README.md
Unit was renamed from **openhab2** to **openhab** in openHAB 3.
=> [bluetooth.bluez] Fix openhab unit name

bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/i18n/openwebnet.properties, bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusCENPlusScenarioControl.xml, bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusCENScenarioControl.xml
Very small PR to fix description for the buttons param for bus_cen_scenario_control and bus_cenplus_scenario_control thing types.
=> [openwebnet] fix CEN/CEN+ scenario control buttons param descriptions

bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/ComponentFactory.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Scene.java
=> [mqtt.homeassistant] Add support for Scene component

bundles/org.openhab.binding.energidataservice/README.md, bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/action/EnergiDataServiceActions.java, bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/i18n/energidataservice.properties, bundles/org.openhab.binding.energidataservice/src/test/java/org/openhab/binding/energidataservice/internal/action/EnergiDataServiceActionsTest.java
Renamed the concept of price **element** to price **component**.
The total electricity price consists of the following components:
- Spot price
- Grid tariff
- System tariff
- Electricity tax
- Grid transmission tariff
I think price components sounds more fitting in this context to refer to the individual parts that make up the total price.
=> [energidataservice] Rename price element to price component

bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/handler/IpCameraHandler.java
Fixes an issue where when a Reolink camera does a reboot, or re-connects perhaps due to a wi-fi reconnection, the alarms do not work.
=> [ipcamera]Fix Reolink alarms not working after a reconnect.

bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/ComponentChannel.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/BinarySensor.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Button.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Scene.java, bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/ButtonTests.java
I.e. Button, Scene, and Binary Sensors.
Also ensure we set up the CommandDescription, since some value types mights use it.
=> [mqtt.homeassistant] VETO updates to read only channels

bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/JSONSchemaLight.java, bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/JSONSchemaLightTests.java
zigbee2mqtt can send a brightness of say 99, with a state of OFF, when a bulb is off. make sure if state is sent, it overrides all other inferences
=> [mqtt.homeassistant] interpret a dimmable light as OFF properly from zigbee2mqtt

tools/static-code-analysis/checkstyle/ruleset.properties
Add-ons should use the OH serial transport and not their own serial communication libraries.
Related to #7573
=> Add SAT warning when jSerialComm, PureJavaComm imports are used

bundles/org.openhab.voice.rustpotterks/src/main/java/org/openhab/voice/rustpotterks/internal/RustpotterKSService.java
Hello, 
I would like to merge these minor fix as a user from the forum has let me know that the library fails on windows after the first run.
This commit is not need in the main branch because the new library version already fixes this.
Best regards!
=> [rustpotterks] Fix for Windows, avoid load library multiple times

bundles/org.openhab.binding.lifx/README.md, bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/LifxProduct.java
Allows for discovering all the new LIFX products and their features:
* LIFX Neon
* LIFX String
See:
* https://github.com/LIFX/products/blob/master/products.json
* https://www.lifx.com.au/products/neon-flex-2m-indoor
* https://www.lifx.com.au/products/lifx-string-light
=> [lifx] Add support for new LIFX products

bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/SolaxBindingConstants.java, bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/SolaxLocalAccessHandler.java
- Added a refresh command 
- Implemented a reentrant lock when we retrieve the data via http call so we don't do multiple calls to the same server unless the first call has returned data or timed out. There is no point to flood it as probably it's not very powerful device anyway.
=> [solax] Implementation of refresh command and improved thread safety

bundles/org.openhab.binding.mail/README.md
Adopt doc README to newest default JS environment (ECMAScript (ECMAScript 262 Edition 11) regarding requesting mail actions via actions.get. So newbies have no longer to search in the community blog for this info.
Signed-off-by: Siggi Immel <siegmar@immels.de>
=> [mail] Use of actions.get instead of getActions with new JS

bundles/org.openhab.binding.roku/src/main/java/org/openhab/binding/roku/internal/RokuHttpException.java, bundles/org.openhab.binding.roku/src/main/java/org/openhab/binding/roku/internal/communication/RokuCommunicator.java
Improve handling of http exceptions. If the http GET request to the roku device fails, xml parsing will now be skipped.
=> [roku] Improve exception handling for failed http connections

CODEOWNERS, bom/openhab-addons/pom.xml, bundles/org.openhab.binding.bluetooth.bluez/src/main/java/org/openhab/binding/bluetooth/bluez/internal/BlueZBridgeHandler.java, bundles/org.openhab.binding.bluetooth.grundfosalpha/NOTICE, bundles/org.openhab.binding.bluetooth.grundfosalpha/README.md, bundles/org.openhab.binding.bluetooth.grundfosalpha/pom.xml, bundles/org.openhab.binding.bluetooth.grundfosalpha/src/main/feature/feature.xml, bundles/org.openhab.binding.bluetooth.grundfosalpha/src/main/java/org/openhab/binding/bluetooth/grundfosalpha/internal/GrundfosAlphaBindingConstants.java, bundles/org.openhab.binding.bluetooth.grundfosalpha/src/main/java/org/openhab/binding/bluetooth/grundfosalpha/internal/GrundfosAlphaDiscoveryParticipant.java, bundles/org.openhab.binding.bluetooth.grundfosalpha/src/main/java/org/openhab/binding/bluetooth/grundfosalpha/internal/GrundfosAlphaHandler.java, bundles/org.openhab.binding.bluetooth.grundfosalpha/src/main/java/org/openhab/binding/bluetooth/grundfosalpha/internal/GrundfosAlphaHandlerFactory.java, bundles/org.openhab.binding.bluetooth.grundfosalpha/src/main/resources/OH-INF/i18n/bluetooth.properties, bundles/org.openhab.binding.bluetooth.grundfosalpha/src/main/resources/OH-INF/thing/thing-types.xml, bundles/org.openhab.binding.bluetooth.grundfosalpha/src/test/java/org/openhab/binding/bluetooth/grundfosalpha/internal/GrundfosAlphaHandlerTest.java, bundles/pom.xml
This adds support for reading out the data of Grundfos Alpha Pumps with a Grundfos Alpha Reader (https://product-selection.grundfos.com/de/products/alpha-reader/mi401-alpha-reader-98916967?pumpsystemid=2213476387&tab=variant-specifications)
=> [grundfosalpha] Initial contribution

bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/api/dto/clip2/Resource.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/api/dto/clip2/helper/Setters.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/Clip2BridgeHandler.java, bundles/org.openhab.binding.hue/src/test/java/org/openhab/binding/hue/internal/clip2/SettersTest.java
The overall goal of this pull request is to address issues with unneeded state updates that can happen under certain circumstances.
This can cause:
- Flickering in UI's.
- Misbehavior from rules (see chapter **Context** in #15700).
- A bit of a mess in persisted values.
Three root causes have been identified:
- Multiple messages wrapped in one event are processed sequentially (one by one), causing intermediate state updates.
- _State sent as multiple events where dimming information is missing in first event._ This has been extracted to #15995.
- _Auto update policy is **default**, so commands will trigger state update immediately rather than awaiting the final state from the bridge._ This fix for this has been extracted to #15984.
Given an initial brightness of 0 and this command: …
=> [hue] Fix multiple state updates (API v2)

features/openhab-addons-external/pom.xml, features/openhab-addons-external/src/main/resources/addon-footer.xml, features/openhab-addons-external/src/main/resources/addon-header.xml
Related to https://github.com/openhab/openhab-core/pull/3865
Supersedes #15780
=> Build addon xml

bundles/org.openhab.binding.squeezebox/README.md, bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxPlayerHandler.java, bundles/org.openhab.binding.squeezebox/src/main/resources/OH-INF/thing/thing-types.xml, bundles/org.openhab.binding.squeezebox/src/main/resources/OH-INF/update/instructions.xml
Add [Units of Measurement](https://www.openhab.org/docs/concepts/units-of-measurement.html) support for channels **currentPlayingTime** and **duration**.
=> [squeezebox] Add UoM support for time channels

bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/AbstractMQTTThingHandler.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/AvailabilityTracker.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/handler/GenericMQTTThingHandler.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/AbstractComponent.java
=> [mqtt.homeassistant] handle multiple availability topics

bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/Clip2ThingHandler.java, bundles/org.openhab.binding.hue/src/main/resources/OH-INF/i18n/hue.properties
This slightly improves the handling of missing and unknown resource ID's:
- **Missing:** Change the wording in the description from "bad" to "missing".
- **Unknown:** Change the working in the description from "bad" to "unknown" and mark Thing as **GONE**.
Example:
The scenario for unknown resource ID can be one of the following:
- The resource was removed from the bridge after the Thing was created. For example, deleting a zone for which a Thing exists.
- The Thing is manually configured with an invalid resource ID.
=> [hue] Improve handling of unknown resource ID (API v2)

bundles/org.openhab.binding.synopanalyzer/src/main/java/org/openhab/binding/synopanalyzer/internal/handler/SynopAnalyzerHandler.java, bundles/org.openhab.binding.synopanalyzer/src/main/java/org/openhab/binding/synopanalyzer/internal/synop/Synop.java, bundles/org.openhab.binding.synopanalyzer/src/main/java/org/openhab/binding/synopanalyzer/internal/synop/WindDirections.java
=> [synop] Enhance error handling when no value is provided for windDirection

bundles/org.openhab.binding.opensprinkler/README.md, bundles/org.openhab.binding.opensprinkler/pom.xml, bundles/org.openhab.binding.opensprinkler/src/main/feature/feature.xml, bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/OpenSprinklerBindingConstants.java, bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/OpenSprinklerState.java, bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/api/OpenSprinklerApi.java, bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/api/OpenSprinklerApiFactory.java, bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/api/OpenSprinklerHttpApiV100.java, bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/api/OpenSprinklerHttpApiV219.java, bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/api/OpenSprinklerHttpApiV220.java, bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/handler/OpenSprinklerDeviceHandler.java, bundles/org.openhab.binding.opensprinkler/src/main/resources/OH-INF/i18n/opensprinkler.properties, bundles/org.openhab.binding.opensprinkler/src/main/resources/OH-INF/thing/thing-types.xml, bundles/org.openhab.binding.opensprinkler/src/main/resources/OH-INF/update/instructions.xml
This change fixes the bindings ability to scrape the program names of the sprinkler controllers internal automated programs that a user can select to run. More information is found that the issue this fixes here closes #15260
The newer firmware uses JSON with this structure and the "pd" now has an extra element over previous firmware which causes the update to break the old code. The JSON is an Array that contains mixed types including further arrays. Details are included in case a better method exists.
```
{
"nprogs": 3,
"nboards": 1,
"mnp": 40,
"mnst": 4,
"pnsize": 32,
"pd": [
[3, 68, 0, [20540, 0, 120, 0],
[0, 2700, 2700, 0, 0, 0, 0, 0], Water Lawn, [0, 33, 415]
],
[3, 1, 0, [16384, 0, 0, 0],
[0, 0, 0, 2700, 0, 0, 0, 0], Water Citrus, [0, 33, 415]
],
[3, 18, 0, [16384, 0, 0, 0],
[2700, …
```
=> [opensprinkler] Fix Program names and add new features for firmware 2.2.0

bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/TeslaChannelSelectorProxy.java
Fixes https://github.com/openhab/openhab-addons/issues/15878#issuecomment-1815984738
I tracked this down to a bug which used to update the location from both the location information as well as the "active route location" information, which seems to be delivered by Tesla even though no route is active while the car stays at home.
By cleanly separating these two location types now, the frequent location updates while the car is at home should not appear anymore.
=> [tesla] Fix "jumping" location updates

bundles/org.openhab.binding.pilight/README.md, bundles/org.openhab.binding.pilight/src/main/java/org/openhab/binding/pilight/internal/PilightBridgeConfiguration.java, bundles/org.openhab.binding.pilight/src/main/java/org/openhab/binding/pilight/internal/discovery/PilightDeviceDiscoveryService.java, bundles/org.openhab.binding.pilight/src/main/java/org/openhab/binding/pilight/internal/handler/PilightBridgeHandler.java, bundles/org.openhab.binding.pilight/src/main/resources/OH-INF/i18n/pilight.properties, bundles/org.openhab.binding.pilight/src/main/resources/OH-INF/i18n/pilight_de.properties, bundles/org.openhab.binding.pilight/src/main/resources/OH-INF/thing/bridge.xml
Previously the background discovery updated periodically all channels of all devices regardless whether they have sent an update or not.  This behavior makes it impossible to decide whether a device is still alive by observing channel updates sent by a device itself.  Especially for devices running on battery, it is important to know, if it still sends updates.
=> [pilight] Add option to disable background discovery for a given pilight bridge thing

bundles/org.openhab.binding.denonmarantz/src/main/resources/OH-INF/addon/addon.xml
For my old Denon AVR-3808, the HEOS binding is now suggested. Although it's too old to support HEOS, that's fine. However, the Denon/Marantz binding is **not** suggested. This PR takes the discovery-method provided from HEOS, since this is proven to work with my receiver:
https://github.com/openhab/openhab-addons/blob/8c560a409c5a79c6f935b14b9acb64600fccd0cb/bundles/org.openhab.binding.heos/src/main/resources/OH-INF/addon/addon.xml#L12-L20
=> [denon] Add discovery method for Denon receiver

features/openhab-addons-external/pom.xml
The JDBC persistence add-on has multiple addon-*.xml files, identifying different databases.
The current addon.xml collection process does not collect these, therefore discovery criteria defined for these addons will not be used.
This PR fixes this.
See https://github.com/openhab/openhab-core/issues/3868#issuecomment-1848899824
=> Capture all addon xml files for finders

bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/RollershutterValue.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/TextValue.java, bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/values/ValueTests.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/AbstractComponent.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Cover.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Light.java, bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/CoverTests.java
Fixes #15845
* Add support for covers that report position
* Handle when command and state values for OPEN/CLOSE/STOP differ (as they do by default)
* Expose the full cover state, since it can have tell you if the cover is moving or not
* Handle covers that have a position only, but not a state
=> [mqtt.homeassistant] Improve Cover support

bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/Clip2BridgeHandler.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/Clip2ThingHandler.java
This is a proposal for replacing the approach in #16001.
When receiving this payload:
```json
[
{
"creationtime": "2023-12-07T21:39:38Z",
"data": [
{
"id": "00000000-0000-0000-0000-000000000001",
"id_v1": "/scenes/0000000000000001",
"status": {
"active": "static"
},
"type": "scene"
},
{
"id": "00000000-0000-0000-0000-000000000002",
"id_v1": "/scenes/0000000000000002",
"status": {
"active": "inactive"
},
"type": "scene"
}
],
"id": "00000000-0000-0000-0000-000000000000",
"type": "update"
}
]
```
The correct state change is triggered:
```
2023-12-07 22:39:37.368 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Kontor_Scene' changed from Klar to Slap af
```
Also tested transition from `UNDEF` -> scene and scene -> `UNDEF`.
Since there is only one supported channel for resource type …
=> [hue] Fix scene channel updates (API v2)

bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/addon/addon.xml
Fixes #16036
This now corresponds to the discovery code:
https://github.com/openhab/openhab-addons/blob/f45630064a4959c294ac01f9835df68190ac875d/bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/discovery/BridgeDiscoveryParticipant.java#L89-L93
=> [deconz] Fix discovery methods

bundles/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/handler/ModbusDataThingHandler.java
The fact that a modbus `data` thing can only be used for reading if it is connected to a `polling` bridge thing (rather than to a TCP or serial bridge thing), [might not be obvious to every user](#16041). This PR improves the error message in case of a misconfiguration, i.e. if a thing is configured for reading but not connected to a polling bridge.
=> [modbus] Improve error message if data thing is configured for reading but not connected to a polling bridge.

bundles/org.openhab.binding.nikobus/README.md
Differences in address writing convention between Niko's software and this binding explained
=> [nikobus] Update README.md

bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/DiscoverComponents.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/ComponentFactory.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Update.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/handler/HomeAssistantThingHandler.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/resources/OH-INF/config/homeassistant-thing-config.xml, bundles/org.openhab.binding.mqtt.homeassistant/src/main/resources/OH-INF/i18n/mqtt.properties, bundles/org.openhab.binding.mqtt.homeassistant/src/main/resources/OH-INF/thing/homeassistant-thing.xml
This component is fairly non-standard - it doesn't add any channels. Instead, it provides several properties to the thing, and also adds a thing configuration allowing you to trigger an OTA update on a Home Assistant device from MainUI.
Fixes #14022, #14881
=> [mqtt.homeassistant] Add support for Update component

bundles/org.openhab.binding.mqtt.espmilighthub/src/main/java/org/openhab/binding/mqtt/espmilighthub/internal/handler/EspMilightHubHandler.java
and fix that it expects ranges from 0.0 to 1.0 instead of 0.0 to 100.0
this fixes the error:
```
2023-12-15 09:25:53.036 [WARN ] [nternal.handler.EspMilightHubHandler] - Failed processing Milight state {"state":"OFF","level":0,"color_temp":166,"bulb_mode":"white"} for milight/states/0x1757/fut089/3
java.lang.IllegalArgumentException: xy array only allows two or three values between 0.0 and 1.0.
```
=> [mqtt.espmilighthub] use ColorUtil instead of deprecated HSBType.fromXY

bundles/org.openhab.binding.neato/README.md
I've updated the sample neato.things file in the Neato binding docs with an example configuration for a bridge. I've also included a link between the thing and the bridge as this was missing from the previous example.
=> [neato] Fix things file example in Readme

bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/ApiBridgeHandler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/CommonInterface.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/CapabilityMap.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/ParentUpdateCapability.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/RefreshCapability.java
This PR adresses an issue raised in #15928.
Some zombie job can remain if : 
* The bridge goes online and offline while inbetween one of its child scheduled to ask for data expiration
* Refresh process did not kill the job on error and rescheduled it
=> [netatmo] Ensure to close all scheduled jobs

bundles/org.openhab.binding.knx/doc/dpt.txt, bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/DPTUtil.java, bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/ValueDecoder.java, bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/ValueEncoder.java, bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/client/DummyClient.java, bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/client/DummyKNXNetworkLink.java, bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/client/DummyProcessListener.java, bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/dpt/DPTTest.java, bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/itests/Back2BackTest.java
* Add integration tests which include decoding and encoding KNX frames, and the handling by Calimero library as well. This ensures that the KNX wire format is handled properly.
* Add itests for *all* main DPT numbers supported by Calimero.
* Add a mechanism to check for new missing DPT main numbers when new Calimero release is integrated.
The idea of this PR is basically to check the whole way from bytes on the KNX bus through Calimero, into the plugin, and back again via Calimero down to the bus again. The implementation overwrites KNXNetworkLink to implement a test interface. Calimero is then set up on top.
The benefit of this approach is that we now cover large parts of the handling of KNX frame in the Calimero library, without the need of setting up real itests including bus …
=> [knx] Add integration tests

bundles/org.openhab.automation.jsscripting/pom.xml
You'll find the changelog at the openhab-js repo: https://github.com/openhab/openhab-js/blob/main/CHANGELOG.md#471.
=> [jsscripting] Upgrade openhab-js to 4.7.1

bundles/org.openhab.binding.heos/src/main/resources/OH-INF/addon/addon.xml
As identified in https://github.com/openhab/openhab-addons/pull/16035, with the current discovery criteria in addon.xml, Denon devices that do not support HEOS are also discovered.
This PR aligns the criteria in addon.xml with the checks in the discovery java code and should eliminate these false positives.
I don't own HEOS devices (or other Wifi enabled Denon devices), so cannot test.
@jlaur Could you check if you still see the HEOS suggestion?
=> [HEOS] more restrictive HEOS finder criteria

bundles/org.openhab.binding.energidataservice/README.md, bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/handler/EnergiDataServiceHandler.java, bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/thing/channel-groups.xml, bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/thing/channel-types.xml, bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/thing/thing-service.xml, bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/update/instructions.xml
Related to openhab/openhab-core#3503
Tested with latest snapshot and custom built org.openhab.core-4.1.0-SNAPSHOT.jar and org.openhab.core.config.core-4.1.0-SNAPSHOT.jar from main.
=> [energidataservice] Add UoM support for energy prices

CODEOWNERS, bom/openhab-addons/pom.xml, bundles/org.openhab.binding.smgw/NOTICE, bundles/org.openhab.binding.smgw/README.md, bundles/org.openhab.binding.smgw/pom.xml, bundles/org.openhab.binding.smgw/src/main/feature/feature.xml, bundles/org.openhab.binding.smgw/src/main/java/org/openhab/binding/smgw/internal/SmgwBindingConstants.java, bundles/org.openhab.binding.smgw/src/main/java/org/openhab/binding/smgw/internal/SmgwConfiguration.java, bundles/org.openhab.binding.smgw/src/main/java/org/openhab/binding/smgw/internal/SmgwHandler.java, bundles/org.openhab.binding.smgw/src/main/java/org/openhab/binding/smgw/internal/SmgwHandlerFactory.java, bundles/org.openhab.binding.smgw/src/main/resources/OH-INF/addon/addon.xml, bundles/org.openhab.binding.smgw/src/main/resources/OH-INF/i18n/smgw.properties, bundles/org.openhab.binding.smgw/src/main/resources/OH-INF/thing/thing-types.xml, bundles/pom.xml
This integrates smart meter gateways from PPC which are in widespread-use for supplier provided smart meters.
Topic: https://community.openhab.org/t/integration-smart-meter-geteway-smgw-in-openhab/123772
Marketplace: https://community.openhab.org/t/smgw-binding-4-0-0-5-0-0/151845
=> [smgw] Initial contribution

bundles/org.openhab.binding.wemo/src/main/resources/OH-INF/addon/addon.xml
This should more closely match:
https://github.com/openhab/openhab-addons/blob/6763100511974badda06eb970c5bd68254722462/bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/discovery/WemoDiscoveryParticipant.java#L82-L164
In the UPnP Explorer app for Android, my WeMo Insight shows as:
- **Manufacturer:** Belkin International Inc.
- **Model Name:** Insight
- **Model Number:** 1.0
- **Model Description:** Belkin Insight 1.0
Relevant XML part:
```xml
<deviceType>urn:Belkin:device:insight:1</deviceType>
<manufacturer>Belkin International Inc.</manufacturer>
<manufacturerURL>http://www.belkin.com</manufacturerURL>
<modelDescription>Belkin Insight 1.0</modelDescription>
<modelName>Insight</modelName>
<modelNumber>1.0</modelNumber> …
```
=> [wemo] Fix discovery methods

bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/api/OpenSprinklerHttpApiV100.java, bundles/org.openhab.binding.opensprinkler/src/main/resources/OH-INF/thing/thing-types.xml
The channel will display "0" when the current draw is 300mA, so users will think this is a bug. Changing the default state description allows it to be displayed as '0.3 A'
Also the WARN that is changed to DEBUG is very annoying in the logs as the sprinkler controller is often located outside a long way from the wifi and getting multiple WARNS when it has not yet failed all the allowed retries is IMHO not inline with logging guidelines.
=> [opensprinkler] Fix excessive WARN in logs due to wifi dropouts, and current displays as 0

bundles/org.openhab.binding.surepetcare/src/main/java/org/openhab/binding/surepetcare/internal/discovery/SurePetcareDiscoveryService.java
=> [surepetcare] Fix `NullReferenceException`

bundles/org.openhab.binding.surepetcare/src/main/java/org/openhab/binding/surepetcare/internal/utils/GsonZonedDateTimeTypeAdapter.java, bundles/org.openhab.binding.surepetcare/src/test/java/org/openhab/binding/surepetcare/internal/data/SurePetcareTopologyTest.java
Fixes #16082
JAR for testing: [org.openhab.binding.surepetcare-4.1.0-SNAPSHOT.jar](https://drive.google.com/file/d/1zWylM9TzlHJ-9bVPOLEwbEKQe_ZmDn8z/view?usp=sharing)
=> [surepetcare] Fix `DateTimeParseException`

bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/HikvisionHandler.java, bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/IpCameraBindingConstants.java, bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/handler/IpCameraHandler.java
These changes fix an issue reported on the forum that created repeat warnings in the logs due to some Hikvision cameras giving a http 403 error when a call to an unsupported API was made:
https://community.openhab.org/t/ipcamera-binding-doing-erroneous-isapi-request-to-hikvision-camera/147345
It also removes channels from being seen by the user when the camera reports that it has no IO inputs and outputs.
=> [ipcamera] Remove channels and stop checking IO status when camera does not support IO

bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/OpenhabGraalJSScriptEngine.java
Regression from https://github.com/openhab/openhab-js/pull/312.
=> [jssscripting] Fix JS Quantity to Java QuantityType conversion

bundles/org.openhab.binding.mqtt.espmilighthub/src/main/resources/OH-INF/thing/thing-types.xml
since #13801, it's not been possible to add new milight things, because the thing XML already has the new channel types, but not the thingTypeVersion property set, so it would try to apply the update instructions and error about duplicate channels
=> [mqtt.espmilighthub] fix upgrade instructions

bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/NAHomeStatus.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/deserialization/NADeserializer.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/EnergyCapability.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/SecurityCapability.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/channelhelper/SecurityChannelHelper.java
=> [netatmo] Enable home being both energy and security

bundles/org.openhab.binding.pjlinkdevice/src/main/java/org/openhab/binding/pjlinkdevice/internal/discovery/AbstractDiscoveryParticipant.java
This is an issue if the user cancels/restarts discovery scans, new tasks were added to the shutdown threadpool.
- With this PR, a new threadpool will be created on the next scan in getExecutorService().
- Without this PR, java.util.concurrent.RejectedExecutionExceptions would happen from the second scan.
=> [PJLink] forget threadpool after it was shutdown

bundles/org.openhab.persistence.jdbc/README.md, bundles/org.openhab.persistence.jdbc/pom.xml, bundles/org.openhab.persistence.jdbc/src/main/feature/feature.xml, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcConfiguration.java
Release notes:
- https://dev.mysql.com/doc/relnotes/connector-j/en/news-8-2-0.html
Library:
- https://mvnrepository.com/artifact/com.mysql/mysql-connector-j/8.2.0
Tested by installing compiled bundle as well as `mysql-connector-j-8.2.0.jar` into addons directory as `mysql-connector-j.jar`.
Previous upgrade: #15802
=> [jdbc] Upgrade MySQL Connector/J to 8.2.0

bundles/org.openhab.binding.chatgpt/src/main/java/org/openhab/binding/chatgpt/internal/ChatGPTBindingConstants.java, bundles/org.openhab.binding.chatgpt/src/main/java/org/openhab/binding/chatgpt/internal/ChatGPTModelOptionProvider.java
See https://github.com/openhab/openhab-addons/pull/15578/files#r1438056961
=> [chatgpt] Fix ConfigOptionProvider

bundles/org.openhab.binding.boschshc/README.md, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/BoschSHCBindingConstants.java, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/BoschSHCHandlerFactory.java, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/BoschHttpClient.java, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/BridgeHandler.java, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/ScenarioHandler.java, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/dto/UserDefinedState.java, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/userdefinedstate/UserStateHandler.java, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/discovery/ThingDiscoveryService.java, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/serialization/BoschServiceDataDeserializer.java, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/dto/BoschSHCServiceState.java, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/userstate/UserStateService.java, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/userstate/dto/UserStateServiceState.java, bundles/org.openhab.binding.boschshc/src/main/resources/OH-INF/config/configs.xml, bundles/org.openhab.binding.boschshc/src/main/resources/OH-INF/i18n/boschshc.properties, bundles/org.openhab.binding.boschshc/src/main/resources/OH-INF/thing/thing-types.xml, bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/bridge/BoschHttpClientTest.java, bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/bridge/BridgeHandlerTest.java, bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/bridge/LongPollingTest.java, bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/bridge/ScenarioHandlerTest.java, bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/bridge/dto/UserDefinedStateTest.java, bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/userdefinedstate/UserStateHandlerTest.java, bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/discovery/ThingDiscoveryServiceTest.java, bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/services/dto/BoschSHCServiceStateTest.java, bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/services/userstate/dto/UserStateServiceStateTest.java
This PR adds the new User-defined states as separate things to the Bosch Smart Home Binding
Bosch recently added a new feature called User-defined states (see also issue #16008 ). 
With this PR it is possible to add the User-defined states as new Things in openHAB and get or set the state.
Already existing User-defined states are also auto discovered by the binding.
Your pull request will automatically be built and available under the following folder:
https://openhab.jfrog.io/ui/native/libs-pullrequest-local/org/openhab/addons/bundles/
Jar: https://openhab.jfrog.io/artifactory/libs-pullrequest-local/org/openhab/addons/bundles/org.openhab.binding.boschshc/4.1.0-SNAPSHOT/org.openhab.binding.boschshc-4.1.0-SNAPSHOT.jar
=> [boschshc] Add user defined states

bundles/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/handler/MilightV6RGBCWWWHandler.java, bundles/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/handler/MilightV6RGBWHandler.java
Sending a "INCREASE" to a dimmer-Item on "animation_speed_relative" decreases the animation Speed.
Caused by a wrong comparison in:
org\openhab\binding\milight\internal\handler\MilightV6RGBCWWWHandler.java: line 87,
org\openhab\binding\milight\internal\handler\MilightV6RGBWHandler.java line: 80
relative Speed cannot be greater than one, as it is called with the values -1 or 1 from handleCommand() inside AbstractLedHandler.java.
Fixes #8430
=> [milight] Fix for failing to increas animation speed

bundles/org.openhab.binding.shelly/pom.xml
Adds a package import so the class can be found by the class loader.
Fixes #16118
=> [shelly] Fix WebSocketServerFactory ClassNotFoundException

bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosBindingConstants.java, bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/discovery/ZonePlayerDiscoveryParticipant.java
Some devices like subs are more or less a transparant slave and are not added to openHAB as Thing. As the amount of devices slowly grows a more future proof check is needed to prevent unwanted logging. 
Fixes:  https://github.com/openhab/openhab-addons/issues/16125
=> [sonos] prevent logging unsupported device

bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/api/WledApiV0110.java
Presets can have the `bri` value missing and the binding was using this to detect playlist objects from presets. This PR fixes this and should be backwards and forwards compatible with different firmwares. Reported on the forum here:
https://community.openhab.org/t/wled-0-14-doesnt-fetch-preset/152313
This pull request is available under the following links if anyone wants to test:
https://openhab.jfrog.io/ui/native/libs-pullrequest-local/org/openhab/addons/bundles/
Just the needed jar.
https://openhab.jfrog.io/ui/native/libs-pullrequest-local/org/openhab/addons/bundles/org.openhab.binding.wled/4.2.0-SNAPSHOT/org.openhab.binding.wled-4.2.0-SNAPSHOT.jar
=> [wled] Fix Playlist and Preset detection when missing bri values

bundles/org.openhab.binding.bluetooth.bluez/pom.xml, bundles/org.openhab.binding.bluetooth.bluez/src/main/java/org/openhab/binding/bluetooth/bluez/internal/BlueZBluetoothDevice.java
- Upgrade bluez-dbus-osgi dependency 0.1.3 to 0.1.4
- Fixes https://github.com/openhab/openhab-addons/issues/10197 (not only for bluez, but also for ruuvitags)
Jar for 4.2.0: https://1drv.ms/u/s!AnMcxmvEeupwjuJXEKzJfN_WzqWm4g?e=mPMKXu
=> [bluetooth.bluez] Workaround exception on disconnect

bundles/org.openhab.binding.kaleidescape/README.md, bundles/org.openhab.binding.tivo/README.md
Update the README for kaleidescape and tivo to provide example usages of the sitemap element type 'Input'.
=> Update README with sitemap Input example

bundles/org.openhab.voice.pollytts/pom.xml, bundles/org.openhab.voice.pollytts/src/main/feature/feature.xml
A newer AWS Java SDK is required when using Jackson 2.16.
Fixes #16108 
Depends on https://github.com/openhab/openhab-osgiify/pull/45
=> [pollytts] Update AWS Java SDK

bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/OnOffValue.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/TextValue.java, bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/values/ValueTests.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/AbstractComponent.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Lock.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Switch.java, bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/LockTests.java
* handle state and command payloads differing (as they do by default)
* expose full state possibilities and OPEN command by adding a TextValue channel
=> [mqtt.homeassistant] Improve support for Lock component

bundles/org.openhab.persistence.inmemory/src/main/java/org/openhab/persistence/inmemory/internal/InMemoryPersistenceService.java, bundles/org.openhab.persistence.inmemory/src/test/java/org/openhab/persistence/inmemory/internal/InMemoryPersistenceTests.java
=> [inmemory] Add filterCritera ordering

bundles/org.openhab.binding.chromecast/NOTICE, bundles/org.openhab.binding.chromecast/pom.xml
Protobuf library 2.6.0 has known issues and causes security warnings.
Try to update protobuf to a more recent release (which does not issue update warnings).
*Not sure if this works.*
@wborn You offered to do some testing on the forum, so maybe you could give it a try.
=> [chromecast] Update protobuf from 2.6.0 to protobuf-javalite 3.25.1

bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/LongPolling.java, bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/bridge/LongPollingTest.java
If the long poll response from the Smart Home Controller does not contain valid JSON, the subscription is gracefully terminated a new one is initiated after 15 seconds.
closes #15912
=> [boschshc] Handle invalid long poll responses gracefully

bundles/org.openhab.binding.systeminfo/pom.xml, bundles/org.openhab.binding.systeminfo/src/main/feature/feature.xml
This is the latest OSHI version that is compatible with the Karaf provided JNA 5.13.0
=> [systeminfo] Bump OSHI to 6.4.8

bundles/org.openhab.binding.bosesoundtouch/src/main/feature/feature.xml, bundles/org.openhab.binding.deconz/src/main/feature/feature.xml, bundles/org.openhab.binding.evohome/src/main/feature/feature.xml, bundles/org.openhab.binding.hyperion/src/main/feature/feature.xml, bundles/org.openhab.binding.jablotron/src/main/feature/feature.xml, bundles/org.openhab.binding.kodi/src/main/feature/feature.xml, bundles/org.openhab.binding.konnected/src/main/feature/feature.xml, bundles/org.openhab.binding.livisismarthome/src/main/feature/feature.xml, bundles/org.openhab.binding.mycroft/src/main/feature/feature.xml, bundles/org.openhab.binding.nuki/src/main/feature/feature.xml, bundles/org.openhab.binding.somfytahoma/src/main/feature/feature.xml, bundles/org.openhab.binding.spotify/src/main/feature/feature.xml, bundles/org.openhab.binding.vektiva/src/main/feature/feature.xml
The openhab-transport-http feature dependency is redundant since OH 2.3 when it was added to the openhab-runtime-base feature dependencies.
See:
* https://github.com/openhab/openhab-core/pull/344
* https://github.com/openhab/openhab-addons/pull/16181#issuecomment-1876015592
=> Remove openhab-transport-http feature dependencies

bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/handler/EnergiDataServiceHandler.java
This reduces the work-around provided in #16085 after the root cause has been fixed in openhab/openhab-core#4016.
Updating using currency code rather than currency symbol should be more robust since currency code is guaranteed to be unique. Therefore I'd propose to also cherry-pick this fix into 4.1.x along with openhab/openhab-core#4016 which was already cherry-picked.
=> [energidataservice] Increase robustness of UoM price updates by using currency code rather than symbol

bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/handler/EnergiDataServiceHandler.java
Unlike spotprices, tariffs are not updated by the hour.
The most dynamic tariff is the grid tariff which can currently change as often as four times per day. The most static one is the system tariff which is usually only changed once in very hectic years.
The time series implementation didn't take any of this into consideration. Previously when using persistence strategy **everyChange** this was not a problem (first row is an actual change, the rest are probably caused by restarts):
| Timestamp               | Value   |
|-------------------------|---------|
| 2023-07-01 00:00:00.064 | 0.87125 |
| 2023-09-30 12:51:56.487 | 0.87125 |
| 2023-11-04 20:31:20.955 | 0.87125 |
| 2023-11-18 17:25:23.032 | 0.87125 |
Now, when using persistence strategy **forecast**, this would cause many redundant …
=> [energidataservice] Reduce redundant persistence of tariffs

bundles/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/internal/live/TelldusLiveDeviceController.java, bundles/org.openhab.binding.tellstick/src/main/resources/OH-INF/addon/addon.xml
Resolves #15987
Note: not (yet) tested.
=> [tellstick] Adopt new API url

bundles/org.openhab.binding.tellstick/README.md, bundles/org.openhab.binding.tellstick/src/main/resources/OH-INF/addon/addon.xml
=> [tellstick] Add support for suggestion finder

bundles/org.openhab.binding.roku/README.md, bundles/org.openhab.binding.roku/src/main/java/org/openhab/binding/roku/internal/communication/RokuCommunicator.java, bundles/org.openhab.binding.roku/src/main/java/org/openhab/binding/roku/internal/discovery/RokuDiscoveryService.java, bundles/org.openhab.binding.roku/src/main/java/org/openhab/binding/roku/internal/handler/RokuHandler.java
Improve the label that is given to the thing by the discovery process. Previously TV things were not easily identified as a Roku device by the model name provided by the API. The `friendly-model-name` and `user-device-location` fields are now combined to help the user identify the thing in case of duplicate devices in different rooms.  The strings are formatted to remove any extraneous characters as seen in the friendly-model-name example. 
Addresses #15797 by setting a timeout on http requests sent to the roku device. Previously if the device was to crash while an http request was in progress it could cause the binding to hang.
Addresses #16164 by setting the uuid property to prevent manually added things from appearing in the inbox.
=> [roku] Improve TV discovery model name and add timeout

bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/discovery/IndegoDiscoveryService.java
Although not very well documented (only as "timestamp"), [removeOlderResults](https://www.openhab.org/javadoc/latest/org/openhab/core/config/discovery/abstractdiscoveryservice#removeOlderResults(long)) expects number of milliseconds since epoch:
https://github.com/openhab/openhab-core/blob/9cb4b9ee1fe7c6fbc68df5db74429be7da4ccb3b/bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/internal/DiscoveryResultImpl.java#L222-L225
=> [boschindego] Fix removal of discovery results

bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/influx1/InfluxDB1RepositoryImpl.java
=> [influxdb] Fix exception handling for InfluxDB 1.x

bundles/org.openhab.binding.asuswrt/src/main/java/org/openhab/binding/asuswrt/internal/AsuswrtDiscoveryService.java, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/discovery/ThingDiscoveryService.java, bundles/org.openhab.binding.bticinosmarther/src/main/java/org/openhab/binding/bticinosmarther/internal/discovery/SmartherModuleDiscoveryService.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/discovery/ThingDiscoveryService.java, bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/discovery/DeviceDiscoveryService.java, bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/discovery/SceneDiscoveryService.java, bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/discovery/ZoneTemperatureControlDiscoveryService.java, bundles/org.openhab.binding.gpstracker/src/main/java/org/openhab/binding/gpstracker/internal/discovery/TrackerDiscoveryService.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/discovery/Clip2ThingDiscoveryService.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/discovery/HueDeviceDiscoveryService.java, bundles/org.openhab.binding.hydrawise/src/main/java/org/openhab/binding/hydrawise/internal/discovery/HydrawiseCloudControllerDiscoveryService.java, bundles/org.openhab.binding.livisismarthome/src/main/java/org/openhab/binding/livisismarthome/internal/discovery/LivisiDeviceDiscoveryService.java, bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/discovery/MaxDeviceDiscoveryService.java, bundles/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/discovery/XiaomiItemDiscoveryService.java, bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/discovery/AbstractMQTTDiscovery.java, bundles/org.openhab.binding.nobohub/src/main/java/org/openhab/binding/nobohub/internal/discovery/NoboHubDiscoveryService.java, bundles/org.openhab.binding.nobohub/src/main/java/org/openhab/binding/nobohub/internal/discovery/NoboThingDiscoveryService.java, bundles/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/discovery/OwDiscoveryService.java, bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/discovery/OpenWeatherMapDiscoveryService.java, bundles/org.openhab.binding.touchwand/src/main/java/org/openhab/binding/touchwand/internal/discovery/TouchWandUnitDiscoveryService.java, bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/Tr064DiscoveryService.java, bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/discovery/TradfriDiscoveryService.java, bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/discovery/VelbusThingDiscoveryService.java
This refactors some [java.util.Date](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/Date.html) usages to the more modern [time API](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/time/package-summary.html).
See also openhab/openhab-core#4026
=> Refactor `java.util.Date` usages to `java.time.Instant`

bundles/org.openhab.binding.energidataservice/README.md, bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/EnergiDataServiceBindingConstants.java, bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/handler/EnergiDataServiceHandler.java, bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/i18n/energidataservice.properties, bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/thing/channel-groups.xml, bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/thing/channel-types.xml, bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/thing/thing-service.xml, bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/update/instructions.xml
With the introduction of openhab/openhab-core#3597 and #15063 in openHAB 4.1, the advanced channel `hourly-prices` is now fully obsoleted.
It was already possible to use binding-specific Thing actions for importing future prices into rules, but since 4.1.1 it's also possible to access future prices through [in-memory persistence](https://www.openhab.org/addons/persistence/inmemory/), i.e. persisted time series.
Therefore, the binding can be simplified by removing this channel.
=> [energidataservice] Remove obsoleted advanced channel `hourly-prices`

bundles/org.openhab.binding.androidtv/src/main/java/org/openhab/binding/androidtv/internal/AndroidTVHandler.java, bundles/org.openhab.binding.androidtv/src/main/java/org/openhab/binding/androidtv/internal/discovery/GoogleTVDiscoveryParticipant.java, bundles/org.openhab.binding.androidtv/src/main/java/org/openhab/binding/androidtv/internal/discovery/ShieldTVDiscoveryParticipant.java
Resolves issue with discovered items not being ignored correctly
Resolves #16223
=> [androidtv] Resolves discovery issues

bundles/org.openhab.binding.tibber/README.md, bundles/org.openhab.binding.tibber/src/main/java/org/openhab/binding/tibber/internal/handler/TibberHandler.java
This PR addeds time series support for future tibber prices to openhab.
The values, that are currenty served as json data, are parsed and served as time series for the current total costs channel.
=> [tibber] Add time series support for Tibber prices

bundles/org.openhab.binding.ojelectronics/src/main/java/org/openhab/binding/ojelectronics/internal/ThermostatHandler.java
Since version OH4.1 (maybe OH4) there are some problems with setting temperatur values. The reasons seems to be that sometimes the command is not a QuantityType<?> but a Number.
This PR fixes #16158
=> [ojelectronics] Adjust setpoint command handling

bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/api/DatahubTariffFilterFactory.java
Update grid tariff filter for Nordvestjylland og Omegns Elforsyning according to new tariff model 3.0:
https://noe.dk/wp-content/uploads/2023/09/Prisblad-pr.-1.-januar-2024.pdf
=> [energidataservice] Update tariff filter for NOE Net

bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/BoschHttpClient.java, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/discovery/BridgeDiscoveryParticipant.java, bundles/org.openhab.binding.boschshc/src/main/resources/OH-INF/addon/addon.xml, bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/discovery/BridgeDiscoveryParticipantTest.java
The bridge discovery participant receives lots of mDNS events. Previously, all events that contained IP addresses of potential bridges were actively contacted using HTTP requests. On some systems eventually the long polling stops due to too many requests.
With this change, we
* only consider mDNS events where the name property starts with "Bosch SHC"
* cache already discovered bridges so we don't have to contact them over and over again
* make sure that this happens in a thread-safe manner because the mDNS events are handled in individual concurrently running threads
closes #16174
=> [boschshc] Cache mDNS-based bridge discovery results

CODEOWNERS, bom/openhab-addons/pom.xml, bundles/org.openhab.binding.freecurrency/NOTICE, bundles/org.openhab.binding.freecurrency/README.md, bundles/org.openhab.binding.freecurrency/pom.xml, bundles/org.openhab.binding.freecurrency/src/main/feature/feature.xml, bundles/org.openhab.binding.freecurrency/src/main/java/org/openhab/binding/freecurrency/internal/ExchangeRateListener.java, bundles/org.openhab.binding.freecurrency/src/main/java/org/openhab/binding/freecurrency/internal/FreecurrencyBindingConstants.java, bundles/org.openhab.binding.freecurrency/src/main/java/org/openhab/binding/freecurrency/internal/FreecurrencyHandler.java, bundles/org.openhab.binding.freecurrency/src/main/java/org/openhab/binding/freecurrency/internal/FreecurrencyHandlerFactory.java, bundles/org.openhab.binding.freecurrency/src/main/java/org/openhab/binding/freecurrency/internal/FreecurrencyProvider.java, bundles/org.openhab.binding.freecurrency/src/main/java/org/openhab/binding/freecurrency/internal/config/FreecurrencyExhangeRateChannelConfig.java, bundles/org.openhab.binding.freecurrency/src/main/java/org/openhab/binding/freecurrency/internal/config/FreecurrencyServiceConfig.java, bundles/org.openhab.binding.freecurrency/src/main/java/org/openhab/binding/freecurrency/internal/dto/CurrenciesDTO.java, bundles/org.openhab.binding.freecurrency/src/main/java/org/openhab/binding/freecurrency/internal/dto/ExchangeRatesDTO.java, bundles/org.openhab.binding.freecurrency/src/main/resources/OH-INF/addon/addon.xml, bundles/org.openhab.binding.freecurrency/src/main/resources/OH-INF/i18n/freecurrency.properties, bundles/org.openhab.binding.freecurrency/src/main/resources/OH-INF/thing/thing-types.xml, bundles/pom.xml
This is the first "real" `CurrencyProvider` that makes full use of the UoM currency capability introduced in openHAB 4.1. By getting a free API key 33 common currencies can be automatically converted.
=> [freecurrency] Initial contribution

bundles/org.openhab.persistence.influxdb/pom.xml, bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/influx2/InfluxDB2RepositoryImpl.java
Update influx client to 4.3.0 and use ping endpoint to check for database availability. Fixes https://github.com/openhab/openhab-addons/issues/16147
Chose not to go to newest client version since this will resolve to some vulnerabilities in the dependency tree according to maven central (https://mvnrepository.com/artifact/com.squareup.retrofit2/adapter-rxjava3/2.9.0)
Did not run all tests since they seem to require some running influx instances and i could not find information on how to setup those. 
Resulting jar: [org.openhab.persistence.influxdb-4.2.0-SNAPSHOT.jar.zip](https://github.com/openhab/openhab-addons/files/13798883/org.openhab.persistence.influxdb-4.2.0-SNAPSHOT.jar.zip)
=> [influxdb] Add compatibility with InfluxDB Cloud Serverless 

bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/HttpThingHandler.java, bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/http/RefreshingUrlCache.java, bundles/org.openhab.binding.http/src/test/java/org/openhab/binding/http/RateLimitedHttpClientTest.java, bundles/org.openhab.binding.http/src/test/java/org/openhab/binding/http/RefreshingUrlCacheTest.java
Found while investigating https://community.openhab.org/t/http-refresh-and-delay/128747/32
=> [http] Fix refresh time check and calculation

bundles/org.openhab.binding.shelly/src/main/resources/scripts/oh-blu-scanner.js
Overcome timing issue when script starts, but the BLU communication layer is not yet fully initialized
=> [shelly] Make blu gw script more robust on startup

bundles/org.openhab.binding.yamahamusiccast/src/main/resources/OH-INF/addon/addon.xml, bundles/org.openhab.binding.yamahamusiccast/src/main/resources/OH-INF/i18n/yamahamusiccast.properties, bundles/org.openhab.binding.yamahareceiver/src/main/resources/OH-INF/addon/addon.xml, bundles/org.openhab.binding.yamahareceiver/src/main/resources/OH-INF/i18n/yamahareceiver.properties
Seems like Yamaha is using uppercase `YAMAHA CORPORATION` for the manufacturer info of non-MusicCast devices and normal case `Yamaha Corporation` for MusicCast devices.
=> [yamahamusiccast] Add discovery information

bundles/org.openhab.binding.mpd/src/main/java/org/openhab/binding/mpd/internal/protocol/MPDConnectionThread.java
I'm using MPD on an old tablet. I wrote a rule to play music to alert when windows are open to long. It works in general. 
Unfortunately, when MPD is idle for a long time, the connection get lost. Then (when my window rule send the play command) the mpd binding automatically reconnects after 60s, but the pending commands are lost. Therefore my alert is not working most of the time.
The mpd binding should handle reconnect on idle connections without loosing commands. (This is similar to JDBC connection pools like HikariCP handle broken idle JDBC connections.)
The mpd binding looses pending commands when reconnecting after detecting a broken connection.
Here is a trace log of such a case (formatted with extra empty lines):
```
...
2024-01-14 11:19:20.249 [TRACE] …
```
=> [MPD] reconnect on broken idle connection should not loose pending commands

bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/ValueDecoder.java, bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/ValueEncoder.java, bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/itests/Back2BackTest.java
* Allow assigning Switch or Contact to most of the DPT 1 subtypes (exceptions 1.008 UpDownType, 1.010 StopMoveType, 1.022 DecimalType).
* Tests for all published subtypes for DPT 1.
* Fix sending of DPT 1.022.
This PR has been initiated because of a discussion in the (German speaking) [KNX User Forum](https://knx-user-forum.de/forum/supportforen/openhab/1921835-ko-mit-datentyp-1-011-als-switch-geht-als-contact-nicht).
DPT1 implementation had a rather strict mapping to types before. A Contact could not be used if the specific DPT was added to the group address definition ```ga="1.011:<17/1/38"```, unless it was 1.009 or 1.019. As only subtypes 009 and 019 were mapped to OpenClosedType and the fallback for other DPTs was OnOffType,
=> [knx] DPT 1 to support Switch and Contact

bundles/org.openhab.binding.knx/README.md, bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/DPTUtil.java, bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/ValueDecoder.java, bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/dpt/DPTTest.java
Composed type not yet supported by Calimero, thus only receiving data is implemented.
Configure DPT 235.001 to receive ActiveEnergy.
Configure DPT 235.61001 to receive Tariff information.
Fixes #15159
=> [knx] Allow receiving DPT 235.001

bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/api/DatahubTariffFilterFactory.java
Update filter to grid tariff C. Verified with price list available here:
https://www.ikastelnet.dk/wp-content/uploads/2023/09/Takstblad-Ikast-El-Net-A_S-1.-Oktober-2023.pdf
=> [energidataservice] Update tariff filter for Ikast El Net

bundles/org.openhab.binding.openwebnet/README.md
Currently the links are broken on binding README rendering for OH website
=> [openwebnet] fixed 2 dotted links in README

bundles/org.openhab.binding.teleinfo/README.md
Resolve #16323
This PR remove a sentence which implies standard TIC mode is not supported by the binding.
Standard TIC mode is supported since #11375.
=> [teleinfo] Update documentation to match #16323

bundles/org.openhab.binding.knx/README.md, bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/DPTUtil.java, bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/ValueDecoder.java, bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/ValueEncoder.java, bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/itests/Back2BackTest.java
Allow lossy conversion from RGBW to HSBType and back instead of using separate items for RGB and W.
Select via DPT 251.60600.
> RGBW (DPT 251.600) can either be converted to HSBType, or be represented two items: a HSBType for RGB and an additional PercentType for W channel.
Default handling for RGBW is to use separate items.
Note that this also requires two frames being sent out separately when these elements are sent to the bus, as the binary representation uses a partially populated KNX frame.  
Alternatively, a single HSB item can be used. Conversion to a single HSBType will loose the exact setting for W, and will reconstruct it when a conversion to RGBW is required.
This option can be selected using the special DPT 251.60600.
=> [knx] Add support for RGBW represented by HSBType

bundles/org.openhab.binding.smartmeter/src/main/java/org/openhab/binding/smartmeter/internal/conformity/negate/NegateHandler.java, bundles/org.openhab.binding.smartmeter/src/test/java/org/openhab/binding/smartmeter/TestNegateBit.java
- Fixes #11029 by handling the way string values are converted to long. 
- Adds test to prevent regression
=> [smartmeter] Prevent NumberFormatException

bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyEventServlet.java, bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyBaseHandler.java, bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/manager/ShellyManagerCache.java, bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/i18n/shelly.properties
The binding checks now the local ip to be != 169.254.x.x, which is the result of a failed DHCP assignment. The framework reports this in the list of interfaces and the binding had send this to the device as part of the callback url, which resulted in device functioning in general, but the binding is not receiving any events. Now the user sees a WARNING is the log, which is a clear indicator of a setup to be fixed.
=> [shelly] Add check and ThingStatus for local IP issue (APIPA)

bundles/org.openhab.persistence.jpa/src/main/java/org/openhab/persistence/jpa/internal/JpaPersistenceService.java
in case the user manually added a UNIQUE constraint to the database, openHAB might send duplicate timestamps.
effectively this means the first attempt is kept, while others are dropped. as long as you're using sub-second timestamps, this shouldn't be an issue - the state updates truly should be duplicates
=> [jpa] Do not log failure to persist item with duplicate timestamp as error

bundles/org.openhab.binding.boschshc/src/main/resources/OH-INF/thing/thing-types.xml
wrong references were introduced during copy & paste from the previous thing type definition
=> [boschshc] fix wrong config description references

bundles/org.openhab.automation.jsscripting/pom.xml
Changelog: https://github.com/openhab/openhab-js/blob/main/CHANGELOG.md#480.
4.8.1 only contains a fix for the add-on build.
FYI @holgerfriedrich : CoreUtil actions should now be available in JS Scripting.
=> [jsscripting] Upgrade openhab-js to 4.8.1

bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/channel/KNXChannel.java, bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/channel/KNXChannelTest.java
This fixes a problem when KNX channels are linked to items that support sub-types of what the DPTs can handle in case of "-control" channels or channels with a follow profile.
More concretely: Having a Color Item linked through the follow profile to a DPT 1.001 results in `None of the configured GAs on channel 'xxx' could handle the command`, while it would be expected that `true` is sent for anything that isn't equal to the state `OFF`.
This PR makes sure that the binding tries to check if the command is a state that can be converted to a suitable subtype for the linked DPT and then sends out the according KNX telegram.
=> [knx] Correctly support state sub-types for DPTs 

bundles/org.openhab.binding.growatt/README.md, bundles/org.openhab.binding.growatt/src/main/resources/OH-INF/addon/addon.xml
Suggest the addon to be installed.
(Also fixes a formatting error in readme file).
=> [growatt] Suggest addon to be installed

bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/handler/IpCameraHandler.java, bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/onvif/OnvifConnection.java
Add better support for checking online and offline when the camera is an ONVIF type.
Changes should now allow for edge cases where an ONVIF camera has no snapshot and hence no http server to use for checking online status.
Also should allow for cameras that do not support ONVIF events, so they fall back to the proven method of opening a HTTP connecting to the configured port.
Cameras that have working ONVIF event streams will not try additional methods as the open stream proves the camera is already online.
=> [ipcamera] Improve online/offline detection for ONVIF cameras

bundles/org.openhab.transform.jinja/src/main/java/org/openhab/transform/jinja/internal/JinjaTransformationService.java, bundles/org.openhab.transform.jinja/src/test/java/org/openhab/transform/jinja/internal/JinjaTransformationServiceTest.java
Home Assistant doesn't enable strict mode, so we shouldn't either. Fixes https://github.com/Koenkk/zigbee2mqtt/issues/17395
=> [jinja] disable failOnUnknownTokens

bundles/org.openhab.transform.jinja/pom.xml
Making sure we can easily update so we can add https://github.com/HubSpot/jinjava/pull/1152 when it's merged and released.
=> [jinja] update jinjava

bundles/org.openhab.binding.mqtt.generic/src/main/resources/OH-INF/config/rollershutter-channel-config.xml
Closes #16276
This is how it mostly works already anyway. Sometimes core isn't persisting the default into the configuration, so we're getting null. I tried to infer that `null` should mean `"STOP"` (and empty string should mean `null`), but that resulted in weirdness where you could click the X next to the field in the UI to default it, but it would show empty until you saved and reloaded, at which point it would then show `STOP` again. Defaulting to null gets rid of that surprise, and brings it inline with how UP and DOWN already behave.
=> [mqtt.generic] default STOP to null for rollershutter channel

bundles/org.openhab.transform.jsonpath/pom.xml, bundles/org.openhab.transform.jsonpath/src/main/java/org/openhab/transform/jsonpath/internal/JSonPathTransformationService.java, bundles/org.openhab.transform.jsonpath/src/main/java/org/openhab/transform/jsonpath/internal/profiles/JSonPathTransformationProfile.java, bundles/org.openhab.transform.jsonpath/src/main/java/org/openhab/transform/jsonpath/internal/profiles/JSonPathTransformationProfileFactory.java, bundles/org.openhab.transform.jsonpath/src/main/resources/readme.txt, bundles/org.openhab.transform.jsonpath/src/test/java/org/openhab/transform/jsonpath/internal/JSonPathTransformationServiceTest.java
* Upgrade json-path from 2.5.0 to 2.9.0
* Cleanup code
* Fix all SAT findings
Fixes CVE-2023-1370 and CVE-2023-51074
For json-path release notes, see:
https://github.com/json-path/JsonPath/releases
=> [jsonpath] Upgrade dependencies and some cleanup

bundles/org.openhab.transform.exec/src/main/resources/readme.txt, bundles/org.openhab.transform.regex/src/main/resources/readme.txt, bundles/org.openhab.transform.xpath/src/main/resources/readme.txt, bundles/org.openhab.transform.xslt/src/main/resources/readme.txt
It's obvious and the file also ends up in the bundle JARs.
=> Remove readme.txt from transformation bundles

bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java
This PR does some small improvements to querying the RRD4jPersistenceService:
- detects the target type for the state only once, it does not change for the complete query
- uses `ZonedDateTime.plusSeconds`, it is faster than `ZonedDateTime.ofInstant` all the time ²
- fixes suppressed warnings
² when using `ZonedDateTime.ofInstant` more objects are created than calling `ZonedDateTime.plusSeconds,` e.g.:
- a new `LocatDate` is created for each call, even when it is the same date like the last call
- the `Instant.ofEpochSecond` call will create a `Instant`
- `ZoneId.systemDefault()` will clone the timezone internally
=> [rrd4j] Improve querying the RRD4jPersistenceService

bundles/org.openhab.binding.openwebnet/pom.xml, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/discovery/UsbGatewayDiscoveryService.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetBridgeHandler.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetLightingHandler.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/serial/SerialPortAdapter.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/serial/SerialPortEventAdapter.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/serial/SerialPortProviderAdapter.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/serial/SerialTransportAdapter.java
This PR uses a new version of openwebnet4j lib (0.12.0) to avoid dependency of the binding on `gnu.io`.
Version 0.12.0 of the openwebnet4j  lib defines a new `SerialPortProvider` interface to discover and interact with serial ports.
With this PR the binding now provides a `SerialPortProviderAdapter` implementation of openwebnet4j's `SerialPortProvider` based on OH Serial Transport to provide serial port access to the lib, thus making the binding independent from  `gnu.io`.
It has been tested extensively  in a real environment with the Zigbee serial-USB dongle integrated by the binding.
Related to #7573
=> [openwebnet] Replace gnu.io dependency with serial transport

bundles/org.openhab.binding.shelly/src/main/resources/scripts/oh-blu-scanner.js
Hotfix to avoid a crash on the blue gateway script when receiving unknown properties
Please consider backport to 4.1
Closing
#16370
=> [shelly] Fix blu gateway script to prevent crash

bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/InfluxDBPersistenceService.java
The label looks out of place in Blockly
Before:
After:
=> [influxdb] Standardize the label for influxdb

bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/channel/KNXChannel.java, bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/channel/KNXChannelTest.java
Related to #16337 
Types that are directly accepted are send as-is and not checked if they are a sub-type of an accepted type. This prevents `PercentType` to be converted to `DecimalType` or `QuantityType`.
=> [knx] Fix dimmer channels
