- bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java
> [rrd4j] Do not create RRD file when querying data

- bundles/org.openhab.binding.remoteopenhab/src/main/java/org/openhab/binding/remoteopenhab/internal/RemoteopenhabChannelTypeProvider.java
> [remoteopenhab] Use AbstractStorageBasedTypeProvider

- bundles/org.openhab.binding.goecharger/src/main/java/org/openhab/binding/goecharger/internal/handler/GoEChargerHandler.java
- bundles/org.openhab.binding.goecharger/src/main/java/org/openhab/binding/goecharger/internal/handler/GoEChargerV2Handler.java
Also include change from PR #14632
> [goecharger] Avoid potential NullPointerException

- bundles/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/sdm/api/PubSubAPI.java
- bundles/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/sdm/api/SDMAPI.java
- bundles/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/sdm/handler/SDMAccountHandler.java
> [nest] Remove the access token when the thing is removed

- bundles/org.openhab.voice.voicerss/src/main/resources/OH-INF/addon/addon.xml
> [voicerss] Fix service-id in addon.xml

- bundles/org.openhab.binding.vizio/README.md
Update app list URLs in README
> [vizio] Update app list URLs

- bundles/org.openhab.binding.caddx/README.md
The field name for the speed of the serial interface is baudrate and not baud. At least this is what I had to implement in OH3.4.4.
> [caddx] Update README.md

- bundles/org.openhab.binding.danfossairunit/README.md
- bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/DanfossAirUnit.java
- bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/DanfossAirUnitBindingConstants.java
- bundles/org.openhab.binding.danfossairunit/src/main/resources/OH-INF/thing/thing-types.xml
- bundles/org.openhab.binding.danfossairunit/src/main/resources/OH-INF/update/instructions.xml
- bundles/org.openhab.binding.danfossairunit/src/test/java/org/openhab/binding/danfossairunit/internal/DanfossAirUnitTest.java
Depends on openhab/openhab-core#3616
> [danfossairunit] Add UoM support for rotational speed channels

- bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/InfluxDBStateConvertUtils.java
- bundles/org.openhab.persistence.influxdb/src/test/java/org/openhab/persistence/influxdb/internal/InfluxDBStateConvertUtilsTest.java
Closes #9578
Superseded #12010
> [influxdb] support restoring unit for dimension items

- bundles/org.openhab.binding.bluetooth.airthings/src/main/resources/OH-INF/thing/airthings.xml
- bundles/org.openhab.binding.bluetooth.airthings/src/main/resources/OH-INF/update/update.xml
> [airthings] Fix thing types

- pom.xml
Related to https://github.com/openhab/openhab-distro/issues/1540
> Update to SAT version 0.15.0

- bundles/org.openhab.io.homekit/src/main/resources/OH-INF/addon/addon.xml
- bundles/org.openhab.io.hueemulation/src/main/resources/OH-INF/addon/addon.xml
- bundles/org.openhab.io.metrics/src/main/resources/OH-INF/addon/addon.xml
- bundles/org.openhab.io.neeo/src/main/resources/OH-INF/addon/addon.xml
- bundles/org.openhab.io.openhabcloud/src/main/resources/OH-INF/addon/addon.xml
- bundles/org.openhab.persistence.dynamodb/src/main/resources/OH-INF/addon/addon.xml
- bundles/org.openhab.persistence.influxdb/src/main/resources/OH-INF/addon/addon.xml
- bundles/org.openhab.persistence.jpa/src/main/resources/OH-INF/addon/addon.xml
- bundles/org.openhab.persistence.mapdb/src/main/resources/OH-INF/addon/addon.xml
- bundles/org.openhab.persistence.mongodb/src/main/resources/OH-INF/addon/addon.xml
- bundles/org.openhab.persistence.rrd4j/src/main/resources/OH-INF/addon/addon.xml
- bundles/org.openhab.transform.bin2json/src/main/resources/OH-INF/addon/addon.xml
- bundles/org.openhab.transform.exec/src/main/resources/OH-INF/addon/addon.xml
- bundles/org.openhab.transform.jinja/src/main/resources/OH-INF/addon/addon.xml
- bundles/org.openhab.transform.jsonpath/src/main/resources/OH-INF/addon/addon.xml
- bundles/org.openhab.transform.map/src/main/resources/OH-INF/addon/addon.xml
- bundles/org.openhab.transform.regex/src/main/resources/OH-INF/addon/addon.xml
- bundles/org.openhab.transform.rollershutterposition/src/main/resources/OH-INF/addon/addon.xml
- bundles/org.openhab.transform.scale/src/main/resources/OH-INF/addon/addon.xml
- bundles/org.openhab.transform.xpath/src/main/resources/OH-INF/addon/addon.xml
- bundles/org.openhab.transform.xslt/src/main/resources/OH-INF/addon/addon.xml
- bundles/org.openhab.voice.actiontemplatehli/src/main/resources/OH-INF/addon/addon.xml
- bundles/org.openhab.voice.mactts/src/main/resources/OH-INF/addon/addon.xml
- bundles/org.openhab.voice.marytts/src/main/resources/OH-INF/addon/addon.xml
- bundles/org.openhab.voice.picotts/src/main/resources/OH-INF/addon/addon.xml
- bundles/org.openhab.voice.porcupineks/src/main/resources/OH-INF/addon/addon.xml
- bundles/org.openhab.voice.rustpotterks/src/main/resources/OH-INF/addon/addon.xml
- bundles/org.openhab.voice.voskstt/src/main/resources/OH-INF/addon/addon.xml
For those addons the new attribute "connection" has not yet been declared.
Fixes #14885.
See https://next.openhab.org/docs/developer/addons/addon.html#xml-structure-for-add-on-definitions
for further information on the attribute.
This patch does not include io.imperihome, as I have opened a PR to remove it from the repo.
> Declare missing connection attribute

- bundles/org.openhab.binding.oceanic/pom.xml
- bundles/org.openhab.binding.oceanic/src/main/java/org/openhab/binding/oceanic/internal/OceanicHandlerFactory.java
- bundles/org.openhab.binding.oceanic/src/main/java/org/openhab/binding/oceanic/internal/handler/NetworkOceanicThingHandler.java
- bundles/org.openhab.binding.oceanic/src/main/java/org/openhab/binding/oceanic/internal/handler/SerialOceanicThingHandler.java
> [Oceanic] Remove dependency on RXTX for serial communication

- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/DeviceThingHandler.java
Fixes #15065 
@holgerfriedrich WDYT?
> [knx] dynamic channel-types

- bundles/org.openhab.binding.vesync/README.md
[veSync] Corrected Readme channel definitions
- Removal of timer left channel in documentations but non-existent. The correct channel is already present in the documentation named: timerExpiry
- Minor syntax corrections - alignment in Readme, and missing double-quote at end of line.
Signed-off-by: David Goodyear <david.goodyear@gmail.com>
> [vesync] Update README.md

- bundles/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/handler/ADThingHandler.java
- bundles/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/protocol/KeypadMessage.java
- bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/WebSocketConnection.java
- bundles/org.openhab.binding.bluetooth.radoneye/src/main/java/org/openhab/binding/bluetooth/radoneye/internal/RadoneyeDiscoveryParticipant.java
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/grxprg/GrafikEyeHandler.java
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/grxprg/PrgBridgeHandler.java
- bundles/org.openhab.binding.miio/README.base.md
- bundles/org.openhab.binding.miio/README.md
- bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/discovery/SunspecDiscoveryProcess.java
- bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/handler/AbstractSunSpecHandler.java
- bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/parser/CommonModelParser.java
- bundles/org.openhab.binding.netatmo/README.md
- bundles/org.openhab.binding.qbus/src/main/java/org/openhab/binding/qbus/internal/protocol/QbusMessageDeserializer.java
- bundles/org.openhab.binding.sensorcommunity/src/main/java/org/openhab/binding/sensorcommunity/internal/handler/HTTPHandler.java
- bundles/org.openhab.binding.sensorcommunity/src/main/java/org/openhab/binding/sensorcommunity/internal/utils/DateTimeUtils.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiClient.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/discovery/ShellyDiscoveryParticipant.java
- bundles/org.openhab.binding.solarwatt/README.md
- bundles/org.openhab.binding.sonnen/src/main/java/org/openhab/binding/sonnen/internal/SonnenHandler.java
- bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/schema/ApiPageParser.java
- bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/schema/ChangerX2Parser.java
- bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/constants/TapoErrorCode.java
- bundles/org.openhab.binding.wundergroundupdatereceiver/src/test/java/org/openhab/binding/wundergroundupdatereceiver/internal/WundergroundUpdateReceiverDiscoveryServiceTest.java
- itests/org.openhab.binding.modbus.tests/src/main/java/org/openhab/binding/modbus/tests/ModbusPollerThingHandlerTest.java
> Reduce SAT warnings

- bundles/org.openhab.binding.radiothermostat/README.md
Minor README edit; no code changes.
> [radiothermostat] Add MyRadioThermostat/EnergyHub cloud removal note

- bundles/org.openhab.binding.boschindego/README.md
- bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/DeviceStatus.java
- bundles/org.openhab.binding.boschindego/src/main/resources/OH-INF/i18n/boschindego.properties
- bundles/org.openhab.binding.boschindego/src/main/resources/OH-INF/thing/thing-types.xml
[boschindego] Add 'Mowing randomly' state code 524
When choosing "Mow without Dock" on the Indego, status switches to 524. This is indicated in the mobile app as "Mowing randomly".
> [boschindego] Add support for random mowing status code

- bundles/org.openhab.binding.velux/README.md
- bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/VeluxBindingConstants.java
- bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/handler/VeluxBridgeHandler.java
> [velux] Fix limit minimum bug

- bundles/org.openhab.binding.androidtv/src/main/java/org/openhab/binding/androidtv/internal/protocol/shieldtv/ShieldTVMessageParser.java
Resolves remaining 4 EmptyControlStatement SAT alerts on the build.
> [androidtv] Resolves EmptyControlStatement SAT alerts

- bundles/org.openhab.voice.mactts/README.md
- bundles/org.openhab.voice.mactts/src/main/java/org/openhab/voice/mactts/internal/MacTTSAudioStream.java
- bundles/org.openhab.voice.mactts/src/main/java/org/openhab/voice/mactts/internal/MacTTSService.java
- bundles/org.openhab.voice.mactts/src/test/java/org/openhab/voice/mactts/internal/TTSServiceMacOSTest.java
> [mactts] Add LRU cache

- bundles/org.openhab.binding.avmfritz/src/main/resources/OH-INF/thing/thing-types.xml
- bundles/org.openhab.binding.avmfritz/src/main/resources/OH-INF/update/instructions.xml
> [avmfritz] Fix wrong system channel types

- bundles/org.openhab.binding.modbus.helioseasycontrols/README.md
Updated README.md to reflect additionally required "unit" declarations.
Fixed broken links in markdown.
> [modbus.helioseasycontrols] Updated README.md (UoM, fixed links)

- bundles/org.openhab.binding.doorbird/src/main/java/org/openhab/binding/doorbird/internal/audio/DoorbirdAudioSink.java
Following some rewrite with openhab/openhab-core#3461
Support for more audio streams
Proper use of the new synchronous base class.
> [doorbird] Support for more audio streams

- bundles/org.openhab.voice.picotts/README.md
- bundles/org.openhab.voice.picotts/src/main/java/org/openhab/voice/picotts/internal/PicoTTSAudioStream.java
- bundles/org.openhab.voice.picotts/src/main/java/org/openhab/voice/picotts/internal/PicoTTSService.java
This pull request make use of the [new TTS LRU cache](https://github.com/openhab/openhab-core/pull/3057) by applying it to the Pico TTS service.
> [picotts] Add LRU cache

- bundles/org.openhab.binding.energidataservice/README.md
> [energidataservice] Fix documentation of history/cache

- bundles/org.openhab.automation.jsscripting/pom.xml
For changelog see https://github.com/openhab/openhab-js/blob/v4.5.0/CHANGELOG.md#450.
> [jsscripting] Upgrade openhab-js to 4.5.0

- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/HomeData.java
> [Netatmo] Binding doesn't work if no persons are defined

- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/data/EventType.java
I identified a previously unexperiment event type received by webhook : 
```
2023-07-07 04:57:37.203 [WARN ] [serialization.NAPushTypeDeserializer] - Unknown module or event type : NACamera-siren_tampered, deserialized to 'WELCOME-unknown'
2023-07-07 04:57:37.230 [WARN ] [serialization.NAPushTypeDeserializer] - Unknown module or event type : NACamera-siren_tampered, deserialized to 'WELCOME-unknown'
```
> [netatmo] Add siren_tampered notification

- bundles/org.openhab.binding.heos/src/main/java/org/openhab/binding/heos/internal/api/HeosAudioSink.java
> [heos] Support for more audio streams through the HTTP audio servlet

- bundles/org.openhab.voice.marytts/README.md
- bundles/org.openhab.voice.marytts/src/main/java/org/openhab/voice/marytts/internal/MaryTTSService.java
Relates to openhab/openhab-addons#15110
> [marytts] Add LRU cache

- bundles/org.openhab.binding.androidtv/src/main/java/org/openhab/binding/androidtv/internal/protocol/shieldtv/ShieldTVMessageParser.java
Adds additional checks to the parser to prevent exception when information is missing.
Resolves #15163
> [androidtv] Adds additional checks for parser

- bundles/org.openhab.binding.mynice/README.md
- bundles/org.openhab.binding.mynice/src/main/java/org/openhab/binding/mynice/internal/MyNiceBindingConstants.java
- bundles/org.openhab.binding.mynice/src/main/java/org/openhab/binding/mynice/internal/MyNiceHandlerFactory.java
- bundles/org.openhab.binding.mynice/src/main/java/org/openhab/binding/mynice/internal/config/CourtesyConfiguration.java
- bundles/org.openhab.binding.mynice/src/main/java/org/openhab/binding/mynice/internal/discovery/MyNiceDiscoveryService.java
- bundles/org.openhab.binding.mynice/src/main/java/org/openhab/binding/mynice/internal/handler/GateHandler.java
- bundles/org.openhab.binding.mynice/src/main/java/org/openhab/binding/mynice/internal/handler/It4WifiConnector.java
- bundles/org.openhab.binding.mynice/src/main/java/org/openhab/binding/mynice/internal/handler/It4WifiHandler.java
- bundles/org.openhab.binding.mynice/src/main/java/org/openhab/binding/mynice/internal/xml/dto/Properties.java
- bundles/org.openhab.binding.mynice/src/main/java/org/openhab/binding/mynice/internal/xml/dto/T4Command.java
- bundles/org.openhab.binding.mynice/src/main/resources/OH-INF/i18n/mynice.properties
- bundles/org.openhab.binding.mynice/src/main/resources/OH-INF/thing/thing-types.xml
- bundles/org.openhab.binding.mynice/src/main/resources/OH-INF/update/instructions.xml
Gate status channel is now R/W, accepting StopMoveType commands.
Courtesy light channel added.
Also resolves #14795
> [MyNice] Addition of Courtesy Light Channel

- CODEOWNERS
Related to:
* https://github.com/openhab/openhab-addons/pull/11958
* https://github.com/openhab/openhab-addons/pull/13315
* https://github.com/openhab/openhab-addons/pull/13815
* https://github.com/openhab/openhab-addons/pull/14499
* https://github.com/openhab/openhab-addons/pull/15063
> Add missing CODEOWNERS

- bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/handler/ZonePlayerHandler.java
- bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/channels.xml
Adds DTS Surround 5.1 for codec ID 8494721.
> [sonos] Add DTS Surround 5.1

- bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/api/DatahubTariffFilterFactory.java
> [energidataservice] Update tariff filter for Nord Energi Net

- bundles/org.openhab.binding.openwebnet/README.md
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/i18n/openwebnet.properties
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusAlarmZone.xml
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusAutomation.xml
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusAux.xml
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusBasicScenarioControl.xml
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusCENPlusScenarioControl.xml
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusCENScenarioControl.xml
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusDimmer.xml
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusDryContactIR.xml
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusEnergyMeter.xml
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusOnOffSwitch.xml
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusThermoCentralUnit.xml
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusThermoSensor.xml
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusThermoZone.xml
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/ZBAutomation.xml
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/ZBDimmer.xml
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/ZBOnOffSwitch.xml
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/ZBOnOffSwitch2Units.xml
- bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/channels.xml
Updated: README, `where` parameter description for Things and channels descriptions. Added `AUTO` option for mode channel-type.
Added `OFF` option for speedFanCoil channel-type.
Updated default translations.
> [openwebnet] Binding documentation update for OH4 release

- bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/api/rest/HomeManager.java
- bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/AbstractHomeAssistantTests.java
- pom.xml
This version still checks test files.
See: openhab/openhab-core#3515
> Use Eclipse formatter 4.25 with Spotless

- bundles/org.openhab.binding.avmfritz/src/main/resources/OH-INF/thing/bridge-types.xml
- bundles/org.openhab.binding.avmfritz/src/main/resources/OH-INF/thing/thing-types.xml
> [avmfritz] Fix update instructions

- bundles/org.openhab.io.openhabcloud/pom.xml
- bundles/org.openhab.io.openhabcloud/src/main/feature/feature.xml
> [openhabcloud] Updates JSON Library.

- bundles/org.openhab.transform.vat/README.md
Add JavaScript example as well in the documentation to avoid doubts about syntax etc.
> [transform.vat] Provide example in JavaScript

- bundles/org.openhab.transform.jsonpath/src/main/java/org/openhab/transform/jsonpath/internal/JSonPathTransformationService.java
Related to https://github.com/openhab/openhab-addons/issues/15282
> [jsonpath] Fix exception when input string is empty

- bundles/org.openhab.automation.jsscripting/src/main/resources/node_modules/@jsscripting-globals.js
Regression from #15193.
Reported on the community, see https://community.openhab.org/t/openhab-4-0-release-discussion/147957/53?u=florian-h05.
> [jsscripting] Fix timerId not returned by JS timer methods

- bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/api/rest/FreeplugManager.java
- bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/FreeplugHandler.java
Correcting two false assumptions : 
* -1 rate does not means it does not exist, but was not measurable (ref in code)
* The Coordinator is not always the one linked to the freebox server
> [freeboxos] Enhance freeplug data interpretation

- bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/BluetoothUtils.java
Fixes #15313
Partially reverts #13967
> [bluetooth] Fix `ArrayStoreException`

- bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/lib/serverconnection/impl/HttpTransportImpl.java
This fixes #15318 and keeps removal of StringUtils which was introduced by https://github.com/openhab/openhab-addons/pull/14402
Tested successfully on my environment.
@jlaur @lsiepel Please check and approve
> [digitalstrom] Fix StringIndexOutOfBoundsException (#15318) retaining #14402

- bundles/org.openhab.binding.dscalarm/README.md
Removed quotes from the <shieldGreen> statement to make it work with OH4.
> [dscalarm] Fix icon reference in documentation example

- bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/handler/ZonePlayerHandler.java
Fixes typo in codec ID from #15238 
@lolodomo
> [sonos] Fixes DTS Typo

- bundles/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromecastCommander.java
Fixes: https://github.com/openhab/openhab-addons/issues/14516
Split from #14159 that already had a review from @jlaur
> [chromecast] Fix STOP command

- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/connection/Clip2Bridge.java
> [hue] Fix bug due to parallel PUT commands

- bundles/org.openhab.automation.jsscripting/README.md
- bundles/org.openhab.binding.exec/README.md
- bundles/org.openhab.binding.logreader/README.md
- bundles/org.openhab.binding.mqtt.generic/README.md
- bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/internal/ssl/PinTrustManager.java
- bundles/org.openhab.binding.mqtt/xtend_examples.md
- bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/PresenceDetection.java
- bundles/org.openhab.binding.ntp/README.md
- bundles/org.openhab.binding.telegram/README.md
- bundles/org.openhab.io.metrics/README.md
- bundles/org.openhab.transform.map/README.md
- bundles/org.openhab.transform.regex/README.md
This prevents issues because older documentation may not apply to Java 17.
> Link to Java 17 documentation

- bundles/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/GardenaSmartImpl.java
- bundles/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/GardenaSmartWebSocket.java
- bundles/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/discovery/GardenaDeviceDiscoveryService.java
- bundles/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/handler/GardenaAccountHandler.java
- bundles/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/handler/GardenaThingHandler.java
- bundles/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/model/dto/Device.java
- Fixes #15039 
- Some small checkstyle/java17 improvements
Jar 4.1.0 is here:  https://1drv.ms/u/s!AnMcxmvEeupwjrMrdauw9Dg2U6hGtw?e=X7nDUY
> [gardena] Fix close all valves command

- bundles/org.openhab.binding.volumio/src/main/java/org/openhab/binding/volumio/internal/VolumioHandler.java
Removing compiler warnings
Fixes #15380
> [volumio] Removing compiler warnings

- bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/DSCAlarmMessage.java
- bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/factory/DSCAlarmHandlerFactory.java
- bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/handler/DSCAlarmBaseBridgeHandler.java
- bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/handler/DSCAlarmBaseThingHandler.java
- bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/handler/PartitionThingHandler.java
Fixes mainly some checkstyle EqualsAvoidNullCheck and a compiler warning
> [dscalarm] Fix checkstyle and warning

- bundles/org.openhab.binding.bluetooth.daikinmadoka/NOTICE
- bundles/org.openhab.binding.homeconnect/NOTICE
- bundles/org.openhab.binding.plugwiseha/NOTICE
- bundles/org.openhab.binding.tr064/NOTICE
- bundles/org.openhab.voice.rustpotterks/NOTICE
This makes it easier to find the source code of these add-ons when reading these NOTICE files.
> Fix wrong source code URLs in NOTICE files

- bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/JRubyScriptEngineFactory.java
- bundles/org.openhab.automation.jrubyscripting/src/main/resources/OH-INF/config/config.xml
This is to match the uri defined in https://github.com/openhab/openhab-addons/pull/15438
Please also apply this to 4.0.x
> [jrubyscripting] Fix config description uri

- bundles/org.openhab.binding.chatgpt/src/main/java/org/openhab/binding/chatgpt/internal/ChatGPTChannelConfiguration.java
- bundles/org.openhab.binding.chatgpt/src/main/java/org/openhab/binding/chatgpt/internal/ChatGPTHandler.java
Withhout this patch, creating a new channel in the UI without changing the default values for model, temperature, or maxtokens, the values are not stored to the json db.
Added a trace logging for the requests sent to chatgpt. Without this ends up with an invalid query starting with 
``` {"temperature":0.0,"model":"","max_tokens":0,"```...
> [chatgpt] Set proper default values for channel configuration

- bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/OpenUVIconProvider.java
- bundles/org.openhab.binding.openuv/src/main/resources/icon/uv-index-0.svg
Resolves #15464.
Avoids loading an icon that does not exist.
Adds UV 0 icon.
> [openuv] Correcting NPE in IconProvider

- bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/MyNettyAuthHandler.java
- bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/onvif/OnvifConnection.java
- bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/kostalinverter/internal/thirdgeneration/ThirdGenerationEncryptionHelper.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/cloud/CloudUtil.java
- bundles/org.openhab.binding.millheat/src/main/java/org/openhab/binding/millheat/internal/handler/MillheatAccountHandler.java
- bundles/org.openhab.binding.mybmw/src/main/java/org/openhab/binding/mybmw/internal/utils/Converter.java
- bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/protocol/Ethm1Module.java
Make sure that SecureRadom is used whenever the random number is used for cryptographic operations, e.g. as nonce/salt.
> Use SecureRandom instead of Random

- bundles/org.openhab.binding.fineoffsetweatherstation/src/test/java/org/openhab/binding/fineoffsetweatherstation/internal/service/FineOffsetDataParserTest.java
[CI build](https://ci.openhab.org/job/openHAB-Addons/1158/org.openhab.addons.bundles$org.openhab.binding.fineoffsetweatherstation/testReport/junit/org.openhab.binding.fineoffsetweatherstation.internal.service/FineOffsetDataParserTest/testRainDataW90/) has been failing with this error:
```
java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
```
> [fineoffsetweatherstation] Fix failing tests

- itests/org.openhab.automation.groovyscripting.tests/itest.bndrun
- itests/org.openhab.binding.nest.tests/itest.bndrun
- pom.xml
Related to openhab/openhab-core#3768
> Update Jackson to 2.15.2

- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/config/HueBridgeConfig.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/connection/HueBridge.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/discovery/BridgeJsonParameters.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/discovery/HueBridgeNupnpDiscovery.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/discovery/HueBridgeUPNPDiscoveryParticipant.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/dto/ApiVersion.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/dto/Config.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/dto/FullConfig.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/dto/FullGroup.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/dto/FullHueObject.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/dto/Scene.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/dto/SearchForLightsRequest.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/dto/SetAttributesRequest.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueBridgeHandler.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueGroupHandler.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueStateDescriptionProvider.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/LightStateConverter.java
- bundles/org.openhab.binding.hue/src/test/java/org/openhab/binding/hue/internal/SceneTest.java
- itests/org.openhab.binding.hue.tests/src/main/java/org/openhab/binding/hue/internal/AbstractHueOSGiTestParent.java
- itests/org.openhab.binding.hue.tests/src/main/java/org/openhab/binding/hue/internal/HueDeviceDiscoveryServiceOSGiTest.java
- itests/org.openhab.binding.hue.tests/src/main/java/org/openhab/binding/hue/internal/discovery/HueBridgeNupnpDiscoveryOSGITest.java
- itests/org.openhab.binding.hue.tests/src/main/java/org/openhab/binding/hue/internal/handler/HueBridgeHandlerOSGiTest.java
Fix all compiler warnings and one checkstyle warning.
> [hue] Fix compiler warnings

- bundles/org.openhab.binding.surepetcare/src/main/java/org/openhab/binding/surepetcare/internal/SurePetcareAPIHelper.java
- bundles/org.openhab.binding.surepetcare/src/main/java/org/openhab/binding/surepetcare/internal/SurePetcareConstants.java
- bundles/org.openhab.binding.surepetcare/src/main/java/org/openhab/binding/surepetcare/internal/discovery/SurePetcareDiscoveryService.java
- bundles/org.openhab.binding.surepetcare/src/main/java/org/openhab/binding/surepetcare/internal/handler/SurePetcareBridgeHandler.java
- bundles/org.openhab.binding.surepetcare/src/main/java/org/openhab/binding/surepetcare/internal/handler/SurePetcareDeviceHandler.java
- bundles/org.openhab.binding.surepetcare/src/main/java/org/openhab/binding/surepetcare/internal/handler/SurePetcarePetHandler.java
- Resolves https://github.com/openhab/openhab-addons/issues/11527
- Minor java17 improvements
Test jar is here: 4.1.0: https://1drv.ms/u/s!AnMcxmvEeupwjrMwEoS1zTCIf2zmxQ?e=9dOG5d
> [surepetcare] Fix possible timeout bug

- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitTelevisionSpeakerImpl.java
- bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/NetworkUtils.java
- bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/rest/ConfigurationAccess.java
- bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/rest/Scenes.java
- bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/rest/UserManagement.java
- bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/rest/CommonSetup.java
- bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/rest/ItemUIDtoHueIDMappingTests.java
- bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/rest/ScheduleTests.java
- bundles/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/NeeoService.java
- bundles/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/internal/NeeoItemValueConverter.java
- bundles/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/internal/serialization/NeeoBrainDeviceSerializer.java
- bundles/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/internal/serialization/NeeoDeviceChannelSerializer.java
- bundles/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/internal/servletservices/NeeoBrainService.java
- bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudClient.java
- bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudService.java
- bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/actions/NotificationModuleHandlerFactory.java
- Use instanceof matching and multiline strings.
- Use Map/Set/List.of instead of Collections.
Similar to what we did in core a few month ago. Note that this breaks compatibilty to Java 11.
> [io] Use Java 17 features

- bundles/org.openhab.voice.picotts/src/main/java/org/openhab/voice/picotts/internal/PicoTTSService.java
Use Map/Set/List.of instead of Collections.
> [voice] Use Java 17 features

- bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/RuleUtils.java
- bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/automation/HueRuleConditionHandler.java
- bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/dto/AbstractHueState.java
- bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/dto/HueAuthorizedConfig.java
- bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/dto/HueDataStore.java
- bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/dto/HueGroupEntry.java
- bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/dto/HueLightEntry.java
- bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/dto/HueRuleEntry.java
- bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/dto/HueSceneEntry.java
- bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/dto/HueStateColorBulb.java
- bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/rest/Rules.java
- bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/rest/Scenes.java
- bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/rest/Schedules.java
- bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/rest/StatusResource.java
- bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/rest/UserManagement.java
- bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/upnp/UpnpServer.java
- add missing @override
- Java style array syntax
- remove redundant modifiers
- always move String constants to left side in comparisons
- simplify lambda expressions and return statements
> [hueemulation] Java 17 features

- bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/fs/watch/JSDependencyTracker.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitCommandExtension.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitTaggedItem.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/AbstractHomekitAccessoryImpl.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/BooleanItemReader.java
- bundles/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/internal/models/NeeoDirectoryResult.java
- bundles/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/internal/serialization/NeeoDeviceChannelSerializer.java
- bundles/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/internal/servletservices/BrainDashboardService.java
- bundles/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/internal/servletservices/NeeoBrainSearchService.java
- bundles/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/internal/servletservices/NeeoBrainService.java
- bundles/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/internal/servletservices/ThingDashboardService.java
- bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudClient.java
- bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudService.java
- bundles/org.openhab.persistence.dynamodb/src/main/java/org/openhab/persistence/dynamodb/internal/AbstractDynamoDBItem.java
- bundles/org.openhab.persistence.dynamodb/src/main/java/org/openhab/persistence/dynamodb/internal/DynamoDBPersistenceService.java
- bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcBaseDAO.java
- bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/utils/StringUtilsExt.java
- bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java
- bundles/org.openhab.transform.regex/src/main/java/org/openhab/transform/regex/internal/RegExTransformationService.java
- bundles/org.openhab.transform.scale/src/main/java/org/openhab/transform/scale/internal/ScaleTransformationService.java
- bundles/org.openhab.voice.actiontemplatehli/src/main/java/org/openhab/voice/actiontemplatehli/internal/ActionTemplateInterpreter.java
- bundles/org.openhab.voice.picotts/src/main/java/org/openhab/voice/picotts/internal/PicoTTSService.java
- bundles/org.openhab.voice.pollytts/src/main/java/org/openhab/voice/pollytts/internal/PollyTTSService.java
- bundles/org.openhab.voice.porcupineks/src/main/java/org/openhab/voice/porcupineks/internal/PorcupineKSService.java
- bundles/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/tool/CreateTTSCache.java
- bundles/org.openhab.voice.voskstt/src/main/java/org/openhab/voice/voskstt/internal/VoskSTTService.java
- add missing @override
- Java style array syntax
- remove redundant modifiers
- always move String constants to left side in comparisons
- simplify lambda expressions and return statements
- use replace instead of replaceAll w/o regex
> Java 17 features

- bundles/org.openhab.persistence.dynamodb/src/main/java/org/openhab/persistence/dynamodb/internal/AbstractDynamoDBItem.java
- bundles/org.openhab.persistence.dynamodb/src/main/java/org/openhab/persistence/dynamodb/internal/DynamoDBConfig.java
- bundles/org.openhab.persistence.dynamodb/src/main/java/org/openhab/persistence/dynamodb/internal/DynamoDBPersistenceService.java
- bundles/org.openhab.persistence.dynamodb/src/test/java/org/openhab/persistence/dynamodb/internal/AbstractDynamoDBItemSerializationTest.java
- bundles/org.openhab.persistence.dynamodb/src/test/java/org/openhab/persistence/dynamodb/internal/DynamoDBConfigTest.java
- bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/InfluxDBStateConvertUtils.java
- bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/influx1/InfluxDB1RepositoryImpl.java
- bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/influx2/InfluxDB2RepositoryImpl.java
- bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/console/JdbcCommandExtension.java
- bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcBaseDAO.java
- bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcDerbyDAO.java
- bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcHsqldbDAO.java
- bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcPostgresqlDAO.java
- bundles/org.openhab.persistence.jpa/src/main/java/org/openhab/persistence/jpa/internal/StateHelper.java
- bundles/org.openhab.persistence.mapdb/src/main/java/org/openhab/persistence/mapdb/internal/MapDbPersistenceService.java
- bundles/org.openhab.persistence.mongodb/src/main/java/org/openhab/persistence/mongodb/internal/MongoDBPersistenceService.java
- bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java
- bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/charts/RRD4jChartServlet.java
- bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/console/RRD4jCommandExtension.java
- Use instanceof matching and multiline strings.
- Use Map/Set/List.of instead of Collections.
Similar to what we did in core a few month ago. Note that this breaks compatibilty to Java 11.
> [persistence] Use Java 17 features

- bundles/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/discovery/ZoneDiscoveryService.java
- bundles/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/handler/YamahaBridgeHandler.java
- bundles/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/handler/YamahaZoneThingHandler.java
- bundles/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/protocol/InputConverter.java
- bundles/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/protocol/xml/DeviceInformationXML.java
- bundles/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/protocol/xml/InputConverterXML.java
- bundles/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/protocol/xml/InputWithNavigationControlXML.java
- bundles/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/protocol/xml/InputWithPlayControlXML.java
- bundles/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/protocol/xml/InputWithPresetControlXML.java
- bundles/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/protocol/xml/XMLUtils.java
- Partial fixes #7667
- Java 17 instanceof
- Some (not all) checkstyle
> [yamahareceiver] Show correct status detail on failure

- bundles/org.openhab.binding.haywardomnilogic/src/main/java/org/openhab/binding/haywardomnilogic/internal/handler/HaywardPumpHandler.java
pumpHandler was missing a case break statement
> [haywardomnilogic] Fix sending command to channel pumpSpeedPercent

- .github/workflows/ci-build.yml
- bundles/pom.xml
- features/openhab-addons/pom.xml
- itests/pom.xml
- pom.xml
* Use Maven 3.9.4 with GitHub Actions CI
* Upgrade Maven plug-ins
> Upgrade Maven and plug-ins

- itests/org.openhab.automation.groovyscripting.tests/itest.bndrun
- itests/org.openhab.automation.jsscriptingnashorn.tests/itest.bndrun
- itests/org.openhab.binding.astro.tests/itest.bndrun
- itests/org.openhab.binding.avmfritz.tests/itest.bndrun
- itests/org.openhab.binding.feed.tests/itest.bndrun
- itests/org.openhab.binding.hue.tests/itest.bndrun
- itests/org.openhab.binding.max.tests/itest.bndrun
- itests/org.openhab.binding.mielecloud.tests/itest.bndrun
- itests/org.openhab.binding.modbus.tests/itest.bndrun
- itests/org.openhab.binding.mqtt.homeassistant.tests/itest.bndrun
- itests/org.openhab.binding.mqtt.homie.tests/itest.bndrun
- itests/org.openhab.binding.mqtt.ruuvigateway.tests/itest.bndrun
- itests/org.openhab.binding.nest.tests/itest.bndrun
- itests/org.openhab.binding.ntp.tests/itest.bndrun
- itests/org.openhab.binding.systeminfo.tests/itest.bndrun
- itests/org.openhab.binding.tradfri.tests/itest.bndrun
- itests/org.openhab.binding.wemo.tests/itest.bndrun
- itests/org.openhab.persistence.mapdb.tests/itest.bndrun
Related to openhab/openhab-core#3790
> Resolve runbundles for directory-watcher upgrade

- bundles/org.openhab.binding.systeminfo/README.md
as the text above does suggest so.
> [systeminfo] Use DataAmount for dataSent and dataReceived in the example

- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/data/EventSubType.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/data/EventType.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/Event.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/WebhookEvent.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/deserialization/NAPushType.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/deserialization/NAPushTypeDeserializer.java
I identified two events sent through the webhook related to : 
* Manual action on the thermostat
* Alarm triggered on a weather station device
These new events implied a change of type for the subType identifier because they hold string values.
Discovering these new webhook events (that was restricted to Security) makes me think that webhook handling will need a complete revamp in the future for better handling of various cases but at least now, they are recognized.
> [netatmo] Handle new event types

- CODEOWNERS
> [jrubyscripting] @boc-tothefuture is no longer a maintainer

- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/data/ModuleType.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/Capability.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/providers/NetatmoThingTypeProvider.java
> [netatmo] Adding "thingTypeVersion" property at thing creation

- bundles/org.openhab.binding.icalendar/src/main/java/org/openhab/binding/icalendar/internal/handler/PullJob.java
- bundles/org.openhab.voice.mactts/src/main/java/org/openhab/voice/mactts/internal/MacTTSAudioStream.java
- bundles/org.openhab.voice.picotts/src/main/java/org/openhab/voice/picotts/internal/PicoTTSAudioStream.java
Use function from nio package as it uses more restrictive file permissions.
> Migrate to java.nio.file.createTempFile

- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/SomfyTahomaBindingConstants.java
- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaBridgeHandler.java
This PR addresses one of the biggest pains of this binding - too many requests error (cloud throtting problem introduced by changes in Tahoma cloud).
Moreover it fixes another problem with local communication when the local gateway IP changes.
> [somfytahoma] Improvements to avoid cloud login throttling

- bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/InfluxDBStateConvertUtils.java
- bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/influx1/InfluxDB1RepositoryImpl.java
- bundles/org.openhab.persistence.influxdb/src/test/java/org/openhab/persistence/influxdb/internal/InfluxDBStateConvertUtilsTest.java
Fix #15443 
Type conversion issues reported in https://community.openhab.org/t/openhab-4-0-1-unstable/148569
> [influxdb] Fix exception handling and improve some type conversions

- bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/dpt/DPTTest.java
Currently PR build is broken due to KNX tests.
For now disable broken tests due to openhab/openhab-core#3792.
*Allows PR builds to complete again* but does not yet fix the issue.
See #15567
> [knx] Disable tests failing due to QuantityType change in core

- bundles/org.openhab.binding.juicenet/README.md
- bundles/org.openhab.binding.juicenet/src/main/java/org/openhab/binding/juicenet/internal/api/JuiceNetApi.java
- bundles/org.openhab.binding.juicenet/src/main/java/org/openhab/binding/juicenet/internal/handler/JuiceNetDeviceHandler.java
Changing a charging state through the Juicenet API is considered an override, the correct time must be supplied for the override to go into effect. Once the state is set, it is overridden. The override can be removed by setting the override time to zero. Setting the charging state to something new just changes the override (it's possible to override smart charging with different smart charging)
Per #15564 there are two problems, the setOverride() method used to control the override and set the state is broken due to a typo. Second, while the API supports removing an API, the binding lacks that function.
This pull request fixes the typo and adds the ability to remove the override.
> [Juicenet] Fix Charging state controls and override functionality

- itests/org.openhab.binding.astro.tests/src/main/java/org/openhab/binding/astro/handler/test/AstroCommandTest.java
- itests/org.openhab.binding.astro.tests/src/main/java/org/openhab/binding/astro/handler/test/AstroValidConfigurationTest.java
- itests/org.openhab.binding.astro.tests/src/main/java/org/openhab/binding/astro/test/AstroStateTest.java
- itests/org.openhab.binding.astro.tests/src/main/java/org/openhab/binding/astro/test/cases/AstroBindingTestsData.java
- itests/org.openhab.binding.mielecloud.tests/src/main/java/org/openhab/binding/mielecloud/internal/config/ConfigFlowTest.java
- itests/org.openhab.binding.mielecloud.tests/src/main/java/org/openhab/binding/mielecloud/internal/handler/AbstractMieleThingHandlerTest.java
- itests/org.openhab.binding.mielecloud.tests/src/main/java/org/openhab/binding/mielecloud/internal/handler/MieleHandlerFactoryTest.java
- itests/org.openhab.binding.mielecloud.tests/src/main/java/org/openhab/binding/mielecloud/internal/util/OpenHabOsgiTest.java
- itests/org.openhab.binding.modbus.tests/src/main/java/org/openhab/binding/modbus/tests/AbstractModbusOSGiTest.java
- itests/org.openhab.binding.mqtt.homeassistant.tests/src/main/java/org/openhab/binding/mqtt/homeassistant/DiscoverComponentsTest.java
- itests/org.openhab.binding.mqtt.homeassistant.tests/src/main/java/org/openhab/binding/mqtt/homeassistant/HomeAssistantMQTTImplementationTest.java
- itests/org.openhab.binding.mqtt.ruuvigateway.tests/src/main/java/org/openhab/binding/mqtt/ruuvigateway/RuuviGatewayTest.java
- itests/org.openhab.binding.mqtt.ruuvigateway.tests/src/main/java/org/openhab/binding/mqtt/ruuvigateway/ThingStatusInfoChangedSubscriber.java
- itests/org.openhab.binding.ntp.tests/src/main/java/org/openhab/binding/ntp/test/NtpOSGiTest.java
- itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/discovery/test/WemoDiscoveryParticipantTest.java
- replace Collections by List.of and Set.of
- instanceof
- SAT warnings
> Java 17 features (itests)

- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/ValueEncoder.java
- bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/dpt/DPTTest.java
Special handling for temperature differences in °F and °F/%, DPT 9.002 and 9.003, needs to be adapted due to change in core. 
Refs openhab/openhab-core#3792
Implementation is valid for 4.0 and 4.x snapshot.
Fixes #15567.
> [knx] Adapt to core, temperature differences

- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoCrypto.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/Utils.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/cloud/CloudConnector.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/cloud/MiCloudConnector.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoAbstractHandler.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoVacuumHandler.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/miot/MiotParser.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/robot/RRMapDraw.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/robot/RRMapDrawOptions.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/transport/MiIoAsyncCommunication.java
- bundles/org.openhab.binding.miio/src/test/java/org/openhab/binding/miio/internal/ReadmeHelper.java
- bundles/org.openhab.binding.miio/src/test/java/org/openhab/binding/miio/internal/RoboMapViewer.java
Introducing non-breaking improvements from #15520
- Java style array syntax
- remove redundant modifiers
- always move String constants to left side in comparisons
- multiline strings
> [miio] Java style cleanup

- bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcBaseDAO.java
- bundles/org.openhab.persistence.jdbc/src/test/java/org/openhab/persistence/jdbc/internal/db/JdbcBaseDAOTest.java
This refactors for:
- Type-safety.
- Better error handling (in case of incompatible types).
- Increased test coverage.
Fixes #15433
> [jdbc] Improve conversion of database value to item state

- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoVacuumHandler.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/robot/RRMapFileParser.java
Adding new block types in map parser.
close #15068
> [miio] add new robo map blocks to map parser

- bundles/org.openhab.binding.nanoleaf/README.md
Migrating from OH 2.5 I tripped over this, as :power no longer exists and instead one has to send ON/OFF commands to the :color channel instead.
Looks like documentation wasn't fully updated with the code changes.
> [nanoleaf] Remove non-existing power channel from documentation

- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/discovery/HueBridgeNupnpDiscovery.java
- itests/org.openhab.binding.hue.tests/src/main/java/org/openhab/binding/hue/internal/discovery/HueBridgeNupnpDiscoveryOSGITest.java
> [hue] Fix NUPnP discovery after firmware change

- bundles/org.openhab.binding.xmltv/src/main/java/org/openhab/binding/xmltv/internal/XmlTVHandlerFactory.java
XMLInputFactory: Disable property IS_SUPPORTING_EXTERNAL_ENTITIES which allows injecting external entities.
I cannot test this change. @clinique was it intentional to disable DTD and keep external entities on?
In case, please close my PR.
> [xmltv] Handle possible XXE injection

- bundles/org.openhab.binding.surepetcare/README.md
Feeders seem to be supported as they are mentioned below.
> [surepetcare] Update Readme

- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/HomeApi.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/data/NetatmoConstants.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/NAError.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/NAHomeStatus.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/Capability.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/ChannelHelperCapability.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/HomeCapability.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/SecurityCapability.java
- bundles/org.openhab.binding.netatmo/src/main/resources/OH-INF/i18n/netatmo.properties
This information is currently provided by the API but ignored by the binding, thus letting things in UNKNOWN state
because no informations is provided for these by API answer (this behaves differently from the Weather side).
Resolves #15383
> [netatmo] Take in account errored modules/devices for Security/Energy areas

- bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/subhandler/LcnModuleLogicSubHandler.java
- bundles/org.openhab.binding.lcn/src/test/java/org/openhab/binding/lcn/internal/subhandler/LcnModuleLogicSubHandlerTest.java
Please consider backporting this.
> [lcn] Fix processing of logic function "all fulfilled" status message

- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/data/NetatmoConstants.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/HomeData.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/ApiBridgeHandler.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/BufferedWeatherCapability.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/CacheWeatherCapability.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/MeasureCapability.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/RefreshCapability.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/WeatherCapability.java
- bundles/org.openhab.binding.netatmo/src/main/resources/OH-INF/i18n/netatmo.properties
Some problems have been raised regarding high level of requests sent to Netatmo servers resulting in bans.
I spotted a NPE preventing proper discovery.
Also improved RefreshCapability that appeared to come back to 120s after a proper interval.
Added a buffer strategy for API requests.
Resolves #15519
> [netatmo] Add a buffer to lower Weather API requests

- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/PresenceCapability.java
Resolves #15377
There was a forgotten leftover here.
> [Netatmo] Fix presence warning every three minutes when not siren exists

- bundles/org.openhab.voice.watsonstt/pom.xml
Upgrade Watson library and dependencies.
Testest on 4.1.0.m1.
> [watsonstt] Upgrade dependencies

- CODEOWNERS
- bundles/org.openhab.binding.nanoleaf/README.md
Add IPV6 note on discovery as mentioned in https://community.openhab.org/t/nanoleaf-binding-may-fail-when-upgrading-to-the-latest-nanoleaf-firmware-because-of-ipv6/148152
> [Nanoleaf] ipv6 address doc

- bundles/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/PlugwiseBindingConstants.java
- bundles/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/PlugwiseCommunicationContext.java
- bundles/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/PlugwiseDeviceTask.java
- bundles/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/PlugwiseFilteredMessageListenerList.java
- bundles/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/PlugwiseMessageProcessor.java
- bundles/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/PlugwiseMessageSender.java
- bundles/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/PlugwiseThingDiscoveryService.java
- bundles/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/PlugwiseUtils.java
- bundles/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/handler/AbstractPlugwiseThingHandler.java
- bundles/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/handler/AbstractSleepingEndDeviceHandler.java
- bundles/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/handler/PlugwiseRelayDeviceHandler.java
- bundles/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/handler/PlugwiseSenseHandler.java
- bundles/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/handler/PlugwiseStickHandler.java
- bundles/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/listener/PlugwiseMessageListener.java
- bundles/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/protocol/AcknowledgementMessage.java
- bundles/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/protocol/AnnounceAwakeRequestMessage.java
- bundles/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/protocol/ClockSetRequestMessage.java
- bundles/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/protocol/InformationResponseMessage.java
- bundles/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/protocol/Message.java
- bundles/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/protocol/MessageFactory.java
- bundles/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/protocol/field/Energy.java
The cleanup includes:
* Use lambdas
* Use enhanced switches
* Make abstract class constructors protected
* Fix typos
> [plugwise] Cleanup code

- bundles/org.openhab.binding.tesla/README.md
> [tesla] fix small typo in documentation

- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoBindingConstants.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/cloud/CloudConnector.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/cloud/HomeDTO.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/cloud/HomeListDTO.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/cloud/HomeRoomDTO.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/cloud/MiCloudConnector.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoVacuumHandler.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/robot/HistoryRecordDTO.java
- bundles/org.openhab.binding.miio/src/main/resources/OH-INF/thing/vacuumThing.xml
* Room Mapping from cloud
* New history record
closing #15490
> [miio] new gen vacuums cleaning map and rooms

- itests/org.openhab.automation.groovyscripting.tests/itest.bndrun
- itests/org.openhab.automation.jsscriptingnashorn.tests/itest.bndrun
- itests/org.openhab.binding.astro.tests/itest.bndrun
- itests/org.openhab.binding.avmfritz.tests/itest.bndrun
- itests/org.openhab.binding.feed.tests/itest.bndrun
- itests/org.openhab.binding.hue.tests/itest.bndrun
- itests/org.openhab.binding.max.tests/itest.bndrun
- itests/org.openhab.binding.mielecloud.tests/itest.bndrun
- itests/org.openhab.binding.modbus.tests/itest.bndrun
- itests/org.openhab.binding.mqtt.homeassistant.tests/itest.bndrun
- itests/org.openhab.binding.mqtt.homie.tests/itest.bndrun
- itests/org.openhab.binding.mqtt.ruuvigateway.tests/itest.bndrun
- itests/org.openhab.binding.ntp.tests/itest.bndrun
- itests/org.openhab.binding.systeminfo.tests/itest.bndrun
- itests/org.openhab.binding.tradfri.tests/itest.bndrun
- itests/org.openhab.binding.wemo.tests/itest.bndrun
- itests/org.openhab.persistence.mapdb.tests/itest.bndrun
- pom.xml
https://github.com/bndtools/bnd/wiki/Changes-in-7.0.0
> Update bnd to 7.0.0

- itests/org.openhab.automation.groovyscripting.tests/itest.bndrun
- itests/org.openhab.automation.jsscriptingnashorn.tests/itest.bndrun
- itests/org.openhab.binding.astro.tests/itest.bndrun
- itests/org.openhab.binding.avmfritz.tests/itest.bndrun
- itests/org.openhab.binding.feed.tests/itest.bndrun
- itests/org.openhab.binding.hue.tests/itest.bndrun
- itests/org.openhab.binding.max.tests/itest.bndrun
- itests/org.openhab.binding.mielecloud.tests/itest.bndrun
- itests/org.openhab.binding.modbus.tests/itest.bndrun
- itests/org.openhab.binding.mqtt.homeassistant.tests/itest.bndrun
- itests/org.openhab.binding.mqtt.homie.tests/itest.bndrun
- itests/org.openhab.binding.mqtt.ruuvigateway.tests/itest.bndrun
- itests/org.openhab.binding.ntp.tests/itest.bndrun
- itests/org.openhab.binding.systeminfo.tests/itest.bndrun
- itests/org.openhab.binding.tradfri.tests/itest.bndrun
- itests/org.openhab.binding.wemo.tests/itest.bndrun
- itests/org.openhab.persistence.mapdb.tests/itest.bndrun
Depends on https://github.com/openhab/openhab-core/pull/3832
> Resolve runbundles for JUnit upgrade

- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiRpc.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2RpcSocket.java
This reverts #15719 until the issue has been further investigated.
> [shelly] Revert "Always try to stop WebSocketClient"

- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/dto/clip2/enums/EffectType.java
> [hue] Support additional effect types

- bundles/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/handler/MyQAccountHandler.java
see  https://community.openhab.org/t/chamberlain-myq-binding/4192/849
> [myq] Fix broken authentication due to changes in the myQ Cloud API

- bundles/org.openhab.binding.jellyfin/README.md
- bundles/org.openhab.binding.jellyfin/pom.xml
Upgrade Jellyfin sdk and deps.
BR.
> [jellyfin] Upgrade sdk

- bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/converter/ColorItemConverter.java
> [http] Fix brightness

- bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/TeslaBindingConstants.java
- bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaVehicleHandler.java
- Fix the update channel.
- Fix a NULL exception caused by attempted poll when vehicle is offline.
> [tesla] Fix update timestamp and null exception for offline state

- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/dto/clip2/Recall.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/dto/clip2/Resource.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/dto/clip2/enums/ResourceType.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/dto/clip2/enums/SceneRecallAction.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/dto/clip2/enums/SmartSceneRecallAction.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/dto/clip2/enums/SmartSceneState.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/Clip2BridgeHandler.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/Clip2ThingHandler.java
- bundles/org.openhab.binding.hue/src/test/java/org/openhab/binding/hue/internal/clip2/Clip2DtoTest.java
- bundles/org.openhab.binding.hue/src/test/resources/smart_scene.json
Resolves #15386 
With this PR the 'scene' channel, in addition to displaying options for selecting regular scenes, now also displays options for selecting smart scenes.
> [hue] Support smart scenes

- bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/Ffmpeg.java
- bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/ReolinkHandler.java
- bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/handler/IpCameraGroupHandler.java
- bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/handler/IpCameraHandler.java
- bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/onvif/OnvifCodec.java
- bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/onvif/OnvifConnection.java
- bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/onvif/OnvifDiscovery.java
- bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/rtsp/NettyRtspHandler.java
- bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/rtsp/RtspConnection.java
- bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/servlet/CameraServlet.java
- bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/servlet/IpCameraServlet.java
- bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/servlet/OpenStreams.java
- bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/servlet/StreamOutput.java
Some code cleanup on the IP Camera binding
> [ipcamera] Fix warnings and improve logging

- bundles/org.openhab.binding.pushover/README.md
> [pushover] Clarify priority message documentation

- bundles/org.openhab.binding.bticinosmarther/src/main/java/org/openhab/binding/bticinosmarther/internal/api/dto/Module.java
- bundles/org.openhab.binding.bticinosmarther/src/main/java/org/openhab/binding/bticinosmarther/internal/handler/SmartherModuleHandler.java
- bundles/org.openhab.binding.bticinosmarther/src/main/java/org/openhab/binding/bticinosmarther/internal/util/StringUtil.java
> [bticinosmarter] adapt to core StringUtils

- bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/message/XmlRpcRequest.java
> [homematic] adapt to core StringUtils

- bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudService.java
> [openhabcloud] adapt to core StringUtils

- bundles/org.openhab.binding.millheat/src/main/java/org/openhab/binding/millheat/internal/handler/MillheatAccountHandler.java
> [millheat] adapt to core StringUtils

- bundles/org.openhab.binding.ekey/README.md
Updated documentation with my experience from running this addon with MULTI protocol
> [ekey] Update documentation

- bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/api/DatahubTariffFilterFactory.java
- Previous [result set](https://api.energidataservice.dk/dataset/DatahubPricelist?filter=%7B%22ChargeType%22%3A%5B%22D03%22%5D%2C%22GLN_Number%22%3A%5B%225790001100520%22%5D%2C%22ChargeTypeCode%22%3A%5B%22T3002%22%5D%2C%22Note%22%3A%5B%22Nettarif+C%22%5D%7D&start=StartOfDay)
- New [result set](https://api.energidataservice.dk/dataset/DatahubPricelist?filter=%7B%22ChargeType%22%3A%5B%22D03%22%5D%2C%22GLN_Number%22%3A%5B%225790001100520%22%5D%2C%22ChargeTypeCode%22%3A%5B%22T3001%22%5D%2C%22Note%22%3A%5B%22Nettarif+C%22%5D%7D&start=StartOfDay)
> [energidataservice] Adjust filter for Elnet Midt

- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/data/EventType.java
Corrected some existing events wrongly associated to Outdoor (weather) module instead of Presence.
Added 'alarm_started' event.
> [netatmo] Add and correct webhook events

- bundles/org.openhab.binding.mybmw/src/main/java/org/openhab/binding/mybmw/internal/handler/MyBMWProxy.java
- bundles/org.openhab.binding.mybmw/src/main/java/org/openhab/binding/mybmw/internal/utils/Converter.java
- bundles/org.openhab.binding.mybmw/src/test/java/org/openhab/binding/mybmw/internal/handler/AuthTest.java
> [mybmw] adapt to core StringUtils

- bundles/org.openhab.binding.miio/README.base.md
- bundles/org.openhab.binding.miio/README.md
- bundles/org.openhab.binding.miio/src/test/java/org/openhab/binding/miio/internal/ReadmeHelper.java
* Minor formatting
* Fix hyperlink for robo rock vacuums channels
> [miio] readme hyperlink fix

- bundles/org.openhab.binding.sonyaudio/src/main/java/org/openhab/binding/sonyaudio/internal/discovery/SonyAudioDiscoveryParticipant.java
- bundles/org.openhab.binding.sonyaudio/src/main/java/org/openhab/binding/sonyaudio/internal/handler/SonyAudioHandler.java
- bundles/org.openhab.binding.sonyaudio/src/main/java/org/openhab/binding/sonyaudio/internal/protocol/SonyAudioConnection.java
- bundles/org.openhab.binding.sonyaudio/src/main/java/org/openhab/binding/sonyaudio/internal/protocol/SonyAudioMethod.java
Some minor SAT warnings fixed.
> [sonyaudio] small cleanup

- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/connection/Clip2Bridge.java
> [hue] Reduce log level for logging of unknown resource types (API v2)

- bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcPersistenceService.java
Resolves #14927
Resolves #15821 (for good)
Tested by installing compiled bundle as well as [mysql-connector](https://mvnrepository.com/artifact/com.mysql/mysql-connector-j/8.0.33) into addons directory as `mysql-connector.jar`.
> [jdbc] Process operations asynchronously

- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/DeviceInspector.java
- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/KNXClient.java
- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/SerialClient.java
- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/IPBridgeThingHandler.java
- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/i18n/KNXTranslationProvider.java
- bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/i18n/KNXTranslationProviderTest.java
purely code documentation, no effect on functionality, pls. just merge
> [knx] Fix typos in code comments

- bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/discovery/internal/BluetoothDiscoveryService.java
Follow up to :
https://github.com/openhab/openhab-addons/pull/15828#discussion_r1382267062
> [bluetooth] null check refactored

- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/channel/KNXChannelFactory.java
- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/SerialTransportAdapter.java
- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/DPTUnits.java
- bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/channel/KNXChannelFactoryTest.java
- bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/channel/KNXChannelTest.java
- bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/dpt/DPTTest.java
With this PR the build if KNX addon is warning-free on Win32.
CI to be checked.
> [knx] Fix all compiler warnings

- bundles/org.openhab.persistence.jdbc/src/main/resources/OH-INF/addon/addon-sqlite.xml
> [jdbc] Fix addon id for SQLite

- bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/BluetoothUtils.java
Sorry to say, but with #15828 i re-introduced an `arraystoreexception` that was fixed before in #15320
Fixes: #15313
> [Bluetooth] re-fix ArrayStoreException

- bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/JSONSchemaLight.java
Due to #15427 and #14839 being developed independently, but merged to main successively
> [mqtt.homeassistant] fix compilation problems

- bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/AbstractComponent.java
Follow on to #15427
ring-mqtt sends `"name": ""`, not `"name": null` or simply omitting it, so be sure to handle that way as well
> [mqtt.homeassistant] Handle empty device name

- bundles/org.openhab.binding.nanoleaf/README.md
> [nanoleaf] Fix typo in Readme

- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoVacuumHandler.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/robot/HistoryRecordDTO.java
Fixes Roborock Q7Max Historical Cleaning record missing
closing #15490
Signed-off-by: Marcel Verpaalen marcel@verpaalen.com
> [miio] Fix cleaning record for newer vacuums

- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/Clip2ThingHandler.java
Minor refactoring done while working on #15905.
It simplifies the code a bit for better readability. I have now extracted it to reduce that size of that PR with changes that are out of scope for actually fixing the bug.
> [hue] Refactor method to reduce nesting and code duplication

- bundles/org.openhab.binding.solax/README.md
> [solax] Update README.md

- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/DPTUnits.java
- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/DeviceThingHandler.java
- bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/dpt/DPTTest.java
See https://community.openhab.org/t/knx-thing-no-longer-working-after-upgrade-3-x-4-x/150252
Also improves test messages for DPT unit tests
> [knx] Fix IOOB exception with missing DPT in number channels

- bundles/org.openhab.binding.ecovacs/src/main/resources/devices/supported_device_list.json
> [ecovacs] Add some new models to device database

- bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaAccountHandler.java
> [tesla] Fix location with firmware 2023.38.x

- bundles/org.openhab.binding.jellyfin/README.md
- bundles/org.openhab.binding.jellyfin/pom.xml
- bundles/org.openhab.binding.jellyfin/src/main/java/org/openhab/binding/jellyfin/internal/handler/JellyfinClientHandler.java
Hello,
This PR fixes/unifies how the refresh command is handled by the different channels.
Also include a minor upgrade of the Jellyfin sdk.
> [Jellyfin] Fix how refresh is handled

- bundles/org.openhab.binding.openwebnet/README.md
[openwebnet] Energy: update readme to reflect update behaviour of F520/F521 on updates. Add %unit% string to energyToday and energyMonth channels' item to show the  unit of measure in item's detail 
Bticino F520
> [openwebnet] Update label pattern in items example

- bundles/org.openhab.binding.boschshc/README.md
- bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/BoschSHCBindingConstants.java
- bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/motiondetector/MotionDetectorHandler.java
- bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/illuminance/IlluminanceService.java
- bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/illuminance/dto/IlluminanceServiceState.java
- bundles/org.openhab.binding.boschshc/src/main/resources/OH-INF/thing/thing-types.xml
- bundles/org.openhab.binding.boschshc/src/main/resources/OH-INF/update/binding.xml
- bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/motiondetector/MotionDetectorHandlerTest.java
- add channel and corresponding channel type
- add update description
- add state model
- implement service and handler
- add documentation
- add unit test
> [boschshc] Add support for motion detector illuminance sensor

- bundles/org.openhab.binding.knx/README.md
- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/channel/GroupAddressConfiguration.java
- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/DeviceThingHandler.java
Group address notation of the KNX binding currently uses a mainGA used for writing and reading from the bus, and additional listenGAs to listen to further addresses, e.g. status addresses.
https://www.openhab.org/addons/bindings/knx/#group-address-notation
mainGA is always listening, which is misleading or even wrong in certain situations, e.g. whenever commands are sent form device on the bus and the corresponding actor is locked and does not execute the command. In those cases OH should relay only on the listenGAs, not the mainGA.
This PR introduces a new optional modifier ">" to turn the mainGA write-only.
Alternative implementation to #16003, which maintains compatibility with existing installations.
> [knx] New modifier to set mainGA write-only

- bundles/org.openhab.binding.knx/README.md
Refs: #16042
as discussed after merge
> [knx] Refine GA documentation

- bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java
> [rrd4j] Reliably get the latest value, if the filter end date is set to "now"

- bundles/org.openhab.automation.jsscripting/README.md
- bundles/org.openhab.automation.jsscripting/pom.xml
You'll find the changelog at the openhab-js repo: https://github.com/openhab/openhab-js/blob/main/CHANGELOG.md#470.
> [jsscripting] Upgrade openhab-js to 4.7.0

- bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/addon/addon.xml
- bundles/org.openhab.binding.knx/src/main/resources/OH-INF/addon/addon.xml
- bundles/org.openhab.binding.mqtt/src/main/resources/OH-INF/addon/addon.xml
- bundles/org.openhab.binding.onewire/src/main/resources/OH-INF/addon/addon.xml
- bundles/org.openhab.persistence.influxdb/src/main/resources/OH-INF/addon/addon.xml
- bundles/org.openhab.persistence.jdbc/src/main/resources/OH-INF/addon/addon-mariadb.xml
- bundles/org.openhab.persistence.jdbc/src/main/resources/OH-INF/addon/addon-mysql.xml
- bundles/org.openhab.persistence.jdbc/src/main/resources/OH-INF/addon/addon-postgresql.xml
- bundles/org.openhab.persistence.mongodb/src/main/resources/OH-INF/addon/addon.xml
Addon-info for new add-on suggestion finder which detects running processes on the OH server.
Refs: openhab/openhab-core#3904
> addoninfo for new add-on suggestion finder "process"

- bundles/org.openhab.binding.knx/README.md
- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/discovery/KNXnetDiscoveryService.java
- bundles/org.openhab.binding.knx/src/main/resources/OH-INF/thing/ip.xml
This PR adds automatic discovery of KNX IP interfaces and routers.
It will create a thing in the inbox (for routers it might create two entries, if both routing and tunneling is announced).
Discovery uses multicast traffic to IP 224.0.23.12, port 3671.
> [knx] Add discovery service

- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/HueBindingConstants.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/Clip2ThingHandler.java
> [hue] Re-create missing scene channel (API v2)

- bundles/org.openhab.automation.jsscripting/pom.xml
Fixes a minor issue introduced by openhab-js 4.7.1.
> [jsscripting] Upgrade openhab-js to 4.7.2

- bundles/org.openhab.binding.knx/src/main/resources/OH-INF/addon/addon.xml
Refs: openhab/openhab-core#3912, openhab/openhab-core#3920
> [knx] Metadata for discovery

- bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/i18n/energidataservice.properties
> [energidataservice] Update I18N properties

- itests/org.openhab.automation.groovyscripting.tests/itest.bndrun
- itests/org.openhab.automation.jsscriptingnashorn.tests/itest.bndrun
- itests/org.openhab.binding.avmfritz.tests/itest.bndrun
- itests/org.openhab.binding.feed.tests/itest.bndrun
- itests/org.openhab.binding.hue.tests/itest.bndrun
- itests/org.openhab.binding.max.tests/itest.bndrun
- itests/org.openhab.binding.mielecloud.tests/itest.bndrun
- itests/org.openhab.binding.modbus.tests/itest.bndrun
- itests/org.openhab.binding.mqtt.homeassistant.tests/itest.bndrun
- itests/org.openhab.binding.mqtt.homie.tests/itest.bndrun
- itests/org.openhab.binding.mqtt.ruuvigateway.tests/itest.bndrun
- itests/org.openhab.binding.ntp.tests/itest.bndrun
- itests/org.openhab.binding.systeminfo.tests/itest.bndrun
- itests/org.openhab.binding.tradfri.tests/itest.bndrun
- itests/org.openhab.binding.wemo.tests/itest.bndrun
- itests/org.openhab.persistence.mapdb.tests/itest.bndrun
Related to openhab/openhab-core#3935
> Resolve runbundles for logback upgrade

- bundles/org.openhab.binding.heos/README.md
> [heos] Minor doc update

- bundles/org.openhab.io.metrics/src/main/resources/OH-INF/addon/addon.xml
Input data for addon suggestion finder "process": if local instance of prometheus is running, suggest the metrics service.
> [metrics] Add addoninfo for suggestion

- bundles/org.openhab.binding.asuswrt/README.md
- bundles/org.openhab.binding.asuswrt/src/main/feature/feature.xml
- bundles/org.openhab.binding.asuswrt/src/main/java/org/openhab/binding/asuswrt/internal/AsuswrtDiscoveryParticipant.java
- bundles/org.openhab.binding.asuswrt/src/main/java/org/openhab/binding/asuswrt/internal/constants/AsuswrtBindingConstants.java
- bundles/org.openhab.binding.asuswrt/src/main/resources/OH-INF/addon/addon.xml
- bundles/org.openhab.binding.asuswrt/src/main/resources/OH-INF/thing/router.xml
This makes it easier to discover the devices and the add-on.
> [asuswrt] Support router discovery and add-on suggestion using UPnP

- bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/handler/EcobeeUtils.java
- bundles/org.openhab.binding.livisismarthome/src/main/java/org/openhab/binding/livisismarthome/internal/handler/LivisiBridgeHandler.java
- bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/handler/MaxCubeBridgeHandler.java
The brackets in EcobeeUtils got added in #16101 and I found a few more occurrences.
> Remove some redundant brackets

- bundles/org.openhab.binding.mqtt.homeassistant/src/main/resources/OH-INF/config/homeassistant-thing-config.xml
- bundles/org.openhab.binding.mqtt.homeassistant/src/main/resources/OH-INF/i18n/mqtt.properties
The prefix (homeassistant/) and the suffix (/config) are automatically added
> [mqtt.homeassistant] update example config topic

- bundles/org.openhab.binding.mqtt.homeassistant/README.md
Enumerate supported components, rather than a few limitations.
> [mqtt.homeassistant] Update README

- bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/AccountServlet.java
Fixes #16149
Similar to #14554
> [amazonechocontrol] Fix Servlet exceptions due to non-unique names

- bundles/org.openhab.binding.nuki/README.md
See https://github.com/openhab/openhab-addons/issues/16113
> [nuki] Refer to network settings for callback

- bundles/org.openhab.binding.luxtronikheatpump/src/main/java/org/openhab/binding/luxtronikheatpump/internal/enums/HeatpumpVisibility.java
> [luxtronikheatpump] Fix typo in Javadoc

- itests/org.openhab.automation.groovyscripting.tests/itest.bndrun
- itests/org.openhab.automation.jsscriptingnashorn.tests/itest.bndrun
- itests/org.openhab.binding.astro.tests/itest.bndrun
- itests/org.openhab.binding.avmfritz.tests/itest.bndrun
- itests/org.openhab.binding.feed.tests/itest.bndrun
- itests/org.openhab.binding.hue.tests/itest.bndrun
- itests/org.openhab.binding.max.tests/itest.bndrun
- itests/org.openhab.binding.mielecloud.tests/itest.bndrun
- itests/org.openhab.binding.modbus.tests/itest.bndrun
- itests/org.openhab.binding.mqtt.homeassistant.tests/itest.bndrun
- itests/org.openhab.binding.mqtt.homie.tests/itest.bndrun
- itests/org.openhab.binding.mqtt.ruuvigateway.tests/itest.bndrun
- itests/org.openhab.binding.ntp.tests/itest.bndrun
- itests/org.openhab.binding.systeminfo.tests/itest.bndrun
- itests/org.openhab.binding.tradfri.tests/itest.bndrun
- itests/org.openhab.binding.wemo.tests/itest.bndrun
Related to https://github.com/openhab/openhab-core/pull/4015
> Resolve runbundles for JmDNS upgrade

- bundles/org.openhab.binding.pushover/src/main/java/org/openhab/binding/pushover/internal/actions/PushoverActions.java
Reported in the forum:
- https://community.openhab.org/t/openhab-4-1-release-discussion/152252/9
- https://community.openhab.org/t/pushover-stopped-working-after-oh3-oh4-upgrade/152669
Regression of #15289
> [pushover] Fix thing action backwards compatibility

- bundles/org.openhab.binding.elerotransmitterstick/src/main/resources/OH-INF/addon/addon.xml
> [elerotransmitterstick] Support suggestion finder

- bundles/org.openhab.binding.hydrawise/src/main/java/org/openhab/binding/hydrawise/internal/api/graphql/HydrawiseGraphQLClient.java
- bundles/org.openhab.binding.hydrawise/src/main/java/org/openhab/binding/hydrawise/internal/handler/HydrawiseAccountHandler.java
Handles a new condition where the service rejects a request as unauthorized, but really we just need to refresh our token after waiting 60 seconds.  This should probably be cherry picked back to 4.x.   I have a version of this against 4.1 if that would help.
> [hydrawise] Handle API auth changes

- bundles/org.openhab.binding.pilight/src/main/java/org/openhab/binding/pilight/internal/PilightConnector.java
- bundles/org.openhab.binding.pilight/src/main/java/org/openhab/binding/pilight/internal/discovery/PilightBridgeDiscoveryService.java
- bundles/org.openhab.binding.pilight/src/main/java/org/openhab/binding/pilight/internal/discovery/PilightDeviceDiscoveryService.java
- bundles/org.openhab.binding.pilight/src/main/java/org/openhab/binding/pilight/internal/handler/PilightBridgeHandler.java
- bundles/org.openhab.binding.pilight/src/main/java/org/openhab/binding/pilight/internal/handler/PilightGenericHandler.java
- bundles/org.openhab.binding.pilight/src/main/java/org/openhab/binding/pilight/internal/types/PilightContactType.java
- Fix warnings from static code analysis
- Remove superfluous if
- Remove redundant member
- Introduce constant
- Use correct thing type uids in PilightDeviceDiscoveryService
- Fix log messages
Signed-off-by: Stefan Roellin <stefan@roellin-baumann.ch>
> [pilight] Various minor code improvements

- bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/NumberValue.java
- bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/values/ValueTests.java
> [mqtt] recognize -NaN as UNDEF as well

- bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/handler/ZonePlayerHandler.java
- bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/i18n/sonos.properties
- bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/channels.xml
Adds Dolby TrueHD 7.1
Resolves #16251
> [sonos] Add TrueHD 7.1

- itests/org.openhab.automation.groovyscripting.tests/itest.bndrun
- itests/org.openhab.automation.jsscriptingnashorn.tests/itest.bndrun
Related to https://github.com/openhab/openhab-core/pull/4033
> Resolve runbundles for Jollyday upgrade

- bundles/org.openhab.binding.dmx/src/main/java/org/openhab/binding/dmx/internal/DmxBridgeHandler.java
If an exception is thrown while sending (or connecting) the refreshJob died. This exception is now handled gracefully.
> [dmx] Improve exception handling in refresh job

- bundles/org.openhab.binding.hydrawise/src/main/java/org/openhab/binding/hydrawise/internal/handler/HydrawiseAccountHandler.java
> [hydrawise] Small fix when retying token

- bundles/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/ChannelsTypeProviderAvailableInputs.java
- bundles/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/ChannelsTypeProviderPreset.java
- bundles/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/handler/YamahaZoneThingHandler.java
> [yamahareceiver] Fix ChannelTypeProvider

- bundles/org.openhab.binding.androidtv/src/main/java/org/openhab/binding/androidtv/internal/protocol/shieldtv/ShieldTVMessageParser.java
Adds missing default apps reported by community
Resolves #16284
> [androidtv] Fix missing default shieldtv applications

- bundles/org.openhab.binding.doorbird/src/main/java/org/openhab/binding/doorbird/internal/api/DoorbirdAPI.java
- bundles/org.openhab.binding.doorbird/src/main/java/org/openhab/binding/doorbird/internal/api/DoorbirdSession.java
- bundles/org.openhab.binding.doorbird/src/main/java/org/openhab/binding/doorbird/internal/handler/DoorbellHandler.java
- bundles/org.openhab.binding.doorbird/src/main/java/org/openhab/binding/doorbird/internal/listener/DoorbirdEvent.java
- bundles/org.openhab.binding.doorbird/src/main/java/org/openhab/binding/doorbird/internal/listener/DoorbirdUdpListener.java
- bundles/org.openhab.binding.doorbird/src/main/java/org/openhab/binding/doorbird/internal/model/GetsessionDTO.java
> [doorbird] Add support for version 2 encryption scheme

- bundles/org.openhab.binding.govee/README.md
- bundles/org.openhab.binding.nanoleaf/README.md
Update information about Govee and Nanoleaf in Readme
> Readme updates for Nanoleaf and Govee

- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiRpc.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/ShellyBluApi.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyBaseHandler.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyBluSensorHandler.java
- bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/i18n/shelly.properties
- bundles/org.openhab.binding.shelly/src/main/resources/scripts/oh-blu-scanner.js
This includes
-  improved logging on WebSocket connection problems
- removing a duplicate resource on shelly.properties
- some minor (cosmetic) code improvements
> [shelly] improved logging on WebSocket connection problems

- bundles/org.openhab.binding.boschindego/NOTICE
> [boschindego] Update third party licenses

- bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/HomeAssistantConfiguration.java
- bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/discovery/HomeAssistantDiscovery.java
- bundles/org.openhab.binding.mqtt.homeassistant/src/main/resources/OH-INF/config/config.xml
- bundles/org.openhab.binding.mqtt.homeassistant/src/main/resources/OH-INF/i18n/mqtt.properties
- bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/discovery/HomeAssistantDiscoveryTests.java
> [mqtt.homeassistant] Trigger HA devices to update discovery information

- bundles/org.openhab.binding.tacmi/README.md
update on the units. Measured with CMI, Firmware version 1.38.3
> [tacmi] Update README.md

- bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/TeslaBindingConstants.java
- bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaAccountHandler.java
- bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaVehicleHandler.java
Fixes https://github.com/openhab/openhab-addons/issues/16318
I've ported the fix provided by @psmedley on https://github.com/psmedley/openhab-addons/tree/tesla-4.1.x.
> [tesla] Adapt calls to new products API endpoint

- bundles/org.openhab.binding.modbus.studer/README.md
Nothing extra special, but some corrections to the docs.
> [modbus.studer] Some little markdown and grammar corrections

- bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/lib/manager/impl/TemperatureControlManager.java
This fixes an _UnsupportedOperationException_ thrown when adding an element to a fixed-size list.
This code section has not worked for years ...
Fixes #10649
> [digitalstrom] Fix initialization of temperature control devices

- bundles/org.openhab.binding.teleinfo/src/main/java/org/openhab/binding/teleinfo/internal/TeleinfoDiscoveryService.java
This PR enable background discovery for the teleinfo binding.
> [teleinfo] Enable background discovery

- bundles/org.openhab.automation.groovyscripting/README.md
> [groovyscripting] Described a way for code reuse

- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueLightHandler.java
> [hue] Fix `NullPointerException`

- bundles/org.openhab.binding.shelly/README.md
- bundles/org.openhab.binding.shelly/pom.xml
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/ShellyBindingConstants.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyDeviceProfile.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiJsonDTO.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/discovery/ShellyDiscoveryParticipant.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/discovery/ShellyThingCreator.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyBaseHandler.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/manager/ShellyManagerPage.java
- bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/config/configblu.xml
- bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/i18n/shelly.properties
- bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/thing/shellyBlu.xml
Add support for
- Shelly Plus Mini genration 3 series of devices
- Shelly Plus UNI
- Shelly BLU Gateway
Closing
- #15990 
- #15991
- #15992
> [shelly] Support for Shelly Plus Mini Gen 3 series of devices, Shelly Plus UNI

- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoVacuumHandler.java
Fixes issue reported in forum.
https://community.openhab.org/t/miio-binding-roborock-s4max-no-longer-getting-last-cleaning-details/153260/3
> [miio] Fix date parsing issue last cleaning details

- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoVacuumHandler.java
> [miio] Fix sending empty command for feature channels

- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoVacuumHandler.java
closes #16005
Fixes missing end timestamp and wrong start timestamp
> [miio] Fix last cleaning details wrong start and end missing issue

- bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/itests/Back2BackTest.java
No functional impact, just increasing the test coverage.
> [knx] Add tests for DPT 5, DPT 6, DPT 8, DPT 13

- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyBaseHandler.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/util/ShellyUtils.java
Nothing huge, Just removing of duplicated code.
> [shelly] Remove duplicated code

- bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/itests/Back2BackTest.java
No impact on function, just adding some tests.
> [knx] Add tests for DPT 9 and DPT 14

- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/channel/KNXChannel.java
- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/ValueDecoder.java
- bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/channel/KNXChannelTest.java
should not change anything, but this way it is accepted without warnings
> [knx] Fix warnings and remove TODOs

- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/channel/KNXChannel.java
- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/channel/TypeColor.java
- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/channel/TypeDimmer.java
- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/channel/TypeRollershutter.java
- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/DeviceThingHandler.java
- bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/channel/KNXChannelTest.java
> [knx] Fix KNX dimmer channels

- itests/org.openhab.automation.groovyscripting.tests/itest.bndrun
- itests/org.openhab.automation.jsscriptingnashorn.tests/itest.bndrun
- itests/org.openhab.binding.astro.tests/itest.bndrun
- itests/org.openhab.binding.avmfritz.tests/itest.bndrun
- itests/org.openhab.binding.feed.tests/itest.bndrun
- itests/org.openhab.binding.hue.tests/itest.bndrun
- itests/org.openhab.binding.max.tests/itest.bndrun
- itests/org.openhab.binding.mielecloud.tests/itest.bndrun
- itests/org.openhab.binding.modbus.tests/itest.bndrun
- itests/org.openhab.binding.mqtt.homeassistant.tests/itest.bndrun
- itests/org.openhab.binding.mqtt.homie.tests/itest.bndrun
- itests/org.openhab.binding.mqtt.ruuvigateway.tests/itest.bndrun
- itests/org.openhab.binding.ntp.tests/itest.bndrun
- itests/org.openhab.binding.systeminfo.tests/itest.bndrun
- itests/org.openhab.binding.tradfri.tests/itest.bndrun
- itests/org.openhab.binding.wemo.tests/itest.bndrun
- itests/org.openhab.binding.wemo.tests/pom.xml
Related to openhab/openhab-core#4098
> Resolve runbundles for jUPnP upgrade

- bundles/org.openhab.binding.roku/src/main/resources/OH-INF/addon/addon.xml
Add discovery methods for the binding suggestion finder.
> [roku] Add discoveryMethods

- bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/channel/KNXChannelTest.java
Minor change to get fix warnings recently introduced with #16421.
> [knx] Fix warnings in test

- bundles/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/internal/enums/PowerStatus.java
> [epsonprojector] Add A/V standby power status

- bundles/org.openhab.binding.melcloud/README.md
- bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/handler/MelCloudAccountHandler.java
- bundles/org.openhab.binding.melcloud/src/main/resources/OH-INF/thing/acDevice.xml
- bundles/org.openhab.binding.melcloud/src/main/resources/OH-INF/thing/heatpumpDevice.xml
Adjust polling values according to new limits introduced by Mitsubishi Electric.
Fixes: #16385
Signed-off-by: Wietse van Buitenen <thewiep@gmail.com>
> [melcloud] Adjust to new API limits

- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/DPTUtil.java
- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/ValueDecoder.java
- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/ValueEncoder.java
- bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/dpt/DPTTest.java
- bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/itests/Back2BackTest.java
Findings from Back2Back test:
DPT 6.020 uses a StringType representation in Calimero. Added StringType to allowed types.
DPT 8.010 was depending on locale, as it renders numbers with fraction. Calimero expects decimal separator in current locale.
> [knx] Fix DPT 6.020 and 8.010

- bundles/org.openhab.binding.knx/README.md
Added a table containing all supported DPTs.
Any suggestions how to improve the table view in md?
> [knx] Add list of supported DPTs

- bundles/org.openhab.voice.googlestt/src/main/java/org/openhab/voice/googlestt/internal/GoogleSTTService.java
- bundles/org.openhab.voice.watsonstt/src/main/java/org/openhab/voice/watsonstt/internal/WatsonSTTService.java
These is a fix related to PR https://github.com/openhab/openhab-addons/pull/16111 I adapted incorrectly the googlestt and watsonstt to support PCM audio streams.
> [Voice] Fix google and watson speech-to-text services PCM format support

- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/ValueDecoder.java
- bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/itests/Back2BackTest.java
Both DPTs are provided as String by Calimero and contain a time value in seconds.
When time is >=1000s, it might render to something like ```6.553,5 s``` - breaking the current implementation.
This was missed in Back2Back test, as only small time values were tested.
> [knx] Fix DPT 243.600 and 249.600 when time>=1000s

- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/ApiBridgeHandler.java
> [netatmo] Fix account bridge staying offline

- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/ValueDecoder.java
- bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/dpt/DPTTest.java
- bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/i18n/KNXTranslationProviderTest.java
- bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/itests/Back2BackTest.java
Close gaps in test coverage identified with jacoco coverage analysis tool, #16507.
This PR can be merged independently.
> [knx] Increase test coverage

- bundles/org.openhab.automation.jythonscripting/src/main/resources/OH-INF/addon/addon.xml
This fix was picked from #16508 with intention of being cherry-picked into 4.1.x.
This is similar to #15877 and might cause similar issues as described in #15847. This is unverified though.
> [jythonscripting] Fix addon id

- itests/org.openhab.binding.avmfritz.tests/src/main/java/org/openhab/binding/avmfritz/internal/discovery/AVMFritzDiscoveryServiceOSGiTest.java
See: https://github.com/openhab/openhab-addons/issues/16536
> [avmfritz] Disable unstable AVMFritzDiscoveryServiceOSGiTest

- bundles/org.openhab.automation.jythonscripting/README.md
changed script and default library path
> [jythonscripting] updated readme

- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/NAHomeStatus.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/channelhelper/SecurityChannelHelper.java
> [netatmo] Don't read of Energy data for Security area

- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/HomeCapability.java
Resolves #16544
Reverts incorrect code move
> [netatmo] Home child things won't go online

- features/openhab-addons/src/main/resources/footer.xml
> [modbus.sungrow] Add missing sungrow bundle

- bundles/org.openhab.binding.jellyfin/README.md
Just some simple changes to the README
- Fix some typos
- Add some code brackets
- Some formatting changes
> [Jellyfin] Overhaul README.md

- bundles/org.openhab.persistence.inmemory/src/main/java/org/openhab/persistence/inmemory/internal/InMemoryPersistenceService.java
- bundles/org.openhab.persistence.inmemory/src/test/java/org/openhab/persistence/inmemory/internal/InMemoryPersistenceTests.java
Queries should include the boundaries, but the previous code did not.
Discovered by @splatch
> [inmemory] Fix boundaries for queries

- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/AirCareCapability.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/CacheWeatherCapability.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/WeatherCapability.java
Two child things may request cache update in a very small time frame, thus leading to two API calls when one would have been enough.
Extracted from #16489
> [netatmo] Weather cache must be synchronized

- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/CacheCapability.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/HomeCapability.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/MeasureCapability.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/RefreshCapability.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/WeatherCapability.java
Resolves #16561 
Must be reviewed after #16572
> [netatmo] Add a buffer to lower Home API requests

- bundles/org.openhab.automation.jsscripting/README.md
- bundles/org.openhab.automation.jsscripting/pom.xml
For the changelog, see https://github.com/openhab/openhab-js/blob/main/CHANGELOG.md#490.
> [jsscripting] Upgrade to openhab-js to 4.9.0

- bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/internal/MailBuilder.java
> [mail] Fix sending HTML mails

- bundles/org.openhab.persistence.mongodb/src/main/java/org/openhab/persistence/mongodb/internal/MongoDBPersistenceService.java
> [mongodb] Fix missing service pid

- bundles/org.openhab.persistence.dynamodb/pom.xml
Add missing dependencies after Karaf upgrade #16493.
Fixes #16535.
@wborn FYI
> [dynamodb] Enable tests

- bundles/org.openhab.binding.knx/README.md
- bundles/org.openhab.binding.knx/pom.xml
- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/DeviceInspector.java
- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/discovery/KNXnetDiscoveryService.java
- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/DPTUnits.java
- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/ValueDecoder.java
- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/ValueEncoder.java
- bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/dpt/DPTTest.java
- bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/itests/Back2BackTest.java
- Upstream update of base library for KNX access from v2.5.1 to v2.6-rc1.
- Bugfixes and new subtypes for DPTs 20, 21, 22.
- Remove workarounds for issues in v2.5.1.
Version 2.6 (rc1) is the latest release of the 2.x branch, which is much closer to the 2.5.1 than the upcoming release 3.x.
See https://github.com/calimero-project/calimero-core/issues/129#issuecomment-2023403908
~~Once this one is merged, I will also update the PR for 3.x, #16506.~~
> [knx] Upgrade Calimero to 2.6-rc1

- bundles/org.openhab.binding.upnpcontrol/src/main/java/org/openhab/binding/upnpcontrol/internal/handler/UpnpRendererHandler.java
> [upnpcontrol] Catch IAE when Album Art URI is invalid

- bundles/org.openhab.io.openhabcloud/README.md
Update Cloud Connector installation procedure
> Update Cloud Connector installation procedure

- bundles/org.openhab.io.hueemulation/pom.xml
- itests/org.openhab.binding.avmfritz.tests/itest.bndrun
- itests/org.openhab.binding.hue.tests/itest.bndrun
- itests/org.openhab.binding.wemo.tests/itest.bndrun
- itests/org.openhab.binding.wemo.tests/pom.xml
> Move to JUPnP v3.0.1

- bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/generic/GenericEEP.java
Re-write static list initialization.
Old implementation was breaking the Java 21 build when output was set to Java 17 class files.
Refs:
openhab/openhab-distro#1590
openhab/openhab-distro#1640
> [enocean] Fix Java 21 build

- bundles/org.openhab.persistence.jpa/pom.xml
This is a workaround to allow compiling with Java 21.
Folder is pinned to create Java 17 code.
A PR #16591 is has been opened to upgrade base libraries to a version compatible with Java 21.
I do not expect it to be merged soon, as we need testing before we can proceed.
This is why the workaround should be merged in the meantime.
Refs: 
openhab/openhab-distro#1590
openhab/openhab-distro#1640
> [persistence.jpa] Pin to Java 17

- bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/channeltypes.xml
Test report here: https://github.com/openhab/openhab-addons/pull/16614#issuecomment-2041107663
> [miele] Provide unit hint for water consumption channel

- bundles/org.openhab.binding.knx/pom.xml
Test coverage analysis is based on JaCoCo tool.
This tool is also used in the mybmw binding.
Test-coverage report is part of the site documentation
in the target after test and can be viewed in a web browser.
IDE integration is possible via coverage extensions.
(Note: implementation changed from separate profile to always active, see comments below)
> [knx] Add JaCoCo test-coverage

- bundles/org.openhab.binding.deutschebahn/README.md
Fixes #16577.
The example was not in sync with the documentation, credentials are provided differently.
Definition of Things no longer causes warnings.
Added hint to how to escape data in textual config.
Unfortunately, Deutsche Bahn does no longer provide [Station IDs](https://de.wikipedia.org/wiki/Interne_Bahnhofsnummer) needed for this binding (```evaNo```) in the Open Data portal. Although links to other portals were provided, I could not find the official list.
Thus, I added two links to other pages providing this information.
> [deutschebahn] Fix example and update links

- bundles/org.openhab.binding.mybmw/README.md
- bundles/org.openhab.binding.mybmw/src/main/java/org/openhab/binding/mybmw/internal/utils/ImageProperties.java
- bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/i18n/mybmw.properties
- bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/thing/image-channel-types.xml
- bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/thing/thing-bev.xml
- bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/thing/thing-bev_rex.xml
- bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/thing/thing-conv.xml
- bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/thing/thing-phev.xml
- bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/update/thing-update.xml
> [mybmw] Fix images not loading anymore

- bundles/org.openhab.binding.harmonyhub/pom.xml
- bundles/org.openhab.binding.harmonyhub/src/main/java/org/openhab/binding/harmonyhub/internal/handler/HarmonyHubHandler.java
> [harmonyhub] Fix NumberFormatException when selecting hue scene

- bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/IndegoController.java
Resolves #16517
See https://community.openhab.org/t/bosch-indego-how-to-use-bosch-single-id/146299/33
> [boschindego] Bypass WAF by using app user-agent

- bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/utils/LatencyParser.java
LatencyParser fails to parse ping times on systems with comma (,) set as decimal separator.
Background:
On my openhab host, I have set system locale to _german_.
This leads to _ping_ spitting out results in the following form:
```bash
ping detritus
PING detritus.lan (192.168.1.137): 56 data bytes
64 bytes from 192.168.1.137: icmp_seq=0 ttl=64 time=0,481 ms
64 bytes from 192.168.1.137: icmp_seq=1 ttl=64 time=0,497 ms
```
This format will be rejected by LatencyParser, as Double.parseDouble does not exprect commas in the duration values.
> [network] Fix NumberFormatException for ping when locale has comma as decimal separator

- bundles/org.openhab.binding.amplipi/pom.xml
* openapi-generator-maven-plugin, 5.1.0 to 7.0.1, see https://github.com/OpenAPITools/openapi-generator/releases
This is a follow-up on #16683, as it affects only a single binding.
@kaikreuzer I cannot get this working with current plugin version 7.5.0, there was a breaking change in 7.1.0.
> [amplipi] Update plugins

- bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/DenonMarantzStateChangedListener.java
- bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/handler/DenonMarantzHandler.java
> [denonmarantz] Interrupt running job on handler disposal

- bundles/org.openhab.persistence.mapdb/src/main/java/org/openhab/persistence/mapdb/internal/MapDbPersistenceService.java
- bundles/org.openhab.persistence.mapdb/src/test/java/org/openhab/persistence/mapdb/StateTypeAdapterTest.java
Between Java 17 and Java 21, serialization of Date has changed due to CLDR 42 which uses a narrow non-breaking space.
To ease switching JDK versions, the serialization format is explicitly set to the Java 17 format when GsonBuilder is used.
This seems the only occurrence in add-ons.
Fixes: openhab/openhab-core#4174
Depends-on: openhab/openhab-core#4185
> [mapdb] Explicitly set date format for serialization

- bundles/org.openhab.binding.mybmw/README.md
- bundles/org.openhab.binding.mybmw/src/main/java/org/openhab/binding/mybmw/internal/utils/ImageProperties.java
- bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/i18n/mybmw.properties
- bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/thing/image-channel-types.xml
- bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/thing/thing-bev.xml
- bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/thing/thing-bev_rex.xml
- bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/thing/thing-conv.xml
- bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/thing/thing-phev.xml
- bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/update/thing-update.xml
unfortunately I had to revert my changes in PR https://github.com/openhab/openhab-addons/pull/16643 as the API is working again
> [mybmw] revert the changes for 16642 as BMW seems to have reverted the changes in the API

- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/channelhelper/EventChannelHelper.java
Complete resolution of issue https://github.com/openhab/openhab-addons/issues/15883 .
Enhanced:
- vpnUrl that should never be null.
> [netatmo] Correction of Last-Event group

- bundles/org.openhab.automation.jsscripting/README.md
- bundles/org.openhab.automation.jsscripting/pom.xml
See https://github.com/openhab/openhab-js/blob/main/CHANGELOG.md#500.
Required to adjust to breaking changes from https://github.com/openhab/openhab-core/pull/3736.
> [jsscripting] Upgrade openhab-js to 5.0.0

- bundles/org.openhab.binding.tivo/README.md
fix grammar error in README introduced by #16701
> [tivo] fix README

- bundles/org.openhab.binding.serial/README.md
Added information when having one device attached
> [serial] Update README.md

- bundles/org.openhab.binding.danfossairunit/src/main/resources/OH-INF/addon/addon.xml
Depends on openhab/openhab-core#4036
> [danfossairunit] Add support for suggestion finder

- bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/DenonMarantzBindingConstants.java
- bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/handler/DenonMarantzHandler.java
Remove work-around mentioned in code comment - see https://github.com/eclipse/smarthome/pull/4787#issuecomment-362287430
> [denonmarantz] Refactor dynamic creation of zone channels

- bundles/org.openhab.binding.denonmarantz/README.md
This PR contains some minor README improvements - see individual commits.
> [denonmarantz] Improve README

- bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/LightThingHandler.java
After core changes to ColorUtil the Y part can no longer be used as brightness.
> [deconz] Fix color conversion

- bundles/org.openhab.binding.homeconnect/README.md
> [homeconnect] Remove duplicate warning

- bundles/org.openhab.binding.speedtest/README.md
Fix typing error: "bandwith" -> "bandwidth"
> README.md - "bandwith" -> "bandwidth"

- bundles/org.openhab.binding.snmp/pom.xml
- bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/SnmpServiceImpl.java
Reported on the forum: https://community.openhab.org/t/snmp-v3-passwordstring-is-null/156172
> [snmp] Upgrade SNMP4J and fix AUTH_NO_PRIV

- bundles/org.openhab.binding.haywardomnilogic/README.md
- bundles/org.openhab.binding.haywardomnilogic/src/main/java/org/openhab/binding/haywardomnilogic/internal/handler/HaywardChlorinatorHandler.java
Fixed a bug that causes the chlorinator to turn off if the salt output % channel is adjusted.  Also added colorLogicLight speed and brightness channels to README.MD.
Regression from #15478
> [haywardomnilogic] Fixed chlorinator bug

- bundles/org.openhab.binding.volumio/src/main/java/org/openhab/binding/volumio/internal/mapping/VolumioCommands.java
Fixed (#16826)
Volumio-Addon doesn't play playlists. The Problem is, that the commands sent to volumio, needs to be in camel case. This will be fixed with this PR.
> [volumio] Fix some commands not working

- bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/SystemInfoBindingConstants.java
- bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/SystemInfoHandlerFactory.java
- bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/SystemInfoThingTypeProvider.java
- bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/discovery/SystemInfoDiscoveryService.java
- bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/handler/SystemInfoHandler.java
- bundles/org.openhab.binding.systeminfo/src/main/resources/OH-INF/thing/computer.xml
This request will reduce a little bit load on garbage collector as well code complexity. 
Signed-off-by: Alexander Falkenstern [alexander.falkenstern@gmail.com](mailto:alexander.falkenstern@gmail.com)
> [systeminfo] Reduce code complexity as well garbage collection

- bundles/org.openhab.binding.energidataservice/README.md
Fix full example.
Regression of #16070
> [energidataservice] Fix UoM in documentation example

- bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/handler/BrokerHandler.java
- bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/internal/ssl/Pin.java
> [mqtt] Fix certificate pinning

- bundles/org.openhab.binding.androidtv/pom.xml
Improvements in underlying dependency and also aligning versions.
Follow up to https://github.com/openhab/openhab-addons/pull/16855
> [androidtv] Bump bouncy castle to 1.78.1

- bundles/org.openhab.binding.nibeheatpump/contrib/NibeGW/Arduino/README.md
Added build information for ProDiNo ESP32 Ethernet v1 board.
Signed-off-by: Pauli Anttila pauli.anttila@gmail.com
> [nibeheatpump] Updated NibeGW readme

- bundles/org.openhab.binding.sonyprojector/README.md
- bundles/org.openhab.binding.sonyprojector/src/main/feature/feature.xml
- bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/SonyProjectorItem.java
- bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/sdcp/SonyProjectorSdcpConnector.java
- bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/configuration/SonyProjectorEthernetConfiguration.java
- bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/configuration/SonyProjectorSerialConfiguration.java
- bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/configuration/SonyProjectorSerialOverIpConfiguration.java
- bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/discovery/SonyProjectorDiscoveryParticipant.java
- bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/handler/SonyProjectorHandler.java
- bundles/org.openhab.binding.sonyprojector/src/main/resources/OH-INF/addon/addon.xml
Only applicable to projector models having a network connector
Not tested because my projector has no network connector
> [sonyprojector] Add discovery through SDDP

- bundles/org.openhab.binding.salus/NOTICE
- bundles/org.openhab.binding.salus/pom.xml
- bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/aws/http/AwsSalusApi.java
- bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/aws/http/AwsSigner.java
- bundles/org.openhab.binding.salus/src/test/java/org/openhab/binding/salus/internal/aws/http/AwsSignerTest.java
Continuation of: https://github.com/openhab/openhab-addons/pull/16807#discussion_r1623663494
@lsiepel from the doc:
For now, I would suggest you just copy its content straight into your source code, if there will be any demand, I might publish it on [maven central](https://mvnrepository.com/repos/central).
should I do it?
If yes then should I put it in original package com.frusal.amazonsig4 or in my package?
> [salus] Salus auth

- bundles/org.openhab.binding.tado/README.md
- bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/internal/discovery/TadoDiscoveryParticipant.java
- bundles/org.openhab.binding.tado/src/main/resources/OH-INF/i18n/tado.properties
Add mDNS discovery for internet bridge thing.
> [tado] Add mDNS discovery

- bundles/org.openhab.binding.verisure/src/main/java/org/openhab/binding/verisure/internal/dto/VerisureAlarmsDTO.java
- Handling of error code list being null
Fixes #16867.
Test [jar-file](https://drive.google.com/file/d/1T-YVj-NcWO13P2x96dOrgH9yXQ8hQIo0/view?usp=sharing) OH 4.2.
> [verisure] Fix NPE (#16867)

- bundles/org.openhab.automation.jsscripting/README.md
- bundles/org.openhab.automation.jsscripting/pom.xml
See https://github.com/openhab/openhab-js/blob/main/CHANGELOG.md#510.
> [jsscripting] Upgrade openhab-js to 5.1.0

- bundles/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/internal/local/TelldusLocalBridgeHandler.java
- bundles/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/internal/local/TelldusLocalDeviceController.java
- Handling of newList being null
Fixes https://github.com/openhab/openhab-addons/issues/16869.
Test [jar-file](https://drive.google.com/file/d/1Cc0pb1kyYkgH6GG2vHbeMEtEZbU7_UNq/view?usp=sharing) OH 4.2.
> [tellstick] Fix NPE (#16869)

- bundles/org.openhab.binding.nikohomecontrol/README.md
- bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/NikoHomeControlBindingConstants.java
- bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/NikoHomeControlHandlerFactory.java
- bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/discovery/NikoHomeControlDiscoveryService.java
- bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/handler/NikoHomeControlAccessHandler.java
- bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/handler/NikoHomeControlAlarmConfig.java
- bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/handler/NikoHomeControlAlarmHandler.java
- bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/handler/NikoHomeControlMeterHandler.java
- bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/NhcAlarm.java
- bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/NhcAlarmEvent.java
- bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/NikoHomeControlCommunication.java
- bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/NikoHomeControlConstants.java
- bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc2/NhcAlarm2.java
- bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc2/NhcDevice2.java
- bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc2/NhcMqttConnection2.java
- bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc2/NikoHomeControlCommunication2.java
- bundles/org.openhab.binding.nikohomecontrol/src/main/resources/OH-INF/i18n/nikohomecontrol.properties
- bundles/org.openhab.binding.nikohomecontrol/src/main/resources/OH-INF/thing/thing-types.xml
Add support for alarm systems in Niko Home Control
> [nikohomecontrol] Alarm systems

- bundles/org.openhab.binding.shelly/README.md
See https://community.openhab.org/t/shelly-binding/56862/3864 (and thus https://community.openhab.org/t/shelly-binding/56862/3771).
> [shelly] Update README regarding discovery of BLU devices

- bundles/org.openhab.binding.energidataservice/README.md
Unfortunately I can only provide this example in JavaScript, since I have not been successful in figuring out how to use [PersistenceExtensions](https://www.openhab.org/javadoc/latest/org/openhab/core/persistence/extensions/persistenceextensions) methods from DSL.
> [energidataservice] Provide JavaScript example for persisting total price

- bundles/org.openhab.binding.bluetooth.airthings/README.md
- bundles/org.openhab.binding.bluetooth.airthings/src/main/java/org/openhab/binding/bluetooth/airthings/internal/AirthingsBindingConstants.java
- bundles/org.openhab.binding.bluetooth.airthings/src/main/java/org/openhab/binding/bluetooth/airthings/internal/AirthingsDataParser.java
- bundles/org.openhab.binding.bluetooth.airthings/src/main/java/org/openhab/binding/bluetooth/airthings/internal/AirthingsDiscoveryParticipant.java
- bundles/org.openhab.binding.bluetooth.airthings/src/main/java/org/openhab/binding/bluetooth/airthings/internal/AirthingsHandlerFactory.java
- bundles/org.openhab.binding.bluetooth.airthings/src/main/java/org/openhab/binding/bluetooth/airthings/internal/AirthingsWaveRadonHandler.java
- bundles/org.openhab.binding.bluetooth.airthings/src/main/resources/OH-INF/i18n/bluetooth.properties
- bundles/org.openhab.binding.bluetooth.airthings/src/main/resources/OH-INF/thing/airthings.xml
- bundles/org.openhab.binding.bluetooth.airthings/src/test/java/org/openhab/binding/bluetooth/airthings/AirthingsParserTest.java
Add support for model Wave Radon https://www.airthings.com/en/wave-radon
> [bluetooth.airthings] Add support for Airthings Wave Radon

- bundles/org.openhab.binding.sensibo/src/main/java/org/openhab/binding/sensibo/internal/model/SensiboModel.java
- bundles/org.openhab.binding.sensibo/src/main/java/org/openhab/binding/sensibo/internal/model/SensiboSky.java
Remove dependency on apache.commons
Untested, minor refactoring, only from code perspective
> [sensibo] Remove org.apache.common

- bundles/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/internal/TokenSearch.java
Remove dependency on apache.commons
Untested, minor refactoring, only from code perspective
> [neeo] Remove apache commons

- bundles/org.openhab.binding.ephemeris/src/main/resources/OH-INF/i18n/ephemeris.properties
> [ephemeris] Clean up i18n entries

- bundles/org.openhab.binding.mffan/src/main/resources/OH-INF/i18n/mffan.properties
> [mffan] Regenerate the i18n file

- bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/handler/AccountHandler.java
- bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/handler/VehicleHandler.java
- bundles/org.openhab.binding.mercedesme/src/test/java/org/openhab/binding/mercedesme/StatusTests.java
- bundles/org.openhab.binding.mercedesme/src/test/java/org/openhab/binding/mercedesme/internal/handler/AccountHandlerMock.java
- bundles/org.openhab.binding.mercedesme/src/test/java/org/openhab/binding/mercedesme/internal/handler/VehicleHandlerTest.java
A follow up to https://github.com/openhab/openhab-addons/pull/15628 
Refactored the `handleCommand` method and adjusted the tests. This needs some testing as i do not own a mercedes to test. 
The Thing properties hold the capabilities of the car/account. I assumed that if a car has a capability, it is listed with a `true` value. Unfortunately the tests where inconclusive so please double check @weymann
> [mercedesme] Refactor code and fix test

- bundles/org.openhab.automation.jsscripting/README.md
- bundles/org.openhab.automation.jsscripting/pom.xml
Adds support for https://github.com/openhab/openhab-core/pull/4259.
> [jsscripting] Upgrade openhab-js to 5.2.0

- bundles/org.openhab.binding.mybmw/README.md
- bundles/org.openhab.binding.mybmw/src/main/java/org/openhab/binding/mybmw/internal/MyBMWConstants.java
- bundles/org.openhab.binding.mybmw/src/main/java/org/openhab/binding/mybmw/internal/handler/enums/RemoteService.java
- bundles/org.openhab.binding.mybmw/src/test/java/org/openhab/binding/mybmw/internal/dto/VehiclePropertiesTest.java
This PR enables to start and stop charging the EV
> [mybmw] add stop charging command

- bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/NotificationAction.java
- bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudClient.java
- bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudService.java
- bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/actions/BaseNotificationActionHandler.java
- bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/actions/NotificationActionTypeProvider.java
- bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/actions/NotificationModuleHandlerFactory.java
- bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/actions/SendBroadcastNotificationActionHandler.java
- bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/actions/SendNotificationActionHandler.java
> [openhabcloud] Enhanced Notification Actions

- bundles/org.openhab.binding.livisismarthome/README.md
- bundles/org.openhab.binding.livisismarthome/src/main/java/org/openhab/binding/livisismarthome/internal/LivisiBindingConstants.java
- bundles/org.openhab.binding.livisismarthome/src/main/java/org/openhab/binding/livisismarthome/internal/client/LivisiClient.java
- bundles/org.openhab.binding.livisismarthome/src/main/java/org/openhab/binding/livisismarthome/internal/client/api/entity/action/ActionParamsDTO.java
- bundles/org.openhab.binding.livisismarthome/src/main/java/org/openhab/binding/livisismarthome/internal/client/api/entity/action/StateActionSetterDTO.java
- bundles/org.openhab.binding.livisismarthome/src/main/java/org/openhab/binding/livisismarthome/internal/client/api/entity/capability/CapabilityDTO.java
- bundles/org.openhab.binding.livisismarthome/src/main/java/org/openhab/binding/livisismarthome/internal/client/api/entity/capability/CapabilityStateDTO.java
- bundles/org.openhab.binding.livisismarthome/src/main/java/org/openhab/binding/livisismarthome/internal/client/api/entity/event/EventPropertiesDTO.java
- bundles/org.openhab.binding.livisismarthome/src/main/java/org/openhab/binding/livisismarthome/internal/handler/LivisiBridgeHandler.java
- bundles/org.openhab.binding.livisismarthome/src/main/java/org/openhab/binding/livisismarthome/internal/handler/LivisiDeviceHandler.java
- bundles/org.openhab.binding.livisismarthome/src/main/resources/OH-INF/thing/SIR.xml
- bundles/org.openhab.binding.livisismarthome/src/main/resources/OH-INF/thing/channels.xml
Adds support for the indoor siren device.
This change solves issue #16533, see issue #16533
> [livisismarthome] Add support for the indoor siren device

- CODEOWNERS
- bom/openhab-addons/pom.xml
- bundles/org.openhab.binding.teslapowerwall/NOTICE
- bundles/org.openhab.binding.teslapowerwall/README.md
- bundles/org.openhab.binding.teslapowerwall/pom.xml
- bundles/org.openhab.binding.teslapowerwall/src/main/feature/feature.xml
- bundles/org.openhab.binding.teslapowerwall/src/main/java/org/openhab/binding/teslapowerwall/internal/TeslaPowerwallAuthenticationException.java
- bundles/org.openhab.binding.teslapowerwall/src/main/java/org/openhab/binding/teslapowerwall/internal/TeslaPowerwallBindingConstants.java
- bundles/org.openhab.binding.teslapowerwall/src/main/java/org/openhab/binding/teslapowerwall/internal/TeslaPowerwallCommunicationException.java
- bundles/org.openhab.binding.teslapowerwall/src/main/java/org/openhab/binding/teslapowerwall/internal/TeslaPowerwallConfiguration.java
- bundles/org.openhab.binding.teslapowerwall/src/main/java/org/openhab/binding/teslapowerwall/internal/TeslaPowerwallHandler.java
- bundles/org.openhab.binding.teslapowerwall/src/main/java/org/openhab/binding/teslapowerwall/internal/TeslaPowerwallHandlerFactory.java
- bundles/org.openhab.binding.teslapowerwall/src/main/java/org/openhab/binding/teslapowerwall/internal/TeslaPowerwallTlsTrustManagerProvider.java
- bundles/org.openhab.binding.teslapowerwall/src/main/java/org/openhab/binding/teslapowerwall/internal/TeslaPowerwallWebTargets.java
- bundles/org.openhab.binding.teslapowerwall/src/main/java/org/openhab/binding/teslapowerwall/internal/api/BatterySOE.java
- bundles/org.openhab.binding.teslapowerwall/src/main/java/org/openhab/binding/teslapowerwall/internal/api/GridStatus.java
- bundles/org.openhab.binding.teslapowerwall/src/main/java/org/openhab/binding/teslapowerwall/internal/api/MeterAggregates.java
- bundles/org.openhab.binding.teslapowerwall/src/main/java/org/openhab/binding/teslapowerwall/internal/api/Operations.java
- bundles/org.openhab.binding.teslapowerwall/src/main/java/org/openhab/binding/teslapowerwall/internal/api/SystemStatus.java
- bundles/org.openhab.binding.teslapowerwall/src/main/resources/OH-INF/addon/addon.xml
- bundles/org.openhab.binding.teslapowerwall/src/main/resources/OH-INF/i18n/teslapowerwall.properties
- bundles/org.openhab.binding.teslapowerwall/src/main/resources/OH-INF/thing/thing-types.xml
- bundles/pom.xml
[teslapowerwall] Initial Contribution - replaces https://github.com/openhab/openhab-addons/pull/16667
> [teslapowerwall] Initial contribution 

- bundles/org.openhab.binding.ecovacs/src/main/resources/devices/supported_device_list.json
> [ecovacs] Add DEEBOT T20e to supported device list

- bundles/org.openhab.automation.jsscripting/README.md
- bundles/org.openhab.automation.jsscripting/pom.xml
This adds the new notification builder.
> [jsscripting] Upgrade openhab-js to 5.3.0

- bundles/org.openhab.binding.energidataservice/README.md
@florian-h05 I think this was changed in the latest js helper?
> [energidataservice] Update JS example

- bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/handler/VehicleHandler.java
- bundles/org.openhab.binding.mercedesme/src/test/java/org/openhab/binding/mercedesme/internal/handler/VehicleHandlerTest.java
> [mercedesme] bugfix websocket exception after sending command

- bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/SystemInfoBindingConstants.java
- bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/SystemInfoHandlerFactory.java
Fixes https://github.com/openhab/openhab-addons/issues/16965
> [systeminfo] Fix startup of existing thing type config

- bundles/org.openhab.binding.mail/README.md
[mail] fix documentation
See this https://community.openhab.org/t/javascript-val-mail-binding-documentation/156928/4
> [mail] Fix documentation bug

- bundles/org.openhab.persistence.mongodb/src/main/java/org/openhab/persistence/mongodb/internal/MongoDBTypeConversions.java
Related to https://github.com/openhab/openhab-core/pull/4257
> [mongodb] Fix handling of GroupItems on restore

- bundles/org.openhab.binding.homeconnect/README.md
Added note for possible occurrence of 403 error during application registration in homeconnect developer portal and recommended a solution to resolve the error.
I ran into the issue that the homeconnect developer portal refused the registration of a new application. It gave me a 403 error and multiple devices, browsers and OS and I had a hard time to find the actual cause. Entering the hostname in the `uri` field did the trick. I haven't manged to find out why IPs are apparently not allowed, but I thought it might help other users to not despair.
> [homeconnect] Update README.md

- bundles/org.openhab.automation.jsscripting/README.md
- bundles/org.openhab.automation.jsscripting/pom.xml
> [jsscripting] Upgrade to openhab-js 5.3.1

- bundles/org.openhab.automation.jsscripting/README.md
This fixes the notification builder examples in the docs.
> [jsscripting] Fix notification builder examples

- bundles/org.openhab.binding.growatt/README.md
This PR extends and improves the documentation for example rule actions.
> [growatt] Improved and extended documentation examples

- bundles/org.openhab.binding.energidataservice/README.md
Some minor tweaks:
- Like in JRuby examples, include `actions` object.
- Add comment in JRuby example like in others.
- Some tabs to spaces previously missed.
> [energidataservice] Increase consistency between examples

- bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/internal/handler/DigiplexBridgeHandler.java
- bundles/org.openhab.binding.pentair/src/main/java/org/openhab/binding/pentair/internal/handler/PentairIntelliFloHandler.java
- bundles/org.openhab.binding.sonyaudio/src/main/java/org/openhab/binding/sonyaudio/internal/protocol/SonyAudioClientSocket.java
- bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/api/protocol/aes/SecurePasstroughCipher.java
- bundles/org.openhab.binding.verisure/src/main/java/org/openhab/binding/verisure/internal/VerisureSession.java
Hi,
Thanks for approving [PR#16984](https://github.com/openhab/openhab-addons/pull/16984). Really hope my contribution can make openhab-addons more perfect, though the contribution is incremental.
I further reviewed some source code and logging messages and found some typos and some inaccurate expression of the relation between the logging statement and its corresponding action in the source code.
1.  typo `Intellflo` -> `Intelliflo` based on the surrounding code
2. typo `fo` -> `for`
3. typo `initChiper` -> `initCipher` based on the surrounding code
4. some inaccurate expression of the relation, change `started` -> `starting`
> Fix logging statements

- bundles/org.openhab.binding.argoclima/README.md
- standalone code fences de-indented (as-is displays poorly ref: https://next.openhab.org/addons/bindings/argoclima/#full-example)
- changed link to Argo Smart APP to YT playlist (official vendor's link seems EOLed)
- other minor editorials
> [argoclima] Editorial fixes in README.md

- bundles/org.openhab.io.openhabcloud/README.md
> [openhabcloud] Fix typo in Readme

- bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/handler/AwattarPriceHandler.java
Fixes #17027 
Should be backported to 4.2.x
> [awattar] Fix price handler refresh

- bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/Constants.java
- bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/handler/VehicleHandler.java
- bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/server/MBWebsocket.java
- bundles/org.openhab.binding.mercedesme/src/main/resources/OH-INF/thing/charge-channel-types.xml
- bundles/org.openhab.binding.mercedesme/src/test/java/org/openhab/binding/mercedesme/internal/handler/VehicleHandlerTest.java
- bundles/org.openhab.binding.mercedesme/src/test/resources/proto-json/MB-BEV-EQA-Charging-Weekday-Underrun.json
- bundles/org.openhab.binding.mercedesme/src/test/resources/proto-json/MB-BEV-EQA-Charging-Weekday.json
> [mercedesme] take end of charge weekday into account

- bundles/org.openhab.voice.googlestt/src/main/resources/OH-INF/i18n/googlestt.properties
- bundles/org.openhab.voice.googletts/src/main/resources/OH-INF/i18n/googletts.properties
- bundles/org.openhab.voice.mactts/src/main/resources/OH-INF/i18n/mactts.properties
- bundles/org.openhab.voice.marytts/src/main/resources/OH-INF/i18n/marytts.properties
- bundles/org.openhab.voice.mimictts/src/main/resources/OH-INF/i18n/mimictts.properties
- bundles/org.openhab.voice.picotts/src/main/resources/OH-INF/i18n/picotts.properties
- bundles/org.openhab.voice.pollytts/src/main/resources/OH-INF/i18n/pollytts.properties
- bundles/org.openhab.voice.voicerss/src/main/resources/OH-INF/i18n/voicerss.properties
- bundles/org.openhab.voice.voskstt/src/main/resources/OH-INF/i18n/voskstt.properties
- bundles/org.openhab.voice.watsonstt/src/main/resources/OH-INF/i18n/watsonstt.properties
> Fix i18n entry matching the add-on name for voice add-ons

- bundles/org.openhab.io.homekit/src/main/resources/OH-INF/i18n/homekit.properties
- bundles/org.openhab.io.hueemulation/src/main/resources/OH-INF/i18n/hueemulation.properties
- bundles/org.openhab.io.metrics/src/main/resources/OH-INF/i18n/metrics.properties
- bundles/org.openhab.io.neeo/src/main/resources/OH-INF/i18n/neeo.properties
- bundles/org.openhab.io.openhabcloud/src/main/resources/OH-INF/i18n/openhabcloud.properties
> Fix i18n entry matching the add-on name for io add-ons

- bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/discovery/FreeboxOsDiscoveryService.java
> [freeboxos] Fix macAddress property when discovering a server

- bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/ApiConsumerHandler.java
This was bypassed in bridgeStatusChanged.
Fix #17078
Fix #17079
> [freeboxos] Fix creation of properties and dynamic channels at init

- bundles/org.openhab.binding.sensibo/src/main/java/org/openhab/binding/sensibo/internal/CallbackChannelsTypeProvider.java
- bundles/org.openhab.binding.sensibo/src/main/java/org/openhab/binding/sensibo/internal/handler/SensiboSkyHandler.java
- bundles/org.openhab.binding.sensibo/src/main/java/org/openhab/binding/sensibo/internal/model/SensiboModel.java
- bundles/org.openhab.binding.sensibo/src/test/java/org/openhab/binding/sensibo/internal/SensiboModelTest.java
- bundles/org.openhab.binding.sensibo/src/test/java/org/openhab/binding/sensibo/internal/handler/SensiboSkyHandlerTest.java
- bundles/org.openhab.binding.sensibo/src/test/resources/get_pod_details_response_valter.json
Ref https://community.openhab.org/t/sensibo-binding-4-2-does-not-work/157116
> [sensibo] Fix channel provider throwing exception

- bundles/org.openhab.binding.monopriceaudio/src/main/java/org/openhab/binding/monopriceaudio/internal/communication/AmplifierModel.java
Follow up to #16991, fix remaining compiler warning.
> [monopriceaudio] fix compiler warning

- bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/handler/AwattarBestPriceHandler.java
This PR fixes the countdown and remaining channels stuck in "undef".
The channels would not get updated when the conditions are not met and the default is UNDEF.
> [aWATTar] Fix countdown and remaining channels

- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitTemperatureSensorImpl.java
so that it automatically gets the proper unit handling like Thermostat
> [homekit] Use characteristic factory for TemperatureSensor

- features/openhab-addons/src/main/resources/footer.xml
Add binding reference to 'footer.xml'
Resolves #17102 
> [bluetooth.grundfosalpha] Add to footer.xml

- bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/DSCAlarmMessage.java
- bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/discovery/DSCAlarmBridgeDiscovery.java
- bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/discovery/EnvisalinkBridgeDiscovery.java
- bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/handler/DSCAlarmBaseBridgeHandler.java
- bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/handler/EnvisalinkBridgeHandler.java
- bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/handler/IT100BridgeHandler.java
- bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/handler/TCPServerBridgeHandler.java
See https://community.openhab.org/t/dscalarm-spamming-log/155552
> [dscalarm] Add details in bridge handler error log to help find the problem

- bundles/org.openhab.io.homekit/README.md
> [homekit] use java, not xtend, for code fences in README

- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitOHItemProxy.java
> [homekit] Fix linking a Lighting to a Group:Dimmer

- bundles/org.openhab.io.homekit/README.md
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitTaggedItem.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/AbstractHomekitPositionAccessoryImpl.java
> [homekit] Support UP/DOWN for WindowCoverings

- bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/api/rest/WebSocketManager.java
> [freeboxos] Fix websocket registration

- bundles/org.openhab.binding.sensibo/src/main/java/org/openhab/binding/sensibo/internal/handler/SensiboAccountHandler.java
- bundles/org.openhab.binding.sensibo/src/test/java/org/openhab/binding/sensibo/internal/handler/SensiboAccountHandlerTest.java
> [sensibo] Add test for Accept-Encoding header

- bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/discovery/FreeboxOsDiscoveryService.java
Avoid an interrupted discovery because getting a kind of devices is failing.
> [freeboxos] Avoid partial discovery

- bundles/org.openhab.binding.ism8/README.md
Currently, ism8 documentation lacks the embedded image.
The image seems to be missed by the automatic collection of files when the docs are generated.
Hopefully, this change fixes the issue. Other bindings like the mercedesme binding use the tag ```img src``` as well. All other bindings use ```./docs/``` instread of ```docs/```.
> [ism8] Fix broken image in docs

- bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/ApiConsumerHandler.java
- bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/HostHandler.java
- bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/VmHandler.java
> [freeboxos] Fix handling of REFRESH command for connectivity channels

- bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/GreeCryptoUtil.java
- bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/discovery/GreeDeviceFinder.java
- bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/gson/GreeBaseDTO.java
- bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/gson/GreeBindRequestPackDTO.java
- bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/gson/GreeBindResponseDTO.java
- bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/gson/GreeBindResponsePackDTO.java
- bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/gson/GreeExecResponseDTO.java
- bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/gson/GreeExecResponsePackDTO.java
- bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/gson/GreeExecuteCommandPackDTO.java
- bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/gson/GreeReqStatusDTO.java
- bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/gson/GreeReqStatusPackDTO.java
- bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/gson/GreeRequestDTO.java
- bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/gson/GreeResponseBaseDTO.java
- bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/gson/GreeScanRequestDTO.java
- bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/gson/GreeScanResponseDTO.java
- bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/gson/GreeScanResponsePackDTO.java
- bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/gson/GreeStatusResponseDTO.java
- bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/gson/GreeStatusResponsePackDTO.java
- bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/handler/GreeAirDevice.java
New Gree AC uses ASC/GCM encryption and different general key Fixes #16949
Fixes #16949
Link to a built [JAR](https://file.io/EzSrZOZaFIVy) file
> [gree] Add support for ASC/GCM encryption

- bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/connector/http/DenonMarantzHttpConnector.java
Reported here: https://community.openhab.org/t/anyone-using-the-denon-marantz-binding-willing-to-help-with-a-few-tests/156042/25
Regression of #16757
> [denonmarantz] Fix clearing Now Playing channels

- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/PicoKeypadHandler.java
> [lutron] Fix Pico buttons for non-LEAP bridges

- bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/config/player-config.xml
- bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/i18n/freeboxos.properties
> [freeboxos] Remove unneeded thing config parameter

- bundles/org.openhab.binding.awattar/README.md
- bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/handler/AwattarBridgeHandler.java
- bundles/org.openhab.binding.awattar/src/main/resources/OH-INF/config/config.xml
- bundles/org.openhab.binding.awattar/src/main/resources/OH-INF/thing/thing-types.xml
- bundles/org.openhab.binding.awattar/src/main/resources/OH-INF/update/update.xml
- bundles/org.openhab.binding.awattar/src/test/java/org/openhab/binding/awattar/internal/handler/AwattarBridgeHandlerRefreshTest.java
- bundles/org.openhab.binding.awattar/src/test/java/org/openhab/binding/awattar/internal/handler/AwattarBridgeHandlerTest.java
This adds TieSeries support to the Awattar binding. Follow-up to #16871 
> [awattar] Add TimeSeries support

- bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/api/rest/PlayerManager.java
Resolves issue #17216 
Wrong exception catched
> [freeboxos] Sending a remote key to player generates an IAE

- bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/thing/channel-types.xml
> [freeboxos] Enhance state display pattern for uptime

- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyApiResult.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyDeviceProfile.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyEventServlet.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api1/Shelly1HttpApi.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiClient.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiRpc.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2RpcSocket.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/ShellyBluApi.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/discovery/ShellyBasicDiscoveryService.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyBaseHandler.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyColorUtils.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyComponents.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyLightHandler.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyThingTable.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/manager/ShellyManagerCache.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/manager/ShellyManagerPage.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/provider/ShellyChannelDefinitions.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/provider/ShellyStateDescriptionProvider.java
- bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/i18n/shelly.properties
Fix all compiler and SAT warnings, mainly related to null annotations and potential `NullPointerExceptions`. This will make it easier to detect when new warnings are introduced.
> [shelly] Fix compiler warnings

- bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/ApiConsumerHandler.java
- bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/HostHandler.java
> [freeboxos] Fix start/stop audio sink

- bundles/org.openhab.io.openhabcloud/README.md
Adds new 'rule' and 'app' actions to the docs for mobile push notifications
See #16934
> [openhabcloud] Update Docs : rules and app actions

- bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/api/rest/FreeboxOsSession.java
- bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/api/rest/WebSocketManager.java
Checks if the server supports VM.
Replace #17124 which was more a workaround.
> [freeboxos] Better fix for WEB socket registration

- bundles/org.openhab.binding.freeboxos/README.md
- bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/action/ActivePlayerActions.java
- bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/action/CallActions.java
- bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/action/FreeplugActions.java
- bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/action/HostActions.java
- bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/action/PlayerActions.java
- bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/action/RepeaterActions.java
- bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/action/ServerActions.java
Also rename actions to avoid name conflicts.
Fix #17225
> [freeboxos] Fix actions to make them available in DSL rules

- bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/ActivePlayerHandler.java
- bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/ApiConsumerHandler.java
- bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/HostHandler.java
- bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/RepeaterHandler.java
- bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/VmHandler.java
- bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/WifiStationHandler.java
- bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/i18n/freeboxos.properties
> [freeboxos] Fix thing status handling when rebooting the player

- bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/JSONSchemaLight.java
- bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Light.java
- bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/JSONSchemaLightTests.java
See https://github.com/home-assistant/core/pull/111676
Fixes #17184
> [mqtt.homeassistant] Fix color lights that don't specify color_mode: true

- bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/RevolutionHandler.java
> [freeboxos] Avoid a call to the lcd API when not required

- bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/FreeboxOsBindingConstants.java
- bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/api/rest/ConnectionManager.java
- bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/ServerHandler.java
- bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/i18n/freeboxos.properties
- bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/thing/channel-types.xml
- bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/thing/server-channel-groups.xml
- bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/update/instructions.xml
> [freeboxos] Add channels in group xdsl

- bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/WLedHelper.java
- bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/api/WledApiV084.java
- bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/handlers/WLedSegmentHandler.java
> [wled] Fix brightness inconsistency + power on

- bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/api/rest/MediaReceiverManager.java
> [freeboxos] Keep enum in API response record DTO (play media)

- bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/api/rest/AfpManager.java
Partial revert of #17203
Signed-off-by: Laurent Garnier <lg.hc@ree.fr>
> [freeboxos] Restore enum in API response record DTO (MacOS file sharing)

- bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/handlers/WLedSegmentHandler.java
> [wled] Fix: FX and Palettes channel StateDescriptionProvider handling

- bundles/org.openhab.binding.telegram/src/main/java/org/openhab/binding/telegram/internal/TelegramHandler.java
Resolves: https://github.com/openhab/openhab-addons/issues/17113
Test jar (openHAB 4.2.0) https://1drv.ms/u/s!AnMcxmvEeupwjvsHyGFM4f3IfgiI-g?e=9ZPr7k
> [telegram] Fix log spamming when transient network issue occurs

- bundles/org.openhab.binding.govee/src/main/java/org/openhab/binding/govee/internal/CommunicationManager.java
fixes #17101
It is completely unclear even after a four eyes review why the socket would be closed. I will provide a patch that at least should make it more resilient.
> [govee] make socket close more resilient

- bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/config/PhoneConfigurationBuilder.java
- bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/discovery/FreeboxOsDiscoveryService.java
- bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/i18n/freeboxos.properties
> [freeboxos] Add translatable labels for discovered things

- bundles/org.openhab.persistence.jpa/src/main/java/org/openhab/persistence/jpa/internal/JpaHistoricItem.java
`Double.parseDouble` throws `NumberFormatException` if the persisted state includes a unit. So parse it as a `QuantityType`, and then apply unit conversions as necessary.
Without this, I was getting the following error when using `lastChange()` in a rule:
```
024-08-07 16:33:43.591 [ERROR] [e.jpa.internal.JpaPersistenceService] - Error while querying database!
java.lang.NumberFormatException: For input string: "2 gal/min"
at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054) ~[?:?]
at jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:?]
at java.lang.Double.parseDouble(Double.java:651) ~[?:?]
at org.openhab.persistence.jpa.internal.JpaHistoricItem.fromPersistedItem(JpaHistoricItem.java:108) ~[?:?]
at …
```
> [jpa] Fix restoring quantity types

- bundles/org.openhab.binding.airq/src/main/java/org/openhab/binding/airq/internal/AirqHandler.java
In rare cases the sensor sends a null value in the JSON data, which lead to a crash of the poller task.
Also:
- Remove trace debugging statements
- Handle InterruptedException correctly
- Replace substring parsing by GSON functionality
Fixes #17164
> [airq] Fix occasional stalling of sensor value updates and refactoring

- bundles/org.openhab.binding.freeboxos/README.md
- bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/FreeboxOsHandlerFactory.java
- bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/api/ApiHandler.java
- bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/addon/addon.xml
> [freeboxos] Change default timeout to 10s

- bundles/org.openhab.binding.solarforecast/src/main/java/org/openhab/binding/solarforecast/internal/forecastsolar/ForecastSolarObject.java
- bundles/org.openhab.binding.solarforecast/src/main/java/org/openhab/binding/solarforecast/internal/solcast/SolcastObject.java
- bundles/org.openhab.binding.solarforecast/src/test/java/org/openhab/binding/solarforecast/ForecastSolarTest.java
- bundles/org.openhab.binding.solarforecast/src/test/java/org/openhab/binding/solarforecast/SolcastTest.java
> [solarforecast] Avoid past data updates

- bundles/org.openhab.automation.jsscripting/pom.xml
See https://github.com/openhab/openhab-js/blob/main/CHANGELOG.md#550 for changelog.
> [jsscripting] Upgrade to openhab-js 5.5.0

- bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosXMLParser.java
- bundles/org.openhab.binding.sonos/src/test/java/org/openhab/binding/sonos/internal/SonosXMLParserTest.java
> [sonos] Ignore Sonos Boost at discovery

- bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/DectHandler.java
- bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/FxsHandler.java
Avoids API requests when channels are unlinked.
> [freeboxos] Avoid useless API requests (phone)

- bundles/org.openhab.transform.map/src/main/java/org/openhab/transform/map/internal/profiles/MapTransformationProfile.java
This adds timeseries support to map transformation. Tested with openweathermap binding.
> [transform.map] Add time series support

- bundles/org.openhab.binding.tibber/src/main/java/org/openhab/binding/tibber/internal/handler/TibberHandler.java
New Pull request for PR https://github.com/openhab/openhab-addons/pull/17214
After changing the Log Level to Debug I was not able to see something in the logs. Also a Thread Dump could not give me a hint to the error.
So it is not a real fix, but the WebSocket should be reconnect after the Tibber WebSocket connection received no data for 5 minutes.
Fixes https://github.com/openhab/openhab-addons/issues/14735
> [Tibber] Improve connection logic

- bundles/org.openhab.binding.mqtt.homeassistant/pom.xml
- bundles/org.openhab.transform.jinja/NOTICE
- bundles/org.openhab.transform.jinja/pom.xml
- bundles/org.openhab.transform.jinja/src/main/feature/feature.xml
Depends on https://github.com/openhab/openhab-osgiify/pull/48
> [jinja] Use osgiified Jinjava

- bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/MappingJsonReader.java
Just copy pasted from https://github.com/home-assistant/core/blob/dev/homeassistant/components/mqtt/abbreviations.py
> [mqtt.homeassistant] Update config abbreviations

- bundles/org.openhab.binding.smartmeter/src/main/java/org/openhab/binding/smartmeter/SmartMeterConfiguration.java
- bundles/org.openhab.binding.smartmeter/src/main/java/org/openhab/binding/smartmeter/internal/MeterDevice.java
- bundles/org.openhab.binding.smartmeter/src/main/java/org/openhab/binding/smartmeter/internal/MeterDeviceFactory.java
- bundles/org.openhab.binding.smartmeter/src/main/java/org/openhab/binding/smartmeter/internal/MeterValue.java
- bundles/org.openhab.binding.smartmeter/src/main/java/org/openhab/binding/smartmeter/internal/ObisCode.java
- bundles/org.openhab.binding.smartmeter/src/main/java/org/openhab/binding/smartmeter/internal/SmartMeterChannelTypeProvider.java
- bundles/org.openhab.binding.smartmeter/src/main/java/org/openhab/binding/smartmeter/internal/SmartMeterHandler.java
- bundles/org.openhab.binding.smartmeter/src/main/java/org/openhab/binding/smartmeter/internal/conformity/Conformity.java
- bundles/org.openhab.binding.smartmeter/src/main/java/org/openhab/binding/smartmeter/internal/conformity/negate/NegateHandler.java
- bundles/org.openhab.binding.smartmeter/src/main/java/org/openhab/binding/smartmeter/internal/iec62056/MeterReader.java
- bundles/org.openhab.binding.smartmeter/src/main/java/org/openhab/binding/smartmeter/internal/iec62056/SerialConnector.java
- bundles/org.openhab.binding.smartmeter/src/main/java/org/openhab/binding/smartmeter/internal/iec62056/UnitConversion.java
- bundles/org.openhab.binding.smartmeter/src/main/java/org/openhab/binding/smartmeter/internal/sml/SmlFileDebugOutput.java
- bundles/org.openhab.binding.smartmeter/src/main/java/org/openhab/binding/smartmeter/internal/sml/SmlSerialConnector.java
- bundles/org.openhab.binding.smartmeter/src/test/java/org/openhab/binding/smartmeter/MockMeterReaderConnector.java
- bundles/org.openhab.binding.smartmeter/src/test/java/org/openhab/binding/smartmeter/TestMeterReading.java
- bundles/org.openhab.binding.smartmeter/src/test/java/org/openhab/binding/smartmeter/TestNegateBit.java
- Fixes: https://github.com/openhab/openhab-addons/issues/12488
- Reduces compile warnings
- Reduces SAT errors
Should not have any functional changes.
Test JAR (openHAB 4.2.0+): https://1drv.ms/u/s!AnMcxmvEeupwjvsrpKKdb2NBpVOb7A?e=chUYjm
> [smartmeter] Fix Undelivered IOException

- itests/org.openhab.binding.hue.tests/itest.bndrun
- itests/org.openhab.binding.tradfri.tests/itest.bndrun
Adapt itests to core, see openhab/openhab-core#4337.
> Upgrade to JmDNS 3.5.12

- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/data/ChannelGroup.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/HomeEvent.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/ApiBridgeHandler.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/CameraCapability.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/PersonCapability.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/channelhelper/EventCameraChannelHelper.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/channelhelper/EventChannelHelper.java
- bundles/org.openhab.binding.netatmo/src/main/resources/OH-INF/i18n/netatmo.properties
> [netatmo] Fix doorbell channels flapping

- bundles/org.openhab.binding.netatmo/README.md
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/SecurityApi.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/data/ModuleType.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/PresenceCapability.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/SecurityCapability.java
- bundles/org.openhab.binding.netatmo/src/main/resources/OH-INF/thing/security.xml
- bundles/org.openhab.binding.netatmo/src/main/resources/OH-INF/update/instructions.xml
Resolves issue #16707 
This channel is not supported by Netatmo API in write mode.
> [netatmo] Switching siren channel of the Presence to Read-Only

- bundles/org.openhab.binding.mqtt.homeassistant/README.md
- bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Fan.java
- bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/FanTests.java
Percentage/speed control (replaces on/off channel if it's supported), oscillation, direction, and preset_mode channels.
> [mqtt.homeassistant] Fully implement Fan component

- bundles/org.openhab.binding.pihole/README.md
- bundles/org.openhab.binding.pihole/src/main/java/org/openhab/binding/pihole/internal/PiHoleBindingConstants.java
- bundles/org.openhab.binding.pihole/src/main/java/org/openhab/binding/pihole/internal/PiHoleHandler.java
- bundles/org.openhab.binding.pihole/src/main/java/org/openhab/binding/pihole/internal/PiHoleHandlerFactory.java
- bundles/org.openhab.binding.pihole/src/main/resources/OH-INF/thing/thing-types.xml
- bundles/org.openhab.binding.pihole/src/main/resources/OH-INF/update/gravity.xml
Added channels for gravity
https://community.openhab.org/t/pi-hole-binding-add-new-feature-gravity-last-updated/158331/2
> [pihole] Add channels for gravity

- bundles/org.openhab.automation.jsscripting/README.md
- bundles/org.openhab.automation.jsscripting/pom.xml
Also sync webpack dependency with openhab-js package.json.
Changelog can be found here: https://github.com/openhab/openhab-js/blob/main/CHANGELOG.md#560.
> [jsscripting] Upgrade to openhab-js 5.6.0

- bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/handler/UniFiPoePortThingHandler.java
- Fixes https://github.com/openhab/openhab-addons/issues/15850
> [unifi] Fix `NullPointerException`

- bundles/org.openhab.persistence.jdbc/src/main/feature/feature.xml
Solves issue with distro build
> [jdbc] revert db version variables

- bundles/org.openhab.automation.groovyscripting/README.md
- bundles/org.openhab.automation.groovyscripting/pom.xml
Updates Groovy from 4.0.22 to 4.0.23.
For all bugfixes and improvements, see:
* https://groovy-lang.org/changelogs/changelog-4.0.23.html
> [groovyscripting] Update Groovy to 4.0.23

- bundles/org.openhab.binding.gce/src/main/java/org/openhab/binding/gce/internal/handler/Ipx800DeviceConnector.java
> [gce] Fix `NullPointerException`

- bundles/org.openhab.binding.smaenergymeter/src/main/java/org/openhab/binding/smaenergymeter/internal/SMAEnergyMeterHandlerFactory.java
- bundles/org.openhab.binding.smaenergymeter/src/main/java/org/openhab/binding/smaenergymeter/internal/discovery/SMAEnergyMeterDiscoveryService.java
- bundles/org.openhab.binding.smaenergymeter/src/main/java/org/openhab/binding/smaenergymeter/internal/handler/EnergyMeter.java
- bundles/org.openhab.binding.smaenergymeter/src/main/java/org/openhab/binding/smaenergymeter/internal/handler/SMAEnergyMeterHandler.java
- bundles/org.openhab.binding.smaenergymeter/src/main/java/org/openhab/binding/smaenergymeter/internal/packet/DefaultPacketListenerRegistry.java
- bundles/org.openhab.binding.smaenergymeter/src/main/java/org/openhab/binding/smaenergymeter/internal/packet/PacketListener.java
- Fixes : https://github.com/openhab/openhab-addons/issues/17280
- Added null annotations
- Replaced some Multicast deprecated methods
- Fix SAT warnings
Test jar 4.2.1+: https://1drv.ms/u/s!AnMcxmvEeupwjv9m9osRyk-2jY9whA?e=ICEKNF
Confirmed to be a working fix, thanks @Hoerli1337
> [smaenergymeter] Fix `IllegalStateException`

- bundles/org.openhab.automation.jsscripting/README.md
- bundles/org.openhab.automation.jsscripting/pom.xml
Changelog can be found here: https://github.com/openhab/openhab-js/blob/main/CHANGELOG.md#570
> [jsscripting] Upgrade openhab-js to 5.7.0

- bundles/org.openhab.binding.smsmodem/README.md
Adding some devices to work/doesn't work lists
> [smsmodem] Update README.md with devices

- bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/service/SmartThingsApiService.java
Extracted from https://github.com/openhab/openhab-addons/pull/17368
Fixes: https://github.com/openhab/openhab-addons/issues/17228
Can be backported to 4.2.x
> [samsungtv] Fix `NullPointerException`

- bundles/org.openhab.binding.benqprojector/README.md
- bundles/org.openhab.binding.benqprojector/src/main/resources/OH-INF/thing/thing-types.xml
Set autoUpdatePolicy=veto for `directcmd` channel
> [benqprojector] Set autoUpdatePolicy for directcmd channel

- bundles/org.openhab.binding.epsonprojector/README.md
- bundles/org.openhab.binding.epsonprojector/src/main/resources/OH-INF/thing/thing-types.xml
Set autoUpdatePolicy=veto for `keycode` channel
> [epsonprojector] Set autoUpdatePolicy for keycode channel

- bundles/org.openhab.binding.atlona/src/main/resources/OH-INF/thing/thing-types.xml
Set autoUpdatePolicy=veto for WriteOnly channels
> [atlona] Set autoUpdatePolicy for WriteOnly channels

- bundles/org.openhab.binding.nuvo/README.md
- bundles/org.openhab.binding.nuvo/src/main/resources/OH-INF/thing/channels.xml
Set autoUpdatePolicy=veto for WriteOnly channels
> [nuvo] Set autoUpdatePolicy for WriteOnly channels

- bundles/org.openhab.binding.panasonicbdp/README.md
- bundles/org.openhab.binding.panasonicbdp/src/main/resources/OH-INF/thing/bdplayer.xml
- bundles/org.openhab.binding.panasonicbdp/src/main/resources/OH-INF/thing/uhdplayer.xml
Set autoUpdatePolicy=veto for `button` channel
> [panasonicbdp] Set autoUpdatePolicy for button channel

- bundles/org.openhab.binding.roku/README.md
- bundles/org.openhab.binding.roku/src/main/resources/OH-INF/thing/roku.xml
Set autoUpdatePolicy=veto for `button` channel
> [roku] Set autoUpdatePolicy for button channel

- bundles/org.openhab.binding.tivo/README.md
- bundles/org.openhab.binding.tivo/src/main/resources/OH-INF/thing/thing-types.xml
Set autoUpdatePolicy=veto for WriteOnly channels
> [tivo] Set autoUpdatePolicy for WriteOnly channels

- bundles/org.openhab.binding.vizio/README.md
- bundles/org.openhab.binding.vizio/src/main/resources/OH-INF/thing/vizio.xml
Set autoUpdatePolicy=veto for `button` channel
> [vizio] Set autoUpdatePolicy for button channel

- bundles/org.openhab.binding.pushover/README.md
Supercedes #17194
Related to #17461
> [pushover] Provide JavaScript examples

- bundles/org.openhab.binding.pushover/README.md
Add additional guidance around using Image-type item content in an attachment message.
> [pushover] Update README.md

- bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/action/EcobeeActions.java
- bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/action/FroniusSymoInverterActions.java
- bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/internal/action/SendMailActions.java
- bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/handler/TPLinkSmartHomeActions.java
- bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/action/UniFiSiteActions.java
- bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/action/WarmupActions.java
> Thing actions: add type in @ActionInput for generic class

- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/AuthenticationApi.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/SecurityApi.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/data/NetatmoConstants.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/ApiBridgeHandler.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/SecurityCapability.java
Resolves #17478 
While digging in this issue, I landed in the immediate MAXIMUM_USAGE_REACHED issue (see comment [here](https://community.openhab.org/t/netatmo-bridge-offline-99-of-time/149168/44?u=glhopital)
> [netatmo] Avoid endless loop when Security claims event history

- bundles/org.openhab.binding.goecharger/README.md
- bundles/org.openhab.binding.goecharger/src/main/java/org/openhab/binding/goecharger/internal/GoEChargerBindingConstants.java
- bundles/org.openhab.binding.goecharger/src/main/java/org/openhab/binding/goecharger/internal/api/GoEStatusResponseV2DTO.java
- bundles/org.openhab.binding.goecharger/src/main/java/org/openhab/binding/goecharger/internal/handler/GoEChargerV2Handler.java
- bundles/org.openhab.binding.goecharger/src/main/resources/OH-INF/i18n/goecharger.properties
- bundles/org.openhab.binding.goecharger/src/main/resources/OH-INF/thing/thing-types.xml
- bundles/org.openhab.binding.goecharger/src/main/resources/OH-INF/update/upgrade.xml
Resolves: https://github.com/openhab/openhab-addons/issues/17369
> [goecharger] Add awattarMaxPrice channel

- bundles/org.openhab.binding.growatt/src/main/java/org/openhab/binding/growatt/internal/handler/GrowattInverterHandler.java
> [growatt] Improve logging

- bundles/org.openhab.binding.broadlink/pom.xml
- bundles/org.openhab.binding.broadlink/src/test/java/org/openhab/binding/broadlink/internal/handler/BroadlinkRemoteModel4HandlerTest.java
- bundles/org.openhab.binding.broadlink/src/test/java/org/openhab/binding/broadlink/internal/handler/BroadlinkRemoteModelProHandlerTest.java
- bundles/org.openhab.binding.broadlink/src/test/java/org/openhab/binding/broadlink/internal/handler/BroadlinkSocketModel2HandlerTest.java
- bundles/org.openhab.binding.broadlink/src/test/java/org/openhab/binding/broadlink/internal/handler/BroadlinkSocketModel3HandlerTest.java
- bundles/org.openhab.binding.broadlink/src/test/java/org/openhab/binding/broadlink/internal/handler/BroadlinkSocketModel3SHandlerTest.java
- bundles/org.openhab.binding.linktap/pom.xml
> Remove JUnit 4 dependencies

- bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/handler/IpCameraHandler.java
Add recently added ability to auto re-start the ONVIF event streams to Reolink branded cameras.
> [ipcamera] Fix Reolink events do not auto restart

- bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/Constants.java
This will fix the bug reported here in the community
https://community.openhab.org/t/mercedes-me-binding/136852/212
> [mercedesme] fix websocket endpoint

- bundles/org.openhab.binding.irtrans/README.md
Resolves: https://github.com/openhab/openhab-addons/issues/9532 by improving the markdown.
> [irtrans] Adapt documentation

- bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/internal/homie300/Property.java
> [mqtt.homie] Populate unit hint on dynamic channels

- bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/internal/action/SendMailActions.java
- bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/actions/MaxCubeActions.java
- bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/actions/MaxDevicesActions.java
- bundles/org.openhab.binding.modbus.helioseasycontrols/src/main/java/org/openhab/binding/modbus/helioseasycontrols/internal/HeliosEasyControlsActions.java
- bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/actions/OpenWebNetBridgeActions.java
- bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/actions/OpenWebNetCENActions.java
> [m-o] Fix @ActionOutput annotations

- bundles/org.openhab.binding.webexteams/src/main/java/org/openhab/binding/webexteams/internal/WebexTeamsActions.java
Related to #17636
Signed-off-by: Laith Budairi <laith.budairi@exalt.ps>
> [webexteams] Fix @ActionOutput annotations (#17653)

- bundles/org.openhab.binding.pushbullet/src/main/java/org/openhab/binding/pushbullet/internal/action/PushbulletActions.java
- bundles/org.openhab.binding.pushover/src/main/java/org/openhab/binding/pushover/internal/actions/PushoverActions.java
- bundles/org.openhab.binding.pushsafer/src/main/java/org/openhab/binding/pushsafer/internal/actions/PushsaferActions.java
- bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/action/SatelEventLogActions.java
- bundles/org.openhab.binding.solarforecast/src/main/java/org/openhab/binding/solarforecast/internal/actions/SolarForecastActions.java
> [p-s] Fix @ActionOutput annotations

- bundles/org.openhab.automation.jsscripting/pom.xml
Changelog: https://github.com/openhab/openhab-js/blob/main/CHANGELOG.md#571.
> [jsscripting] Upgrade openhab-js to 5.7.1

- bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/action/UniFiSiteActions.java
- bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/action/VeluxActions.java
> [u-v] Fix @ActionOutput annotations

- bundles/org.openhab.binding.telegram/src/main/java/org/openhab/binding/telegram/internal/action/TelegramActions.java
- bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/handler/TPLinkSmartHomeActions.java
- bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/FritzboxActions.java
> [t*] Fix @ActionOutput annotations

- bundles/org.openhab.binding.evcc/src/main/java/org/openhab/binding/evcc/internal/EvccHandler.java
Fixes #17645 
Fix for the Vehicle Plan Time not reflecting on the item linked on openHAB when changed from EVCC software
> [evcc] Chargeplan changes on the app are not synced to openHAB (#17645)

- bundles/org.openhab.binding.x/src/main/java/org/openhab/binding/x/internal/action/XActions.java
> [x] Fix @ActionOutput annotations

- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiJsonDTO.java
- If 'Auto OFF' mode is enabled on a Shelly Plus 1 device and set to a value with decimal places a status update throws an NumberFormatException.
Changed timerDuration/timer_duration from Integer to Double fixes the problem.
```
Unable to create object of type Shelly2DeviceStatus$Shelly2DeviceStatusResult from JSON 
(syntax/format error: java.lang.NumberFormatException: Expected an int but was 1.25 at line 1 column 211 path $.switch:0.timer_duration): 
{
...
"switch:0":{
"id":0.0,
"source":"HTTP_in",
"output":true,
"timer_started_at":1.72366902863E9,
"timer_duration":1.25,
"temperature":{
"tC":45.8,
"tF":114.4
}
},
...
}
```
> [shelly] fix NumberFormatException on Shelly2RelayStatus.timerDuration

- bundles/org.openhab.binding.fmiweather/src/main/java/org/openhab/binding/fmiweather/internal/discovery/FMIWeatherDiscoveryService.java
This removes the hardcoded replacement of specific characters with accents. This makes it more robust since all accents and diacritics should now be supported.
Also refactors some usages of `String.format`.
> [fmiweather] Refactor removal of accents for Thing ID normalization

- bundles/org.openhab.automation.jsscripting/README.md
- bundles/org.openhab.automation.jsscripting/pom.xml
- Changelog: https://github.com/openhab/openhab-js/blob/main/CHANGELOG.md#580
- Refs the core fix https://github.com/openhab/openhab-core/pull/4437.
> [jsscripting] Upgrade openhab-js to 5.8.0 & Add note to check core fix on on upgrade

- bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/SnmpServiceImpl.java
Fixes https://github.com/openhab/openhab-addons/issues/17550#issuecomment-2453582050
Confirmed here https://community.openhab.org/t/snmp-seems-not-to-work-as-expected/157319/28
> [snmp] make use of openHAB network configuration

- bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/AVMFritzBaseThingHandler.java
- bundles/org.openhab.binding.avmfritz/src/test/java/org/openhab/binding/avmfritz/internal/dto/AVMFritzDeviceListModelTest.java
Fixes #17609 - HAN_FUN_DIMMABLE_BULB state not updating correctly when turned off
- Ensure correct state update for HAN_FUN_DIMMABLE_BULB when switched off
> [avmfritz] Fix incorrect state of dimmable bulb

- bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/handler/AwattarBestpriceHandler.java
- bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/handler/AwattarBridgeHandler.java
- bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/handler/TimeRange.java
- bundles/org.openhab.binding.awattar/src/test/java/org/openhab/binding/awattar/internal/handler/AwattarBridgeHandlerTest.java
> [awattar] Fix last hour not being considered for best price

- bundles/org.openhab.binding.ipobserver/src/main/java/org/openhab/binding/ipobserver/internal/IpObserverHandler.java
Fixes https://github.com/openhab/openhab-addons/issues/17735
> [ipobserver] Fix absolute pressure not updating

- bundles/org.openhab.binding.ism8/README.md
* Add things, items, and sitemap for heat pump and solar module.
* Use UOM for all items.
This PR adds example code needed for heat pumps. Implementation of new channels was done in #17688.
Closes: #17682
> [ism8] Extend example sitemap

- bundles/org.openhab.binding.ism8/README.md
Small regression of example introduced with #17738.
The file contained leftover Contact items from testing #17742.
Contact items are not yet supported.
Sorry for that.
> [ism8] Fix example, regression

- bundles/org.openhab.io.metrics/README.md
Maybe fixes #17418.
Same approach worked for an image in #17175, not sure if it works for other files.
@stefan-hoehn WDYT?
> [metrics] Fix link to json example

- itests/org.openhab.automation.groovyscripting.tests/itest.bndrun
- itests/org.openhab.automation.jsscriptingnashorn.tests/itest.bndrun
- itests/org.openhab.binding.astro.tests/itest.bndrun
- itests/org.openhab.binding.avmfritz.tests/itest.bndrun
- itests/org.openhab.binding.feed.tests/itest.bndrun
- itests/org.openhab.binding.hue.tests/itest.bndrun
- itests/org.openhab.binding.max.tests/itest.bndrun
- itests/org.openhab.binding.mielecloud.tests/itest.bndrun
- itests/org.openhab.binding.modbus.tests/itest.bndrun
- itests/org.openhab.binding.mqtt.homeassistant.tests/itest.bndrun
- itests/org.openhab.binding.mqtt.homie.tests/itest.bndrun
- itests/org.openhab.binding.mqtt.ruuvigateway.tests/itest.bndrun
- itests/org.openhab.binding.ntp.tests/itest.bndrun
- itests/org.openhab.binding.systeminfo.tests/itest.bndrun
- itests/org.openhab.binding.tradfri.tests/itest.bndrun
- itests/org.openhab.binding.wemo.tests/itest.bndrun
- itests/org.openhab.persistence.mapdb.tests/itest.bndrun
* Upgrade XStream from 1.4.20 to 1.4.21, fixes CVE-2024-47072.
See changelog at https://x-stream.github.io/changes.html#1.4.21
Depends on openhab/openhab-core#4457.
> Upgrade XStream to 1.4.21

- bundles/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/protocol/xml/XMLConnection.java
> [yamahareceiver] Assign proper read timeouts

- bundles/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/handler/OnkyoAudioSink.java
- bundles/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/handler/OnkyoUpnpHandler.java
- bundles/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/handler/URIMetaDataProcessor.java
- bundles/org.openhab.binding.onkyo/src/test/java/org/openhab/binding/onkyo/internal/handler/URIMetaDataProcessorTest.java
Fix for Onkyo audio sink on TX-NR646: #17755 
More details on community [thread](https://community.openhab.org/t/using-onkyo-as-audio-sink/29946/16)
> [Onkyo] Set "CurrentURIMetaData" for "SetAVTransportURI" action (#17755)

- bundles/org.openhab.binding.govee/src/main/resources/OH-INF/thing/thing-types.xml
> [govee] Improvements to color temperature channel

- bundles/org.openhab.binding.avmfritz/src/main/resources/OH-INF/thing/channel-types.xml
> [avmfritz]  Improvements to color temperature channel

- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/SerialTransportAdapter.java
* Logger in SerialAdapter respects the log setting for the binding.
* Additional warning if open port is detected.
> [knx] Improve logging for serial gateways

- bundles/org.openhab.binding.hydrawise/README.md
Fixes: https://github.com/openhab/openhab-addons/issues/11938
> [hydrawise] Update documentation

- bundles/org.openhab.binding.metofficedatahub/README.md
Minor cleanup's to the readme file's formatting and data.
> [metOfficeDataHub] Minor documentation Updates

- bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/handler/LinkyHandler.java
> [linky] Filter on dates when building the report requested from console

- bundles/org.openhab.binding.knx/pom.xml
Upgrade library which was not included in #16588.
> [knx] Upgrade calimero-device to 2.6-rc1

- bundles/org.openhab.binding.gpstracker/src/main/java/org/openhab/binding/gpstracker/internal/profile/GPSTrackerTriggerSwitchProfile.java
Fixes https://github.com/openhab/openhab-addons/issues/10240
> [gpstracker] Fix handling ambigious region names

- CODEOWNERS
Adds the missing code owners and sorts the paths.
> Add missing code owners

- bundles/org.openhab.binding.wiz/src/main/resources/OH-INF/addon/addon.xml
> [wiz] Enable addon finder support

- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/api/dto/clip2/enums/ZigbeeStatus.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/Clip2ThingHandler.java
> [hue] Friends of Hue sensors show as online

- bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/action/ActivePlayerActions.java
> [freeboxos] Add missing thing actions for active player

- .github/workflows/ci-build.yml
- pom.xml
Relates to openhab/openhab-core#4483
In contrast to other repos, I added a profile "j17" to force code generator to Java17-compatible code.
This is likely to fail if new language features are used in a binding.
Lets see if this helps - if not, it can be removed later.
> Remove Java 17 build, switch to 21

- bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/HomeAssistantChannelTransformation.java
- bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/HomeAssistantJinjaFunctionLibrary.java
- bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/HomeAssistantChannelTransformationTests.java
Refs #17374.
zigbee2mqtt's new event component's template utilizes this (and more... I'm still working through their incredibly complex template getting it to fully render).
> [mqtt.homeassistant] Implement regex_findall and regex_findall_index Jinja filters

- bundles/org.openhab.binding.androidtv/README.md
> [androidtv] Improve documentation with hint and potential troubleshooting

- bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcBaseDAO.java
When working on #15434 I wanted to do this, but it was a preview feature back then in Java 17. With Java 21 it's finally possible. 🙂 This improves readability and makes it less error-prone.
> [jdbc] Use switch pattern matching

- bundles/org.openhab.binding.exec/README.md
- bundles/org.openhab.binding.http/README.md
- bundles/org.openhab.binding.logreader/README.md
- bundles/org.openhab.binding.mqtt.generic/README.md
- bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/internal/ssl/PinTrustManager.java
- bundles/org.openhab.binding.mqtt/xtend_examples.md
- bundles/org.openhab.binding.ntp/README.md
- bundles/org.openhab.binding.telegram/README.md
- bundles/org.openhab.io.metrics/README.md
- bundles/org.openhab.transform.basicprofiles/README.md
- bundles/org.openhab.transform.map/README.md
- bundles/org.openhab.transform.regex/README.md
This prevents issues because older documentation may not apply to Java 21.
Previous update: #15406
> Link to Java 21 documentation

- bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/GroupThingHandler.java
- bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/LightThingHandler.java
> [deconz] Support QuantityType commands

- bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/device/BulbDevice.java
> [tplinksmarthome] Support QuantityType Color Temperature command

- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyLightHandler.java
> [shelly] Support QuantityType Color Temperature command

- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/api/dto/clip2/helper/Setters.java
> [hue] Improve QuantityType Color Temperature command

- bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/transport/HubIOStream.java
- bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/transport/IOStream.java
- bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/transport/LegacyPort.java
- bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/transport/Port.java
- bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/transport/SerialIOStream.java
- bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/transport/TcpIOStream.java
- bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/transport/message/MsgFactory.java
- bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/utils/HexUtils.java
Pulled from #17922 as a separate PR.
I did run a successful test in my environment of this change.
> [insteon] Refactor iostream transport classes

- bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudClient.java
see https://github.com/openhab/openhab-webui/issues/2934
> [openhabcloud] Send the correct response status text

- bundles/org.openhab.binding.knx/pom.xml
- bundles/org.openhab.binding.mybmw/pom.xml
Upgrades JaCoCo and corrensponding maven plugin from 8.11 to 8.12. See changelog:
https://www.jacoco.org/jacoco/trunk/doc/changes.html
Affects only knx and mybmw.
> Upgrade JaCoCo to 8.12

- bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/AbstractComponent.java
- bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/ClimateTests.java
After merge of #17908 build is broken.
Small regression.
@ccutrer could you please check if I did this correctly. Thanks!
> [mqtt.homeassistant] Fix build

- bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/AbstractComponent.java
- bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/SwitchTests.java
Re-fixes #15427, regressed from #17933
> [mqtt.homeassistant] Re-fix null component name

- bundles/org.openhab.binding.energidataservice/README.md
Make the rule example more real-life/less naive.
See https://community.openhab.org/t/entsoe-binding-4-0-0-0-4-3-0-0/149699/130
> [energidataservice] Improve rule example for calculating totals

- bundles/org.openhab.automation.jsscripting/pom.xml
- bundles/org.openhab.binding.mybmw/pom.xml
- bundles/pom.xml
- itests/pom.xml
- pom.xml
* frontend-maven-plugin to 1.15.1
* license-maven-plugin to 4.6 https://github.com/mathieucarbou/license-maven-plugin/releases
* maven-clean-plugin to 3.4.0 https://github.com/apache/maven-clean-plugin/releases/tag/maven-clean-plugin-3.4.0
* maven-dependency-plugin to 3.8.1
* maven-deploy-plugin to 3.1.3
* maven-enforcer-plugin to 3.5.0 https://github.com/apache/maven-enforcer/releases
* maven-failsafe-plugin to 3.5.2
* maven-install-plugin to 3.1.3 https://github.com/apache/maven-install-plugin/releases
* maven-jar-plugin to 3.4.2 https://github.com/apache/maven-jar-plugin/releases/tag/maven-jar-plugin-3.4.2
* maven-javadoc-plugin to 3.11.2
* maven-release-plugin to 3.1.1
* maven-site-plugin to 3.21.0
* maven-surefire-plugin to 3.5.2
* build-helper-maven-plugin to 3.6.0 …
> Upgrade plugins

- bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusNewDimmerHandler.java
- bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/packets/VelbusNewDimmerRequestPacket.java
Fix for files recently added with 2024 header. 
(Since #18015 CI enforces "2025").
> Fix build: [velbus] Update license headers to 2025

- bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/command/DeviceCommand.java
This changes adds the ability to refresh all configured device things via the console. Doing so will schedule each configured device to be refreshed based on their poll schedule. This is to prevent all devices from being polled immediately when the command is issued.
> [insteon] Add device refresh all command parameter

- bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/internal/DigiplexAreaConfiguration.java
- bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/internal/DigiplexBridgeConfiguration.java
- bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/internal/handler/DigiplexBridgeHandler.java
Found these two missing null annotations when reviewing another PR.
> [digiplex] Fix SAT errors

- CODEOWNERS
See https://github.com/openhab/openhab-addons/pull/18039#issuecomment-2571617563
> [broadlink] Correct binding maintainer

- itests/org.openhab.binding.mqtt.homie.tests/src/main/java/org/openhab/binding/mqtt/homie/HomieImplementationTest.java
> [mqtt.homie] Disable another unstable test

- itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/handler/test/WemoMakerHandlerOSGiTest.java
> [wemo] Disable another unstable test

- bundles/org.openhab.automation.jrubyscripting/README.md
Make it easier to see examples of rules written in JRuby
> [jrubyscripting] Minor updates, add short examples at the top of README.md

- bundles/org.openhab.binding.panasonicbdp/src/main/java/org/openhab/binding/panasonicbdp/internal/discovery/PanaBlurayDiscoveryParticipant.java
> [panasonicbdp] Refactor usages of deprecated methods

- bundles/org.openhab.voice.whisperstt/pom.xml
As reported in #18063 issue some anti-virus scanners report the windows dll inside libfvad-jni used in whisperstt as a virus. After looking on google seems like many binaries built using the mingw compiler have that problem, so I have updated the library so it uses a dll built with MSVC for windows.
> [whisperstt] Update libfvad-jni library

- bundles/org.openhab.binding.surepetcare/README.md
- bundles/org.openhab.binding.surepetcare/src/main/java/org/openhab/binding/surepetcare/internal/handler/SurePetcarePetHandler.java
* API seems to be changed at some point... the weight is now in gram not in kilogram anymore
> [surepetcare] API change pet weight

- bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/config/config.xml
- bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/i18n/energidataservice.properties
- bundles/org.openhab.binding.energidataservice/src/main/resources/filters/grid_tariffs.yaml
See https://elvrk.dk/forside/priser/
Also updated GLN to new one.
> [energidataservice] Update tariff filter for Netselskabet Elværk

- itests/org.openhab.automation.groovyscripting.tests/itest.bndrun
- itests/org.openhab.automation.jsscriptingnashorn.tests/itest.bndrun
- itests/org.openhab.binding.avmfritz.tests/itest.bndrun
- itests/org.openhab.binding.hue.tests/itest.bndrun
- itests/org.openhab.binding.wemo.tests/itest.bndrun
Depends on:
* https://github.com/openhab/openhab-core/pull/4566
* https://github.com/openhab/openhab-core/pull/4565
> Resolve runbundles for Jollyday and JUPnP upgrades

- bundles/org.openhab.binding.bluetooth.bluez/pom.xml
- bundles/org.openhab.binding.bluetooth.bluez/src/main/feature/feature.xml
- features/openhab-addons/src/main/resources/footer.xml
This PR does update to `bluez-dbus-osgi` version `0.3.1`, as the osgi bundle of version `0.3.0` is broken.
FYI @lsiepel
> [bluetooth.bluez] update to dbus version 0.3.1

- bundles/org.openhab.binding.lgwebos/README.md
- bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/MediaControlPlayer.java
- bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/handler/LGWebOSTVSocket.java
- bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/handler/core/AppInfo.java
- bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/handler/core/MediaAppInfo.java
See https://community.openhab.org/t/detecting-play-pause-state-of-lg-webos-tv/160043/
> [lgwebos] Subscribe to Play/Pause state changes from the TV

- bundles/org.openhab.binding.solarforecast/README.md
changed historicState to persistedState
changed Solcast Thing actions
added note for limit of api calls for free solcast hobbyist plan
https://community.openhab.org/t/solar-forecast-pv/137681/297
Signed-off-by: sihui <10405486+sihui62@users.noreply.github.com>
> [solarforecast] Update README.md

- bundles/org.openhab.binding.shelly/README.md
> [shelly] Correct doc for Pro EM-50

- bundles/org.openhab.binding.bluetooth.bluez/src/main/java/org/openhab/binding/bluetooth/bluez/internal/BlueZBluetoothDevice.java
> [bluetooth.bluez] Fix `NullPointerException`

- bundles/org.openhab.binding.ipcamera/README.md
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/robot/RRMapDraw.java
- bundles/org.openhab.binding.milight/README.md
Fixed everywhere:
- README's
- Variable names
> Fix typo: prefered

- bundles/org.openhab.automation.jrubyscripting/pom.xml
Passed CI at https://github.com/openhab/openhab-jruby/pull/384
> [jrubyscripting] Update to JRuby 9.4.10.0

- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/discovery/HDPowerViewSddpDiscoveryParticipant.java
> [hdpowerview] Fix bug in discovered Bridge label

- bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/phonebook/PhonebookProfileFactory.java
- bundles/org.openhab.transform.basicprofiles/src/main/java/org/openhab/transform/basicprofiles/internal/factory/BasicProfilesFactory.java
- bundles/org.openhab.transform.vat/src/main/java/org/openhab/transform/vat/internal/profile/VATTransformationProfileFactory.java
Depends on openhab/openhab-core#4486
> Adapt Nullable annotations to core change

- bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/command/SceneCommand.java
- bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/InsteonScene.java
This change fixes duplicate scene entry feature listeners when refreshing a scene. It also includes refactoring the scene console commands.
> [insteon] Fix duplicate scene entry feature listeners

- bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/transport/message/Field.java
- bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/transport/message/FieldType.java
- bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/transport/message/MsgDefinitionRegistry.java
This change refactors the transport message field type renaming `DataType` class as `FieldType`.
> [insteon] Refactor transport message field type

- bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/handler/InsteonBaseThingHandler.java
- bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/handler/InsteonBridgeHandler.java
- bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/handler/InsteonLegacyNetworkHandler.java
Backport for #18147 resolving conflicts.
> [insteon] Use separate pool for long running threads

- bundles/org.openhab.persistence.mapdb/src/main/java/org/openhab/persistence/mapdb/internal/MapDbPersistenceService.java
- itests/org.openhab.persistence.mapdb.tests/src/main/java/org/openhab/persistence/mapdb/MapDbPersistenceServiceOSGiTest.java
Fixes mapdb after core change, see https://github.com/openhab/openhab-core/pull/4363#issuecomment-2666767920
@holgerfriedrich FYI
> Fix mapdb after core change

- bundles/org.openhab.transform.basicprofiles/README.md
Small improvement to documentation as discussed [here](https://github.com/openhab/openhab-addons/pull/18144#issuecomment-2667336770)
> [basicprofiles] Small improvement to documentation

- bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/handler/AccountHandler.java
Port of https://github.com/smarthomej/addons/pull/607
> [amazonechocontrol] Fix push activity handling

- bundles/org.openhab.persistence.jdbc/README.md
- bundles/org.openhab.persistence.jdbc/pom.xml
- bundles/org.openhab.persistence.jdbc/src/main/feature/feature.xml
Supersedes: https://github.com/openhab/openhab-addons/pull/15941
Tested up to the point that it connects and writes several fields into a mariadb. Prefer to have this in 5.0.0 m1 if possible.
I guess both dependency's need to be uploaded (derby and derbytools) when merging this. @kaikreuzer
> [jdbc] Update derby to version 10.17.1.0

- bundles/org.openhab.binding.airparif/README.md
This is a hotfix for the website build.
> [airparif] Remove missing image from README

- bundles/org.openhab.binding.sonnen/README.md
Add additional hardware/software configuration which was tested successfully
> [sonnen] Update README.md

- bundles/org.openhab.binding.mqtt.awtrixlight/pom.xml
#18242 was merged without the sortpom PR #18318, applying spotless to fix the build.
> [mqtt.awtrix3] Spotless

- bundles/org.openhab.binding.knx/pom.xml
- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/channel/KNXChannel.java
- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/CustomKNXNetworkLinkIP.java
- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/IPClient.java
- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/DeviceThingHandler.java
This PR is to upgrade to the next rc release on the 2.6.x branch of Calimero KNX library, containing latest fixes.
* Upgrade Calimero from 2.6-rc1 to 2.6-rc2, see changes https://github.com/calimero-project/calimero-core/compare/v2.6-rc1...v2.6-rc2
* Handle deprecations
The new release contains several fixes, e.g. the one for KNX secure sequence numbers which could be off by one during resend attempts.
Also fixes #8277.
Note that this was just released today and the binding did not get a fair amount of testing on my systems yet.
IMHO, so short after a milestone release, we could take the risk.
Refs: #18256 (Calimero 3 snapshot, WIP, not released as an rc version yet)
> [knx] Upgrade Calimero to 2.6-rc2

- bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/handler/SatelEventLogHandler.java
- bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/util/DeviceNameResolver.java
- bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/util/EventLogReader.java
- bundles/org.openhab.binding.satel/src/test/java/org/openhab/binding/satel/internal/handler/SatelEventLogHandlerTest.java
- bundles/org.openhab.binding.satel/src/test/java/org/openhab/binding/satel/internal/util/DeviceNameResolverTest.java
- bundles/org.openhab.binding.satel/src/test/java/org/openhab/binding/satel/internal/util/EventLogReaderTest.java
Event log reading refactored with other fixes:
- partition keypad decoding for I128 WRL,
- replaced N/A text with device number when device name is unavailable,
- user decoding for certain cases fixed.
From `SatelEventLogHandler` has been extracted new classes: `DeviceNameResolver` and `EventLogReader` to simplify and limit responsibility of `SatelEventLogHandler` class.
Binary can be downloaded [here](https://github.com/druciak/openhab-addons/releases/tag/satel-event-log-fix)
> [satel] Event log reading refactored with other fixes

- bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxPlayerHandler.java
- bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxServerHandler.java
- bundles/org.openhab.binding.squeezebox/src/main/resources/OH-INF/i18n/squeezebox.properties
Also:
- Remove redundant logging where already logged through Thing status
- Optimize trace/debug logging by making it conditional when string operations are involved
> [squeezebox] Add I18N support for Thing status descriptions

- bundles/org.openhab.binding.insteon/README.md
This change adds all the supported Insteon console commands to the documentation.
> [insteon] Update console commands documentation

- bundles/org.openhab.binding.smartthings/README.md
> [smartthings] Correct the link to the compatible devices

- bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/handler/FroniusBaseThingHandler.java
- bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/handler/FroniusBridgeHandler.java
- bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/handler/FroniusSymoInverterHandler.java
> [fronius] Fix bridge config update not properly handled

- bundles/org.openhab.binding.bambulab/src/main/java/org/openhab/binding/bambulab/internal/PrinterHandler.java
- [bambulab] Support updating state of lights channel
> [bambulab] Add support updating state of lights

- bundles/org.openhab.automation.jsscripting/README.md
- bundles/org.openhab.automation.jsscripting/pom.xml
See https://github.com/openhab/openhab-js/blob/main/CHANGELOG.md#590 for changes.
> [jsscripting] Upgrade openhab-js to 5.9.0

- bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/discovery/DanfossAirUnitDiscoveryService.java
#18384 and #18414 didn't blend well.
> [danfossairunit] Fix build after merges

- bundles/org.openhab.binding.vizio/src/main/resources/OH-INF/thing/vizio.xml
- bundles/org.openhab.binding.vizio/src/main/resources/OH-INF/update/update.xml
- bundles/org.openhab.binding.vizio/src/main/resources/db/apps.json
Also remove Redbox app from json db.
waiting on https://github.com/openhab/openhab-core/pull/4616
see also #18314
> [vizio] Add semantic tag to Active App channel

- bundles/org.openhab.binding.roku/src/main/resources/OH-INF/thing/roku.xml
- bundles/org.openhab.binding.roku/src/main/resources/OH-INF/update/update.xml
waiting on https://github.com/openhab/openhab-core/pull/4616
see also #18314
> [roku] Add semantic tag to Active App and Active Channel channels

- bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/handler/JablotronBridgeHandler.java
This PR fixes a bug when an invalid event history  message is received
thanks.
> [somfytahoma] Fix exception when invalid event history response received

- bundles/org.openhab.binding.bambulab/src/main/java/org/openhab/binding/bambulab/internal/BambuLabBindingConstants.java
- bundles/org.openhab.binding.bambulab/src/main/java/org/openhab/binding/bambulab/internal/PrinterHandler.java
- bundles/org.openhab.binding.bambulab/src/main/resources/OH-INF/i18n/bambulab.properties
- bundles/org.openhab.binding.bambulab/src/main/resources/OH-INF/thing/channel-types.xml
- bundles/org.openhab.binding.bambulab/src/main/resources/OH-INF/thing/thing-types.xml
- bundles/org.openhab.binding.bambulab/src/test/java/org/openhab/binding/bambulab/internal/PrinterHandlerTest.java
[bambulab]  Support commands for `CHANNEL_GCODE_FILE` and `CHANNEL_SPEED_LEVEL`
> [bambulab] Support commands for CHANNEL_GCODE_FILE and CHANNEL_SPEED_LEVEL

- bundles/org.openhab.binding.evcc/src/main/java/org/openhab/binding/evcc/internal/api/dto/Loadpoint.java
- bundles/org.openhab.binding.evcc/src/main/java/org/openhab/binding/evcc/internal/api/dto/Result.java
> [evcc] Fix #18345, now every disallowed char will be replaced with a hyphen

- bundles/org.openhab.binding.homewizard/src/main/resources/OH-INF/thing/hwe-bat.xml
This file got lost in a merge from a previous PR.
> [homewizard] Added thing-type file for plug-in battery

- .github/workflows/ci-build.yml
* pin external action stCarolas/setup-maven to specific SHA
* pin external action Ana06/get-changed-files to specific SHA
* set global timeout
* comments
> Improve GitHub Actions

- bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/handler/JablotronBridgeHandler.java
This PR fixed improper json parsing resulting in empty channel values
> [jablotron] fix improper JSON response parsing

- bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/DanfossAirUnit.java
- bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/DanfossAirUnitBindingConstants.java
- bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/DanfossAirUnitHandlerFactory.java
- bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/discovery/DanfossAirUnitDiscoveryService.java
- bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/handler/DanfossAirUnitHandler.java
- bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/protocol/Parameter.java
- bundles/org.openhab.binding.danfossairunit/src/test/java/org/openhab/binding/danfossairunit/internal/DanfossAirUnitTest.java
This provides a few additional Thing properties:
- ccmSerialNumber
- hardwareVersion
- firmwareVersion
Also improve reliability when parsing responses to avoid runtime exceptions (`ArrayIndexOutOfBoundsException`).
> [danfossairunit] Provide additional properties

- bundles/org.openhab.binding.sensorcommunity/src/test/java/org/openhab/binding/sensorcommunity/internal/mock/ThingMock.java
* Add dummy functions for semantic tags to mockup
This hopefully fixes the build.
Pls. trigger a Jenkins build once this is merged.
> [sensorcommunity] Adapt test to core change

- bundles/org.openhab.automation.jsscripting/README.md
- bundles/org.openhab.automation.jsscripting/pom.xml
For changelog, see https://github.com/openhab/openhab-js/blob/main/CHANGELOG.md#5100.
> [jsscripting] Upgrade to openhab-js 5.10.0

- bundles/org.openhab.binding.bluetooth.daikinmadoka/src/test/java/org/openhab/binding/bluetooth/daikinmadoka/handler/DummyThing.java
* Add dummy functions for semantic tags to mockup
This hopefully fixes the build.
Pls. trigger a Jenkins build once this is merged.
Follow-up to #18488
> [bluetooth.daikinmodoka] Adapt test to core change

- bundles/org.openhab.binding.bambulab/pom.xml
- bundles/org.openhab.binding.bambulab/src/main/java/org/openhab/binding/bambulab/internal/AmsDeviceHandler.java
- bundles/org.openhab.binding.bambulab/src/main/java/org/openhab/binding/bambulab/internal/BambuLabBindingConstants.java
- bundles/org.openhab.binding.bambulab/src/main/java/org/openhab/binding/bambulab/internal/CommandParser.java
- bundles/org.openhab.binding.bambulab/src/main/java/org/openhab/binding/bambulab/internal/PrinterHandler.java
- bundles/org.openhab.binding.bambulab/src/main/java/org/openhab/binding/bambulab/internal/StateParserHelper.java
- bundles/org.openhab.binding.bambulab/src/main/java/org/openhab/binding/bambulab/internal/TrayHelper.java
- bundles/org.openhab.binding.bambulab/src/test/java/org/openhab/binding/bambulab/internal/CommandParserTest.java
- bundles/org.openhab.binding.bambulab/src/test/java/org/openhab/binding/bambulab/internal/PrinterHandlerTest.java
- bundles/org.openhab.binding.bambulab/src/test/java/org/openhab/binding/bambulab/internal/StateParserHelperTest.java
_As this is a new binding not part of a milestone, upgrade instructions are not needed._
I did some testing during weekend and I found bug with AMS. Also apparently the printer is sending weird values for `speed level` (instead of sending 1-4, from time to time it can send 253 🥲), so I've adjusted JBambuAPI for it.
> [bambulab] Fix AMS and use JBambuAPI 1.4.0

- bundles/org.openhab.automation.jsscripting/src/main/resources/OH-INF/i18n/jsscripting.properties
> [jsscripting] Update default translation

- bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/F6_00/F6_00_00_EltakoFJ62.java
> [enocean] Fix copyright header

- bundles/org.openhab.binding.growatt/src/main/resources/OH-INF/thing/thing-types.xml
Depends on
- https://github.com/openhab/openhab-core/pull/4708
- https://github.com/openhab/website/pull/511
> [growatt] Add semantic tags

- bundles/org.openhab.binding.growatt/src/main/resources/OH-INF/thing/thing-types.xml
See https://github.com/openhab/openhab-addons/pull/18516#discussion_r2038250733
> [growatt] Add unit hint on frequency channel

- bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/util/DeviceNameResolver.java
- bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/util/EventLogReader.java
- bundles/org.openhab.binding.satel/src/test/java/org/openhab/binding/satel/internal/util/DeviceNameResolverTest.java
- bundles/org.openhab.binding.satel/src/test/java/org/openhab/binding/satel/internal/util/EventLogReaderTest.java
This PR adds support for event description with id 10. This description regards to a telephone relay (an output connected to a relay that can be switched by DTMF).
> [satel] Add event log details for event description 10

- bundles/org.openhab.binding.argoclima/src/main/resources/OH-INF/thing/thing-types.xml
- bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/thing/group-thing-types.xml
- bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/thing/light-thing-types.xml
- bundles/org.openhab.binding.fineoffsetweatherstation/src/main/resources/OH-INF/thing/gateway.xml
- bundles/org.openhab.binding.plugwiseha/src/main/resources/OH-INF/thing/channels.xml
- bundles/org.openhab.binding.wiz/src/main/resources/OH-INF/thing/thing-types.xml
- bundles/org.openhab.binding.wundergroundupdatereceiver/src/main/resources/OH-INF/thing/channel-types.xml
Analog to #18483 this is a special PR for patch back port to v4.3.x
> Patch backport fix schema validation issues

- bundles/org.openhab.binding.epsonprojector/src/main/resources/OH-INF/thing/thing-types.xml
- bundles/org.openhab.binding.epsonprojector/src/main/resources/OH-INF/update/instructions.xml
Add semantic tags on the epson projector Things and Channels.
> [epsonprojector] Add semantic tags

- bundles/org.openhab.binding.benqprojector/src/main/resources/OH-INF/thing/thing-types.xml
- bundles/org.openhab.binding.benqprojector/src/main/resources/OH-INF/update/instructions.xml
Add semantic tags on the benq projector Things and Channels.
> [benqprojector] Add semantic tags

- bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/WLedHelper.java
- bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/api/WledApi.java
- bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/api/WledApiV0110.java
- bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/api/WledApiV084.java
- bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/handlers/WLedSegmentHandler.java
> [wled] Fix + Improve brightness and RGBW segment handling

- bundles/org.openhab.automation.jrubyscripting/README.md
- Add new config keys:
- bundle_gemfile  from #18404 
- console from #18374
- Add Console Commands from #18374
- Minor table formatting
> [jrubyscripting] Update README.md

- bundles/org.openhab.automation.jrubyscripting/pom.xml
Hot off the press: https://www.jruby.org/2025/04/14/jruby-10-0-0-0.html
> [jrubyscripting] Upgrade to JRuby 10.0.0.0

- bundles/org.openhab.binding.enphase/src/main/java/org/openhab/binding/enphase/internal/dto/PdmEnergyDTO.java
- bundles/org.openhab.binding.enphase/src/main/java/org/openhab/binding/enphase/internal/handler/EnvoyBridgeHandler.java
- bundles/org.openhab.binding.enphase/src/main/java/org/openhab/binding/enphase/internal/handler/EnvoyConnector.java
- bundles/org.openhab.binding.enphase/src/main/java/org/openhab/binding/enphase/internal/handler/EnvoyEntrezConnector.java
Tested on my own system running firmware D8.2.4264
Closes #16448
> [enphase] Fix for reading production values for newer enphase software versions.

- bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/JRubyEngineWrapper.java
This now possible since JRuby 10 implements it.
> [jrubyscripting] Implement AutoCloseable on JRubyEngineWrapper

- bundles/org.openhab.binding.lgwebos/src/main/resources/OH-INF/thing/thing-types.xml
Depends on https://github.com/openhab/website/pull/511
> [lgwebos] Add semantic equipment tag

- bundles/org.openhab.binding.daikin/src/main/resources/OH-INF/thing/thing-types.xml
Depend on https://github.com/openhab/website/pull/511
> [daikin] Add semantic equipment tag

- bundles/org.openhab.binding.tasmotaplug/src/main/resources/OH-INF/thing/thing-types.xml
- bundles/org.openhab.binding.tasmotaplug/src/main/resources/OH-INF/update/update.xml
Add semantic tags on tasmotaplug Things and Channels.
> [tasmotaplug] Add semantic tags

- bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/OpenhabGraalJSScriptEngine.java
Regression from #18500.
Fixes https://github.com/openhab/openhab-addons/issues/18566.
> [jsscripting] Fix bundled resources not found on windows

- bundles/org.openhab.binding.lgtvserial/README.md
- bundles/org.openhab.binding.lgtvserial/src/main/java/org/openhab/binding/lgtvserial/internal/handler/LgTvSerialHandler.java
- bundles/org.openhab.binding.lgtvserial/src/main/resources/OH-INF/config/config.xml
- bundles/org.openhab.binding.lgtvserial/src/main/resources/OH-INF/i18n/lgtvserial.properties
> [lgtvserial] Make refresh interval configurable

- bundles/org.openhab.binding.monopriceaudio/src/main/resources/OH-INF/thing/dax88.xml
- bundles/org.openhab.binding.monopriceaudio/src/main/resources/OH-INF/thing/monoprice.xml
- bundles/org.openhab.binding.monopriceaudio/src/main/resources/OH-INF/thing/monoprice4.xml
- bundles/org.openhab.binding.monopriceaudio/src/main/resources/OH-INF/thing/monoprice70.xml
- bundles/org.openhab.binding.monopriceaudio/src/main/resources/OH-INF/thing/xantech.xml
- bundles/org.openhab.binding.nuvo/src/main/resources/OH-INF/thing/channels.xml
- bundles/org.openhab.binding.radiothermostat/src/main/resources/OH-INF/thing/thing-types.xml
- bundles/org.openhab.binding.tivo/src/main/resources/OH-INF/thing/thing-types.xml
- bundles/org.openhab.binding.vizio/src/main/resources/OH-INF/thing/vizio.xml
Add equipment tags to remaining bindings where I am the code owner.
> Add equipment tags

- bundles/org.openhab.binding.bluetooth.daikinmadoka/src/test/java/org/openhab/binding/bluetooth/daikinmadoka/handler/DummyThing.java
- bundles/org.openhab.binding.sensorcommunity/src/test/java/org/openhab/binding/sensorcommunity/internal/mock/ThingMock.java
Add dummy functions for semantic tags to mockup.
Depends on openhab/openhab-core#4713.
> Adapt test to core change

- bundles/org.openhab.binding.siemensrds/src/main/java/org/openhab/binding/siemensrds/internal/RdsAccessToken.java
- bundles/org.openhab.binding.siemensrds/src/main/java/org/openhab/binding/siemensrds/internal/RdsCloudHandler.java
This PR allows the user login credentials to contain special characters.
Resolves #18507 
> [siemensrds] Allow special characters in login credentials

- bundles/org.openhab.binding.gardena/src/main/resources/OH-INF/thing/bridge.xml
- bundles/org.openhab.binding.gardena/src/main/resources/OH-INF/thing/thing-types.xml
> [gardena] Add semantic tags

- bundles/org.openhab.binding.bluetooth.hdpowerview/src/main/java/org/openhab/binding/bluetooth/hdpowerview/internal/shade/ShadeHandler.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/database/ShadeCapabilitiesDatabase.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewShadeHandler.java
- bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/ShadeThingHandler.java
- bundles/org.openhab.binding.hdpowerview/src/main/resources/OH-INF/thing/bridge.xml
- bundles/org.openhab.binding.hdpowerview/src/main/resources/OH-INF/thing/channels.xml
- bundles/org.openhab.binding.hdpowerview/src/main/resources/OH-INF/thing/repeater.xml
- bundles/org.openhab.binding.hdpowerview/src/main/resources/OH-INF/thing/shade.xml
> [hdpowerview] Add semantic tags

- bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/coffeemachine.xml
- bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/dishwasher.xml
- bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/fridge.xml
- bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/fridgefreezer.xml
- bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/hob.xml
- bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/hood.xml
- bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/oven.xml
- bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/tumbledryer.xml
- bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/washingmachine.xml
- bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/xgw3000.xml
Awaiting new XSD for validation (openhab/website#511) and Main UI support for testing (openhab/openhab-webui#3124).
> [miele] Add semantic equipment tags

- bundles/org.openhab.binding.homeconnect/src/main/resources/OH-INF/thing/thing-types.xml
> [homeconnect] Add semantic tags

- bundles/org.openhab.binding.icalendar/src/main/resources/OH-INF/thing/thing-types.xml
> [icalendar] Add semantic tags

- bundles/org.openhab.binding.ntp/src/main/resources/OH-INF/thing/thing-types.xml
> [ntp] Add semantic tags

- bundles/org.openhab.binding.solarforecast/src/main/resources/OH-INF/thing/channel-types.xml
- bundles/org.openhab.binding.solarforecast/src/main/resources/OH-INF/thing/fs-plane-type.xml
- bundles/org.openhab.binding.solarforecast/src/main/resources/OH-INF/thing/fs-site-type.xml
- bundles/org.openhab.binding.solarforecast/src/main/resources/OH-INF/thing/sc-plane-type.xml
- bundles/org.openhab.binding.solarforecast/src/main/resources/OH-INF/thing/sc-site-type.xml
> [solarforecast] Add semantic tags

- bundles/org.openhab.binding.hpprinter/src/main/resources/OH-INF/thing/channel-types.xml
- bundles/org.openhab.binding.hpprinter/src/main/resources/OH-INF/thing/thing-printer.xml
> [hpprinter] Add semantic tags

- bundles/org.openhab.binding.siemensrds/src/main/resources/OH-INF/thing/thing-types.xml
> [siemensrds] Add semantic tags

- bundles/org.openhab.binding.velux/src/main/resources/OH-INF/thing/bridge.xml
- bundles/org.openhab.binding.velux/src/main/resources/OH-INF/thing/channels.xml
- bundles/org.openhab.binding.velux/src/main/resources/OH-INF/thing/thing-type-actuator.xml
- bundles/org.openhab.binding.velux/src/main/resources/OH-INF/thing/thing-type-rollershutter.xml
- bundles/org.openhab.binding.velux/src/main/resources/OH-INF/thing/thing-type-vshutter.xml
- bundles/org.openhab.binding.velux/src/main/resources/OH-INF/thing/thing-type-window.xml
> [velux] Add semantic tags

- bundles/org.openhab.binding.neohub/src/main/resources/OH-INF/thing/thing-types.xml
> [neohub] Add semantic tags

- bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/thing/sensor-thing-types.xml
Regression of https://github.com/openhab/openhab-addons/pull/18515
cc @holgerfriedrich
> [deconz] Fix build

- bundles/org.openhab.binding.openthermgateway/src/main/resources/OH-INF/thing/boiler.xml
- bundles/org.openhab.binding.openthermgateway/src/main/resources/OH-INF/thing/channels.xml
- bundles/org.openhab.binding.openthermgateway/src/main/resources/OH-INF/thing/openthermgateway.xml
- bundles/org.openhab.binding.openthermgateway/src/main/resources/OH-INF/thing/ventilationheatrecovery.xml
> [openthermgateway] Add semantic tags

- .github/workflows/ci-build.yml
- .github/workflows/rebuild.yml
* This restores functionality we had before we migrated the PR builds to GitHub Actions.
see openhab/openhab-core#4739
> [GHA] Allow rebuild using label rebuild

- bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/thing/bridge-types.xml
- bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/thing/channel-types.xml
> [openweathermap] Add semantic tags

- bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java
Closes https://github.com/openhab/openhab-addons/issues/18523
See also: https://community.openhab.org/t/openhab-5-0-milestone-discussion/162686/65?u=mherwege
Regression from https://github.com/openhab/openhab-addons/pull/18480 and https://github.com/openhab/openhab-addons/pull/18308
In some cases, the selected matching archive start date ended up being after the query date. This caused:
- queries to fail in specific cases (query for data exactly 1 year ago)
- restore on startup to fail if no recent data was available
The start date has to be offset with the matching archive step size for the query.
> [rrd4j] Fix matching archive start date selection

- bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/handler/OpenWeatherMapOneCallHandler.java
- bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/handler/OpenWeatherMapOneCallHistoryHandler.java
- bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/thing/thing-types.xml
- bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/update/instructions.xml
This fixes two issues with the OneCall `visibility` channels (see also https://community.openhab.org/t/openweathermap-binding-bug-in-4-3-4-forecast-visibility-channels-receive-cloudiness-instead-of-distance/163751):
1. missing `break`s led to fall through and thus wrong updates to the channel
2. due to a typo in the update instructions the timeseries channel for `visibility` was not working (regression from #15963)
Not sure if the *instruction-set* is correct with removing the wrong and adding the correct channel, but in my tests it worked.
> [openweathermap] Fix visibility channels

- bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/A5_3F/A5_3F_7F_EltakoFSB.java
Fixes: https://github.com/openhab/openhab-addons/issues/15491
> [enocean] Fix rollershutter open completely

- bundles/org.openhab.automation.jythonscripting/src/main/java/org/openhab/automation/jythonscripting/internal/JythonScriptEngineFactory.java
- bundles/org.openhab.automation.jythonscripting/src/main/java/org/openhab/automation/jythonscripting/internal/watch/JythonScriptFileWatcher.java
- bundles/org.openhab.automation.pythonscripting/README.md
- bundles/org.openhab.automation.pythonscripting/src/main/java/org/openhab/automation/pythonscripting/internal/PythonScriptEngineFactory.java
This is a follow up pull request of https://github.com/openhab/openhab-addons/pull/18499 for changing transformation indentifier of pythonscripting and jythonscripting
jythonscripting is changed from PY to JYTHONPY   (like NASHORNJS for javascript)
pythonscripting is changed from PY3 to PY
@wborn can you please review :-)
> Python transform shortcut

- bundles/org.openhab.automation.pidcontroller/src/main/resources/OH-INF/addon/addon.xml
> [pidcontroller] Fix incorrect addon id

- bundles/org.openhab.automation.pythonscripting/README.md
* Fix capitalization to make it more consistent
* Start sentences on new lines for easier reviewing diffs
---
I updated them here as the docs in https://github.com/openhab/openhab-python did not yet seem to have been updated.
> [pythonscripting] Add documentation polish

- bundles/org.openhab.binding.shelly/README.md
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/ShellyBindingConstants.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyDeviceProfile.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiClient.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiJsonDTO.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiRpc.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/discovery/ShellyBasicDiscoveryService.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/discovery/ShellyThingCreator.java
- bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/i18n/shelly.properties
- bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/thing/shellyGen2_relay.xml
- bundles/org.openhab.binding.shelly/src/test/java/org/openhab/binding/shelly/internal/discovery/ShellyThingCreatorTest.java
This PR adds support for the new Shelly Circuit Breakers
> [shelly] Add support for Pro 1CB

- bundles/org.openhab.binding.modbus.stiebeleltron/README.md
Energy channels rename from "_" underscore to "-"
> [stiebeleltron] Update README.md

- bundles/org.openhab.binding.senseenergy/src/main/java/org/openhab/binding/senseenergy/internal/actions/SenseEnergyMonitorActions.java
- bundles/org.openhab.binding.senseenergy/src/main/java/org/openhab/binding/senseenergy/internal/api/SenseEnergyApi.java
- bundles/org.openhab.binding.senseenergy/src/main/java/org/openhab/binding/senseenergy/internal/api/SenseEnergyApiException.java
- bundles/org.openhab.binding.senseenergy/src/main/java/org/openhab/binding/senseenergy/internal/api/SenseEnergyDatagram.java
- bundles/org.openhab.binding.senseenergy/src/main/java/org/openhab/binding/senseenergy/internal/api/SenseEnergyWebSocket.java
- bundles/org.openhab.binding.senseenergy/src/main/java/org/openhab/binding/senseenergy/internal/api/SenseEnergyWebSocketListener.java
- bundles/org.openhab.binding.senseenergy/src/main/java/org/openhab/binding/senseenergy/internal/handler/SenseEnergyBridgeHandler.java
- bundles/org.openhab.binding.senseenergy/src/main/java/org/openhab/binding/senseenergy/internal/handler/SenseEnergyMonitorHandler.java
- bundles/org.openhab.binding.senseenergy/src/main/resources/OH-INF/i18n/senseenergy.properties
Fixes an issue where the senseenergy monitor goes offline due to a network issue - but then does not come back online after the network connection is restored.
> [senseenergy] Address reconnect issues on failure

- bundles/org.openhab.binding.bambulab/pom.xml
Fixes bug from https://github.com/openhab/openhab-addons/issues/18642
> [bambulab] Fix `JsonMappingException` by upgrading JBambuAPI

- bundles/org.openhab.binding.tuya/src/main/java/org/openhab/binding/tuya/internal/util/SchemaDp.java
> [tuya] Fix to allow for Channels whose DPs have string values

- bundles/org.openhab.binding.tuya/README.md
> [tuya] Fix Thing ID in documentation

- bundles/org.openhab.binding.powermax/src/main/resources/OH-INF/thing/channels.xml
- bundles/org.openhab.binding.powermax/src/main/resources/OH-INF/thing/ip.xml
- bundles/org.openhab.binding.powermax/src/main/resources/OH-INF/thing/serial.xml
See https://github.com/openhab/openhab-addons/pull/18558#discussion_r2081512200
Note I also took the liberty to apply the Point & Property tags from #18585
> [powermax] Correct Equipment tags

- bundles/org.openhab.automation.jrubyscripting/pom.xml
This is just a "minor" update only affecting ssl, but I'm not sure when 10.0.1.0 will be released, so it's better to update now.
https://github.com/jruby/jruby/releases/tag/10.0.0.1
> [jrubyscripting] Update to JRuby 10.0.0.1

- CODEOWNERS
I don't own the hardware anymore. Additionally, I'm not an openhab user anymore
> remove myself from code owners

- bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/generic/internal/MqttThingHandlerFactory.java
- bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/actions/HomeAssistantUpdateThingActions.java
- bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/handler/HomeAssistantThingHandler.java
- bundles/org.openhab.binding.mqtt.homeassistant/src/main/resources/OH-INF/config/homeassistant-thing-config.xml
- bundles/org.openhab.binding.mqtt.homeassistant/src/main/resources/OH-INF/i18n/mqtt.properties
- bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/AbstractComponentTests.java
- bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/handler/HomeAssistantThingHandlerTests.java
Refs #17992
Depends on https://github.com/openhab/openhab-core/pull/4719
> [mqtt.homeassistant] Use a thing action for updates, instead of a config action

- bundles/org.openhab.binding.tuya/src/main/java/org/openhab/binding/tuya/internal/handler/TuyaDeviceHandler.java
> [tuya] Prettify the labels used for command options

- bundles/org.openhab.binding.upnpcontrol/src/main/java/org/openhab/binding/upnpcontrol/internal/discovery/UpnpControlDiscoveryParticipant.java
Depends on https://github.com/openhab/openhab-core/pull/4735
> [upnpcontrol] Discover child devices

- bundles/org.openhab.binding.amberelectric/src/main/resources/OH-INF/thing/thing-types.xml
- bundles/org.openhab.binding.amberelectric/src/main/resources/OH-INF/update/instructions.xml
nem-time channel is broken due to a typo in thing-types.xml
This PR corrects this bug and upgrades the channel for existing installs.
> [amberelectric] Fix nem-time channel

- bundles/org.openhab.binding.matter/src/main/java/org/openhab/binding/matter/internal/controller/devices/converter/ColorControlConverter.java
Fixes a comment from the original matter PR after it was merged, as well as a small fix to ensure the color light is on before we send a temp command.
> [matter] Small color tweaks

- bundles/org.openhab.binding.spotify/src/main/resources/OH-INF/thing/thing-types.xml
> [spotify] add thingTypeVersion

- bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/handler/InsteonBaseThingHandler.java
This change set all channels to be rebuild during the thing initialization using the existing channel configuration and properties. This removes the need to use update instructions to update existing channels when changes to the channel structure occurs.
This change should be back ported along with #18273.
> [insteon] Rebuild all channels during thing initialization

- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/ValueDecoder.java
- bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/dpt/DPTTest.java
* For DPT 14, the standard IEEE 754 encoded NaN and Inf values are ignored for incoming packets
* For DPT 9, the special value 0x7FFF used for NaN (and invalid data) is ignored for incoming packets
Warnings are only logged on loglevel debug, as real hardware might use those values to indicate errors.
The decision to ignore incoming NaN values is based on the fact that we cannot represent NaN in QuantityType.
This is a breaking change at least for DPD9, as we did not do any special handling for the value 0x7fff (which is according to spec "shall be used to denote invalid data").
Fixes #18222.
> [knx] Ignore value NaN for DPT 9 and DPT 14

- bundles/org.openhab.binding.matter/matter-server/eslint.config.mjs
- bundles/org.openhab.binding.matter/matter-server/package-lock.json
- bundles/org.openhab.binding.matter/matter-server/package.json
- bundles/org.openhab.binding.matter/matter-server/src/Controller.ts
- bundles/org.openhab.binding.matter/matter-server/src/app.ts
- bundles/org.openhab.binding.matter/matter-server/src/bridge/BridgeController.ts
- bundles/org.openhab.binding.matter/matter-server/src/bridge/DeviceNode.ts
- bundles/org.openhab.binding.matter/matter-server/src/bridge/devices/ColorDeviceType.ts
- bundles/org.openhab.binding.matter/matter-server/src/bridge/devices/DoorLockDeviceType.ts
- bundles/org.openhab.binding.matter/matter-server/src/bridge/devices/GenericDeviceType.ts
- bundles/org.openhab.binding.matter/matter-server/src/bridge/devices/WindowCoveringDeviceType.ts
- bundles/org.openhab.binding.matter/matter-server/src/client/ClientController.ts
- bundles/org.openhab.binding.matter/matter-server/src/client/namespaces/Clusters.ts
- bundles/org.openhab.binding.matter/matter-server/src/client/namespaces/Nodes.ts
- bundles/org.openhab.binding.matter/matter-server/src/util/error.ts
This adds ESLint to the typescript server, with a config inspired from the main matter.js repo.   Changes to files are only to satisfy the linter (removing unneeded asyncs, specifying return types, use of const vs let), no material changes were made.
> [matter] Typescript ESLint modifications

- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiClient.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiJsonDTO.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiRpc.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/discovery/ShellyBasicDiscoveryService.java
- bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/i18n/shelly.properties
- bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/thing/shellyGen2_relay.xml
This PR fixes an issue with Plus 2PM discovery and newer firmware
> [shelly] Fix Shelly Plus 2PM discovery in Roller/Cover mode

- bundles/org.openhab.binding.orbitbhyve/src/main/java/org/openhab/binding/orbitbhyve/internal/handler/OrbitBhyveBridgeHandler.java
This PR removes the the obsolete setting for redirections. 
Fixes #14470
> [orbitbhyve] Remove obsolete redirects setting

- bundles/org.openhab.persistence.jdbc/README.md
Table needs a title row to be rendered as a table.
> [jdbc] Fix table in documentation

- bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/OpenhabGraalJSScriptEngine.java
Also add some commnents to the context config.
> [jsscripting] Fix deprecation warning from Polyglot Context.Builder

- bundles/org.openhab.automation.pythonscripting/README.md
- bundles/org.openhab.automation.pythonscripting/pom.xml
- bundles/org.openhab.automation.pythonscripting/src/main/java/org/openhab/automation/pythonscripting/internal/PythonScriptEngine.java
This pull request contains various smaller fixes and improvements
1. Updated (synced) README with version of helper libs
2. Updated helper lib version tag
3. Fixed value type mapping
> [pythonscripting] Updated README, helper lib and value type mapping fix

- bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/dto/LightState.java
- bundles/org.openhab.binding.deconz/src/test/java/org/openhab/binding/deconz/LightsTest.java
> [deconz] Fix for color item state not correct

- bundles/org.openhab.binding.matter/matter-server/src/app.ts
Several people have reported that occasionally the service starts with the error "Namespace nodes not found", this is due to a race condition where the controller class is not fully initialized before we report a ready state and accept messages.
> [matter] Fix race condition at startup

- bundles/org.openhab.binding.knx/pom.xml
* Upgrade Calimero from 2.6-rc2 to 2.6, see changes https://github.com/calimero-project/calimero-core/compare/v2.6-rc2...v2.6
> [knx] Upgrade Calimero to 2.6

- CODEOWNERS
- bom/openhab-addons/pom.xml
- bundles/org.openhab.binding.ecoflow/NOTICE
- bundles/org.openhab.binding.ecoflow/README.md
- bundles/org.openhab.binding.ecoflow/pom.xml
- bundles/org.openhab.binding.ecoflow/src/main/feature/feature.xml
- bundles/org.openhab.binding.ecoflow/src/main/java/org/openhab/binding/ecoflow/internal/EcoflowBindingConstants.java
- bundles/org.openhab.binding.ecoflow/src/main/java/org/openhab/binding/ecoflow/internal/EcoflowHandlerFactory.java
- bundles/org.openhab.binding.ecoflow/src/main/java/org/openhab/binding/ecoflow/internal/api/EcoflowApi.java
- bundles/org.openhab.binding.ecoflow/src/main/java/org/openhab/binding/ecoflow/internal/api/EcoflowApiException.java
- bundles/org.openhab.binding.ecoflow/src/main/java/org/openhab/binding/ecoflow/internal/api/dto/response/DataWrapper.java
- bundles/org.openhab.binding.ecoflow/src/main/java/org/openhab/binding/ecoflow/internal/api/dto/response/DeviceListResponseEntry.java
- bundles/org.openhab.binding.ecoflow/src/main/java/org/openhab/binding/ecoflow/internal/api/dto/response/MqttConnectionData.java
- bundles/org.openhab.binding.ecoflow/src/main/java/org/openhab/binding/ecoflow/internal/config/EcoflowApiConfiguration.java
- bundles/org.openhab.binding.ecoflow/src/main/java/org/openhab/binding/ecoflow/internal/config/EcoflowDeltaConfiguration.java
- bundles/org.openhab.binding.ecoflow/src/main/java/org/openhab/binding/ecoflow/internal/discovery/EcoflowDeviceDiscoveryService.java
- bundles/org.openhab.binding.ecoflow/src/main/java/org/openhab/binding/ecoflow/internal/handler/AbstractEcoflowHandler.java
- bundles/org.openhab.binding.ecoflow/src/main/java/org/openhab/binding/ecoflow/internal/handler/Delta2Handler.java
- bundles/org.openhab.binding.ecoflow/src/main/java/org/openhab/binding/ecoflow/internal/handler/EcoflowApiHandler.java
- bundles/org.openhab.binding.ecoflow/src/main/java/org/openhab/binding/ecoflow/internal/handler/PowerStreamHandler.java
- bundles/org.openhab.binding.ecoflow/src/main/java/org/openhab/binding/ecoflow/internal/util/SchedulerTask.java
- bundles/org.openhab.binding.ecoflow/src/main/resources/OH-INF/addon/addon.xml
- bundles/org.openhab.binding.ecoflow/src/main/resources/OH-INF/config/config.xml
- bundles/org.openhab.binding.ecoflow/src/main/resources/OH-INF/i18n/ecoflow.properties
- bundles/org.openhab.binding.ecoflow/src/main/resources/OH-INF/thing/bridge.xml
- bundles/org.openhab.binding.ecoflow/src/main/resources/OH-INF/thing/channels.xml
- bundles/org.openhab.binding.ecoflow/src/main/resources/OH-INF/thing/delta2.xml
- bundles/org.openhab.binding.ecoflow/src/main/resources/OH-INF/thing/powerstream.xml
- bundles/pom.xml
This PR adds a binding for [EcoFlow](https://ecoflow.com) devices via their cloud API, particularly for
- the Delta 2 and Delta 2 Max power stations
- the PowerStream micro inverter
Adding support for other devices of their [published API](https://developer-eu.ecoflow.com/us/document/introduction) later shouldn't be too hard; I just didn't do it because I only have Delta 2 Max + PowerStream at hand.
> [ecoflow] Initial contribution

- bundles/org.openhab.binding.fronius/pom.xml
- bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/api/FroniusUnauthorizedException.java
- bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/api/dto/inverter/PostConfigResponse.java
@lsiepel This is needed after #18887.
> Fix spotless and licence headers

- bundles/org.openhab.binding.ecotouch/src/main/resources/OH-INF/update/instructions.xml
Fixes: https://github.com/openhab/openhab-addons/issues/18866
> [ecotouch] Fix upgrade instructions

- bundles/org.openhab.binding.matter/code-gen/package.json
- bundles/org.openhab.binding.matter/matter-server/package-lock.json
- bundles/org.openhab.binding.matter/matter-server/package.json
- bundles/org.openhab.binding.matter/matter-server/src/bridge/DeviceNode.ts
- bundles/org.openhab.binding.matter/matter-server/src/bridge/devices/ColorDeviceType.ts
- bundles/org.openhab.binding.matter/matter-server/src/bridge/devices/FanDeviceType.ts
- bundles/org.openhab.binding.matter/matter-server/src/bridge/devices/GenericDeviceType.ts
- bundles/org.openhab.binding.matter/matter-server/src/bridge/devices/ThermostatDeviceType.ts
- bundles/org.openhab.binding.matter/matter-server/src/bridge/devices/WindowCoveringDeviceType.ts
- bundles/org.openhab.binding.matter/src/main/java/org/openhab/binding/matter/internal/bridge/AttributeState.java
- bundles/org.openhab.binding.matter/src/main/java/org/openhab/binding/matter/internal/bridge/MatterBridgeClient.java
- bundles/org.openhab.binding.matter/src/main/java/org/openhab/binding/matter/internal/bridge/devices/ColorDevice.java
- bundles/org.openhab.binding.matter/src/main/java/org/openhab/binding/matter/internal/bridge/devices/DimmableLightDevice.java
- bundles/org.openhab.binding.matter/src/main/java/org/openhab/binding/matter/internal/bridge/devices/FanDevice.java
- bundles/org.openhab.binding.matter/src/main/java/org/openhab/binding/matter/internal/bridge/devices/GenericDevice.java
- bundles/org.openhab.binding.matter/src/main/java/org/openhab/binding/matter/internal/bridge/devices/ThermostatDevice.java
- bundles/org.openhab.binding.matter/src/test/java/org/openhab/binding/matter/internal/bridge/devices/ColorDeviceTest.java
- bundles/org.openhab.binding.matter/src/test/java/org/openhab/binding/matter/internal/bridge/devices/DimmableLightDeviceTest.java
Adds transactions (multiple attribute changes) to bridge updates 
Prevents feedback loop from bridge attribute updates 
Updates to latest matter.js stable
> [matter] Bridge transaction support, matter.js upgrade

- bundles/org.openhab.binding.matter/src/main/java/org/openhab/binding/matter/internal/util/MatterUIDUtils.java
- bundles/org.openhab.binding.matter/src/test/java/org/openhab/binding/matter/internal/util/MatterUIDUtilsTest.java
See https://github.com/openhab/openhab-addons/issues/16374#issuecomment-3040330529
> [matter] Fix `ClassCastException`

- bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/BaseDevice.java
- bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/Device.java
- bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/InsteonDevice.java
- bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/LegacyDevice.java
- bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/RequestManager.java
- bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/transport/message/Msg.java
This change refactors the device request scheduled delay.
> [Insteon] Refactor device request scheduled delay

- bundles/org.openhab.binding.buienradar/README.md
- bundles/org.openhab.binding.buienradar/src/main/resources/OH-INF/i18n/buienradar.properties
- bundles/org.openhab.binding.buienradar/src/main/resources/OH-INF/thing/thing-types.xml
While creating translations i found this channel is partly documented, but not used in code or channel definition.
> [buienradar] Fix documentation for 120 min channel

- itests/org.openhab.binding.hue.tests/src/main/java/org/openhab/binding/hue/internal/discovery/HueBridgeNupnpDiscoveryOSGITest.java
See https://github.com/openhab/openhab-addons/pull/18895#issuecomment-3048147325
Regression of #18895
> [hue] Fix `HueBridgeNupnpDiscoveryOSGITest`

- bundles/org.openhab.binding.goecharger/src/main/java/org/openhab/binding/goecharger/internal/api/GoEStatusV2ApiKeys.java
- bundles/org.openhab.binding.goecharger/src/main/java/org/openhab/binding/goecharger/internal/handler/GoEChargerBaseHandler.java
- bundles/org.openhab.binding.goecharger/src/main/java/org/openhab/binding/goecharger/internal/handler/GoEChargerHandler.java
- bundles/org.openhab.binding.goecharger/src/main/java/org/openhab/binding/goecharger/internal/handler/GoEChargerV2Handler.java
Follow up to https://github.com/openhab/openhab-addons/pull/18781
Testable jar 5.0 m2 or later: https://1drv.ms/u/c/70ea7ac46bc61c73/EX3SreAoyUxJjFL67VkwFc4BOspyWwCvrzDl0Am4HVNT6A?e=gLiDpb
> [goecharger] Fix warnings and some minor refactoring

- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/discovery/ShellyBasicDiscoveryService.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/discovery/ShellyThingCreator.java
- bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyBaseHandler.java
> [shelly] Fix `NullPointerException` during discovery

- bundles/org.openhab.binding.zwavejs/src/main/java/org/openhab/binding/zwavejs/internal/api/dto/Event.java
- bundles/org.openhab.binding.zwavejs/src/main/java/org/openhab/binding/zwavejs/internal/discovery/NodeDiscoveryService.java
- bundles/org.openhab.binding.zwavejs/src/main/java/org/openhab/binding/zwavejs/internal/handler/ZwaveJSBridgeHandler.java
- bundles/org.openhab.binding.zwavejs/src/main/java/org/openhab/binding/zwavejs/internal/handler/ZwaveJSNodeHandler.java
- bundles/org.openhab.binding.zwavejs/src/main/java/org/openhab/binding/zwavejs/internal/handler/ZwaveNodeListener.java
- bundles/org.openhab.binding.zwavejs/src/main/resources/OH-INF/i18n/zwavejs.properties
- bundles/org.openhab.binding.zwavejs/src/test/java/org/openhab/binding/zwavejs/internal/handler/ZwaveJSNodeHandlerTest.java
- bundles/org.openhab.binding.zwavejs/src/test/resources/json/event_controller_node_removed.json
Fixes: https://github.com/openhab/openhab-addons/issues/18944
Commented where the actual fix is. Also:
- To be safe added null check to the `addDiscovery` 
- Added test to show the sates are actually transitioning between unknown > online > offline
- Had to adapt the interface a little bit
As test coverage is good, i see minimal to no risk.
> [zwavejs] Fix add and remove event handling

- bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/HomeAssistantPythonBridge.java
- bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/LogHandler.java
Refs https://github.com/openhab/openhab-distro/issues/1768
> [mqtt.homeassistant] send GraalPy logging to standard openHAB logging

- bundles/org.openhab.binding.tr064/src/main/resources/channels.xml
Fixes: https://github.com/openhab/openhab-addons/issues/18371
Test jar 5.0M4 or later: https://1drv.ms/u/c/70ea7ac46bc61c73/EXMcxmvEeuoggHDKxwMAAAAB6cQknvuHaFtaYRPfI1yvJQ?e=hKCfyC
> [tr064] Fix channel type

- bundles/org.openhab.binding.amberelectric/src/main/java/org/openhab/binding/amberelectric/internal/AmberElectricHandler.java
- bundles/org.openhab.binding.chatgpt/src/main/java/org/openhab/binding/chatgpt/internal/ChatGPTHandler.java
- bundles/org.openhab.binding.chatgpt/src/main/java/org/openhab/binding/chatgpt/internal/hli/ChatGPTHLIService.java
- bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/handler/DSCAlarmBaseBridgeHandler.java
- bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/F6_00/F6_00_00_EltakoFJ62.java
- bundles/org.openhab.binding.folderwatcher/src/main/java/org/openhab/binding/folderwatcher/internal/api/auth/AzureSignerBase.java
- bundles/org.openhab.binding.frenchgovtenergydata/src/main/java/org/openhab/binding/frenchgovtenergydata/internal/dto/Tariff.java
- bundles/org.openhab.binding.govee/src/main/java/org/openhab/binding/govee/internal/CommunicationManager.java
- bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/client/HomeConnectApiClient.java
- bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/AbstractHomeConnectThingHandler.java
- bundles/org.openhab.binding.homewizard/src/main/java/org/openhab/binding/homewizard/internal/devices/HomeWizardDeviceHandler.java
- bundles/org.openhab.binding.homewizard/src/test/java/org/openhab/binding/homewizard/internal/devices/plug_in_battery/HomeWizardPlugInBatteryMeterHandlerTest.java
- bundles/org.openhab.binding.modbus.kermi/src/main/java/org/openhab/binding/modbus/kermi/internal/dto/PowerDTO.java
- bundles/org.openhab.binding.modbus.kermi/src/main/java/org/openhab/binding/modbus/kermi/internal/dto/PvDTO.java
- bundles/org.openhab.binding.modbus.kermi/src/main/java/org/openhab/binding/modbus/kermi/internal/dto/WorkHoursDTO.java
- bundles/org.openhab.binding.modbus.kermi/src/main/java/org/openhab/binding/modbus/kermi/internal/handler/KermiXcenterThingHandler.java
- bundles/org.openhab.binding.mqtt.fpp/src/main/java/org/openhab/binding/mqtt/fpp/internal/handler/FPPPlayerHandler.java
- bundles/org.openhab.transform.basicprofiles/src/main/java/org/openhab/transform/basicprofiles/internal/profiles/StateFilterProfile.java
- bundles/org.openhab.voice.whisperstt/src/main/java/org/openhab/voice/whisperstt/internal/WhisperSTTService.java
Fixes about all NoEmptyLineSeparatorCheck SAT errors.
> [various] Fix NoEmptyLineSeparatorCheck

- bundles/org.openhab.binding.bambulab/src/main/java/org/openhab/binding/bambulab/internal/BambuLabBindingConstants.java
- bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/DemandControl.java
- bundles/org.openhab.binding.folderwatcher/src/main/java/org/openhab/binding/folderwatcher/internal/api/auth/AWS4SignerBase.java
- bundles/org.openhab.binding.folderwatcher/src/main/java/org/openhab/binding/folderwatcher/internal/api/auth/AzureSignerBase.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/data/NetatmoConstants.java
- bundles/org.openhab.binding.nibeheatpump/src/test/java/org/openhab/binding/nibeheatpump/internal/handler/NibeHeatPumpHandlerCommand2NibeTest.java
> [various] Fix StaticVariableNameCheck

- bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/Constants.java
- bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/MercedesMeHandlerFactory.java
- bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/discovery/MercedesMeDiscoveryService.java
- bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/handler/AccountHandler.java
- bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/server/MBWebsocket.java
Some internal improvements collected over time
- Mercedes version updates
- remove self handeled OSGi service registration for discovery
- websocket rework 
- scheduler Thread was kept in loop until websocket ended
- now statemachine
- use pings to keep websocket aliver
> [mercedesme] internal websocket rework

- bundles/org.openhab.binding.avmfritz/README.md
> [avmfritz] Fix links in documention

- bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/DenonMarantzState.java
> [denonmarantz] Fix zone 3 input source update

- CODEOWNERS
> [hue] Retire as a codeowner for hue binding

- .github/dependabot.yml
This is a follow-up to #19029, addressing the following point:
> I did not add PRs for maven.
Maven will both update the plugins (which it typically wanted) but also all dependences (which is largely not wanted).
For Core, we exclude all known dependencies (based on output of a script).
This is IMHO not viable for add-ons, where we constantly add new dependencies.
The PR activates plugin updates by allowing it for specific names, e.g. everythign that matches the string `plugin`.
I have defined some exclusions.
Maybe we overlook some plugins which are not matching the patterns; maybe we need some more exclusions.
I think this is a good start.
> Dependabot for Plugins

- bundles/org.openhab.automation.jsscripting/README.md
- bundles/org.openhab.automation.jsscripting/pom.xml
Changelog: https://github.com/openhab/openhab-js/blob/main/CHANGELOG.md#5120.
> [jsscripting] Upgrade openhab-js to 5.12.0

- CONTRIBUTING.md
- README.md
- features/readme.md
Ref: https://github.com/openhab/openhab-addons/issues/19011
> Fix markdown repo files

- bundles/org.openhab.binding.resol/README.md
- bundles/org.openhab.binding.ring/README.md
- bundles/org.openhab.binding.rotel/README.md
- bundles/org.openhab.binding.salus/DEV_README.md
- bundles/org.openhab.binding.salus/README.md
- bundles/org.openhab.binding.samsungtv/README.md
- bundles/org.openhab.binding.sbus/README.md
- bundles/org.openhab.binding.senseenergy/README.md
- bundles/org.openhab.binding.shelly/README.md
- bundles/org.openhab.binding.shelly/doc/AdvancedUsers.md
- bundles/org.openhab.binding.shelly/doc/ShellyManager.md
- bundles/org.openhab.binding.shelly/doc/UseCaseSmartRoller.md
- bundles/org.openhab.binding.siemenshvac/README.md
- bundles/org.openhab.binding.smartthings/doc/SmartthingsInstallation.md
- bundles/org.openhab.binding.smartthings/doc/Troubleshooting.md
- bundles/org.openhab.binding.snmp/README.md
- bundles/org.openhab.binding.solarforecast/README.md
- bundles/org.openhab.binding.solarman/README.md
- bundles/org.openhab.binding.solax/README.md
- bundles/org.openhab.binding.somfytahoma/README.md
- bundles/org.openhab.binding.speedtest/README.md
- bundles/org.openhab.binding.systeminfo/README.md
Ref: https://github.com/openhab/openhab-addons/issues/19011
> Fix markdown bindings Q-S

- .github/dependabot.yml
This groups jacoco-maven-plugin and org.jacoco.agent in one PR.
Proposed here:
https://github.com/openhab/openhab-addons/pull/19049#issuecomment-3118413592
Otherwise dependabot creates two separate commits which do not compile (see #19046, #19049).
> Dependabot groups

- bundles/org.openhab.binding.bluetooth.bluez/src/main/java/org/openhab/binding/bluetooth/bluez/internal/BlueZBluetoothDevice.java
- bundles/org.openhab.binding.bluetooth.bluez/src/main/java/org/openhab/binding/bluetooth/bluez/internal/DeviceManagerWrapper.java
This should make it easier to notice when new warnings are introduced.
> [bluetooth.bluez] Fix some warnings

- bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosBindingConstants.java
> [sonos] Ignore Sonos Boost and any Sub including Sonos Sub 4

- itests/org.openhab.automation.groovyscripting.tests/itest.bndrun
- itests/org.openhab.automation.jsscriptingnashorn.tests/itest.bndrun
- itests/org.openhab.binding.mqtt.homeassistant.tests/itest.bndrun
- pom.xml
Depends on https://github.com/openhab/openhab-core/pull/4942
> Update Jackson to 2.19.2

- bundles/org.openhab.automation.groovyscripting/README.md
- bundles/org.openhab.automation.groovyscripting/pom.xml
This was tagged just now: https://github.com/apache/groovy/tags.
> [groovyscripting] Upgrade Groovy to 4.0.28

- bundles/org.openhab.binding.evcc/src/main/java/org/openhab/binding/evcc/internal/api/EvccAPI.java
- [evcc] Fix #19116
- Support for old and new API
Quick fix for supporting new evcc APIs. As mentioned in the fix there might be a bigger redesign for the binding.
See this PR as a quick fix for e.g. an openHAB version 5.0.1
> [evcc] Support for evcc 0.207.1

- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/CcoHandler.java
Fixes: https://github.com/openhab/openhab-addons/issues/18702
Testable jar for oh 5.0m4 or later: https://1drv.ms/u/c/70ea7ac46bc61c73/Ebk6g1FuY2FMoxjtobrAIOQBin9foYTFawf2TkYjU6MJQA?e=KASU8W
> [lutron] Fix comparison bug

- bundles/org.openhab.binding.mqtt.awtrixlight/README.md
The documentation was [AI generated](https://community.openhab.org/t/awtrix-3-binding-formerly-awtrix-light/149739/130?u=habau) and has some errata.
This is a documentation fix only but the fixes work on my OH5 setup. 
The existing documentated way to create things/items does not.
> [mqtt.awtrixlight] Improve documentation

- bundles/org.openhab.automation.jrubyscripting/pom.xml
Related ci update in the helper library: https://github.com/openhab/openhab-jruby/pull/482
> [jrubyscripting] Upgrade to JRuby 10.0.2.0

- bundles/org.openhab.binding.homematic/README.md
- bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/discovery/HomematicDeviceDiscoveryService.java
Fixes: #18401
Should be backported to both 5.0.x and 4.3.x
Bridge settings did not change, just reformated to table for readability.
> [homematic] Fix premature end of discovery

- bundles/org.openhab.binding.evcc/src/main/java/org/openhab/binding/evcc/internal/handler/EvccSiteHandler.java
Hotfixing bug where smartCostType was tried to set even it was null
> [evcc] Update EvccSiteHandler.java

- bundles/org.openhab.binding.lgwebos/README.md
- bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/LGWebOSBindingConstants.java
- bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/PowerControlPower.java
- bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/WakeOnLanUtility.java
- bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/handler/LGWebOSConfiguration.java
- bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/handler/LGWebOSHandler.java
- bundles/org.openhab.binding.lgwebos/src/main/resources/OH-INF/config/config.xml
- bundles/org.openhab.binding.lgwebos/src/main/resources/OH-INF/i18n/lgwebos.properties
When running in docker, broadcast address can be configured to allow the wol packet to be forwarded to the correct network. This allows to use bridged mode, while still maintaining full functionality of the binding.
> [lgwebos] Add support for wakeonlan in docker

- bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosAudioSink.java
- bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/handler/ZonePlayerHandler.java
> [sonos] Enhance logging for playback of notifications

- .github/dependabot.yml
> Add ecj to Dependabot config

- bundles/org.openhab.transform.bin2json/pom.xml
* Upgrade jbbp from 1.4.1 to 3.0.1, Changelog: https://github.com/raydac/java-binary-block-parser?tab=readme-ov-fie#change-log
Depends-on:
* openhab/openhab-core#4954
* openhab/openhab-osgiify#72
> [transform.bin2json] Upgrade jbbp to 3.0.1

- bundles/org.openhab.automation.jsscripting/pom.xml
https://github.com/openhab/openhab-js/blob/main/CHANGELOG.md#5113
> [jsscripting] Upgrade openhab-js to 5.11.3

- itests/org.openhab.binding.mqtt.homeassistant.tests/itest.bndrun
- itests/org.openhab.binding.mqtt.homie.tests/itest.bndrun
- itests/org.openhab.binding.mqtt.ruuvigateway.tests/itest.bndrun
Depends on openhab/openhab-core#4958
> Resolve itests after hivemq upgrade

- bundles/org.openhab.binding.amplipi/pom.xml
depends on openhab/openhab-core#4950
> Upgrade cxf to 3.6.8

- bundles/org.openhab.binding.comfoair/src/main/java/org/openhab/binding/comfoair/internal/datatypes/DataTypeRPM.java
- bundles/org.openhab.binding.comfoair/src/main/java/org/openhab/binding/comfoair/internal/datatypes/DataTypeTemperature.java
fixes the calculation for sending non-integer temperature values (apparently this never correctly)
> [comfoair] fix temperatur command calculation

- bundles/org.openhab.binding.comfoair/src/main/java/org/openhab/binding/comfoair/internal/ComfoAirCommandType.java
- bundles/org.openhab.binding.comfoair/src/main/java/org/openhab/binding/comfoair/internal/ComfoAirHandler.java
reworks the item update logic to update all associated values from a single request instead of requesting each value individually even if read commands are the same. this reduces traffic over serial connection.
> [comfoair] Improve updater logic to reduce serial communication

- bundles/org.openhab.automation.jsscripting/README.md
- bundles/org.openhab.automation.jsscripting/pom.xml
Changelog: https://github.com/openhab/openhab-js/blob/main/CHANGELOG.md#5130
> [jsscripting] Upgrade to openhab-js 5.13.0

- itests/org.openhab.binding.hue.tests/itest.bndrun
- itests/org.openhab.binding.tradfri.tests/itest.bndrun
depends on openhab/openhab-core#5002
> Resolve after jmdns upgrade

- bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/handler/VehicleHandler.java
_Charge Program Values_ and _selected Charge Program Index_ are updated  properly when `fullUpdate` is delivered.
If vehicle update is _partial_, state update isn't performed with the new index.
Bugfix checks now index in every update.
> [mercedesme] Bugfix charge program selection

- .github/dependabot.yml
Keep the ftpupload binding up to date. 
This will cause Dependabot to create PRs to upgrade:
> Extend dependabot: ftpupload

- bundles/org.openhab.binding.zwavejs/src/main/java/org/openhab/binding/zwavejs/internal/conversion/BaseMetadata.java
ZUI does not use a strict unit declaration. Like this PR, we sometimes need to manually correct those units to map it to openHAB's UoM system.
In this case:
Map.entry("oC", "°C"),
openHAB 5.1.0 jar : https://1drv.ms/u/c/70ea7ac46bc61c73/EYtEveV8x4lGsA_n-Y30vYcB673NLEwjPx529q-H3f57ng?e=RUrUx9
Should be backported to 5.0.x
> [zwavejs] Add unit conversion

- bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/itests/Back2BackTest.java
```
WARNUNG: TestEngine with ID 'junit-jupiter' encountered a non-critical issue during test discovery:
(1) [WARNING] @Test method 'static void org.openhab.binding.knx.internal.itests.Back2BackTest.checkForMissingMainTypes()' must not be static. It will not be executed.
Source: MethodSource [className = 'org.openhab.binding.knx.internal.itests.Back2BackTest', methodName = 'checkForMissingMainTypes', methodParameterTypes = '']
at org.openhab.binding.knx.internal.itests.Back2BackTest.checkForMissingMainTypes(SourceFile:0)
```
> [knx] Fix test warning

- bundles/org.openhab.automation.jsscripting/README.md
- bundles/org.openhab.automation.jsscripting/pom.xml
Changelog: https://github.com/openhab/openhab-js/blob/main/CHANGELOG.md#5140
> [jsscripting] Upgrade to openhab-js 5.14.0

- bundles/org.openhab.binding.zwavejs/README.md
- bundles/org.openhab.binding.zwavejs/src/main/java/org/openhab/binding/zwavejs/internal/BindingConstants.java
- bundles/org.openhab.binding.zwavejs/src/main/java/org/openhab/binding/zwavejs/internal/api/ZWaveJSClient.java
- bundles/org.openhab.binding.zwavejs/src/main/java/org/openhab/binding/zwavejs/internal/api/dto/Args.java
- bundles/org.openhab.binding.zwavejs/src/main/java/org/openhab/binding/zwavejs/internal/api/dto/Event.java
- bundles/org.openhab.binding.zwavejs/src/main/java/org/openhab/binding/zwavejs/internal/conversion/BaseMetadata.java
- bundles/org.openhab.binding.zwavejs/src/main/java/org/openhab/binding/zwavejs/internal/handler/ZwaveJSBridgeHandler.java
- bundles/org.openhab.binding.zwavejs/src/main/java/org/openhab/binding/zwavejs/internal/type/ZwaveJSTypeGeneratorImpl.java
- bundles/org.openhab.binding.zwavejs/src/test/java/org/openhab/binding/zwavejs/internal/handler/ZwaveJSBridgeHandlerTest.java
- bundles/org.openhab.binding.zwavejs/src/test/java/org/openhab/binding/zwavejs/internal/handler/ZwaveJSNodeHandlerTest.java
- bundles/org.openhab.binding.zwavejs/src/test/java/org/openhab/binding/zwavejs/internal/type/ZwaveJSTypeGeneratorTest.java
- bundles/org.openhab.binding.zwavejs/src/test/resources/json/event_node_186_notification.json
- Added more unit tests
- Add notification channel that provides JSON data about the event. Generally i do not prefer to expose JSON, but as the event is super dynamic, i do not see another option.
Test jar 5.1.0: https://1drv.ms/u/c/70ea7ac46bc61c73/EYtEveV8x4lGsA_n-Y30vYcB673NLEwjPx529q-H3f57ng?e=4VSwy4
~This PR is build on top of https://github.com/openhab/openhab-addons/pull/19191 will need to rebase after that was merged.~ 
Fixes: https://github.com/openhab/openhab-addons/issues/19307
> [zwavejs] Add notification channel

- bundles/org.openhab.binding.opengarage/src/main/java/org/openhab/binding/opengarage/internal/OpenGarageCommunicationException.java
- bundles/org.openhab.binding.opengarage/src/main/java/org/openhab/binding/opengarage/internal/OpenGarageHandler.java
- bundles/org.openhab.binding.opengarage/src/main/java/org/openhab/binding/opengarage/internal/OpenGarageWebTargets.java
- bundles/org.openhab.binding.opengarage/src/main/java/org/openhab/binding/opengarage/internal/api/ControllerVariables.java
- bundles/org.openhab.binding.opengarage/src/main/java/org/openhab/binding/opengarage/internal/api/Enums.java
Per title, fixed warnings, and simplified code by using gson to parse the json from the controller.
> [opengarage] Fix warnings, use gson to parse json to simplify code

- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/connection/Clip2Bridge.java
Related to openhab/static-code-analysis#490
> [hue] Refactor `Optional` fields to nullable

- bundles/org.openhab.binding.ring/src/main/java/org/openhab/binding/ring/internal/RingHandlerFactory.java
> [ring] Fix `HttpResponseException`: HTTP protocol violation

- bundles/org.openhab.binding.avmfritz/README.md
Do we already support hint or tip boxes in markdown?
> [avmfritz] Add hint for renaming product brand from FRITZ!DECT to FRITZ!SMART
