openhab/openhab-addons

bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/PresenceDetection.java
bundles/org.openhab.binding.network/src/test/java/org/openhab/binding/network/internal/PresenceDetectionTest.java

* Use timeouts with CompletableFutures
* Use seperate executor when waiting for results
* Catch exceptions when joining CompletableFutures
* Stop previous detection when starting a new one
Fixes #16305
To test the changes use this [org.openhab.binding.network-4.2.0-SNAPSHOT.jar](https://github.com/wborn/openhab-addons/releases/download/network-20240125/org.openhab.binding.network-4.2.0-SNAPSHOT.jar).

[network] Improve threading

---

bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java

A lot of items report the same value for some time, the same `State` can be used to avoid creating the identical `State` instances again and again.

[rrd4j] Reuse the state for identical values

---

bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/ShellyBindingConstants.java

During the merge process the 10v got lost

[shelly] Re-adding Shelly Plus10V to list of supported things

---

bundles/org.openhab.binding.solax/README.md
bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/SolaxBindingConstants.java
bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/SolaxConfiguration.java
bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/SolaxHandlerFactory.java
bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/connectivity/CloudHttpConnector.java
bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/connectivity/rawdata/cloud/CloudRawDataBean.java
bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/connectivity/rawdata/cloud/Result.java
bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/connectivity/rawdata/local/LocalConnectRawDataBean.java
bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/exceptions/SolaxUpdateException.java
bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/handlers/AbstractSolaxHandler.java
bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/handlers/SolaxCloudHandler.java
bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/handlers/SolaxLocalAccessHandler.java
bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/model/InverterType.java
bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/model/cloud/CloudInverterData.java
bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/model/local/CommonLocalInverterData.java
bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/model/local/LocalInverterData.java
bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/model/local/X1HybridG4InverterData.java
bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/model/local/X3HybridG4InverterData.java
bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/model/local/X3MicOrProG2InverterData.java
bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/model/local/parsers/RawDataParser.java
bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/model/local/parsers/X1HybridG4DataParser.java
bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/model/local/parsers/X3HybridG4DataParser.java
bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/model/local/parsers/X3MicOrProG2DataParser.java
bundles/org.openhab.binding.solax/src/main/resources/OH-INF/i18n/solax.properties
bundles/org.openhab.binding.solax/src/main/resources/OH-INF/thing/channel_types.xml
bundles/org.openhab.binding.solax/src/main/resources/OH-INF/thing/cloudConnectInverter.xml
bundles/org.openhab.binding.solax/src/test/java/org/openhab/binding/solax/internal/cloud/TestCloudParser.java
bundles/org.openhab.binding.solax/src/test/java/org/openhab/binding/solax/internal/local/TestX1HybridG4Parser.java
bundles/org.openhab.binding.solax/src/test/java/org/openhab/binding/solax/internal/local/TestX3HybridG4Parser.java
bundles/org.openhab.binding.solax/src/test/java/org/openhab/binding/solax/internal/local/TestX3MicOrProG2Parser.java

Besides the direct connection to the local wi-fi module that we started to support with OpenHAB 4.1, now the binding will support also a new type - cloud connect. The documentation for the API can be obtained from the Solax web portal even though it's not very thorough.
========
Implemented a new thing type - cloud connect inverter.
Refactored the packages, model and classes to reflect that now we have two different ways to retrieve the data.
The common logic is extracted in the AbstractSolaxHandler.
The handler now requires two method implementations with the specific logics for the Local and Cloud connection:
* createConnector() - specific for the two different types of HTTP connection. 
*  updateFromData() - method that maps from the response to the specific thing type channels.
README …

[solax] Cloud connection support

---

bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/ValueEncoder.java
bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/dpt/DPTTest.java
bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/itests/Back2BackTest.java

Bug discovered with the recently introduced Back2BackTest:
Calimero uses seconds for DPT 7.002 and DPT 7.003, while OpenHab converts to milliseconds as described in KNX spec. This causes wrong scale when sending those values to the bus.
This PR introduces a workaround to get the correct values when sending.

[knx] Fix scale when sending DPT 7.002 or DPT 7.003

---

bundles/org.openhab.binding.radiothermostat/README.md

Add units and other minor readme edits.

[radiothermostat] Add units to README

---

bundles/org.openhab.binding.govee/src/main/resources/OH-INF/addon/addon.xml

Allow addon suggestion finders to send a discovery message to multicast address.
Requires https://github.com/openhab/openhab-core/pull/3943

[govee] Addon info for suggestions

---

bundles/org.openhab.persistence.mongodb/pom.xml
bundles/org.openhab.persistence.mongodb/src/main/java/org/openhab/persistence/mongodb/internal/MongoDBFields.java
bundles/org.openhab.persistence.mongodb/src/main/java/org/openhab/persistence/mongodb/internal/MongoDBItem.java
bundles/org.openhab.persistence.mongodb/src/main/java/org/openhab/persistence/mongodb/internal/MongoDBPersistenceService.java
bundles/org.openhab.persistence.mongodb/src/main/java/org/openhab/persistence/mongodb/internal/MongoDBTypeConversions.java
bundles/org.openhab.persistence.mongodb/src/test/java/org/openhab/persistence/mongodb/internal/DataCreationHelper.java
bundles/org.openhab.persistence.mongodb/src/test/java/org/openhab/persistence/mongodb/internal/DatabaseTestContainer.java
bundles/org.openhab.persistence.mongodb/src/test/java/org/openhab/persistence/mongodb/internal/ILoggingEvent.java
bundles/org.openhab.persistence.mongodb/src/test/java/org/openhab/persistence/mongodb/internal/MongoDBPersistenceServiceTest.java
bundles/org.openhab.persistence.mongodb/src/test/java/org/openhab/persistence/mongodb/internal/PersistenceTestItem.java
bundles/org.openhab.persistence.mongodb/src/test/java/org/openhab/persistence/mongodb/internal/SetupResult.java
bundles/org.openhab.persistence.mongodb/src/test/java/org/openhab/persistence/mongodb/internal/VerificationHelper.java

This pull request addresses issues #16308 and #16310, introducing significant updates and improvements to the system:
- **Improvement**: Updates the MongoDB driver for enhanced compatibility and adds comprehensive unit testing.
- **Bugfix**: Fixes handling for various item types, ensuring consistent behavior across different MongoDB versions.
The main objective is to modernize the MongoDB driver used within our system from the outdated `mongo-java-driver 2.13.1` (2015) to the current `mongo-driver-sync 4.11.1`. This upgrade not only extends support to MongoDB versions 3.6 through 6.0 but also addresses compatibility issues with MongoDB 5.0 and above, which is no longer adequately supported by the old driver.
- **Database Driver Upgrade**: Transition to `mongo-driver-sync 4.11.1`, …

[mongodb] Upgrade DB driver, add more type handlings, fix QuantityType handling

---

bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/LGWebOSHandlerFactory.java

A user reported an error with size 4 316 809 while previous max was 4 194 304.

[lgwebos] Increase limit to 5MB for Websocket text message

---

bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java

This PR will replace the nested `Map`s with a `Map` and a `record` as key. Storing values will now avoid creating a 
`ConcurrentHashMap` instance for each second to buffer the values to write.

[rrd4j] Improved the internal data structure

---

bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/handler/OpenWeatherMapOneCallHandler.java
bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/config/config.xml
bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/thing/thing-types.xml

- Remove config description for removed UV Index Thing. (Follow-up for #16369, where this was forgotten.)
- Fix OneCall Forecast Thing creates too many channels:
The default setting is to create 0 minutes, 12 hours and 6 days of forecast channels.
When creating a new OneCall Thing, actually 60 minutes, 24 hours and 8 days of forecast were created due to the thing-types, now they are removed by the Thing handler if they should not be created according to the config.
It is important to have them in the thing-types though, because otherwise the channel groups won't be ordered correctly.

[openweathermap] Finish clean-up & Fix OneCall Forecast Thing channel creation

---

bundles/org.openhab.binding.homematic/README.md
bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/common/AuthenticationHandler.java
bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/common/HomematicConfig.java
bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/AbstractHomematicGateway.java
bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/CcuGateway.java
bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/HomematicGatewayFactory.java
bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/client/XmlRpcClient.java
bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/handler/HomematicBridgeHandler.java
bundles/org.openhab.binding.homematic/src/main/resources/OH-INF/i18n/homematic.properties
bundles/org.openhab.binding.homematic/src/main/resources/OH-INF/i18n/homematic_de.properties
bundles/org.openhab.binding.homematic/src/main/resources/OH-INF/thing/bridge.xml

This PR enable authorization (resolves #8625 ) when accessing Homematic Server (like CCU). I've added three new binding configuration values to enable this. Now it's possible to disable unauthorized accesses to the CCU. I added some documentation which is relevant for testing.
I tested the new feature with raspberrymatic and OH running in a K8s environment. I thinks it's necessary to test it with other settings.

[homematic] Add Authentication

---

bundles/org.openhab.binding.shelly/src/main/resources/sniplets/header.html

The header.html has a closing head tag, but no opener head tag. This commit fixes it.

[shelly] Fix missing starting head tag in manager web ui

---

bundles/org.openhab.transform.jsonpath/README.md

[jsonpath] change code-fence so it doesn't overlap with logo

---

bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/model/InverterType.java
bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/model/local/X1BoostAirMiniInverterData.java
bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/model/local/parsers/X1BoostAirMiniDataParser.java
bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/model/local/parsers/X1HybridG4DataParser.java
bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/model/local/parsers/X3HybridG4DataParser.java
bundles/org.openhab.binding.solax/src/test/java/org/openhab/binding/solax/internal/local/AbstractParserTest.java
bundles/org.openhab.binding.solax/src/test/java/org/openhab/binding/solax/internal/local/TestX1BoostAirMiniDataParser.java
bundles/org.openhab.binding.solax/src/test/java/org/openhab/binding/solax/internal/local/TestX1HybridG4Parser.java
bundles/org.openhab.binding.solax/src/test/java/org/openhab/binding/solax/internal/local/TestX3HybridG4Parser.java

- Added support for yet another inverter upon user request.
- Extracted the common logic for the local wi-fi connect inverter tests into an abstract class, so only the values are compared in the child test classes.
Waiting for user confirmation that everything works after the cherry pick on top of the main branch's last major merge in the addon and then will remove the WIP label.
Best regards,
Konstantin

[solax] Support for x1 mini inverter local connection

---

.github/workflows/ci-build.yml

This fixes the last remaining deprecation warning:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20

Upgrade get-changed-files GHA dependency

---

bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/DebuggingGraalScriptEngine.java
bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/OpenhabGraalJSScriptEngine.java
bundles/org.openhab.automation.jsscripting/suppressions.properties

- Use the file name, rule UID or transformation UID in the stack trace printed on a JS error.
- Minor code improvements.
- Suppress a warning.

[jsscripting] Improve logging on JS error

---

bundles/org.openhab.binding.mybmw/README.md
bundles/org.openhab.binding.mybmw/src/main/java/org/openhab/binding/mybmw/internal/MyBMWConstants.java
bundles/org.openhab.binding.mybmw/src/main/java/org/openhab/binding/mybmw/internal/handler/RemoteServiceExecutor.java
bundles/org.openhab.binding.mybmw/src/main/java/org/openhab/binding/mybmw/internal/handler/VehicleHandler.java
bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/config/thing-config.xml
bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/i18n/mybmw.properties
bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/thing/ev-vehicle-update-group.xml
bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/thing/thing-bev.xml
bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/thing/thing-bev_rex.xml
bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/thing/thing-conv.xml
bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/thing/thing-phev.xml
bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/thing/vehicle-update-channel-types.xml
bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/thing/vehicle-update-group.xml
bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/update/thing-update.xml
bundles/org.openhab.binding.mybmw/src/test/resources/responses/BEV2/charging_sessions.json
bundles/org.openhab.binding.mybmw/src/test/resources/responses/BEV2/charging_statistics.json
bundles/org.openhab.binding.mybmw/src/test/resources/responses/BEV2/vehicles_base.json
bundles/org.openhab.binding.mybmw/src/test/resources/responses/BEV4/charging_sessions.json
bundles/org.openhab.binding.mybmw/src/test/resources/responses/BEV4/charging_statistics.json
bundles/org.openhab.binding.mybmw/src/test/resources/responses/BEV5/charging_sessions.json
bundles/org.openhab.binding.mybmw/src/test/resources/responses/BEV5/charging_statistics.json
bundles/org.openhab.binding.mybmw/src/test/resources/responses/PHEV/charging_sessions.json
bundles/org.openhab.binding.mybmw/src/test/resources/responses/PHEV/charging_statistics.json

This PR will add some functionalities:
- disable automated refresh of the vehicle data by setting the refresh interval to 0
- enable manual refresh by forcing update of parts of the vehicle data (state, charging statistics, image)
Resolves: #16351

[mybmw] Improve data refresh handling

---

bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/console/BoschShcCommandExtension.java
bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/BridgeHandler.java
bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/dto/Device.java
bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/dto/PublicInformation.java
bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/dto/Scenario.java
bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/dto/SoftwareUpdateState.java
bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/dto/SubscribeResult.java
bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/dto/UserDefinedState.java
bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/discovery/ThingDiscoveryService.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/console/BoschShcCommandExtensionTest.java

Added command to list SHC devices and mapping to openhab devices and related services.
The new console command lists Bosch SHC devices and openhab support.
Uses the SHC API to get all SHC devices and SHC services and tries to lookup openhab devices and implemented service classes.
The command should help to get an overview what devices are supported, see #14672.
The implementation uses pull request #13615 as example to start.

[boschshc] Add command to list SHC device mappings

---

bundles/org.openhab.automation.jythonscripting/README.md
bundles/org.openhab.automation.jythonscripting/pom.xml

Remove the deprecation notice in jython readme
https://community.openhab.org/t/jython-is-not-deprecated/154187

[jythonscripting] Upgrade to Jython 2.7.3

---

bundles/org.openhab.binding.amazondashbutton/pom.xml
bundles/org.openhab.binding.doorbird/pom.xml
bundles/org.openhab.binding.doorbird/src/main/feature/feature.xml
bundles/org.openhab.binding.systeminfo/pom.xml
bundles/org.openhab.binding.tellstick/pom.xml
bundles/org.openhab.binding.tellstick/src/main/feature/feature.xml
bundles/org.openhab.voice.voskstt/pom.xml
pom.xml

PR will update the net.java.dev.jna library.
Updates the oshi-core lib for the system info binding, have tested it works.
Gets all bindings onto the same version. I count 5 different versions are/were in use.
Makes it easier to keep them all updated in the future.

Bump net.java.dev.jna lib to version 5.14.0

---

bundles/org.openhab.binding.http/README.md

Added "The relevant transformation service needs to be installed via the Main UI before use." (I wasted several hours trying to figure out why my JSONPATH transformation wasn't working.)

[http] Document translation services need to be installed before usage

---

bundles/org.openhab.binding.fronius/README.md

Link to the Fronius Homepage was broken. 
More consistent spelling of "Thing"

[Fronius] Fix broken link & spelling issues

---

bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/api/EcobeeApi.java

The error code 14 (token expired) returned by the Ecobee API is not handled correctly by the binding. No matter how much time passes, the AccessTokenResponse `isExpired` method never returns true. I don't know why this is the case. I can only assume there's something wrong with the access token returned from Ecobee.
Therefore, the only way to recover from this condition (short of the user manually disabling and enabling the account thing) is to close and recreate the OAuthClientService (which is essentially what happens when you disable/enable the account thing).
Also raising the log level from DEBUG to INFO to give more visibility in the log to when the condition occurs.

[ecobee] Fix for error code 14 (token expired)

---

bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/DebuggingGraalScriptEngine.java
bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/OpenhabGraalJSScriptEngine.java

Regression from #16445.
Logger initialization needs access to the ScriptContext, however does GraalJS not allow multi-thread access to the ScriptContext. 
Therefore logger initialization needs to be included in the existing multi-thread access synchronization.

[jsscripting] Fix multi-thread access requested by logger initialization

---

bundles/org.openhab.binding.evcc/README.md
bundles/org.openhab.binding.evcc/src/main/java/org/openhab/binding/evcc/internal/EvccBindingConstants.java
bundles/org.openhab.binding.evcc/src/main/java/org/openhab/binding/evcc/internal/EvccHandler.java
bundles/org.openhab.binding.evcc/src/main/java/org/openhab/binding/evcc/internal/api/dto/Loadpoint.java
bundles/org.openhab.binding.evcc/src/main/java/org/openhab/binding/evcc/internal/api/dto/Vehicle.java
bundles/org.openhab.binding.evcc/src/main/resources/OH-INF/i18n/evcc.properties
bundles/org.openhab.binding.evcc/src/main/resources/OH-INF/thing/thing-types.xml

1. Fixed channels vehicle/capacity (bugfix)
* Capacity channel is under vehicle and no longer under loadpoint since evcc 0.123.1 
2. Fixed channel vehicle/vehicleName (bugfix)
* Update was done using a wrong channelUID 
3. Added channels for current Vehicle/HeatingDevice per Loadpoint (enhancement)
* The new ChannelGroup provides direct access to the vehicle/heating device connected to the loadpoint without the indirection using the `vehicleName`
* Example:
* Access vehicle title in a rule before this PR:
* `const vehicleTitle = items.getItem("evcc" + items.evccLoadpoint0_VehicleName.state + "_VehicleTitle").state;`
* Now:
* `const vehicleTitle = items.evccLoadpoint0CurrentVehicle_VehicleTitle.state;`
* Users with a big fleet of vehicles will benefit allot. Because they must no longer add …

[evcc] fixed channels vehicle/capacity and vehicle/vehicleName, added channels for current Vehicle/HeatingDevice per Loadpoint

---

bundles/org.openhab.binding.tasmotaplug/README.md
bundles/org.openhab.binding.tasmotaplug/src/main/java/org/openhab/binding/tasmotaplug/dto/TasmotaDTO.java
bundles/org.openhab.binding.tasmotaplug/src/main/java/org/openhab/binding/tasmotaplug/internal/TasmotaPlugBindingConstants.java
bundles/org.openhab.binding.tasmotaplug/src/main/java/org/openhab/binding/tasmotaplug/internal/TasmotaPlugHandlerFactory.java
bundles/org.openhab.binding.tasmotaplug/src/main/java/org/openhab/binding/tasmotaplug/internal/handler/TasmotaPlugHandler.java
bundles/org.openhab.binding.tasmotaplug/src/main/resources/OH-INF/i18n/tasmotaplug.properties
bundles/org.openhab.binding.tasmotaplug/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.tasmotaplug/src/main/resources/OH-INF/update/update.xml

Add energy monitoring channels to tasmotaplug.

[tasmotaplug] Add energy monitor channels

---

bundles/org.openhab.binding.keba/README.md
bundles/org.openhab.binding.keba/src/main/java/org/openhab/binding/keba/internal/KebaBindingConstants.java

Fixed https://github.com/openhab/openhab-addons/issues/16472.
The following wallboxes from the x-series are now supported as well:
- x-series 4G, w/o LM: identified via `S` in the product designation string
- x-series WLAN, w/o LM: identfied via `U` in the product designation string
Fixed type mapping for identifier 'A':
- was x-series but actually is c-series
Test Build: [org.openhab.binding.keba-4.2.0-SNAPSHOT-2024-03-01.zip](https://www.dropbox.com/scl/fi/4f10fw3d2dcgmzxfzbm7h/org.openhab.binding.keba-4.2.0-SNAPSHOT-2024-03-01.zip?rlkey=rcxs7gm5uypy6oz6aao1ybas8&dl=0)

[keba] Add support for additional x-series wallboxes

---

bundles/org.openhab.binding.ecovacs/src/main/java/org/openhab/binding/ecovacs/internal/api/commands/GetErrorCommand.java
bundles/org.openhab.binding.ecovacs/src/main/java/org/openhab/binding/ecovacs/internal/api/commands/SpotAreaCleaningCommand.java
bundles/org.openhab.binding.ecovacs/src/main/java/org/openhab/binding/ecovacs/internal/api/impl/JsonReportParser.java
bundles/org.openhab.binding.ecovacs/src/main/java/org/openhab/binding/ecovacs/internal/api/model/CleanMode.java
bundles/org.openhab.binding.ecovacs/src/main/java/org/openhab/binding/ecovacs/internal/api/model/DeviceCapability.java
bundles/org.openhab.binding.ecovacs/src/main/java/org/openhab/binding/ecovacs/internal/handler/EcovacsVacuumHandler.java
bundles/org.openhab.binding.ecovacs/src/main/resources/devices/supported_device_list.json

[ecovacs] Add support for DEEBOT X2 Omni

---

bundles/org.openhab.binding.ecovacs/src/main/java/org/openhab/binding/ecovacs/internal/api/EcovacsApiException.java
bundles/org.openhab.binding.ecovacs/src/main/java/org/openhab/binding/ecovacs/internal/api/impl/EcovacsApiImpl.java

The API has differing responses depending on device type. If our understanding of the JSON format differs from that of the API, make sure to properly set the thing OFFLINE and to log a meaningful message.
Related to #16187

[ecovacs] Handle invalid JSON responses properly

---

bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/MieleApplianceHandler.java

Fix small corner-case bug where commands would be sent to the previously configured appliance, if the ID is blanked in the configuration.

[miele] Fix sticky appliance ID

---

bundles/org.openhab.binding.energidataservice/README.md
bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/ApiController.java
bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/EnergiDataServiceBindingConstants.java
bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/api/Dataset.java
bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/api/dto/CO2EmissionRecord.java
bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/api/dto/CO2EmissionRecords.java
bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/handler/EnergiDataServiceHandler.java
bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/i18n/energidataservice.properties
bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/thing/channel-groups.xml
bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/thing/channel-types.xml
bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/thing/thing-service.xml
bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/update/instructions.xml

Publishes CO₂ emission prognosis as time series:
**Draft/unfinished work.**
Depends on openhab/openhab-core#4069

[energidataservice] Add CO₂ emission channels

---

bundles/org.openhab.binding.orbitbhyve/src/main/java/org/openhab/binding/orbitbhyve/internal/handler/OrbitBhyveBridgeHandler.java
bundles/org.openhab.binding.orbitbhyve/src/main/java/org/openhab/binding/orbitbhyve/internal/model/OrbitBhyveDevice.java

Some "devices" responses contain a null value in the `location` attribute. Json parsing failed because JsonObject will not deserialize a null value. Also added a check for `JsonSyntaxException` and logged the stack trace to better be able to track down parsing issues.
BTW, I noticed that `location` is not used anywhere in the binding. So, an alternative would be to just remove it from the DTO. However, I still think it's a good idea to catch `JsonSyntaxException` and log the stack trace to be able to track down parsing issues.
This doesn't seem critical enough to cherry pick to 4.1.x.

[orbitbhyve] Handle null location attribute in devices json

---

bundles/org.openhab.binding.ecovacs/src/main/java/org/openhab/binding/ecovacs/internal/EcovacsBindingConstants.java
bundles/org.openhab.binding.ecovacs/src/main/java/org/openhab/binding/ecovacs/internal/api/EcovacsApiConfiguration.java
bundles/org.openhab.binding.ecovacs/src/main/java/org/openhab/binding/ecovacs/internal/api/EcovacsDevice.java
bundles/org.openhab.binding.ecovacs/src/main/java/org/openhab/binding/ecovacs/internal/api/impl/EcovacsApiImpl.java
bundles/org.openhab.binding.ecovacs/src/main/java/org/openhab/binding/ecovacs/internal/api/impl/EcovacsApiUrlFactory.java
bundles/org.openhab.binding.ecovacs/src/main/java/org/openhab/binding/ecovacs/internal/api/impl/EcovacsIotMqDevice.java
bundles/org.openhab.binding.ecovacs/src/main/java/org/openhab/binding/ecovacs/internal/api/impl/EcovacsXmppDevice.java
bundles/org.openhab.binding.ecovacs/src/main/java/org/openhab/binding/ecovacs/internal/api/impl/dto/response/portal/PortalCleanLogRecord.java
bundles/org.openhab.binding.ecovacs/src/main/java/org/openhab/binding/ecovacs/internal/api/impl/dto/response/portal/PortalCleanResultsResponse.java
bundles/org.openhab.binding.ecovacs/src/main/java/org/openhab/binding/ecovacs/internal/api/model/DeviceCapability.java
bundles/org.openhab.binding.ecovacs/src/main/java/org/openhab/binding/ecovacs/internal/api/util/HashUtil.java
bundles/org.openhab.binding.ecovacs/src/main/java/org/openhab/binding/ecovacs/internal/handler/EcovacsApiHandler.java
bundles/org.openhab.binding.ecovacs/src/main/java/org/openhab/binding/ecovacs/internal/handler/EcovacsVacuumHandler.java
bundles/org.openhab.binding.ecovacs/src/main/resources/devices/supported_device_list.json

The existing cleaning logs API is only populated for devices older than the T9/N9 generation; all newer devices use a new API. Since the new API isn't populated for older devices, select the correct API depending on device type.

[ecovacs] Add support for new API for fetching cleaning logs

---

bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/data/NetatmoConstants.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/NAThing.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/Capability.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/ChannelHelperCapability.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/EnergyCapability.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/HomeCapability.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/channelhelper/AirQualityChannelHelper.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/channelhelper/SecurityChannelHelper.java

[netatmo] Thing properties were no more provided

---

bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/api/dto/clip2/Resource.java
bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/Clip2ThingHandler.java

A step size of 30 with a value range of 0..100 leads to only 4 steps, which additionally are spaced unevenly. Shrink the step size to 10, which yields 10 evenly spaced steps.
While at it, also deduplicate the increase/decrease code, which had slightly different implementation in both branches.
Fixes #16532

[hue] Shrink step size for increase/decrease commands

---

bundles/org.openhab.binding.caddx/README.md

Small correction to the binding's README file.
- Added missing ignoreZoneStatusTransitions parameter

[caddx] Amend README with missing bridge configuration parameter

---

bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/manager/ShellyManagerPage.java

I have 2 shelly plug s sockets. None of them has a device name or service name.
The function getDisplayName returns a empty string and in ShellyManagerOverviewPage.java in the sortedMap the empty string is used as the key. The result is that the overview page shows only one row.
After the fix, it shows

[shelly] Use macaddress as a fallback name

---

bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/provider/ShellyChannelDefinitions.java

The Shelly Pro 3EM does not show the accumulated channels on the device, although the values are transferred from the device.
The reason seems to be this [commit](https://github.com/openhab/openhab-addons/pull/15922/commits/3e120b7ecd4cfd0593a09c22fb2de0afebe9bdaf). The **Pro 3EM** has no internal relay (only available as an add-on), unlike the **3EM** and the **Pro EM**.
Fixes #16552 
openHAB Community: [Discussion](https://community.openhab.org/t/shelly-binding/56862/3742)

[shelly] Enable accumulated channels for Shelly Pro 3EM

---

bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/config/ConfigurationLevel.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/ApiBridgeHandler.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/servlet/NetatmoServlet.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/servlet/WebhookServlet.java
bundles/org.openhab.binding.netatmo/src/main/resources/OH-INF/i18n/netatmo.properties

This small PR just reports the granting path in the status of the bridge so the user does not have to search in the log to find the path to grant the binding against the API
Extracted from #16489

[netatmo] Enhance bridge status reporting

---

bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/CommonInterface.java

This solves the `ClassCastException` identified [here](https://github.com/openhab/openhab-addons/pull/16489#issuecomment-2001961797)
Extracted from #16489

[netatmo] Fix `ClassCastException`

---

bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/internal/POP3IMAPHandler.java

Reported on the community forum. Could be backported to 4.1.x
Under some (unknown) circumstances an `IMAPInputstream` is returned as content instead of a `MimeMultipart`.

[mail] Fix content processing

---

bundles/org.openhab.persistence.mapdb/src/main/java/org/openhab/persistence/mapdb/internal/MapDbPersistenceService.java

[mapdb] Fix missing service pid

---

bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/DebuggingGraalScriptEngine.java
bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/OpenhabGraalJSScriptEngine.java
bundles/org.openhab.automation.jsscripting/suppressions.properties

Add-on part of the fix for #16462.

[jsscripting] Fix memory leak on script execution failure

---

bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/HomeCapability.java

Complement to issue #16561
HomeData answers only holds general configuration information - there is no need to request it at every refresh.
Startup of the binding and thing activation are enough for this.

[netatmo] Lower Home API request quantity

---

bundles/org.openhab.binding.bluetooth.generic/pom.xml
bundles/org.openhab.binding.dbquery/pom.xml
bundles/org.openhab.binding.jellyfin/pom.xml
bundles/org.openhab.binding.telegram/pom.xml
bundles/org.openhab.binding.telegram/src/main/java/org/openhab/binding/telegram/internal/TelegramHandler.java
bundles/org.openhab.persistence.influxdb/pom.xml
bundles/org.openhab.voice.watsonstt/pom.xml
pom.xml

Update various libraries to their latest versions, and also make it easier to keep multiple bindings in sync with the latest and same version. No need to use 3+ different versions of the same library.
Updating java-telegram-bot-api to tackle some of the Telegram bugs and feature requests.

Bump Kotlin, okhttp, okio, and java-telegram-bot-api libraries

---

bundles/org.openhab.binding.bluetooth.govee/src/main/java/org/openhab/binding/bluetooth/gattserial/GattSocket.java
bundles/org.openhab.binding.bluetooth.govee/src/test/java/org/openhab/binding/bluetooth/govee/internal/readme/ThingTypeTableGenerator.java
bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/api/rest/HomeManager.java
bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/connection/Clip2Bridge.java
bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/mapping/MqttTopicClassMapperTests.java
bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/discovery/ObjectPropertyRequest.java
bundles/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/rio/AbstractRioHandlerCallback.java
bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/protocol/RemoteControllerLegacy.java
bundles/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/handler/SpotifyDynamicStateDescriptionProvider.java
bundles/org.openhab.binding.verisure/src/main/java/org/openhab/binding/verisure/internal/handler/VerisureThingHandler.java
pom.xml

Static code analysis: SAT plugin 0.16.0 has been released yesterday.
https://github.com/openhab/static-code-analysis/releases/tag/0.16.0
This PR upgrades to this version and modifies code which leads to build error with new version of SpotBugs.
Refs: https://github.com/openhab/openhab-distro/issues/1590

Upgrade SAT plugin to 0.16.0

---

bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/BridgeHandler.java
bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/ScenarioHandler.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/console/BoschShcCommandExtensionTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/AbstractBatteryPoweredDeviceHandlerTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/AbstractBoschSHCDeviceHandlerTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/AbstractBoschSHCHandlerTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/AbstractPowerSwitchHandlerTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/AbstractPowerSwitchHandlerWithPowerMeterTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/bridge/BridgeHandlerTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/bridge/LongPollingTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/bridge/ScenarioHandlerTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/bridge/dto/ScenarioTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/intrusion/IntrusionDetectionHandlerTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/shuttercontrol/ShutterControl2HandlerTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/userdefinedstate/UserStateHandlerTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/discovery/BridgeDiscoveryParticipantTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/discovery/ThingDiscoveryServiceTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/services/userstate/dto/UserStateServiceStateTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/tests/common/CommonTestUtils.java

Boosts the unit test coverage for the `boschshc` binding in `src/main/java`
to 94%.
Main code changes:
* made some methods package-protected in order to be testable
* fix typo in exception message (in class `BridgeHandler`)
Test code changes:
* add lots of additional tests
* refactor redundant tests to parameterized tests
* add utility class providing arguments for common parameterized tests
* fix a problem caused by wrong order of `super.beforeEach()` calls
* remove unnecessary `lenient()` configurations

[boschshc] Boost unit test coverage

---

bundles/org.openhab.binding.lutron/doc/leapnotes.md

`get_lutron_cert.py` no longer exists in the referenced repository.

[lutron] update instructions for LEAP authentication

---

bundles/org.openhab.binding.boschshc/README.md
bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/BoschSHCBindingConstants.java
bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/BoschSHCHandlerFactory.java
bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/lightcontrol/DimmerHandler.java
bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/discovery/ThingDiscoveryService.java
bundles/org.openhab.binding.boschshc/src/main/resources/OH-INF/i18n/boschshc.properties
bundles/org.openhab.binding.boschshc/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/lightcontrol/DimmerHandlerTest.java

Adds support for Bosch Smart Home Dimmer devices.
* Add thing type definition
* Re-generate i18n properties file
* Implement handler
* Register handler in factory
* Register dimmer in discovery
* Add unit tests
* Add documentation
Resolves #16241

[boschshc] Add support for Dimmer

---

pom.xml

* Support Java 17 and 21, default compilation to Java 17 class files
* Add profile "j21" to compile to Java 21 class files
* Bump ecj to 3.36.0
Note that this PR does not fully cover all measures required for Java 21. I factored out changes to persistence.jpa: #16591.
Refs: https://github.com/openhab/openhab-distro/issues/1590

Allow for compiling with Java 21

---

bundles/org.openhab.binding.awattar/src/main/resources/OH-INF/addon/addon.xml

According to the [documentation](https://www.openhab.org/addons/bindings/awattar/) this binding is for the German and Austrian provider aWATTar, and Thing configuration parameter `country` should be either AT or DE.

[awattar] Declare countries

---

bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcMysqlDAO.java

See analysis here: https://github.com/openhab/openhab-addons/issues/15697#issuecomment-2032937666
And test results here: https://github.com/openhab/openhab-addons/issues/15697#issuecomment-2032983898
I can currently only test MySQL, so I have scoped the fix accordingly, although other implementations may suffer from something similar.
Resolves #15697
Regression of openhab/openhab1-addons#4605 (in MySQL, both `DATETIME` and `TIMESTAMP` support microsecond precision)

[jdbc] Provide better MySQL datatype for `DateTimeType`

---

bundles/org.openhab.binding.senechome/src/main/java/org/openhab/binding/senechome/internal/SenecHomeApi.java

Fixes #12900. Add a timeout for requests to the local Senec device. Currently there may occur some endlessly hanging requests which basically freeze the values provided by the binding.

[Senec] Add request timeout

---

bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/api/EcobeeApi.java

Improve handling of error code 14 by forcing a token refresh rather that closing/creating the oauth client service.
@jlaur This is what we talked about previously, and it seems to be working fine for me. It had some issues the first time it executed for me (it eventually worked), but I think it's because Ecobee was restarting servers multiple times. Since then it has worked flawlessly.
I don't think there's a compelling need to cherry pick this for 4.1.x since 4.1.2 is working fine with the oauth client service close/create. But that's your call.

[ecobee] Improve handling of error code 14

---

bundles/org.openhab.binding.miio/README.base.md
bundles/org.openhab.binding.miio/README.md
bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoCommand.java
bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoVacuumHandler.java
bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/robot/RobotCababilities.java
bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/robot/StatusDTO.java
bundles/org.openhab.binding.miio/src/main/resources/OH-INF/i18n/miio.properties
bundles/org.openhab.binding.miio/src/main/resources/OH-INF/thing/vacuumThing.xml

This PR adds the mop mode feature found in the Roborock S7 vacuum cleaners.
Closes #16607

[miio] Add Roborock S7/S7MaxV mop mode

---

bundles/org.openhab.binding.lutron/README.md
bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/BaseKeypadHandler.java
bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/LeapBridgeHandler.java
bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/PicoKeypadHandler.java
bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/protocol/leap/LeapMessageParser.java
bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/protocol/leap/LeapMessageParserCallbacks.java
bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/protocol/leap/Request.java
bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/protocol/leap/dto/ButtonEvent.java
bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/protocol/leap/dto/ButtonStatus.java

I've only tested this with a PJ2-3BRL connecting to a Caseta SmartBridge 2. But I'm pretty sure I handled all of the id translation correctly for other types of Picos that don't happen to have sequential button ids.
I used pylutron_caseta to guide me somewhat in implementing.

[lutron] Implement button press notifications for Picos from LEAP

---

bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/api/dto/clip2/Power.java

Resolves #16617 
Sometimes when new battery devices are added to the bridge, the device will not have had enough time on the network for its battery state to have been queried by the bridge. In such cases the bridge returns null in the `Power.batteryState` DTO field, and this causes an NPE.
This PR resolves that issue.

[hue] Fix potential NPE when new battery devices are added to bridge

---

bundles/org.openhab.binding.siemensrds/src/main/resources/OH-INF/thing/thing-types.xml

Remove "r.H." from state description pattern.

[siemensrds] Remove r.H. from humidity state description pattern

---

bundles/org.openhab.binding.intesis/src/main/java/org/openhab/binding/intesis/internal/handler/IntesisHomeHandler.java

I have changed the login process so that the binding now only logs in at the beginning and logs out at the end of the lifetime. If a request fails due to a missing login or an invalid session ID, a new login attempt is made.
This ensures that
- Several requests can be sent in direct succession (if I switch the air conditioning from cooling to heating, I also want to change the slats at the same time)
- Less traffic is generated as there is not a constant logout and login again
- Ideally, the login credentials should only be visible once at startup
This change fixes #15502.
Signed-off-by: Christoph <fd0cwp@gmx.de>

[intesis] Session Handling improved

---

bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/PercentageValue.java

Since #16307, the state could get set to NULL, not just UNDEF, and once it got in that state PercentageValue would throw an error every time it received any other message or command, effectively rendering the channel broken until openHAB restarted.

[mqtt] fix UnDefType comparison in PercentageValue

---

bundles/org.openhab.binding.tibber/README.md
bundles/org.openhab.binding.tibber/src/main/java/org/openhab/binding/tibber/internal/TibberBindingConstants.java
bundles/org.openhab.binding.tibber/src/main/java/org/openhab/binding/tibber/internal/handler/TibberHandler.java
bundles/org.openhab.binding.tibber/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.tibber/src/main/resources/OH-INF/update/instructions.xml

Makes net consumption/production since last hour shift available

[tibber] Add two channels: consumption and production for current hour

---

bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/api/DatahubTariffFilterFactory.java

Reported here:
https://community.openhab.org/t/energi-data-service-binding-4-0-0-0-4-1-0-0/144370/48

[energidataservice] Update tariff filter for Radius

---

bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/channelhelper/DoorTagChannelHelper.java

Apparently door tags may report other values than open / closed.
Resolves #16629
From the event feed, the no_news answer corresponds to a signal lost event in the Netatmo UI, so setting state to UNDEF seems appropriate.

[netatmo] IllegalArgumentException for DoorTags

---

bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/handler/EnergiDataServiceHandler.java

Today I noticed that my [dishwasher price calculation automation](https://community.openhab.org/t/dishwasher-price-calculation-automation/139207) did not work as expected, and investigated why.
I found that is what caused by a simple lack of spot price data from the service: https://www.energidataservice.dk/news
> 2024-04-12
>Currently we experience technical problems updating a number of datasets. We are working on solving the error.
Even though the spot price channel may be `UNDEF` (when prices are very behind) and the `nextCall` property is before ~13:00 next day, the binding is probably a bit too silent in this case. Thus a warning would help. Since retries use an exponential backoff strategy, they should not occur too often or spam the log in any way.

[energidataservice] Log warning when spot prices are unavailable

---

bundles/org.openhab.binding.energidataservice/README.md
bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/action/EnergiDataServiceActions.java
bundles/org.openhab.binding.energidataservice/src/test/java/org/openhab/binding/energidataservice/internal/action/EnergiDataServiceActionsTest.java

Action `calculatePrice` would return 0 when the calculation could not be performed due to missing prices within the requested period.
Unfortunately this result is ambiguous since 0 is a valid price, even if unlikely.
Therefore the method will now return `null` if data is missing.
This can break rules. However, usually this would only affect rules during service outages. Also, rules might have been broken in other ways already: if not checking for the value 0, this could result in wrong decisions being made when data is not available. Therefore I would consider both the risk and impact quite low. Still, I can prepare a breaking change note for this.

[energidataservice] Improve error handling for action `calculatePrice`

---

bundles/org.openhab.binding.tr064/README.md
bundles/org.openhab.binding.tr064/src/main/resources/channels.xml

Supersedes #16454
See discussion in other PR. This makes the channel naming more consistent, but requires re-linking of the channel (we can rename channels, but not re-link them with update instructions). Therefore the old channels are still supported and will be removed in a future version.

[tr064] Enable fourth WiFi channel and improvements

---

bundles/org.openhab.binding.energidataservice/README.md
bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/ApiController.java
bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/handler/EnergiDataServiceHandler.java

Avoid trying to request CO₂ emission data for price areas outside Denmark.
No data would be found, which would result in the Thing showing as **OFFLINE** with description "No records" (without impact on updates for other channels though).
When linking a CO₂ emission channel while configured price area is not DK*, a warning will be logged.
Regression of #16330

[energidataservice] Restrict CO₂ emission datasets to price area DK1/DK2

---

bundles/org.openhab.binding.orbitbhyve/src/main/java/org/openhab/binding/orbitbhyve/internal/handler/OrbitBhyveBridgeHandler.java
bundles/org.openhab.binding.orbitbhyve/src/main/java/org/openhab/binding/orbitbhyve/internal/handler/OrbitBhyveSprinklerHandler.java

Need to compare the device id from the thing config with the device id's in the devices array. It was comparing the id of the thing with the id of the thing.

[orbitbhyve] Fix handling of multiple sprinkler controllers

---

bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/ApiController.java
bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/handler/EnergiDataServiceHandler.java
bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/retry/RetryPolicyFactory.java

The number of **future** spot prices changes throughout a day:
- 00:00 (midnight): 24 prices should be available, i.e. all hours of the day.
- 01:00: 23 prices available.
- (...)
- 11:00: 13 prices available.
- 12:00: 12 prices available.
- 13:00: 35 prices available (11 for this day and 24 for tomorrow)
- 14:00: 34 prices available
- (...)
We always receive 24 prices per day, so the logic for determining if we have everything is quite simple:
- We should always have at least 13 future prices.
- Except between 12:00 and 13:00, we have only 12.
If everything is working, we'll fetch new prices once per day - around 13:00. However, if we are missing spot prices for a longer period, we'll have to retry.
The logic here had a flaw. It said:
- Less than 13 prices from 13:00? Let's apply …

[energidataservice] Adjust retry policy for extended spot price unavailability

---

bundles/org.openhab.binding.openwebnet/README.md
bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetThermoregulationHandler.java

Depends on https://github.com/openhab/openhab-addons/pull/16605
This PR fixes a bug when trying to update setPoint when local offset is in use on a zone thermostat.
Fixes #16193.

[openwebnet] Thermo: fix update zone setPoint when local offset is in use

---

bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/handler/EnergiDataServiceHandler.java

Decouple updating of all tariff time series from the spot price time series so they are updated independently of each other.
This fixes the persistence of historic/future tariffs when spot prices are unavailable or when the spot price channel is not linked to any items.

[energidataservice] Fix tariff time series when spot prices are unavailable

---

bundles/org.openhab.binding.evcc/README.md
bundles/org.openhab.binding.evcc/src/main/java/org/openhab/binding/evcc/internal/EvccHandler.java
bundles/org.openhab.binding.evcc/src/main/java/org/openhab/binding/evcc/internal/api/dto/Battery.java
bundles/org.openhab.binding.evcc/src/main/java/org/openhab/binding/evcc/internal/api/dto/PV.java
bundles/org.openhab.binding.evcc/src/main/java/org/openhab/binding/evcc/internal/api/dto/Result.java

Implementation of https://github.com/openhab/openhab-addons/issues/16658 due to https://github.com/evcc-io/evcc/issues/13463.
The change is backward compatible.

[evcc] Adjust to evcc 0.125.0 API changes

---

bundles/org.openhab.binding.renault/src/main/java/org/openhab/binding/renault/internal/api/MyRenaultHttpSession.java

As per the excellent Bug report this apply the suggested fix.  
The odometer information no longer works in version 2 of the API so switching to V1 restores this channel.  This is a problem on the Renault API but the suggested fix repairs the binding.
This was built and tested on my installation and the odometer value is updated again.  Also the Bug report suggest this fix worked on their test installation.

[Renault] Fix retrieval of cockpit/odometer information

---

bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcMariadbDAO.java
bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcMysqlDAO.java

See https://dev.mysql.com/doc/refman/8.3/en/storage-requirements.html and namely:
> The effective maximum number of bytes that can be stored in a [VARCHAR](https://dev.mysql.com/doc/refman/8.3/en/char.html) or [VARBINARY](https://dev.mysql.com/doc/refman/8.3/en/binary-varbinary.html) column is subject to the maximum row size of 65,535 bytes, which is shared among all columns. For a [VARCHAR](https://dev.mysql.com/doc/refman/8.3/en/char.html) column that stores multibyte characters, the effective maximum number of characters is less. For example, utf8mb4 characters can require up to four bytes per character, so a [VARCHAR](https://dev.mysql.com/doc/refman/8.3/en/char.html) column that uses the utf8mb4 character set can be declared to be a maximum of 16,383 characters. See [Section 10.4.7, …

[jdbc] Reduce the default character limit for `VARCHAR` columns in MySQL

---

bundles/org.openhab.binding.energidataservice/README.md
bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/ApiController.java
bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/EnergiDataServiceBindingConstants.java
bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/PriceComponent.java
bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/PriceListParser.java
bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/action/EnergiDataServiceActions.java
bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/api/DatahubTariffFilter.java
bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/api/DateQueryParameter.java
bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/console/EnergiDataServiceCommandExtension.java
bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/handler/EnergiDataServiceHandler.java
bundles/org.openhab.binding.energidataservice/src/test/java/org/openhab/binding/energidataservice/internal/PriceListParserTest.java

This introduces a console command for downloading and persisting historic prices in a given period.
This can be useful after extended service interruptions, data unavailability, or openHAB downtime. If the persisted data is used for historic calculations (e.g. energy bill), gaps are quite undesired.
This will only update the individual price components. If a Group `SUM` is used for calculating the total hourly price, historic persistence is not supported - see openhab/openhab-core#3869.
Related to [technical issue](https://www.energidataservice.dk/news):
> Over the weekend from Friday April 12th to Monday April 15th 2024, we experienced technical problems updating a number of datasets (including: Elspot Prices, Power System Right Now, CO2 Emission, Regulating Balance Power Data, …

[energidataservice] Introduce console command for history persistence

---

bundles/org.openhab.binding.openwebnet/README.md
bundles/org.openhab.binding.openwebnet/pom.xml
bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/actions/OpenWebNetBridgeActions.java
bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/actions/OpenWebNetCENActions.java
bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetBridgeHandler.java
bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetThermoregulationHandler.java
bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/serial/SerialPortAdapter.java
bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/i18n/openwebnet.properties

This PR adds two new rule actions to allow sending generic OpenWebNet messages from Rules.
The new actions are:
- `Boolean sendMessage(String message)` returns a `Boolean` = `true` if the `message` (OpenWebNet frame) was successfully sent via the gateway, `false` otherwise.
- `Map<String, Object> sendMessageWithResponse(String message)` same as previous one, but returns a `Map<String, Object>` with following keys:
- `success`: a `Boolean` = `true` if the `message` was sent successfully
- `responseMessages`: a `List<String>` object containing all returned frames as response to command sent
`openwebnet4j` library has been updated to 0.14.0 to allow using `DefaultMessage` to send messages not yet supported by the binding.
Fixes #10431.

[openwebnet] add sendMessage rule actions to send generic OWN messages on the BUS

---

bundles/org.openhab.binding.tado/pom.xml

* swagger-codegen-maven-plugin, 2.3.1 to 2.4.41
This is a follow-up on #16683, as it affects only a single binding.

[tado] Update plugins

---

bundles/org.openhab.persistence.dynamodb/README.md
bundles/org.openhab.persistence.dynamodb/src/main/java/org/openhab/persistence/dynamodb/internal/DynamoDBQueryUtils.java

We optimize consumed read capacity by limiting the queries to read at most page size entries per underlying dynamodb request. (Multiple requests might be necessary to fill page full of data)
This should significantly reduce the consumed read capacity in cases where the persistence service is queried with page size, as the default before was to read up to 1MB of data. For example, with historicState, the page size is set to 1, and only the first page is of interest.

[dynamodb] Optimize consumed read capacity

---

bundles/org.openhab.binding.hue/src/test/java/org/openhab/binding/hue/internal/handler/HueLightHandlerTest.java

Requires https://github.com/openhab/openhab-core/pull/4124
In https://github.com/openhab/openhab-core/pull/4124 we introduced some improvements in the precision of the HSB to XY color conversions. Which means that the conversions produce slightly different (more accurate) coordinates. The JUnit tests for the Hue binding depended on seeing the prior less precise coordinates. This PR modifies the JUnit tests to use the new expected XY coordinates.
**Nota Bene**: for this reason -- therefore -- this PR will FAIL the CI build until https://github.com/openhab/openhab-core/pull/4124 will have been merged!

[hue] Fix JUnit tests for revised ColorUtil

---

bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/TextValue.java

Since #16307, everything except TextValue would treat an empty string as NULL. TextValue was excluded because empty string could be a valid value. Instead it had a config option added to match for a NULL value if you wanted. BUT, if a TextValue has specific valid states configured (such as from Homie or Home Assistant bindings), then empty string is no longer a valid value, and should receive the same treatment of setting the state to NULL when encountered.

[mqtt] Treat incoming empty string as NULL for enum

---

bundles/org.openhab.binding.airq/src/main/java/org/openhab/binding/airq/internal/AirqEmptyResonseException.java
bundles/org.openhab.binding.airq/src/main/java/org/openhab/binding/airq/internal/AirqException.java
bundles/org.openhab.binding.airq/src/main/java/org/openhab/binding/airq/internal/AirqHandler.java
bundles/org.openhab.binding.airq/src/main/java/org/openhab/binding/airq/internal/AirqPasswordIncorrectException.java

The current implementation shows "probably wrong pasword" on most errors, but not all of them are related to a wrong password. E.g. a network error or failing of the decryption caused by limited JVM crypto strength, due to US import restrictions 🙈.
Also, some null warnings were fixed, JSON syntax errors are handled, and network operations in `initialize()` were removed.
And when the connection failed, the ThingStatus was flapping between ONLINE and OFFLINE, although a connection has never been established.

[airq] Improve error handling

---

bundles/org.openhab.binding.tradfri/src/test/java/org/openhab/binding/tradfri/internal/TradfriColorTest.java

openhab/openhab-core#4124 changed the implementation of color conversions slightly.
As tradfri has some test checking the values for known colors, those need to be adapted (slightly!).
This currently breaks the CI build.

[tradfri] Adapt tests to ColorUtil changes on core

---

bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/api/rest/APManager.java
bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/WifiStationHandler.java

[freeboxos] Handle null WifiInformation in Access Point Manager

---

bundles/org.openhab.binding.netatmo/README.md
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/HomeStatusModule.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/WebhookEvent.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/CameraCapability.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/channelhelper/CameraChannelHelper.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/utils/ChannelTypeUtils.java

Partially resolves issue #15883 .
Making tests, I identified that:
- When camera is on local network, the default timeout (5s) can be too short (maybe long SD card reading ?) and leads to a null value => time out extended (30s)
- A fallback on VPN camera live picture as been added.
- Identified a race condition that lead to display live picture before localUrl or vpnUrl are set leading to UndefType.NULL in the item.
Enhanced:
- live#picture now handles REFRESH command requests.
- vpnUrl that should never be null.

[netatmo] Fix Live Picture not always available

---

bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/HomeSecurityThingCapability.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/channelhelper/EventCameraChannelHelper.java

An IAE appeared for Doorbell modules : 
```
2024-04-29 17:05:59.269 [ERROR] [core.thing.internal.ThingManagerImpl] - Exception occurred while calling thing handler factory 'org.openhab.binding.netatmo.internal.NetatmoHandlerFactory@7160fe3a': HomeSecurityThingCapability must find an EventChannelHelper, please file a bug report.
java.lang.IllegalArgumentException: HomeSecurityThingCapability must find an EventChannelHelper, please file a bug report.
at org.openhab.binding.netatmo.internal.handler.capability.HomeSecurityThingCapability.lambda$1(HomeSecurityThingCapability.java:47) ~[?:?]
at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
at org.openhab.binding.netatmo.internal.handler.capability.HomeSecurityThingCapability.<init>(HomeSecurityThingCapability.java:47) ~[?:?]
at …
```

[netatmo] Fix error introduced in #16681

---

bundles/org.openhab.binding.denonmarantz/src/main/feature/feature.xml
bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/DenonMarantzBindingConstants.java
bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/discovery/DenonMarantzMDNSDiscoveryParticipant.java
bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/discovery/DenonMarantzUpnpDiscoveryParticipant.java

This contains a few discovery improvements:
- Older Denon receivers can now be discovered through UPnP.
- The false assumption about relation between MAC address and brand name (Denon/Marantz) has been replaced by string matching of the `am` property. This fixes the vendor property being set to Marantz for Denon receivers.
- Label is shortened, i.e. "Denon AVC-X4800H" rather than "Denon AVC-X4800H (Marantz Denon AVC-X4800H)".
The UPnP discovery is now in sync with the suggestion add-on definition (see #16035):
https://github.com/openhab/openhab-addons/blob/229c2b7032e3f686b957df19d79f21700912df67/bundles/org.openhab.binding.denonmarantz/src/main/resources/OH-INF/addon/addon.xml#L12-L20
I have only been able to test this with a very old and very new Denon receiver. If the new assumption …

[denonmarantz] Improve discovery

---

bundles/org.openhab.binding.openweathermap/README.md
bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/config/config.xml
bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/i18n/openweathermap.properties

Closes #16665.
OpenWeatherMap One Call API version will shut down in June 2024, therefore users need to switch to API version 3.0.
This changes the default API version to 3.0 and updates the docs accordingly.

[openweathermap] Prepare for shutdown of One Call API version 2.5

---

bundles/org.openhab.voice.pollytts/src/main/feature/feature.xml

Updates Apache httpcore and httpclient to resolve dependencies.
Resolves #16293

[pollytts] Update Apache httpcore and httpclient

---

bundles/org.openhab.binding.airq/README.md
bundles/org.openhab.binding.airq/src/main/java/org/openhab/binding/airq/internal/AirqHandler.java
bundles/org.openhab.binding.airq/src/main/resources/OH-INF/i18n/airq.properties
bundles/org.openhab.binding.airq/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.airq/src/main/resources/OH-INF/update/update.xml

[airq] Add Hydrogen Sulfide (H₂S)

---

pom.xml

#16683 mentioned:
> maven-javadoc-plugin, 3.2.0 to 3.6.3, see https://github.com/apache/maven-javadoc-plugin/releases
but actually changed version to 3.12.0, causing this build warning:
```
[WARNING] The POM for org.apache.maven.plugins:maven-javadoc-plugin:jar:3.12.0 is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for org.apache.maven.plugins:maven-javadoc-plugin:3.12.0: Plugin org.apache.maven.plugins:maven-javadoc-plugin:3.12.0 or one of its dependencies could not be resolved: org.apache.maven.plugins:maven-javadoc-plugin:jar:3.12.0 was not found in https://openhab.jfrog.io/openhab/libs-snapshot during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of …
```

Fix maven-javadoc-plugin upgrade

---

bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/HueBindingConstants.java
bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/console/HueCommandExtension.java
bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/discovery/Clip2ThingDiscoveryService.java
bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/Clip2BridgeHandler.java

Resolves #16711 
When migrating a system from API v1 to v2, there could under some circumstances, be conflicts preventing a) the creation of new v2 things, and b) the migration thing attributes and linked items from the legacy v1 thing to the respective new v2 thing. This was due to ambiguous thing ids if there happened to be multiple v1 legacy things having identical thing ids and different thing type ids.
This PR resolves that issue by ensuring that:
1. all new v2 things are created with a unique thing id, and 
2. thing attributes, and item channel linkages are copied from the correct v1 legacy thing

[hue] Fix migration of API v1 legacy data to new v2 things

---

bundles/org.openhab.binding.energidataservice/README.md
bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/EnergiDataServiceBindingConstants.java
bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/handler/EnergiDataServiceHandler.java
bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/i18n/energidataservice.properties
bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/thing/channel-groups.xml
bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/thing/channel-types.xml
bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/thing/thing-service.xml
bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/update/instructions.xml

This introduces a new trigger channel allowing rules to know when day-ahead prices are available.
See https://community.openhab.org/t/bringing-electricity-information-from-eloverblik-dk-and-energidataservice-dk-into-openhab/143470/100

[energidataservice] Introduce a trigger channel to announce the availability of day-ahead prices

---

bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/JablotronBindingConstants.java
bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/handler/JablotronBridgeHandler.java

The current Jablotron API v1.6 is no longer working. I updated the binding to the currrent API v2.2
I am not sure if you are planning a bugfix release for the 4.1.x branch, but this is definitely a hot candidate.
here is the issue:
https://github.com/openhab/openhab-addons/issues/16740
here is the discussion:
https://community.openhab.org/t/jablotron-alarm-binding-for-openhab/41930/209

[jablotron] Migrate to v2.2 API

---

bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/ReolinkHandler.java

Updated whiteLED channel for reolink ipcamera so that when the light is turned on, it will stay on forever and if the light is turned off, it will stay off forever. This is achieved by setting the floodlight mode to "Always On at Night" when the floodlight is turned on and to Off when the floodlight is turned off. Prior to this change, the mode would be set to Auto when turning the floodlight off and to Off when setting the floodlight ON and then back to Auto if you change the brightness via the dimmer.
This was tested and confirmed on a Reolink Duo Floodlight POE camera and is working well for me. I believe this setting would be more ideal for most users but I could be wrong. I just thought it was odd that the floodlight wouldn't stay on longer than 3 minutes after the brightness was set …

[ipcamera] Fix Reolink Duo Floodlight whiteLED Channel

---

bundles/org.openhab.binding.volumio/src/main/resources/OH-INF/addon/addon.xml

Related to #14885 and #14525 
```shell
$ grep -RL "<connection>" --include addon.xml | sed 's/^bundles\/org\.openhab\.\(.*\)\/src\(.*\)/- \1/' | sort
- binding.volumio
```

[volumio] Declare connection

---

bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiClient.java

Improvement: This patch enables reading the analog input of a Shelly Plus Add-on as a percentage value when it's attached to a host Shelly device. The analogue input will show up as an external sensor channel on the Shelly Thing.
Signed-off-by: Fabian Fagerholm <fabbe@paniq.net>

[shelly] Enable use of analog input with Shelly Plus Add-on

---

bundles/org.openhab.binding.denonmarantz/README.md
bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/DenonMarantzState.java
bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/connector/DenonMarantzConnector.java
bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/xml/adapters/VolumeAdapter.java
bundles/org.openhab.binding.denonmarantz/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.denonmarantz/src/main/resources/OH-INF/update/instructions.xml

`VolumeDB` channels for all zones are now `Number:Dimensionless` with unit hint **dB**.

[denonmarantz] Add UoM support for volume dB channels

---

CODEOWNERS

Gracefully ending maintenace of icalendar. See the linked issue #16764 for details.

[icalendar] Ending maintenance

---

bundles/org.openhab.voice.pipertts/README.md
bundles/org.openhab.voice.pipertts/pom.xml
bundles/org.openhab.voice.pipertts/src/main/java/org/openhab/voice/pipertts/internal/PiperTTSService.java

I made these changes to reduce the size as discussed on https://github.com/openhab/openhab-distro/issues/1643 
The add-on now downloads the dependency jar from maven and unpack the required files from it, or it can be provided manually to workaround offline installations.

[PiperTTS] Reduce bundle size

---

bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaBridgeHandler.java

This PR improves the functionality of the LAN mode.
When the first direct call over the lan fails, it forces the gateway discovery. This comes useful in several scenarios
- either the user misconfigured the IP address or the IP address of the gateway changes.
thanks.

[somfytahoma] force the gateway discovery if the LAN mode is not working

---

bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/ChannelState.java
bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/NumberValue.java

See https://github.com/openhab/openhab-core/pull/4169#issuecomment-2118869442
Some MQTT tests with QuantityTypes fail after https://github.com/openhab/openhab-core/pull/4169 because the MQTT binding assumes a format pattern of %s to drop the unit of the Number with Dimension. As this was changed in core, this PR introduces some logic in the MQTT binding to account for this.
All failing tests have run again and pass.
Also, default formatting for Number types was not in line with the documentation. It used %s, while the documentation states it should be %f, dropping all decimals (and the unit). It now is for Number types.

[MQTT] Fix tests after core change

---

bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/FoscamHandler.java
bundles/org.openhab.binding.ipcamera/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.ipcamera/src/main/resources/OH-INF/update/instructions.xml

Adds support for some new object detection features on Foscam cameras that have these abilities supported. A a user reported and has already tested (what can be tested) on their camera here on the forum:
https://community.openhab.org/t/ipcamera-binding-and-motion-detect-does-not-work-as-expected/155697/11

[ipcamera] Add new AI object detection alarms for Foscam cameras

---

bundles/org.openhab.binding.pjlinkdevice/src/main/java/org/openhab/binding/pjlinkdevice/internal/PJLinkDeviceBindingConstants.java
bundles/org.openhab.binding.pjlinkdevice/src/main/java/org/openhab/binding/pjlinkdevice/internal/PJLinkDeviceHandler.java
bundles/org.openhab.binding.pjlinkdevice/src/main/java/org/openhab/binding/pjlinkdevice/internal/device/command/mute/MuteQueryResponse.java
bundles/org.openhab.binding.pjlinkdevice/src/main/resources/OH-INF/i18n/pjLinkDevice.properties
bundles/org.openhab.binding.pjlinkdevice/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.pjlinkdevice/src/main/resources/OH-INF/update/instructions.xml

As requested on the [community](https://community.openhab.org/t/new-pjlink-binding-for-controlling-multiple-projector-brands-models/56608/58).

[PJLinkDevice] audio/video mute

---

bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/ChannelStateTransformation.java

To help identify which transformation caused the problem
https://community.openhab.org/t/which-channel-executing-the-jsonpath-transformation-failed-an-error-occurred-while-transforming-json-expression/156126

[mqtt] Add additional details in ChannelStateTransformation logging

---

CODEOWNERS
bom/openhab-addons/pom.xml
bundles/org.openhab.binding.frenchgovtenergydata/NOTICE
bundles/org.openhab.binding.frenchgovtenergydata/README.md
bundles/org.openhab.binding.frenchgovtenergydata/pom.xml
bundles/org.openhab.binding.frenchgovtenergydata/src/main/feature/feature.xml
bundles/org.openhab.binding.frenchgovtenergydata/src/main/java/org/openhab/binding/frenchgovtenergydata/internal/FrenchGovtEnergyDataBindingConstants.java
bundles/org.openhab.binding.frenchgovtenergydata/src/main/java/org/openhab/binding/frenchgovtenergydata/internal/FrenchGovtEnergyDataHandlerFactory.java
bundles/org.openhab.binding.frenchgovtenergydata/src/main/java/org/openhab/binding/frenchgovtenergydata/internal/dto/BaseTariff.java
bundles/org.openhab.binding.frenchgovtenergydata/src/main/java/org/openhab/binding/frenchgovtenergydata/internal/dto/HpHcTariff.java
bundles/org.openhab.binding.frenchgovtenergydata/src/main/java/org/openhab/binding/frenchgovtenergydata/internal/dto/Tariff.java
bundles/org.openhab.binding.frenchgovtenergydata/src/main/java/org/openhab/binding/frenchgovtenergydata/internal/handler/BaseTariffHandler.java
bundles/org.openhab.binding.frenchgovtenergydata/src/main/java/org/openhab/binding/frenchgovtenergydata/internal/handler/HpHcTariffHandler.java
bundles/org.openhab.binding.frenchgovtenergydata/src/main/java/org/openhab/binding/frenchgovtenergydata/internal/handler/TariffHandler.java
bundles/org.openhab.binding.frenchgovtenergydata/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.frenchgovtenergydata/src/main/resources/OH-INF/i18n/frenchgovtenergydata.properties
bundles/org.openhab.binding.frenchgovtenergydata/src/main/resources/OH-INF/thing/thing-types.xml
bundles/pom.xml

This new binding provides electrical energy prices for the french historical provider EDF.

[French Govt Energy Data] New binding

---

bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/service/MainTVServerService.java

This PR fixes #16783
additional testing preferred

[samsungtv] Fix `IllegalStateException` on sourceName command

---

bundles/org.openhab.binding.freeboxos/pom.xml
bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/FreeboxOsIconProvider.java
bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/i18n/freeboxos.properties

Currently the FreeboxOsIconProvider tries to provide icons for every icon requests. This should be restricted to `freeboxos:iconname`
Updated ipaddress dependency because previous version was marked with one known vulnerability.

[freeboxos] FreeboxOsIconProvider should only provide icons for its own icon set

---

bundles/org.openhab.binding.denonmarantz/src/main/resources/OH-INF/i18n/denonmarantz.properties
bundles/org.openhab.binding.denonmarantz/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.denonmarantz/src/main/resources/OH-INF/update/instructions.xml

Refactored to use system channel types in order to provide icons and semantic tags (and in some cases also localized labels).

[denonmarantz] Provide channels icons and semantic tags

---

bundles/org.openhab.binding.denonmarantz/README.md
bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/connector/http/DenonMarantzHttpConnector.java
bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/exception/HttpCommunicationException.java
bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/handler/DenonMarantzHandler.java
bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/xml/dto/commands/CommandRx.java

The API call for fetching main zone is now auto-detected. Newer receivers will return HTTP status 403 for the legacy API calls, in which case an alternative API call is now used.
Notes:
- Surround mode is different between Telnet and HTTP `AppCommand.xml` **GetSurroundModeStatus** - e.g. "DOLBY AUDIO-DSUR" vs. "Dolby Audio - Dolby Surround". I don't know what `formMainZone_MainZoneXmlStatus.xml` returns for older models.
- Information equivalent to `formMainZone_MainZoneXml.xml` is missing. This is used to update channel `general#power`. It seems the logic (for my receiver) is that if any zones are on, this is on, otherwise off. The same logic could be achived from a `Group:Switch:OR(ON,OFF)` item, but since this channel is updated directly from the receiver, we should not try to …

[denonmarantz] Add HTTP protocol support for newer receivers

---

bundles/org.openhab.binding.androidtv/pom.xml

Supercedes #16712
Supercedes #16766
Should fix all of these:
https://github.com/openhab/openhab-addons/security/dependabot
Related to:
- openhab/openhab-core#4181
- openhab/openhab-core#4230
Core is currently on bcpkix-jdk18on 1.77 and was on 1.76 before openhab/openhab-core#4181, so it seems the binding doesn't have to be aligned.

[androidtv] Upgrade Bouncy Castle to 1.78

---

bundles/org.openhab.binding.solarforecast/README.md

As can be seen in [ForecastSolarPlaneConfiguration.java](https://github.com/openhab/openhab-addons/blob/4.2.0.M3/bundles/org.openhab.binding.solarforecast/src/main/java/org/openhab/binding/solarforecast/internal/forecastsolar/config/ForecastSolarPlaneConfiguration.java#L29) there are default values of 0.25 for `dampAM` and `dampPM`. But the documentation states "N/A" which is not correct.
**Edit:** Updated link. The previous one was for a different ticket. Now the link points to the correct code.

[solarforecast] Fix ForecastSolar Plane default values in documentation.

---

CODEOWNERS

Add codeowner contact as requested by @jlaur in https://github.com/openhab/openhab-addons/pull/16814#issuecomment-2134072301
Needed for https://github.com/openhab/openhab-addons/pull/13308

[solarforecast] adding codeowner

---

bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyApiInterface.java
bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api1/Shelly1HttpApi.java
bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiRpc.java
bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/discovery/ShellyThingCreator.java
bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyBaseHandler.java
bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyComponents.java
bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyRelayHandler.java
bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/provider/ShellyChannelDefinitions.java
bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/config/config2.xml
bundles/org.openhab.binding.shelly/src/main/resources/scripts/oh-blu-scanner.js

This PR includes various small fixes (1 liners)
Closing
#16736
#16734
#16542
#16709
#16655
#16724

[shelly] Various small fixes for BLU HT, Range Extender, Plus 10V, TRV set temp

---

bundles/org.openhab.persistence.jpa/pom.xml
bundles/org.openhab.persistence.jpa/src/main/java/org/openhab/persistence/jpa/internal/JpaPersistenceService.java
bundles/org.openhab.persistence.jpa/src/main/java/org/openhab/persistence/jpa/internal/model/JpaPersistentItem.java

This updates all base libraries of persistence.java. Goal is to support compiling and running with Java 21 (currently we compile this directory with target release Java 17).
- Upgrade openjpa from 3.2.2 to 4.0.0
- Upgrade derby from 10.14.2.0 to 10.16.1.1 (last Java 17 release)
- Migrate javax.el to jakarta.el-api 6.0.0-RC1
- Revert workaround for Java 21, #16612
Note that Derby 10.16.x.x is the last release built for Java 17. It is still affected by [CVE-2022-46337](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-46337). Using version 10.17.x.x which contains a fix is not yet possible until we drop Java 17 support. Derby project did not release fixed version compiled for Java 17.
As I do not use this binding, I need help testing this version. Unfortunately, the binding does not …

[persistence.jpa] Upgrade openjpa and derby

---

bundles/org.openhab.binding.systeminfo/pom.xml
bundles/org.openhab.binding.systeminfo/src/main/feature/feature.xml
itests/org.openhab.binding.systeminfo.tests/pom.xml

Bump OSHI dependency version to 6.5.0
Release notes: https://github.com/oshi/oshi/blob/master/CHANGELOG.md
Especially https://github.com/oshi/oshi/pull/2538
Signed-off-by: Alexander Falkenstern [alexander.falkenstern@gmail.com](mailto:alexander.falkenstern@gmail.com)

[systeminfo] Bump OSHI to 6.5.0

---

bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/api/TapoCloudConnector.java
bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/api/protocol/aes/SecurePassthrough.java
bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/api/protocol/klap/KlapProtocol.java
bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/api/protocol/passthrough/PassthroughProtocol.java
bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/dto/TapoRequest.java

Bugfix: 
Fixed cloud connection error.
- Http-Header: Content-Type was sent twice and this caused a 405 error on cloud response
- Request did sent empty "params" object wich will cause an error in cloud. So "params" must be null that gson will not serialize it.

[tapocontrol] bugfix cloud connection error

---

bundles/org.openhab.binding.hdpowerview/src/main/resources/OH-INF/addon/addon.xml

The HDPowerview Hub can be discovered via SDDP. This PR adds support for that.
Depends on https://github.com/openhab/openhab-core/pull/4237

[hdpowerview] Support SDDP addon suggestion finder

---

bundles/org.openhab.binding.epsonprojector/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.sonyprojector/src/main/resources/OH-INF/addon/addon.xml

Add SSDP addon finder methods for epsonprojector and sonyprojector bindings
Depends on https://github.com/openhab/openhab-core/pull/4237

[epsonprojector] Support SDDP addon suggestion finder

---

bundles/org.openhab.binding.systeminfo/pom.xml
bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/SystemInfoBindingConstants.java
bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/SystemInfoHandlerFactory.java
bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/SystemInfoThingTypeProvider.java
bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/discovery/SystemInfoDiscoveryService.java
bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/handler/SystemInfoHandler.java
bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/model/OSHISystemInfo.java
bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/model/SystemInfoInterface.java
itests/org.openhab.binding.systeminfo.tests/pom.xml
itests/org.openhab.binding.systeminfo.tests/src/main/java/org/openhab/binding/systeminfo/test/SystemInfoOSGiTest.java

Just reflect naming conventions as described in https://www.openhab.org/docs/developer/guidelines.html
Signed-off-by: Alexander Falkenstern [alexander.falkenstern@gmail.com](mailto:alexander.falkenstern@gmail.com)

[systeminfo] Rename Systeminfo* to SystemInfo*

---

bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcPersistenceService.java

Fixes #16844
Regression of #15869
Related to openhab/openhab-core#4267

[jdbc] Fix state and timestamp being discarded on `store` with alias

---

bundles/org.openhab.binding.govee/README.md

Small update on the docs
- remove device type
- mark H6072 as confirmed

[govee] docs: remove device type

---

bundles/org.openhab.binding.hdpowerview/src/main/feature/feature.xml
bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/discovery/HDPowerViewHubDiscoveryParticipantSddp.java
bundles/org.openhab.binding.hdpowerview/src/main/resources/OH-INF/addon/addon.xml

Makes the following improvements:
- Extend SDDP addon discovery to include Gen 3 gateways
- Add thing discovery via SDDP for both Gen1/2 hubs and Gen 3 gateways

[hdpowerview] Improvements to SDDP discovery

---

bundles/org.openhab.binding.solarforecast/src/main/java/org/openhab/binding/solarforecast/internal/SolarForecastHandlerFactory.java
bundles/org.openhab.binding.solarforecast/src/main/java/org/openhab/binding/solarforecast/internal/forecastsolar/handler/ForecastSolarBridgeHandler.java
bundles/org.openhab.binding.solarforecast/src/main/java/org/openhab/binding/solarforecast/internal/forecastsolar/handler/ForecastSolarPlaneHandler.java
bundles/org.openhab.binding.solarforecast/src/main/java/org/openhab/binding/solarforecast/internal/utils/Utils.java
bundles/org.openhab.binding.solarforecast/src/main/resources/OH-INF/i18n/solarforecast.properties
bundles/org.openhab.binding.solarforecast/src/test/java/org/openhab/binding/solarforecast/CallbackMock.java
bundles/org.openhab.binding.solarforecast/src/test/java/org/openhab/binding/solarforecast/ForecastSolarTest.java

Fixes #16811
After receiving [http status 429 for forecast.solar API](https://doc.forecast.solar/facing429) special treatment is necessary. All API calls for `sf-site` needs to stop for at least 1 hour to recover the `OFFLINE` situation.
Treatment for Clock added in order to perform valid unit tests.

[solarforecast] wait 1 hour after http 429 error

---

bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/handler/ICloudDeviceHandler.java

Use device.Id instead of device.DiscoveryId to fix playsound
Should fix #15333

[icloud] Use device.Id instead of device.DiscoveryId to fix playsound

---

bundles/org.openhab.binding.boschshc/pom.xml

This relates to the following issue and security alerts:
* https://github.com/openhab/openhab-addons/issues/16459
* https://github.com/openhab/openhab-addons/security/dependabot/81
* https://github.com/openhab/openhab-addons/security/dependabot/82
* https://github.com/openhab/openhab-addons/security/dependabot/83
The binding should not be affected by
https://github.com/openhab/openhab-addons/issues/16459. No detailed analysis was done for the remaining alerts, but the bumped version is not vulnerable anymore in any case.

[boschshc] Bump Bouncy Castle Dependencies to 1.78.1

---

bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/DateTimeValue.java
bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/NumberValue.java
bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/PercentageValue.java
bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/values/ValueTests.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/SensorTests.java

The dynamic stateDescription created by the MQTT binding always uses `%s` for all of its types.
The consequence of this is that for a Number QuantityType, the full state including the unit will be returned. When retrieving the state description from the Number:Dimension item linked to that channel, another unit will be added, effectively showing the unit label twice.
See https://community.openhab.org/t/doubled-unit-output/156591 for more details about the problem.
This PR makes sure proper state descriptions, complying to the default, are returned.
At the same time, the MQTT binding currently always returns a `QuantityType<Dimensionless>` with `Unit.ONE` for channels where the unit is not set. This has been changed here to return `DecimalType` instead. Without it, the state description …

[MQTT] Fix state description

---

CODEOWNERS
bom/openhab-addons/pom.xml
bundles/org.openhab.binding.mffan/NOTICE
bundles/org.openhab.binding.mffan/README.md
bundles/org.openhab.binding.mffan/pom.xml
bundles/org.openhab.binding.mffan/src/main/feature/feature.xml
bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/MfFanBindingConstants.java
bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/MfFanConfiguration.java
bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/MfFanHandlerFactory.java
bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/api/FanRestApi.java
bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/api/RestApiException.java
bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/api/ShadowBufferDto.java
bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/handler/MfFanHandler.java
bundles/org.openhab.binding.mffan/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.mffan/src/main/resources/OH-INF/i18n/mffan.properties
bundles/org.openhab.binding.mffan/src/main/resources/OH-INF/thing/mffan.xml
bundles/pom.xml

I've developed a new binding for "Modern Forms" and "WAC Lighting" ceiling fans.  The binding implements communications , and control of these WIFI connected, smart fans.

[mffan] Initial contribution

---

bundles/org.openhab.binding.pegelonline/src/test/java/org/openhab/binding/pegelonline/internal/handler/PegelTest.java

Fix race condition which can occur during unit testing. 
`ThingStatus` can be `UNKNOWN` or `ONLINE` after initialize call, all other stati shall fail.
https://github.com/openhab/openhab-addons/pull/16831#issuecomment-2174157015

[pegelonline] fix junit status race condition

---

bundles/org.openhab.automation.jsscripting/pom.xml

Fixes a problem, where persisting TimeSeries failed when injection caching was enabled.

[jsscripting] Upgrade openhab-js to 5.1.1

---

bundles/org.openhab.binding.emotiva/src/main/resources/OH-INF/addon/addon.xml

This PR removes discovery-methods declartion in the emotiva binding. The declariton was missing fields, and upon further invesrtigation, the scanBroadcast in IpAddonFinder.java does not support separate destination and listen ports, meaning a discovery via the IpAddonFinder will not work.

[emotiva] Remove discovery-methods because of missing listen port support in scanBroadcast

---

bundles/org.openhab.binding.nibeheatpump/contrib/NibeGW/RasPi/nibegw.c

Nibegw wasn't working on my rpi zero 2W + waveshare RS485 CAN Hat due to missing serial parameters.
Signed-off-by: Joren Claus <joren.claus@gmail.com>

[nibeheatpump] Fix serial params

---

bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/connection/HueBridge.java

[hue] API v1: retry once on timeout for GET requests to the bridge

---

bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/channels.xml

For consistency with corresponding system channel types referenced by non-advanced channel variants:
https://github.com/openhab/openhab-core/blob/2aacdcd4e8a6f2dcc5dca83a28267cd0e44f6cd6/bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/DefaultSystemChannelTypeProvider.java#L212-L228
https://github.com/openhab/openhab-core/blob/2aacdcd4e8a6f2dcc5dca83a28267cd0e44f6cd6/bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/DefaultSystemChannelTypeProvider.java#L185-L191

[hue] Add semantic tags for advanced light channels (API v2)

---

bundles/org.openhab.binding.jellyfin/pom.xml

SDK 1.4.6 is not compatible with the most recent Jellyfin Server versions (10.9.x). This update adds compatibility for Jellyfin [10.9.x](https://github.com/jellyfin/jellyfin/tags).
➡️ resolves #16903 
---
- [Jellyfin SDK 1.4.7 Release](https://github.com/jellyfin/jellyfin-sdk-kotlin/releases/tag/v1.4.7)
- [Jellyfin SDK PR 895](https://github.com/jellyfin/jellyfin-sdk-kotlin/pull/896)
- [Jellyfin Android TV Issue 3467](https://github.com/jellyfin/jellyfin-androidtv/issues/3467)

[jellyfin] Add support for 10.9.x Jellyfin Servers

---

bundles/org.openhab.automation.jsscripting/pom.xml

Second attempt to fix a problem, where persisting TimeSeries failed when injection caching was enabled.

[jsscripting] Upgrade openhab-js to 5.1.2

---

bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/AwattarBestPriceResult.java
bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/AwattarBestpriceConfiguration.java
bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/AwattarBindingConstants.java
bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/AwattarBridgeConfiguration.java
bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/AwattarConsecutiveBestPriceResult.java
bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/AwattarNonConsecutiveBestPriceResult.java
bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/AwattarPrice.java
bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/AwattarUtil.java
bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/handler/AwattarBestpriceHandler.java
bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/handler/AwattarBridgeHandler.java
bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/handler/AwattarHandlerFactory.java
bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/handler/AwattarPriceHandler.java
bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/handler/TimeRange.java
bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/handler/Timerange.java
bundles/org.openhab.binding.awattar/src/test/java/org/openhab/binding/awattar/internal/handler/AwattarBridgeHandlerTest.java
bundles/org.openhab.binding.awattar/src/test/resources/org/openhab/binding/awattar/internal/handler/api_response.json

This adds some tests for the bridge and bestprice thing. This is the first part of additions to this binding. I'll add support for `TimeSeries` later.
@Wolfgang1966 Do you think that the new channels for sending the `TimeSeries` (a set of data for a given time range that is persisted for an item and later automatically restored by the framework to always reflect the current value) should be added to the bridge or the prices thing? Since it only adds four channels I would prefer to add it to the bridge, so users that don't need any specials (like hourly channels or best price ranges) only need the bridge and no other things.

[awattar] Add tests and improve code

---

bundles/org.openhab.binding.smaenergymeter/README.md
bundles/org.openhab.binding.smaenergymeter/src/main/java/org/openhab/binding/smaenergymeter/internal/discovery/SMAEnergyMeterDiscoveryService.java
bundles/org.openhab.binding.smaenergymeter/src/main/java/org/openhab/binding/smaenergymeter/internal/handler/SMAEnergyMeterHandler.java
bundles/org.openhab.binding.smaenergymeter/src/main/java/org/openhab/binding/smaenergymeter/internal/packet/DefaultPacketListenerRegistry.java
bundles/org.openhab.binding.smaenergymeter/src/main/java/org/openhab/binding/smaenergymeter/internal/packet/FilteringPayloadHandler.java
bundles/org.openhab.binding.smaenergymeter/src/main/java/org/openhab/binding/smaenergymeter/internal/packet/PacketListener.java
bundles/org.openhab.binding.smaenergymeter/src/main/java/org/openhab/binding/smaenergymeter/internal/packet/ThrottlingPayloadHandler.java

Fix SMA energy meter delays unintentionally introduced by #11718 reported in #16789.
This PR changes a bit internal logic of binding. It pulls up control over update interval and filtering of packets to caller of packet listener.
Anyone with SMA Energy Meter is welcome to test updates, especially these who have more than one device in their network!

[smaenergymeter] Make sure that energy meter packets are not queued up.

---

bundles/org.openhab.io.openhabcloud/README.md

Refs #16938.
This adds the NotificationAction docs to the openHAB Cloud Connector add-on, my plan is to link the action docs to this new docs. Documentation close to code is always a good thing.

[openhabcloud] Update README for new notification features

---

bundles/org.openhab.persistence.inmemory/README.md
bundles/org.openhab.persistence.inmemory/src/main/java/org/openhab/persistence/inmemory/internal/InMemoryPersistenceService.java

The in memory persistence is especially relevant for forecasts or future value calculations.
To make it easy to configure, I propose a default strategy of Forecast. Any item with time series data will then get persisted in memory.
Memory impact is expected to be limited, as typically there are few items with time series. The most likely ones are for weather forecasts and solar predication calculated values.
See discussion: https://community.openhab.org/t/solar-forecast-pv/137681/157?u=mherwege
This would also make it possible to add it as a proposed persistence extension to the setup wizard, without further configuration required. See https://github.com/openhab/openhab-webui/pull/2431

[inmemory] Default persistence strategy Forecast

---

bundles/org.openhab.binding.bosesoundtouch/src/main/java/org/openhab/binding/bosesoundtouch/internal/XMLResponseHandler.java
bundles/org.openhab.binding.bosesoundtouch/src/main/java/org/openhab/binding/bosesoundtouch/internal/XMLResponseProcessor.java
bundles/org.openhab.binding.bosesoundtouch/src/test/java/org/openhab/binding/bosesoundtouch/internal/XMLResponseProcessorTest.java
bundles/org.openhab.binding.bosesoundtouch/src/test/resources/NowPlayingUpdate.xml

XML text content was not processed correctly in case the value contained XML entities. In this case multiple updates were fired, resulting in incomplete text chunks in the associated items.
The solution was to create a string builder aggregating all content, which is delivered by the SAX parser by means of multiple characters() callbacks. The state updates are now fired in endElement() instead of characters(), after the complete content was appended to the string builder.
Further fixes/improvements:
* add missing genre status to state machine
* extract local variable for string in characters()
* add unit tests
closes #16896

[bosesoundtouch] Fix parsing of metadata fields

---

itests/org.openhab.binding.max.tests/itest.bndrun

Follow up to https://github.com/openhab/openhab-addons/pull/14413#issuecomment-2187373577

[max] Remove org.apache.commons from itest bnd.run

---

bundles/org.openhab.binding.energidataservice/README.md

This PR:
- Adds language tab for DSL examples, so it's clear that these examples are DSL (and prepare for other languages).
- Fixes code fences for DSL (javascript → java).

[energidataservice] Add language tab for Rule DSL examples

---

bundles/org.openhab.binding.energidataservice/README.md

Earlier work on the example inspired a minor improvement in the JRuby helper library. This [PR](https://github.com/openhab/openhab-jruby/pull/288) simplified how PersistedState objects are used in additions, so it is no longer necessary to call `.state`.

[energidataservice] Update JRuby example

---

bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/sdcp/SonyProjectorSdcpConnector.java

Decodes mac address as byte values rather than characters
Relates to the problem described in [#16964](https://github.com/openhab/openhab-addons/issues/16964#issuecomment-2199652869)

[sonyprojector] Fix decoding of mac address

---

bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/sdcp/SonyProjectorSdcpConnector.java

In PR #16972 we fixed the decoding of mac addresses, but in the edge case that the mac byte value is less than 16, the fix fails because Integer.toHexString() does not produce leading zeros (i.e. the mac address appears wrongly as `12-34-5-67-89-0` instead of `12-34-05-67-89-00`)

[sonyprojector] Fix edge case in mac address decoding

---

bundles/org.openhab.persistence.jpa/src/main/java/org/openhab/persistence/jpa/internal/JpaHistoricItem.java

For `Number` items with dimension a `QuantityType` should be returned (instead of a `DecimalType`. Related to https://github.com/openhab/openhab-core/pull/4257.

[jpa] Fix return value for UoM items

---

bundles/org.openhab.binding.verisure/src/main/java/org/openhab/binding/verisure/internal/VerisureSession.java

Fix the logging statement typo
Hi,
We found a typo in the logging messages.
It's an incremental commit but it can improve the quality of logging messages.

[verisure] Fix logging statement

---

bundles/org.openhab.binding.growatt/src/main/java/org/openhab/binding/growatt/internal/action/GrowattActions.java

The ThingActions implementation must be annotated as a Component

[growatt] Annotate ThingActions implementation as a Component

---

pom.xml

This may help with fixing or diagnosing read timouts during deployment.

Upgrade maven-deploy-plugin to 3.1.2

---

bundles/org.openhab.io.openhabcloud/README.md

The JRuby library was updated (https://github.com/openhab/openhab-jruby/pull/297) to support the new referenceId parameter, and also refactored for more consistency with other action classes. The previous `notify` method is still kept for backwards compatibility.
@florian-h05 I also noticed some changes that I think may be needed for the JS example. Would you mind checking it please?

[openhabcloud] Update JRuby examples and minor changes to JS examples

---

bundles/org.openhab.binding.meater/src/main/java/org/openhab/binding/meater/internal/api/MeaterRestAPI.java
bundles/org.openhab.binding.meater/src/main/java/org/openhab/binding/meater/internal/handler/MeaterBridgeHandler.java

The binding is currently broken because the cloud service started to reject HTTP GET requests having a `Content-Type` header but no content.
Tested when creating a cook for first probe:
(the other three probes are still offline because of apption-labs/meater-cloud-public-rest-api#7)
```
2024-07-04 23:39:49.953 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'meater:meaterapi:block' changed from UNKNOWN to ONLINE
2024-07-04 23:46:22.314 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Meater_Probe1_InternalTemperature' changed from 97.3 °C to 22.8 °C
2024-07-04 23:46:22.316 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'meater:meaterprobe:block:probe1' changed from OFFLINE (COMMUNICATION_ERROR): MEATER stegetermometer er offline to ONLINE
2024-07-04 23:46:22.317 [INFO …
```

[meater] Fix broken cloud communication

---

bundles/org.openhab.binding.energidataservice/README.md

After latest documentation build I noticed two syntax errors causing wrong rendering:
https://next.openhab.org/addons/bindings/energidataservice/#calculatecheapestperiod-from-power-phases
Also fix a Rule DSL example after changes in [PersistenceExtensions](https://www.openhab.org/javadoc/latest/org/openhab/core/persistence/extensions/persistenceextensions).

[energidataservice] Fix JRuby tabs

---

bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyBaseHandler.java

Fixes Gen1 initialization when thing is defined in .things (discovered and added thing via UI worked fine, Gen2+3 also)
See also #17006

[shelly] Fixes Gen1 initialization when thing is defined in .things

---

bundles/org.openhab.automation.jrubyscripting/pom.xml

Build the addon with JRuby 9.4.8.0 release.
Ruby Compatibility
- Fixed a bug in the bytecode JIT causing patterns to execute incorrect branches. [#8283](https://github.com/jruby/jruby/issues/8283), [#8284](https://github.com/jruby/jruby/pull/8284)
Standard Library
- jruby-openssl is updated to 0.15.0, with updated Bouncy Castle libraries to avoid CVEs in older versions.
- uri is updated to 0.12.2, mitigating CVE-2023-36617.
- net-ftp is updated to 0.3.7 with restored functionality on JRuby.
Bug fixes as listed in the announcement: https://www.jruby.org/2024/07/02/jruby-9-4-8-0.html

[jrubyscripting] Upgrade to JRuby 9.4.8.0

---

bundles/org.openhab.binding.shelly/README.md
bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyDeviceProfile.java
bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiRpc.java
bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyBaseHandler.java

This PR replaces #17009 with a more solid solution supporting gen 1/2/3 devices discovered by UI for defined in a .things file

[shelly] Revise fix for Gen1 initialization problem for manually created Things

---

bundles/org.openhab.automation.jsscripting/README.md

The command to install an npm package that was suggested in the documentation would not work, as it was missing the required path. I've added information to explain this is required.

[jsscripting] Add info about npm requiring path

---

bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitCharacteristicFactory.java

There are so many shared characteristics now, and so many accessories they belong to, there is no longer any groupings that make sense. so just sort solely by characteristic/method name.  While the diff is huge, no actual code changes were made. Once this is merged, it will be easier to work on multiple PRs at the same time without conflicting with each other.

[homekit] sort characteristics in HomekitCharacteristicFactory

---

bundles/org.openhab.binding.awattar/README.md
bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/AwattarBestPriceConfiguration.java
bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/handler/AwattarBestPriceHandler.java
bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/handler/AwattarHandlerFactory.java
bundles/org.openhab.binding.awattar/src/main/resources/OH-INF/config/config.xml
bundles/org.openhab.binding.awattar/src/main/resources/OH-INF/i18n/awattar.properties
bundles/org.openhab.binding.awattar/src/main/resources/OH-INF/i18n/awattar_de.properties
bundles/org.openhab.binding.awattar/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.awattar/src/test/java/org/openhab/binding/awattar/internal/handler/AwattarBridgeHandlerTest.java

The goal is to add an inverted best price to the aWattar add-on.
If you set the ìnverted` flag via configuration it will return the inverted result of a best price. 
So if you set for example 4h and inverted, the four hours with the highest price will be selected.
Does currently not work with the `consectuive` flag.

[aWattar] Add inverted best price

---

bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/HttpThingHandler.java
bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/Util.java
bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/http/RefreshingUrlCache.java
bundles/org.openhab.binding.http/src/test/java/org/openhab/binding/http/UtilTest.java

Fixes #17039
Reported on the forum: https://community.openhab.org/t/openhab-4-2-release-discussion/157076/35 and in private communication
This also allows pre-escaped characters in the `stateExtension` and `commandExtension` if the automatic escaping is not sufficient.

[http] Properly escape + character in query string

---

bundles/org.openhab.persistence.mongodb/src/test/java/org/openhab/persistence/mongodb/internal/MongoDBPersistenceServiceTest.java

It causes Jenkins CI builds to fail, see #17046

[mongodb] Disable failing MongoDBPersistenceServiceTest

---

bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/D2_50/D2_50.java

Fixes #16974
There is a problem with parsing the data send from fan devices using EEP D2_50 (like Dimplex)
When the value is with leading bite - 1 is converted to a number < 0 and then to unsined int which leads to a very big value for OutdorAirTempareture channel.
Looking at the code I thing this could also happen to other channels so I added a fix for them `& 0xff`

[enocean] Fix temperature values for D2_50 eep

---

bundles/org.openhab.persistence.mongodb/src/test/java/org/openhab/persistence/mongodb/internal/DataCreationHelper.java
bundles/org.openhab.persistence.mongodb/src/test/java/org/openhab/persistence/mongodb/internal/MongoDBPersistenceServiceTest.java

On the former CI Build, the build did exclude the tests using testcontainer, since there was no docker available. Obviously it is now, but the CPU does not support the AVX instruction set. So testcontainer fail.
Needed to change the way, to check whether to run the tests - so checked whether AVX is there...
just run and see whether the build fails on the CI system...

[mongodb] Fixes #17046 CI Build fails on new systems - complaining CPU does not support AVX

---

bundles/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/net/SocketChannelSession.java
bundles/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/pro3/AtlonaPro3Handler.java
bundles/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/pro3/AtlonaPro3PortocolHandler.java

After a power outage my Atlona switch did not get an IP and as a result the binding was spamming the log with reconnect messages every 10 seconds.
This PR changes almost all existing logging calls to use DEBUG instead.

[atlona] Supress unecessary INFO and WARN logging

---

bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java

Reported on the forum
Should be backported.

[rrd4j] Fix unit retrieval for group items

---

bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/handler/DenonMarantzHandler.java

[denonmarantz] Fix blocking initialization

---

bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitCharacteristicFactory.java

use the item's unit if it has one. or allow explicit units

[homekit] Fix temperature unit conversion for min/max/step

---

bundles/org.openhab.binding.govee/src/main/java/org/openhab/binding/govee/internal/CommunicationManager.java
bundles/org.openhab.binding.govee/src/main/java/org/openhab/binding/govee/internal/GoveeHandler.java
bundles/org.openhab.binding.govee/src/main/java/org/openhab/binding/govee/internal/GoveeHandlerFactory.java
bundles/org.openhab.binding.govee/src/test/java/org/openhab/binding/govee/internal/GoveeHandlerMock.java
bundles/org.openhab.binding.govee/src/test/java/org/openhab/binding/govee/internal/GoveeSerializeGoveeHandlerTest.java

- Fixes https://github.com/openhab/openhab-addons/issues/17041
- Improve logging a bit
- Add some basic tests

[govee] Fix invalid status response handling

---

bundles/org.openhab.binding.deconz/src/test/java/org/openhab/binding/deconz/DeconzTest.java

[deconz] Fix tests. Fix #17104

---

bundles/org.openhab.binding.sensibo/src/main/java/org/openhab/binding/sensibo/internal/dto/pods/GetPodsRequest.java
bundles/org.openhab.binding.sensibo/src/main/java/org/openhab/binding/sensibo/internal/handler/SensiboAccountHandler.java
bundles/org.openhab.binding.sensibo/src/test/java/org/openhab/binding/sensibo/internal/handler/SensiboAccountHandlerTest.java
bundles/org.openhab.binding.sensibo/src/test/resources/get_pods_response.json

Utilize Sensibo's field selector to get all data for all pods in one request and avoid request rate limiting
resolves openhab/openhab-addons#17090

[sensibo] Fix potential API throttling at binding start

---

bundles/org.openhab.binding.tesla/README.md

the item channel name is incorrect 
also removed some items which are no longer in thing channel
ideally owner of addon should also review the rest of the documentation
Corrections to Tesla demo items changes to channel names to align with thing definition.
N/A documentation

[tesla] Update README.md correct channel name

---

bundles/org.openhab.binding.bluetooth.bluez/src/main/java/org/openhab/binding/bluetooth/bluez/internal/DeviceManagerFactory.java

Resolves #17035 
Handles UnsatisfiedLinkError on Windows (and macOS).

[bluetooth.bluez] Handle UnsatisfiedLinkError on Windows (and macOS)

---

bundles/org.openhab.binding.bluetooth.bluez/NOTICE
bundles/org.openhab.binding.bluetooth.bluez/src/main/feature/feature.xml
features/openhab-addons/src/main/resources/footer.xml

Multiple declarations of the same dependency. They should be aligned. 
For reference: https://github.com/openhab/openhab-addons/issues/17112#issuecomment-2241556862

[bluetooth.bluez] Sync bluez-dbus-osgi to version 0.1.4

---

bundles/org.openhab.binding.awattar/README.md
bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/handler/AwattarBridgeHandler.java

Shedules the API update more than once per day.

[aWATTar] Schedule API update more then once per day

---

bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/handler/AstroThingHandler.java
itests/org.openhab.binding.astro.tests/src/main/java/org/openhab/binding/astro/handler/test/AstroCommandTest.java

This PR will avoid creation of a new ChannelUID instances to check linked state of the channel.
Signed-off-by: Jörg Sautter <joerg.sautter@gmx.net>

[astro] Use the existing ChannelUID instance to check the linked state

---

bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitThermostatImpl.java

Allow configuring such an accessory, and it's up to the user to be okay with how the Home app deals with it.
Fixes #17131

[homekit] Fix thermostats with auto mode and only target temperature

---

bundles/org.openhab.binding.http/README.md
bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/Util.java
bundles/org.openhab.binding.http/src/test/java/org/openhab/binding/http/UtilTest.java

Related to #12350 
Related to #17039 
@jamesmelville FYI

[http] Improve escaping of URLs

---

bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitCharacteristicFactory.java

This is especially important when linking a many-valued enum (such as CurrentHeatingCoolingState) to a switch, and you want to use a value beyond 0 and 1 (i.e. OFF (0) and COOL (2)).
Fixes #16791

[homekit] Don't pre-fill enums from switches if metadata has enum values

---

bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/AbstractHomekitAccessoryImpl.java

Depending on how the accessory initializes, optional characteristics may be added before or after the service. For IrrigationSystem, it's added before optional characteristics. Because Name is special (it belons on the AccessoryInformationService for the primary service, and on the service itself for others), we need to be careful to not add it to the primary service. It will get moved to the accessory service later if the accessory ends up being a secondary service on a composite accessory.
Fixes #15387

[homekit] Fix duplicate name characteristic errors

---

bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/handler/AwattarBridgeHandler.java
bundles/org.openhab.binding.awattar/src/test/java/org/openhab/binding/awattar/internal/handler/AwattarBridgeHandlerRefreshTest.java

The PR fixes the wrong check of null.
(Edit: as follow-up to https://github.com/openhab/openhab-addons/pull/17068#discussion_r1687719217)
Also the unconditional ONLINE state is remove. This should probably be discussed.
Some tests have been added also as regression checks.

[aWATTar] fix handle wrong null check

---

bundles/org.openhab.automation.jsscripting/src/main/resources/node_modules/@jsscripting-globals.js

Fixes #17165.
Caused by https://github.com/openhab/openhab-core/pull/4289.

[jsscripting] Fix console logger name & timer identifier missing for UI scripts

---

bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/FreeDeviceIntf.java

Also update the firmware property when the player is reachable for the first time.
Do not trigger the event firmware_updated when just first setting the firmware property.

[freeboxos] Fix triggering of event firmware_updated

---

bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyDeviceProfile.java

Extracted from #17166 for being backported to `4.2.x`, see:
- https://github.com/openhab/openhab-addons/pull/17166#discussion_r1694213265
- https://github.com/openhab/openhab-addons/pull/17166#discussion_r1694230920

[shelly] Fix `NullPointerExceptions`

---

bundles/org.openhab.binding.dbquery/pom.xml
bundles/org.openhab.binding.dbquery/src/main/resources/OH-INF/thing/influx2-bridge.xml
bundles/org.openhab.binding.dbquery/src/test/java/org/openhab/binding/dbquery/internal/Value2StateConverterTest.java
bundles/org.openhab.binding.dbquery/src/test/java/org/openhab/binding/dbquery/internal/domain/QueryResultJSONEncoderTest.java

+ Update libraries to newer versions and fix thing staying on UNKNOWN status as reported in closes #17064
+ Changed the default port to 8086 to match the default. See https://github.com/influxdata/telegraf/issues/8080
+ Removed some depreciated code in the tests.
Need users to help test this as now instead of saying UNKNOWN it reports to me that it gets a refused attempt as I have V1.8 database and this binding requires V2.0 as minimum.
http://pcmus.com/openhab/org.openhab.binding.dbquery-4.3.0-SNAPSHOT.zip

[dbquery] Fix dependency issues and bump to newer version libs

---

bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyApiInterface.java
bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api1/Shelly1HttpApi.java
bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiJsonDTO.java
bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiRpc.java
bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/ShellyBluApi.java

The binding's gateway script could not get access to the BLE observer in case the Shelly Cloud Bluetooth Gateway is enabled. Therefore no discovery results will be passed to openHAB.
The binding now checks the device settings and adjust them if nessecary.

[shelly] Fix BLU Discovery when Shelly Cloud Bluetooth Gateway is enabled

---

bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitCharacteristicFactory.java

In #17137, CurrentDoorState and TargetDoorState were moved from being part of the accessory itself, to using the CharacteristicFactory, but they lost the flag that default-inverts them. So make sure to pass that flag in the new location that the mapping is created.

[homekit] Fix invertedness of GarageDoorOpener characteristics

---

bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/api/rest/AfpManager.java

[freeboxos] Fix enabling/disabling of Mac OS file sharing

---

bundles/org.openhab.io.homekit/README.md
bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/AbstractHomekitAccessoryImpl.java
bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/AbstractHomekitPositionAccessoryImpl.java
bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitAirQualitySensorImpl.java
bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitCarbonDioxideSensorImpl.java
bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitCarbonMonoxideSensorImpl.java
bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitCharacteristicFactory.java
bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitContactSensorImpl.java
bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitFilterMaintenanceImpl.java
bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitHeaterCoolerImpl.java
bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitIrrigationSystemImpl.java
bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitLeakSensorImpl.java
bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitLockImpl.java
bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitOccupancySensorImpl.java
bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitSecuritySystemImpl.java
bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitSlatImpl.java
bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitSmartSpeakerImpl.java
bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitSmokeSensorImpl.java

[homekit] Support multiple values per enum mapping

---

bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/PlayerHandler.java
bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/thing/channel-types.xml

This allows to have as status the last command sent.
Also fix a typo in a log and enhance the check of the remoteCode parameter.

[freeboxos] Remove veto policy on key-code channel

---

bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/handler/SamsungTvHandler.java

As the `Thing` is already set to offline later on, there is no need to also log to warn level that the device is unreachable / timeout for getting the TV Properties. debug is good enough.
Fixes: https://github.com/openhab/openhab-addons/issues/17118

[samsungtv] Adjust logging when TV is off

---

bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/FreeboxOsBindingConstants.java
bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/ActivePlayerHandler.java
bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/ApiConsumerHandler.java
bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/ApiConsumerIntf.java
bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/HostHandler.java
bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/RepeaterHandler.java
bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/RevolutionHandler.java
bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/ServerHandler.java
bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/VmHandler.java
bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/WifiStationHandler.java

Avoids API requests when channels are unlinked.

[freeboxos] Avoid useless API requests (server/player)

---

bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/LongPolling.java
bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/dto/UserDefinedState.java
bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/serialization/BoschServiceDataDeserializer.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/bridge/LongPollingTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/bridge/dto/UserDefinedStateTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/serialization/BoschServiceDataDeserializerTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/services/dto/BoschSHCServiceStateTest.java

* Fix NPE while deserializing service data JSON objects
* Catch exceptions while handling long poll results
* Correct `@type` name for user-defined states
* Add unit tests and enhance existing unit tests
closes #17176
Test JAR can be downloaded [here](http://davidpace.de/openhab/org.openhab.binding.boschshc-4.3.0-SNAPSHOT-longpoll.jar).

[boschshc] Fix NPE during deserialization, make long polling more robust

---

bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/api/rest/MediaReceiverManager.java
bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/api/rest/RestManager.java
bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/ApiConsumerHandler.java

[freeboxos] Fix media playing

---

bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/api/ApiHandler.java
bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/api/PermissionException.java
bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/ApiConsumerHandler.java

[freeboxos] Enhance log warning when handling channel command fails

---

bundles/org.openhab.transform.rollershutterposition/src/main/resources/OH-INF/addon/addon.xml

Reported here:
https://community.openhab.org/t/add-ons-regex-addon-appears-with-wrong-name/157805
Regression of #14559

[rollershutterposition] Fix addon id

---

bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/ServerHandler.java

This will set the related thing properties.
No audio sink will be created for the revolution server as it only supports audio and pushing audio media is not yet supported by the API.

[freeboxos] Get server AirPlay capabilities

---

bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/thing/channel-types.xml

Also make line-type, lcd-orientation and airmedia_status channel types advanced

[freeboxos] Fix category for lcd-brightness channel type

---

itests/itest-common.bndrun

When this JVM variable is not set Jetty creates selectors based on the number of available processors (`Runtime.getRuntime().availableProcessors()`). Jetty will also throw an exception when there is a mismatch between the max thread pool size and the number of selectors. This causes issues with the default thread pool size of 10 on machines with more than 10 available processors.
See also [`SelectorManager.defaultSelectors(Executor)`](https://github.com/jetty/jetty.project/blob/70015831e5195ba74da6383c4ab7c90c56bb08af/jetty-io/src/main/java/org/eclipse/jetty/io/SelectorManager.java#L71-L80).

Fix itests on machines with lots of processors

---

bundles/org.openhab.binding.ecovacs/README.md

Fixed typo for "ecovacs" folder name in README.md instructions. 
[Ecovacs Binding] Fixed typo for ecovacs folder name in documentation
Basic documentation fix where ecovacs was spelled incorrectly.

[ecovacs] Fix typo in ecovacs folder name

---

bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/LongPolling.java
bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/dto/UserDefinedState.java
bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/serialization/BoschServiceDataDeserializer.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/bridge/LongPollingTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/bridge/dto/UserDefinedStateTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/serialization/BoschServiceDataDeserializerTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/services/dto/BoschSHCServiceStateTest.java

* Fix NPE while deserializing service data JSON objects
* Catch exceptions while handling long poll results
* Correct @type name for user-defined states
* Add unit tests and enhance existing unit tests
This was cherry-picked from `main`, but minor merge conflicts had to be resolved.

[boschshc] Fix NPE during deserialization, make long polling more robust (#17190)

---

bundles/org.openhab.transform.map/README.md
bundles/org.openhab.transform.map/src/main/java/org/openhab/transform/map/internal/MapTransformationService.java
bundles/org.openhab.transform.map/src/test/java/org/openhab/transform/map/internal/MapTransformationServiceTest.java

The mapping table can be specified inline by prefixing it with the `|` character.
The "key=value" pairs are separated with a semicolon (`;`) or a newline character.
For example, the following map function translates open/closed to ON/OFF: `|open=ON; closed=OFF`

[map] Support inline map

---

bundles/org.openhab.binding.roku/src/main/java/org/openhab/binding/roku/internal/communication/RokuCommunicator.java

While recently helping to troubleshoot an issue that a community member had with this binding, I realized that currently there is very little logging available besides when exceptions are thrown. Therefore, this PR adds TRACE logging for the http GET and POST requests sent to the Roku device.

[roku] Add device communcation logging

---

bundles/org.openhab.binding.govee/README.md

device confirmed to be working: https://community.openhab.org/t/govee-dreamcoulour-led-strips/84435/70

[govee] Add H61C5 as supported device

---

CODEOWNERS

This was forgotten in #16282 and #16754.

Add J-N-K as code-owner to http and basicprofiles add-ons

---

bundles/org.openhab.transform.rollershutterposition/src/main/resources/OH-INF/config/rollerShutterPosition.xml

This pull request fixes the uri in the .xml config file to match other transform profiles. This addresses the bug #17340 where the parameters cannot be configured via the main ui.

[rollershutterposition] Fix parameter configuration through UI

---

bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/DaikinWebTargets.java
bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/Enums.java
bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/handler/DaikinAcUnitHandler.java
bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/handler/DaikinAirbaseUnitHandler.java
bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/handler/DaikinBaseHandler.java
bundles/org.openhab.binding.daikin/src/main/resources/OH-INF/thing/thing-types.xml

This was requested in https://github.com/openhab/openhab-addons/issues/16479#issuecomment-2249747109
In summary, when sending an API call to change something, the device will return a `ret=OK` if it accepted the values that we've set. Therefore, we should know the updated value already, without having to wait for the next poll. We therefore update the relevant channel immediately.
This helps for when changing something requires immediate feedback, such as increasing/decreasing the set temperature. Previously, the only way to get a smooth user experience is by relying on autoupdate.

[daikin] Update channels immediately after a successful API command

---

bundles/org.openhab.binding.homematic/README.md
bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/handler/HomematicBridgeHandler.java
bundles/org.openhab.binding.homematic/src/test/java/org/openhab/binding/homematic/internal/handler/HomematicBridgeHandlerMock.java
bundles/org.openhab.binding.homematic/src/test/java/org/openhab/binding/homematic/internal/handler/HomematicBridgeHandlerTest.java

fixes #16940 
Spaces in Callback-URL caused that values in openhab are no longer updated from ccu, but no error occoured at openhab (but on ccu3).

[homematic] Fixed #16940: Spaces in URLs are not allowed

---

bundles/org.openhab.binding.visualcrossing/docs/Day_01.items
bundles/org.openhab.binding.visualcrossing/docs/Day_02.items
bundles/org.openhab.binding.visualcrossing/docs/Day_03.items
bundles/org.openhab.binding.visualcrossing/docs/Day_04.items
bundles/org.openhab.binding.visualcrossing/docs/Day_05.items
bundles/org.openhab.binding.visualcrossing/docs/Day_06.items
bundles/org.openhab.binding.visualcrossing/docs/Day_07.items
bundles/org.openhab.binding.visualcrossing/docs/Day_08.items
bundles/org.openhab.binding.visualcrossing/docs/Day_09.items
bundles/org.openhab.binding.visualcrossing/docs/Day_10.items
bundles/org.openhab.binding.visualcrossing/docs/Day_11.items
bundles/org.openhab.binding.visualcrossing/docs/Day_12.items
bundles/org.openhab.binding.visualcrossing/docs/Day_13.items
bundles/org.openhab.binding.visualcrossing/docs/Day_14.items
bundles/org.openhab.binding.visualcrossing/docs/Day_15.items
bundles/org.openhab.binding.visualcrossing/src/main/resources/OH-INF/thing/channel-types.xml

@lsiepel I found 1 bug 😬 and 1 missing doc
1. I cannot add `uihint` with % channel `Caused by: java.lang.IllegalArgumentException: A unit hint must not be set if the item type is not a number with dimension!`
2. At `Day_xx.items` files I was missing hours. `only_days.items` contains days without hours and `Day_xx.items` should contains 0-23 hours (for easy copying)

[visualcrossing] Fix missing dimension

---

bundles/org.openhab.binding.airgradient/src/main/java/org/openhab/binding/airgradient/internal/discovery/AirGradientLocationDiscoveryService.java

[AirGradient] Convert from AbstractDiscoveryService to AbstractThingHandlerDiscoveryService
Because we get NPE on apiHandler in 4.2.1 (not on 4.2.0).
This has been tested to not get the same NPE in 4.2.1, and is aligning the code to the new way to
write discovery services.
The reason AbstractDiscoveryService was used was to keep backwards compatibility when developing the
binding outside the code base and it was installed from the addon store.

[AirGradient] Convert from AbstractDiscoveryService to AbstractThingHandlerDiscoveryService

---

bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/AwattarPrice.java
bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/api/AwattarApi.java
bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/handler/AwattarBestPriceHandler.java
bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/handler/AwattarBridgeHandler.java
bundles/org.openhab.binding.awattar/src/main/resources/OH-INF/i18n/awattar.properties
bundles/org.openhab.binding.awattar/src/test/java/org/openhab/binding/awattar/internal/api/AwattarApiTest.java
bundles/org.openhab.binding.awattar/src/test/java/org/openhab/binding/awattar/internal/handler/AwattarBridgeHandlerRefreshTest.java
bundles/org.openhab.binding.awattar/src/test/java/org/openhab/binding/awattar/internal/handler/AwattarBridgeHandlerTest.java
bundles/org.openhab.binding.awattar/src/test/resources/org/openhab/binding/awattar/internal/api/api_response.json

This PR introduces an class for the aWATTar API for future refactoring and testing.
The class is intended to encapsualtes the API access.
All current tests will still be positive but can later be split into API and Bridge tests.

[aWATTar] add aWATTar API class

---

bundles/org.openhab.transform.basicprofiles/src/main/java/org/openhab/transform/basicprofiles/internal/profiles/StateFilterProfile.java
bundles/org.openhab.transform.basicprofiles/src/test/java/org/openhab/transform/basicprofiles/internal/profiles/StateFilterProfileTest.java

Fix a bug introduced in #17323: the item state on the right hand side is only evaluated on the first check execution.

[basicprofile] Fix statefilter check against item's value on the rhs

---

bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc2/NikoHomeControlCommunication2.java

https://github.com/openhab/openhab-addons/pull/16834 introduced better support for alarm systems in Niko Home Control.
It broke the functionality when the alarm is not a full alarm system with arming/disarming functionality, but just an trigger. This fix restores basic functionality.

[nikohomecontrol] fix basic alarm

---

bundles/org.openhab.binding.mqtt.homeassistant/pom.xml
bundles/org.openhab.transform.jinja/pom.xml
bundles/org.openhab.transform.jinja/src/main/feature/feature.xml

Follow-up to #17356 
Depends on https://github.com/openhab/openhab-osgiify/pull/49
The former version did use the OSGiified bundle, but did still embed it. This properly adds it as a bundle dependency.

[transform.jinja] Properly use jinjava OSGi

---

bundles/org.openhab.binding.kaleidescape/README.md
bundles/org.openhab.binding.kaleidescape/src/main/feature/feature.xml
bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/KaleidescapeBindingConstants.java
bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/communication/KaleidescapeStatusCodes.java
bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/discovery/KaleidescapeDiscoveryParticipant.java
bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/discovery/KaleidescapeDiscoveryService.java

This PR implements the following changes:
- Support discovery of Strato V
- Alto and Strato are now discovered via UPnP
- Status code lookup tables for VIDEO_MODE and EOTF updated per the latest Kaleidescape Control Protocol document

[kaleidescape] Support discovery of Strato V

---

bundles/org.openhab.binding.solarman/README.md
bundles/org.openhab.binding.solarman/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.solarman/src/main/resources/definitions/deye_2mppt.yaml
bundles/org.openhab.binding.solarman/src/main/resources/definitions/deye_4mppt.yaml
bundles/org.openhab.binding.solarman/src/main/resources/definitions/deye_hybrid.yaml
bundles/org.openhab.binding.solarman/src/main/resources/definitions/deye_sg04lp3.yaml
bundles/org.openhab.binding.solarman/src/main/resources/definitions/hyd-zss-hp-3k-6k.yaml
bundles/org.openhab.binding.solarman/src/main/resources/definitions/kstar_hybrid.yaml
bundles/org.openhab.binding.solarman/src/main/resources/definitions/sofar_g3hyd.yaml
bundles/org.openhab.binding.solarman/src/main/resources/definitions/sofar_hyd3k-6k-es.yaml
bundles/org.openhab.binding.solarman/src/main/resources/definitions/sofar_lsw3.yaml
bundles/org.openhab.binding.solarman/src/main/resources/definitions/solis_3p-4g.yaml
bundles/org.openhab.binding.solarman/src/main/resources/definitions/solis_hybrid.yaml
bundles/org.openhab.binding.solarman/src/main/resources/definitions/solis_s6-gr1p.yaml

This PR implements the following changes:
1. Syncs the inverter definition files from upstream (https://github.com/StephanJoubert/home_assistant_solarman/tree/main/custom_components/solarman/inverter_definitions).
2. Updates README.md to add the new channels which have been made available.
3. Updates thing-types.xml to add the new supported inverters.

[solarman] Sync inverter definition files from upstream.

---

bundles/org.openhab.binding.tplinksmarthome/README.md
bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/TPLinkSmartHomeThingType.java
bundles/org.openhab.binding.tplinksmarthome/src/main/resources/OH-INF/i18n/tplinksmarthome.properties
bundles/org.openhab.binding.tplinksmarthome/src/main/resources/OH-INF/thing/EP25.xml

The Kasa EP25 appears to be a version of the KP125 that lacks the LED. Because of this, and per the comments in #16027, this simply copies the KP125, without the LED channel.
This is my attempt at contributing to this project, so I'm sure I've missed something. I haven't run any testing or build steps, all I've done is use the code that I saw in PR #1171 (Adding the KP125) as a template and add the EP25 device. I'm hoping this at least provides a base for someone more familiar with the project to do a quick review and test so we can get the device added! As mentioned in #16027, the EP25 appears to behave properly when added manually as a KP125 device, but that is the only testing that I've done, I have *not* figured out how to take this PR into my live OpenHAB environment to test it.
If …

[tplinksmarthome] Add new device: EP25

---

bundles/org.openhab.binding.warmup/README.md
bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/WarmupBindingConstants.java
bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/action/WarmupActions.java
bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/api/MyWarmupApi.java
bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/discovery/WarmupDiscoveryService.java
bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/handler/RoomHandler.java
bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/handler/WarmupThingHandler.java
bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/model/auth/AuthRequestDTO.java
bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/model/auth/AuthRequestDataDTO.java
bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/model/auth/AuthResponseDTO.java
bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/model/auth/AuthResponseDataDTO.java
bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/model/auth/AuthResponseStatusDTO.java
bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/model/query/DeviceDTO.java
bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/model/query/LocationDTO.java
bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/model/query/QueryDataDTO.java
bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/model/query/QueryResponseDTO.java
bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/model/query/RoomDTO.java
bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/model/query/UserDTO.java
bundles/org.openhab.binding.warmup/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.warmup/src/main/resources/OH-INF/i18n/warmup.properties
bundles/org.openhab.binding.warmup/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.warmup/src/main/resources/OH-INF/update/warmup.xml

Enhancements to the Warmup binding:
1. Documentation updates to reflect that it supports a range of devices
2. Fix to `targetTemperature` channel - this was broken by a UoM change to the multiply function
3. Add a `fixedTemperature` channel - sets a fixed mode where the setpoint does not vary on a schedule
4. Add an `energyToday` channel - reports cumulative energy usage
5. Make `runMode` writeable to return the mode to a schedule
6. Add thing action for dynamic overrides

[warmup] Fixes & Enhancements

---

bundles/org.openhab.binding.goecharger/README.md

[goecharger] Update README.md (name of chargers and setup instructions)
I got stuck connecting my charger, because I did not find any hint in the readme that elaborates the need to activate the local HTTP API on the app first. Added this hint with a short chapter.
At the same time, when adding information on the support for the new Gemini charger, I realized that go-e slightly changed the spelling of their products, which I updated too throughout the readme.
Not needed (readme only)

[goecharger] Update README.md

---

bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/onvif/OnvifConnection.java

Added a missing motion detection topic for VivoTek cameras as reported on the forum by a user here:
https://community.openhab.org/t/unimplemented-onvif-event-videoanalytics-motion/157364

[ipcamera]Add missing motion detection topic for VivoTek FD9388-HTV cameras

---

bundles/org.openhab.binding.kaleidescape/README.md
bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/KaleidescapeBindingConstants.java
bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/configuration/KaleidescapeThingConfiguration.java
bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/handler/KaleidescapeHandler.java
bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/handler/KaleidescapeMessageHandler.java
bundles/org.openhab.binding.kaleidescape/src/main/resources/OH-INF/config/config.xml
bundles/org.openhab.binding.kaleidescape/src/main/resources/OH-INF/i18n/kaleidescape.properties

This PR implements the following improvements:
- Improve handling of volume events from IR remotes (i.e. KREMOTE-STRATO, KREMOTE-20). MUTE_TOGGLE events were not published to the user_defined_event channel by the previous implementation.
- Add an additional thing configuration parameter 'volumeBasicEnabled' that configures the Kaleidescape iPad and phone apps for stateless volume up/down and mute controls.
- Provide additional rule examples for both volume handling scenarios.
- Improve exiting rule examples and documentation.

[kaleidescape] Improve volume event handling

---

bundles/org.openhab.binding.androidtv/src/main/java/org/openhab/binding/androidtv/internal/protocol/philipstv/service/TvChannelService.java
bundles/org.openhab.binding.androidtv/src/main/java/org/openhab/binding/androidtv/internal/protocol/philipstv/service/model/channel/AvailableTvChannelsDTO.java
bundles/org.openhab.binding.androidtv/src/test/java/org/openhab/binding/androidtv/internal/protocol/philipstv/service/PhilipsTvChannelTest.java

closing #17370
This fixes the issue for me. But needs to be tested for older TVs which provides the int as a version.
(note, the alternative would be to completely remove the version parsing, as the getVersion & setVersions don't seem to be called anywhere)

[androidTV] fix version parsing for newer Philips TV models

---

bundles/org.openhab.binding.senechome/src/main/java/org/openhab/binding/senechome/internal/SenecHomeApi.java
bundles/org.openhab.binding.senechome/src/main/java/org/openhab/binding/senechome/internal/SenecHomeHandler.java
bundles/org.openhab.binding.senechome/src/main/java/org/openhab/binding/senechome/internal/SenecSystemStatus.java
bundles/org.openhab.binding.senechome/src/main/java/org/openhab/binding/senechome/internal/SenecWallboxStatus.java
bundles/org.openhab.binding.senechome/src/main/java/org/openhab/binding/senechome/internal/dto/SenecHomeBattery.java
bundles/org.openhab.binding.senechome/src/main/java/org/openhab/binding/senechome/internal/dto/SenecHomeEnergy.java
bundles/org.openhab.binding.senechome/src/main/java/org/openhab/binding/senechome/internal/dto/SenecHomeGrid.java
bundles/org.openhab.binding.senechome/src/main/java/org/openhab/binding/senechome/internal/dto/SenecHomePower.java
bundles/org.openhab.binding.senechome/src/main/java/org/openhab/binding/senechome/internal/dto/SenecHomeResponse.java
bundles/org.openhab.binding.senechome/src/main/java/org/openhab/binding/senechome/internal/dto/SenecHomeStatistics.java
bundles/org.openhab.binding.senechome/src/main/java/org/openhab/binding/senechome/internal/dto/SenecHomeTemperature.java
bundles/org.openhab.binding.senechome/src/main/java/org/openhab/binding/senechome/internal/dto/SenecHomeWallbox.java

- Fixes https://github.com/openhab/openhab-addons/issues/17298
- Fixes compile warnings
- Add null annotations
Test jar (openHAB 4.2.0+): https://1drv.ms/u/s!AnMcxmvEeupwjv9z4GKsp4RZxpWAFg?e=FpXAc9

[senechome] Fix `ArrayIndexOutOfBoundsException` when less than 4 packs

---

bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/MelCloudBindingConstants.java
bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/MelCloudHandlerFactory.java
bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/api/MelCloudConnection.java
bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/api/dto/Area.java
bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/api/dto/Device.java
bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/api/dto/DeviceProps.java
bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/api/dto/DeviceStatus.java
bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/api/dto/Floor.java
bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/api/dto/HeatpumpDeviceStatus.java
bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/api/dto/ListDevicesResponse.java
bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/api/dto/LoginClientResponse.java
bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/api/dto/LoginData.java
bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/api/dto/Preset.java
bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/api/dto/QuantizedCoordinates.java
bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/api/dto/Structure.java
bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/api/dto/WeatherObservation.java
bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/config/AcDeviceConfig.java
bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/config/AccountConfig.java
bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/config/HeatpumpDeviceConfig.java
bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/discovery/MelCloudDiscoveryService.java
bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/exceptions/MelCloudCommException.java
bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/exceptions/MelCloudLoginException.java
bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/handler/MelCloudAccountHandler.java
bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/handler/MelCloudDeviceHandler.java
bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/handler/MelCloudHeatpumpDeviceHandler.java

- Fixes https://github.com/openhab/openhab-addons/issues/17268
- Adds null annotations
- Fixes SAT errors
Test jar (4.2.0+): https://1drv.ms/u/s!AnMcxmvEeupwjv9oizGjOiFJV0gIJw?e=Qi4RZT

[melcloud] Improve null handling

---

bundles/org.openhab.transform.map/README.md
bundles/org.openhab.transform.map/src/main/java/org/openhab/transform/map/internal/MapTransformationService.java
bundles/org.openhab.transform.map/src/main/resources/OH-INF/config/mapProfile.xml
bundles/org.openhab.transform.map/src/main/resources/OH-INF/i18n/map.properties
bundles/org.openhab.transform.map/src/test/java/org/openhab/transform/map/internal/MapTransformationServiceTest.java

Supersedes #17322
- The delimiter can be changed by adding `?delimiter=` immediately after the pipe character `|`.
To use `?delimiter` as an actual map key, do not place it at the beginning of the map.
- Remove special handling of newline characters. Previously when `\n` was found in the inline pattern, the semicolon delimiters were ignored. This is now no longer the case. 
Some examples of changing to different delimiters:
- `|?delimiter=,online=ON,offline=OFF`
- `|?delimiter=|online=ON|offline=OFF`
- `|?delimiter=##online=ON##offline=OFF`

[map] Add a way to customize inline-map delimiters

---

bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitCharacteristicFactory.java
bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitLightSensorImpl.java

Fixes #15818
* Illuminance can obviously get down to 0, instead of 0.0001lx (especially if your sensor only reports integer values)
* Raise Illuminance ceiling slightly (from 100k lx)
* Adjust default range of Color Temperature to the warmest and coolest bulbs I could find on Amazon (for settable characteristics, you don't want to have too large of a range because HomeKit will often use those ranges to determine the scale of the slider). Original is 50-400 mired/2500-20000 K
* Lower min value of current temperature from 0°C to -100°C (going below freezing is not unusual. lowest recorded temperature on earth is -89.2°C. I just chose a nice round number)

[homekit] Adjust default ranges for some characteristics

---

bundles/org.openhab.persistence.jdbc/src/main/resources/OH-INF/addon/addon-oracle.xml
bundles/org.openhab.persistence.jdbc/src/main/resources/OH-INF/i18n/jdbc.properties
features/openhab-addons-external/src/main/resources/conf/jdbc.cfg

- Fixes an error in `addon-oracle.xml` which was copied from another file and not updated completely
- Updates i8n
- Updates content of `jdbc.cfg` to include Oracle url example

[jdbc] Fix error in addon info for Oracle

---

bundles/org.openhab.binding.nikohomecontrol/README.md
bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/NikoHomeControlBindingConstants.java
bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/NikoHomeControlHandlerFactory.java
bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/console/NikoHomeControlCommandExtension.java
bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/discovery/NikoHomeControlBridgeDiscoveryService.java
bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/handler/NikoHomeControlBridgeHandler.java
bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/handler/NikoHomeControlBridgeHandler1.java
bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/handler/NikoHomeControlBridgeHandler2.java
bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/NikoHomeControlDiscover.java
bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc2/NikoHomeControlCommunication2.java

Added console commands to retrieve information about the Niko Home Control installation. This is useful to get all information for as yet unsupported devices, to be able to implement these. It gives an easy way to users to extract and provide this information.
As this information is collected based on a unique Niko Home Control controller ID, also made this controller ID the representation property.

[nikohomecontrol] Add console commands

---

bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/Clip2Thing.xml
bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/channels.xml

Follows on from #15984 by applying `autoUpdatePolicy=veto` on several more channels which **_both_** a) are writable, and b) send immediate SSE notifications. See forum discussion [here](https://community.openhab.org/t/philips-hue-clip-2-api-v2-discussion-thread/142111/502)

[hue] Apply 'autoUpdatePolicy=veto' on more channels

---

bundles/org.openhab.binding.wifiled/src/main/java/org/openhab/binding/wifiled/internal/handler/AbstractWiFiLEDDriver.java
bundles/org.openhab.binding.wifiled/src/main/java/org/openhab/binding/wifiled/internal/handler/ClassicWiFiLEDDriver.java

When I tried the binding on my LED bulb, I encountered an issue while attempting to change its color: the changes were not applied, and after restarting the bulb, no light was emitted.
After a lot of tests, I discovered that the problem was due to the fact that the level write mode was consistently set to `0x00` in this binding.
This pull request addresses this issue, ensuring the correct updating of my bulb's color, and it should not affect other devices. Unfortunately, I am unable to test it, as the only compatible WiFi LED I have is this one... I tried the binding on my own setup and everything works fine for me with these changes.
For reference, I used this python implementation: [Danielhiversen/flux_led](https://github.com/Danielhiversen/flux_led).
I am not sure that I implemented it …

[wifiled] Support LED's that demand seperate white and color updates

---

bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/discovery/HomematicDeviceDiscoveryService.java
bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/handler/HomematicBridgeHandler.java

Fixed a NPE caused due new check introduced in #17206
fixes #17372

[homematic] Fix `NullPointerException` in discovery

---

bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java

This change will limit the interpolation workaround to updates to different values.
In case we write the same value again, there should be no interpolation between the same value and the workaround can be skipped.
Signed-off-by: Jörg Sautter <joerg.sautter@gmx.net>

[rrd4j] Improved the interpolation workaround

---

bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/Clip2ThingHandler.java

Previously room / zone Things did not have the `resourceId` representation property assigned. This meant that if the respective thing was instantiated, it would still be re-added to the inbox. This PR resolves that issue.

[hue] Room / Zone Things no longer re-appear in Inbox

---

bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/HaID.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/handler/HomeAssistantThingHandler.java

Refs #17182.
This does not (yet) handle component discovery topics getting deleted from MQTT, just channels left over after you've manually removed a component topic from the thing config.

[mqtt.homeassistant] Remove channels for no-longer-configured components

---

bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java

Calling `RrdDb.getRrdDef` will read several fields and create a complete `RrdDef` copy.
This PR will avoid this and read the needed information from the `Header` / `Archive`.
Signed-off-by: Jörg Sautter <joerg.sautter@gmx.net>

[rrd4j] Avoid RrdDb.getRrdDef calls

---

bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/SecurityApi.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/SecurityCapability.java

[netatmo] Prevent `IndexOutOfBoundsException`

---

bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/config/dto/AbstractChannelConfiguration.java

While it's useful in general to not have to copy/paste a MQTT message into a JSON parser to verify syntax, it also includes details about fields that are the wrong data type that a generic JSON parser won't catch. A la #17375.
Example log line:
```
2024-09-20 11:06:17.539 [WARN ] [nal.discovery.HomeAssistantDiscovery] - HomeAssistant discover error: invalid configuration of thing smartlock component lock: Cannot parse channel configuration JSON: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 213 path $.avty
```

[mqtt.homeassistant] Include the details of JSON syntax errors when parsing fails

---

bundles/org.openhab.binding.mqtt.homeassistant/pom.xml
bundles/org.openhab.binding.mqtt.homeassistant/src/main/feature/feature.xml
bundles/org.openhab.transform.jinja/pom.xml
bundles/org.openhab.transform.jinja/src/main/feature/feature.xml
features/openhab-addons/src/main/resources/footer.xml
itests/org.openhab.binding.mqtt.homeassistant.tests/itest.bndrun

Dependent on https://github.com/openhab/openhab-osgiify/pull/51.
Closes #15145

[mqtt.homeassistant] Update Jinjava to 2.7.3

---

bundles/org.openhab.binding.oppo/README.md
bundles/org.openhab.binding.oppo/src/main/resources/OH-INF/thing/channels.xml

Set autoUpdatePolicy=veto for `remote_button` channel

[oppo] Set autoUpdatePolicy for remote_button channel

---

bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/generic/internal/MqttThingHandlerFactory.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/HomeAssistantChannelTransformation.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/HomeAssistantJinjaFunctionLibrary.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/HomeAssistantChannelTransformationTests.java

`iif` is pretty straight forward besides having optional parameters. `is_defined` is a bit weird, because it's _supposed_ to throw an exception, which is then silently ignored and used to _not_ update a value. This actually works out because mqtt.generic checks if a transformation returns null, and if it does just ignores the message.
There are lots more HASS extensions to implement, but it'll be a slow process to check which ones are already implemented in Jinjava, which ones don't even make sense in openHAB, which ones are even possible to implement, etc. But these two seem like the most desperately needed, and serve as a base to easily add more, so this is where I started.
Refs #15382, #17374, #16872.
For #16872, I need to do more investigation to see what's up. Jinjava will return an …

[mqtt.homeassistant] implement iif and is_defined jinja function and filters

---

bundles/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusTransformation.java
bundles/org.openhab.binding.modbus/src/test/java/org/openhab/binding/modbus/internal/ModbusTransformationTest.java

[modbus] Discard data if transformation failed

---

bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/AbstractMQTTThingHandler.java
bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/AvailabilityTracker.java
bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/handler/GenericMQTTThingHandler.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/ComponentChannel.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/AbstractComponent.java
bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/internal/handler/HomieThingHandler.java

Use the local Jinjava, instead of implicitly depending on the Jinja transformation service.
This was missed in the recent conversion to using Jinjava for transformations in "normal" channels.

[mqtt.homeassistant] Fix jinja usage in availability templates

---

bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/EmotivaBindingConstants.java
bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/EmotivaCommandHelper.java
bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/EmotivaProcessorHandler.java
bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/EmotivaProcessorState.java
bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/EmotivaUdpReceivingService.java
bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/EmotivaUdpSendingService.java
bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/InputStateOptionProvider.java
bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/dto/EmotivaSubscriptionRequest.java
bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/dto/EmotivaUnsubscribeDTO.java
bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/protocol/EmotivaControlRequest.java
bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/protocol/EmotivaSubscriptionTags.java
bundles/org.openhab.binding.emotiva/src/test/java/org/openhab/binding/emotiva/internal/EmotivaCommandHelperTest.java
bundles/org.openhab.binding.emotiva/src/test/java/org/openhab/binding/emotiva/internal/EmotivaProcessorStateTest.java
bundles/org.openhab.binding.emotiva/src/test/java/org/openhab/binding/emotiva/internal/dto/EmotivaSubscriptionRequestTest.java
bundles/org.openhab.binding.emotiva/src/test/java/org/openhab/binding/emotiva/internal/dto/EmotivaUnsubscriptionTest.java
bundles/org.openhab.binding.emotiva/src/test/java/org/openhab/binding/emotiva/internal/protocol/EmotivaControlRequestTest.java

Fixes https://github.com/openhab/openhab-addons/issues/17363
Can be backported to 4.2.x

[emotiva] Fix missing data in source channels

---

itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/handler/test/WemoMakerHandlerOSGiTest.java

Hopefully this (temporary) fixes the build issues. Not sure what casused this itest to fail, probably something in core or a dependency as there does not seem to be a wemo binding related PR.
Somewhere between 18/19 september all  (except 1 ?!) seem to fail.

[wemo] Disable wemo itest to fix build issue

---

bundles/org.openhab.binding.androiddebugbridge/README.md
bundles/org.openhab.binding.ephemeris/README.md
bundles/org.openhab.binding.loxone/README.md
bundles/org.openhab.binding.mycroft/README.md
bundles/org.openhab.binding.mynice/README.md
bundles/org.openhab.binding.netatmo/README.md
bundles/org.openhab.binding.nikobus/README.md
bundles/org.openhab.binding.openuv/README.md
bundles/org.openhab.binding.openwebnet/README.md
bundles/org.openhab.binding.smsmodem/README.md
bundles/org.openhab.binding.sncf/README.md
bundles/org.openhab.binding.synopanalyzer/README.md
bundles/org.openhab.binding.teleinfo/README.md
bundles/org.openhab.binding.vektiva/README.md
bundles/org.openhab.binding.vigicrues/README.md
bundles/org.openhab.binding.xmltv/README.md
bundles/org.openhab.binding.yamahamusiccast/README.md
bundles/org.openhab.io.openhabcloud/README.md
bundles/org.openhab.transform.scale/README.md
bundles/org.openhab.voice.mimictts/README.md

In French, there is a space before a colon, whereas in English, there is not.
Also fix spelling occured → occurred.

Remove space before colon

---

bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/action/WarmupActions.java
bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/handler/RoomHandler.java
bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/handler/WarmupThingHandler.java

[warmup] Set Dimension to QuantityType

---

bundles/org.openhab.binding.linktap/src/main/java/org/openhab/binding/linktap/internal/LinkTapBridgeHandler.java

Regression of openhab/openhab-core#4389

[linktap] Fix build

---

bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/DebuggingGraalScriptEngine.java
bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/OpenhabGraalJSScriptEngine.java

… to avoid illegal multi-thread access
Fixes #17494.

[jsscripting] Synchronize context access in logger initialization

---

itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/handler/test/WemoHandlerOSGiTest.java
itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/handler/test/WemoMakerHandlerOSGiTest.java

Related to #12474
See latest failure today: https://github.com/openhab/openhab-addons/actions/runs/11166591581/job/31040917173?pr=17501
```
TEST org.openhab.binding.wemo.internal.handler.test.WemoHandlerOSGiTest#assertThatThingHandlesOnOffCommandCorrectly() <<< ERROR: 
Expected: is <UNKNOWN>
but: was <OFFLINE>
java.lang.AssertionError: 
Expected: is <UNKNOWN>
but: was <OFFLINE>
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
at org.openhab.binding.wemo.internal.handler.test.WemoHandlerOSGiTest.lambda$0(WemoHandlerOSGiTest.java:78)
at org.openhab.core.test.java.JavaTest.waitForAssert(JavaTest.java:245)
at org.openhab.core.test.java.JavaTest.waitForAssert(JavaTest.java:213)
at …
```

[wemo] Disable more unstable tests

---

bundles/org.openhab.binding.telegram/src/main/java/org/openhab/binding/telegram/internal/action/TelegramActions.java

Also fix the methods sendTelegramAnimation for DSL rules that were calling sendTelegramVideo actions.
Related to #17504

[telegram] Add missing @ActionOutput annotation

---

bundles/org.openhab.binding.solarforecast/README.md
bundles/org.openhab.binding.solarforecast/src/main/java/org/openhab/binding/solarforecast/internal/actions/SolarForecastActions.java

[solarforecast] Add missing @ActionOutput annotation

---

bundles/org.openhab.binding.kaleidescape/README.md
bundles/org.openhab.binding.kaleidescape/src/main/feature/feature.xml
bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/discovery/KaleidescapeDiscoveryParticipant.java
bundles/org.openhab.binding.kaleidescape/src/main/resources/OH-INF/addon/addon.xml

Regression of #17371. UPnP discovery does not work due to an invalid deviceType field in the device description.xml. Accordingly, this PR changes the discovery participant to use SDDP instead.

[kaleidescape] Switch to SDDP discovery

---

bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/schema/ApiPageParser.java
bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/schema/ChangerX2Entry.java
bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/schema/ChangerX2Parser.java
bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/schema/TACmiSchemaHandler.java

Hi,
* This PR fixes some wrong Unit of Measurement mappings for some values provided by the C.M.I.. I haven't used them, so I didn't notice the problem.
* It also improves the handling of the values themselves.
The changes should fix #12445 
Finally (the 3rd commit) adds support for the time values provided by the C.M.I.. Since only hour/minutes are provided, the current day is used for the date part in the DateTimeType.
Bye,
chris

[tacmi] Unit of Measurement fixes, added missing DateTime support

---

bundles/org.openhab.binding.pushbullet/README.md
bundles/org.openhab.binding.pushbullet/src/main/java/org/openhab/binding/pushbullet/internal/PushbulletBindingConstants.java
bundles/org.openhab.binding.pushbullet/src/main/java/org/openhab/binding/pushbullet/internal/PushbulletConfiguration.java
bundles/org.openhab.binding.pushbullet/src/main/java/org/openhab/binding/pushbullet/internal/PushbulletHttpClient.java
bundles/org.openhab.binding.pushbullet/src/main/java/org/openhab/binding/pushbullet/internal/handler/PushbulletHandler.java
bundles/org.openhab.binding.pushbullet/src/main/resources/OH-INF/i18n/pushbullet.properties
bundles/org.openhab.binding.pushbullet/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.pushbullet/src/main/resources/OH-INF/update/instructions.xml

This change removes unimplemented channels and thing parameters.
It also hardcodes the API Base URL parameter since there is no way to run your own Pushbullet server as far as I know.

[pushbullet] Remove unimplemented channels and thing parameters

---

itests/org.openhab.automation.groovyscripting.tests/itest.bndrun
itests/org.openhab.automation.jsscriptingnashorn.tests/itest.bndrun
itests/org.openhab.binding.mqtt.homeassistant.tests/itest.bndrun

Related to:
* openhab/openhab-core#4398
* openhab/openhab-core#4403

Resolve runbundles for Xtext and Jollyday upgrades

---

bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/UniFiBindingConstants.java
bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/dto/UniFiDevice.java
bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/handler/UniFiAccessPointThingHandler.java
bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/handler/UniFiBaseThingHandler.java
bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/handler/UniFiThingDiscoveryService.java

This provides a few basic properties for the `accessPoint` Thing.
Also removes two properties for the `wlan` being provided (only) by discovery. They were probably mistakenly copied from another Thing type for which they are parameters. They are not parameters the `wlan` Thing:
https://github.com/openhab/openhab-addons/blob/6b411899cc5cbe2e0822b1b3939ed2a2867489e6/bundles/org.openhab.binding.unifi/src/main/resources/OH-INF/config/config.xml#L47-L52
`site` is parameter for the `client` Thing:
https://github.com/openhab/openhab-addons/blob/6b411899cc5cbe2e0822b1b3939ed2a2867489e6/bundles/org.openhab.binding.unifi/src/main/resources/OH-INF/config/config.xml#L59-L62

[unifi] Provide basic properties for access point

---

bundles/org.openhab.binding.gree/README.md
bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/GreeBindingConstants.java
bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/GreeConfiguration.java
bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/GreeCryptoUtil.java
bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/GreeException.java
bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/discovery/GreeDeviceFinder.java
bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/discovery/GreeDiscoveryService.java
bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/handler/GreeAirDevice.java
bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/handler/GreeHandler.java
bundles/org.openhab.binding.gree/src/main/resources/OH-INF/i18n/gree.properties
bundles/org.openhab.binding.gree/src/main/resources/OH-INF/thing/thing-types.xml

Change the encryption mode to GCM if different when binding to AC device fails with SocketTimeoutException and try again. Detect if device version is bigger than or equal to 2 and set encryption to GCM
Fixes #16911
There are gree devices that on scan request responds with package encrypted with ECB encryption using the old key, but expects GCM encryption bind request in response. Such behavior is described in #16911 
Also in [openhab community forum](https://community.openhab.org/t/new-gree-air-conditioner-binding/36429/487) a few people are saying that they have the same problem.
Not sure which approach is better to change the encryption mode to GCM when SocketTimeoutException was catched and try again or try to determine is the AC expects GCM encryption bind request base on the value of …

[gree] Use GCM encryption when bind fails

---

bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/ChannelState.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/ComponentChannel.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/AbstractComponent.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/AlarmControlPanel.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/BinarySensor.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Button.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Camera.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Climate.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Cover.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/DefaultSchemaLight.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/DeviceTrigger.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Fan.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/JSONSchemaLight.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Light.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Lock.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Number.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Scene.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Select.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Sensor.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Switch.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/TemplateSchemaLight.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Vacuum.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/handler/HomeAssistantThingHandler.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/resources/OH-INF/config/homeassistant-channel-config.xml
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/BinarySensorTests.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/SensorTests.java
itests/org.openhab.binding.mqtt.homeassistant.tests/src/main/java/org/openhab/binding/mqtt/homeassistant/HomeAssistantMQTTImplementationTest.java

This fixes a couple of problems. The biggest is that if multiple components were single channel OR no-name, they would all get mapped to a "groupId" of "", and the next time the Thing started, all but one of them would disappear unless new discovery information was received. While fixing that, I fixed two other issues:
* Multi-channel components with a blank name were getting all their channels dumped into the top level of no group. In the newStyleChannels world, we don't care about the component's name anymore - multi-channel components get a group, single-channel components do not.
* Instead of statically saying that certain components are only ever single or multi-channel components, determine at runtime if a component only added a single channel, and if so re-classify it as a …

[mqtt.homeassistant] fix newStyleChannels

---

bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/ComponentChannel.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Climate.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Cover.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/DefaultSchemaLight.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Fan.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/JSONSchemaLight.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Number.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Select.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Switch.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/TemplateSchemaLight.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/AbstractComponentTests.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/FanTests.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/NumberTests.java

This really doesn't make much difference unless you've set `sendOptimisticUpdates=false` for AutoUpdateManager, but if you have, this can be critical to having proper functionality.

[mqtt.homeassistant] Implement optimistic components with AutoUpdatePolicy.RECOMMEND

---

bundles/org.openhab.binding.evcc/src/main/java/org/openhab/binding/evcc/internal/EvccHandler.java

Since EVCC version 0.127.0 (https://github.com/evcc-io/evcc/pull/13319) the [EVCC Rest API](https://docs.evcc.io/docs/integrations/rest-api) duration states are in seconds instead of nanoseconds.
Current EVCC implementation still treats them as Nano-Seconds. E.g.:
```
long chargeDuration = loadpoint.getChargeDuration();
channel = new ChannelUID(uid, channelGroup, CHANNEL_LOADPOINT_CHARGE_DURATION);
updateState(channel, new QuantityType<>(chargeDuration, MetricPrefix.NANO(Units.SECOND)));
```
Fixes the following issues:
- https://github.com/openhab/openhab-addons/issues/17485
- https://github.com/openhab/openhab-addons/issues/17432

[evcc] API change on duration channels

---

bundles/org.openhab.binding.automower/src/main/java/org/openhab/binding/automower/internal/things/AutomowerCommand.java

Fixed the problem of non-working automower command channels reported via [automower-missing-channels/122319/4](https://community.openhab.org/t/automower-missing-channels/122319/4).

[automower] fix automower command channels

---

bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/IpCameraBindingConstants.java
bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/handler/IpCameraHandler.java
bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/onvif/OnvifCodec.java
bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/onvif/OnvifConnection.java

+ Refactor to use a switch statement instead of .contains
+ Add an auto restart to the event stream if a camera closes the request without making a valid ONVIF reply.
+ Improve date and time check to ensure the time is in sync with openHAB.

[ipcamera] Improve onvif events with an auto restart feature

---

bundles/org.openhab.binding.omnikinverter/README.md
bundles/org.openhab.binding.omnikinverter/src/main/java/org/openhab/binding/omnikinverter/internal/OmnikInverterConfiguration.java
bundles/org.openhab.binding.omnikinverter/src/main/java/org/openhab/binding/omnikinverter/internal/handler/OmnikInverterHandler.java
bundles/org.openhab.binding.omnikinverter/src/main/resources/OH-INF/i18n/omnikinverter.properties
bundles/org.openhab.binding.omnikinverter/src/main/resources/OH-INF/thing/thing-types.xml

Fixes: https://github.com/openhab/openhab-addons/issues/10123

[omnikinverter] Add refreshInterval parameter

---

bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/DahuaHandler.java
bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/ReolinkHandler.java
bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/handler/IpCameraHandler.java
bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/onvif/OnvifConnection.java

PR does the following:
+ Fixes a major bug that stops mjpeg from getting fetched from a camera if the user enters their own URL. Code strips the IP and port from the requestUrl so it never matches the user entered URL.
+ Minor improvements for Dahua users that were picked up when running tests with a newer camera.
+ Fix minor compiler warnings.
User reported this bug here on the forum
https://community.openhab.org/t/ipcamera-new-ip-camera-binding/42771/2977

[ipcamera]Fix mjpeg does not work if overridden by user

---

bundles/org.openhab.binding.fmiweather/README.md
bundles/org.openhab.binding.fmiweather/src/main/java/org/openhab/binding/fmiweather/internal/AbstractWeatherHandler.java
bundles/org.openhab.binding.fmiweather/src/main/java/org/openhab/binding/fmiweather/internal/BindingConstants.java
bundles/org.openhab.binding.fmiweather/src/main/java/org/openhab/binding/fmiweather/internal/ForecastWeatherHandler.java
bundles/org.openhab.binding.fmiweather/src/main/resources/OH-INF/i18n/fmiweather.properties
bundles/org.openhab.binding.fmiweather/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.fmiweather/src/main/resources/OH-INF/update/instructions.xml

This introduces a new channel group `forecast` with channels receiving both current and future values (through time series).
See https://community.openhab.org/t/spot-price-optimizer-advanced-algorhitms-to-optimize-heating-charging-of-electric-vehicles-water-boilers-and-more/159539/5
JARs for testing:
- [org.openhab.binding.fmiweather-4.2.3-SNAPSHOT.jar](https://drive.google.com/file/d/1r06S6I5y39bJADQTSX95CBx1gh2nruSC/view?usp=sharing)
- [org.openhab.binding.fmiweather-4.3.0-SNAPSHOT.jar](https://drive.google.com/file/d/1a4xXLUrygSLLkBN3mNFBAoIBcHixscsw/view?usp=sharing)

[fmiweather] Add time series support for forecasts

---

bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/handler/IpCameraHandler.java

Fix a bug where `http://192.XXX.YYY.17:80/ISAPI/Streaming/channels/103/httpPreview` this url was getting compared as:
`:80/ISAPI/Streaming/channels/103/httpPreview` to `/ISAPI/Streaming/channels/103/httpPreview`
Change will now allow users to specify a URL containing a port for the cameras MJPEG stream.

[ipcamera]Fix bug where port numbers in a URL stop MJPEG from camera working

---

bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/HomeEvent.java

[netatmo] Ensure expiresAt is usable

---

bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/EmotivaBindingConstants.java

Fixes https://github.com/openhab/openhab-addons/issues/17566
As stated in the issue. This was left out when I did some of the last refactoring on the initial PR. I have mostly been using the other volume channel, so did not notice it before now.
Can be backported to 4.2.x.

[emotiva] Fix main zone volume-db channel name

---

bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/SomfyTahomaBindingConstants.java
bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaBridgeHandler.java

This PR should improve stability of the binding and fix https://github.com/openhab/openhab-addons/issues/14763
More testing warmly welcomed, especially the Cozytouch OAUTH, Tahoma confirmed to be working fine by several users.

[somfytahoma] Switch Tahoma to OAUTH2 authentication

---

bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaBridgeHandler.java

Due to partial cherry-picking, I forgot to include the token refreshing feature in my last PR
https://github.com/openhab/openhab-addons/pull/17361
thanks for reviewing and merging

[somfytahoma] add proper OAuth2 token refreshing

---

bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/ChannelState.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/AbstractComponentTests.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/DeviceTriggerTests.java

If multiple DeviceTrigger components share a topic, and each has a payload value configured, only messages matching that payload should be delivered to the corresponding channel.
The DeviceTrigger already sets up the TextValue with the appropriate (single) enumeration of allowed value(s). But the mqtt.generic binding processes trigger before any value processing is done. So do the most basic of processing, to make sure the value is pertinent.

[mqtt.homeassistant] Avoid improperly delivered triggers

---

bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/WakeOnLanUtility.java
bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/handler/LGWebOSHandler.java
bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/handler/LGWebOSTVKeyboardInput.java
bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/handler/LGWebOSTVSocket.java
bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/handler/command/ServiceCommand.java
bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/handler/command/ServiceSubscription.java

Currently the representation property `deviceId` is only set when the device is added by auto-discovery (managed thing). When the device is configured by a file based configuration the property is not set.
This PR grabs this deviceId a.k.a UUID when performing the `hello` procedure similar to osVersion etc. This prevents the Thing to be added to the inbox while it already exists.
Also fixes some null annotations and compiler warnings while at it.

[lgwebos] Fix representation property

---

bundles/org.openhab.binding.fmiweather/README.md
bundles/org.openhab.binding.fmiweather/src/main/java/org/openhab/binding/fmiweather/internal/AbstractWeatherHandler.java
bundles/org.openhab.binding.fmiweather/src/main/java/org/openhab/binding/fmiweather/internal/ForecastWeatherHandler.java
bundles/org.openhab.binding.fmiweather/src/main/java/org/openhab/binding/fmiweather/internal/client/Client.java
bundles/org.openhab.binding.fmiweather/src/main/java/org/openhab/binding/fmiweather/internal/client/ForecastRequest.java
bundles/org.openhab.binding.fmiweather/src/main/java/org/openhab/binding/fmiweather/internal/config/ForecastConfiguration.java
bundles/org.openhab.binding.fmiweather/src/main/resources/OH-INF/i18n/fmiweather.properties
bundles/org.openhab.binding.fmiweather/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.fmiweather/src/test/java/org/openhab/binding/fmiweather/FMIRequestTest.java

[fmiweather] Add support for edited Scandinavia forecast

---

bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/ReolinkHandler.java
bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/handler/IpCameraHandler.java
bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/onvif/OnvifCodec.java
bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/onvif/OnvifConnection.java

Reolink cameras would not tell a user when the wrong user or password was entered, these changes make setup easier.

[ipcamera] Fix Reolink does not detect bad user or passwords.

---

bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/TACmiBindingConstants.java
bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/schema/ApiPageEntry.java
bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/schema/ApiPageParser.java
bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/schema/ChangerX2Entry.java
bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/schema/ChangerX2Parser.java
bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/schema/TACmiSchemaHandler.java
bundles/org.openhab.binding.tacmi/src/main/resources/OH-INF/i18n/tacmi.properties
bundles/org.openhab.binding.tacmi/src/main/resources/OH-INF/thing/thing-types.xml

Hi,
this PR picks up the discussion with @holana in [Issue #12445](https://github.com/openhab/openhab-addons/issues/12445#issuecomment-2390947317) to find a more generic way to map units between the TA devices and OpenHAB.
I had the idea to use a so called 'fixed value setting' within TA to test all possible unit types and validate the mapping to OH. Since this is now a generic way, it should also work for additional units added by TA, as long as they are supported by OpenHAB.
A special handling for time periods has also been implemented. Periods are mapped to a `Number:Time` channel. This is a bit complex because TA visualizes them in sequences like `1d 4h 20m 11.2s`.
During testing, we also discovered a situation where we had values that were reported as 'updateable' by TA, but when we …

[tacmi] Reworked unit-mapping between TA and OH; added support for timespans

---

bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/ComponentChannel.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/HaID.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/DeviceTrigger.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/handler/HomeAssistantThingHandler.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/resources/OH-INF/config/homeassistant-channel-config.xml
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/AbstractHomeAssistantTests.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/HaIDTests.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/AbstractComponentTests.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/DeviceTriggerTests.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/handler/HomeAssistantThingHandlerTests.java

Use the `subtype` field to collapse multiple DeviceAutomation components into a single channel. this helps immensefuly if you have a device (an Inovelli switch) with 3 buttons (turn on, turn off, config) with 7 events each (hold, release, 1-5x taps)
This involves special casing the "colliding component name" code to merge the components together, rather than renaming them. Then we also have to persist the configuration JSON for each component into a single channel, and support restoring that when initializing the Thing handler.
I wrote new tests for restoring a Thing handler with persisted JSON, which also found an issue in HaID that was calculating topics wrong, causing channels to _all_ disappear on restore, and requiring waiting for new discovery messages to come in to restore the …

[mqtt.homeassistant] Use a single channel for all events from a single button

---

bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Climate.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/DefaultSchemaLight.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Fan.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/JSONSchemaLight.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Light.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/TemplateSchemaLight.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Update.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Vacuum.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/ClimateTests.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/DefaultSchemaLightTests.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/JSONSchemaLightTests.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/TemplateSchemaLightTests.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/VacuumTests.java

but only for newStyleChannels, which is already a breaking change of most channels getting renamed for 4.3 anyway

[mqtt.homeassistant] bring channel ids inline with coding standards

---

bundles/org.openhab.persistence.jdbc/README.md
bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcBaseDAO.java
bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcDerbyDAO.java
bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcH2DAO.java
bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcHsqldbDAO.java
bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcOracleDAO.java
bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcPostgresqlDAO.java
bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcSqliteDAO.java
bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcTimescaledbDAO.java

This eliminates duplicated queries for PostgreSQL and fixes some regressions as well.
Additionally make Derby queries consistent by always explicitly uppercasing the table names. These queries had it done already:
- **sqlCreateItemsTableIfNot**:
```sql
CREATE TABLE #itemsManageTable# ( ItemId INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), #colname# #coltype# NOT NULL)
```
- **sqlCreateNewEntryInItemsTable**:
```sql
INSERT INTO #itemsManageTable# (ItemName) VALUES ('#itemname#')
```
- **sqlCreateItemsTableIfNot**:
```sql
CREATE TABLE IF NOT EXISTS #itemsManageTable# (ItemId INT NOT NULL AUTO_INCREMENT,#colname# #coltype# NOT NULL,PRIMARY KEY (ItemId))
```
- **sqlInsertItemValue**:
```sql
INSERT INTO #tableName# (TIME, VALUE) VALUES( #tablePrimaryValue#, CAST( …
```

[jdbc] Fix case-sensitive table names for PostgreSQL

---

bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/BinarySensor.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Camera.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Fan.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Sensor.java

also fix the conditional for JSON attributes on other components, and make the channel read only.

[mqtt.homeassistant] JSON Attributes can exist on BinarySensor

---

bundles/org.openhab.binding.ipcamera/README.md
bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/Ffmpeg.java
bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/handler/IpCameraHandler.java
bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/onvif/OnvifConnection.java
bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/servlet/CameraServlet.java
bundles/org.openhab.binding.ipcamera/src/main/resources/OH-INF/thing/thing-types.xml

Adds support to use a lower resolution RTSP feed as the mjpeg source which will lower CPU load on the openHAB server. Previously if you used a lower res feed, then any recordings made would use the lower res stream as well as the mjpeg feed.

[ipcamera] Add support to change MJPEG source to a different RTSP sub stream to lower CPU usage

---

bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/DebuggingGraalScriptEngine.java
bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/OpenhabGraalJSScriptEngine.java
bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/threading/ThreadsafeTimers.java

This fixes illegal multi-thread access requests to the GraalJS context for UI-based rules.
Those have two causes:
1. The execution of pre-compiled scripts (refs https://github.com/openhab/openhab-core/pull/4289) is not synchronized for JS Scripting.
2. If the script is currently executed and a timer is already waiting to acquire the lock, illegal multi-thread access is requested even though the locking mechanism is in place. I cannot really explain that behaviour, but it seems to be a timing issue in the milliseconds range ... When adding logging, the logger tells me that the timer acquires the lock before its released by the script execution. And when attaching a debugger to verify the correct functionality of the locking mechanism, the issue is gone, which IMO again speaks for a timing …

[jsscripting] Fix multi-threading issues in UI-based scripts

---

bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/AlarmControlPanel.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/AlarmControlPanelDeprecatedTests.java

* state values aren't configurable
* there are several more arming types. instead of using a channel for each, use a single channel for both states and commands, with separate state and command descriptions (as first used in the Lock component)
* use the (new?) supported_features config option to limit the list of available states and commands
as usual, removal of old channels is dependent on newStyleChannels flag

[mqtt.homeassistant] bring AlarmControlPanel in line with current documentation

---

bundles/org.openhab.persistence.dynamodb/src/main/java/org/openhab/persistence/dynamodb/internal/AbstractDynamoDBItem.java
bundles/org.openhab.persistence.dynamodb/src/main/java/org/openhab/persistence/dynamodb/internal/DynamoDBHistoricItem.java
bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/InfluxDBPersistenceService.java
bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/InfluxDBHistoricItem.java
bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcBaseDAO.java
bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcOracleDAO.java
bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/dto/JdbcHistoricItem.java
bundles/org.openhab.persistence.jpa/src/main/java/org/openhab/persistence/jpa/internal/JpaHistoricItem.java
bundles/org.openhab.persistence.jpa/src/main/java/org/openhab/persistence/jpa/internal/model/JpaPersistentItem.java
bundles/org.openhab.persistence.mapdb/src/main/java/org/openhab/persistence/mapdb/internal/MapDbItem.java
bundles/org.openhab.persistence.mongodb/src/main/java/org/openhab/persistence/mongodb/internal/MongoDBItem.java
bundles/org.openhab.persistence.mongodb/src/main/java/org/openhab/persistence/mongodb/internal/MongoDBPersistenceService.java
bundles/org.openhab.persistence.mongodb/src/test/java/org/openhab/persistence/mongodb/internal/MongoDBPersistenceServiceTest.java
bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jItem.java
bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java

This PR does implement the new `HistoricItem.getInstant` method from PR https://github.com/openhab/openhab-core/pull/4384 for persistence implementations.

[persistence] Implement HistoricItem.getInstant

---

bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/CameraCapability.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/Capability.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/HomeCapability.java

Lazy reading of thing in Capability.
I had a hard time identifying this one. Apparently it's a bad option to store `thing` in the `Capability` - the framework may change it afterward (it's the only explanation I found).
I did not dig further as it solves the issue but it could also be a reason for some ghost scheduled job.
Resolves #17600

[netatmo] Home properties are not persisted

---

bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/handler/IpCameraHandler.java

Fixes an issue where the binding does not fetch a new token anymore after the camera disconnects or reboots.

[ipcamera] Fix Reolink will not update a new token after a disconnect.

---

bundles/org.openhab.binding.mqtt.homeassistant/README.md
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/AbstractComponent.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/BinarySensor.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Camera.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Climate.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Cover.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Event.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Fan.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Lock.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Number.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Scene.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Select.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Sensor.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Switch.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Update.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Vacuum.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/config/dto/AbstractChannelConfiguration.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/FanTests.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/HAConfigurationTests.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/SwitchTests.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/handler/HomeAssistantThingHandlerTests.java

Also moves JSON attributes channel to AbstractComponent, since _every_ component supports it now (so this commit adds it to the final few components that didn't have it).
And renames the switch channel on a fan to `switch` instead of `fan`, matching how `light` works. Only for newStyleChannels.

[mqtt.homeassistant] document which channels a component might have

---

bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/OpenhabGraalJSScriptEngine.java

Follow-up for #1710.
Depends on https://github.com/openhab/openhab-core/pull/4426.

[jsscripting] Remove workaround for multi-threading issues with UI-based scripts

---

bundles/org.openhab.binding.evcc/src/main/java/org/openhab/binding/evcc/internal/EvccHandler.java
bundles/org.openhab.binding.evcc/src/main/java/org/openhab/binding/evcc/internal/EvccHandlerFactory.java
bundles/org.openhab.binding.evcc/src/main/java/org/openhab/binding/evcc/internal/api/EvccAPI.java

Fixes #17620.
this change fixes the Charge Plan Time not showing correctly on EVCC.
jar file with fix: [EVCC jar](https://exalttechnologies-my.sharepoint.com/:u:/g/personal/laith_budairi_exalt_ps/ET4yBYTUvMZDrC6e9EjVt6cBsuFck36aFxNOQxwbKt_mkw?e=DFOxff)
Signed-off-by: Laith Budairi <laith38@yahoo.com>

[evcc] Charge plan time is not converted to correct timezone

---

bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/CameraConfig.java
bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/ReolinkHandler.java
bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/ReolinkState.java
bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/handler/IpCameraHandler.java

These changes allow multiple brands to now update the controls in openHAB by asking the camera the state of the controls. Users can REFRESH at any time using the REFRESH command. This used to work in an earlier version of openHAB as the framework was auto sending the refresh commands.

[ipcamera] Update openhab controls by asking camera for states.

---

bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/handler/ZonePlayerHandler.java

Partial fix for: https://github.com/openhab/openhab-addons/issues/17646
As the Thing handler state is allready set, there is no need to also log it to the `info` level.

[sonos] Reduce log level

---

bundles/org.openhab.binding.cm11a/README.md
bundles/org.openhab.binding.hccrubbishcollection/README.md
bundles/org.openhab.binding.homematic/README.md
bundles/org.openhab.binding.hpprinter/README.md
bundles/org.openhab.binding.hydrawise/README.md
bundles/org.openhab.binding.nuki/README.md
bundles/org.openhab.binding.prowl/README.md
bundles/org.openhab.binding.pulseaudio/README.md
bundles/org.openhab.binding.samsungtv/README.md
bundles/org.openhab.binding.solaredge/README.md
bundles/org.openhab.binding.webexteams/README.md

As part of the large documentation cleanup, some regressions occured. double spaces are interpreted as linebreaks. Some where fixed in #17619. This PR fixes the remaining ones.

Multiple line break fixes in documentation

---

bundles/org.openhab.transform.vat/README.md
bundles/org.openhab.transform.vat/src/main/java/org/openhab/transform/vat/internal/RateProvider.java
bundles/org.openhab.transform.vat/src/main/java/org/openhab/transform/vat/internal/VATTransformationService.java
bundles/org.openhab.transform.vat/src/main/java/org/openhab/transform/vat/internal/model/VATCountry.java
bundles/org.openhab.transform.vat/src/main/java/org/openhab/transform/vat/internal/model/VATPeriod.java
bundles/org.openhab.transform.vat/src/main/java/org/openhab/transform/vat/internal/profile/VATTransformationProfile.java
bundles/org.openhab.transform.vat/src/main/java/org/openhab/transform/vat/internal/profile/VATTransformationProfileFactory.java
bundles/org.openhab.transform.vat/src/main/resources/vat_rates.yaml
bundles/org.openhab.transform.vat/src/test/java/org/openhab/transform/vat/internal/RateProviderTest.java

VAT rates are now read from a YAML resource rather than a simple `Map` of countries. The format now also allows defining multiple validity periods for VAT rates in a given country, making it possible to prepare future changes so that they come into effect when they should.
Included rate changes:
- Uruguay now has correct rate; it was previously missing.
- Israel has a new rate with effect January 1st 2025.
- Indonesia has a new rate with effect January 1st 2025. Time-zone with 60% of the population selected (see below).
There is a small remaining issue for countries having multiple time-zones. I don't know if the change will come into effect at local midnight in each of the time-zones, but this is anyhow not supported. I thought about using local dates and applying openHAB's configured …

[transform.vat] Add support for VAT rate periodization

---

bundles/org.openhab.binding.visualcrossing/src/main/java/org/openhab/binding/visualcrossing/internal/WeatherCrossingActions.java

Related to #17504
Also fix the return of corresponding static methods

[visualcrossing] Add missing @ActionOutput annotation

---

bundles/org.openhab.binding.entsoe/src/main/java/org/openhab/binding/entsoe/internal/EntsoeHandler.java
bundles/org.openhab.binding.entsoe/src/main/java/org/openhab/binding/entsoe/internal/EntsoeHandlerFactory.java
bundles/org.openhab.binding.entsoe/src/main/java/org/openhab/binding/entsoe/internal/client/Client.java
bundles/org.openhab.binding.entsoe/src/main/java/org/openhab/binding/entsoe/internal/client/EntsoeRequest.java

The primary objective of this pull request is to improve handling of HTTP error code 401 ("Unauthorized") by eliminating exception message string comparison - see https://github.com/openhab/openhab-addons/pull/17416#discussion_r1759837495.
Additionally, we will now provide "openHAB" with version number in the `User-Agent` header. This will make it possible to reach out to us in case of any issues.
And last, but not least, `InterruptedException` will no longer be swallowed by `HttpUtil` and rethrown as `IOException`. This allows us rethrow `InterruptedException` all the way up the call chain. This will ensure that the thread interruption request is respected immediately, rather than masking the exception by catching it prematurely.

[entsoe] Refactor HTTP error handling

---

bundles/org.openhab.binding.fmiweather/src/main/java/org/openhab/binding/fmiweather/internal/AbstractWeatherHandler.java
bundles/org.openhab.binding.fmiweather/src/main/java/org/openhab/binding/fmiweather/internal/ForecastWeatherHandler.java
bundles/org.openhab.binding.fmiweather/src/main/java/org/openhab/binding/fmiweather/internal/HandlerFactory.java
bundles/org.openhab.binding.fmiweather/src/main/java/org/openhab/binding/fmiweather/internal/ObservationWeatherHandler.java
bundles/org.openhab.binding.fmiweather/src/main/java/org/openhab/binding/fmiweather/internal/client/Client.java
bundles/org.openhab.binding.fmiweather/src/main/java/org/openhab/binding/fmiweather/internal/client/FMIRequest.java
bundles/org.openhab.binding.fmiweather/src/main/java/org/openhab/binding/fmiweather/internal/client/ForecastRequest.java
bundles/org.openhab.binding.fmiweather/src/main/java/org/openhab/binding/fmiweather/internal/client/ObservationRequest.java
bundles/org.openhab.binding.fmiweather/src/main/java/org/openhab/binding/fmiweather/internal/discovery/FMIWeatherDiscoveryService.java
bundles/org.openhab.binding.fmiweather/src/test/java/org/openhab/binding/fmiweather/internal/AbstractFMIResponseParsingTest.java

Fixes #17668
Refactoring similar to #17616

[fmiweather] Fix discovery exception

---

bundles/org.openhab.binding.freeathome/README.md
bundles/org.openhab.binding.lgtvserial/README.md
bundles/org.openhab.binding.paradoxalarm/README.md
bundles/org.openhab.binding.pentair/README.md
bundles/org.openhab.binding.velux/README.md

I found some irregularities in the [list of addons](https://www.openhab.org/addons/), for example:
The only thing I could find within these bindings being different from other bindings was the first heading in the README not ending in "Binding" (case sensitive):
```bash
$ find ./bundles/org.openhab.binding.* -maxdepth 1 -type f -name "README.md" -exec sh -c 'head -n 1 "$1" | grep -P -qv "Binding\r?$" && echo "$1"' _ {} \;
./bundles/org.openhab.binding.bluetooth.airthings/README.md
./bundles/org.openhab.binding.bluetooth.am43/README.md
./bundles/org.openhab.binding.bluetooth.bluegiga/README.md
./bundles/org.openhab.binding.bluetooth.bluez/README.md
./bundles/org.openhab.binding.bluetooth.blukii/README.md
./bundles/org.openhab.binding.bluetooth.daikinmadoka/README.md …
```

Fix binding name in first README lines

---

bundles/org.openhab.transform.jsonpath/README.md

[org.openhab.transform.jsonpath] Replace a dead link
Replace dead link https://jsonpath.herokuapp.com/ with https://jsonpath.fly.dev/

[org.openhab.transform.jsonpath] Fix dead link

---

bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiClient.java
bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiJsonDTO.java
bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyBaseHandler.java
bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/util/ShellyUtils.java

[shelly] Fix timeDuration handling in DTOs

---

bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/addon/addon.xml

My PM Mini is discovered as name starting with "shelly" (lowercase):
Making the matching case-insensitive is consistent with the logic in code:
https://github.com/openhab/openhab-addons/blob/18862d3e28d1061b1daca5a54f547236bbf7df10/bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/discovery/ShellyDiscoveryParticipant.java#L95-L99
Regression of #15817

[shelly] Fix suggestion finder

---

bundles/org.openhab.binding.siemensrds/src/main/java/org/openhab/binding/siemensrds/internal/RdsHandler.java

[siemensrds] Fix setting of target temperature

---

bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/utils/NetworkUtils.java

The network binding has functionality that assumes, by default, that a device is an iOS device, and should be woken up by sending a packet to port 5353 (mDNS). The code sends a packet with an empty UDP payload, which is not a valid mDNS packet. 
If the device is not an iOS device, but is instead a Windows device running the Apple Bonjour Service, the Bonjour Service will add an entry to the application event log for each "malformed" packet received. While this feature can now be disabled (since #16259 was merged), I believe it would be a simple (and non-breaking) change to send a 12-byte packet of zeroes instead. This *is* a valid mDNS packet (representing a query with 0 questions and 0 answers) so doesn't trigger the error logging in Bonjour for Windows.
There is also a possibility that …

[network] Modify iOS port knock to use a valid mDNS packet

---

bundles/org.openhab.binding.ecovacs/src/main/java/org/openhab/binding/ecovacs/internal/api/impl/dto/response/portal/AbstractPortalIotCommandResponse.java
bundles/org.openhab.binding.ecovacs/src/main/java/org/openhab/binding/ecovacs/internal/api/impl/dto/response/portal/PortalIotCommandJsonResponse.java
bundles/org.openhab.binding.ecovacs/src/main/java/org/openhab/binding/ecovacs/internal/api/impl/dto/response/portal/PortalIotCommandXmlResponse.java

At least the Deebot 900 sends an unusual error response in case of expired token.
Fixes #15961

[ecovacs] Fix expired token handling for XML-over-MQTT models

---

bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/internal/Ism8Handler.java
bundles/org.openhab.binding.ism8/src/test/java/org/openhab/binding/ism8/internal/util/Ism8DomainMapTest.java

When ISM8 add-on is set to DEBUG logging, the output is currently as follows:
```
[DEBUG] [g.openhab.binding.ism8.server.Server] - CHA Heizleistung 8300.00
[DEBUG] [ab.binding.ism8.internal.Ism8Handler] - Ism8: dataPointChanged DataPoint 178=8300.00
[DEBUG] [ab.binding.ism8.internal.Ism8Handler] - Ism8 channel: ism8:device:wolf:DpId053 and DataPoint do not have a matching Id: 53 vs 178
[DEBUG] [ab.binding.ism8.internal.Ism8Handler] - Ism8 channel: ism8:device:wolf:DpId054 and DataPoint do not have a matching Id: 54 vs 178
[DEBUG] [ab.binding.ism8.internal.Ism8Handler] - Ism8 channel: ism8:device:wolf:DpId194 and DataPoint do not have a matching Id: 194 vs 178
[DEBUG] [ab.binding.ism8.internal.Ism8Handler] - Ism8 channel: ism8:device:wolf:DpId056 and DataPoint do not have a matching Id: 56 …
```

[ism8] Improve debug logging

---

bundles/org.openhab.binding.netatmo/README.md
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/data/ModuleType.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/CommonInterface.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/DeviceHandler.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/ModuleHandler.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/CameraCapability.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/Capability.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/PersonCapability.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/servlet/WebhookServlet.java

Resolves issue #17660 
Being the first opening this issue, I guess this feature is not that much used :-)

[netatmo] Webhook events are dispatched but group id is missing

---

bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/handler/SamsungTvHandler.java

Bugfix for #17542
On some TV's, sending ON to turn the TV on, would result in the TV immediately turning OFF a few seconds later.
This was caused by the POJO which is used for decoding the json from the TV being changed to camelCase (don't know when this happened). Some of the json values are in UpperCamelCase though, so were not being decoded, specifically OS and PowerState.
This bug fix changes the POJO back to match the received json, and should resolve a number of similar issues.

[samsungtv] Fix for incorrect PowerState

---

bundles/org.openhab.binding.linky/README.md
bundles/org.openhab.binding.linky/pom.xml
bundles/org.openhab.binding.linky/src/main/feature/feature.xml
bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/LinkyException.java
bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/LinkyHandlerFactory.java
bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/api/EnedisHttpApi.java
bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/dto/PrmDetail.java
bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/dto/PrmInfo.java
bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/handler/LinkyHandler.java
bundles/org.openhab.binding.linky/src/main/resources/OH-INF/thing/thing-types.xml

[linky] Yet another website underlaying API modification

---

bundles/org.openhab.binding.nanoleaf/README.md
bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/discovery/NanoleafMDNSDiscoveryParticipant.java

The nanoleaf binding becomes very unstable when run in an ipv6 environment (though ipv6 is required when using matter). This simple change ignores the (additional) ipv6 announcement of the nanoleaf controller which fixes online/offline flapping of the nanoleaf thing.
Also see https://community.openhab.org/t/nanoleaf-binding-may-fail-when-upgrading-to-the-latest-nanoleaf-firmware-because-of-ipv6/148152

[nanoleaf] Suppress ipv6 addr in controller discovery

---

bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/discovery/LeapDeviceDiscoveryService.java

Added discovery of  DivaSmartDimmer and PaddleSwitchPico device types and mapped to creation of appropriate device.
Also, added the deviceId to the "Unrecognized" device log so that users can manually add new devices in the future.

[lutron] Added device discovery for DivaSmartDimmer and PaddleSwitchPico

---

bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/AbstractKNXClient.java
bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/console/KNXCommandExtension.java
bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/KNXBridgeBaseThingHandler.java

* Show encrypted frames without a matching key using console command "openhab:knx list-unknown-ga"; sort output numerically by GA.
* Add trace logging to show decryption error due to missing key. Previously, those frames were silently dropped unless logging for Calimero was explicitly enabled as well.

[knx] Improve handling of unknown encrypted frames

---

bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/handler/AwattarBestPriceHandler.java
bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/handler/AwattarBridgeHandler.java
bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/handler/TimeRange.java
bundles/org.openhab.binding.awattar/src/test/java/org/openhab/binding/awattar/internal/handler/AwattarBridgeHandlerTest.java

Resolves #17316
Regression of #16871

[awattar] Fix last hour not being considered for best price

---

bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/discovery/MercedesMeDiscoveryService.java
bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/handler/AccountHandler.java

Bugfix: Discovered things are not working immediately because `vin` configuration was missing. Added vin now as representation property.

[mercedesme] Add vin automatically to discovered vehicle

---

bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/handler/SmartHomeDeviceHandler.java

Just a small typo I noticed while using the binding
```
20:46:29 (14. 11.)    Thing 'amazonechocontrol:smartHomeDeviceGroup:Amazon_System_Konto:Multimedia_Kueche_Echo_Geraet' changed from OFFLINE: Can't find smarthomeBaseDevice! to OFFLINE: Can't find smarthomeBaseDevice
20:46:37 (14. 11.)    Thing 'amazonechocontrol:smartHomeDeviceGroup:Amazon_System_Konto:Multimedia_Kueche_Echo_Geraet' changed from OFFLINE: Can't find smarthomeBaseDevice to OFFLINE: Can't find smarthomeBaseDevice!
```

[AmazonEchoControl] Unifiy error messages

---

bundles/org.openhab.binding.ipobserver/src/main/java/org/openhab/binding/ipobserver/internal/IpObserverBindingConstants.java
bundles/org.openhab.binding.ipobserver/src/main/java/org/openhab/binding/ipobserver/internal/IpObserverHandler.java
bundles/org.openhab.binding.ipobserver/src/main/resources/OH-INF/i18n/ipobserver.properties
bundles/org.openhab.binding.ipobserver/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.ipobserver/src/main/resources/OH-INF/update/instructions.xml

Fixes: #17658
- Add channel rainTotal

[ipobserver] Add channel rainTotal

---

bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/PlugwiseHAController.java
bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/PlugwiseHAControllerRequest.java
bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/converter/DateTimeConverter.java
bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/ActuatorFunctionalityThermostat.java
bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/DomainObjects.java
bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/Log.java
bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/Module.java
bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/Service.java
bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/discovery/PlugwiseHADiscoveryService.java
bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/handler/PlugwiseHAApplianceHandler.java
bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/handler/PlugwiseHAZoneHandler.java
bundles/org.openhab.binding.plugwiseha/src/main/resources/OH-INF/config/config.xml

This PR mainly improves the handling of the connection to the Adam device, but also has other improvements:
- Whenever a timeout occurs, a 3 second delay is added to give the device some time to catch up.
- Improved locking to prevent multiple parallel calls to the device
- When a zone temperature set command is performed it now also accepts a DecimalType.
- Various minor fixes like javadoc, method modifiers and others.
- Solve compile warnings
- Adjust refresh interval to match both config and readme

[plugwiseha] Improve connection stability

---

bundles/org.openhab.binding.dbquery/src/test/java/org/openhab/binding/dbquery/internal/Value2StateConverterTest.java
bundles/org.openhab.binding.fineoffsetweatherstation/src/test/java/org/openhab/binding/fineoffsetweatherstation/internal/service/FineOffsetDataParserTest.java
bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/dpt/DPTTest.java
bundles/org.openhab.binding.mybmw/src/test/java/org/openhab/binding/mybmw/internal/dto/vehicle/VehicleStateContainerTest.java

This refactors a few tests that assume the time-zone being put into a `DateTimeType` will be the same as returned from `getZonedDateTime()` or used by `format()`. Also fixes a few tests mixing UTC and system time-zone.
These assumptions are still valid now, but if openhab/openhab-core#3583 is merged, they no longer will be. Therefore, this PR needs to be merged at latest at the same time to not break the build, but **can be merged already now**. Verifying these assumptions in addon tests provide no real value - this belongs to the core tests related to `DateTimeType`.
Prerequisite for openhab/openhab-core#3583
Also related to #17725 which simplifies `DateTimeType` logic if openhab/openhab-core#3583 is merged

Fix `DateTimeType` tests

---

bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/api/EnedisHttpApi.java

Correction of the url.
Resolves #17773

[linky] Thing goes OFFLINE once again

---

bundles/org.openhab.binding.solarman/src/test/java/org/openhab/binding/solarman/internal/DefinitionParserTest.java

This test failed on my local Windows system due to having a space in my path.
`url.getPath()` here:
https://github.com/openhab/openhab-addons/blob/12d3babc17f0ab83bbc82562543efc90ea0184e5/bundles/org.openhab.binding.solarman/src/test/java/org/openhab/binding/solarman/internal/DefinitionParserTest.java#L103
returns "/C:/Users/Jacob%20Laursen/Development/jlaur/openhab-addons/bundles/org.openhab.binding.solarman/target/classes/definitions" on my system.
`java.io.File` doesn't understand this encoding.
Did some minor additional refactoring as well.

[solarman] Fix missing URL decoding in test

---

bundles/org.openhab.binding.dbquery/src/main/java/org/openhab/binding/dbquery/action/DBQueryActions.java

Related to #17504
Edit: Also fixes support for old DSL-rules

[dbquery] Fix thing action annotation

---

bundles/org.openhab.binding.verisure/src/main/java/org/openhab/binding/verisure/internal/VerisureBindingConstants.java
bundles/org.openhab.binding.verisure/src/main/java/org/openhab/binding/verisure/internal/VerisureHandlerFactory.java
bundles/org.openhab.binding.verisure/src/main/java/org/openhab/binding/verisure/internal/VerisureSession.java
bundles/org.openhab.binding.verisure/src/main/java/org/openhab/binding/verisure/internal/handler/VerisureSmartLockThingHandler.java

Fix for Verisure bridge cannot login ([#17730](https://github.com/openhab/openhab-addons/issues/17730)).
Re-wrote logic for login and handling of tokens.

[verisure] Fix broken cloud authentication

---

bundles/org.openhab.binding.knx/README.md

[knx] Readme: Troubleshooting, Logger, kBerry

---

bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/AbstractComponent.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/handler/HomeAssistantThingHandlerTests.java

unique_id is only unique per component type. so we need to a) take that into account, and b) use that when resolving duplicates

[mqtt.homeassistant] Fix duplicate component resolution when unique_id is set

---

bundles/org.openhab.binding.irobot/README.md
bundles/org.openhab.binding.zway/src/main/java/org/openhab/binding/zway/internal/discovery/ZWayBridgeDiscoveryService.java

Fixes: https://github.com/openhab/openhab-addons/issues/10388

[irobot] Update documentation regarding button names

---

bundles/org.openhab.binding.metofficedatahub/README.md

A very minor readme adjustment I missed, when sorting out the formatting, and a few unit ref's.
This clarifies the specific variant of the "Site Specific" API, a key should be obtained for.
References to the older version of the API that had 2 parameters client id and secret have been removed, and replaced by API key for the newer version of the API that this is was updated and merged against.

[metOfficeDataHub] Readme adjustment for accuracy

---

bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/AwattarConsecutiveBestPriceResult.java
bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/AwattarNonConsecutiveBestPriceResult.java
bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/handler/AwattarBestPriceHandler.java
bundles/org.openhab.binding.awattar/src/test/java/org/openhab/binding/awattar/internal/AwattarBestPriceTest.java
bundles/org.openhab.binding.awattar/src/test/java/org/openhab/binding/awattar/internal/api/AwattarApiTest.java

This PR moves the calculation logic into the corresponding classes and adds tests.

[aWATTar] move calculation logic into best price classes

---

bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/action/ActivePlayerActions.java
bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/action/CallActions.java
bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/action/FreeplugActions.java
bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/action/HostActions.java
bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/action/PlayerActions.java
bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/action/RepeaterActions.java
bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/action/ServerActions.java
bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/i18n/freeboxos.properties

[freeboxos] Internationalize thing actions

---

bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/internal/Ism8Handler.java
bundles/org.openhab.binding.ism8/src/main/resources/OH-INF/thing/thing-types.xml

ISM8 binding defines a few read-only channel types, e.g. `switch-r`.
With this PR, commands from sitemap elements will not be sent to ISM8 when read-only channel types are used.
Auto-update policy is set to veto to prevent state change.
One missing readonly attribute added (mode-r).

[ism8] Prevent sending for read-only channel types

---

bundles/org.openhab.binding.ism8/README.md
bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/internal/util/Ism8DomainMap.java
bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/server/DataPointBool.java
bundles/org.openhab.binding.ism8/src/test/java/org/openhab/binding/ism8/internal/Ism8HandlerTest.java
bundles/org.openhab.binding.ism8/src/test/java/org/openhab/binding/ism8/internal/util/Ism8DomainMapTest.java

switch-r elements are typically mapped to Switch items.
With this PR, you can also map them to Contact items.
This is better suited for the read-only elements.
Additionally, I added the warning statement about DPT 1.009 to the README. (It is the same as for KNX, DPT1.009 should have been inverted. Implementing it correctly will break existing installations.)
Without this PR, Contact items are not compatible and will not be updated.
I am not sure about the approach (using DecimalType 0 and 1 instead of enum identifiers from OnOffType).
Further testing is recommended. I did a short developer test, Contact and Switch items are now being filled correctly when data arrives.

[ism8] Allow linking switch-r to Contact items

---

bundles/org.openhab.automation.jrubyscripting/pom.xml

https://www.jruby.org/2024/11/04/jruby-9-4-9-0.html
There are no major changes, just bug fixes. Notable fix include:
> REXML was updated to 3.3.9 to get recent fixes and to address [CVE-2024-49761](https://github.com/advisories/GHSA-2rxp-v6pw-ch6m), a ReDOS vulnerability. Only users parsing unsanitized XML with REXML are affected. [#8396](https://github.com/jruby/jruby/pull/8396)
This version passed the helper library's ci: https://github.com/openhab/openhab-jruby/pull/363

[jrubyscripting] Upgrade to JRuby 9.4.9.0

---

bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/handler/AccountHandler.java
bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/handler/VehicleHandler.java
bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/server/MBWebsocket.java
bundles/org.openhab.binding.mercedesme/src/test/java/org/openhab/binding/mercedesme/internal/handler/ThingCallbackListener.java
bundles/org.openhab.binding.mercedesme/src/test/java/org/openhab/binding/mercedesme/internal/handler/VehicleHandlerTest.java

Warnings from MercedesMe websocket reported in [community](https://community.openhab.org/t/mercedes-me/136866/12), After analysis design flaw in current binding needs to solved:
Websocket thread is performing the complete chain from reading bytestream up to channel updates. While this other messages  are dismissed 
Structural change to free websocket thread as early as possible:
1. Websocket thread responsible for reading stream in bytes and enqueue for AccountHandler.
2. AccountHamdler thread responsible for encoding proto message. In case of update enqueue proto message at VehicleHandöer
4. VehicleHandler responsible to update channels

[mercedesme] Websocket decoupling

---

bundles/org.openhab.binding.easee/src/main/resources/OH-INF/thing/easee-readonly-channel-types.xml
bundles/org.openhab.binding.ecovacs/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/thing/channel-types.xml
bundles/org.openhab.binding.hdpowerview/src/main/resources/OH-INF/thing/channels.xml
bundles/org.openhab.binding.netatmo/src/main/resources/OH-INF/thing/channels.xml
bundles/org.openhab.binding.tplinksmarthome/src/main/resources/OH-INF/thing/channels.xml
bundles/org.openhab.binding.unifi/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.wlanthermo/src/main/resources/OH-INF/thing/channel-types.xml

Based on this search:
```bash
grep -R "<item-type>Number:Power</item-type>" -B 1 | grep -i rssi | sort
```
Without this hint, **W** will be defaulted as unit.

Provide unit hints for RSSI channel types

---

bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/PercentageValue.java
bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/ValueFactory.java
bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/ChannelStateTests.java
bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/values/ValueTests.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Fan.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Light.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/TemplateSchemaLight.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Vacuum.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Valve.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/FanTests.java
bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/internal/homie300/Property.java

The original implementation for a fan with speeds was written without an actual device, and just guessing from Home Assistant's limited documentation. Now I actually have a 3-speed fan, and I can see how it's expecting to behave. In short, "percentage" is actually "speed", and it just defaults to a range of 0-100, but if it advertises as say 0-3, it actually wants 0-3, not 0, 33, 66, and 100.
* fix step math so that the state description represents the step scaled to 0-100%
* introduce a format override to PercentageValue - Home Assistant expects integers in several places. for a true percentage, most devices were accepting a floating point just fine, but if there's a device (like a 3-speed fan) that has a command template that translates the speeds to some other string value, and uses a …

[mqtt.homeassistant] fix multi-speed fans

---

bundles/org.openhab.transform.basicprofiles/README.md
bundles/org.openhab.transform.basicprofiles/src/main/java/org/openhab/transform/basicprofiles/internal/profiles/StateFilterProfile.java
bundles/org.openhab.transform.basicprofiles/src/test/java/org/openhab/transform/basicprofiles/internal/profiles/StateFilterProfileTest.java

- Improve the conditions flexibility so that any type of operand can be on either side of the operator, e.g.: `ItemName > 10` and `10 < ItemName`
- Add support for functions:
- `$DELTA` to represent the absolute difference between the incoming value and the previously accepted value.
- `$AVERAGE`, or `$AVG` to represent the average of the previous incoming values, excluding the incoming value.
- `$MEDIAN` to represent the median value of the previous incoming values.
- `$STDDEV` to represent the _population_ standard deviation of the previous unfiltered incoming values.
- `$MIN` to represent the minimum value of the previous incoming values.
- `$MAX` to represent the maximum value of the previous incoming values.  
By default, 5 samples of the previous values are kept.
This can be …

[basicprofiles] Add support for functions (DELTA, MEDIAN, AVG, STDDEV, MIN, MAX) in State Filter

---

bundles/org.openhab.binding.vesync/src/main/java/org/openhab/binding/vesync/internal/handlers/VeSyncBaseDeviceHandler.java

[vesync] SCA error catches
Apologies - Removal of 2 SCA errors that crept in just prior to the merge, that I missed. I just caught these while I was preparing a branch to look at the other PR against the current main branch.

[vesync] SCA error catches

---

bundles/org.openhab.binding.vesync/README.md
bundles/org.openhab.binding.vesync/src/main/java/org/openhab/binding/vesync/internal/handlers/VeSyncDeviceAirPurifierHandler.java

[vesync] Core 300S Updates
This updates the device profile for the core 300S. This adds the auto mode to the fan modes for its profile. It looks like since the initial ports the modes specified for the device have been updated.
This change adds the auto mode as a valid payload for the protocol to allow for this device.
This relates to OpenHab issue: [#16456] (https://github.com/openhab/openhab-addons/issues/16456).
The changes have been confirmed as working as expected.

[vesync] Core 300S Updates

---

bundles/org.openhab.binding.airgradient/README.md
bundles/org.openhab.binding.airgradient/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.airgradient/src/main/resources/OH-INF/update/update.xml
bundles/org.openhab.binding.bluetooth/README.md
bundles/org.openhab.binding.bluetooth/src/main/resources/OH-INF/thing/channels.xml
bundles/org.openhab.binding.bluetooth/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.bluetooth/src/main/resources/OH-INF/update/update.xml
bundles/org.openhab.binding.draytonwiser/README.md
bundles/org.openhab.binding.draytonwiser/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.draytonwiser/src/main/resources/OH-INF/update/update.xml
bundles/org.openhab.binding.mqtt.ruuvigateway/README.md
bundles/org.openhab.binding.mqtt.ruuvigateway/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.mqtt.ruuvigateway/src/main/resources/OH-INF/update/update.xml
bundles/org.openhab.binding.surepetcare/README.md
bundles/org.openhab.binding.surepetcare/src/main/java/org/openhab/binding/surepetcare/internal/handler/SurePetcareDeviceHandler.java
bundles/org.openhab.binding.surepetcare/src/main/resources/OH-INF/thing/things.xml
bundles/org.openhab.binding.surepetcare/src/main/resources/OH-INF/update/update.xml
itests/org.openhab.binding.mqtt.ruuvigateway.tests/src/main/java/org/openhab/binding/mqtt/ruuvigateway/RuuviGatewayTest.java

As mentioned in #17826 there are some bindings having a received signal strength indication channel -- **_where there is at least a strong suspicion_** -- that the UoM unit is `dBm` .. but where the thing type is currently not fully specified to reflect that.
This PR seeks to improve the thing type xml specification of those channels, and provide update instructions for existing things.
Clues leading to my suspicion that the unit is `dBm` are as follows:
- bluetooth binding(s): the channel type has a state description pattern `dBm` 
- airgradient binding: the channel type has a state description pattern `dBm` 
- surepetcare binding: the channel type has a state description pattern `dB`
- mqtt.ruuvitag binding: channel provides a `Units.DECIBEL_MILLIWATTS` QuantityType
- draytonwiser …

Add UoM support for RSSI channels

---

bundles/org.openhab.transform.basicprofiles/README.md
bundles/org.openhab.transform.basicprofiles/src/main/java/org/openhab/transform/basicprofiles/internal/profiles/StateFilterProfile.java
bundles/org.openhab.transform.basicprofiles/src/test/java/org/openhab/transform/basicprofiles/internal/profiles/StateFilterProfileTest.java

Support `$DELTA_PERCENT > 5` or simply `> 5%`

[basicprofiles] Add $DELTA_PERCENT function to State Filter profile

---

bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/DiscoverComponents.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/discovery/HomeAssistantDiscovery.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/handler/HomeAssistantThingHandler.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/discovery/HomeAssistantDiscoveryTests.java
itests/org.openhab.binding.mqtt.homeassistant.tests/src/main/java/org/openhab/binding/mqtt/homeassistant/HomeAssistantMQTTImplementationTest.java

Fixes #17182
This should fix all cases of devices adding and removing components at runtime. For a non-managed thing (i.e. file-based), if the component is removed, we can't change the config, but the corresponding channels should still disappear. For a managed thing, the component will be removed from the config ([by PersistentInbox in core](https://github.com/openhab/openhab-core/blob/4.3.0.M4/bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/internal/PersistentInbox.java#L294) - I didn't realize discovery could "modify" already-created things! but it explains how I didn't have to do anything special for _new_ components to show up on existing things). This also fixes the issue I had sometimes seen, but never understood, where a thing would …

[mqtt.homeassistant] Fix thing consistency for existing things when a device adds or removes components

---

bundles/org.openhab.automation.groovyscripting/src/main/java/org/openhab/automation/groovyscripting/internal/GroovyScriptEngineFactory.java

Fixes the `ClassNotFoundException` when using Thing actions caused by #17383. The `GroovyClassLoader` loads classes by name however the Thing actions classes cannot be loaded by name because they are internal classes.
Fixes #17683
--- 
In the future we could probably also modify the `CustomizableGroovyClassLoader` to return the `Class` instances provided by the `scopeValues` call to prevent class loader issues.

[groovyscripting] Prevent CNFE for scoped classes unavailable to the class loader

---

bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/factory/EnergiDataServiceHandlerFactory.java

`super.activate` should only be called when method is overridden.

[energidataservice] Remove unneeded code

---

bundles/org.openhab.binding.mqtt.homeassistant/pom.xml
bundles/org.openhab.binding.mqtt.homeassistant/src/main/feature/feature.xml
bundles/org.openhab.transform.jinja/pom.xml
bundles/org.openhab.transform.jinja/src/main/feature/feature.xml
features/openhab-addons/src/main/resources/footer.xml
itests/org.openhab.binding.mqtt.homeassistant.tests/itest.bndrun

Which includes support for break/continue, which is what Zigbee2MQTT's new event component uses in their template.

[mqtt.homeassistant] Update Jinjava to 2.7.4

---

itests/org.openhab.binding.ntp.tests/src/main/java/org/openhab/binding/ntp/test/NtpOSGiTest.java

These tests are no longer relevant since `DateTimeType` is now "zone-less". They are currently failing.
Related to openhab/openhab-core#3583

[ntp] Remove obsoleted integration tests

---

bundles/org.openhab.binding.robonect/src/main/java/org/openhab/binding/robonect/internal/handler/RobonectHandler.java
bundles/org.openhab.binding.robonect/src/test/java/org/openhab/binding/robonect/internal/handler/RobonectHandlerTest.java

This fixes a test that fails when being run on a system in another time-zone than CET (i.e. CI builds):
https://github.com/jlaur/openhab-addons/actions/runs/12244010700
The commit has been cherry-picked from #17725
Related to openhab/openhab-core#3583

[robonect] Simplify `DateTimeType` handling

---

bundles/org.openhab.binding.wiz/src/main/java/org/openhab/binding/wiz/internal/handler/WizHandler.java
bundles/org.openhab.binding.wiz/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.wiz/src/main/resources/OH-INF/update/instructions.xml

Number:Power of dBm, instead of Number:Dimensionless of dB.
See discussion in #17826

[wiz] Correct units for RSSI

---

bundles/org.openhab.binding.broadlinkthermostat/README.md
bundles/org.openhab.binding.broadlinkthermostat/pom.xml
bundles/org.openhab.binding.broadlinkthermostat/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.broadlinkthermostat/src/main/resources/OH-INF/i18n/broadlinkthermostat.properties

With the new broadlink binding, we now have two bindings with the same name:
See also https://community.openhab.org/t/broadlink-binding-4-1-0-4-3-0/154734/151

[broadlinkthermostat] Fix binding name

---

itests/itest-common.bndrun
itests/org.openhab.automation.groovyscripting.tests/itest.bndrun
itests/org.openhab.automation.jsscriptingnashorn.tests/itest.bndrun
itests/org.openhab.binding.astro.tests/itest.bndrun
itests/org.openhab.binding.avmfritz.tests/itest.bndrun
itests/org.openhab.binding.feed.tests/itest.bndrun
itests/org.openhab.binding.hue.tests/itest.bndrun
itests/org.openhab.binding.max.tests/itest.bndrun
itests/org.openhab.binding.mielecloud.tests/itest.bndrun
itests/org.openhab.binding.modbus.tests/itest.bndrun
itests/org.openhab.binding.mqtt.homeassistant.tests/itest.bndrun
itests/org.openhab.binding.mqtt.homie.tests/itest.bndrun
itests/org.openhab.binding.mqtt.ruuvigateway.tests/itest.bndrun
itests/org.openhab.binding.ntp.tests/itest.bndrun
itests/org.openhab.binding.systeminfo.tests/itest.bndrun
itests/org.openhab.binding.tradfri.tests/itest.bndrun
itests/org.openhab.binding.wemo.tests/itest.bndrun
itests/org.openhab.persistence.mapdb.tests/itest.bndrun

Related to openhab/openhab-core#4499

Resolve runbundles for reverting LinkedTransferQueue high CPU usage workaround

---

bundles/org.openhab.binding.bondhome/src/main/java/org/openhab/binding/bondhome/internal/api/BondHttpApi.java

Upon upgrading to OH-4.3.0, I am seeing this error at startup or anytime the bond bridge is disabled and re-enabled. The issue appears to be a race condition where the discovery service attempts to start calling request() before bridgeHandler.getBridgeIpAddress() can provide the IP address of the bridge. By catching the IllegalArgumentException , the service will continue and is able to discover devices in subsequent scans.

[bondhome] Catch null host exception in discovery service

---

bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/InsteonLegacyBinding.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/LegacyDevice.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/LegacyPollManager.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/LegacyRequestManager.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/PollManager.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/RequestManager.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/transport/LegacyDriver.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/transport/LegacyPort.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/transport/Port.java

Initially, I was going to revert the change part of #17804 to the `LegacyPort` class as the thread names were already normalized through the `setParamsAndStart` wrapper method (not sure why I wasn't on the reviewer list?).
However, it made more sense to just convert all the legacy threads to use the scheduler service instead, removing unnecessary singleton instances in the process. I did run a successful test in my environment of these changes.

[insteon] Convert legacy threads to use scheduler service

---

bundles/org.openhab.binding.tibber/README.md
bundles/org.openhab.binding.tibber/src/main/java/org/openhab/binding/tibber/internal/handler/TibberPriceConsumptionHandler.java

This PR implements the feature request from issue #17915.  
The Tibber Binding's `today_prices` and `tomorrow_prices` JSON arrays now include the `level` field, which provides price level information (e.g., "EXPENSIVE", "NORMAL", "CHEAP") for each price entry.

[tibber] Add price_level to today_prices and tomorrow_prices

---

bundles/org.openhab.binding.nest/README.md

I found the pub/sub installation instructions didn't work for me as the subscription was missing in my GCP project, and required manually creating. It looks like it's probably a change made by google to their pub/sub approach for google.
I've updated the README.md with the instructions to manually create the pub/sub which is what worked for me.

[nest] Update README pub/sub instructions

---

bundles/org.openhab.binding.roku/README.md
bundles/org.openhab.binding.roku/src/main/java/org/openhab/binding/roku/internal/RokuBindingConstants.java
bundles/org.openhab.binding.roku/src/main/java/org/openhab/binding/roku/internal/RokuLimitedModeException.java
bundles/org.openhab.binding.roku/src/main/java/org/openhab/binding/roku/internal/communication/RokuCommunicator.java
bundles/org.openhab.binding.roku/src/main/java/org/openhab/binding/roku/internal/handler/RokuHandler.java
bundles/org.openhab.binding.roku/src/main/resources/OH-INF/i18n/roku.properties

Very recently Roku has pushed out new firmware that blocks external control commands by default. This PR adds code to detect when the Roku is configured incorrectly and notifies the user via the Thing status description message about how to correct the problem.

[roku] Check for ECP Limited Mode

---

bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/InsteonHandlerFactory.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/InsteonLegacyBinding.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/InsteonModem.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/handler/InsteonBridgeHandler.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/handler/InsteonLegacyNetworkHandler.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/transport/HubIOStream.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/transport/IOStream.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/transport/LegacyDriver.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/transport/LegacyPort.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/transport/Port.java

Use the `HttpClientFactory` shared Jetty HTTP client over `HttpURLConnection` to communicate with an Insteon Hub 2.
I did run a successful test in my environment of this change.

[insteon] Use shared jetty http client

---

bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/AbstractComponent.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/ClimateTests.java

As opposed to null name. In either case, it's not usable, and we need to use our fallbacks.
Fixes #17920

[mqtt.homeassistant] Fix components with an empty name

---

bundles/org.openhab.binding.tado/README.md

Updated the documentation of the tado binding, as the current binding is not compatible to the new tado X devices.
Inserted a swagger link to updated API for the new devices.

[tado.doc] Updated tado binding documentation for tado X

---

bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/util/LifxMessageUtil.java

[lifx] Fix QuantityType command

---

bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/devices/wifi/bulb/TapoBulbHandler.java
bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/devices/wifi/lightstrip/TapoLightStripHandler.java

[tapocontrol] Support QuantityType Color Temperature command

---

bundles/org.openhab.automation.jsscripting/pom.xml
bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/OpenhabGraalJSScriptEngine.java
bundles/org.openhab.automation.jsscripting/src/main/resources/META-INF/services/com.oracle.truffle.api.TruffleLanguage$Provider

Changelog: https://github.com/oracle/graaljs/blob/master/CHANGELOG.md#version-2410
FYI I wondered if we could OSGi-ify org.graalvm.polglot:polyglot and possibly other dependencies and what would be the benefit of this.
This is tested on my dev system running 5.0.0 snapshot.

[jsscripting] Upgrade GraalJS from 22.0.0.2 to 24.1.1

---

bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/JRubyEngineWrapper.java

due to a bug in JRuby https://github.com/jruby/jruby/issues/8346
This affects UI-based rules, which are compiled when the script engine supports it.
Reported in https://community.openhab.org/t/jruby-arrayindexoutofboundsexception-index-1-out-of-bounds-for-length-1/161030
This should be backported to 4.3.x

[jrubyscripting] Remove Compilable implementation

---

bundles/org.openhab.binding.pulseaudio/README.md

Two tables were rendered incorrectly due to missing pipes, see https://www.openhab.org/addons/bindings/pulseaudio/
Further markdownlint fixes.

[pulseaudio] Markdown documentation fixes

---

bundles/org.openhab.binding.pihole/src/main/java/org/openhab/binding/pihole/internal/rest/JettyAdminService.java

The pihole thing action `enableBlocking` currently uses the wrong API endpoint and therefor disables the blocking instead of enabling it.
fixes #17966

[pihole] Fix enableBlocking action

---

bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/handler/NetworkHandler.java

This fix makes it possible to use `restoreOnStartup` for the last-seen channel. When a device is not on the network and openHAB reboots, the last-seen channel is set to `UNDEF`. This renders the use of `restoreOnStartup` useless. 
If `restoreOnStartup` is not used, the channel remains `NULL` after startup. I think that is a fair trade-off compared to being set to `UNDEF`.
Fixes  https://github.com/openhab/openhab-addons/issues/17404

[network] Fix last-seen channel being set to `UNDEF` at startup

---

bundles/org.openhab.binding.upnpcontrol/src/main/java/org/openhab/binding/upnpcontrol/internal/handler/UpnpRendererHandler.java

Artwork was failing to download on my new WiiM pro streamers due to whitespace in the URI.
```
2024-12-23 11:33:55.964 [DEBUG] [internal.handler.UpnpRendererHandler] - Invalid album art URI: http://mediaserver-cont-usc-mp1-1-v4v6.pandora.com/images/
88/0c/ed/6e/d48642d08e076af31fc3dd51/1080W_1080H.jpg
java.lang.IllegalArgumentException: Illegal character in path at index 110: http://mediaserver-cont-usc-mp1-1-v4v6.pandora.com/images/88/0c/ed/6e/d48642d0
8e076af31fc3dd51/1080W_1080H.jpg
at java.net.URI.create(URI.java:906) ~[?:?]
at org.eclipse.jetty.client.HttpClient.newRequest(HttpClient.java:473) ~[?:?]
at org.openhab.core.io.net.http.HttpUtil.executeUrlAndGetReponse(HttpUtil.java:212) ~[?:?]
at org.openhab.core.io.net.http.HttpUtil.downloadData(HttpUtil.java:443) ~[?:?]
at …
```

[upnpcontrol] Fix `IllegalArgumentException` when downloading album art

---

bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/PercentageValue.java
bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/values/ValueTests.java

A dimmer channel used to be able to receive `ON` / `OFF` through MQTT in openHAB 4.2. This broke in 4.3.
Reported here: https://community.openhab.org/t/openhab-4-3-release-discussion/160888/192
This needs to be backported to 4.3.x

[mqtt.generic] Fix ClassCastException when receiving ON/OFF on a dimmer channel

---

bundles/org.openhab.binding.insteon/README.md
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/discovery/InsteonLegacyDiscoveryService.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/handler/InsteonDeviceHandler.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/handler/InsteonLegacyDeviceHandler.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/handler/InsteonLegacyNetworkHandler.java

This change fixes the legacy backward compatibility for thing textual configuration that I overlooked when working on that implementation.
Unfortunately, the framework is preventing things with channel configuration from going through its initialization process due to the original channel type not being available. This requires the user to update their thing configuration file updating the channel types to the new ones. Reverting to the old ones is not possible as some are conflicting with the new ones. 
These include:
* Fixing the missing `broadcastOnOff` channels when migrating textual configuration.
* Restoring all the original channel characteristics including any custom labels, compared to only the channel configuration previously.
* Removing the previously discovered legacy device …

[insteon] Fix legacy backward compatibility

---

bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/protocol/dto/VehicleData.java

Fix NumberFormatException reported here: https://community.openhab.org/t/tesla-binding-exception-occurred-while-parsing-data/161012/5
Test jar should be usable in 4.3.0: https://1drv.ms/u/s!AnMcxmvEeupwj49RabXgS_bRX-8P4Q?e=dVZurL
Should be backported when confirmed as fix.

[tesla] Fix `NumberFormatException`

---

bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/feature/CommandHandler.java

Instead of sending a command to a relevant feature, it sent it back to itself causing the stack overflow. Additionally, the command should be sent regardless of the current state since it may not be up to date at the time the command is received.
This bugfix should be included in 4.3.1.

[insteon] Fix led command stack overflow error

---

bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/feature/CommandHandler.java
bundles/org.openhab.binding.insteon/src/main/resources/OH-INF/config/config.xml
bundles/org.openhab.binding.insteon/src/main/resources/OH-INF/i18n/insteon.properties
bundles/org.openhab.binding.insteon/src/main/resources/OH-INF/thing/channels.xml
bundles/org.openhab.binding.insteon/src/main/resources/device-features.xml

This change adds a channel parameter to set the LED brightness level to use when an ON command is received. It now defaults to 50% in line with [standard behavior](https://www.insteon.com/support-knowledgebase/2016/8/15/change-led-brightness-levels-switchlincs).
This also includes removing `OnOffType` command support for the `on-level` channel since it should only be set to a percent value.

[insteon] Add led brightness on level channel parameter

---

bundles/org.openhab.binding.tellstick/pom.xml

Fixes securrity issue: https://github.com/AsyncHttpClient/async-http-client/security/advisories/GHSA-mfj5-cf8g-g2fv
Supersedes: https://github.com/openhab/openhab-addons/pull/17897

[tellstick] Update async-http-client to version 2.12.4

---

bundles/org.openhab.persistence.jpa/pom.xml

- Upgrade derby from 10.16.1.1 to 10.17.1.0 (requires Java 21)
- Upgrade openjpa from 4.0.0 to 4.0.1
- Upgrade jakarta.el-api from 6.0.0-RC1 to 6.0.1
Derby 10.17.1.0 is **only available for Java 21**.
This release fixes CVE-2022-46337.
Refs:
#15942

[persistence.jpa] Upgrade Apache Derby to 10.17.1.0

---

bundles/org.openhab.voice.pipertts/README.md
bundles/org.openhab.voice.pipertts/pom.xml
bundles/org.openhab.voice.pipertts/src/main/java/org/openhab/voice/pipertts/internal/PiperTTSService.java

The previous version of the library had an issue loading the library files from an external directory on windows, this version fixed it.

[pipertts] Fix library load on windows

---

bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/NetatmoBindingConstants.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/config/ApiHandlerConfiguration.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/config/ConfigurationLevel.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/ApiBridgeHandler.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/AlarmEventCapability.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/CameraCapability.java
bundles/org.openhab.binding.netatmo/src/main/resources/OH-INF/i18n/netatmo.properties

Distinct timing (60 minutes) when API LIMIT REACHED has been issued.
Partially resolves issue #16485

[netatmo] API limit reached handling

---

bundles/org.openhab.binding.pushbullet/src/main/java/org/openhab/binding/pushbullet/internal/handler/PushbulletHandler.java

Replaced deprecated `URL` constructor with `URI` one.

[pushbullet] Replace deprecated URL constructor

---

bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/NumberValue.java
bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/values/ValueTests.java

Fixes https://community.openhab.org/t/openhab-4-3-zigbee2mqtt-color-temperature-in-mired-not-working/160911/8

[mqtt.generic] create the proper item type for channels with units

---

bundles/org.openhab.binding.tellstick/README.md

It's currently not clear from the documentation that a yearly refresh of the access token is required, so I thought I'd contribute with this info

Added note about required yearly manual step

---

bundles/org.openhab.binding.insteon/src/main/resources/device-types.xml

This change fixes a typo in the device types configuration for motion sensor.
This should be back ported since the motion sensor channels `battery-level` and `light-level` don't have any state for in the OH 4.3 release.

[insteon] Fix motion sensor device type config typo

---

bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/handler/AccountHandler.java

Bugfix for initial setup of MercedesMe things mentioned in [community thread](https://community.openhab.org/t/mercedes-me/136866/32).
Looks like Mercedes doesn't send the proto message with `hasAssignedVehicles` anymore which is used for discovery.

[mercedesme] Bugfix discovery and thing properties

---

bundles/org.openhab.transform.basicprofiles/src/main/java/org/openhab/transform/basicprofiles/internal/profiles/StateFilterProfile.java
bundles/org.openhab.transform.basicprofiles/src/test/java/org/openhab/transform/basicprofiles/internal/profiles/StateFilterProfileTest.java

- Fix a bug in delta percent state filter when the input data is negative.
- In State Filter with a delta / delta percent condition, the first/initial data is not passed through to the item even though it is used as the basis to filter subsequent data. This is not the correct behaviour, and the initial data should be passed through to the item.
This should be backported to 4.3

[basicprofiles] Fix delta state filter handling of negative values

---

bundles/org.openhab.binding.xmppclient/src/main/java/org/openhab/binding/xmppclient/internal/action/XMPPActions.java
bundles/org.openhab.binding.xmppclient/src/main/java/org/openhab/binding/xmppclient/internal/client/XMPPClient.java
bundles/org.openhab.binding.xmppclient/src/main/java/org/openhab/binding/xmppclient/internal/handler/XMPPClientConfiguration.java
bundles/org.openhab.binding.xmppclient/src/main/java/org/openhab/binding/xmppclient/internal/handler/XMPPClientHandler.java
bundles/org.openhab.binding.xmppclient/src/main/resources/OH-INF/thing/thing-types.xml

my take on getting group messages to work.
did avoid updating smack (don´t know what that would trigger) and simply added a new function to be called

[xmpp] Add action for sending a group message

---

bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/ValueEncoder.java
bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/dpt/DPTTest.java

This allows other bindings or scripts to send commands which specify the color temperature in mired.

[knx] Allow color temperatures specified in mired

---

bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/action/RoomActions.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/AircareApi.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/RestManager.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/SecurityApi.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/WeatherApi.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/data/NetatmoConstants.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/deserialization/NAPushTypeDeserializer.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/EnergyCapability.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/SecurityCapability.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/providers/NetatmoThingTypeProvider.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/servlet/GrantServlet.java
bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/servlet/WebhookServlet.java

In French, there is a space before a colon, whereas in English, there is not.
This also fixes a few Javadoc issues.
See also #17483 for similar fix in all README's.

[netatmo] Remove space before colon

---

bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/AreaAlarm.java
bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/OmnilinkBindingConstants.java
bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/TemperatureFormat.java
bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/action/OmnilinkActions.java
bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/discovery/OmnilinkDiscoveryService.java
bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/exceptions/BridgeOfflineException.java
bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/AbstractAreaHandler.java
bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/AbstractOmnilinkHandler.java
bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/AbstractOmnilinkStatusHandler.java
bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/AudioSourceHandler.java
bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/ButtonHandler.java
bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/HumiditySensorHandler.java
bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/LockHandler.java
bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/LuminaAreaHandler.java
bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/OmniAreaHandler.java
bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/OmnilinkBridgeHandler.java
bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/TempSensorHandler.java
bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/ThermostatHandler.java
bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/UnitHandler.java
bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/ZoneHandler.java
bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/units/DimmableUnitHandler.java
bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/units/UpbRoomHandler.java
bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/units/dimmable/UpbUnitHandler.java

Just some basic QOL improvements to the OmniLink code, also a few typo fixes as well.

[omnilink] Improve code quality

---

bundles/org.openhab.binding.ahawastecollection/src/main/java/org/openhab/binding/ahawastecollection/internal/CollectionDate.java

Fixes: https://github.com/openhab/openhab-addons/issues/17879
Test jar: https://1drv.ms/u/s!AnMcxmvEeupwj49KMnQ3vzEIZLkpRA?e=pmrC4d (should be 4.3.0 compatible)
Can be backported

[ahawastecollection] Add support for Christmas Tree collection

---

bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/handler/EnOceanBaseSensorHandler.java

Fixes #18032
Regression of #17531
@lovery's original fix [here](https://github.com/openhab/openhab-addons/pull/17531#discussion_r1796912904) was correct. [Hashtable.get](https://docs.oracle.com/en/java/javase/21//docs/api/java.base/java/util/Hashtable.html#get(java.lang.Object)) returns `null` if this map contains no mapping for the key.
Should be backported to `4.3.x`.

[enocean] Fix `NullPointerException`

---

bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/InsteonBindingConstants.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/command/DebugCommand.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/command/InsteonCommand.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/command/ModemCommand.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/command/SceneCommand.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/InsteonDevice.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/InsteonModem.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/database/DatabaseRecord.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/database/LinkDB.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/database/LinkDBReader.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/database/LinkDBWriter.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/database/ModemDB.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/database/ModemDBReader.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/database/ModemDBRecord.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/database/ModemDBWriter.java

This changes adds the ability to backup and restore a modem database via console commands. A console command to initiate a modem reset was added as well.

[insteon] Add modem database backup restore console commands

---

bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/BaseDevice.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/InsteonDevice.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/InsteonModem.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/X10Address.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/feature/MessageDispatcher.java

This change fixes the message handling for x10 device.
This includes 3 bug fixes:
- `X10Address` house code is incorrect when instantiated with a message address byte. This is affecting the legacy implementation as well preventing incoming X10 messages from being processed by the binding.
- `X10Address` failed to instantiate with a string based X10 address including a unit code with more than 1 digit (e.g. `L.15`). This is affecting the legacy implementation which rely on a string based address being parsed, opposed to the new one that has the house and unit configuration already separated.
- X10 messages received by the binding weren't changing their associated feature query status causing a 30 seconds delay for a X10 command to be sent to the device, waiting for the initial X10 address …

[insteon] Fix x10 device message handling

---

pom.xml

* maven-site-plugin to 3.21.0
* maven-plugin-plugin to 3.15.1
I missed those two in #18037.
Now all plugins are up to date (besides openapi-generator, which is blocked by an issue, see https://github.com/openhab/openhab-webui/pull/2975#issue-2768921956)
Beta versions are ignored, mvn command line:
```mvn versions:display-plugin-updates -nsu -Dmaven.version.ignore=".*-beta-.*,.*\.BETA[0-9]+,.*-M[0-9]+" -B -Dversions.outputLineWidth=120```

Upgrade plugins

---

bundles/org.openhab.binding.broadlink/README.md

Documentation improvement to help new users. Clarify some aspects, add context, correct a few spelling mistakes.

[broadlink] Update README

---

bundles/org.openhab.binding.benqprojector/README.md
bundles/org.openhab.binding.benqprojector/src/main/java/org/openhab/binding/benqprojector/internal/BenqProjectorBindingConstants.java
bundles/org.openhab.binding.benqprojector/src/main/java/org/openhab/binding/benqprojector/internal/BenqProjectorDevice.java
bundles/org.openhab.binding.benqprojector/src/main/java/org/openhab/binding/benqprojector/internal/connector/BenqProjectorConnector.java
bundles/org.openhab.binding.benqprojector/src/main/java/org/openhab/binding/benqprojector/internal/connector/BenqProjectorSerialConnector.java
bundles/org.openhab.binding.benqprojector/src/main/java/org/openhab/binding/benqprojector/internal/connector/BenqProjectorTcpConnector.java

Resolves #17996. The current implementation does not work at all with some newer projectors possibly due to an unexpected carriage return in the projector's response. This PR fixes the issue and also an issue where the off command needed to be sent twice to make the projector turn off.
Test build: https://github.com/mlobstein/openhab-addons/releases/download/v4.3.0-snapshot/org.openhab.binding.benqprojector-4.3.0-SNAPSHOT.jar

[benqprojector] Fix response processing for newer projectors

---

bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/InsteonLegacyBinding.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/LegacyDevice.java

This change fixes a bug introduced in the legacy implementation where incoming all link broadcast messages aren't being processed. Previously, the `Msg` class method `isBroadcast` included both broadcast message types (standard and all-link broadcasts). After the rewrite, that method was decoupled only including the standard type, while a new method `isAllLinkBroadcast` was added to check for the other type. For reference, Insteon message requests (outgoing) can only be of direct or all-link broadcast types.
This fix should be back ported as physical button press events aren't processed by the legacy implementation delaying the state update of some of the channels until the next binding poll. I did run a successful test in my environment of this change.

[insteon] Fix legacy all link broadcast message not processed

---

bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/InsteonBindingConstants.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/handler/InsteonSceneHandler.java

This changes fixes a bug where the scene channel state isn't getting updated. This was introduced with the scene channel rename that happened during the [rewrite review process](https://github.com/openhab/openhab-addons/pull/17146#discussion_r1764238746).
This should be back ported since the scene channel state isn't updated currently. I did run a successful test in my environment of this change.

[insteon] Fix scene channel state updates

---

bundles/org.openhab.binding.speedtest/src/main/java/org/openhab/binding/speedtest/internal/SpeedtestHandler.java
bundles/org.openhab.binding.speedtest/src/main/java/org/openhab/binding/speedtest/internal/dto/ResultContainer.java

The issue is mentioned on the forum, but I ran into the same thing: https://community.openhab.org/t/an-exception-occurred-while-running-speedtest-invalid-uri-host-null-authority-null/156906
The root cause is Ookla does not always create a result image. This is visible through a flag(`persisted`) that is also part of the result. At the moment, the whole things goes offline. With this fix, it will just set the image to UnDefType.NULL but still show the other results.
The root cause of the thing going offline is in https://github.com/openhab/openhab-core/blob/f00c7700cb13b4ab6dbc6a8e493f226d8099689c/bundles/org.openhab.core.io.net/src/main/java/org/openhab/core/io/net/http/HttpUtil.java#L212. If the `url` is not a valid `uri` this line will throw a (somewhat hidden) …

[speedtest] Fix speedtest thing going offline when image not available

---

bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/internal/communication/ErroneousResponse.java
bundles/org.openhab.binding.digiplex/src/test/java/org/openhab/binding/digiplex/internal/communication/DigiplexResponseResolverTest.java

This fixes the build.
Caused by #18035 being merged after #18061 because build was not invalidated.

[digiplex] Fix license headers

---

bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/schema/ApiPageParser.java
bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/schema/ChangerX2Parser.java
bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/schema/TACmiSchemaHandler.java

While reviewing a tacmi related PR, i noticed these errors and fixed them right away.
(empty control statements, empty line and naming convention.

[tacmi] Fix SAT errors

---

bundles/org.openhab.binding.insteon/src/main/resources/device-products.xml

This change corrects the first database record location configuration for iMeter Solo products.
This fix should be backported as the database verification for iMeter Solo products is currently failing leaving the thing in pending configuration status.

[insteon] Fix imeter solo product first record location

---

bundles/org.openhab.binding.radiothermostat/src/main/java/org/openhab/binding/radiothermostat/internal/discovery/RadioThermostatDiscoveryService.java

Refactor code in RadioThermostatDiscoveryService to remove deprecated java.net.URL, MulticastSocket.joinGroup() and MulticastSocket.leaveGroup() usage.

[radiothermostat] Refactor usages of deprecated methods

---

bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/BaseDevice.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/InsteonDevice.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/handler/InsteonBaseThingHandler.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/handler/InsteonThingHandler.java

This changes fixes the handling of device request failures when a feature query couldn't be sent or wasn't answered.
While the Insteon Hub generates `0x5C` failure report messages when it's unable to get a response from the intended device, serial PLM do not produce such message. This mean the binding must rely on the query status timeouts to determine if a device is responding or not.
This change should be backported since unavailable devices connected to a serial PLM are currently showing as online status.

[insteon] Fix device request failure handling

---

bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/WakeOnLanUtility.java
bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/action/LGWebOSActions.java

These methods are deprecated:
- The method `exec(java.lang.String)` from the type java.lang.Runtime is deprecated since version 18
- The constructor `java.net.URL(java.lang.String)` is deprecated since version 20

[lgwebos] Refactor usages of deprecated methods

---

bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/ApiBridgeHandler.java
bundles/org.openhab.binding.netatmo/src/main/resources/OH-INF/i18n/netatmo.properties

See https://github.com/openhab/openhab-webui/pull/2996

[netatmo] Make configuration link clickable in Main UI

---

bundles/org.openhab.binding.oppo/src/main/java/org/openhab/binding/oppo/internal/discovery/OppoDiscoveryService.java

Refactor deprecated usages of MulticastSocket joinGroup() and leaveGroup(). Also fix compiler warning for potential null pointer access on e.getMessage(). Reference #14198

[oppo] Refactor usages of deprecated methods

---

bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/manager/ShellyManagerPage.java

This PR intends to fix https://github.com/openhab/openhab-addons/issues/18065.
The mode seems to be null under certain conditions. Since this bug is actually located in a special handling for one specific device this quick fix was taken.

[shelly] Fix `NullPointerException`

---

bundles/org.openhab.binding.freeathome/src/main/java/org/openhab/binding/freeathome/internal/datamodel/FreeAtHomeDatapoint.java
bundles/org.openhab.binding.freeathome/src/main/java/org/openhab/binding/freeathome/internal/datamodel/FreeAtHomeDatapointGroup.java
bundles/org.openhab.binding.freeathome/src/main/java/org/openhab/binding/freeathome/internal/datamodel/FreeAtHomeDeviceChannel.java

#Description
Freeathome Binding.
There is no direct 1:1 relationship between Function IDs and the required pairing IDs. As a result, a "needed" pairing ID may sometimes not exist. In such cases, we avoid adding an invalid datapoint group.
Should fix:
https://github.com/openhab/openhab-addons/issues/17353
Added ParingID for Slat Positions
https://github.com/openhab/openhab-addons/issues/17355
Added function IDs for Wind and Rain Alarms
Thanks to @ML19821
Hint: Sorry for the git chaos - we're still exercise and learn ;)
Hint2: Good News, @uha is back again - so we hope that there will be more improvments & fixes.

[Freeathome] Some more fixes

---

bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/NukiHandlerFactory.java

This fixes the [failing build](https://ci.openhab.org/job/openHAB-Addons/1632/console) that is caused by [this change in core](https://github.com/openhab/openhab-core/pull/4498).

[nuki] Fix nullable issue

---

bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/AwattarBestPriceResult.java
bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/AwattarConsecutiveBestPriceResult.java
bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/AwattarNonConsecutiveBestPriceResult.java
bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/AwattarUtil.java
bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/api/AwattarApi.java
bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/dto/AwattarTimeProvider.java
bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/handler/AwattarBestPriceHandler.java
bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/handler/AwattarBridgeHandler.java
bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/handler/AwattarHandlerFactory.java
bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/handler/AwattarPriceHandler.java
bundles/org.openhab.binding.awattar/src/test/java/org/openhab/binding/awattar/internal/AwattarBestPriceTest.java
bundles/org.openhab.binding.awattar/src/test/java/org/openhab/binding/awattar/internal/api/AwattarApiTest.java
bundles/org.openhab.binding.awattar/src/test/java/org/openhab/binding/awattar/internal/handler/AwattarBridgeHandlerRefreshTest.java
bundles/org.openhab.binding.awattar/src/test/java/org/openhab/binding/awattar/internal/handler/AwattarBridgeHandlerTest.java

PR does not change behaviour.
Only pushes code coverage and code maintainability.

[awattar] Refactor and add test coverage

---

bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/function/CreateVacationFunction.java
bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/handler/EcobeeThermostatBridgeHandler.java

[ecobee] Fix setting vacation hold temperatures and ignore unrealistic actual temperature

---

bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/server/MBWebsocket.java

WebSocket error status detail message is declared with a parameter providing the reason. This reason isn't forwarded by the code.
This bugfix corrects it.

[mercedesme] Add missing status parameter for web socket error

---

bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/command/ModemCommand.java

This changes adds the ability to list the modem features and product data via console commands.

[insteon] Add modem list features and product data console commands

---

bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/api/FroniusBatteryControl.java
bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/api/FroniusConfigAuthUtil.java
bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/api/FroniusUnauthorizedException.java
bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/handler/FroniusSymoInverterHandler.java

When setting invalid credentials, one received the following exception:
```
org.eclipse.jetty.client.HttpResponseException: HTTP protocol violation: Authentication challenge without WWW-Authenticate header
```
With the changes from this PR, the status code is now properly read and for 401, a meaningful warnings is logged instead.

[fronius] Fix invalid credentials lead to unexpected exception

---

bundles/org.openhab.binding.modbus/README.md
bundles/org.openhab.persistence.dynamodb/README.md

These don't actually render. Not sure what the tags were for.
https://next.openhab.org/addons/binding/modbus/
https://next.openhab.org/addons/persistence/dynamodb/

Fix table of content tag

---

bundles/org.openhab.binding.amazondashbutton/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.amazondashbutton/src/main/resources/OH-INF/i18n/amazondashbutton.properties
bundles/org.openhab.binding.digitalstrom/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.digitalstrom/src/main/resources/OH-INF/i18n/digitalstrom.properties
bundles/org.openhab.binding.icloud/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.icloud/src/main/resources/OH-INF/i18n/iCloud.properties
bundles/org.openhab.binding.jeelink/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.mielecloud/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.nanoleaf/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.nikohomecontrol/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.nikohomecontrol/src/main/resources/OH-INF/i18n/nikohomecontrol.properties
bundles/org.openhab.binding.sagercaster/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.sagercaster/src/main/resources/OH-INF/i18n/sagercaster.properties
bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.urtsi/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.urtsi/src/main/resources/OH-INF/i18n/urtsi.properties
bundles/org.openhab.binding.velux/src/main/resources/OH-INF/addon/addon.xml

The corresponding ids in the properties files are converted to the standard naming so they can be automatically inferred.
See the discussion https://github.com/openhab/openhab-addons/pull/14310#issuecomment-2601972772
TL;DR: This change here should not affect the appearance of the add-ons as they're viewed in mainUI. By using actual text, the `runtime/etc/addons.xml` which is built by combining all the addon.xml files, will contain name/description that can be used in MainUI search / display.

Convert i18n references in addon.xml to actual text

---

bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/BaseDevice.java

This change limits the device request failure condition introduced in #18087. Only request queries that were in sent and acked status should be considered for determining if a device failed to respond. If such query fails while waiting to be sent, it should not be considered as a device failure.

[insteon] Limit device request failure condition

---

bundles/org.openhab.binding.insteon/src/main/resources/device-types.xml

This change removes the IOLinc device `eventButton` feature. This device doesn't have a physical button that would trigger key press events.
It should be backported as internal relay state update events are triggering false button event.

[insteon] Remove iolinc event button feature

---

bundles/org.openhab.transform.basicprofiles/src/main/java/org/openhab/transform/basicprofiles/internal/profiles/StateFilterProfile.java
bundles/org.openhab.transform.basicprofiles/src/test/java/org/openhab/transform/basicprofiles/internal/profiles/StateFilterProfileTest.java

There was a bug when having multiple DELTA conditions, resulting in pematurely saving the previous accepted value.
Example:
`$DELTA > 1, $DELTA < 10`:
- An initial input 50 will be accepted (correct behavior)
- Second input of 60 will pass `$DELTA > 1` (60 - 50 is greater than 1)
- Here, the accepted value was incorrectly saved to be 60 before checking the next condition
- When the next condition is checked, the input of 60 is compared against the acceptedvalue (now 60), so the delta is 60 - 60 which is less than 10.
- The correct behavior should be that input 60 is compared against the accepted value of 50, so 60 - 50 which is not less than 10.
Only after all conditions are checked and met should the accepted value be updated.
Please backport to 4.3

[basicprofiles] Fix handling of multiple `$DELTA` conditions

---

bundles/org.openhab.transform.basicprofiles/README.md
bundles/org.openhab.transform.basicprofiles/src/main/java/org/openhab/transform/basicprofiles/internal/profiles/StateFilterProfile.java
bundles/org.openhab.transform.basicprofiles/src/test/java/org/openhab/transform/basicprofiles/internal/profiles/StateFilterProfileTest.java

Alternative solution to #18091

[basicprofiles] Fix regular comparison of Percent Quantity interpreted as $DELTA_PERCENT check

---

bundles/org.openhab.binding.comfoair/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.danfossairunit/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.haywardomnilogic/src/main/resources/OH-INF/thing/filter.xml
bundles/org.openhab.binding.haywardomnilogic/src/main/resources/OH-INF/thing/pump.xml

This ensures that the UI will suggest "rpm" rather than "Hz" when creating new items.

Provide unit hints for rpm channels

---

bundles/org.openhab.binding.jellyfin/src/main/java/org/openhab/binding/jellyfin/internal/handler/JellyfinServerHandler.java

See https://github.com/openhab/openhab-webui/pull/2996

[jellyfin] Make configuration link clickable in Main UI

---

bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/rest/mocks/DummyItemRegistry.java
bundles/org.openhab.persistence.dynamodb/src/test/java/org/openhab/persistence/dynamodb/internal/BaseIntegrationTest.java

Adapt to core change https://github.com/openhab/openhab-core/pull/4568.
`RegistryHook` and related methods have been removed.

Remove RegistryHook

---

bundles/org.openhab.binding.bluetooth.bluez/src/main/java/org/openhab/binding/bluetooth/bluez/internal/BlueZBluetoothDevice.java

Fixes #18180
I had another look at the call stack in the linked issue while going through the BlueZ code again, and unfortunately the fix provided in #18181 didn't fix this exception. This PR is technically not a regression (the mentioned PR is harmless and potentially fixes another scenario), but rather a "proper fix". Nevertheless adding the label to not have it mentioned in release notes twice.

[bluetooth.bluez] Fix `NullPointerException`

---

bundles/org.openhab.binding.benqprojector/README.md
bundles/org.openhab.binding.epsonprojector/README.md
bundles/org.openhab.binding.kaleidescape/README.md
bundles/org.openhab.binding.monopriceaudio/README.md
bundles/org.openhab.binding.nuvo/README.md
bundles/org.openhab.binding.oppo/README.md
bundles/org.openhab.binding.panasonicbdp/README.md
bundles/org.openhab.binding.radiothermostat/README.md
bundles/org.openhab.binding.roku/README.md
bundles/org.openhab.binding.tasmotaplug/README.md
bundles/org.openhab.binding.tivo/README.md
bundles/org.openhab.binding.vizio/README.md

Add chapter headings for examples in all bindings for which I am code owner. This follows the suggestion in #18154 to delineate each file example as a chapter. Also normalize the capitalization of `Thing` throughout.

Add chapter headings for examples

---

bundles/org.openhab.binding.bluetooth.radoneye/README.md
bundles/org.openhab.binding.bluetooth.radoneye/src/main/java/org/openhab/binding/bluetooth/radoneye/internal/AbstractRadoneyeHandler.java
bundles/org.openhab.binding.bluetooth.radoneye/src/main/java/org/openhab/binding/bluetooth/radoneye/internal/RadoneyeBindingConstants.java
bundles/org.openhab.binding.bluetooth.radoneye/src/main/java/org/openhab/binding/bluetooth/radoneye/internal/RadoneyeDataParser.java
bundles/org.openhab.binding.bluetooth.radoneye/src/main/java/org/openhab/binding/bluetooth/radoneye/internal/RadoneyeDiscoveryParticipant.java
bundles/org.openhab.binding.bluetooth.radoneye/src/main/java/org/openhab/binding/bluetooth/radoneye/internal/RadoneyeHandler.java
bundles/org.openhab.binding.bluetooth.radoneye/src/main/resources/OH-INF/i18n/bluetooth.properties
bundles/org.openhab.binding.bluetooth.radoneye/src/main/resources/OH-INF/thing/radoneye.xml
bundles/org.openhab.binding.bluetooth.radoneye/src/main/resources/OH-INF/update/instructions.xml
bundles/org.openhab.binding.bluetooth.radoneye/src/test/java/org/openhab/binding/bluetooth/radoneye/RadoneyeParserTest.java

This PR does fix the randoneye integration and simplifies the code by using the `ConnectedBluetoothHandler`.
For V2 devices a new channel `decay` is available showing the number of decays in the last timeframe.
Signed-off-by: Jörg Sautter <joerg.sautter@gmx.net>

[radoneye] Add decay channel for HW v2 and simplify the code

---

bundles/org.openhab.automation.jrubyscripting/pom.xml

This release fixes two critical bugs in JRuby 9.4.10.0
https://www.jruby.org/2025/01/29/jruby-9-4-11-0.html
CI: https://github.com/openhab/openhab-jruby/pull/385

[jrubyscripting] Update to JRuby 9.4.11.0

---

bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/internal/action/MQTTActions.java
bundles/org.openhab.binding.mqtt/src/main/resources/OH-INF/i18n/mqtt.properties

This is so they can be differentiated in MainUI
Before
After

[mqtt] Set distinct action labels

---

bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/Constants.java
bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/handler/AccountHandler.java

Bugfix for auth problem observed yesterday in my system and also [observed by community](https://community.openhab.org/t/mercedes-me/136866/59). Mercedes abandoned "too old" clients to access the data so version numbers needs to be adapted.
This is a **showstopper** because since yesterday old bindings are not working anymore. I recommend to put this PR into the next minor update to fix this as early as possible.
In addition small bugfix of subsequent JSON error which was [reported by community](https://community.openhab.org/t/mercedes-me/136866/61)

[mercedesme] bugfix auth problem causing http 412 error

---

bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/calc/MoonCalc.java
bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/util/DateTimeUtils.java

Instead of returning a constant value of the moon phase age relative to the start of the day, return the real-time calculation of the moon phase age on each channel update
See https://community.openhab.org/t/astro-binding-is-moon-phase-age-and-other-phase-channels-not-recalculated-with-the-thing-set-interval/162111

[astro] Update real-time Moon Phase Age

---

bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/command/DebugCommand.java

This changes adds the ability to log message events for the modem and x10 devices via the console. Previously only messages for Insteon devices could be logged. Outbound all link broadcast (scene) messages will be attached to the modem event log.

[insteon] Add debug monitoring support for modem and x10 devices

---

bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/handler/InsteonBaseThingHandler.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/handler/InsteonBridgeHandler.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/handler/InsteonLegacyNetworkHandler.java

This change adds a separate pool for long running threads.
This should be backported as the binding is unable to successfully download the modem database for some users, preventing the initialization process from completing.

[insteon] Use separate pool for long running threads

---

bundles/org.openhab.transform.basicprofiles/src/main/java/org/openhab/transform/basicprofiles/internal/profiles/StateFilterProfile.java
bundles/org.openhab.transform.basicprofiles/src/test/java/org/openhab/transform/basicprofiles/internal/profiles/StateFilterProfileTest.java

Reported in https://community.openhab.org/t/state-filter-range-filter-profile/158025/51

[basicprofiles] Convert to relative unit in State Filter's Delta check

---

bundles/org.openhab.transform.basicprofiles/src/main/java/org/openhab/transform/basicprofiles/internal/profiles/StateFilterProfile.java
bundles/org.openhab.transform.basicprofiles/src/test/java/org/openhab/transform/basicprofiles/internal/profiles/StateFilterProfileTest.java

This should also be backported

[basicprofiles] Fix division-by-zero error in $DELTA_PERCENT state filter

---

bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitTaggedItem.java
bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitCharacteristicFactory.java

`getConfigurationAsQuantity` was using `toUnitRelative` appropriately, but the final conversion to Celsius was not, resulting in a 1 °F step being interpreted as a -17.5 °C step!

[homekit] fix unit conversions on step values for temperatures

---

bundles/org.openhab.binding.bluetooth/CONTRIBUTE.md

This adjustment is for compliance with the [naming convention](https://www.openhab.org/docs/developer/guidelines.html#naming-convention) established in 2023 (see https://github.com/openhab/openhab-distro/discussions/1504).

[bluetooth] Adapt documentation to naming convention

---

bundles/org.openhab.automation.jrubyscripting/pom.xml

This version should fix the bundle installation problem related to snakeyaml. It also has a critical fix for a CME.
https://www.jruby.org/2025/02/11/jruby-9-4-12-0.html

[jrubyscripting] Update to JRuby 9.4.12.0

---

bundles/org.openhab.binding.lgtvserial/README.md
bundles/org.openhab.binding.lgtvserial/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.lgtvserial/src/main/resources/OH-INF/config/config.xml
bundles/org.openhab.binding.lgtvserial/src/main/resources/OH-INF/i18n/lgtvserial.properties
bundles/org.openhab.binding.lgtvserial/src/main/resources/OH-INF/thing/thing-channels.xml
bundles/org.openhab.binding.lgtvserial/src/main/resources/OH-INF/thing/thing-types-M6503C.xml
bundles/org.openhab.binding.lgtvserial/src/main/resources/OH-INF/thing/thing-types-SAC34134216.xml

The PR makes the following improvements to the README and labels & descriptions:
- Improve README content, grammar, punctuation, etc.
- Add missing Thing Configuration parameters table
- Fix incorrect or missing ids and normalize descriptions in the Channels table
- Fix broken links to reference documents
- Fix incorrect or awkward thing and channel labels & descriptions
No code changes were made.

[lgtvserial] Update documentation and fix labels/descriptions

---

bundles/org.openhab.binding.awattar/README.md
bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/AwattarBridgeConfiguration.java
bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/AwattarPrice.java
bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/api/AwattarApi.java
bundles/org.openhab.binding.awattar/src/main/resources/OH-INF/config/config.xml
bundles/org.openhab.binding.awattar/src/main/resources/OH-INF/i18n/awattar.properties
bundles/org.openhab.binding.awattar/src/test/java/org/openhab/binding/awattar/internal/api/AwattarApiTest.java

The current calculations are a bit off and the config is not able to compensate for this.
This MR would include the correct fees for the service directly in the calculation. 
There seems to be a little diverge:
In [DE](https://de.energy-support.tado.com/de/articles/9496158-wie-setzt-sich-der-hourly-tarif-zusammen) the 3% fee seems to be calculated directly from the net price, while in [AT](https://www.awattar.at/tariffs/hourly) the absolute value of the net prices is used to calculate the fee.
Maybe there is another way of reflecting that in config, I'm open for suggestions.

[aWATTar] include fees in calculation

---

bundles/org.openhab.transform.jsonpath/pom.xml

Fixes [CVE-2024-57699](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-57699)
See:
- https://github.com/openhab/openhab-addons/security/dependabot/100
- https://github.com/netplex/json-smart-v2?tab=readme-ov-file#changelog
Release:
- https://mvnrepository.com/artifact/net.minidev/json-smart
- https://mvnrepository.com/artifact/net.minidev/accessors-smart

[jsonpath] Upgrade json-smart to 2.5.2

---

bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/DiscoverComponents.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/HomeAssistantChannelLinkageChecker.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/AbstractComponent.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/ComponentFactory.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/handler/HomeAssistantThingHandler.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/AbstractComponentTests.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/AlarmControlPanelTests.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/BinarySensorTests.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/ButtonTests.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/CameraTests.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/ClimateTests.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/CoverTests.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/DefaultSchemaLightTests.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/DeviceTrackerTests.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/FanTests.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/HumidifierTests.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/JSONSchemaLightTests.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/LockTests.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/NumberTests.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/SelectTests.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/SensorTests.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/SwitchTests.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/TemplateSchemaLightTests.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/TextTests.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/VacuumTests.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/ValveTests.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/WaterHeaterTests.java
itests/org.openhab.binding.mqtt.homeassistant.tests/src/main/java/org/openhab/binding/mqtt/homeassistant/DiscoverComponentsTest.java
itests/org.openhab.binding.mqtt.homeassistant.tests/src/main/java/org/openhab/binding/mqtt/homeassistant/HomeAssistantMQTTImplementationTest.java

[mqtt.homeassistant] Only subscribe to topics for linked channels

---

bundles/org.openhab.automation.jsscripting/README.md
bundles/org.openhab.automation.jsscripting/bnd.bnd
bundles/org.openhab.automation.jsscripting/pom.xml
bundles/org.openhab.automation.jsscripting/src/main/feature/feature.xml
bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/scriptengine/DelegatingScriptEngineWithInvocableAndCompilableAndAutocloseable.java

Fixes #18054 by using a OSGi-ified Truffle Runtime, which is loaded only once.
It also reduces the add-on size from 34 MB to 16 MB: Truffle ICU4j was pretty big and now is provided as OSGi bundle and hence not bundled with the add-on anymore.
GraalVM Polyglot and Truffle API dependencies cannot be provided as OSGi bundles, because those use the Java ServiceLoader to load the available polyglot and truffle language implementations, which depend on on the individual add-on, and we cannot configure the service loading for those if they are shared OSGi bundles.

[jsscripting] Use OSGi-ified GraalVM dependencies

---

bundles/org.openhab.binding.amplipi/pom.xml
bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api1/Shelly1CoapServer.java
bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/handler/TradfriGatewayHandler.java
itests/org.openhab.automation.groovyscripting.tests/itest.bndrun
itests/org.openhab.automation.jsscriptingnashorn.tests/itest.bndrun
itests/org.openhab.binding.astro.tests/itest.bndrun
itests/org.openhab.binding.avmfritz.tests/itest.bndrun
itests/org.openhab.binding.feed.tests/itest.bndrun
itests/org.openhab.binding.hue.tests/itest.bndrun
itests/org.openhab.binding.max.tests/itest.bndrun
itests/org.openhab.binding.mielecloud.tests/itest.bndrun
itests/org.openhab.binding.modbus.tests/itest.bndrun
itests/org.openhab.binding.modbus.tests/src/main/java/org/openhab/binding/modbus/tests/ModbusPollerThingHandlerTest.java
itests/org.openhab.binding.mqtt.homeassistant.tests/itest.bndrun
itests/org.openhab.binding.mqtt.homie.tests/itest.bndrun
itests/org.openhab.binding.mqtt.ruuvigateway.tests/itest.bndrun
itests/org.openhab.binding.ntp.tests/itest.bndrun
itests/org.openhab.binding.systeminfo.tests/itest.bndrun
itests/org.openhab.binding.tradfri.tests/itest.bndrun
itests/org.openhab.binding.wemo.tests/itest.bndrun
itests/org.openhab.persistence.mapdb.tests/itest.bndrun

* junit, cxf, javassist, hamcrest
* [tradfri] Adapt NetworkConfig to new Californium API
* [shelly] Adapt NetworkConfig to new Californium API
* _[modbus.itests] Temporarily disable some test steps which fail with hamcrest3_
Depends on core change, openhab/openhab-core#4584

Adapt dependencies due to core changes

---

bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/HueBindingConstants.java

Resolves #18260 
I suggest to back port this to v4.3

[hue] Fix support for dynamics on "..only" channels

---

bundles/org.openhab.transform.basicprofiles/src/main/java/org/openhab/transform/basicprofiles/internal/profiles/StateFilterProfile.java

The new code of the `toInvertibleUnit()` method of https://github.com/openhab/openhab-core/pull/4561 had been duplicated in parallel in #18144.
This PR simply removes that duplication.
Note this PR relies on new code in OH Core https://github.com/openhab/openhab-core/pull/4561 so probably this PR cannot be backported to OH 4.3.x -- depends if the core PR would be backported too..

[basicprofiles] Remove duplicate code

---

bundles/org.openhab.binding.insteon/src/main/resources/device-products.xml

This changes fixes the first record config for ICON products. The default value should be used instead.
It should be backported as the status of ICON device things would get stuck in `CONFIGURATION_PENDING` as the database record validation will keep failing due to a different first record address.

[insteon] Fix icon products first record config

---

bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/InsteonBindingConstants.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/command/DeviceCommand.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/DefaultLink.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/DeviceFeature.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/DeviceType.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/DeviceTypeRegistry.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/InsteonDevice.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/database/LinkDB.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/database/LinkDBChange.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/database/ModemDB.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/database/ModemDBChange.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/feature/MessageHandler.java
bundles/org.openhab.binding.insteon/src/main/resources/device-features.xml
bundles/org.openhab.binding.insteon/src/main/resources/device-types.xml

This change fixes the missing links implementation. It includes:
* Ignore missing modem links when its monitor mode is on.
* Allowing device with one component to have a component ID of `0` or `1` instead of being driven by the default link configuration.
* Removing default link command support migrating the configure commands as hidden features.
* Refactoring the device missing links console commands
This should be backported as the current implementation identifies false positives with unnecessary warning log statements, along with the `addMissingLinks` console command failing to add multiple modem missing links in a row requiring the command to be ran multiple times.

[insteon] Fix missing links implementation

---

bundles/org.openhab.binding.mielecloud/src/main/java/org/openhab/binding/mielecloud/internal/MieleCloudBindingConstants.java
bundles/org.openhab.binding.mielecloud/src/main/java/org/openhab/binding/mielecloud/internal/auth/OpenHabOAuthTokenRefresher.java
bundles/org.openhab.binding.mielecloud/src/main/java/org/openhab/binding/mielecloud/internal/config/OAuthAuthorizationHandlerImpl.java
bundles/org.openhab.binding.mielecloud/src/main/java/org/openhab/binding/mielecloud/internal/handler/MieleBridgeHandler.java
bundles/org.openhab.binding.mielecloud/src/main/resources/OH-INF/i18n/mielecloud.properties

This changes the OAuth service handle from the configured e-mail address to the bridge UID in order to avoid conflicts in the global namespace of handles in the OAuth storage.
Automated migration is not supported by the core classes, therefore the logic is as follows:
- If the new service handle is found, it will be used.
- Otherwise, if an old service handle is found, it will be used, and the user will be advised to re-authorize (through logging).
- On successful re-authorization, any old service handle will be removed from the OAuth storage.
Additionally a clickable link will now be provided when authorization is missing.
Fixes #14783
Fixes #18265

[mielecloud] Fix OAuth service handle

---

bundles/org.openhab.binding.huesync/src/main/java/org/openhab/binding/huesync/internal/HueSyncConstants.java
bundles/org.openhab.binding.huesync/src/main/java/org/openhab/binding/huesync/internal/connection/HueSyncConnection.java
bundles/org.openhab.binding.huesync/src/main/java/org/openhab/binding/huesync/internal/connection/HueSyncDeviceConnection.java
bundles/org.openhab.binding.huesync/src/main/java/org/openhab/binding/huesync/internal/exceptions/HueSyncConnectionException.java
bundles/org.openhab.binding.huesync/src/main/java/org/openhab/binding/huesync/internal/exceptions/HueSyncException.java
bundles/org.openhab.binding.huesync/src/main/java/org/openhab/binding/huesync/internal/factory/HueSyncHandlerFactory.java
bundles/org.openhab.binding.huesync/src/main/java/org/openhab/binding/huesync/internal/handler/HueSyncHandler.java
bundles/org.openhab.binding.huesync/src/main/java/org/openhab/binding/huesync/internal/handler/tasks/HueSyncRegistrationTask.java
bundles/org.openhab.binding.huesync/src/main/java/org/openhab/binding/huesync/internal/handler/tasks/HueSyncUpdateTask.java
bundles/org.openhab.binding.huesync/src/main/java/org/openhab/binding/huesync/internal/i18n/ResourceHelper.java
bundles/org.openhab.binding.huesync/src/main/java/org/openhab/binding/huesync/internal/types/HueSyncExceptionHandler.java
bundles/org.openhab.binding.huesync/src/main/resources/OH-INF/i18n/huesync.properties

➡️ Refactoring of connection handling
Refactored exception connection exception handling to provide more information and improve code structure/maintainability. Connection settings are no longer deleted if the device disconnects.
---
---

[huesync] Fix lost api-token when device goes offline

---

bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/AbstractComponent.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/DeviceTrigger.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Scene.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/config/dto/AbstractChannelConfiguration.java
bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/handler/HomeAssistantThingHandler.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/SceneTests.java

It accepts either object ID, or scene name (assuming the latter doesn't conflict with the former). Command descriptions are fully populated. You also no longer need to deal with sending the payload_on.
Merging components is refactored slightly, now that multiple component types do it.
Closes #18259

[mqtt.homeassistant] Use a single channel for all scenes on a device

---

bundles/org.openhab.binding.bluetooth.grundfosalpha/README.md
bundles/org.openhab.binding.bluetooth.grundfosalpha/src/main/java/org/openhab/binding/bluetooth/grundfosalpha/internal/CharacteristicRequest.java
bundles/org.openhab.binding.bluetooth.grundfosalpha/src/main/java/org/openhab/binding/bluetooth/grundfosalpha/internal/GrundfosAlphaBindingConstants.java
bundles/org.openhab.binding.bluetooth.grundfosalpha/src/main/java/org/openhab/binding/bluetooth/grundfosalpha/internal/GrundfosAlphaHandlerFactory.java
bundles/org.openhab.binding.bluetooth.grundfosalpha/src/main/java/org/openhab/binding/bluetooth/grundfosalpha/internal/discovery/GrundfosAlphaDiscoveryParticipant.java
bundles/org.openhab.binding.bluetooth.grundfosalpha/src/main/java/org/openhab/binding/bluetooth/grundfosalpha/internal/handler/GrundfosAlpha3Handler.java
bundles/org.openhab.binding.bluetooth.grundfosalpha/src/main/java/org/openhab/binding/bluetooth/grundfosalpha/internal/handler/GrundfosAlphaReaderHandler.java
bundles/org.openhab.binding.bluetooth.grundfosalpha/src/main/java/org/openhab/binding/bluetooth/grundfosalpha/internal/protocol/CRC16Calculator.java
bundles/org.openhab.binding.bluetooth.grundfosalpha/src/main/java/org/openhab/binding/bluetooth/grundfosalpha/internal/protocol/MessageHeader.java
bundles/org.openhab.binding.bluetooth.grundfosalpha/src/main/java/org/openhab/binding/bluetooth/grundfosalpha/internal/protocol/MessageStartDelimiter.java
bundles/org.openhab.binding.bluetooth.grundfosalpha/src/main/java/org/openhab/binding/bluetooth/grundfosalpha/internal/protocol/MessageType.java
bundles/org.openhab.binding.bluetooth.grundfosalpha/src/main/java/org/openhab/binding/bluetooth/grundfosalpha/internal/protocol/ResponseMessage.java
bundles/org.openhab.binding.bluetooth.grundfosalpha/src/main/java/org/openhab/binding/bluetooth/grundfosalpha/internal/protocol/SensorDataType.java
bundles/org.openhab.binding.bluetooth.grundfosalpha/src/main/resources/OH-INF/i18n/bluetooth.properties
bundles/org.openhab.binding.bluetooth.grundfosalpha/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.bluetooth.grundfosalpha/src/test/java/org/openhab/binding/bluetooth/grundfosalpha/internal/handler/GrundfosAlphaReaderHandlerTest.java
bundles/org.openhab.binding.bluetooth.grundfosalpha/src/test/java/org/openhab/binding/bluetooth/grundfosalpha/internal/protocol/CRC16CalculatorTest.java
bundles/org.openhab.binding.bluetooth.grundfosalpha/src/test/java/org/openhab/binding/bluetooth/grundfosalpha/internal/protocol/MessageTypeTest.java
bundles/org.openhab.binding.bluetooth.grundfosalpha/src/test/java/org/openhab/binding/bluetooth/grundfosalpha/internal/protocol/ResponseMessageTest.java

This adds support for the Grundfos Alpha3 pump with built-in Bluetooth.
Related:
- #18185 for fixing a bug I found in the BlueZ bridge: #18180
- openhab/openhab-docs#2452, openhab/openhab-docs#2454 for adding the Grundfos logo, which I forgot to mention in #15907
Resolves #16116

[grundfosalpha] Add support for Alpha3 pump

---

bundles/org.openhab.binding.linktap/src/main/java/org/openhab/binding/linktap/internal/LinkTapBridgeHandler.java
bundles/org.openhab.binding.linktap/src/main/java/org/openhab/binding/linktap/internal/LinkTapHandler.java
bundles/org.openhab.binding.linktap/src/main/java/org/openhab/binding/linktap/internal/PollingDeviceHandler.java
bundles/org.openhab.binding.linktap/src/main/java/org/openhab/binding/linktap/internal/TransactionProcessor.java
bundles/org.openhab.binding.linktap/src/main/java/org/openhab/binding/linktap/protocol/frames/GatewayDeviceResponse.java
bundles/org.openhab.binding.linktap/src/main/java/org/openhab/binding/linktap/protocol/frames/GatewayEndDevListReq.java
bundles/org.openhab.binding.linktap/src/main/java/org/openhab/binding/linktap/protocol/http/TransientCommunicationIssueException.java
bundles/org.openhab.binding.linktap/src/main/java/org/openhab/binding/linktap/protocol/http/WebServerApi.java
bundles/org.openhab.binding.linktap/src/main/resources/OH-INF/i18n/linktap.properties

[linktap] Bugfix Issue 18076
This is the patch for the main branch for the LinkTap corrections.
Timing changes in the firmware have highlighted some potential race conditions that can occur, with older firmware's it may also happen.
Consequently, these changes ensure that the race conditions cannot happen, meaning the communications stack misses device registration to the gateway's data. New defensive checks on CMD16 ensure that incorrect responses are ignored / handled, which can occur when the gateway is booting up. The new ret code's are being rolled out in a firmware now globally, so these changes ensure that reply has a ret status that shows CMD16 is not ready to be used, the binding falls back, and will try again when the gateway is ready.
In addition it was noted during testing …

[linktap] Improve connection handling

---

bundles/org.openhab.binding.energidataservice/src/main/resources/filters/grid_tariffs.yaml

This reflects data published since 01.01.2025 - see:
https://flow-elnet.dk/fileadmin/user_upload/PDF/Prisblad_Flow-Elnet_2025-01-01.pdf

[energidataservice] Update tariff filter for FLOW Elnet

---

bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/ProductData.java

This change fixes the product data first record not getting updated. This is related to #18271. When the first record property was remove, the cached product data property wasn't getting updated because it was considered as not defined. The properties that can only be defined through the `ProductDataRegistry` class should be able to clear a previous value. While the ones that are retrieved from the device (firmware/hardware) should not.

[insteon] Fix product data not updating first record

---

bundles/org.openhab.persistence.dynamodb/src/main/java/org/openhab/persistence/dynamodb/internal/AbstractDynamoDBItem.java
bundles/org.openhab.persistence.dynamodb/src/main/java/org/openhab/persistence/dynamodb/internal/DynamoDBPersistenceService.java
bundles/org.openhab.persistence.dynamodb/src/main/java/org/openhab/persistence/dynamodb/internal/DynamoDBQueryUtils.java
bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/InfluxDBPersistenceService.java
bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/FilterCriteriaQueryCreator.java
bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/InfluxDBMetadataService.java
bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/InfluxDBRepository.java
bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/influx1/InfluxDB1FilterCriteriaQueryCreatorImpl.java
bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/influx1/InfluxDB1RepositoryImpl.java
bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/influx2/InfluxDB2FilterCriteriaQueryCreatorImpl.java
bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/influx2/InfluxDB2RepositoryImpl.java
bundles/org.openhab.persistence.influxdb/src/test/java/org/openhab/persistence/influxdb/internal/InfluxFilterCriteriaQueryCreatorImplTest.java
bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcMapper.java
bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcPersistenceService.java
bundles/org.openhab.persistence.jpa/src/main/java/org/openhab/persistence/jpa/internal/JpaPersistenceService.java
bundles/org.openhab.persistence.mongodb/src/main/java/org/openhab/persistence/mongodb/internal/MongoDBPersistenceService.java
bundles/org.openhab.persistence.mongodb/src/test/java/org/openhab/persistence/mongodb/internal/MongoDBPersistenceServiceTest.java
bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java
bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/charts/RRD4jChartServlet.java
bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/console/RRD4jCommandExtension.java

With the core improvements in https://github.com/openhab/openhab-core/pull/4363, it is now possible to also improve alias support in the persistence addons.
Without changes in the addons, the core improvements would make it possible to configure aliases, it does not improve the support in the addons. For that, the persistence addons also need to be adjusted.
Depending on the addon, there where varying levels of support for aliases. In most cases, support was incomplete.
The most common issue was that the item registry was called to check an item existed, find the group base item, or to get a unit. If the item was stored with an alias, the alias was used to search the item in the item registry, which fails. So even when an alias was used to store the item, it could never be retrieved.
With …

Persistence alias support

---

bundles/org.openhab.binding.xmppclient/src/main/java/org/openhab/binding/xmppclient/internal/handler/XMPPClientConfiguration.java

Fixes: https://github.com/openhab/openhab-addons/issues/18007
Regression of https://github.com/openhab/openhab-addons/pull/14397
4.3.x jar: https://1drv.ms/u/s!AnMcxmvEeupwj5MJkLK2YIf6wTy5Zw?e=yhO5oD

[xmppclient] Host parameter should not be mandatory

---

bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/DSCAlarmCode.java
bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/DSCAlarmMessage.java
bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/handler/DSCAlarmBaseBridgeHandler.java
bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/handler/ZoneThingHandler.java

Bypassing a zone from the keypad did not reflect the change in openhab, although envisalink board issues a Process Bypassed Zones Bitfield Dump (616) command that can be used to update the appropriate channels.
This change will start processing Bypassed Zones Bitfield Dump (616) command and update every zone's `zone_bypass_mode` channel and it is documented [here](https://forum.eyezon.com/download/file.php?id=379&sid=6b1e1197bad7c56a9e24bf0f697ce420)

[dscalarm] Fix update of channel `zone_bypass_mode`

---

bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/BoschSHCBindingConstants.java
bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/BoschSHCDeviceHandler.java
bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/BridgeHandler.java
bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/discovery/ThingDiscoveryService.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/AbstractBoschSHCDeviceHandlerTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/bridge/BridgeHandlerTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/relay/RelayHandlerTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/discovery/ThingDiscoveryServiceTest.java

When a device is initialized, an attempt is made to look up the room name for the room id specified for the device and to store the room name in a thing property. This property is also updated if a room change is detected.
The legacy property `Location` is removed if present. From now on the property `location` (with proper lower case spelling) is used.
* add constants for location properties
* implement location updates in abstract device handler
* extend bridge handler to provide a cached list of rooms
* add unit tests
closes #16599

[boschshc] Update location properties when initializing things

---

bundles/org.openhab.binding.cbus/README.md

Fixes: https://github.com/openhab/openhab-addons/issues/17969

[cbus] Adapt documentation for c-gate version 3.4.0

---

bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java

Closes https://github.com/openhab/openhab-addons/issues/18303
With https://github.com/openhab/openhab-core/pull/4463, the restoreOnStartup strategy not only restores the last state, but also the last state update, last state change and previous state. To achieve that, a default method was implemented that queries the DB and searches backwards for the last state change. That query does not have a start date, rather looks as far as it needs.
RRD4J does not allow a query with no start date. Therefore the default method is overriden in this PR to limit how far back in the history the query will look.
In general, mapdb is the more efficient storage to restore values on startup, allowing to retrieve all values for all item types.
@kaikreuzer FYI

[rrd4j] Fix restore on startup

---

bundles/org.openhab.binding.insteon/src/main/resources/device-products.xml

This reverts the first record config change for specific icon products in #18271. It seems that products from that line with two defined versions use `0x00FF` on the most recent one. This was confirm by the user that reported this issue. It includes the following devices:
* ICON Dimmer Switch (2876DB)
* `0x01 0x03` @ `0x0FFF`
* `0x01 0x1E` @ `0x00FF`
* ICON On/Off Switch (2876SB)
* `0x02 0x0B` @ `0x0FFF`
* `0x02 0x16` @ `0x00FF`
* ICON Appliance Module (2856S3B)
* `0x02 0x0C` @ `0x0FFF`
* `0x02 0x17` @ `0x00FF`

[insteon] Revert specific icon products first record

---

bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/command/ReadEventCommand.java
bundles/org.openhab.binding.satel/src/test/java/org/openhab/binding/satel/internal/command/ReadEventCommandTest.java

Fix to properly decode partition keypad number from event log record in `ReadEventCommand` class.
There are also other minor changes in that class for things spotted while fixing the bug.
Unit tests has been added for this class as well.
Related discussion with details is here: https://community.openhab.org/t/satel-binding-support-announcements-and-feature-requests/56135/304

[satel] Fix event log partition keypad decoding

---

bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/InstarHandler.java
bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/ReolinkHandler.java
bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/onvif/OnvifCodec.java
bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/onvif/OnvifConnection.java

This push requests fixes a few issues/regressions after a recent PR made changes in these areas. Can these changes be applied to STABLE 4.x branch please? closes #18313 closes #18052
1. No source on events cause a NPE when the cause is only used for logging and no real code. Removed to make code execute faster.
2. Readme description of onvifEventServiceType does not match the codes implementation. Changed to make the code consistent.
3. Fixes that may cause event streams to stop.
4. Fixes minor WARN that gets wrongly displayed for Reolink cameras.

[ipcamera] Fix event streams crash when no source is specified.

---

bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/handler/ZonePlayerHandler.java

This methods is deprecated:
- The constructor `java.net.URL(java.lang.String)` is deprecated since version 20

[sonos] Refactor usage of deprecated method

---

bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/AbstractHomekitAccessoryImpl.java

So that they'll always be added in a consistent order. Otherwise we might accidentally change the order (and thus the IID) of a characteristic, but not actually detect that it's different and signal Home to reload accessory structures.
This seems to at least help #18140, if not a complete fix for it.

[homekit] Sort optional characteristics before adding them to the service

---

bundles/org.openhab.binding.luxtronikheatpump/src/main/java/org/openhab/binding/luxtronikheatpump/internal/enums/HeatpumpChannel.java
bundles/org.openhab.binding.luxtronikheatpump/src/main/resources/OH-INF/i18n/luxtronikheatpump.properties
bundles/org.openhab.binding.luxtronikheatpump/src/main/resources/OH-INF/thing/channels.xml
bundles/org.openhab.binding.luxtronikheatpump/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.luxtronikheatpump/src/main/resources/OH-INF/update/instructions.xml

Enables the channel `Input "Utility Lock 2"`
fixes #18255 
Note: I have also added type definitions to the update instructions. Without them the handler triggered this error for all  things:
``` 
[org.openhab.core.thing.internal.ThingManagerImpl(269)] : The addThingHandlerFactory method has thrown an exception
java.lang.NullPointerException: Cannot invoke "String.split(String)" because "id" is null
at org.openhab.core.common.AbstractUID.splitToSegments(AbstractUID.java:124) ~[?:?]
at org.openhab.core.common.AbstractUID.<init>(AbstractUID.java:49) ~[?:?]
at org.openhab.core.thing.UID.<init>(UID.java:48) ~[?:?]
at org.openhab.core.thing.type.ChannelTypeUID.<init>(ChannelTypeUID.java:42) ~[?:?]
at org.openhab.core.thing.internal.update.UpdateChannelInstructionImpl.<init>(UpdateChannelInstruct …
```

[LuxtronikHeatpump] Enable Utility Lock 2 channel (EVU2)

---

bundles/org.openhab.binding.jablotron/README.md
bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/JablotronBindingConstants.java
bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/handler/JablotronAlarmHandler.java
bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/handler/JablotronBridgeHandler.java
bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/handler/JablotronJa100FHandler.java
bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/model/JablotronAccessTokenData.java
bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/model/JablotronAccessTokenResponse.java
bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/model/JablotronHistoryDataEvent.java
bundles/org.openhab.binding.jablotron/src/main/resources/OH-INF/thing/oasis.xml
bundles/org.openhab.binding.jablotron/src/main/resources/OH-INF/update/update.xml

This PR fixes a Http 400 error while calling former endpoint for getting events history.
Moreover it adds a new channel lastEventSection for the good old JA-80 alarms, because Jablotron has unified access to the event history of all alarms.

[somfytahoma] Fix getting last history event

---

bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/devices/wifi/lightstrip/TapoLightStripHandler.java

Accept decimal, percent and on off on color channel. 
Accept on/off on brightness channel
Turn off if color channel received a HSB color with 0% brightness.

[tapocontrol] Accept more commands on dimmer/color channels

---

bundles/org.openhab.binding.casokitchen/src/test/java/org/openhab/binding/caso/internal/TestHandler.java

Locally always and sometimes by CI it passes, but most of the time it fails. I removed the part that causes the failure. It is probably due to some timeing issue that the state is not always as expected. 
```
[ERROR] org.openhab.binding.caso.internal.TestHandler.testConfigErrors -- Time elapsed: 0.091 s <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <UNKNOWN> but was: <ONLINE>
at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177) …
```

[casokitchen] Adjust flaky test

---

bundles/org.openhab.binding.homewizard/src/main/java/org/openhab/binding/homewizard/internal/devices/HomeWizardEnergyMeterMeasurementPayload.java
bundles/org.openhab.binding.homewizard/src/main/java/org/openhab/binding/homewizard/internal/devices/p1_meter/HomeWizardP1MeterMeasurementPayload.java
bundles/org.openhab.binding.homewizard/src/main/java/org/openhab/binding/homewizard/internal/devices/plug_in_battery/HomeWizardPlugInBatteryMeasurementPayload.java
bundles/org.openhab.binding.homewizard/src/main/java/org/openhab/binding/homewizard/internal/devices/water_meter/HomeWizardWaterMeterHandler.java
bundles/org.openhab.binding.homewizard/src/main/java/org/openhab/binding/homewizard/internal/devices/water_meter/HomeWizardWaterMeterMeasurementPayload.java
bundles/org.openhab.binding.homewizard/src/main/resources/OH-INF/i18n/homewizard.properties
bundles/org.openhab.binding.homewizard/src/main/resources/OH-INF/thing/hwe-kwh.xml
bundles/org.openhab.binding.homewizard/src/test/java/org/openhab/binding/homewizard/internal/devices/water_meter/HomeWizardWaterMeterMeasurementPayloadTest.java

Contains a fix for an incorrect thing type id for the kWh meter. 
In addition, it also contains fixes for errors in toString() in a couple of payload classes.

[homewizard] Fix for incorrect thing type id for kWh meter

---

bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyBaseHandler.java

To prevent shelly smoke sensors to go offline if they slightly exceed the reported wake up period (24 hours) the time limit is extended by 30 minutes for this kind of devices.
Fixes #17767

[shelly] Improve smoke sensor wake-up period handling

---

bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/parser/AbstractBaseParser.java

In 2020 the ACC32 fields were changed from unsigned int to signed, ref. #7826 . This is incorrect. The acc32 is an unsigned integer. On top of that, the sunspec meter handlers had values assigned with acc32 that are uint32 according to the sunspec specification.
https://sunspec.org/wp-content/uploads/2025/01/SunSpec-Device-Information-Model-Specificiation-V1-2-1-1.pdf
This is the latest specification from 2024. Here it is stated that: acc32 = Unsigned 32-bit accumulator (deprecated in favor of uint32)
Basically both acc32 and uint32 can have values from 0 to 4294967294 acc32 even until 4294967295, which is due to uint32 0xFFFFFFFF is specified as "not implemented".
See also https://community.openhab.org/t/modbus-sunspec-showing-negative-total-exported-energy/161611/13 for the bug.
Please …

[modbus.sunspec] Fix acc32 and uint32

---

bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/SqueezeBoxAudioSink.java
bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/SqueezeBoxBindingConstants.java
bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/SqueezeBoxHandlerFactory.java
bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/config/SqueezeBoxPlayerConfig.java
bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/discovery/SqueezeBoxPlayerDiscoveryService.java
bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/discovery/SqueezeBoxServerDiscoveryParticipant.java
bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxNotificationListener.java
bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxNotificationPlayer.java
bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxPlayerEventListener.java
bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxPlayerHandler.java
bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxPlayerPlayState.java
bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxPlayerState.java
bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxServerHandler.java
bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/model/Favorite.java
bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/utils/HttpUtils.java
bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/utils/SqueezeBoxCommunicationException.java
bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/utils/SqueezeBoxNotAuthorizedException.java
bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/utils/SqueezeBoxTimeoutException.java
bundles/org.openhab.binding.squeezebox/src/main/resources/OH-INF/i18n/squeezebox.properties
bundles/org.openhab.binding.squeezebox/src/main/resources/OH-INF/thing/thing-types.xml

Summary of all changes:
- Refactor the player discovery service to be based on `AbstractThingHandlerDiscoveryService` rather than `AbstractDiscoveryService` and thereby remove the manual life-cycle management in `SqueezeBoxHandlerFactory`.
- Add null annotations and fix warnings.
- Fix initialization of properties for manually configured Things.

[squeezebox] Fix properties for manually configured Things

---

bundles/org.openhab.binding.solarforecast/README.md
bundles/org.openhab.binding.solarforecast/src/main/resources/OH-INF/thing/sc-plane-type.xml
bundles/org.openhab.binding.solarforecast/src/main/resources/OH-INF/thing/sc-site-type.xml
bundles/org.openhab.binding.solarforecast/src/main/resources/OH-INF/thing/update-group.xml
bundles/org.openhab.binding.solarforecast/src/main/resources/OH-INF/update/instructions.xml

Fix channel typo and example mentioned in [community](https://community.openhab.org/t/solar-forecast-pv/137681/311)

[solarforecast] Fix `latest-update` channel typo

---

bundles/org.openhab.binding.plex/README.md

I've just noticed this channel missing from the doc. I can't really find a more comprehensive explanation, but at least it's now being listed in the doc.

[plex] Document the `user` channel

---

bundles/org.openhab.binding.solarforecast/src/main/resources/OH-INF/update/instructions.xml

Additional bugfix to the channel typo of solarforecast PR #18373. See possibilities regarding `thing type version`: 
0 | 1 | 2
--- | --- | ---
create | upgrade => _channel name correct_ | upgrade => **duplicate channel detected**
X | create => _channel name incorrect_ | upgrade => channel name corrected
X | X | create  => channel name correct
**Solution:**
Due to the fact that channel names of `thingtype version 1` maybe **correct or incorrect** remove both channels and add correct one.

[solarforecast] Bugfix channel typo

---

bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/JRubyScriptEngineConfiguration.java

If a script (or a library it calls) accidentally calls Process.exec, it will immediately terminate all of openHAB. That is bad. An example is Bundler trying to shell out to `man` to display its help page.

[jrubyscripting] Disallow Process.exec

---

bundles/org.openhab.binding.easee/README.md

This PR fixes an incorrect channel name in the example documented in the Readme. This avoids new users, who copy and use the example code, to bump into an issue with an incorrect link.
This is purely a documentation-related bugfix.

[easee] Fixing incorrect channel name in example

---

bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/internal/handler/TadoHandlerFactory.java

Since https://github.com/openhab/openhab-addons/pull/18354 now when you disable and re-enable the Home Thing, it requires a restart of OH before the Thing comes online again. This PR fixes that regression.
Fixes #18418

[tado] fix regression

---

bundles/org.openhab.automation.jsscripting/bnd.bnd
bundles/org.openhab.automation.jsscripting/pom.xml
bundles/org.openhab.automation.jsscripting/src/main/feature/feature.xml

Depends on https://github.com/openhab/openhab-osgiify/pull/59.
Changelog: https://github.com/oracle/graaljs/blob/master/CHANGELOG.md#version-2420

[jsscripting] Upgrade GraalJS to 24.2.0

---

bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/DanfossAirUnitBindingConstants.java
bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/DanfossAirUnitCommunicationController.java
bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/discovery/DanfossAirUnitDiscoveryService.java
bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/handler/DanfossAirUnitHandler.java
bundles/org.openhab.binding.danfossairunit/src/main/resources/OH-INF/thing/thing-types.xml

This eliminates inbox results for already configured Things.
Additionally, the suggested Thing ID is now compliant with `.things` file configuration by avoiding "-" as first character in ID. See openhab/openhab-core#4652.
A downside is that discovery now need to be able to connect to the unit to get the serial number. This is not possible while another connection to the unit is already established. However, the disovered Thing would not be able to come online anyway while such other connection exists.

[danfossairunit] Use serial number as valid Thing ID in discovery

---

bundles/org.openhab.binding.danfossairunit/README.md
bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/DanfossAirUnit.java
bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/DanfossAirUnitConfiguration.java
bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/DanfossAirUnitHandlerFactory.java
bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/FixedTimeZoneProvider.java
bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/handler/DanfossAirUnitHandler.java
bundles/org.openhab.binding.danfossairunit/src/main/resources/OH-INF/i18n/danfossairunit.properties
bundles/org.openhab.binding.danfossairunit/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.danfossairunit/src/test/java/org/openhab/binding/danfossairunit/internal/DanfossAirUnitTest.java

The time zone used for converting from local time for the `current_time` channel has been changed from **system** time zone to **openHAB** time zone.
Neither of these assumptions about the air unit time zone are bullet-proof, so addtionally an advanced configuration parameter for explicitly setting the time-zone has been introduced.

[danfossairunit] Improve time zone handling

---

bundles/org.openhab.binding.tacmi/README.md
bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/TACmiBindingConstants.java
bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/TACmiHandlerFactory.java
bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/json/Config.java
bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/json/TACmiJsonHandler.java
bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/json/obj/Data.java
bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/json/obj/Header.java
bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/json/obj/IO.java
bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/json/obj/JsonResponse.java
bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/json/obj/Value.java
bundles/org.openhab.binding.tacmi/src/main/resources/OH-INF/i18n/tacmi.properties
bundles/org.openhab.binding.tacmi/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.tacmi/src/test/java/org/openhab/binding/tacmi/internal/json/obj/test/DeSer.java
bundles/org.openhab.binding.tacmi/src/test/resources/ex.json

This implementation is based on the JSON-API provided by TA.
The API is provided here: https://wiki.ta.co.at/C.M.I._JSON-API

[tacmi] Support JSON-Api

---

bundles/org.openhab.binding.wundergroundupdatereceiver/src/main/java/org/openhab/binding/wundergroundupdatereceiver/internal/WundergroundUpdateReceiverHandler.java
bundles/org.openhab.binding.wundergroundupdatereceiver/src/test/java/org/openhab/binding/wundergroundupdatereceiver/internal/WundergroundUpdateReceiverDiscoveryServiceTest.java
bundles/org.openhab.binding.wundergroundupdatereceiver/src/test/java/org/openhab/binding/wundergroundupdatereceiver/internal/WundergroundUpdateReceiverServletTest.java

The parameter is formatted with 1 digit hours, spewing warnings into the log, but otherwise having no effects, as normal last XXX values are also recorded.
Additionally a couple of unnoticed capitalisations were corrected.

[wundergroundupdatereceiver] Fix parsing of dateutc query parameter

---

bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/charts/RRD4jChartServlet.java

https://github.com/openhab/openhab-core/pull/4610 introduced an interpolation parameter for charts.
rrd4j persistence has its own chart servlet that implements the core chart provider interface. I am not  even sure it is still used anywhere as core has an implementation of a chart servlet and that is used for sitemaps. Anyway, to make the build work, the rrd4j chart servlet needs to have an extra parameter.

[rrd4j] Fix chart servlet build

---

bundles/org.openhab.binding.tado/README.md
bundles/org.openhab.binding.tado/pom.xml
bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/internal/api/HomeApiFactory.java
bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/internal/auth/OAuthorizerV2.java
bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/internal/config/TadoHomeConfig.java
bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/internal/handler/TadoHandlerFactory.java
bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/internal/handler/TadoHomeHandler.java
bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/internal/servlet/TadoAuthenticationServlet.java
bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/swagger/codegen/api/ApiException.java
bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/swagger/codegen/api/client/HomeApi.java
bundles/org.openhab.binding.tado/src/main/resources/OH-INF/i18n/tado.properties
bundles/org.openhab.binding.tado/src/main/resources/OH-INF/thing/thing-types.xml

Backport of: https://github.com/openhab/openhab-addons/pull/18354
The Jar file for testing is here (but it requires the latest patch OH v4.3.4 or greater).
[org.openhab.binding.tado-4.3.4-SNAPSHOT.zip](https://github.com/user-attachments/files/19428314/org.openhab.binding.tado-4.3.4-SNAPSHOT.zip)

[tado] OAuth RFC-8628 authentication work flow

---

bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/discovery/SatelDeviceDiscoveryService.java
bundles/org.openhab.binding.satel/src/test/java/org/openhab/binding/satel/internal/discovery/SatelDeviceDiscoveryServiceTest.java
bundles/org.openhab.binding.satel/src/test/java/org/openhab/binding/satel/internal/handler/SatelEventLogHandlerTest.java

This PR fixes discovery of roller shutter devices. For some reason it has been disabled.
It also contains the following changes:
- removed discovery of devices that are not supported,
- switch statements replaced with switch expressions,
- added unit test for discovery service,
- other minor code refactoring.

[satel] Discovery fix for roller shutter things, other minor changes

---

bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/JRubyScriptEngineConfiguration.java

This allows the helper library to have a dependency on the openHAB version, allowing us to drop support for older openHAB versions without doing a major version bump (and thus possibly requiring the user to make changes to their config to get a new major version).
Ideally this will be backported to 4.3, so that we're able to do the helper library change sooner. This will have no effect on 4.3 with the current helper library, since it has no dependency on the "openhab" gem. https://github.com/ccutrer/openhab-jruby/commit/9bfbdc99babd191e2efc6c1eccdfaa55e11fda45 is the helper library change that will lock out any version of openHAB that doesn't have _this_ PR.

[jrubyscripting] Add "dummy" openHAB gem to environment

---

bundles/org.openhab.binding.bambulab/src/main/java/org/openhab/binding/bambulab/internal/AmsDeviceHandler.java
bundles/org.openhab.binding.bambulab/src/main/java/org/openhab/binding/bambulab/internal/BambuLabBindingConstants.java
bundles/org.openhab.binding.bambulab/src/main/java/org/openhab/binding/bambulab/internal/BambuLabHandlerFactory.java
bundles/org.openhab.binding.bambulab/src/main/java/org/openhab/binding/bambulab/internal/Camera.java
bundles/org.openhab.binding.bambulab/src/main/java/org/openhab/binding/bambulab/internal/PrinterHandler.java
bundles/org.openhab.binding.bambulab/src/main/java/org/openhab/binding/bambulab/internal/StateParserHelper.java
bundles/org.openhab.binding.bambulab/src/main/java/org/openhab/binding/bambulab/internal/TrayHelper.java
bundles/org.openhab.binding.bambulab/src/main/resources/OH-INF/i18n/bambulab.properties
bundles/org.openhab.binding.bambulab/src/main/resources/OH-INF/thing/channel-types.xml
bundles/org.openhab.binding.bambulab/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.bambulab/src/test/java/org/openhab/binding/bambulab/internal/PrinterHandlerTest.java
bundles/org.openhab.binding.bambulab/src/test/java/org/openhab/binding/bambulab/internal/StateParserHelperTest.java
bundles/org.openhab.binding.bambulab/src/test/java/org/openhab/binding/bambulab/internal/TrayHelperTest.java

_As this is a new binding not part of a milestone, upgrade instructions are not needed._
[bambulab] Support `REFRESH` command for all channels
Previously the refresh command was not supported, now all channels from the printer refreshes it's self when receiving command.

[bambulab] Support `REFRESH` command for all channels

---

bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/handler/InsteonBaseThingHandler.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/handler/InsteonSceneHandler.java

This fixes an issue where scene channels would not respond to commands after a modem db reload was initiated from the console. The root cause was that these channels would remain linked to the previous `InsteonModem` object prior to the reload, and never got relinked to the new one.

[insteon] Fix scene channels not responding after modem db reload

---

bundles/org.openhab.binding.insteon/README.md
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/InsteonScene.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/LinkManager.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/database/LinkDB.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/database/ModemDB.java
bundles/org.openhab.binding.insteon/src/main/resources/OH-INF/thing/scene.xml

The change improves the way the modem db tracks the default controller group by using the database information to determine that value instead of having a static interval.

[insteon] Improve modem db default controller group support

---

bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/handler/DanfossAirUnitHandler.java

Previously, when linking a new item to a channel, the state update could be delayed by up to one minute.
This occurred because all channels (not just linked ones) were updated and cached. As a result, when an item was newly linked, its state was already present in the cache, preventing an immediate update and deferring it until the next state change or cache timeout.
This fix ensures that the state is updated immediately upon linking.

[danfossairunit] Ensure immediate channel update after item linking

---

bundles/org.openhab.persistence.jdbc/pom.xml
bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcPersistenceService.java
bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcBaseDAO.java

Upgrade Yank with related dependencies:
- Updated to [Hikari-CP 5.1.0](https://github.com/brettwooldridge/HikariCP/blob/dev/CHANGES).
- Updated to [commons-dbutils 1.8.1](https://commons.apache.org/proper/commons-dbutils/changes-report.html).
brettwooldridge/HikariCP@5f3c97702facbdd09e91632324d26e952b4cc62c dropped support for `Properties` defaults in HikariCP 2.4.9, therefore `getConnectionProperties` had to be adapted.

[jdbc] Upgrade Yank to 3.5.0

---

bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java

Closes https://github.com/openhab/openhab-addons/issues/18475
See https://github.com/openhab/openhab-addons/pull/18308
The previous fix for rrd4j restore on startup did not work in all cases. Tests when stopping and immediatly restarting OH succeeded, but waiting a while and restarting would not restore, or would restore the wrong value.
The main problem was that rrd4j did not allow descending queries beyond a single datapoint. This is not just a restore on startup issue, but would also impact the `previousChange` persistence extension method.
This PR allows queries with descending ordering with no start date, but will limit the query to the data returned to data in the current archive.
The restore on startup (`persistedItem`) logic has been made more efficient, not calling the `query` …

[rrd4j] restore on startup and descending queries

---

bundles/org.openhab.io.metrics/pom.xml
bundles/org.openhab.io.metrics/src/main/java/org/openhab/io/metrics/MetricsRestController.java
bundles/org.openhab.io.metrics/src/main/java/org/openhab/io/metrics/exporters/InfluxMetricsExporter.java
bundles/org.openhab.io.metrics/src/main/java/org/openhab/io/metrics/exporters/JmxMetricsExporter.java

Depends on openhab/openhab-core#4639
* Adapt to core change, i.e.
* metrics-core from 4.0.7 to 4.2.30
* micrometer-core from 1.6.3 to 1.14.4
* HdrHistogram from 2.1.12 to 2.2.2
* Upgrade prometheus metrics from 0.9.0 to 1.3.6 This includes upgrade of client API from v0 to v1.
Changelog: https://github.com/prometheus/client_java/releases

[metrics] Upgrade dependencies

---

bundles/org.openhab.binding.argoclima/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.casokitchen/src/main/resources/OH-INF/thing/channel-types.xml
bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/thing/group-thing-types.xml
bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/thing/light-thing-types.xml
bundles/org.openhab.binding.fineoffsetweatherstation/src/main/resources/OH-INF/thing/gateway.xml
bundles/org.openhab.binding.plugwiseha/src/main/resources/OH-INF/thing/channels.xml
bundles/org.openhab.binding.wiz/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.wundergroundupdatereceiver/src/main/resources/OH-INF/thing/channel-types.xml

This PR fixes some xml schema validation errors in several addons as follows:
- ArgoClima
- CasoKitchen
- Deconz
- FineOffsetWeatherStation
- PlugWiseHA
- Wiz
- WunderGroundUpdateReceiver
See https://github.com/openhab/openhab-core/pull/4615#issuecomment-2776036635
Note: it depends on two other PRs  to add some missing PROPERTY tags `Speed` and `AirQuality` 
- https://github.com/openhab/openhab-core/pull/4695 to add the missing tags
- https://github.com/openhab/openhab-core/pull/4626 to inject the tags into the XSD file

[various] Fix xml validation errors

---

bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/config/config.xml
bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/i18n/energidataservice.properties
bundles/org.openhab.binding.energidataservice/src/main/resources/filters/grid_tariffs.yaml

Price list as PDF here: https://www.forsyningelnet.dk/wp-content/uploads/2025/02/1_januar_til_31_december_2025_-_aarsforbrug_0_-_50000_kWh.pdf
Query: https://api.energidataservice.dk/dataset/DatahubPricelist?offset=0&filter=%7B%22GLN_Number%22:[%225790001088309%22],%22ChargeType%22:[%22D03%22],%22ChargeTypeCode%22:[%22STR-NT-03%22],%22Note%22:[%22Nettarif%20C%22]%7D&sort=ValidFrom%20DESC

[energidataservice] Add tariff filter for Forsyning Elnet

---

bundles/org.openhab.binding.asuswrt/src/main/java/org/openhab/binding/asuswrt/internal/api/AsuswrtConnector.java

Router does not recover when if there are issues with the network.  When a connection failure happens, the router status was set to UNKOWN and the "reconnectJob" only attempts to reconnect if the status is OFFLINE.
This PR sets the status to OFFLINE in the event of a network failure (instead of UNKNWOWN).  This could have also been fixed by attempting to reconnect if the status was either OFFLINE or UNKNOWN, however I chose this change as I thought  it was less intrusive since the UNKOWN state is used as the initial state on init.
@wildcs, could you provide feedback.

[asuswrt] Fixed issue where reconnectJob does not try to reconnect (#18456)

---

bundles/org.openhab.automation.jrubyscripting/pom.xml
bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/JRubyConsoleCommandExtension.java

I'm not sure why the distro addon failed to detect `console instanceof org.openhab.core.io.console.karaf.OSGiConsole`. 
I didn't experience this issue with a custom built jar.
Trying a different approach by moving this into Ruby.

[jrubyscripting] Move console instance check from Java to Ruby code

---

bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/JRubyConsoleCommandExtension.java
bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/JRubyScriptEngineConfiguration.java
bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/JRubyScriptEngineFactory.java
bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/watch/BidiSetBag.java
bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/watch/JRubyScriptFileWatcher.java
bundles/org.openhab.automation.jrubyscripting/src/main/resources/OH-INF/config/config.xml
bundles/org.openhab.automation.jrubyscripting/src/main/resources/OH-INF/i18n/jrubyscripting.properties

- By default, if `bundle_gemfile` (default: `CONF/automation/ruby/Gemfile`) exists:
- the `gems` setting will be ignored
- Execute bundle install / bundle update (depending on `check_update` setting) on startup/config updates
- Bundler.setup + require will be executed on user script startups
- If Gemfile doesn't exist, continue with the original gems handling
- `require` continues to be executed regardless
- the console command `jrubyscripting bundle init` can be used to create a new Gemfile and it inserts
```
gem "openhab-scripting", "~> 5.0"
```
- https://github.com/openhab/openhab-jruby/pull/428 will provide the default require file
The configuration system has been refactored to support the use of multiline / List configuration, to support entering UI Gemfile but that idea is dropped …

[jrubyscripting] Support using Gemfile with Bundler

---

bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/ShellyBluApi.java

The BLU devices send packets, but the packet ID resets to 0 after 254. This fix accounts for that reset. It also accounts for the situation where one or more packets have not been received by the binding. If the logic is that the reset is only accepted if the last received packet has ID 254, and if that packet was never received, the reset is not accepted, and the functionality breaks.
The value of 50 for `pidCycleThreshold` is obviously arbitrary, but I figured a packed with such an old PID seems unlikely to still be floating around.
Relevant discussion: https://community.openhab.org/t/shelly-binding/56862/4182.

[shelly] Fix BLU package cycle fix

---

bundles/org.openhab.binding.kaleidescape/README.md
bundles/org.openhab.binding.kaleidescape/src/main/resources/OH-INF/thing/channels.xml
bundles/org.openhab.binding.kaleidescape/src/main/resources/OH-INF/update/instructions.xml

Add semantic tags on kaleidescape Things and Channels.
Also format all time channels, i.e. title_length, title_loc, etc. as a time value rather than seconds.

[kaleidescape] Add semantic tags and format time channels

---

bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/virtual/ButtonVirtualDatapointHandler.java
bundles/org.openhab.binding.homematic/src/test/java/org/openhab/binding/homematic/internal/communicator/virtual/ButtonDatapointTest.java

When starting a long press right after a short press, the short press wrongly was emitted twice.
Reported in the forum: https://community.openhab.org/t/homematic-ip-wired-virtual-datapoints-of-buttons-long-press-fires-short-pressed-command/163673

[homematic] Fix HM-IP long press button handling

---

bundles/org.openhab.binding.bluetooth.bluegiga/src/main/java/org/openhab/binding/bluetooth/bluegiga/handler/BlueGigaBridgeHandler.java

I had the following exception in my logs during startup:
```
16:10:36.282 [WARN ] [luegiga.handler.BlueGigaBridgeHandler] - Error initializing bluegiga
java.util.concurrent.CompletionException: java.util.NoSuchElementException: No value present
at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179) ~[?:?]
at org.openhab.binding.bluetooth.util.RetryFuture$CallableTask.run(RetryFuture.java:67) ~[?:?] …
```

[bluetooth.bluegiga] Fix NoSuchElementException during initialization

---

pom.xml
src/thing-type-xml-validation-catalog.xml

I went to great extents to modify the thing-description xml schema to be stricter in validating semantic tags against pre-defined allowed values. But then I discovered that the standard Maven build process does not actually do any xml schema validation at all. Maybe it was deleted at some time? Anyway this PR adds back the schema validation.

Maven Build: Validate Thing-type XML against schema

---

bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/provider/ElectricityPriceProvider.java
bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/provider/cache/DatahubPriceSubscriptionCache.java
bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/provider/cache/ElectricityPriceSubscriptionCache.java
bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/provider/cache/SpotPriceSubscriptionCache.java
bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/provider/cache/SubscriptionDataCache.java
bundles/org.openhab.binding.energidataservice/src/test/java/org/openhab/binding/energidataservice/internal/provider/cache/SpotPriceSubscriptionCacheTest.java

This is some preliminary work in preparation for spot prices in 15-minute resolution.

[energidataservice] Add support for variable spot price resolution

---

bundles/org.openhab.persistence.jdbc/README.md
bundles/org.openhab.persistence.jdbc/pom.xml
bundles/org.openhab.persistence.jdbc/src/main/feature/feature.xml
bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcConfiguration.java

Release notes:
- https://dev.mysql.com/doc/relnotes/connector-j/en/
Library:
- https://mvnrepository.com/artifact/com.mysql/mysql-connector-j/9.2.0
Previous upgrade: #16132

[jdbc] Upgrade MySQL Connector/J to 9.2.0

---

pom.xml

* Fix failing validation in submodules (regression, #18579)
* Skip schema validation when -DskipChecks is set
@andrewfg FYI
This fixes the broken build when run in a subdirectory for a specific add-on (second issue mentioned in https://github.com/openhab/openhab-addons/pull/18579#issuecomment-2816735359)
Though, it still validates all xml files when run on top level with `-pl` for a specific add-on.

Improve XML schema validation

---

bundles/org.openhab.binding.danfossairunit/src/main/resources/OH-INF/thing/thing-types.xml

Awaiting new XSD for validation (openhab/website#511) and Main UI support for testing (openhab/openhab-webui#3124).

[danfossairunit] Add semantic equipment tag

---

bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/handler/HomeAssistantThingHandler.java

When the thing config changes, core will dispose of the handler, and then immediately initialize the exact same object again. If we don't clear the internal data, we'll find conflicts, and cause channels to be renamed unnecessarily. I believe this also fixes an issue that I'm never able to remove topics from the config, even though they no longer exist.
Closes #18278 and #18494

[mqtt.homeassistant] Clear internal data when stopping

---

bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/provider/cache/SpotPriceSubscriptionCache.java

4.3.x backport: Cherry-picks #18588 with conflict resolution (adjacent import removed in #18379).

[energidataservice] Fix `NullPointerException`

---

bundles/org.openhab.binding.emotiva/README.md
bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/EmotivaBindingConstants.java
bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/EmotivaProcessorHandler.java
bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/EmotivaUdpBroadcastService.java
bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/EmotivaUdpReceivingService.java
bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/EmotivaUdpSendingService.java
bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/dto/EmotivaBarNotifyDTO.java
bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/protocol/EmotivaDataType.java
bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/protocol/EmotivaSubscriptionTags.java
bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/protocol/EmotivaXmlUtils.java
bundles/org.openhab.binding.emotiva/src/main/resources/OH-INF/i18n/emotiva.properties

Fixes #18468.
* Improves handling of keep alive poll job.
* Bumps default Emotiva protocol version to 3.0.
* Add documentation about opening of ports, protocol versions and keep alive.
Has been tested on 4.3.x and 5.0.0-SNAPSHOT. Backporting should be possible, and probably disariable to avoid this issue for users.

[emotiva] Fix keep alive when adding devices manually

---

pom.xml

As [discussed here](https://community.openhab.org/t/californium-removed/163625/40) there's an error preventing building from Eclipse since #18579.
`xml-maven-plugin` doesn't seem to have its own M2E "configuration", which leads to an error from M2E when encountering this plugin. Since the plugin is used for XML validation, which isn't needed for Eclipse builds, the solution here is to simply tell M2E to ignore the plugin.
According to my testing, this solves the issue.

Fix xml-maven-plugin error in Eclipse since #18579

---

bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/discovery/LeapDeviceDiscoveryService.java
bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/LeapBridgeHandler.java
bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/protocol/leap/LeapMessageParser.java
bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/protocol/leap/LeapMessageParserCallbacks.java
bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/protocol/leap/Request.java
bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/protocol/leap/dto/Device.java
bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/protocol/leap/dto/LeapRequest.java
bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/protocol/leap/dto/Zone.java
bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/protocol/leap/dto/ZoneExpanded.java

The current implementation would discover and add Things to the "Inbox" using only the integration ID.  For RA3 devices the name is buried with the Area & Zone.  This provides the ability to see what has been discovered based on the names of the Area, if defined, and Zone.  
I have this currently running on my home system with Dimmer, Switches and Occupancy Sensors.  The binding currently doesn't support RA2 RadioSavr Sensors working outside of OccupancyGroups.

[lutron] Provides device location and names during discovery

---

CODEOWNERS

I'm proposing to add myself as maintainer of the Grundfos binding after contributing support for the Alpha3 pump: #18187
Please do not merge without approval from @tisoft who originally contributed the binding: #15907

[grundfosalpha] Add myself as code owner for Alpha3

---

bundles/org.openhab.binding.nest/README.md

Makes the documentation examples less real as it causes false positives in some secret scans.
---
See: https://github.com/openhab/openhab-addons/pull/12602/files/d737e7b3f3f2f73334651a26dad7bc7d2da35617#r2058192732
Does it still trigger your secrets scan with these changes @kaikreuzer?

[nest] Change examples to prevent secret scan false positives

---

bundles/org.openhab.automation.groovyscripting/README.md
bundles/org.openhab.automation.groovyscripting/pom.xml

Upgrades Groovy from 4.0.23 to 4.0.26.
* https://groovy-lang.org/changelogs/changelog-4.0.24.html
* https://groovy-lang.org/changelogs/changelog-4.0.25.html
* https://groovy-lang.org/changelogs/changelog-4.0.26.html

[groovyscripting] Upgrade Groovy to 4.0.26

---

bundles/org.openhab.binding.boschshc/README.md

This is a follow-up PR for #18326.
The documentation update was kindly provided by github user @hofingerandi.

[boschshc] Update pairing documentation for Smart Home Controller II

---

bundles/org.openhab.binding.tuya/src/main/resources/schema.json

This PR adds support for the PAUTIX HH-1201K3E Controller.

[tuya] add schema for PAUTIX WiFi/Bluetooth LED Controller

---

bundles/org.openhab.binding.tuya/src/main/java/org/openhab/binding/tuya/internal/cloud/dto/DeviceSchema.java
bundles/org.openhab.binding.tuya/src/main/java/org/openhab/binding/tuya/internal/handler/TuyaDeviceHandler.java
bundles/org.openhab.binding.tuya/src/main/java/org/openhab/binding/tuya/internal/util/SchemaDp.java

As per smarthomej tuya binding changes.
Allow schemas to provide labels for Channels and if none is provided map the code to something reasonably presentable.
It may seem like Channel labels are something of an internal detail in openHAB but they are used in generating the default names of linked Items and thence to places likely to be exposed to users.
(Only affects newly added Things. Existing Things keep using what they have.)

[tuya] Get channel labels from schema label or map from schema code

---

bundles/org.openhab.automation.pythonscripting/src/main/java/org/openhab/automation/pythonscripting/internal/PythonScriptEngine.java
bundles/org.openhab.automation.pythonscripting/src/main/java/org/openhab/automation/pythonscripting/internal/PythonScriptEngineFactory.java

The goal of this pull request is to fix the helper lib deployment on windows.
The main problem was the usage of PosixPermissions before. Now, everything is handled in a more generic way.
In addition, a warning about missing TruffleAttachLibrary is ignored. It will never be available, except we are using the graalvm directly.
The fix was already tested by @jlaur 
@wborn &  @florian-h05 could one of you please review and approve please?

[pythonscripting] Fix helper lib deployment on Windows

---

CODEOWNERS
bom/openhab-addons/pom.xml
bundles/org.openhab.binding.froniuswattpilot/NOTICE
bundles/org.openhab.binding.froniuswattpilot/README.md
bundles/org.openhab.binding.froniuswattpilot/pom.xml
bundles/org.openhab.binding.froniuswattpilot/src/main/feature/feature.xml
bundles/org.openhab.binding.froniuswattpilot/src/main/java/org/openhab/binding/froniuswattpilot/internal/FroniusWattpilotBindingConstants.java
bundles/org.openhab.binding.froniuswattpilot/src/main/java/org/openhab/binding/froniuswattpilot/internal/FroniusWattpilotConfiguration.java
bundles/org.openhab.binding.froniuswattpilot/src/main/java/org/openhab/binding/froniuswattpilot/internal/FroniusWattpilotHandler.java
bundles/org.openhab.binding.froniuswattpilot/src/main/java/org/openhab/binding/froniuswattpilot/internal/FroniusWattpilotHandlerFactory.java
bundles/org.openhab.binding.froniuswattpilot/src/main/java/org/openhab/binding/froniuswattpilot/internal/FroniusWattpilotMDNSDiscoveryServiceParticipant.java
bundles/org.openhab.binding.froniuswattpilot/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.froniuswattpilot/src/main/resources/OH-INF/i18n/froniuswattpilot.properties
bundles/org.openhab.binding.froniuswattpilot/src/main/resources/OH-INF/thing/thing-types.xml
bundles/pom.xml

This adds a new binding that allows to integrate Fronius Wattpilot wallboxes into openHAB.
It has been tested with the following models:
- Fronius Wattpilot Home 11J (tested by @sihui62)
- Fronius Wattpilot Home 22J (tested myself)

[froniuswattpilot] Initial contribution

---

.github/workflows/ci-build.yml
.github/workflows/rebuild.yml

* Move triggering rebuild on label to separate workflow
```
#
#
```
* Grant permissions for removing label
Due to our default settings on this repo, changing PR labels is not possible from Actions:
```
Run gh pr edit $PR --remove-label rebuild
GraphQL: Resource not accessible by integration (removeLabelsFromLabelable)
Error: Process completed with exit code 1.
```
This PR adds the necessary permissions for `GITHUB_TOKEN` used by the `gh` tool to remove the label.

[GHA] Adapt rebuild

---

bundles/org.openhab.automation.pythonscripting/pom.xml
bundles/org.openhab.automation.pythonscripting/src/main/java/org/openhab/automation/pythonscripting/internal/PythonScriptEngine.java

This fixes the mapping between a python timedelta to java Duration mapping
@jlaur can you please review?

[pythonscripting] Fix python timedelta to java duration mapping

---

bundles/org.openhab.binding.weatherunderground/src/main/resources/OH-INF/thing/bridge.xml

Make it consistent with openweathermap binding.

[weatherunderground] Fix equipment tag

---

bundles/org.openhab.binding.freeathome/src/main/java/org/openhab/binding/freeathome/internal/configuration/FreeAtHomeBridgeHandlerConfiguration.java
bundles/org.openhab.binding.freeathome/src/main/java/org/openhab/binding/freeathome/internal/datamodel/FreeAtHomeDeviceChannel.java
bundles/org.openhab.binding.freeathome/src/main/java/org/openhab/binding/freeathome/internal/handler/FreeAtHomeBridgeHandler.java
bundles/org.openhab.binding.freeathome/src/main/java/org/openhab/binding/freeathome/internal/handler/FreeAtHomeDeviceHandler.java
bundles/org.openhab.binding.freeathome/src/main/java/org/openhab/binding/freeathome/internal/util/FidTranslationUtils.java
bundles/org.openhab.binding.freeathome/src/main/java/org/openhab/binding/freeathome/internal/util/FreeAtHomeHttpCommunicationException.java
bundles/org.openhab.binding.freeathome/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.freeathome/src/main/resources/OH-INF/i18n/freeathome.properties
bundles/org.openhab.binding.freeathome/src/main/resources/OH-INF/i18n/freeathomesystem.properties
bundles/org.openhab.binding.freeathome/src/main/resources/OH-INF/thing/bridge-type.xml

- Enhancement: Added support for Wireless Blind Actuator devices
- Enhancement: Added keep-alive message option, improved error handling, and enhanced reconnect behavior in the FreeAtHome binding
- Improved (re)connection handling: A SysApp restart is now correctly managed, and a disconnected SysApp is properly detected.
- Added sendPing() as an alternative to sendString().
fixes:
https://github.com/openhab/openhab-addons/issues/18440
https://github.com/openhab/openhab-addons/issues/18441
Community:
https://community.openhab.org/t/abb-busch-jager-free-home-official-rest-api/141698/165
Signed-off-by: Martin Littkovsky <2018turtle@proton.me>

[freeathome] Add Wireless Blind Actuator support, Improve connection handling

---

bundles/org.openhab.automation.jsscriptingnashorn/pom.xml

Upgrades Nashorn from 15.4 to 15.6.
https://github.com/openjdk/nashorn/blob/main/CHANGELOG.md

[jsscriptingnashorn] Upgrade Nashorn to 15.6

---

bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/handler/EnergiDataServiceHandler.java
bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/provider/ElectricityPriceProvider.java
bundles/org.openhab.binding.energidataservice/src/test/java/org/openhab/binding/energidataservice/internal/provider/ElectricityPriceProviderTest.java

Fixes the underlying issue of #18583.
The previously provided fix caused the event to be triggered before updating the time series. Additionally, although it fixed the event in the specific scenario where a Thing action would trigger successful spot price updates, it did not make sure to update the time series in this case.
Now, Thing actions will not cause any unplanned requests, unless they are made for a subscription without any listeners. Otherwise only already cached prices will be returned, and the already applied retry policy will make sure to request prices when appropriate, and notify all listeners on success.

[energidataservice] Fix `DAY_AHEAD_AVAILABLE` event

---

bundles/org.openhab.automation.jsscripting/README.md
bundles/org.openhab.automation.jsscripting/pom.xml

For changelog see https://github.com/openhab/openhab-js/blob/main/CHANGELOG.md#5110.

[jsscripting] Upgrade openhab-js to 5.11.0

---

bundles/org.openhab.binding.tuya/src/main/java/org/openhab/binding/tuya/internal/TuyaBindingConstants.java
bundles/org.openhab.binding.tuya/src/main/java/org/openhab/binding/tuya/internal/handler/TuyaDeviceHandler.java

Retain the order of DPs in schemas so that Channels are created in consistent order. Remote schemas seem to be ordered by DP id, local schemas are ordered however whoever added them thought was logical.

[tuya] Order Channels using DP order in schemas

---

bundles/org.openhab.binding.ecovacs/src/main/java/org/openhab/binding/ecovacs/internal/api/commands/SpotAreaCleaningCommand.java

The device wants the list of rooms to clean in the form `1,1;1,5;1,2`, while we previously sent `1,1;5;2`.

[ecovacs] Fix spot area cleaning for X2 and newer

---

bundles/org.openhab.binding.lgtvserial/README.md
bundles/org.openhab.binding.lgtvserial/src/main/java/org/openhab/binding/lgtvserial/internal/protocol/serial/commands/BaseOnOffInvertCommand.java
bundles/org.openhab.binding.lgtvserial/src/main/java/org/openhab/binding/lgtvserial/internal/protocol/serial/commands/VolumeMuteCommand.java
bundles/org.openhab.binding.lgtvserial/src/main/java/org/openhab/binding/lgtvserial/internal/protocol/serial/responses/OnOffResponse.java

Fix the issue with the `volume-mute` channel being inverted relative to the actual mute state on the TV. Confusingly the API reports a state of 00 when the mute is on and 01 when the mute is off. This is opposite to how other states such as the power state are reported. With this change the volume is muted when the switch is on and not muted when the switch is off.

[lgtvserial] Fix inverted Volume Mute switch

---

.github/workflows/rebuild.yml

carryover from openhab/openhab-core#4808 - it seems it finally works fine now for core....
Rebuild still did not work on PRs from forked repost.
This is to protect the repo from malicious PRs.
The way to do it is basically, to use the `pull_request_target` instead of `pull_request` (which always runs on read-only permissions).
This needs to be done carefully, see
https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/
Permissions have been reduced to the necessary ones. Persistence of checkout credentials has been disabled.
Regression of 
#18596
#18629
#18632

[GHA] Permit rebuild from forks

---

bundles/org.openhab.automation.jsscripting/pom.xml

This includes a fix for a regression from 5.11.0.

[jsscripting] Upgrade openhab-js to 5.11.1

---

bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/InsteonModem.java
bundles/org.openhab.binding.insteon/src/main/resources/device-products.xml

This change adds support for Insteon 2448A7 USB adapter (different versions) by setting its device type to `NetworkBridge_PLM`.
Fixes: #18649

[insteon] Set device type for usb adapter as plm network bridge

---

bundles/org.openhab.binding.tuya/src/main/java/org/openhab/binding/tuya/internal/TuyaDiscoveryService.java
bundles/org.openhab.binding.tuya/src/main/java/org/openhab/binding/tuya/internal/local/CommandType.java
bundles/org.openhab.binding.tuya/src/main/java/org/openhab/binding/tuya/internal/local/ProtocolVersion.java
bundles/org.openhab.binding.tuya/src/main/java/org/openhab/binding/tuya/internal/local/TuyaDevice.java
bundles/org.openhab.binding.tuya/src/main/java/org/openhab/binding/tuya/internal/local/UdpDiscoveryListener.java
bundles/org.openhab.binding.tuya/src/main/java/org/openhab/binding/tuya/internal/local/UdpDiscoverySender.java
bundles/org.openhab.binding.tuya/src/main/java/org/openhab/binding/tuya/internal/local/handlers/TuyaDecoder.java
bundles/org.openhab.binding.tuya/src/main/java/org/openhab/binding/tuya/internal/local/handlers/TuyaEncoder.java
bundles/org.openhab.binding.tuya/src/main/java/org/openhab/binding/tuya/internal/local/handlers/TuyaMessageHandler.java
bundles/org.openhab.binding.tuya/src/main/java/org/openhab/binding/tuya/internal/local/handlers/UdpBroadcastHandler.java
bundles/org.openhab.binding.tuya/src/main/java/org/openhab/binding/tuya/internal/util/CryptoUtil.java
bundles/org.openhab.binding.tuya/src/main/java/org/openhab/binding/tuya/internal/util/NetworkUtil.java
bundles/org.openhab.binding.tuya/src/main/resources/OH-INF/thing/thing-types.xml
bundles/org.openhab.binding.tuya/src/test/java/org/openhab/binding/tuya/internal/util/CryptoUtilTest.java

Add support for the 3.5 protocol version. This was merged into the Smarthome/J version of the Tuya binding but only after the openhab-addons version had been created. Since Tuya has been removed from Smarthome/J in favour of the openhab-addons version it's kind of important that we don't lose this!

[tuya] Add support for protocol version 3.5

---

bundles/org.openhab.binding.teslapowerwall/src/main/java/org/openhab/binding/teslapowerwall/internal/api/SystemStatus.java

The last commit for teslapowerwall had a regression with an incorrect variable type in the json class.
I've now aligned SystemStatus.java with Align SystemStatus.java with the values at https://pkg.go.dev/github.com/foogod/go-powerwall#section-readme

[teslapowerwall] Fix regression in last PR

---

bundles/org.openhab.binding.matter/src/main/java/org/openhab/binding/matter/internal/controller/devices/converter/ColorControlConverter.java
bundles/org.openhab.binding.matter/src/test/java/org/openhab/binding/matter/internal/controller/devices/converter/ColorControlConverterTest.java

Also defaults to min = 153, since i think i misread that most devices were "between" 153-MAX, but its 153 to MAX.  Only relevant if a devices sets its min to 0 or 1 (which means it probably did not set it)

[matter] fixes min/max init of color temp values, adds a few tests as well

---

bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/config/SomfyTahomaConfig.java
bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaBridgeHandler.java
bundles/org.openhab.binding.somfytahoma/src/main/resources/OH-INF/config/config.xml

This PR brings pure local communication, when developer mode enabled and token provided in configuration.
You can pregenerate the token in the Somfy application and in this case the cloud communication is not required at all.

[somfytahoma] pure local mode if token provided

---

bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java

Descending order started with `getFirstTimestamp`. Time steps are negative which shifts the iteration variable `ts`  _before_ start so all values are rejected.
Iteration starts now with `getFirstTimestamp` for ascending order and `getLastTimestamp` for descending order.

[rrd4j] Bugfix descending order

---

bundles/org.openhab.automation.jsscripting/pom.xml

This aligns with the Node.js version openhab-js is developed on.

[jsscripting] Use Node.js 22.13.1 for webpack build

---

bundles/org.openhab.binding.flume/src/main/java/org/openhab/binding/flume/internal/FlumeBindingConstants.java
bundles/org.openhab.binding.flume/src/main/java/org/openhab/binding/flume/internal/FlumeBridgeConfig.java
bundles/org.openhab.binding.flume/src/main/java/org/openhab/binding/flume/internal/FlumeHandlerFactory.java
bundles/org.openhab.binding.flume/src/main/java/org/openhab/binding/flume/internal/actions/FlumeDeviceActions.java
bundles/org.openhab.binding.flume/src/main/java/org/openhab/binding/flume/internal/api/FlumeApi.java
bundles/org.openhab.binding.flume/src/main/java/org/openhab/binding/flume/internal/api/dto/FlumeApiQueryWaterUsage.java
bundles/org.openhab.binding.flume/src/main/java/org/openhab/binding/flume/internal/handler/FlumeBridgeHandler.java
bundles/org.openhab.binding.flume/src/main/java/org/openhab/binding/flume/internal/handler/FlumeDeviceHandler.java

This PR modifies how historical data is queried from the Flume API. Flume made the following restrictions to the API: 
- Restricted the duration of a query to be no longer than 1 year
- Restricted the bucket size to be no larger than 100
The binding now submits multiple yearly queries to get the baseline only on the first start of the binding and stores the number using the StorageService. It will also update the baseline number at the beginning of every month. Subsequent queries are done from the start of month.
A few minor cosmetic changes as well.
This issue has been mentioned and the fix verified here: https://community.openhab.org/t/flume-water-monitoring/119526/13?u=jsjames

[flume] Modifications required to support new restrictions in Flume's API

---

bundles/org.openhab.automation.jrubyscripting/pom.xml

This is an update for openHAB 4.3.x branch for jrubyscripting.
OH5 uses jruby 10.x so this doesn't apply to it.
Release Notes: https://www.jruby.org/2025/06/10/jruby-9-4-13-0.html
It contains many security fixes, but primarily:
- Fixed a slow memory leak in subclass management.

[jrubyscripting] Update version to 9.4.13.0

---

bundles/org.openhab.binding.meteofrance/src/main/resources/OH-INF/thing/channels.xml
bundles/org.openhab.binding.metofficedatahub/src/main/resources/OH-INF/thing/channel-types.xml
bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/thing/channel-types.xml

This PR adjusts some channel tags to use the recently introduced Precipitation property tag.

Apply Precipitation tag

---

bundles/org.openhab.binding.roku/src/main/java/org/openhab/binding/roku/internal/handler/RokuHandler.java

Regression of #18059. Check to ensure that `position` is less than or equal to `duration` to avoid percent calculations greater than 100%. This will prevent the IllegalArgumentException that can occur when updating the state value that uses PercentType. I have only noticed this once in my logs as seen below:

[roku] Prevent progress bar calculation greater than 100%

---

bundles/org.openhab.binding.asuswrt/src/main/java/org/openhab/binding/asuswrt/internal/constants/AsuswrtBindingSettings.java
bundles/org.openhab.binding.asuswrt/src/main/java/org/openhab/binding/asuswrt/internal/structures/AsuswrtConfiguration.java
bundles/org.openhab.binding.asuswrt/src/main/java/org/openhab/binding/asuswrt/internal/things/AsuswrtRouter.java

This is an additional fix/enhancement so that the binding can recover on an interrupted connection (#18456).
Current implementation:
when the router goes offline, the binding starts a reconnectJobScheduler job which will call reconnectJobAction at the appropriate time. This reconnectJobAction attempts to connect(). However, if the connect is unsuccessful, no further action is taken and hence no additional reconnect will be attempted in the future.
New implementation (fix);
when reconnectJobAction calls connect(), connect() now returns whether it was successful or not.  If unsuccessful, reconnectJobScheduler is rescheduled for sometime in the future - using a exponential backoff delay.
This fix has been successfully running in my setup for over 1 month without issues and able to recover in …

[asuswrt] Additional fix to address recovery when offline

---

bundles/org.openhab.persistence.jdbc/pom.xml

This reverts to the version prior to #18472, which seems to fix:
> java.util.ServiceConfigurationError: org.apache.commons.dbutils.ColumnHandler: org.apache.commons.dbutils.handlers.columns.StringColumnHandler not a subtype
Unfortunately that brings us back to the 2014 version of this dependency. Version 1.7 (from 2017) also causes the issue.
It seems that Yank 3.5 doesn't depend on anything new in 1.7+.
Regression of #18472
Resolves #18662

[jdbc] Downgrade dbutils to 1.6

---

bundles/org.openhab.binding.teslapowerwall/src/main/java/org/openhab/binding/teslapowerwall/internal/api/MeterAggregates.java

One of my powerwalls starting reporting a gson parsing error today:
`Expected an int but was 60000000000 at line 1 column 570 path $.site.timeout`
I updated the class to a float for timeout and a few others to be safe.

[teslapowerwall] Fix error with JSON parsing

---

bundles/org.openhab.binding.tuya/src/main/java/org/openhab/binding/tuya/internal/handler/TuyaDeviceHandler.java

There's nothing wrong with a newly linked Item showing the last state known if the Thing is offline. That's what already linked Items do.

[tuya] Allow refresh commands for offline Things

---

bundles/org.openhab.automation.jsscripting/pom.xml

This prevents webpack being installed in another directory.

[jsscripting] Add prefix when installing webpack to fix build issues

---

bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/i18n/shelly.properties

As indicated by Markus here is a commit dedicated to remove trailing white spaces from the shelly_xx.properties files

[shelly] Remove trailing blanks from properties files

---

bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java

A previous fix looks like not being complete, see https://github.com/openhab/openhab-addons/issues/18523#issuecomment-3001574197
This issue pops up again because the alignment of the archives relative to the current time matters in this query. In previous testing, the alignment did not hit the problem of the request date being after the matched archive end date.

[rrd4j] Fix rrd4j query boundaries

---

bundles/org.openhab.binding.fronius/README.md

This adds the ZonedDateTime overload that was forgotten in #18846.

[fronius] Update README

---

bundles/org.openhab.binding.shelly/README.md
bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/discovery/ShellyThingCreator.java
bundles/org.openhab.binding.shelly/src/test/java/org/openhab/binding/shelly/internal/discovery/ShellyThingCreatorTest.java

The changes in #17869 do not seem to work because this is a gen3 device.
Also adds support for Shelly Outdoor Plug S Gen3 and Shelly AZ Plug.

[shelly] Add support for Shelly Plug S Gen3, Outdoor Plug S Gen3, AZ Plug

---

bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc2/NikoHomeControlCommunication2.java

Extends the binding with 3 extra Niko Home Control device types.

[nikohomecontrol] Add relay, peakmode and solarmode device types

---

bundles/org.openhab.binding.broadlinkthermostat/src/main/java/org/openhab/binding/broadlinkthermostat/internal/discovery/BroadlinkDiscoveryService.java
bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/discovery/DaikinACUnitDiscoveryService.java
bundles/org.openhab.binding.ecovacs/src/main/java/org/openhab/binding/ecovacs/internal/discovery/EcovacsDeviceDiscoveryService.java
bundles/org.openhab.binding.irobot/src/main/java/org/openhab/binding/irobot/internal/discovery/IRobotDiscoveryService.java

This is a non-breaking change for future-proofing in case openhab/openhab-core#4866 will be accepted. It will make sure that the new overload `removeOlderResults(Instant)` is automatically selected when `getTimestampOfLastScan()` is changed to return an `Instant` rather than `long`.
There are two variants of the `getTimestampOfLastScan()` usages.
This one will already work:
```java
removeOlderResults(getTimestampOfLastScan());
```
whereas this one will currently not:
```java
long lastScan = getTimestampOfLastScan();
removeOlderResults(lastScan);
```
This PR can be merged before any of the other related PR's.
Using `var` when the type is not obvious is somewhat controversial, but it will ease the migration. I will provide another PR for finally changing to `Instant` when core PR is merged. …

Use `var` for timestampOfLastScan to support upcoming Instant-based API

---

bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/handler/AccountHandler.java
bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/server/MBWebsocket.java
bundles/org.openhab.binding.mercedesme/src/test/java/org/openhab/binding/mercedesme/internal/handler/AccountHandlerMock.java

There are sporadic issues raised in community that proto messages cannot be decoded. This is shown in the logs with an `IOException`.
See
https://community.openhab.org/t/mercedes-me/136866/119
https://community.openhab.org/t/mercedes-me/136866/113
**Problem**
Binary response cannot be logged so I'm _blind_ about the root cause.
**My proposal**
If message decoding exception occurs I'm writing a file into `temp` directory. Implementation ensures
- max 10 files are written
- for info: file size is approx 7KB
- files are deleted in `dispose` so openhab restart or stopping thing will deleted them in order to keep temp dir clean

[mercedesme] Message dumps

---

bundles/org.openhab.binding.androidtv/src/main/java/org/openhab/binding/androidtv/internal/protocol/philipstv/PhilipsTVConnectionManager.java
bundles/org.openhab.binding.homematic/src/test/java/org/openhab/binding/homematic/test/util/SimpleDiscoveryListener.java
bundles/org.openhab.binding.ipp/src/main/java/org/openhab/binding/ipp/internal/handler/IppPrinterHandler.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/discovery/HomeAssistantDiscoveryTests.java
bundles/org.openhab.binding.mqtt.ruuvigateway/src/test/java/org/openhab/binding/mqtt/ruuvigateway/internal/discovery/RuuviGatewayDiscoveryTests.java
bundles/org.openhab.binding.tradfri/src/test/java/org/openhab/binding/tradfri/internal/discovery/TradfriDiscoveryServiceTest.java
itests/org.openhab.binding.avmfritz.tests/src/main/java/org/openhab/binding/avmfritz/internal/discovery/AVMFritzDiscoveryServiceOSGiTest.java
itests/org.openhab.binding.hue.tests/src/main/java/org/openhab/binding/hue/internal/HueDeviceDiscoveryServiceOSGiTest.java
itests/org.openhab.binding.hue.tests/src/main/java/org/openhab/binding/hue/internal/discovery/HueBridgeNupnpDiscoveryOSGITest.java

This removes the now deprecated `DiscoveryListener.removeOlderResults(long)` implementations.
#18838 introduced the new `DiscoveryListener.removeOlderResults(Instant)` implementations in a4b5f0faddd7fe15e965901740eaa4c71e8aa875.
This is the last step for the addons repository to complete the plan outlined in https://github.com/openhab/openhab-core/issues/4866
Depends on openhab/openhab-core#4883

Remove deprecated `DiscoveryListener` method implementations

---

bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/config/InsteonChannelConfiguration.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/InsteonDevice.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/database/LinkDB.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/database/LinkDBChange.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/database/LinkDBRecord.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/database/ModemDBChange.java
bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/database/ModemDBRecord.java

This change refactors static copy factory methods used in Insteon binding, to instance methods instead.

[insteon] Refactor static copy factory methods to instance methods

---

bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyHttpClient.java

The connect timeout was set to 10 seconds and was effective for all bindings using the common `HttpClient`:
https://github.com/openhab/openhab-addons/blob/66990cbe9aaf361571b2a4b07b9522b847c4bd9d/bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/ShellyBindingConstants.java#L304
The request/response is already set to the same value:
https://github.com/openhab/openhab-addons/blob/66990cbe9aaf361571b2a4b07b9522b847c4bd9d/bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyHttpClient.java#L162-L163
https://github.com/openhab/openhab-addons/blob/66990cbe9aaf361571b2a4b07b9522b847c4bd9d/bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/manager/ShellyManagerOtaPage.java#L171-L172 …

[shelly] Do not set connect timeout for shared `HttpClient`

---

bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyDeviceProfile.java
bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyBluSensorHandler.java
bundles/org.openhab.binding.shelly/src/test/java/org/openhab/binding/shelly/internal/api/ShellyDeviceProfileTest.java

This cherry-picks two commits from #18923 to reduce the size of that PR. I believe this PR can be processed faster, and I can then rebase the other one.
Refactoring is in the first commit and a small fix is in the second. I'm not sure the MAC address is already normalized in this case, so it's now normalized within the method itself:
https://github.com/openhab/openhab-addons/blob/8f7578e63897736479ddbd720e920b85aeaa2867/bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/ShellyBluApi.java#L243
The reason for my doubt is that in this other place, `Shelly2NotifyEvent.data.addr` is normalized before calling the method:
https://github.com/openhab/openhab-addons/blob/8f7578e63897736479ddbd720e920b85aeaa2867/bundles/org.openhab.binding.shelly/src/main/java/o …

[shelly] Decouple BLU device names

---

bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/AVMFritzBaseThingHandler.java

The battery channels were not being updated in #18909

[avmfritz] Fix battery channel updating for Smart Energy 250

---

CODEOWNERS
bom/openhab-addons/pom.xml
bundles/org.openhab.binding.bluetooth.listener/NOTICE
bundles/org.openhab.binding.bluetooth.listener/README.md
bundles/org.openhab.binding.bluetooth.listener/pom.xml
bundles/org.openhab.binding.bluetooth.listener/src/main/feature/feature.xml
bundles/org.openhab.binding.bluetooth.listener/src/main/java/org/openhab/binding/bluetooth/listener/internal/ListenerBindingConstants.java
bundles/org.openhab.binding.bluetooth.listener/src/main/java/org/openhab/binding/bluetooth/listener/internal/ListenerConfiguration.java
bundles/org.openhab.binding.bluetooth.listener/src/main/java/org/openhab/binding/bluetooth/listener/internal/ListenerHandler.java
bundles/org.openhab.binding.bluetooth.listener/src/main/java/org/openhab/binding/bluetooth/listener/internal/ListenerHandlerFactory.java
bundles/org.openhab.binding.bluetooth.listener/src/main/resources/OH-INF/i18n/bluetooth.properties
bundles/org.openhab.binding.bluetooth.listener/src/main/resources/OH-INF/thing/thing-types.xml
bundles/pom.xml

This binding adds the ability to connect non-connectable Bluetooth devices. 
It gives the possibility to read data from devices that only broadcast data.
Compiled addon is available at: [org.openhab.binding.bluetooth.listener-5.0.0-SNAPSHOT.jar](https://github.com/docbender/openhab-addons/releases/download/bluetooth.listener-snapshot/org.openhab.binding.bluetooth.listener-5.0.0-SNAPSHOT.jar)

[bluetooth.listener] Initial binding contribution

---

bundles/org.openhab.binding.ondilo/src/main/java/org/openhab/binding/ondilo/internal/OndiloApiClient.java
bundles/org.openhab.binding.ondilo/src/main/java/org/openhab/binding/ondilo/internal/OndiloHandler.java
bundles/org.openhab.binding.ondilo/src/main/java/org/openhab/binding/ondilo/internal/dto/LastMeasure.java
bundles/org.openhab.binding.ondilo/src/main/java/org/openhab/binding/ondilo/internal/dto/Recommendation.java

follow-up PR for post fixes like the warning:
- https://github.com/openhab/openhab-addons/pull/18914#discussion_r2203404215
- https://github.com/openhab/openhab-addons/pull/18914#discussion_r2203391970

[ondilo] Implement review findings

---

bundles/org.openhab.binding.bambulab/src/main/resources/OH-INF/i18n/bambulab.properties

There's also a related bug in MainUI that prevents the links from working properly:
https://github.com/openhab/openhab-webui/issues/3262
Fixed in https://github.com/openhab/openhab-webui/pull/3265

[bambulab] Add the missing i18n text for action input

---

bundles/org.openhab.automation.pythonscripting/pom.xml

this just changes the used helper lib version which includes the following fixes
- improved rule config handling for openhab 5
- fix datetime conversion for null values
- add datetime conversion for getLastStateUpdate and getLastStateChange

[pythonscripting] change python helper lib version to final release

---

bundles/org.openhab.binding.mqtt.homeassistant/src/main/resources/OH-INF/thing/homeassistant-channels.xml

ComponentChannel.Builder automatically adds -advanced to the type if is an advanced child, so bring the definitions in the XML inline with that for gps-accuracy.
Fixes #18604

[mqtt.homeassistant] correct GPS Accuracy channel type

---

bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Climate.java
bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/ClimateTests.java

See https://github.com/home-assistant/core/blob/f65fa3842932ece090e62b508945f9e8d4eaf136/homeassistant/components/mqtt/climate.py#L607.
none is not allowed in the configuration, but is always added as an allowed value
Fixes #18598

[mqtt.homeassistant] add none as an implicit preset for Climate

---

bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyDeviceProfile.java
bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/discovery/ShellyThingCreator.java

Rename constants with wrong names, which could lead to confusion and bugs.
They slipped into #18923 with the opposite effect of what was the intention of that PR.

[shelly] Fix constant names

---

bundles/org.openhab.binding.zwavejs/src/main/java/org/openhab/binding/zwavejs/internal/handler/ZwaveJSNodeHandler.java
bundles/org.openhab.binding.zwavejs/src/test/java/org/openhab/binding/zwavejs/internal/handler/ZwaveJSNodeHandlerTest.java

Reported in the community forums. Changing the parameter `configurationAsChannel` was inconsistent. Also added a test to prevent regression

[zwavejs] Fix configuration as channel 

---

bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyDeviceProfile.java
bundles/org.openhab.binding.shelly/src/test/java/org/openhab/binding/shelly/internal/api/ShellyDeviceProfileTest.java

This removes a useless check, since the method will already return a few lines above. This was picked from #18686.
Additionally full test coverage has been added, and the tests pass both before and after the fix.

[shelly] Add test coverage and remove dead code

---

bundles/org.openhab.binding.airparif/src/main/resources/OH-INF/thing/channels.xml

Fixes: https://github.com/openhab/openhab-addons/issues/18591
Other version is here:
https://github.com/openhab/openhab-addons/blob/9ec05520b4cbd4897e34a8c7ddfcfee2678ecdf1/bundles/org.openhab.binding.airparif/src/main/resources/OH-INF/thing/channels.xml#L7-L16

[airparif] Fix duplicate channel

---

bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaBridgeHandler.java

This PR fixes the bug mentioned in https://github.com/openhab/openhab-addons/issues/18172
New token requires a new event handler registration, no matter if  you ask for token refreshing or do a new  login.

[somfytahoma] Fix invalid event listener after token renewal

---

bundles/org.openhab.binding.plex/src/main/java/org/openhab/binding/plex/internal/handler/PlexApiConnector.java
bundles/org.openhab.binding.plex/src/main/java/org/openhab/binding/plex/internal/handler/PlexPlayerHandler.java
bundles/org.openhab.binding.plex/src/main/java/org/openhab/binding/plex/internal/handler/PlexServerHandler.java

BUGFIX: https://github.com/openhab/openhab-addons/issues/18164
* Better handling of `server` in configuration. Now possible to add hostname which can be matched against plex configuration
* Updated error handling which not supports `CONFIGURATION_ERROR`

[plex] Improve support for hostname as `server` configuration

---

itests/org.openhab.binding.astro.tests/itest.bndrun

The build is currently still failing: https://ci.openhab.org/job/openHAB-Addons/1831/

Fix runbundles on astro itests

---

bundles/org.openhab.binding.zwavejs/src/main/java/org/openhab/binding/zwavejs/internal/handler/ZwaveJSNodeHandler.java

Just before the release of this binding as part of openHAB 5, a bug was fixed that inadvertently revealed another, older one.
During Thing initialization, all channels were being re-created. Initially, this was fine, but when changing the configuration, the Thing would re-initialize and all channels—using their default configuration—would be re-created again, overwriting any configuration changes.
In short, the updateChannels method was refactored to perform only delta operations and leave existing channels untouched. As a side effect, binding initialization should now be faster, as channels typically do not change that often.
Should be backported to 5.0.x

[zwavejs] Fix Channel configuration overwrite

---

bundles/org.openhab.binding.tacmi/README.md
bundles/org.openhab.binding.tapocontrol/README.md
bundles/org.openhab.binding.tellstick/README.md
bundles/org.openhab.binding.teslapowerwall/README.md
bundles/org.openhab.binding.teslascope/README.md
bundles/org.openhab.binding.tibber/README.md
bundles/org.openhab.binding.tivo/README.md
bundles/org.openhab.binding.touchwand/README.md
bundles/org.openhab.binding.tr064/README.md
bundles/org.openhab.binding.tuya/README.md
bundles/org.openhab.binding.velbus/README.md
bundles/org.openhab.binding.velux/README.md
bundles/org.openhab.binding.velux/doc/items.md
bundles/org.openhab.binding.velux/doc/rules.md
bundles/org.openhab.binding.velux/doc/sitemaps.md
bundles/org.openhab.binding.velux/doc/things.md
bundles/org.openhab.binding.verisure/README.md
bundles/org.openhab.binding.vesync/README.md
bundles/org.openhab.binding.vigicrues/README.md
bundles/org.openhab.binding.visualcrossing/README.md
bundles/org.openhab.binding.vitotronic/README.md
bundles/org.openhab.binding.volumio/README.md

Ref: https://github.com/openhab/openhab-addons/issues/19011

Fix markdown bindings T-V

---

bundles/org.openhab.binding.freeboxos/README.md

[freeboxos] Fix Markdown

---

bundles/org.openhab.binding.tibber/src/main/java/org/openhab/binding/tibber/internal/action/TibberActions.java
bundles/org.openhab.binding.tibber/src/main/java/org/openhab/binding/tibber/internal/handler/TibberHandler.java
bundles/org.openhab.binding.tibber/src/main/java/org/openhab/binding/tibber/internal/websocket/TibberWebsocket.java
bundles/org.openhab.binding.tibber/src/test/java/org/openhab/binding/tibber/internal/TibberHandlerMock.java

`Optional` is primarily meant as a return type, not a field type. See for example Brian Goetz, Java’s language architect, [shedding light](https://stackoverflow.com/questions/26327957/should-java-8-getters-return-optional-type/26328555#26328555) on Oracle’s intention with the `Optional` type.
This refactoring aims to make the code clearer, more idiomatic and less error-prone.

[tibber] Refactor `Optional` to nullable

---

bundles/org.openhab.binding.bluetooth.bluez/src/main/java/org/openhab/binding/bluetooth/bluez/internal/BlueZPropertiesChangedHandler.java

This is similar to #19071 where I overlooked another instance of the same bug that mostly affects `BeaconBluetoothHandler` implementations.
Reported here: https://community.openhab.org/t/openhab-5-0-release-discussion/165032/173
Regression of #18124

[bluetooth.bluez] Fix data not being updated

---

bundles/org.openhab.binding.surepetcare/src/main/java/org/openhab/binding/surepetcare/internal/handler/SurePetcareDeviceHandler.java

NullPointerException occurs when `device.status.signal.hubRssi` or other signal values are null:
java.lang.NullPointerException: Cannot invoke "java.lang.Float.floatValue()" because "device.status.signal.hubRssi" is null
text
- Added null checks for all signal fields (hubRssi, deviceRssi)
- Set channel state to `UnDefType.UNDEF` when values are missing
- Prevents the binding from returning an ERROR when API returns incomplete data

[surepetcare] Fix hubRssi `NullPointerException`

---

bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/DebuggingGraalScriptEngine.java
bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/OpenhabGraalJSScriptEngine.java
bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/ScriptExtensionModuleProvider.java
bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/scriptengine/helper/LifecycleTracker.java

Fixes #18224.
This overwrites core's LifecycleTracker as we need to handle the lifecycle tracking internally, because if we properly close the engine, core is unable to run the dispose hook of the lifecycle tracker as the context is already closed.
I think the main issue is that core's lifecycle tracker is disposed after core closes the engine, fixing this in core however would require a bigger refactoring.

[jsscripting] Fix memory leak caused by GraalJSScriptEngine not closed properly

---

bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/dto/HeatingModel.java
bundles/org.openhab.binding.avmfritz/src/test/java/org/openhab/binding/avmfritz/internal/dto/HeatingModelTest.java

See for https://community.openhab.org/t/fritz-binding-dect302-smartthermo302/165280/1
Fixes #17554 
Consider backporting to v4.3.x
Tip for reviewer: there seems to have been two issues
1. The result of `BigDecimal.equals()` depends on the scale of the two values .. so `1.00` is not the same as `1.0`. => The code has been changed to use `BigDecimal.compareTo()` which does not depend on scale.
2. The logic precedence sequence was returning on/off/comfort/eco before the boost or window open states could be evaluated. => The logic precedence has been changed.
Jar files for testing 
- [org.openhab.binding.avmfritz-5.1.0-SNAPSHOT.zip](https://github.com/user-attachments/files/21669394/org.openhab.binding.avmfritz-5.1.0-SNAPSHOT.zip)
- [org.openhab.binding.avmfritz-4.3.7-SNAPSHOT.zip](https://git …

[avmfritz] Fix boost and window open modes

---

bundles/org.openhab.binding.tuya/src/main/java/org/openhab/binding/tuya/internal/local/handlers/TuyaEncoder.java

Presumably this was used back before openHAB required Java 8. The problem is this addon doesn't declare a dependency on it, and while jose4j is available in a core openHAB feature, in some extreme barebones testing scenarios, it's not present.

[tuya] Remove dependency on jose4j

---

bundles/org.openhab.binding.knx/src/main/resources/OH-INF/thing/device.xml

Basically set better defaults.
In KNX, DPT 9.001 is default for number, and represents Temperature.
Contact is typically a read-only status, so Status matches better.
Things like DateTime and Info Strings are typically sent from KNX to OH, so changed to Status.
@andrewfg In KNX, you have quite a strict mapping from DPT to Semantic Tag.
Is there a way to adapt the suggestion once the user has entered the group address with DPT?

[knx] Refine default semantic tags

---

bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/bridge/LongPollingTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/camera/CameraHandlerTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/climatecontrol/ClimateControlHandlerTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/intrusion/IntrusionDetectionHandlerTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/lightcontrol/DimmerHandlerTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/lightcontrol/LightControl2HandlerTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/lightcontrol/LightControlHandlerTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/motiondetector/MotionDetectorHandlerTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/plug/PlugHandlerTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/relay/RelayHandlerTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/shuttercontrol/ShutterControl2HandlerTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/shuttercontrol/ShutterControlHandlerTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/smartbulb/SmartBulbHandlerTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/smokedetector/SmokeDetector2HandlerTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/smokedetector/SmokeDetectorHandlerTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/thermostat/ThermostatHandlerTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/twinguard/TwinguardHandlerTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/universalswitch/UniversalSwitchHandler2Test.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/universalswitch/UniversalSwitchHandlerTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/userdefinedstate/UserStateHandlerTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/wallthermostat/WallThermostatHandlerTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/waterleakage/WaterLeakageSensorHandlerTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/windowcontact/WindowContact2HandlerTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/windowcontact/WindowContact2PlusHandlerTest.java
bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/windowcontact/WindowContactHandlerTest.java

- do not mix mocking via `@Mock` annotation and `mock()` method
- add `@ExtendWith(MockitoExtension.class)` to classes extending test classes that use `@Mock` annotations

[boschshc] Fix unit test setups

---

bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/connection/Connection.java
bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/dto/response/EndPointItemTO.java
bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/dto/response/SmartHomeTO.java
bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/handler/AccountHandler.java
bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/handler/EchoHandler.java
bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/util/HttpRequestBuilder.java
bundles/org.openhab.binding.amazonechocontrol/src/main/resources/json/music_providers.json
bundles/org.openhab.binding.amazonechocontrol/src/main/resources/json/smarthomedevices.json

Amazon changed their API and that broke the openHAB binding. 
Two API calls needed to change including the dto/gsoin plumbing.
- call to get smarthomedevices (api/phoenix) leads to JsonParseException response is empty.
- call to get musicproviders leads to JsonParseException
Fixes: https://github.com/openhab/openhab-addons/issues/19084
Fixes: https://github.com/openhab/openhab-addons/issues/18899
Testable jar 5.0.x: https://1drv.ms/u/c/70ea7ac46bc61c73/EaBslrypz_lEnDVvwt562tEBKG6BjXu-IW-KGrls37m8BA?e=iZZGAc
(the zip file also contains 2 dependency's, drop all three files in your addons folder while the bundled binding is uninstalled)
Tested by me and by @sihui62 who provided me with an Echo dot to ease development and test this fix. A big thanks for his support!

[amazoneechocontrol] Adapt to changed API

---

bundles/org.openhab.binding.ecovacs/README.md
bundles/org.openhab.binding.ecovacs/src/main/java/org/openhab/binding/ecovacs/internal/EcovacsBindingConstants.java
bundles/org.openhab.binding.ecovacs/src/main/java/org/openhab/binding/ecovacs/internal/api/model/CleanMode.java
bundles/org.openhab.binding.ecovacs/src/main/java/org/openhab/binding/ecovacs/internal/handler/EcovacsVacuumHandler.java

Makes it consistent with 'drying', 'washing' and 'returning' states.

[ecovacs] Rename 'autoEmpty' state to 'emptying'

---

pom.xml

https://github.com/openhab/openhab-addons/pull/19180 is causing the build to fail.
It was merged without a successful CI check.
This upgrade is also causing issues in the Core see https://github.com/openhab/openhab-core/pull/4960.

Revert "Bump org.eclipse.jdt:ecj from 3.39.0 to 3.42.0 (#19180)"

---

bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/smarthome/Constants.java

Discovered when porting to 4.3.x. 
Related thread here: https://community.openhab.org/t/amazon-echo-api-broken-again-u-s/165457/18
Only occurs if you have a humidity device. 
Regression of: https://github.com/openhab/openhab-addons/pull/17935
Should be backport to 5.0.x and 4.3.x (for 4.3.x it depends on https://github.com/openhab/openhab-addons/pull/19214)

[amazonechocontrol] Fix `IllegalArgumentException` for devices with humidity

---

bundles/org.openhab.binding.tuya/src/main/resources/OH-INF/i18n/tuya.properties
bundles/org.openhab.binding.tuya/src/main/resources/OH-INF/thing/thing-types.xml

User reports on the forum that the Singapore data centre is missing (See https://community.openhab.org/t/singapore-data-center-not-available-in-tuya-binding/165907)
I found the URL for the data centre at https://github.com/jasonacox/tinytuya/blob/ad91c8eab9b64ec73e668f4e0236f38ed8bfedaf/tinytuya/Cloud.py#L136 and this PR adds it the Thing settings.

[tuya] Add Singapore Data Centre

---

bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/FroniusBindingConstants.java
bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/api/dto/inverter/InverterInfoBody.java
bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/api/dto/inverter/InverterInfoBodyData.java
bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/api/dto/inverter/InverterInfoResponse.java
bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/handler/FroniusSymoInverterHandler.java

By using the documented GetInverterInfo request to the Solar API V1, chances of successfully getting the inverter serial are much higher than by using an undocumented API endpoint.

[fronius] Use Solar API for getting serial number

---

bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/ArcUltra.xml

Related to #19162
XML tag semantic-equipment-tag was introduced in 5.0 and is not supported in 4.3.

[sonos] Remove unexpected XML tag added by backport of #19162 in 4.3.x

---

bundles/org.openhab.voice.openaitts/src/main/java/org/openhab/voice/openaitts/internal/OpenAITTSConfiguration.java
bundles/org.openhab.voice.openaitts/src/main/java/org/openhab/voice/openaitts/internal/OpenAITTSService.java
bundles/org.openhab.voice.openaitts/src/main/resources/OH-INF/config/config.xml
bundles/org.openhab.voice.openaitts/src/main/resources/OH-INF/i18n/openaitts.properties
bundles/org.openhab.voice.openaitts/src/main/resources/OH-INF/i18n/openaitts_it.properties

Update for the OpenAI Speech-to-Text addon. New voices added, new model. Instruction field added to voice settings. You can now customize tone, accent, emotional style, intonation, etc.
These updates allow for much more fine-grained control over speech synthesis, enabling more natural and context-appropriate outputs.
Try it live: https://www.openai.fm/

[openaitts] Add new voices, model and configuration

---

bundles/org.openhab.persistence.jdbc/README.md
bundles/org.openhab.persistence.jdbc/pom.xml
bundles/org.openhab.persistence.jdbc/src/main/feature/feature.xml
bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcConfiguration.java

Upgrade all jdbc persistence library's to the most recent.
Bump com.h2database:h2 from 2.2.224 from to 2.3.232
Bump org.hsqldb:hsqldb from 2.3.3 to 2.7.4
Bump org.mariadb.jdbc:mariadb-java-client from 3.0.8 to 3.5.5
- [Commits](https://github.com/mariadb-corporation/mariadb-connector-j/compare/3.0.8...3.5.5)
Bumps [com.mysql:mysql-connector-j](https://github.com/mysql/mysql-connector-j) from 9.2.0 to 9.4.0.
- [Changelog](https://github.com/mysql/mysql-connector-j/blob/release/9.x/CHANGES)
- [Commits](https://github.com/mysql/mysql-connector-j/compare/9.2.0...9.4.0)
Bump org.postgresql:postgresql from 42.4.4 to 42.7.7 3.0.8
Bump org.xerial:sqlite-jdbc 3.42.0.0 to 3.50.3.0
I also tried to upgrade com.oracle.database.jdbc.ojdbc11 from 23.5.0.2407 to 23.9.0.25.07 and upgrade to ojdbc17. But …

[jdbc] Update dependencies

---

bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/ReolinkHandler.java

Some of the Alarms would not enable/disable with newer versions of the Reolink firmware. These changes make the JSON be formatted in the way the camera wants. Tested on a Reolink 820A camera.

[ipcamera] Fix Reolink needs changes to JSON formatting to work in newer firmwares

---

bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/parser/CcuParamsetDescriptionParser.java
bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/parser/CommonRpcParser.java
bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/parser/GetParamsetDescriptionParser.java
bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/handler/HomematicThingHandler.java
bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/model/HmDatapoint.java

In the MASTER parameter set, for some devices the default value is outside the min..max range; most notably for the CONF_BUTTON_TIME data point, where min=1, max=254 and defaultValue=255.
Avoid showing the warning shown for out-of-range values when gathering the configuration values for such cases.
While at it, make the warning slightly more useful by printing the address of the offending device.
Fixes #13477

[homematic] Adjust warning if current value is out of range

---

bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComInterfaceMessage.java

This adds additional firmware types as requested in https://github.com/openhab/openhab-addons/issues/13024
I provided a download:
https://download.martinvw.nl/org.openhab.binding.rfxcom-5.1.0-SNAPSHOT.13024.jar

[rfxcom] Added additional FirmwareType's

---

bundles/org.openhab.binding.network/README.md
bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/NetworkBindingConfiguration.java
bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/NetworkBindingConstants.java
bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/NetworkHandlerFactory.java
bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/PresenceDetection.java
bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/PresenceDetectionValue.java
bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/WakeOnLanPacketSender.java
bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/discovery/NetworkDiscoveryService.java
bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/handler/NetworkHandler.java
bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/handler/SpeedTestHandler.java
bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/utils/LatencyParser.java
bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/utils/NetworkUtils.java
bundles/org.openhab.binding.network/src/main/resources/OH-INF/addon/addon.xml
bundles/org.openhab.binding.network/src/main/resources/OH-INF/i18n/network.properties
bundles/org.openhab.binding.network/src/test/java/org/openhab/binding/network/internal/PresenceDetectionTest.java
bundles/org.openhab.binding.network/src/test/java/org/openhab/binding/network/internal/discovery/DiscoveryTest.java
bundles/org.openhab.binding.network/src/test/java/org/openhab/binding/network/internal/handler/NetworkHandlerTest.java
bundles/org.openhab.binding.network/src/test/java/org/openhab/binding/network/internal/utils/LatencyParserTest.java

- Fixes: https://github.com/openhab/openhab-addons/issues/17956
- Fixes: https://github.com/openhab/openhab-addons/issues/16810
- Fixes: https://github.com/openhab/openhab-addons/issues/16262
- 
No breaking changes.
Improved logging
Improved separation of concerns
Improved parsing of ping results (<1ms)
Improved resource use (memory and threads)
Discovery takes binding configuration into consideration 
should be backported to 5.0.x and 4.3.x.
Testable jar 5.1.0 snapshot (2025-09-05) or later:  https://1drv.ms/u/c/70ea7ac46bc61c73/EegJadzMpp1IlQYIN5kMCfwBpyUEcQF8ReQZGRMTmTcllw?e=TQEpxt

[network] Fix discovery performance causing a slow openHAB start

---

bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/manager/ShellyManagerOverviewPage.java
bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/manager/ShellyManagerPage.java

This pull requests implements a display name fallback for devices which was never online since the last openhab restart.
In my example only 1 of these 4 devices is visible. 3 of them are missing.
after this fix, it looks like below.
e.g. 4 of my 9 shelly plug s devices are only used during Christmas time for light decorations. This means they are offline for 11 month.

[shelly] Improve Shelly Manager for offline devices

---

bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/api/FroniusBatteryControl.java
bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/api/FroniusConfigAuthUtil.java
bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/handler/FroniusSymoInverterHandler.java

Fronius changed the digest hash algorithm for the config API endpoints from MD5 to SHA256 in firmware version 1.38.6-1.
This adjusts to this change and keeps backwards compatibility.
Reported on the community: https://community.openhab.org/t/fronius-binding-invalid-username-or-password-after-firmware-update/166188
I have tested the backwards compatibility by testing this PR against my Symo inverter before upgrading, and tested the new firmware afterwards.

[fronius] Fix config API authentication for firmware >= 1.38.6

---

bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiRpc.java

This is useful for finding bugs like #19331.
Before:
```text
2025-09-21 13:15:57.841 [DEBUG] [g.shelly.internal.api2.Shelly2ApiRpc] - shellypmmini-543204828114: WebSocket error: Index 10 out of bounds for length 1
```
After:
```text
2025-09-21 13:16:57.834 [DEBUG] [g.shelly.internal.api2.Shelly2ApiRpc] - WebSocket error
java.lang.IndexOutOfBoundsException: Index 10 out of bounds for length 1
at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100) ~[?:?]
at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106) ~[?:?]
at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302) ~[?:?]
at java.util.Objects.checkIndex(Objects.java:385) ~[?:?]
at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
at …
```

[shelly] Improve debug logging for WebSocket exceptions

---

pom.xml

This fixes this error on `mvn clean install` from a path having spaces in it:
```text
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
Error opening zip file or JAR manifest missing : C:\Users\Jacob
[ERROR] Error occurred during initialization of VM
```
in this case on a Windows machine where path starts with "C:\Users\Jacob Laursen".
Regression of #19329

Fix tests when having spaces in path

---

bundles/org.openhab.binding.bluetooth/CONTRIBUTE.md
bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/ConnectedBluetoothHandler.java
bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/internal/BluetoothHandlerFactory.java
bundles/org.openhab.binding.bluetooth/src/main/resources/OH-INF/i18n/bluetooth.properties
bundles/org.openhab.binding.bluetooth/src/main/resources/OH-INF/thing/thing-types.xml

Currently there are three generic Bluetooth thing types:
Manually creating a Thing of type `connected` results in:
```text
2025-09-21 13:51:52.412 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'bluetooth:connected:90cf825ecd:50abc36f7f' changed from UNINITIALIZED to UNINITIALIZED (HANDLER_MISSING_ERROR): Handler factory not found
```
since `connected` is not a supported type.
I lost the track from [2019](https://github.com/openhab/openhab2-addons/commits/5a2b3a4d5d41a28dfa7daa5aa3735c8bcd9d688a/addons/binding/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/internal/BluetoothHandlerFactory.java?browsing_rename_history=true&new_path=bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/internal/BluetoothHandlerFactory.java&origin …

[bluetooth] Remove unsupported thing type `connected`

---

bundles/org.openhab.binding.zoneminder/README.md

[zoneminder] Update README.md

---

bundles/org.openhab.binding.monopriceaudio/src/main/java/org/openhab/binding/monopriceaudio/internal/communication/AmplifierModel.java
bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/handler/NuvoHandler.java
bundles/org.openhab.binding.oppo/src/main/java/org/openhab/binding/oppo/internal/handler/OppoHandler.java
bundles/org.openhab.binding.panasonicbdp/src/main/java/org/openhab/binding/panasonicbdp/internal/handler/PanaBlurayHandler.java

Use getOrDefault when accessing a HashMap to avoid needing to check the result for null in all bindings where I am codeowner.

Use getOrDefault() to reduce null checks

---

bundles/org.openhab.binding.frenchgovtenergydata/src/main/java/org/openhab/binding/frenchgovtenergydata/internal/dto/BaseTariff.java
bundles/org.openhab.binding.frenchgovtenergydata/src/main/java/org/openhab/binding/frenchgovtenergydata/internal/dto/HpHcTariff.java
bundles/org.openhab.binding.frenchgovtenergydata/src/main/java/org/openhab/binding/frenchgovtenergydata/internal/dto/TempoTariff.java
bundles/org.openhab.binding.frenchgovtenergydata/src/main/java/org/openhab/binding/frenchgovtenergydata/internal/handler/BaseTariffHandler.java
bundles/org.openhab.binding.frenchgovtenergydata/src/main/java/org/openhab/binding/frenchgovtenergydata/internal/handler/HpHcTariffHandler.java
bundles/org.openhab.binding.frenchgovtenergydata/src/main/java/org/openhab/binding/frenchgovtenergydata/internal/handler/TempoTariffHandler.java

The was an error in 5.0 in the format of EMPTY_LINE for tempo tariff.
This 1 line fix correct the issue.
Without it, the thing never come online :(

[frenchgovtenergydata] Fix `IllegalArgumentException` for thing type `tempo`

---

bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/thing/channel-types.xml

[OpenWeatherMap] Added unitHint for ChannelType definitions with ItemType 'Number:Dimensionless'

[OpenWeatherMap] Add unitHint for ChannelType definitions with ItemType 'Number:Dimensionless'

---

bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/api/ApiHandler.java
bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/api/rest/FreeboxOsSession.java
bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/api/rest/LoginManager.java

This PR came to be following the analysis of the thread dump posted in [this forum thread](https://community.openhab.org/t/jmdns-memory-leak/166318).
There's a multitude of problems going on for this user, so this isn't the only issue. But, it does contribute.
Basically, the binding makes blocking calls while holding a lock that "traps" other threads that have to wait for the blocking call to return or time out. Since I don't have a FreeboxOS device to test against, I can't know how long these calls can block, but it's clear from the thread dump that it's a significant problem, since it's blocking 6 threads from the `OH-thingHandler` pool, a pool that is already needed for so many other things and have no threads to spare.
The binding is written in a way that makes it very difficult to …

[freeboxos] Fix synchronization problems
