- addons/ui/org.openhab.ui.cometvisu/src/main/java/org/openhab/ui/cometvisu/servlet/CometVisuServlet.java
> [cometvisu] fix regex for sitemap request detection

- addons/binding/org.openhab.binding.tesla/OSGI-INF/TeslaCommands.xml
- addons/binding/org.openhab.binding.tesla/OSGI-INF/TeslaHandlerFactory.xml
- addons/binding/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/command/TeslaCommandExtension.java
- addons/binding/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/handler/TeslaHandler.java
- addons/binding/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/TeslaChannelSelectorProxy.java
- addons/binding/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/protocol/TokenRequest.java
- addons/binding/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/protocol/TokenRequestPassword.java
- addons/binding/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/protocol/TokenRequestRefreshToken.java
@kaikreuzer Just noticed that you only merged a single commit from this PR? There are further fixes for the PR introduced by @ngrodum as well further enhancements to cope with the crap Tesla API back-end (There servers are going down every other week and so on - they can definitely not cope with the growth of the business - hold your breath the day you get your model 3 ;-) )
[update]
@kaikreuzer huh.... I take this back. You merged both commits, but GitHub did not close the PR?
> Tesla : various improvements

- addons/binding/org.openhab.binding.harmonyhub/src/main/java/org/openhab/binding/harmonyhub/handler/HarmonyHubHandler.java
> Fixes issue with reconnects to Harmony Hubs

- addons/binding/org.openhab.binding.hdpowerview/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.keba/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.max/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.urtsi/META-INF/MANIFEST.MF
Found by openhab/static-code-analysis#72
Signed-off-by: Svilen Valkanov <svilen.valkanov@musala.com>
> Remove some package version constraints.

- .pullapprove.yml
I don't know whether this is already enough, but we could try it.
> Added pullaprove config

- addons/voice/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/internal/VoiceRSSAudioStream.java
- addons/voice/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/internal/VoiceRSSTTSService.java
- addons/voice/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/internal/cloudapi/CachedVoiceRSSCloudImplementation.java
- addons/voice/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/internal/cloudapi/VoiceRSSCloudImplementation.java
and fix audio file name extension
> VoiceRSS TTS: add support for AAC format

- addons/binding/create_openhab_binding_skeleton.cmd
- addons/binding/create_openhab_binding_skeleton.sh
- src/etc/about.html
Make sure that the openHAB about.html is copied to the new binding.
Fixes #2205
> Make sure that the openHAB about.html is copied to the new binding.

- addons/io/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudClient.java
Based on the X-Forwarded-Proto header, openHAB will decide, what protocol is used for url's porvided in the output of the REST API request. Hardcofing it to https forces hosters of the openhab-cloud application to use https, otherwise a connection of REST based applications (e.g. the openHAB app) will not work (trying to connect using https to a http only page).
This commit dynamically determines, what protocol should be used for the X-Forwarded-Proto header and sets it automatically. The preference is set to be the protocol of the openhab-cloud service url (baseURL), which is configured in the plugin. If the baseURL could not be parsed (normally, the service shouldn't be reachable in this case), it will check, if the openHAB-cloud app provides the protocol in the request data and, as a …
> Don't hardcode the use of https for X-Forwarded-Proto

- addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/type/HomematicTypeGeneratorImpl.java
- addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/type/MetadataUtils.java
Signed-off-by: Alexander Falkenstern <alexander.falkenstern@gmail.com> (github: falkena)
> Homematic: NPE if a system variable is present in homegear (fixes #1437)

- addons/binding/org.openhab.binding.sensebox/.classpath
- addons/binding/org.openhab.binding.sensebox/.project
- addons/binding/org.openhab.binding.sensebox/ESH-INF/binding/binding.xml
- addons/binding/org.openhab.binding.sensebox/ESH-INF/config/config-description.xml
- addons/binding/org.openhab.binding.sensebox/ESH-INF/thing/box.xml
- addons/binding/org.openhab.binding.sensebox/ESH-INF/thing/channels.xml
- addons/binding/org.openhab.binding.sensebox/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.sensebox/OSGI-INF/SenseBoxHandlerFactory.xml
- addons/binding/org.openhab.binding.sensebox/README.md
- addons/binding/org.openhab.binding.sensebox/about.html
- addons/binding/org.openhab.binding.sensebox/build.properties
- addons/binding/org.openhab.binding.sensebox/pom.xml
- addons/binding/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/SenseBoxBindingConstants.java
- addons/binding/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/config/SenseBoxConfiguration.java
- addons/binding/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/handler/SenseBoxHandler.java
- addons/binding/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/internal/ExpiringCache.java
- addons/binding/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/internal/SenseBoxHandlerFactory.java
- addons/binding/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/model/SenseBoxData.java
- addons/binding/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/model/SenseBoxDescriptor.java
- addons/binding/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/model/SenseBoxGeometry.java
- addons/binding/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/model/SenseBoxLoc.java
- addons/binding/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/model/SenseBoxLocation.java
- addons/binding/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/model/SenseBoxMeasurement.java
- addons/binding/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/model/SenseBoxSensor.java
Signed-off-by: Hakan Tandogan <hakan@tandogan.com>
> [sensebox] binding initial contribution

- .travis.yml
> explicitly set jdk version

- addons/binding/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/discovery/GardenaDeviceDiscoveryService.java
- addons/binding/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/handler/GardenaAccountHandler.java
- addons/binding/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/handler/GardenaThingHandler.java
- addons/binding/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/util/UidUtils.java
> Gardena: Fixed channel update when using thing file config

- addons/binding/org.openhab.binding.homematic/build.properties
Signed-off-by: Svilen Valkanov <svilen.valkanov@musala.com>
> Remove missing directories from build.properties

- addons/binding/org.openhab.binding.avmfritz/ESH-INF/binding/binding.xml
- addons/binding/org.openhab.binding.avmfritz/ESH-INF/i18n/avmfritz_de_DE.properties
- addons/binding/org.openhab.binding.avmfritz/ESH-INF/thing/bridge.xml
- addons/binding/org.openhab.binding.avmfritz/ESH-INF/thing/thing-types.xml
- addons/binding/org.openhab.binding.avmfritz/README.md
- addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/BindingConstants.java
- addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/handler/BoxHandler.java
- addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/handler/DeviceHandler.java
- addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/handler/DeviceListPolling.java
- addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/ahamodel/DeviceModel.java
- addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/ahamodel/DevicelistModel.java
- addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/ahamodel/HeatingModel.java
- addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/ahamodel/PowerMeterModel.java
- addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/ahamodel/SwitchModel.java
- addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/ahamodel/TemperatureModel.java
- addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/hardware/FritzahaWebInterface.java
- addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/hardware/callbacks/FritzAhaDiscoveryCallback.java
- addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/hardware/callbacks/FritzAhaSetHeatingTemperatureCallback.java
- addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/hardware/callbacks/FritzAhaUpdateXmlCallback.java
- Added support for AVM FRITZ!DECT 300 and Comet DECT
Special thanks to @LukaNoah for testing.
Signed-off-by: Christoph Weitkamp github@christophweitkamp.de
> [avmfritz] Added support for AVM FRITZ!DECT 300 and Comet DECT (#1687)

- addons/binding/org.openhab.binding.feed/src/main/java/org/openhab/binding/feed/handler/FeedHandler.java
Added gzip support to the feed binding.
https://github.com/openhab/openhab2-addons/issues/2160
> Added gzip support to feed binding

- addons/binding/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/protocol/KodiConnection.java
The thing status changed to OFFLINE if the Kodi instance is shut down, restarted or crashed. But it never was set to ONLINE again. This PR adds updates of the thing status whenever the Kodi instance sends a websocket message.
> [kodi] Improvements in Kodi thing status handling

- addons/binding/org.openhab.binding.rfxcom/ESH-INF/thing/RFXrec433.xml
- addons/binding/org.openhab.binding.rfxcom/ESH-INF/thing/RFXtrx315.xml
- addons/binding/org.openhab.binding.rfxcom/ESH-INF/thing/RFXtrx433.xml
- addons/binding/org.openhab.binding.rfxcom/ESH-INF/thing/bridge.xml
- addons/binding/org.openhab.binding.rfxcom/ESH-INF/thing/tcpbridge.xml
- addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/handler/RFXComBridgeHandler.java
- addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/config/RFXComBridgeConfiguration.java
- addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/discovery/RFXComDeviceDiscoveryService.java
These RF protocols are just inherently noisy. Having the inbox
continuously fill up with junk is annoying.
Closes #2186
> [RFXCOM] Add a bridge option to disable discovery

- addons/binding/org.openhab.binding.rfxcom.test/src/test/java/org/openhab/binding/rfxcom/internal/messages/RFXComChimeMessageTest.java
- addons/binding/org.openhab.binding.rfxcom/ESH-INF/thing/channels.xml
- addons/binding/org.openhab.binding.rfxcom/ESH-INF/thing/chime.xml
- addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/RFXComBindingConstants.java
- addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/RFXComValueSelector.java
- addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/handler/RFXComHandler.java
- addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComChimeMessage.java
- addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComMessageFactory.java
> [RFXCOM] Add chime devices

- addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/handler/RFXComBridgeHandler.java
We don't queue more than one TX message on the device at once so we
never need to worry about serial numbers in messages. The RFXCOM ALWAYS
gives a response to a TX message. We use the response to clock out the
next message in the queue. We queue TX messages within the driver rather
than blocking the core as the core has its own timeouts. Note that the
sort of RF protocols used for these things are fairly primitive, not
fast and a burst of commands can easily take several _minutes_ to drain
through the system!
See the below issue for why the previous code goes horribly wrong :-(
Closes #1611
> [RFXCOM] Improved TX handling

- addons/binding/org.openhab.binding.keba/ESH-INF/thing/kecontact.xml
- addons/binding/org.openhab.binding.keba/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.keba/src/main/java/org/openhab/binding/keba/KebaBindingConstants.java
- addons/binding/org.openhab.binding.keba/src/main/java/org/openhab/binding/keba/handler/KeContactBroadcastListener.java
- addons/binding/org.openhab.binding.keba/src/main/java/org/openhab/binding/keba/handler/KeContactHandler.java
- addons/binding/org.openhab.binding.keba/src/main/java/org/openhab/binding/keba/internal/KebaHandlerFactory.java
> Keba : Fixes #2237 #2236 #2234 #2038

- addons/binding/org.openhab.binding.keba/ESH-INF/thing/kecontact.xml
> Keba : Fix kecontact.xml in ESH-INF

- addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/handler/RFXComBridgeHandler.java
- addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/connector/RFXComSerialConnector.java
When trying to send a message while the bridge was not connected an NPE occurred
Also no exception will be rethrown since we actually handle it so no reason to rethrow the error as well.
fixes #2298
> [RFXCOM] When trying to send a message while the bridge was not connected an NPE occurred

- addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/discovery/RFXComDeviceDiscoveryService.java
In https://github.com/openhab/openhab2-addons/pull/2045 I accidentally inverted an if condition, instead of only adding new items, I ignored all new items.
Signed-off-by: Martin van Wingerden <martinvw@mtin.nl>
> [RFXCOM] Corrected the discovery of new devices

- ISSUE_TEMPLATE.md
- PULL_REQUEST_TEMPLATE.md
This is a first idea of providing a pull request template.
My main motivation for this PR is to motivate users to clarify the impact of their PR better.
The document is just a first draft! Please add your comments.
A few notes:
* The purpose of the html comment block is to make sure the template doesn't show up in the PR
* Analogue to the included file a file "ISSUE_TEMPLATE.md" can be defined.
* Both files plus the file CONTRIBUTING.md can alternatively be moved to a folder ".github". 
Signed-off-by: Thomas Dietrich <thomas.dietrich@tu-ilmenau.de> (github: ThomDietrich)
> Create Issue and PR template files

- addons/binding/org.openhab.binding.rfxcom.test/src/test/java/org/openhab/binding/rfxcom/internal/messages/RFXComUVMessageTest.java
- addons/binding/org.openhab.binding.rfxcom/ESH-INF/thing/channels.xml
- addons/binding/org.openhab.binding.rfxcom/ESH-INF/thing/uv.xml
- addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/RFXComBindingConstants.java
- addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/RFXComValueSelector.java
- addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/handler/RFXComHandler.java
- addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComMessageFactory.java
- addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComUVMessage.java
> [RFXCOM] Add support for UV sensors

- addons/binding/org.openhab.binding.bigassfan/OSGI-INF/BigAssFanDiscovery.xml
- addons/binding/org.openhab.binding.bigassfan/OSGI-INF/BigAssFanHandlerFactory.xml
- addons/binding/org.openhab.binding.bigassfan/src/main/java/org/openhab/binding/bigassfan/BigAssFanBindingConstants.java
- addons/binding/org.openhab.binding.bigassfan/src/main/java/org/openhab/binding/bigassfan/discovery/BigAssFanDevice.java
- addons/binding/org.openhab.binding.bigassfan/src/main/java/org/openhab/binding/bigassfan/discovery/BigAssFanDiscoveryService.java
- addons/binding/org.openhab.binding.bigassfan/src/main/java/org/openhab/binding/bigassfan/discovery/DiscoveryListener.java
- addons/binding/org.openhab.binding.bigassfan/src/main/java/org/openhab/binding/bigassfan/handler/BigAssFanHandler.java
- addons/binding/org.openhab.binding.bigassfan/src/main/java/org/openhab/binding/bigassfan/internal/BigAssFanConfig.java
- addons/binding/org.openhab.binding.bigassfan/src/main/java/org/openhab/binding/bigassfan/internal/BigAssFanHandlerFactory.java
- addons/binding/org.openhab.binding.dlinksmarthome/OSGI-INF/DLinkSmartHomeHandlerFactory.xml
Some small non-standard copyright banners which we missed while reviewing
> Some small non-standard copyright banners which we missed while reviewing

- addons/binding/org.openhab.binding.synopanalyzer/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.synopanalyzer/src/main/java/org/openhab/binding/synopanalyzer/handler/SynopAnalyzerHandler.java
- addons/binding/org.openhab.binding.synopanalyzer/src/main/java/org/openhab/binding/synopanalyzer/internal/SynopAnalyzerHandlerFactory.java
Not reproducing the error raised in Issue #2341 so took the opportunity to remove dependency to org.apache.http.client librairies that seems to be progressively removed from ESH. Also made a bit code refactoring.
Signed-off-by: Gaël L'hopital <glhopital@gmail.com>
> Removed utilisation of org.apache.http.client

- addons/binding/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/KodiAudioSink.java
Kodi requests the audio stream several times from the HTTP server
Signed-off-by: Andreas Reinhardt <an_re@gmx.com>
> [Kodi] Fix audio sink (#2301)

- features/openhab-addons/src/main/feature/feature.xml
Somehow, the commit adding this binding to feature.xml must have got lost before starting the pull requests 😊
> [senseBox] Forgot to add binding to feature.xml

- addons/binding/org.openhab.binding.sensebox/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/handler/SenseBoxHandler.java
- addons/binding/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/internal/SenseBoxAPIConnection.java
- addons/binding/pom.xml
Not only forgot to add the binding to feature.xml, also forgot to add to upper level pom.xml.
Signed-off-by: Hakan Tandogan <hakan@tandogan.com>
> [senseBox] Forgot to add binding to addons/binding/pom.xml

- addons/binding/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/handler/TeslaHandler.java
> [Tesla] Extend exception handling in TeslaHandler

- addons/binding/org.openhab.binding.onebusaway/.classpath
- addons/binding/org.openhab.binding.onebusaway/.project
- addons/binding/org.openhab.binding.onebusaway/ESH-INF/binding/binding.xml
- addons/binding/org.openhab.binding.onebusaway/ESH-INF/config/config.xml
- addons/binding/org.openhab.binding.onebusaway/ESH-INF/thing/api.xml
- addons/binding/org.openhab.binding.onebusaway/ESH-INF/thing/channels.xml
- addons/binding/org.openhab.binding.onebusaway/ESH-INF/thing/route.xml
- addons/binding/org.openhab.binding.onebusaway/ESH-INF/thing/stop.xml
- addons/binding/org.openhab.binding.onebusaway/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.onebusaway/OSGI-INF/OneBusAwayHandlerFactory.xml
- addons/binding/org.openhab.binding.onebusaway/README.md
- addons/binding/org.openhab.binding.onebusaway/about.html
- addons/binding/org.openhab.binding.onebusaway/build.properties
- addons/binding/org.openhab.binding.onebusaway/pom.xml
- addons/binding/org.openhab.binding.onebusaway/src/main/java/org/openhab/binding/onebusaway/OneBusAwayBindingConstants.java
- addons/binding/org.openhab.binding.onebusaway/src/main/java/org/openhab/binding/onebusaway/internal/OneBusAwayHandlerFactory.java
- addons/binding/org.openhab.binding.onebusaway/src/main/java/org/openhab/binding/onebusaway/internal/config/ApiConfiguration.java
- addons/binding/org.openhab.binding.onebusaway/src/main/java/org/openhab/binding/onebusaway/internal/config/ChannelConfig.java
- addons/binding/org.openhab.binding.onebusaway/src/main/java/org/openhab/binding/onebusaway/internal/config/RouteConfiguration.java
- addons/binding/org.openhab.binding.onebusaway/src/main/java/org/openhab/binding/onebusaway/internal/config/StopConfiguration.java
- addons/binding/org.openhab.binding.onebusaway/src/main/java/org/openhab/binding/onebusaway/internal/handler/ApiHandler.java
- addons/binding/org.openhab.binding.onebusaway/src/main/java/org/openhab/binding/onebusaway/internal/handler/ObaStopArrivalResponse.java
- addons/binding/org.openhab.binding.onebusaway/src/main/java/org/openhab/binding/onebusaway/internal/handler/RouteDataListener.java
- addons/binding/org.openhab.binding.onebusaway/src/main/java/org/openhab/binding/onebusaway/internal/handler/RouteHandler.java
- addons/binding/org.openhab.binding.onebusaway/src/main/java/org/openhab/binding/onebusaway/internal/handler/StopHandler.java
- addons/binding/pom.xml
- features/openhab-addons/src/main/feature/feature.xml
OneBusAway is a transit data provider used in a number of locations:
https://onebusaway.org/onebusaway-deployments/
> Add a binding for OneBusAway Data

- addons/binding/org.openhab.binding.onebusaway/ESH-INF/thing/api.xml
- addons/binding/org.openhab.binding.onebusaway/src/main/java/org/openhab/binding/onebusaway/internal/OneBusAwayHandlerFactory.java
- addons/binding/org.openhab.binding.onebusaway/src/main/java/org/openhab/binding/onebusaway/internal/config/ApiConfiguration.java
- addons/binding/org.openhab.binding.onebusaway/src/main/java/org/openhab/binding/onebusaway/internal/config/ChannelConfig.java
- addons/binding/org.openhab.binding.onebusaway/src/main/java/org/openhab/binding/onebusaway/internal/config/RouteConfiguration.java
- addons/binding/org.openhab.binding.onebusaway/src/main/java/org/openhab/binding/onebusaway/internal/config/StopConfiguration.java
- addons/binding/org.openhab.binding.onebusaway/src/main/java/org/openhab/binding/onebusaway/internal/handler/ApiHandler.java
- addons/binding/org.openhab.binding.onebusaway/src/main/java/org/openhab/binding/onebusaway/internal/handler/StopHandler.java
> some small cleanup on OneBusAway

- features/openhab-addons/src/main/feature/feature.xml
> added dependency to provider-gson from com.eclipsesource.jaxrs

- addons/binding/org.openhab.binding.yamahareceiver/ESH-INF/thing/thing-types.xml
please do not remove the <option value="5ch Stereo">5ch Stereo</option> my yamaha receive is 5ch Stereo please update
> addon 5ch Stereo

- features/openhab-addons/src/main/feature/feature.xml
Reverts openhab/openhab2-addons#2387
> Revert "added dependency to provider-gson from com.eclipsesource.jaxrs"

- addons/binding/org.openhab.binding.rfxcom/ESH-INF/thing/channels.xml
- addons/binding/org.openhab.binding.rfxcom/README.md
- addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/RFXComValueSelector.java
- addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/config/RFXComBridgeConfiguration.java
To clarify the documentation, a lot of information was added on setting up the RFXCOM binding manually.
> [RFXCOM] Updated the readme

- addons/binding/org.openhab.binding.bigassfan/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.bigassfan/src/main/java/org/openhab/binding/bigassfan/handler/BigAssFanHandler.java
Fixes several small bugs in the bigassfan binding
- Fixes handling of light level min and max messages
- Catches exceptions thrown by Scanner.next()
- Fix code analysis complaint about missing package import
> [bigassfan] Several bug fixes

- addons/binding/org.openhab.binding.bigassfan/src/main/java/org/openhab/binding/bigassfan/handler/BigAssFanHandler.java
I normally would've waited to include this small fix with several other changes.  But, since the cutoff for 2.1 is tomorrow...  ;-)
> [bigassfan] Whoosh mode fix

- addons/binding/org.openhab.binding.amazondashbutton/README.md
Markdown fixup
Phrasing
Some links
Windows installation hints
foo
Signed-off-by: Thomas Dietrich <thomas.dietrich@tu-ilmenau.de> (github: ThomDietrich)
> [amazondashbutton] Update README.md

- addons/binding/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/protocol/ClimateState.java
> [Tesla] Fix #2401

- addons/binding/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/handler/OnkyoHandler.java
> [onkyo] Fix volume level limit functionality for zone 2 and 3.

- addons/binding/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/protocol/KodiConnection.java
* Changed type for 'speed' values to 'Number'
* Changed 'speed' for REWIND to -2
Closes #2429 
> [kodi] Fixed REWIND/FASTFORWARD for channel 'control'

- addons/binding/org.openhab.binding.tankerkoenig/README.md
- addons/binding/org.openhab.binding.tankerkoenig/src/main/java/org/openhab/binding/tankerkoenig/TankerkoenigBindingConstants.java
- addons/binding/org.openhab.binding.tankerkoenig/src/main/java/org/openhab/binding/tankerkoenig/handler/StationHandler.java
- addons/binding/org.openhab.binding.tankerkoenig/src/main/java/org/openhab/binding/tankerkoenig/handler/WebserviceHandler.java
- addons/binding/org.openhab.binding.tankerkoenig/src/main/java/org/openhab/binding/tankerkoenig/internal/config/TankerkoenigDetailResult.java
- addons/binding/org.openhab.binding.tankerkoenig/src/main/java/org/openhab/binding/tankerkoenig/internal/config/TankerkoenigListResult.java
- addons/binding/org.openhab.binding.tankerkoenig/src/main/java/org/openhab/binding/tankerkoenig/internal/serializer/CustomTankerkoenigDetailResultDeserializer.java
- addons/binding/org.openhab.binding.tankerkoenig/src/main/java/org/openhab/binding/tankerkoenig/internal/serializer/CustomTankerkoenigListResultDeserializer.java
**Changes in the Readme:**
- As reported by @cweitkamp and @hannibal29 the syntax of the example Items file had an error.
- Procedure to import hhtps certificates included
- FAQ section included
**Changes in Code:**
In case the web-request for price -data does not return status=OK al Station(s) and the Webservice go OFFLINE and the scheduled polling is stopped.
> [Tankerkoenig] Changed Readme and handling of web-returns not OK.

- addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/handler/RFXComBridgeHandler.java
- addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComInterfaceMessage.java
Somfy/Rfy commands return extended responses using interface messages
rather than simple transmitter message responses. We don't support them
(and don't need to?) but we do need to _survive_ them at least.
Closes #2394
> [RFXCOM] Handle Somfy/Rfy extended responses

- addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/type/HomematicTypeGeneratorImpl.java
See openhab/static-code-analysis#106
Signed-off-by: Svilen Valkanov <svilen.valkanov@musala.com>
> Fix logger message

- addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/type/HomematicConfigDescriptionProviderImpl.java
> adapted ConfigDescription to changed ESH API

- addons/binding/org.openhab.binding.nikohomecontrol/ESH-INF/thing/thing-types.xml
- addons/binding/org.openhab.binding.nikohomecontrol/README.md
- addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/NikoHomeControlBindingConstants.java
- addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/handler/NikoHomeControlBridgeHandler.java
- addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/NikoHomeControlCommunication.java
Expose Niko Home Control alarms and notices as trigger events to openHAB.
> [nikohomecontrol] Implementation of alarms and notices.

- PULL_REQUEST_TEMPLATE.md
Added `TESTING` section.
cc: @ThomDietrich @martinvw 
Signed-off-by: Kuba Wolanin <hi@kubawolanin.com> (github: kubawolanin)
> [Novel Addition] Updated PULL_REQUEST_TEMPLATE

- addons/binding/org.openhab.binding.synopanalyzer/src/main/java/org/openhab/binding/synopanalyzer/handler/SynopAnalyzerHandler.java
Changed data retrieving approach to 24 time window by default. JavaIzed to v8.
Complements to comments raised in PR #2480 
Signed-off-by: Gaël L'hopital <glhopital@gmail.com>
> Changed data retrieving approach to 24 time window by default.

- addons/binding/org.openhab.binding.rfxcom.test/pom.xml
- addons/binding/org.openhab.binding.rfxcom.test/src/test/java/org/openhab/binding/rfxcom/internal/messages/RFXComInterfaceMessageTest.java
Corrected the failing test, new changed behaviour is okay, adapted the name to reflect that.
> [RFXCOM] Corrected the failing test

- addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComCurrentEnergyMessage.java
- addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComDateTimeMessage.java
- addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComUndecodedRFMessage.java
While refactoring something else I noted some inconsistent handling of the subtypes, a separate PR for the overview.
@mjagdis @paulianttila please review, its small and isolated :-)
> [RFXCOM] Corrected some non-standard Subtype handling

- addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComBaseMessage.java
- addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComHomeConfortMessage.java
- addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComTemperatureHumidityBarometricMessage.java
- addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComTemperatureRainMessage.java
- addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComUndecodedRFMessage.java
While refactoring something else I noted some inconsistent toString methods, a separate PR for the overview.
@mjagdis @paulianttila please review, its small and isolated :-)
> [RFXCOM] Corrected some non-standard toString methods

- addons/binding/org.openhab.binding.windcentrale/.classpath
> changed to default JRE

- addons/binding/org.openhab.binding.netatmo/README.md
Signed-off-by: Christoph Wempe <cw-git@wempe.net> (github: CWempe)
> [netatmo] add example config to README.md

- addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComWindMessage.java
> [RFXCOM] fix missing temperature and chill temperature

- addons/binding/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/handler/AirQualityHandler.java
- addons/binding/org.openhab.binding.autelis/src/main/java/org/openhab/binding/autelis/handler/AutelisHandler.java
- addons/binding/org.openhab.binding.coolmasternet/src/main/java/org/openhab/binding/coolmasternet/handler/HVACHandler.java
- addons/binding/org.openhab.binding.coolmasternet/src/main/java/org/openhab/binding/coolmasternet/internal/ControllerHandler.java
- addons/binding/org.openhab.binding.feed/src/main/java/org/openhab/binding/feed/handler/FeedHandler.java
- addons/binding/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/handler/HDPowerViewShadeHandler.java
- addons/binding/org.openhab.binding.meteostick/src/main/java/org/openhab/binding/meteostick/handler/MeteostickBridgeHandler.java
- addons/binding/org.openhab.binding.meteostick/src/main/java/org/openhab/binding/meteostick/handler/MeteostickSensorHandler.java
- addons/binding/org.openhab.binding.minecraft/src/main/java/org/openhab/binding/minecraft/handler/MinecraftServerHandler.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/handler/AbstractNetatmoThingHandler.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/handler/NetatmoBridgeHandler.java
- addons/binding/org.openhab.binding.network/src/main/java/org/openhab/binding/network/handler/NetworkHandler.java
- addons/binding/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/handler/AbstractAvrHandler.java
- addons/binding/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/handler/PulseaudioBridgeHandler.java
- addons/binding/org.openhab.binding.silvercrestwifisocket/src/main/java/org/openhab/binding/silvercrestwifisocket/handler/SilvercrestWifiSocketHandler.java
- addons/binding/org.openhab.binding.synopanalyzer/src/main/java/org/openhab/binding/synopanalyzer/handler/SynopAnalyzerHandler.java
- addons/binding/org.openhab.binding.toon/src/main/java/org/openhab/binding/toon/handler/ToonDisplayHandler.java
- addons/binding/org.openhab.binding.toon/src/main/java/org/openhab/binding/toon/handler/ToonPlugHandler.java
- addons/binding/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/handler/ZoneMinderBaseThingHandler.java
- addons/binding/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/handler/ZoneMinderServerBridgeHandler.java
Needed due to change in ESH: https://github.com/eclipse/smarthome/pull/3917
Signed-off-by: Stefan Triller <stefan.triller@telekom.de>
> Thinghandler should not call super.initialize()

- addons/binding/org.openhab.binding.tankerkoenig/README.md
Setting the log level did not work as described in the readme
> [tankerkoenig] Fix typo in readme

- addons/io/org.openhab.io.hueemulation/ESH-INF/config/config.xml
- addons/io/org.openhab.io.hueemulation/META-INF/MANIFEST.MF
- addons/io/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/HueEmulationServlet.java
- addons/io/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/HueEmulationUpnpServer.java
- addons/io/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/api/HueDataStore.java
- addons/io/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/api/HueDevice.java
- addons/io/org.openhab.io.hueemulation/src/main/resources/discovery.xml
> Hueemulation: Initital support for google home

- addons/io/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/HueEmulationServlet.java
- addons/io/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/HueEmulationUpnpServer.java
> addressed review comments

- addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/BindingConstants.java
- addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/HandlerFactory.java
- addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/discovery/AVMFritzDiscoveryService.java
- addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/hardware/callbacks/FritzAhaDiscoveryCallback.java
- Added firmware property to discovered things
- Renamed AvmDiscoveryService to AVMFritzDiscoveryService
> [avmfritz] Added firmware property to discovered things

- addons/binding/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/YamahaChannelsTypeProvider.java
Added missing author tag
Removed overly verbose public declaration, note that all interface methods are public.
> [yamaha] Correct failing static code analysis

- addons/ui/org.openhab.ui.cometvisu/src/main/java/org/openhab/ui/cometvisu/servlet/CometVisuServlet.java
This PR fixes several errors in the dataprovider responses used by the CometVisu editor. 
The main goal is to fix the listing of available addresses (aka Item-Names) in the editor.
It also handles some changes in the data-structure of the current development version of the CometVisu and fixes the responses for the listing of items, designs and plugins.
> [cometvisu] fix cometvisu dataprovider response values

- addons/ui/org.openhab.ui.cometvisu/OSGI-INF/dashboardtile.xml
- addons/ui/org.openhab.ui.cometvisu/src/main/java/org/openhab/ui/cometvisu/internal/CometVisuDashboardTile.java
correct starting point and shows an existing config.
> [cometvisu] Make sure that the CometVisu Dashboard tile link always points to the

- addons/binding/org.openhab.binding.autelis/README.md
- addons/binding/org.openhab.binding.folding/README.md
- addons/binding/org.openhab.binding.globalcache/README.md
- addons/binding/org.openhab.binding.harmonyhub/README.md
- addons/binding/org.openhab.binding.lutron/README.md
- addons/binding/org.openhab.binding.mihome/README.md
- addons/binding/org.openhab.binding.pioneeravr/README.md
- addons/binding/org.openhab.binding.regoheatpump/README.md
- addons/binding/org.openhab.binding.russound/README.md
- addons/binding/org.openhab.binding.sensebox/README.md
- addons/binding/org.openhab.binding.smaenergymeter/README.md
- addons/binding/org.openhab.binding.toon/README.md
- addons/binding/org.openhab.binding.urtsi/README.md
- addons/io/org.openhab.io.homekit/README.md
- addons/ui/org.openhab.ui.cometvisu/README.md
I already made a PR with corrected .md files but after improving MarkDownCheck and executing it over the repo it found some more. :) 
Signed-off-by: Erdoan Hadzhiyusein <3rdoan@gmail.com>
> Added corrected README files after static analysis.

- addons/binding/org.openhab.binding.kodi/README.md
> [Kodi] Updated documentation with reference to #2442

- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/handler/AbstractNetatmoThingHandler.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/handler/NetatmoModuleHandler.java
Signed-off-by: Stefan Triller <stefan.triller@telekom.de>
> NetAtmo: Fix passing null to handleCommand

- addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/converter/type/PercentTypeConverter.java
- addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/misc/HomematicConstants.java
- addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/type/MetadataUtils.java
- addons/binding/org.openhab.binding.homematic/src/main/resources/homematic/extra-descriptions.properties
- addons/binding/org.openhab.binding.homematic/src/main/resources/homematic/extra-descriptions_de.properties
> Homematic: Added support for Homematic IP blind actuator

- addons/binding/org.openhab.binding.netatmo/ESH-INF/i18n/netatmo_fr.properties
> Netatmo binding: updated French translation

- addons/binding/org.openhab.binding.netatmo/ESH-INF/i18n/netatmo_de.properties
> [Netatmo] Added german translation

- addons/binding/org.openhab.binding.netatmo/ESH-INF/config/config.xml
- addons/binding/org.openhab.binding.netatmo/ESH-INF/thing/station.xml
- addons/binding/org.openhab.binding.netatmo/README.md
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/handler/NetatmoBridgeHandler.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/handler/station/NAModule4Handler.java
- Changed pattern for MAC address in config.xml (Closes #2526)
- Added channels MinTemp, MaxTemp, DateMinTemp, DateMaxTemp and TempTrend to NAModule4
- Refactored ThingStatus for NetatmoBridgeHandler
> [Netatmo] Changed pattern for MAC address in config.xml and new channels for NAModule4

- addons/binding/org.openhab.binding.rfxcom.test/src/test/java/org/openhab/binding/rfxcom/internal/messages/RFXComLighting4MessageTest.java
- addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComLighting4Message.java
A bugix to properly support the sending of partially supported commands.
See also: https://github.com/openhab/openhab2-addons/issues/2534
> [RFXCOM] Improved sending partially supported commands and added missing test

- addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/parser/CcuVariablesAndScriptsParser.java
- addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/parser/CommonRpcParser.java
> Fixed parsing min/max variable values

- addons/binding/org.openhab.binding.kodi/ESH-INF/binding/binding.xml
- addons/binding/org.openhab.binding.kodi/ESH-INF/config/config.xml
- addons/binding/org.openhab.binding.kodi/ESH-INF/i18n/kodi_de.properties
- addons/binding/org.openhab.binding.kodi/ESH-INF/thing/thing-types.xml
> [Kodi] Updated and added complete german translation

- addons/binding/org.openhab.binding.network/ESH-INF/i18n/network_de.properties
Fixed typo, GitHub changed encoding to UTF8, thus the many changed lines.
> [network binding] Fix typo

- features/openhab-addons/src/main/feature/feature.xml
> added nest binding to features (got lost on the PR before...)

- addons/binding/org.openhab.binding.allplay/ESH-INF/binding/binding.xml
- addons/binding/org.openhab.binding.allplay/OSGI-INF/AllPlayHandlerFactory.xml
- addons/binding/org.openhab.binding.allplay/src/main/java/org/openhab/binding/allplay/handler/AllPlayHandler.java
- addons/binding/org.openhab.binding.allplay/src/main/java/org/openhab/binding/allplay/internal/AllPlayBindingProperties.java
Fixes issue #2335 that the AllPlay binding did not read the configuration correctly. Also fixes reading of the double values specified in the configuration (did not work correctly after the first issue has been fixed)
> [allplay] Make sure AllPlay binding reads configuration correctly

- addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/AbstractHomematicGateway.java
Reverts openhab/openhab2-addons#2595
> Revert "[homematic] Do not start RPC server too often."

- addons/binding/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/handler/AbstractAvrHandler.java
- addons/binding/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/protocol/ParameterizedCommand.java
- addons/binding/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/protocol/StreamAvrConnection.java
- addons/binding/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/protocol/utils/VolumeConverter.java
[PioneerAvr] Zone2 / Zone3 / HDZone Volume Control
Improvement: this adds support for changing volume for Zone2 / Zone3 / HDZone for PioneerAVR binding.
> [PioneerAvr] Zone2 / Zone3 / HDZone Volume Control

- addons/binding/org.openhab.binding.max/ESH-INF/i18n/max_de.properties
- addons/binding/org.openhab.binding.max/ESH-INF/thing/bridge.xml
- addons/binding/org.openhab.binding.max/ESH-INF/thing/thing-types.xml
- addons/binding/org.openhab.binding.max/src/main/java/org/openhab/binding/max/MaxBinding.java
* Updated and added complete german translation
* Clean-up of xml-files
> [max] Updated and added complete german translation

- addons/binding/org.openhab.binding.meteostick/ESH-INF/thing/thing-types.xml
- addons/binding/org.openhab.binding.meteostick/README.md
Add New Zealand to channel list, correction to things example
> [meteostick] Minor corrections to README.md

- addons/binding/org.openhab.binding.atlona/OSGI-INF/AtlonaDiscovery.xml
- addons/binding/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/discovery/AtlonaDiscovery.java
- addons/binding/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/pro3/AtlonaPro3Config.java
- addons/binding/org.openhab.binding.autelis/OSGI-INF/AutelisDiscovery.xml
- addons/binding/org.openhab.binding.autelis/src/main/java/org/openhab/binding/autelis/handler/AutelisHandler.java
- addons/binding/org.openhab.binding.autelis/src/main/java/org/openhab/binding/autelis/internal/config/AutelisConfiguration.java
- addons/binding/org.openhab.binding.autelis/src/main/java/org/openhab/binding/autelis/internal/discovery/AutelisDiscoveryParticipant.java
Also-by: Svilen Valkanov <svilen.valkanov@musala.com>
> Atlona package renamed to .internal.

- addons/binding/org.openhab.binding.regoheatpump/META-INF/MANIFEST.MF
> added null annotations to import to avoid errors in workspace

- addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/handler/BoxHandler.java
- addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/handler/DeviceHandler.java
- addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/config/AvmFritzConfiguration.java
- addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/hardware/FritzahaWebInterface.java
- addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/hardware/callbacks/FritzAhaDiscoveryCallback.java
- addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/hardware/callbacks/FritzAhaUpdateXmlCallback.java
- addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/util/JAXBtUtils.java
> Renamed avmfritz package to internal.

- addons/binding/org.openhab.binding.bigassfan/src/main/java/org/openhab/binding/bigassfan/internal/discovery/BigAssFanDevice.java
- addons/binding/org.openhab.binding.bigassfan/src/main/java/org/openhab/binding/bigassfan/internal/discovery/BigAssFanDiscoveryService.java
- addons/binding/org.openhab.binding.bigassfan/src/main/java/org/openhab/binding/bigassfan/internal/discovery/DiscoveryListener.java
> Renamed bigassfan package to internal.

- addons/binding/org.openhab.binding.folding/OSGI-INF/FoldingSlotDiscovery.xml
- addons/binding/org.openhab.binding.folding/src/main/java/org/openhab/binding/folding/handler/FoldingClientHandler.java
- addons/binding/org.openhab.binding.folding/src/main/java/org/openhab/binding/folding/internal/discovery/FoldingDiscoveryProxy.java
- addons/binding/org.openhab.binding.folding/src/main/java/org/openhab/binding/folding/internal/discovery/FoldingSlotDiscoveryService.java
> Renamed a package in the folding binding to internal.

- addons/binding/org.openhab.binding.coolmasternet/src/main/java/org/openhab/binding/coolmasternet/handler/HVACHandler.java
- addons/binding/org.openhab.binding.coolmasternet/src/main/java/org/openhab/binding/coolmasternet/internal/ControllerHandler.java
- addons/binding/org.openhab.binding.coolmasternet/src/main/java/org/openhab/binding/coolmasternet/internal/config/CoolMasterNetConfiguration.java
> Renamed CoolMasterNet package to internal.

- addons/binding/org.openhab.binding.globalcache/src/main/java/org/openhab/binding/globalcache/internal/discovery/GlobalCacheDiscoveryService.java
- addons/binding/org.openhab.binding.globalcache/src/main/java/org/openhab/binding/globalcache/internal/discovery/MulticastListener.java
> Renamed discovery package to internal in the globalcache binding.

- addons/binding/org.openhab.binding.kostalinverter/META-INF/MANIFEST.MF
> Exported kostal inverter package.

- addons/binding/org.openhab.binding.jeelink/META-INF/MANIFEST.MF
> [jeelink] Importing null annotations as optional

- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/handler/DimmerHandler.java
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/handler/IPBridgeHandler.java
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/config/DimmerConfig.java
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/config/IPBridgeConfig.java
> Renamed the config package to internal in the lutron binding.

- addons/binding/org.openhab.binding.smaenergymeter/OSGI-INF/SMAEnergyMeterDiscovery.xml
- addons/binding/org.openhab.binding.smaenergymeter/src/main/java/org/openhab/binding/smaenergymeter/handler/SMAEnergyMeterHandler.java
- addons/binding/org.openhab.binding.smaenergymeter/src/main/java/org/openhab/binding/smaenergymeter/internal/configuration/EnergyMeterConfig.java
- addons/binding/org.openhab.binding.smaenergymeter/src/main/java/org/openhab/binding/smaenergymeter/internal/discovery/SMAEnergyMeterDiscoveryService.java
> Renamed config and discovery packages in the SMAEnergyMeter binding.

- addons/binding/org.openhab.binding.jeelink/.classpath
> use default JRE

- addons/binding/org.openhab.binding.network/src/main/java/org/openhab/binding/network/handler/NetworkHandler.java
> Network: Fix wrong paramter used

- addons/binding/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/handler/YamahaBridgeHandler.java
- addons/binding/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/discovery/YamahaDiscoveryParticipant.java
- addons/binding/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/discovery/ZoneDiscoveryService.java
> Renamed discovery package to internal in the yamahareceiver binding.

- addons/binding/org.openhab.binding.zway/src/main/java/org/openhab/binding/zway/handler/ZWayBridgeHandler.java
- addons/binding/org.openhab.binding.zway/src/main/java/org/openhab/binding/zway/handler/ZWayZAutomationDeviceHandler.java
- addons/binding/org.openhab.binding.zway/src/main/java/org/openhab/binding/zway/handler/ZWayZWaveDeviceHandler.java
- addons/binding/org.openhab.binding.zway/src/main/java/org/openhab/binding/zway/internal/config/ZWayBridgeConfiguration.java
- addons/binding/org.openhab.binding.zway/src/main/java/org/openhab/binding/zway/internal/config/ZWayZAutomationDeviceConfiguration.java
- addons/binding/org.openhab.binding.zway/src/main/java/org/openhab/binding/zway/internal/config/ZWayZWaveDeviceConfiguration.java
> Renamed config package to internal in the ZWay binding.

- addons/binding/org.openhab.binding.chromecast/ESH-INF/config/config.xml
- addons/binding/org.openhab.binding.chromecast/ESH-INF/i18n/chromecast_de.properties
- addons/binding/org.openhab.binding.chromecast/ESH-INF/thing/thing-types.xml
- Updated and added complete german translation
- Clean-up of xml-files
> [chromecast] Updated and added complete german translation

- addons/binding/org.openhab.binding.homematic/ESH-INF/thing/bridge.xml
- addons/binding/org.openhab.binding.homematic/README.md
- addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/handler/HomematicBridgeHandler.java
- addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/common/HomematicConfig.java
- addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/AbstractHomematicGateway.java
- addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/HomematicGatewayAdapter.java
- addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/client/RpcClient.java
- addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/model/HmDatapointInfo.java
see https://github.com/openhab/openhab2-addons/pull/2595
> Homematic: Optimized connection tracker

- addons/binding/org.openhab.binding.network/src/main/java/org/openhab/binding/network/handler/NetworkHandler.java
aka the real fix for #2591.
Fixes #2591
> Fix DHCP property displays wrong state

- addons/binding/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/protocol/KodiClientSocket.java
- addons/binding/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/protocol/KodiConnection.java
> [kodi] Added NPE safe-guard and error handling

- addons/binding/org.openhab.binding.tesla/OSGI-INF/TeslaCommands.xml
- addons/binding/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/command/TeslaCommandExtension.java
> Renamed command package to internal in the tesla binding.

- addons/binding/org.openhab.binding.netatmo/ESH-INF/config/config.xml
- addons/binding/org.openhab.binding.netatmo/ESH-INF/i18n/netatmo_de.properties
- addons/binding/org.openhab.binding.netatmo/ESH-INF/thing/channels.xml
- Updated and added german translations
- Clean-up of xml-files
> [netatmo] Updated and added german translations

- addons/ui/org.openhab.ui.cometvisu/src/main/java/org/openhab/ui/cometvisu/internal/config/ConfigHelper.java
> [CometVisu] make download link realy download the file

- addons/binding/org.openhab.binding.synopanalyzer/src/main/java/org/openhab/binding/synopanalyzer/handler/SynopAnalyzerHandler.java
- addons/binding/org.openhab.binding.synopanalyzer/src/main/java/org/openhab/binding/synopanalyzer/internal/config/SynopAnalyzerConfiguration.java
> Renamed the config package to internal in the SynopAnalyzer binding.

- addons/binding/org.openhab.binding.kodi/README.md
See
https://community.openhab.org/t/oh2-kodi-no-binding-found-that-supports-creating-a-thing-of-type-kodi-kodi/33955/1
https://community.openhab.org/t/open-tv-channel-in-xbmc-kodi/17330/36
> [kodi] Updated documentation to address comments in the community

- addons/binding/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/utils/NetworkUtils.java
> Network: Thomas arping changed end of 2016 the cli interface

- addons/binding/org.openhab.binding.netatmo/README.md
Fixes #2685
Signed-off-by: Laurent Garnier <lg.hc@ree.fr>
> Netatmo: fix example for channel WifiStatus

- addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComRfyMessage.java
> [RFXCOM] Allow Rfy things to send on venetian blind channels.

- addons/binding/org.openhab.binding.netatmo/ESH-INF/i18n/netatmo_fr.properties
> Netatmo: fix French translation (Healthy Home Coach)

- addons/binding/org.openhab.binding.nest.test/src/test/java/org/openhab/binding/nest/internal/data/GsonParsingTest.java
- addons/binding/org.openhab.binding.nest/OSGI-INF/NestHandlerFactory.xml
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/NestBindingConstants.java
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/config/NestBridgeConfiguration.java
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/discovery/NestDiscoveryService.java
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/handler/NestBridgeHandler.java
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/handler/NestCameraHandler.java
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/handler/NestSmokeDetectorHandler.java
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/handler/NestStructureHandler.java
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/handler/NestThermostatHandler.java
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/NestAccessToken.java
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/NestDeviceAddedListener.java
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/NestHandlerFactory.java
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/NestUpdateRequest.java
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/data/AccessTokenData.java
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/data/BaseNestDevice.java
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/data/Camera.java
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/data/NestDevices.java
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/data/NestMetadata.java
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/data/SmokeDetector.java
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/data/Structure.java
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/data/Thermostat.java
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/data/TopLevelData.java
[Nest] update copyright headers
> [Nest] update copyright headers

- addons/binding/org.openhab.binding.opensprinkler/OSGI-INF/OpenSprinklerDiscovery.xml
- addons/binding/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/handler/OpenSprinklerHTTPHandler.java
- addons/binding/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/handler/OpenSprinklerPiHandler.java
- addons/binding/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/config/OpenSprinklerConfig.java
- addons/binding/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/config/OpenSprinklerPiConfig.java
- addons/binding/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/discovery/OpenSprinklerDiscoveryJob.java
- addons/binding/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/discovery/OpenSprinklerDiscoveryService.java
> Renamed a few packages to internal in the OpenSprinkler binding.

- addons/binding/org.openhab.binding.mihome/ESH-INF/thing/channel.xml
- addons/binding/org.openhab.binding.mihome/ESH-INF/thing/sensor_smoke.xml
- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/XiaomiGatewayBindingConstants.java
- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/handler/XiaomiSensorBaseAlarmHandler.java
- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/handler/XiaomiSensorBaseHandler.java
- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/handler/XiaomiSensorGasHandler.java
- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/handler/XiaomiSensorSmokeHandler.java
Signed-off-by: Dieter Schmidt <dima.loschkin@gmail.com>
[mihome] add new channel for smoke sensor & minor improvements
- New channel for smoke sensor! Credits to [the Community](https://community.openhab.org/t/support-for-more-mi-home-aqara-items/32122/46)
-> can be useful for air quality measurements too
- smoke & gas sensor now show status "OK" instead of "Release alarm"
> [mihome] add new channel for smoke sensor & minor improvements

- addons/binding/org.openhab.binding.tankerkoenig/ESH-INF/i18n/tankerkoenig_de.properties
- addons/binding/org.openhab.binding.tankerkoenig/README.md
> (Tankerkoenig) Corrected typos in README and tankerkoenig_de.properties 

- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/ModelMapper.java
Fixes  #2714 
Signed-off-by: Daniel Walters <danielwalters1@hotmail.com>
> [mihome] Add Aqara Motion Sensor to model mapper

- addons/io/org.openhab.io.homekit/META-INF/MANIFEST.MF
> Exported a package in the org.openhab.io.homekit bundle.

- addons/binding/org.openhab.binding.harmonyhub/src/main/java/org/openhab/binding/harmonyhub/internal/discovery/HarmonyHubDiscoveryService.java
- addons/binding/org.openhab.binding.ipp/src/main/java/org/openhab/binding/ipp/handler/IppPrinterHandler.java
- addons/binding/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/discovery/MaxCubeBridgeDiscovery.java
- addons/binding/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/handler/PulseaudioHandler.java
- addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/handler/RFXComHandler.java
- addons/binding/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/net/SocketChannelSession.java
- addons/binding/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/internal/live/xml/TellstickNetSensor.java
See https://github.com/openhab/static-code-analysis/issues/196
> Remove some non-javadoc

- addons/binding/org.openhab.binding.yamahareceiver/README.md
Added manual configuration of bridge and thing.
Signed-off-by: Udo Hartmann <udo1toni@gmail.com>
> [yamaha] add configuration to readme

- addons/binding/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/NetworkHandlerFactory.java
This fixes the [currently broken build](https://openhab.ci.cloudbees.com/job/openHAB2-Bundles/154/console)
> fixed passing of null argument

- addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/parser/CommonRpcParser.java
@gerrieg can you agree with this?
> [Homematic] Add debug logging in case of a NumberFormatException

- addons/binding/org.openhab.binding.milight/OSGI-INF/TestDiscovery.xml
- addons/binding/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/test/EmulatedV6Bridge.java
- addons/binding/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/test/TestDiscovery.java
> Renamed a package to internal in the milight binding.

- addons/binding/org.openhab.binding.onkyo/ESH-INF/thing/tx-nr737.xml
- addons/binding/org.openhab.binding.onkyo/README.md
- addons/binding/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/OnkyoBindingConstants.java
Added support for TX-NR737
Added the IDs and tested with my receiver.
[onkyo] Added support for TX-NR737
Signed-off-by: stasee <ste@stasee.de>
> Onkyo: Added support for TX-NR737

- addons/binding/org.openhab.binding.cm11a/.classpath
- addons/binding/org.openhab.binding.cm11a/.project
- addons/binding/org.openhab.binding.cm11a/.settings/org.eclipse.jdt.core.prefs
- addons/binding/org.openhab.binding.cm11a/ESH-INF/binding/binding.xml
- addons/binding/org.openhab.binding.cm11a/ESH-INF/thing/thing-types.xml
- addons/binding/org.openhab.binding.cm11a/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.cm11a/OSGI-INF/CM11AHandlerFactory.xml
- addons/binding/org.openhab.binding.cm11a/README.md
- addons/binding/org.openhab.binding.cm11a/about.html
- addons/binding/org.openhab.binding.cm11a/build.properties
- addons/binding/org.openhab.binding.cm11a/pom.xml
- addons/binding/org.openhab.binding.cm11a/src/etc/header.txt
- addons/binding/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/CM11ABindingConstants.java
- addons/binding/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/config/Cm11aConfig.java
- addons/binding/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/handler/Cm11aAbstractHandler.java
- addons/binding/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/handler/Cm11aApplianceHandler.java
- addons/binding/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/handler/Cm11aBridgeHandler.java
- addons/binding/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/handler/Cm11aLampHandler.java
- addons/binding/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/handler/ReceivedDataListener.java
- addons/binding/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/internal/Cm11aHandlerFactory.java
- addons/binding/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/internal/InvalidAddressException.java
- addons/binding/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/internal/X10Interface.java
- addons/binding/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/internal/X10ReceivedData.java
- addons/binding/pom.xml
- features/openhab-addons/src/main/feature/feature.xml
This should be considered an extension of pull #1724. This fork is the result of code changes identified in the PR.
The cm11a is a serial computer interface for X-10 devices. The goal of this request is to have this binding merged into openHAB. Or, at least get constructive feedback on changes to be made. It has been running on my openHAB system for several months. It has also been available in my [repo](https://github.com/BobRak/OpenHAB-cm11a)and tested by other users.
> [cm11a] Initial contribution and 2nd code review 

- addons/ui/org.openhab.ui.cometvisu.php/OSGI-INF/phprovider.xml
- addons/ui/org.openhab.ui.cometvisu.php/src/main/java/org/openhab/ui/cometvisu/internal/servlet/quercus/PHProviderImpl.java
> Renamed a package to internal in the cometvisu.php bundle.

- addons/binding/org.openhab.binding.avmfritz/ESH-INF/i18n/avmfritz_de.properties
- addons/binding/org.openhab.binding.avmfritz/ESH-INF/thing/thing-types.xml
- addons/binding/org.openhab.binding.avmfritz/README.md
- addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/BindingConstants.java
- addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/handler/BoxHandler.java
- addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/handler/DeviceHandler.java
- features/openhab-addons/src/main/feature/feature.xml
> [avmfritz] Added support for new FRITZ!DECT 301 device

- addons/binding/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/CM11ABindingConstants.java
- addons/binding/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/handler/Cm11aAbstractHandler.java
- addons/binding/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/handler/Cm11aApplianceHandler.java
- addons/binding/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/handler/Cm11aBridgeHandler.java
- addons/binding/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/handler/Cm11aLampHandler.java
- addons/binding/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/handler/ReceivedDataListener.java
- addons/binding/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/internal/Cm11aHandlerFactory.java
- addons/binding/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/internal/InvalidAddressException.java
- addons/binding/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/internal/X10Interface.java
- addons/binding/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/internal/X10ReceivedData.java
- addons/binding/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/internal/config/Cm11aConfig.java
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/discovery/NestDiscoveryService.java
> Fixed the header of a few files

- addons/ui/org.openhab.ui.cometvisu/OSGI-INF/cv-backend-charts.xml
- addons/ui/org.openhab.ui.cometvisu/OSGI-INF/itemregistryeventlistener.xml
the last refactoring (2409184b20bf088adf62ac06175caf5fde102e98) missed some references
> fix references to internal classes

- addons/binding/org.openhab.binding.synopanalyzer/src/main/java/org/openhab/binding/synopanalyzer/handler/SynopAnalyzerHandler.java
Corrected Attenuation Factor calculation in this case.
Removed initial started delay
Signed-off-by: Gaël L'hopital <glhopital@gmail.com>
> Octa can go up to nine if the sky is not visible.

- addons/binding/org.openhab.binding.kodi/ESH-INF/config/config.xml
- addons/binding/org.openhab.binding.kodi/ESH-INF/i18n/kodi_de.properties
- addons/binding/org.openhab.binding.kodi/ESH-INF/thing/thing-types.xml
- addons/binding/org.openhab.binding.kodi/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.kodi/README.md
- addons/binding/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/KodiBindingConstants.java
- addons/binding/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/handler/KodiHandler.java
- addons/binding/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/KodiEventListener.java
- addons/binding/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/config/KodiConfig.java
- addons/binding/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/protocol/KodiConnection.java
Signed-off-by: Andreas Reinhardt <an_re@gmx.com>
> [Kodi] Add channels for fanart and thumbnail (#2302)

- addons/io/org.openhab.io.openhabcloud/README.md
Signed-off-by: Hakam Saffour <hakam.saffour@gmail.com>
>  Show exposed items after they receive an update

- addons/binding/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/discovery/MieleMDNSDiscoveryParticipant.java
- addons/binding/org.openhab.binding.minecraft/src/main/java/org/openhab/binding/minecraft/internal/discovery/MinecraftMDNSDiscoveryParticipant.java
> removed invalid imports

- addons/binding/org.openhab.binding.network.test/src/test/java/org/openhab/binding/network/internal/PresenceDetectionTest.java
- addons/binding/org.openhab.binding.network.test/src/test/java/org/openhab/binding/network/internal/toberemoved/cache/ExpiringCacheAsyncTest.java
- addons/binding/org.openhab.binding.network.test/src/test/java/org/openhab/binding/network/internal/toberemoved/cache/ExpiringCacheHelper.java
- addons/binding/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/PresenceDetection.java
- addons/binding/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/toberemoved/cache/ExpiringCacheAsync.java
> Renamed a package to internal in the network binding.

- features/openhab-addons/src/main/feature/feature.xml
> add apache http dependency to IPP binding

- addons/binding/org.openhab.binding.amazondashbutton/README.md
A few additions for the Amazon Dash Button Addon README.
Signed-off-by: Thomas Dietrich <thomas.dietrich@tu-ilmenau.de> (github: ThomDietrich)
> [amazondashbutton] Add manual Thing def, add response time warning

- addons/binding/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/handler/TeslaHandler.java
There seems to be changes wrt authentication at the Tesla side of the world, with Tesla resetting authentication/sessions frequently
> [Tesla] Improve authentication upon HTTP 401 status codes

- addons/binding/org.openhab.binding.dscalarm/ESH-INF/thing/it100bridge.xml
- addons/binding/org.openhab.binding.jeelink/ESH-INF/thing/thing-types.xml
- addons/binding/org.openhab.binding.oceanic/ESH-INF/thing/softener.xml
- addons/binding/org.openhab.binding.pioneeravr/ESH-INF/thing/thing-types.xml
- addons/binding/org.openhab.binding.rfxcom/ESH-INF/thing/bridge.xml
- addons/binding/org.openhab.binding.rme/ESH-INF/thing/rme.xml
> added serial-port context to config parameters in order to support automatic selection lists

- addons/io/org.openhab.io.imperihome/README.md
- addons/io/org.openhab.io.imperihome/src/main/java/org/openhab/io/imperihome/internal/ImperiHomeApiServlet.java
- addons/io/org.openhab.io.imperihome/src/main/java/org/openhab/io/imperihome/internal/action/ActionRegistry.java
- addons/io/org.openhab.io.imperihome/src/main/java/org/openhab/io/imperihome/internal/action/StopShutterAction.java
- addons/io/org.openhab.io.imperihome/src/main/java/org/openhab/io/imperihome/internal/handler/DeviceActionHandler.java
- addons/io/org.openhab.io.imperihome/src/main/java/org/openhab/io/imperihome/internal/model/device/ShutterDevice.java
Update ImperiHome binding:
- Fix action URL without value for Android clients
- Add support for Shutter stopper
> [imperihome] Update ImperiHome binding

- addons/binding/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/YamahaReceiverHandlerFactory.java
See openhab/static-code-analysis#213
See openhab/static-code-analysis#217
> Fixed wrong class passed as logger parameter.

- addons/binding/org.openhab.binding.network/META-INF/MANIFEST.MF
> added annotations import to network binding

- addons/binding/org.openhab.binding.tesla/ESH-INF/thing/models.xml
> [Tesla] Fix 2 channels wrongly tagged as properties

- addons/binding/org.openhab.binding.network/META-INF/MANIFEST.MF
Reverts openhab/openhab2-addons#2869
> Revert "added annotations import to network binding"

- addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/handler/HomematicThingHandler.java
- addons/binding/org.openhab.binding.ipp/src/main/java/org/openhab/binding/ipp/handler/IppPrinterHandler.java
- addons/binding/org.openhab.binding.rme/src/main/java/org/openhab/binding/rme/handler/RMEThingHandler.java
- addons/binding/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/handler/SamsungTvHandler.java
This should fix the currently broken build, which is due to new non null annotations in ESH.
> fixed errors from changed null annotations

- addons/binding/org.openhab.binding.sleepiq/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.sleepiq/src/main/java/org/openhab/binding/sleepiq/handler/SleepIQCloudHandler.java
> removed usage of guava base as this is incompatible between different versions

- addons/binding/org.openhab.binding.windcentrale/META-INF/MANIFEST.MF
> added ds annotation import to Windcentrale

- addons/binding/org.openhab.binding.lgwebos/META-INF/MANIFEST.MF
> added DS annotations import as long as we need it

- addons/binding/org.openhab.binding.nest.test/src/test/java/org/openhab/binding/nest/internal/data/GsonParsingTest.java
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/data/Thermostat.java
> [Nest] java.lang.NumberFormatException: For input string: "<10"

- addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/handler/BoxHandler.java
- addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/handler/DeviceHandler.java
- Positioned finals first in comparisons
Closes #2902 
> [avmfritz] NPE safe-guard

- addons/binding/org.openhab.binding.network/ESH-INF/i18n/network_de.properties
Signed-off-by: Björn Brings <bjoernbrings@web.de> (github: bjoernbrings)
Small fix of two typos mentioned in Issue #2600.
Small remark: This is my first commit. Hope I did everything right.
> Fixed Issue #2600 ([network] Two small typos)

- addons/binding/org.openhab.binding.tankerkoenig/README.md
Signed-off-by: Juergen Baginski <opus42@gmx.dee> (github: JueBag)
> Updated ReadMe to show the minimal required Java Version

- addons/binding/org.openhab.binding.avmfritz/README.md
> [avmfritz] Updated Thing configuration in documentation

- addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/handler/SqueezeBoxServerHandler.java
[Squeezebox] The cover, title, remote tille, genre, year are now correctly refreshed
> [Squeezebox] Fix : web radio doesn't update cover art 

- addons/binding/org.openhab.binding.tankerkoenig/README.md
Signed-off-by: Juergen Baginski opus42@gmx.de (github: JueBag)
> [Tankerkoenig] ReadMe: Added linebreak for readability.

- addons/binding/org.openhab.binding.windcentrale/src/main/java/org/openhab/binding/windcentrale/handler/WindcentraleHandler.java
- addons/binding/org.openhab.binding.windcentrale/src/main/java/org/openhab/binding/windcentrale/internal/WindcentraleHandlerFactory.java
- addons/binding/org.openhab.binding.windcentrale/src/main/java/org/openhab/binding/windcentrale/internal/config/MillConfig.java
* Add null annotations
* Add configuration object
* Make some properties final, static and move their initialization
> [Windcentrale] Add null annotations and configuration object

- addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/handler/DeviceHandler.java
> [avmfritz] Fixed handle command for channel 'radiator_mode'

- addons/binding/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/TeslaChannelSelectorProxy.java
Signed-Off-By: Karel Goderis <karel.goderis@me.com>
> [Tesla] Fix NPE for changed DateTimeTpe dateFormatter

- addons/binding/org.openhab.binding.tellstick/README.md
Small error in the documentation fixed.
Signed-off-by: Jakob Stenfeldt <jakob.stenfeldt@gmail.com> (github:
jakobstenfeldt)
> [Tellstick] - Updated documentation

- addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/RFXComBindingConstants.java
- addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/handler/RFXComBridgeHandler.java
Hardware and firmware versions shouldn't need too much effort to find. Let's log them on connect and put them in the bridge thing's properties for the GUIs.
> [RFXCOM] Make HW/FW versions available

- addons/binding/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/handler/GardenaThingHandler.java
> reduced log level of expected Gardena exceptions (that are not related to a bug)

- addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/discovery/HomematicDeviceDiscoveryService.java
> Avoid NPE in Homematic discovery

- addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/handler/HomematicBridgeHandler.java
> replaced some runnables by lambdas

- addons/binding/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/handler/GardenaAccountHandler.java
> improved Gardena logging in case of an invalid Thing definition

- addons/binding/org.openhab.binding.ipp/src/main/java/org/openhab/binding/ipp/handler/IppPrinterHandler.java
- addons/binding/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/handler/SamsungTvHandler.java
> adapted method signatures to breaking change from ESH

- addons/binding/org.openhab.binding.bigassfan/README.md
- addons/binding/org.openhab.binding.boschindego/README.md
> [Binding addons starting with "B"] Correct linter errors only

- addons/binding/org.openhab.binding.chromecast/README.md
- addons/binding/org.openhab.binding.cm11a/README.md
- addons/binding/org.openhab.binding.coolmasternet/README.md
> [Binding addons starting with "C"] Correct linter errors only

- addons/binding/org.openhab.binding.gardena/README.md
- addons/binding/org.openhab.binding.globalcache/README.md
> [Binding addons starting with "G"] Correct linter errors only

- addons/binding/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/internal/core/TelldusCoreBridgeHandler.java
> improve lifecycle of TelldusCoreBridgeHandler

- addons/binding/org.openhab.binding.harmonyhub/README.md
- addons/binding/org.openhab.binding.hdanywhere/README.md
- addons/binding/org.openhab.binding.hdpowerview/README.md
- addons/binding/org.openhab.binding.homematic/README.md
> [Binding addons starting with "H"] Correct linter errors only

- addons/binding/org.openhab.binding.dlinksmarthome/README.md
- addons/binding/org.openhab.binding.dscalarm/README.md
> [Binding addons starting with "D"] Correct linter errors only

- addons/binding/org.openhab.binding.exec/README.md
> [Binding addons starting with "E"] Correct linter errors only

- addons/binding/org.openhab.binding.ipp/README.md
> [Binding addons starting with "I"] Correct linter errors only

- addons/binding/org.openhab.binding.jeelink/README.md
> [Binding addons starting with "J"] Correct linter errors only

- addons/binding/org.openhab.binding.keba/README.md
- addons/binding/org.openhab.binding.kodi/README.md
- addons/binding/org.openhab.binding.kostalinverter/README.md
> [Binding addons starting with "K"] Correct linter errors only

- addons/binding/org.openhab.binding.max/README.md
- addons/binding/org.openhab.binding.meteostick/README.md
- addons/binding/org.openhab.binding.miele/README.md
- addons/binding/org.openhab.binding.mihome/README.md
- addons/binding/org.openhab.binding.milight/README.md
- addons/binding/org.openhab.binding.minecraft/README.md
> [Binding addons starting with "M"] Correct linter errors only

- pom.xml
related to https://github.com/openhab/openhab-core/pull/259
> added esh release p2 repo

- pom.xml
> Fix typo from #2960 (caused build errors)

- addons/binding/org.openhab.binding.nest.test/README.md
- addons/binding/org.openhab.binding.nest/README.md
- addons/binding/org.openhab.binding.network/README.md
- addons/binding/org.openhab.binding.nikohomecontrol/README.md
* Omitted Netatmo at the request of @martinvw.  See #2682.
> [Binding addons starting with "N"*] Correct linter errors only

- addons/binding/org.openhab.binding.oceanic/README.md
- addons/binding/org.openhab.binding.onebusaway/README.md
- addons/binding/org.openhab.binding.onkyo/README.md
- addons/binding/org.openhab.binding.opensprinkler/README.md
- addons/binding/org.openhab.binding.orvibo/README.md
> [Binding addons starting with "O"] Correct linter errors only

- addons/binding/org.openhab.binding.avmfritz/ESH-INF/thing/thing-types.xml
- addons/binding/org.openhab.binding.netatmo/ESH-INF/i18n/netatmo_fr.properties
- addons/binding/org.openhab.binding.network/ESH-INF/thing/thing-types.xml
- addons/binding/org.openhab.binding.systeminfo/ESH-INF/thing/channels.xml
see https://github.com/eclipse/smarthome/pull/4411
> [i18n] Adapted channel translation to changed ESH API

- addons/binding/org.openhab.binding.pioneeravr/README.md
- addons/binding/org.openhab.binding.plugwise/README.md
- addons/binding/org.openhab.binding.pulseaudio/README.md
> [Binding addons starting with "P"] Correct linter errors only

- addons/binding/org.openhab.binding.kodi/ESH-INF/i18n/kodi_de.properties
> [Kodi] Updated and added missing german translations for callback URL

- targetplatform/openHAB2.setup
see https://github.com/eclipse/smarthome/pull/4783
Signed-off-by: Simon Kaufmann <simon.kfm@googlemail.com>
> Default import of static members

- addons/binding/org.openhab.binding.netatmo/README.md
> Name of Camera Thing was wrong

- addons/binding/org.openhab.binding.netatmo/ESH-INF/thing/station.xml
- addons/binding/org.openhab.binding.netatmo/README.md
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/station/NAModule2Handler.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/station/NAModule3Handler.java
> [Netatmo] Added timestamp 'channel' to NAModule2 (wind gauge) and NAModule3 (rain gauge)

- addons/binding/create_openhab_binding_skeleton.cmd
- addons/binding/create_openhab_binding_skeleton.sh
- addons/binding/create_openhab_binding_test_skeleton.cmd
- addons/binding/create_openhab_binding_test_skeleton.sh
> Fix correct version in create_openhab_*_skeleton.*

- addons/binding/org.openhab.binding.tankerkoenig/README.md
- addons/binding/org.openhab.binding.tellstick/README.md
- addons/binding/org.openhab.binding.tesla/README.md
- addons/binding/org.openhab.binding.toon/README.md
> [Binding addons starting with "T"] Correct linter errors only

- addons/binding/org.openhab.binding.samsungtv/README.md
- addons/binding/org.openhab.binding.sensebox/README.md
- addons/binding/org.openhab.binding.silvercrestwifisocket/README.md
- addons/binding/org.openhab.binding.sleepiq/README.md
- addons/binding/org.openhab.binding.smaenergymeter/README.md
- addons/binding/org.openhab.binding.squeezebox/README.md
- addons/binding/org.openhab.binding.synopanalyzer/README.md
- addons/binding/org.openhab.binding.systeminfo/README.md
> [Binding addons starting with "S"] Correct linter errors only

- addons/binding/org.openhab.binding.urtsi/README.md
> [Binding addons starting with "U"] Correct linter errors only

- addons/binding/org.openhab.binding.vitotronic/README.md
> [Binding addons starting with "V"] Correct linter errors only

- addons/binding/org.openhab.binding.wifiled/README.md
- addons/binding/org.openhab.binding.windcentrale/README.md
> [Binding addons starting with "W"] Correct linter errors only

- addons/binding/org.openhab.binding.rfxcom.test/src/test/java/org/openhab/binding/rfxcom/internal/messages/RFXComCurrentMessageTest.java
- addons/binding/org.openhab.binding.rfxcom/ESH-INF/thing/current.xml
- addons/binding/org.openhab.binding.rfxcom/README.md
- addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComCurrentMessage.java
- addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComMessageFactory.java
Follow-up of #1271
Also-by:  Jordan Cook <jordan@jc.me.uk> (github: netjordan)
> [RFXCOM] Adding support for CURRENT messages

- addons/binding/org.openhab.binding.nest/ESH-INF/thing/channels.xml
- addons/binding/org.openhab.binding.nest/README.md
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/data/Structure.java
> [Nest] Remove deprecated auto-away state

- addons/binding/org.openhab.binding.tplinksmarthome.test/src/test/java/org/openhab/binding/tplinksmarthome/internal/PropertiesCollectorTest.java
- addons/binding/org.openhab.binding.tplinksmarthome.test/src/test/java/org/openhab/binding/tplinksmarthome/internal/TPLinkSmartHomeHandlerFactoryTest.java
- addons/binding/org.openhab.binding.tplinksmarthome.test/src/test/java/org/openhab/binding/tplinksmarthome/internal/device/BulbDeviceTest.java
- addons/binding/org.openhab.binding.tplinksmarthome/ESH-INF/thing/KB100.xml
- addons/binding/org.openhab.binding.tplinksmarthome/ESH-INF/thing/KB130.xml
- addons/binding/org.openhab.binding.tplinksmarthome/ESH-INF/thing/KP100.xml
- addons/binding/org.openhab.binding.tplinksmarthome/ESH-INF/thing/LB200.xml
- addons/binding/org.openhab.binding.tplinksmarthome/ESH-INF/thing/LB230.xml
- addons/binding/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/TPLinkSmartHomeBindingConstants.java
- addons/binding/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/Commands.java
- addons/binding/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/PropertiesCollector.java
- addons/binding/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/TPLinkSmartHomeDiscoveryService.java
- addons/binding/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/TPLinkSmartHomeHandlerFactory.java
- addons/binding/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/TPLinkSmartHomeThingType.java
This PR adds support for new devices. These devices haven't all been tested, but theoretically should be ok, hence the WIP tag. The code itself should be ok. Created the PR to get a jar that can be linked to in the Eclipse Marketplace.
> [tplinksmarthome][WIP] New devices: KB100, KB130, KP100, LB200 and LB230

- addons/voice/org.openhab.voice.voicerss/README.md
> [Voice Addons] Correct linter errors only

- addons/ui/org.openhab.ui.cometvisu/README.md
-  There is one remaining linter error on line 42.  I was unsure of how to correctly format the link.
> [UI Addons] Correct linter errors only

- addons/binding/org.openhab.binding.yamahareceiver/README.md
> [Binding addons starting with "Y"] Correct linter errors only

- addons/binding/org.openhab.binding.zoneminder/README.md
- addons/binding/org.openhab.binding.zway/README.md
> [Binding addons starting with "Z"] Correct linter errors only

- addons/io/org.openhab.io.homekit/README.md
- addons/io/org.openhab.io.hueemulation/README.md
- addons/io/org.openhab.io.imperihome/README.md
> [IO Addons] Correct linter errors only

- addons/binding/org.openhab.binding.bigassfan/README.md
- PorchFanLightSpeed -> PorchFanLightLevel
> [BigAssFan Binding] Correct sitemap example

- addons/binding/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/protocol/KodiClientSocket.java
- addons/binding/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/protocol/KodiConnection.java
The normal behavior of fast forward on Kodi is that the speed increases with each click on fast forward and slows down by pressing the rewind button until normal speed is reached. Same for rewind. This PR adds this behavior to the Kodi binding.
> [Kodi] Feature faster fast forward

- addons/io/org.openhab.io.homekit/ESH-INF/config/config.xml
fixes https://github.com/openhab/openhab2-addons/issues/3049
> Fixed typo

- addons/binding/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/net/SocketChannelSession.java
- addons/binding/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/handler/Cm11aAbstractHandler.java
- addons/binding/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/internal/X10Interface.java
- addons/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/handler/DSCAlarmBaseBridgeHandler.java
- addons/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/handler/PanelThingHandler.java
- addons/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/DSCAlarmMessage.java
- addons/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/discovery/IT100BridgeDiscovery.java
- addons/binding/org.openhab.binding.globalcache/src/main/java/org/openhab/binding/globalcache/internal/command/CommandSetserial.java
- addons/binding/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/BaseChannelHandler.java
- addons/binding/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/core/LxServer.java
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/grxprg/SocketSession.java
- addons/binding/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/handler/MaxCubeBridgeHandler.java
- addons/binding/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/test/EmulatedV6Bridge.java
- addons/binding/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/PresenceDetection.java
- addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/NikoHomeControlCommunication.java
- addons/binding/org.openhab.binding.onebusaway/src/main/java/org/openhab/binding/onebusaway/internal/handler/StopHandler.java
- addons/binding/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/OnkyoConnection.java
- addons/binding/org.openhab.binding.pentair/src/main/java/org/openhab/binding/pentair/handler/PentairEasyTouchHandler.java
- addons/binding/org.openhab.binding.pentair/src/main/java/org/openhab/binding/pentair/handler/PentairIntelliFloHandler.java
- addons/binding/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/net/SocketChannelSession.java
- addons/binding/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/rio/RioPresetsProtocol.java
- addons/binding/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/handler/ZoneMinderServerBridgeHandler.java
- addons/binding/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/handler/ZoneMinderThingMonitorHandler.java
See openhab/static-code-analysis#213
and openhab/static-code-analysis#237
Signed-off-by: Kristina S. Simova <kssimovaa@gmail.com>
> Fixed few loggers with mismatching placeholder-parameter count

- addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/hardware/callbacks/FritzAhaDiscoveryCallback.java
- addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/hardware/callbacks/FritzAhaUpdateXmlCallback.java
> [avmfritz] Reduced log level

- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/station/NAMainHandler.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/thermostat/NAPlugHandler.java
Signed-off-by: Gaël L'hopital <glhopital@gmail.com>
> Corrects issue #3048 and hopefully #3066

- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/handler/AbstractNetatmoThingHandler.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/handler/NetatmoBridgeHandler.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/handler/NetatmoDeviceHandler.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/handler/NetatmoModuleHandler.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/handler/TrustingOkHttpClient.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/NetatmoHandlerFactory.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/RefreshStrategy.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/WeatherUtils.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/WelcomeWebHookServlet.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/channelhelper/BatteryHelper.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/station/NAMainHandler.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/thermostat/NAPlugHandler.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/thermostat/NATherm1Handler.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/welcome/NAWelcomeHomeHandler.java
Some small changes fixing a part of #3048 and some general small cleanups
Signed-off-by: Martin van Wingerden <martinvw@mtin.nl>
> [Netatmo] small bug fix

- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/ChannelTypeUtils.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/station/NAMainHandler.java
> [netatmo] Moved null check

- addons/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/PlugwiseMessageSender.java
* Log missed ACKs for NETWORK_STATUS_REQUEST on debug
* Use messageHexString in log messages instead of packetString which makes logging better readable
> [Plugwise] Tune logging

- addons/binding/org.openhab.binding.homematic/README.md
- addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/virtual/PressVirtualDatapointHandler.java
> [Homematic] Added CONT to press trigger channel

- addons/binding/org.openhab.binding.loxone/ESH-INF/thing/thing-types.xml
- addons/binding/org.openhab.binding.loxone/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.loxone/README.md
- addons/binding/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/handler/LoxoneMiniserverHandler.java
- addons/binding/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/LoxoneDynamicStateDescriptionProvider.java
- addons/binding/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/config/LoxoneMiniserverConfig.java
- addons/binding/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/core/LxJsonApp3.java
- addons/binding/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/core/LxJsonResponse.java
- addons/binding/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/core/LxOfflineReason.java
- addons/binding/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/core/LxServer.java
- addons/binding/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/core/LxServerListener.java
- addons/binding/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/core/LxWsClient.java
- addons/binding/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/core/LxWsSecurity.java
- addons/binding/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/core/LxWsSecurityHash.java
- addons/binding/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/core/LxWsSecurityToken.java
- addons/binding/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/core/LxWsSecurityType.java
- addons/binding/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/core/LxWsStateUpdateEvent.java
- addons/binding/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/discovery/LoxoneMiniserverDiscoveryParticipant.java
A new safer authentication method that involves tokens instead of passwords.
It also includes encryption and decryption of commands.
Two things to clear up before ready, I hope someone can help me with that:
**First**
Unfortunately, the tokens are supposed to be generated and negotiated with the Miniserver from within the application that will be using them. A password is needed for this generation. This kind of removes the benefit of having tokens, unless we can clear the password in the configuration after token is generated and stored (persistently). Is this a scenario that makes sense for openHAB? I'm not sure if a binding can override user configuration parameters. Even so, this seems ugly and we would need to inform the user if token expired to reenter the password. 
**Second …
> [Loxone] Token-based authentication and encryption of commands.

- addons/binding/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/core/LxWsSecurity.java
- addons/binding/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/core/LxWsSecurityHash.java
- addons/binding/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/core/LxWsSecurityToken.java
- addons/binding/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/core/LxWsSecurityType.java
See openhab/static-code-analysis#231
Signed-off-by: Svilen Valkanov <svilen.valkanov@musala.com>
> Update headers in Loxone binding

- addons/binding/org.openhab.binding.onkyo/ESH-INF/thing/tx-nr828.xml
- addons/binding/org.openhab.binding.onkyo/ESH-INF/thing/tx-nr838.xml
- addons/binding/org.openhab.binding.onkyo/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/handler/OnkyoHandler.java
- addons/binding/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/OnkyoAlbumArt.java
Set mime type for album art image channel.
Fixed also TX-NR828 and TX-NR838 thing types to match file names.
Fixes #3088
> [Onkyo] Set album art mime type

- addons/binding/org.openhab.binding.rfxcom.test/src/test/java/org/openhab/binding/rfxcom/internal/messages/RFXComLighting4MessageTest.java
- addons/binding/org.openhab.binding.rfxcom/ESH-INF/thing/lighting4.xml
- addons/binding/org.openhab.binding.rfxcom/README.md
- addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComLighting4Message.java
Added support for 10, 11 and 14
Fixes: #3103
> [rfxcom] additional lighting4 support

- addons/binding/org.openhab.binding.bigassfan/src/main/java/org/openhab/binding/bigassfan/handler/BigAssFanHandler.java
Fixed the processing of fan smartmode message (see [here](https://community.openhab.org/t/new-binding-request-big-ass-fans-senseme-haiku/23857/11))
Clarified debug messages related to fan & light smartmode.
Fixed IDE warning in processMessage method.
> [bigassfan] Fix fan smartmode processing

- addons/binding/org.openhab.binding.yamahareceiver/ESH-INF/thing/thing-types.xml
- addons/binding/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/YamahaReceiverBindingConstants.java
- addons/binding/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/ChannelsTypeProviderAvailableInputs.java
- addons/binding/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/ChannelsTypeProviderPreset.java
...between the ChannelTypeProvider and the ChannelTypeRegistry
which was established well-hidden via the TypeResolver.
Signed-off-by: Simon Kaufmann <simon.kfm@googlemail.com>
> [yamaha] resolved cyclic dependency

- addons/binding/org.openhab.binding.keba/ESH-INF/thing/kecontact.xml
> [Keba] Minor fix in ESH-INF

- addons/binding/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/handler/DishwasherChannelSelector.java
- addons/binding/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/handler/HobChannelSelector.java
- addons/binding/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/handler/MieleApplianceHandler.java
> [Miele] Fix NPE in HobChannelSelector + some minor code layout fixes

- addons/binding/org.openhab.binding.pioneeravr/README.md
> Fixed layout of Pioneer AVR documentation

- addons/binding/org.openhab.binding.mcp23017/README.md
> fixed layout in mcp docs

- addons/binding/org.openhab.binding.helios/.classpath
> corrected JRE to Java8 in order to fix compilation errors in the IDE

- pom.xml
- tools/checkstyle.properties
**Note: This should be merged after the next release of the static-code-analysis tool.**
> Added static-code-analysis tool configuration file.

- addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/handler/SqueezeBoxPlayerHandler.java
- addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/handler/SqueezeBoxServerHandler.java
Modifies cover art URL construction
Fixes cover art caching issue. Fixes #3043 
Small optimization to downloadImage
Catch IllegalArgumentException from HttpUtil in downloadImage
> [squeezebox] Simplify artwork url construction and fix caching issue

- addons/binding/org.openhab.binding.keba/src/main/java/org/openhab/binding/keba/handler/KeContactHandler.java
- addons/binding/org.openhab.binding.keba/src/main/java/org/openhab/binding/keba/handler/KeContactTransceiver.java
> [Keba] Improve Thread handling and synchronisation

- addons/binding/org.openhab.binding.onewiregpio/pom.xml
- addons/binding/org.openhab.binding.onewiregpio/src/main/java/org/openhab/binding/onewiregpio/handler/OneWireGPIOHandler.java
Some code style fixes, to unbreak the build
> [hotfix] [onewiregpio] Some code style fixes

- addons/binding/org.openhab.binding.jeelink/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/lacrosse/LaCrosseRollingReadingAverage.java
- addons/binding/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/lacrosse/LaCrosseTemperatureReading.java
- addons/binding/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/lacrosse/LaCrosseTemperatureReadingConverter.java
- addons/binding/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/lacrosse/LaCrosseTemperatureSensorHandler.java
This adds support for LaCrosse sensors having more than one temperature/humidity sensor.
It dynamically adds channels to the Sensor thing for the additional sensors.
Closes #3027.
Signed-off-by: Volker Bier volker.bier@web.de
> [jeelink] Add support for sensors with multiple channels.

- addons/binding/org.openhab.binding.keba/src/main/java/org/openhab/binding/keba/handler/KeContactHandler.java
- addons/binding/org.openhab.binding.keba/src/main/java/org/openhab/binding/keba/handler/KeContactTransceiver.java
> [Keba] Fix typo in Class name

- addons/ui/org.openhab.ui.cometvisu/src/main/java/org/openhab/ui/cometvisu/internal/backend/ConfigResource.java
- addons/ui/org.openhab.ui.cometvisu/src/main/java/org/openhab/ui/cometvisu/internal/servlet/CometVisuApp.java
- fix string->boolean conversion for config setting
- fix rest path annotation
fixes #3167
> [cometvisu] Fix config error and rest 500 errors

- addons/ui/org.openhab.ui.cometvisu/src/main/java/org/openhab/ui/cometvisu/internal/servlet/CometVisuApp.java
refs #3197
addition to the referenced PR, which did not seem to be complete
> [cometvisu] add type check to handle string and boolean values

- addons/binding/org.openhab.binding.tplinksmarthome.test/src/test/resources/org/openhab/binding/tplinksmarthome/internal/model/plug_get_realtime_response_v2.json
- addons/binding/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/device/BulbDevice.java
- addons/binding/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/model/Realtime.java
[tplinksmarthome] Fixed HS110v2 power meter readings so they are consistent with the HS110v1 devices.
Fixes #3172
@Hilbrand, this method is slightly different than the original SerializedName annotations in Realtime.java that we both attempted at previously.  However this approach seems like least amount of risk in trying to detect the versions of different devices and is also a simple means to apply the appropriate emeter conversions.  
Signed-off-by: KC Stonacek <source@stonacek.nz> (github: kcstonacek)
> [tplinksmarthome] fix for HS110v2 power meter calculations #3172

- addons/binding/org.openhab.binding.helios/src/main/java/org/openhab/binding/helios/handler/HeliosHandler221.java
> [Helios] safeguard against a potential NPE

- addons/binding/org.openhab.binding.helios/README.md
> [Helios] Fix Documentation

- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/handler/NetatmoBridgeHandler.java
> Netatmo: avoid remaining in INITIALIZING state in case of API timeout

- addons/binding/org.openhab.binding.avmfritz.test/src/test/java/org/openhab/binding/avmfritz/internal/ahamodel/HeatingModelTest.java
- addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/handler/DeviceHandler.java
- addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/ahamodel/HeatingModel.java
See discussion in issue #3244 .
Closes #3244 
> [avmfritz] Fix for BigDecimal precision issues

- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/welcome/NAWelcomeHomeHandler.java
> Netatmo: fix refresh frequency for Welcome camera

- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/handler/AbstractNetatmoThingHandler.java
> Netatmo: check if channel is linked before updating its state

- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/handler/NetatmoBridgeHandler.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/NetatmoHandlerFactory.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/WelcomeWebHookServlet.java
Start the webhook servlet only when appropriate
Fixes #2988
> Netatmo: discovery service and webhook servlet for each bridge thing

- addons/ui/org.openhab.ui.cometvisu/README.md
- addons/ui/org.openhab.ui.cometvisu/src/main/java/org/openhab/ui/cometvisu/internal/backend/ChartResource.java
- fix some errors in readme, and add some hints about charting
- add some debug logging in the ChartResource
> [cometvisu] documentation fixes + debug logging

- addons/binding/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/handler/MieleBridgeHandler.java
> reduced logging level

- addons/binding/org.openhab.binding.kodi/META-INF/MANIFEST.MF
> removed dependency to annotations

- addons/binding/org.openhab.binding.icloud/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.lametrictime/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.netatmo/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.nikohomecontrol/META-INF/MANIFEST.MF
> removed dependency to DS annotations

- addons/binding/org.openhab.binding.jeelink/ESH-INF/i18n/jeelink.properties
- addons/binding/org.openhab.binding.jeelink/ESH-INF/i18n/jeelink_de.properties
- addons/binding/org.openhab.binding.jeelink/ESH-INF/thing/thing-types.xml
- addons/binding/org.openhab.binding.jeelink/README.md
- addons/binding/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/JeeLinkBindingConstants.java
- addons/binding/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/IgnoringConverter.java
- addons/binding/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/JeeLinkHandler.java
- addons/binding/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/ReadingHandler.java
- addons/binding/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/SensorDefinition.java
- addons/binding/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/config/Pca301SensorConfig.java
- addons/binding/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/connection/AbstractJeeLinkConnection.java
- addons/binding/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/connection/JeeLinkConnection.java
- addons/binding/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/connection/JeeLinkTcpConnection.java
- addons/binding/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/discovery/SensorDiscoveryService.java
- addons/binding/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/ec3k/Ec3kReadingConverter.java
- addons/binding/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/ec3k/Ec3kSensorHandler.java
- addons/binding/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/lacrosse/LaCrosseSensorDefinition.java
- addons/binding/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/lacrosse/LaCrosseTemperatureReadingConverter.java
- addons/binding/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/lacrosse/LaCrosseTemperatureSensorHandler.java
- addons/binding/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/pca301/DiscardConfigReadingsPublisher.java
- addons/binding/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/pca301/Pca301Reading.java
- addons/binding/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/pca301/Pca301ReadingConverter.java
- addons/binding/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/pca301/Pca301SensorDefinition.java
- addons/binding/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/pca301/Pca301SensorHandler.java
This adds support for PCA301 power monitoring wireless sockets.
> [jeelink]  add support for PCA301 sockets

- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/handler/NetatmoModuleHandler.java
> Netatmo: run parent refresh for modules in a scheduled task

- addons/binding/org.openhab.binding.tesla/ESH-INF/thing/models.xml
- addons/binding/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/TeslaChannelSelectorProxy.java
- addons/binding/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/protocol/ClimateState.java
> [Tesla] Fix https://github.com/openhab/openhab2-addons/issues/3289

- addons/binding/org.openhab.binding.netatmo/ESH-INF/thing/channels.xml
- addons/binding/org.openhab.binding.netatmo/ESH-INF/thing/welcomehome.xml
- addons/binding/org.openhab.binding.netatmo/ESH-INF/thing/welcomeperson.xml
- addons/binding/org.openhab.binding.netatmo/README.md
> Netatmo: improve documentation with tables for list of channels

- addons/binding/org.openhab.binding.netatmo/ESH-INF/i18n/netatmo_de.properties
- addons/binding/org.openhab.binding.netatmo/ESH-INF/i18n/netatmo_fr.properties
Add strings for Netatmo Welcome
Fixes #3288
> Netatmo: update binding internationalization

- addons/binding/org.openhab.binding.mihome/ESH-INF/binding/binding.xml
- addons/binding/org.openhab.binding.mihome/ESH-INF/thing/aqara_86sw1.xml
- addons/binding/org.openhab.binding.mihome/ESH-INF/thing/aqara_ctrl_ln1.xml
- addons/binding/org.openhab.binding.mihome/ESH-INF/thing/channel.xml
- addons/binding/org.openhab.binding.mihome/ESH-INF/thing/curtain.xml
- addons/binding/org.openhab.binding.mihome/ESH-INF/thing/gateway.xml
- addons/binding/org.openhab.binding.mihome/ESH-INF/thing/sensor_cube.xml
- addons/binding/org.openhab.binding.mihome/ESH-INF/thing/sensor_ht.xml
- addons/binding/org.openhab.binding.mihome/ESH-INF/thing/sensor_motion.xml
- addons/binding/org.openhab.binding.mihome/ESH-INF/thing/sensor_motion_aq2.xml
- addons/binding/org.openhab.binding.mihome/ESH-INF/thing/sensor_switch.xml
- addons/binding/org.openhab.binding.mihome/ESH-INF/thing/sensor_switch_aq2.xml
- addons/binding/org.openhab.binding.mihome/README.md
- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/XiaomiGatewayBindingConstants.java
- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/handler/XiaomiActorGatewayHandler.java
- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/ModelMapper.java
Hi all!
After a while without any updates here comes a little one:
- __improvement:__ you can now trigger inclusion mode of the gateway from the binding (see #2851)! Have a look in the readme, there you have an example of a switch item for that. As the gateway only accepts new devices for 30sec after activation, it's hardcoded into the binding, that the channel resets to OFF 30sec after the ON command
- __bugfix:__ implemented a small fix for the issue #2957, so that the model `ctrl_ln1.aq1` is now discovered correctly
- __bugfix:__ reformatted all xml files to only have tabbed whitespace
Download link for snapshot JAR:
https://openhab.jfrog.io/openhab/libs-pullrequest-local/org/openhab/binding/org.openhab.binding.mihome/2.3.0-SNAPSHOT/org.openhab.binding.mihome-2.3.0-SNAPSHOT.jar
> [mihome] fix #2957 & add device inclusion to gateway (#2851)

- src/etc/xml-header-style.xml
@kaikreuzer License header style and for openhab2-addons.
> Add new license header style for the XML files

- addons/binding/org.openhab.binding.cm11a/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.cm11a/README.md
- addons/binding/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/handler/Cm11aAbstractHandler.java
- addons/binding/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/handler/Cm11aApplianceHandler.java
- addons/binding/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/handler/Cm11aBridgeHandler.java
- addons/binding/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/handler/Cm11aLampHandler.java
- addons/binding/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/internal/X10Interface.java
Fixes the null pointer exception reported in [this community thread](https://community.openhab.org/t/cm11a-binding-failed-to-initialize-null-pointer-exception/39369/2).
Also fixes a number of compiler warnings.
Signed-off-by: Chris Carman <namraccr@gmail.com> (github: 9037568)
> [CM11a] Fix null pointer exception

- addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/discovery/AVMFritzDiscoveryService.java
- addons/binding/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/discovery/LGWebOSDiscovery.java
- addons/binding/org.openhab.binding.zway/src/main/java/org/openhab/binding/zway/internal/discovery/ZWayDeviceDiscoveryService.java
Related to https://github.com/eclipse/smarthome/pull/5227
> removed static reference to scheduler

- addons/binding/org.openhab.binding.avmfritz/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/discovery/AVMFritzUpnpDiscoveryParticipant.java
> [avmfritz] Use UpnpDiscoveryParticipant  of different package

- addons/binding/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/rio/AbstractBridgeHandler.java
- addons/binding/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/rio/AbstractThingHandler.java
- addons/binding/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/rio/RioCallbackHandler.java
- addons/binding/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/rio/controller/RioControllerHandler.java
- addons/binding/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/rio/system/RioSystemHandler.java
- addons/binding/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/rio/zone/RioZoneHandler.java
> adapted implementation to not collide with the newly introduced getCallback method in ESH

- addons/binding/org.openhab.binding.kodi/ESH-INF/thing/thing-types.xml
- addons/binding/org.openhab.binding.kodi/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/discovery/KodiUpnpDiscoveryParticipant.java
- Moved UpnpDiscoveryParticipant
- Added representation property to thing-type
> [Kodi] Use UpnpDiscoveryParticipant of different package

- addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/parser/CcuLoadDeviceNamesParser.java
- addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/parser/CommonRpcParser.java
- addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/parser/DeleteDevicesParser.java
- addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/parser/EventParser.java
- addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/parser/HomegearLoadDeviceNamesParser.java
- addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/parser/ListBidcosInterfacesParser.java
- addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/parser/ListDevicesParser.java
- addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/parser/NewDevicesParser.java
> Fixed error when device address contains invalid characters

- features/openhab-addons/src/main/feature/feature.xml
> added http client dependency to Kodi

- pom.xml
> moved release repo in profile

- addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/KNXCoreTypeMapper.java
update mapping 9.007 to PercentType
> update mapping 9.007 to PercentType

- addons/binding/org.openhab.binding.irtrans/.classpath
- addons/binding/org.openhab.binding.irtrans/.project
- addons/binding/org.openhab.binding.irtrans/ESH-INF/binding/binding.xml
- addons/binding/org.openhab.binding.irtrans/ESH-INF/thing/blaster.xml
- addons/binding/org.openhab.binding.irtrans/ESH-INF/thing/ethernetbridge.xml
- addons/binding/org.openhab.binding.irtrans/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.irtrans/OSGI-INF/org.openhab.binding.irtrans.internal.IRtransHandlerFactory.xml
- addons/binding/org.openhab.binding.irtrans/README.md
- addons/binding/org.openhab.binding.irtrans/about.html
- addons/binding/org.openhab.binding.irtrans/build.properties
- addons/binding/org.openhab.binding.irtrans/pom.xml
- addons/binding/org.openhab.binding.irtrans/src/main/java/org/openhab/binding/irtrans/IRtransBindingConstants.java
- addons/binding/org.openhab.binding.irtrans/src/main/java/org/openhab/binding/irtrans/IrCommand.java
- addons/binding/org.openhab.binding.irtrans/src/main/java/org/openhab/binding/irtrans/handler/BlasterHandler.java
- addons/binding/org.openhab.binding.irtrans/src/main/java/org/openhab/binding/irtrans/handler/EthernetBridgeHandler.java
- addons/binding/org.openhab.binding.irtrans/src/main/java/org/openhab/binding/irtrans/handler/TransceiverStatusListener.java
- addons/binding/org.openhab.binding.irtrans/src/main/java/org/openhab/binding/irtrans/internal/IRtransHandlerFactory.java
- addons/binding/pom.xml
- features/openhab-addons/src/main/feature/feature.xml
Replaces PR #16 
Signed-off-by: Karel Goderis <karel.goderis@me.com> (github: kgoderis)
> Initial contribution of IRtrans 2.0 binding

- addons/binding/org.openhab.binding.onkyo/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/OnkyoConnection.java
- addons/binding/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/eiscp/EiscpProtocol.java
Fixes #3421
Signed-off-by: Martin van Wingerden <martinvw@mtin.nl>
> [onkyo] Replaced usage of DatatypeConverter

- addons/binding/org.openhab.binding.regoheatpump/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/handler/Rego6xxHeatPumpHandler.java
- addons/binding/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/rego6xx/AbstractResponseParser.java
Fixes #3423 
Signed-off-by: Lyubomir V. Papazov <lpapazow@gmail.com>
> Replaced usage of DatatypeConverter

- addons/binding/pom.xml
> Added Nibe heatpump to build

- addons/binding/org.openhab.binding.nibeheatpump.test/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.nibeheatpump.test/about.html
- addons/binding/org.openhab.binding.nibeheatpump.test/build.properties
- addons/binding/org.openhab.binding.nibeheatpump.test/src/test/java/org/openhab/binding/nibeheatpump/internal/message/NibeHeatPumpProtocolTest.java
- addons/binding/org.openhab.binding.nibeheatpump/ESH-INF/binding/binding.xml
- addons/binding/org.openhab.binding.nibeheatpump/ESH-INF/thing/f1x45.xml
- addons/binding/org.openhab.binding.nibeheatpump/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.nibeheatpump/README.md
- addons/binding/org.openhab.binding.nibeheatpump/about.html
- addons/binding/org.openhab.binding.nibeheatpump/build.properties
- addons/binding/org.openhab.binding.nibeheatpump/pom.xml
- addons/binding/org.openhab.binding.nibeheatpump/src/main/java/org/openhab/binding/nibeheatpump/handler/NibeHeatPumpHandler.java
- addons/binding/org.openhab.binding.nibeheatpump/src/main/java/org/openhab/binding/nibeheatpump/internal/connection/SerialConnector.java
- addons/binding/org.openhab.binding.nibeheatpump/src/main/java/org/openhab/binding/nibeheatpump/internal/protocol/NibeHeatPumpProtocolContext.java
- addons/binding/org.openhab.binding.nibeheatpump/src/main/java/org/openhab/binding/nibeheatpump/internal/protocol/NibeHeatPumpProtocolDefaultContext.java
- addons/binding/org.openhab.binding.nibeheatpump/src/main/java/org/openhab/binding/nibeheatpump/internal/protocol/NibeHeatPumpProtocolStates.java
> [Nibe] Code analysis fixes

- addons/ui/org.openhab.ui.cometvisu/src/main/java/org/openhab/ui/cometvisu/internal/servlet/CometVisuServlet.java
> [cometvisu] remove 'kuf-' prefix from icon ids

- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/handler/NetatmoBridgeHandler.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/WelcomeWebHookServlet.java
One of the changes is for security reasons.
> Netatmo: few changes in log levels

- addons/binding/org.openhab.binding.onkyo/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/handler/OnkyoHandler.java
- addons/binding/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/handler/UpnpAudioSinkHandler.java
- addons/binding/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/OnkyoAlbumArt.java
- addons/binding/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/OnkyoConnection.java
- addons/binding/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/OnkyoEventListener.java
- addons/binding/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/OnkyoHandlerFactory.java
- addons/binding/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/config/OnkyoDeviceConfiguration.java
- addons/binding/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/discovery/OnkyoUpnpDiscoveryParticipant.java
- addons/binding/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/eiscp/EiscpProtocol.java
* Fix static code analysis findings
* Fix UpnpDiscoveryParticipant deprecation
* Use HexUtils instead of DatatypeConverter in OnkyoAlbumArt (#3431)
* Use diamond operator
* Use final loggers
Are you OK with these changes @paulianttila, @pail23?
> [Onkyo] Fix static code analysis findings and improvements

- addons/binding/org.openhab.binding.irtrans/.classpath
- addons/binding/org.openhab.binding.rfxcom/.classpath
* Fixes errors in the RFXCom Eclipse classpath
* Sets the IRTrans JVM to JavaSE-1.8
> Fix RFXCom and IRTrans Eclipse classpath files

- addons/binding/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/core/LxControlDimmer.java
Hello @martinvw 
It is a simple fix for handling zero value of dimmer. Please take a look and merge if ok.
We have a different min-max ranges for dimmer state value in OH and Loxone. Regardless of the proper scaling between the ranges, value zero should be passed transparently as it means to switch the dimmer off.
Thanks
Pawel
Signed-off-by: Pawel Pieczul <pieczul@gmail.com> (github: ppieczul)
> [Loxone] Fix for dimmer switch off

- addons/binding/org.openhab.binding.avmfritz.test/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.avmfritz.test/src/test/java/org/openhab/binding/avmfritz/internal/ahamodel/AVMFritzModelTest.java
- addons/binding/org.openhab.binding.avmfritz.test/src/test/java/org/openhab/binding/avmfritz/internal/ahamodel/HeatingModelTest.java
- addons/binding/org.openhab.binding.avmfritz.test/src/test/java/org/openhab/binding/avmfritz/internal/discovery/AVMFritzDiscoveryServiceTest.java
- addons/binding/org.openhab.binding.avmfritz/ESH-INF/i18n/avmfritz_de.properties
- addons/binding/org.openhab.binding.avmfritz/ESH-INF/thing/channel-types.xml
- addons/binding/org.openhab.binding.avmfritz/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.avmfritz/README.md
- addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/handler/AVMFritzBaseBridgeHandler.java
- addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/handler/AVMFritzBaseThingHandler.java
- addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/ahamodel/HeatingModel.java
- addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/ahamodel/PowerMeterModel.java
- Incorporated new QuantityType (Units of Measurement)
- Removed `org.hamcrest` dependency from unit tests
> [avmfritz] Incorporated new QuantityType (Units of Measurement)

- addons/binding/org.openhab.binding.tellstick/README.md
- Rewrite requirments for tellstick-core
- Fixed broken examples
Signed-off-by: Elias Gabrielsson <elias@benefactory.se> (github: EliasGabrielsson)
> Updated Tellstick README

- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/handler/XiaomiAqaraActorSwitch1Handler.java
- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/handler/XiaomiBridgeHandler.java
- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/handler/XiaomiDeviceBaseHandler.java
Signed-off-by: Dieter Schmidt <dima.loschkin@gmail.com>
Only small fixes in this PR:
- incorporate code like suggested in review for #3446 - thx to @martinvw 
- fix error message for devices "ctrl_neutral1" & "ctrl_ln1" even if command was processed
- remove non-existent verb
> [mihome] maintenance & fix false error log for 1 channel switches

- addons/binding/org.openhab.binding.avmfritz.test/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.knx.test/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.nibeheatpump.test/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.tplinksmarthome.test/META-INF/MANIFEST.MF
See openhab/static-code-analysis#285
See openhab/static-code-analysis#295
> Fixed occurrences of lines bigger than 72 bytes in some manifest files

- addons/binding/org.openhab.binding.network/README.md
Various fixes for spelling and grammar.
> [Network] Update README.md

- addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/AbstractHomematicGateway.java
closes https://github.com/openhab/openhab2-addons/issues/3090
> [homematic] Fixed CCU1 connection tracker

- addons/binding/org.openhab.binding.nibeheatpump/src/main/java/org/openhab/binding/nibeheatpump/handler/NibeHeatPumpHandler.java
> [nibeheatpump] fixed channel unlinking

- addons/binding/org.openhab.binding.network/README.md
> [Network] Fix file based binding configuration documentation

- addons/binding/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/TeslaChannelSelectorProxy.java
> [Tesla] Fix SEAT_HEATER_LEFT typeClass

- addons/binding/org.openhab.binding.irtrans/README.md
> [irTrans] Update README - See https://github.com/openhab/openhab2-addons/pull/3518

- addons/io/org.openhab.io.azureiothub/README.md
- addons/io/org.openhab.io.azureiothub/pom.xml
- features/openhab-addons/src/main/feature/feature.xml
> fixed spelling

- addons/binding/org.openhab.binding.nest.test/src/test/java/org/openhab/binding/nest/handler/NestCameraHandlerTest.java
- addons/binding/org.openhab.binding.nest.test/src/test/java/org/openhab/binding/nest/handler/NestThingHandlerOSGiTest.java
- addons/binding/org.openhab.binding.nest.test/src/test/java/org/openhab/binding/nest/internal/data/GsonParsingTest.java
- addons/binding/org.openhab.binding.nest.test/src/test/resources/org/openhab/binding/nest/internal/data/camera-data.json
- addons/binding/org.openhab.binding.nest.test/src/test/resources/org/openhab/binding/nest/internal/data/top-level-data.json
- addons/binding/org.openhab.binding.nest.test/src/test/resources/org/openhab/binding/nest/internal/data/top-level-streaming-data.json
- addons/binding/org.openhab.binding.nest/ESH-INF/thing/camera.xml
- addons/binding/org.openhab.binding.nest/ESH-INF/thing/channels.xml
- addons/binding/org.openhab.binding.nest/README.md
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/NestBindingConstants.java
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/handler/NestBaseHandler.java
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/handler/NestCameraHandler.java
* Move existing camera channels to camera# channel group
* Add new last event camera channels to last_event# channel group
* Update documentation and unit tests
Fixes #3458
> [Nest] Add last event channels to camera thing

- addons/binding/org.openhab.binding.nest.test/src/test/java/org/openhab/binding/nest/handler/NestStructureHandlerTest.java
- addons/binding/org.openhab.binding.nest.test/src/test/java/org/openhab/binding/nest/handler/NestThermostatHandlerTest.java
- addons/binding/org.openhab.binding.nest.test/src/test/java/org/openhab/binding/nest/internal/data/GsonParsingTest.java
- addons/binding/org.openhab.binding.nest.test/src/test/resources/org/openhab/binding/nest/internal/data/structure-data.json
- addons/binding/org.openhab.binding.nest.test/src/test/resources/org/openhab/binding/nest/internal/data/top-level-data.json
- addons/binding/org.openhab.binding.nest.test/src/test/resources/org/openhab/binding/nest/internal/data/top-level-streaming-data.json
- addons/binding/org.openhab.binding.nest/ESH-INF/thing/channels.xml
- addons/binding/org.openhab.binding.nest/ESH-INF/thing/structure.xml
- addons/binding/org.openhab.binding.nest/ESH-INF/thing/thermostat.xml
- addons/binding/org.openhab.binding.nest/README.md
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/NestBindingConstants.java
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/handler/NestBaseHandler.java
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/handler/NestBridgeHandler.java
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/handler/NestCameraHandler.java
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/handler/NestSmokeDetectorHandler.java
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/handler/NestStructureHandler.java
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/handler/NestThermostatHandler.java
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/NestHandlerFactory.java
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/data/Structure.java
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/data/Thermostat.java
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/discovery/NestDiscoveryService.java
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/listener/NestDeviceDataListener.java
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/listener/NestStreamingDataListener.java
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/rest/NestAuthorizer.java
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/rest/NestStreamingRequestFilter.java
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/rest/NestStreamingRestClient.java
* Add missing eco temperature channels to thermosat
* Add missing security state channel to structure
* Add missing null annotations
* Fix UI Color State channel label
* Add missing readOnly="true" to several channels
* Add options to fan timer duration channel
* Update tests and documentation
* Remove duplication from NestThermostatHandlerTest
> [Nest] Add missing units, channels and other improvements

- addons/binding/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/handler/GardenaThingHandler.java
> [gardena] Catch wrong date from gardena cloud

- addons/binding/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/handler/GardenaThingHandler.java
> [gardena] Fixed null state handling

- addons/binding/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/handler/TeslaHandler.java
> [Tesla] Fix change wrt Tesla’s back-end handling Event Stream errors

- addons/io/org.openhab.io.homekit/META-INF/MANIFEST.MF
> removed unused model dependency

- addons/binding/org.openhab.binding.seneye/META-INF/MANIFEST.MF
> removed unused joda-time dependency

- addons/ui/org.openhab.ui.cometvisu.php/pom.xml
- addons/ui/org.openhab.ui.cometvisu/pom.xml
This PR adds all "unusual" dependencies as Maven dependencies as they are no longer available to all add-ons with https://github.com/openhab/openhab-core/pull/341.
> added special dependencies

- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/handler/NetatmoDeviceHandler.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/handler/NetatmoModuleHandler.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/thermostat/NATherm1Handler.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/welcome/NAWelcomePersonHandler.java
> [Netatmo] Do not refresh module data when not expected

- addons/binding/org.openhab.binding.gardena/ESH-INF/i18n/gardena_de.properties
- addons/binding/org.openhab.binding.gardena/ESH-INF/thing/thing-types.xml
> [Gardena] Added power timer state options

- addons/binding/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/FreeboxDataListener.java
- addons/binding/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/handler/FreeboxHandler.java
- addons/binding/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/handler/FreeboxThingHandler.java
- addons/binding/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/FreeboxHandlerFactory.java
- addons/binding/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/config/FreeboxAirPlayDeviceConfiguration.java
- addons/binding/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/config/FreeboxNetDeviceConfiguration.java
- addons/binding/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/config/FreeboxNetInterfaceConfiguration.java
- addons/binding/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/config/FreeboxPhoneConfiguration.java
- addons/binding/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/config/FreeboxServerConfiguration.java
- addons/binding/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/discovery/FreeboxDiscoveryService.java
- addons/binding/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/discovery/FreeboxServerDiscoveryParticipant.java
Properties handling
Static code analysis
Exported FreeboxDataListener
Discovery service activate/deactivate
Replaces #2872
> [Freebox] Various little changes

- features/openhab-addons/src/main/feature/feature.xml
Fixes problem [reported here](https://community.openhab.org/t/openhab-2-3-release-candidate-available/45318/18?u=kai)
> removed outdated feature dependency

- addons/binding/org.openhab.binding.netatmo/README.md
- Changes spelling and grammar
- Fixed linter errors
See https://github.com/openhab/openhab2-addons/pull/3312#pullrequestreview-102876139
> [Netatmo] Addressed comments from review in #3312

- addons/binding/org.openhab.binding.keba/ESH-INF/thing/kecontact.xml
> [KEBA] fix kecontact.xml

- addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/handler/AVMFritzBaseThingHandler.java
- Added missing `initialize()` method in ThingHandler to avoid warning in logs
```
2018-05-24 11:14:04.086 [WARN ] [.core.thing.binding.BaseThingHandler] - BaseThingHandler.initialize() will be removed soon, ThingStatus can be set manually via updateStatus(ThingStatus.ONLINE)
```
> [avmfritz] Added missing initialize() method in ThingHandler to avoid warning in logs

- addons/binding/org.openhab.binding.amazonechocontrol/README.md
- addons/binding/org.openhab.binding.boschindego/README.md
- addons/binding/org.openhab.binding.icloud/README.md
- addons/binding/org.openhab.binding.netatmo/README.md
- addons/binding/org.openhab.binding.seneye/README.md
- addons/binding/org.openhab.binding.sleepiq/README.md
- addons/binding/org.openhab.binding.tado/README.md
- addons/binding/org.openhab.binding.tesla/README.md
> This domain is established to be used for illustrative examples in documents. You may use this domain in examples without prior coordination or asking for permission.
From example.com
Signed-off-by: mueller-ma <mueller-ma@users.noreply.github.com>
> Replace example mail addresses with mail@example.com

- CONTRIBUTING.md
- PULL_REQUEST_TEMPLATE.md
- addons/binding/org.openhab.binding.avmfritz/README.md
- addons/binding/org.openhab.binding.exec/README.md
- addons/binding/org.openhab.binding.logreader/README.md
- addons/binding/org.openhab.binding.loxone/README.md
- addons/binding/org.openhab.binding.phc/README.md
- addons/binding/org.openhab.binding.sensebox/README.md
- addons/binding/org.openhab.binding.squeezebox/README.md
- addons/binding/org.openhab.binding.zway/doc/GETTING_STARTED.md
- addons/io/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitTaggedItem.java
- addons/io/org.openhab.io.imperihome/README.md
- project-orga/MAINTAINERS.md
* Update documentations links to the new website layout
* Update GitHub links to use openhab/openhab2-addons repo instead of openhab/openhab2
> Update documentation links

- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/handler/NetatmoBridgeHandler.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/handler/NetatmoDataListener.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/handler/NetatmoDeviceHandler.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/NetatmoHandlerFactory.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/discovery/NetatmoModuleDiscoveryService.java
> [Netatmo] Automatic discovery of things without the need of a user request

- addons/binding/org.openhab.binding.kostalinverter/ESH-INF/thing/thing-types.xml
- addons/binding/org.openhab.binding.kostalinverter/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.kostalinverter/README.md
- addons/binding/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/kostal/inverter/ChannelConfig.java
- addons/binding/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/kostal/inverter/WebscrapeHandler.java
- Incorporated new QuantityType (Units of Measurement)
Fixes #3578
Fixes #3598
> [kostalinverter] Incorporated new QuantityType (Units of Measurement)

- tools/checkstyle.properties
Signed-off-by: Martin van Wingerden <martinvw@mtin.nl>
> Update version number regex

- addons/binding/org.openhab.binding.kostalinverter/ESH-INF/i18n/kostalinverter_de.properties
> [kostalinverter] Added German translations

- addons/binding/org.openhab.binding.robonect/README.md
> [robonect] Update README

- addons/voice/org.openhab.voice.marytts/README.md
> [MaryTTS] Add log files documentation

- addons/binding/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/KodiDynamicStateDescriptionProvider.java
> Kodi: fix for the dynamic state description provider

- addons/binding/org.openhab.binding.hyperion/src/main/java/org/openhab/binding/hyperion/internal/HyperionStateDescriptionProvider.java
> Hyperion: fix for the dynamic state description provider

- addons/binding/org.openhab.binding.denonmarantz/ESH-INF/binding/binding.xml
- addons/binding/org.openhab.binding.denonmarantz/ESH-INF/thing/thing-types.xml
- addons/binding/org.openhab.binding.hyperion/ESH-INF/binding/binding.xml
- addons/binding/org.openhab.binding.velbus/ESH-INF/thing/thing-types.xml
- addons/binding/org.openhab.binding.yamahareceiver/ESH-INF/binding/binding.xml
> Fixed indentation of some xml files.

- addons/binding/org.openhab.binding.robonect.test/.classpath
- addons/binding/org.openhab.binding.robonect.test/.project
Signed-off-by: Henning Treu <henning.treu@telekom.de>
> [robonect] remove obsolete groovy nature from IDE project file

- features/openhab-addons/src/main/feature/feature.xml
> Added Nibe Heat Pump Binding to features

- addons/binding/create_openhab_binding_skeleton.cmd
- addons/binding/create_openhab_binding_skeleton.sh
- addons/binding/create_openhab_binding_test_skeleton.cmd
- addons/binding/create_openhab_binding_test_skeleton.sh
Signed-off-by: Henning Treu <henning.treu@telekom.de>
> Set version 2.4.0 for new bindings

- addons/binding/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/ICloudConnection.java
Signed-off-by: Patrik Gfeller <patrik.gfeller@gmail.com>
> SOCKET_TIMEOUT changed from 2500 to 10000 to fix timeout problems

- addons/binding/org.openhab.binding.mihome/README.md
- Xiaomi Aqara Motion Sensor (with light intensity support)
> added examples

- addons/binding/org.openhab.binding.coolmasternet/src/main/java/org/openhab/binding/coolmasternet/handler/HVACHandler.java
- addons/binding/org.openhab.binding.coolmasternet/src/main/java/org/openhab/binding/coolmasternet/internal/ControllerHandler.java
- addons/binding/org.openhab.binding.coolmasternet/src/main/java/org/openhab/binding/coolmasternet/internal/CoolMasterNetHandlerFactory.java
> [CoolMasterNet] Fix NPEs, stop refreshJob when disposing bridge, add null annotations

- addons/binding/org.openhab.binding.nest.test/src/test/java/org/openhab/binding/nest/handler/NestThingHandlerOSGiTest.java
of https://github.com/eclipse/smarthome/pull/5700
> fixed compilation error after ESH update that includes the breaking changes

- addons/binding/org.openhab.binding.logreader/src/main/java/org/openhab/binding/logreader/handler/LogHandler.java
Signed-off-by: Pauli Anttila pauli.anttila@gmail.com
> [logreader] Fixed logging

- addons/binding/org.openhab.binding.gardena/README.md
> [gardena] Updated readme

- addons/binding/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/handler/FroniusBaseThingHandler.java
> [Fronius] Fix the NullPointerException

- addons/binding/org.openhab.binding.coolmasternet/src/main/java/org/openhab/binding/coolmasternet/handler/HVACHandler.java
- addons/binding/org.openhab.binding.coolmasternet/src/main/java/org/openhab/binding/coolmasternet/internal/ControllerHandler.java
> [CoolMasterNet] Fix NPEs, restart refreshJob on Thing updates

- addons/binding/org.openhab.binding.coolmasternet/src/main/java/org/openhab/binding/coolmasternet/handler/HVACHandler.java
Fixes the NumberFormatException reported by @Dan1001 in https://github.com/openhab/openhab2-addons/issues/3717#issuecomment-404602197.
There's also a [org.openhab.binding.coolmasternet-2.4.0-SNAPSHOT.zip](https://github.com/openhab/openhab2-addons/files/2190629/org.openhab.binding.coolmasternet-2.4.0-SNAPSHOT.zip) for testing.
I created a PR for adding null annotations to the types to prevent future null issues, see https://github.com/eclipse/smarthome/pull/5901.
> [CoolMasterNet] Fix NumberFormatException during refresh

- addons/binding/org.openhab.binding.amazonechocontrol/README.md
Added an information about where to find the serial number besides the Alexa App.
> [amazonechocontrol] Amazon Devices - serial number location

- addons/binding/org.openhab.binding.max/README.md
- Correct Thing definition example within Bridge (current example works but throws errors)
- Include example for Shutter contact
- Update Item definition example with shutter contact and UoM
> [max] Update Readme

- addons/binding/org.openhab.binding.coolmasternet/ESH-INF/thing/thing-types.xml
- addons/binding/org.openhab.binding.dscalarm/ESH-INF/thing/envisalinkbridge.xml
- addons/binding/org.openhab.binding.dscalarm/ESH-INF/thing/tcpserverbridge.xml
- addons/binding/org.openhab.binding.freebox/ESH-INF/thing/thing-types.xml
- addons/binding/org.openhab.binding.hdpowerview/ESH-INF/thing/thing-types.xml
- addons/binding/org.openhab.binding.miele/ESH-INF/thing/xgw3000.xml
- addons/binding/org.openhab.binding.mihome/ESH-INF/config/config.xml
Same as https://github.com/eclipse/smarthome/pull/5964
> Fixed network-address context

- addons/binding/org.openhab.binding.gardena/README.md
> [gardena] Fixed readme

- addons/binding/org.openhab.binding.airquality/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/AirQualityBindingConstants.java
> removed Guava dependency in Airquality binding

- addons/binding/org.openhab.binding.valloxmv/src/main/java/org/openhab/binding/valloxmv/internal/ValloxMVHandler.java
Signed-off-by: Björn Brings <bjoernbrings@web.de>
Compare #3782 and #3777 
No more conversion required
> [valloxmv] Removed unused Number to QuantityType command conversion

- addons/binding/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/discovery/KodiUpnpDiscoveryParticipant.java
- Applied changes from review in PR https://github.com/openhab/openhab2-addons/pull/3775#discussion_r206810999
> [Kodi] Added deactivation of background discovery

- addons/binding/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/handler/FreeboxHandler.java
- addons/binding/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/handler/FreeboxThingHandler.java
- addons/binding/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/FreeboxAirPlayAudioSink.java
- addons/binding/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/FreeboxHandlerFactory.java
- addons/binding/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/discovery/FreeboxServerDiscoveryParticipant.java
> Freebox: fix Eclipse warnings and deprecated code

- addons/binding/org.openhab.binding.modbus.test/pom.xml
- addons/binding/org.openhab.binding.nibeheatpump.test/pom.xml
- addons/binding/org.openhab.binding.robonect.test/pom.xml
- addons/binding/org.openhab.binding.wifiled.test/pom.xml
- addons/binding/org.openhab.binding.yamahareceiver.test/pom.xml
- addons/io/org.openhab.io.transport.modbus.test/pom.xml
Maven really needs to use the placeholder consistently otherwise it will not resolve.
cc: @pfink
> Corrected references to tycho

- addons/binding/org.openhab.binding.max.test/src/test/java/org/openhab/binding/max/internal/message/L_MessageTest.java
- addons/binding/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/device/Device.java
- addons/binding/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/handler/MaxDevicesHandler.java
- Considered 'error' flag to set thing to OFFLINE
- Ported test case for `L_Message` from OH1 addon
Closes #2753
> [max] Considered 'error' flag to set thing to OFFLINE

- addons/binding/org.openhab.binding.max/ESH-INF/i18n/max_de.properties
- addons/binding/org.openhab.binding.max/ESH-INF/thing/bridge.xml
- addons/binding/org.openhab.binding.max/ESH-INF/thing/thing-types.xml
- addons/binding/org.openhab.binding.max/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.max/README.md
- addons/binding/org.openhab.binding.max/src/main/java/org/openhab/binding/max/MaxBinding.java
- addons/binding/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/device/HeatingThermostat.java
- addons/binding/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/discovery/MaxCubeBridgeDiscovery.java
- addons/binding/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/handler/MaxCubeBridgeHandler.java
- addons/binding/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/handler/MaxDevicesHandler.java
- Incorporated new QuantityType (Units of Measurement)
- Replaced `Runnable`
- Added 'representation-property' tag in brige type an thing type definitions
- Removed dependencies for `com.google.common.*` (Guava)
Fixes #3689 
> [max] Incorporated new QuantityType (Units of Measurement)

- addons/binding/org.openhab.binding.max.test/src/test/java/org/openhab/binding/max/internal/message/H_MessageTest.java
- addons/binding/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/message/H_Message.java
- Fixed wrong timestamp in logs
Fixes #3091 
> [max] Fixed wrong timestamp in logs

- addons/binding/org.openhab.binding.netatmo/ESH-INF/thing/healthyhomecoach.xml
- addons/binding/org.openhab.binding.netatmo/ESH-INF/thing/station.xml
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/handler/NetatmoDeviceHandler.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/RefreshStrategy.java
> Netatmo: automatic search of the refresh interval

- addons/io/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/NeeoService.java
Related to https://github.com/eclipse/smarthome/pull/6091#issuecomment-414770757
> [NEEO] adapt listener registration to changed ESH API

- addons/binding/org.openhab.binding.freebox/ESH-INF/thing/thing-types.xml
- addons/binding/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/FreeboxDataListener.java
- addons/binding/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/handler/FreeboxHandler.java
- addons/binding/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/config/FreeboxServerConfiguration.java
- addons/binding/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/discovery/FreeboxDiscoveryService.java
> Freebox: make things discovery configurable

- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/handler/XiaomiAqaraActorSwitch1Handler.java
- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/handler/XiaomiAqaraActorSwitch2Handler.java
- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/ModelMapper.java
Signed-off-by: Dieter Schmidt <dima.loschkin@gmail.com>
- fix #3100: Devices responded with actual state first, then with target state - causing item to be updated by user command, then being reset to former state, then set to the target state again. I disabled parsing of the "write_ack" messages for the devices, as they don't provide any valueable information
- add aqara cube: new cube version basically supports same events as old so just mapped the device "sensor_cube.aqgl1" to the first version handler
If anybody wants to test things out and leave a quick feedback, [here is the link to the JAR file](https://openhab.jfrog.io/openhab/libs-pullrequest-local/org/openhab/binding/org.openhab.binding.mihome/2.4.0-SNAPSHOT/org.openhab.binding.mihome-2.4.0-SNAPSHOT.jar)
> [MiHome] add Aqara Cube & fix #3100

- addons/binding/org.openhab.binding.netatmo/README.md
In the documentation it says:
Thing netatmo:NAMain:home:inside "Netatmo Inside" [ id="aa:aa:aa:aa:aa:aa" ]
and
Thing NAMain livingroom [ id="aa:aa:aa:aa:aa:aa" ]
According to the ESH docs the second one is the preferred way to use. So the syntax is Thing <thingTypeId> <thingId> [] . As a short cut it is possible to skip the Thing in the textual configuration, however this confuses the average user, so I changed the first one to to second one.
> Made thing configuration consistant throughout the file Signed-off-by: Kim Skatun <skatun@gmail.com> (github: github_handle)

- addons/binding/org.openhab.binding.logreader/README.md
Signed-off-by: Holger Eisold <kugelsicha@gmail.com> (github: HerzScheisse)
> [LogReader] update readme & added [CUSTOM] example

- addons/binding/org.openhab.binding.neato/src/main/java/org/openhab/binding/neato/internal/classes/AvailableServices.java
Signed-off-by: Holger Eisold holgereisold@gmx.de (github: HerzScheisse)
> [Neato] Typo in setGeneralInfo class

- addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/handler/SqueezeBoxServerHandler.java
> [squeezebox] Fix 60-second squeeze server reconnect

- addons/binding/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/handler/MaxCubeBridgeHandler.java
rollback readlines to previous logic to fix cube remaining offline
> [Max] fix issue #3829

- addons/binding/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/command/UdpCubeCommand.java
- addons/binding/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/device/Device.java
- addons/binding/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/discovery/MaxCubeBridgeDiscovery.java
- addons/binding/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/handler/MaxCubeBridgeHandler.java
- addons/binding/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/handler/MaxDevicesHandler.java
- addons/binding/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/message/MMessage.java
> [max] Reduced logging levels

- addons/binding/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/AmazonEchoControlHandlerFactory.java
- addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/AVMFritzHandlerFactory.java
- addons/binding/org.openhab.binding.dsmr/src/main/java/org/openhab/binding/dsmr/internal/DSMRHandlerFactory.java
- addons/binding/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/FreeboxHandlerFactory.java
- addons/binding/org.openhab.binding.groheondus/src/main/java/org/openhab/binding/groheondus/internal/handler/GroheOndusHandlerFactory.java
- addons/binding/org.openhab.binding.harmonyhub/src/main/java/org/openhab/binding/harmonyhub/internal/HarmonyHubHandlerFactory.java
- addons/binding/org.openhab.binding.innogysmarthome/src/main/java/org/openhab/binding/innogysmarthome/internal/InnogyHandlerFactory.java
- addons/binding/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/JeeLinkHandlerFactory.java
- addons/binding/org.openhab.binding.lametrictime/src/main/java/org/openhab/binding/lametrictime/internal/LaMetricTimeHandlerFactory.java
- addons/binding/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/factory/MaxCubeHandlerFactory.java
- addons/binding/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/MieleHandlerFactory.java
- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/XiaomiHandlerFactory.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/NetatmoHandlerFactory.java
- addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/NikoHomeControlHandlerFactory.java
- addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/RFXComHandlerFactory.java
- addons/binding/org.openhab.binding.sleepiq/src/main/java/org/openhab/binding/sleepiq/internal/SleepIQHandlerFactory.java
- addons/binding/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/handler/TadoHandlerFactory.java
- addons/binding/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/VelbusHandlerFactory.java
- addons/binding/org.openhab.binding.zway/src/main/java/org/openhab/binding/zway/internal/ZWayHandlerFactory.java
> Fix discovery service unregistration/deactivate order

- addons/binding/org.openhab.binding.groheondus/README.md
> fixed link syntax

- addons/binding/org.openhab.binding.amazondashbutton/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.amazondashbutton/src/main/java/org/openhab/binding/amazondashbutton/internal/AmazonDashButtonBindingConstants.java
- addons/binding/org.openhab.binding.amazondashbutton/src/main/java/org/openhab/binding/amazondashbutton/internal/AmazonDashButtonHandlerFactory.java
- addons/binding/org.openhab.binding.amazondashbutton/src/main/java/org/openhab/binding/amazondashbutton/internal/config/AmazonDashButtonConfigOptionProvider.java
- addons/binding/org.openhab.binding.amazondashbutton/src/main/java/org/openhab/binding/amazondashbutton/internal/discovery/AmazonDashButtonDiscoveryService.java
- addons/binding/org.openhab.binding.amazondashbutton/src/main/java/org/openhab/binding/amazondashbutton/internal/handler/AmazonDashButtonHandler.java
Currently the public API is unusable, because in AmazonDashButtonHandler method onPcapNetworkInterfaceAdded and onPcapNetworkInterfaceRemoved take internal type PcapNetworkInterfaceWrapper as parameter.
See openhab/static-code-analysis#210
> Exported the pcap package in the AmazonDashButton binding.

- addons/binding/org.openhab.binding.gardena/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/GardenaBindingConstants.java
- addons/binding/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/discovery/GardenaDeviceDiscoveryService.java
- addons/binding/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/handler/AccountHandlerNotAvailableException.java
- addons/binding/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/handler/GardenaAccountHandler.java
- addons/binding/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/handler/GardenaDeviceConfig.java
- addons/binding/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/handler/GardenaHandlerFactory.java
- addons/binding/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/handler/GardenaThingHandler.java
- addons/binding/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/util/UidUtils.java
> Made constants and handler packages internal in the gerdana binding

- addons/binding/org.openhab.binding.feican/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.feican/src/main/java/org/openhab/binding/feican/internal/FeicanBindingConstants.java
- addons/binding/org.openhab.binding.feican/src/main/java/org/openhab/binding/feican/internal/FeicanDiscoveryService.java
- addons/binding/org.openhab.binding.feican/src/main/java/org/openhab/binding/feican/internal/FeicanHandlerFactory.java
- addons/binding/org.openhab.binding.feican/src/main/java/org/openhab/binding/feican/internal/handler/FeicanHandler.java
> Made constants and handler packages internal in the feican binding

- addons/binding/org.openhab.binding.dscalarm/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/DSCAlarmBindingConstants.java
- addons/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/discovery/DSCAlarmBridgeDiscovery.java
- addons/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/discovery/DSCAlarmDiscoveryService.java
- addons/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/factory/DSCAlarmHandlerFactory.java
- addons/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/handler/DSCAlarmBaseBridgeHandler.java
- addons/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/handler/DSCAlarmBaseThingHandler.java
- addons/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/handler/DSCAlarmBridgeType.java
- addons/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/handler/DSCAlarmProtocol.java
- addons/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/handler/DSCAlarmThingType.java
- addons/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/handler/EnvisalinkBridgeHandler.java
- addons/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/handler/IT100BridgeHandler.java
- addons/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/handler/KeypadThingHandler.java
- addons/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/handler/PanelThingHandler.java
- addons/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/handler/PartitionThingHandler.java
- addons/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/handler/TCPServerBridgeHandler.java
- addons/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/handler/ZoneThingHandler.java
> Made constants and handler packages internal in the dscalarm binding

- addons/binding/org.openhab.binding.feed.test/src/test/java/org/openhab/binding/feed/test/FeedHandlerTest.java
- addons/binding/org.openhab.binding.feed/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.feed/src/main/java/org/openhab/binding/feed/internal/FeedBindingConstants.java
- addons/binding/org.openhab.binding.feed/src/main/java/org/openhab/binding/feed/internal/FeedHandlerFactory.java
- addons/binding/org.openhab.binding.feed/src/main/java/org/openhab/binding/feed/internal/handler/FeedHandler.java
> Made constants and handler packages internal in the feed binding.

- addons/binding/org.openhab.binding.folding/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.folding/src/main/java/org/openhab/binding/folding/internal/FoldingBindingConstants.java
- addons/binding/org.openhab.binding.folding/src/main/java/org/openhab/binding/folding/internal/FoldingHandlerFactory.java
- addons/binding/org.openhab.binding.folding/src/main/java/org/openhab/binding/folding/internal/discovery/FoldingSlotDiscoveryService.java
- addons/binding/org.openhab.binding.folding/src/main/java/org/openhab/binding/folding/internal/handler/FoldingClientHandler.java
- addons/binding/org.openhab.binding.folding/src/main/java/org/openhab/binding/folding/internal/handler/SlotHandler.java
- addons/binding/org.openhab.binding.folding/src/main/java/org/openhab/binding/folding/internal/handler/SlotInfo.java
- addons/binding/org.openhab.binding.folding/src/main/java/org/openhab/binding/folding/internal/handler/SlotUpdateListener.java
> Made constants and handler packages internal in the folding binding.

- addons/binding/org.openhab.binding.dlinksmarthome/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.dlinksmarthome/src/main/java/org/openhab/binding/dlinksmarthome/internal/DLinkSmartHomeBindingConstants.java
- addons/binding/org.openhab.binding.dlinksmarthome/src/main/java/org/openhab/binding/dlinksmarthome/internal/DLinkSmartHomeDiscoveryParticipant.java
- addons/binding/org.openhab.binding.dlinksmarthome/src/main/java/org/openhab/binding/dlinksmarthome/internal/DLinkSmartHomeHandlerFactory.java
- addons/binding/org.openhab.binding.dlinksmarthome/src/main/java/org/openhab/binding/dlinksmarthome/internal/handler/DLinkMotionSensorHandler.java
> Made constants and handler packages internal in the dlink binding

- addons/binding/org.openhab.binding.cm11a/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/internal/CM11ABindingConstants.java
- addons/binding/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/internal/Cm11aHandlerFactory.java
- addons/binding/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/internal/X10Interface.java
- addons/binding/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/internal/handler/Cm11aAbstractHandler.java
- addons/binding/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/internal/handler/Cm11aApplianceHandler.java
- addons/binding/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/internal/handler/Cm11aBridgeHandler.java
- addons/binding/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/internal/handler/Cm11aLampHandler.java
- addons/binding/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/internal/handler/ReceivedDataListener.java
> Made constants and handler packages internal in the cm11a binding

- addons/binding/org.openhab.binding.boschindego/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/BoschIndegoBindingConstants.java
- addons/binding/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/BoschIndegoHandlerFactory.java
- addons/binding/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/handler/BoschIndegoHandler.java
> Made constants and handler packages internal in the boschindego binding

- addons/binding/org.openhab.binding.bigassfan/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.bigassfan/src/main/java/org/openhab/binding/bigassfan/internal/BigAssFanBindingConstants.java
- addons/binding/org.openhab.binding.bigassfan/src/main/java/org/openhab/binding/bigassfan/internal/BigAssFanHandlerFactory.java
- addons/binding/org.openhab.binding.bigassfan/src/main/java/org/openhab/binding/bigassfan/internal/discovery/BigAssFanDiscoveryService.java
- addons/binding/org.openhab.binding.bigassfan/src/main/java/org/openhab/binding/bigassfan/internal/discovery/DiscoveryListener.java
- addons/binding/org.openhab.binding.bigassfan/src/main/java/org/openhab/binding/bigassfan/internal/handler/BigAssFanHandler.java
> Made constants and handler packages internal in the bigassfan binding.

- addons/binding/org.openhab.binding.allplay/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.allplay/src/main/java/org/openhab/binding/allplay/internal/AllPlayAudioSink.java
- addons/binding/org.openhab.binding.allplay/src/main/java/org/openhab/binding/allplay/internal/AllPlayBindingConstants.java
- addons/binding/org.openhab.binding.allplay/src/main/java/org/openhab/binding/allplay/internal/AllPlayHandlerFactory.java
- addons/binding/org.openhab.binding.allplay/src/main/java/org/openhab/binding/allplay/internal/discovery/AllPlaySpeakerDiscoveryService.java
- addons/binding/org.openhab.binding.allplay/src/main/java/org/openhab/binding/allplay/internal/handler/AllPlayHandler.java
> Made constants and handler packages internal in the allplay binding

- addons/binding/org.openhab.binding.amazonechocontrol/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/AccountServlet.java
- addons/binding/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/AmazonEchoControlBindingConstants.java
- addons/binding/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/AmazonEchoControlHandlerFactory.java
- addons/binding/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/BindingServlet.java
- addons/binding/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/StateStorage.java
- addons/binding/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/discovery/AmazonEchoDiscovery.java
- addons/binding/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/handler/AccountHandler.java
- addons/binding/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/handler/EchoHandler.java
- addons/binding/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/handler/FlashBriefingProfileHandler.java
- addons/binding/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/statedescription/AmazonEchoDynamicStateDescriptionProvider.java
> Made all packages internal in the amazonchronocontrol binding.

- addons/binding/org.openhab.binding.fronius/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/FroniusBaseDeviceConfiguration.java
- addons/binding/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/FroniusBindingConstants.java
- addons/binding/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/FroniusBridgeConfiguration.java
- addons/binding/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/FroniusHandlerFactory.java
- addons/binding/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/handler/FroniusBaseThingHandler.java
- addons/binding/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/handler/FroniusBridgeHandler.java
- addons/binding/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/handler/FroniusSymoInverterHandler.java
> Made constants and handler packages internal in the fronius binding

- addons/binding/org.openhab.binding.ftpupload/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.ftpupload/src/main/java/org/openhab/binding/ftpupload/internal/FtpUploadBindingConstants.java
- addons/binding/org.openhab.binding.ftpupload/src/main/java/org/openhab/binding/ftpupload/internal/FtpUploadHandlerFactory.java
- addons/binding/org.openhab.binding.ftpupload/src/main/java/org/openhab/binding/ftpupload/internal/handler/FtpUploadHandler.java
> Made constants and handler packages internal in the ftpupload binding

- addons/binding/org.openhab.binding.hyperion/README.md
- Clarification of "clear" channel with example and better differentiation between "V1" and "NG".
- Remove clear_all channel (does not exist).
Signed-off-by: David Kalwar <david.kalwar@gmail.com> (github: chiefymuc)
> [Hyperion] Update Readme

- addons/binding/org.openhab.binding.hdpowerview/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/HDPowerViewBindingConstants.java
- addons/binding/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/HDPowerViewHandlerFactory.java
- addons/binding/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/discovery/HDPowerViewHubDiscoveryService.java
- addons/binding/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/discovery/HDPowerViewShadeDiscoveryService.java
- addons/binding/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/AbstractHubbedThingHandler.java
- addons/binding/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewHubHandler.java
- addons/binding/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewShadeHandler.java
> Made constant and handler packages internal in the hdpowerview binding.

- addons/binding/org.openhab.binding.jeelink/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/JeeLinkBindingConstants.java
- addons/binding/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/JeeLinkHandlerFactory.java
- addons/binding/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/discovery/SensorDiscoveryService.java
- addons/binding/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/ec3k/Ec3kSensorDefinition.java
- addons/binding/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/ec3k/Ec3kSensorHandler.java
- addons/binding/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/lacrosse/LaCrosseSensorDefinition.java
- addons/binding/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/lacrosse/LaCrosseTemperatureSensorHandler.java
- addons/binding/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/lacrosse/Tx22SensorDefinition.java
- addons/binding/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/lacrosse/Tx22SensorHandler.java
- addons/binding/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/pca301/Pca301SensorDefinition.java
- addons/binding/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/pca301/Pca301SensorHandler.java
> Made constants package internal in the jeelink binding

- addons/binding/org.openhab.binding.harmonyhub/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.harmonyhub/src/main/java/org/openhab/binding/harmonyhub/internal/HarmonyHubBindingConstants.java
- addons/binding/org.openhab.binding.harmonyhub/src/main/java/org/openhab/binding/harmonyhub/internal/HarmonyHubHandlerFactory.java
- addons/binding/org.openhab.binding.harmonyhub/src/main/java/org/openhab/binding/harmonyhub/internal/discovery/HarmonyDeviceDiscoveryService.java
- addons/binding/org.openhab.binding.harmonyhub/src/main/java/org/openhab/binding/harmonyhub/internal/discovery/HarmonyHubDiscoveryService.java
- addons/binding/org.openhab.binding.harmonyhub/src/main/java/org/openhab/binding/harmonyhub/internal/handler/HarmonyDeviceHandler.java
- addons/binding/org.openhab.binding.harmonyhub/src/main/java/org/openhab/binding/harmonyhub/internal/handler/HarmonyHubHandler.java
- addons/binding/org.openhab.binding.harmonyhub/src/main/java/org/openhab/binding/harmonyhub/internal/handler/HubStatusListener.java
> Made constants and handler packages internal in the harmonyhub binding

- addons/binding/org.openhab.binding.hdanywhere/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.hdanywhere/src/main/java/org/openhab/binding/hdanywhere/internal/HDanywhereBindingConstants.java
- addons/binding/org.openhab.binding.hdanywhere/src/main/java/org/openhab/binding/hdanywhere/internal/HDanywhereHandlerFactory.java
- addons/binding/org.openhab.binding.hdanywhere/src/main/java/org/openhab/binding/hdanywhere/internal/handler/Mhub4K431Handler.java
- addons/binding/org.openhab.binding.hdanywhere/src/main/java/org/openhab/binding/hdanywhere/internal/handler/MultiroomPlusHandler.java
> Made constants and handler packages internal in the hdanywhere binding

- addons/binding/org.openhab.binding.kodi/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/KodiAudioSink.java
- addons/binding/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/KodiBindingConstants.java
- addons/binding/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/KodiHandlerFactory.java
- addons/binding/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/discovery/KodiUpnpDiscoveryParticipant.java
- addons/binding/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/handler/KodiHandler.java
> Made constants and handler packages internal in the kodi binding

- addons/binding/org.openhab.binding.milight/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/MilightBindingConstants.java
- addons/binding/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/MilightHandlerFactory.java
- addons/binding/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/discovery/MilightBridgeDiscovery.java
- addons/binding/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/discovery/ThingDiscoveryService.java
- addons/binding/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/handler/AbstractMilightBridgeHandler.java
- addons/binding/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/handler/MilightBridgeV3Handler.java
- addons/binding/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/handler/MilightBridgeV6Handler.java
- addons/binding/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/handler/MilightLedHandler.java
- addons/binding/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/protocol/MilightDiscover.java
- addons/binding/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/test/EmulatedV6Bridge.java
- addons/binding/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/test/TestDiscovery.java
> [milight] Made constants and handler packages internal

- addons/binding/org.openhab.binding.kostalinverter/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/internal/kostal/inverter/ChannelConfig.java
- addons/binding/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/internal/kostal/inverter/SourceConfig.java
- addons/binding/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/internal/kostal/inverter/WebscrapeHandler.java
- addons/binding/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/internal/kostal/inverter/WebscrapeHandlerFactory.java
> Made kostal.inverter package internal

- addons/binding/org.openhab.binding.neato/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.neato/src/main/java/org/openhab/binding/neato/internal/NeatoBindingConstants.java
- addons/binding/org.openhab.binding.neato/src/main/java/org/openhab/binding/neato/internal/NeatoHandlerFactory.java
- addons/binding/org.openhab.binding.neato/src/main/java/org/openhab/binding/neato/internal/discovery/NeatoAccountDiscoveryService.java
- addons/binding/org.openhab.binding.neato/src/main/java/org/openhab/binding/neato/internal/handler/NeatoAccountHandler.java
- addons/binding/org.openhab.binding.neato/src/main/java/org/openhab/binding/neato/internal/handler/NeatoHandler.java
> [naeto] Made constants and handler packages internal

- addons/binding/org.openhab.binding.logreader/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.logreader/src/main/java/org/openhab/binding/logreader/internal/LogReaderBindingConstants.java
- addons/binding/org.openhab.binding.logreader/src/main/java/org/openhab/binding/logreader/internal/LogReaderHandlerFactory.java
- addons/binding/org.openhab.binding.logreader/src/main/java/org/openhab/binding/logreader/internal/handler/LogHandler.java
> Made constants and handler packages internal in the logreader binding

- addons/binding/org.openhab.binding.leapmotion/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.leapmotion/src/main/java/org/openhab/binding/leapmotion/internal/LeapMotionBindingConstants.java
- addons/binding/org.openhab.binding.leapmotion/src/main/java/org/openhab/binding/leapmotion/internal/LeapMotionColorProfile.java
- addons/binding/org.openhab.binding.leapmotion/src/main/java/org/openhab/binding/leapmotion/internal/LeapMotionDimmerProfile.java
- addons/binding/org.openhab.binding.leapmotion/src/main/java/org/openhab/binding/leapmotion/internal/LeapMotionHandlerFactory.java
- addons/binding/org.openhab.binding.leapmotion/src/main/java/org/openhab/binding/leapmotion/internal/LeapMotionProfileFactory.java
- addons/binding/org.openhab.binding.leapmotion/src/main/java/org/openhab/binding/leapmotion/internal/LeapMotionSwitchProfile.java
- addons/binding/org.openhab.binding.leapmotion/src/main/java/org/openhab/binding/leapmotion/internal/discovery/LeapMotionDiscoveryService.java
- addons/binding/org.openhab.binding.leapmotion/src/main/java/org/openhab/binding/leapmotion/internal/handler/LeapMotionHandler.java
> Made constants and handler packages internal in the leapmotion binding

- addons/binding/org.openhab.binding.irtrans/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.irtrans/src/main/java/org/openhab/binding/irtrans/internal/IRtransBindingConstants.java
- addons/binding/org.openhab.binding.irtrans/src/main/java/org/openhab/binding/irtrans/internal/IRtransHandlerFactory.java
- addons/binding/org.openhab.binding.irtrans/src/main/java/org/openhab/binding/irtrans/internal/IrCommand.java
- addons/binding/org.openhab.binding.irtrans/src/main/java/org/openhab/binding/irtrans/internal/handler/BlasterHandler.java
- addons/binding/org.openhab.binding.irtrans/src/main/java/org/openhab/binding/irtrans/internal/handler/EthernetBridgeHandler.java
- addons/binding/org.openhab.binding.irtrans/src/main/java/org/openhab/binding/irtrans/internal/handler/TransceiverStatusListener.java
> Made constants and handler packages internal in the irtrans binding

- addons/binding/org.openhab.binding.ipp/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.ipp/src/main/java/org/openhab/binding/ipp/internal/IppBindingConstants.java
- addons/binding/org.openhab.binding.ipp/src/main/java/org/openhab/binding/ipp/internal/IppHandlerFactory.java
- addons/binding/org.openhab.binding.ipp/src/main/java/org/openhab/binding/ipp/internal/discovery/IppPrinterDiscoveryParticipant.java
- addons/binding/org.openhab.binding.ipp/src/main/java/org/openhab/binding/ipp/internal/handler/IppPrinterHandler.java
> Made constants and handler packages internal in the ipp binding

- addons/binding/org.openhab.binding.plugwise/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/PlugwiseBindingConstants.java
- addons/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/PlugwiseHandlerFactory.java
- addons/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/PlugwiseStickDiscoveryService.java
- addons/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/PlugwiseThingDiscoveryService.java
- addons/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/PlugwiseUtils.java
- addons/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/handler/AbstractPlugwiseThingHandler.java
- addons/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/handler/AbstractSleepingEndDeviceHandler.java
- addons/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/handler/PlugwiseRelayDeviceHandler.java
- addons/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/handler/PlugwiseScanHandler.java
- addons/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/handler/PlugwiseSenseHandler.java
- addons/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/handler/PlugwiseStickHandler.java
- addons/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/handler/PlugwiseSwitchHandler.java
- addons/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/listener/PlugwiseStickStatusListener.java
> [plugwise] Made constants and handler packages internal

- addons/binding/org.openhab.binding.russound/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/RussoundBindingConstants.java
- addons/binding/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/rio/RioConstants.java
> [russound] Made constants package internal

- addons/binding/org.openhab.binding.regoheatpump/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/RegoHeatPumpBindingConstants.java
- addons/binding/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/RegoHeatPumpHandlerFactory.java
- addons/binding/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/handler/HusdataHandler.java
- addons/binding/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/handler/IpHusdataHandler.java
- addons/binding/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/handler/IpRego6xxHeatPumpHandler.java
- addons/binding/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/handler/Rego6xxHeatPumpHandler.java
- addons/binding/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/handler/SerialHusdataHandler.java
- addons/binding/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/handler/SerialRego6xxHeatPumpHandler.java
- addons/binding/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/rego6xx/RegoRegisterMapper.java
> [regoheatpump] Made constants and handler packages internal

- addons/binding/org.openhab.binding.phc/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.phc/src/main/java/org/openhab/binding/phc/internal/PHCBindingConstants.java
- addons/binding/org.openhab.binding.phc/src/main/java/org/openhab/binding/phc/internal/PHCHandlerFactory.java
- addons/binding/org.openhab.binding.phc/src/main/java/org/openhab/binding/phc/internal/handler/PHCBridgeHandler.java
- addons/binding/org.openhab.binding.phc/src/main/java/org/openhab/binding/phc/internal/handler/PHCHandler.java
- addons/binding/org.openhab.binding.phc/src/main/java/org/openhab/binding/phc/internal/handler/QueueObject.java
> [phc] Made constants and handler packages internal

- addons/binding/org.openhab.binding.netatmo/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/NetatmoBindingConstants.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/NetatmoHandlerFactory.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/channelhelper/BatteryHelper.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/channelhelper/RadioHelper.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/discovery/NetatmoModuleDiscoveryService.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/AbstractNetatmoThingHandler.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/MeasurableChannels.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/NetatmoBridgeHandler.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/NetatmoDataListener.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/NetatmoDeviceHandler.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/NetatmoModuleHandler.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/TrustingOkHttpClient.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/homecoach/NAHealthyHomeCoachHandler.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/station/NAMainHandler.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/station/NAModule1Handler.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/station/NAModule2Handler.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/station/NAModule3Handler.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/station/NAModule4Handler.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/thermostat/NAPlugHandler.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/thermostat/NATherm1Handler.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/webhook/WelcomeWebHookServlet.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/welcome/NAWelcomeCameraHandler.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/welcome/NAWelcomeHomeHandler.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/welcome/NAWelcomePersonHandler.java
> [netatmo] Made constants and handler packages internal

- addons/binding/org.openhab.binding.satel/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/SatelBindingConstants.java
- addons/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/SatelHandlerFactory.java
- addons/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/discovery/SatelDeviceDiscoveryService.java
- addons/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/handler/Ethm1BridgeHandler.java
- addons/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/handler/IntRSBridgeHandler.java
- addons/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/handler/SatelBridgeHandler.java
- addons/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/handler/SatelOutputHandler.java
- addons/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/handler/SatelPartitionHandler.java
- addons/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/handler/SatelShutterHandler.java
- addons/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/handler/SatelSystemHandler.java
- addons/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/handler/SatelThingHandler.java
- addons/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/handler/SatelZoneHandler.java
> [satel] Made constants and handler packages internal

- addons/binding/org.openhab.binding.sensebox/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/internal/SenseBoxAPIConnection.java
- addons/binding/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/internal/SenseBoxBindingConstants.java
- addons/binding/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/internal/SenseBoxHandlerFactory.java
- addons/binding/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/internal/handler/SenseBoxHandler.java
> [sensebox] Made constants and handler packages internal

- addons/binding/org.openhab.binding.solarlog/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.solarlog/src/main/java/org/openhab/binding/solarlog/internal/SolarLogBindingConstants.java
- addons/binding/org.openhab.binding.solarlog/src/main/java/org/openhab/binding/solarlog/internal/SolarLogHandlerFactory.java
- addons/binding/org.openhab.binding.solarlog/src/main/java/org/openhab/binding/solarlog/internal/handler/SolarLogHandler.java
> [solarlog] Made constants and handler packages internal

- addons/binding/org.openhab.binding.squeezebox/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/SqueezeBoxAudioSink.java
- addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/SqueezeBoxBindingConstants.java
- addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/SqueezeBoxHandlerFactory.java
- addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/discovery/SqueezeBoxPlayerDiscoveryParticipant.java
- addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/discovery/SqueezeBoxServerDiscoveryParticipant.java
- addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxNotificationListener.java
- addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxNotificationPlayer.java
- addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxPlayer.java
- addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxPlayerEventListener.java
- addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxPlayerHandler.java
- addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxPlayerPlayState.java
- addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxPlayerState.java
- addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxServerHandler.java
> [squeezebox] Made constants and handler packages internal

- addons/binding/org.openhab.binding.synopanalyzer/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.synopanalyzer/src/main/java/org/openhab/binding/synopanalyzer/internal/SynopAnalyzerBindingConstants.java
- addons/binding/org.openhab.binding.synopanalyzer/src/main/java/org/openhab/binding/synopanalyzer/internal/SynopAnalyzerHandlerFactory.java
- addons/binding/org.openhab.binding.synopanalyzer/src/main/java/org/openhab/binding/synopanalyzer/internal/config/SynopAnalyzerConfiguration.java
- addons/binding/org.openhab.binding.synopanalyzer/src/main/java/org/openhab/binding/synopanalyzer/internal/handler/SynopAnalyzerHandler.java
> [synopanalyzer] Made constants and handler packages internal

- addons/binding/org.openhab.binding.tankerkoenig/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.tankerkoenig/src/main/java/org/openhab/binding/tankerkoenig/internal/TankerkoenigBindingConstants.java
- addons/binding/org.openhab.binding.tankerkoenig/src/main/java/org/openhab/binding/tankerkoenig/internal/TankerkoenigHandlerFactory.java
- addons/binding/org.openhab.binding.tankerkoenig/src/main/java/org/openhab/binding/tankerkoenig/internal/config/TankerkoenigDetailResult.java
- addons/binding/org.openhab.binding.tankerkoenig/src/main/java/org/openhab/binding/tankerkoenig/internal/config/TankerkoenigListResult.java
- addons/binding/org.openhab.binding.tankerkoenig/src/main/java/org/openhab/binding/tankerkoenig/internal/handler/StationHandler.java
- addons/binding/org.openhab.binding.tankerkoenig/src/main/java/org/openhab/binding/tankerkoenig/internal/handler/WebserviceHandler.java
> [tankerkoenig] Made constants and handler packages internal

- addons/binding/org.openhab.binding.toon/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.toon/src/main/java/org/openhab/binding/toon/internal/ToonBindingConstants.java
- addons/binding/org.openhab.binding.toon/src/main/java/org/openhab/binding/toon/internal/ToonHandlerFactory.java
- addons/binding/org.openhab.binding.toon/src/main/java/org/openhab/binding/toon/internal/discovery/ToonDiscoveryService.java
- addons/binding/org.openhab.binding.toon/src/main/java/org/openhab/binding/toon/internal/handler/AbstractToonHandler.java
- addons/binding/org.openhab.binding.toon/src/main/java/org/openhab/binding/toon/internal/handler/ToonBridgeHandler.java
- addons/binding/org.openhab.binding.toon/src/main/java/org/openhab/binding/toon/internal/handler/ToonDisplayHandler.java
- addons/binding/org.openhab.binding.toon/src/main/java/org/openhab/binding/toon/internal/handler/ToonPlugHandler.java
> [toon] Made constants and handler packages internal

- addons/binding/org.openhab.binding.urtsi/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.urtsi/src/main/java/org/openhab/binding/urtsi/internal/UrtsiBindingConstants.java
- addons/binding/org.openhab.binding.urtsi/src/main/java/org/openhab/binding/urtsi/internal/UrtsiHandlerFactory.java
- addons/binding/org.openhab.binding.urtsi/src/main/java/org/openhab/binding/urtsi/internal/handler/RtsCommand.java
- addons/binding/org.openhab.binding.urtsi/src/main/java/org/openhab/binding/urtsi/internal/handler/RtsDeviceHandler.java
- addons/binding/org.openhab.binding.urtsi/src/main/java/org/openhab/binding/urtsi/internal/handler/UrtsiDeviceHandler.java
> [urtsi] Made constants and handler packages internal

- addons/binding/org.openhab.binding.samsungtv/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/SamsungTvBindingConstants.java
- addons/binding/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/SamsungTvHandlerFactory.java
- addons/binding/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/config/SamsungTvConfiguration.java
- addons/binding/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/discovery/SamsungTvDiscoveryParticipant.java
- addons/binding/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/handler/SamsungTvHandler.java
- addons/binding/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/service/MainTVServerService.java
- addons/binding/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/service/MediaRendererService.java
- addons/binding/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/service/RemoteControllerService.java
> [samsungtv] Made constants and handler packages internal

- addons/binding/org.openhab.binding.nest.test/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.nest.test/src/test/java/org/openhab/binding/nest/handler/NestBridgeHandlerTest.java
- addons/binding/org.openhab.binding.nest.test/src/test/java/org/openhab/binding/nest/handler/NestCameraHandlerTest.java
- addons/binding/org.openhab.binding.nest.test/src/test/java/org/openhab/binding/nest/handler/NestSmokeDetectorHandlerTest.java
- addons/binding/org.openhab.binding.nest.test/src/test/java/org/openhab/binding/nest/handler/NestStructureHandlerTest.java
- addons/binding/org.openhab.binding.nest.test/src/test/java/org/openhab/binding/nest/handler/NestThermostatHandlerTest.java
- addons/binding/org.openhab.binding.nest.test/src/test/java/org/openhab/binding/nest/handler/NestThingHandlerOSGiTest.java
- addons/binding/org.openhab.binding.nest.test/src/test/java/org/openhab/binding/nest/test/NestTestApiServlet.java
- addons/binding/org.openhab.binding.nest.test/src/test/java/org/openhab/binding/nest/test/NestTestBridgeHandler.java
- addons/binding/org.openhab.binding.nest.test/src/test/java/org/openhab/binding/nest/test/NestTestHandlerFactory.java
- addons/binding/org.openhab.binding.nest/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/NestBindingConstants.java
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/NestHandlerFactory.java
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/discovery/NestDiscoveryService.java
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/handler/NestBaseHandler.java
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/handler/NestBridgeHandler.java
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/handler/NestCameraHandler.java
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/handler/NestRedirectUrlSupplier.java
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/handler/NestSmokeDetectorHandler.java
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/handler/NestStructureHandler.java
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/handler/NestThermostatHandler.java
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/rest/NestAuthorizer.java
- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/rest/NestStreamingRestClient.java
> [nest] Made constants and handler packages internal

- addons/binding/org.openhab.binding.velbus/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/VelbusBindingConstants.java
- addons/binding/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/VelbusHandlerFactory.java
- addons/binding/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/VelbusModule.java
- addons/binding/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/discovery/VelbusThingDiscoveryService.java
- addons/binding/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusBlindsHandler.java
- addons/binding/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusBridgeHandler.java
- addons/binding/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusDimmerHandler.java
- addons/binding/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusRelayHandler.java
- addons/binding/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusSensorHandler.java
- addons/binding/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusTemperatureSensorHandler.java
- addons/binding/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusThingHandler.java
- addons/binding/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusVMBGPHandler.java
- addons/binding/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusVMBGPOHandler.java
- addons/binding/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusVMBPIROHandler.java
- addons/binding/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/packets/VelbusBlindOffPacket.java
- addons/binding/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/packets/VelbusBlindPositionPacket.java
- addons/binding/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/packets/VelbusChannelNameRequestPacket.java
- addons/binding/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/packets/VelbusSensorTemperatureRequestPacket.java
- addons/binding/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/packets/VelbusStatusRequestPacket.java
> [velbus] Made constants and handler packages internal

- addons/binding/org.openhab.binding.windcentrale/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.windcentrale/src/main/java/org/openhab/binding/windcentrale/internal/WindcentraleBindingConstants.java
- addons/binding/org.openhab.binding.windcentrale/src/main/java/org/openhab/binding/windcentrale/internal/WindcentraleHandlerFactory.java
- addons/binding/org.openhab.binding.windcentrale/src/main/java/org/openhab/binding/windcentrale/internal/handler/WindcentraleHandler.java
> [windcentrale] Made constants and handler packages internal

- addons/binding/org.openhab.binding.zway/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.zway/src/main/java/org/openhab/binding/zway/internal/ZWayBindingConstants.java
- addons/binding/org.openhab.binding.zway/src/main/java/org/openhab/binding/zway/internal/ZWayHandlerFactory.java
- addons/binding/org.openhab.binding.zway/src/main/java/org/openhab/binding/zway/internal/config/ZWayBridgeConfiguration.java
- addons/binding/org.openhab.binding.zway/src/main/java/org/openhab/binding/zway/internal/config/ZWayZAutomationDeviceConfiguration.java
- addons/binding/org.openhab.binding.zway/src/main/java/org/openhab/binding/zway/internal/config/ZWayZWaveDeviceConfiguration.java
- addons/binding/org.openhab.binding.zway/src/main/java/org/openhab/binding/zway/internal/discovery/ZWayBridgeDiscoveryService.java
- addons/binding/org.openhab.binding.zway/src/main/java/org/openhab/binding/zway/internal/discovery/ZWayDeviceDiscoveryService.java
- addons/binding/org.openhab.binding.zway/src/main/java/org/openhab/binding/zway/internal/handler/ZWayBridgeHandler.java
- addons/binding/org.openhab.binding.zway/src/main/java/org/openhab/binding/zway/internal/handler/ZWayDeviceHandler.java
- addons/binding/org.openhab.binding.zway/src/main/java/org/openhab/binding/zway/internal/handler/ZWayZAutomationDeviceHandler.java
- addons/binding/org.openhab.binding.zway/src/main/java/org/openhab/binding/zway/internal/handler/ZWayZWaveDeviceHandler.java
> [zway] Made constants and handler packages internal

- addons/binding/org.openhab.binding.wifiled.test/src/test/java/org/openhab/binding/wifiled/internal/handler/LEDStateDTOTest.java
- addons/binding/org.openhab.binding.wifiled/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.wifiled/src/main/java/org/openhab/binding/wifiled/internal/WiFiLEDBindingConstants.java
- addons/binding/org.openhab.binding.wifiled/src/main/java/org/openhab/binding/wifiled/internal/WiFiLEDHandlerFactory.java
- addons/binding/org.openhab.binding.wifiled/src/main/java/org/openhab/binding/wifiled/internal/discovery/WiFiLEDDiscoveryService.java
- addons/binding/org.openhab.binding.wifiled/src/main/java/org/openhab/binding/wifiled/internal/handler/AbstractWiFiLEDDriver.java
- addons/binding/org.openhab.binding.wifiled/src/main/java/org/openhab/binding/wifiled/internal/handler/ClassicWiFiLEDDriver.java
- addons/binding/org.openhab.binding.wifiled/src/main/java/org/openhab/binding/wifiled/internal/handler/FadingWiFiLEDDriver.java
- addons/binding/org.openhab.binding.wifiled/src/main/java/org/openhab/binding/wifiled/internal/handler/InternalLedState.java
- addons/binding/org.openhab.binding.wifiled/src/main/java/org/openhab/binding/wifiled/internal/handler/LEDState.java
- addons/binding/org.openhab.binding.wifiled/src/main/java/org/openhab/binding/wifiled/internal/handler/LEDStateDTO.java
- addons/binding/org.openhab.binding.wifiled/src/main/java/org/openhab/binding/wifiled/internal/handler/WiFiLEDHandler.java
> [wifiled] Made constants and handler packages internal

- addons/binding/org.openhab.binding.systeminfo.test/src/test/java/org/openhab/binding/systeminfo/test/SysteminfoOSGiTest.java
- addons/binding/org.openhab.binding.systeminfo/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/SysteminfoBindingConstants.java
- addons/binding/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/SysteminfoHandlerFactory.java
- addons/binding/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/discovery/SysteminfoDiscoveryService.java
- addons/binding/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/handler/SysteminfoHandler.java
> [systeminfo] Made constants and handler packages internal

- addons/binding/org.openhab.binding.network.test/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.network.test/src/test/java/org/openhab/binding/network/internal/discovery/DiscoveryTest.java
- addons/binding/org.openhab.binding.network.test/src/test/java/org/openhab/binding/network/internal/handler/NetworkHandlerTest.java
- addons/binding/org.openhab.binding.network/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/NetworkBindingConstants.java
- addons/binding/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/NetworkHandlerFactory.java
- addons/binding/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/discovery/NetworkDiscoveryService.java
- addons/binding/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/handler/NetworkHandler.java
> [network] Made constants and handler packages internal

- addons/binding/org.openhab.binding.nibeheatpump.test/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.nibeheatpump/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.nibeheatpump/src/main/java/org/openhab/binding/nibeheatpump/internal/NibeHeatPumpBindingConstants.java
- addons/binding/org.openhab.binding.nibeheatpump/src/main/java/org/openhab/binding/nibeheatpump/internal/NibeHeatPumpHandlerFactory.java
- addons/binding/org.openhab.binding.nibeheatpump/src/main/java/org/openhab/binding/nibeheatpump/internal/connection/ConnectorFactory.java
- addons/binding/org.openhab.binding.nibeheatpump/src/main/java/org/openhab/binding/nibeheatpump/internal/handler/NibeHeatPumpHandler.java
> [nibeheatpump] Made constants and handler packages internal

- addons/binding/org.openhab.binding.robonect.test/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.robonect.test/src/test/java/org/openhab/binding/robonect/internal/handler/RobonectHandlerTest.java
- addons/binding/org.openhab.binding.robonect/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.robonect/src/main/java/org/openhab/binding/robonect/internal/RobonectBindingConstants.java
- addons/binding/org.openhab.binding.robonect/src/main/java/org/openhab/binding/robonect/internal/RobonectHandlerFactory.java
- addons/binding/org.openhab.binding.robonect/src/main/java/org/openhab/binding/robonect/internal/handler/RobonectHandler.java
> [roboconnect] Made constants and handler packages internal

- addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/AVMFritzHandlerFactory.java
- addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/discovery/AVMFritzDiscoveryService.java
- addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/AVMFritzBaseBridgeHandler.java
- addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/AVMFritzBaseThingHandler.java
- addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/Powerline546EHandler.java
- addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/hardware/callbacks/FritzAhaDiscoveryCallback.java
- addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/hardware/callbacks/FritzAhaUpdateXmlCallback.java
- Reduced logging level and removed superfluous logging
- Added handling for REFRESH commands
Fixes #4014
> [avmfritz] Added handling for REFRESH commands

- addons/binding/org.openhab.binding.modbus.test/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.modbus.test/src/test/java/org/openhab/binding/modbus/internal/AtomicStampedKeyValueTest.java
- addons/binding/org.openhab.binding.modbus.test/src/test/java/org/openhab/binding/modbus/internal/ModbusDataHandlerTest.java
- addons/binding/org.openhab.binding.modbus.test/src/test/java/org/openhab/binding/modbus/internal/ModbusPollerThingHandlerTest.java
- addons/binding/org.openhab.binding.modbus.test/src/test/java/org/openhab/binding/modbus/internal/ModbusTcpThingHandlerTest.java
- addons/binding/org.openhab.binding.modbus/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusBindingConstants.java
- addons/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusHandlerFactory.java
- addons/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/handler/AbstractModbusEndpointThingHandler.java
- addons/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/handler/EndpointNotInitializedException.java
- addons/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/handler/ModbusDataThingHandler.java
- addons/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/handler/ModbusEndpointThingHandler.java
- addons/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/handler/ModbusPollerThingHandler.java
- addons/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/handler/ModbusPollerThingHandlerImpl.java
- addons/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/handler/ModbusSerialThingHandler.java
- addons/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/handler/ModbusTcpThingHandler.java
> [modbus] Made constants and handler packages internal

- addons/binding/org.openhab.binding.keba/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.keba/src/main/java/org/openhab/binding/keba/internal/KebaBindingConstants.java
- addons/binding/org.openhab.binding.keba/src/main/java/org/openhab/binding/keba/internal/KebaHandlerFactory.java
- addons/binding/org.openhab.binding.keba/src/main/java/org/openhab/binding/keba/internal/handler/KeContactHandler.java
- addons/binding/org.openhab.binding.keba/src/main/java/org/openhab/binding/keba/internal/handler/KeContactTransceiver.java
> [keba] Made constants and handler packages internal

- addons/binding/org.openhab.binding.denonmarantz/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/DenonMarantzBindingConstants.java
- addons/binding/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/DenonMarantzHandlerFactory.java
- addons/binding/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/DenonMarantzState.java
- addons/binding/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/DenonMarantzStateChangedListener.java
- addons/binding/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/connector/DenonMarantzConnector.java
- addons/binding/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/discovery/DenonMarantzDiscoveryParticipant.java
- addons/binding/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/handler/DenonMarantzHandler.java
- addons/binding/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/xml/adapters/VolumeAdapter.java
> [denonmarantz] Made constants and handler packages internal

- addons/binding/org.openhab.binding.helios/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.helios/src/main/java/org/openhab/binding/helios/internal/HeliosBindingConstants.java
- addons/binding/org.openhab.binding.helios/src/main/java/org/openhab/binding/helios/internal/HeliosHandlerFactory.java
- addons/binding/org.openhab.binding.helios/src/main/java/org/openhab/binding/helios/internal/handler/HeliosHandler221.java
- addons/binding/org.openhab.binding.helios/src/main/java/org/openhab/binding/helios/internal/handler/HeliosHandler27.java
- addons/binding/org.openhab.binding.helios/src/main/java/org/openhab/binding/helios/internal/ws/soap/SOAPCallStateChanged.java
- addons/binding/org.openhab.binding.helios/src/main/java/org/openhab/binding/helios/internal/ws/soap/SOAPCardEntered.java
- addons/binding/org.openhab.binding.helios/src/main/java/org/openhab/binding/helios/internal/ws/soap/SOAPCodeEntered.java
- addons/binding/org.openhab.binding.helios/src/main/java/org/openhab/binding/helios/internal/ws/soap/SOAPDeviceState.java
- addons/binding/org.openhab.binding.helios/src/main/java/org/openhab/binding/helios/internal/ws/soap/SOAPEvent.java
- addons/binding/org.openhab.binding.helios/src/main/java/org/openhab/binding/helios/internal/ws/soap/SOAPKeyPressed.java
- addons/binding/org.openhab.binding.helios/src/main/java/org/openhab/binding/helios/internal/ws/soap/SOAPObjectFactory.java
- addons/binding/org.openhab.binding.helios/src/main/java/org/openhab/binding/helios/internal/ws/soap/SOAPSubscriptionActionHandler.java
> [helios] Made constants and handler packages internal

- addons/binding/org.openhab.binding.max.test/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.max.test/src/test/java/org/openhab/binding/max/test/MaxCubeBridgeHandlerOSGiTest.java
- addons/binding/org.openhab.binding.max/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/MaxBindingConstants.java
- addons/binding/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/config/MaxCubeBridgeConfiguration.java
- addons/binding/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/discovery/MaxCubeBridgeDiscovery.java
- addons/binding/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/discovery/MaxDeviceDiscoveryService.java
- addons/binding/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/factory/MaxCubeHandlerFactory.java
- addons/binding/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/handler/MaxCubeBridgeHandler.java
- addons/binding/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/handler/MaxDevicesHandler.java
- addons/binding/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/message/CMessage.java
> [max] Made constants and handler packages internal

- addons/binding/org.openhab.binding.atlona/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/AtlonaHandlerFactory.java
- addons/binding/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/discovery/AtlonaDiscovery.java
> [atlona] Removed Guava dependency

- addons/binding/org.openhab.binding.bigassfan/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.bigassfan/src/main/java/org/openhab/binding/bigassfan/internal/BigAssFanBindingConstants.java
> [bigassfan] Removed Guava dependency

- addons/binding/org.openhab.binding.dscalarm/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/DSCAlarmBindingConstants.java
> [dscalarm] Removed Guava dependency

- addons/binding/org.openhab.binding.milight/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/MilightBindingConstants.java
- addons/binding/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/MilightHandlerFactory.java
> [milight] Removed Guava dependency

- addons/binding/org.openhab.binding.globalcache/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.globalcache/src/main/java/org/openhab/binding/globalcache/GlobalCacheBindingConstants.java
> [globalcache] Removed Guava dependency

- addons/binding/org.openhab.binding.ipp/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.ipp/src/main/java/org/openhab/binding/ipp/internal/IppBindingConstants.java
> [ipp] Removed Guava dependency

- addons/binding/org.openhab.binding.nibeuplink/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/NibeUplinkBindingConstants.java
> [nibeuplink] Removed Guava dependency

- addons/binding/org.openhab.binding.nikohomecontrol/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/NikoHomeControlBindingConstants.java
> [nikohomecontrol] Removed Guava dependency

- addons/binding/org.openhab.binding.oceanic/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.oceanic/src/main/java/org/openhab/binding/oceanic/internal/OceanicHandlerFactory.java
> [oceanic] Removed Guava dependency

- addons/binding/org.openhab.binding.jeelink/README.md
Signed-off-by: Oliver Libutzki <oliver@libutzki.de> (github: OLibutzki)
> [jeelink] Example fix: batteryNew instead of batteryLow

- addons/binding/org.openhab.binding.samsungtv/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/SamsungTvHandlerFactory.java
> [samsungtv] Removed Guava dependency

- addons/binding/org.openhab.binding.russound/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/RussoundHandlerFactory.java
- addons/binding/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/discovery/RioSystemDiscovery.java
> [russound] Removed Guava dependency

- addons/binding/org.openhab.binding.pulseaudio/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/PulseaudioHandlerFactory.java
- addons/binding/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/handler/PulseaudioHandler.java
> [pulseaudio] Removed Guava dependency

- addons/binding/org.openhab.binding.phc/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.phc/src/main/java/org/openhab/binding/phc/internal/PHCHandlerFactory.java
> [phc] Removed Guava dependency

- addons/binding/org.openhab.binding.pentair/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.pentair/src/main/java/org/openhab/binding/pentair/internal/PentairBindingConstants.java
> [pentair] Removed Guava dependency

- addons/binding/org.openhab.binding.powermax/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/PowermaxBindingConstants.java
> [powermax] Removed Guava dependency

- addons/io/org.openhab.io.openhabcloud/README.md
Solves openhab/openhab-docs#239
I just recognized this small change while looking through the open docs issues and simply solved it directly.
Signed-off-by: Jerome Luckenbach <github@luckenba.ch>
> Clarified item exposal

- addons/binding/org.openhab.binding.mihome/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/ModelMapper.java
- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/XiaomiGatewayBindingConstants.java
- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/XiaomiHandlerFactory.java
- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/discovery/XiaomiBridgeDiscoveryService.java
- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/discovery/XiaomiItemDiscoveryService.java
- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/handler/XiaomiActorBaseHandler.java
- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/handler/XiaomiActorCurtainHandler.java
- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/handler/XiaomiActorGatewayHandler.java
- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/handler/XiaomiActorPlugHandler.java
- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/handler/XiaomiAqaraActorSwitch1Handler.java
- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/handler/XiaomiAqaraActorSwitch2Handler.java
- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/handler/XiaomiAqaraSensorSwitch1Handler.java
- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/handler/XiaomiAqaraSensorSwitch2Handler.java
- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/handler/XiaomiBridgeHandler.java
- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/handler/XiaomiDeviceBaseHandler.java
- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/handler/XiaomiSensorBaseAlarmHandler.java
- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/handler/XiaomiSensorBaseHandler.java
- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/handler/XiaomiSensorBaseHandlerWithTimer.java
- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/handler/XiaomiSensorCubeHandler.java
- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/handler/XiaomiSensorGasHandler.java
- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/handler/XiaomiSensorHtHandler.java
- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/handler/XiaomiSensorLockHandler.java
- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/handler/XiaomiSensorMagnetHandler.java
- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/handler/XiaomiSensorMotionHandler.java
- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/handler/XiaomiSensorSmokeHandler.java
- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/handler/XiaomiSensorSwitchHandler.java
- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/handler/XiaomiSensorVibrationHandler.java
- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/handler/XiaomiSensorWaterHandler.java
- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/socket/XiaomiSocket.java
> [mihome] Made constants and handler packages internal

- addons/binding/org.openhab.binding.lutron/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/LutronBindingConstants.java
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/LutronHandlerFactory.java
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/config/DimmerConfig.java
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/config/IPBridgeConfig.java
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/discovery/LutronDeviceDiscoveryService.java
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/discovery/RadioRA2MainRepeaterDiscoveryService.java
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/grxprg/PrgConstants.java
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/BaseKeypadHandler.java
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/CcoHandler.java
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/DimmerHandler.java
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/IPBridgeHandler.java
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/KeypadHandler.java
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/LutronHandler.java
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/MaintainedCcoHandler.java
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/OccupancySensorHandler.java
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/PicoKeypadHandler.java
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/PulsedCcoHandler.java
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/ShadeHandler.java
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/SwitchHandler.java
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/TabletopKeypadHandler.java
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/VcrxHandler.java
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/VirtualKeypadHandler.java
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/hw/HwConstants.java
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/hw/HwDimmerHandler.java
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/radiora/RadioRAConstants.java
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/radiora/handler/DimmerHandler.java
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/radiora/handler/PhantomButtonHandler.java
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/radiora/handler/SwitchHandler.java
> [lutron] Made constants and handler packages internal

- addons/io/org.openhab.io.transport.modbus.test/src/test/java/org/openhab/io/transport/modbus/test/SmokeTest.java
To decrease susceptibility to CI slowness 
- testing with slower poll rate (50 -> 150 ms)
- relaxing assertion limits
Also
- improved error message to give out more details
(Hopefully) resolves #3910 
> [modbus] Increase robustness in tests and improve assertion error messages

- addons/binding/org.openhab.binding.mihome/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.mihome/README.md
- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/XiaomiHandlerFactory.java
> [mihome]  Removed Guava dependency 

- addons/binding/org.openhab.binding.irtrans/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.irtrans/src/main/java/org/openhab/binding/irtrans/internal/IRtransHandlerFactory.java
> [irtrans] Removed Guava dependency

- addons/binding/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/MaxBindingConstants.java
- addons/binding/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/factory/MaxCubeHandlerFactory.java
- addons/binding/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/handler/MaxCubeBridgeHandler.java
- addons/binding/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/handler/MaxDevicesHandler.java
- Fixed an error sending a QuantityType command
- Minor code clean-ups
Closes #4119
> [max] Fixed an error sending a QuantityType command

- addons/binding/org.openhab.binding.lutron/ESH-INF/thing/thing-types.xml
- addons/binding/org.openhab.binding.lutron/README.md
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/LutronBindingConstants.java
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/config/IPBridgeConfig.java
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/discovery/LutronDeviceDiscoveryService.java
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/IPBridgeHandler.java
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/net/TelnetSession.java
Hi. This PR fixes the problems described in Issue #4050.  It mainly consists of changes to IPBridgeHandler and TelnetSession.
The changes include the following:
•	Improved tracking of connection status in TelnetSession
•	Improved exception handling in TelnetSession to make it more robust.
•	Addition of automatic retries when initial connection attempt fails in IPBridgeHandler.
•	Addition of configuration parameters for IPBridgeHandler to allow the user to set heartbeat and retry intervals.
•	Additional debug logging to help resolve any future issues.
•	Documentation update
Many of the changes in this PR were originally developed by Allan Tong ( @actong ), and are used here with his permission.
Regards,
Bob Adair
> [Lutron] Bridge connection resiliency improvements

- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/handler/XiaomiBridgeHandler.java
Hi all,
I fixed a small bug I made in a former commit.
- the bridge sends a heartbeat every 10 seconds
- I made a timeout to react to the bridge being offline and update the bridge thing status in #3897 
- the timeout timer was started on binding start
- the timer was never reset as soon as the binding received a heartbeat message
> [MiHome] fix bridge timeout timer

- addons/binding/org.openhab.binding.onkyo/ESH-INF/thing/tx-nr575e.xml
- addons/binding/org.openhab.binding.onkyo/README.md
- addons/binding/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/OnkyoBindingConstants.java
This should fix my issue #4010. The code is NOT tested as I don't have a working dev env but should compile fine and work as expected. I tried to follow PR #3863 as suggested.
> [ONKYO] Add support for device TX-NR575E

- addons/binding/org.openhab.binding.openuv/ESH-INF/thing/thing-types.xml
- addons/binding/org.openhab.binding.openuv/README.md
- addons/binding/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/handler/OpenUVBridgeHandler.java
- addons/binding/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/handler/OpenUVReportHandler.java
Code refactoring and cleansing
> [OpenUV] Adding UoM

- addons/binding/org.openhab.binding.icloud/README.md
I think group name parameters should be switched
> [iCloud] Update README.md

- addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxServerHandler.java
Fix for some third-party apps sending a `subscribe playlist` command, which is not handled properly by the binding.
Fixes #4156
> [squeezebox] Fix for ArrayIndexOutOfBounds exception

- addons/binding/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/KodiHandlerFactory.java
- addons/binding/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/KodiPlayerState.java
- addons/binding/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/config/KodiChannelConfig.java
- addons/binding/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/config/KodiConfig.java
- addons/binding/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/handler/KodiHandler.java
- addons/binding/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/protocol/KodiClientSocket.java
- addons/binding/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/protocol/KodiClientSocketEventListener.java
- addons/binding/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/protocol/KodiConnection.java
- Switched to shared instance of WebSocketClient using WebSocketFactory
- Minor code cleanups to fix sat findings
> [kodi] Switched to shared instance of WebSocketClient

- addons/io/org.openhab.io.transport.modbus/src/main/java/org/openhab/io/transport/modbus/internal/ModbusManagerImpl.java
In modbus transport, binding(s) will set-up regular polling of a device. This polling happens using a dedicated thread pool. Once the transport bundle receives the response from the modbus slave, the  callback is called ("hey, here's some new data") in a separate thread. The callbacks have their own dedicated thread pool.
Now there's a problem (see #4135) if the callbacks take longer time than the actual interaction with the slave -- internal queue of the call back thread pool executor increases without limit. For example, if the transport can poll the slave 50 per second (period=20ms), but the callback takes at least 100 ms to process every response (updating channels, item persistence etc.), queue increases with the rate of 40 responses / second.
This PR makes sure the callbacks are …
> [modbus] use same threads for callbacks and polling

- addons/binding/org.openhab.binding.solaredge/src/main/java/org/openhab/binding/solaredge/internal/AtomicReferenceTrait.java
- addons/binding/org.openhab.binding.solaredge/src/main/java/org/openhab/binding/solaredge/internal/AtomicReferenceUtils.java
- addons/binding/org.openhab.binding.solaredge/src/main/java/org/openhab/binding/solaredge/internal/SolarEdgeBindingConstants.java
- addons/binding/org.openhab.binding.solaredge/src/main/java/org/openhab/binding/solaredge/internal/command/AggregateDataUpdatePublicApi.java
- addons/binding/org.openhab.binding.solaredge/src/main/java/org/openhab/binding/solaredge/internal/command/LiveDataUpdateMeterless.java
- addons/binding/org.openhab.binding.solaredge/src/main/java/org/openhab/binding/solaredge/internal/command/LiveDataUpdatePrivateApi.java
- addons/binding/org.openhab.binding.solaredge/src/main/java/org/openhab/binding/solaredge/internal/command/LiveDataUpdatePublicApi.java
- addons/binding/org.openhab.binding.solaredge/src/main/java/org/openhab/binding/solaredge/internal/connector/WebInterface.java
- addons/binding/org.openhab.binding.solaredge/src/main/java/org/openhab/binding/solaredge/internal/handler/SolarEdgeAggregateDataPolling.java
- addons/binding/org.openhab.binding.solaredge/src/main/java/org/openhab/binding/solaredge/internal/handler/SolarEdgeBaseHandler.java
- addons/binding/org.openhab.binding.solaredge/src/main/java/org/openhab/binding/solaredge/internal/handler/SolarEdgeHandler.java
- addons/binding/org.openhab.binding.solaredge/src/main/java/org/openhab/binding/solaredge/internal/handler/SolarEdgeLiveDataPolling.java
- addons/binding/org.openhab.binding.solaredge/src/main/java/org/openhab/binding/solaredge/internal/model/DataResponse.java
- addons/binding/org.openhab.binding.solaredge/src/main/java/org/openhab/binding/solaredge/internal/model/LiveDataResponseMeterless.java
- incorporated some improvements due findings in the nibe uplink binding (e.g. thread saftey improvements)
- binding will no longer crash when solaredge is not available for several minutes and command queue is full
> [solaredge] improve code quality and stability

- addons/binding/org.openhab.binding.somfytahoma/ESH-INF/thing/exteriorscreen.xml
- addons/binding/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/SomfyTahomaBindingConstants.java
- addons/binding/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/handler/SomfyTahomaBaseThingHandler.java
- addons/binding/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/handler/SomfyTahomaBridgeHandler.java
- addons/binding/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/handler/SomfyTahomaGatewayHandler.java
Fixes problem with refreshing values for Connexoon users addressed in the [forum](https://community.openhab.org/t/tahoma-binding-compatible-with-oh2/27004/209?u=ondrej_pecta)
> [somfytahoma] Improved compatibility with the Connexoon box

- addons/binding/org.openhab.binding.kostalinverter/ESH-INF/thing/thing-types.xml
- addons/binding/org.openhab.binding.kostalinverter/README.md
- addons/binding/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/internal/kostal/inverter/WebscrapeHandler.java
Signed-off-by: Christian Schneider <cschneid@adobe.com> (github: cschneider)
Integrated issue from
#1021
Adding some more channels
Tested in Paper UI.
> [kostal] Add channels (#1021)

- addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/handler/NestBaseHandler.java
The caching is no longer necessary now that the ESH registry performance has substantially improved
See also: eclipse/smarthome#6416
> [Nest] Remove caching of linked channel UIDs

- addons/binding/org.openhab.binding.modbus.test/src/test/java/org/openhab/binding/modbus/internal/ModbusDataHandlerTest.java
Null check fix cherry-picked from https://github.com/openhab/openhab2-addons/pull/4159#event-1948949246
> [modbus] null check fixes

- addons/binding/org.openhab.binding.icloud/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/ICloudBindingConstants.java
- addons/binding/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/ICloudHandlerFactory.java
- addons/binding/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/discovery/ICloudDeviceDiscovery.java
- addons/binding/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/handler/ICloudAccountBridgeHandler.java
- addons/binding/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/handler/ICloudDeviceHandler.java
- addons/binding/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/json/request/ICloudFindMyDeviceRequest.java
> [icloud] Made constants and handler packages internal

- addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/channel/KNXChannelType.java
- addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/AbstractKNXClient.java
- addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/KNXCoreTypeMapper.java
*CHANGES*
KNXCoreTypeMapper: Added percentage manipulation
KNXChannelType: PATTERN can deal with 123.1234 now 
KNXChannelType, AbstractKNXClient: Added some traces for better debug.
*DESCRIPTION*
Solution for the bugs from: https://github.com/openhab/openhab2-addons/pull/3433
*TESTING*
Disable knx in PaperUI or /etc/openhab2/services/addons.cfg and copy [org.openhab.binding.knx-2.4.0-SNAPSHOT.jar](https://github.com/lewie/openhab2/raw/KNX2_addColorChannel_rev3_testfile/org.openhab.binding.knx-2.4.0-SNAPSHOT.jar) to /usr/share/openhab2/addons
> [KNX2] Add Color Channel - KNX2_addColorChannel_rev3

- addons/io/org.openhab.io.neeo/README.md
- addons/io/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/internal/NeeoApi.java
- addons/io/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/internal/NeeoDeviceDefinitions.java
- addons/io/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/internal/NeeoUtil.java
- addons/io/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/internal/OpenHabToDeviceConverter.java
- addons/io/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/internal/models/ListUiAction.java
- addons/io/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/internal/models/NeeoDevice.java
- addons/io/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/internal/models/NeeoDeviceChannelDirectoryListItem.java
- addons/io/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/internal/serialization/ListUiActionSerializer.java
- addons/io/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/internal/serialization/NeeoBrainDeviceSerializer.java
- addons/io/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/internal/serialization/NeeoDeviceSerializer.java
- addons/io/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/internal/servletservices/NeeoBrainSearchService.java
- addons/io/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/internal/servletservices/ThingDashboardService.java
- addons/io/org.openhab.io.neeo/web/index.html
- addons/io/org.openhab.io.neeo/web/js/app.js
Signed-off-by: Tim Roberts <troberts@bigfoot.com>
Implements features from firmware 52.10:
1. Added driver version
2. Added ui action to list
> [NEEO] Implements firmware 52.10 (4210)

- addons/binding/org.openhab.binding.icloud/ESH-INF/i18n/iCloud_fr.properties
- addons/binding/org.openhab.binding.icloud/ESH-INF/thing/thing-types.xml
- addons/binding/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/ICloudBindingConstants.java
- addons/binding/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/handler/ICloudDeviceHandler.java
> [iCloud] Adding system low battery channel and french localization

- addons/binding/org.openhab.binding.yeelight/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/YeelightBindingConstants.java
- addons/binding/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/YeelightHandlerFactory.java
- addons/binding/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/discovery/DiscoveryService.java
- addons/binding/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/handler/YeelightCeilingHandler.java
- addons/binding/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/handler/YeelightColorHandler.java
- addons/binding/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/handler/YeelightHandlerBase.java
- addons/binding/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/handler/YeelightStripeHandler.java
- addons/binding/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/handler/YeelightWhiteHandler.java
> [yeelight] Made constants and handler packages internal

- addons/binding/org.openhab.binding.lutron/README.md
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/grxprg/GrafikEyeConfig.java
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/grxprg/GrafikEyeHandler.java
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/grxprg/PrgBridgeConfig.java
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/grxprg/PrgBridgeHandler.java
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/grxprg/PrgConstants.java
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/grxprg/PrgHandlerCallback.java
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/grxprg/PrgProtocolHandler.java
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/grxprg/SocketSession.java
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/grxprg/SocketSessionCallback.java
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/hw/HwConstants.java
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/hw/HwDiscoveryService.java
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/hw/HwSerialBridgeHandler.java
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/radiora/config/DimmerConfig.java
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/radiora/handler/PhantomButtonHandler.java
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/radiora/handler/RS232Handler.java
- addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/radiora/protocol/RadioRAFeedback.java
Hi.  This update to the Lutron binding contains two sets of changes.  First, it contains some improvements to the documentation in README.md.  This needed a bit of cleanup and reorganization after several recent additions.
Second, it contains a bunch of minor code formatting and comment changes necessary to resolve most complaints from the static code analysis tool.  It also includes some Javadoc formatting changes made automatically by Eclipse.  Since these seemed to improve readability, I left them in.  None of the code changes should impact code function.
Regards,
Bob
> [Lutron] Resolve code analysis warnings and update documentation

- addons/binding/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/device/DeviceBase.java
Signed-off-by: Daniel Walters <danielwalters1@hotmail.com>
Fixes https://github.com/openhab/openhab2-addons/issues/4242
> [yeelight] Fix brightness handling

- addons/binding/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/HDPowerViewWebTargets.java
Scenes aren't working on my Powerview 2 Hub because the parameter is passed as "sceneid" instead of "sceneId". I've confirmed this by curling.
Working request returns the shades that were changed.
~/openhab master * curl http://192.168.2.14/api/scenes?sceneId=31325
{"shadeIds":[3044,38643]}
Bad request lists all the scenes
~/openhab master * curl http://192.168.2.14/api/scenes?sceneid=31325
{"sceneIds":[31325,14304,31975,53030,12733,14965],"sceneData":[{"roomId":15794,"name":"RGluaW5nIFJvb20gRnVsbCBPcGVu","colorId":6,"iconId":100,"networkNumber":154,"id":31325,"order":2},{"roomId":15794,"name":"RGluaW5nIFJvb20gQ2xvc2Vk","colorId":7,"iconId":71,"networkNumber":34,"id":14304,"order":1},{"roomId":31443,"name":"TWFzdGVyIERvd24=","colorId":14,"iconId":0,"networkNumber":221,"id":31975,"order":5} …
> HD PowerView Scene Fix

- addons/binding/org.openhab.binding.seneye/ESH-INF/binding/binding.xml
- addons/binding/org.openhab.binding.seneye/ESH-INF/thing/thing-types.xml
- addons/binding/org.openhab.binding.seneye/README.md
- addons/binding/org.openhab.binding.seneye/build.properties
- addons/binding/org.openhab.binding.seneye/src/main/java/org/openhab/binding/seneye/SeneyeBindingConstants.java
- addons/binding/org.openhab.binding.seneye/src/main/java/org/openhab/binding/seneye/handler/SeneyeHandler.java
- addons/binding/org.openhab.binding.seneye/src/main/java/org/openhab/binding/seneye/internal/SeneyeStatus.java
New Pull Request for [Seneye] Add disconnected, slideserial, outofwater, wrongslide channels #3961.
Due to problems cleaning up previous commits.
Signed-off-by: mickursell <bindings@mru-photography.co.uk>
> [Seneye] Add disconnected, slideserial, outofwater, wrongslide channels - new pull

- addons/binding/org.openhab.binding.konnected/README.md
> [konnected] fixed link in docs and put it in-line

- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/ModelMapper.java
- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/handler/XiaomiBridgeHandler.java
Two small changes to fix the mentioned issues:
- add backslash to JSON command string
- add device "remote.b1acn01"
> [MiHome] fix #4190 && fix #4191

- addons/binding/org.openhab.binding.valloxmv/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.valloxmv/src/main/java/org/openhab/binding/valloxmv/internal/ValloxMVHandler.java
- addons/binding/org.openhab.binding.valloxmv/src/main/java/org/openhab/binding/valloxmv/internal/ValloxMVHandlerFactory.java
- addons/binding/org.openhab.binding.valloxmv/src/main/java/org/openhab/binding/valloxmv/internal/ValloxMVWebSocket.java
Switched to shared instance of WebSocketClient using WebSocketFactory
Tried to follow example #4164 from @cweitkamp as much as possible.
Signed-off-by: Björn Brings <bjoernbrings@web.de>
> [ValloxMV] Switched to shared instance of WebSocketClient

- addons/binding/create_openhab_binding_skeleton.cmd
Fixed double quotation marks being passed to maven
This is a minor fix.
I'm not sure how this was missed, but the script fails if one of the arguments contains quotes, which is most likely the case for "Firstname Lastname".
Probably no one dares try develop bindings under Windows :)
Using %~1 instead of %1 returns the first argument with stripped quotes, which is what we need in this case.
This fixes the error message
```
The syntax of the command is incorrect.
The system cannot find the path specified.
```
> [skeleton] Fixed create_openhab_binding_skeleton.cmd

- addons/binding/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/handler/OpenUVBridgeHandler.java
- addons/binding/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/handler/OpenUVReportHandler.java
> [OpenUV] Give a little more time to API timeout.

- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/ChannelTypeUtils.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/NetatmoDeviceHandler.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/NetatmoModuleHandler.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/station/NAMainHandler.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/station/NAModule1Handler.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/station/NAModule2Handler.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/station/NAModule3Handler.java
- addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/station/NAModule4Handler.java
- Added NPE safe-guard
- Fixed SAT findings
Closes #4263 
> [Netatmo] Added NPE safe-guard

- addons/binding/org.openhab.binding.mihome/README.md
Using Openhabian, with openhab 2.3 and Xiaomi Mi smart Home Bundle 2.3.0. Was getting frequent log entries with:
```
Validation issues found in configuration model 'xiaomi.things', using it anyway:
Provide a thing type ID and a thing ID in this format:
<thingTypeId> <thingId>
```
Found posts in the forum with advice to change the xiaomi.things file to the "correct format", i.e. https://community.openhab.org/t/xiaomi-binding-2-1-thing-configuratin-failures-in-log/30751/9
Found that the modifications also required a change to the .items and .rules.
Now have many things in PaperUI inbox, but no errors in log files with the changes I've made. Suggesting the update so others don't have to search for this.
You may wish to have an example for <=2.1 and 2.2/2.3+
> [mihome] Update .things, .items and .rules examples.

- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/ModelMapper.java
Signed-off-by: Dieter Schmidt <dima.loschkin@gmail.com>
> [MiHome] add model remote.b286acn01

- addons/io/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/dto/HueSuccessResponseCreateUser.java
> Hue emulation: Improve class documentation

- addons/io/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/dto/AbstractHueState.java
Add "mode" and "alert" for a better hue emulation.
> Hue emulation: Extend AbstractHueState

- addons/io/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/dto/HueDevice.java
Add "capabilities" and "config", which hopefully makes the OSRAM plug emulation more compatible to Alexa and co.
> Hue emulation: Extend HueDevice response

- addons/io/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/HueEmulationServlet.java
The user created message was not wrapped in a `HueResponse`.
Important note: Although a trivial change, Travis must succeed on this PR before merging.
> Hue emulation: Fix the user created message

- addons/binding/org.openhab.binding.knx/ESH-INF/thing/ip.xml
Closes https://github.com/openhab/openhab2-addons/issues/4236
Signed-off-by: Angelos Fountoulakis agf@wired-net.gr (github: AngelosF)
https://github.com/openhab/openhab2-addons/pull/4237#issuecomment-443579170
> [KNX] Update `localSourceAddr` label & description

- addons/binding/org.openhab.binding.solaredge/src/main/java/org/openhab/binding/solaredge/internal/config/SolarEdgeConfiguration.java
- addons/binding/org.openhab.binding.solaredge/src/main/java/org/openhab/binding/solaredge/internal/connector/WebInterface.java
- addons/binding/org.openhab.binding.solaredge/src/main/java/org/openhab/binding/solaredge/internal/handler/SolarEdgeBaseHandler.java
improved code quality / configuration checks
fixed issue where config changes during runtime were not applied without restart
improved error handling / improved user notifications on errors
> [solaredge] improved handling of configuration / fixed handling of configuration updates

- addons/binding/org.openhab.binding.tesla/ESH-INF/thing/models.xml
- addons/binding/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/TeslaBindingConstants.java
- addons/binding/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/handler/TeslaHandler.java
- addons/binding/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/TeslaChannelSelectorProxy.java
This is a bugfix that includes the following:
1. This fixes the wake up of the vehicle once it did get to sleep, the command was sent to the wrong endpoint so the vehicle never woke up
2. If allow wake up is set to false, the binding will stop polling the vehicle for updates once it detects that the vehicle is not charging and not on the move. After that, it will stop polling for 15 minutes to allow the vehicle to go to sleep. If the vehicle did not go to sleep in that period, it is polled again and the process starts over again.
3. This also adds a new channel "force refresh" that can be used to forcefully refresh vehicle state even if the binding is in the process of trying to let the car go to sleep. I use this to update the states once my wife's or my phone have detected that they …
> [tesla] Allow vehicle to sleep to fix vampire drain

- addons/binding/org.openhab.binding.chromecast/ESH-INF/binding/binding.xml
- addons/binding/org.openhab.binding.chromecast/ESH-INF/config/config.xml
- addons/binding/org.openhab.binding.chromecast/ESH-INF/i18n/chromecast_de.properties
- addons/binding/org.openhab.binding.chromecast/ESH-INF/thing/thing-types.xml
- addons/binding/org.openhab.binding.chromecast/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.chromecast/README.md
- addons/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromecastBindingConstants.java
- addons/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromecastStatusUpdater.java
- addons/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/discovery/ChromecastDiscoveryParticipant.java
- addons/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/factory/ChromecastHandlerFactory.java
- addons/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/handler/ChromecastHandler.java
- Added UoM for some channels
- Switched to system default channel types
- Added German translations
- Added representation property
- Minor performance and code improvements
> [chromecast] General Improvements

- addons/binding/org.openhab.binding.icloud/.classpath
- addons/binding/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/ICloudTlsCertificateProvider.java
> [iCloud] make certificate provider work in IDE as well

- addons/binding/org.openhab.binding.nibeheatpump/src/main/java/org/openhab/binding/nibeheatpump/internal/handler/NibeHeatPumpHandler.java
> [Nibe] Fixed issue related to linked channels

- addons/binding/org.openhab.binding.miio/README.md
Remove product pictures as discussed in #2548
> [miio] update readme

- addons/binding/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/ICloudConnection.java
- addons/binding/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/ICloudDeviceInformationListener.java
- addons/binding/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/handler/ICloudAccountBridgeHandler.java
- addons/binding/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/handler/ICloudDeviceHandler.java
Add nullable annotations and added additional information to the status updates.
> [icloud] Improved the lifecycle

- addons/binding/org.openhab.binding.network.test/src/test/java/org/openhab/binding/network/internal/discovery/DiscoveryTest.java
- addons/binding/org.openhab.binding.network.test/src/test/java/org/openhab/binding/network/internal/toberemoved/cache/ExpiringCacheAsyncTest.java
- addons/binding/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/NetworkBindingConfiguration.java
- addons/binding/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/NetworkHandlerConfiguration.java
- addons/binding/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/NetworkHandlerFactory.java
- addons/binding/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/PresenceDetection.java
- addons/binding/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/PresenceDetectionType.java
- addons/binding/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/dhcp/DHCPPacket.java
- addons/binding/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/discovery/NetworkDiscoveryService.java
- addons/binding/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/handler/NetworkHandler.java
- addons/binding/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/utils/NetworkUtils.java
Let's polish the Network Binding code for the release! :smile:
> [network] Fix SAT findings and some code improvements

- addons/binding/org.openhab.binding.yamahareceiver/ESH-INF/thing/thing-types.xml
- addons/binding/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/discovery/ZoneDiscoveryService.java
Fix #4259
Signed-off-by: David Graeff <david.graeff@web.de>
> Yamaha zones: Add representation-property

- addons/binding/org.openhab.binding.modbus/ESH-INF/thing/thing-data.xml
- addons/binding/org.openhab.binding.modbus/README.md
- addons/io/org.openhab.io.transport.modbus.test/src/test/java/org/openhab/io/transport/modbus/test/BitUtilitiesCommandToRegistersTest.java
- addons/io/org.openhab.io.transport.modbus.test/src/test/java/org/openhab/io/transport/modbus/test/BitUtilitiesExtractStateFromRegistersTest.java
- addons/io/org.openhab.io.transport.modbus/src/main/java/org/openhab/io/transport/modbus/ModbusBitUtilities.java
- addons/io/org.openhab.io.transport.modbus/src/main/java/org/openhab/io/transport/modbus/ModbusConstants.java
> [modbus] Support for 64 bit integers on read & write

- addons/binding/org.openhab.binding.yamahareceiver.test/src/test/java/org/openhab/binding/yamahareceiver/internal/protocol/xml/ModelContext.java
- addons/io/org.openhab.io.hueemulation.test/src/test/java/org/openhab/io/hueemulation/internal/HueEmulationServiceOSGiTest.java
- addons/io/org.openhab.io.hueemulation.test/src/test/java/org/openhab/io/hueemulation/internal/HueRestAPITest.java
- addons/io/org.openhab.io.hueemulation.test/src/test/java/org/openhab/io/hueemulation/internal/LightItemsTest.java
> Updated / edit some missing or otherwise distinct copyright headers

- addons/binding/org.openhab.binding.deconz/README.md
Example and presence description were not correct.
> [deconz] Update README.md

- addons/binding/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/SensorThingHandler.java
- addons/binding/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/netutils/ValueUpdateListener.java
- addons/binding/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/netutils/WebSocketConnection.java
Fixes #4355
@Markkuuss Could you test this change?
> Deconz: Fix ChannelID!=SensorID

- addons/binding/org.openhab.binding.samsungtv/README.md
> [samsungtv] Add LE40C650 to tested models list

- addons/io/org.openhab.io.hueemulation.test/src/test/java/org/openhab/io/hueemulation/internal/HueRestAPITest.java
- addons/io/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/dto/HueDevice.java
- addons/io/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/dto/HueStateColorBulb.java
Added the missing xy and xy_inc features aswell as a testcase to the HueEmulation as discussed in the comments of #4216 
Fixes #4348
> [HueEmulation] Implement xy and xy_inc functionality

- tools/checkstyle.properties
Due to still open issue: [openhab/static-code-analysis/issues/304](https://github.com/openhab/static-code-analysis/issues/304)
Fixes #4397
> Update version number regex in checkstyle.properties

- addons/binding/org.openhab.binding.solarlog/README.md
> [solarlog] Update README.md

- addons/binding/org.openhab.binding.systeminfo/README.md
Add Sitemap example
correct some spelling errors
correct indentation
> [systeminfo] Update Readme.md

- addons/binding/org.openhab.binding.modbus/README.md
Small fix for README
See constructConnectionPool in ModbusManagerImpl
https://github.com/openhab/openhab2-addons/blob/master/addons/io/org.openhab.io.transport.modbus/src/main/java/org/openhab/io/transport/modbus/internal/ModbusManagerImpl.java#L294
PaperUI default is also 35 ms
https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.modbus/ESH-INF/thing/bridge-serial.xml#L124
> [modbus] README: timeBetweenTransactionsMillis default fix w/ serial

- addons/binding/org.openhab.binding.modbus.test/src/test/java/org/openhab/binding/modbus/internal/ModbusDataHandlerTest.java
- addons/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/handler/ModbusDataThingHandler.java
> Modbus fix status descriptions

- addons/voice/org.openhab.voice.googletts/README.md
Fixes #4447
Signed-off-by: Florian Schmidt <florian.schmidt.welzow@t-online.de>
> [googletts] Mention that the TTS service is not free

- addons/io/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/dto/HueDevice.java
Post received commands to the framework no matter if it would change or not change the currently known state.
> [Hue emulation] Always post received command

- addons/binding/org.openhab.binding.gpstracker/README.md
Updated README.md of binding [gpstracker]
> [gpstracker] Update README.md

- addons/binding/org.openhab.binding.miio/ESH-INF/config/config.xml
- addons/binding/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/handler/MiIoBasicHandler.java
addressing issue https://community.openhab.org/t/xiaomi-robot-vacuum-binding/31317/914
> [miio] fixes issue with text defined devices

- addons/binding/org.openhab.binding.groheondus/src/main/java/org/openhab/binding/groheondus/internal/discovery/GroheOndusDiscoveryService.java
Adding the new thing type to the constructor of the discovery service was a mistake when the thing type was added :)
> [groheondus] Mention Grohe Sense as being discovered

- addons/binding/org.openhab.binding.smartmeter/README.md
**fix:** missing space
**change:** consistent casing of AUTO
**change:** better indication for certain values that strings have to be used
> [smartmeter] Update readme.md

- addons/binding/org.openhab.binding.amazondashbutton/ESH-INF/thing/thing-types.xml
- addons/binding/org.openhab.binding.amazondashbutton/README.md
- addons/binding/org.openhab.binding.amazondashbutton/src/main/java/org/openhab/binding/amazondashbutton/internal/discovery/AmazonDashButtonDiscoveryService.java
- addons/binding/org.openhab.binding.amazondashbutton/src/main/java/org/openhab/binding/amazondashbutton/internal/handler/AmazonDashButtonHandler.java
- Changed trigger channel type to `system.rawbutton` to allow the usage of the `rawbutton-toggle-switch` profile
> [amazondashbutton] Changed trigger channel type to 'system.rawbutton' to allow the usage of the 'rawbutton-toggle-switch' profile

- addons/binding/org.openhab.binding.smartmeter/.project
Fixes the 6 errors showing in Eclipse for this project.
> [smartmeter] Disable Maven nature in Eclipse project configuration

- addons/binding/org.openhab.binding.pentair/ESH-INF/thing/easytouch.xml
- addons/binding/org.openhab.binding.pentair/README.md
- addons/binding/org.openhab.binding.pentair/src/main/java/org/openhab/binding/pentair/internal/PentairBindingConstants.java
- addons/binding/org.openhab.binding.pentair/src/main/java/org/openhab/binding/pentair/internal/PentairPacketStatus.java
- addons/binding/org.openhab.binding.pentair/src/main/java/org/openhab/binding/pentair/internal/handler/PentairEasyTouchHandler.java
[pentair] Add support for feature circuits
Add supports for feature circuits as well as AUX circuits.
Tested and working in local installation.
> [pentair] Support for Feature circuits 1-8

- pom.xml
> Redo #3812

- addons/binding/org.openhab.binding.amazonechocontrol/README.md
- addons/binding/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/AccountServlet.java
- addons/binding/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/BindingServlet.java
- addons/binding/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/Connection.java
- addons/binding/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/handler/AccountHandler.java
- addons/binding/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/handler/EchoHandler.java
- addons/binding/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/statedescription/AmazonEchoDynamicStateDescriptionProvider.java
This is a bugfix PR for amazonechocontrol
Fixed: 
POST and PUT through proxy
TTS problem for users which do not user the device owner account
> [amazonechocontrol] Bugfix for POST and PUT through proxy and TTS problem with none device owner accounts

- addons/binding/org.openhab.binding.enocean/ESH-INF/thing/OccupancySensor.xml
- addons/binding/org.openhab.binding.enocean/README.md
- addons/binding/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/EnOceanBindingConstants.java
- addons/binding/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/A5_07/A5_07.java
- addons/binding/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/A5_07/A5_07_01.java
- addons/binding/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/A5_07/A5_07_02.java
- addons/binding/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/A5_07/A5_07_03.java
- addons/binding/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/EEPType.java
- addons/binding/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/handler/EnOceanBaseSensorHandler.java
Implemented motion sensor EEP family A5_07 (A5-07-01 to A5-07-03)
fixes #4543 
> [enocean] Implemented motion sensor EEP family A5_07

- addons/binding/org.openhab.binding.konnected/README.md
- addons/binding/org.openhab.binding.konnected/src/main/java/org/openhab/binding/konnected/internal/KonnectedBindingConstants.java
- bugfix to konnected:constants to humidity channel
Signed-off-by: Zachary Christiansen <volfan6415@gmail.com> (github: volfan6415)
> [konnected] Bugfix and updates to readme

- addons/binding/org.openhab.binding.lgwebos/README.md
- addons/binding/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/BaseChannelHandler.java
- addons/binding/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/LGWebOSHandlerFactory.java
- addons/binding/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/LauncherApplication.java
- addons/binding/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/MediaControlPlayer.java
- addons/binding/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/MediaControlStop.java
- addons/binding/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/PowerControlPower.java
- addons/binding/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/TVControlChannel.java
- addons/binding/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/TVControlChannelName.java
- addons/binding/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/ToastControlToast.java
- addons/binding/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/VolumeControlMute.java
- addons/binding/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/VolumeControlVolume.java
- addons/binding/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/discovery/LGWebOSDiscovery.java
This PR mainly improves performance by caching channel and application list once the TV turns on, instead of reading them over the network before any change. There are also various improvements on logging, specifically in case the device does not have the required capabilities.
Readme file was updated as well to include information on how to enable debug level logging.
> [lgwebos] Null Safety and Caching

- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/ModelMapper.java
- Add new plug device with model id "ctrl_86plug.aq1"
> [mihome] Added Support for Xiaomi Aqara Smart Wall Socket (86plug)

- addons/binding/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/transport/MiIoAsyncCommunication.java
> [miio] Fix reset for yeelights

- addons/binding/org.openhab.binding.satel/ESH-INF/thing/event-log.xml
- addons/binding/org.openhab.binding.satel/ESH-INF/thing/output.xml
- addons/binding/org.openhab.binding.satel/ESH-INF/thing/shutter.xml
- addons/binding/org.openhab.binding.satel/README.md
- addons/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/SatelBindingConstants.java
- addons/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/SatelHandlerFactory.java
- addons/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/command/IntegraStatusCommand.java
- addons/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/command/ReadDeviceInfoCommand.java
- addons/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/command/ReadEventCommand.java
- addons/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/command/ReadEventDescCommand.java
- addons/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/command/SetClockCommand.java
- addons/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/config/SatelBridgeConfig.java
- addons/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/discovery/SatelDeviceDiscoveryService.java
- addons/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/event/IntegraStatusEvent.java
- addons/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/handler/SatelBridgeHandler.java
- addons/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/handler/SatelEventLogHandler.java
- addons/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/handler/SatelOutputHandler.java
- addons/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/handler/SatelPartitionHandler.java
- addons/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/handler/SatelShutterHandler.java
- addons/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/handler/SatelStateThingHandler.java
- addons/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/handler/SatelSystemHandler.java
- addons/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/handler/SatelThingHandler.java
- addons/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/handler/SatelZoneHandler.java
- addons/binding/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/protocol/SatelModule.java
This PR adds new thing type "Event Log" to allow reading event log records of the alarm system.
Reading must be performed sequentially record by record, starting from the most recent one, by sending index of the record to read to "index" channel. After sending index command, the rest of the channels are populated with the data of the event log record. 
Example rule of reading first 30 records from the ecent log is included in the documentation.
There are also few other minor changes. mostly related to ESH changes.
> [satel] Event log support added, code cleanup

- addons/binding/org.openhab.binding.regoheatpump/ESH-INF/thing/thing-types.xml
- addons/binding/org.openhab.binding.regoheatpump/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.regoheatpump/README.md
- addons/binding/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/RegoHeatPumpBindingConstants.java
- addons/binding/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/handler/HusdataHandler.java
- addons/binding/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/handler/Rego6xxHeatPumpHandler.java
- addons/binding/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/rego6xx/AbstractResponseParser.java
- addons/binding/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/rego6xx/Checksum.java
- addons/binding/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/rego6xx/CommandFactory.java
- addons/binding/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/rego6xx/ErrorLine.java
- addons/binding/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/rego6xx/RegoRegisterMapper.java
- addons/binding/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/rego6xx/ResponseParserFactory.java
- addons/binding/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/rego6xx/ValueConverter.java
- addons/binding/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/rego6xx/WriteResponse.java
Added support for UoM, new channels, write support.
Signed-off-by: Boris Krivonog boris.krivonog@gmail.com
> [regoheatpump] Added support for UoM, new channels, write support.

- addons/binding/org.openhab.binding.smartmeter/README.md
* Updated README.md and added Landis+Gyr E650 as working hardware (running for several days now (without any issue).
* changed enumeration to headers
> [smartmeter] Added Landis+Gyr E650 as working hardware

- addons/binding/org.openhab.binding.deconz/ESH-INF/thing/thing-types.xml
- addons/binding/org.openhab.binding.deconz/README.md
- addons/binding/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/BindingConstants.java
- addons/binding/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/HandlerFactory.java
- addons/binding/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/discovery/ThingDiscoveryService.java
- addons/binding/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/dto/SensorConfig.java
- addons/binding/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/dto/SensorState.java
- addons/binding/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/SensorThingHandler.java
- Added support for Water Leakage Sensor
- Added support for optional channel temperature for Xiaomi sensors
- Added support for optional channel power on consumption sensors
- Added support for optional channels voltage and current on power sensors
Closes #4588
Closes #4515
> [deconz] Added Water Leakage Sensor, Added checks for optional Channels

- addons/io/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/LightItems.java
> [Hueemulation] Allow rollershutters to be exposed

- addons/binding/org.openhab.binding.lgwebos/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/action/LGWebOSActions.java
- addons/binding/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/BaseChannelHandler.java
- addons/binding/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/ChannelHandler.java
- addons/binding/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/LGWebOSHandlerFactory.java
- addons/binding/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/LauncherApplication.java
- addons/binding/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/MediaControlPlayer.java
- addons/binding/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/MediaControlStop.java
- addons/binding/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/PowerControlPower.java
- addons/binding/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/TVControlChannel.java
- addons/binding/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/TVControlChannelName.java
- addons/binding/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/ToastControlToast.java
- addons/binding/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/VolumeControlMute.java
- addons/binding/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/VolumeControlVolume.java
- addons/binding/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/handler/LGWebOSHandler.java
> [lgwebos] Made constants and handler packages internal

- addons/binding/org.openhab.binding.vitotronic/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.vitotronic/src/main/java/org/openhab/binding/vitotronic/VitotronicBindingConstants.java
> [vitotronic] Removed Guava dependency

- addons/binding/org.openhab.binding.vitotronic/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.vitotronic/src/main/java/org/openhab/binding/vitotronic/internal/VitotronicBindingConfiguration.java
- addons/binding/org.openhab.binding.vitotronic/src/main/java/org/openhab/binding/vitotronic/internal/VitotronicBindingConstants.java
- addons/binding/org.openhab.binding.vitotronic/src/main/java/org/openhab/binding/vitotronic/internal/VitotronicHandlerFactory.java
- addons/binding/org.openhab.binding.vitotronic/src/main/java/org/openhab/binding/vitotronic/internal/discovery/VitotronicBridgeDiscovery.java
- addons/binding/org.openhab.binding.vitotronic/src/main/java/org/openhab/binding/vitotronic/internal/discovery/VitotronicDiscoveryService.java
- addons/binding/org.openhab.binding.vitotronic/src/main/java/org/openhab/binding/vitotronic/internal/handler/VitotronicBridgeHandler.java
- addons/binding/org.openhab.binding.vitotronic/src/main/java/org/openhab/binding/vitotronic/internal/handler/VitotronicThingHandler.java
> [vitotronic] Made constants and handler packages internal

- addons/binding/org.openhab.binding.autelis/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.autelis/src/main/java/org/openhab/binding/autelis/internal/AutelisBindingConstants.java
> [autelis] Removed Guava dependency

- features/openhab-addons/src/main/feature/feature.xml
> fixed bundle groupId of UIs

- addons/binding/org.openhab.binding.weatherunderground/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.weatherunderground/src/main/java/org/openhab/binding/weatherunderground/WeatherUndergroundBindingConstants.java
- addons/binding/org.openhab.binding.weatherunderground/src/main/java/org/openhab/binding/weatherunderground/handler/WeatherUndergroundBridgeHandler.java
- addons/binding/org.openhab.binding.weatherunderground/src/main/java/org/openhab/binding/weatherunderground/handler/WeatherUndergroundHandler.java
- addons/binding/org.openhab.binding.weatherunderground/src/main/java/org/openhab/binding/weatherunderground/internal/WeatherUndergroundHandlerFactory.java
- addons/binding/org.openhab.binding.weatherunderground/src/main/java/org/openhab/binding/weatherunderground/internal/config/WeatherUndergroundConfiguration.java
- addons/binding/org.openhab.binding.weatherunderground/src/main/java/org/openhab/binding/weatherunderground/internal/discovery/WeatherUndergroundDiscoveryService.java
- addons/binding/org.openhab.binding.weatherunderground/src/main/java/org/openhab/binding/weatherunderground/internal/json/WeatherUndergroundJsonCurrent.java
- addons/binding/org.openhab.binding.weatherunderground/src/main/java/org/openhab/binding/weatherunderground/internal/json/WeatherUndergroundJsonData.java
- addons/binding/org.openhab.binding.weatherunderground/src/main/java/org/openhab/binding/weatherunderground/internal/json/WeatherUndergroundJsonError.java
- addons/binding/org.openhab.binding.weatherunderground/src/main/java/org/openhab/binding/weatherunderground/internal/json/WeatherUndergroundJsonForecast.java
- addons/binding/org.openhab.binding.weatherunderground/src/main/java/org/openhab/binding/weatherunderground/internal/json/WeatherUndergroundJsonForecastDay.java
- addons/binding/org.openhab.binding.weatherunderground/src/main/java/org/openhab/binding/weatherunderground/internal/json/WeatherUndergroundJsonLocation.java
- addons/binding/org.openhab.binding.weatherunderground/src/main/java/org/openhab/binding/weatherunderground/internal/json/WeatherUndergroundJsonResponse.java
- addons/binding/org.openhab.binding.weatherunderground/src/main/java/org/openhab/binding/weatherunderground/internal/json/WeatherUndergroundJsonSimpleForecast.java
- addons/binding/org.openhab.binding.weatherunderground/src/main/java/org/openhab/binding/weatherunderground/internal/json/WeatherUndergroundJsonUtils.java
Updates the WeatherUnderground Binding to use openHAB packages.
> [weatherunderground] Changes ESH packages to openHAB

- addons/io/org.openhab.io.javasound/src/main/java/org/openhab/io/javasound/internal/AudioPlayer.java
- addons/io/org.openhab.io.javasound/src/main/java/org/openhab/io/javasound/internal/JavaSoundAudioSink.java
- addons/io/org.openhab.io.javasound/src/main/java/org/openhab/io/javasound/internal/JavaSoundAudioSource.java
- addons/io/org.openhab.io.javasound/src/main/java/org/openhab/io/javasound/internal/JavaSoundInputStream.java
Updates Javasound to use openHAB packages.
> [javasound] Changes ESH packages to openHAB

- addons/binding/org.openhab.binding.enocean/ESH-INF/thing/ClassicDevice.xml
- addons/binding/org.openhab.binding.enocean/ESH-INF/thing/channels.xml
- addons/binding/org.openhab.binding.kostalinverter/ESH-INF/thing/thing-types.xml
- addons/binding/org.openhab.binding.mqtt.generic/ESH-INF/config/color-channel-config.xml
- addons/binding/org.openhab.binding.mqtt.generic/ESH-INF/config/dimmer-channel-config.xml
- addons/binding/org.openhab.binding.mqtt.generic/ESH-INF/config/number-channel-config.xml
- addons/binding/org.openhab.binding.mqtt.generic/ESH-INF/config/rollershutter-channel-config.xml
- addons/binding/org.openhab.binding.mqtt.generic/ESH-INF/config/string-channel-config.xml
- addons/binding/org.openhab.binding.mqtt/ESH-INF/thing/thing-types.xml
- addons/binding/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/OwHandlerFactory.java
- addons/binding/org.openhab.binding.yamahareceiver/ESH-INF/thing/thing-types.xml
- addons/extensionservice/org.openhab.extensionservice.marketplace/ESH-INF/config/config.xml
- addons/transform/org.openhab.transform.exec/ESH-INF/config/execProfile.xml
- addons/transform/org.openhab.transform.javascript/ESH-INF/config/javascriptProfile.xml
- addons/transform/org.openhab.transform.jsonpath/ESH-INF/config/jsonpathProfile.xml
- addons/transform/org.openhab.transform.map/ESH-INF/config/mapProfile.xml
- addons/transform/org.openhab.transform.regex/ESH-INF/config/regexProfile.xml
- addons/transform/org.openhab.transform.scale/ESH-INF/config/scaleProfile.xml
- addons/transform/org.openhab.transform.xpath/ESH-INF/config/xpathProfile.xml
- addons/transform/org.openhab.transform.xslt/ESH-INF/config/xsltProfile.xml
- tools/checkstyle.properties
* Replace spaces with tabs in XML files because SAT will consider these as errors (https://github.com/openhab/static-code-analysis/pull/268)
* Use default file name for generated OwHandlerFactory component XML so it can contain spaces
* Add com.google.common.collect to forbidden packages (see also https://github.com/openhab/openhab-core/pull/407)
Resolves most of the issues with SAT 0.6.0-SNAPSHOT.
> Replace spaces with tabs in XML and update checkstyle.properties

- addons/binding/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/command/UdpCubeCommand.java
Signed-off-by: Metin Savignano ms@savignano.net (github: cubistico)
Just a quick fix for the StringIndexOutOfBoundsException that happened when sending the rebootCube action.
Fixes #4618
> [max] Fix StringIndexOutOfBoundsException when on rebootCube action

- addons/binding/org.openhab.binding.neato/README.md
The readme is now updated with the configuration needed to make the items work.
A user can now copy past the example and it should work out of the box.
> [neato] Updated the readme with the correct channel configuration for items

- features/openhab-addons/src/main/feature/feature.xml
> fixed sound feature names and indentation

- addons/binding/org.openhab.binding.hue/README.md
Migrated from https://github.com/eclipse/smarthome/pull/6853
Also-By: justClouds <justClouds@users.noreply.github.com>
> [hue] Updated README with fixed example and some clarifications

- addons/binding/org.openhab.binding.bosesoundtouch/src/main/java/org/openhab/binding/bosesoundtouch/internal/CommandExecutor.java
Migrated from https://github.com/eclipse/smarthome/pull/6874
Also-By: Alexander Kostadinov <alexander.g.kostadinov@gmail.com>
> [bosesoundtouch] Fixed an issue with async. websocket requests

- addons/binding/org.openhab.binding.homematic/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/discovery/HomegearDiscoveryParticipant.java
- addons/binding/org.openhab.binding.loxone/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/discovery/LoxoneMiniserverDiscoveryParticipant.java
- addons/binding/org.openhab.binding.samsungtv/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/discovery/SamsungTvDiscoveryParticipant.java
- addons/binding/org.openhab.binding.squeezebox/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/discovery/SqueezeBoxServerDiscoveryParticipant.java
Fixes the 4 remaining `UpnpDiscoveryParticipant` deprecations.
> Fix all remaining UpnpDiscoveryParticipant deprecations

- addons/binding/org.openhab.binding.lifx/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/LifxBindingConstants.java
- addons/binding/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/LifxChannelFactoryImpl.java
- addons/binding/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/LifxHandlerFactory.java
- addons/binding/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/LifxLightCommunicationHandler.java
- addons/binding/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/LifxLightConfig.java
- addons/binding/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/LifxLightContext.java
- addons/binding/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/LifxLightCurrentStateUpdater.java
- addons/binding/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/LifxLightDiscovery.java
- addons/binding/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/LifxLightOnlineStateUpdater.java
- addons/binding/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/LifxLightPropertiesUpdater.java
- addons/binding/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/LifxLightState.java
- addons/binding/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/LifxLightStateChanger.java
- addons/binding/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/handler/LifxLightHandler.java
- addons/binding/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/protocol/GetColorZonesRequest.java
- addons/binding/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/protocol/Product.java
- addons/binding/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/protocol/SetColorZonesRequest.java
- addons/binding/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/util/LifxNetworkUtil.java
- addons/binding/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/util/LifxThrottlingUtil.java
> [lifx] Made constants and handler packages internal

- addons/binding/org.openhab.binding.airquality/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/AirQualityBindingConstants.java
- addons/binding/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/AirQualityHandlerFactory.java
- addons/binding/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/discovery/AirQualityDiscoveryService.java
- addons/binding/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/handler/AirQualityHandler.java
- addons/binding/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/json/AirQualityJsonCity.java
- addons/binding/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/json/AirQualityJsonData.java
- addons/binding/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/json/AirQualityJsonIaqi.java
- addons/binding/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/json/AirQualityJsonResponse.java
- addons/binding/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/json/AirQualityJsonTime.java
- addons/binding/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/json/AirQualityValue.java
- addons/binding/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/json/Attribute.java
> [airquality] Made constants and handler packages internal

- addons/binding/org.openhab.binding.bosesoundtouch/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.bosesoundtouch/src/main/java/org/openhab/binding/bosesoundtouch/internal/BoseSoundTouchBindingConstants.java
- addons/binding/org.openhab.binding.bosesoundtouch/src/main/java/org/openhab/binding/bosesoundtouch/internal/BoseSoundTouchConfiguration.java
- addons/binding/org.openhab.binding.bosesoundtouch/src/main/java/org/openhab/binding/bosesoundtouch/internal/BoseSoundTouchHandlerFactory.java
- addons/binding/org.openhab.binding.bosesoundtouch/src/main/java/org/openhab/binding/bosesoundtouch/internal/CommandExecutor.java
- addons/binding/org.openhab.binding.bosesoundtouch/src/main/java/org/openhab/binding/bosesoundtouch/internal/XMLResponseHandler.java
- addons/binding/org.openhab.binding.bosesoundtouch/src/main/java/org/openhab/binding/bosesoundtouch/internal/XMLResponseProcessor.java
- addons/binding/org.openhab.binding.bosesoundtouch/src/main/java/org/openhab/binding/bosesoundtouch/internal/discovery/SoundTouchDiscoveryParticipant.java
- addons/binding/org.openhab.binding.bosesoundtouch/src/main/java/org/openhab/binding/bosesoundtouch/internal/handler/BoseSoundTouchHandler.java
> [bosesoundtouch] Made constants and handler packages internal

- addons/binding/org.openhab.binding.astro.test/src/test/java/org/openhab/binding/astro/handler/test/AstroCommandTest.java
- addons/binding/org.openhab.binding.astro.test/src/test/java/org/openhab/binding/astro/handler/test/AstroValidConfigurationTest.java
- addons/binding/org.openhab.binding.astro.test/src/test/java/org/openhab/binding/astro/test/AstroStateTest.java
- addons/binding/org.openhab.binding.astro/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/AstroBindingConstants.java
- addons/binding/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/AstroHandlerFactory.java
- addons/binding/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/discovery/AstroDiscoveryService.java
- addons/binding/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/handler/AstroThingHandler.java
- addons/binding/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/handler/MoonHandler.java
- addons/binding/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/handler/SunHandler.java
- addons/binding/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/job/DailyJobMoon.java
- addons/binding/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/job/DailyJobSun.java
- addons/binding/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/job/EventJob.java
- addons/binding/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/job/Job.java
- addons/binding/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/job/PositionalJob.java
- addons/binding/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/job/PublishPlanetJob.java
- addons/binding/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/job/SunPhaseJob.java
> [astro] Made constants and handler packages internal

- addons/binding/org.openhab.binding.dmx.test/src/test/java/org/openhab/binding/dmx/ArtnetBridgeHandlerTest.java
- addons/binding/org.openhab.binding.dmx.test/src/test/java/org/openhab/binding/dmx/ChaserThingHandlerTest.java
- addons/binding/org.openhab.binding.dmx.test/src/test/java/org/openhab/binding/dmx/ColorThingHandlerTest.java
- addons/binding/org.openhab.binding.dmx.test/src/test/java/org/openhab/binding/dmx/DimmerThingHandlerTest.java
- addons/binding/org.openhab.binding.dmx.test/src/test/java/org/openhab/binding/dmx/Lib485BridgeHandlerTest.java
- addons/binding/org.openhab.binding.dmx.test/src/test/java/org/openhab/binding/dmx/SacnBridgeHandlerTest.java
- addons/binding/org.openhab.binding.dmx.test/src/test/java/org/openhab/binding/dmx/TunableWhiteThingHandlerTest.java
- addons/binding/org.openhab.binding.dmx.test/src/test/java/org/openhab/binding/dmx/multiverse/DmxChannelTest.java
- addons/binding/org.openhab.binding.dmx/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.dmx/src/main/java/org/openhab/binding/dmx/internal/DmxHandlerFactory.java
- addons/binding/org.openhab.binding.dmx/src/main/java/org/openhab/binding/dmx/internal/handler/ArtnetBridgeHandler.java
- addons/binding/org.openhab.binding.dmx/src/main/java/org/openhab/binding/dmx/internal/handler/ChaserThingHandler.java
- addons/binding/org.openhab.binding.dmx/src/main/java/org/openhab/binding/dmx/internal/handler/ColorThingHandler.java
- addons/binding/org.openhab.binding.dmx/src/main/java/org/openhab/binding/dmx/internal/handler/DimmerThingHandler.java
- addons/binding/org.openhab.binding.dmx/src/main/java/org/openhab/binding/dmx/internal/handler/Lib485BridgeHandler.java
- addons/binding/org.openhab.binding.dmx/src/main/java/org/openhab/binding/dmx/internal/handler/SacnBridgeHandler.java
- addons/binding/org.openhab.binding.dmx/src/main/java/org/openhab/binding/dmx/internal/handler/TunableWhiteThingHandler.java
> [dmx] Made constants and handler packages internal

- addons/binding/org.openhab.binding.fsinternetradio.test/src/test/java/org/openhab/binding/fsinternetradio/internal/handler/HandlerUtils.java
- addons/binding/org.openhab.binding.fsinternetradio.test/src/test/java/org/openhab/binding/fsinternetradio/test/FSInternetRadioDiscoveryParticipantJavaTest.java
- addons/binding/org.openhab.binding.fsinternetradio.test/src/test/java/org/openhab/binding/fsinternetradio/test/FSInternetRadioHandlerJavaTest.java
- addons/binding/org.openhab.binding.fsinternetradio.test/src/test/java/org/openhab/binding/fsinternetradio/test/MockedRadioHandler.java
- addons/binding/org.openhab.binding.fsinternetradio/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.fsinternetradio/src/main/java/org/openhab/binding/fsinternetradio/internal/FSInternetRadioBindingConstants.java
- addons/binding/org.openhab.binding.fsinternetradio/src/main/java/org/openhab/binding/fsinternetradio/internal/FSInternetRadioDiscoveryParticipant.java
- addons/binding/org.openhab.binding.fsinternetradio/src/main/java/org/openhab/binding/fsinternetradio/internal/FSInternetRadioHandlerFactory.java
- addons/binding/org.openhab.binding.fsinternetradio/src/main/java/org/openhab/binding/fsinternetradio/internal/handler/FSInternetRadioHandler.java
> [fsinternetradio] Made constants and handler packages internal

- addons/binding/org.openhab.binding.globalcache/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.globalcache/src/main/java/org/openhab/binding/globalcache/internal/GlobalCacheBindingConstants.java
- addons/binding/org.openhab.binding.globalcache/src/main/java/org/openhab/binding/globalcache/internal/GlobalCacheHandlerFactory.java
- addons/binding/org.openhab.binding.globalcache/src/main/java/org/openhab/binding/globalcache/internal/command/AbstractCommand.java
- addons/binding/org.openhab.binding.globalcache/src/main/java/org/openhab/binding/globalcache/internal/command/CommandGetdevices.java
- addons/binding/org.openhab.binding.globalcache/src/main/java/org/openhab/binding/globalcache/internal/command/CommandGetserial.java
- addons/binding/org.openhab.binding.globalcache/src/main/java/org/openhab/binding/globalcache/internal/command/CommandGetstate.java
- addons/binding/org.openhab.binding.globalcache/src/main/java/org/openhab/binding/globalcache/internal/command/CommandGetversion.java
- addons/binding/org.openhab.binding.globalcache/src/main/java/org/openhab/binding/globalcache/internal/command/CommandSendir.java
- addons/binding/org.openhab.binding.globalcache/src/main/java/org/openhab/binding/globalcache/internal/command/CommandSendserial.java
- addons/binding/org.openhab.binding.globalcache/src/main/java/org/openhab/binding/globalcache/internal/command/CommandSetserial.java
- addons/binding/org.openhab.binding.globalcache/src/main/java/org/openhab/binding/globalcache/internal/command/CommandSetstate.java
- addons/binding/org.openhab.binding.globalcache/src/main/java/org/openhab/binding/globalcache/internal/command/RequestMessage.java
- addons/binding/org.openhab.binding.globalcache/src/main/java/org/openhab/binding/globalcache/internal/discovery/GlobalCacheDiscoveryService.java
- addons/binding/org.openhab.binding.globalcache/src/main/java/org/openhab/binding/globalcache/internal/discovery/MulticastListener.java
- addons/binding/org.openhab.binding.globalcache/src/main/java/org/openhab/binding/globalcache/internal/handler/GlobalCacheHandler.java
> [globalcache] Made constants and handler packages internal

- addons/binding/org.openhab.binding.meteoblue/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.meteoblue/src/main/java/org/openhab/binding/meteoblue/internal/MeteoBlueBindingConstants.java
- addons/binding/org.openhab.binding.meteoblue/src/main/java/org/openhab/binding/meteoblue/internal/MeteoBlueHandlerFactory.java
- addons/binding/org.openhab.binding.meteoblue/src/main/java/org/openhab/binding/meteoblue/internal/handler/MeteoBlueBridgeHandler.java
- addons/binding/org.openhab.binding.meteoblue/src/main/java/org/openhab/binding/meteoblue/internal/handler/MeteoBlueHandler.java
> [meteoblue] Made constants and handler packages internal

- addons/binding/org.openhab.binding.miio/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoBindingConfiguration.java
- addons/binding/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoBindingConstants.java
- addons/binding/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoDevices.java
- addons/binding/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoHandlerFactory.java
- addons/binding/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/discovery/MiIoDiscovery.java
- addons/binding/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/discovery/MiIoDiscoveryParticipant.java
- addons/binding/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoAbstractHandler.java
- addons/binding/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoBasicHandler.java
- addons/binding/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoGenericHandler.java
- addons/binding/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoUnsupportedHandler.java
- addons/binding/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoVacuumHandler.java
- addons/binding/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/transport/MiIoAsyncCommunication.java
> [miio] Made constants and handler packages internal

- addons/binding/org.openhab.binding.ntp.test/src/test/java/org/openhab/binding/ntp/test/NtpOSGiTest.java
- addons/binding/org.openhab.binding.ntp/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.ntp/src/main/java/org/openhab/binding/ntp/internal/NtpBindingConstants.java
- addons/binding/org.openhab.binding.ntp/src/main/java/org/openhab/binding/ntp/internal/NtpHandlerFactory.java
- addons/binding/org.openhab.binding.ntp/src/main/java/org/openhab/binding/ntp/internal/discovery/NtpDiscovery.java
- addons/binding/org.openhab.binding.ntp/src/main/java/org/openhab/binding/ntp/internal/handler/NtpHandler.java
> [ntp] Made constants and handler packages internal

- addons/binding/org.openhab.binding.rotelra1x/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.rotelra1x/src/main/java/org/openhab/binding/rotelra1x/internal/RotelRa1xBindingConstants.java
- addons/binding/org.openhab.binding.rotelra1x/src/main/java/org/openhab/binding/rotelra1x/internal/RotelRa1xHandlerFactory.java
- addons/binding/org.openhab.binding.rotelra1x/src/main/java/org/openhab/binding/rotelra1x/internal/handler/RotelRa1xHandler.java
> [rotelra1x] Made constants and handler packages internal

- addons/binding/org.openhab.binding.weatherunderground/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.weatherunderground/src/main/java/org/openhab/binding/weatherunderground/internal/WeatherUndergroundBindingConstants.java
- addons/binding/org.openhab.binding.weatherunderground/src/main/java/org/openhab/binding/weatherunderground/internal/WeatherUndergroundHandlerFactory.java
- addons/binding/org.openhab.binding.weatherunderground/src/main/java/org/openhab/binding/weatherunderground/internal/discovery/WeatherUndergroundDiscoveryService.java
- addons/binding/org.openhab.binding.weatherunderground/src/main/java/org/openhab/binding/weatherunderground/internal/handler/WeatherUndergroundBridgeHandler.java
- addons/binding/org.openhab.binding.weatherunderground/src/main/java/org/openhab/binding/weatherunderground/internal/handler/WeatherUndergroundHandler.java
> [weatherunderground] Made constants and handler packages internal

- addons/binding/org.openhab.binding.serialbutton/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.serialbutton/src/main/java/org/openhab/binding/serialbutton/internal/SerialButtonBindingConstants.java
- addons/binding/org.openhab.binding.serialbutton/src/main/java/org/openhab/binding/serialbutton/internal/SerialButtonHandlerFactory.java
- addons/binding/org.openhab.binding.serialbutton/src/main/java/org/openhab/binding/serialbutton/internal/handler/SerialButtonHandler.java
> [serialbutton] Made constants and handler packages internal

- addons/binding/org.openhab.binding.tesla/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/TeslaBindingConstants.java
- addons/binding/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/TeslaChannelSelectorProxy.java
- addons/binding/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/TeslaHandlerFactory.java
- addons/binding/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/command/TeslaCommandExtension.java
- addons/binding/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaHandler.java
- addons/binding/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/protocol/TokenRequest.java
> [tesla] Made constants and handler packages internal

- addons/binding/org.openhab.binding.tradfri.test/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.tradfri.test/src/test/java/org/openhab/binding/tradfri/TradfriHandlerTest.java
- addons/binding/org.openhab.binding.tradfri.test/src/test/java/org/openhab/binding/tradfri/discovery/TradfriDiscoveryParticipantOSGITest.java
- addons/binding/org.openhab.binding.tradfri.test/src/test/java/org/openhab/binding/tradfri/discovery/TradfriDiscoveryServiceTest.java
- addons/binding/org.openhab.binding.tradfri/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/DeviceUpdateListener.java
- addons/binding/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/TradfriBindingConstants.java
- addons/binding/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/TradfriHandlerFactory.java
- addons/binding/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/discovery/TradfriDiscoveryParticipant.java
- addons/binding/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/discovery/TradfriDiscoveryService.java
- addons/binding/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/handler/TradfriControllerHandler.java
- addons/binding/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/handler/TradfriGatewayHandler.java
- addons/binding/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/handler/TradfriLightHandler.java
- addons/binding/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/handler/TradfriPlugHandler.java
- addons/binding/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/handler/TradfriSensorHandler.java
- addons/binding/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/handler/TradfriThingHandler.java
- addons/binding/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/model/TradfriControllerData.java
- addons/binding/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/model/TradfriDeviceData.java
- addons/binding/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/model/TradfriLightData.java
- addons/binding/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/model/TradfriPlugData.java
- addons/binding/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/model/TradfriSensorData.java
- addons/binding/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/model/TradfriWirelessDeviceData.java
> [tradfri] Made constants and handler packages internal

- addons/binding/org.openhab.binding.robonect/README.md
I added the 320 in the README.md. Tested. Works.
> Added 320 - tested. Works with 1.0 Beta7a

- addons/binding/org.openhab.binding.vitotronic/README.md
The link to the old openv wiki in sikispaces was invalid. It seems as if this wiki has been shutdown and the whole content has been moved to GitHub.
> The link to the old openv Wiki was invalid

- features/openhab-addons/src/main/feature/feature.xml
* Remove dependencies on ESH binding features
* Add missing `openhab-runtime-base`
* Fix indentation issues
See https://github.com/openhab/openhab2-addons/pull/4705#issuecomment-457580917.
> Fix some issues in feature definitions

- addons/binding/org.openhab.binding.exec/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.exec/src/main/java/org/openhab/binding/exec/internal/ExecBindingConstants.java
- addons/binding/org.openhab.binding.exec/src/main/java/org/openhab/binding/exec/internal/ExecHandlerFactory.java
- addons/binding/org.openhab.binding.exec/src/main/java/org/openhab/binding/exec/internal/handler/ExecHandler.java
> [exec] Made constants and handler packages internal

- addons/binding/org.openhab.binding.mcp23017/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.mcp23017/src/main/java/org/openhab/binding/mcp23017/internal/Mcp23017BindingConstants.java
- addons/binding/org.openhab.binding.mcp23017/src/main/java/org/openhab/binding/mcp23017/internal/Mcp23017HandlerFactory.java
- addons/binding/org.openhab.binding.mcp23017/src/main/java/org/openhab/binding/mcp23017/internal/PinMapper.java
- addons/binding/org.openhab.binding.mcp23017/src/main/java/org/openhab/binding/mcp23017/internal/handler/Mcp23017Handler.java
- addons/binding/org.openhab.binding.mcp23017/src/main/java/org/openhab/binding/mcp23017/internal/handler/Mcp23017PinStateHolder.java
> [mcp23017] Made constants and handler packages internal

- addons/binding/org.openhab.binding.amazonechocontrol/README.md
Signed-off-by: Scott Rushworth openhab@5iver.com (github: openhab-5iver)
> Corrected startRoutine Item type

- addons/binding/org.openhab.binding.amazonechocontrol/README.md
> [amazonechocontrol] Fix tiny spelling mistake

- addons/binding/org.openhab.binding.network.test/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.network.test/src/test/java/org/openhab/binding/network/internal/handler/NetworkHandlerTest.java
- addons/binding/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/PresenceDetection.java
- addons/binding/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/discovery/NetworkDiscoveryService.java
- addons/binding/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/handler/NetworkHandler.java
Solves #4562
This PR adds a cache for the host name resolution with a TTL of 5 minutes. If presence detection fails, the destination address is invalidated immediately.
Also removes the NPE reported in #3464.
> [network] improve host resolution and fix NPE

- addons/binding/org.openhab.binding.plclogo/README.md
> [plclogo] Added documentation for pulse - thing

- addons/binding/org.openhab.binding.somfytahoma/ESH-INF/config/config.xml
- addons/binding/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/SomfyTahomaBindingConstants.java
- addons/binding/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaAwningHandler.java
- addons/binding/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaBaseThingHandler.java
- addons/binding/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaBridgeHandler.java
- addons/binding/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/model/SomfyTahomaApplyResponse.java
- addons/binding/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/model/SomfyTahomaDeviceDefinitionCommand.java
- addons/binding/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/model/SomfyTahomaState.java
- addons/binding/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/model/SomfyTahomaStatusResponse.java
- addons/binding/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/model/SomfyTahomaVersionResponse.java
This update 
- improves compatibility with Tahoma Cloud
- decreases number of messages sent to cloud during status update (decreases the occurency of “Too many requests, try again later” errors)
All issues were reported and fixes confirmed working by community
https://community.openhab.org/t/tahoma-binding-compatible-with-oh2/27004/277?u=ondrej_pecta
> [somfytahoma] Improved compatibility with Tahoma cloud

- addons/binding/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/handler/AdvancedMultisensorThingHandler.java
> [onewire] fix missing sensor refresh for AMS/BMS

- addons/binding/org.openhab.binding.mqtt.generic/README.md
Update documentation to show generic ".items" file item - for help figuring the channel structure of the items file.
Fixed issues with heatpump example.
> [MQTT Generic]Update documentation

- addons/binding/org.openhab.binding.solaredge/README.md
> [solaredge] Update README.md

- addons/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromecastCommander.java
- Added handling for INCREASE/DECREASE commands on volume channel
> [chromecast] Added handling for INCREASE/DECREASE commands on volume channel

- addons/binding/org.openhab.binding.hue/README.md
Migrated from https://github.com/eclipse/smarthome/pull/6829
> [hue] improved readme

- addons/binding/org.openhab.binding.wemo/ESH-INF/thing/thing-types.xml
- addons/binding/org.openhab.binding.wemo/README.md
- addons/binding/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/WemoBindingConstants.java
- addons/binding/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoHandler.java
Signed-off-by: Mihir Patil zbot473@gmail.com (github: zbot473)
I have added a read-only switch for checking if the appliance is in standby. If the current power is more than the standby power, the switch is off, and vice versa.
> Added Standby Switch

- addons/binding/org.openhab.binding.bluetooth/README.md
Fix typo in Bluetooth documentation.
> [Impovement]fix typo in documentation

- addons/binding/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/handler/EchoHandler.java
- addons/binding/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/jsons/JsonActivities.java
This is a small bugfix PR. It fixes that the state update are not working after some time.
Would be nice to get a review very soon.
> [amazonechocontrol] Bugfix for not working state updates

- addons/binding/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/connector/UplinkWebInterface.java
- addons/binding/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/model/BaseChannels.java
two minor fixes reported by community
> [Nibeuplink] bugfixes

- addons/binding/org.openhab.binding.onkyo/ESH-INF/thing/channels.xml
Signed-off-by: Christian Güdel <cg@dmesg.ch>
Fixes issue described here: https://github.com/openhab/openhab2-addons/issues/3509#issuecomment-445367490
> Remove step size to support smaller increments for volume control

- addons/binding/org.openhab.binding.gpstracker/README.md
> Fixed URL to Owntracks in Google Play Store.

- addons/binding/org.openhab.binding.solaredge/README.md
- addons/binding/org.openhab.binding.solaredge/src/main/java/org/openhab/binding/solaredge/internal/connector/WebInterface.java
- adopted documentation, also added changes missing in #4727 
- fixed a minor bug: a configuration change while openhab is running will now cause a new login attempt and thus the thing will not remain in state "UNKNOWN"
> [Solaredge] improved documentation / minor bugfix

- CODEOWNERS
> I am not code owner of the hue binding

- addons/binding/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/WebSocketConnection.java
- addons/binding/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/handler/EchoHandler.java
This is an important bugfix for all users. 
It fixes a thread leak in the case of lost internet connection.
The review comment from my last PR to remove the getAsString() functions in the logging is handled too.
> [amazonechocontrol] Bugfix for thread leak on lost internet connection

- addons/binding/org.openhab.binding.tplinksmarthome.test/src/test/java/org/openhab/binding/tplinksmarthome/internal/TPLinkSmartHomeHandlerFactoryTest.java
- addons/binding/org.openhab.binding.tplinksmarthome/ESH-INF/thing/KL110.xml
- addons/binding/org.openhab.binding.tplinksmarthome/ESH-INF/thing/KL120.xml
- addons/binding/org.openhab.binding.tplinksmarthome/ESH-INF/thing/KL130.xml
- addons/binding/org.openhab.binding.tplinksmarthome/README.md
- addons/binding/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/TPLinkSmartHomeHandlerFactory.java
- addons/binding/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/TPLinkSmartHomeThingType.java
Signed-off-by: Scott Hanson scooter_seh@yahoo.com (github: computergeek1507)
Added KL110, KL120, and KL130 Light Bulb Support
> [tplink] Added KL110, KL120, and KL130 Light Bulb Support

- addons/binding/org.openhab.binding.milight/README.md
- addons/binding/org.openhab.binding.minecraft/README.md
Quickfix to remove some mixed content warnings, i discovered on the website.
> Fix mixed content

- features/openhab-addons-verify/pom.xml
- features/openhab-addons/src/main/feature/feature.xml
> adapted feature names to new openhab-core

- addons/binding/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/utils/NetworkUtils.java
> [network] Fix arping command line

- addons/binding/org.openhab.binding.mqtt/README.md
Explain the event payload for the publishTrigger channel a little more
Signed-off-by: Metin Savignano ms@savignano.net (github: cubistico)
> [mqtt] Update README.md

- addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/KNXCoreTypeMapper.java
#4844
Signed-off-by: lewie <helmut.lehmeyer@gmail.com>
Added direct support for DTP 232.600.
> [knx] DPT 232.600 sends percentage instead of byte

- addons/binding/org.openhab.binding.max/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/MaxBackupUtils.java
- addons/binding/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/MaxConsoleCommandExtension.java
- addons/binding/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/command/UdpCubeCommand.java
- addons/binding/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/handler/MaxCubeBridgeHandler.java
Basic backup of cube data for possible restoring
due to MAX! cube loosing settings  sometimes
https://community.openhab.org/t/max-cube-loses-all-settings-with-openhab/8537
> [max] Cube data backup

- addons/binding/org.openhab.binding.km200/.classpath
> fixed JRE version

- addons/binding/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/AccountServlet.java
Fix wrong title in account page
> [amazonechocontrol] Fix wrong title

- addons/binding/org.openhab.binding.airquality/README.md
Please always use the object method instead of the static method. This is safer and less confusing for newcomers. See https://www.openhab.org/docs/configuration/rules-dsl.html#manipulating-item-states
> [airquality] Update README.md

- addons/binding/org.openhab.binding.milight/README.md
Added ``` for better readability on openhab.org
> [milight] Update README.md

- addons/ui/org.openhab.ui.paper/web-src/js/control/component.control.commandOptions.html
- addons/ui/org.openhab.ui.paper/web-src/js/control/component.control.commandOptions.js
- addons/ui/org.openhab.ui.paper/web-src/js/control/component.control.item.js
- addons/ui/org.openhab.ui.paper/web-src/js/control/string/component.control.string.html
- addons/ui/org.openhab.ui.paper/web-src/js/control/string/component.control.string.js
- addons/ui/org.openhab.ui.paper/web-src/js/control/switch/component.control.switch.html
- addons/ui/org.openhab.ui.paper/web-src/js/control/switch/component.control.switch.js
- addons/ui/org.openhab.ui.paper/web-src/js/repositories/repositories-module.js
This is the follow up on https://github.com/openhab/openhab-core/pull/540.
Signed-off-by: Henning Treu <henning.treu@googlemail.com>
> Paper UI: add support for command options

- addons/binding/org.openhab.binding.elerotransmitterstick/README.md
> [elerotransmitterstick] Update README.md

- addons/ui/org.openhab.ui.paper/PaperUI Setup.launch
> fixed workspace location for Paper UI launch config

- addons/binding/org.openhab.binding.evohome/README.md
Changed pre/indention to ``` for better readability on openhab.org
> [evohome] Changed README.md

- addons/binding/org.openhab.binding.gardena/README.md
Little changes for better readability on openhab.org
> [gardena] Update README.md

- addons/binding/org.openhab.binding.globalcache/README.md
Changed ```*** to ``` for better readability on openhab.org and please use the object method instead of the static method. :)
see https://www.openhab.org/docs/configuration/rules-dsl.html#manipulating-item-states
> [globalcache] Update README.md

- addons/binding/org.openhab.binding.homematic/README.md
> [homematic] Update README.md

- addons/binding/org.openhab.binding.lametrictime/README.md
> [lametrictime] Update README.md

- addons/binding/org.openhab.binding.lgwebos/README.md
> [lgwebos] Update README.md

- addons/binding/org.openhab.binding.lirc/README.md
> [lirc] Update README.md

- addons/binding/org.openhab.binding.neato/README.md
Changed indention to ``` for better readability on openhab.org
> [neato] Update README.md

- addons/binding/org.openhab.binding.pentair/README.md
Changed indention to ``` for better readability on openhab.org
> [pentair] Update README.md

- addons/binding/org.openhab.binding.tellstick/README.md
> [tellstick] Update README.md

- addons/binding/org.openhab.binding.mihome/README.md
Tried to fix the broken layout on openhab.org and please use the object method instead of the static method. :) see https://www.openhab.org/docs/configuration/rules-dsl.html#manipulating-item-states
> [mihome] Update README.md

- addons/binding/org.openhab.binding.zoneminder/README.md
> [zoneminder] Update README.md

- addons/io/org.openhab.io.homekit/README.md
> [homekit] Update README.md

- addons/binding/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/PresenceDetection.java
Added additional check for tool(s) which do not support / required Interface Option
[network] Added support for Eli Fulkerson ARP Ping Tool
Support for arp-ping.exe tool for Windows from Eli Fulkerson:
https://www.elifulkerson.com/projects/arp-ping.php
Signed-off-by: Konstantin Panchenko <kpanchen@konstantech.com>
> [network] Update PresenceDetection.java

- addons/binding/org.openhab.binding.mqtt.generic/ESH-INF/config/number-channel-config.xml
> [mqtt] postCommand for number channels

- addons/binding/org.openhab.binding.mqtt.generic/ESH-INF/config/dimmer-channel-config.xml
> [mqtt] postCommand for dimmer channels

- addons/binding/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/handler/SysteminfoHandler.java
- Reduced logging
- Fixed spelling mistakes
See https://community.openhab.org/t/systeminfo-error-no-information-for-channel-battery-remainingcapacity-with-device-intex-0/67846/3
> [systeminfo] Reduced logging

- addons/transform/org.openhab.transform.jsonpath/README.md
Rule example contained a dot which shouldn't be there. I have tested the example first with and then without rule. The transformation only worked without the dot.
> [jsonpath] Updated README.md (fixed typo)

- addons/binding/org.openhab.binding.mqtt.generic/README.md
Wasn't clear that the option accepts a boolean value.
> [mqtt.generic] Documentation, postCommand

- addons/binding/org.openhab.binding.bluetooth.bluez/src/main/java/org/openhab/binding/bluetooth/bluez/handler/BlueZBridgeHandler.java
> [bluetooth.bluez] Fill in manufacturer id when available

- addons/binding/org.openhab.binding.modbus/README.md
Docs: Refer to general serial port configuration, as discussed [in openhab-docs/#755](https://github.com/openhab/openhab-docs/pull/755#issuecomment-464446980).
> [modbus] docs: refer to general serial port configuration instructions

- CODEOWNERS
> Remove UIs from Codeowners

- addons/binding/org.openhab.binding.mqtt.generic/README.md
> [mqtt][Docu] Finish "Synchronise two instances"

- addons/binding/org.openhab.binding.amazonechocontrol/README.md
This PR updates the readme. It was reported by a user that the documentation should be improved in this way.
> [amazonechocontrol] Documentation update

- addons/io/org.openhab.io.transport.modbus/README.md
> [modbus] Readme

- addons/io/org.openhab.io.transport.feed/README.md
> [feed] Readme

- addons/io/org.openhab.io.javasound/README.md
> [javasound] Readme

- addons/voice/org.openhab.voice.kaldi/README.md
> [kaldi] Readme

- addons/extensionservice/org.openhab.extensionservice.marketplace/README.md
> [eclipsemarketplace] Readme

- addons/binding/org.openhab.binding.modbus/README.md
A few small corrections and improvements.
I understand real names are required - I am Ross Kennedy
> [modbus] Minor text updates

- addons/binding/org.openhab.binding.samsungtv/README.md
Update .md in samsung tv binding. Add a new device tested.
Because the user instruction of this particular binding does not provide necessary setting, how to operate the binding etc., I'm not sure if how I used the binding is sufficient. With that, my testing result may be limited and might not reflect the actual capability of the binding.
> [samsungtv] Update tested device list (UN50J5200)

- addons/binding/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/PresenceDetection.java
Need to be equal instead of unequal.
Fixes #4966
> [network] Fix NPE

- addons/binding/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/handler/YeelightCeilingHandler.java
- addons/binding/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/handler/YeelightHandlerBase.java
- addons/binding/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/handler/YeelightWhiteHandler.java
Signed-off-by: Joe Ho <goodfore@gmail.com> (github: goodfore)
Fixes #4767
> [yeelight] Fix UI not updating from status for Color bulb

- addons/binding/org.openhab.binding.knx/README.md
[KNX] 
Binding documentation improvement
I added two notes which would have saved me hours when switching from KNX1 to KNX2.
See https://community.openhab.org/t/knx2-massive-problems/67309/6
Regards,
Dirk
> [knx] Update README.md

- CODEOWNERS
- addons/transform/org.openhab.transform.jinja.test/NOTICE
- addons/transform/org.openhab.transform.jinja.test/src/test/java/org/openhab/transform/jinja/internal/JinjaTransformationServiceTest.java
- addons/transform/org.openhab.transform.jinja/ESH-INF/config/jinjaProfile.xml
- addons/transform/org.openhab.transform.jinja/NOTICE
- addons/transform/org.openhab.transform.jinja/build.properties
- addons/transform/org.openhab.transform.jinja/src/main/java/org/openhab/transform/jinja/internal/JinjaTransformationService.java
- addons/transform/org.openhab.transform.jinja/src/main/java/org/openhab/transform/jinja/internal/profiles/JinjaTransformationProfile.java
- addons/transform/org.openhab.transform.jinja/src/main/java/org/openhab/transform/jinja/internal/profiles/JinjaTransformationProfileFactory.java
- features/openhab-addons/src/main/feature/feature.xml
See https://github.com/openhab/openhab2-addons/pull/4943#discussion_r259614623
> [jinja] Fix license headers, update CODEOWNERS

- addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/CFactory.java
Small change in CFactory to get ride of duplicate code
> [mqtt] CFactory: don't repeat yourself

- addons/binding/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/GardenaSmartImpl.java
- addons/binding/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/config/GardenaConfig.java
- addons/binding/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/config/GardenaConfigDataWrapper.java
- addons/binding/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/model/Session.java
- addons/binding/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/model/SessionAttributes.java
- addons/binding/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/model/SessionWrapper.java
> [gardena] Adaptations to new Gardena API

- addons/binding/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaHandler.java
> [tesla] fixed increase/decrease handling for sunroof

- addons/binding/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/model/BaseChannels.java
- addons/binding/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/model/F1145Channels.java
- addons/binding/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/model/F1155Channels.java
- addons/binding/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/model/F730Channels.java
- addons/binding/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/model/F750Channels.java
- addons/binding/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/model/VVM310Channels.java
- addons/binding/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/model/VVM320Channels.java
- addons/binding/org.openhab.binding.robonect/src/main/java/org/openhab/binding/robonect/internal/handler/RobonectHandler.java
- addons/binding/org.openhab.binding.synopanalyzer/src/main/java/org/openhab/binding/synopanalyzer/internal/SynopAnalyzerBindingConstants.java
Pfff so much for local builds....I don't know why but my local build was all nice and dandy on my core changes, except for the earlier fixed issues...
> Fixed more incorrect usages of units classes.

- addons/binding/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/HandlerFactory.java
- addons/binding/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/discovery/ThingDiscoveryService.java
- addons/binding/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/DeconzBridgeHandler.java
- Added background discovery service
- Fixed discovery of `water-leakage` sensor
> [deconz] Added background discovery service

- addons/binding/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/handler/OwserverBridgeHandler.java
addresses some comments from #4710.
> [onewire] fix JavaDoc

- addons/binding/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/model/TradfriLightData.java
- Fixed rounding, cast result to `int`
Fixes #5032 
> [tradfri] Fixed rounding, cast result to 'int'
