openhab/openhab-addons

addons/binding/org.openhab.binding.squeezebox/META-INF/MANIFEST.MF, addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/handler/SqueezeBoxPlayerHandler.java, addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/SqueezeBoxHandlerFactory.java, addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/utils/HttpUtils.java
- Switch to ESH HttpUtil for downloading images
- Added cache for downloaded images
- Removed `com.google.common.collect` dependency
Closes #2989
=> [Squeezebox] Switch to ESH HttpUtil for downloading images

addons/binding/create_openhab_binding_skeleton.cmd, addons/binding/create_openhab_binding_skeleton.sh, addons/binding/create_openhab_binding_test_skeleton.cmd, addons/binding/create_openhab_binding_test_skeleton.sh
Change create_openhab_binding_skeleton from using version 0.9.0 to 0.10.0 of org.eclipse.smarthome.archetype.binding
The current scripts try to get 0.9.0 of org.eclipse.smarthome.archetype.binding. This version is not available as can be confirmed [here](https://repo.eclipse.org/content/repositories/smarthome-snapshots/org/eclipse/smarthome/archetype/org.eclipse.smarthome.archetype.binding/). I confirmed that with this change the .sh script was able to run successfully. Note that I did not test the changes to the .cmd files, but it should follow the same pattern as the changes to the .sh file.
=> Change create_openhab_binding_skeleton from using version 0.9.0 to 0.10.0 of org.eclipse.smarthome.archetype.binding

addons/binding/org.openhab.binding.cm11a/OSGI-INF/CM11AHandlerFactory.xml, addons/binding/org.openhab.binding.icloud/OSGI-INF/org.openhab.binding.icloud.internal.ICloudHandlerFactory.xml, addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/welcome/NAWelcomePersonHandler.java, addons/binding/org.openhab.binding.systeminfo/OSGI-INF/SysteminfoInterfaceService.xml
Fix license format for several files
Simple fix to the license headers so people can run `mvn license:format` without changing files outside of the scope of what they're developing. This is performing the fix on the other files that would get fixed up at the same time.
Signed-off-by: Tim Waterhouse <tim@timwaterhouse.com>
=> Fix license format for several files

addons/binding/org.openhab.binding.avmfritz/ESH-INF/thing/thing-types.xml
See https://community.openhab.org/t/avm-fritz-binding-dect-301-no-device-locked-channel-any-more/37976
=> [avmfritz] Added missing channel 'device_locked' to FRITZ!DECT 301

addons/binding/org.openhab.binding.chromecast/README.md
Add the full list of available Things and Channels to the documentation for the Chromecast binding. 
This change is to documentation only.
=> [chromecast] Complete list of available things and channels in README

addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/handler/SqueezeBoxPlayerHandler.java, addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/handler/SqueezeBoxServerHandler.java
On configurations with multiple squeezebox players (hardware) the mixer volume command needs to be handled to avoid timeouts during text-to-speech.
Signed-off-by: Patrik Gfeller <patrik.gfeller@gmail.com>
=> [SqueezeBox] Support for mixer volume command added

addons/binding/org.openhab.binding.netatmo/ESH-INF/config/config.xml, addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/ChannelTypeUtils.java
Closes #3032 
This solution works for the moment by using the system default timezone. The ESH framework provides a configuration for system independent timzone in the regional settings. Maybe we want to use that timezone for the calculation (see https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/i18n/TimeZoneProvider.java).
=> [Netatmo] Changed ZoneId from UTC to system default time

addons/binding/org.openhab.binding.keba/src/main/java/org/openhab/binding/keba/KebaBindingConstants.java
Short-term fix for https://github.com/openhab/openhab2-addons/issues/3070
(a more consistent solution would also require THING_TYPE_KECONTACTP20 to be renamed to THING_TYPE_KECONTACT, and an update of the README but this is part https://github.com/openhab/openhab2-addons/pull/2844)
=> Fix https://github.com/openhab/openhab2-addons/issues/3070

addons/binding/org.openhab.binding.avmfritz.test/src/test/java/org/openhab/binding/avmfritz/internal/ahamodel/AVMFritzModelTest.java, addons/binding/org.openhab.binding.avmfritz.test/src/test/java/org/openhab/binding/avmfritz/internal/discovery/AVMFritzDiscoveryServiceTest.java, addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/hardware/callbacks/FritzAhaDiscoveryCallback.java, addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/hardware/callbacks/FritzAhaUpdateXmlCallback.java, addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/util/JAXBUtils.java
Introduced in #2820
Unmarshaller class is not thread save (see https://javaee.github.io/jaxb-v2/doc/user-guide/ch03.html#other-miscellaneous-topics-performance-and-thread-safety). I ran into some NPEs afterwards.
```
2018-01-08 19:55:05.075 [ERROR] [.callbacks.FritzAhaUpdateXmlCallback] - Exception creating Unmarshaller: null
javax.xml.bind.UnmarshalException: null
at javax.xml.bind.helpers.AbstractUnmarshallerImpl.createUnmarshalException(AbstractUnmarshallerImpl.java:335) [?:?]
at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.createUnmarshalException(UnmarshallerImpl.java:563) [?:?]
at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:249) [?:?]
at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unm …
```
=> [avmfritz] Revert use of JAXB Unmarshaller as singleton instance to improve performance

addons/binding/org.openhab.binding.kodi/README.md
- `port` and `httpPort` are `Integer` values.
See https://community.openhab.org/t/kodi-binding-manual-setup-broken-since-update/38523
=> [kodi] Updated documentation to address comments in the community

addons/binding/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/lacrosse/DifferenceCheckingPublisher.java
Fixes the discarding of values that differ too much from the previous value.
Problem has been reported here:
https://community.openhab.org/t/jeelink-strange-behavior/38203/9
=> [jeelink] fix difference check

addons/binding/org.openhab.binding.exec/ESH-INF/i18n/exec_de.properties
As the exec binding had no (German) translation I created one.
As I couldn't find any script generating a translation template (which is as much work as the translation) for bindings without any translation I generated an XSLT file to start with.
[Thing Translation Template - DRAFT.zip](https://github.com/openhab/openhab2-addons/files/1604935/Thing.Translation.Template.-.DRAFT.zip)
=> [Translation] German translation for exec Binding

addons/binding/org.openhab.binding.bigassfan/src/main/java/org/openhab/binding/bigassfan/handler/BigAssFanHandler.java, addons/binding/org.openhab.binding.bigassfan/src/main/java/org/openhab/binding/bigassfan/internal/discovery/BigAssFanDiscoveryService.java, addons/binding/org.openhab.binding.globalcache/src/main/java/org/openhab/binding/globalcache/internal/discovery/GlobalCacheDiscoveryService.java
It appears [this ](https://github.com/openhab/openhab2-addons/commit/52f768a3f8f80ac30d98dfb286bac134116baf99#diff-20d869adac9ab48b4a6bfc46a34d68ae)commit broke discovery for these two bindings. Reference discussion on [this issue](https://github.com/eclipse/smarthome/issues/4751#issuecomment-358416890). The fix is to change the DS annotation for the discovery service.
In addition, remove the use of ExtendedDiscoveryService. This was originally used to avoid spamming openhab.log with "Thing already exists" messages from the framework every time a device sent a discovery packet for an existing thing; however, those messages are no longer at INFO level.
Finally, in the BigAssFan handler, catch BufferOverflowException generated by Scanner.next. …
=> [globalcache/bigassfan] Fix discovery due to previous commit

addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/SqueezeBoxBindingConstants.java, addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/handler/SqueezeBoxNotificationListener.java, addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/handler/SqueezeBoxNotificationPlayer.java, addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/handler/SqueezeBoxPlayer.java, addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/handler/SqueezeBoxPlayerEventListener.java, addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/handler/SqueezeBoxPlayerHandler.java, addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/handler/SqueezeBoxPlayerState.java, addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/handler/SqueezeBoxServerHandler.java, addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/SqueezeBoxAudioSink.java, addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/SqueezeBoxHandlerFactory.java, addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/config/SqueezeBoxPlayerConfig.java, addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/config/SqueezeBoxServerConfig.java, addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/discovery/SqueezeBoxPlayerDiscoveryParticipant.java, addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/discovery/SqueezeBoxServerDiscoveryParticipant.java, addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/utils/HttpUtils.java, addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/utils/SqueezeBoxNotAuthorizedException.java, addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/utils/SqueezeBoxTimeoutException.java
Utility class "SqueezeBoxNotificationPlayer" added and "SqueezeBoxPlayerState" moved to its own file to reduce complexity and length of SqueezeBoxPlayerHandler.java
Signed-off-by: Patrik Gfeller <patrik.gfeller@gmail.com>
=> [SqueezeBox] Refactoring to simplify player handler code, also solves issue #3080

addons/binding/org.openhab.binding.bigassfan/README.md, addons/binding/org.openhab.binding.bigassfan/src/main/java/org/openhab/binding/bigassfan/internal/discovery/BigAssFanDiscoveryService.java, addons/binding/org.openhab.binding.globalcache/README.md, addons/binding/org.openhab.binding.globalcache/src/main/java/org/openhab/binding/globalcache/internal/discovery/GlobalCacheDiscoveryService.java
This [ESH PR](https://github.com/eclipse/smarthome/pull/4079) broke the ability to configure (enable/disable) background discovery for globalcache and bigassfan bindings.
This PR fixes the problem based on the information in [this discussion](https://github.com/eclipse/smarthome/pull/4079#issuecomment-358981113).
=> [globalcache/bigassfan] Fix configurability of background discovery

addons/binding/org.openhab.binding.mcp23017/README.md
A7 and B7 channels were missing in Readme
They are listed in `Mcp23017BindingConstants.java`
@aogorek please take a look.
=> [MCP23017]Added missing channels in  README

addons/binding/org.openhab.binding.homematic/META-INF/MANIFEST.MF, addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/HomematicBindingConstants.java, addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/handler/HomematicThingHandler.java, addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/AbstractHomematicGateway.java, addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/CcuGateway.java, addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/HomematicGateway.java, addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/client/RpcClient.java, addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/parser/DisplayOptionsParser.java, addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/parser/ListDevicesParser.java, addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/model/HmChannel.java, addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/model/HmDevice.java, addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/type/HomematicTypeGeneratorImpl.java
HM-MOD-EM-8 devices have reconfigurable channels, whose data point set (and thus set of available thing channels) varies depending on what type the channel is configured to. For such devices, put the list of available channel types not in the ThingType, but assign it to each Thing when initializing it.
=> [homematic] Dynamically assign reconfigurable channels

addons/binding/org.openhab.binding.kodi/README.md
Clarified that there have to be two different settings.
Corresponding discussion -> https://community.openhab.org/t/kodi-wont-change-to-online/39261
Signed-off-by: Jerome Luckenbach <github@luckenba.ch>
=> [Kodi] Updated readme - preparation section

AUTHORS, addons/binding/org.openhab.binding.homematic/META-INF/MANIFEST.MF, addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/message/BinRpcMessage.java
Improvement: Refactored the only line in the homematic binding that made use of the org.apache.commons.io library. As a result, the dependency on that library was removed.
Closes #3193
=> [Homematic] Remove the dependency to org.apache.commons.io

AUTHORS, addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/CcuGateway.java
Bugfix: In the CcuGateway class of the Homematic Binding, an XML resource was
loaded using the class loader provided by the thread. Now, the resource
is directly loaded via the bundle to avoid using the wrong class loader.
Closes #3195
=> [Homematic] Load resource via bundle

addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/message/BinRpcMessage.java
In the class BinRpcMessage, while reading the message content from the InputStream, `read()` was only called once. This call might not acquire the whole message.
Now, it is called repeatedly until no more content is available. If the amount read from the stream is smaller than expected, an EOFException is thrown.
This behavior is also much closer to the implementation of `toByteArray()`, which was used to read the stream into an array before the refactoring.
Improves on #3194
=> Improve safety of refactored operation from #3194

addons/binding/org.openhab.binding.feed.test/pom.xml, addons/binding/org.openhab.binding.feed.test/src/test/groovy/org/openhab/binding/feed/test/FeedHandlerTest.groovy
=> removed additional repo for Jetty dependencies and temporarily disabled tests

addons/binding/org.openhab.binding.nest/README.md, addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/handler/NestBridgeHandler.java
Sets the Thing status of deleted devices and structures to offline/gone.
See also https://github.com/eclipse/smarthome/issues/3306.
=> [Nest] Handle deletion of devices and structures from account

addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/handler/HomematicBridgeHandler.java
Improvement:
The `HomematicBridgeHandler` retrieves information about a bridge's firmware, model and serial number during initialization. Currently, these properties are stored in a private field of the handler of type `HomematicConfig`. These properties, however, could also be provided as `thingProperties` in the bridge thing.
Users will now be able to access the firmware, model and serial number of a homematic bridge from the bridge thing after initialization. Moreover, if the bridge thing has already configured values for any of these properties, they will **not** be overwritten. This should prevent any undesired changes in existing systems that already make use of these specific properties.
The decision to map `PROPERTY_SERIAL_NUMBER` to `info.getAddress()` comes from the …
=> [homematic] Add properties to a homematic bridge during initialization

addons/binding/org.openhab.binding.lgwebos/ESH-INF/binding/binding.xml, addons/binding/org.openhab.binding.lgwebos/META-INF/MANIFEST.MF, addons/binding/org.openhab.binding.lgwebos/README.md, addons/binding/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/discovery/LGWebOSDiscovery.java
Adding back LocalIP Binding Property
Reintroducing the ability to set the IP address to bind to. It used to exist in the binding until we switched to using NetworkAddressService. Multiple users have found that it would be advantageous to bring this feature back. It allows to override what is configured as primary network interface. This is required in situations when users segregate networks into multiple zones.
=> [LGWebOS] LocalIP Binding Property

addons/binding/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/protocol/KodiConnection.java
The `label` property is always present whereas the `title` property is only returned for media in your library.
Closes #3265 
=> [Kodi] Use 'label' property if 'title' property is not present

addons/binding/org.openhab.binding.icloud/README.md
This PR improves the full example included with the iCloud binding.
It adds a sitemap with a pushbutton and a map view. A simple rule is included to use the binding for presence detection.
This is a new attempt, since I messed up #3226.
cc @kaikreuzer @martinvw @hmerk
=> Improve and extend iCloud binding example

addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/type/HomematicTypeGeneratorImpl.java
Our application evaluates any thing's ConfigDescriptions to decorate the thing with application-specific functionality. Therefore I suggest that the binding creates ConfigDescrition for each created
ThingType, even if it does not contain any parameter.
Closes #3277 
Signed-off-by: Michael Reitler <github@madpage.de>
=> [homematic] Provide config-descriptions for every config-description-URI

addons/binding/org.openhab.binding.tankerkoenig/README.md
Updated FAQ with a more in depth explanation on how to load missing certificates!  
On that topic my personell knowledge is rather limited. Community member @Andreh_T suggested this change in this thread (https://community.openhab.org/t/new-oh2-binding-tankerkoenig/20289/112).
Signed-off-by: Juergen Baginski opus42@gmx.de (github: JueBag)
=> [Tankerkoenig] Updated FAQ 

addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/handler/NetatmoBridgeHandler.java, addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/handler/NetatmoDeviceHandler.java, addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/handler/NetatmoModuleHandler.java, addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/handler/TrustingOkHttpClient.java
We currently see the complete stack trace in case of an error.
```
2018-02-28 09:42:02.964 [ERROR] [netatmo.handler.NetatmoDeviceHandler] - Unable to connect Netatmo API : 502 Bad Gateway
retrofit.RetrofitError: 502 Bad Gateway
at retrofit.RetrofitError.httpError(RetrofitError.java:40) ~[?:?]
at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388) ~[?:?]
at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240) ~[?:?]
at com.sun.proxy.$Proxy182.getstationsdata(Unknown Source) ~[?:?]
at org.openhab.binding.netatmo.handler.NetatmoBridgeHandler.getStationsDataBody(NetatmoBridgeHandler.java:231) ~[?:?]
at org.openhab.binding.netatmo.internal.station.NAMainHandler.updateReadings(NAMainHandler.java:42) ~[?:?]
at org.openhab.binding.netatmo.internal.station.NAMainHandler.up …
```
=> [Netatmo] Handle errors more gracefully

addons/binding/org.openhab.binding.bigassfan/ESH-INF/config/config.xml, addons/binding/org.openhab.binding.bigassfan/ESH-INF/thing/thing-types.xml, addons/binding/org.openhab.binding.bigassfan/README.md, addons/binding/org.openhab.binding.bigassfan/pom.xml, addons/binding/org.openhab.binding.bigassfan/src/main/java/org/openhab/binding/bigassfan/BigAssFanBindingConstants.java, addons/binding/org.openhab.binding.bigassfan/src/main/java/org/openhab/binding/bigassfan/handler/BigAssFanHandler.java, addons/binding/org.openhab.binding.bigassfan/src/main/java/org/openhab/binding/bigassfan/internal/BigAssFanConfig.java, addons/binding/org.openhab.binding.bigassfan/src/main/java/org/openhab/binding/bigassfan/internal/discovery/BigAssFanDevice.java, addons/binding/org.openhab.binding.bigassfan/src/main/java/org/openhab/binding/bigassfan/internal/discovery/BigAssFanDiscoveryService.java, addons/binding/org.openhab.binding.bigassfan/src/main/java/org/openhab/binding/bigassfan/internal/utils/BigAssFanConverter.java
- Add support for standalone lights, including ON/OFF, brightness level, and color temperature. See community discussion [here](https://community.openhab.org/t/haiku-light-with-bigassfan-binding/41226/3).
- Refactor config parameters into separate config.xml.
- Fix issues from code analysis
=> [bigassfan] Add support for standalone lights

addons/binding/org.openhab.binding.yamahareceiver/ESH-INF/thing/thing-types.xml, addons/binding/org.openhab.binding.yamahareceiver/README.md, addons/binding/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/YamahaReceiverBindingConstants.java, addons/binding/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/handler/YamahaZoneThingHandler.java, addons/binding/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/protocol/ZoneControl.java, addons/binding/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/protocol/xml/ZoneControlXML.java, addons/binding/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/state/ZoneControlState.java
Adds item `dialogueLevel` to the Yamaha AVR binding.
It allows to adjust the volume of voice independent of master volume.
=> [yamaha] add dialogue level item

addons/binding/org.openhab.binding.feed.test/pom.xml, addons/binding/org.openhab.binding.hdpowerview/pom.xml, addons/binding/org.openhab.binding.knx.test/pom.xml, addons/binding/org.openhab.binding.max.test/pom.xml, addons/binding/org.openhab.binding.rfxcom.test/pom.xml, addons/binding/org.openhab.binding.systeminfo.test/pom.xml
* Replace `org.eclipse.tycho` with `${tycho-groupid}` where applicable
* Remove `${tycho-version}` from plugins that is managed by parent POM
* Remove unnecessary tycho pluginManagement section from hdpowerview POM
This should also fix the following warning:
```
[WARNING] Some problems were encountered while building the effective model for org.openhab.binding:org.openhab.binding.knx.test:eclipse-test-plugin:2.3.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.eclipse.tycho:target-platform-configuration is missing. @ org.openhab.binding:org.openhab.binding.knx.test:[unknown-version], /home/wouter/git/openhab/openhab2-addons/addons/binding/org.openhab.binding.knx.test/pom.xml, line 19, column 12
[WARNING] 'build.plugins.plugin.version' for org.eclipse.tycho:tycho-surefire-plugin …
```
=> Tycho POM improvements

addons/binding/org.openhab.binding.rfxcom/README.md
=> [rfxcom] Doc fix - heading was incorrect for Lighting1 section

addons/binding/org.openhab.binding.chromecast/META-INF/MANIFEST.MF
* the "org.jupnp.model.*" packages seem to be a leftover from #1477
* the "com.fasterxml.jackson.annotation" does not make any sense to me
as neither the binding code needs it nor does any of the included
dependencies import it in their manifests.
Signed-off-by: Simon Kaufmann <simon.kfm@googlemail.com>
=> [Chromecast] cleanup manifest

addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/client/XmlRpcClient.java
Previously, httpClient.destroy() was called during disposal of the
XmlRpcClient. This e.g. does not stop the threads created by the jetty
client. Now, httpClient.stop() is called.
In other places in the binding, e.g. the `CCUGateway` class, this call was already used to correctly dispose of the jetty client.
Contributes to fixing #3388
Signed-off-by: Florian Stolte <fstolte@gmx.de>
=> [Homematic] Properly stop JettyClient when XmlRpcClient is disposed

addons/binding/org.openhab.binding.coolmasternet/ESH-INF/thing/thing-types.xml, addons/binding/org.openhab.binding.coolmasternet/META-INF/MANIFEST.MF, addons/binding/org.openhab.binding.coolmasternet/README.md, addons/binding/org.openhab.binding.coolmasternet/src/main/java/org/openhab/binding/coolmasternet/CoolMasterNetBindingConstants.java, addons/binding/org.openhab.binding.coolmasternet/src/main/java/org/openhab/binding/coolmasternet/handler/HVACHandler.java, addons/binding/org.openhab.binding.coolmasternet/src/main/java/org/openhab/binding/coolmasternet/internal/CoolMasterNetHandlerFactory.java
* Rename fan channel to fan_speed so it is inline with documentation and the binding will also handle commands
* Update documentation so available states are listed
* Remove Guava dependency
---
@dirkypower I don't use this binding myself but I think this PR should fix the issue your reported in this [community post](https://community.openhab.org/t/coolmasternet-binding-fan-speed-not-working/40821?u=wborn). 
Can you test if this fixes your issue when you use this [org.openhab.binding.coolmasternet-2.3.0-SNAPSHOT.jar](http://www.maindrain.net/iot-marketplace/org.openhab.binding.coolmasternet-2.3.0-SNAPSHOT.jar) with OH 2.3.0-SNAPSHOT? You might need to remove and re-add the HVAC Thing so you have a `fan_speed` instead of a `fan` channel.
I've also updated the [binding …
=> [CoolMasterNet] Fix fan speed commands not working

features/openhab-addons/src/main/feature/feature.xml
=> correctly declare dependency to UPnP in Kodi binding

addons/binding/org.openhab.binding.lgwebos/README.md
ThingID is no longer made up by IP address. It uses a Unique ID provided by the TV, which remains constant. This was incorrectly described in the Readme file.
Signed-off-by: Sebastian Prehn <sebastian.prehn@gmx.de> (github: sprehn)
=> [lgwebos] Correction in Readme file

addons/binding/org.openhab.binding.avmfritz/META-INF/MANIFEST.MF, addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/handler/BoxHandler.java, addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/handler/DeviceHandler.java, addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/HandlerFactory.java, addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/hardware/FritzahaWebInterface.java
- Switched to shared instance of `HttpClient` using `HttpClientFactory`
- Removed deprecated usage of the constructor `DateTimeType(Calendar)`
- Minor code cleanups to fix sat findings
=> [avmfritz] Switched to shared instance of HttpClient

addons/binding/org.openhab.binding.homematic/ESH-INF/thing/bridge.xml, addons/binding/org.openhab.binding.homematic/README.md, addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/HomematicBindingConstants.java, addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/handler/HomematicBridgeHandler.java, addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/common/HomematicConfig.java, addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/AbstractHomematicGateway.java, addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/HomematicGateway.java, addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/client/RpcClient.java, addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/discovery/HomematicDeviceDiscoveryService.java
Whenever the bindings DiscoveryService is started, the controller is set to install_mode==true for a well defined time period. During that time it accepts pairing of new devices. Since the RPC call for
enabling the install_mode is well documented, this can be achieved without using GATEWAY_EXTRAS. Henceforth it is optional to use GATEWAY_EXTRAS, since the most important function of this thing is
implicitely available on the DiscoveryService. For convenience desired duration may be specified on the homematic:bridge.
To be backwarts compatible with GATEWAY_EXTRAS the virtual datapoints are utilized. So in setups using GATEWAY_EXTRAS you will also see applications of install mode and duration on this thing.
Closes: #3330 
Signed-off-by: Michael Reitler <github@madpage.de>
=> [homematic] Put controller into install_mode on DiscoveryService#start()

addons/binding/org.openhab.binding.knx/ESH-INF/thing/device.xml
changed  label and item-type  in XML
=> [KNX] fix XML for number-control and string-control

addons/binding/org.openhab.binding.innogysmarthome/src/main/java/org/openhab/binding/innogysmarthome/InnogyBindingConstants.java
Signed-off-by: Oliver Kuhl oliver.kuhl@gmail.com (github: ollie-dev)
Fixed the new innogy oauth redirect URLs. 
Important to mention: today there are still the old URLs active on the innogy backend, so that creating the auth code fails until the new ones are activated. I expect this to happen in the next days.
=> Fixed oauth redirect URLs

addons/binding/org.openhab.binding.lgwebos/ESH-INF/binding/binding.xml, addons/binding/org.openhab.binding.lgwebos/ESH-INF/config/config.xml, addons/binding/org.openhab.binding.lgwebos/ESH-INF/thing/thing-types.xml, addons/binding/org.openhab.binding.lgwebos/README.md, addons/binding/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/LGWebOSBindingConstants.java, addons/binding/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/handler/LGWebOSHandler.java, addons/binding/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/LGWebOSHandlerFactory.java, addons/binding/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/discovery/LGWebOSDiscovery.java
This allows users to choose their own ThingIDs if they wish.
This addresses issue #3403
=> [lgwebos] Store deviceId in Thing Configuration instead of deriving it from ThingID

addons/binding/org.openhab.binding.squeezebox/ESH-INF/thing/thing-types.xml, addons/binding/org.openhab.binding.squeezebox/README.md, addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/SqueezeBoxBindingConstants.java, addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/handler/SqueezeBoxNotificationPlayer.java, addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/handler/SqueezeBoxPlayerHandler.java, addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/handler/SqueezeBoxServerHandler.java, addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/config/SqueezeBoxPlayerConfig.java, addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/discovery/SqueezeBoxPlayerDiscoveryParticipant.java, addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/discovery/SqueezeBoxServerDiscoveryParticipant.java, addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/utils/HttpUtils.java, addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/utils/SqueezeBoxCommunicationException.java
Removes `notificationSoundVolume` channel and replaces it with a configuration parameter on the Player thing. This maintains consistency with pending changes to Sonos, as well as supports the modifications to audio actions where the volume can be specified as part of the audio and voice APIs.
Also adds a `notificationTimeout` config parameter on the Player thing to provide greater user control over notification duration, as well as to maintain consistency with Sonos notification functionality.
Depends on next stable ESH containing this PR .
https://github.com/eclipse/smarthome/pull/4963
Also
- Rework HttpUtils to not throw Exception in order to resolve build failure due to code analysis error
- Rework Notification Player to consolidate code …
=> [squeezebox] Remove notification volume channel and replace with config property

addons/binding/pom.xml, features/openhab-addons/src/main/feature/feature.xml
This is a temporary measure until we have a solution for https://github.com/openhab/openhab2-addons/issues/3402. To be added again before the 2.3 release!
=> temporarily remove the ZWay binding

addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/handler/XiaomiBridgeHandler.java, addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/handler/XiaomiDeviceBaseHandler.java
add cyclic thing status check (fix #3342) 
- check if the device did not report for more than 2 hours (normally every device sends a heartbeat every 60 mins)
fix NPE mentioned in #3384
- if no token was received from the gateway yet (for example due to network issues) warn the user and suppress an NPE
=> [mihome] add cyclic thing status check (fix #3342) & fix NPE mentioned in #3384

addons/binding/create_openhab_binding_skeleton.cmd, addons/binding/create_openhab_binding_skeleton.sh, addons/binding/create_openhab_binding_test_skeleton.cmd, addons/binding/create_openhab_binding_test_skeleton.sh
- Removed required `BindingIdInLowerCase` argument in *.cmd scripts
- Added required `Author` in all scripts
- Added variables for binding and archetype version in all scripts
Preparations for closing openhab/openhab-docs#482
Can anyone please test the *.cmd scripts? Thank you in advance.
=> Adjusted skeleton scripts to be compliant with ESH versions

addons/binding/org.openhab.binding.feed.test/src/test/java/org/openhab/binding/feed/test/FeedHandlerTest.java, addons/binding/org.openhab.binding.feed/src/main/java/org/openhab/binding/feed/handler/FeedHandler.java
* Start refresh after updating Thing status to UNKNOWN so last status is always the refresh result
* Increase waitForAssert timeout because it sometimes takes more than 10s before the UnknownHostException occurs in the createThingWithInvalidUrlHostname test
=> [Feed] Fix tests sometimes failing

addons/binding/org.openhab.binding.harmonyhub/src/main/java/org/openhab/binding/harmonyhub/handler/HarmonyHubHandler.java
Currently, you'll find an error with full stacktrace in the log if you try to start an unknown activity:
```
2018-04-09 19:27:35.752 [ERROR] [harmonyhub.handler.HarmonyHubHandler] - Could not start activity
java.lang.IllegalArgumentException: Unknown activity 'ABC'
at net.whistlingfish.harmony.HarmonyClient.startActivityByName(HarmonyClient.java:431) [216:org.openhab.binding.harmonyhub:2.3.0.201803230940]
at org.openhab.binding.harmonyhub.handler.HarmonyHubHandler.handleCommand(HarmonyHubHandler.java:114) [216:org.openhab.binding.harmonyhub:2.3.0.201803230940]
at sun.reflect.GeneratedMethodAccessor96.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
at …
```
=> provide proper logging message for unknown activity

addons/binding/org.openhab.binding.feed.test/.settings/org.eclipse.jdt.groovy.core.prefs, addons/binding/org.openhab.binding.max.test/.groovy/suggestions.xdsl, addons/binding/org.openhab.binding.max.test/.settings/org.eclipse.jdt.groovy.core.prefs, addons/binding/org.openhab.binding.nibeheatpump.test/.project, addons/binding/org.openhab.binding.nibeheatpump.test/.settings/org.eclipse.jdt.groovy.core.prefs, addons/binding/org.openhab.binding.rfxcom.test/.classpath, addons/binding/org.openhab.binding.rfxcom.test/.project, addons/binding/org.openhab.binding.systeminfo.test/.settings/org.eclipse.jdt.groovy.core.prefs
These files and settings are unused because all Groovy tests have been migrated to Java.
=> Remove unused Groovy settings and natures from Eclipse projects

addons/binding/org.openhab.binding.homematic/META-INF/MANIFEST.MF, addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/handler/HomematicBridgeHandler.java, addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/handler/HomematicThingHandlerFactory.java, addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/AbstractHomematicGateway.java, addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/CcuGateway.java, addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/DefaultGateway.java, addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/HomegearGateway.java, addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/HomematicGatewayFactory.java, addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/client/XmlRpcClient.java
Improvement/Bugfix:
The HttpClientFactory provides a common jetty http client for all
bundles. The homematic binding now uses this shared client.
This not only reduces the binding's memory footprint, but also gets rid
of some problems during the disposal of http clients.
Impact: The connection timeout of the client can no longer be customized since the shared client must not be modified by calling setter methods.
Fixes #3388
Signed-off-by: Florian Stolte <fstolte@gmx.de>
=> [homematic] Introduce the HttpClientFactory to the homematic binding

addons/binding/org.openhab.binding.innogysmarthome/.classpath
Small fix by removing the local source path for a used library. Refers to #3227.
Signed-off-by: Oliver Kuhl oliver.kuhl@gmail.com (github: ollie-dev)
=> [innogy] Removed local source path

addons/binding/org.openhab.binding.lgwebos/README.md
User @tjakobi reported this bug in the binding's documentation.
=> [lgwebos] Removed outdated items from demo site map.

addons/binding/org.openhab.binding.avmfritz/ESH-INF/thing/channel-types.xml, addons/binding/org.openhab.binding.avmfritz/README.md
- Ensured backward compatibility like suggested in https://github.com/openhab/openhab2-addons/pull/3477#issuecomment-381575982
- Fixed example in `README.md`
I deleted my comment about it in the release notes: https://github.com/openhab/openhab-distro/wiki/%5BDRAFT%5D-openHAB-2.3-Release-Notes.
=> [avmfritz] Ensured backward compatibility

addons/binding/org.openhab.binding.nest.test/src/test/java/org/openhab/binding/nest/internal/data/GsonParsingTest.java, addons/binding/org.openhab.binding.nest.test/src/test/java/org/openhab/binding/nest/internal/data/NestDataUtil.java, addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/handler/NestBridgeHandler.java, addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/handler/NestStructureHandler.java, addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/handler/NestThermostatHandler.java, addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/NestUtils.java, addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/data/AccessTokenData.java, addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/data/BaseNestDevice.java, addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/data/Camera.java, addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/data/ErrorData.java, addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/data/NestDevices.java, addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/data/NestMetadata.java, addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/data/SmokeDetector.java, addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/data/Structure.java, addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/data/Thermostat.java, addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/data/TopLevelData.java, addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/data/TopLevelStreamingData.java, addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/rest/NestAuthorizer.java, addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/rest/NestStreamingRestClient.java
* Use Gson with `FieldNamingPolicy.LOWER_CASE_WITH_UNDERSCORES`
* Remove `@SerializedName` annotations from data objects where applicable
* Reuse Gson instance with NestUtils
* Simplify date time comparisons in GsonParsingTest
=> [Nest] Use FieldNamingPolicy to reduce Gson annotations

addons/binding/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/utils/NetworkUtils.java
See #3499 for details of the problem being addressed.  This is the minimal fix.  If you would like me to add a new property to control the interpretation of this exception, let me know and I can do that.
I was unable to add a unit test via mocking since servicePing currently creates a Socket directly rather than using a factory.
I tested manually via mvn clean install and then deploying the updated addon into my test OpenHab server and verifying the correct behavior with a test service.
Fixes #3499
Signed-off-by: John Sichi <jsichi@gmail.com> (github: jsichi)
=> [network] Interpret ConnectException as service absent rather than present.

addons/binding/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/PresenceDetection.java
The given port is not logged because there's a typo in the variable.
It should be the variable name tcpPort instead of tcpPorts.
=> Typo in logging

addons/io/org.openhab.io.homekit/README.md, addons/io/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitSettings.java
Name of the homekit bridge as announced in the network can be changed
from default "openHAB" to any valid name by setting the parameter "name"
Signed-off-by: Metin Savignano <ms@savignano.net> (github: cubistico)
[homekit] MAKE BRIDGE NAME CONFIGURABLE
Make name of the homekit bridge as announced in the network configurable
from default "openHAB" to any valid name by setting the parameter "name", 
as requested in issue #1946 
This is helpful, if you have more than one openHAB running.
=> [homekit] Make bridge name configurable

addons/binding/org.openhab.binding.zway/ESH-INF/binding/binding.xml, addons/binding/org.openhab.binding.zway/ESH-INF/config/bridge-config.xml, addons/binding/org.openhab.binding.zway/ESH-INF/i18n/zway.properties, addons/binding/org.openhab.binding.zway/ESH-INF/i18n/zway_de.properties, addons/binding/org.openhab.binding.zway/README.md, addons/binding/org.openhab.binding.zway/doc/GETTING_STARTED.md, addons/binding/org.openhab.binding.zway/src/main/java/org/openhab/binding/zway/ZWayBindingConstants.java, addons/binding/org.openhab.binding.zway/src/main/java/org/openhab/binding/zway/handler/ZWayBridgeHandler.java, addons/binding/org.openhab.binding.zway/src/main/java/org/openhab/binding/zway/handler/ZWayDeviceHandler.java, addons/binding/org.openhab.binding.zway/src/main/java/org/openhab/binding/zway/internal/config/ZWayBridgeConfiguration.java, addons/binding/pom.xml, features/openhab-addons/src/main/feature/feature.xml
To eliminate the link registry dependency, the bbserver mechanism must be removed.
Initially, this PR is used to reactivate the binding. In a following PR, an update is implemented by WebSockets.
Signed-off-by: Patrick Hecker <pah111kg@fh-zwickau.de> (github: pathec)
=> Remove observer mechanism

addons/binding/org.openhab.binding.irtrans/META-INF/MANIFEST.MF, addons/binding/org.openhab.binding.irtrans/src/main/java/org/openhab/binding/irtrans/IRtransBindingConstants.java, addons/binding/org.openhab.binding.irtrans/src/main/java/org/openhab/binding/irtrans/handler/EthernetBridgeHandler.java
I am clueless as to why the binding worked previously; Maybe something else was fixed which caused this obvious error to pop-up. I never noticed this as the code base was >2 years old
=> [irtrans] Fix ChannelTypeUID usage in handleCommand()

addons/binding/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/utils/NetworkUtils.java
Related to #3502.
Fixes the problem described in [this community thread](https://community.openhab.org/t/windows-ping-does-not-work-correct/43776/24) where Windows pings from the Network binding to hosts on the local subnet are incorrectly parsed, leading to unreachable hosts being flagged as reachable.
This is the [test jar](https://drive.google.com/open?id=17CLqpE7mWSLggY8rtMW3SNNzkyiJDon5).
=> [Network] Fix the windows ping problem for local subnets.

addons/binding/org.openhab.binding.avmfritz/ESH-INF/thing/channel-types.xml
- Removed min/max/step attributes for `set_temp` channel. They are currently not predictable.
=> [avmfritz] Removed min/max/step attributes for set_temp channel

addons/binding/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/config/GardenaConfig.java
Removed transient from GardenaConfig. With transient the account configuration is not applied.
=> [gardena] Fixed Gardena account configuration

addons/io/org.openhab.io.azureiothub/pom.xml, addons/io/org.openhab.io.homekit/pom.xml, addons/io/org.openhab.io.hueemulation/pom.xml, addons/io/org.openhab.io.imperihome/pom.xml, addons/io/org.openhab.io.openhabcloud/pom.xml, addons/io/org.openhab.io.transport.feed/pom.xml, addons/io/pom.xml, addons/voice/org.openhab.voice.kaldi/pom.xml, addons/voice/org.openhab.voice.marytts/pom.xml, addons/voice/org.openhab.voice.voicerss/pom.xml, addons/voice/pom.xml
Fixes issue reported in https://github.com/openhab/openhab2-addons/pull/3464#issuecomment-386813984
=> removed "addons" from group id of artifacts

addons/binding/org.openhab.binding.homematic/ESH-INF/thing/bridge.xml, addons/binding/org.openhab.binding.homematic/README.md, addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/handler/HomematicBridgeHandler.java, addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/handler/HomematicThingHandler.java, addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/common/HomematicConfig.java, addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/AbstractHomematicGateway.java, addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/HomematicGateway.java
Solves issue #3510
This PR tries to make the deletion of homematic things in combination with the unpairing of devices from their gateway more comfortable.
The first problem addressed by this PR is that the thing status does not properly communicate whether a device has been deleted from the bridge or if it is otherwise unreachable. To fix this, we can react on the "deleteDevices" call from the homematic gateway. If a thing exists for a device that is being deleted from the gateway, we can set it to the state "OFFLINE - GONE". This signifies that the thing can be deleted. If the device should be paired to the gateway again before the thing is deleted, the thing will come back "ONLINE" again.
The second problem addressed by this PR is that unpairing a device from the gateway and deleting a …
=> [homematic] Support thing status "OFFLINE - GONE" and add auto-delete option

addons/binding/org.openhab.binding.mcp23017/README.md, addons/binding/org.openhab.binding.mcp23017/src/main/java/org/openhab/binding/mcp23017/handler/Mcp23017Handler.java
Signed-off-by: Igor Arenz <igor.arenz@ia-it.de>
I want to be able to use the pull_mode PULL_UP at input-pins of a MCP23017-Binding. 
I need over a week with analysing xtext-files and debugging Java-Code and a lot of help of the community (Thank you, Udo! -> https://community.openhab.org/t/mcp23017-binding-items-file-configuration-additional-parameters/44603/12) to get a working configuration.
After I get a correct configuration, I found out, that the pull_mode-configuration is not working as expected. 
I do a oneliner-fix in the MCP23017Handler and improve the doc. 
If there is anything wrong with my pull-request, please give me a hint. Its my first one on openhab
Thank you,
Igor Arenz
=> [MCP23017] channel config "pull_mode=PULL_UP" not working

pom.xml
The `esh.releaseVersion` property became obsolete after PR #3406.
=> Remove obsolete esh.releaseVersion property

addons/binding/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/utils/NetworkUtils.java
Thomas Habets arping required "-i" instead of "-I", at least in the latest (2017) 2.19 version.
Fixes #3539
=> Network binding arping fix

addons/binding/org.openhab.binding.nikohomecontrol/ESH-INF/thing/thing-types.xml, addons/binding/org.openhab.binding.nikohomecontrol/META-INF/MANIFEST.MF, addons/binding/org.openhab.binding.nikohomecontrol/README.md, addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/NikoHomeControlBindingConstants.java, addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/handler/NikoHomeControlBridgeHandler.java, addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/handler/NikoHomeControlHandler.java, addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/NikoHomeControlHandlerFactory.java, addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/discovery/NikoHomeControlBridgeDiscoveryService.java, addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/discovery/NikoHomeControlDiscoveryService.java, addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/NhcAction.java, addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/NhcLocation.java, addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/NhcMessageBase.java, addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/NhcMessageCmd.java, addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/NhcMessageListMap.java, addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/NhcMessageMap.java, addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/NhcSystemInfo.java, addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/NikoHomeControlCommunication.java, addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/NikoHomeControlDiscover.java, addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/NikoHomeControlMessageDeserializer.java
Previous implementation only mirrors native Niko Home Control app functionality for rollershutters, i.e. up/down/stop. PercentType commands were send as up or down. This PR adds a stop calculated based on current position and total time to open/close for PercentType commands.
An invert flag is also introduced to allow the open/close positions and direction to be switched.
=> [nikohomecontrol] Improvement of rollershutter PercentType implementation.

pom.xml
This PR requires https://github.com/openhab/openhab-core/pull/341 to be merged first.
=> removing ESH p2 repo references

addons/binding/org.openhab.binding.silvercrestwifisocket/README.md
Fixes #3571
For the available vendor options see also [thing-types.xml](https://github.com/openhab/openhab2-addons/blob/02182028b86fc8d042ea4d27021f39b526d270b2/addons/binding/org.openhab.binding.silvercrestwifisocket/ESH-INF/thing/thing-types.xml#L34).
=> [Silvercrest] Capitalize vendor values in documentation

addons/binding/org.openhab.binding.avmfritz.test/src/test/java/org/openhab/binding/avmfritz/internal/discovery/AVMFritzDiscoveryServiceTest.java, addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/handler/AVMFritzBaseBridgeHandler.java, addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/handler/AVMFritzBaseThingHandler.java, addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/handler/Powerline546EHandler.java, addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/hardware/callbacks/FritzAhaUpdateXmlCallback.java
- Refactored handler to use AIN for updating things instead of deriving it from the ThingID
- Added handling for deleted devices and structures from FRITZ!OS
This allows users to choose their own ThingIDs if they wish. Addresses issue #1963.
This allows users to add things manually if the discovery doesn't work (e.g. old firmware for FRITZ!Box). See https://community.openhab.org/t/avm-fritz-dect210-not-detected/45474.
Test version: [org.openhab.binding.avmfritz-2.4.0-SNAPSHOT.jar.zip](https://github.com/openhab/openhab2-addons/files/2045510/org.openhab.binding.avmfritz-2.4.0-SNAPSHOT.jar.zip)
=> [avmfritz] Refactored handler to use AIN for updating things instead of deriving it from the ThingID

addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/AbstractHomematicGateway.java, addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/server/BinRpcNetworkService.java, addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/server/XmlRpcServer.java
Open Server on host specified in the property "callbackHost" instead of opening it without specification. This will prevent conflicts on machines which provide multiple network interfaces.
Further improvements for stability of the communication between binding and gateway:
* Improved error logging of ConnectionTrackerThread
* Synchronized AbstractHomematicGateway's start/stopServers to prevent starting of new servers while previous operation is still blocking
Signed-off-by: Michael Reitler <michael.reitler@telekom.de>
=> [homematic] Reduce Bin/XmlRpcServer to specified callback host address

addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/handler/AVMFritzBaseBridgeHandler.java, addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/handler/AVMFritzBaseThingHandler.java, addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/handler/Powerline546EHandler.java, addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/hardware/FritzAhaWebInterface.java, addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/hardware/callbacks/FritzAhaUpdateXmlCallback.java
- Fixed and streamlined thing status handling (not set the status on the Thing directly to benefit from callback trigger e.g. for DSL rules)
=> [avmfritz] Fixed and streamlined thing status handling

addons/binding/org.openhab.binding.nest.test/src/test/java/org/openhab/binding/nest/handler/NestThermostatHandlerTest.java, addons/binding/org.openhab.binding.nest/META-INF/MANIFEST.MF, addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/handler/NestBaseHandler.java, addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/handler/NestThermostatHandler.java, addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/NestHandlerFactory.java
* Handle DecimalType and StringType on QuantityType channels with unit assumptions
* Send temperature commands to Nest API using UnitProvider temperature unit instead of Celsius when thermostat unit is unknown
Fixes #3614
See also the discussion/limitations in this [community thread](https://community.openhab.org/t/rest-api-temperature-item-problem/45817?u=wborn).
=> [Nest] Command handling improvements

addons/binding/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/handler/BaseHomeThingHandler.java, addons/binding/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/handler/TadoHomeHandler.java, addons/binding/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/handler/TadoMobileDeviceHandler.java, addons/binding/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/handler/TadoZoneHandler.java
The tado binding did not recover automatically from OFFLINE state, but a restart of OH was required instead. This PR fixes the issue and #3628.
There are 2 scenarios:
**Bridge goes offline**
The binding retries every 5 minutes to initialise the binding again, in case it's offline. As soon as the bridge is back online, the `bridgeStatusChanged` methods of the children are called, bringing them back online.
**Individual things are offline**
This can happen if individual requests are failing. In that case, scheduled status updates are not cancelled. As soon as a status update was executed successfully, the thing's status is set to ONLINE again.
=> [tado] automatically recover things from offline state

addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/CcuGateway.java, addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/virtual/BatteryTypeVirtualDatapointHandler.java, addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/discovery/HomematicDeviceDiscoveryService.java, addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/type/MetadataUtils.java
Resolve resources from bundle instead of class loader (see https://github.com/openhab/openhab2-addons/issues/3195) & refactor to try-with-ressources
Additionally: Prevent potential NullPointerException on HomematicDeviceDiscoveryService
Signed-off-by: Michael Reitler <michael.reitler@telekom.de>
=> [homematic] Improve stability of resource loading

addons/binding/org.openhab.binding.robonect/META-INF/MANIFEST.MF
This fixes a compilation issue in the IDE since JDT annotation dependency was missing from the MANIFEST.MF.
Signed-off-by: Henning Treu <henning.treu@telekom.de>
=> [robonect] add optional jdt annotation dependency to MANIFEST

addons/binding/org.openhab.binding.innogysmarthome/ESH-INF/thing/WRT.xml, addons/binding/org.openhab.binding.innogysmarthome/README.md
Added missing channels to wall mounted room thermostat and updated documentation:
- channels frost_warning, mold_warning, operation_mode, window_reduction_active added
- updated README with thermostat examples, especially operation_mode mappings are important to be documented
Signed-off-by: Oliver Kuhl <oliver.kuhl@gmail.com> (github: ollie-dev)
=> [innogy] Added missing channels to wall mounted thermostat

addons/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/handler/DSCAlarmBaseBridgeHandler.java, addons/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/handler/KeypadThingHandler.java, addons/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/handler/PanelThingHandler.java, addons/binding/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/handler/ZoneThingHandler.java
Fixes:
* Special panel alarms when being restored were not turning the partition_in_alarm channel OFF (#3580).
* LCDCursor and LCDUpdate for the IT100 were not functioning (#3586).
* Network login password length checking has been removed for the Envisalink as discussed [here](https://community.openhab.org/t/dscalarmbinding-with-envisalink-4/6966/12).
* Zone Bypass Mode command wasn't working in the binding.
Signed-off-by: Russell Stephens rsstephens@gmail.com (github:RSStephens)
=> [DSCALARM] Various Bug Fixes

addons/binding/org.openhab.binding.meteostick/ESH-INF/thing/thing-types.xml, addons/binding/org.openhab.binding.meteostick/META-INF/MANIFEST.MF, addons/binding/org.openhab.binding.meteostick/README.md, addons/binding/org.openhab.binding.meteostick/src/main/java/org/openhab/binding/meteostick/MeteostickBindingConstants.java, addons/binding/org.openhab.binding.meteostick/src/main/java/org/openhab/binding/meteostick/handler/MeteostickBridgeHandler.java, addons/binding/org.openhab.binding.meteostick/src/main/java/org/openhab/binding/meteostick/handler/MeteostickSensorHandler.java
- Add configurable spoon size, update doc. Fixes #3636
- Added support for UoM
- Make `rainHourlyWindow` hold last hour's worth of data instead of only one minute's worth of data.
- Don't add repeated differences to total ticks within time window because the MeteoStick repeatedly reports the same tick count (use `=` and not `+=`). `+=` causes the amount of rainfall to grow "out of control" within the time window.
=> [meteostick] Allow configurable spoon, UoM support, bug fixes

features/openhab-addons/src/main/feature/feature.xml
Fixes the runtime failing to start when using misc-azureiothub in addons.cfg, see [community post](https://community.openhab.org/t/uis-not-installed-on-openhab-2-4-0-build-1300/46480/7?u=wborn). 
This would cause for example the following error to be logged:
`[ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-binding-hue, openhab-binding-exec, openhab-binding-ftpupload, openhab-misc-openhabcloud, openhab-misc-restdocs, openhab-binding-network, openhab-persistence-influxdb, openhab-ui-habpanel, openhab-persistence-mysql, openhab-transformation-map, openhab-binding-logreader, openhab-ui-habmin, openhab-transformation-xslt, openhab-binding-lgtv1, openhab-transformation-exec, openhab-binding-systeminfo, openhab-ui-paper, openhab-binding-market:binding-3805847, …
=> [AzureIOT] Add missing MQTT Transport to feature

addons/binding/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/statedescription/AmazonEchoDynamicStateDescriptionProvider.java, addons/binding/org.openhab.binding.hyperion/src/main/java/org/openhab/binding/hyperion/internal/HyperionStateDescriptionProvider.java, addons/binding/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/KodiDynamicStateDescriptionProvider.java, addons/binding/org.openhab.binding.lametrictime/src/main/java/org/openhab/binding/lametrictime/internal/StateDescriptionOptionsProvider.java, addons/binding/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/LoxoneDynamicStateDescriptionProvider.java, addons/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/NATherm1StateDescriptionProvider.java, addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/SqueezeBoxStateDescriptionOptionsProvider.java
- Removed immediate activation for `DynamicStateDescriptionProvider` components
wrt https://github.com/eclipse/smarthome/pull/5682#discussion_r193424683
=> Removed immediate activation for 'DynamicStateDescriptionProvider' components

addons/binding/org.openhab.binding.meteostick/ESH-INF/thing/thing-types.xml, addons/binding/org.openhab.binding.meteostick/README.md, addons/binding/org.openhab.binding.meteostick/src/main/java/org/openhab/binding/meteostick/MeteostickBindingConstants.java, addons/binding/org.openhab.binding.meteostick/src/main/java/org/openhab/binding/meteostick/handler/MeteostickSensorHandler.java
Add three advanced channels to summarise wind speed and direction over last two minutes. Instantaneous wind speed and direction samples are not useful in isolation, and relying on automation to compute statistics is much more burdensome on the system than doing so directly in the binding. (The same thinking applies to the existing current and last hour rain channels.)
The use case of using openHAB as a personal weather station for data upload to Wunderground, for example, is made easy with this change, along with unit-of-measure support.
Signed-off-by: John Cocula <john@cocula.com>
=> [meteostick] advanced channels for wind statistics

addons/binding/org.openhab.binding.freebox/META-INF/MANIFEST.MF, addons/binding/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/discovery/FreeboxServerDiscoveryParticipant.java, addons/binding/org.openhab.binding.innogysmarthome/META-INF/MANIFEST.MF, addons/binding/org.openhab.binding.innogysmarthome/src/main/java/org/openhab/binding/innogysmarthome/internal/discovery/InnogyBridgeDiscoveryParticipant.java
Use `org.eclipse.smarthome.config.discovery.mdns.MDNSDiscoveryParticipant` 
instead of  `org.eclipse.smarthome.io.transport.mdns.discovery.MDNSDiscoveryParticipant`
because it is deprecated.
=> Fix using deprecated MDNSDiscoveryParticipant

addons/binding/org.openhab.binding.hyperion/.settings/org.eclipse.core.resources.prefs, addons/binding/org.openhab.binding.hyperion/.settings/org.eclipse.jdt.core.prefs
It's unnecessary to override the default Eclipse settings for this project.
See also: https://github.com/openhab/openhab2-addons/pull/3472
=> [Hyperion] Use default Eclipse project settings

addons/binding/org.openhab.binding.squeezebox/README.md
- Add documentation for duration channel (was missed when channel was added)
- Fix syntax for say and playSound with volume argument
- Revise documentation for playing favorites using sitemap
=> [squeezebox] Documentation updates/fixes

addons/binding/org.openhab.binding.systeminfo.test/src/test/java/org/openhab/binding/systeminfo/test/SysteminfoOSGiTest.java
The tests started throwing the following IAE due to changes in https://github.com/eclipse/smarthome/pull/5838:
```
java.lang.IllegalArgumentException: The given reference (class: class org.openhab.binding.systeminfo.internal.discovery.SysteminfoDiscoveryService) does not implement an interface.
at org.eclipse.smarthome.test.java.JavaOSGiTest.getInterfaceName(JavaOSGiTest.java:289)
at org.eclipse.smarthome.test.java.JavaOSGiTest.unregisterService(JavaOSGiTest.java:258)
at org.openhab.binding.systeminfo.test.SysteminfoOSGiTest.testDiscoveryService(SysteminfoOSGiTest.java:922)
at org.openhab.binding.systeminfo.test.SysteminfoOSGiTest.testDiscoveryWithUnresolvedHostname(SysteminfoOSGiTest.java:904)
```
I'm passing the `DiscoveryService.class` and not `discoveryService` as argument because …
=> Fix IllegalArgumentExceptions in SysteminfoOSGiTest

addons/voice/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/internal/VoiceRSSTTSService.java
I've added back the properties in the annotation because they seem to be used for the file based configuration which is not used by other TTS services.
See: https://github.com/openhab/openhab2-addons/pull/3723#issuecomment-405116566
Can you test if this fixes the issue for you @mhilbush ?
=> [VoiceRSS] Add back properties to fix missing configuration

addons/voice/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/internal/VoiceRSSTTSService.java
Since the component name is now generated the default configurationPid (based on the name) changed. Defining the configurationPid fixes the issue for me @mhilbush .
=> [VoiceRSS] Add configurationPid to fix missing API key

addons/binding/org.openhab.binding.denonmarantz/README.md, addons/binding/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/DenonMarantzBindingConstants.java
Updated BindingConstants to map SurroundProgram to the the 'general' Channel Group.
Fixed table in README.md
Fixes #3724
=> [denonmarantz] SurroundProgram was assigned to the wrong ChannelGroup

addons/binding/org.openhab.binding.harmonyhub/ESH-INF/thing/thing-types.xml, addons/binding/org.openhab.binding.harmonyhub/src/main/java/org/openhab/binding/harmonyhub/HarmonyHubBindingConstants.java, addons/binding/org.openhab.binding.harmonyhub/src/main/java/org/openhab/binding/harmonyhub/handler/HarmonyDeviceHandler.java, addons/binding/org.openhab.binding.harmonyhub/src/main/java/org/openhab/binding/harmonyhub/handler/HarmonyHubHandler.java, addons/binding/org.openhab.binding.harmonyhub/src/main/java/org/openhab/binding/harmonyhub/handler/HubStatusListener.java, addons/binding/org.openhab.binding.harmonyhub/src/main/java/org/openhab/binding/harmonyhub/internal/HarmonyHubHandlerFactory.java, addons/binding/org.openhab.binding.harmonyhub/src/main/java/org/openhab/binding/harmonyhub/internal/config/HarmonyDeviceConfig.java, addons/binding/org.openhab.binding.harmonyhub/src/main/java/org/openhab/binding/harmonyhub/internal/config/HarmonyHubConfig.java, addons/binding/org.openhab.binding.harmonyhub/src/main/java/org/openhab/binding/harmonyhub/internal/discovery/HarmonyDeviceDiscoveryService.java, addons/binding/org.openhab.binding.harmonyhub/src/main/java/org/openhab/binding/harmonyhub/internal/discovery/HarmonyHubDiscoveryService.java
* Annotate all classes with null annotations
* Fix buttonPress channel has no state options when only the device name is configured
* Fix buttonPress channel has no state options when Thing is updated
* Set ThingStatus to UNKNOWN in initialize to trigger updates when Things are modified
* Fix wrong label for name parameter in device configuration
* Give discovery thread a proper name which includes TCP port
* Simplify code where possible
* Remove binding dependency on google.collect, it is still in the manifest because the harmony-client has a Guava dependency
* Use Channel/Thing UIDs in logging so logging is more clear when using multiple hubs
* Update HarmonyHubBindingConstants, add/remove missing/unused properties
* Update field modifiers, add private and final where possible
--- …
=> [Harmony] Add null annotations, bugfixes and improvements

addons/binding/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/handler/FroniusSymoInverterHandler.java
Fixes Issue #3725
In case of an timeout error, the respone message of the fronius inverter does not contain a data node. This causes a NullPointerException in the inverter handler.
The message I received from the inverter was:
```
URL = http://192.168.2.76/solar_api/v1/GetInverterRealtimeData.cgi?Scope=Device&DeviceId=1&DataCollection=CommonInverterData
2018-07-19 23:14:34.376 [DEBUG] [s.handler.FroniusSymoInverterHandler] - aqiResponse = {
"Body" : {
"Data" : {}
},
"Head" : {
"RequestArguments" : {
"DataCollection" : "CommonInverterData",
"DeviceClass" : "Inverter",
"DeviceId" : "1",
"Scope" : "Device"
},
"Status" : {
"Code" : 8,
"Reason" : "Transfer timeout.",
"UserMessage" : ""
},
"Timestamp" : "2018-07-19T23:14:32+02:00"
}
}
```
=> [fronius] Fixed the NullPointerException if timeout response received

addons/binding/org.openhab.binding.kodi/README.md, addons/binding/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/discovery/KodiUpnpDiscoveryParticipant.java
- Added null annotations to discovery service
- Use `discovery.kodi:background=false` to disable discovery service
Streamlined background discovery to be compliant with [Concept: Thing Discovery](https://www.openhab.org/docs/concepts/discovery.html#background-discovery).
=> [Kodi] Streamlined and fixed deactivation of background discovery

addons/binding/org.openhab.binding.nest.test/META-INF/MANIFEST.MF, addons/binding/org.openhab.binding.nest/ESH-INF/config/config.xml, addons/binding/org.openhab.binding.nest/META-INF/MANIFEST.MF, addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/handler/NestBaseHandler.java, addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/handler/NestBridgeHandler.java, addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/config/NestBridgeConfiguration.java, addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/config/NestDeviceConfiguration.java, addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/config/NestStructureConfiguration.java, addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/discovery/NestDiscoveryService.java, addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/exceptions/FailedResolvingNestUrlException.java, addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/exceptions/FailedRetrievingNestDataException.java, addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/exceptions/FailedSendingNestDataException.java, addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/exceptions/InvalidAccessTokenException.java, addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/rest/NestStreamingRestClient.java
Add missing null annotation to all binding packages except for `org.openhab.binding.nest.internal.data`.
I don't know if it is a good idea to also add null annotations to the Gson data classes. Currently the binding is very defensive and assumes everything could be null in these data classes. There are also unit tests to test it can handle all null values. Data could be null due to lack of API permissions or deprecated properties that may get removed some day.
So you might want to annotate all methods/fields with `@Nullable` but that seems quite laborious. There doesn't seem to be a `@NullByDefault` annotation for such classes. Also annotating the whole class with `@Nullable` doesn't work. 
@maggu2810 would it make sense to add null annotations to such data classes and if so how?
=> [Nest] Add missing null annotations and fix warnings

addons/binding/org.openhab.binding.max/META-INF/MANIFEST.MF, addons/binding/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/command/UdpCubeCommand.java, addons/binding/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/handler/SendCommand.java, addons/binding/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/message/C_Message.java, addons/binding/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/message/H_Message.java
As can be [seen on the current build](https://openhab.ci.cloudbees.com/job/openHAB2-Bundles/375/console), the MAX binding makes use of Guava methods that are not available in the different versions of Guava, so we have a mismatch between IDE and Maven build here.
As the use of Guava is not anymore recommended for these reasons, this PR removes the dependency with the imho acceptable impact of having a few less tabular trace/debug log messages.
=> removed usage of Guava from MAX binding

addons/binding/org.openhab.binding.nest.test/src/test/java/org/openhab/binding/nest/handler/NestThermostatHandlerTest.java, addons/binding/org.openhab.binding.nest/META-INF/MANIFEST.MF, addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/handler/NestBaseHandler.java, addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/handler/NestThermostatHandler.java, addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/NestHandlerFactory.java
Removes the conversion to QuantityType values of commands with Number values in the Nest Binding (introduced in https://github.com/openhab/openhab2-addons/pull/3618). ESH will nowadays automatically do these conversions (see https://github.com/eclipse/smarthome/pull/5734).
See also the discussion in https://github.com/openhab/openhab2-addons/pull/3777.
=> [Nest] Remove unused Number to QuantityType command conversion

addons/binding/org.openhab.binding.avmfritz/README.md, addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/discovery/AVMFritzUpnpDiscoveryParticipant.java
- Added null annotations to discovery service
- Use `discovery.avmfritz:background=false` to disable discovery service
=> [avmfritz] Added deactivation of background discovery

CONTRIBUTING.md
As a result of the dicsussion in PR #3696 (starting from this[1] comment), the users noreply e-mail addresses
(username@users.noreply.github.com) are not allowed as an e-mail address in the Signed-off-by trailer  to certify the
developer certificate of origin. This commit updates the doc accordingly.
[1] https://github.com/openhab/openhab2-addons/pull/3696#issuecomment-410025110
=> Update contribution doc to disallow noreply e-mail addresses

addons/binding/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/rest/NestStreamingRestClient.java
* Stop and restart checkConnectionJob when reconnecting
* Use CONNECTION_TIMEOUT_MILLIS for checkConnectionJob as initial delay
=> [Nest] Prevent race conditions when NestStreamingRestClient reconnects

addons/binding/org.openhab.binding.icloud/README.md
Adding informations about the device ID and location information in the .things file.
- It´s clear where to find the device ID. I had so search in the community to found someone mentioning where to find the device ID.
Changing the transformation for 'batteryStatus' and 'batteryLevel'.
- The transformation [%s %% ] for 'batteryStatus' is wrong and brings the information "Not charging %"
- The transformation [%.0f] for 'batteryLevel' is wrong and shows the battery level without '%'
=> [iCloud binding] Update help for things and change the transformation for items

pom.xml
I am not completely sure that this is required, but it is an attempt to solve the build issues that we have at https://openhab.ci.cloudbees.com/view/Sandbox/job/sandbox-openhab2-release/658/
=> added Orbit repo so that it those dependencies are available in the build

pom.xml
Reverts openhab/openhab2-addons#3800 as it didn't make any difference.
=> Revert "added Orbit repo so that it those dependencies are available in the build"

addons/binding/org.openhab.binding.knx.test/src/test/java/org/openhab/binding/knx/internal/channel/KNXChannelTypeTest.java, addons/binding/org.openhab.binding.knx.test/src/test/java/org/openhab/binding/knx/internal/dpt/KNXCoreTypeMapperTest.java, addons/binding/org.openhab.binding.knx/README.md, addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/handler/AbstractKNXThingHandler.java, addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/channel/KNXChannelType.java, addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/KNXCoreTypeMapper.java
This PR contains a few minor fixes for the KNX2 binding:
* Avoid NPE in case bridge handler has been destroyed already
* added support for 2-level and free style GA notations
* Strip off trailing zeroes of DecimalTypes in order to gain compatibility with integer types in case any UI can't distinguish integers and floats coming from JS
* fixed < position in README.md  …
fixes #3609
fixes #3735
fixes #3686
fixes #3648
Signed-off-by: Simon Kaufmann <simon.kfm@googlemail.com>
=> [KNX2] some small fixes

pom.xml
fixes a build issue within the release automation: `Missing requirement: org.openhab.binding.airquality 2.4.0.qualifier requires 'package com.google.gson 0.0.0' but it could not be found`
=> Re-add missing version parameter that was deleted on a POM refactoring

addons/binding/org.openhab.binding.meteostick/src/main/java/org/openhab/binding/meteostick/handler/MeteostickSensorHandler.java
Rain counters have been seen to wrap at 127 and also at 255, depending on unspecified hardware differences. The Meteostick documentation only mentions 255 at the time of this writing. This potential difference is solved by having all rain counters wrap at 127 (0x7F) by removing the high bit.
Signed-off-by: John Cocula <john@cocula.com>
=> [Meteostick] Consistently wrap rain counters

addons/binding/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/handler/HDPowerViewHubHandler.java, addons/binding/org.openhab.binding.miele/OSGI-INF/MieleMDNSDiscoveryParticipant.xml, addons/io/org.openhab.io.transport.modbus/src/main/java/org/openhab/io/transport/modbus/ModbusUnexpectedTransactionIdException.java, addons/io/org.openhab.io.transport.modbus/src/main/java/org/openhab/io/transport/modbus/endpoint/ModbusTCPSlaveEndpoint.java, addons/io/org.openhab.io.transport.modbus/src/main/java/org/openhab/io/transport/modbus/endpoint/ModbusUDPSlaveEndpoint.java, addons/voice/org.openhab.voice.marytts/src/main/java/org/openhab/voice/marytts/internal/MaryTTSService.java
While looking at the MaryTTS code I stumbled upon a duplicate header. A grep showed there were a few more (outdated) duplicate license headers.
=> Remove outdated license header duplicates

addons/binding/org.openhab.binding.airvisualnode/META-INF/MANIFEST.MF, addons/binding/org.openhab.binding.modbus.test/META-INF/MANIFEST.MF, addons/binding/org.openhab.binding.modbus/META-INF/MANIFEST.MF, addons/binding/org.openhab.binding.neato/META-INF/MANIFEST.MF, addons/binding/org.openhab.binding.neeo/META-INF/MANIFEST.MF, addons/binding/org.openhab.binding.openuv/META-INF/MANIFEST.MF, addons/binding/org.openhab.binding.valloxmv/META-INF/MANIFEST.MF, addons/binding/org.openhab.binding.yamahareceiver.test/META-INF/MANIFEST.MF, addons/io/org.openhab.io.neeo/META-INF/MANIFEST.MF, addons/io/org.openhab.io.transport.modbus.test/META-INF/MANIFEST.MF, addons/io/org.openhab.io.transport.modbus/META-INF/MANIFEST.MF, addons/voice/org.openhab.voice.picotts/META-INF/MANIFEST.MF
Hopefully we can test these with newer Java versions on the forthcoming Karaf 4.2.1.
=> Add missing Automatic-Module-Name manifest entries

addons/voice/org.openhab.voice.googletts/src/main/java/org/openhab/voice/googletts/internal/GoogleTTSService.java, addons/voice/org.openhab.voice.marytts/src/main/java/org/openhab/voice/marytts/internal/MaryTTSService.java, addons/voice/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/internal/VoiceRSSTTSService.java
The TTS service names should be short because otherwise voice labels may get very long (https://github.com/eclipse/smarthome/pull/6031#issuecomment-412779924).
=> Streamline TTS service names

addons/voice/org.openhab.voice.marytts/src/main/java/org/openhab/voice/marytts/internal/MaryTTSAudioStream.java, addons/voice/org.openhab.voice.marytts/src/main/java/org/openhab/voice/marytts/internal/MaryTTSService.java, addons/voice/org.openhab.voice.marytts/src/main/java/org/openhab/voice/marytts/internal/MaryTTSVoice.java
* Fix SAT findings
* Add missing final modifiers to fields
* Use diamond operator
* Use autoboxing
* Use Set for variable types instead of HashSet
* Use stream to simplify AudioFormat supported check
* Remove unncessary variables, final, this declarations
Why is MaryTTS the only project that downloads some of its library JARs from an openHAB Bintray repo to the /lib directory during the build with maven-external-dependency-plugin (see [pom.xml](https://github.com/openhab/openhab2-addons/blob/871deb58a817fa1bc674773d61f626acab89c4a5/addons/voice/org.openhab.voice.marytts/pom.xml#L31))? Is that for space or licensing reasons? The downloaded content is 20MB.
=> [MaryTTS] Cleanup and simplify code

addons/binding/org.openhab.binding.mcp23017/src/main/java/org/openhab/binding/mcp23017/handler/Mcp23017Handler.java
Fixed INPUT PIN support after changes in 2.3.0.1
After upgrade to OH2 ver 2.3.0.0 INPUT pins in [mcp23017] binding stopped to work.
I investigated a little, and it turned out, that "channelLinked" method is not called at all, so input pins cannot be initialized.
First I suspected that it is due to wrong order of loading configuration files - items are loaded before things - but in ThingLinkManager there is method receiveTypedEvent which should be called after ThingStatusInfoChangedEvent (INITIALIZING -> ONLINE).
The problem is - it is not called for my binding and I really do not know why. I changed log level to TRACE and noticed that event itself is generated, but this handler is not called - so channelLinked is not called - so input pins are not initialized - so binding is not working. …
=> [mcp23017] Workaround for input pins not being initialized

addons/binding/org.openhab.binding.modbus/pom.xml, addons/io/org.openhab.io.transport.modbus/pom.xml
I think the missing transport dependency is causing the Jenkins PR builds to fail.
=> [Modbus] Add transport dependency, remove unused bundle properties

addons/binding/org.openhab.binding.jeelink/ESH-INF/i18n/jeelink.properties, addons/binding/org.openhab.binding.jeelink/ESH-INF/i18n/jeelink_de.properties, addons/binding/org.openhab.binding.jeelink/ESH-INF/thing/thing-types.xml, addons/binding/org.openhab.binding.jeelink/META-INF/MANIFEST.MF, addons/binding/org.openhab.binding.jeelink/README.md, addons/binding/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/JeeLinkBindingConstants.java, addons/binding/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/ec3k/Ec3kSensorHandler.java, addons/binding/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/lacrosse/LaCrosseTemperatureSensorHandler.java, addons/binding/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/pca301/Pca301SensorHandler.java
This adds unit of measurement to the LaCrosse Sensor temperature channel.
AFAICS on https://www.openhab.org/docs/concepts/units-of-measurement.html#quantitytype, this is the only channel for which I could add unit support, or have I missed something?
=> [jeelink] Add units of measurement

addons/voice/org.openhab.voice.googletts/META-INF/MANIFEST.MF, addons/voice/org.openhab.voice.googletts/README.md, addons/voice/org.openhab.voice.googletts/pom.xml, addons/voice/org.openhab.voice.kaldi/META-INF/MANIFEST.MF, addons/voice/org.openhab.voice.kaldi/pom.xml, addons/voice/org.openhab.voice.marytts/META-INF/MANIFEST.MF, addons/voice/org.openhab.voice.marytts/pom.xml, addons/voice/org.openhab.voice.picotts/META-INF/MANIFEST.MF, addons/voice/org.openhab.voice.picotts/pom.xml, addons/voice/org.openhab.voice.voicerss/META-INF/MANIFEST.MF, addons/voice/org.openhab.voice.voicerss/pom.xml, features/openhab-addons/src/main/feature/feature.xml
Consistently use the same name for a voice addon as:
* feature description
* bundle name
* POM project name
I.e. similar to what is also done for bindings. See also  https://github.com/openhab/openhab2-addons/pull/3836#issuecomment-413333008.
=> Streamline TTS/STT feature, bundle and POM names

addons/voice/org.openhab.voice.googletts/src/main/java/org/openhab/voice/googletts/internal/GoogleTTSService.java, addons/voice/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/internal/VoiceRSSTTSService.java
The services configuration screen does not have a TTS context. So adding a "Text-to-Speech" suffix to the voice TTS service labels makes it more clear what the purpose of these services is.
=> Add Text-to-Speech suffix to Google Cloud and VoiceRSS service labels

addons/binding/org.openhab.binding.jeelink/ESH-INF/i18n/jeelink.properties, addons/binding/org.openhab.binding.jeelink/ESH-INF/i18n/jeelink_de.properties, addons/binding/org.openhab.binding.jeelink/ESH-INF/thing/thing-types.xml, addons/binding/org.openhab.binding.jeelink/README.md, addons/binding/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/JeeLinkBindingConstants.java, addons/binding/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/JeeLinkHandler.java, addons/binding/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/SensorDefinition.java, addons/binding/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/lacrosse/LaCrosseTemperatureReading.java, addons/binding/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/lacrosse/Tx22Reading.java, addons/binding/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/lacrosse/Tx22ReadingConverter.java, addons/binding/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/lacrosse/Tx22SensorDefinition.java, addons/binding/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/lacrosse/Tx22SensorHandler.java
This adds support for reading TX22 temperature and humidity sensors (as well as TX23 wind sensors and TX26 rain sensors wired to the TX22).
=> [jeelink] add support for TX22 sensors and connected TX23 & TX26 sensors.

addons/binding/org.openhab.binding.knx/ESH-INF/config/channelConfig.xml, addons/binding/org.openhab.binding.knx/ESH-INF/thing/device.xml, addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/KNXBindingConstants.java, addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/channel/KNXChannelTypes.java, addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/channel/TypeColor.java
Signed-off-by: lewie <helmut.lehmeyer@gmail.com>
[KNX2] Add Color Channel
Adds the ability for Color (control) to KNX2.
Use PaperUI or Things file like:
```
Type color : demoColor "Demo Color" [ hsb="232.600:<7/0/25", switch="1.001:<7/0/26", position="5.001:<7/0/27", increaseDecrease="3.007:<7/0/28" ]
Type color : demoColorControl "Demo Color Control" [ hsb="232.600:<7/0/25", switch="1.001:<7/0/26", position="5.001:<7/0/27", increaseDecrease="3.007:<7/0/28" ]
```
Fixes issue: #3411
=> [KNX2] Add Color Channel

addons/binding/org.openhab.binding.lgwebos/ESH-INF/thing/thing-types.xml, addons/binding/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/LGWebOSBindingConstants.java, addons/binding/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/handler/LGWebOSHandler.java, addons/binding/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/BaseChannelHandler.java, addons/binding/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/ChannelHandler.java, addons/binding/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/LauncherApplication.java, addons/binding/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/MediaControlPlayer.java, addons/binding/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/MediaControlStop.java, addons/binding/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/PowerControlPower.java, addons/binding/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/TVControlChannel.java, addons/binding/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/TVControlChannelName.java, addons/binding/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/ToastControlToast.java, addons/binding/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/VolumeControlMute.java, addons/binding/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/VolumeControlVolume.java, addons/binding/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/discovery/LGWebOSDiscovery.java
Closes #3903
Method getSubscription expects an optional, but most implementing classes returned a null if the capability was not supported.
Also:
- Cleanup of constants
- Added @NonNullByDefault
- Made the default response listener a final field method instead of creating one on each and every handle command call.
=> [LG webOS] Fixed NullPointerException Closes #3903

addons/binding/org.openhab.binding.nikohomecontrol/README.md
Signed-off-by: Mark Herwege mark.herwege@telenet.be
=> Niko Home Control: README spelling correction

addons/binding/org.openhab.binding.dsmr.test/META-INF/MANIFEST.MF, addons/binding/org.openhab.binding.dsmr.test/src/test/java/org/openhab/binding/dsmr/internal/TelegramReaderUtil.java, addons/binding/org.openhab.binding.dsmr/src/main/java/org/openhab/binding/dsmr/internal/handler/DSMRMeterHandler.java
Instead of setting meter offline when updateState is called it's now set offline when no cosem values in received telegram. If no values are available there will simply by no update done. When no messages were received at all the meter will still go offline because this is monitored by the bridge. This was how it already worked, and what should trigger the offline status. This fixes the problem that the meter will go offline if the refresh rate is set to a value lower than the actual speed with which the messages are send by the meter. Closes #3920
=> [dsmr] Changed when meter is set offline on no cosem values available.

addons/binding/org.openhab.binding.lutron/ESH-INF/thing/thing-types.xml, addons/binding/org.openhab.binding.lutron/README.md, addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/LutronBindingConstants.java, addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/handler/IPBridgeHandler.java, addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/handler/ShadeHandler.java, addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/LutronHandlerFactory.java, addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/discovery/LutronDeviceDiscoveryService.java, addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/discovery/project/OutputType.java
Hi. This PR contains an improvement to the Lutron binding that adds support for Lutron Sivoia QS wireless shades on Radio RA2 systems.  It should also support other Lutron shades on other Lutron system which support Lutron Integration Protocol.
From the updated docs:
Each Lutron Sivoia QS shade is controlled by a “shade” thing. The only configuration parameter it accepts is integrationId.
A single channel shadelevel with item type Rollershutter and category Rollershutter will be created for each shade thing. It accepts Percent, Up, Down, Stop and Refresh commands. Sending a Percent command will cause the shade to immediately move so as to be open the specified percentage. You can also read the current shade level from the channel. It is specified as a percentage, where 0% = closed and …
=> [Lutron] Add support for shades

addons/binding/org.openhab.binding.samsungtv/README.md
I have tested the LE40D579 with the Samsung TV Binding...
Signed-off-by: Jan Haffner <info@jan-haffner.de>
=> [samsungtv] Add LE40D579 to the tested TV models

addons/io/org.openhab.io.transport.modbus/src/main/java/org/openhab/io/transport/modbus/ModbusSlaveErrorResponseException.java, addons/io/org.openhab.io.transport.modbus/src/main/java/org/openhab/io/transport/modbus/internal/ModbusSlaveErrorResponseExceptionImpl.java
This is a minor addition to the modbus transport.
The modbus protocol uses a custom error handling method, where a few predefined exceptions can be sent to the master by the salve when it can not fulfill the request. These exception codes will tell the master what is the exact cause of the failure.
The modbus implementation in the master branch failed to expose this value, and that made writing sophisticated error handling impossible.
This change is related to an upcoming extension of the modbus addon, see #3216
=> [modbus] Expose modbus exceptions

addons/binding/org.openhab.binding.meteostick/README.md
Added dewpoint temperature to the report to Weather Underground in the rule example in the doc, derived from relative humidity and temperature as computed with the "reverse" Magnus formula.  This example wasn't possible in the openHAB 2.3 release but is possible in 2.4 with improvements to the UoM support from rules.
Signed-off-by: John Cocula <john@cocula.com>
=> [meteostick] Add example of working with UoM in example rule

addons/binding/org.openhab.binding.modbus.test/src/test/java/org/openhab/binding/modbus/internal/ModbusDataHandlerTest.java, addons/binding/org.openhab.binding.modbus.test/src/test/java/org/openhab/binding/modbus/internal/ModbusPollerThingHandlerTest.java, addons/binding/org.openhab.binding.modbus.test/src/test/java/org/openhab/binding/modbus/internal/ModbusTcpThingHandlerTest.java, addons/binding/org.openhab.binding.modbus/META-INF/MANIFEST.MF, addons/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/ModbusBindingConstants.java, addons/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/handler/EndpointNotInitializedException.java, addons/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/handler/ModbusEndpointThingHandler.java, addons/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusBindingConstants.java, addons/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusBindingConstantsInternal.java, addons/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusHandlerFactory.java, addons/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/handler/AbstractModbusEndpointThingHandler.java, addons/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/handler/ModbusDataThingHandler.java, addons/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/handler/ModbusPollerThingHandlerImpl.java
This is a follow up to PR #4053 
The modbus binding could easily be extended by other bundles to add device specific things and their handlers. There is already such a work in progress, see issue #3216 
Fortunately @ssalonen  did a nice work separating interfaces from actual implementations so exporting the base handler interfaces is quite straightforward.
This work is based on the zigbee and bluetooth package practices and work by @triller-telekom 
I've split the ModbusBindingConstants class also in two: one that is public and could be used by other bundles and one that remains internal.
=> [modbus] Export thing handler interface for upcoming bundles

addons/binding/org.openhab.binding.nikohomecontrol/ESH-INF/thing/thing-types.xml
Fix for thermostat parameter being attached to the wrong thing.
=> [nikohomecontrol] Fix thermostat parameter.

addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/ChannelMapper.java, addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/handler/XiaomiAqaraSensorSwitch2Handler.java
This PR fixes the issue described in #4136 
___Single press reports an extra event as "UNKNOWN_EVENT" after "SHORT_PRESSED"___
The log shows, that the button is sending __click__ and shortly afterwards __long_click__.
The proposed solution is to trigger on both messages and distinguish one event as SHORT_PRESSED, the other as LONG_PRESSED. 
The issue states, that maybe the button is not even able to only send one __click__ event and always sends both. I am against suppressing the second one. There is no downside in having two event triggers - on the other hand there may be devices (or new firmware versions in the future) sending __click__ and __long_click__ seperately.
___Double press reports "SHORT_PRESSED" twice in a row.___
The log shows a unrecognized message __long_both_click__. It …
=> [MiHome] fix #4136

addons/binding/org.openhab.binding.yamahareceiver/docs/desc_RX-V775.xml, addons/binding/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/ChannelsTypeProviderAvailableInputs.java, addons/binding/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/handler/YamahaBridgeHandler.java
There was an issue where the internal timer for device state polling was called prior the thing handler was initialized. This resulted in an NPE exception in certain situations:
```
2018-10-19 23:05:45.491 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception
at org.openhab.binding.yamahareceiver.handler.YamahaBridgeHandler.updateAllZoneInformation(YamahaBridgeHandler.java:219) ~[?:?]
at org.openhab.binding.yamahareceiver.handler.YamahaBridgeHandler.lambda$0(YamahaBridgeHandler.java:192) ~[?:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:?]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTas …
```
=> [YamahaReceiver] Fixing NPE while refresh timer (2.4.0-SNAPSHOT) and add XML descriptor for RX-V775

addons/io/org.openhab.io.transport.modbus.test/src/test/java/org/openhab/io/transport/modbus/test/SmokeTest.java
=> [modbus] Timing sensitive assertions enabled only outside CI

addons/binding/org.openhab.binding.avmfritz.test/src/test/java/org/openhab/binding/avmfritz/internal/ahamodel/AVMFritzModelTest.java, addons/binding/org.openhab.binding.avmfritz.test/src/test/java/org/openhab/binding/avmfritz/internal/discovery/AVMFritzDiscoveryServiceTest.java, addons/binding/org.openhab.binding.avmfritz/ESH-INF/i18n/avmfritz_de.properties, addons/binding/org.openhab.binding.avmfritz/ESH-INF/thing/channel-types.xml, addons/binding/org.openhab.binding.avmfritz/ESH-INF/thing/thing-types.xml, addons/binding/org.openhab.binding.avmfritz/README.md, addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/BindingConstants.java, addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/ahamodel/AVMFritzBaseModel.java, addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/ahamodel/AlertModel.java, addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/ahamodel/ButtonModel.java, addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/ahamodel/DeviceModel.java, addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/AVMFritzBaseBridgeHandler.java, addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/AVMFritzBaseThingHandler.java, addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/Powerline546EHandler.java
- Added support for HAN-FUN devices
Beta version: [org.openhab.binding.avmfritz-2.4.0-SNAPSHOT.jar.zip](https://github.com/openhab/openhab2-addons/files/2490418/org.openhab.binding.avmfritz-2.4.0-SNAPSHOT.jar.zip)
See https://community.openhab.org/t/avmfritz-support-for-han-fun-dect-ule-devices/38950
=> [avmfritz] Added support for HAN-FUN devices

addons/binding/org.openhab.binding.lutron/ESH-INF/thing/thing-types.xml, addons/binding/org.openhab.binding.lutron/README.md, addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/LutronBindingConstants.java, addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/LutronHandlerFactory.java, addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/discovery/LutronDeviceDiscoveryService.java, addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/discovery/project/GreenMode.java, addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/discovery/project/Project.java, addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/discovery/project/Timeclock.java, addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/GreenModeHandler.java, addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/IPBridgeHandler.java, addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/LutronHandler.java, addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/TabletopKeypadHandler.java, addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/TimeclockHandler.java, addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/protocol/LutronCommandType.java, addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/xml/DbXmlInfoReader.java
[Lutron] Add support for Radio RA2 Timeclock and Green Mode control
This PR adds support for controlling Lutron Radio RA2 Timeclock and Green Mode subsystems, as described in Issue #4122.
It consists of the following:
* Addition of new GreenModeHandler and TimeclockHandler classes.
* Changes to the discovery service and xml parser to support timeclock and green mode discovery.
* Changes to IPBridgeHandler and LutronHandler to add support for TIMECLOCK and MODE commands sets.
* Doc updates
* Includes a minor fix to the indicator LED configuration for some keypad models supported by TabletopKeypadHandler.
Closes: #4122
=> [Lutron] Add support for Radio RA2 Timeclock and Green Mode control

addons/binding/org.openhab.binding.nibeheatpump/ESH-INF/thing/f1x45.xml, addons/binding/org.openhab.binding.nibeheatpump/ESH-INF/thing/f750.xml, addons/binding/org.openhab.binding.nibeheatpump/README.md, addons/binding/org.openhab.binding.nibeheatpump/src/main/java/org/openhab/binding/nibeheatpump/internal/config/NibeHeatPumpConfiguration.java, addons/binding/org.openhab.binding.nibeheatpump/src/main/java/org/openhab/binding/nibeheatpump/internal/handler/NibeHeatPumpHandler.java
Nibe heat pumps send data read out messages at a high speed (e.g. every second) which can cause lot of item updates. Added throttle feature which can be used to skip some incoming messages. 
=> [nibe heat pump] Throttle incoming messages support

addons/binding/org.openhab.binding.onewiregpio/ESH-INF/thing/thing-types.xml, addons/binding/org.openhab.binding.onewiregpio/META-INF/MANIFEST.MF, addons/binding/org.openhab.binding.onewiregpio/README.md, addons/binding/org.openhab.binding.onewiregpio/src/main/java/org/openhab/binding/onewiregpio/internal/handler/OneWireGPIOHandler.java
I have configured Fahrenheit as my unit of temperature. The onewire sysfs uses Celsius. When reading the temperature, it was being assumed Fahrenheit. I updated it to use QuantityType instead of DecimalType. Built a jar and loaded the bundle. Worked!
`10:54:19.217 [INFO ] [smarthome.event.ItemStateChangedEvent] - Air_East_Supply changed from 23.5 °F to 74.4116 °F`
`10:54:19.373 [INFO ] [smarthome.event.ItemStateChangedEvent] - Air_West_Supply changed from 58.812 °F to 97.1366 °F`
(Note the math doesn't work out on the change for Air_West_Supply - this is okay, it was cooling down between unloading the old bundle and loading the new one.)
=> [onewiregpio] Temperature localization: declare sysfs reading as Celsius

addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/handler/XiaomiSensorMagnetHandler.java
When using the MiHome addon and a Door / Windows Sensors, then when openhab2 is restart the status of the sensors remain empty, until the Door / Windows sensor is triggered.
The status information is available and using be other sensors by parsing the heartbeat data.
I have update the XiaomiSensorMagnetHandler to also parse this data, so the state is update.
=> [MiHome] fixed Update of magnet sensorStatus from heartbeat's

addons/binding/org.openhab.binding.wifiled/src/main/java/org/openhab/binding/wifiled/internal/handler/WiFiLEDHandler.java
The White2 channel of an item with two white channels (CW and WW) was always NULL because of missing line for reading the actual White2 value and updating the item state.
Signed-off-by: Jan Mollenhauer <janmo0904@gmail.com> (github: t1lt3rr0r)
=> [WifiLED] Missing WHITE2 parameter while updating item

addons/binding/org.openhab.binding.tellstick/.classpath, addons/binding/org.openhab.binding.tellstick/ESH-INF/thing/bridge.xml, addons/binding/org.openhab.binding.tellstick/ESH-INF/thing/devices.xml, addons/binding/org.openhab.binding.tellstick/ESH-INF/thing/sensor.xml, addons/binding/org.openhab.binding.tellstick/README.md, addons/binding/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/TellstickBindingConstants.java, addons/binding/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/handler/DeviceStatusListener.java, addons/binding/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/handler/TelldusBridgeHandler.java, addons/binding/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/handler/TelldusDeviceController.java, addons/binding/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/handler/TelldusDevicesHandler.java, addons/binding/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/internal/TelldusBindingException.java, addons/binding/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/internal/TellstickRuntimeException.java, addons/binding/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/internal/core/TelldusCoreBridgeHandler.java, addons/binding/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/internal/core/TelldusCoreDeviceController.java, addons/binding/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/internal/discovery/TellstickDiscoveryService.java, addons/binding/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/internal/live/TelldusLiveBridgeHandler.java, addons/binding/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/internal/live/TelldusLiveDeviceController.java, addons/binding/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/internal/live/TelldusLiveException.java, addons/binding/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/internal/live/xml/DataTypeValue.java, addons/binding/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/internal/live/xml/LiveDataType.java, addons/binding/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/internal/live/xml/NameToDataType.java, addons/binding/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/internal/live/xml/NumberToBooleanMapper.java, addons/binding/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/internal/live/xml/TelldusLiveResponse.java, addons/binding/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/internal/live/xml/TellstickNetDevice.java, addons/binding/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/internal/live/xml/TellstickNetDevices.java, addons/binding/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/internal/live/xml/TellstickNetSensor.java, addons/binding/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/internal/live/xml/TellstickNetSensorEvent.java, addons/binding/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/internal/live/xml/TellstickNetSensors.java
This pull request adds support for Power and Lux sensors values in [tellstick] binding, also fixes some null pointers when these value types are sent 
This pull request adds a new sensor: PowerSensor. Any sensor with a "watt" data type will be treated as a powersensor, these are normally devices that can report on current watt usage.
Also included are a new channel for normal sensors, lux. This channel will report the current detected lux if the sensor has this value type.
=> [tellstick] Added support for Power and Lux sensor values from the Telldus Live.

addons/binding/org.openhab.binding.konnected/ESH-INF/config/config.xml, addons/binding/org.openhab.binding.konnected/ESH-INF/thing/thing-types.xml, addons/binding/org.openhab.binding.konnected/README.md, addons/binding/org.openhab.binding.konnected/src/main/java/org/openhab/binding/konnected/internal/handler/KonnectedHandler.java
Signed-off-by: Zachary Christiansen <volfan6415@gmail.com> (github: volfan6415)
@kaikreuzer When i changed the thing type of the switch per #3702 (comment) i neglected to correct the handling of the states in the handler.
This pull request corrects that so that the states are properly updated as OnOffType instead of OpenClosed type.
This also adds checking in the handle command section to check the channel type and ignores commands for the channel type of switch (previously i was ignoring based on command type but since they are both OnOffType now that needed to change)
=> -handle channel type of switch as OnOffType

addons/binding/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/pca301/Pca301SensorHandler.java
Gets rid of the following warnings in the log:
> Handler Pca301SensorHandler tried updating the thing status although the handler was already disposed.
=> [jeelink] Cancel cyclic status update task on disposal of Pca301SensorHandler

features/openhab-addons/src/main/feature/feature.xml
This corrects #2167 and fixes the distro build (see https://ci.openhab.org/job/openHAB-Distribution/1432/console)
=> fixed Karaf feature definition for Smartmeter binding

addons/binding/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/TPLinkSmartHomeDiscoveryService.java
Timeout of discovery was very short. For devices with a low connection rssi this seems to give them some more time to react.
Also reduced to overall time because if the packet timeout triggers discovery is over anyway, so no need to keep it longer.
Also cleared the idINet cache to avoid having old results. It keeps the cache clean.
=> [tplinksmarthome] Discovery package timeout gets more time, clear cache before discovery

addons/binding/org.openhab.binding.onkyo/ESH-INF/config/config.xml, addons/binding/org.openhab.binding.onkyo/README.md, addons/binding/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/config/OnkyoDeviceConfiguration.java, addons/binding/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/handler/OnkyoHandler.java
This adds a configuration parameter to the onkyo receiver thing that allows to control volume scaling. The following 4 variants are supported:
- 0-100 -> no scaling
- 0-200 -> 0.5 increments for volume, scale by 2
- 0-80  -> volume goes from 0-80, scale by 0.8
- 0-50  -> volume goes from 0-50, scale by 0.5
The default behavior remains unchanged. Volume limiting is applied before the scaling, so should still be ok.
=> [onkyo] Add volume scaling variants

addons/binding/org.openhab.binding.knx/README.md
Minor typo, clarified default ipAddress for ROUTER mode, corrected false localSourceAddr (this is no group address but a not necessarilly real physical address)
Signed-off-by: Udo Hartmann <udo1toni@gmail.com>
=> [knx] update README.md

addons/binding/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/model/deser/PropertyValueDeserializer.java
Gardena added some properties to the gateway, they can be ignored.
Closes https://github.com/openhab/openhab2-addons/issues/4265
=> [Gardena] Ignore known gateway properties

features/openhab-addons/src/main/feature/feature.xml
The Lutron and Pioneer AVR bindings use gnu.io but are missing a serial transport feature dependency.
Fixes #4281
=> Add missing serial transports to lutron and pioneeravr binding features

addons/binding/org.openhab.binding.konnected/ESH-INF/config/config.xml, addons/binding/org.openhab.binding.konnected/ESH-INF/thing/thing-types.xml, addons/binding/org.openhab.binding.konnected/src/main/java/org/openhab/binding/konnected/internal/KonnectedBindingConstants.java, addons/binding/org.openhab.binding.konnected/src/main/java/org/openhab/binding/konnected/internal/KonnectedHTTPUtils.java, addons/binding/org.openhab.binding.konnected/src/main/java/org/openhab/binding/konnected/internal/KonnectedHttpRetryExceeded.java, addons/binding/org.openhab.binding.konnected/src/main/java/org/openhab/binding/konnected/internal/handler/KonnectedHandler.java, addons/binding/org.openhab.binding.konnected/src/main/java/org/openhab/binding/konnected/internal/servlet/KonnectedHTTPServlet.java
- add high/low onvalue config parameter to thing
- updates to httpUtils to use request timeout and retry count parameters with http requests
- addition of custom exception for retry timeout exceed exception
- updates to handler to utilize retry timeout config parameter and request timeout parameter or defaults of 30 seconds and 2 if none configured
So i have added a request timeout config parameter and a retry count parameter.  The binding now utilizes these instead to retry the http requests to the module and throws a custom exception when the retry count is exceed that sets the thing status to offline.  This allows the end user to better configure the thing to tailor the thing to their address network latency issues.
Also added high/low config option to the switch and actuator channel …
=> [Konnected]- Updates,  Tweaks,  add retry count and request timeout config parameter to thing

addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxServerHandler.java
Fixes #4253 
Add synchronization to `squeezeBoxPlayerListeners` iteration as required [here](https://docs.oracle.com/javase/8/docs/api/java/util/Collections.html#synchronizedList-java.util.List-).
=> [squeezebox] Synchronize on squeezeBoxPlayerListeners iteration

addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/channel/KNXChannelType.java
There are no spaces allowed in the GA configuration. And many users are
irritated because no errors or warnings are displayed but errors occur.
This little patch erases any spaces.
"7 .001 : 7/0/209 + < 7 / 0 / 208" -> "7.001:7/0/209+<7/0/208"
=> [KNX] replace spaces in GA config string

addons/binding/org.openhab.binding.mihome/ESH-INF/thing/basic.xml, addons/binding/org.openhab.binding.mihome/ESH-INF/thing/channel.xml, addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/XiaomiGatewayBindingConstants.java, addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/XiaomiHandlerFactory.java, addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/discovery/XiaomiItemDiscoveryService.java, addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/handler/XiaomiBridgeHandler.java, addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/handler/XiaomiDeviceBaseHandler.java
I just read of IKEA and Xiaomi partnering up on smart home solutions. As IKEA is also using Zigbee for it's current lineup, most likely in the future IKEA products will be able to speak to the Xiaomi gateway, adding more devices to the MiHome ecosystem and opening the chinese market for IKEA I guess. Also Xiaomi is expanding the MiHome lineup frequently.
Today, yet unsupported models have to be issued by users by searching through debug logs.
Also unsupported devices do not show up in the PaperUI inbox. So only advanced users can contribute with new model requests, even if there is a [tutorial how to do so](https://www.openhab.org/addons/bindings/mihome/#supporting-new-devices).
This PR is aiming to help discovering, analyzing and handling unsupported device models without the need to …
=> [MiHome] add basic thing type for yet unsupported models

addons/binding/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/handler/UplinkBaseHandler.java, addons/binding/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/connector/UplinkWebInterface.java
added additional checks to make sure that "NibeId" is correct
simplified handling of configuration. fixed issue where config changes during runtime were not applied without restart
=> [nibeuplink] improved handling of configuration / fixed handling of configuration updates

addons/binding/org.openhab.binding.network/ESH-INF/i18n/network_de.properties, addons/binding/org.openhab.binding.network/ESH-INF/thing/thing-types.xml
Fixes #3761.
Updates to the refresh interval in the UI are ignored because the thing type definitions were not updated after the configuration parameter variable names were renamed in #2580.
The affected Network Binding Things need to be removed/readded for the fix to work.
=> [network] Use refreshInterval in thing type definitions

addons/binding/org.openhab.binding.smartmeter.test/.classpath, addons/binding/org.openhab.binding.smartmeter.test/build.properties
Fixes the following warnings shown in Eclipse:
* Project 'org.openhab.binding.smartmeter.test' is missing required source folder: 'src/test/resources'
* The project cannot be built until build path errors are resolved
=> [smartmeter] Fix test build path

addons/io/org.openhab.io.hueemulation.test/src/test/java/org/openhab/io/hueemulation/internal/HueEmulationServiceOSGiTest.java, addons/io/org.openhab.io.hueemulation.test/src/test/java/org/openhab/io/hueemulation/internal/HueRestAPITest.java, addons/io/org.openhab.io.hueemulation.test/src/test/java/org/openhab/io/hueemulation/internal/LightItemsTest.java, addons/io/org.openhab.io.hueemulation/README.md, addons/io/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/HueEmulationService.java, addons/io/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/LightItems.java, addons/io/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/RESTApi.java, addons/io/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/UserManagement.java, addons/io/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/dto/HueAuthorizedConfig.java, addons/io/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/dto/HueDataStore.java, addons/io/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/dto/HueDevice.java, addons/io/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/dto/HueStateBulb.java, addons/io/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/dto/HueStateColorBulb.java, addons/io/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/dto/HueStatePlug.java, addons/io/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/dto/HueUserAuth.java, addons/io/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/dto/response/HueSuccessCreateGroup.java
Fixes:
* Fix user creation without a proposed username in the request. Incl. test
* Fix: The hue value was wrongly applied to the saturation field. Incl. test
* Fix usage of StorageService: Set the classloader
* Set the saturation to 0 if a ct (color temperature) value is set.
This is because Alexa only sets "ct" if you command her to turn the light white.
* Only call writeToFile in LightItems once, after all items have been
loaded up from the registry.
* Don't load items twice from the registry.
* Reload items whenever the tags configuration has changed.
* Allow group items
Features:
* Add troubleshoot section to readme.
Allow a pretty printed output for /api/{username}/lights?debug=true.
Tests:
* Add LightItems class unit tests for adding/updating items and group items
by category and …
=> Hue emulation: Fixes (user creation, storage service, turn light white)

addons/io/org.openhab.io.hueemulation.test/src/test/java/org/openhab/io/hueemulation/internal/HueEmulationServiceOSGiTest.java, addons/io/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/HueEmulationService.java, addons/io/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/RESTApi.java, addons/io/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/dto/HueDevice.java
* Add test that the troubleshoot view with ?debug=true works
* Use switch construct for HttpMethod if/else-branches.
* RestApi: Throw JSonException with proper error message instead of just
returning a 400 error. That way HueEmulationService can
return the exact error to the user and log a proper warning.
(400-errors only happen if the user is sending errornous json.)
I'm pretty sure, backed by the test suits, with this commit the hue emulation is in release quality now.
Signed-off-by: David Graeff <david.graeff@web.de>
=> Hue emulation: Don't use getParameter on a HttpServletRequest

addons/binding/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/discovery/MilightBridgeDiscovery.java, addons/binding/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/handler/BridgeV3Handler.java, addons/binding/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/protocol/MilightV6SessionManager.java
resolves #4232.
@TomaSpeed: I only tested it with emulated V3 bridges. Could you (or anybody else) test with the real ones? For convenience, I attached a snaphot build of the binding which contains the fix.
[org.openhab.binding.milight-2.4.0-SNAPSHOT.zip](https://github.com/openhab/openhab2-addons/files/2659957/org.openhab.binding.milight-2.4.0-SNAPSHOT.zip)
=> Milight: Use any free port instead of fixed port on client-side for bridge communication

addons/binding/org.openhab.binding.modbus/README.md
Thanks to rossko57: https://community.openhab.org/t/modbus-openhab2-binding-available-for-alpha-testing/27657/560?u=ssalonen
=> [modbus] Dimmer example

addons/binding/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/HDPowerViewWebTargets.java, addons/binding/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/requests/ShadeIdPosition.java, addons/binding/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/requests/ShadeMove.java
Fixes #3454
As the shade ID was cast as a string, the json encoder correctly added double quotes in the PUT message. This however, resulted in a 404 (see original bug report). Recasting as an int under a new variable resolves this. Note, changing this to an int in the referencing functions seems to break other things. 
Signed-off-by: tomdc01 
Tested on current version of HD PowerView 2 device. No regression testing at this point.
=> [HD PowerView] Fix quoted ID issue

addons/binding/org.openhab.binding.plclogo/ESH-INF/i18n/plclogo_de_DE.properties, addons/binding/org.openhab.binding.plclogo/ESH-INF/thing/analog.xml, addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/handler/PLCBridgeHandler.java, addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/handler/PLCCommonHandler.java, addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/internal/PLCLogoClient.java, addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/internal/config/PLCDateTimeConfiguration.java, addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/internal/config/PLCDigitalConfiguration.java, addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/internal/config/PLCLogoBridgeConfiguration.java, addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/internal/config/PLCMemoryConfiguration.java, addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/internal/config/PLCPulseConfiguration.java
@wborn Please, review.
Kind regards,
Alaxander.
=> [PLCLogo] Fix compiler warnings. (fixes #4335)

addons/binding/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/netutils/WebSocketConnection.java
The introduced "connected" flag was not used at all.
This worked in the very first version of the binding, because a new Websocket connection was established.
Now that a framework connection is used, the `client.isRunning()` will always return true.
Fixes #4355
=> Deconz: Fix: Websocket connection is never established

addons/binding/org.openhab.binding.gpstracker/ESH-INF/config/config.xml, addons/binding/org.openhab.binding.gpstracker/README.md, addons/binding/org.openhab.binding.gpstracker/src/main/java/org/openhab/binding/gpstracker/internal/config/ConfigHelper.java, addons/binding/org.openhab.binding.gpstracker/src/main/java/org/openhab/binding/gpstracker/internal/handler/TrackerHandler.java
Each distance channel now has an accuracyThreshold parameter. If the accuracy of the received GPS log record is above this threshold the binding skips the distance calculation and firing enter/leave event on the region trigger channel.
Setting 0 as threshold disables this check.
Closes #4362
Signed-off-by: Gabor Bicskei <gbicskei@gmail.com>
=> [gpstracker] Location accuracy threshold for distance channels

addons/binding/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/discovery/ThingDiscoveryService.java
I don't use the deconz binding and don't even know what it does. But after briefly looking at the code I think this change may help with fixing the OOM reported in #4361. WDYT @davidgraeff?
=> [deconz] Remove results field from ThingDiscoveryService to fix OOM

addons/binding/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/transceiver/EnOceanSerialTransceiver.java
Handle exceptions in calls to enableReceiveThreshold silently. Is needed for rfc2217 serial connections. Fixes #4371
=> [enocean] Handle exceptions for enableReceiveThreshold  silently

addons/binding/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/handler/EnOceanClassicDeviceHandler.java
The switch command of the virtualSwitchA channels is already converted into a StringType. However this result is not passed to the EEP. Therefore the "PRESSED" messages are not send by the ClassicDevice thing. This PR fixes #4373.
=> [enocean] Handle commands of virtualSwitchA channel correctly

addons/io/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/dto/HueDevice.java, addons/io/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/dto/HueStateBulb.java, addons/io/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/dto/HueStateColorBulb.java
This PR corrects #3171, which was flagged as resolved in #4216, but it was not. This change corrects errors introduced when doing arithmetic with integers. I have tested sending values to lights, by having Alexa set a dimmers level (0-10, 100). I have not tested the changes with colored lights, or states received by Alexa. @davidgraeff , please review!
Signed-off-by: Scott Rushworth openhab@5iver.com (github: openhab-5iver)
=> [Hue Emulation] Made corrections for integer arithmetic

addons/binding/org.openhab.binding.enocean/ESH-INF/thing/MechanicalHandle.xml, addons/binding/org.openhab.binding.enocean/ESH-INF/thing/channels.xml, addons/binding/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/EnOceanBindingConstants.java, addons/binding/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/A5_14/A5_14.java, addons/binding/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/A5_14/A5_14_09.java, addons/binding/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/EEPType.java
Signed-off-by: Dominik Krickl-Vorreiter <dominikkv@gmx.de> (github: dominikkv)
Eltako TF-FGB is a window handle addon that can detect the handle position: OPEN, CLOSED and TILT. It is powered by a battery. The EEP is A5-14-09 which contains two pieces of information: the handle position and battery voltage.
This PR adds the said EEP and enables the user to use the device.
Example DSLs:
Thing mechanicalHandle 05818C61 "Balkontüre" @ "Wohnzimmer" [ enoceanId="11223344", receivingEEPId="A5_14_09" ]
String c_handle_door_balkon_state "Balkontürgriff [%s]" <door> {channel="enocean:mechanicalHandle:usb300:11223344:windowHandleState"}
Contact c_handle_door_balkon_contact "Balkontür [%s]" <door> {channel="enocean:mechanicalHandle:usb300:11223344:contact"}
Number:ElectricPotential …
=> [enocean] Support Eltako TF-FGB

addons/binding/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/D2_01/D2_01.java
This PR fixes the parsing of SwitchingState messages of D2_01 EEPs.
=> [enocean] Parse SwitchingState messages of D2_01 EEPs correctly

addons/binding/org.openhab.binding.plugwise/META-INF/MANIFEST.MF, addons/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/PlugwiseBindingConstants.java, addons/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/PlugwiseCommunicationContext.java, addons/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/PlugwiseCommunicationHandler.java, addons/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/PlugwiseHandlerFactory.java, addons/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/PlugwiseMessageProcessor.java, addons/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/PlugwiseMessageSender.java, addons/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/PlugwiseStickDiscoveryService.java, addons/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/PlugwiseThingDiscoveryService.java, addons/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/PlugwiseUtils.java, addons/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/config/PlugwiseRelayConfig.java, addons/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/config/PlugwiseScanConfig.java, addons/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/config/PlugwiseSenseConfig.java, addons/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/handler/PlugwiseRelayDeviceHandler.java, addons/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/handler/PlugwiseStickHandler.java
In 2.4.0 an Inbox circular reference was fixed (https://github.com/eclipse/smarthome/issues/6216) by deprecating the `ExtendedDiscoveryService` and removing the functionality it provided.
As a result during background discovery the binding would request data from each and every node in the network instead of only the newly discovered nodes.
The increase in network traffic on the mesh resulted in Things going online/offline all the time. Also commands could be delayed or never executed.
Background discovery will now again skip existing Things registered with the associated Bridge to fix the stability issues. Other bindings using the `ExtendedDiscoveryService` may have similar issues.
Furthermore the code has been improved by:
* Removing the Guava dependency
* Replacing gnu.io with the …
=> [plugwise] Fix stability issues and some code improvements

addons/binding/org.openhab.binding.avmfritz/ESH-INF/thing/thing-types.xml, addons/binding/org.openhab.binding.avmfritz/README.md, addons/binding/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/AVMFritzBaseBridgeHandler.java
- Changed trigger channel type to `system.rawbutton` to allow the usage of the 'rawbutton-toggle-switch' profile
=> [avmfritz] Changed trigger channel type to 'system.rawbutton'

addons/binding/create_openhab_binding_skeleton.cmd, addons/binding/create_openhab_binding_skeleton.sh, addons/binding/create_openhab_binding_test_skeleton.cmd, addons/binding/create_openhab_binding_test_skeleton.sh
Signed-off-by: Hakan Tandogan <hakan@tandogan.com>
The skeleton generators create a new binding with version 2.4.0. Fixed.
=> Update skeleton binding and archetype versions to 2.5.0, 0.11.0

addons/binding/org.openhab.binding.feed/src/main/java/org/openhab/binding/feed/internal/handler/FeedHandler.java
Prevent the `publishChannelIfLinked` method from throwing null pointer exceptions when the feed has not provided dates.  (as reported in [this community thread](https://community.openhab.org/t/feed-binding-null-pointer-exception/60921/3))
Also cleaned up arrow code.
=> [Feed] Fix null pointer exceptions

addons/binding/org.openhab.binding.smartmeter/README.md
Not sure if "Smartreader" is correct here. The beginning of this sentence was anyhow redundant. Feel free to edit the PR content.
Signed-off-by: Thomas Dietrich <thomas.dietrich@tu-ilmenau.de>
=> [SmartMeter] Fix typo in first README sentence

addons/binding/org.openhab.binding.smartmeter/README.md
**clean:** removed duplicate info from smartmeter README.md
=> clean-smartmeter-readme

addons/binding/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/discovery/EnOceanUsbSerialDiscoveryParticipant.java
FTDI devices should not be treated as USB300 gateways any longer, except these devices are manufactured by "EnOcean GmbH"
Fixes #4421
=> [enocean] USB Discovery checks the manufacturer now too

addons/binding/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/handler/BridgeV3Handler.java
A change in the 2.4 binding resulted in the timeout for V3 keep-alive discovery packets changing from 1000ms to 300ms. In certain environments the response to a discovery packet is often greater than 300ms which resulted in the V3 bridge constantly going offline. This PR sets the timeout back to 1000ms. 
=> [milight] Fix timeout for V3 bridges which are slow to respond

addons/binding/org.openhab.binding.openuv/README.md, features/openhab-addons/src/main/feature/feature.xml
Hi,
I've tried yesterday to install the openUV addon. I could not find the addon from the list of add-ons and according to the [current documentation](https://www.openhab.org/addons/bindings/openuv/) it should be sufficient to just add the Bridge and the Items and the addon is configured.
The values were still empty and I found this discussion which pointed me into the right direction:
https://community.openhab.org/t/solved-location-of-openuv-binding/49200/3
The plugin can be found if you search for `opensprinkler`. Therefore it seems to be a copy&paste error when the `feature.xml` was touched. 
Here's a screenshot of how it currently looks in openHAB 2.4:
I've updated now the `feature.xml` to show the correct name of the addon "openUV" and also updated the binding's `readme.md` to make …
=> [openuv] Fix openUV addon name and installation instructions

addons/io/org.openhab.io.hueemulation/README.md
It was not clear from the documentation, that a group needs a tag as well as a base type in order to work with the hue emulation.
This is now mentioned in the documentation.
Co-Authored-By: Florian Schmidt <florian.schmidt.welzow@t-online.de>
=> [hueemulation] Mention that groups need a base type

addons/binding/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/OnkyoAlbumArt.java
This push request fixes an error with the **Onkyo TX-NR686** receiver displaying no image for the _albumArt_ channel (a broken image icon appears under Paper UI).
When parsing the _incorrect page headers_ that appear in the content of the album art page, the parser only looks for carriage returns after searching for the `image/` string; however on the **Onkyo TX-NR686** receiver, the headers are terminated with _Line Feeds_ instead of _Carriage Returns_.
The code has been modified to check for line feeds as well as carriage returns.
This has been built and tested locally and the fix successfully displays the artwork in the _albumArt_ channel correctly.
=> [onkyo] Fix error with album art not displaying correctly on Onkyo TX-NR686 models

addons/binding/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/MilightHandlerFactory.java, addons/binding/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/handler/AbstractBridgeHandler.java, addons/binding/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/handler/AbstractLedHandler.java, addons/binding/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/handler/BridgeV3Handler.java, addons/binding/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/handler/BridgeV6Handler.java
The unique command id generated for the global queue needs to take into
account the bridge. This is a fix for an issue introduced in the 2.4
binding when a single global queue was added.
=> [milight] Fix issue with commands being lost when using multiple bridges.

addons/binding/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/SensorThingHandler.java
Fixing a bug (no issue on GH), where on every reconnect calling the
valueUpdated-method also fires the buttonevent-trigger, which makes
using trigger on rules impossible, due to repeatedly firing false
positives.
For fixing this an initializing flag was added, to determine, whether a
button was actually pressed or bridge status just changed (most of the
time due to timeout reconnects)
Signed-off-by: Patrick Willnow <pwillnow@gmail.com> (github: @Hex-3-En)
=> [deconz] Fix: Buttonevent trigger refiring on each reconnect

addons/binding/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/A5_38/A5_38_08_Dimming.java, addons/binding/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/transceiver/EnOceanTransceiver.java
* Dimmer profile EEP A5_38_08 checks channelId not longer by reference, fixes #4541
* Message about adding an EnOcean listener is just posted if it is really added
=> [enocean] Dimmer not updated after openhab restart

addons/binding/org.openhab.binding.smartmeter/src/main/java/org/openhab/binding/smartmeter/internal/sml/SmlSerialConnector.java
Try to fix the read timeout which was reported in #4472 
Signed-off-by: Matthias Steigenberger <matthias.steigenberger@gmail.com>
=> [smartmeter] #4472 Added Flowcontrol settings and receive timeout

addons/binding/org.openhab.binding.airvisualnode/ESH-INF/thing/thing-types.xml, addons/binding/org.openhab.binding.airvisualnode/README.md
The binding has a few occurrences of the "Greek Small Letter Mu" (U+03BC) which may cause issues when copy/pasted. The "Micro sign" (U+00B5) should be used instead. 
See https://github.com/eclipse/smarthome/pull/6818.
=> [airvisualnode] Replace "Greek Small Letter Mu" with "Micro sign"

addons/binding/org.openhab.binding.exec/README.md
The default setting for `interval` is missing in the documentation for the exec-biniding, insert this.
(github has also converted encoding from ISO-8859-1 to UTF-8)
=> [exec] State default setting for interval

addons/binding/org.openhab.binding.icloud/README.md
Mapview is also available for Android and iOS applications.
Maybe another information that the parameter `height=X` is needed for Mapview to work in applications?
Signed-off-by: Michael Bredehorn <michael@bredehorn.nrw> (github: bredmich)
=> [iCloud] Update readme for Mapview usage in applications (Android/iOS)

addons/binding/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/handler/MilightV3RGBWHandler.java, addons/binding/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/handler/MilightV3WhiteHandler.java, addons/binding/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/handler/MilightV6RGBCWWWHandler.java, addons/binding/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/handler/MilightV6RGBIBOXHandler.java, addons/binding/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/handler/MilightV6RGBWHandler.java, addons/binding/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/protocol/ProtocolConstants.java
This is a fix for an issue introduced in the 2.4
binding which changed the queue category for white mode to be the same
as power commands. This change broke rules which changed the bulb back
to white before turning it off (in case it was subsequently turned on by
a manual switch) since the white mode command would be removed from the
send queue by the power off command.
Also fixed a long standing issue with V3 white bulbs which would not
turn on to 98% from off.
=> [milight] Fix issue with white mode commands being lost

addons/binding/org.openhab.binding.gpstracker/src/main/java/org/openhab/binding/gpstracker/internal/handler/TrackerHandler.java, addons/binding/org.openhab.binding.gpstracker/src/main/java/org/openhab/binding/gpstracker/internal/message/LocationMessage.java
Having accuracy set to its default 0, the disablement didn't work for me as the comparison of a double value with 0 is not safe. This PR fixes that.
Note that the code formatting has been also applied by my IDE - I have therefore split the PR into two commits, to make clear what I have actually changed about the code.
=> [gpstracker] Fixes the disablement of accuracy check

addons/binding/org.openhab.binding.deconz/ESH-INF/thing/thing-types.xml, addons/binding/org.openhab.binding.deconz/README.md, addons/binding/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/BindingConstants.java, addons/binding/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/dto/SensorState.java, addons/binding/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/SensorThingHandler.java
- Added util channels (e.g. `battery_level`, `battery_low` and `last_updated`)
- Added more light sensor channels (e.g. `lightlevel`, `dark` and `daylight`)
- Added check for the optional `dark` channel on presence sensors
Test version:
[org.openhab.binding.deconz-2.5.0-SNAPSHOT.jar.zip](https://github.com/openhab/openhab2-addons/files/2746191/org.openhab.binding.deconz-2.5.0-SNAPSHOT.jar.zip)
~I did not find the time to do a real test. Just threw in the code.~
Closes #4538
Closes #4524
=> [deconz] Added util channels (e.g. 'battery')

addons/binding/org.openhab.binding.smartmeter/src/main/java/org/openhab/binding/smartmeter/internal/sml/SmlSerialConnector.java
Final fix of timeout issue. Using a buffered stream fixes the performance issue. 
Fixes #4472
=> [smartmeter] Bugfix/4472 read timeout

addons/binding/org.openhab.binding.tplinksmarthome/ESH-INF/thing/HS100.xml, addons/binding/org.openhab.binding.tplinksmarthome/ESH-INF/thing/HS105.xml, addons/binding/org.openhab.binding.tplinksmarthome/ESH-INF/thing/HS110.xml, addons/binding/org.openhab.binding.tplinksmarthome/ESH-INF/thing/HS200.xml, addons/binding/org.openhab.binding.tplinksmarthome/ESH-INF/thing/HS210.xml, addons/binding/org.openhab.binding.tplinksmarthome/ESH-INF/thing/HS220.xml, addons/binding/org.openhab.binding.tplinksmarthome/ESH-INF/thing/KB100.xml, addons/binding/org.openhab.binding.tplinksmarthome/ESH-INF/thing/KB130.xml, addons/binding/org.openhab.binding.tplinksmarthome/ESH-INF/thing/KP100.xml, addons/binding/org.openhab.binding.tplinksmarthome/ESH-INF/thing/LB100.xml, addons/binding/org.openhab.binding.tplinksmarthome/ESH-INF/thing/LB110.xml, addons/binding/org.openhab.binding.tplinksmarthome/ESH-INF/thing/LB120.xml, addons/binding/org.openhab.binding.tplinksmarthome/ESH-INF/thing/LB130.xml, addons/binding/org.openhab.binding.tplinksmarthome/ESH-INF/thing/LB200.xml, addons/binding/org.openhab.binding.tplinksmarthome/ESH-INF/thing/LB230.xml, addons/binding/org.openhab.binding.tplinksmarthome/ESH-INF/thing/channels.xml
Changed channel type Id to system-wide channel type ids. See https://www.eclipse.org/smarthome/documentation/development/bindings/thing-definition.html#system-state-channel-types
=> [tplinksmarthome] Use system-wide channel type ids.

addons/binding/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/discovery/EnOceanDeviceDiscoveryService.java
The `ExtendedDiscoveryService` implementation seems unused and is deprecated. So I've removed it in this PR.
=> [enocean] Remove unused and deprecated ExtendedDiscoveryService implementation

CODEOWNERS
@clinique is neither using nor maintening the Freebox binding since few years. I do.
=> CODEOWNERS: Change for freebox binding

addons/binding/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/handler/BridgeV3Handler.java
Fixes #4609
An issue introduced in 2.4 meant that a V3 bridge could go offline and
remain offline following a router reboot.
Also tweaked the keep-alive logic to use 5 attempts with the delay between attempts ranging from 500ms to 2500ms. In my environment this keeps my bridges permanently online and resolves the 5-10 spurious offline/online blips I would see throughout the day.
=> [milight] Prevent V3 bridge getting stuck in the offline state.

addons/io/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/HueEmulationConfig.java
Add trimming so that a user can assign multiple tags, comma separated, with whitespace around the commas.
E.g. "Lighting, Switchable"
=> [Hueemulation] More lenient with tag configuration

addons/binding/org.openhab.binding.miio/README.md
According to the commit https://github.com/openhab/openhab2-addons/commit/5465eb2b90eb03421c07b0ca2b7df68a40419647#diff-eee65336c9e776e03bb70f74aecedddc the deviceId is required. Unfortunately, the parameter is an advanced one, which makes it not that obvious, that this one is missing (when configured in textual configuration at least). Marking it as required in the documentation seems reasonable here.
Signed-Off-By: Florian Schmidt <florian.schmidt.welzow@t-online.de>
=> [miio] Reflect deviceId being required as in the actual implementation

features/openhab-addons/src/main/feature/feature.xml
As the Maven GAVs were still incorrect after https://github.com/openhab/openhab2-addons/pull/4645...
=> fixed artifactIds of UIs

addons/binding/org.openhab.binding.loxone/META-INF/MANIFEST.MF, addons/binding/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/LoxoneHandlerFactory.java
=> [loxone] Removed Guava dependency

addons/binding/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/D5_00/D5_00_01.java
Fixes channel name comparison by reference (String). Should be done by value.
Signed-off-by: Dominik Krickl-Vorreiter dominikkv@gmx.de
closes #4580
See https://github.com/fruggy83/openocean/pull/55
=> [enocean] Fixes channel comparison in D5-00-01

addons/binding/org.openhab.binding.mqtt/README.md
The 'secure' configuration parameter can be either true or false, not ON/OFF/AUTO.
Fixes  https://github.com/openhab/openhab-docs/issues/880
=> [mqtt] Fix the description of the secure parameter

addons/binding/org.openhab.binding.modbus/META-INF/MANIFEST.MF, addons/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusBindingConstants.java, addons/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusBindingConstantsInternal.java, addons/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/handler/AbstractModbusEndpointThingHandler.java, addons/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/handler/EndpointNotInitializedException.java, addons/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/handler/ModbusDataThingHandler.java, addons/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/handler/ModbusEndpointThingHandler.java, addons/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/handler/ModbusPollerThingHandlerImpl.java
=> [modbus] Made constants and handler packages internal

addons/binding/org.openhab.binding.modbus/META-INF/MANIFEST.MF, addons/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/ModbusBindingConstants.java, addons/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/handler/EndpointNotInitializedException.java, addons/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/handler/ModbusEndpointThingHandler.java, addons/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusBindingConstantsInternal.java, addons/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/handler/AbstractModbusEndpointThingHandler.java, addons/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/handler/ModbusDataThingHandler.java, addons/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/handler/ModbusPollerThingHandlerImpl.java
Reverts #4685.
As @mrbig [pointed out](https://github.com/openhab/openhab2-addons/pull/4685#issuecomment-457407781) the exported packages are there so they can be used in https://github.com/openhab/openhab2-addons/pull/4220. Sorry for making them internal again! 
We'd best review/merge https://github.com/openhab/openhab2-addons/pull/4220 so whenever we make them internal it results in build errors. :wink:
=> Revert 4685 modbus internal

addons/binding/org.openhab.binding.onewire.test/src/test/java/org/openhab/binding/onewire/test/AbstractThingHandlerTest.java, addons/binding/org.openhab.binding.onewire/README.md, addons/binding/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/DigitalIoConfig.java, addons/binding/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/device/AbstractDigitalOwDevice.java, addons/binding/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/handler/AdvancedMultisensorThingHandler.java, addons/binding/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/handler/BasicMultisensorThingHandler.java, addons/binding/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/handler/EDSSensorThingHandler.java, addons/binding/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/handler/OwBaseBridgeHandler.java, addons/binding/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/handler/OwBaseThingHandler.java
This will fix the "digital I/O does not respect inverted setting on write" bug, reported [here](https://community.openhab.org/t/solved-onewire-binding-digitalio-output-is-inverted/65171) and a thing initialization problem found in the same thread. Also makes documentation more clear for upgrading thing-types.
=> [OneWire] fix digital I/O and initialization

addons/binding/org.openhab.binding.squeezebox/README.md, addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxPlayerHandler.java, addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxPlayerState.java, addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxServerHandler.java
Fixes #4653
- Add basic authentication to the download URL for LMS-served covert art images when LMS authentication is enabled. 
- Ensure that the password is not logged in the openHAB log file.
- Add private to SqueezeBoxPlayerState fields.
Note that there are now a number of new SAT warnings, which were not there before. I presume this is because new SAT checks were added. I will fix these in a separate PR.
=> [squeezebox] Fix local cover art download failure when auth enabled

features/openhab-addons/src/main/feature/feature.xml
As a result of the move of the ESH addons to openhab, the map transform dependency needs to be updated.
=> [globalcache] Fix dependency on map transform in feature.xml

addons/ui/org.openhab.ui.paper/pom.xml
Fixes the following warning:
```
[WARNING] Some problems were encountered while building the effective model for org.openhab.ui:org.openhab.ui.paper:eclipse-plugin:2.5.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-clean-plugin is missing. @ org.openhab.ui:org.openhab.ui.paper:[unknown-version], /home/wouter/git/openhab/openhab2-addons/addons/ui/org.openhab.ui.paper/pom.xml, line 19, column 15
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
```
=> [paper] Fix missing maven-clean-plugin version warning

addons/binding/org.openhab.binding.airquality/README.md
Added how to find the stationId to the Air Quality Binding documentation. After a long search and a question on the community forum. 
Only a single line of the documentation changed, but it will sure help others save time :-)
=> [airquality] Added how to find the stationId to the documentation

CODEOWNERS
- Added myself to be a CODEOWNERS for the Kodi binding
=> Added myself to be a CODEOWNERS for the Kodi binding

addons/binding/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/discovery/NetworkDiscoveryService.java
=> [network] fix discovery service

addons/binding/org.openhab.binding.hue.test/src/test/java/org/openhab/binding/hue/internal/handler/HueLightHandlerTest.java, addons/binding/org.openhab.binding.hue/ESH-INF/i18n/hue.properties, addons/binding/org.openhab.binding.hue/ESH-INF/thing/ColorLight.xml, addons/binding/org.openhab.binding.hue/ESH-INF/thing/ColorTemperatureLight.xml, addons/binding/org.openhab.binding.hue/ESH-INF/thing/DimmableLight.xml, addons/binding/org.openhab.binding.hue/ESH-INF/thing/DimmablePlug.xml, addons/binding/org.openhab.binding.hue/ESH-INF/thing/ExtendedColorLight.xml, addons/binding/org.openhab.binding.hue/META-INF/MANIFEST.MF, addons/binding/org.openhab.binding.hue/README.md, addons/binding/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/FullLight.java, addons/binding/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/HueBindingConstants.java, addons/binding/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/StateUpdate.java, addons/binding/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/action/LightActions.java, addons/binding/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueLightHandler.java
Implemented fade time config for light things.
Implemented fade time channel for dynamically changing the fade times of light things.
Bug: #1722
Signed-off-by: Jochen jochen.leopold@model-view.com
=> [hue] Add support for TransitionTime

addons/binding/org.openhab.binding.groheondus/.classpath, addons/binding/org.openhab.binding.groheondus/ESH-INF/thing/thing-types.xml, addons/binding/org.openhab.binding.groheondus/META-INF/MANIFEST.MF, addons/binding/org.openhab.binding.groheondus/README.md, addons/binding/org.openhab.binding.groheondus/build.properties, addons/binding/org.openhab.binding.groheondus/src/main/java/org/openhab/binding/groheondus/internal/GroheOndusBindingConstants.java, addons/binding/org.openhab.binding.groheondus/src/main/java/org/openhab/binding/groheondus/internal/handler/GroheOndusBaseHandler.java, addons/binding/org.openhab.binding.groheondus/src/main/java/org/openhab/binding/groheondus/internal/handler/GroheOndusSenseGuardHandler.java, addons/binding/org.openhab.binding.groheondus/src/main/java/org/openhab/binding/groheondus/internal/handler/GroheOndusSenseHandler.java
The waterconsumption is a combined metric of the total consumed water
registered by the grohe sense guard. The channel allows you to get the
value of a specific timeframe (in days) from 1 to up to 90 days (the 90
days is a restriction of the api).
This also fixes (by an update of the api library) the issue of
deserializing an array to an actual appliance.
Fixes #4554
=> [groheondus] Export the waterconsumption value of the grohe sense guard

addons/binding/org.openhab.binding.yeelight/ESH-INF/thing/desklamp.xml, addons/binding/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/YeelightBindingConstants.java, addons/binding/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/YeelightHandlerFactory.java, addons/binding/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/discovery/YeelightDiscoveryService.java, addons/binding/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/handler/YeelightHandlerBase.java, addons/binding/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/device/DesklampDevice.java, addons/binding/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/device/DeviceFactory.java, addons/binding/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/device/MethodFactory.java, addons/binding/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/enums/DeviceType.java, addons/binding/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/services/DeviceManager.java
This PR should provide basic functions of the desklamp, like the ceeling light
I have a desklamp at home and want to include it into my openhab environment
Fixes #4452
=> [yeelight] Add basic support for yeelight desklamp

addons/binding/org.openhab.binding.openweathermap/ESH-INF/thing/channel-types.xml, addons/binding/org.openhab.binding.openweathermap/README.md
This is applied to every forecast, no matter how far in the future.
=> Remove static "for the next 3 hours" text

addons/binding/org.openhab.binding.miio/database/chuangmi.plug.m1.json, addons/binding/org.openhab.binding.miio/database/zhimi.airmonitor.v1.json, addons/binding/org.openhab.binding.miio/database/zhimi.fan.v3.json, addons/binding/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoDevices.java, addons/binding/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/MiIoBasicChannel.java, addons/binding/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoBasicHandler.java, addons/binding/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/robot/StatusType.java, addons/binding/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/transport/MiIoAsyncCommunication.java
- Fix error for devices with battery channel
- Add chungmi plug m3
- minor edits
=> [miio] Fix issue battery channel

addons/binding/org.openhab.binding.mqtt.generic/README.md
Add example and clarify the differences when using a bridged setup for the MQTT broker or a non-bridge setup (broker as a stand alone Thing). I also fixed a missing " in the MQTT 1.x heat pump example...
Signed-off-by: Garrett Porter hotmail.yahoo@icloud.com
=> [MQTT Generic] update documentation

addons/binding/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/handler/TradfriGatewayHandler.java
As discussed in eclipse/smarthome#6065 the tradfri gateway does not support a session resumption after a gateway reboot or other communcation errors.
@boaks implemented changes in californium scandium:
Californium 1.0.7 is able to force a full handshake instead.
This change calls "forceResumeSessionFor" after a communication error, so that a full handshake is done.
Related discussion: https://github.com/eclipse/smarthome/issues/6065#issuecomment-452752073
Californium 1.0.7 version bump: openhab/openhab-core#475
=> [Tradfri] Force session resume after communication errors

addons/binding/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/owserver/OwserverConnection.java
Fixes a NumberFormatException if the string returned from the owserver could not be parsed to a DecimalType.
Reported [in the forum](https://community.openhab.org/t/new-onewire-binding-bms-sensor-working-for-a-few-hours-seperate-temperature-sensor-dss18x20-not-initializing/64203/24).
=> [onewire] fix NumberFormatException

addons/binding/org.openhab.binding.openweathermap/README.md
- Fixed spelling of channel id in example
=> [openweathermap] Fixed spelling of channel id in example

addons/binding/org.openhab.binding.openweathermap/ESH-INF/i18n/openweathermap_de.properties, addons/binding/org.openhab.binding.openweathermap/ESH-INF/i18n/openweathermap_fr.properties, addons/binding/org.openhab.binding.openweathermap/README.md
- Fixed and improved translations
- Fixed spelling mistakes
=> [openweathermap] Fixed and improved translations

addons/binding/org.openhab.binding.sonos/ESH-INF/thing/Beam.xml, addons/binding/org.openhab.binding.sonos/ESH-INF/thing/CONNECT.xml, addons/binding/org.openhab.binding.sonos/ESH-INF/thing/CONNECTAMP.xml, addons/binding/org.openhab.binding.sonos/ESH-INF/thing/One.xml, addons/binding/org.openhab.binding.sonos/ESH-INF/thing/PLAY1.xml, addons/binding/org.openhab.binding.sonos/ESH-INF/thing/PLAY3.xml, addons/binding/org.openhab.binding.sonos/ESH-INF/thing/PLAY5.xml, addons/binding/org.openhab.binding.sonos/ESH-INF/thing/PLAYBAR.xml, addons/binding/org.openhab.binding.sonos/ESH-INF/thing/PLAYBASE.xml, addons/binding/org.openhab.binding.sonos/ESH-INF/thing/ZonePlayer.xml
Added missing playlinein channel to things.xml for Play1,Play3, One & ZonePlayer. As this is no longer an extended channel the channel has been moved to the correct location in the xml on the other players
=> [sonos] Added missing playlinein channel on Play1,Play3,One,ZonePlayer

addons/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/handler/ModbusDataThingHandler.java
Fixes sloppy modification based on [code review comment](https://github.com/openhab/openhab2-addons/pull/4701#discussion_r251032820) (which was valid on its own) from a maintainer, which lead to [situation that "time of last update" was not kept up-to-date](https://github.com/openhab/openhab2-addons/pull/4701/commits/e13e893af3b30d89c66856dc21b3dda72fb440fd).
cc @martinvw 
=> [modbus] update time-of-last-update

addons/binding/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/PresenceDetection.java
=> [Network] Present used arping tool to user

addons/binding/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/utils/NetworkUtils.java
The content of the arping tool result is a multi line string. matches() returns true, when the whole
string matches against the regex, thus we need to switch to DOTALL mode by using (?s)
inside the regex.
=> [Network] Fix regex for tool recognition

addons/ui/org.openhab.ui.homebuilder/web/.gitignore
- Added removed files / folder to .gitignore
Related to #4814 
// CC @wborn
=> [homebuilder] Added removed files / folder to .gitignore

features/openhab-addons/src/main/feature/feature.xml
- Reordered features neato and netatmo
- Removed dependency on commons-net (see https://github.com/openhab/openhab-core/pull/545)
- Changed feature dependencies to openHAB Core
@kaikreuzer Might I ask you for review? I am not sure if I did it right. Thanks.
=> Changed feature dependencies to openHAB Core

features/openhab-addons/src/main/feature/feature.xml
Fixes https://github.com/openhab/openhab-distro/issues/865
Fixes #4841
=> fixed automation feature references

addons/ui/org.openhab.ui.basic/META-INF/MANIFEST.MF, addons/ui/org.openhab.ui.paper/META-INF/MANIFEST.MF
This fixes those exceptions that I found in my log:
```
org.osgi.framework.BundleException: The bundle class path entry "patch/" could not be found for the bundle "osgi.identity; osgi.identity="org.openhab.ui.basic"; type="osgi.bundle"; version:Version="2.5.0.201902092017""
at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findClassPathEntry(ClasspathManager.java:174) ~[?:?]
at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.buildClasspath(ClasspathManager.java:152) ~[?:?]
at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.<init>(ClasspathManager.java:81) ~[?:?]
```
=> removed patch folder from classpath

addons/binding/org.openhab.binding.network/META-INF/MANIFEST.MF, addons/binding/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/utils/NetworkUtils.java
Fixes #3145 
Large networks (like /8) caused an OOM exception because 16 million IP addresses were cconstructed during network discovery. This reduces the network size to the number of requested addresses (usually 255 which results in /24).
Verified locally.
=> [Network] fix oom bug

addons/binding/org.openhab.binding.network.test/src/test/java/org/openhab/binding/network/internal/PresenceDetectionTest.java, addons/binding/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/NetworkBindingConfiguration.java, addons/binding/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/PresenceDetection.java, addons/binding/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/discovery/NetworkDiscoveryService.java, addons/binding/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/handler/NetworkHandler.java
Currently the arping method is determined for each address. This PR caches the method determination.
=> [network] fixes excessive testing of arping method during discovery

addons/binding/org.openhab.binding.dscalarm/README.md
Please always use the object method instead of the static method. This is safer and less confusing for newcomers. See https://www.openhab.org/docs/configuration/rules-dsl.html#manipulating-item-states
=> [dscalarm] Update README.md

addons/binding/org.openhab.binding.wifiled/README.md
Changed indention to ``` for better readability on openhab.org
=> [wifiled] Update README.md

addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxServerHandler.java
My previous fix #4654 for retrieving cover art from LMS with authentication failed to deal with user ids and passwords that contain special characters. This PR encodes the userid and password parts of the cover art URL.
=> [squeezebox] Url encode userid and password in cover art URL

addons/binding/org.openhab.binding.miio/README.md
=> [miio] update readme

addons/binding/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/TradfriColor.java, addons/binding/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/model/TradfriLightData.java
- Aligned rounding for brigthness values
Sending 1% from OH to TRADFRI results in 2% on next update
See https://community.openhab.org/t/off-by-1-value-in-events-with-tradfri-dimmer-levels/67568
=> [tradfri] Aligned rounding for brightness values

addons/binding/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/TeslaChannelSelectorProxy.java
Signed-off-by: Christian Güdel <cg@dmesg.ch>
=> [tesla] Fixes #4230: Chargecable channel is a string, not a decimal.

addons/binding/org.openhab.binding.chromecast.test/src/test/java/org/openhab/binding/chromecast/internal/handler/ChromecastOSGiTest.java, addons/binding/org.openhab.binding.chromecast/ESH-INF/thing/thing-types.xml, addons/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromecastBindingConstants.java, addons/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/discovery/ChromecastDiscoveryParticipant.java
- Removed representational property
> The way the groups work is they are virtual on the audio. So the same ip will be listed multiple times under different things.
See https://community.openhab.org/t/chromecast-binding-how-to-send-stopmovetype/63547/16
Fixed #4186 
=> [chromecast] Use device ID as representational property

addons/binding/org.openhab.binding.chromecast/ESH-INF/i18n/chromecast_de.properties, addons/binding/org.openhab.binding.chromecast/ESH-INF/thing/thing-types.xml, addons/binding/org.openhab.binding.chromecast/README.md, addons/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromecastBindingConstants.java, addons/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromecastCommander.java, addons/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromecastEventReceiver.java, addons/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromecastStatusUpdater.java, addons/binding/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/handler/ChromecastHandler.java
- Added dedicated channel to stop playback
- Removed handling of `StopMoveType` from `control` channel
Closes #1783
Closes #4794
Test version:
[org.openhab.binding.chromecast-2.5.0-SNAPSHOT.jar.zip](https://github.com/openhab/openhab2-addons/files/2855457/org.openhab.binding.chromecast-2.5.0-SNAPSHOT.jar.zip)
=> [chromecast] Added dedicated channel to stop playback

.github/ISSUE_TEMPLATE/usage_question.md
Stack Overflow is for a specific target group and for source code related questions: https://stackoverflow.com/help/on-topic So I would not advice people to visit stack overflow for 'usage' questions.
=> Removed stackoverflow from 'usage' template

addons/binding/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/Connection.java
This PR fixes a problem where routines can not be started, if the user have more than 20 routines defined in alexa app.
=> [amazonechocontrol] Fix for the startRoutine channel if more than 20 routines are defined

addons/io/org.openhab.io.webaudio/README.md
=> [webaudio] Readme

addons/binding/org.openhab.binding.keba/ESH-INF/binding/binding.xml, addons/binding/org.openhab.binding.tesla/ESH-INF/binding/binding.xml
=> removed superfluous "openHAB" in name and fixed typos

addons/binding/org.openhab.binding.meteoblue/README.md
Fixes #4924. See also [this community thread](https://community.openhab.org/t/new-meteoblue-binding-no-icon/66143).
Signed-off-by: Chris Carman <namraccr@gmail.com>
=> [meteoblue] Update README with new section on image icon usage

addons/binding/org.openhab.binding.nibeuplink/ESH-INF/thing/base-channel-groups.xml, addons/binding/org.openhab.binding.nibeuplink/ESH-INF/thing/base-channel-types.xml, addons/binding/org.openhab.binding.nibeuplink/ESH-INF/thing/f1145-channel-groups.xml, addons/binding/org.openhab.binding.nibeuplink/ESH-INF/thing/f1145-channel-types.xml, addons/binding/org.openhab.binding.nibeuplink/ESH-INF/thing/f1155-channel-groups.xml, addons/binding/org.openhab.binding.nibeuplink/ESH-INF/thing/f1155-channel-types.xml, addons/binding/org.openhab.binding.nibeuplink/ESH-INF/thing/vvm310-channel-groups.xml, addons/binding/org.openhab.binding.nibeuplink/ESH-INF/thing/vvm310-channel-types.xml, addons/binding/org.openhab.binding.nibeuplink/ESH-INF/thing/vvm320-channel-groups.xml, addons/binding/org.openhab.binding.nibeuplink/ESH-INF/thing/vvm320-channel-types.xml, addons/binding/org.openhab.binding.nibeuplink/README.md, addons/binding/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/model/BaseChannels.java, addons/binding/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/model/F1145Channels.java, addons/binding/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/model/F1155Channels.java, addons/binding/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/model/VVM310Channels.java, addons/binding/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/model/VVM320Channels.java
added new channels for different models:
all models: 43437, 47043, 47044, 47045, 47046, 47047, 47048, 47049
removed channel 43437 from VVM310/VVM320 as it is now a base channel available for all models
F1145: 44270, 43103, 40015, 40016, 43439
F1155: 40015, 40016, 43439
VVM320: 47374, 47375, 47376, 47377
=> [Nibeuplink] extended available channels for different models

addons/binding/org.openhab.binding.lutron/ESH-INF/thing/thing-types.xml, addons/binding/org.openhab.binding.lutron/README.md, addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/BaseKeypadHandler.java, addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/KeypadHandler.java
Hi.  This PR contains two minor changes to the Lutron keypad handler code.
The first adds support for Lutron seeTouch CL hybrid keypad models: HN1RLD, HN2RLD, HN3S, HN3BSRL, HN4S, HN5BRL, HN6BRL. Their configurations simply map to the corresponding older keypad models: H1RLD, H2RLD, H3S, H3BSRL, H4S, H5BRL, H6BRL.
The second fixes an issue reported by some users where with some keypad/system model combinations a keypad button channel can become stuck in the on (pressed) state when a user holds down a button.
Regards,
Bob
Closes #4484
Closes #4982
=> [Lutron] Add new model support and button hold fix to keypad handler

addons/io/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudService.java
=> [openhabcloud] Adds "configurationPid" to the CloudService component annotation

addons/binding/org.openhab.binding.keba/README.md, addons/binding/org.openhab.binding.keba/src/main/java/org/openhab/binding/keba/internal/KebaBindingConstants.java, addons/binding/org.openhab.binding.keba/src/main/java/org/openhab/binding/keba/internal/handler/KeContactHandler.java, addons/binding/org.openhab.binding.keba/src/main/java/org/openhab/binding/keba/internal/handler/KeContactTransceiver.java
Fixes https://github.com/openhab/openhab2-addons/issues/3328
Note that this PR only removes the check for specific firmware versions (which imho does not make much sense as this info is nowhere used and in general it is better to assume that Keba does not break backward compatibility when releasing newer firmwares).
I cannot say whether or not this binding works correctly with newer firmwares, though, but if there are problems, we should open dedicated issues about them.
=> [Keba] Removed check of firmware version

addons/binding/org.openhab.binding.onkyo/META-INF/MANIFEST.MF, addons/binding/org.openhab.binding.onkyo/README.md, addons/binding/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/automation/modules/OnkyoThingActionsService.java, addons/binding/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/handler/OnkyoHandler.java
I've added a thing action to the Onkyo binding to send raw eISCP commands to the receiver to support commands that are not built in as channels. I e.g. use this to adjust the volume of the center speaker.
Here is the link to the forum thread I created for this: https://community.openhab.org/t/onkyo-testers-for-thing-action-to-send-raw-eiscp-commands/68446
Please see the chapter “Rule Actions” in the readme how to use this: https://github.com/TheNetStriker/openhab2-addons/tree/OnkyoThingAction/addons/binding/org.openhab.binding.onkyo
Signed-off-by: David Masshardt <david@masshardt.ch>
=> [Onkyo] Thing action to send raw eISCP commands

addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/discovery/LutronDeviceDiscoveryService.java, addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/discovery/project/OutputType.java
Hi. This PR contains a small commit which enhances RadioRA 2 device auto-discovery support by adding several new output device types. Note that output types SHEER_BLIND and VENETIAN_BLIND do not yet map to a handler, but are added to OutputType for completeness.
Regards,
Bob
=> [lutron] Add new output device types to RA2 auto-discovery code

addons/transform/org.openhab.transform.jinja/.classpath, addons/transform/org.openhab.transform.jinja/build.properties
After setting up the IDE for add-on development, I noticed some build path errors of the `org.openhab.transform.jinja` bundle in Eclipse. 
This PR is intended to solve these build path errors by adapting the `.classpath`/`build.properties` files so that the non-existing `src/main/resource` directory is no longer referenced.
Signed-off-by: Hannes Hofmann <hannes.hofmann92@gmail.com>
EDIT: Force-pushed to amend signed-off signature.
=> Fix build path errors of Jinja addon by adapting build resource files

addons/binding/org.openhab.binding.mcp23017/README.md
Without this dependency the pi4j library did not work on my Raspberry Pi Model 3 B+.
Unfortunately there is another issue Pi4J/pi4j#319 which can be resolved by updating to pi4j release 1.2 (not yet released).
Supersedes #4806.
// CC @mrumpf 
Also-by: Michael Rumpf <michael@rumpfonline.de> (github: mrumpf)
=> [mcp23017] Added hint to the wiringPi library

addons/binding/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/DenonMarantzStateChangedListener.java, addons/binding/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/connector/http/DenonMarantzHttpConnector.java, addons/binding/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/handler/DenonMarantzHandler.java
I have experienced several issues with how the binding  is maintaining it's connection state and polling, the first issue is that the handler would create a new instance of its connection object when initalized without stopping or disposing the old one, this would create havac as the polling code would continue to run and conflict with the shared state model that is use between them.
Second is that the HTTP connection code did not handle exceptions well and would set the binding to offline on the first failed attempt but then continue to make more requests, once a request was successful, nothing would tell the binding to go back online if the state had not changed during the network outage (which is very likely) .
=> [denonmarantz] Refactors reconnection logic

addons/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/PlugwiseUtils.java
When this code was written the `ZonedDateTime` constructor wasn't there yet.
Now we can just pass the `ZonedDateTime` value to the constructor. :-)
=> [plugwise] Fix DateTimeType constructor deprecation

addons/binding/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueLightHandler.java
- `setTransitionTime(`) not for ON/OFF commands
The transition time has no effects on the "state" `{"on":true/false}` property but results in a not expected brightness values.
Fixes #4996
=> [hue] setTransitionTime() not for ON/OFF commands

addons/binding/org.openhab.binding.homematic.test/src/test/java/org/openhab/binding/homematic/internal/converter/ConvertFromBindingTest.java
- Fixed wrong usage of HERTZ, should be from SmartHomeUnits.
- Added tec.uom.se to nest test. For some reasons with the changes in core units the compiler fails on NestThermostatHandlerTest. It's related to the static imports.
Related to https://github.com/openhab/openhab-core/pull/617
=> Fixed usages of units.

addons/binding/org.openhab.binding.modbus/README.md
removed node id values as they caused confusion. See #4930  for details
Corrected one internal link
Signed-off-by: Wolfgang Klimt <github@klimt.de> (github: @Wolfgang1966 )
Fixes #4930
=> [modbus] Improve migration documentation

addons/binding/org.openhab.binding.tplinksmarthome/ESH-INF/thing/HS103.xml, addons/binding/org.openhab.binding.tplinksmarthome/README.md, addons/binding/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/TPLinkSmartHomeThingType.java
This plug (thing) is simply a smaller version of the existing HS105 module (12A versus 15A). It follows the same protocol.
Follow up to #5001
First PR, still getting my head wrapped around this build system.
Signed-off-by: Gus Grubba gus@grubba.com (github: dogmaphobic)
=> [tplinksmarthome] Adding support for TP-Link HS103 Smart Wi-Fi Plug Mini

addons/binding/org.openhab.binding.tplinksmarthome/ESH-INF/thing/HS200.xml, addons/binding/org.openhab.binding.tplinksmarthome/ESH-INF/thing/HS210.xml, addons/binding/org.openhab.binding.tplinksmarthome/ESH-INF/thing/HS220.xml, addons/binding/org.openhab.binding.tplinksmarthome/README.md
Technically they supported it, but it was not in the thing definition xml.
Updated documentation. It missed any information about the led channel. And some readability improvements of the readme.
=> [tplinksmarthome] Added led channel to HS2xx switches.

CODEOWNERS
Updates the CODEOWNERS file for the migrations in #5018 and #5050.
=> Update CODEOWNERS for Astro and AVM Fritz bnd migrations

.travis.yml, pom.xml, poms/tycho/pom.xml
It currently doesn't seem to be an issue to use both bnd and tycho in the same reactor. So if this also works with Jenkins this would be a good simplification.
See https://github.com/openhab/openhab2-addons/pull/5018#issuecomment-471173379
=> Use one reactor for bnd and tycho builds

addons/binding/org.openhab.binding.chromecast/README.md
Clarification on the manual thing configuration, audio groups concerning. I determined the port with "iobroker".
See also: https://community.openhab.org/t/solved-chromecast-audiogroup-unable-to-play-stream-on-group/67059
=> [chromecast] Manual Thing Configuration, Port of chromecast audio group is necessary

addons/binding/org.openhab.binding.zway/README.md
Tried to fix the broken image on openhab.org by changing the relative path to image to an absolute one.
=> [zway] Update README.md

addons/binding/org.openhab.binding.dwdunwetter.test/pom.xml
Fixes the following warning when building with Maven:
```
[WARNING] Some problems were encountered while building the effective model for org.openhab.binding:org.openhab.binding.dwdunwetter.test:eclipse-test-plugin:2.5.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.eclipse.tycho:target-platform-configuration is missing. @ org.openhab.binding:org.openhab.binding.dwdunwetter.test:[unknown-version], /home/wouter/git/openhab/openhab2-addons/addons/binding/org.openhab.binding.dwdunwetter.test/pom.xml, line 20, column 15
[WARNING] 'build.plugins.plugin.version' for org.eclipse.tycho:tycho-surefire-plugin is missing. @ org.openhab.binding:org.openhab.binding.dwdunwetter.test:[unknown-version], /home/wouter/git/openhab/openhab2-addons/addons/binding/org.openhab.binding.dwdunwetter.tes …
```
=> [dwdunwetter] Fix build.plugins.plugin.version is missing warning

addons/binding/org.openhab.binding.openweathermap/ESH-INF/i18n/openweathermap_de.properties, addons/binding/org.openhab.binding.openweathermap/ESH-INF/i18n/openweathermap_fr.properties, addons/binding/org.openhab.binding.openweathermap/ESH-INF/thing/channel-types.xml, addons/binding/org.openhab.binding.openweathermap/README.md, addons/binding/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/connection/OpenWeatherMapConnection.java, addons/binding/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/handler/OpenWeatherMapWeatherAndForecastHandler.java, addons/binding/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/model/base/Rain.java, addons/binding/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/model/base/Snow.java
- Renamed cache folder
- Prioritize '1h' and divide '3h' by three to always have an estimated value for one hour
Closes #5058
=> [openweathermap] Consider "1h" property for precipitation

poms/tycho/pom.xml
With this configuration change it seems possible to use SAT when building at root level as well as  individual project level. See comments in https://github.com/openhab/openhab2-addons/pull/5072.
=> Fix running SAT in non-root dir

poms/bnd/pom.xml, poms/tycho/pom.xml
The addons injects the openHAB snapshot repository with a update policy set to always. This slows done the build as all the time every snapshot dependency is checked using external repository look up.
Repositories are also transitive, so every other reactor that includes an addon is affected.
This change does not affect the normal behavior but it allows to disable the snapshot repository usage by defining the "noOhSnapRepo" property on build time.
=> allow to disable openHAB snapshot repository

addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/MappingJsonReader.java, addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/tools/JsonReaderDelegate.java
SAT fails the build because files without headers were commited in #5065. 
Jenkins didn't fail because it only said ["Hello..."](https://ci.openhab.org/job/PR-openHAB2-Addons/12994/console).
=> [mqtt] Fix build by adding missing headers

addons/binding/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/handler/DaikinAcUnitHandler.java
[Daikin] Fix exceptions due to not checking the type of commands
Add type checking on the commands received in the Daikin addon to eliminate exceptions due to bad type conversions. This fixes an issue brought up in the end of https://github.com/openhab/openhab2-addons/pull/3044.
Signed-off-by: Tim Waterhouse <tim@timwaterhouse.com>
=> [daikin] Fix exceptions due to not checking the type of commands

addons/binding/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/handler/DaikinAcUnitHandler.java
[daikin] Fix rounding for set point temperature
The Daikin systems reject any temperatures which are not whole or half degrees in Celcius. When the code was switched to UoM the rounding logic that ensured the numbers were valid was lost. The Daikin system simply silently ignores any unexpected values so no errors are shown, the temperature just won't be changed. This is exceptionally pronounced on Fahrenheit since degrees Fahrenheit pretty much never result in a whole or half degree when converted to Celsius.
Signed-off-by: Tim Waterhouse <tim@timwaterhouse.com>
=> [daikin] Fix rounding for set point temperature

addons/binding/org.openhab.binding.mqtt.generic/README.md
The original rule doesn't work as it includes part in the string that don't belong to the item name giving this error
```
2019-03-17 19:22:13.017 [vent.ChannelTriggeredEvent] - mqtt:broker:MQTTBroker:myTriggerChannel triggered allItems/LichterketteFenster#ON
==> /var/log/openhab2/openhab.log <==
2019-03-17 19:22:13.068 [WARN ] [rthome.model.script.actions.BusEvent] - Item 'mqtt:broker:MQTTBroker:myTriggerChannel triggered allItems/LichterketteFenster' does not exist.
```
So I propose too split the string twice and change rule name to "Receive all".
=> [mqtt] change the 1st rule for synchronizing instances

addons/voice/org.openhab.voice.googletts/src/main/java/org/openhab/voice/googletts/internal/GoogleCloudAPI.java, addons/voice/org.openhab.voice.googletts/src/main/java/org/openhab/voice/googletts/internal/protocol/ListVoicesResponse.java
- Added additional null check to prevent NPE
@wborn @gbicskei Do you think this is the right way to do it? Do you have a clue what could be the reason for it?
See
https://community.openhab.org/t/openhab-2-5-and-google-tts-on-raspberry-pi/70231
https://community.openhab.org/t/google-tts-exception/70426
=> [googletts] Added additional null check to prevent NPE

bundles/org.openhab.binding.denonmarantz/pom.xml, features/karaf/openhab-addons/src/main/feature/feature.xml
The previous feature did only contain API, no implementation. This should fix it.
=> [denonmarantz] fix missing implementation

addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/parser/GetParamsetParser.java
fixed ClassCastException when using Osram Lightify Devices binded to Homematic-Bridge/Base which aborted initializing device to get online. added a simple check of Parameter-Object given to parse-method.
Signed-off-by: Kai Neuhaus <code@kaineuhaus.com>
=> [homematic] fixed ClassCastException when parsing XMLResponse from Lightify-Devices (#5164)

addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/convention/homie300/Property.java, addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/convention/homie300/PropertyAttributes.java
Hi @davidgraeff!
Here you have a PR to fix the issue reported yesterday (#5186): Homie 3 convention doesn't force properties to have a name and datatype attributes.
Best regards,
Aitor 
=> [mqtt] Remove mandatory condition for name and datatype property attributes (fixes #5186)

poms/bnd/pom.xml
This way adding libraries with includeresource should work on both Linux and Windows.
See https://github.com/openhab/openhab2-addons/pull/5190#issuecomment-475602640.
=> Fix including libraries with bnd includeresource on Windows

addons/binding/org.openhab.binding.mqtt.generic.test/src/test/java/org/openhab/binding/mqtt/generic/HomeAssistantMQTTImplementationTests.java, addons/binding/org.openhab.binding.mqtt.generic.test/src/test/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/DiscoverComponentsTests.java, addons/binding/org.openhab.binding.mqtt.generic.test/src/test/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/HaIDTests.java, addons/binding/org.openhab.binding.mqtt.generic/ESH-INF/config/homeassistant-channel-config.xml, addons/binding/org.openhab.binding.mqtt.generic/README.md, addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/AbstractComponent.java, addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/CChannel.java, addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/CFactory.java, addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/DiscoverComponents.java, addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/HaID.java, addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/HandlerConfiguration.java, addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/discovery/HomeAssistantDiscovery.java, addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/handler/HomeAssistantThingHandler.java
Use the device.unique_id as a channel group id, if availble. Use nodeId,  ObjectId and component as fallback.
Write the information about nodeId and objectId into the channel config to avoid the need to recover the information from the group id.
Also make the channel configuration read only in the GUI. I changes are needed, then a GenericMQTTThing should be used and not a HomeAssistantThing.
With this PR I am having functional autodisovery for tasmota for the already supported compoenents / features.
@davidgraeff Sorry, but I forgot this PR in my other list, because it was basically already prepared.
This PR is based on #4990
=> [mqtt] Have a working Group Id

bundles/org.openhab.binding.avmfritz/pom.xml, features/karaf/openhab-addons/src/main/feature/feature.xml
This adds the necessary dependencies for building the binding on Java 11.
=> [avmfritz] fixes to build on java 11

poms/bnd/pom.xml
There is an issue in the addjars-maven-plugin that it modifies the basepath:
https://code.google.com/archive/p/addjars-maven-plugin/issues/8
Because the lib dir is used with `${.}` it is relative to the base path
(required for Windows, see #5196). The addjars-maven-plugin doesn't run in Eclipse
because it has no m2e lifecycle mapping. bnd tools now has issues including the
resources in Eclipse. This generates error messages for such projects in Eclipse.
For now the best solution seems to disable this profile in Eclipse. :disappointed:
=> Rework add-libraries profile for CLI and Eclipse

bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/LifxLightDiscovery.java
When an exception occurs during discovery it may result in discovery no longer working because the binding thinks a scan is still in progress.
It will then log every minute: _A discovery scan for LIFX lights is already underway_
See: [A discovery scan for LIFX lights is already underway](https://community.openhab.org/t/a-discovery-scan-for-lifx-lights-is-already-underway/70947?u=wborn)
=> [lifx] Fix discovery possibly blocked after exception

.gitignore
Fixes the pattern that was added in #5216 which does not seem to work.
=> Fix ignore Eclipse specific settings pattern

bundles/org.openhab.binding.deconz/README.md, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/BindingConstants.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/HandlerFactory.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/discovery/ThingDiscoveryService.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/SensorThingHandler.java, bundles/org.openhab.binding.deconz/src/main/resources/ESH-INF/config/config.xml, bundles/org.openhab.binding.deconz/src/main/resources/ESH-INF/thing/thing-types.xml
- Added support for ZHAVibration sensors
- Moved `config-description` to separate file and add reference to thing type definitions
- Added `representation-property` to sensor thing types
- Added missing channel type definition for `tampered` (see #5071)
Depends on #5223
Closes #5191
=> [deconz] Added support for ZHAVibration sensors

bundles/.project, bundles/org.openhab.binding.bosesoundtouch/.classpath, bundles/org.openhab.binding.coolmasternet/.classpath, bundles/org.openhab.binding.deconz/.settings/org.eclipse.core.resources.prefs, bundles/org.openhab.binding.deconz/.settings/org.eclipse.m2e.core.prefs, bundles/org.openhab.binding.evohome/.classpath, bundles/org.openhab.binding.folding/.classpath, bundles/org.openhab.binding.hdanywhere/.classpath, bundles/org.openhab.binding.hyperion/.classpath, bundles/org.openhab.binding.irtrans/.classpath, bundles/org.openhab.binding.kodi/.classpath, bundles/org.openhab.binding.leapmotion/.classpath, bundles/org.openhab.binding.lifx/.classpath, bundles/org.openhab.binding.lirc/.classpath, bundles/org.openhab.binding.openweathermap/.project, bundles/org.openhab.binding.plclogo/.classpath, bundles/org.openhab.binding.plugwise/.classpath, bundles/org.openhab.binding.pulseaudio/.classpath, bundles/org.openhab.binding.serialbutton/.classpath, bundles/org.openhab.binding.tesla/.classpath, bundles/org.openhab.binding.valloxmv/.classpath, bundles/org.openhab.binding.windcentrale/.classpath, bundles/org.openhab.io.mqttembeddedbroker/.settings/org.eclipse.core.resources.prefs, bundles/org.openhab.io.mqttembeddedbroker/.settings/org.eclipse.jdt.core.prefs, bundles/org.openhab.io.mqttembeddedbroker/.settings/org.eclipse.m2e.core.prefs, bundles/org.openhab.voice.googletts/.settings/org.eclipse.core.resources.prefs, bundles/org.openhab.voice.googletts/.settings/org.eclipse.m2e.core.prefs, bundles/org.openhab.voice.picotts/.classpath, bundles/org.openhab.voice.voicerss/.classpath, itests/org.openhab.persistence.mapdb.tests/.classpath
After importing or updating projects in Eclipse there are a lot of changes.
Those changes are committed in this PR.
It also removes some Eclipse project specific settings which are ignored.
=> Fix Eclipse project, classpath and settings files

addons/io/org.openhab.io.homekit/META-INF/MANIFEST.MF, addons/io/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitAccessoryRegistry.java, addons/io/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitAccessoryUpdater.java
Probably fixes #1258, since most of the descriptions given say the binding is functioning correctly in spite of seeing bogus duplicate subscription messages.
See also this [community thread](https://community.openhab.org/t/homekit-binding/37690/14).
Signed-off-by: Chris Carman <namraccr@gmail.com>
=> [homekit] Fix Eclipse warnings and reduce bogus logger ERRORs to DEBUGs.

addons/binding/org.openhab.binding.mcp23017/README.md, addons/binding/org.openhab.binding.mcp23017/src/main/java/org/openhab/binding/mcp23017/internal/Mcp23017BindingConstants.java, addons/binding/org.openhab.binding.mcp23017/src/main/java/org/openhab/binding/mcp23017/internal/handler/Mcp23017Handler.java
DESCRIPTION
There are som relay-devices triggert by the MCP23017, which switches to "ON" if the electrical level goes to GND. Therefor, its helpfull to invert the output-states of the chip. This is now configureable in the things-config.
Question: Its ok to access the config every time the handleOutputCommand-Method is triggered? Could this be an performance-Issue?
TESTING
Ive tested it locally with my raspi/openhabian
=> [mcp23017] New Feature "active_low" or "invert logic"

addons/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/handler/AbstractModbusEndpointThingHandler.java
I noticed that things connected to a modbus bridge won't be reinitialized when the bridge changes. Digging down to openhab core I found out that connected things are only notified when the bridge changes status.
This small PR changes the bridge to OFFLINE if it was ONLINE when a change happened.
This is a split of the original PR #4220 as requested by @davidgraeff .
=> [modbus] Change bridge to offline during reinitialization

features/karaf/openhab-addons/src/main/feature/feature.xml
If persistence is enabled, the h2 mvstore dependency must be available.
Fortunately an osgi bundle.
=> [embeddedbroker] Karaf fix: Add h2 store for persistence

addons/io/org.openhab.io.neeo/pom.xml
This fixes the release build issue that currently occurs at https://ci.openhab.org/view/Sandbox/job/sandbox-openhab2-release/1036/.
=> [neeo] removed outdated dependency on no longer existing bundle

bundles/org.openhab.binding.denonmarantz/pom.xml, features/karaf/openhab-addons/src/main/feature/feature.xml
It seems the DenonMarantz Binding still doesn't compile on Java 11 after #5157 got merged. It fails in the Java 11 build of #5335 now that the Tellstick Binding is compatible.
So I've added the same JAXB dependencies in this PR that were added in the other Java 11 compatibility PRs.
=> [denonmarantz] Fix Java 11 compatibility

.travis.yml
We should from now on also require successful [Java 11 Travis CI builds](https://travis-ci.org/openhab/openhab2-addons/jobs/513549994) since we've worked hard to achieve this.
=> Require successful Travis CI Java 8 and 11 builds

bundles/org.openhab.binding.robonect/.project
Eclipse can no longer import the project because a newline got added in #5325.
=> [robonect] Fix Eclipse project file

CODEOWNERS
These tests were moved into the bundle itself in #5334.
=> Remove non-existing fsinternetradio.tests from CODEOWNERS

addons/binding/org.openhab.binding.enocean/ESH-INF/thing/channels.xml, addons/binding/org.openhab.binding.enocean/README.md, addons/binding/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/config/EnOceanChannelDimmerConfig.java, addons/binding/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/A5_38/A5_38_08_Dimming.java
Signed-off-by: Dominik Vorreiter <dominikkv@gmx.de>
Fixes the bug for EEP profile A5-38-08 CMD 0x02 (dimming) for non-Eltako dimmers, where the dimming value was sent incorrectly to the actuator. With this PR, there is a new channel parameter "eltakoDimmer", which determines how the dimming value is sent. It defaults to "true" so it does not break current installations. 
Furthermore, there is a new parameter "storeValue" to give the user the possibility to set this value. It is sent to the actuator. I'm not sure what it really does. For Eltako devices, this parameters sets the "block dimm value" field.
closes #4865
=> [enocean] Add two new channel config parameters "eltakoDimmer" and "storeValue".

bundles/org.openhab.binding.avmfritz/pom.xml, features/karaf/openhab-addons/src/main/feature/feature.xml
Fixes #5341 
This downgrades JAXB to 2.2 since 2.3 seems to have problems on Java 8. Contains only AVMFritz. Needs to be extended to the other bundles.
=> [avmfritz] Downgrade JAXB to 2.2

.travis.yml, poms/bnd/pom.xml
The code can be successfully compiled with Java 11 so it's no longer necessary to enforce Java 8.
This also allows for removing the enforcer override for the Travis CI Java 11 build.
Similar to https://github.com/openhab/openhab-core/pull/688.
=> Update enforcer and Travis CI for allowing Java 11 compilation

bundles/org.openhab.binding.mqtt.homie/src/main/resources/ESH-INF/binding/binding.xml
Multiple binding.xml files with the same binding-id are not possible.
In my opinion the core should allow to reference bridges defined in other bundles which would allow me to give each bundle its own binding id, but that is not the case.
This is the first of three files to be deleted to fix the reported issue of PaperUI showing the wrong binding label. See #5373
=> [mqtt] Delete binding.xml

bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/DeconzBridgeHandler.java
Try to restart websocket connection not only on `connectionLost` but also on `connectionError`.
=> [Deconz] restart websocket connection

bundles/org.openhab.binding.mqtt.generic/src/main/resources/ESH-INF/binding/binding.xml
And the last sub-bundle with a binding.xml that is not allowed / cannot be processed.
=> [mqtt] Remove binding.xml of sub-bundle

CODEOWNERS
It probably got copy/pasted from the code owners line below (nest) in #5240.
Hopefully with this change #5414 will also be fixed soon. :wink:
=> @davidgraeff is the MQTT integration tests code owner

bundles/org.openhab.binding.darksky/.classpath, bundles/org.openhab.binding.fsinternetradio/.classpath, bundles/org.openhab.binding.logreader/.classpath, bundles/org.openhab.binding.robonect/.classpath, bundles/org.openhab.binding.tado/.classpath, bundles/org.openhab.transform.bin2json/.classpath, bundles/org.openhab.voice.marytts/.classpath
With the migration to bnd not all .classpath files were updated accordingly. This would result in eclipse updating these files when loaded and showing up to git as modified. This change corrects those files.
Note: I've added all other libraries downloaded by marytts to the .classpath. Eclipse doesn't complain because they are missing. But I would expect they should be added.
=> Fixed .classpath files.

addons/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/handler/IhcHandler.java, addons/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/ws/IhcClient.java
Also changed couple of list iterators to streams.
=> [ihc] Changed pulse command to use scheduling

bundles/org.openhab.binding.keba/src/main/java/org/openhab/binding/keba/internal/handler/KeContactHandler.java
[KEBA] ignore 0 mA if keba booting up. 
on my p30c after bootup the "curr hw" is sometimes reporting 0 mA.
0 is a invalid value, only values from 6000 are valid. then it would set 6000 as min value,
but on first charging it will then not jump to 32000 but stay on 6000. as the documentation
tells "curr" is affecting the changes power output until keba is reset, or "currtime" is used.
tested on a P30c.
also the Documentation is stating values only from 6000 are valid.
=> [keba] Ignore values if the curr hw commands sends 0

addons/io/org.openhab.io.openhabcloud/README.md
=> [openhabcloud] Updated readme clarifying keys gen

bundles/org.openhab.binding.spotify/README.md, bundles/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/SpotifyBindingConstants.java, bundles/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/api/SpotifyConnector.java, bundles/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/discovery/SpotifyDeviceDiscoveryService.java, bundles/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/handler/SpotifyBridgeHandler.java, bundles/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/handler/SpotifyDeviceHandler.java, bundles/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/handler/SpotifyDynamicStateDescriptionProvider.java, bundles/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/handler/SpotifyHandleCommands.java, bundles/org.openhab.binding.spotify/src/main/resources/ESH-INF/thing/thing-types.xml
This changes some of the channels. So it requires the things to be readded
---- 
The deviceName was a option list with id as key, name as value. However that is not usable in rules. In rules only the id can been seen, so it's impossible to create a rule that checks on a name.
This change adds a new channel devices specific for selecting and changes the deviceName channel back to only displaying the name.
Also changed it's possible to select a player by setting the deviceName or deviceId.
For playlists this was the same problem. Therefor a new channel was added playlists that can be used to select a playlist.
Another new playlistName channel is added that shows the name of the playlist being played.
Changed using the device name as representation property instead of the id. This because …
=> [spotify] Changed deviceName and playlists channels

features/karaf/openhab-addons/src/main/feature/feature.xml, poms/bnd/pom.xml
The org.apache.servicemix.specs.saaj-api-1.3 bundle dependency is added to the Helios Binding feature because javax.xml.soap is no longer provided by bundle 0, see [KARAF-6093](https://issues.apache.org/jira/browse/KARAF-6093).
For Karaf 4.2.3 release notes, see:
https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12311140&version=12344587
For Karaf 4.2.4 release notes, see:
https://issues.apache.org/jira/secure/ReleaseNote.jspa?version=12344856&projectId=12311140
---
Shoud be merged together with:
* https://github.com/openhab/openhab-core/pull/723
* https://github.com/openhab/openhab-webui/pull/56
* https://github.com/openhab/openhab-distro/pull/900
=> Upgrade to Karaf 4.2.4

features/karaf/openhab-addons/src/main/feature/feature.xml
The wrapped xpp3 bundle version added in #5451 does not follow the OSGi [semantic versioning](https://www.osgi.org/wp-content/uploads/SemanticVersioning.pdf) scheme causing the following exception:
```
20:41:02.879 [ERROR] [.core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-binding-lgwebos': Invalid Manifest header "Bundle-Version": 1.1.4c
org.osgi.framework.BundleException: Invalid Manifest header "Bundle-Version": 1.1.4c
at org.eclipse.osgi.container.builders.OSGiManifestBuilderFactory.getSymbolicNameAndVersion(OSGiManifestBuilderFactory.java:248)
at org.eclipse.osgi.container.builders.OSGiManifestBuilderFactory.createBuilder(OSGiManifestBuilderFactory.java:79)
at org.eclipse.osgi.container.builders.OSGiManifestBuilderFactory.createBuilder(OSGiManifestBuilderFactory.java …
```
=> [lgwebos] Binding fails to install due to invalid bundle version

addons/io/org.openhab.io.homekit/META-INF/MANIFEST.MF
Caused by #4920
Fixes #5432
There's quite a flood of exceptions due to this bug when installing the Demo package.
=> [homekit] Fix NoClassDefFoundError by adding missing javax.jmdns package import

bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/internal/homie300/Device.java
As discussed in #5469, the first proposal is applied to fix the bug, replacing the 'createChannelFromAttribute()' function with 'attributesReceived()' method.
Closes #5469 
=> [mqtt] Fix channelType creation when channels are restored

bundles/org.openhab.binding.modbus/pom.xml
=> [modbus] Fix modbus io groupId dependency in modbus binding pom.

bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/utils/NetworkUtils.java
The network binding documentation mentioned the "iputils-arping" version as a possible option:
https://www.openhab.org/addons/bindings/network/#network-binding
The current version of this tool does not support the option "-C" (uppercase).
But it actually supports the "-c" (lowercase) option, in order to set the maximum packet count.
Verification on openhabian release v1.4.1:
- install iputils-arping: "apt-get install iputils-arping"
- check arping: "man arping"
8<--
-c count
Stop after sending count ARP REQUEST packets. With deadline option, instead wait for count ARP REPLY packets, or until the timeout expires.
-->8    
-> there is no parameter "-C" (uppercase) as an option.
-> but the option "-c" (lowercase) exists
=> [network] fix iputils-arping option for setting maximal packet count

features/karaf/openhab-addons/src/main/feature/feature.xml
- Bump Guava version
As we are already using version 21 for Xtext I am wondering if we should bump it for the add-ons too (see https://github.com/openhab/openhab-core/blob/2c7ca348ef42093ae0e42ef48eead61ffbb0195e/features/karaf/openhab-tp/src/main/feature/feature.xml#L180). Otherwise we will have multiple bundles:
```
openhab> bundle:list | grep -i guava
22 │ Active │  80 │ 18.0.0                │ Guava: Google Core Libraries for Java
23 │ Active │  80 │ 21.0.0                │ Guava: Google Core Libraries for Java
265 │ Active │  80 │ 20.0.0                │ Guava: Google Core Libraries for Java
```
```
WARNING: multiple bundles are exporting package com.google.common.base
- com.google.guava_21.0.0 [23]
- com.google.guava_20.0.0 [208]
WARNING: multiple bundles are exporting package …
```
=> Bump Guava version

addons/binding/org.openhab.binding.enocean/ESH-INF/thing/channels.xml, addons/binding/org.openhab.binding.enocean/README.md, addons/binding/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/config/EnOceanChannelTotalusageConfig.java, addons/binding/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/A5_11/A5_11_04.java, addons/binding/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/A5_12/A5_12.java, addons/binding/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/D2_01/D2_01.java, addons/binding/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/EEPHelper.java
Signed-off-by: Dominik Vorreiter <dominikkv@gmx.de>
Add new channel config for channel "totalusage" to enable value validation, defaulting to false.
Validation is done in all EEPs receiving values for this channel.
If value decreases by less than 1 kWh, discard value.
If value increases by more than 10 kWh, discard value.
Closes #5052
=> [enocean] Add validation for new values for channel "totalusage"

bundles/org.openhab.binding.spotify/README.md, bundles/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/api/SpotifyConnector.java, bundles/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/discovery/SpotifyDeviceDiscoveryService.java, bundles/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/handler/SpotifyBridgeHandler.java, bundles/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/handler/SpotifyDeviceHandler.java, bundles/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/handler/SpotifyHandleCommands.java, bundles/org.openhab.binding.spotify/src/main/resources/ESH-INF/thing/thing-types.xml
Under certain conditions when a command is given, for example play next and a refresh happened a almost the same time a deadlock could happen causing the binding to hang. This fix limits synchronization on time formatter to only what matters and not wraps it also around state update (that is also synchronized).
Removed retry on 202. This is given when a command is given, so it's not necessary to retry that command.
Also made some documentation and other small code fixes.
=> [spotify] Fixed deadlock causing status to stop.

bundles/org.openhab.binding.pioneeravr/README.md, bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/PioneerAvrBindingConstants.java, bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/handler/AbstractAvrHandler.java, bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/protocol/ParameterizedCommand.java, bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/protocol/Response.java, bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/protocol/SimpleCommand.java, bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/protocol/StreamAvrConnection.java, bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/protocol/avr/AvrConnection.java, bundles/org.openhab.binding.pioneeravr/src/main/resources/ESH-INF/thing/thing-types.xml
This improves the *pioneeravr* binding by adding two channels for setting and reading the *Listening Mode* and reading the *Playing Listening Mode*.
The *Listening Mode* is set by user to instruct the AVR how to treat the audio signal and do upscaling, downscaling and amplification. This settings corresponds to the settings made with the remote control or front panel. What the AVR actually does with each setting/input-signal-combination can be read out using the *Playing Listening Mode* channel.
The *Playing Listening Mode* is the Listening Mode that is actually playing as opposed to the *Listening Mode* set by the user. The *Playing Listening Mode* is what the display on the device shows.
- [PioneerAVR 2 - Listen Mode](https://community.openhab.org/t/pioneeravr-2-listen-mode/18595) …
=> [pioneeravr] Add Listening Mode Channels

bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/KodiDynamicStateDescriptionProvider.java
- Changed `DynamicStateDescriptionProvider` implementation to use new `BaseDynamicStateDescriptionProvider`. It now supports translated state options.
=> [kodi] Changed 'DynamicStateDescriptionProvider' implementation to use new 'BaseDynamicStateDescriptionProvider'

bundles/pom.xml
This fixes the following warnings on Jenkins builds:
`[WARNING] Failed to getClass for org.apache.maven.plugins.source.SourceJarMojo`
See also:
* [JENKINS-27372](https://issues.jenkins-ci.org/browse/JENKINS-27372)
* https://github.com/openhab/openhab-core/pull/741
=> Attach source JARs without forking to fix Jenkins warnings

bundles/org.openhab.binding.lutron/README.md, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/BaseKeypadHandler.java
Hi. This PR contains a small fix for CCI channels in the Lutron keypad handler.  They were not using the proper command types.  Mea culpa.
Regards,
Bob
=> [lutron] Fix for keypad/VCRX CCI channels

bom/openhab-addons/pom.xml, bom/pom.xml
This allows to auto-create the addons-BOM from the bundles-POM.
The problem is that it needs an extra maven-call ` mvn antrun:run@create-bom` in front of `mvn clean install` because the bom-POM is otherwise parsed before it is created. Therefore I left it in place.
=> [infrastructure] auto-create addons-BOM

bundles/org.openhab.binding.keba/src/main/java/org/openhab/binding/keba/internal/KebaBindingConstants.java, bundles/org.openhab.binding.keba/src/main/java/org/openhab/binding/keba/internal/handler/KeContactHandler.java, bundles/org.openhab.binding.keba/src/main/resources/ESH-INF/thing/kecontact.xml
In order to retrieve the RFID Tag used on a Keba i interoduced the "Report100" which is getting the RFID and SessionID of the last charging session done. The Report100 is only done if the session state changes, not to overload the connection with too many reports. Tested on a keba p30c.
=> [keba] add RFID tag id and sessionID

bundles/pom.xml, pom.xml
Feature verification was notproperly performed for bundles with embedded libraries because the addjars-maven-plugin changes ${project.basedir} and a non existing input-file was used for generating the features descriptor. 
=> fix feature verification

bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/Connection.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/handler/AccountHandler.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/jsons/JsonActivities.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/jsons/JsonAnnouncementContent.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/jsons/JsonAnnouncementTarget.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/jsons/JsonAscendingAlarm.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/jsons/JsonAutomation.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/jsons/JsonBluetoothStates.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/jsons/JsonCommandPayloadPushActivity.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/jsons/JsonCommandPayloadPushDevice.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/jsons/JsonDeviceNotificationState.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/jsons/JsonDevices.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/jsons/JsonExchangeTokenResponse.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/jsons/JsonMediaState.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/jsons/JsonPlayerState.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/jsons/JsonPlaylists.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/jsons/JsonRegisterAppRequest.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/jsons/JsonRegisterAppResponse.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/jsons/JsonWakeWords.java
I have updated my development environment to the new bndtools
Unfortunately the binding does not work anymore. I figured out that the json parsing is the problem. Now inner classes can only be created if the a marked as static. 
I have no idea whats going on here, because this works in the past. Maybe a wrong gson version is now used?
Anyway, the PR fixes this issue, but it would be nice for me to understand what was changed.
=> [amazonechocontrol] Fix problem with new json parser in new build environment

bundles/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/OwHandlerFactory.java
This logging statement was added for debugging purposes and unintentionally entered the codebase.
=> [onewire] remove error logging

bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudClient.java
- Reduced logging levels
To prevent outputs like this which occurred when openHAB Cloud is down. But the binding is capable of handling it and continues its work without any problem.
```
2019-05-05 19:19:39.224 [ERROR] [io.openhabcloud.internal.CloudClient] - Socket.IO error: {}
io.socket.engineio.client.EngineIOException: xhr poll error
at io.socket.engineio.client.Transport.onError(Transport.java:71) [230:org.openhab.io.openhabcloud:2.5.0.M1]
at io.socket.engineio.client.transports.PollingXHR.access$100(PollingXHR.java:19) [230:org.openhab.io.openhabcloud:2.5.0.M1]
at io.socket.engineio.client.transports.PollingXHR$6$1.run(PollingXHR.java:124) [230:org.openhab.io.openhabcloud:2.5.0.M1]
at io.socket.thread.EventThread$2.run(EventThread.java:80) [230:org.openhab.io.openhabcloud:2.5.0.M1] …
```
=> [openhabcloud] Reduced logging levels

bundles/org.openhab.binding.amazonechocontrol/pom.xml, bundles/org.openhab.binding.digitalstrom/pom.xml, bundles/org.openhab.binding.fsinternetradio/pom.xml, bundles/org.openhab.binding.ftpupload/pom.xml, bundles/org.openhab.binding.km200/pom.xml, bundles/org.openhab.binding.logreader/pom.xml, bundles/org.openhab.binding.neato/pom.xml, bundles/org.openhab.binding.neeo/pom.xml, bundles/org.openhab.binding.solarlog/pom.xml, bundles/org.openhab.binding.sonyaudio/pom.xml, bundles/org.openhab.binding.tado/pom.xml, bundles/org.openhab.binding.valloxmv/pom.xml, bundles/org.openhab.binding.velbus/pom.xml, bundles/org.openhab.binding.volvooncall/pom.xml
These properties duplicate the parent values so they are unnecessary.
=> Remove version and groupId duplication from POMs

bundles/org.openhab.binding.avmfritz/README.md, bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/AVMFritzBaseBridgeHandler.java, bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/Powerline546EHandler.java, bundles/org.openhab.binding.avmfritz/src/main/resources/ESH-INF/config/config.xml, bundles/org.openhab.binding.avmfritz/src/main/resources/ESH-INF/i18n/avmfritz_de.properties
- Fixed flapping ONLINE/OFFLINE status of FRITZ!Powerline 546E device in standalone mode
- Fixed creation of `voltage` channel for FRITZ!Powerline 546E device in standalone mode
See https://community.openhab.org/t/repeating-hingstatusinfochangedevent-with-fritz-powerline-546e-going-from-online-to-offline/73648/
=> [avmfritz] Fixed flapping ONLINE/OFFLINE status of FRITZ!Powerline 546E device in standalone mode

bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitAccessoryRegistry.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitAccessoryUpdater.java
Fixes #5645 
- prevent null-callbacks from being added
- properly remove subscriptions if bridge is removed
=> [homekit] NPE protection

bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/DeconzBridgeHandler.java
- Changed scheduler policy
I do not trust the recursion of the `scheduler.scheduleWithFixedDelay(this::startWebsocket, ...)` calls. I think a one time shot should be sufficient. On the weekend my test environment crashed because of a `java.lang.OutOfMemoryError: Java heap space` error - If I remember correctly I updated my FRITZ!Box to the latest OS version and there was a temporarily downtime of my network:
Screenshot of the heap dump in Eclipse Memory Analyzer Tool (MAT).
=> [deconz] Changed scheduler policy to fix OutOfMemoryError

bundles/org.openhab.binding.dsmr/src/test/java/org/openhab/binding/dsmr/internal/device/SmartyDecrypterTest.java, bundles/org.openhab.binding.loxone/src/test/java/org/openhab/binding/loxone/internal/controls/LxControlTest.java, bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/rest/mocks/ConfigStoreWithoutMetadata.java, pom.xml
After running `mvn license:format` this was the result. I've also removed OSGI-INF from the includes because that content is no longer part of the repo and generated in `/target/` nowadays.
=> Update license headers

bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComLighting4Message.java, bundles/org.openhab.binding.rfxcom/src/test/java/org/openhab/binding/rfxcom/internal/messages/RFXComLighting4MessageTest.java
Closes #4432
[org.openhab.binding.rfxcom-2.5.0-SNAPSHOT.jar.zip](https://github.com/openhab/openhab2-addons/files/3249007/org.openhab.binding.rfxcom-2.5.0-SNAPSHOT.jar.zip)
=> Support some new lighting-4 devices

bundles/org.openhab.io.imperihome/src/main/java/org/openhab/io/imperihome/internal/processor/ItemProcessor.java
The ItemProcessor implements the ItemRegistryChangeListener interface which got null annotations.
See: https://github.com/openhab/openhab-core/pull/850
=> [imperihome] Fix compilation error due to new null annotations

bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/calc/MoonCalc.java
- Fixed handling of division by 0 for new moon
The division by 0 results in `Double.POSITIVE_INFINITY` ("Infinity" after converting to String) which cannot be parsed correctly by the `QuantityType` / `BigDecimal` constructor and leads to an error:
```
2019-06-03 09:10:29.391 [ERROR] [o.internal.handler.AstroThingHandler] - Can't update state for channel astro:moon:local:phase#ageDegree : null
java.lang.reflect.InvocationTargetException: null
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
at …
```
=> [astro] Fixed handling of division by 0 for new moon

bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/A5_38/A5_38_08_Dimming.java
Fix the getbit parameter 0, so that internal dimmer state resembles the external state.
As described in issue #5608, the getbit function will always return false.
Fixes #5608
=> [enocean] Fix A5-38-08 Dimmer reset to 0

bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/HueEmulationService.java, bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/rest/LightsAndGroups.java, bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/rest/StatusResource.java, bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/upnp/HueEmulationConfigWithRuntime.java, bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/upnp/UpnpServer.java
* Properly annotates optional references with nullable to fix NPEs
* Reworked HueEmulationConfigWithRuntime.startNow to prevent IllegalStateException
Fixes #5622
---
This fixes all warning/stacktrace noise from this add-on when using the Demo.
=> [hueemulation] Fix warnings/stacktraces at startup

pom.xml
For Karaf 4.2.5 release notes, see:
https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12311140&version=12345153
For Karaf 4.2.6 release notes, see:
https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12311140&version=12345365
---
Should be merged together with:
* https://github.com/openhab/openhab-distro/pull/924
* https://github.com/openhab/openhab-core/pull/859
* https://github.com/openhab/openhab-webui/pull/79
=> Upgrade Karaf to 4.2.6

bundles/org.openhab.binding.xmppclient/src/main/feature/feature.xml
Fixes #5473 
- Replaced wrapped xpp3 with servicemix
- The missing dependencies are not properly referenced by the bundles that need them at runtime. Therefore we have to force their installation.
=> [xmppclient] remove wrapping and force dependency install

bundles/org.openhab.binding.keba/README.md, bundles/org.openhab.binding.keba/src/main/java/org/openhab/binding/keba/internal/KebaBindingConstants.java, bundles/org.openhab.binding.keba/src/main/java/org/openhab/binding/keba/internal/handler/KeContactHandler.java, bundles/org.openhab.binding.keba/src/main/resources/ESH-INF/thing/kecontact.xml
introduce setenergy command (for openhab#4417) this is adding read and write item setenergy to set a charging limit in Wh. Quite handy command to limit the overall carge the car gets. if you only want to charge 20kWh set it to 20000. also added documentation.
Fixes #4417
=> [keba] Add setenergy command

bundles/org.openhab.binding.network/src/test/java/org/openhab/binding/network/internal/dhcp/DHCPTest.java
In maven this test tends to fail, so by using an assume we can disable it automatically if the precondition does not hold.
=> [network] DHCPTest.java

bundles/org.openhab.binding.globalcache/README.md, bundles/org.openhab.binding.globalcache/src/main/resources/ESH-INF/thing/channel-types.xml
The current item type prevents globalcache contact closures from being modified by this module, since it is marked as an item type of "Contact" that can only accept "REFRESH" commands. So, while it can show changes that are done external to this module, all the functionality in the module that makes changes to the contact relays can never be triggered.
The documentation at https://www.openhab.org/addons/bindings/globalcache/ has examples that showcase both Switch and Contact item types. This change will make the Switch use cases actually work.
Today, this is shown in the log:
2019-06-12 22:39:05.386 [DEBUG] [.thing.internal.CommunicationManager] - Received event 'ON' (OnOffType) could not be converted to any type accepted by item 'HomeTheaterCurtainsOpen' (Switch) …
=> [globalcache] Update the Item type for Contact Closures to "Switch"

bundles/org.openhab.io.hueemulation/src/main/java/org/glassfish/jersey/servlet/init/JerseyServletContainerInitializer.java, bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/HueEmulationService.java, bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/automation/TimerTriggerHandler.java, bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/rest/ConfigurationAccess.java, bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/rest/Rules.java, bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/rest/Scenes.java, bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/rest/Schedules.java, bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/upnp/UpnpServer.java, bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/automation/RuleConditionHandlerTests.java, bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/rest/LightsAndGroupsTests.java, bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/rest/SensorTests.java, bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/rest/UsersAndConfigTests.java, bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/rest/mocks/DummyItemRegistry.java
Resolves exception of combining ipv4 / ipv6 by getting to separate channels
Exception in thread "HueEmulation UPNP Server" java.lang.IllegalArgumentException: IPv6 socket cannot join IPv4 multicast group
at sun.nio.ch.DatagramChannelImpl.innerJoin(DatagramChannelImpl.java:808)
at sun.nio.ch.DatagramChannelImpl.join(DatagramChannelImpl.java:894)
at org.openhab.io.hueemulation.internal.upnp.UpnpServer.accept(UpnpServer.java:439)
at org.openhab.io.hueemulation.internal.upnp.UpnpServer.accept(UpnpServer.java:1)
at org.openhab.io.hueemulation.internal.upnp.HueEmulationConfigWithRuntime.run(HueEmulationConfigWithRuntime.java:105)
@davidgraeff would this be a sensible solution?
=> [hueemulation] seperate ipv4 / ipv6

features/openhab-addons/pom.xml
Adapt regular expression so it also matches the bundles of the openhab-io-webaudio and openhab-misc-market features.
See also: https://github.com/openhab/openhab-core/issues/821
=> Fix missing feature bundles

bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/protocol/KodiClientSocket.java, bundles/org.openhab.binding.sonyaudio/src/main/java/org/openhab/binding/sonyaudio/internal/protocol/SonyAudioClientSocket.java
Fixes https://github.com/openhab/openhab2-addons/issues/5715
=> implement onError method for websocket connection

bundles/org.openhab.binding.avmfritz/pom.xml, bundles/org.openhab.binding.denonmarantz/pom.xml, bundles/org.openhab.binding.dlinksmarthome/pom.xml, bundles/org.openhab.binding.tellstick/pom.xml, bundles/org.openhab.binding.xmltv/pom.xml
With #5701 some depencencies have changed to OSGi bundles. This updates the dependencies.
=> update POMs with changed dependencies

bundles/org.openhab.binding.xmppclient/README.md
Improved readme file.
* fixed binding parameters description
* added Text-based configuration samples
Signed-off-by: Pavel Gololobov <pavel@ochat.org>
=> [xmppclient] Improved readme file

bundles/org.openhab.io.openhabcloud/src/main/feature/feature.xml
optional imports from automatic wrapping of other bundles prevent needed bundles from being installed
Report: https://community.openhab.org/t/openhab-cloud-connector-not-working-anymore-after-snapshot-1607/76308
=> [openhabcloud] partly revert unwrapping

bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/model/Sun.java, bundles/org.openhab.binding.astro/src/test/java/org/openhab/binding/astro/internal/calc/SunCalcTest.java, bundles/org.openhab.binding.astro/src/test/java/org/openhab/binding/astro/internal/model/SunTest.java
This PR contains a fix for the scenario described in #5006, so it covers the undefinied Sun phase around the SUN_RISE and SUN_SET events.
For now the fix contains two commits:
* 6af8a29ec010 a unit tests to cover the case
* fba7a9b1959 the fix for the issue
There is also a discussion on the community forum
https://community.openhab.org/t/astronight-start-channel-undef-and-others-too/74832/18
but it covers more cases (not only around SUN_RISE and SUN_SET) where some channels are **UNDEF**.
Fixes #5006
=> [astro] Fix astro #5006

.gitignore, .travis.yml, buildci.sh, travis-buddy-failure-template.md, travis-buddy-success-template.md
This PR adds travisbuddy to .travis.yml. That service add (update) a comment to a PR on a build failure with the log attached. This is an intermediate step until we have full github checks api support and a curl command figured out to report SAT findings and Test results to the "Checks" tab. See also #4935
The PR commits are analysed and if exactly one new directory is added to bundles/ then a build with tests and checks is performed for that new bundle otherwise the full repo build without tests and checks is executed as before.
* This PR includes an absolute irrelevant commit for testing the bundles/ changed detection
* Karaf feature test is not yet performed in the partial build
* SAT should fail if a new binding is not added to the bom or the parent pom.xml or the karaf feature file
* …
=> Travis: Build new binding pull requests with tests

bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudClient.java, bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudService.java
[openhabcloud] Create dedicated HttpClient from the factory to connect to the local OpenHAB (Issue #5770)
Create a custom instance of HttpClient to connect to the local OpenHAB so that it can have a dedicated configurable amount of allowed connections to the rest api backend
I have moved the config of the HttpClient from CloudClient.java to CloudService.java so that its configuration (esp amount of councurrent connections) can be updated (not done this configurable yet, by now left the previously existing 200)
=> [openhabcloud] Create dedicated HttpClient from the factory to connect to the local OpenHAB (Issue #5770)

bundles/org.openhab.binding.konnected/src/main/java/org/openhab/binding/konnected/internal/KonnectedHandlerFactory.java, bundles/org.openhab.binding.konnected/src/main/java/org/openhab/binding/konnected/internal/servlet/KonnectedHTTPServlet.java
Fixes https://github.com/openhab/openhab2-addons/issues/5749
=> [konnected] fixes servlet registration

bundles/org.openhab.binding.lgwebos/README.md, bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/TVControlChannel.java, bundles/org.openhab.binding.lgwebos/src/main/resources/ESH-INF/thing/thing-types.xml
In #5744 it was reported that channel numbers can contain non-numeric characters.
Signed-off-by: Sebastian Prehn <sebastian.prehn@gmx.de> (github: sprehn)
=> [lgwebos] Changing type of Channel Number from Number to String.

bundles/org.openhab.binding.milight/README.md
Just updated the README.md of the milight binding with an alive url.
=> [milight] Updated dead github url to alive openhab-doc url

.travis.yml, buildci.sh
Use the commit range given by travis to calculate the changed files (not only new files) and make sure we return the correct exit code
=> Further evolution of travis build script

bundles/org.openhab.binding.rfxcom/README.md, bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/DeviceMessageListener.java, bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/RFXComBindingConstants.java, bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/connector/RFXComConnectorInterface.java, bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/connector/RFXComEventListener.java, bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/handler/RFXComHandler.java, bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComLighting2Message.java, bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComLighting5Message.java, bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComMessage.java, bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComThermostat3Message.java, bundles/org.openhab.binding.rfxcom/src/main/resources/ESH-INF/thing/channels.xml, bundles/org.openhab.binding.rfxcom/src/main/resources/ESH-INF/thing/thermostat3.xml, bundles/org.openhab.binding.rfxcom/src/test/java/org/openhab/binding/rfxcom/internal/messages/RFXComChimeMessageTest.java, bundles/org.openhab.binding.rfxcom/src/test/java/org/openhab/binding/rfxcom/internal/messages/RFXComDateTimeMessageTest.java, bundles/org.openhab.binding.rfxcom/src/test/java/org/openhab/binding/rfxcom/internal/messages/RFXComHomeConfortTest.java, bundles/org.openhab.binding.rfxcom/src/test/java/org/openhab/binding/rfxcom/internal/messages/RFXComInterfaceControlMessageTest.java, bundles/org.openhab.binding.rfxcom/src/test/java/org/openhab/binding/rfxcom/internal/messages/RFXComLighting4MessageTest.java, bundles/org.openhab.binding.rfxcom/src/test/java/org/openhab/binding/rfxcom/internal/messages/RFXComRfyMessageTest.java, bundles/org.openhab.binding.rfxcom/src/test/java/org/openhab/binding/rfxcom/internal/messages/RFXComThermostat3MessageTest.java, bundles/org.openhab.binding.rfxcom/src/test/java/org/openhab/binding/rfxcom/internal/messages/RFXComUndecodedRFMessageTest.java
Fixes #4633 
Test jar: 
~~org.openhab.binding.rfxcom-2.5.0-SNAPSHOT.jar.zip~~
New test jar:
[org.openhab.binding.rfxcom-2.5.0-SNAPSHOT.jar.zip](https://github.com/openhab/openhab2-addons/files/3336194/org.openhab.binding.rfxcom-2.5.0-SNAPSHOT.jar.zip)
To use the Themostat3 now you should be able to either use the string-item to control all the commands: 
```
GashaardCommandString.sendCommand("RUN_DOWN")
```
Or use either the command or control items:
```
GashaardCommand.sendCommand(OFF)
GasHaardControl.sendCommand(UP)
```
If you proper compact ideas / examples for the README they are welcome so I can include them in the PR.
=> [rfxcom] Worked on repairing support for RFXThermostat3 messages

.travis.yml
We do not use p2 anymore in this repo. Remove the cache directory. Add the bnd cache directory instead.
It should speed up itests.
PS: Small patch exception, no sign off
=> Travis Cache

CODEOWNERS, bom/openhab-addons/pom.xml, bundles/org.openhab.binding.pushbullet/.classpath, bundles/org.openhab.binding.pushbullet/.project, bundles/org.openhab.binding.pushbullet/NOTICE, bundles/org.openhab.binding.pushbullet/README.md, bundles/org.openhab.binding.pushbullet/pom.xml, bundles/org.openhab.binding.pushbullet/src/main/feature/feature.xml, bundles/org.openhab.binding.pushbullet/src/main/java/org/openhab/binding/pushbullet/internal/PushbulletBindingConstants.java, bundles/org.openhab.binding.pushbullet/src/main/java/org/openhab/binding/pushbullet/internal/PushbulletConfiguration.java, bundles/org.openhab.binding.pushbullet/src/main/java/org/openhab/binding/pushbullet/internal/PushbulletHandlerFactory.java, bundles/org.openhab.binding.pushbullet/src/main/java/org/openhab/binding/pushbullet/internal/action/PushbulletActions.java, bundles/org.openhab.binding.pushbullet/src/main/java/org/openhab/binding/pushbullet/internal/handler/PushbulletHandler.java, bundles/org.openhab.binding.pushbullet/src/main/java/org/openhab/binding/pushbullet/internal/model/Push.java, bundles/org.openhab.binding.pushbullet/src/main/java/org/openhab/binding/pushbullet/internal/model/PushError.java, bundles/org.openhab.binding.pushbullet/src/main/java/org/openhab/binding/pushbullet/internal/model/PushResponse.java, bundles/org.openhab.binding.pushbullet/src/main/resources/ESH-INF/binding/binding.xml, bundles/org.openhab.binding.pushbullet/src/main/resources/ESH-INF/i18n/pushbullet_en.properties, bundles/org.openhab.binding.pushbullet/src/main/resources/ESH-INF/thing/thing-types.xml, bundles/pom.xml
This is a reimplementation of the pushbullet action which I had authored for openHAB 1:
https://www.openhab.org/addons/actions/pushbullet/
Most of the "business" code is transplanted from OH1, and some adaptations made to be able to use this as an annotated action.
I have not tried to configure the rule via Paper UI, though.
=> [pushbullet] Pushbullet Binding initial contribution

bundles/org.openhab.binding.snmp/src/main/resources/ESH-INF/thing/thing-types.xml
this was forgotten during the last refactoring
=> [snmp] fix thing.xml

bundles/org.openhab.binding.loxone/README.md, bundles/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/LxServerHandler.java, bundles/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/LxServerHandlerApi.java, bundles/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/controls/LxControlAlarm.java, bundles/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/controls/LxControlDimmer.java, bundles/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/controls/LxControlInfoOnlyAnalog.java, bundles/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/controls/LxControlJalousie.java, bundles/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/controls/LxControlLightController.java, bundles/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/controls/LxControlLightControllerV2.java, bundles/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/controls/LxControlSwitch.java, bundles/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/types/LxCategory.java, bundles/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/types/LxState.java, bundles/org.openhab.binding.loxone/src/test/java/org/openhab/binding/loxone/internal/controls/LxControlInfoOnlyAnalogTempTagTest.java, bundles/org.openhab.binding.loxone/src/test/java/org/openhab/binding/loxone/internal/controls/LxControlInfoOnlyAnalogTest.java, bundles/org.openhab.binding.loxone/src/test/java/org/openhab/binding/loxone/internal/controls/LxControlJalousieTest.java, bundles/org.openhab.binding.loxone/src/test/java/org/openhab/binding/loxone/internal/controls/LxControlLightControllerV2Test.java, bundles/org.openhab.binding.loxone/src/test/java/org/openhab/binding/loxone/internal/controls/LxControlPushbuttonTest.java, bundles/org.openhab.binding.loxone/src/test/java/org/openhab/binding/loxone/internal/controls/LxControlSwitchTest.java, bundles/org.openhab.binding.loxone/src/test/java/org/openhab/binding/loxone/internal/controls/LxControlTest.java, bundles/org.openhab.binding.loxone/src/test/java/org/openhab/binding/loxone/internal/controls/LxControlTimedSwitchTest.java, bundles/org.openhab.binding.loxone/src/test/java/org/openhab/binding/loxone/internal/controls/LxServerHandlerDummy.java, bundles/org.openhab.binding.loxone/src/test/resources/org/openhab/binding/loxone/internal/controls/LoxAPP3.json
This PR adds automatic tags generation to channels, to support Google Home scheme described here:  https://www.openhab.org/docs/ecosystem/google-assistant and as a response to request #5615 from @Tihmann.
Changes:
- added binding configuration parameter to switch auto generation off/on (default: on)
- simplified a bit using the binding configuration parameters in the binding and added ability to access them from the LxControl objects
- added generation of tags to:
- switch (and child classes for timed switch and pushbutton) - when switch belongs to lights category, the tag will be _Lighting_, otherwise _Switchable_
- dimmer - if it belongs to category lights, tag will be _Lighting_, otherwise none
- light controller - main channel with selected scene will be tagged _Scene_
- jalousie …
=> [loxone] Added automatic tags generation #5615

bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/handler/SamsungTvHandler.java
Fix for #5794 thing not going to offline 
Bugfix to make the thing go offline when a connection error occurs. This addresses #5794.
A compiled version is available at: https://drive.google.com/open?id=1BAg5Xs1UtuZi61p5FpXjVJGWV31-HLK8
=> [samsungtv] Fix for #5794 thing not going to offline 

bundles/org.openhab.binding.lutron/README.md, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/LutronBindingConstants.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/LutronHandlerFactory.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/discovery/LutronDeviceDiscoveryService.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/discovery/project/DeviceType.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/IntlKeypadHandler.java, bundles/org.openhab.binding.lutron/src/main/resources/ESH-INF/thing/thing-types.xml
Hi. This PR adds support for International seeTouch keypads used in Lutron HomeWorks QS systems. This is part of the on-going work to fully support HomeWorks QS with the Lutron binding.
Regards,
Bob
=> [lutron] Add support for HomeWorks QS International seeTouch keypads

bundles/org.openhab.binding.keba/README.md, bundles/org.openhab.binding.keba/src/main/java/org/openhab/binding/keba/internal/KebaBindingConstants.java, bundles/org.openhab.binding.keba/src/main/java/org/openhab/binding/keba/internal/handler/KeContactHandler.java, bundles/org.openhab.binding.keba/src/main/resources/ESH-INF/thing/kecontact.xml
In order to start a charging session on Keba with RFID enabled, this command can be used. The syntax is a String "RFIDTAG RFIDCLASS" seperator is a whitespace, so e.g "123abdef00000000 00000000000000000000" is a valid string. Be remembered the RFID TAG must be whitlisted to the Keba, so if the keba has never seen this tag it will not work.
tested on a P30c
Signed-off-by: Juergen Benz <juergen.benz@gmail.com>
=> [keba] start command implementation, authentication feature.

bundles/org.openhab.binding.denonmarantz/README.md
The following item had a "-" instead of a "=" : marantz_volumeDB 
It did not cause an error when loading up to OpenHUB but it would cause it once you tried to actually use it in the sitemap.
=> Fixxed a typo in the sitemap

bundles/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/api/SpotifyApi.java, bundles/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/handler/SpotifyBridgeHandler.java, bundles/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/handler/SpotifyDeviceHandler.java
Under certain conditions the binding causes unexpected exceptions.
These changes add guards to these situations and provide additional feedback to the user.
=> [spotify] Small stability improvements

bundles/org.openhab.binding.ambientweather/README.md, bundles/org.openhab.binding.ambientweather/src/main/java/org/openhab/binding/ambientweather/internal/processor/Ws0900ipProcessor.java, bundles/org.openhab.binding.ambientweather/src/main/java/org/openhab/binding/ambientweather/internal/processor/Ws1400ipProcessor.java, bundles/org.openhab.binding.ambientweather/src/main/java/org/openhab/binding/ambientweather/internal/processor/Ws2902aProcessor.java, bundles/org.openhab.binding.ambientweather/src/main/resources/ESH-INF/thing/channels.xml
Now that openhab/openhab-core#644 is fixed (thanks @cweitkamp), the rainfall rate channel can be converted to the `Number:Speed` QuantityType.
Since the initial version of the binding was merged just yesterday, I really don't see a need to document that this is a breaking change.
=> [ambientweather] Implement QuantityType for rainfall rate

bundles/archetype-settings.xml
Currently, the skeleton script fails as described here: https://github.com/openhab/openhab2-addons/issues/5849.
Originally the URL was pointing to the artifactory UI.
I changed it to the actual repository.
=> [skeleton] Use correct repository URL for the archetype

bundles/org.openhab.binding.paradoxalarm/src/main/java/org/openhab/binding/paradoxalarm/internal/discovery/ParadoxDiscoveryService.java, bundles/org.openhab.binding.paradoxalarm/src/main/java/org/openhab/binding/paradoxalarm/internal/handlers/ParadoxAlarmBindingConstants.java, bundles/org.openhab.binding.paradoxalarm/src/main/java/org/openhab/binding/paradoxalarm/internal/handlers/ParadoxAlarmHandlerFactory.java, bundles/org.openhab.binding.paradoxalarm/src/main/java/org/openhab/binding/paradoxalarm/internal/handlers/ParadoxIP150BridgeHandler.java, bundles/org.openhab.binding.paradoxalarm/src/main/java/org/openhab/binding/paradoxalarm/internal/model/Entity.java
Paradox alarm - Discovery service implementation
[paradoxalarm] Implementation of discovery service for entities. Bridge must be configured. When it establishes communication with security system, the discovery service can gather all entities (partitions, zones and panel info)
Signed-off-by: Konstantin Polihronov <polychronov@gmail.com>
=> [paradoxalarm] - Discovery service implementation

bundles/org.openhab.binding.avmfritz/pom.xml, bundles/org.openhab.binding.avmfritz/src/main/feature/feature.xml, itests/itest-common.bndrun, itests/org.openhab.binding.avmfritz.tests/itest.bndrun, itests/org.openhab.binding.avmfritz.tests/pom.xml, itests/org.openhab.binding.avmfritz.tests/src/main/java/org/openhab/binding/avmfritz/internal/discovery/AVMFritzDiscoveryServiceOSGiTest.java, itests/org.openhab.binding.nest.tests/itest.bndrun, itests/org.openhab.binding.nest.tests/pom.xml
- Changed dependencies based on Java EE modules (openhab/openhab-core#920)
- Reactivated avmfritz tests
- Fixed Nest tests
Adresses #5775
Fixes #5413
I disabled non working itests and told Travis to run with performing itests. Another issue popped up related to Astro issues (seems to be related to #5720).
```
[ERROR] Tests run: 22, Failures: 9, Errors: 0, Skipped: 1, Time elapsed: 0.338 s <<< FAILURE! - in org.openhab.binding.astro.internal.calc.SunCalcTest
[ERROR] testGetSunInfoForNauticDawnAccuracy(org.openhab.binding.astro.internal.calc.SunCalcTest)  Time elapsed: 0.059 s  <<< FAILURE!
java.lang.AssertionError: expected:<1.55124826E12> but was:<1.55124485E12>
at org.openhab.binding.astro.internal.calc.SunCalcTest.testGetSunInfoForNauticDawnAccuracy(SunCalcTest.java:109)
[ERROR] …
```
=> [avmfritz] Reenable itests

pom.xml
This url is invalid (gives a 404). The osgiify artifacts are available in the standard openHAB Bintray repo under https://dl.bintray.com/openhab/mvn/org/openhab/osgiify/.
=> removed non-existent repository

itests/org.openhab.binding.astro.tests/itest.bndrun, itests/org.openhab.binding.avmfritz.tests/itest.bndrun, itests/org.openhab.binding.feed.tests/itest.bndrun, itests/org.openhab.binding.hue.tests/itest.bndrun, itests/org.openhab.binding.max.tests/itest.bndrun, itests/org.openhab.binding.mqtt.homeassistant.tests/itest.bndrun, itests/org.openhab.binding.mqtt.homie.tests/itest.bndrun, itests/org.openhab.binding.nest.tests/itest.bndrun, itests/org.openhab.binding.ntp.tests/itest.bndrun, itests/org.openhab.binding.systeminfo.tests/itest.bndrun, itests/org.openhab.binding.tradfri.tests/itest.bndrun, itests/org.openhab.binding.wemo.tests/itest.bndrun, itests/org.openhab.io.hueemulation.tests/itest.bndrun, itests/org.openhab.persistence.mapdb.tests/itest.bndrun, pom.xml
The bnd-testing-maven-plugin that is used to run the tests already
checks for the skipTests property and do not execute any tests if
defined.
We should keep the integration tests part of the reactor also if the
tests are not executed.
Related to: https://github.com/openhab/openhab-core/pull/873
=> don't drop the itests projects from reactor on skipTests

bundles/org.openhab.binding.ambientweather/README.md, bundles/org.openhab.binding.ambientweather/src/main/java/org/openhab/binding/ambientweather/internal/handler/AmbientWeatherEventListener.java
The process for requesting application keys has changed. Instead of emailing Ambient Weather support, application keys can be created using the same user interface that's used for API keys.
It's possible for an API to become invalid after it was determined to be valid during binding initialization. This change improves the user experience when that scenario occurs.
=> [ambientweather] Small improvements

bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/HueEmulationService.java
`getEnityStream` in the log interceptor seems to consume the input stream, and that is causing `java.lang.IllegalStateException: Entity input stream has already been closed.` exceptions.
For now the received http body will not be printed in debug mode.
Signed-of-by: David Graeff <david.graeff@web.de>
PS: No I cannot fix the signed-off-by message. This is a web edit.
=> [HueEmulation] Fix #5835

bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/AbstractMQTTThingHandler.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/handler/GenericMQTTThingHandler.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/handler/HomeAssistantThingHandler.java, bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/internal/handler/HomieThingHandler.java, bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/handler/AbstractBrokerHandler.java, bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/handler/BrokerHandler.java
Fixes #5786 
Fixes #5799 
After the refactoring from single connections to a shared connectionall subscriptions on a connections were cancelled after a thing on the broker/bridge was disposed. Also on disposal of the bridge it was not made sure that all home subscriptions were removed, resulting in multiuple subscription after the thing was re-initialized.
Also fixed some potential NPE.
=> [mqtt] fix subscription issues

bundles/org.openhab.binding.modbus/README.md
Clarify poller names must be unique  (seen several people fall into this trap)
=> [modbus] Clarify poller names must be unique

bundles/org.openhab.binding.dwdunwetter/src/main/java/org/openhab/binding/dwdunwetter/internal/config/DwdUnwetterConfiguration.java, bundles/org.openhab.binding.dwdunwetter/src/main/java/org/openhab/binding/dwdunwetter/internal/factory/DwdUnwetterHandlerFactory.java, bundles/org.openhab.binding.dwdunwetter/src/main/java/org/openhab/binding/dwdunwetter/internal/handler/DwdUnwetterHandler.java, bundles/org.openhab.binding.dwdunwetter/src/test/java/org/openhab/binding/dwdunwetter/DwdUnwetterHandlerTest.java
- Harden thing handler to fix potential NPEs like these:
```
at org.openhab.binding.dwdunwetter.internal.DwdUnwetterHandler.refresh(DwdUnwetterHandler.java:76) ~[?:?]
at org.openhab.binding.dwdunwetter.internal.DwdUnwetterHandler.handleCommand(DwdUnwetterHandler.java:62) ~[?:?]
at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.channelLinked(BaseThingHandler.java:229) ~[?:?]
at org.eclipse.smarthome.core.thing.link.ThingLinkManager.lambda$0(ThingLinkManager.java:266) ~[?:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?] …
```
=> [dwdunwetter] Harden thing handler to fix potential NPEs

bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/AbstractMQTTThingHandler.java
Resolves #5819 
Values are published to the commandTopic, not the stateTopic. 
=> [mqtt] fix wrong topic in logger

bundles/org.openhab.binding.mqtt.generic/src/main/resources/ESH-INF/config/dimmer-channel-config.xml, bundles/org.openhab.binding.mqtt.generic/src/main/resources/ESH-INF/config/number-channel-config.xml
Hi,
Based on my experiences, I propose a change in the documentation as Increase and Decrease are not accepted payload for an mqtt message.
Capital letters are required in the MQTT payload
https://community.openhab.org/t/counting-adding-pulses-from-espeasy-via-mqtt-thing/79644/3
=> [mqtt] Update documentation

itests/org.openhab.binding.nest.tests/itest.bndrun, itests/org.openhab.binding.nest.tests/logback.xml, itests/org.openhab.binding.nest.tests/src/main/java/org/openhab/binding/nest/handler/NestThingHandlerOSGiTest.java, itests/org.openhab.binding.nest.tests/src/main/java/org/openhab/binding/nest/internal/data/NestDataUtil.java
* Convert line endings read from files so tests work on Linux/Windows
* Reduce logging output by suppressing org.eclipse.jetty with logback configuration
Fixes #5906
=> [nest] Fix integration tests fail on Windows

bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/handler/SysteminfoHandler.java
Fix the typographical error 'instantate' and reduce the log level on the call from ERROR to WARN.
Found this defect while reading #5921.
=> [systeminfo] Fix typo and reduce log level

bundles/org.openhab.binding.openweathermap/README.md, bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/OpenWeatherMapBindingConstants.java, bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/handler/OpenWeatherMapWeatherAndForecastHandler.java, bundles/org.openhab.binding.openweathermap/src/main/resources/ESH-INF/thing/channel-types.xml
Visibility is missing in last commit, but I have found visibility supported in "OpenWeatherMapJsonWeatherData.java", not finished in other files. So I finish that.
I convert returned value from meter to kilometer. Because other weather sites (weatherunderground etc.) return kilometer, maybe we want show all visibilities in a single chart.
=> [openweathermap] New Feature: visibility channel.

bundles/org.openhab.binding.solarlog/README.md
This pull request fixes a typo in the solarlog binding documentation related to the totalpower data point. It is now consistent with the channel name.
=> [solarlog] Fix typo in solarlog binding documentation

bundles/org.openhab.binding.snmp/README.md, bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/SnmpDatatype.java, bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/SnmpTargetHandler.java, bundles/org.openhab.binding.snmp/src/main/resources/ESH-INF/thing/thing-types.xml, bundles/org.openhab.binding.snmp/src/test/java/org/openhab/binding/snmp/internal/SnmpTargetHandlerTest.java
SNMP does not support floating point numbers. Some devices use strings with the formatted number as a workaround. This PR adds support for that.
=> [snmp] add float support

bundles/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/handler/SpotifyBridgeHandler.java, bundles/org.openhab.binding.spotify/src/main/resources/ESH-INF/thing/thing-types.xml
Also set access token channel during polling and on refresh. Currently accesstoken is only set when token is refreshed.
Made accesstoken channel read only. It's set by the binding and used to the accesstoken to perform other calls, and it should not be set by the user. Also increased default poll time to 10 seconds, to decrease default load.
=> [spotify] Improve setting accesstoken channel

bundles/org.openhab.binding.systeminfo/README.md, bundles/org.openhab.binding.systeminfo/pom.xml, bundles/org.openhab.binding.systeminfo/src/main/feature/feature.xml, bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/SysteminfoHandlerFactory.java, bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/discovery/SysteminfoDiscoveryService.java, bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/handler/SysteminfoHandler.java, bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/model/DeviceNotFoundException.java, bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/model/OSHISysteminfo.java, bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/model/SysteminfoInterface.java, bundles/org.openhab.binding.systeminfo/src/main/resources/ESH-INF/thing/channels.xml, itests/org.openhab.binding.systeminfo.tests/itest.bndrun, itests/org.openhab.binding.systeminfo.tests/pom.xml, itests/org.openhab.binding.systeminfo.tests/src/main/java/org/openhab/binding/systeminfo/test/SysteminfoOSGiTest.java
* Update oshi to 4.0.0
* Update jna to 5.4.0
* Add null annotations
The `cpu#load` channel is removed because its data is no longer provided by oshi. The `load1`, `load5` and `load15` channels can be used instead. On the Oracle JVM this information can also be obtained using [com.sun.management.OperatingSystemMXBean.getSystemCpuLoad()](https://docs.oracle.com/javase/8/docs/jre/api/management/extension/com/sun/management/OperatingSystemMXBean.html#getSystemCpuLoad--).
See also:
* https://github.com/oshi/oshi/blob/master/UPGRADING.md
* https://github.com/oshi/oshi/blob/master/CHANGELOG.md#400-8102019
Fixes #5921
=> [systeminfo] Update dependencies and add null annotations

bundles/org.openhab.binding.mihome/README.md
Suggest updating gateway firmware after enabling developer mode based on the comments in this post: https://community.openhab.org/t/solved-openhab2-xiaomi-mi-gateway-does-not-respond/52963/193
Signed-off-by: John Schmitz <jswim400im@gmail.com>
=> [mihome] documentation: update firmware after enabling developer mode

bundles/org.openhab.binding.exec/README.md
Disclaimer: I am no expert on Exec binding.
Problem: the demo.rules is rather flaky (I suspect a partly implemented change in the past)
Most seriously, it includes a while-loop
while(yourcommand.state != OFF){
that will infinite loop on first run when the Item state is NULL
Using a wait loop is considered bad practice in rules anyway, I propose a demo restructure to separate event driven "do the thing" and "handle the results" rules.
There's a small issue where a Switch Item is used to kick off execution and also to report running/finished status.  This should have autoupdate disabled to avoid clashes resulting from response to command ON.
Further suggestions welcomed.
Maybe there should be a busy check before action, but it is only a demo and trying to avoid over-complicating it. …
=> [exec] Update demo in README.md

bundles/org.openhab.binding.lutron/README.md
This is a minor update to README.md. It adds two example rules to help illustrate usage of some items that have been confusing to users.
=> [lutron] Documentation update

bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/statedescription/AmazonEchoDynamicStateDescriptionProvider.java, bundles/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/OwDynamicStateDescriptionProvider.java
Don't return `originalStateDescription` as the service code depends on it being null if the specific provider called isn't handling the channel. See #3619
=> DynamicStateDescriptionProvider fixes

bundles/org.openhab.binding.nikohomecontrol/README.md
actionId and thermostatId are stringtype
=> [nikohomecontrol] Documentation correction textual configuration syntax

bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/IPBridgeHandler.java
This is a partial fix for #5898. The change catches a number format exception that sometimes results from the bridge handler passing through a malformed response, and just logs the bad response.  It seems the bridge handler may sometimes receive these bad responses from Caseta hubs when initially establishing a connection.
=> [lutron] Fix for stack trace in log from malformed responses

bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/airbase/AirbaseZoneInfo.java
Signed-off-by: Paul Smedley <paul@smedley.id.au>
=> [daikin] Fix broken zone updating

bundles/org.openhab.binding.modbus/src/test/java/org/openhab/binding/modbus/internal/ModbusDataHandlerTest.java
Related to: https://github.com/openhab/openhab-core/pull/987
Sorry for breaking the build.
In the long run I propose to move this class to be a real OSGi test and use methods like `registerVolatileStorageService` and `getService` to handle the requirements.
=> Fixed failing test after code refactoring

bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/MqttChannelTypeProvider.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/generic/internal/MqttThingHandlerFactory.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/AbstractComponent.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/BaseChannelConfiguration.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/DiscoverComponents.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/HaID.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/HandlerConfiguration.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/discovery/HomeAssistantDiscovery.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/handler/HomeAssistantThingHandler.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/util/FutureCollector.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/resources/ESH-INF/config/homeassistant-channel-config.xml, bundles/org.openhab.binding.mqtt.homeassistant/src/main/resources/ESH-INF/thing/homeassistant-thing.xml, bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/HAConfigurationTests.java, bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/HaIDTests.java, bundles/org.openhab.binding.mqtt.homie/src/test/java/org/openhab/binding/mqtt/homie/internal/handler/HomieThingHandlerTests.java, itests/org.openhab.binding.mqtt.homeassistant.tests/src/main/java/org/openhab/binding/mqtt/DiscoverComponentsTest.java, itests/org.openhab.binding.mqtt.homeassistant.tests/src/main/java/org/openhab/binding/mqtt/EmbeddedBrokerTools.java, itests/org.openhab.binding.mqtt.homeassistant.tests/src/main/java/org/openhab/binding/mqtt/HomeAssistantMQTTImplementationTest.java, itests/org.openhab.binding.mqtt.homeassistant.tests/src/main/java/org/openhab/binding/mqtt/ThingChannelConstants.java
This will group components into things by device.
The component configuration may contain device information.
If multiple components with the same device information are discovered, then they are created as groups in one thing.
Additionally, the complete topic (including the component parts) is used in the thing and component configuration to allow the same object_id to be used for different components by the devices.
See: https://www.home-assistant.io/docs/mqtt/discovery/:
- <object_id>: The ID of the device. This is only to allow for separate topics for each device and is not used for the entity_id.
I do not have many devices to test: Please, everybody also test and give feedback
This should fix #5632
=> [mqtt] homeassisant: Group components by device

bundles/org.openhab.binding.chromecast/README.md
[Chromecast ] Update README.md to fix example things to working format.
Wrong format for the thing file example and it refused to work until these changes were made. Earlier on in the readme it gives a correct example for an audiogroup and mentions that the PORT must be specified. 100% certain this is an error in the readme and I have tested the suggested changes for a few weeks now.
=> [chromecast] Update README.md to fix example things to working format

bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/handler/RFXComHandler.java, bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComDeviceMessage.java, bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComDeviceMessageImpl.java, bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComLighting1Message.java
Sends commands on control channels so that switches behave as expected. Maps X10 SS13 bright/dim to openHAB INCREASE/DECREASE. Fixes the update/command distribution loop so it doesn't abort as soon as an inappropriate channel is seen but checks the others as well (this makes LWRF mood buttons work, quite possibly other things too).
Fixes #2102
=> [rfxcom] Send commands on control channels so that switches behave as expected

bundles/org.openhab.binding.nibeheatpump/src/test/java/org/openhab/binding/nibeheatpump/internal/handler/NibeHeatPumpHandlerNibe2StateTest.java
- Consider local settings for formatted values in unit tests
Prevents errors like these:
```
[ERROR] convertNibeValueToStateTest[5: f(43.009, 287, Number)=28.7](org.openhab.binding.nibeheatpump.internal.handler.NibeHeatPumpHandlerNibe2StateTest)  Time elapsed: 0.025 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<28[.]7> but was:<28[,]7>
at org.openhab.binding.nibeheatpump.internal.handler.NibeHeatPumpHandlerNibe2StateTest.convertNibeValueToStateTest(NibeHeatPumpHandlerNibe2StateTest.java:113)
```
=> [nibeheatpump] Consider local settings for formatted values in unit tests

bundles/org.openhab.binding.satel/README.md, bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/SatelBindingConstants.java, bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/config/SatelThingConfig.java, bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/discovery/SatelDeviceDiscoveryService.java, bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/handler/SatelOutputHandler.java, bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/handler/SatelStateThingHandler.java, bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/handler/SatelThingHandler.java, bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/handler/SatelZoneHandler.java, bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/handler/WirelessChannelsHandler.java, bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/types/IntegraType.java, bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/types/StateType.java, bundles/org.openhab.binding.satel/src/main/resources/ESH-INF/thing/common.xml, bundles/org.openhab.binding.satel/src/main/resources/ESH-INF/thing/output.xml, bundles/org.openhab.binding.satel/src/main/resources/ESH-INF/thing/zone.xml
This PR adds additional channels for wireless devices, like AXD-200, APD-200, etc. 
These devices do not differ much from corresponding wired devices and actually they can be used with existing version of the binding. However most of them are battery devices and they provide additional "low battery" signal to the system. Also when communication is broken, for example when battery is completely exhausted in the device, the system indicates this situation with "no communication" signal. 
Both of the signals are supported in this new version of the binding by adding two additional channels to "Zone" and "Output" things. To make them available the device must be configured as "wireless" device in the thing configuration.
=> [satel] Added channels for troubles in wireless devices

bundles/org.openhab.binding.milight/README.md
Addition of 'repeat' and 'delayTime' description for manual Thing configuration, as this is not obvious either from the Docs or the Paper UI titles of these options.
=> [milight] Update README.md to include manual Thing defintion options 'repeat' and 'delayTime'

bundles/org.openhab.io.mqttembeddedbroker/src/main/feature/feature.xml, itests/org.openhab.io.mqttembeddedbroker.tests/.classpath, itests/org.openhab.io.mqttembeddedbroker.tests/.project, itests/org.openhab.io.mqttembeddedbroker.tests/NOTICE, itests/org.openhab.io.mqttembeddedbroker.tests/itest.bndrun, itests/org.openhab.io.mqttembeddedbroker.tests/pom.xml, itests/org.openhab.io.mqttembeddedbroker.tests/src/main/java/org/openhab/io/mqttembeddedbroker/EmbeddedBrokerTools.java, itests/org.openhab.io.mqttembeddedbroker.tests/src/main/java/org/openhab/io/mqttembeddedbroker/MoquetteTest.java, itests/pom.xml
Fixes #5981 
The latest release version 0.12.1 has a bug with subscriptions which renders the module useless for other openHAB addons. Until a new release is available that includes the fix we use our own version.
Also add some integration tests that at least ensure that the broker is coming up and accepts publications and subscriptions. 
=> [mqttembeddedbroker] bump moquette  to 0.13.0.OH2

bundles/org.openhab.binding.sonos/src/main/resources/ESH-INF/thing/SYMFONISK.xml
Exactly as for other Sonos thing types.
=> [sonos] Don't list SYMFONISK as choice for creating thing type

itests/org.openhab.binding.mqtt.homie.tests/itest.bndrun, itests/org.openhab.binding.mqtt.homie.tests/pom.xml, itests/org.openhab.binding.mqtt.homie.tests/src/main/java/org/openhab/binding/mqtt/HomieImplementationTest.java
Fixes #5905
I reworked the tests a little bit and now they succeed when using an external broker (just change the address of the publishConnection from `embeddedConnection.getHost()` to the IP/hostname of an external broker).
What I can tell is that the subscription to 'homie/#' is obviously received by moquette but NO topics are send back to the client. When using my loccal mosquitto, this works. I'm out of ideas why this happens. Either paho is really sending the messages with QoS 0 (specs allow the broker to discard those, even if retained and moquette is known to do so), moquette is ignoring teh retained flag or not properly expanding the subscription wildcard.
=> [mqtt][homie] fix integration tests

bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/Connection.java
Small change to fix the login in Australia
=> [amazonechocontrol] Bugfix for login in Australia

bundles/org.openhab.binding.heos/src/main/java/org/openhab/binding/heos/handler/HeosGroupHandler.java
Fixes:
```
[ERROR] org.openhab.binding.heos.handler.HeosGroupHandler.java:[44]
Illegal class is passed to LoggerFactory#getLogger(Class). It should be one of [org.openhab.binding.heos.handler.HeosGroupHandler].
```
=> [heos] Fix logger class causing SAT error

buildci.sh
When Travis builds a single add-on it does run SAT but doesn't properly fail the build on errors. So you'll then only find out about this when Jenkins also completes building. By that time the PR might already have been merged. So it's better to prevent this from happening and save everyone some time. :wink: 
Example: https://github.com/openhab/openhab2-addons/pull/2886
Fix: https://github.com/openhab/openhab2-addons/pull/6061
=> Fix Travis CI not failing on SAT errors

bundles/org.openhab.binding.tradfri/README.md, bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/handler/TradfriGatewayHandler.java
This PR drops the support for the tradfri gateway below firmware version 1.2.42.
Fixes #5489.
=> [tradfri] Drop support for gateway below firmware version 1.2.42

itests/org.openhab.binding.feed.tests/itest.bndrun, itests/org.openhab.binding.feed.tests/pom.xml, itests/org.openhab.binding.feed.tests/src/main/java/org/openhab/binding/feed/test/FeedHandlerTest.java, itests/org.openhab.io.hueemulation.tests/itest.bndrun, itests/org.openhab.io.hueemulation.tests/pom.xml, itests/org.openhab.io.hueemulation.tests/src/main/java/org/openhab/io/hueemulation/internal/HueEmulationServiceOSGiTest.java
Hard coded ports may not be available on each computer or when running builds in parallel. Instead assign a random available port. In Eclipse the default port is still used because it doesn't execute the build-helper-maven-plugin goal.
=> Use random available org.osgi.service.http.port in itests

itests/org.openhab.binding.feed.tests/src/main/java/org/openhab/binding/feed/test/FeedHandlerTest.java, itests/org.openhab.binding.ntp.tests/src/main/java/org/openhab/binding/ntp/test/NtpOSGiTest.java
DNS lookup of invalid hosts may take quite some time when using slow DNS servers.
=> Improve itests reliability when hostname resolution is slow

bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/EnOceanBindingConstants.java, bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/A5_14/A5_14_0A.java, bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/EEPType.java, bundles/org.openhab.binding.enocean/src/main/resources/ESH-INF/thing/MechanicalHandle.xml, bundles/org.openhab.binding.enocean/src/main/resources/ESH-INF/thing/channels.xml
This adds the A5-14-0A epp (compare https://www.enocean-alliance.org/wp-content/uploads/2018/02/EEP268_R3_Feb022018_public.pdf) which extends A5-14-09 with a vibration channel through the DB0.0 bit.
This profile is implemented e.g. by:
- Maco mTRONIC multi sensor
- Eltako ftkb-hg
=> [enocean] Add enocean A5-14-0A profile

bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/Config.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/discovery/HueBridgeDiscoveryParticipant.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueBridgeHandler.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueLightHandler.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueSensorHandler.java
- Fix assignment of serial number property - it is not always the same like the mac address (e.g. if you are using an emulated Hue API)
- Added properties for mac address and model id
The serial number is the representational property of discovered devices. If we overwrite it with a wrong value the same device will be discovered again and again. The calculation of the serial number from the bridge id is derived from nUPnP discovery:
https://github.com/openhab/openhab2-addons/blob/a1d1c9cc3762ffee08c455a4d1928b1f82868a25/bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/discovery/HueBridgeNupnpDiscovery.java#L89
=> [hue] Fix assignment of serial number property

bundles/org.openhab.binding.snmp/README.md, bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/SnmpDatatype.java, bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/SnmpTargetHandler.java, bundles/org.openhab.binding.snmp/src/main/resources/ESH-INF/thing/thing-types.xml, bundles/org.openhab.binding.snmp/src/test/java/org/openhab/binding/snmp/internal/SnmpTargetHandlerTest.java, bundles/org.openhab.binding.snmp/src/test/java/org/openhab/binding/snmp/internal/StringChannelTest.java, bundles/org.openhab.binding.snmp/src/test/java/org/openhab/binding/snmp/internal/SwitchChannelTest.java
This adds the option of hex strings (received data is converted to hexadecimal representation). Also adds tests.
=> [snmp] add hexstring channel datatype

bundles/org.openhab.binding.daikin/src/main/resources/ESH-INF/binding/binding.xml, bundles/org.openhab.binding.daikin/src/main/resources/ESH-INF/config/config.xml
Due to indentation on tags the things don't show up in PaperUI. This seems to be related to usage of spaces and tabs in tags. This problem occurs when using this binding in a openHAB 2.4.0 installation.
=> [daikin] Fixed ESH-INF xml

bundles/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/handler/SpotifyHandleCommands.java
In setting volume a check on DecimalType was done before PercentType. However PercentType is a subclass of DecimalType so that code will never be reached and a PercentType command is always uncessary converted to a PercentType. The converting to PrecentType is to enforce a range check on the int value.
=> [spotify] Removed unnecessary cast setting volume

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoDevices.java
Fixes S6 version with different device string
=> [miio] add devicestring for vacuum s6

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/usage_question.md
The template labels are also being used in [openhab-android](https://github.com/openhab/openhab-android/issues) and I think it might save us some labelling work. I think we might only need to update labels for issues of new add-ons when these are not created using "Open a regular issue.". 
Improvements:
* Replace binding with add-on because the repo contains more than just bindings
* Add note on using triple backticks to format log/code
* Update versions in examples so users can easier relate to these
=> Assign labels using issue templates and improvements

bundles/org.openhab.binding.modbus/src/test/java/org/openhab/binding/modbus/internal/ModbusDataHandlerTest.java, bundles/org.openhab.binding.modbus/src/test/java/org/openhab/binding/modbus/internal/ModbusPollerThingHandlerTest.java
Fix the build by ignoring the tests that fail because reflection is used to modify the BaseThingHandler.thingRegistry field that has been removed in openhab/openhab-core#1041.
See: https://github.com/openhab/openhab2-addons/issues/6171
=> [modbus] Ignore failing tests

bundles/org.openhab.binding.lutron/README.md, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/config/IPBridgeConfig.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/IPBridgeHandler.java, bundles/org.openhab.binding.lutron/src/main/resources/ESH-INF/thing/thing-types.xml
This PR adds support for a "delay" parameter to the ipbridge thing. 
From the updated README.md:
```The optional advanced parameter `delay` can be used to set a delay (in milliseconds) between transmission of integration commands to the bridge device. This may be used for command send rate throttling. It can be set to an integer value between 0 and 250 ms, and defaults to 0 (no delay). It is recommended to leave it set to 0 unless you experience problems with commands sent to Caseta hubs being dropped/ignored.```
This change is being made in response to Issue #6012, which contains a report of problems with commands being dropped when sent to a Caseta PRO hub in large numbers.  Since so far this problem seems to be rare, the default for the new delay parameter is left at 0, which results …
=> [lutron] Add delay parameter for command rate throttling

CODEOWNERS, bom/openhab-addons/pom.xml, bundles/org.openhab.binding.nikobus/.classpath, bundles/org.openhab.binding.nikobus/.project, bundles/org.openhab.binding.nikobus/NOTICE, bundles/org.openhab.binding.nikobus/README.md, bundles/org.openhab.binding.nikobus/pom.xml, bundles/org.openhab.binding.nikobus/src/main/feature/feature.xml, bundles/org.openhab.binding.nikobus/src/main/java/org/openhab/binding/nikobus/internal/NikobusBindingConstants.java, bundles/org.openhab.binding.nikobus/src/main/java/org/openhab/binding/nikobus/internal/NikobusHandlerFactory.java, bundles/org.openhab.binding.nikobus/src/main/java/org/openhab/binding/nikobus/internal/handler/NikobusBaseThingHandler.java, bundles/org.openhab.binding.nikobus/src/main/java/org/openhab/binding/nikobus/internal/handler/NikobusDimmerModuleHandler.java, bundles/org.openhab.binding.nikobus/src/main/java/org/openhab/binding/nikobus/internal/handler/NikobusModuleHandler.java, bundles/org.openhab.binding.nikobus/src/main/java/org/openhab/binding/nikobus/internal/handler/NikobusPcLinkHandler.java, bundles/org.openhab.binding.nikobus/src/main/java/org/openhab/binding/nikobus/internal/handler/NikobusPushButtonHandler.java, bundles/org.openhab.binding.nikobus/src/main/java/org/openhab/binding/nikobus/internal/handler/NikobusRollershutterModuleHandler.java, bundles/org.openhab.binding.nikobus/src/main/java/org/openhab/binding/nikobus/internal/handler/NikobusSwitchModuleHandler.java, bundles/org.openhab.binding.nikobus/src/main/java/org/openhab/binding/nikobus/internal/protocol/NikobusCommand.java, bundles/org.openhab.binding.nikobus/src/main/java/org/openhab/binding/nikobus/internal/protocol/NikobusConnection.java, bundles/org.openhab.binding.nikobus/src/main/java/org/openhab/binding/nikobus/internal/protocol/SwitchModuleCommandFactory.java, bundles/org.openhab.binding.nikobus/src/main/java/org/openhab/binding/nikobus/internal/protocol/SwitchModuleGroup.java, bundles/org.openhab.binding.nikobus/src/main/java/org/openhab/binding/nikobus/internal/utils/CRCUtil.java, bundles/org.openhab.binding.nikobus/src/main/java/org/openhab/binding/nikobus/internal/utils/Utils.java, bundles/org.openhab.binding.nikobus/src/main/resources/ESH-INF/binding/binding.xml, bundles/org.openhab.binding.nikobus/src/main/resources/ESH-INF/thing/thing-types.xml, bundles/pom.xml
Signed-off-by: Boris Krivonog boris.krivonog@gmail.com (github: crnjan)
=> [nikobus] Nikobus Binding initial contribution

bundles/org.openhab.binding.lutron/README.md, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/KeypadComponent.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/discovery/LutronDeviceDiscoveryService.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/discovery/project/ComponentType.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/BaseKeypadHandler.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/GrafikEyeKeypadHandler.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/IntlKeypadHandler.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/KeypadHandler.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/PicoKeypadHandler.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/QSIOHandler.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/TabletopKeypadHandler.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/VcrxHandler.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/VirtualKeypadHandler.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/keypadconfig/KeypadConfig.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/keypadconfig/KeypadConfigGrafikEye.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/keypadconfig/KeypadConfigIntlSeetouch.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/keypadconfig/KeypadConfigPico.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/keypadconfig/KeypadConfigSeetouch.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/keypadconfig/KeypadConfigTabletopSeetouch.java
This PR adds support to the Lutron binding for discovery of keypad models. This will finally eliminate the need for RadioRA 2 and HomeWorks QS users to manually select their keypad models after discovery, which has proven to be a major source of confusion and errors. Unfortunately, implementing it required a considerable number of changes to the existing keypad handlers so that the discovery code could have access to the necessary keypad configuration information.
It includes the following changes:
* Moves keypad configuration data from keypad handlers to new keypad configuration classes (base class KeypadConfig) for all keypad handlers supporting multiple models.
* Adds ComponentType to keypad component definitions.
* Updates existing keypad handlers to use new keypad configuration …
=> [lutron] Add discovery of keypad models

bundles/org.openhab.binding.lutron/README.md, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/ShadeHandler.java
This PR fixes a problem where the shade level channel of a shade thing would not be updated with the correct level when an Up or Down command was sent to the shade and it subsequently stopped in the full up or full down position.  This is because the main repeater uses a different response code (```~OUTPUT,<id>,32,2,<position>```) to send a position update in these cases.
=> [lutron] Fix shade handler position update after Up/Down command

bundles/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/handler/YamahaBridgeHandler.java, bundles/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/protocol/ConnectionStateListener.java, bundles/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/protocol/xml/XMLConnection.java, bundles/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/protocol/xml/XMLProtocolFactory.java, bundles/org.openhab.binding.yamahareceiver/src/test/java/org/openhab/binding/yamahareceiver/internal/YamahaReceiverHandlerTest.java
Fixes #5495.
Fix already verified by the requesting user & myself (see issue for more details).
Potentially other users can confirm that too.
Approach taken to fix this:
- When it is detected the connectivity has been lost to the Yamaha device the bridge and zones are marked as offline.
- The device status refresh poll is still happening with the user configured interval. 
- Once communication to the device is successful in a refresh poll, the bridge and zones are marked as online and binding becomes operational.
-----
Your Pull Request will automatically be built and available under the following folder:
https://openhab.jfrog.io/openhab/libs-pullrequest-local/org/openhab/
=> [yamaha] Binding remain offline after device comes back online

bundles/org.openhab.binding.hue/README.md, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/FullSensor.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/HueBindingConstants.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/HueBridge.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/HueThingHandlerFactory.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/StateUpdate.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/discovery/HueLightDiscoveryService.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueBridgeHandler.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueClient.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueSensorHandler.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/sensors/ClipHandler.java, bundles/org.openhab.binding.hue/src/main/resources/ESH-INF/thing/CLIPGenericFlagSensor.xml, bundles/org.openhab.binding.hue/src/main/resources/ESH-INF/thing/CLIPGenericStatusSensor.xml, bundles/org.openhab.binding.hue/src/main/resources/ESH-INF/thing/channels.xml
1: get/set status of CLIPGenericStatusSensor
2: get/set flag of CLIPGenericFlagSensor
HUE using CLIPGenericStatusSensor or CLIPGenericFlagSensor to save state of rules. So when you press the button on switch, you can active different lighting scenes. Wake up timer also using CLIPGenericFlagSensor. And you can add none-zigbee sensor or none-zigbee switch. You only need get/put json to url like http://192.168.0.66/api/NX5KJ0AtXMG9GpazD6j-ish-fQvJQ4FwsqXfjh7v/sensors/5. Many DIY users use CLIP sensor.
API reference: https://developers.meethue.com/develop/hue-api/supported-devices/#clipSensors
=> [hue] New Features: CLIP Sensor Support

bundles/org.openhab.binding.sonos/README.md
#6123 
- Clarification: you need to define them in upper case -> you need to define them **exactly as stated above**
- Added description how to acquire the UDN
Still missing: clarification for section **Binding Configuration**
Signed-off-by: Felix Miske <github@miske.email>
=> [sonos] Update README.md

bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/rest/CommonSetup.java
Fixes build issue seen in https://ci.openhab.org/job/openHAB2-Bundles/784, which turned up after merging https://github.com/openhab/openhab-core/pull/1099.
=> [hueemulation] fix to fit non-nullness expectations

bundles/org.openhab.binding.lgwebos/src/main/resources/ESH-INF/thing/thing-types.xml, bundles/org.openhab.binding.loxone/src/main/resources/ESH-INF/thing/thing-types.xml, bundles/org.openhab.binding.mail/src/main/resources/ESH-INF/thing/thing-types.xml, bundles/org.openhab.binding.mqtt.homeassistant/src/main/resources/ESH-INF/config/homeassistant-channel-config.xml, bundles/org.openhab.binding.network/src/main/resources/ESH-INF/thing/thing-types.xml, bundles/org.openhab.binding.omnikinverter/src/main/resources/ESH-INF/binding/binding.xml, bundles/org.openhab.binding.omnikinverter/src/main/resources/ESH-INF/thing/thing-types.xml, bundles/org.openhab.binding.onewire/src/main/resources/ESH-INF/config/config.xml, bundles/org.openhab.binding.onewire/src/main/resources/ESH-INF/thing/deprecated.xml, bundles/org.openhab.binding.windcentrale/src/main/resources/ESH-INF/binding/binding.xml, bundles/org.openhab.binding.windcentrale/src/main/resources/ESH-INF/thing/millThing.xml
Due to incorrect configured SAT these errors violations were not reported. When the SAT will be updated these violations will cause build errors.
Related to: openhab/static-code-analysis#357
=> [ESH-INF] Fix indentation only tabs in ESH-INF files

bundles/org.openhab.binding.mqtt/README.md, bundles/org.openhab.binding.mqtt/src/main/resources/ESH-INF/thing/thing-types.xml
Fixes #6100 
This brings implementation and documentation for last will and testament messages and thing-type XML of the broker thing in sync.
Also removes option to retain messages on connections (which was not working anyway because of a wrong XML defintion). This should be configured on the channels (topics).
=> [mqtt] adjust XML to config, remove retain config option for connection

bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/SnmpTargetHandler.java
Fixes #6055 
If a channel receives a command before the SNMP target address has been resolved, the bindings tries to send to a null target address. This leads to an NPE in SNMP4J.
=> fix SNMP startup exceptions

itests/org.openhab.binding.astro.tests/itest.bndrun, itests/org.openhab.binding.avmfritz.tests/itest.bndrun, itests/org.openhab.binding.feed.tests/itest.bndrun, itests/org.openhab.binding.mqtt.homeassistant.tests/itest.bndrun, itests/org.openhab.binding.mqtt.homie.tests/itest.bndrun, itests/org.openhab.binding.nest.tests/itest.bndrun, itests/org.openhab.binding.ntp.tests/itest.bndrun, itests/org.openhab.binding.systeminfo.tests/itest.bndrun, itests/org.openhab.binding.tradfri.tests/itest.bndrun, itests/org.openhab.binding.wemo.tests/itest.bndrun, itests/org.openhab.io.mqttembeddedbroker.tests/itest.bndrun, itests/org.openhab.persistence.mapdb.tests/itest.bndrun
Depends on https://github.com/openhab/openhab-core/pull/1127.
=> Resolve itest runbundles for update to Mockito 3.1.0

bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/ChannelState.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/AbstractComponent.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/CChannel.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/CFactory.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/ComponentAlarmControlPanel.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/ComponentBinarySensor.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/ComponentCamera.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/ComponentCover.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/ComponentFan.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/ComponentLight.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/ComponentLock.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/ComponentSensor.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/ComponentSwitch.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/DiscoverComponents.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/discovery/HomeAssistantDiscovery.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/handler/HomeAssistantThingHandler.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/resources/ESH-INF/config/homeassistant-channel-config.xml, itests/org.openhab.binding.mqtt.homeassistant.tests/src/main/java/org/openhab/binding/mqtt/DiscoverComponentsTest.java
Initialization was not stable so i investigated and found some problems:
* <code>stop()</code> on the thing handler would not unsubscribe from the topics (<code>map()</code> as last thing on a stream is noop)
* starting a previously stoped CChannel laked the updateListener callback.
* During initialization (<code>accept()</code>) would add channels to the thing by using <code>updateThing</code> which in turn would stop and start the thing.
* discovery would find and remove things multiple times, if multiple components where found.
<code>stop()</code> will now unregister subscriptions (if started before) and wait for it to finish. The wait is needed or else a later <code>start()</code> might be executed before the actual unsubscribe. (Was this a memory leak?)
New channels are added to the …
=> [mqtt.homeassistant] Improve initialization sequence

bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/LGWebOSHandlerFactory.java
Fixing bug reported by lgwebos beta testers in community. 
Channel and app listing are json docs up to 3MB (instead of 2MB).
=> [lgwebos] Adjusting websocket max message size 

bundles/org.openhab.transform.map/src/test/java/org/openhab/transform/map/internal/MapTransformationServiceTest.java
Use activate/deactivate while testing so the watched directories are properly released by the changes made in openhab/openhab-core#965.
Fixes #5854
=> Fix MapTransformationServiceTest on Windows

bundles/org.openhab.binding.mqtt.generic/README.md, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/ChannelState.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/ChannelStateTransformation.java
Fixes #6224
Abort transformation if one returns null or fails. The previous implementation returned the original value. This is unexpected and not what would be expected if e.g. a regex doesn't match.
=> [mqtt] fix incoming transformation in case of failure

bundles/org.openhab.binding.bluetooth.bluez/src/main/java/org/openhab/binding/bluetooth/bluez/handler/BlueZBridgeHandler.java
[bluetooth] Exception from bluez can be without a message
Avoid NullPointerException in case exception doesn't has a message
=> [bluetooth] Exception from bluez can be without a message

tools/static-code-analysis/checkstyle/suppressions.xml
According to the [coding guidelines](https://www.openhab.org/docs/developer/guidelines.html#null-annotations) we should use null annotations so I was surprised to find the SAT check for this suppressed.
=> Remove NullAnnotationsCheck suppression

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoDevices.java
Adds support for Mi Robot Vacuum 1S
https://xiaomi-mi.com/cleaning-gear/mijia-1s-robot-vacuum-cleaner-/
Related community post: https://community.openhab.org/t/xiaomi-robot-vacuum-binding/31317/1092
Signed-off-by: Siegfried Huismann <sihui@gmx.de>
=> [miio] Update MiIoDevices.java

bundles/org.openhab.binding.loxone/src/test/java/org/openhab/binding/loxone/internal/controls/LxServerHandlerDummy.java
Test resource JSON file was read without specifying character set encoding. On Windows the default character set is not UTF-8 and this caused the unicodes in the JSON file to be incorrectly read and as a result one of the tests failed.
See defect #6273 
Signed-off-by: Pawel Pieczul <pieczul@gmail.com>
Fixes #6273
=> [Loxone] Fix for #6273 - one of tests failing on Windows

bundles/org.openhab.binding.doorbird/src/main/java/org/openhab/binding/doorbird/internal/listener/DoorbirdEvent.java, bundles/org.openhab.binding.loxone/src/test/java/org/openhab/binding/loxone/internal/controls/LxServerHandlerDummy.java, bundles/org.openhab.binding.neeo/src/main/java/org/openhab/binding/neeo/internal/net/HttpResponse.java, bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/http/WemoHttpCall.java, bundles/org.openhab.io.transport.modbus/src/test/java/org/openhab/io/transport/modbus/test/BitUtilitiesExtractStringFromRegistersTest.java
This prevents typos, improves performance and makes it easier to find other code using these standard charsets.
=> Replace Charset.forName calls with StandardCharsets constants

bundles/org.openhab.binding.lutron/README.md, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/LutronBindingConstants.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/LutronHandlerFactory.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/config/BlindConfig.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/discovery/LutronDeviceDiscoveryService.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/BlindHandler.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/IPBridgeHandler.java, bundles/org.openhab.binding.lutron/src/main/resources/ESH-INF/thing/thing-types.xml
This PR adds support for Lutron Sivoia QS Venetian Blinds and Horizontal Sheer Blinds through a new "blind" thing. It also contains a minor fix to IPBridgeHandler for a problem that was discovered during testing. I have tagged the blind thing as "Beta" in README.md, because I have had no success getting anyone in the community forum to test it out.  However, I have tested it myself using dummy devices on my RadioRA 2 system and found no problems.
Closes #3962
=> [Lutron] Add support for venetian blinds

bundles/org.openhab.binding.onewire/README.md
Figured out that parameter value true/false for parameter "ignorepor" must not be set in quotation marks otherwise initialization of thing fails with "[...] changed from OFFLINE (CONFIGURATION_ERROR): required properties missing to UNINITIALIZED [...]"
Therefore added one sentence in documentation chapter "temperature" and according parameter in example section.
Tested on 2.5M2
Signed-off-by: Michael Hoffmann <bitforker@gmail.com>
=> [onewire] Extend documentation: Parameter value "ignorepor" must not use quotation marks

bundles/org.openhab.binding.ambientweather/README.md, bundles/org.openhab.binding.ambientweather/src/main/java/org/openhab/binding/ambientweather/internal/AmbientWeatherBindingConstants.java, bundles/org.openhab.binding.ambientweather/src/main/java/org/openhab/binding/ambientweather/internal/AmbientWeatherHandlerFactory.java, bundles/org.openhab.binding.ambientweather/src/main/java/org/openhab/binding/ambientweather/internal/processor/ProcessorFactory.java, bundles/org.openhab.binding.ambientweather/src/main/java/org/openhab/binding/ambientweather/internal/processor/RemoteSensor.java, bundles/org.openhab.binding.ambientweather/src/main/java/org/openhab/binding/ambientweather/internal/processor/Ws0265Processor.java, bundles/org.openhab.binding.ambientweather/src/main/resources/ESH-INF/thing/channel-group-types.xml, bundles/org.openhab.binding.ambientweather/src/main/resources/ESH-INF/thing/ws0265.xml
Add the model WS-0265 weather station, which includes support for 2 new channels for remote sensors.
Also convert to constructor injection.
=> [ambientweather] Add model WS-0265

bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudClient.java
So far, there is no trace in the log file, if the initial cloud connection fails for some reason.
=> [openhabcloud] Log error upon connection problems

bundles/org.openhab.binding.nest/README.md
Adds a note about WWN retirement to help users making a better decision about investing into Nest devices. They cannot integrate these devices into openHAB using this binding without an existing WWN account.
=> [nest] Add note about WWN retirement

bundles/org.openhab.binding.nikobus/README.md, bundles/org.openhab.binding.nikobus/src/main/java/org/openhab/binding/nikobus/internal/NikobusBindingConstants.java, bundles/org.openhab.binding.nikobus/src/main/java/org/openhab/binding/nikobus/internal/handler/NikobusBaseThingHandler.java, bundles/org.openhab.binding.nikobus/src/main/java/org/openhab/binding/nikobus/internal/handler/NikobusModuleHandler.java, bundles/org.openhab.binding.nikobus/src/main/java/org/openhab/binding/nikobus/internal/handler/NikobusPushButtonHandler.java, bundles/org.openhab.binding.nikobus/src/main/resources/ESH-INF/thing/thing-types.xml
Should resolve pending issues for Nikobus v2 binding, as discussed in [#6181](https://github.com/openhab/openhab2-addons/pull/6181).
Signed-off-by: Boris Krivonog <boris.krivonog@inova.si>
=> [nikobus ]Added address as parameter and not using id anymore + updated readme.

bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/discovery/MieleMDNSDiscoveryParticipant.java, bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/MieleBridgeHandler.java
When a bridge was manually added with an invalid ip address, it was shown as ONLINE nonetheless.
This PR makes its status to start as UNKNOWN and upon the first polling result, it will be switched to ONLINE or OFFLINE.
=> [miele] Fixed bridge status handling upon initialization

tools/static-code-analysis/checkstyle/ruleset.properties
Using the OHC serial transport (org.eclipse.smarthome.io.transport.serial) is preferred over directly using specific serial communication libraries.
---
The changes will log the following warnings (and add them to the SAT results):
```
[WARNING] org.openhab.binding.oceanic.internal.handler.SerialOceanicThingHandler.java:[32]
The package gnu.io.CommPortIdentifier should not be used.
[WARNING] org.openhab.binding.oceanic.internal.handler.SerialOceanicThingHandler.java:[33]
The package gnu.io.NoSuchPortException should not be used.
[WARNING] org.openhab.binding.oceanic.internal.handler.SerialOceanicThingHandler.java:[34]
The package gnu.io.PortInUseException should not be used.
[WARNING] org.openhab.binding.oceanic.internal.handler.SerialOceanicThingHandler.java:[35]
The package …
```
=> Add gnu.io, javax.comm to forbidden packages

buildci.sh
Previously the buildci.sh built a single addon change by entering the
bundle directory and executing mvn clean install Unfortunately if the
bundle depends on other bundles they were not built, and this could lead
to build failures.
Changed buildci.sh to execute mvn clean install -am -pl :artifactid in
such cases instead of a simple directory build.
Also I believe the previous version did not look for the test in the correct directory.
=> buildci.sh builds single addon with dependencies

bundles/org.openhab.binding.mqtt.generic/README.md, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/ChannelState.java
Fixes a null-type mismatch introduced with #6239 
=> [mqtt] fix compilation error

bundles/org.openhab.binding.volvooncall/README.md, bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/action/VolvoOnCallActions.java, bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/handler/VehicleHandler.java, bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/handler/VolvoOnCallBridgeHandler.java
Updates to also enable actions for Volvo models being preclimatizationSupported rather than remoteHeaterSupported.
Also made changes to commands (heater/preclimatization and lock) as a "{}" attribute apparently is required included as part of the POST request sent to vocapi (as identified by bundle created for Homey).
Relate to ongoing discussion in OH forum:
https://community.openhab.org/t/solved-help-with-sending-command/7046/202
**NOTE:** Disregard changes/commit to 'VehicleStateDescriptionProvider.java' as the changes in my commit relate to changes needed to run the binding under my setup: OH 2.4.0 stable release. Later versions of volvooncall binding have implemented 'BaseDynamicStateDescriptionProvider' which apparently is not supported by 2.4.0 stable release.
=> [Volvooncall] Updates to include Volvo V90 XC and to handle lock, heater and engine commands

bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/VolumeControlVolume.java, bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/handler/LGWebOSTVSocket.java
It does not make sense to subscribe to relative volume changes, as this binding will not know which absolute volume is set on the receiver or amplifier.
=> [LG WebOS] Fixing Changing volume with external speaker

bundles/org.openhab.binding.tplinksmarthome/README.md
- Added explanation about deviceId
- Use the word Power for Switch as that is the label of the system channel power.
Apparently these document issues led to questions on the forum.
=> [tplinksmarthome] Clarified documentation

bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/HDPowerViewWebTargets.java, bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/discovery/HDPowerViewShadeDiscoveryService.java, bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewHubHandler.java, bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewShadeHandler.java
The Powerview hub seems to return an HTTP 423 (resource locked) response every night that caused a full "horror" log entry with a complete dump of the exception. Such HTTP 423 errors seem to be a regular occurrence and they are always resolved on the next polling cycle 60 seconds later. So such an event should not produce a "horror dump" in the log file that might scare the user.
Furthermore it was noted that each Shade Handler on being initialized would unnecessarily destroy and re-create the Hub Handler's polling timer. This is unnecessary because the Hub Handler has already created a perfectly good polling timer in the first place.
So the following changes have been made..
1. Explicitly catch HTTP 423 errors and return a logger warning only (rather than a logger error).
2. Modify all …
=> [hdpowerview] simplify polling initialization; downgrade and improve some error logging

bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/LGWebOSBindingConstants.java, bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/LGWebOSHandlerFactory.java, bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/TVControlChannel.java, bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/discovery/LGWebOSUpnpDiscoveryParticipant.java, bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/handler/LGWebOSHandler.java, bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/handler/LGWebOSTVSocket.java
- This fixes an issue with the binding's state machine, in which binding got stuck in CONNECTING state, but would not retry to connect. 
- As a simplification this removes two states from the state machine. CONNECTING and DISCONNECTING.
- Includes fix for websocket library closing connection after 5mins idle timeout.
- Removed some Non-Null Warnings.
Signed-off-by: Sebastian Prehn <sebastian.prehn@gmx.de>
=> [LG WebOS] Fix TV stuck in Connecting state

bundles/org.openhab.binding.irtrans/README.md
Brought in a hint for a larger buffersize as I ran into crashed after only 7 remotes and 47 commands.
The led parameter needed some explanations, as "I" for internal might be the better default.
Added typical values for standard users
Some explanations of typical parameters were missing.
Tested in my invironment 2.5M1
(This is my first edit to the docs. I hope I did everything correct)
=> [irtrans] Update README.md

bundles/org.openhab.transform.map/src/test/java/org/openhab/transform/map/internal/MapTransformationServiceTest.java, itests/org.openhab.io.hueemulation.tests/itest.bndrun, pom.xml
Depends on https://github.com/openhab/openhab-core/pull/1195.
=> Resolve itest.bndrun for Jollyday downgrade

bundles/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/PlugwiseHandlerFactory.java, bundles/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/PlugwiseStickDiscoveryService.java
Using constructor injection `@NonNullByDefault({})` is no longer necessary.
=> [plugwise] Use constructor injection

bundles/org.openhab.binding.bluetooth.bluez/src/main/java/org/openhab/binding/bluetooth/bluez/internal/discovery/BlueZDiscoveryService.java, bundles/org.openhab.binding.bluetooth.bluez/src/main/java/org/openhab/binding/bluetooth/bluez/package-info.java
The TinyB library implements a version check based on the `Specification-Version` header of the manifest. Without that header the bundle initialization fails.
PR also fixes a potential NPE.
=> [bluez] fix version check

bundles/org.openhab.binding.amazondashbutton/src/main/feature/feature.xml, bundles/org.openhab.binding.doorbird/src/main/feature/feature.xml, bundles/org.openhab.binding.systeminfo/src/main/feature/feature.xml, bundles/org.openhab.binding.tellstick/pom.xml, bundles/org.openhab.binding.tellstick/src/main/feature/feature.xml, features/pom.xml, pom.xml
For Karaf 4.2.7 release notes, see:
https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12311140&version=12345539
Also updates dependencies:
* Jetty 9.4.20.v20190813
* JNA 5.4.0 (used by most add-ons)
---
Should be merged together with:
* https://github.com/openhab/openhab-core/pull/1197
* https://github.com/openhab/openhab-webui/pull/139
* https://github.com/openhab/openhab-distro/pull/996
See also : https://github.com/openhab/openhab-distro/issues/995
=> Upgrade to Karaf 4.2.7

bundles/org.openhab.binding.chromecast/pom.xml
Fixes the following exceptions:
```
org.codehaus.jackson.map.JsonMappingException: Could not resolve type id 'MULTIZONE_STATUS' into a subtype of [simple type, class su.litvak.chromecast.api.v2.StandardResponse]
```
See also: https://github.com/vitalidze/chromecast-java-api-v2/issues/117
=> [chromecast] Update API lib to 0.11.2

bundles/org.openhab.binding.paradoxalarm/README.md
A pure README.MD fix in quotes in all code snippets, as per user response that they do not work this way with copy/paste.
=> [paradoxalarm] Fix quotes in code snippets of README.MD

bundles/org.openhab.binding.dsmr/src/main/java/org/openhab/binding/dsmr/internal/device/cosem/CosemHexString.java
When parsing integer values these should be catched for errors and re-thrown.
Because the re-thrown ParseException is correctly handled and doesn't pollute the log.
This catching was missing from the CosemHexString.
Errors can occur due to garbled data. These are simply ignored and should not pollute the log.
=>  [dsmr] integer parsing errors should be catched

bundles/org.openhab.binding.telegram/src/main/java/org/openhab/binding/telegram/internal/TelegramHandler.java
When sending normal messages to the OH Telegram Bot, the username, message, date ... channel is correctly updated.
However, when the bot sends a question and the user clicks a button to answer it, the field "username" wrongly contains the name of the bot and not the username of the user who sent the reply.
Thanks to @HerzScheisse who found that issue.
=> [telegram] Use the username from the user who sent the reply to a query

bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/AbstractMQTTThingHandler.java
Fixes #5879 
The binding can't request the state from the server. Therefore responding to refresh doesn't make sense and does not improve the situation.
=> [mqtt] fix refresh/restoreOnStartup

bundles/org.openhab.binding.lifx/README.md, bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/protocol/Product.java
Adds the [LIFX Candle](https://www.lifx.com/products/candle-color) to the Product enum so it can be discovered and the binding can enable the supported features.
See: https://github.com/LIFX/products/commit/128d4e2935bb872b799af8e71885bee1bc956802
=> [lifx] Add support for LIFX Candle

bundles/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/handler/SpotifyBridgeHandler.java, bundles/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/handler/SpotifyDeviceHandler.java, bundles/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/handler/SpotifyHandleCommands.java, bundles/org.openhab.binding.spotify/src/main/resources/ESH-INF/thing/thing-types.xml
When Spotify returns a 204. It means it doesn't return any data. This can happen after a certain time of inactivity. When this is returned it doesn't make sense to update the states or poll for devices/playlists either.
Also let playlist refresh only once per hour or when an explicit refresh of the channel is given will it update on the next poll.
=> [spotify] Improve performance of handling data

bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComLighting1Message.java
Resolved #6285, following suggestions of @mjagdis
=> [rfxcom] Made lighting1 message always send the unit-code

bundles/org.openhab.binding.exec/src/main/java/org/openhab/binding/exec/internal/handler/ExecHandler.java, bundles/org.openhab.binding.globalcache/src/main/java/org/openhab/binding/globalcache/internal/handler/GlobalCacheHandler.java, bundles/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/handler/ModbusDataThingHandler.java, bundles/org.openhab.binding.modbus/src/test/java/org/openhab/binding/modbus/internal/ModbusDataHandlerTest.java
- Removed use of `bundleContext` from `BaseThingHandler` as it is deprecated
See eclipse/smarthome#5182 and openhab/openhab-core/pull/1214
=> Removed use of 'bundleContext' from 'BaseThingHandler' as it is deprecated

bundles/org.openhab.binding.amazondashbutton/src/main/java/org/openhab/binding/amazondashbutton/package-info.java
PCap4J uses the java service loader for packet captures. If services are not properly declares they will not load in an OSGi environment due to classloader context.
=> [amazondashbutton] Fix ServiceLoader

bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/A5_02/A5_02_20.java, bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/A5_02/A5_02_30.java
Fixes for suggested fix for #6279 , using the right unscaled values for EEP EP-A5-02-20/30
Overwritten as discussed in the issue the getUnscaledMin and getUnscaledMax functions for correct calculation of the temperature values.
=>  [enocean] Issue #6279, EnOcean EEP-A5-02-20/30 used wrong unscaled values

bundles/org.openhab.binding.mqtt.generic/README.md, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/RollershutterValue.java, bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/values/ValueTests.java
Fixes #6067 
This makes the rollershutter implementation symmetric and documents the behaviour. 
Previously it was possible to define strings for `UP` and `DOWN` (which were converted to `PercentType.HUNDRED` and `PercentType.ZERO`) for inbound messages. These strings were not used for sending values to the broker, which is at least unexpected. Now `PercentType.HUNDERED` and `PercentType.ZERO` are converted to the corresponding strings (if defined, otherwise `100` or `0` are sent). 
=> [mqtt] make rollershutter symmetric

bundles/org.openhab.binding.sinope/src/main/java/org/openhab/binding/sinope/handler/SinopeGatewayHandler.java, bundles/org.openhab.binding.sinope/src/main/java/org/openhab/binding/sinope/handler/SinopeThermostatHandler.java
Thermostat handler was staying uninitialized. The same could also happen to the gateway in some condition (two openhab trying to connect to the same gateway.)
This is a bugfix. The bundle should be considered broken without it. Basically, the handlers were staying uninitialized and there were not processing any commands.
The test bundle is available at [here](https://openhab.jfrog.io/openhab/libs-pullrequest-local/org/openhab/addons/bundles/org.openhab.binding.sinope/2.5.0-SNAPSHOT/org.openhab.binding.sinope-2.5.0-SNAPSHOT.jar)
=> [sinope] Bugfix - Handlers staying in uninitialized state.

bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/HueEmulationService.java
Hueemulation does not work with Echo devices that now send "Content-Type" header in GET requests. Jetty simply returns 415 instead of ignoring the superfluous header. This is a simple workaround - a filter that removes the header before Jetty returns 415.
There might be a better way to directly instruct Jetty to do it. I have never worked with Jetty before, but maybe someone else know?
curl --trace -  -X GET http://openhab/api/c17cdce0-db09-4632-8b81-b85af023badf/lights -H 'Content-Type: application/json'
Before:
=> Error 415 Unsupported Media Type
Now:
{ rest data }
=> [hueemulation] Fix Amazon Echo device discovery

bundles/org.openhab.binding.systeminfo/pom.xml, bundles/org.openhab.binding.systeminfo/src/main/feature/feature.xml, itests/org.openhab.binding.systeminfo.tests/itest.bndrun, itests/org.openhab.binding.systeminfo.tests/pom.xml
Current oshi/jna spams openhab.log with 
[WARN ] [ftware.os.linux.LinuxOperatingSystem] - Failed to read process file:
on Raspberry Pi. Upgrade fixes the problem.
Signed-off-by: Alexander Falkenstern <alexander.falkenstern@gmail.com>
=> [systeminfo] Upgrade jna/oshi due to "Failed to read process file" spam on raspberry.

bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/handler/LGWebOSTVSocket.java
Currently the binding listens to volume changes reported in scenario "mastervolume_tv_speaker".
With this change it will also accept scenario "mastervolume_tv_speaker_ext", which is used when external speakers are attached in addition to the internal speakers.
=> [lg webos] Subscribe also to volume changes when TV and external speakers are used

bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/handler/KodiHandler.java, bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/protocol/KodiConnection.java
- Fixed NPE if no profile is returned in response
- Poll profiles only if channel is linked
```
2019-11-21 10:55:01.004 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
at org.openhab.binding.kodi.internal.protocol.KodiConnection.updateCurrentProfile(KodiConnection.java:1118) ~[?:?]
at org.openhab.binding.kodi.internal.handler.KodiHandler.lambda$4(KodiHandler.java:702) ~[?:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:?]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:?]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:?]
at …
```
=> [kodi] Fixed NPE if no profile is returned in response

bundles/org.openhab.binding.telegram/README.md, bundles/org.openhab.binding.telegram/src/main/java/org/openhab/binding/telegram/bot/TelegramActions.java, bundles/org.openhab.binding.telegram/src/main/java/org/openhab/binding/telegram/internal/TelegramHandler.java, bundles/org.openhab.binding.telegram/src/main/java/org/openhab/binding/telegram/internal/TelegramHandlerFactory.java
Although the used Telegram library supports the sending of images from a http/https source, it actually doesn't send the content of the picture, but only the URL where either the Telegram server or the client itself finally downloads that picture. In case the image comes from a local network, nothing it sent.
Therefore, (similar to the old binding) the provided image url is first downloaded and then send to the Telegram server. This difference was found by Mark (https://community.openhab.org/t/new-telegram-binding-and-updated-action-tester-and-feedback-welcome/54806/148) and I agree that it is probably a common use-case to send pictures that e.g. come from a local camera server.
A few design considerations:
- I thought about keeping the memory efficient sending of images via an URL, but …
=> [telegram] Allow to send pictures from a local network + basic authentication

bundles/org.openhab.binding.ambientweather/src/main/feature/feature.xml, bundles/org.openhab.binding.doorbird/src/main/feature/feature.xml, bundles/org.openhab.binding.innogysmarthome/src/main/feature/feature.xml, bundles/org.openhab.binding.lghombot/src/main/feature/feature.xml
Fixes the feature.xml format of a few bindings.
For some reason, the new line in https://github.com/openhab/openhab2-addons/blob/master/bundles/org.openhab.binding.innogysmarthome/src/main/feature/feature.xml#L6 seems to have completely broken the build, I hope this PR will fix it again.
=> fixed XML formatting

bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/upnp/HueEmulationConfigWithRuntime.java, bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/upnp/UpnpServer.java
This PR has two slightly different fixes for the same problem, I have split them into separate commits.
channel.open would throw if ipv6 was not enabled. This would cause ipv4 to fail as well.
* @throws  UnsupportedOperationException
*          If the specified protocol family is not supported. For example,
*          suppose the parameter is specified as {@link
*          java.net.StandardProtocolFamily#INET6 StandardProtocolFamily.INET6}
*          but IPv6 is not enabled on the platform.
I also took the liberty of changing the boolean flags to just use the channels directly. I don't think a lot of readability is lost in the process and seems quite redundant. Also, I got some codestylewarnings when the boolean flags were used - they weren't treated as strong enough nullpointer-exception …
=> [hueemulation] Fix ipv4 or ipv6 only environment

bundles/org.openhab.binding.lutron/README.md, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/LutronHandlerFactory.java, bundles/org.openhab.binding.lutron/src/main/resources/ESH-INF/binding/binding.xml
This PR is a documentation-only update to README.md and binding.xml.  It clarifies supported configurations, and adds recommendations regarding the new “delay” bridge parameter. I also took the opportunity to add myself to the author line in binding.xml since, for better or worse, a lot of the code in the binding is mine now and I’ve been more or less maintaining it through the 2.5 dev cycle.
@actong  - Is this ok with you?
Closes #6012
=> [lutron] Doc update

bundles/org.openhab.binding.innogysmarthome/src/main/java/org/openhab/binding/innogysmarthome/internal/client/InnogyClient.java
Apparently some refactoring after review went wrong and instead of calling the correct method, the method ended up calling itself, resulting in crashing the system.
=> [innogysmarthome] Fix loop bug

bundles/org.openhab.binding.dlinksmarthome/pom.xml, bundles/org.openhab.binding.dlinksmarthome/src/main/feature/feature.xml
Fixes binding so that it works in OH 2.5. Confirmed that it works with a real device.
Fixes #6439
=> [dlinksmarthome] Changed to openHAB Core feature of JAX-WS (#6439)

bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/discovery/TradfriDiscoveryService.java, bundles/org.openhab.binding.tradfri/src/test/java/org/openhab/binding/tradfri/internal/discovery/TradfriDiscoveryServiceTest.java
This is directly addressing https://github.com/openhab/openhab2-addons/issues/6258
Added C/WS as a hint for detecting Ikea Tradfri color bulbs.
Before this PR, bulbs that were advertised by the gateway as "C/WS" as opposed to the earlier "CWS", would be recognized as color temperature (thing type 0220), and not full color bulbs (thing type 210).
=> [tradfri] Fix tradfri color bulb discovery issue

bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/handler/LifxLightHandler.java
It might not have this property e.g. when using .things files.
This NPE was caused by the changes in https://github.com/openhab/openhab2-addons/pull/6180.
=> [lifx] Fix NPE when things don't have properties

bundles/org.openhab.io.hueemulation/README.md, bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/rest/LightsAndGroups.java, bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/rest/LightsAndGroupsTests.java
I made this PR as a result of the discussion in https://community.openhab.org/t/hueemulation-group-items-can-no-longer-be-exposed-as-hue-devices/85679
For us who use Group type items as items, the new addition to the hue-emulation, group support, was a breaking change. I added support for a new tag "huelight" that can be put on a group type item so it will work as before.
=> [hueemulation] Allow Group items to be exposed as devices

bundles/org.openhab.binding.weathercompany/src/main/java/org/openhab/binding/weathercompany/internal/WeatherCompanyHandlerFactory.java, bundles/org.openhab.binding.weathercompany/src/main/java/org/openhab/binding/weathercompany/internal/discovery/WeatherCompanyDiscoveryService.java, bundles/org.openhab.binding.weathercompany/src/main/java/org/openhab/binding/weathercompany/internal/handler/WeatherCompanyAbstractHandler.java, bundles/org.openhab.binding.weathercompany/src/main/java/org/openhab/binding/weathercompany/internal/handler/WeatherCompanyBridgeHandler.java, bundles/org.openhab.binding.weathercompany/src/main/java/org/openhab/binding/weathercompany/internal/handler/WeatherCompanyForecastHandler.java, bundles/org.openhab.binding.weathercompany/src/main/java/org/openhab/binding/weathercompany/internal/handler/WeatherCompanyObservationsHandler.java
When I reworked the binding to create a bridge handler, I screwed up the handling of the thing status. If the forecast and/or observations things go offline for any reason, they will never come back online (unless the binding is restarted).
Also moved the bridge handler to the handler package where it should've been originally.
=> [weathercompany] Fix handling of thing status

bundles/org.openhab.binding.netatmo/README.md
Seems like Netatmo updated their URLs for icons, the old ones are no longer valid.
Updated URLs posted on this page to avoid '404 - Not Found' errors.
=> [netatmo] Updated netatmo icon URLs

bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/client/RpcClient.java, bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/message/BinRpcMessage.java, bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/message/XmlRpcResponse.java, bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/type/HomematicTypeGeneratorImpl.java
Partial revert of #6531 because of conversion exceptions if numeric
values are not wrapped as objects.
Some additonal changes in generic object initializations were caused by applying the formatter and source cleanup.
=> [homematic] Explicit creation of numeric Objects is needed

bundles/org.openhab.binding.tradfri/pom.xml, itests/org.openhab.binding.tradfri.tests/itest.bndrun
depends on https://github.com/openhab/openhab-core/pull/1262
=> [tradfri] removed explicit Californium dependency to avoid embedding

bundles/org.openhab.binding.wifiled/src/main/java/org/openhab/binding/wifiled/internal/discovery/WiFiLEDDiscoveryService.java
Fixes #6557
Fix discover function not listening for device answers by adding port number for listening to datagram socket.
=> [wifiled] Fixed discover() function by adding listen port to DatagramSocket

bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueBridgeHandler.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/sensors/DimmerSwitchHandler.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/sensors/TapSwitchHandler.java
- Decoupling of `sensorRefreshInterval` and time gap for lastchange check
The accuracy of time values returned by the hue API is seconds. The `sensorRefreshInterval` are milliseconds. Reducing the `sensorRefreshInterval` leads to ignored events because of that.
Fixes #6577
Does not fix https://github.com/openhab/openhab2-addons/issues/6577#issuecomment-565160525 or #6578
=> [hue] Decoupling of 'sensorRefreshInterval' and time gap for lastchange check

bundles/org.openhab.binding.ambientweather/README.md, bundles/org.openhab.binding.ambientweather/src/main/java/org/openhab/binding/ambientweather/internal/handler/AmbientWeatherEventListener.java
Attempt to reconnect to the Ambient Weather service when an EVENT_RECONNECT is received form the service. Without this change the Ambient Weather things can remain offline indefinitely.
Also fix documentation so that thing definitions work, and that item definitions align with thing definition.
=> [ambientweather] Attempt to reconnect to service

bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/action/LGWebOSActions.java, bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/VolumeControlMute.java, bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/VolumeControlVolume.java, bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/handler/LGWebOSConfiguration.java, bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/handler/LGWebOSHandler.java, bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/handler/LGWebOSTVSocket.java, bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/handler/command/ServiceCommand.java
- Fixed exception processing response after launching apps, as sessionId is optional in the response.
- Fixed various warnings on handling potential null values.
Signed-off-by: Sebastian Prehn <sebastian.prehn@gmx.de>
=> [lgwebos] Properly handle optional SessionID in response

bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueSensorHandler.java
- Prevent interminable loop when updating the configuration of the sensor thing handler
Fixes #6578
See changes in https://github.com/openhab/openhab2-addons/commit/a9444b37345a665a31c13a6062aa2727d54f7f44
=> [hue] Prevent interminable loop when updating the configuration of the sensor thing handler

bundles/org.openhab.binding.homematic/README.md
make changes to README.md
SCA Jenkins analysis
* https://ci.openhab.org/job/PR-openHAB2-Addons/Static_20Code_20Analysis_20Report/
.binding.homematic/README.md
tool 	priority 	line 	category 	rule 	message
checkstyle 	2 	46 	style 	MarkdownCheck 	The line before a Markdown list must be empty.
checkstyle 	2 	66 	style 	MarkdownCheck 	The line before a Markdown list must be empty.
checkstyle 	2 	92 	style 	MarkdownCheck 	The line before a Markdown list must be empty.
checkstyle 	2 	179 	style 	MarkdownCheck 	The line after a Markdown list must be empty.
checkstyle 	2 	269 	style 	MarkdownCheck 	The line before code formatting section must be empty.
checkstyle 	2 	463 	style 	MarkdownCheck 	The line before a Markdown list must be empty.
Also-by: Michael Roßner <Schrott.Micha@web.de> …
=> [homematic] correct SCA warnings - README.md

bundles/org.openhab.binding.miio/src/main/resources/ESH-INF/thing/vacuumThing.xml
fix invalid type 
see forum
https://community.openhab.org/t/xiaomi-robot-vacuum-binding/31317/1179
=> [miio] fix wrong channel for vacuum thing

bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/ComponentSwitch.java
Fixes #6364 
According to https://www.home-assistant.io/integrations/switch.mqtt/ the default values are ON and OFF. As long as we do not provide the ability to configure state and command values for auto-discovered devices we should go with the default values.
=> [mqtt][homeassistant] fix state/command values for switches

bom/runtime-index/pom.xml, bom/test-index/pom.xml, itests/org.openhab.binding.astro.tests/itest.bndrun, itests/org.openhab.binding.avmfritz.tests/itest.bndrun, itests/org.openhab.binding.feed.tests/itest.bndrun, itests/org.openhab.binding.hue.tests/itest.bndrun, itests/org.openhab.binding.max.tests/itest.bndrun, itests/org.openhab.binding.mqtt.homeassistant.tests/itest.bndrun, itests/org.openhab.binding.mqtt.homie.tests/itest.bndrun, itests/org.openhab.binding.nest.tests/itest.bndrun, itests/org.openhab.binding.ntp.tests/itest.bndrun, itests/org.openhab.binding.systeminfo.tests/itest.bndrun, itests/org.openhab.binding.tradfri.tests/itest.bndrun, itests/org.openhab.binding.wemo.tests/itest.bndrun, itests/org.openhab.io.hueemulation.tests/itest.bndrun, itests/org.openhab.io.mqttembeddedbroker.tests/itest.bndrun, itests/org.openhab.persistence.mapdb.tests/itest.bndrun
itest.bndrun files pointed to older version number for the addons it tested.
=> Fix itest.bndrun version numbers

bundles/org.openhab.binding.harmonyhub/src/main/java/org/openhab/binding/harmonyhub/internal/discovery/HarmonyHubDiscoveryService.java
Fix for other non Harmony Hub Logitech devices responding to a discovery query and preventing hubs from being found, minor discovery code cleanup, closes #6621
=> [harmonyhub] Harmony discovery fix

bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/SnmpTargetHandler.java
This request fixes omission of V1TRAP PDU event.
SNMP4J package sends SNMP V1 Traps in objects of `PDUv1` type. Class `PDUv1` is derived from `PDU` class, specific just for V1 Traps.  If using parent PDU class, there is no access to additional information - `Enterprise OID` / `GenericTrap(GT)` / `SpecificTrap(ST)`.  The code change just calls one more time `updateChannels` with that additional information. 
Regarding GenericTrap/SpecificTrap codes - if GT==6, ST must be used. However RFC1157 allows ST to be populated even if GT !=6. Possible solutions for differentiation between GT/ST are:
- if GT==6 => use ST (possible drawback - misinterpretation of traps that can have either ST or GT values)
- if ST==0 => use GT (possible drawback - SNMP implementations that doesn't set ST=0 when …
=> [SNMP] Process enterprise OID in V1TRAP PDUs

bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/api/OpenSprinklerHttpApiV100.java
OpenSprinkler now supports two rain sensors, including a breaking change
in the http api by renaming rs to sn1 and sn2. Adapting to that in this
commit, so that the rain sensor channel is working again.
=> [opensprinkler] Adapt to breaking api changes of opensprinkler

bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/services/DeviceManager.java
Fixes and optimizes the yeelight auto discovery issues described in #6643
=> [yeelight] Fix autodiscovery with multiple network interfaces. (#6643)

features/openhab-addons/pom.xml, features/openhab-addons/src/main/resources/footer.xml
- Removed aggregated features
Karaf feature verification failed because of missing add-ons
=> Removed aggregated features

bundles/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromecastStatusUpdater.java
- Fixed IAE when downloaded image is `null`
e.g.:
```
2019-12-29 21:05:43.963 [ERROR] [nternal.items.ItemStateConverterImpl] - A conversion of null was requested:
java.lang.IllegalArgumentException: State must not be null.
at org.eclipse.smarthome.core.internal.items.ItemStateConverterImpl.convertToAcceptedState(ItemStateConverterImpl.java:58) ~[?:?]
at org.eclipse.smarthome.core.thing.internal.profiles.ProfileCallbackImpl.sendUpdate(ProfileCallbackImpl.java:134) ~[?:?]
at org.eclipse.smarthome.core.thing.internal.profiles.SystemDefaultProfile.onStateUpdateFromHandler(SystemDefaultProfile.java:53) ~[?:?]
at org.eclipse.smarthome.core.thing.internal.CommunicationManager.lambda$9(CommunicationManager.java:467) ~[?:?]
at org.eclipse.smarthome.core.thing.internal.CommunicationManager.lambda$11 …
```
=> [chromecast] Fixed IAE when downloaded image is 'null'

bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/discovery/HomeAssistantDiscovery.java, bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/internal/discovery/Homie300Discovery.java, bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/discovery/AbstractMQTTDiscovery.java
Enable the MQTT discovery to reset the timeout while there are still messages received.
The timeout of `AbstractDiscoveryService` is disabled in `AbstractMQTTDiscovery` and replaced by an own one, which can be reset by dervied classes.
see #6691
@davidgraeff It would acutally be nicer in `AbstractDiscoveryService`, but is it worth the effort?
=> [mqtt] Enable discovery timeout reset

bundles/org.openhab.binding.mqtt.generic/README.md
see #6566 
This is not a fix for the mentioned problems. It's an adjustment to the current code. Currently the comannd is first converted to a string, then transformations are applied and the formatter comes last. Since the command always is a string at this point, %d or %f will fail.
=> [mqtt] adjust documentation to code

bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/ChannelConfigBuilder.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/CChannel.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/ComponentSwitch.java
My plan is to go over each HA component and fix things that are missing from the HA spec.
Switch is the first.
Fixed here:
- honor `qos` config
- correct default state_xx values
- correct default `optimistic` flag
- rename channel, as group now has the component name already.
=> [mqtt.homassistant] Review Switch

bundles/org.openhab.binding.opengarage/README.md
Update OpenGarage binding readme
[OpenGarage] Fix mistakes in README.txt for a new OpenGarage binding.
The current README.txt for OpenGarage binding contains invalid type in sitemap and the last item quotes are missing around the label. Also the example is updated so that it matches paperUI configuration. Also an item definition type was incorrect. Please see https://www.openhab.org/addons/bindings/opengarage/ for the current version.
=> Update OpenGarage binding readme

bundles/org.openhab.binding.digiplex/src/main/resources/ESH-INF/thing/area.xml
Fix for wrong description of channel states
=> [digiplex] Fix "Area Ready" channel definition (#6600)

tools/static-code-analysis/checkstyle/suppressions.xml
This changes allows parsing of inner classes when the outer one is already @NonNullByDefault
It's requires for the Shelly and MagentaTV bindings to get rid of Travis warnings.
Signed-off-by: Markus Michels <markus7017@gmail.com>
=> NullAnnotationsCheck added to DTO

bundles/org.openhab.binding.groheondus/src/main/resources/ESH-INF/thing/thing-types.xml
This is totally unexpected and we can set a reasonable default here.
This is done in this commit and the default is set to one day, the same
timeframe the app is showing by default.
Fixes #6297
=> [groheondus] Do not require users to configure timeframe for waterconsumption

bundles/org.openhab.binding.mqtt.generic/README.md, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/ChannelState.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/ColorValue.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/DateTimeValue.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/LocationValue.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/NumberValue.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/OnOffValue.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/OpenCloseValue.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/PercentageValue.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/RollershutterValue.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/Value.java, bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/ChannelStateTests.java, bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/values/ValueTests.java, itests/org.openhab.binding.mqtt.homeassistant.tests/pom.xml, itests/org.openhab.binding.mqtt.homie.tests/pom.xml
This PR handles outgoing formats.
For this the value is kept as a `Value`.
Transformations will retrieve the String value by calling the default format (`Value.getMQTTpublishValue(null)`)
After the transformation, the string result is converted to a TextValue.
After all transformations, the value is converted to a String by calling `Value.getMQTTpublishValue(format)` allowing for special handling of the different values.
Default formats are adjusted to the old behaviour and documented in the README.md
This should adress #6566 (Use "%.0f" as format and not "%d")
=> [mqtt] Allow outgoing format

bundles/org.openhab.binding.opensprinkler/README.md, bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/OpenSprinklerBindingConstants.java, bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/handler/OpenSprinklerStationHandler.java, bundles/org.openhab.binding.opensprinkler/src/main/resources/ESH-INF/thing/thing-types.xml
If a station is already turned on and another station is turned on as
well, opensprinkler will put the station into the queue. The station
then is not open but has a remaining water time. However, there's no way
to remove the station from the queue with openHAB only.
This commit adds a new channel "queued", which indicates, if the station
is queued or not. The state to "ON" is read-only, if done manually,
nothing happens. If the station is queued, the channel can be switched
off, which will remove the station from the queue.
Fixes #6727
=> [opensprinkler] Show if a station is queued and allow to remove it from the queue

bundles/org.openhab.binding.telegram/README.md, bundles/org.openhab.binding.telegram/src/main/java/org/openhab/binding/telegram/bot/TelegramActions.java
Base64 encoded images are already supported when the simple data is passed. This PR adds support for  base64 encoded images with [data URI scheme](https://en.wikipedia.org/wiki/Data_URI_scheme) (base64 data starting with "data:").
This was already supported by the old OH1 Telegram action.
Fixes https://github.com/openhab/openhab-addons/issues/6687
=> [Telegram] Support data URI scheme for base64 encoded images

bundles/org.openhab.binding.samsungtv/README.md
Samsung UE40J6300AU tested. Unfortunately only volume and mute is really useful but this is also good progress.
TV was found via scan. It is working perfectly.
=> [samsungtv] Documentation. Add new tested TV model and more examples

bundles/org.openhab.binding.tplinksmarthome/src/main/resources/ESH-INF/thing/KL110.xml
The kl110 device accidentally got the id kl10 instead of kl110. There it won't work because the code would correctly use the value kl110 and that value is also used to match the device with what is returned by the device itself.
=> [tplinksmarthome] Fix typo thing xml kl110 devices

bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/command/ModuleVersionCommand.java, bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/command/SatelCommandBase.java, bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/event/ModuleVersionEvent.java, bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/handler/SatelBridgeHandler.java, bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/protocol/SatelModule.java
This PR fixes issue with updating states with code greater than 0x27 (for example partitions armed in mode 1).
This issue is described here: https://community.openhab.org/t/satel-binding-support-announcements-and-feature-requests/56135/117
PR replaces #6614 with 2.5.x as destination branch.
Signed-off-by: Krzysztof Goworek krzysztof.goworek@gmail.com
=> [satel] Fixes for arming in mode 1

bundles/org.openhab.binding.nanoleaf/README.md
Description on how to get authToken.
Removed Panel1Brightness, because it is not supported right now.
=> [nanoleaf] Adding description for generation of authToken to README.md

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoBindingConstants.java, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoVacuumHandler.java, bundles/org.openhab.binding.miio/src/main/resources/ESH-INF/thing/vacuumThing.xml
Up to now, the status and error codes have only been output as text. On the one hand, this makes it complicated to create a mapping for your own status/error message (for example, in another language), and on the other hand, messages that are not yet implemented are only passed on as "UNKNOWN".
The two channels state_code and error_code now output the integers directly, so a mapping to numbers can be easily done and new codes are also output.
Signed-off-by: Markus Schraufstetter <markus.schraufstetter@gmail.com>
=> [miio] Xiaomi Robot Vacuum Channel "state_code" and "error_code" added

bundles/org.openhab.binding.bluetooth.bluez/README.md
The documentation lacks some necessary steps for Bluez setup. I'd suggest to not put this into the installation section of openhab-docs, but directly into the binding, as it only supports Linux anyway.
=> [bluetooth.bluez] Improve permission setup documentation

bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/handler/RFXComBridgeHandler.java
Changed transceiver type logging level from info to debug. This was only info level logging, which is rather useless for normal user.
=> [rfxcom] Changed logging level

bundles/org.openhab.binding.network/README.md, bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/NetworkBindingConfiguration.java, bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/NetworkBindingConfigurationListener.java, bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/NetworkHandlerFactory.java, bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/PresenceDetection.java, bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/handler/NetworkHandler.java, bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/utils/LatencyParser.java, bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/utils/NetworkUtils.java, bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/utils/PingResult.java, bundles/org.openhab.binding.network/src/main/resources/ESH-INF/binding/binding.xml, bundles/org.openhab.binding.network/src/test/java/org/openhab/binding/network/internal/PresenceDetectionTest.java, bundles/org.openhab.binding.network/src/test/java/org/openhab/binding/network/internal/utils/LatencyParserTest.java
This is a fix for the issue [network] Misleading latency values #6741. I won't copy the issue content to this pull request to avoid redundant information.
- The binding configuration option `preferResponseTimeAsLatency` was added. It is by default false which leads to the same behavior as before the feature provided by this pull request existed.
- If the option is enabled, the binding tries to extract the latency value from the ping command output. If no value is found, the fallback is to use the time it took to execute the ping command (same as before).
=> [network] Fix misleading latency values

bundles/org.openhab.binding.network/README.md
I got presence instantly when my smartphone connects to the wifi on my OpenHAB running in Docker 18.03.1 in Ubuntu 18.04.3 LTS.
Hope this trick will be helpful for others since another two options where not working for me.
Same approach was working for other specific cases based on discussion https://community.openhab.org/t/dhcp-listen-port-forwarding-issue/36846/6
=> [network] Documentation workaround to use DHCP with Docker

bundles/org.openhab.binding.mqtt.generic/README.md, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/ChannelState.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/handler/GenericMQTTThingHandler.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/ColorValue.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/DateTimeValue.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/LocationValue.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/NumberValue.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/OnOffValue.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/OpenCloseValue.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/PercentageValue.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/RollershutterValue.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/TextValue.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/Value.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/ValueFactory.java, bundles/org.openhab.binding.mqtt.generic/src/main/resources/ESH-INF/config/number-channel-config.xml, bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/ChannelStateTests.java, bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/values/ValueTests.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/CChannel.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/ComponentBinarySensor.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/ComponentSensor.java, bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/internal/homie300/Property.java
This PR enables UOMs for number channels.
There is a new optional config parameter `unit`.
The `NumberValue` accepts `QuantityType` updates, which are even converted to the selected uom (like `°F` to `°C`).
The creation of `StateDescription` has been changed to `StateDescriptionFragmentBuilder` to remove deprecated warnings.
For homeassistant, sensors with units are changed to NumberValues (compability issue?)
Addesses / inspired by #6751, #6663
=> [mqtt] Enable unit of measurements for number values

bundles/create_openhab_binding_skeleton.cmd, bundles/create_openhab_binding_skeleton.sh, bundles/org.openhab.binding.mqtt.generic/src/main/resources/ESH-INF/config/color-channel-config.xml, bundles/org.openhab.binding.mqtt.generic/src/main/resources/ESH-INF/config/dimmer-channel-config.xml, bundles/org.openhab.binding.mqtt.generic/src/main/resources/ESH-INF/config/number-channel-config.xml, bundles/org.openhab.binding.mqtt.generic/src/main/resources/ESH-INF/config/rollershutter-channel-config.xml, bundles/org.openhab.binding.mqtt.generic/src/main/resources/ESH-INF/config/string-channel-config.xml, bundles/org.openhab.binding.mqtt.generic/src/main/resources/ESH-INF/config/switch-channel-config.xml, bundles/org.openhab.binding.mqtt.generic/src/main/resources/ESH-INF/thing/generic-thing.xml, itests/org.openhab.binding.astro.tests/itest.bndrun, itests/org.openhab.binding.avmfritz.tests/itest.bndrun, itests/org.openhab.binding.feed.tests/itest.bndrun, itests/org.openhab.binding.hue.tests/itest.bndrun, itests/org.openhab.binding.max.tests/itest.bndrun, itests/org.openhab.binding.mqtt.homeassistant.tests/itest.bndrun, itests/org.openhab.binding.mqtt.homeassistant.tests/pom.xml, itests/org.openhab.binding.mqtt.homie.tests/itest.bndrun, itests/org.openhab.binding.mqtt.homie.tests/pom.xml, itests/org.openhab.binding.nest.tests/itest.bndrun, itests/org.openhab.binding.ntp.tests/itest.bndrun, itests/org.openhab.binding.systeminfo.tests/itest.bndrun, itests/org.openhab.binding.tradfri.tests/itest.bndrun, itests/org.openhab.binding.wemo.tests/itest.bndrun, itests/org.openhab.io.hueemulation.tests/itest.bndrun, itests/org.openhab.io.mqttembeddedbroker.tests/itest.bndrun, itests/org.openhab.io.mqttembeddedbroker.tests/pom.xml, itests/org.openhab.persistence.mapdb.tests/itest.bndrun, pom.xml
- Fixed itest bnd versions in tests
- Fixed pom of disabled itests
- Fixed version in skeleton scripts.
=> Fixed missing 2.5.2-SNAPSHOT changes

bundles/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/handler/YamahaZoneThingHandler.java, bundles/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/protocol/xml/InputWithNavigationControlXML.java, bundles/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/protocol/xml/XMLConnection.java, bundles/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/protocol/xml/ZoneControlXML.java
Fixes #6328
As per #6328 and [thread here](https://community.openhab.org/t/yamaha-receiver-binding-connect-timed-out/84267/26) community tested on few devices and it seems to resolve the issue.
The jar build for testing is available [here](https://www.dropbox.com/sh/pa069i3bnbsptzj/AABqgJSrQ0lISfDNkUCbwWUma?dl=0).
-----
This is rebased against the 2.5.x branch, I hope this can get in as a 2.5.2 release (the bug is critical).
=> [yamahareceiver] connect timed out since 2.5M4 fix

pom.xml
=> switched to SAT 0.9.0

bundles/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/LxServerHandler.java, bundles/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/LxWebSocket.java, bundles/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/types/LxStateUpdate.java
The issue was reported at the forum: https://community.openhab.org/t/loxone-anyone/15712/53
It is caused by a deadlock in binding. When a web-socket binary message is received from Miniserver with a state update indicating a position change of a rollershutter and binding decides it should stop the rollershutter movement, because it reached target position, binding attempts to send a websocket message to the Miniserver. This message is sent from the websocket thread where state update was received and this causes indefinite waiting for the message acknowledgement from the Miniserver, which is never received, as the websocket thread waits for it.
The solution is to add a queue for state updates received from the miniserver and process all state updates in the main binding thread, currently …
=> [Loxone] Fix for deadlock when sending commands from the Miniserver's state handler

bundles/org.openhab.binding.millheat/src/main/feature/feature.xml
The binding does not show in the list of available bindings when installing from neither Habmin nor PaperUI. Installing via the addons folder works.
Assuming the missing file feature.xml is to blame, this PR adds it.
@J-N-K could you have a look?
=> [millheat] Added missing feature.xml

bundles/org.openhab.binding.meteoblue/README.md, bundles/org.openhab.binding.meteoblue/src/main/java/org/openhab/binding/meteoblue/internal/Forecast.java
Fixes directory handling for the image icons by using the ConfigConstants.getConfigFolder() method.
Fixes #6840.
[Test jar with the fix](https://drive.google.com/open?id=1H1dnfmi3kbHO0aJB3EIxg1mRZIpyvrsy).
=> [meteoblue] Fix directory handling for images

bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/lib/serverconnection/impl/DsAPIImpl.java
[digitalSTROM] bugfix for apartment scene calls (#6839)
Fixes a type mismatch in the api implementation where the enum name was used as parameter instead of the numerical id. It seems like it was kind of a typo in this specific call. All the other methods for zone or named scenes had the conversion correct implemented. Instead of executing the call the server responds with a message
{
"ok": false,
"message": "Invalid sceneNumber: 'ABSENT'"
} 
Unfortunately, the response handler is not implemented very well and it swallows this kind of response from the digitalSTROM server. Therefore the bug was not so obvious to spot in the log files.
I'll have a look at the response handler later, but will submit that in another pull request.
The topic was submitted to the community first …
=> [digitalstrom] Bugfix for apartment scene calls (#6839)

bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/BluetoothCompanyIdentifiers.java
Corentium is rebranded to Airthings in 2016. Reference
https://www.airthings.com/en/about-us
Bluetooth binding discovers devices as a Corentium brand, which can be
tricky from user perspective.
=> Changed Corentium AS Bluetooth company id to Airthings AS

bom/openhab-addons/pom.xml, bom/openhab-core-index/pom.xml, bom/pom.xml, bom/runtime-index/pom.xml, bom/test-index/pom.xml, bundles/pom.xml, features/openhab-addons-external/pom.xml, features/openhab-addons/pom.xml, features/pom.xml, itests/pom.xml, pom.xml
- Applied spotless formatter
After https://github.com/openhab/openhab-core/pull/1294 the ordering of imports were mixed up. I applied the spotless `mvn spotless:apply` command on the whole repo.
=> Applied spotless formatter

bundles/org.openhab.binding.mqtt.generic/README.md, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/ChannelState.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/ColorValue.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/DateTimeValue.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/LocationValue.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/NumberValue.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/OnOffValue.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/OpenCloseValue.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/PercentageValue.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/RollershutterValue.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/Value.java, bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/ChannelStateTests.java, bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/values/ValueTests.java
I am a bit confused...
for one thing, I seemed to have a bigger problem handling multiple PRs in parallel. With my last PR I undid the one before :-(
So this PR redoes #6755 .
I was not able to reproduce the described problems with the code versions I found.
Before #6755, the dimmer would always use `BigDecimal.toString()` and ignore the format altogether.
With #6755, dimmer would replace `%s` with `%.0f` for integer values....
Now the `PercentValue` will utilize the `DecimalType.format()` function.
Also a unit test is added.
=> [mqtt] renenable outgoing formatting and address #6831

bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/handler/DenonMarantzHandler.java
Setting the volumeDB didn't work in my zone 2 of my Denon AVR2000. Luckily the bug is easy to fix.
Signed-off-by: Thomas Freudenberg <info@thomasfreudenberg.com>
=> [denonmarantz] Fix setting volumeDB for zones 2 and 3

bundles/org.openhab.binding.telegram/src/main/java/org/openhab/binding/telegram/bot/TelegramActions.java
If the user calls `sendTelegram(chatId, message)` or `sendTelegram(message)`, the message is always formatted even if no formatting args are passed.
In many cases, this doesn't harm anything and the result of `String.format(message)` is the same as the `message `itself, but as soon you pass e.g. a "%" symbol, you'll get an error.
Solution: Do not call `String.format()` if no formatting args were passed.
=> [telegram] Do not format message if no formatting args are passed

bundles/org.openhab.binding.onewiregpio/README.md, bundles/org.openhab.binding.onewiregpio/src/main/java/org/openhab/binding/onewiregpio/internal/OneWireGPIOBindingConstants.java, bundles/org.openhab.binding.onewiregpio/src/main/java/org/openhab/binding/onewiregpio/internal/OneWireGpioConfiguration.java, bundles/org.openhab.binding.onewiregpio/src/main/java/org/openhab/binding/onewiregpio/internal/handler/OneWireGPIOHandler.java, bundles/org.openhab.binding.onewiregpio/src/main/resources/ESH-INF/thing/thing-types.xml
Upon a request from a friend of mine I've added additional parameter to the binding which allows you to lower the precision of the received temperature number from the filesystem. 
A bit of background about the binding itself - the binding reads files inside /sys/bus/w1/devices/DEVICE_ID_FOLDER/w1_slave. 
If there is t=xxxxx, where xxxxx is integer value. Then the binding makes a BigDecimal.valueOf(xxxxx).movePointLeft(3) and returns the value. This makes tha maximum possible precision after the floating point to be total of 3 (i.e. the digits after the floating point). 
The precision parameter allows you to reduce this number down to 0, 1, 2 or 3(the default value is the max value) with round half up rounding strategy. This allows you not to spam event bus on every small change of the …
=> [onewiregpio] Added precision parameter to OneWireGpio Binding

pom.xml
Plugin was only defined/configured, not prepared for actual lifecycle use (listed in the build/plugins section)
Related to https://github.com/openhab/openhab-core/pull/1303 only this is for the addons repo
=> List spotless plugin in plugins section, not only pluginManagement section

bundles/org.openhab.binding.exec/pom.xml, bundles/org.openhab.binding.exec/src/main/feature/feature.xml, bundles/org.openhab.binding.exec/src/main/java/org/openhab/binding/exec/internal/handler/ExecHandler.java, bundles/org.openhab.binding.exec/src/main/resources/ESH-INF/binding/binding.xml, bundles/org.openhab.binding.exec/src/main/resources/ESH-INF/thing/thing-types.xml
- Implemented @@ manual split (@see https://www.openhab.org/docs/configuration/actions.html#exec-actions)
- Pass to shell if not manually split (detect shell via https://stackoverflow.com/a/31547504/7508309, permission by author)
Fixes #6729
Added benefit: Pass to shell allows for pipes
Signed-off-by: Constantin Piber <cp.piber@gmail.com>
=> [Exec] Properly split command & pipe support

bundles/org.openhab.binding.pulseaudio/README.md, bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/cli/Parser.java
This pull request comes after a long day of looking for the reasons behind the pulseaudio binding not being able to talk to the pulseaudio servers, resulting in `Pulseaudio server  localhost: 0 modules and 0 items updated`
As is typical for a long search, the error is quite minute and to be found in the incorrect escaping of backslash charactes in the matching pattern that matches pactl output against a given sink name.
EDIT: the key change is the 5th char in the string from `+` to `*`-
=> [pulseaudio] fix invalid regex not matching pactl output

bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/internal/homie300/Property.java
Fixes #6493
According to the spec (5.3.2):
```
A Homie controller publishes to the set command topic with non-retained messages only.
```
=> [mqtt][homie] Fix retain flag for outgoing messages

bundles/org.openhab.binding.dsmr/src/main/resources/ESH-INF/thing/meter_device_emucs_v1_0.xml
thing-type id in xml file didn't match with id used in code.
=> [dsmr] Fixed typo in emucs thing xml

bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/BluetoothDevice.java
This PR adds the `hasListeners` method to the BluetoothDevice class which is required for both #6916 and #6921.
=> [bluetooth] Added hasListeners method to BluetoothDevice

bundles/org.openhab.binding.bluetooth.bluez/src/main/java/org/openhab/binding/bluetooth/bluez/BlueZBluetoothDevice.java
I've encountered NPE in these methods before and noticed that the enableNotifications have checks for them, but not these ones. So I'm adding them as part of this PR.
=> [bluetooth.bluez] Add missing null checks

bundles/org.openhab.binding.lgwebos/README.md, bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/action/LGWebOSActions.java, bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/LGWebOSBindingConstants.java, bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/RCButtonControl.java, bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/handler/LGWebOSHandler.java, bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/handler/LGWebOSTVSocket.java, bundles/org.openhab.binding.lgwebos/src/main/resources/ESH-INF/i18n/lgwebos.properties, bundles/org.openhab.binding.lgwebos/src/main/resources/ESH-INF/thing/thing-types.xml
This PR adds a new channel ("IRCode") to the LG WebOS binding, which simulates some of the button presses on the LG infrared remote control. Inspiration for this enhancement came [from the discussion here.](https://community.openhab.org/t/lgwebos-binding-sendbutton-question/85872/8)
Here is a list of IR codes that I have found to work. Note that this list has been compiled mostly through trial and error, and I may have missed some of the buttons. I have only been able to test this on an LGUJ657A TV so your mileage may vary.
Code String | Description
-- | --
LEFT | Left button in cursor control group
RIGHT | Right button in cursor control group
UP | Up button in cursor control group
DOWN | Down button in cursor control group
ENTER | "OK" button in the center of the cursor control group …
=> [lgwebos] Added rcButton channel

bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComLighting5Message.java
LIVOLO_APPLIANCE fix
This is to correct the LIVOLO_APPLIANCE handeling by RFXCom. 
Issue is reported here: https://github.com/openhab/openhab-addons/issues/6766 and here: https://community.openhab.org/t/rfxcom-read-error-rfxcomstreamreader-connector-died-java-lang-indexoutofboundsexception/82624/3
Signed-off-by: Patrick Stephan patrick.stephan@live.com
=> [rfxcom] LIVOLO_APPLIANCE fix

bundles/org.openhab.binding.airquality/README.md
Wrong channel name. Cannot receive data from dominant polutor
Signed-off-by: Gleb <47859640+glebster-d@users.noreply.github.com>
=> [airquality] Fix wrong channel name in documentation

bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxServerHandler.java
Currently in the discovery for players the "modelname" instead of the "name"
is taken, because of the `contains` method. Also the "modelname" can be
taken as the "model" because of the `contains`.
Result is that all discovery results are shown with the label "SqueezeLite"
instead of with their real names.
This commit fixes it for all used properties.
=> [squeezebox] Fix discovery names and properties

bundles/org.openhab.binding.dwdunwetter/README.md, bundles/org.openhab.binding.dwdunwetter/src/main/java/org/openhab/binding/dwdunwetter/internal/data/DwdWarningCache.java, bundles/org.openhab.binding.dwdunwetter/src/main/java/org/openhab/binding/dwdunwetter/internal/data/DwdWarningDataAccess.java, bundles/org.openhab.binding.dwdunwetter/src/main/java/org/openhab/binding/dwdunwetter/internal/data/DwdWarningsData.java, bundles/org.openhab.binding.dwdunwetter/src/main/java/org/openhab/binding/dwdunwetter/internal/data/DwdXmlTag.java, bundles/org.openhab.binding.dwdunwetter/src/main/java/org/openhab/binding/dwdunwetter/internal/handler/DwdUnwetterHandler.java, bundles/org.openhab.binding.dwdunwetter/src/main/resources/ESH-INF/i18n/dwdunwetter_de.properties
Fixes #6924. 
This is mainly to address a defect where the periodic data refresh would stop occurring after a data retrieval failure.  This was happening because the `inRefresh` flag was not being reset properly.
Also cleaned up compiler warnings and fixed the description tag in the German language properties file.
See also the two community threads linked in that ticket.
I plan to propose an additional PR to make the binding surface the count of warnings received so that users don't think it's failing to retrieve data just because it's not receiving any warnings.  If someone thinks that should be done in this PR, that's fine with me, but I didn't want to overload it.
=> [dwdunwetter] Fix periodic data refresh failure

bundles/org.openhab.binding.bluetooth.bluez/src/main/java/org/openhab/binding/bluetooth/bluez/BlueZBluetoothDevice.java, bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/ConnectedBluetoothHandler.java
This will conflict with some of my other PRs but I'll deal with the conflicts then they come.
Besides changing all the byte array outputs to hex in the logs, I've also moved the notification logging out of BlueZBluetoothDevice and into the ConnectedBluetoothHandler where all of the value logging can be centralized.
=> [bluetooth] Changed Bluetooth logs to use hexadecimal (#6914)

bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/OnOffValue.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/OpenCloseValue.java, bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/values/ValueTests.java
Fix for #6933
Sorry, I somehow thought, that a format would not be needed, as the string values can be changed.
I did not think about a device which expects a different value than the one it sends....
=> [mqtt] (Re)Add outgoing format for OnOffValues

bundles/org.openhab.binding.opengarage/README.md
Just fixes the Documentation for the correct thing config key - its `hostname` not `host`
=> [opengarage] Fixes README.md with correct config value

bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/StateUtils.java, bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/dto/HueLightEntry.java, bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/dto/HueStateBulb.java, bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/dto/HueStateColorBulb.java, bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/rest/LightsAndGroups.java, bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/rest/LightsAndGroupsTests.java
Fixes #6690 #5897
When Alexa changes the state of a bulb it seems to immediately request the state of the bulb and after three requests will report an error with the device if the state does not match what it expects.
The issue is due to the conversion from hue state to OH state and back again, e.g. Alexa sends a brightness of 128 which is converted to an OH brightness of 50. However, 50 converts back to 127 and Alexa is expecting to see the brightness change to 128.
This change caches the last hue state change so that the same values can be reflected back for the status of the bulb.
Also the minimum hue brightness as stated in the API should be 1 not 0. Changing this has fixed the issue with all off bulbs being reported in the Alexa app with "Device does not support requested value" …
=> [hueemulation] Fixes to prevent Alexa errors when using voice commands and the app (#6690)

bundles/org.openhab.binding.network/README.md, bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/PresenceDetection.java, bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/SpeedTestConfiguration.java, bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/dhcp/DHCPPacketListenerServer.java, bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/handler/SpeedTestHandler.java, bundles/org.openhab.binding.network/src/main/resources/ESH-INF/thing/thing-types.xml
Recreating PR for issue #6495 and adressing two potential NPE
=> [network] Issue 6495

bundles/org.openhab.binding.tradfri/README.md, bundles/org.openhab.binding.tradfri/pom.xml, bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/DeviceUpdateListener.java, bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/TradfriBindingConstants.java, bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/TradfriColor.java, bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/TradfriHandlerFactory.java, bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/discovery/TradfriDiscoveryParticipant.java, bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/discovery/TradfriDiscoveryService.java, bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/handler/TradfriBlindHandler.java, bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/handler/TradfriControllerHandler.java, bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/handler/TradfriGatewayHandler.java, bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/handler/TradfriSensorHandler.java, bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/model/TradfriBlindData.java, bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/model/TradfriDeviceData.java, bundles/org.openhab.binding.tradfri/src/main/resources/ESH-INF/config/config.xml, bundles/org.openhab.binding.tradfri/src/main/resources/ESH-INF/i18n/tradfri_de.properties, bundles/org.openhab.binding.tradfri/src/main/resources/ESH-INF/thing/thing-types.xml, bundles/org.openhab.binding.tradfri/src/test/java/org/openhab/binding/tradfri/internal/TradfriColorTest.java, bundles/org.openhab.binding.tradfri/src/test/java/org/openhab/binding/tradfri/internal/discovery/TradfriDiscoveryServiceTest.java, bundles/org.openhab.binding.tradfri/src/test/java/org/openhab/binding/tradfri/internal/model/TradfriVersionTest.java
- Added basic support for IKEA blinds FYRTUR and KADRILJ
Supersedes #6167 
Test version: [org.openhab.binding.tradfri-2.5.2-SNAPSHOT.zip](https://github.com/openhab/openhab-addons/files/4174200/org.openhab.binding.tradfri-2.5.2-SNAPSHOT.zip)
Also-by: Manuel Raffel <manidu@outlook.com>
=> [tradfri] Added basic support for IKEA blinds FYRTUR and KADRILJ

pom.xml
=> [infrastructure] exclude feature-templates from spotless formatter

bundles/org.openhab.binding.squeezebox/README.md, bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/SqueezeBoxBindingConstants.java, bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/discovery/SqueezeBoxPlayerDiscoveryParticipant.java, bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxNotificationListener.java, bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxPlayerEventListener.java, bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxPlayerHandler.java, bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxServerHandler.java, bundles/org.openhab.binding.squeezebox/src/main/resources/ESH-INF/thing/thing-types.xml
The source channel shows from where the current playlist entry is played
from. For web radios this will be the URL, i.e.
http://www.myradio.org/radio.mp3.
This is particularly helpful if one wants to know the current source to
play something else and afterwards revert to the source before.
For announcements via the openHAB "say" infrastructure this works out of
the box with ONE squeezebox sink. It cannot work if one synchronizes
multiple sinks, because the Logitech Media Server will then use the source
from the squeezebox instance where the other instances were synchronized to.
So the other instances will play whatever was played in the instance they
were synchronized to.
With the new source channel one is able to restore the last played source
before the announcement using the stream …
=> [squeezebox] Add source channel

bundles/org.openhab.binding.mqtt.generic/pom.xml, bundles/org.openhab.binding.mqtt.generic/src/main/feature/feature.xml, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/AbstractMQTTThingHandler.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/AvailabilityTracker.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/ChannelState.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/handler/GenericMQTTThingHandler.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/handler/GenericThingConfiguration.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/mapping/MQTTvalueTransform.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/mapping/SubscribeFieldToMQTTtopic.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/tools/ChildMap.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/utils/FutureCollector.java, bundles/org.openhab.binding.mqtt.generic/src/main/resources/ESH-INF/thing/generic-thing.xml, bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/ChannelStateTransformationTests.java, bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/internal/handler/GenericThingHandlerTests.java, bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/mapping/MqttTopicClassMapperTests.java, bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/mapping/SubscribeFieldToMQTTtopicTests.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/AbstractComponent.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/CFactory.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/DiscoverComponents.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/discovery/HomeAssistantDiscovery.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/handler/HomeAssistantThingHandler.java, bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/internal/handler/HomieThingHandler.java, bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/internal/homie300/Device.java, bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/internal/homie300/Node.java, bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/handler/AbstractBrokerHandler.java, itests/org.openhab.binding.mqtt.homeassistant.tests/src/main/java/org/openhab/binding/mqtt/DiscoverComponentsTest.java, itests/org.openhab.binding.mqtt.homeassistant.tests/src/main/java/org/openhab/binding/mqtt/HomeAssistantMQTTImplementationTest.java
This PR introduces availabiltyTopic to generic MQTT Things.
The handling is done in `AbstractMQTTThingHandler`. This way I was able to reuse the implementation in homassisant components.
Generic MQTT Things without an availabilityTopic will go online as before.
If an availabilityTopic is defined, the thing will only go ONLINE, if the `payloadAvailable` is seen on the topic.
And the thing will go OFFLINE, as soon as the `payloadNotAvailable` is seen on the topic.
This would adress #6723
=> [mqtt.generic] Allow availabilty topic for generic components

bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/PercentageValue.java, bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/ChannelStateTests.java, bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/values/ValueTests.java
[mqtt] Fix increment commands in PercentageValue.
The MQTT Things and Channels plugin specifies channels with a min, max, and a step size (such as the dimmer type here: https://www.openhab.org/addons/bindings/mqtt.generic/#channel-type-dimmer).  The internal openhab percentages are converted to this range when commands are sent and values are received.
This PR fixes a bug where the step size used as a percentage, rather than in the min/max range, and the limits of the INCREASE/DECREASE/UP/DOWN commands are compared against min and max, rather than the percentages, meaning the value can go out of bounds in either direction and raise internal errors.  The PR converts the step size to a percentage before using, and compares against 0/100 instead of min/max, ensuring the increment commands …
=> [mqtt] Fix increment commands in PercentageValue.

bundles/org.openhab.binding.pjlinkdevice/README.md, bundles/org.openhab.binding.pjlinkdevice/src/main/java/org/openhab/binding/pjlinkdevice/internal/PJLinkDeviceBindingConstants.java, bundles/org.openhab.binding.pjlinkdevice/src/main/java/org/openhab/binding/pjlinkdevice/internal/PJLinkDeviceConfiguration.java, bundles/org.openhab.binding.pjlinkdevice/src/main/java/org/openhab/binding/pjlinkdevice/internal/PJLinkDeviceHandler.java, bundles/org.openhab.binding.pjlinkdevice/src/main/java/org/openhab/binding/pjlinkdevice/internal/device/PJLinkDevice.java, bundles/org.openhab.binding.pjlinkdevice/src/main/java/org/openhab/binding/pjlinkdevice/internal/device/command/CacheException.java, bundles/org.openhab.binding.pjlinkdevice/src/main/java/org/openhab/binding/pjlinkdevice/internal/device/command/CachedCommand.java, bundles/org.openhab.binding.pjlinkdevice/src/main/java/org/openhab/binding/pjlinkdevice/internal/device/command/lampstatus/LampStatesCommand.java, bundles/org.openhab.binding.pjlinkdevice/src/main/java/org/openhab/binding/pjlinkdevice/internal/device/command/lampstatus/LampStatesRequest.java, bundles/org.openhab.binding.pjlinkdevice/src/main/java/org/openhab/binding/pjlinkdevice/internal/device/command/lampstatus/LampStatesResponse.java, bundles/org.openhab.binding.pjlinkdevice/src/main/java/org/openhab/binding/pjlinkdevice/internal/discovery/AbstractDiscoveryParticipant.java, bundles/org.openhab.binding.pjlinkdevice/src/main/resources/ESH-INF/thing/thing-types.xml
As [discussed in the initial contribution of this binding](https://github.com/openhab/openhab2-addons/pull/3834#discussion_r304840795) with @lolodomo, it could be useful to the user to have lamp usage hours as a channel instead of a property.
This PR addresses this issue by adding configurable channels for the lamp channels.
There is one preconfigured channel for lamp 1 (which should be available in most devices), if a device has more lamps additional channels can be configured.
=> [pjlinkdevice] Improvement: Projector lamp states as channels

bundles/org.openhab.binding.chromecast/pom.xml
supersedes #6387 
fixes security issues
=> [chromecast] bring jackson version in  line with ohc

bundles/org.openhab.binding.innogysmarthome/README.md
Using the new API of innogy the authentication of bridges has been changed. The according section at https://www.openhab.org/addons/bindings/innogysmarthome/#manual-configuration is outdated.
See also https://community.openhab.org/t/innogysmarthome-where-to-find-refresh-token/90347/4
Signed-off-by: Stephan Strittmatter <stephan@st-strittmatter.name>
=> [innogysmarthome][doc] update documentation for manually configured Bridge

bundles/org.openhab.binding.exec/src/main/java/org/openhab/binding/exec/internal/ExecWhitelistWatchService.java, bundles/org.openhab.transform.exec/src/main/java/org/openhab/transform/exec/internal/ExecTransformationWhitelistWatchService.java
Use own class loggers instead of super-class loggers
=> [exec] fix loggers for whitelist-service

bundles/org.openhab.binding.bluetooth.bluez/src/main/java/org/openhab/binding/bluetooth/bluez/handler/BlueZBridgeHandler.java
Fixes issue #7072 by catching any Bluetooth exception within the discovery loop.
Makes attempt at preventing possible cause of errors and updates the adapter bridge status accordingly.
=> [bluetooth.bluez] Fix for bluez discovery scheduler death (#7072)

bundles/org.openhab.io.transport.modbus/src/main/java/org/openhab/io/transport/modbus/internal/ModbusManagerImpl.java
Certain exceptions in modbus binding were logged inproperly.
Helps to troubleshoot cases when exception message is empty. For example,  https://community.openhab.org/t/problem-with-modbus-binding-with-dynamic-on-off/92288/22 reported by forum user EjvindHald:
> 2020-02-29 18:39:12.703 [ERROR] [rt.modbus.internal.ModbusManagerImpl] - Connection pool swallowed unexpected exception:
=> [modbus] Log more information on unexpected (uncatched) exceptions

bundles/org.openhab.binding.tradfri/README.md
bugfix: sitemap does not seem to support "Rollershutter" element types (at least not for me, gives me an error "mismatched input"), suggesting to replace it with "Switch" and displaying the position value
=> [tradfri] correct sitemap example

bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/ICloudDeviceInformationParser.java, bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/handler/ICloudAccountBridgeHandler.java
Hope this makes sense.
I got this NPE few days ago:
```
2020-02-29 22:10:53.325 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
at org.openhab.binding.icloud.internal.handler.ICloudAccountBridgeHandler.refreshData(ICloudAccountBridgeHandler.java:170) ~[?:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_222]
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[?:1.8.0_222]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_222]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[?:1.8.0_222]
at …
```
=> [icloud] Fix NPE in AccountBridgeHandler

bundles/org.openhab.binding.bluetooth.bluez/src/main/resources/ESH-INF/thing/bluez.xml
Discovery for bluez adapter should be disabled by default to prevent
overwhelming users when they first add a bluez thing. Since the user can
do manual scans when they need to there is no reason for discovery to be
enabled all the time. To make it worse, it is not intuitive for the user at all how to shut off bluetooth discovery.
So to make things better I suggest just having always-on discovery disabled by default.
=> [bluetooth.bluez] Bluez device discovery should be disabled by default

bundles/org.openhab.binding.weathercompany/README.md, bundles/org.openhab.binding.weathercompany/src/main/java/org/openhab/binding/weathercompany/internal/handler/WeatherCompanyForecastHandler.java, bundles/org.openhab.binding.weathercompany/src/main/java/org/openhab/binding/weathercompany/internal/handler/WeatherCompanyObservationsHandler.java, bundles/org.openhab.binding.weathercompany/src/main/java/org/openhab/binding/weathercompany/internal/model/DayPartDTO.java, bundles/org.openhab.binding.weathercompany/src/main/java/org/openhab/binding/weathercompany/internal/model/ForecastDTO.java, bundles/org.openhab.binding.weathercompany/src/main/java/org/openhab/binding/weathercompany/internal/model/PwsObservationsDTO.java, bundles/org.openhab.binding.weathercompany/src/main/resources/ESH-INF/thing/thing-types.xml
Increase decimal precision for PWS Observations by requesting the observations using the new "numericPrecision" query parameter. This has been a much requested feature from the Weather Company service provider, and is especially useful for those who use Celsius.
Also rename model classes to eliminate @Null warnings.
=> [weathercompany] Increase decimal precision for PWS Observations

bundles/org.openhab.binding.mcp23017/src/main/java/org/openhab/binding/mcp23017/internal/handler/Mcp23017Handler.java
The ActiveLow configuration setting is optional, but is being treated as if it's required.
This can cause a NullPointerException when the setting is not defined.
Fixes #6111 
=> [mcp23017] Don't treat the ActiveLow setting as if it's required

bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/handler/ChannelBridgeCheck.java
Mentioning unexpected configurations will only be logged with level debug:
Definitions of the bridge, which aren't used within the binding configuration, had caused an informational log entry. This is now reduced to level debug for convenience.
Signed-off-by: Guenther Schreiner <guenther.schreiner@smile.de>
=> [velux] Decreased logging 

bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/handler/utils/ThingConfiguration.java
When the channel `check` is activated, a warning appears during refresh for any other channel items which do aren't equipped with a property.
=> [velux] fix: avoid warnings during non-existent properties.

bundles/org.openhab.binding.jeelink/README.md, bundles/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/JeeLinkBindingConstants.java, bundles/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/JeeLinkHandler.java, bundles/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/JeeLinkSensorHandler.java, bundles/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/ReadingHandler.java, bundles/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/SensorDefinition.java, bundles/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/config/BufferedSensorConfig.java, bundles/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/config/LaCrosseTemperatureSensorConfig.java, bundles/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/config/Pca301SensorConfig.java, bundles/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/connection/AbstractJeeLinkConnection.java, bundles/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/discovery/SensorDiscoveryService.java, bundles/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/ec3k/Ec3kSensorDefinition.java, bundles/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/ec3k/Ec3kSensorHandler.java, bundles/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/lacrosse/LaCrosseTemperatureSensorHandler.java, bundles/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/lacrosse/Tx22SensorDefinition.java, bundles/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/lacrosse/Tx22SensorHandler.java, bundles/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/pca301/Pca301SensorDefinition.java, bundles/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/pca301/Pca301SensorHandler.java, bundles/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/revolt/RevoltReading.java, bundles/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/revolt/RevoltReadingConverter.java, bundles/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/revolt/RevoltSensorDefinition.java, bundles/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/revolt/RevoltSensorHandler.java, bundles/org.openhab.binding.jeelink/src/main/resources/ESH-INF/i18n/jeelink.properties, bundles/org.openhab.binding.jeelink/src/main/resources/ESH-INF/i18n/jeelink_de.properties, bundles/org.openhab.binding.jeelink/src/main/resources/ESH-INF/thing/thing-types.xml
Adds support for the revolt protocol to the jeelink binding. Fixes #6077.
=> [jeelink] add revolt support

bundles/org.openhab.binding.lutron/README.md, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/LutronBindingConstants.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/discovery/LutronMcastBridgeDiscoveryService.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/discovery/LutronMdnsBridgeDiscoveryService.java
This update allows Caseta Smart Bridge Pro 2 devices to be automatically discovered via mDNS through the use of a MDNSDiscoveryParticipant service.
The new discovery service should also be able to find other recent Lutron devices discoverable via mDNS/DNS-SD (not all of which are supported by openHAB) such as Caseta Smart Bridge 1, RA2 Select main repeaters, and the Lutron Connect Bridge (CONNECT-BDG2). Discovery of these should currently not result in the creation of a discovered thing in the inbox, but instead will cause a log message such as the following to be generated;
```Lutron device with unknown DEVCLASS discovered via mDNS: XXXXXXXX. Configure device manually.```
As users report DEVCLASS information from currently unrecognized devices, discovery support for these can be added as …
=> [lutron] Add support for mDNS bridge discovery

bundles/org.openhab.binding.lifx/README.md, bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/protocol/Product.java
Adds support for the following new LIFX products:
* LIFX A19/+ and BR30/+ (new generation)
* LIFX Candle Warm to White
* LIFX Filament
Fixes the temperature range of the LIFX Candle products
See: https://github.com/LIFX/products/blob/master/products.json
=> [lifx] Support new products, fix Candle temperature range

bundles/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/internal/handler/SenseBoxHandler.java
- Use dimension PERCENT instead of ONE for percentage values (e.g. humidity)
Currently the Item shows wrong values:
```
{"title":"rel. Luftfeuchte","unit":"%","sensorType":"DHT22","icon":"osem-humidity","_id":"XXXXX","lastMeasurement":{"value":"99.90","createdAt":"2020-03-08T20:16:10.766Z"}
```
=> [sensebox] Use dimension PERCENT instead of ONE for percentage values

bundles/org.openhab.binding.bluetooth.bluegiga/src/main/java/org/openhab/binding/bluetooth/bluegiga/BlueGigaBluetoothDevice.java, bundles/org.openhab.binding.bluetooth.bluegiga/src/main/java/org/openhab/binding/bluetooth/bluegiga/handler/BlueGigaBridgeHandler.java
... as it breaks the build for openHAB 3, see https://ci.openhab.org/job/openHAB-Addons-port/58/console
=> [bluetooth.bluegiga] removed usage of Jodatime

bundles/org.openhab.binding.daikin/README.md, bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/DaikinDynamicStateDescriptionProvider.java, bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/DaikinHandlerFactory.java, bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/Enums.java, bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/airbase/AirbaseControlInfo.java, bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/airbase/AirbaseEnums.java, bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/airbase/AirbaseModelInfo.java, bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/handler/DaikinAcUnitHandler.java, bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/handler/DaikinAirbaseUnitHandler.java, bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/handler/DaikinBaseHandler.java, bundles/org.openhab.binding.daikin/src/main/resources/ESH-INF/thing/thing-types.xml
Split the thing handler class for Daikin "AC Unit" and "Airbase"
Fix the for airbase airside and auto fan modes
Add DynamicStateDescriptionProvider for airbase fan mode to hide airside/auto fan levels when not available
Add DynamicStateDescriptionProvider for airbase ac mode to hide auto/dry when not available
Fix documentation for ac mode state from "DEHUMIDIFIER" ->"DRY"
NOTE that the Airbase fan levels are expanded from 3 levels to 5 levels. Previously, LEVEL_3 means maximum fan speed, it now means "medium" fan speed. This applies to Airbase (airbase_ac_unit) only and does not affect non airbase (ac_unit) implementation.
Fixes #6524
=> [daikin] Fix airside fan mode for airbase. Split handler class.

buildci.sh, itests/org.openhab.binding.mqtt.homeassistant.tests/itest.bndrun, itests/org.openhab.binding.mqtt.homeassistant.tests/pom.xml, itests/org.openhab.binding.mqtt.homeassistant.tests/src/main/java/org/openhab/binding/mqtt/HomeAssistantMQTTImplementationTest.java, itests/org.openhab.binding.mqtt.homie.tests/pom.xml, itests/org.openhab.io.mqttembeddedbroker.tests/pom.xml, itests/pom.xml, pom.xml
While I have been making a few small bugfixes to binding.mqtt.homeassistant, it is unsatisfying not to see the green checkmark on the Travis integration tests :).  I have made the following updates to allow the integration tests to run.
Fixed the script buildci.sh.  The sed pattern for CHANGED_ITEST_DIR was not quite correct, if two directories were changed in the same test, then a build of all was forced.  With my change, with this current pull request everything will be built for the CI tests, but if someone approves this pull request, in future pull requests just for the tests, only the modified test will build and be tested.
Bigger overall change, changed the settings for bnd-testing-maven-plugin in itests/pom.xml to do OSGi resolution on the Travis machine before running the tests. …
=> [itests mqtt.homeassistant] Fixed itests for mqtt.homeassistant

bundles/org.openhab.binding.miio/README.base.md, bundles/org.openhab.binding.miio/README.md, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoHandlerFactory.java, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/Utils.java, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/MiIoDatabaseWatchService.java, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoAbstractHandler.java, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoBasicHandler.java, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoGenericHandler.java, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoUnsupportedHandler.java, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoVacuumHandler.java
* Allow users to create their own database files to speed up adoption
for new devices
* Local database files get priority over ones defined in the binding
* Local files to be located in the getUserDataFolder\miio folder
=> [miio] Enable local database files

bundles/org.openhab.io.neeo/README.md
After removal of NEEO dashboard tile, direct link is now required.
=> [NEEO Integration] Update Readme

bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/BaseChannelHandler.java, bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/ChannelHandler.java, bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/LauncherApplication.java, bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/MediaControlPlayer.java, bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/MediaControlStop.java, bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/PowerControlPower.java, bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/RCButtonControl.java, bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/TVControlChannel.java, bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/TVControlChannelName.java, bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/ToastControlToast.java, bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/VolumeControlMute.java, bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/VolumeControlVolume.java, bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/handler/LGWebOSHandler.java, bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/handler/LGWebOSTVSocket.java
This PR improves channel subscription and introduces support for RefreshType commands, which are relevant to update the state of a channel, when items are linked to channels for the first time.
Which addresses bug #7118
=> [lgwebos] Fix Channel Subscription and Support RefreshType

bundles/org.openhab.binding.nanoleaf/README.md, bundles/org.openhab.binding.nanoleaf/pom.xml, bundles/org.openhab.binding.nanoleaf/src/main/feature/feature.xml, bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/OpenAPIUtils.java, bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/discovery/NanoleafMDNSDiscoveryParticipant.java, bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/handler/NanoleafControllerHandler.java, bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/handler/NanoleafPanelHandler.java, bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/model/State.java, bundles/org.openhab.binding.nanoleaf/src/main/resources/ESH-INF/binding/binding.xml, bundles/org.openhab.binding.nanoleaf/src/main/resources/ESH-INF/i18n/nanoleaf.properties, bundles/org.openhab.binding.nanoleaf/src/main/resources/ESH-INF/i18n/nanoleaf_de.properties, bundles/org.openhab.binding.nanoleaf/src/main/resources/ESH-INF/thing/lightpanels.xml, bundles/org.openhab.binding.nanoleaf/src/test/java/org/openhab/binding/nanoleaf/internal/handler/NanoleafControllerHandlerTest.java
- fixed the fact that the power state was not resolved anymore correctly
- added test for power state resolving
- added correct autodiscovery suppression based on representation property.
=> [nanoleaf] fixed powerStateUpdate, ignore statically defined things on discovery

bundles/org.openhab.binding.goecharger/src/main/java/org/openhab/binding/goecharger/internal/handler/GoEChargerHandler.java
Followup to https://github.com/openhab/openhab-addons/pull/7068
There was an error in handling the access state command. I just tested it and noticed, that the commands were not translated correctly so i fixed it.
I also added parsing of the response body of the POST request, as it contains the same data in the body, as a normal GET request. So by sending a command we always get the latest values without the need to query them again.
This is useful for example when setting the access config, as it also has side effects on other properties.
For example
`accessConfig` "OPEN" will set `allowCharging` to true
`accessConfig` "RFID" will set `allowCharging` to false
So when we set "OPEN" we will immidiately get the result for `allowCharging`without additional GET.
@wborn, @J-N-K sorry for …
=> [goecharger] fixed access config command and parse command response

bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/discovery/internal/BluetoothDiscoveryProcess.java
Airthings service discovery takes around 5 seconds when device is very
close to bluetooth dongle. Timeouts have been seen multiple times.
Increased timeout to increase probability for successful service
discovers during connection oriented device discovery.
=> [bluetooth] Increased discovery timeout from 5 sec to 10 sec

bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/discovery/internal/BluetoothDiscoveryProcess.java
Removed extra service discovery from connection event handling. Service
discovery is done when connection based discovery is required.
=> [bluetooth] Removed extra service discovery

bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/model/OSHISysteminfo.java
Remove the null returns for getSwapTotal(), getSwapAvailable() and getSwapUsed(). This makes it obey the specifications in the SysteminfoInterface JavaDoc. Also changes getSwapAvailablePercent() and getSwapUsedPercent() to make variable naming more consistent.
Fixes #6983 
When the getSwap* methods return null the channel and connected Item gets set to UNDEF. This fix makes it able to be set to 0 e.g. shortly after a system reboot, when no pages have been swapped yet.
=> [systeminfo] Make getSwap* methods able to return 0

bundles/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/OnkyoBindingConstants.java, bundles/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/OnkyoModel.java, bundles/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/discovery/OnkyoUpnpDiscoveryParticipant.java
Using an OnkyoModel enum in some streams simplifies the code so there will be less duplication.
This way it will be easier to add new models and review such PRs.
=> [onkyo] Enumerate supported models using OnkyoModel enum

bundles/org.openhab.binding.nanoleaf/README.md, bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/NanoleafBindingConstants.java, bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/NanoleafInterruptedException.java, bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/OpenAPIUtils.java, bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/discovery/NanoleafMDNSDiscoveryParticipant.java, bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/handler/NanoleafControllerHandler.java, bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/model/Layout.java, bundles/org.openhab.binding.nanoleaf/src/main/resources/ESH-INF/i18n/nanoleaf.properties, bundles/org.openhab.binding.nanoleaf/src/main/resources/ESH-INF/i18n/nanoleaf_de.properties, bundles/org.openhab.binding.nanoleaf/src/main/resources/ESH-INF/thing/lightpanels.xml, bundles/org.openhab.binding.nanoleaf/src/test/java/org/openhab/binding/nanoleaf/internal/LayoutTest.java
- Reduce layout logging by manual triggering
- Add more test for inconsistent layout response from device
- Fix wrong type detection for canvas
- Fix rediscovery end handling (could have put controller offline)
- Add model/vendor properties automatically if things configured manually in a static things file
- Some code cleanup
=> [nanoleaf] reduce layout logs, fix wrong type detection, add discovery props

bundles/org.openhab.io.transport.modbus/src/main/java/org/openhab/io/transport/modbus/ModbusReadRequestBlueprint.java, bundles/org.openhab.io.transport.modbus/src/main/java/org/openhab/io/transport/modbus/ModbusUnexpectedResponseFunctionCodeException.java, bundles/org.openhab.io.transport.modbus/src/main/java/org/openhab/io/transport/modbus/ModbusUnexpectedResponseSizeException.java, bundles/org.openhab.io.transport.modbus/src/main/java/org/openhab/io/transport/modbus/ModbusUnexpectedTransactionIdException.java, bundles/org.openhab.io.transport.modbus/src/main/java/org/openhab/io/transport/modbus/internal/ModbusLibraryWrapper.java, bundles/org.openhab.io.transport.modbus/src/main/java/org/openhab/io/transport/modbus/internal/ModbusManagerImpl.java, bundles/org.openhab.io.transport.modbus/src/main/java/org/openhab/io/transport/modbus/internal/SimpleStopWatch.java, bundles/org.openhab.io.transport.modbus/src/test/java/org/openhab/io/transport/modbus/test/SmokeTest.java
Resolves #7159 
In this PR, we handle gracefully the two following errors observed in the wild
- slave responds with too little data (e.g. returning 5 registers even though 7 was requested). Instead of crashing later when
using the data, abort immediately.
- slave responds with function code which does not match the request (e.g. returning input registers even though holding registers were requested).
In addition, we have a catch-all to cover any other unknown corner cases, to prevent silent halting of the polling as discussed in #7159.
=> [modbus] gracefully handle unexpected slave responses

bundles/org.openhab.binding.tellstick/README.md, bundles/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/internal/TellstickBindingConstants.java, bundles/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/internal/discovery/TellstickDiscoveryService.java, bundles/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/internal/handler/TelldusDevicesHandler.java, bundles/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/internal/live/xml/LiveDataType.java, bundles/org.openhab.binding.tellstick/src/main/resources/ESH-INF/config/config.xml, bundles/org.openhab.binding.tellstick/src/main/resources/ESH-INF/thing/devices.xml, bundles/org.openhab.binding.tellstick/src/main/resources/ESH-INF/thing/sensor.xml
This PR implements a correct auto-detect handling for Rain and Wind devices.
It also uses the correct measurement types for the different channel types.
README has been updated.
Fixes #7171 
I've tested this [jar-file](https://drive.google.com/open?id=1ZxtCDecRDktKebWtl0OSPQGjmq5m7YO7) successfully in my own production environment.
=> [tellstick] Fix auto-detect handling for Rain and Wind devices

bundles/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/internal/SenseBoxAPIConnection.java, bundles/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/internal/handler/SenseBoxHandler.java, bundles/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/internal/model/SenseBoxSensor.java
- Fixed handling of micro sign and greek letter mu
See https://community.openhab.org/t/sensebox-binding-bug/82115/20
=> [sensebox] Fixed handling of micro sign and greek letter mu

bundles/create_openhab_binding_skeleton.cmd, bundles/create_openhab_binding_skeleton.sh, itests/org.openhab.binding.astro.tests/itest.bndrun, itests/org.openhab.binding.avmfritz.tests/itest.bndrun, itests/org.openhab.binding.feed.tests/itest.bndrun, itests/org.openhab.binding.hue.tests/itest.bndrun, itests/org.openhab.binding.max.tests/itest.bndrun, itests/org.openhab.binding.modbus.tests/itest.bndrun, itests/org.openhab.binding.nest.tests/itest.bndrun, itests/org.openhab.binding.ntp.tests/itest.bndrun, itests/org.openhab.binding.systeminfo.tests/itest.bndrun, itests/org.openhab.binding.tradfri.tests/itest.bndrun, itests/org.openhab.binding.wemo.tests/itest.bndrun, itests/org.openhab.io.hueemulation.tests/itest.bndrun
Without it itests fail and the binding skeleton uses the wrong version.
=> Fix missing 2.5.4-SNAPSHOT changes

bundles/org.openhab.binding.weathercompany/src/main/java/org/openhab/binding/weathercompany/internal/model/DayPartDTO.java, bundles/org.openhab.binding.weathercompany/src/main/java/org/openhab/binding/weathercompany/internal/model/PwsObservationsDTO.java
I missed these in my recent implementation of greater precision. The issue surfaced because a user had a weather station that reported humidity to one decimal place.
=> [weathercompany] Fix precision issue

bundles/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/JeeLinkBindingConstants.java, bundles/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/SensorDefinition.java, bundles/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/lacrosse/LgwReading.java, bundles/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/lacrosse/LgwReadingConverter.java, bundles/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/lacrosse/LgwSensorDefinition.java, bundles/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/lacrosse/LgwSensorHandler.java, bundles/org.openhab.binding.jeelink/src/main/resources/ESH-INF/i18n/jeelink.properties, bundles/org.openhab.binding.jeelink/src/main/resources/ESH-INF/i18n/jeelink_de.properties, bundles/org.openhab.binding.jeelink/src/main/resources/ESH-INF/thing/thing-types.xml
This adds support for sensors that are directly connected to Lacrosse Gateways.
See https://community.openhab.org/t/new-jeelink-openhab2-binding/15018/370 ff.
=> [jeelink] Add suport for sensors that are directly connected to a LGW

bundles/org.openhab.binding.doorbird/src/main/java/org/openhab/binding/doorbird/internal/handler/DoorbellHandler.java
Some users create a thing for each user of their Doorbird doorbell. In some cases, they create more than 5 things for a single doorbell. Currently, the `DoorbellHandler` uses a single dedicated thread pool for the UDP listener, but that thread pool is limited to 5 threads. As a result, only a maximum of 5 of the thing handlers will receive UDP broadcast packets (which indicate doorbell press and motion detection events). This change creates a dedicated thread pool for each handler. Each pool will only ever consume 1 thread for its pool.
=> [doorbird] Fix for more than 5 doorbell things

bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/NumberValue.java
This is a fix for #7139
There was some remapping of the outgoing format left over from some intermediate state.
`%s` should stay as is and will be handled correctly by `DecimalType`
=> [mqtt] Fix outgoing format for NumberValues

bundles/org.openhab.io.homekit/README.md, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitAccessoryType.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitAccessoryFactory.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitLockImpl.java
This PR contains implementation for Lock mechanism in Homekit such as Door Lock.
Switch items can be tagged with "Lock" tag. Although it could previously work with "Lighting" tags, now allows usage of proper sentences with Siri such as "open the door" instead of "turn on the door", and displays it with proper "lock" icon in Home app.
The documentation (README) is also updated.
=> [homekit] Implements support for HomeKit with Lock mechanisms.

bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/State.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueBridgeHandler.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueLightHandler.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/LightStateConverter.java
Fix NullPointerException on missing state attribute alert at deconz version 2.05.75
See Bug report #7218
=> [Hue] Null-proof handling getAlertMode()

bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxPlayerHandler.java, bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxServerHandler.java
Fixes #7217 
The binding currently does not use the `<playerid> mixer muting <0|1|toggle|?|>` command to mute/unmute the player. Instead, on mute, it saves the current volume, then sets the volume to 0. On unmute, it restores the saved volume. Muting the player twice in a row causes the initial volume level to be lost.
This PR replaces the call to `setVolume` with the mixer muting command.
=> [squeezebox] Change mute/unmute to use mixer muting command

bundles/org.openhab.binding.exec/src/main/java/org/openhab/binding/exec/internal/ExecWhitelistWatchService.java, bundles/org.openhab.binding.harmonyhub/src/main/java/org/openhab/binding/harmonyhub/internal/handler/HarmonyHubHandler.java, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/MiIoDatabaseWatchService.java, bundles/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/config/YamahaZoneConfig.java, bundles/org.openhab.transform.exec/src/main/java/org/openhab/transform/exec/internal/ExecTransformationWhitelistWatchService.java
This change worksaround the PMD ParseException that would occur while analyzing the MiIoDatabaseWatchService.
See also:
* https://github.com/pmd/pmd/issues/1367
* https://github.com/openhab/static-code-analysis/issues/378
=> Workaround PMD ParseException in all add-ons

bundles/org.openhab.binding.darksky/src/main/java/org/openhab/binding/darksky/internal/handler/DarkSkyWeatherAndForecastHandler.java
- Default states to `UNDEF` if no alerts are present
See https://community.openhab.org/t/dark-sky-yawb4oh2-yet-another-weather-binding-for-openhab-2/69968/80
=> [darksky] Default states to 'UNDEF' if no alerts are present

bundles/org.openhab.binding.valloxmv/.classpath, bundles/org.openhab.binding.valloxmv/README.md, bundles/org.openhab.binding.valloxmv/README_DEV.md, bundles/org.openhab.binding.valloxmv/src/main/java/org/openhab/binding/valloxmv/internal/ValloxMVBindingConstants.java, bundles/org.openhab.binding.valloxmv/src/main/java/org/openhab/binding/valloxmv/internal/ValloxMVHandler.java, bundles/org.openhab.binding.valloxmv/src/main/java/org/openhab/binding/valloxmv/internal/ValloxMVWebSocket.java, bundles/org.openhab.binding.valloxmv/src/main/resources/ESH-INF/thing/thing-types.xml
Added support for additional channels, as per here:
https://community.openhab.org/t/new-binding-vallox-mv-ventilation-unit-series-beta/36735/102
This is still to do, not sure what is the best way to do it (added comment about this into code):
- for timer profiles, use timer value from that profile settings instead of “hardcoded” value in binding code
I am thinking that these values should be asked from Vallox device before changing to Fireplace or Boost profile. In general these values have been received from full data update, but not sure if we can save values for later use - if we could, then a separate data request would not be needed.
=> [valloxmv] additional channels support

bundles/org.openhab.binding.mqtt.homie/README.md
Help other poor souls that arrive at the homie binding documentation page by way of the great Google and then are confused when they attempt to install mqtt.homie via their configuration files.
=> [mqtt.homie] Call out homie binding provided by MQTT binding

bundles/org.openhab.binding.chromecast/pom.xml
Sometimes the build process fails due to a missing dependency
```[ERROR] Failed to execute goal on project org.openhab.binding.chromecast: Could not resolve dependencies for project org.openhab.addons.bundles:org.openhab.binding.chromecast:jar:2.5.4-SNAPSHOT: Failed to collect dependencies at su.litvak.chromecast:api-v2:jar:0.11.2 -> com.fasterxml.jackson.core:jackson-databind:jar:2.9.0,pr4-SNAPSHOT: Failed to read artifact descriptor for com.fasterxml.jackson.core:jackson-databind:jar:2.9.0,pr4-SNAPSHOT: Failure to find com.fasterxml.jackson:jackson-bom:pom:2.9.0.pr4-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-snapshots has elapsed or updates are forced -> …
```
=> [chromecast] Explicitly exclude jackson dependencies to avoid build failure

bundles/org.openhab.binding.innogysmarthome/src/main/java/org/openhab/binding/innogysmarthome/internal/client/Constants.java
Changes auth endpoint as livisi will shutdown the old endpoint on 31.06.2020
=> [innogysmarthome] New innogy auth endpoint as livisi will shutdown the old endpoint

bundles/org.openhab.binding.bluetooth.am43/README.md, features/openhab-addons/src/main/resources/footer.xml
I didn't realize there was another file I needed to update in order for those bindings to be bundled into the bluetooth binding.
Also I'm adding a link to the AM43 product page that I forgot to include in my initial commit.
=> [bluetooth] Fix for AM43 and Airthings devices not being discovered.

bundles/org.openhab.binding.pulseaudio/README.md
The pulseaudio README/documentation incorrectly shows an example of using ipAddress as the configuration parameter, while the implementation uses `host`. This really only impacts users that use a remote pulseaudio server as the binding defaults to localhost/127.0.0.1 and hence works for users running everything locally. 
Doc fixes/changes only.
=> [pulseaudio] Fix documentation to use 'host' instead of 'ipAddress'

tools/static-code-analysis/checkstyle/suppressions.xml
Currently there is a checkstyle suppression treating files ending i DTO differently than other files by omitting various rules (the null annotations for instance). This PR also allows packages that contain `.dto.` to be treated the same way. Then we do not have to postfix all DTO classes with `DTO` .
Signed-off-by: Arne Seime <arne.seime@gmail.com>
=> [checkstyle] Treat packages containing .dto. the same way as java classes ending in DTO

bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/connector/RFXComStreamReader.java
=> [rfxcom] EOF fix
