- addons/binding/org.openhab.binding.harmonyhub/.classpath
Fixes eclipse complaining about wrong library in classpath.  
> [harmonyhub] updates classpath 

- addons/transform/org.openhab.transform.jinja/README.md
See https://v0.vuepress.vuejs.org/guide/using-vue.html#escaping
This prevents the infortunate misinterpretation of the example as a Mustache template by VuePress.
Signed-off-by: Yannick Schaus <github@schaus.net>
> [jinja] Readme: Use VuePress escaping in example

- addons/binding/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/Connection.java
This PR fixes an issue in the playMusicVoiceCommand channel, if the device is registered on another amazon account.
> [amazonechocontrol] Fix issue with multiple amazon accounts 

- addons/binding/org.openhab.binding.powermax/README.md
- addons/binding/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/handler/PowermaxBridgeHandler.java
> [powermax] Disable RFC2217 in favor of IP conection thing type

- addons/binding/org.openhab.binding.systeminfo/README.md
In most cases `none` icon looks better than the default `text` icon. It
also fixes the typo in `Recevied`.
Signed-off-by: mueller-ma <mueller-ma@users.noreply.github.com>
> [systeminfo] Add Item labels and icons to Readme

- poms/bnd/pom.xml
The old manifests did not contain version constraints for the OpenHAB or ESH bundles. The bnd-generated manifests set constraints that do not allow using newer bundles with older versions of OpenHAB (e.g. Snapshot-Build-Binding/Release-Core). This PR reverts that change.
> remove version constraint from manifest

- addons/binding/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/KM200Cryption.java
- addons/binding/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/core/LxWsSecurityToken.java
- addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/socket/XiaomiSocket.java
- addons/binding/org.openhab.binding.neato/src/main/java/org/openhab/binding/neato/internal/NeatoRobot.java
- addons/binding/org.openhab.binding.silvercrestwifisocket/src/main/java/org/openhab/binding/silvercrestwifisocket/internal/utils/WifiSocketPacketConverter.java
- addons/io/org.openhab.io.imperihome/src/main/java/org/openhab/io/imperihome/internal/util/DigestUtil.java
- addons/voice/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/internal/cloudapi/CachedVoiceRSSCloudImpl.java
> Use getBytes(StandardCharsets.UTF_8) instead of getBytes("UTF-8")

- addons/binding/org.openhab.binding.yeelight/ESH-INF/thing/ceiling.xml
- addons/binding/org.openhab.binding.yeelight/ESH-INF/thing/channels.xml
- addons/binding/org.openhab.binding.yeelight/ESH-INF/thing/ct_bulb.xml
- addons/binding/org.openhab.binding.yeelight/ESH-INF/thing/desklamp.xml
- addons/binding/org.openhab.binding.yeelight/ESH-INF/thing/dolphin.xml
- addons/binding/org.openhab.binding.yeelight/ESH-INF/thing/stripe.xml
- addons/binding/org.openhab.binding.yeelight/ESH-INF/thing/wonder.xml
- addons/binding/org.openhab.binding.yeelight/README.md
- addons/binding/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/YeelightBindingConstants.java
- addons/binding/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/handler/YeelightHandlerBase.java
- addons/binding/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/device/DeviceBase.java
- addons/binding/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/device/DeviceMethod.java
- addons/binding/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/device/connection/ConnectionBase.java
- addons/binding/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/device/connection/WifiConnection.java
- addons/binding/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/services/DeviceManager.java
Signed-off-by: Joe Ho <goodfore@gmail.com> (github:goodfore)
Closes #3763 .
> [yeelight] Added command channel

- CODEOWNERS
> Added IHC binding to CODEOWNERS file

- addons/io/org.openhab.io.homekit/README.md
Documentation improvement
Hello team! 👋
These links would have made my life a bit easier as a newbie to OpenHab2 and HomeKit integration. Cheers.
> [homekit] Add links to HomeKit Add-on integration guide

- bom/openhab-addons/pom.xml
> [daikin] Added Daikin binding to BOM

- addons/binding/org.openhab.binding.mihome/ESH-INF/binding/binding.xml
- addons/binding/org.openhab.binding.mihome/ESH-INF/thing/gateway.xml
- addons/binding/org.openhab.binding.mihome/ESH-INF/thing/sensor_ht.xml
- addons/binding/org.openhab.binding.mihome/ESH-INF/thing/sensor_switch.xml
- addons/binding/org.openhab.binding.mihome/ESH-INF/thing/sensor_switch_aq2.xml
- addons/binding/org.openhab.binding.mihome/ESH-INF/thing/sensor_vibration.xml
- addons/binding/org.openhab.binding.mihome/ESH-INF/thing/sensor_weather_v1.xml
This PR corrects some spelling and grammar errors in the Things and Binding description.
Signed-off-by: Stewart Cossey <stewart.cossey@gmail.com>
> [mihome] Tidied up spelling and grammar errors in the Thing/Binding descriptions.

- itests/org.openhab.binding.astro.tests/itest.bndrun
- itests/org.openhab.binding.avmfritz.tests/itest.bndrun
- itests/org.openhab.binding.dmx.tests/itest.bndrun
- itests/org.openhab.binding.onewire.tests/itest.bndrun
See:
* https://github.com/openhab/openhab-core/pull/648
* https://github.com/openhab/openhab-core/pull/650
> Update itests bndrun files for Gson and Xtext updates

- addons/binding/org.openhab.binding.squeezebox/ESH-INF/binding/binding.xml
- addons/binding/org.openhab.binding.squeezebox/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.squeezebox/README.md
- addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/SqueezeBoxAudioSink.java
- addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/SqueezeBoxHandlerFactory.java
- addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/config/SqueezeBoxPlayerConfig.java
- addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/config/SqueezeBoxServerConfig.java
- addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/discovery/SqueezeBoxPlayerDiscoveryParticipant.java
- addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/discovery/SqueezeBoxServerDiscoveryParticipant.java
- addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxNotificationListener.java
- addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxNotificationPlayer.java
- addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxPlayer.java
- addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxPlayerEventListener.java
- addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxPlayerPlayState.java
- addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxPlayerState.java
- addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxServerHandler.java
- addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/utils/HttpUtils.java
- addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/utils/SqueezeBoxTimeoutException.java
Fixes #5074
Also fixes SAT issues.
> [squeezebox] Add callback url and fix SAT issues

- addons/binding/org.openhab.binding.mqtt.generic/README.md
The 2nd Publish All Rule didnt work in its current form see
https://community.openhab.org/t/mqtt2-eventbus-rule-only-throws-error/70428
> [mqtt] Update the Readme part about sychronizing two intances

- addons/binding/org.openhab.binding.spotify/README.md
Minor updates to fix table formatting, spelling and grammar.
I've interpreted @Grimthorr's comment in his pr (#5105) as a confirmation I could fix his pr. This pr replaces and closes #5105 (closes #5104).
> [spotify] Update README.md, Replaces #5105

- addons/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/ws/IhcClient.java
- Replaced usage of `DatatypeConverter`
See #5083 
> [ihc] Replaced usage of 'DatatypeConverter'

- bundles/org.openhab.binding.openweathermap/src/main/resources/ESH-INF/i18n/openweathermap_fr.properties
> [openweathermap] Update the French translation

- addons/binding/org.openhab.binding.meteoblue/ESH-INF/i18n/meteoblue_fr.properties
> [meteoblue] Add French translation

- addons/binding/org.openhab.binding.rfxcom/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/RFXComHandlerFactory.java
- addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/connector/RFXComSerialConnector.java
- addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/handler/RFXComBridgeHandler.java
> [rfxcom] Use serial packages from core rather than gnu.io

- addons/binding/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/connector/UplinkWebInterface.java
Require the value of NIBE_ID_THRESHOLD be increased from 10 to 14 as my Nibe F1245 has a 14 digit  Id number. 
Thanks
> [nibeuplink] Increase NIBE_ID_THRESHOLD

- addons/binding/org.openhab.binding.meteoblue/ESH-INF/i18n/meteoblue_fr.properties
> [meteoblue] Add french translation for the weather conditions

- addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/internal/PLCLogoBindingConstants.java
- addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/internal/PLCLogoClient.java
- addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/internal/config/PLCCommonConfiguration.java
- addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/internal/config/PLCDigitalConfiguration.java
- addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/internal/config/PLCLogoBridgeConfiguration.java
- addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/internal/config/PLCMemoryConfiguration.java
- addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/internal/config/PLCPulseConfiguration.java
- addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/internal/handler/PLCAnalogHandler.java
- addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/internal/handler/PLCBridgeHandler.java
- addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/internal/handler/PLCCommonHandler.java
- addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/internal/handler/PLCDateTimeHandler.java
- addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/internal/handler/PLCDigitalHandler.java
- addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/internal/handler/PLCMemoryHandler.java
- addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/internal/handler/PLCPulseHandler.java
Pulse thing had timing issues on slow networks. Additionally removed
Objects.requireNonNull calls. Consolidate constants.
Signed-off-by: Alexander Falkenstern <alexander.falkenstern@gmail.com>
> [plclogo] Fix some timing issues in Pulse thing 

- addons/binding/org.openhab.binding.deconz/ESH-INF/thing/thing-types.xml
- addons/binding/org.openhab.binding.deconz/README.md
- addons/binding/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/BindingConstants.java
- addons/binding/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/HandlerFactory.java
- addons/binding/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/discovery/ThingDiscoveryService.java
- addons/binding/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/dto/SensorState.java
- addons/binding/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/SensorThingHandler.java
- Added support for ZHAAlarm sensors and optional channel 'tampered'
Closes #4976 
> [deconz] Added support for ZHAAlarm sensors and optional channel 'tampered'

- addons/binding/org.openhab.binding.onkyo/README.md
- Added explanation about usage of callback URL
- Fixed spelling
- Fixed linter issues
Closes #2925
> [onkyo] Added explanation about usage of callback URL

- bundles/org.openhab.binding.dmx/README.md
- bundles/org.openhab.binding.dmx/src/main/java/org/openhab/binding/dmx/internal/DmxBridgeHandler.java
- bundles/org.openhab.binding.dmx/src/main/java/org/openhab/binding/dmx/internal/Util.java
- bundles/org.openhab.binding.dmx/src/main/java/org/openhab/binding/dmx/internal/ValueSet.java
- bundles/org.openhab.binding.dmx/src/main/java/org/openhab/binding/dmx/internal/handler/ChaserThingHandler.java
- bundles/org.openhab.binding.dmx/src/test/java/org/openhab/binding/dmx/internal/ValueSetTest.java
Requested in the community forum: support full chaser configuration in rule action.
> [dmx] Extend action to full chasers

- bundles/org.openhab.io.mqttembeddedbroker/pom.xml
* Fix alignment in pom.xml
* Use latest h2-mvstore for testing
> [embeddedbroker] Use latest h2-mvstore for testing

- poms/bnd/pom.xml
- tools/checkstyle/ruleset.properties
- tools/checkstyle/suppressions.xml
> enable SAT for bindings using BND build

- addons/binding/org.openhab.binding.nanoleaf/ESH-INF/thing/lightpanels.xml
- addons/binding/org.openhab.binding.yeelight/ESH-INF/config/config.xml
- addons/binding/org.openhab.binding.yeelight/ESH-INF/thing/ct_bulb.xml
Fixes the build when all projects are build with SAT 0.6.1.
> Fix SAT 0.6.1 tab indentation errors

- .gitignore
We already ignore the "old" IntelliJ project files (*.iml). Ignore the new ones, too.
Signed-off-by: Hakan Tandogan <hakan@tandogan.com>
Signed-off-by: Hakan Tandogan <hakan@tandogan.com> (github: hakan42)
> [intellij] Ignore project metadata for IntelliJ Idea

- features/karaf/openhab-addons/src/main/feature/feature.xml
Add "netty-codec-mqtt"
Fixes #5282 
> [mqtt embedded broker] karaf feature fix

- features/karaf/openhab-addons/src/main/feature/feature.xml
Change start levels according to dependency chain.
Might fix #5259 
> [mqtt] karaf start levels for mqtt

- bundles/org.openhab.binding.mqtt/.project
> [mqtt] Fixed projekt name

- bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/config/AVMFritzConfiguration.java
- bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/hardware/FritzAhaContentExchange.java
- bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/hardware/FritzAhaWebInterface.java
- Reset session id before trying to reconnect
- Do not log password anymore
Fixes #4558 
> [avmfritz] Reset session id before trying to reconnect

- addons/binding/org.openhab.binding.mcp23017/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.mcp23017/src/main/java/org/openhab/binding/mcp23017/internal/Mcp23017BindingConstants.java
- addons/binding/org.openhab.binding.mcp23017/src/main/java/org/openhab/binding/mcp23017/internal/Mcp23017HandlerFactory.java
Also changed these lists to sets as they're only used to check if a value is part of the list. So makes more sense to use a set.
> [mcp23017] Removed dependency on google guava library.

- CODEOWNERS
Looks like I still had to resolve this merge conflict. :relaxed:
> Resolve CODEOWNERS merge conflict

- bundles/org.openhab.binding.mqtt.generic/pom.xml
> [mqtt.generic] pom.xml fix

- bundles/org.openhab.binding.mqtt.homie/pom.xml
> [mqtt.homie] pom fix

- bundles/org.openhab.binding.mqtt.homeassistant/pom.xml
> [mqtt.homeassitant] pom fix

- bundles/org.openhab.binding.mqtt.homeassistant/src/main/resources/ESH-INF/binding/binding.xml
Only the master bundle may have a binding.xml file
> [mqtt] Remove binding.xml of sub-bundle

- bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/LifxLightStateChanger.java
> [lifx] Improved error message

- addons/binding/org.openhab.binding.ihc.test/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.ihc.test/src/test/java/org/openhab/binding/ihc/internal/converters/DecimalTypeWSBooleanValueConverterTest.java
- addons/binding/org.openhab.binding.ihc.test/src/test/java/org/openhab/binding/ihc/internal/converters/DecimalTypeWSEnumValueConverterTest.java
- addons/binding/org.openhab.binding.ihc.test/src/test/java/org/openhab/binding/ihc/internal/converters/DecimalTypeWSFloatingPointValueConverterTest.java
- addons/binding/org.openhab.binding.ihc.test/src/test/java/org/openhab/binding/ihc/internal/converters/DecimalTypeWSIntegerValueConverterTest.java
- addons/binding/org.openhab.binding.ihc.test/src/test/java/org/openhab/binding/ihc/internal/converters/DecimalTypeWSTimerValueConverterTest.java
- addons/binding/org.openhab.binding.ihc.test/src/test/java/org/openhab/binding/ihc/internal/converters/DecimalTypeWSWeekdayValueConverterTest.java
- addons/binding/org.openhab.binding.ihc.test/src/test/java/org/openhab/binding/ihc/internal/converters/OnOffTypeWSBooleanValueConverterTest.java
- addons/binding/org.openhab.binding.ihc.test/src/test/java/org/openhab/binding/ihc/internal/converters/OnOffTypeWSIntegerValueConverterTest.java
- addons/binding/org.openhab.binding.ihc.test/src/test/java/org/openhab/binding/ihc/internal/converters/OpenClosedTypeWSBooleanValueConverterTest.java
- addons/binding/org.openhab.binding.ihc.test/src/test/java/org/openhab/binding/ihc/internal/converters/OpenClosedTypeWSIntegerValueConverterTest.java
- addons/binding/org.openhab.binding.ihc.test/src/test/java/org/openhab/binding/ihc/internal/converters/PercentTypeWSIntegerValueConverterTest.java
- addons/binding/org.openhab.binding.ihc.test/src/test/java/org/openhab/binding/ihc/internal/converters/StringTypeWSEnumValueConverterTest.java
- addons/binding/org.openhab.binding.ihc.test/src/test/java/org/openhab/binding/ihc/internal/converters/UpDownTypeWSBooleanValueConverterTest.java
- addons/binding/org.openhab.binding.ihc.test/src/test/java/org/openhab/binding/ihc/internal/converters/UpDownTypeWSIntegerValueConverterTest.java
- addons/binding/org.openhab.binding.ihc/ESH-INF/thing/channels.xml
- addons/binding/org.openhab.binding.ihc/META-INF/MANIFEST.MF
- addons/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/IhcBindingConstants.java
- addons/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/config/ChannelParams.java
- addons/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/converters/ConverterAdditionalInfo.java
- addons/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/converters/OnOffTypeWSIntegerValueConverter.java
- addons/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/handler/IhcHandler.java
- addons/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/ws/IhcClient.java
Also couple of improvements to error handling.
> [ihc] Introduced onLevel channel parameter to dimmer channel

- bundles/org.openhab.binding.denonmarantz/pom.xml
- bundles/org.openhab.binding.dlinksmarthome/pom.xml
- bundles/org.openhab.binding.tellstick/pom.xml
- features/karaf/openhab-addons/src/main/feature/feature.xml
> downgrade jaxb/jaxws to 2.2

- bundles/org.openhab.binding.digiplex/src/main/resources/ESH-INF/binding/binding.xml
- bundles/org.openhab.binding.digiplex/src/main/resources/ESH-INF/thing/area.xml
- bundles/org.openhab.binding.digiplex/src/main/resources/ESH-INF/thing/bridge.xml
- bundles/org.openhab.binding.digiplex/src/main/resources/ESH-INF/thing/zone.xml
> [digiplex] xml formatting (#5422)

- bundles/org.openhab.binding.netatmo/pom.xml
add missing scope and fix formatting
> [netatmo] fix pom.xml

- bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/discovery/ThingDiscoveryService.java
- bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/internal/DigiplexHandlerFactory.java
- bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/internal/discovery/DigiplexDiscoveryService.java
- bundles/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/discovery/ZoneDiscoveryService.java
- bundles/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/handler/YamahaBridgeHandler.java
- bundles/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/handler/YamahaZoneThingHandler.java
- Fixed discovery services based on 'ThingHandlerService'
See https://github.com/openhab/openhab-core/pull/709#issuecomment-481726321
> Fixed discovery services based on 'ThingHandlerService'

- bundles/org.openhab.binding.digiplex/src/main/resources/ESH-INF/binding/binding.xml
- bundles/org.openhab.binding.digiplex/src/main/resources/ESH-INF/thing/area.xml
- bundles/org.openhab.binding.digiplex/src/main/resources/ESH-INF/thing/bridge.xml
- bundles/org.openhab.binding.digiplex/src/main/resources/ESH-INF/thing/zone.xml
- bundles/org.openhab.binding.onewire/src/main/resources/ESH-INF/thing/bae09x.xml
- bundles/org.openhab.binding.synopanalyzer/src/main/resources/ESH-INF/binding/binding.xml
- bundles/org.openhab.binding.synopanalyzer/src/main/resources/ESH-INF/thing/thing-types.xml
- bundles/org.openhab.binding.xmppclient/src/main/resources/ESH-INF/binding/binding.xml
- bundles/org.openhab.binding.xmppclient/src/main/resources/ESH-INF/thing/thing-types.xml
- bundles/pom.xml
- features/karaf/openhab-addons/src/main/feature/feature.xml
1. Removed 'hidden' U+FEFF first character in feature.xml
1. Changed project tag in bundle pom to 1 line. When generating a new binding with the script. The script modifies the bundle pom to add the new binding. However it rewrites the script and puts the project tag on a single line. This always shows up as a changes and users committing are always ask to undo this. By having it on a single line this will not be a problem anymore.
1. Fixed old schema locations in xml files. Schema changed from eclipse to openHAB.
> Some small clean up changes

- bundles/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/discovery/AtlonaDiscovery.java
- bundles/org.openhab.binding.globalcache/src/main/java/org/openhab/binding/globalcache/internal/handler/GlobalCacheHandler.java
- bundles/org.openhab.binding.minecraft/src/main/java/org/openhab/binding/minecraft/internal/handler/MinecraftPlayerHandler.java
- bundles/org.openhab.binding.minecraft/src/main/java/org/openhab/binding/minecraft/internal/handler/MinecraftSignHandler.java
- bundles/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/handler/NestBaseHandler.java
- bundles/org.openhab.binding.silvercrestwifisocket/src/main/java/org/openhab/binding/silvercrestwifisocket/internal/handler/SilvercrestWifiSocketHandler.java
- bundles/org.openhab.binding.vitotronic/src/main/java/org/openhab/binding/vitotronic/internal/handler/VitotronicThingHandler.java
- bundles/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/internal/servletservices/NeeoBrainService.java
> Added missing logger args

- addons/io/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudService.java
- bundles/org.openhab.binding.coolmasternet/src/main/java/org/openhab/binding/coolmasternet/internal/ControllerHandler.java
- bundles/org.openhab.binding.harmonyhub/src/main/java/org/openhab/binding/harmonyhub/internal/discovery/HarmonyHubDiscoveryService.java
- bundles/org.openhab.binding.hyperion/src/main/java/org/openhab/binding/hyperion/internal/connection/JsonTcpConnection.java
- bundles/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/connection/AbstractJeeLinkConnection.java
- bundles/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/connection/JeeLinkSerialConnection.java
- bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxServerHandler.java
- bundles/org.openhab.binding.wifiled/src/main/java/org/openhab/binding/wifiled/internal/handler/AbstractWiFiLEDDriver.java
> Fixed potential resource leaks

- CODEOWNERS
- bom/openhab-addons/pom.xml
- bundles/org.openhab.binding.mail/.classpath
- bundles/org.openhab.binding.mail/.project
- bundles/org.openhab.binding.mail/.settings/org.eclipse.core.resources.prefs
- bundles/org.openhab.binding.mail/.settings/org.eclipse.m2e.core.prefs
- bundles/org.openhab.binding.mail/NOTICE
- bundles/org.openhab.binding.mail/README.md
- bundles/org.openhab.binding.mail/pom.xml
- bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/action/SendMailActions.java
- bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/internal/MailBindingConstants.java
- bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/internal/MailBuilder.java
- bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/internal/MailCountChannelType.java
- bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/internal/MailHandlerFactory.java
- bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/internal/POP3IMAPHandler.java
- bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/internal/SMTPHandler.java
- bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/internal/ServerSecurity.java
- bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/internal/config/BaseConfig.java
- bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/internal/config/POP3IMAPChannelConfig.java
- bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/internal/config/POP3IMAPConfig.java
- bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/internal/config/SMTPConfig.java
- bundles/org.openhab.binding.mail/src/main/resources/ESH-INF/binding/binding.xml
- bundles/org.openhab.binding.mail/src/main/resources/ESH-INF/i18n/mail_de_DE.properties
- bundles/org.openhab.binding.mail/src/main/resources/ESH-INF/thing/thing-types.xml
- bundles/org.openhab.binding.mail/src/test/java/org/openhab/binding/mail/MailBuilderTest.java
- bundles/pom.xml
- features/karaf/openhab-addons/src/main/feature/feature.xml
Solves #4915 
This implements email
> [mail] Email Binding initial contribution

- CODEOWNERS
Somebodies clearly didn't use automated migrations :smile:
> Clean up CODEOWNERS for missed migration changes.

- bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/statedescription/AmazonEchoDynamicStateDescriptionProvider.java
Introduced by https://github.com/openhab/openhab-core/pull/655
> [amazonechocontrol] Fix nullerrors

- bundles/org.openhab.io.openhabcloud/README.md
Signed-off-by: Yannick Schaus <github@schaus.net>
> [openhabcloud] Fix image link

- bundles/org.openhab.binding.darksky/README.md
- bundles/org.openhab.binding.darksky/src/main/resources/ESH-INF/thing/channel-types.xml
- Minor tweak for `sunrise-event`
> [darksky] Minor tweak for 'sunrise-event'

- CODEOWNERS
- bom/openhab-addons/pom.xml
- bundles/org.openhab.binding.buienradar/.classpath
- bundles/org.openhab.binding.buienradar/.project
- bundles/org.openhab.binding.buienradar/.settings/org.eclipse.core.resources.prefs
- bundles/org.openhab.binding.buienradar/.settings/org.eclipse.m2e.core.prefs
- bundles/org.openhab.binding.buienradar/NOTICE
- bundles/org.openhab.binding.buienradar/README.md
- bundles/org.openhab.binding.buienradar/pom.xml
- bundles/org.openhab.binding.buienradar/src/main/java/org/openhab/binding/buienradar/internal/BuienradarBindingConstants.java
- bundles/org.openhab.binding.buienradar/src/main/java/org/openhab/binding/buienradar/internal/BuienradarConfiguration.java
- bundles/org.openhab.binding.buienradar/src/main/java/org/openhab/binding/buienradar/internal/BuienradarHandler.java
- bundles/org.openhab.binding.buienradar/src/main/java/org/openhab/binding/buienradar/internal/BuienradarHandlerFactory.java
- bundles/org.openhab.binding.buienradar/src/main/java/org/openhab/binding/buienradar/internal/buienradarapi/BuienradarParseException.java
- bundles/org.openhab.binding.buienradar/src/main/java/org/openhab/binding/buienradar/internal/buienradarapi/BuienradarPredictionAPI.java
- bundles/org.openhab.binding.buienradar/src/main/java/org/openhab/binding/buienradar/internal/buienradarapi/Prediction.java
- bundles/org.openhab.binding.buienradar/src/main/java/org/openhab/binding/buienradar/internal/buienradarapi/PredictionAPI.java
- bundles/org.openhab.binding.buienradar/src/main/resources/ESH-INF/binding/binding.xml
- bundles/org.openhab.binding.buienradar/src/main/resources/ESH-INF/thing/thing-types.xml
- bundles/org.openhab.binding.buienradar/src/test/java/org/openhab/binding/buienradar/BuienradarPredictionAPITest.java
- bundles/pom.xml
- features/karaf/openhab-addons/src/main/feature/feature.xml
Hi, this is the initial commit for the buienradar binding. Buienradar is a Dutch/Belgian website which uses radar information to get precipitation information and predictions. This binding simply polls the API every 5 minutes to retrieve current and predicted situations. This can be used to control sprinklers or advice on windows which are inadvertently open during a storm.
> [buienradar] Buienradar Binding initial contribution

- bundles/org.openhab.binding.innogysmarthome/pom.xml
- bundles/org.openhab.binding.innogysmarthome/src/main/java/org/openhab/binding/innogysmarthome/internal/client/InnogyClient.java
- features/karaf/openhab-addons/src/main/feature/feature.xml
Problem reported and solution confirmed here: https://community.openhab.org/t/innogy-on-openhab-2-5-build-1577-throwing-exceptions/73282
> [innogysmarthome] fix dependencies

- bundles/org.openhab.binding.mail/README.md
> Correcting document (cf Issue #5531)

- bundles/org.openhab.binding.logreader/README.md
added another rules example
Signed-off-by: Holger Eisold holgereisold@gmx.de
> Update LogReader README

- README.md
> [readme] Remove addons directory reference

- features/karaf/openhab-addons/src/main/feature/feature.xml
Fixes: https://github.com/openhab/openhab2-addons/issues/5542
> feature: fix coordinates for ihc

- bundles/org.openhab.binding.modbus/src/test/java/org/openhab/binding/modbus/internal/ModbusDataHandlerTest.java
- bundles/org.openhab.extensionservice.marketplace.automation/src/main/java/org/openhab/extensionservice/marketplace/automation/internal/MarketplaceRuleTemplateProvider.java
- bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/rest/UserManagement.java
- bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/rest/CommonSetup.java
Related to: https://github.com/openhab/openhab-core/pull/787
Sorry about that.
> fix code for new storage service handling

- bundles/org.openhab.transform.jsonpath/src/main/java/org/openhab/transform/jsonpath/internal/JSonPathTransformationService.java
- bundles/org.openhab.transform.jsonpath/src/test/java/org/openhab/transform/jsonpath/internal/JSonPathTransformationServiceTest.java
Json path result can be list of Boolean, Number, String values
> [jsonpath] List support

- pom.xml
> Fixes #5416. Daily snapshot downloads only

- bundles/org.openhab.binding.tankerkoenig/README.md
Signed-off-by: Holger Eisold holgereisold@gmx.de
> [tankerkoenig] items example extended

- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/robot/FanModeType.java
- bundles/org.openhab.binding.miio/src/main/resources/ESH-INF/thing/vacuumThing.xml
additional fan levels support #4994
Fixes #4994
> [miio] add fan/mob levels for robo

- bundles/org.openhab.transform.scale/README.md
- bundles/org.openhab.transform.scale/conf/transform/scale/catchnonnumeric.scale
- bundles/org.openhab.transform.scale/conf/transform/scale/netatmo_aq.scale
- bundles/org.openhab.transform.scale/src/main/java/org/openhab/transform/scale/internal/ScaleTransformationService.java
- bundles/org.openhab.transform.scale/src/test/java/org/openhab/transform/scale/internal/ScaleTransformServiceTest.java
* Adding 'NaN' key to nicely take care of non numeric values presented to scale transform
* Adding the ability to format result presented with a format string provided in the .scale file.
* A bit of code cleansing
If this PR finds an agreement, I'll update Scale transformation documentation accordingly
>  [Scale transform] Enhancements

- bundles/org.openhab.binding.network/README.md
- bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/handler/NetworkHandler.java
- bundles/org.openhab.binding.network/src/main/resources/ESH-INF/thing/thing-types.xml
- bundles/org.openhab.binding.network/src/test/java/org/openhab/binding/network/internal/handler/NetworkHandlerTest.java
> Changing 'latency' channel to be UoM Number:Time

- bundles/org.openhab.binding.bluetooth.ruuvitag/.classpath
- bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/handler/KM200ThingHandler.java
- bundles/org.openhab.binding.lgwebos/.classpath
- pom.xml
related to https://github.com/openhab/openhab2-addons/issues/5005#issuecomment-490243096
> fixed issues that led to compilation errors in the IDE

- bundles/org.openhab.binding.xmppclient/pom.xml
- bundles/org.openhab.io.javasound/src/main/feature/feature.xml
- bundles/org.openhab.io.mqttembeddedbroker/pom.xml
- bundles/org.openhab.io.mqttembeddedbroker/src/main/feature/feature.xml
> Fix Jenkins builds

- bundles/org.openhab.extensionservice.marketplace.automation/pom.xml
- bundles/org.openhab.extensionservice.marketplace/pom.xml
- bundles/org.openhab.io.azureiothub/pom.xml
- bundles/org.openhab.io.homekit/pom.xml
- bundles/org.openhab.io.hueemulation/pom.xml
- bundles/org.openhab.io.imperihome/pom.xml
- bundles/org.openhab.io.javasound/pom.xml
- bundles/org.openhab.io.neeo/pom.xml
- bundles/org.openhab.io.openhabcloud/pom.xml
- bundles/org.openhab.io.transport.modbus/pom.xml
- bundles/org.openhab.io.webaudio/pom.xml
- bundles/org.openhab.persistence.mapdb/pom.xml
- bundles/org.openhab.transform.bin2json/pom.xml
- bundles/org.openhab.transform.exec/pom.xml
- bundles/org.openhab.transform.javascript/pom.xml
- bundles/org.openhab.transform.jinja/pom.xml
- bundles/org.openhab.transform.jsonpath/pom.xml
- bundles/org.openhab.transform.map/pom.xml
- bundles/org.openhab.transform.regex/pom.xml
- bundles/org.openhab.transform.scale/pom.xml
- bundles/org.openhab.transform.xpath/pom.xml
- bundles/org.openhab.transform.xslt/pom.xml
- bundles/org.openhab.voice.googletts/pom.xml
- bundles/org.openhab.voice.mactts/pom.xml
- bundles/org.openhab.voice.marytts/pom.xml
- bundles/org.openhab.voice.picotts/pom.xml
- bundles/org.openhab.voice.pollytts/pom.xml
- bundles/org.openhab.voice.voicerss/pom.xml
> Adjust bundle names

- bundles/org.openhab.binding.ftpupload/src/main/feature/feature.xml
- bundles/org.openhab.binding.groheondus/src/main/feature/feature.xml
- bundles/org.openhab.io.openhabcloud/src/main/feature/feature.xml
- bundles/org.openhab.voice.pollytts/src/main/feature/feature.xml
* Add missing wrapping URL parameters and feature prerequisites
* Remove unnecessary wrapping and feature prerequisites
I'va added a [comment to PR #5581](https://github.com/openhab/openhab2-addons/pull/5581#pullrequestreview-236373050) for some Homekit wrapping improvements.
> Improve bundle wrapping in Karaf features

- bundles/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromecastCommander.java
- Fixed `INCREASE`/`DECREASE` handling for volume
> [chromecast] Fixed INCREASE/DECREASE handling for volume

- bundles/org.openhab.binding.keba/README.md
- bundles/org.openhab.binding.keba/src/main/java/org/openhab/binding/keba/internal/KebaBindingConstants.java
- bundles/org.openhab.binding.keba/src/main/java/org/openhab/binding/keba/internal/handler/KeContactHandler.java
- bundles/org.openhab.binding.keba/src/main/resources/ESH-INF/thing/kecontact.xml
> [KEBA] Improvements on code formatting, labels and naming

- bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxServerHandler.java
- Revert changes from #5497
Fixed #5524 
Lesson learned: [closing the stream will close an associated socket](https://docs.oracle.com/javase/7/docs/api/java/net/Socket.html#getOutputStream()) too.
> [squeezebox] Revert changes from #5497

- bundles/org.openhab.binding.gpstracker/src/main/java/org/openhab/binding/gpstracker/internal/handler/TrackerHandler.java
- bundles/org.openhab.binding.gpstracker/src/main/java/org/openhab/binding/gpstracker/internal/message/LocationMessage.java
- bundles/org.openhab.binding.gpstracker/src/main/java/org/openhab/binding/gpstracker/internal/provider/AbstractCallbackServlet.java
> [Gpstracker] Small NPE protection

- bundles/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/handler/IhcHandler.java
> [ihc] clear last update time cache during disconnect

- bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/handler/SysteminfoHandler.java
> [SystemInfo] Small NPE catching

- bundles/org.openhab.binding.avmfritz/src/test/java/org/openhab/binding/avmfritz/internal/ahamodel/AVMFritzDeviceListModelTest.java
- bundles/org.openhab.binding.avmfritz/src/test/java/org/openhab/binding/avmfritz/internal/ahamodel/AVMFritzTemplateListModelTest.java
- Added unit tests for templates
> [avmfritz] Added unit tests for templates

- bundles/create_openhab_binding_skeleton.cmd
- bundles/create_openhab_binding_skeleton.sh
Related to https://github.com/openhab/openhab-core/pull/781
> [skeleton script] groupId has changed

- bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudClient.java
- bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudService.java
- Switched to shared Jetty `HttpClient` instance
> [openhabcloud] Switched to shared Jetty `HttpClient` instance

- bundles/org.openhab.binding.helios/src/main/java/org/openhab/binding/helios/internal/HeliosHandlerFactory.java
- bundles/org.openhab.binding.mcp23017/src/main/java/org/openhab/binding/mcp23017/internal/handler/Mcp23017Handler.java
- bundles/org.openhab.binding.meteoblue/src/main/java/org/openhab/binding/meteoblue/internal/handler/MeteoBlueHandler.java
- bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/AbstractMQTTThingHandler.java
- bundles/org.openhab.binding.yamahareceiver/src/test/java/org/openhab/binding/yamahareceiver/internal/protocol/XMLProtocolFactoryTest.java
- bundles/org.openhab.binding.yamahareceiver/src/test/java/org/openhab/binding/yamahareceiver/internal/protocol/xml/InputWithPresetControlXMLTest.java
- bundles/org.openhab.binding.yamahareceiver/src/test/java/org/openhab/binding/yamahareceiver/internal/protocol/xml/SystemControlXMLTest.java
These classes have unused imports so I've removed these unused imports to fix the warnings.
> Remove unused imports

- bundles/org.openhab.io.homekit/README.md
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitAccessoryType.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitChangeListener.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitCharacteristicType.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitTaggedItem.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitAccessoryFactory.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitThermostatImpl.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/IncompleteAccessoryException.java
> [homekit]  fix wrong group tag handling

- README.md
> [readme] Adapt to IDE setup guide

- bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudClient.java
- Do not set timeout globally
See https://github.com/openhab/openhab2-addons/pull/5612#pullrequestreview-239139437
> [openhabcloud] Do not set timeout globally

- bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/handler/OpenWeatherMapWeatherAndForecastHandler.java
- Prevent `IndexOutOfBoundsException`
```
2019-05-21 02:23:29.174 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:?]
at java.util.ArrayList.get(ArrayList.java:433) ~[?:?]
at org.openhab.binding.openweathermap.internal.handler.OpenWeatherMapWeatherAndForecastHandler.updateDailyForecastChannel(OpenWeatherMapWeatherAndForecastHandler.java:392) ~[?:?]
at org.openhab.binding.openweathermap.internal.handler.OpenWeatherMapWeatherAndForecastHandler.updateChannel(OpenWeatherMapWeatherAndForecastHandler.java:205) ~[?:?]
at org.openhab.binding.openweathermap.internal.handler.AbstractOpenWeatherMapHandler.updateChannels(AbstractOpenWeatherMapHan …
```
> [openweathermap] Prevent 'IndexOutOfBoundsException'

- bundles/org.openhab.voice.pollytts/pom.xml
- bundles/org.openhab.voice.pollytts/src/main/feature/feature.xml
> [pollytts] security fix

- bundles/org.openhab.binding.network/README.md
- bundles/org.openhab.binding.network/pom.xml
- bundles/org.openhab.binding.network/src/main/feature/feature.xml
- bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/NetworkBindingConstants.java
- bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/NetworkHandlerFactory.java
- bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/SpeedTestConfiguration.java
- bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/handler/SpeedTestHandler.java
- bundles/org.openhab.binding.network/src/main/resources/ESH-INF/thing/thing-types.xml
> [network] Adding speedtest

- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitChangeListener.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitImpl.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitSettings.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/AbstractTemperatureHomekitAccessoryImpl.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitThermostatImpl.java
> [homekit] better configuration handling

- bundles/org.openhab.binding.lgwebos/README.md
- bundles/org.openhab.binding.neato/README.md
- bundles/org.openhab.binding.neeo/README.md
- bundles/org.openhab.binding.pentair/README.md
- bundles/org.openhab.binding.rotelra1x/README.md
- bundles/org.openhab.binding.volvooncall/README.md
- bundles/org.openhab.binding.wemo/README.md
Some tables in the documentation don't render properly on GitHub or are broken (Pentair).
> Fix broken Markdown tables

- bundles/org.openhab.io.homekit/README.md
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitAccessoryRegistry.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitChangeListener.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitImpl.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitSettings.java
Sorry for that. Introduced with #5637 
> [homekit] fix NPE on config change

- bundles/org.openhab.binding.dsmr/README.md
> [dsmr] Fix electricity channels in items example

- bundles/org.openhab.binding.mail/README.md
- Changed wrong parameter for `mailcount` ChannelType from `name` to `folder`
- Added note about how to observe sub directories
- Minor tweaks
> [mail] Added note about how to observe sub directories

- bundles/org.openhab.binding.mail/src/main/resources/ESH-INF/i18n/mail_de_DE.properties
- Updated and fixed translations
Some are missing. I will add them to this PR.
> [mail] Updated and fixed translations

- bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/ChannelStateTests.java
Some cleanups & made test independent of time zones
Closes #5406
> [mqtt] ChannelStateTests.java

- bundles/org.openhab.binding.evohome/README.md
> [evohome] Amend typo in display supported values on README

- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoDevices.java
Support the new Roborock S6 vacuum robot. Works fine with my new device. 🤖
> [miio] Add support for Roborock S6

- bundles/org.openhab.transform.scale/README.md
> [transform.scale] Update README.md

- bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/AbstractComponent.java
- bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/discovery/HomeAssistantDiscovery.java
Working on zigbee2mqtt support.
New thingID needs to include nodeId.
Replace invalid char sequences in unique_id with underscore.
> [mqtt][mqtt.homeassistant] #5632 Homeassistant improvements

- bundles/org.openhab.io.homekit/README.md
> [homekit] update documentation

- bundles/org.openhab.binding.deconz/README.md
- Fixed rule with Channel trigger example
> [deconz] Fixed rule with Channel trigger example

- bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/SafeExposureConfiguration.java
- bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/handler/OpenUVBridgeHandler.java
- bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/handler/OpenUVReportHandler.java
- bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/json/SafeExposureTime.java
> [OpenUV] Correcting a NPE when SafeExposure not being provided by API

- bundles/org.openhab.binding.avmfritz/src/main/feature/feature.xml
- bundles/org.openhab.binding.denonmarantz/src/main/feature/feature.xml
- bundles/org.openhab.binding.dlinksmarthome/src/main/feature/feature.xml
- bundles/org.openhab.binding.lgwebos/src/main/feature/feature.xml
- bundles/org.openhab.binding.netatmo/src/main/feature/feature.xml
- bundles/org.openhab.binding.tellstick/src/main/feature/feature.xml
- bundles/org.openhab.binding.xmltv/src/main/feature/feature.xml
- bundles/org.openhab.io.mqttembeddedbroker/src/main/feature/feature.xml
- bundles/org.openhab.io.openhabcloud/src/main/feature/feature.xml
remove unnecessary wrappings and replace wrappings with apache service-mix
> unwrap some features

- .gitignore
Adds VSCode files to gitignore
> 5693 - VSCode/gitignore

- bundles/org.openhab.binding.knx/README.md
[knx] Documentation: simplify Bridge and Thing configuration
Simplification and more concrete information on Bridge and Thing configuration.
https://github.com/openhab/openhab2-addons/issues/5281#issuecomment-498284324
Signed-off-by: lewie helmut.lehmeyer@gmail.com
> [knx] Docu: simplify Bridge and Thing configuration

- bundles/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/connection/JeeLinkSerialConnection.java
This fixes the Jeelink serial connection after changes commited in #5497.
> [jeelink] fix serial connection

- bundles/org.openhab.binding.dmx/README.md
Updated Type-ID colortemperature to its correct value color_temperature
> [dmx] fix documentation typo

- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/AbstractKNXClient.java
- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/config/BridgeConfiguration.java
- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/IPBridgeThingHandler.java
- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/SerialBridgeThingHandler.java
- bundles/org.openhab.binding.knx/src/main/resources/ESH-INF/thing/ip.xml
> [knx] improve connection handling on reconnect

- bundles/org.openhab.binding.onkyo/README.md
- bundles/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/OnkyoBindingConstants.java
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/ht-rc560.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/onkyoAVR.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr3007.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr414.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr474.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr509.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr515.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr525.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr535.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr545.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr555.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr575.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr575e.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr616.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr626.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr636.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr646.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr656.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr676.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr686.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr708.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr717.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr727.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr737.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr747.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr818.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr828.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr838.xml
I have an old TX-NR3007 which gets detected as "Unsupported", so this adds support.
It is not tested yet as it's currently building, but I will test locally and update this PR when things are working.
First foray into java - this will be fun!
> [onkyo] Add support for TX-NR3007

- bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/SamsungTvTlsTrustManagerProvider.java
- bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/WakeOnLanUtility.java
- bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/discovery/SamsungTvDiscoveryParticipant.java
- bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/handler/SamsungTvHandler.java
- bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/protocol/RemoteControllerWebSocket.java
- bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/protocol/WebSocketBase.java
- bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/protocol/WebSocketRemote.java
- bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/service/MainTVServerService.java
- bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/service/MediaRendererService.java
- bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/service/RemoteControllerService.java
- bundles/org.openhab.binding.samsungtv/src/main/resources/ESH-INF/config/config.xml
Bugfix for minor bugs introduced in #4169: reported in issue #5737:
- Protocol & port were not properly stored due to wrong config.xml.
- Thing put offline during service creation
Additional minor changes: 
- Corrected and added some debug and trace level logging
Not changed:
- I have not changed to the TrustAllTrustMananger built into OH2.5: 1) I still use OH 2.4 for my production and test environment; 2) I prefer to have the additional logging in to be able to resolve issues of other users
The built jar file can be found at:
https://drive.google.com/open?id=1BAg5Xs1UtuZi61p5FpXjVJGWV31-HLK8
> [samsungtv] Fix minor bugs introduced with #4169

- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/ht-rc560.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/onkyoAVR.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr414.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr474.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr509.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr515.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr525.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr535.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr545.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr555.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr575.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr575e.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr616.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr626.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr636.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr646.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr656.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr676.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr686.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr708.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr717.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr727.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr737.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr747.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr818.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr828.xml
- bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr838.xml
> [onkyo] fix missing closing tag 

- bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/device/BulbDevice.java
- bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/device/DimmerDevice.java
- bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/device/EnergySwitchDevice.java
- bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/device/RangeExtenderDevice.java
- bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/device/SmartHomeDevice.java
- bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/device/SwitchDevice.java
- bundles/org.openhab.binding.tplinksmarthome/src/test/java/org/openhab/binding/tplinksmarthome/internal/PropertiesCollectorTest.java
- bundles/org.openhab.binding.tplinksmarthome/src/test/java/org/openhab/binding/tplinksmarthome/internal/device/DeviceTestBase.java
- bundles/org.openhab.binding.tplinksmarthome/src/test/java/org/openhab/binding/tplinksmarthome/internal/device/EnergySwitchDeviceTest.java
- bundles/org.openhab.binding.tplinksmarthome/src/test/java/org/openhab/binding/tplinksmarthome/internal/handler/SmartHomeHandlerTest.java
Follow up on review comment in https://github.com/openhab/openhab2-addons/pull/5716#discussion_r298109245
> [tplinksmarthome] Remove protected fields from methods

- bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/SatelHandlerFactory.java
- bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/handler/IntRSBridgeHandler.java
- bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/protocol/IntRSModule.java
- bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/protocol/SatelModule.java
This PR removes dependency to gnu.io and migrates the code to use ESH serial API.
> [Satel] Migration to ESH serial API

- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/SomfyTahomaBindingConstants.java
- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/config/SomfyTahomaConfig.java
- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/discovery/SomfyTahomaItemDiscoveryService.java
- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaBaseThingHandler.java
- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaBridgeHandler.java
- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaWindowHandler.java
- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/model/SomfyTahomaLoginResponse.java
Improved binding robustness - introduces the recovery from "too many requests" error
> [somfytahoma] Added recovery from "too many requests" error

- bundles/org.openhab.binding.allplay/.classpath
- bundles/org.openhab.binding.bluetooth.bluez/.classpath
see: https://github.com/openhab/openhab-distro/issues/927
> fix wrong classpath

- bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/handler/KodiHandler.java
- bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/protocol/KodiClientSocket.java
- Changed message of ThingStatusInfo and reduced logging level
Closes #5755 
// CC: @openhab-5iver 
> [kodi] Changed massage of ThingStatusInfo and reduced logging level

- buildci.sh
Correctly detect the itest directory and also support changes in (only) itests
> Further ci improvements

- CODEOWNERS
- bom/openhab-addons/pom.xml
- bundles/org.openhab.binding.snmp/.classpath
- bundles/org.openhab.binding.snmp/.project
- bundles/org.openhab.binding.snmp/NOTICE
- bundles/org.openhab.binding.snmp/README.md
- bundles/org.openhab.binding.snmp/cfg/snmp.cfg
- bundles/org.openhab.binding.snmp/pom.xml
- bundles/org.openhab.binding.snmp/src/main/feature/feature.xml
- bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/SnmpBindingConstants.java
- bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/SnmpChannelMode.java
- bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/SnmpDatatype.java
- bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/SnmpHandlerFactory.java
- bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/SnmpProtocolVersion.java
- bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/SnmpService.java
- bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/SnmpServiceImpl.java
- bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/SnmpTargetHandler.java
- bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/config/SnmpChannelConfiguration.java
- bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/config/SnmpInternalChannelConfiguration.java
- bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/config/SnmpServiceConfiguration.java
- bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/config/SnmpTargetConfiguration.java
- bundles/org.openhab.binding.snmp/src/main/resources/ESH-INF/binding/binding.xml
- bundles/org.openhab.binding.snmp/src/main/resources/ESH-INF/thing/thing-types.xml
- bundles/org.openhab.binding.snmp/src/test/java/org/openhab/binding/snmp/internal/SnmpTargetHandlerTest.java
- bundles/pom.xml
> [snmp] SNMP Binding initial contribution

- bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/ICloudConnection.java
- bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/discovery/ICloudDeviceDiscovery.java
- bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/handler/ICloudAccountBridgeHandler.java
- bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/handler/ICloudDeviceHandler.java
- bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/json/request/ICloudAccountDataRequest.java
- bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/utilities/ICloudTextTranslator.java
While there, removed redundant null check.
> [iCloud] Catching a NumberFormatException upon unexpected api answer.

- bundles/org.openhab.binding.somfytahoma/README.md
Signed-off-by: Hakan Tandogan <hakan@tandogan.com> (github: hakan42)
> [somfytahoma] fixed links to the manufacturer

- bundles/org.openhab.binding.darksky/README.md
- bundles/org.openhab.binding.darksky/src/main/java/org/openhab/binding/darksky/internal/DarkSkyBindingConstants.java
- bundles/org.openhab.binding.darksky/src/main/java/org/openhab/binding/darksky/internal/handler/DarkSkyWeatherAndForecastHandler.java
- bundles/org.openhab.binding.darksky/src/main/resources/ESH-INF/i18n/darksky_de.properties
- bundles/org.openhab.binding.darksky/src/main/resources/ESH-INF/thing/channel-types.xml
- Added new channels for precipitation intensity and type
Dark Sky introduced an additional precipitation type ("sleet") which breaks my previous logic for the `rain` and `snow` channels.
> [darksky] Added new channels for precipitation intensity and type

- bundles/org.openhab.binding.airquality/README.md
- bundles/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/AirQualityBindingConstants.java
- bundles/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/handler/AirQualityHandler.java
- bundles/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/json/AirQualityJsonIaqi.java
- bundles/org.openhab.binding.airquality/src/main/resources/ESH-INF/thing/thing-types.xml
Channel Sulfur dioxide level (so2) added. Also documentation update
Signed-off-by: Meng Yiqi m17design@hotmail.com
> [airquality] Feature added: Sulfur dioxide level

- bundles/org.openhab.binding.rfxcom/README.md
- bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComLighting1Message.java
- bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComLighting5Message.java
- bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComRfyMessage.java
- bundles/org.openhab.binding.rfxcom/src/main/resources/ESH-INF/thing/lighting1.xml
- bundles/org.openhab.binding.rfxcom/src/main/resources/ESH-INF/thing/lighting5.xml
- bundles/org.openhab.binding.rfxcom/src/test/java/org/openhab/binding/rfxcom/internal/messages/RFXComLighting1MessageTest.java
- bundles/org.openhab.binding.rfxcom/src/test/java/org/openhab/binding/rfxcom/internal/messages/RFXComLighting5MessageTest.java
> [rfxcom] Added support for string-commands for Lighting-5 & Lighting-1

- bundles/org.openhab.binding.network/README.md
- Minor tweaks of documentation,  use dimension for items
The given example URL results in a Bad Request. Changing to "https" redirects to another target. Using that one now.
> [network] Minor tweaks of documentation

- bundles/org.openhab.binding.vektiva/pom.xml
- bundles/org.openhab.binding.vektiva/src/main/java/org/openhab/binding/vektiva/internal/VektivaHandlerFactory.java
- bundles/org.openhab.binding.vektiva/src/main/java/org/openhab/binding/vektiva/internal/config/VektivaSmarwiConfiguration.java
- bundles/org.openhab.binding.vektiva/src/main/java/org/openhab/binding/vektiva/internal/handler/VektivaSmarwiHandler.java
- bundles/org.openhab.binding.vektiva/src/main/resources/ESH-INF/thing/smarwi.xml
Implemented some code improvements based on @J-N-K 's review
https://github.com/openhab/openhab2-addons/pull/4626
> [vektiva] code improvements based on suggestions from review

- bundles/org.openhab.binding.lutron/README.md
- bundles/org.openhab.binding.lutron/src/main/resources/ESH-INF/binding/binding.xml
This PR contains an update to README.md which fixes some incorrect configuration examples, as well as some other minor doc improvements.  The problems with the examples have been causing confusion for users.
Regards,
Bob
> [lutron] Documentation update

- itests/org.openhab.binding.astro.tests/itest.bndrun
- itests/org.openhab.binding.avmfritz.tests/itest.bndrun
- itests/org.openhab.binding.feed.tests/itest.bndrun
- itests/org.openhab.binding.hue.tests/itest.bndrun
- itests/org.openhab.binding.max.tests/itest.bndrun
- itests/org.openhab.binding.mqtt.homeassistant.tests/itest.bndrun
- itests/org.openhab.binding.mqtt.homie.tests/itest.bndrun
- itests/org.openhab.binding.nest.tests/itest.bndrun
- itests/org.openhab.binding.ntp.tests/itest.bndrun
- itests/org.openhab.binding.systeminfo.tests/itest.bndrun
- itests/org.openhab.binding.tradfri.tests/itest.bndrun
- itests/org.openhab.binding.wemo.tests/itest.bndrun
- itests/org.openhab.io.hueemulation.tests/itest.bndrun
- itests/org.openhab.persistence.mapdb.tests/itest.bndrun
- Bump `tec.uom` libraries to latest version
Depends on https://github.com/openhab/openhab-core/pull/923
> [uom] Bump `tec.uom` libraries

- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/welcome/NAWelcomeCameraHandler.java
> [netatmo] Recompute VPN URL

- bundles/org.openhab.binding.bluetooth.bluegiga/src/main/java/org/openhab/binding/bluetooth/bluegiga/internal/factory/BlueGigaHandlerFactory.java
- bundles/org.openhab.binding.bosesoundtouch/src/main/java/org/openhab/binding/bosesoundtouch/internal/BoseSoundTouchHandlerFactory.java
- bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/DaikinHandlerFactory.java
- bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/internal/DigiplexHandlerFactory.java
- bundles/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/EleroTransmitterStickHandlerFactory.java
- bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/EnOceanHandlerFactory.java
- bundles/org.openhab.binding.harmonyhub/src/main/java/org/openhab/binding/harmonyhub/internal/HarmonyHubHandlerFactory.java
- bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/handler/HomematicThingHandlerFactory.java
- bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/KM200HandlerFactory.java
- bundles/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/LxHandlerFactory.java
- bundles/org.openhab.binding.meteoblue/src/main/java/org/openhab/binding/meteoblue/internal/MeteoBlueHandlerFactory.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoHandlerFactory.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/NetatmoHandlerFactory.java
- bundles/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/OwHandlerFactory.java
- bundles/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/internal/PLCLogoHandlerFactory.java
- bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/SnmpHandlerFactory.java
- bundles/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/SpotifyHandlerFactory.java
- bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/UniFiThingHandlerFactory.java
- bundles/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/internal/ZoneMinderHandlerFactory.java
Suppress "immediate = true"
Suppress configurationPolicy set to ConfigurationPolicy.OPTIONAL
Add configurationPid when missing
Fixes issue #5852
Signed-off-by: Laurent Garner <lg.hc@free.fr>
> ThingHandlerFactory: start on demand

- bundles/org.openhab.binding.groheondus/pom.xml
- bundles/org.openhab.binding.groheondus/src/main/feature/feature.xml
The dependency update of ondus-api removes the requirement of httpclient
and httpcomponents, which required commons-logging. This however, I
wasn't able in any way to get it working with openHAB locally. So this
is a workaround as we didn't manage to use 3rd party libraries in our
own framework infrastructure...
Fixes #5753
> [groheondus] Minimize dependency tree of grohe ondus

- bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/statedescription/AmazonEchoDynamicStateDescriptionProvider.java
- bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/AVMFritzDynamicStateDescriptionProvider.java
- bundles/org.openhab.binding.bosesoundtouch/src/main/java/org/openhab/binding/bosesoundtouch/internal/BoseStateDescriptionOptionProvider.java
- bundles/org.openhab.binding.hyperion/src/main/java/org/openhab/binding/hyperion/internal/HyperionStateDescriptionProvider.java
- bundles/org.openhab.binding.lametrictime/src/main/java/org/openhab/binding/lametrictime/internal/StateDescriptionOptionsProvider.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/NATherm1StateDescriptionProvider.java
- bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosStateDescriptionOptionProvider.java
- bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/SonyProjectorStateDescriptionOptionProvider.java
- bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/SqueezeBoxStateDescriptionOptionsProvider.java
- bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/handler/VehicleStateDescriptionProvider.java
> DynamicStateDescriptionProvider: don't use deprecated method

- bundles/org.openhab.binding.sonyprojector/src/main/resources/ESH-INF/binding/binding.xml
- bundles/org.openhab.binding.sonyprojector/src/main/resources/ESH-INF/i18n/sonyprojector_fr.properties
> [sonyprojector] Add french translation

- bundles/org.openhab.binding.avmfritz/src/main/feature/feature.xml
- bundles/org.openhab.binding.denonmarantz/pom.xml
- bundles/org.openhab.binding.denonmarantz/src/main/feature/feature.xml
- bundles/org.openhab.binding.dlinksmarthome/pom.xml
- bundles/org.openhab.binding.dlinksmarthome/src/main/feature/feature.xml
- bundles/org.openhab.binding.tellstick/pom.xml
- bundles/org.openhab.binding.tellstick/src/main/feature/feature.xml
- bundles/org.openhab.binding.xmltv/pom.xml
- bundles/org.openhab.binding.xmltv/src/main/feature/feature.xml
- Changed to openHAB Core feature of JAXB
> Changed to openHAB Core feature of JAXB

- bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/dto/Status.java
- bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/handler/VehicleHandler.java
> [VolvoOnCall] Correcting a potential NPE

- bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/internal/discovery/Homie300Discovery.java
> [mqtt] fix homie discovery (name)

- bundles/org.openhab.io.neeo/src/main/feature/feature.xml
> [neeo] re-add feature for neeo-io

- bundles/org.openhab.binding.darksky/README.md
- bundles/org.openhab.binding.darksky/src/main/java/org/openhab/binding/darksky/internal/DarkSkyBindingConstants.java
- bundles/org.openhab.binding.darksky/src/main/java/org/openhab/binding/darksky/internal/config/DarkSkyWeatherAndForecastConfiguration.java
- bundles/org.openhab.binding.darksky/src/main/java/org/openhab/binding/darksky/internal/factory/DarkSkyHandlerFactory.java
- bundles/org.openhab.binding.darksky/src/main/java/org/openhab/binding/darksky/internal/handler/DarkSkyWeatherAndForecastHandler.java
- bundles/org.openhab.binding.darksky/src/main/java/org/openhab/binding/darksky/internal/model/DarkSkyJsonWeatherData.java
- bundles/org.openhab.binding.darksky/src/main/resources/ESH-INF/config/config.xml
- bundles/org.openhab.binding.darksky/src/main/resources/ESH-INF/i18n/darksky.properties
- bundles/org.openhab.binding.darksky/src/main/resources/ESH-INF/i18n/darksky_de.properties
- bundles/org.openhab.binding.darksky/src/main/resources/ESH-INF/thing/channel-types.xml
- Added support for weather alerts
- Changed channel types for precipitation to `Number:Speed` / `MILLIMETRE_PER_HOUR` (API breaking)
- Minor code improvements
> [darksky] Added support for weather alerts

- bundles/org.openhab.binding.toon/src/main/resources/ESH-INF/thing/channels.xml
> [toon] Suppress useless state options

- bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/ChannelState.java
> [mqtt] apply transformation before output formatter

- bundles/org.openhab.binding.mqtt/README.md
> [mqtt] Add internal link to Moquette broker add-on in readme

- bundles/org.openhab.binding.ihc/src/test/java/org/openhab/binding/ihc/internal/ws/ResourceFileUtils.java
The tests fail on Windows when git checks out files using Windows line endings.
Fixes #5904
> [ihc] Fix tests failing on Windows

- bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/BindingConstants.java
- bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/discovery/ThingDiscoveryService.java
- bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/SensorThingHandler.java
- Added properties for sensors
This enhancement additionaly prevents automatically discovered things to show in the inbox if configured via textual files.
> [deconz] Added properties for sensors

- CODEOWNERS
- bundles/pom.xml
> [skeleton] Some fixes related to the skeleton script generation 

- bom/openhab-addons/pom.xml
- bundles/org.openhab.binding.paradoxalarm/src/main/feature/feature.xml
> [paradoxalarm] Added missing feature.xml

- bundles/org.openhab.binding.opensprinkler/README.md
- bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/OpenSprinklerBindingConstants.java
- bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/api/OpenSprinklerApi.java
- bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/api/OpenSprinklerGpioApi.java
- bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/api/OpenSprinklerHttpApiV100.java
- bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/handler/OpenSprinklerDeviceHandler.java
- bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/handler/OpenSprinklerStationHandler.java
- bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/model/StationProgram.java
- bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/util/Http.java
- bundles/org.openhab.binding.opensprinkler/src/main/resources/ESH-INF/thing/thing-types.xml
This PR builts on top of #5862, which is required to be merged before this one.
> [opensprinkler] Show remaining water time of a station

- bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/AbstractKNXClient.java
Fixes #5916 
Re-add null check (removed by mistake).
> [knx] re-add null check

- bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/SonyProjectorAspect.java
- bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/SonyProjectorCalibrationPreset.java
- bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/SonyProjectorColorSpace.java
- bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/SonyProjectorColorTemp.java
- bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/SonyProjectorConnector.java
- bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/SonyProjectorContrastEnhancer.java
- bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/SonyProjectorFilmMode.java
- bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/SonyProjectorFilmProjection.java
- bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/SonyProjectorGammaCorrection.java
- bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/SonyProjectorInput.java
- bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/SonyProjectorIrisMode.java
- bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/SonyProjectorMotionEnhancer.java
- bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/SonyProjectorMpegNr.java
- bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/SonyProjectorNr.java
- bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/SonyProjectorPicturePosition.java
- bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/sdcp/SonyProjectorSdcpConnector.java
- bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/serial/SonyProjectorSerialConnector.java
- bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/serial/SonyProjectorSerialOverIpConnector.java
- bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/handler/SonyProjectorHandler.java
> [sonyprojector] Remove code warnings

- bom/openhab-addons/pom.xml
- bundles/pom.xml
- features/openhab-addons/pom.xml
> [azureiot] remove temporarily

- CODEOWNERS
- bom/openhab-addons/pom.xml
- bundles/org.openhab.binding.linuxinput/.classpath
- bundles/org.openhab.binding.linuxinput/.project
- bundles/org.openhab.binding.linuxinput/NOTICE
- bundles/org.openhab.binding.linuxinput/README.md
- bundles/org.openhab.binding.linuxinput/pom.xml
- bundles/org.openhab.binding.linuxinput/src/main/feature/feature.xml
- bundles/org.openhab.binding.linuxinput/src/main/java/org/openhab/binding/linuxinput/internal/DeviceReadingHandler.java
- bundles/org.openhab.binding.linuxinput/src/main/java/org/openhab/binding/linuxinput/internal/LinuxInputBindingConstants.java
- bundles/org.openhab.binding.linuxinput/src/main/java/org/openhab/binding/linuxinput/internal/LinuxInputConfiguration.java
- bundles/org.openhab.binding.linuxinput/src/main/java/org/openhab/binding/linuxinput/internal/LinuxInputDiscoveryService.java
- bundles/org.openhab.binding.linuxinput/src/main/java/org/openhab/binding/linuxinput/internal/LinuxInputHandler.java
- bundles/org.openhab.binding.linuxinput/src/main/java/org/openhab/binding/linuxinput/internal/LinuxInputHandlerFactory.java
- bundles/org.openhab.binding.linuxinput/src/main/java/org/openhab/binding/linuxinput/internal/Utils.java
- bundles/org.openhab.binding.linuxinput/src/main/java/org/openhab/binding/linuxinput/internal/evdev4j/EvdevDevice.java
- bundles/org.openhab.binding.linuxinput/src/main/java/org/openhab/binding/linuxinput/internal/evdev4j/LastErrorException.java
- bundles/org.openhab.binding.linuxinput/src/main/java/org/openhab/binding/linuxinput/internal/evdev4j/Utils.java
- bundles/org.openhab.binding.linuxinput/src/main/java/org/openhab/binding/linuxinput/internal/evdev4j/jnr/EvdevLibrary.java
- bundles/org.openhab.binding.linuxinput/src/main/java/org/openhab/binding/linuxinput/internal/evdev4j/jnr/Utils.java
- bundles/org.openhab.binding.linuxinput/src/main/resources/ESH-INF/binding/binding.xml
- bundles/org.openhab.binding.linuxinput/src/main/resources/ESH-INF/thing/thing-types.xml
- bundles/pom.xml
Add a binding that allow openHAB/smarthome to read input events from
keyboards when running on a Linux system.
This can be used to utilize a keyboard as a remote with *many* buttons.
Previous discussions:
*  https://github.com/eclipse/smarthome/issues/6686
* https://community.openhab.org/t/binding-for-usb-input/58058
Signed-off-by: Thomas Weißschuh `<thomas@weissschuh.net>`
> [linuxinput] Linux Input Binding initial contribution

- bundles/org.openhab.transform.jsonpath/NOTICE
- bundles/org.openhab.transform.jsonpath/pom.xml
- bundles/org.openhab.transform.jsonpath/src/main/feature/feature.xml
- Updated dependency to latest version
We are using version 2.4.0 in OHC integration tests.
> [jsonpath] Updated dependency to latest version

- bundles/org.openhab.binding.sonyprojector/README.md
- bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/handler/SonyProjectorHandler.java
- bundles/org.openhab.binding.sonyprojector/src/main/resources/ESH-INF/thing/channels.xml
Signed-off-by : Laurent Garnier <lg.hc@free.fr>
> [sonyprojector] Few channels moved from Number to Dimmer item type

- bundles/org.openhab.binding.onebusaway/README.md
> Update to Bridge key "pugentsound" to "pugetsound"

- bundles/org.openhab.binding.groheondus/pom.xml
- bundles/org.openhab.binding.groheondus/src/main/feature/feature.xml
> Bump to new ondus-api version

- bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/handler/SonyProjectorHandler.java
> [sonyprojector] REFRESH channel handled through an ExpiringCache

- bundles/org.openhab.binding.daikin/README.md
- bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/DaikinBindingConstants.java
- bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/DaikinHandlerFactory.java
- bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/DaikinWebTargets.java
- bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/ControlInfo.java
- bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/Enums.java
- bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/airbase/AirbaseBasicInfo.java
- bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/airbase/AirbaseControlInfo.java
- bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/airbase/AirbaseEnums.java
- bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/airbase/AirbaseModelInfo.java
- bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/airbase/AirbaseZoneInfo.java
- bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/discovery/DaikinACUnitDiscoveryService.java
- bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/handler/DaikinAcUnitHandler.java
- bundles/org.openhab.binding.daikin/src/main/resources/ESH-INF/config/config.xml
- bundles/org.openhab.binding.daikin/src/main/resources/ESH-INF/thing/thing-types.xml
Signed-off-by: Paul Smedley <paul@smedley.id.au>
Add support for the BRP1B61 controller which uses a similar (but slightly) different API.
> [daikin] Support the BRP1B61 (aka Airbase) controller

- bundles/org.openhab.binding.network/README.md
Adressing [these observations](https://github.com/openhab/openhab2-addons/pull/5746#discussion_r315538156)
> [network] Documentation corrections

- features/openhab-addons/pom.xml
Silly me. Didn't commit the latest version.
> [infrastructure] fix azure iot hub removal

- bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/CoapCallback.java
- bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/TradfriCoapClient.java
- bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/TradfriCoapEndpoint.java
- bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/TradfriCoapHandler.java
- bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/TradfriColor.java
- bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/TradfriHandlerFactory.java
- bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/discovery/TradfriDiscoveryParticipant.java
- bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/discovery/TradfriDiscoveryService.java
- bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/handler/TradfriControllerHandler.java
- bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/handler/TradfriGatewayHandler.java
- bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/handler/TradfriLightHandler.java
- bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/handler/TradfriPlugHandler.java
- bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/handler/TradfriSensorHandler.java
- bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/handler/TradfriThingHandler.java
- bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/model/TradfriControllerData.java
- bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/model/TradfriDeviceData.java
- bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/model/TradfriLightData.java
- bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/model/TradfriPlugData.java
- bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/model/TradfriSensorData.java
- bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/model/TradfriWirelessDeviceData.java
> [tradfri] add null annotations and fix potential NPE

- bundles/org.openhab.binding.neohub/README.md
- bundles/org.openhab.binding.siemensrds/README.md
I noticed some syntax errors in the ReadMe files for my two recently published bindings
> [neohub] & [siemensrds] correction of syntax errors in Things file example

- bundles/org.openhab.binding.somfytahoma/README.md
Update the Readme.md of the SomfyTahoma Addon 
In the README.md there is missing the Config Parameter statusTimeout  of the Bridge in the Thing File
> [somfytahoma] Update README.md

- bundles/org.openhab.binding.snmp/README.md
- bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/SnmpTargetHandler.java
- bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/config/SnmpChannelConfiguration.java
- bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/config/SnmpInternalChannelConfiguration.java
- bundles/org.openhab.binding.snmp/src/main/resources/ESH-INF/thing/thing-types.xml
- bundles/org.openhab.binding.snmp/src/test/java/org/openhab/binding/snmp/internal/AbstractSnmpTargetHandlerTest.java
- bundles/org.openhab.binding.snmp/src/test/java/org/openhab/binding/snmp/internal/SnmpTargetHandlerTest.java
Behaviour in case of SNMP exceptions is now configurable.
> [snmp] better SNMP exception handling

- bundles/org.openhab.binding.samsungtv/README.md
Added UE43MU6199 to the list.
Signed-off-by: Udo Hartmann udo1toni@gmail.com
> [SamsungTV] Update README.md

- bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/model/StationProgram.java
> Fixed SAT errors in opensprinkler binding

- bundles/org.openhab.binding.siemensrds/src/main/java/org/openhab/binding/siemensrds/internal/RdsAccessToken.java
- bundles/org.openhab.binding.siemensrds/src/main/java/org/openhab/binding/siemensrds/internal/RdsDataPoints.java
- bundles/org.openhab.binding.siemensrds/src/main/java/org/openhab/binding/siemensrds/internal/RdsPlants.java
> [siemensrds] Fix SAT errors

- bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/KM200BindingConstants.java
- bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/KM200ThingType.java
- bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/handler/KM200ThingHandler.java
- bundles/org.openhab.binding.km200/src/main/resources/ESH-INF/thing/systemStates.xml
It's a small extenstion for a new system path called "systemStates". This feature is availible only on a specific hardware configuration and is tested by a user with this hardware.
> [km200] Added support for "systemStates"

- bundles/org.openhab.binding.chromecast/pom.xml
- bundles/org.openhab.binding.chromecast/src/main/feature/feature.xml
- Bump to new `su.litvak.chromecast` version
Resolves #5873
> [chromecast] Bump to new 'su.litvak.chromecast' version

- bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/handler/OpenWeatherMapWeatherAndForecastHandler.java
See also https://github.com/openhab/openhab2-addons/pull/5853/files#r318739461
> [openweathermap] Correcting null-handling

- bundles/org.openhab.binding.omnikinverter/README.md
Forgot one last thing for #4061; forgot to update the `README.md` wrt thing parameters which we renamed during the review process.
@wborn 
Signed-off-by: Hans van den Bogert <hansbogert@gmail.com>
> [omnikinverter] trivial:Fix thing parameters in README.md

- bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosBindingConstants.java
- bundles/org.openhab.binding.sonos/src/main/resources/ESH-INF/i18n/sonos_de.properties
- bundles/org.openhab.binding.sonos/src/main/resources/ESH-INF/i18n/sonos_fr.properties
- bundles/org.openhab.binding.sonos/src/main/resources/ESH-INF/thing/SYMFONISK.xml
> [sonos] Add discovery of IKEA SYMFONISK

- bundles/org.openhab.binding.omnikinverter/.project
- bundles/org.openhab.binding.omnikinverter/src/main/java/org/openhab/binding/omnikinverter/internal/OmnikInverter.java
- bundles/org.openhab.binding.omnikinverter/src/test/java/org/openhab/binding/omnikinverter/internal/test/OmnikInverterMessageTest.java
These are the minor improvements I saw after importing the binding in Eclipse @hansbogert.
> [omnikinverter] Add .project file, remove unused loggers

- bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/action/MQTTActions.java
- bundles/org.openhab.binding.mqtt/src/main/resources/ESH-INF/i18n/mqttbroker_de.properties
- bundles/org.openhab.binding.mqtt/src/main/resources/ESH-INF/i18n/mqttbroker_en.properties
> added retain parameter to action

- bundles/org.openhab.binding.boschindego/pom.xml
- bundles/org.openhab.binding.boschindego/src/main/feature/feature.xml
- bundles/org.openhab.binding.chromecast/src/main/feature/feature.xml
- bundles/org.openhab.binding.groheondus/src/main/feature/feature.xml
- bundles/org.openhab.transform.jinja/src/main/feature/feature.xml
- bundles/org.openhab.voice.pollytts/pom.xml
- bundles/org.openhab.voice.pollytts/src/main/feature/feature.xml
- Changed to openHAB Core feature of Jackson
Chromecast Binding (PR https://github.com/vitalidze/chromecast-java-api-v2/pull/115) and Grohe Ondus Binding (https://github.com/FlorianSW/grohe-ondus-api-java/pull/8) maybe will need another dependency update once the related PRs in their repositories will have been merged.
I am not sure what about Bosch Indego Binding. Currently the dependency `de.zazaz.iot.bosch.indego.bosch-indego-controller-lib` requires Jackson 2.7.3 but we are using 2.9.8. Is that the expected solution? Can we do that with others too (see above)?
Last but not least: I am working on Google Voice add-on too. I will submit a separate PR for it because the dependencies need a little bit more attention and I thinks we can get rid of Guava 20 (update to Guava 28-jre???) for it …
> Changed to openHAB Core feature of Jackson

- bundles/org.openhab.binding.mail/README.md
- bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/internal/MailBuilder.java
> [mail] properly handle UTF-8 content

- bundles/org.openhab.binding.bluetooth.ruuvitag/README.md
- bundles/org.openhab.binding.bluetooth.ruuvitag/src/main/java/org/openhab/binding/bluetooth/ruuvitag/internal/RuuviTagBindingConstants.java
- bundles/org.openhab.binding.bluetooth.ruuvitag/src/main/java/org/openhab/binding/bluetooth/ruuvitag/internal/RuuviTagDiscoveryParticipant.java
- bundles/org.openhab.binding.bluetooth.ruuvitag/src/main/java/org/openhab/binding/bluetooth/ruuvitag/internal/RuuviTagHandler.java
- bundles/org.openhab.binding.bluetooth.ruuvitag/src/main/java/org/openhab/binding/bluetooth/ruuvitag/internal/RuuviTagHandlerFactory.java
Note to reviewer. This pr also moves the `RuuviTagHandler` to an internal package. To best view the changes look at the second commit.
> [ruuvitag] Add a heartbeat to detect missing ruuvitags 

- bundles/org.openhab.binding.satel/README.md
- bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/SatelBindingConstants.java
- bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/SatelHandlerFactory.java
- bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/command/ReadZoneTemperature.java
- bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/config/Atd100Config.java
- bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/event/ZoneTemperatureEvent.java
- bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/handler/Atd100Handler.java
- bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/handler/SatelBridgeHandler.java
- bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/handler/SatelEventLogHandler.java
- bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/handler/SatelStateThingHandler.java
- bundles/org.openhab.binding.satel/src/main/resources/ESH-INF/thing/atd-100.xml
This PR adds support for ATD-100 wireless temperature sensor. It introduces new thing type for this purpose and extends the protocol by adding new command for reading temperature from the system.
Signed-off-by: Krzysztof Goworek krzysztof.goworek@gmail.com
> [satel] Added support for ATD-100 temperature sensor.

- bundles/org.openhab.binding.tplinksmarthome/README.md
- bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/PropertiesCollector.java
- bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/TPLinkSmartHomeBindingConstants.java
- bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/TPLinkSmartHomeDiscoveryService.java
- bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/TPLinkSmartHomeHandlerFactory.java
- bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/TPLinkSmartHomeThingType.java
- bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/device/BulbDevice.java
- bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/device/EnergySwitchDevice.java
- bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/handler/SmartHomeHandler.java
- bundles/org.openhab.binding.tplinksmarthome/src/main/resources/ESH-INF/thing/KB130.xml
- bundles/org.openhab.binding.tplinksmarthome/src/main/resources/ESH-INF/thing/KL120.xml
- bundles/org.openhab.binding.tplinksmarthome/src/main/resources/ESH-INF/thing/KL130.xml
- bundles/org.openhab.binding.tplinksmarthome/src/main/resources/ESH-INF/thing/LB120.xml
- bundles/org.openhab.binding.tplinksmarthome/src/main/resources/ESH-INF/thing/LB130.xml
- bundles/org.openhab.binding.tplinksmarthome/src/main/resources/ESH-INF/thing/LB230.xml
- bundles/org.openhab.binding.tplinksmarthome/src/main/resources/ESH-INF/thing/channels.xml
- bundles/org.openhab.binding.tplinksmarthome/src/test/java/org/openhab/binding/tplinksmarthome/internal/ChannelUIDConstants.java
- bundles/org.openhab.binding.tplinksmarthome/src/test/java/org/openhab/binding/tplinksmarthome/internal/PropertiesCollectorTest.java
- bundles/org.openhab.binding.tplinksmarthome/src/test/java/org/openhab/binding/tplinksmarthome/internal/TPLinkSmartHomeHandlerFactoryTest.java
- bundles/org.openhab.binding.tplinksmarthome/src/test/java/org/openhab/binding/tplinksmarthome/internal/device/BulbDeviceTest.java
- bundles/org.openhab.binding.tplinksmarthome/src/test/java/org/openhab/binding/tplinksmarthome/internal/device/EnergySwitchDeviceTest.java
- bundles/org.openhab.binding.tplinksmarthome/src/test/java/org/openhab/binding/tplinksmarthome/internal/device/PowerStripDeviceTest.java
- bundles/org.openhab.binding.tplinksmarthome/src/test/java/org/openhab/binding/tplinksmarthome/internal/handler/SmartHomeHandlerTest.java
- bundles/org.openhab.binding.tplinksmarthome/src/test/resources/org/openhab/binding/tplinksmarthome/internal/model/bulb_get_sysinfo_response_on.json
This change adds the following enhancements:
- Added color temperature channels in Kelvin.
- Refactored rssi and energy channels to use UoM.
- Added forced refresh for long refresh configuration times. Closes #5967 
The changes require the things to be recreated.
> [tplinksmarthome] Several enhancements

- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/IPBridgeHandler.java
This PR contains a fix for a recently reported problem experienced with Lutron Caseta Pro hubs.
Caseta apparently does not allow the prompt string to be disabled with a "#MONITORING,12,2" command, as other Lutron systems do. Worse yet, in some cases it seems to insert the prompt string into the middle of a response line, rather than at the beginning of it. For example, the bridge handler may receive the malformed response "~OUTPUT,41,1,GNET> 0.00" (where "GNET> " is the CLI prompt string) instead of the expected response "~OUTPUT,41,1,0.00".
The fix tightens up the regex pattern for recognizing good response lines, and adds a bit of code that attempts a prompt string removal in the case of bad response lines.  The trade-off is a bit more overhead for processing all responses, but not …
> [lutron] Fix malformed responses from Caseta by removing prompt string

- bundles/org.openhab.binding.denonmarantz/README.md
> [DenonMarantz] Some clean up and alignment with the template of the README

- itests/org.openhab.binding.mqtt.homeassistant.tests/itest.bndrun
- itests/org.openhab.binding.mqtt.homeassistant.tests/pom.xml
- itests/org.openhab.binding.mqtt.homeassistant.tests/src/main/java/org/openhab/binding/mqtt/EmbeddedBrokerTools.java
- itests/org.openhab.binding.mqtt.homeassistant.tests/src/main/java/org/openhab/binding/mqtt/HomeAssistantMQTTImplementationTest.java
> [mqtt][homeassistant] fix integration tests

- bundles/org.openhab.binding.sinope/README.md
- bundles/org.openhab.binding.sinope/pom.xml
Rename readme.md into README.md and fix it
> [sinope] Update name in pom.xml

- bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/handler/OpenWeatherMapWeatherAndForecastHandler.java
- bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/model/OpenWeatherMapJsonWeatherData.java
- Fixed NPE on visibility channel
> [openweathermap] Fixed NPE on visibility channel

- bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/transceiver/EnOceanTransceiver.java
Reverting the deletion of the exception handler from PR https://github.com/openhab/openhab2-addons/pull/5055/files#diff-908e2d5e982ae84f6e8ace8d3362e9a3.
See https://community.openhab.org/t/new-openhab2-enocean-binding/39917/694
It is used to catch all parsing exceptions, preventing the executing thread from collapsing.
Signed-off-by: Dominik Vorreiter <dominikkv@gmx.de>
> [enocean] Re-add exception handler

- bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/transceiver/EnOceanTransceiver.java
Related to https://github.com/openhab/openhab2-addons/pull/6050
> [Enocean] removed tabs

- bundles/org.openhab.binding.windcentrale/src/main/java/org/openhab/binding/windcentrale/internal/handler/WindcentraleHandler.java
See https://community.openhab.org/t/problem-with-windcentrale-binding/81841
> [windcentrale] Fix cast exception

- bundles/org.openhab.io.hueemulation/src/main/java/org/glassfish/jersey/servlet/init/JerseyServletContainerInitializer.java
- bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/HueEmulationService.java
- bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/rest/ConfigurationAccess.java
- bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/rest/LightsAndGroups.java
- bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/rest/Rules.java
- bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/rest/Scenes.java
- bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/rest/Schedules.java
- bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/rest/UserManagement.java
- bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/automation/RuleConditionHandlerTests.java
- bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/rest/LightsAndGroupsTests.java
- bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/rest/SensorTests.java
- bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/rest/UsersAndConfigTests.java
- bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/rest/mocks/DummyItemRegistry.java
- itests/org.openhab.io.hueemulation.tests/itest.bndrun
- itests/org.openhab.io.hueemulation.tests/logback.xml
- itests/org.openhab.io.hueemulation.tests/src/main/java/org/openhab/io/hueemulation/internal/HueEmulationServiceOSGiTest.java
Fixes #5907
The tricky part was to get the jupnp components to start. These require a configuration to be provided by the `ConfigurationAdmin`.
> [hueemulation] Fix integration tests and cleanup

- .travis.yml
- buildci.sh
- bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/rest/CommonSetup.java
- bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/upnp/UpnpTests.java
Since all tests in https://github.com/openhab/openhab2-addons/issues/5775 have been fixed, it should be possible to enable them with a full build.
> Enable tests with full Travis CI build

- bundles/org.openhab.binding.spotify/README.md
> [spotify] Fixed headline so that doc website renders it correctly

- bundles/org.openhab.binding.daikin/README.md
Without these new lines these tables aren't properly rendered on GitHub.
> [daikin] Fix tables not always properly rendered

- CODEOWNERS
> Fixed spelling of contributors name

- itests/org.openhab.binding.mqtt.homie.tests/src/main/java/org/openhab/binding/mqtt/HomieImplementationTest.java
> [mqtt][homie] increase wait time for slower machines in itest

- itests/org.openhab.binding.mqtt.homeassistant.tests/src/main/java/org/openhab/binding/mqtt/HomeAssistantMQTTImplementationTest.java
> [mqtt][homeassistant] make itest more robust

- bundles/org.openhab.binding.rfxcom/src/main/resources/ESH-INF/thing/fan_falmec.xml
Fix openhab/openhab-distro#970
> [rfxcom] Fix fan_falmec.xml

- bundles/org.openhab.binding.spotify/README.md
Corrected typo in items and sitemap
> [spotify] Fix typos in README.md

- CONTRIBUTING.md
> [documentation] Fix url to development ide docs

- bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/handler/ZonePlayerHandler.java
> [sonos] Fix notification playback for Beam/Playbar/Playbase when current input is TV

- bundles/org.openhab.binding.allplay/src/main/java/org/openhab/binding/allplay/internal/AllPlayHandlerFactory.java
- bundles/org.openhab.binding.allplay/src/main/java/org/openhab/binding/allplay/internal/handler/AllPlayHandler.java
- bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosHandlerFactory.java
- bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/handler/ZonePlayerHandler.java
- Use own service reference to `ThingRegistry`
Bindings should no longer use the property `thingRegistry` from `BaseThingHandler`. It is deprecated and will be removed in the future.
> Use own service reference to 'ThingRegistry'

- bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/handler/OpenWeatherMapUVIndexHandler.java
- bundles/org.openhab.binding.openweathermap/src/main/resources/ESH-INF/i18n/openweathermap_de.properties
- bundles/org.openhab.binding.openweathermap/src/main/resources/ESH-INF/i18n/openweathermap_fr.properties
- Added missing translation
- Fixed null-handling
> [openweathermap] Added missing translation

- bundles/org.openhab.binding.mqtt.generic/README.md
Added documentation for the new retained argument to the mqttPublish Action. 
Signed off by Rich Koshak <rlkoshak@gmail.com>
> [MQTT] Doc retained argument for Action

- bundles/org.openhab.binding.netatmo/README.md
modified the "Configure Things" section. update di URL and add instructions to retreive the device_id.
> [netatmo] Update README.md

- bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/connector/RFXComStreamReader.java
1. Fix IndexOutOfBoundsException if first read byte value (message len)
is 255.
2. Bridge state is updated if uncaught exception occurs.
3. Improved logging.
Hopefully fixes https://community.openhab.org/t/rfxcom-read-error-rfxcomstreamreader-connector-died-java-lang-indexoutofboundsexception/82624
> [rfxcom] Improved message receiving

- bundles/org.openhab.binding.nibeheatpump/src/main/java/org/openhab/binding/nibeheatpump/internal/config/NibeHeatPumpConfiguration.java
> [nibeheatpump] Fixed logging

- bundles/org.openhab.binding.enturno/.classpath
- bundles/org.openhab.binding.enturno/.project
> [enturno] Add missing Eclipse project files

- bundles/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/handler/Rego6xxHeatPumpHandler.java
- bundles/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/rego6xx/RegoRegisterMapper.java
Should fix #6101 and #6095.
Fix confirmed, removed WIP - please review - thx.
Signed-off-by: Boris Krivonog <boris.krivonog@gmail.com>
> [regoheatpump] fix - using unsigned 16 bit value for opertional hours

- bundles/pom.xml
- pom.xml
See: https://github.com/openhab/openhab-distro/issues/927#issuecomment-538716530
> fix lifecycle-mapping for m2e

- bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/internal/handler/HomieThingHandler.java
- bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/internal/homie300/Device.java
- bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/internal/homie300/Property.java
> [mqtt][homie] remove connection setting retain, add retain to channel

- bundles/org.openhab.binding.darksky/README.md
- bundles/org.openhab.binding.darksky/src/main/java/org/openhab/binding/darksky/internal/DarkSkyBindingConstants.java
- bundles/org.openhab.binding.darksky/src/main/java/org/openhab/binding/darksky/internal/handler/DarkSkyWeatherAndForecastHandler.java
- bundles/org.openhab.binding.darksky/src/main/resources/ESH-INF/i18n/darksky_de.properties
- bundles/org.openhab.binding.darksky/src/main/resources/ESH-INF/thing/channel-types.xml
- Added channels for apparent temperature
Closes #6159
> [darksky] Added channels for apparent temperature

- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueClient.java
> [hue] removed tabs from code

- bundles/org.openhab.binding.sinope/.classpath
> [sinope] Remove non-existing folder from class path

- bundles/org.openhab.binding.modbus/src/main/resources/ESH-INF/thing/bridge-serial.xml
> [modbus] Fixes swapped flowControl options text

- bundles/org.openhab.binding.homematic/README.md
The PR corrects and improves some formatting and updates links to eq3.
> [homematic] Documentation improvements

- bundles/org.openhab.binding.mail/README.md
Extend sendMail example with recipients list:
mailActions.sendMail("mail1@example.com, mail2@example.com", "Test subject", "This is the mail content.")
Note ',' delimiter. (';' does not work)
> [mail] add example to documentation

- bundles/org.openhab.binding.mail/README.md
> [mail] clarify recipient parameter in rule action

- bundles/org.openhab.binding.deconz/README.md
- bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/BindingConstants.java
- bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/HandlerFactory.java
- bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/discovery/BridgeDiscoveryParticipant.java
- bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/DeconzBridgeConfig.java
- bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/DeconzBridgeHandler.java
- bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/SensorThingHandler.java
- bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/netutils/AsyncHttpClient.java
- bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/netutils/WebSocketConnection.java
- bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/netutils/WebSocketValueUpdateListener.java
- bundles/org.openhab.binding.deconz/src/main/resources/ESH-INF/config/config.xml
- Added missing `config` parameter
- Added "password" context for `apikey` parameter
- Fixed SAT findings and warnings
- Added optional `httpPort` and websocket `port` parameter
Closes #6072 
Fixes #5691 
Fixes #5534 
Fixes #4525  
Test version: [org.openhab.binding.deconz](https://openhab.jfrog.io/openhab/libs-pullrequest-local/org/openhab/addons/bundles/org.openhab.binding.deconz/2.5.0-SNAPSHOT/org.openhab.binding.deconz-2.5.0-SNAPSHOT.jar)
~TODO: Add a note about the split of `host` parameter into `host` and `port` to [update.lst](https://github.com/openhab/openhab-distro/blob/master/distributions/openhab/src/main/resources/bin/update.lst).~ I built in a method to truncate the `port` from the `host` parameter.
> [deconz] Feature deconz improvements

- bundles/org.openhab.transform.jsonpath/src/main/feature/feature.xml
- Fixed wrong feature file
See https://community.openhab.org/t/snapshots-1715-1716-1717-1718-1719-1720-1721-restdocs-rest-api-errors/83371/19 and https://github.com/openhab/openhab2-addons/commit/b00c8cc5c3b7811bef1e9e268c2b228bdd69ed11#r35480350
> [jsonpath] Fixed wrong feature file

- bundles/org.openhab.transform.jsonpath/src/main/feature/feature.xml
This reverts commit e1b35eb843eb09df4bb2bf0d44d38a7b2904682c.
> Revert "[jsonpath] Fixed wrong features (#6217)"

- bundles/org.openhab.transform.jsonpath/pom.xml
- bundles/org.openhab.transform.jsonpath/src/main/feature/feature.xml
See https://github.com/openhab/openhab2-addons/pull/6217#issuecomment-541462625
> [jsonpath] remove bundle dependency on Jackson

- bundles/org.openhab.binding.nikobus/README.md
> [nikobus] adapted README to match the standard format

- bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/AbstractMQTTThingHandler.java
- bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/MqttChannelStateDescriptionProvider.java
- bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/MqttChannelTypeProvider.java
- bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/mapping/AbstractMqttAttributeClass.java
- bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/mapping/MQTTvalueTransform.java
- bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/mapping/SubscribeFieldToMQTTtopic.java
- bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/tools/ChildMap.java
> [mqtt] fix code-style issues in generic MQTT

- bundles/org.openhab.binding.freebox/README.md
> Fixed link to FB revolution

- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/discovery/HueBridgeNupnpDiscovery.java
- Fixed deprecated bridge discovery endpoint
See https://developers.meethue.com/news/:
> Effective July 1 2018 (nupnp) bridge discovery is supported by a new endpoint, which is https://discovery.meethue.com. The old endpoint  www.meethue.com/api/nupnp has been deprecated but remains available until July 1 2019.
Currently the old one is still working but who knows how long.
> [hue] Fixed deprecated bridge discovery endpoint

- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoHandler.java
Signed-off-by: Hans-Jörg Merk <hans-joerg.merk@t-online.de>
> [wemo] Fixes 5487 - devices change ports without notification

- bundles/org.openhab.io.mqttembeddedbroker/pom.xml
- bundles/org.openhab.io.mqttembeddedbroker/src/main/java/org/openhab/io/mqttembeddedbroker/internal/EmbeddedBrokerService.java
- bundles/org.openhab.io.mqttembeddedbroker/src/test/java/org/openhab/io/mqttembeddedbroker/internal/MqttEmbeddedBrokerServiceTest.java
- itests/org.openhab.io.mqttembeddedbroker.tests/itest.bndrun
- itests/org.openhab.io.mqttembeddedbroker.tests/pom.xml
- itests/org.openhab.io.mqttembeddedbroker.tests/src/main/java/org/openhab/io/mqttembeddedbroker/MoquetteTest.java
Fixes #5527
See https://community.openhab.org/t/solved-mqtt-embedded-crashed-will-not-restart/83342 and https://community.openhab.org/t/solved-mqtt-broker-moquette-offline-after-upgrade-to-2-5m3/83074
> [embeddedbroker] bump moquette and fix corrupt database

- bundles/org.openhab.binding.amazonechocontrol/README.md
- bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/channelhandler/ChannelHandlerAnnouncement.java
- bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/channelhandler/ChannelHandlerSendMessage.java
- bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/handler/AccountHandler.java
- bundles/org.openhab.binding.amazonechocontrol/src/main/resources/ESH-INF/i18n/amazonechocontrol_de.properties
- bundles/org.openhab.binding.amazonechocontrol/src/main/resources/ESH-INF/thing/thing-types.xml
New channel to send a message to all echo devices.
The device will show the green light and the user can ask for the message.
> [amazonechocontrol] Send message (Green light on echo device)

- itests/org.openhab.io.hueemulation.tests/itest.bndrun
> [hueemulation] Resolve itest runbundles to fix build

- bundles/org.openhab.binding.buienradar/src/main/resources/ESH-INF/thing/thing-types.xml
- bundles/org.openhab.binding.fsinternetradio/src/main/resources/ESH-INF/thing/thing-types.xml
- bundles/org.openhab.binding.pjlinkdevice/src/main/resources/ESH-INF/thing/thing-types.xml
- bundles/org.openhab.binding.systeminfo/src/main/resources/ESH-INF/thing/computer.xml
Removes skeleton sample texts from the add-ons XML
> Remove sample texts from XML

- bundles/org.openhab.io.homekit/src/main/feature/feature.xml
- bundles/org.openhab.io.mqttembeddedbroker/src/main/feature/feature.xml
For mqttembeddedbroker and homekit
> use openhab-core netty feature

- bundles/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/api/model/FreeboxSensor.java
- bundles/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/api/model/FreeboxSystemConfig.java
> [freebox] fix temperatures and fan speed channels

- bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/channelhandler/ChannelHandlerAnnouncement.java
- bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/statedescription/AmazonEchoDynamicStateDescriptionProvider.java
- bundles/org.openhab.binding.modbus/src/test/java/org/openhab/binding/modbus/internal/ModbusDataHandlerTest.java
- bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/rest/mocks/DummyItemRegistry.java
Depends on https://github.com/openhab/openhab-core/pull/1134.
> Update add-ons for new null annotations

- bundles/org.openhab.binding.rfxcom/README.md
- bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/RFXComBindingConstants.java
- bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/ByteEnumUtil.java
- bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/ByteEnumWrapper.java
- bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/ByteEnumWrapperWithSupportedSubTypes.java
- bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComBaseMessage.java
- bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComDeviceMessage.java
- bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComFanMessage.java
- bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComMessageFactory.java
- bundles/org.openhab.binding.rfxcom/src/main/resources/ESH-INF/thing/channels.xml
- bundles/org.openhab.binding.rfxcom/src/main/resources/ESH-INF/thing/fan_lucci_dc.xml
- bundles/org.openhab.binding.rfxcom/src/main/resources/ESH-INF/thing/fan_lucci_dc_ii.xml
- bundles/org.openhab.binding.rfxcom/src/test/java/org/openhab/binding/rfxcom/internal/messages/RFXComFanFalmecMessageTest.java
- bundles/org.openhab.binding.rfxcom/src/test/java/org/openhab/binding/rfxcom/internal/messages/RFXComFanLucciAirDc2MessageTest.java
- bundles/org.openhab.binding.rfxcom/src/test/java/org/openhab/binding/rfxcom/internal/messages/RFXComFanLucciAirDcMessageTest.java
- bundles/org.openhab.binding.rfxcom/src/test/java/org/openhab/binding/rfxcom/internal/messages/RFXComFanMessageTest.java
Add support for LucciAir DC 1 and 2
See also: #6231
> [rfxcom] extend fan support

- bundles/org.openhab.binding.astro/README.md
If the altitude is optional (as indicated by the square brackets) on line 23, then the comma should also be optional. As in, if you aren't specifying the altitude, you shouldn't leave a trailing comma.
> Trivial change for optional altitude parameter

- bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/providers/DsChannelTypeProvider.java
- bundles/org.openhab.binding.harmonyhub/src/main/java/org/openhab/binding/harmonyhub/internal/HarmonyHubHandlerFactory.java
- bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/MqttChannelTypeProvider.java
- bundles/org.openhab.binding.networkupstools/src/main/java/org/openhab/binding/networkupstools/internal/NUTChannelTypeProvider.java
- bundles/org.openhab.binding.smartmeter/src/main/java/org/openhab/binding/smartmeter/internal/SmartMeterChannelTypeProvider.java
- bundles/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/ChannelsTypeProviderAvailableInputs.java
- bundles/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/ChannelsTypeProviderPreset.java
- Fixed `ChannelTypeProvider` annotations for 'getChannelTypes' method
- Removed deprecated usage of `getChannelGroupType` and `getChannelGroupTypes` of `ChannelTypeProvider` and replaced by `ChannelGroupTypeProvider` where needed
Depends on https://github.com/openhab/openhab-core/pull/1167
> Fixed 'ChannelTypeProvider' annotations for 'getChannelTypes' method

- bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/OpenAPIUtils.java
- bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/discovery/NanoleafPanelsDiscoveryService.java
- bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/handler/NanoleafControllerHandler.java
- bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/model/BooleanState.java
- bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/model/Brightness.java
- bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/model/Ct.java
- bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/model/GlobalOrientation.java
- bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/model/Hue.java
- bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/model/IntegerState.java
- bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/model/Layout.java
- bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/model/On.java
- bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/model/Palette.java
- bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/model/PositionDatum.java
- bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/model/Rhythm.java
- bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/model/RhythmPos.java
- bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/model/Sat.java
- bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/model/Write.java
Fixes [#5863](https://github.com/openhab/openhab2-addons/issues/5863) introduced by firmware 3.1.2 and an issue when no Rhythm module is connected to the panels.
See https://community.openhab.org/t/nanoleaf-nanoleaf-aurora-binding-just-started-development-collecting-requirements/63431/31 and https://community.openhab.org/t/binding-request-nanoleaf-aurora-led-design-triangle/24931/74
> [nanoleaf] Bugfixes for missing rhythm module and firmware 3.1.2

- bundles/org.openhab.binding.autelis/src/main/resources/ESH-INF/thing/pentair.xml
support for solar sensor (present on my pentair SunTouch)
> [autelis] Update for solar sensor

- bundles/org.openhab.binding.autelis/README.md
adding soltemp (solar sensor temperature) Pentair's measurement
Signed-off-by: Javier Garza github@javiergarza.net
> [autelis] adding soltemp Pentair's measurement

- itests/org.openhab.io.hueemulation.tests/itest.bndrun
- Bump jollyday version to 0.5.9
Depends on https://github.com/openhab/openhab-core/pull/1170
> Bump jollyday version to 0.5.9

- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/MieleBindingConstants.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/discovery/MieleApplianceDiscoveryService.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/discovery/MieleMDNSDiscoveryParticipant.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/CoffeeMachineHandler.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/DishWasherHandler.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/FridgeFreezerHandler.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/FridgeHandler.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/HoodHandler.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/MieleApplianceHandler.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/MieleBridgeHandler.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/OvenHandler.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/TumbleDryerHandler.java
- bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/WashingMachineHandler.java
This PR adds support for WiFi devices if a gateway is present (Fixes #2359) and prevents WiFi devices from being discovered as a gateway.
Additionally a bug that might occur after invoking an operation on a device is fixed (Fixes #5947)
> [miele] Support for WiFi devices and bugfix

- bundles/org.openhab.binding.heos/.classpath
- bundles/org.openhab.binding.heos/pom.xml
- bundles/org.openhab.binding.heos/src/main/java/org/openhab/binding/heos/handler/HeosBridgeHandler.java
- bundles/org.openhab.binding.heos/src/main/java/org/openhab/binding/heos/internal/discovery/HeosPlayerDiscovery.java
**[heos] Fix an dependency issue**
This pull request fixes a issue with the dependency of the commons-net library which prevents the binding to start.
Also a possible null pointer is fixed which may occur during scan for player and groups if the connection is not established at this point.
This pull request fixes the issues mentioned in the discussion here:
https://community.openhab.org/t/heos-denon-support/3449/231
An build can be found here
https://openhab.jfrog.io/openhab/libs-pullrequest-local/org/openhab/
> [heos ]Fixed an issue with the commons-net library

- bundles/org.openhab.binding.bluetooth.bluez/src/main/java/org/openhab/binding/bluetooth/bluez/package-info.java
> [bluetooth][bluez] add x86-64 native code

- bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/connection/OpenWeatherMapConnection.java
- Added additional check for extracting error message from response
Fixes #6309 
> [openweathermap] Added additional check for extracting error message from response

- bundles/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/FreeboxAirPlayAudioSink.java
- bundles/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/FreeboxHandlerFactory.java
- bundles/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/handler/FreeboxThingHandler.java
- bundles/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/handler/UpnpAudioSinkHandler.java
Depends on https://github.com/openhab/openhab-core/pull/1174
> Update add-ons for new audio package null annotations

- bundles/org.openhab.binding.doorbird/pom.xml
- bundles/org.openhab.binding.doorbird/src/main/feature/feature.xml
- bundles/org.openhab.binding.heos/pom.xml
- itests/org.openhab.binding.mqtt.homie.tests/src/main/java/org/openhab/binding/mqtt/HomieImplementationTest.java
Cleanup leftovers from scope-changing
> [infrastructure] change scopes where necessary

- bundles/org.openhab.binding.spotify/README.md
Re-added #6313 with credits to @zero-24
> [spotify] Fixed item example

- pom.xml
See https://github.com/openhab/openhab-core/issues/935
Signed-off-by: Arne Seime <arne.seime@gmail.com>
> [infrastructure] Added spotless maven code formatter config

- itests/org.openhab.binding.avmfritz.tests/itest.bndrun
- itests/org.openhab.binding.feed.tests/itest.bndrun
- itests/org.openhab.binding.hue.tests/itest.bndrun
- itests/org.openhab.binding.wemo.tests/itest.bndrun
- itests/org.openhab.io.hueemulation.tests/itest.bndrun
Depends on https://github.com/openhab/openhab-core/pull/1171.
> Resolve itests runbundles for Xtext/LSP update

- bundles/org.openhab.binding.mqtt/README.md
- bundles/org.openhab.binding.mqtt/src/main/resources/ESH-INF/thing/thing-types.xml
> [mqtt] adjust documentation for keepAlive to code

- bundles/org.openhab.binding.miele/README.md
> [miele] Improved documentation

- bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/AVMFritzTlsTrustManagerProvider.java
- bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/hardware/FritzAhaContentExchange.java
- bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/hardware/callbacks/FritzAhaReauthCallback.java
- Added `TlsTrustManagerProvider` / `TrustAllTrustMananger` for hostname "fritz.box"
> [avmfritz] Added 'TlsTrustManagerProvider' / 'TrustAllTrustMananger' for hostname 'fritz.box'

- bundles/org.openhab.binding.keba/src/main/resources/ESH-INF/thing/kecontact.xml
for some reason the channels authreq and authon are getting exceptions, so this is fixing the issue. tested on keba P30c.
> [keba] formatting exception fix

- bundles/org.openhab.binding.avmfritz/src/main/resources/ESH-INF/thing/bridge-types.xml
- bundles/org.openhab.binding.dscalarm/src/main/resources/ESH-INF/thing/channels.xml
- bundles/org.openhab.binding.dscalarm/src/main/resources/ESH-INF/thing/envisalinkbridge.xml
- bundles/org.openhab.binding.dscalarm/src/main/resources/ESH-INF/thing/it100bridge.xml
- bundles/org.openhab.binding.dscalarm/src/main/resources/ESH-INF/thing/tcpserverbridge.xml
- bundles/org.openhab.binding.nest/src/main/resources/ESH-INF/thing/channels.xml
- bundles/org.openhab.binding.openweathermap/src/main/resources/ESH-INF/thing/bridge-types.xml
- bundles/org.openhab.binding.pentair/src/main/resources/ESH-INF/thing/ip_bridge.xml
- bundles/org.openhab.binding.pentair/src/main/resources/ESH-INF/thing/serial_bridge.xml
- bundles/org.openhab.binding.pulseaudio/src/main/resources/ESH-INF/thing/bridge.xml
- bundles/org.openhab.binding.rfxcom/src/main/resources/ESH-INF/thing/RFXrec433.xml
- bundles/org.openhab.binding.rfxcom/src/main/resources/ESH-INF/thing/RFXtrx315.xml
- bundles/org.openhab.binding.rfxcom/src/main/resources/ESH-INF/thing/RFXtrx433.xml
- bundles/org.openhab.binding.rfxcom/src/main/resources/ESH-INF/thing/bridge.xml
- bundles/org.openhab.binding.rfxcom/src/main/resources/ESH-INF/thing/tcpbridge.xml
- bundles/org.openhab.binding.tankerkoenig/src/main/resources/ESH-INF/thing/webservice.xml
- bundles/org.openhab.binding.vitotronic/src/main/resources/ESH-INF/thing/bridge.xml
- bundles/org.openhab.binding.zoneminder/src/main/resources/ESH-INF/thing/server-bridge.xml
- bundles/org.openhab.binding.zway/src/main/resources/ESH-INF/thing/bridge.xml
- Updated binding XML schema locations to openhab
> Updated binding XML schema locations to openhab

- bundles/org.openhab.binding.networkupstools/src/main/java/org/openhab/binding/networkupstools/internal/NUTBindingConstants.java
- bundles/org.openhab.binding.networkupstools/src/main/java/org/openhab/binding/networkupstools/internal/NUTHandler.java
- bundles/org.openhab.binding.networkupstools/src/main/java/org/openhab/binding/networkupstools/internal/nut/NutConnector.java
- bundles/org.openhab.binding.networkupstools/src/main/java/org/openhab/binding/networkupstools/internal/nut/NutResponseReader.java
- Constant MAX_RETRIES contained a unintended space.
- Improved logging to log only when relevant.
> [networkupstools] Fix typo and misc log

- bundles/org.openhab.binding.yamahareceiver/src/main/resources/ESH-INF/thing/thing-types.xml
> [yamahareceiver] There is no unit dB

- bundles/org.openhab.binding.tplinksmarthome/src/test/java/org/openhab/binding/tplinksmarthome/internal/handler/SmartHomeHandlerTest.java
- Fixed failing build related to openhab/openhab-core#1209
> Fixed failing build

- bundles/org.openhab.binding.kodi/README.md
- Added more details and example of configuration for `shownotifiation` channel
Related to #5988
> [kodi] Added more details and example of configuration for 'shownotifiation' channel

- bundles/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/discovery/GardenaDeviceDiscoveryService.java
- bundles/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/handler/GardenaAccountHandler.java
- bundles/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/handler/GardenaHandlerFactory.java
- bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/discovery/HomematicDeviceDiscoveryService.java
- bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/handler/HomematicBridgeHandler.java
- bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/handler/HomematicThingHandlerFactory.java
- bundles/org.openhab.binding.homematic/src/test/java/org/openhab/binding/homematic/internal/discovery/HomematicDeviceDiscoveryServiceTest.java
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/LutronHandlerFactory.java
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/IPBridgeHandler.java
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/hw/HwDiscoveryService.java
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/hw/HwSerialBridgeHandler.java
- bundles/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/internal/ZoneMinderHandlerFactory.java
- bundles/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/internal/discovery/ZoneMinderDiscoveryService.java
- bundles/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/internal/handler/ZoneMinderServerBridgeHandler.java
- Remodel discovery services as `ThingHandlerService` to not use the `bundleContext` from `BaseThingHandler` as it is deprecated
See eclipse/smarthome/issues/5182 and openhab/openhab-core/pull/1214
> Remodel discovery services as 'ThingHandlerService'

- bundles/org.openhab.binding.wemo/README.md
- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/WemoBindingConstants.java
- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/WemoHandlerFactory.java
- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/discovery/WemoDiscoveryParticipant.java
- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoCoffeeHandler.java
- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoDimmerHandler.java
- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoLightHandler.java
- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoMakerHandler.java
- bundles/org.openhab.binding.wemo/src/main/resources/ESH-INF/thing/thing-types.xml
Some warnings also supressed.
closes #4808 
Signed-off-by: Hans-Jörg Merk <hans-joerg.merk@t-online.de>
> [wemo] Add DimmerSwitch support and update README

- bundles/org.openhab.binding.mqtt.generic/README.md
- bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/ChannelConfig.java
- bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/ChannelState.java
- bundles/org.openhab.binding.mqtt.generic/src/main/resources/ESH-INF/config/color-channel-config.xml
- bundles/org.openhab.binding.mqtt.generic/src/main/resources/ESH-INF/config/dimmer-channel-config.xml
- bundles/org.openhab.binding.mqtt.generic/src/main/resources/ESH-INF/config/number-channel-config.xml
- bundles/org.openhab.binding.mqtt.generic/src/main/resources/ESH-INF/config/rollershutter-channel-config.xml
- bundles/org.openhab.binding.mqtt.generic/src/main/resources/ESH-INF/config/string-channel-config.xml
- bundles/org.openhab.binding.mqtt.generic/src/main/resources/ESH-INF/config/switch-channel-config.xml
Fixes #6169 
Depends on #6245 
> [mqtt] add QoS to channel config

- bundles/org.openhab.io.homekit/pom.xml
- bundles/org.openhab.io.homekit/src/main/feature/feature.xml
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitAccessoryRegistry.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitAccessoryUpdater.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitAuthInfoImpl.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitChangeListener.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitImpl.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/AbstractHomekitAccessoryImpl.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/AbstractHomekitLightbulbImpl.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/AbstractTemperatureHomekitAccessoryImpl.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/GroupedAccessory.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitAccessoryFactory.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitCarbonMonoxideSensorImpl.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitColorfulLightbulbImpl.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitContactSensorImpl.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitDimmableLightbulbImpl.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitHumiditySensorImpl.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitLeakSensorImpl.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitMotionSensorImpl.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitOccupancySensorImpl.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitSmokeSensorImpl.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitSwitchImpl.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitTemperatureSensorImpl.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitThermostatImpl.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitValveImpl.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitWindowCoveringImpl.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/battery/BatteryLevelStatus.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/battery/BatteryLowStatus.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/battery/BatteryStatus.java
- bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/battery/NoBatteryStatus.java
> [homekit] upgrade hap to 1.2.0

- bundles/org.openhab.binding.wemo/README.md
> [wemo] Improvements and corrections in README

- bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/handler/RotelHandler.java
> [rotel] Fix handling of freq value

- bundles/org.openhab.binding.enturno/README.md
- Update of link in documentation (Target resource was updated by API provider)
- Some renaming of items in configuration example - this is to reflect how thing are configured + to work with widget that will be released soon
> [enturno] Documentation update

- bundles/org.openhab.binding.kodi/src/main/resources/ESH-INF/thing/thing-types.xml
- Updated pattern for `rating` channel
The rating is a decimal number so we should better support on decimal place in the pattern.
> [kodi] Updated pattern for rating channel

- bundles/org.openhab.binding.lgwebos/README.md
> [lgwebos] README update for to new new binding version

- bundles/org.openhab.binding.iaqualink/src/main/java/org/openhab/binding/iaqualink/internal/handler/IAqualinkHandler.java
Checks if the response message has an error response state and takes appropriate action.
> [iaqualink] Checks for "error" status of returned home message

- bundles/org.openhab.binding.ambientweather/README.md
- bundles/org.openhab.binding.ambientweather/src/main/resources/ESH-INF/thing/bridge.xml
Minor updates to the README and the bridge label/description.
> [ambientweather] Minor documentation updates

- bundles/org.openhab.binding.globalcache/README.md
> [globalcache] README updates

- bundles/org.openhab.binding.bigassfan/README.md
> [bigassfan] README updates

- bundles/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/GardenaSmartImpl.java
- Removed dependency on `org.apache.commons.collections`
> Removed dependency on 'org.apache.commons.collections'

- bundles/org.openhab.binding.kodi/src/main/resources/ESH-INF/config/config.xml
- bundles/org.openhab.binding.kodi/src/main/resources/ESH-INF/i18n/kodi_de.properties
- bundles/org.openhab.binding.kodi/src/main/resources/ESH-INF/thing/thing-types.xml
- Added German translations for `shownotification` channel configuration
> [kodi] Added German translations for 'shownotification' channel configuration

- bundles/org.openhab.binding.keba/src/main/java/org/openhab/binding/keba/internal/handler/KeContactTransceiver.java
> [keba] fixes NPE if get method returns null

- bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoDimmerHandler.java
Signed-off-by: Hans-Jörg Merk hans-joerg.merk@t-online.de
> [wemo] DimmerHandler - reduced one logger from info to debug

- bundles/org.openhab.binding.ipp/pom.xml
- bundles/org.openhab.binding.ipp/src/main/feature/feature.xml
> [ipp] added simple-xml dependency

- bundles/org.openhab.binding.homematic/src/main/resources/homematic/batteries.properties
- bundles/org.openhab.binding.homematic/src/main/resources/homematic/extra-descriptions.properties
- bundles/org.openhab.binding.homematic/src/main/resources/homematic/extra-descriptions_de.properties
Added Max! Basic Thermostat descriptions
> [homematic] Add Max! Basic Thermostat Descriptions

- bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/AbstractMQTTThingHandler.java
- bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/ChannelState.java
- bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/handler/GenericMQTTThingHandler.java
Fixes #4835 
Fixes #6435 
Fixes #6438 
Also fixes wrong "success" log reported in https://github.com/openhab/openhab-core/issues/1237
> [mqtt] Fix several issues after loss of connection

- bundles/org.openhab.binding.mail/pom.xml
- bundles/org.openhab.binding.mail/src/main/feature/feature.xml
- bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/action/SendMailActions.java
- bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/internal/MailBuilder.java
Fixes https://github.com/openhab/openhab2-addons/issues/6423
> [mail] added dependency to javax.mail

- bundles/org.openhab.binding.telegram/pom.xml
- bundles/org.openhab.binding.telegram/src/main/feature/feature.xml
- bundles/org.openhab.binding.telegram/src/main/java/org/openhab/binding/telegram/bot/TelegramActions.java
- bundles/org.openhab.binding.telegram/src/main/java/org/openhab/binding/telegram/internal/TelegramConfiguration.java
- bundles/org.openhab.binding.telegram/src/main/java/org/openhab/binding/telegram/internal/TelegramHandler.java
- bundles/org.openhab.binding.telegram/src/main/resources/ESH-INF/thing/thing-types.xml
Fixes #6501 and some codestyle issues
> [telegram] small fixes

- bundles/org.openhab.binding.tradfri/pom.xml
- Bump Californium to 2.0.0
Depends on https://github.com/openhab/openhab-core/pull/1257
>  [tradfri] Bump Californium to 2.0.0

- bundles/org.openhab.binding.miio/README.md
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoDevices.java
Support the new Roborock S5 Max vacuum robot.
Signed-off-by: Markus Schraufstetter <markus.schraufstetter@gmail.com>
> [miio] Add support for Roborock S5max

- bundles/org.openhab.binding.yamahareceiver/README.md
> Add RX-860 to compatible receivers

- bundles/org.openhab.binding.innogysmarthome/src/main/java/org/openhab/binding/innogysmarthome/internal/InnogyBindingConstants.java
- bundles/org.openhab.binding.innogysmarthome/src/main/java/org/openhab/binding/innogysmarthome/internal/handler/InnogyBridgeHandler.java
- bundles/org.openhab.binding.innogysmarthome/src/main/java/org/openhab/binding/innogysmarthome/internal/handler/InnogyDeviceHandler.java
- Reschedule after failure, otherwise it can happen a restart of the bundle is needed to get it running again.
- Fixed missing updating channel energy_day_euro.
> [innogysmarthome] Several improvements

- .gitignore
Add directory .history to .gitignore file to ignore VSCode auto-backup files
Also-by: Michael Roßner <Schrott.Micha@web.de>
Signed-off-by: Rosi2143 <Schrott.Micha@web.de>
> [openhab2-addons] Update global .gitignore file

- bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/internal/homie300/Device.java
- bundles/org.openhab.binding.mqtt.homie/src/test/java/org/openhab/binding/mqtt/homie/generic/internal/mapping/HomieChildMapTests.java
- bundles/org.openhab.binding.mqtt.homie/src/test/java/org/openhab/binding/mqtt/homie/internal/handler/HomieThingHandlerTests.java
- bundles/org.openhab.binding.mqtt.homie/src/test/java/org/openhab/binding/mqtt/homie/internal/handler/ThingChannelConstants.java
Fixes #6487 
Also fixes codestyle issues
> [mqtt][homie] fix handleCommand with special characters

- bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/dataexchange/NukiHttpClient.java
- bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/handler/NukiBridgeHandler.java
- bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/handler/NukiSmartLockHandler.java
Check that callbacks is not null to avoid a NPE
Fix #5859
> [nuki] Clean handling of bridge/things

- bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/MqttBindingConstants.java
- bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/discovery/AbstractMQTTDiscovery.java
- bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/handler/AbstractBrokerHandler.java
- bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/handler/SystemBrokerHandler.java
- bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/internal/MqttBrokerHandlerFactory.java
> [mqtt] add missing logger parameters and  codestyle

- bundles/org.openhab.binding.mqtt.homie/src/test/java/org/openhab/binding/mqtt/homie/internal/handler/HomieThingHandlerTests.java
> [mqtt][homie] fix homie test after refresh handling changed

- bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/BaseChannelConfiguration.java
- bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/ConnectionDeserializer.java
- bundles/org.openhab.binding.mqtt.homeassistant/src/test/resources/org/openhab/binding/mqtt/homeassistant/internal/configA.json
- bundles/org.openhab.binding.mqtt.homeassistant/src/test/resources/org/openhab/binding/mqtt/homeassistant/internal/configB.json
Fixes #6569 
Old implementation expected an object where the specification gives a list of strings.
> [mqtt][homeassistant] fix connection deserialization

- bundles/org.openhab.binding.miio/src/main/resources/database/chuangmi.plug.m1.json
Signed-off-by: Alexander Skvortsov <skvalex@gmail.com>
> [miio] Add indicator light channel for Mi-Power plug

- bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/handler/AbstractAvrHandler.java
Signed-off-by: Scott Rushworth <openhab@5iver.com>
> [pioneeravr] Fixed typo in log

- bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/Connection.java
Signed-off-by: Scott Rushworth <openhab@5iver.com>
> [amazonechocontrol] Fixed typo in log

- bundles/org.openhab.binding.shelly/README.md
> [Shelly] Fix typo in Readme

- bundles/create_openhab_binding_skeleton.cmd
- bundles/create_openhab_binding_skeleton.sh
Updated the openhabVersion in the skeleton scripts to fix #6609 
Signed-off-by: Yifeng Huang hyf980817@163.com
> Updated the openhabVersion in the skeleton scripts

- bundles/org.openhab.binding.tankerkoenig/README.md
Updated README to suggest the use of the ephemeris action for setting the holiday switch.
Signed-off-by: Juergen Baginski opus42@gmx.de (github: JueBag)
> [Tankerkoenig] Updated README 

- bundles/org.openhab.binding.mail/README.md
Use sampleimap - instead of sampleserver - to keep it consistent in the example
Also-by: Michael Roßner <Schrott.Micha@web.de>
Signed-off-by: Rosi2143 <Schrott.Micha@web.de>
> [mail] update smtp server name to have it consistent

- bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/handler/OpenSprinklerStationHandler.java
> [opensprinkler] Fix type cast exception

- bundles/org.openhab.io.javasound/pom.xml
- bundles/org.openhab.io.javasound/src/main/feature/feature.xml
- bundles/org.openhab.voice.marytts/pom.xml
- bundles/org.openhab.voice.marytts/src/main/feature/feature.xml
- Added dependency on commons-collections to marrytts
- Bump version to 3.2.2
> Added dependency on commons-collections to marrytts; Bump version to 3.2.2;

- README.md
- Changed path to Travis badge in README.md to display the current build status
> Changed path to Travis badge in README.md

- bundles/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/handler/ModbusDataThingHandler.java
Trying to aid readability, no change in logic
> [modbus] Rename local variable

- bundles/org.openhab.binding.mail/README.md
use apostrophe correctly
Also-by: Michael Roßner <Schrott.Micha@web.de>
Signed-off-by: Rosi2143 <Schrott.Micha@web.de>
> [mail-binding] correct README.md

- bundles/org.openhab.binding.deconz/README.md
- bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/BindingConstants.java
- bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/HandlerFactory.java
- bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/discovery/ThingDiscoveryService.java
- bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/SensorThingHandler.java
- bundles/org.openhab.binding.deconz/src/main/resources/ESH-INF/thing/thing-types.xml
- Added support for ZHAFire sensors
Closes #6298 
> [deconz] Added support for ZHAFire sensors

- bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/discovery/ZonePlayerDiscoveryParticipant.java
> [sonos] Discovery of Sonos One SL

- bundles/org.openhab.binding.innogysmarthome/src/main/java/org/openhab/binding/innogysmarthome/internal/client/entity/device/State.java
- bundles/org.openhab.binding.innogysmarthome/src/main/java/org/openhab/binding/innogysmarthome/internal/handler/InnogyDeviceHandler.java
Closes #6610
Closes #6613
Closes #6624
> [innogysmarthome] Fix Dimmer / Rollershutter / Gen 1 devices and Pushbutton

- bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/handler/KodiHandler.java
- Fixed assignment of values for channels 'userrating' and 'rating'
Channel `ratung` iwas updated twice:
https://github.com/openhab/openhab-addons/blob/83e8d6969a4204590465fef49c9a6596dae27f9b/bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/handler/KodiHandler.java#L809-L817
See https://community.openhab.org/t/kodi-imdb-rating/87815
> [kodi] Fixed assignment of values for channels 'userrating' and 'rating'

- features/openhab-addons/src/main/resources/header.xml
- pom.xml
- tools/static-code-analysis/checkstyle/ruleset.properties
> Update copyright headers to 2020 (master)

- bundles/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromecastAudioSink.java
- bundles/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromecastCommander.java
- Stop stream instead of throwing NPE
Fixes #6740 
> [chromecast] Stop stream instead of throwing NPE

- bundles/org.openhab.transform.scale/README.md
> Correction: "[" in example change to "]"

- CONTRIBUTING.md
- pom.xml
- src/etc/NOTICE
> Update POM and documentation for renamed repository (master)

- bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/discovery/TeslaVehicleDiscoveryService.java
fixes https://github.com/openhab/openhab-addons/issues/6604
> [tesla] ignore unknown types and prevent NPEs

- bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/handler/ZonePlayerHandler.java
> [sonos] Avoid resuming a wrong playlist after a notification

- bundles/create_openhab_binding_skeleton.cmd
- bundles/create_openhab_binding_skeleton.sh
- Fixed version in create binding skeleton scripts
- Distinguish between `version` and `archetypeVersion`
- temporary fix for `{ohc.version}` variable in linux script - ~~windows is missing~~
@Hilbrand wdyt? I am not a Windows expert thus I am afraid I do not know how to replace the variable inside the `feature.xml`.
Also-by: Hilbrand Bouwkamp <hilbrand@h72.nl>
Also-by: Jan N. Klug <jan.n.klug@rub.de>
> [skeleton] Fixed versions in create binding skeleton scripts

- bundles/org.openhab.binding.tesla/README.md
changed e.g channel="tesla:model3:myaccount:mycar::heading"} to channel="tesla:model3:myaccount:mycar:heading"}
> [tesla] Updated Things example

- bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/handler/MaxCubeBridgeHandler.java
- bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/handler/MaxDevicesHandler.java
Avoid OH2.5 rule triggers due to config updates
Always update channel so we always see info in the UI
> [max] Max always update channels & avoid config updates

- bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/CryptUtil.java
- bundles/org.openhab.binding.tplinksmarthome/src/test/java/org/openhab/binding/tplinksmarthome/internal/device/EncodingTest.java
- bundles/org.openhab.binding.tplinksmarthome/src/test/resources/org/openhab/binding/tplinksmarthome/internal/model/encoding_test.json
> [tplinksmarthome] Fix special characters in data

- bundles/org.openhab.binding.tplinksmarthome/README.md
- bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/TPLinkSmartHomeHandlerFactory.java
- bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/TPLinkSmartHomeThingType.java
- bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/device/PowerStripDevice.java
- bundles/org.openhab.binding.tplinksmarthome/src/main/resources/ESH-INF/thing/KP303.xml
- bundles/org.openhab.binding.tplinksmarthome/src/test/java/org/openhab/binding/tplinksmarthome/internal/device/DeviceTestBase.java
- bundles/org.openhab.binding.tplinksmarthome/src/test/java/org/openhab/binding/tplinksmarthome/internal/device/EnergySwitchDeviceTest.java
- bundles/org.openhab.binding.tplinksmarthome/src/test/java/org/openhab/binding/tplinksmarthome/internal/device/PowerStripDeviceTest.java
- bundles/org.openhab.binding.tplinksmarthome/src/test/java/org/openhab/binding/tplinksmarthome/internal/model/ModelTestUtil.java
Fixes also global On/Off state of power strip devices.
Closes #6576
> [tplinksmarthome] Added support for KP303

- bundles/org.openhab.binding.zoneminder/.classpath
- Removed missing lib from classpath
> [zoneminder] Removed missing lib from classpath

- bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/Connection.java
This adds a timeout to the socket connections otherwise it can possibly block forever.
> [tplinksmarthome] Added socket timeout avoids block

- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaAdjustableSlatsRollerShutterHandler.java
- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaBaseThingHandler.java
- Added checks to omit null type mismatch errors
> [somfytahoma] Added checks to omit null type mismatch errors

- bundles/org.openhab.binding.ftpupload/README.md
> [ftpupload] Improved README

- bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/utils/ByteArrayFileCache.java
- bundles/org.openhab.binding.kodi/src/test/java/org/openhab/binding/kodi/internal/utils/ByteArrayFileCacheTest.java
- Strip URL parameters from the end of the file extension
Prevent `java.nio.file.FileSystemException`  (File name too long) if source is an URL with a bunch of parameters. See https://community.openhab.org/t/openhab-2-kodi/21941/49 for an example.
> [kodi] Strip URL parameters from the end of the file extension

- bundles/org.openhab.binding.logreader/README.md
- bundles/org.openhab.binding.logreader/src/main/java/org/openhab/binding/logreader/internal/filereader/FileTailer.java
- bundles/org.openhab.binding.logreader/src/main/java/org/openhab/binding/logreader/internal/filereader/api/LogFileReader.java
- bundles/org.openhab.binding.logreader/src/main/java/org/openhab/binding/logreader/internal/handler/LogHandler.java
> [Logreader] Changed FileTailer to use own executor service

- bundles/org.openhab.binding.ftpupload/src/main/java/org/openhab/binding/ftpupload/internal/FtpUploadHandlerFactory.java
> [ftpupload] Minimize startup loggings

- .travis.yml
- bom/openhab-core-index/.classpath
- bom/runtime-index/.classpath
- bom/test-index/.classpath
- bundles/pom.xml
- features/pom.xml
- itests/itest-common.bndrun
- pom.xml
Related to:
* https://github.com/openhab/openhab-core/issues/1287
* https://github.com/openhab/openhab-core/pull/1305
* https://github.com/openhab/openhab-distro/pull/1033
* https://github.com/openhab/openhab-webui/pull/160
* https://github.com/openhab/org.openhab.binding.zigbee/pull/540
* https://github.com/openhab/org.openhab.binding.zwave/pull/1277
> Switch to Java 11 and drop Java 8 support

- bundles/org.openhab.binding.homematic/src/main/resources/homematic/extra-descriptions.properties
HmIP-MOD-TM added to List
Devices works flawlessly but had no description.
> [homematic] Update extra-descriptions.properties

- tools/static-code-analysis/checkstyle/ruleset.properties
See https://github.com/openhab/static-code-analysis/pull/306
> Removed obsolete checkstyle configuration

- bundles/org.openhab.binding.miio/.gitignore
- bundles/org.openhab.binding.miio/README.base.md
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/ReadmeHelper.java
- bundles/org.openhab.binding.miio/src/test/java/org/openhab/binding/miio/internal/ReadmeHelper.java
Support tool to create the miio binding readme file
as discussed in #6448
note: I mainly used this tool for my own purpose, but sharing this so other contributers can also make updates to the readme without painful manual creation of the details
> [miio] readme file creator

- bundles/org.openhab.binding.modbus/DEVELOPERS.md
> [modbus] Developer's guide to advice how to debug binding in IDE

- bundles/org.openhab.binding.heos/src/main/java/org/openhab/binding/heos/handler/HeosBridgeHandler.java
- bundles/org.openhab.binding.heos/src/main/java/org/openhab/binding/heos/handler/HeosThingBaseHandler.java
- bundles/org.openhab.binding.heos/src/main/java/org/openhab/binding/heos/internal/HeosChannelHandlerFactory.java
- bundles/org.openhab.binding.heos/src/main/java/org/openhab/binding/heos/internal/api/HeosSystem.java
- bundles/org.openhab.binding.heos/src/main/java/org/openhab/binding/heos/internal/resources/Telnet.java
[heos] Fix of favorite channels and restarting of the binding
This fix solves an issue with starting playback from the favorite channels. It also fixes an issue which can cause the binding to stop if the Telnet connection is closed
If the build was successful it can be found here:
https://openhab.jfrog.io/openhab/libs-pullrequest-local/org/openhab/
and here:
https://github.com/Wire82/openhab-addons/releases/tag/V2.5.1.beta2
The discussion about the issues can be found here:
https://community.openhab.org/t/heos-denon-support/3449/257
> [heos] Fix of favorite channel and Telnet issues

- pom.xml
Depends on upgrade of SAT version. Related to SAT pr: https://github.com/openhab/static-code-analysis/pull/368
> Added spotless format config for feature.xml

- bundles/org.openhab.binding.homematic/src/main/resources/homematic/extra-descriptions_de.properties
Closes: #6826
Signed-of-by: Martin van Wingerden <martin@martinvw.nl>
Also-by: BOFH90
> [homematic] Update extra-descriptions_de.properties

- bundles/org.openhab.binding.millheat/src/main/java/org/openhab/binding/millheat/internal/discovery/MillheatDiscoveryService.java
Only one account's devices got listed
> [millheat] Fixed discovery bug when using multiple accounts

- bundles/org.openhab.binding.bluetooth.bluegiga/src/main/java/org/openhab/binding/bluetooth/bluegiga/BlueGigaBluetoothDevice.java
> [bluegiga] Fixed get characteristic data issue

- bundles/org.openhab.binding.lutron/README.md
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/KeypadComponent.java
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/LutronHandlerFactory.java
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/discovery/LutronDeviceDiscoveryService.java
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/discovery/LutronMcastBridgeDiscoveryService.java
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/CcoHandler.java
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/GreenModeHandler.java
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/LutronHandler.java
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/MaintainedCcoHandler.java
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/OccupancySensorHandler.java
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/PulsedCcoHandler.java
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/ShadeHandler.java
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/SwitchHandler.java
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/TimeclockHandler.java
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/net/TelnetSession.java
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/net/TelnetSessionListener.java
No functional changes. This commit just adds null annotations to 15 classes and includes a doc update intended to eliminate some confusion reported by users regarding VCRX thing configuration.
> [lutron] Add null annotations and update docs

- bundles/org.openhab.binding.hydrawise/src/main/java/org/openhab/binding/hydrawise/internal/HydrawiseCloudHandler.java
> [hydrawise] Some sensors do not have values for all fields.

- bundles/org.openhab.voice.googletts/README.md
- Added hint to folder where the add-on caches files
> [googletts] Added hint to folder where the add-on caches files

- bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/dto/SensorMessage.java
- bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/SensorThingHandler.java
- bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/netutils/WebSocketConnection.java
- bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/netutils/WebSocketValueUpdateListener.java
- Added config change listener
Related to #6362 
According to [deCONZ REST API - Websocket documentation](http://dresden-elektronik.github.io/deconz-rest-doc/websocket/) the websocket emits events for state and config changes.
> [deconz] Added config change listener

- bundles/org.openhab.binding.wifiled/README.md
- bundles/org.openhab.binding.wifiled/src/main/java/org/openhab/binding/wifiled/internal/discovery/WiFiLEDDiscoveryService.java
Fix the ArrayIndexOutOfBoundsException.
This change also:
allows the discovery process to skip over unparseable responses and continue searching
adds additional logging output
fixes a few tiny typos
fixes a few tiny problems in the README
A [test jar](https://drive.google.com/open?id=1WXviT-zKdU8kSeqXn630UpF0jgVTbZTT) is available.
Fixes #6848 
> [wifiled] Fix ArrayIndexOutOfBoundsException during discovery

- bundles/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/ChannelsTypeProviderAvailableInputs.java
- bundles/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/ChannelsTypeProviderPreset.java
Related to https://github.com/openhab/openhab-core/pull/1317
Fixes https://ci.openhab.org/job/openHAB-Addons-port/23/console
> [yamahareceiver] fixed null annotations

- bundles/org.openhab.binding.xmltv/README.md
- bundles/org.openhab.binding.xmltv/pom.xml
- bundles/org.openhab.binding.xmltv/src/main/feature/feature.xml
- bundles/org.openhab.binding.xmltv/src/main/java/org/openhab/binding/xmltv/internal/configuration/XmlTVConfiguration.java
- bundles/org.openhab.binding.xmltv/src/main/java/org/openhab/binding/xmltv/internal/handler/XmlTVHandler.java
- bundles/org.openhab.binding.xmltv/src/main/resources/ESH-INF/thing/thing-types.xml
For me the titles and other String type data will rendered incorrectly, because the encoding was not set correctly.
This commit adds the ability to change the encoding of the XMLTV file.
> [xmltv] Added encoding option

- bundles/org.openhab.binding.deconz/README.md
- bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/BindingConstants.java
- bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/dto/SensorState.java
- bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/SensorThingHandler.java
- bundles/org.openhab.binding.deconz/src/main/resources/ESH-INF/thing/thing-types.xml
- Added optional channel 'gesture' for Xiaomi smart cubes
> [deconz] Added optional channel 'gesture' for Xiaomi smart cubes

- bundles/org.openhab.binding.feed/pom.xml
- bundles/org.openhab.binding.feed/src/main/feature/feature.xml
- bundles/org.openhab.binding.feed/src/main/java/org/openhab/binding/feed/internal/handler/FeedHandler.java
- bundles/org.openhab.binding.feed/src/main/resources/ESH-INF/binding/binding.xml
- bundles/org.openhab.binding.feed/src/main/resources/ESH-INF/thing/thing-types.xml
Reduce the log-level of messages emitted to eliminate log spam.
Fix the Null Pointer Exception that occurs when various attributes have no value.
[Test jar is available](https://drive.google.com/open?id=1twN7zHn7hiAYDnMYHWd-IEeCRnV7dC5B).
Fixes #6906.
> [feed] Fix Null Pointer Exceptions and reduce log spam

- bundles/org.openhab.binding.innogysmarthome/src/main/java/org/openhab/binding/innogysmarthome/internal/handler/InnogyBridgeHandler.java
- bundles/org.openhab.binding.innogysmarthome/src/main/java/org/openhab/binding/innogysmarthome/internal/manager/DeviceStructureManager.java
> [innogysmarthome] Added guard against null value

- bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/SamsungTvTlsTrustManagerProvider.java
- Use OHC `TrustAllTrustMananger`
> Use OHC 'TrustAllTrustMananger'

- bundles/org.openhab.binding.nanoleaf/README.md
- bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/OpenAPIUtils.java
- bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/handler/NanoleafControllerHandler.java
- bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/handler/NanoleafPanelHandler.java
> [nanoleaf] corrected item definition for touch items in README.

- bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/discovery/internal/BluetoothDiscoveryService.java
Signed-off-by: Connor Petty <cpmeister@users.noreply.github.com>
> [bluetooth] Fix discovery on startup bug  (#6912)

- bundles/org.openhab.binding.fsinternetradio/README.md
This adds a new Radio to the documentation. Added is the Radio "Hama DIR3505MSCBT".
> Added a new Radio to Mode table (Hama DIR3505MSCBT)

- bundles/org.openhab.binding.bluetooth.bluez/src/main/java/org/openhab/binding/bluetooth/bluez/BlueZBluetoothDevice.java
- bundles/org.openhab.binding.bluetooth.bluez/src/main/java/org/openhab/binding/bluetooth/bluez/handler/BlueZBridgeHandler.java
- bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/discovery/internal/BluetoothDiscoveryService.java
This contains the bulk of important changes from #6916. This should make it a bit easier to review.
> [bluetooth.bluez] Fix for endless device discovery filling inbox (#6836)(#6915)

- bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/handler/MaxCubeBridgeHandler.java
Limit refreshes to 1 per 10 seconds, avoid excessive connections to the cube  esp during startup.
> [max] prevent excessive refreshes

- bundles/org.openhab.binding.freebox/README.md
- bundles/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/FreeboxBindingConstants.java
- bundles/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/api/FreeboxApiManager.java
- bundles/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/api/model/FreeboxFtthStatus.java
- bundles/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/api/model/FreeboxFtthStatusResponse.java
- bundles/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/handler/FreeboxHandler.java
- bundles/org.openhab.binding.freebox/src/main/resources/ESH-INF/binding/binding.xml
- bundles/org.openhab.binding.freebox/src/main/resources/ESH-INF/thing/thing-types.xml
- pom.xml
> [freebox] Adding Fiber optic and support of Delta bridge

- bundles/org.openhab.binding.hpprinter/pom.xml
- bundles/org.openhab.binding.hpprinter/src/main/feature/feature.xml
- bundles/org.openhab.binding.hpprinter/src/main/java/org/openhab/binding/hpprinter/internal/HPPrinterBindingConstants.java
- bundles/org.openhab.binding.hpprinter/src/main/java/org/openhab/binding/hpprinter/internal/HPPrinterConfiguration.java
- bundles/org.openhab.binding.hpprinter/src/main/java/org/openhab/binding/hpprinter/internal/HPPrinterDiscoveryParticipant.java
- bundles/org.openhab.binding.hpprinter/src/main/java/org/openhab/binding/hpprinter/internal/api/HPProperties.java
- bundles/org.openhab.binding.hpprinter/src/main/java/org/openhab/binding/hpprinter/internal/api/HPServerResult.java
- bundles/org.openhab.binding.hpprinter/src/main/java/org/openhab/binding/hpprinter/internal/api/HPStatus.java
- bundles/org.openhab.binding.hpprinter/src/main/java/org/openhab/binding/hpprinter/internal/api/HPType.java
- bundles/org.openhab.binding.hpprinter/src/main/java/org/openhab/binding/hpprinter/internal/api/HPUsage.java
- bundles/org.openhab.binding.hpprinter/src/main/java/org/openhab/binding/hpprinter/internal/api/HPWebServerClient.java
- bundles/org.openhab.binding.hpprinter/src/main/java/org/openhab/binding/hpprinter/internal/binder/HPPrinterBinder.java
- bundles/org.openhab.binding.hpprinter/src/main/java/org/openhab/binding/hpprinter/internal/binder/HPPrinterBinderEvent.java
- bundles/org.openhab.binding.hpprinter/src/main/java/org/openhab/binding/hpprinter/internal/handler/HPPrinterHandler.java
- bundles/org.openhab.binding.hpprinter/src/main/java/org/openhab/binding/hpprinter/internal/handler/HPPrinterHandlerFactory.java
- bundles/org.openhab.binding.hpprinter/src/main/resources/ESH-INF/config/config.xml
- bundles/org.openhab.binding.hpprinter/src/main/resources/ESH-INF/thing/channel-types.xml
- bundles/org.openhab.binding.hpprinter/src/main/resources/ESH-INF/thing/thing-printer.xml
While traveling I noted some non-standard thing in the HP printer binding and I decided to walk through them. I did not change the flow but cleaned up some details.
- some string comparisons where using ==
- there were some issues with the null annotations, things were passed along as being null while that would be killing for the status constructing an hp-client without httpClient is useless.
- improved formatting
- Made more fields immutable
- do not recreate the status message map on every request
- add braces for `if` statements
- Use parseInt to convert int instead of using both parsing and unboxing
- use diamond operators
- use method references where possible
- do not put the device OFFLINE while starting to connect
> [hpprinter] Some small updates to the HP binding

- bundles/org.openhab.binding.darksky/README.md
- bundles/org.openhab.binding.darksky/src/main/java/org/openhab/binding/darksky/internal/handler/DarkSkyWeatherAndForecastHandler.java
- Fixed examples of alert channels 
- Added warning, if channel group does not exist
> [darksky] Fixed examples of alert channels

- bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/discovery/RFXComDeviceDiscoveryService.java
> [rfxcom] Added 3600 sec TTL to discovered devices

- bundles/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/handler/ModbusPollerThingHandlerImpl.java
> [modbus] Fix for data things not initializing properly in some cases.

- bundles/org.openhab.transform.jsonpath/README.md
An attempt at improving/clarifying the README for the JsonPath transformation.
> [JsonPath transform] Improve/clarify README

- bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/job/DailyJobMoon.java
- bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/job/DailyJobSun.java
> [astro] Changed daily event jobs log level from info to debug

- bundles/org.openhab.binding.innogysmarthome/src/main/java/org/openhab/binding/innogysmarthome/internal/client/InnogyClient.java
- bundles/org.openhab.binding.innogysmarthome/src/main/java/org/openhab/binding/innogysmarthome/internal/handler/InnogyBridgeHandler.java
Fixed a number of logging convention problems and a typographical error.
> [innogysmarthome] Fix log message problems

- bundles/org.openhab.transform.javascript/README.md
> [javascript] Added online tester example

- bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/device/DimmerDevice.java
- bundles/org.openhab.binding.tplinksmarthome/src/test/java/org/openhab/binding/tplinksmarthome/internal/device/DimmerDeviceTest.java
> [tplinksmarthome] fix dimmer not turning on via brightness value

- bundles/org.openhab.binding.exec/README.md
(1) Binding behaviour for "autorun" mode is not obvious.  Counter intuitively, it ignores duplicate commands.  Highlighting this in docs.  (Desirable or not, just documenting the way it is now)
(2) improve 'full' rules example with "busy" check, and accounting for asynchronous races between various in/out channels.
Signed-off-by: Ross Kennedy rossko@culzean.clara.co.uk
> [exec] Update README.md

- bundles/create_openhab_binding_skeleton.cmd
- bundles/create_openhab_binding_skeleton.sh
- itests/itest-common.bndrun
- itests/itest-include.bndrun
- itests/org.openhab.binding.astro.tests/itest.bndrun
- itests/org.openhab.binding.avmfritz.tests/itest.bndrun
- itests/org.openhab.binding.feed.tests/itest.bndrun
- itests/org.openhab.binding.hue.tests/itest.bndrun
- itests/org.openhab.binding.max.tests/itest.bndrun
- itests/org.openhab.binding.mqtt.homeassistant.tests/itest.bndrun
- itests/org.openhab.binding.mqtt.homie.tests/itest.bndrun
- itests/org.openhab.binding.nest.tests/itest.bndrun
- itests/org.openhab.binding.ntp.tests/itest.bndrun
- itests/org.openhab.binding.systeminfo.tests/itest.bndrun
- itests/org.openhab.binding.tradfri.tests/itest.bndrun
- itests/org.openhab.binding.wemo.tests/itest.bndrun
- itests/org.openhab.io.hueemulation.tests/itest.bndrun
- itests/org.openhab.io.mqttembeddedbroker.tests/itest.bndrun
- itests/org.openhab.persistence.mapdb.tests/itest.bndrun
- Fixed itest bnd versions in tests
- Fixed version in skeleton scripts
-  Split up` itest-common.bndrun` into `itest-common.bndrun` (excluding storage) and `itest-include.bndrun` (using storage)
> Fixed missing 2.5.3-SNAPSHOT changes

- bundles/org.openhab.binding.telegram/README.md
add pointer to use bot to get Telegram chatID
> update Telegram binding docs

- bundles/org.openhab.transform.regex/README.md
- bundles/org.openhab.transform.xslt/README.md
[transform][doc] Added online tools to Transformation Service
Added an online XLS transformer (freeformatter.com) to XSLT Transformation Service
Added an online Regex tester (extendsclass.com, I am the founder) with a Regex visualizer to RegEx Transformation Service
Signed-off-by: Cyril Bois <cyrilbois82@gmail.com>
> [transform][doc] Added online tools to Transformation Service

- bundles/org.openhab.binding.tradfri/README.md
> correct typo item= instead of item)

- bundles/org.openhab.binding.homematic/README.md
Added a section about the combined parameter used by the HmIP-WRCD.
Signed-off-by: Matthias Brandt <mattelacchiato@gmail.com>
> [homematic] update Readme for HmIP-WRCD

- bundles/org.openhab.binding.bluetooth.bluegiga/src/main/java/org/openhab/binding/bluetooth/bluegiga/BlueGigaBluetoothDevice.java
- bundles/org.openhab.binding.bluetooth.bluegiga/src/main/java/org/openhab/binding/bluetooth/bluegiga/handler/BlueGigaBridgeHandler.java
Replaces #6595. Ready for review / merge.
> [bluetooth.bluegiga] Fix BlueGiga discovery and manufacturerData handling

- bundles/org.openhab.binding.exec/src/main/java/org/openhab/binding/exec/internal/ExecWhitelistWatchService.java
- bundles/org.openhab.transform.exec/src/main/java/org/openhab/transform/exec/internal/ExecTransformationWhitelistWatchService.java
> [exec] read whitelist on startup

- bundles/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/handler/OwBaseThingHandler.java
> [onewire] fix updating presence channel

- bundles/org.openhab.binding.nanoleaf/README.md
- bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/NanoleafBadRequestException.java
- bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/OpenAPIUtils.java
- bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/handler/NanoleafControllerHandler.java
- bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/handler/NanoleafPanelHandler.java
Last commit introduced an NPE in logging which is critical to be fixed. Moved more logging to trace. Also implemented correct http 400 nanoleaf response handling.
> [nanoleaf] Fixed: Http 400 handling / NPE in logging. Reduced logging.

- bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/command/ReadEventCommand.java
- bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/handler/SatelEventLogHandler.java
This PR contains better decoding of event log records:
- support for additional record types,
- better decoding of records for existing record types,
- other small changes/fixes.
> [satel] Event log improvements

- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/transport/MiIoAsyncCommunication.java
> [miio] Prevent unneeded pings

- bundles/org.openhab.binding.meteoblue/src/main/java/org/openhab/binding/meteoblue/internal/handler/MeteoBlueBridgeHandler.java
- bundles/org.openhab.binding.meteoblue/src/main/java/org/openhab/binding/meteoblue/internal/handler/MeteoBlueHandler.java
Change the default units for wind speed to match what the meteoblue service delivers.
Also clean up some compiler warnings.
Fixes #7077 .
> [meteoblue] Fix wind speed units

- bundles/org.openhab.binding.bluetooth.bluez/src/main/java/org/openhab/binding/bluetooth/bluez/handler/BlueZBridgeHandler.java
Just a minor fix for another exception that I encountered.
> [bluetooth.bluez] Prevent adapter from going offline for certain exceptions

- bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/ConfigStore.java
> [hueemulation] Consider property discoveryIps if configured (#6662)

- bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/command/ControlObjectCommand.java
- bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/command/IntegraStateCommand.java
- bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/command/IntegraStatusCommand.java
- bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/command/IntegraVersionCommand.java
- bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/command/ModuleVersionCommand.java
- bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/command/NewStatesCommand.java
- bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/command/ReadDeviceInfoCommand.java
- bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/command/ReadEventCommand.java
- bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/command/ReadEventDescCommand.java
- bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/command/ReadZoneTemperature.java
- bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/command/SatelCommand.java
- bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/command/SatelCommandBase.java
- bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/event/EventDispatcher.java
- bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/event/SatelEventListener.java
- bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/handler/Atd100Handler.java
- bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/handler/SatelBridgeHandler.java
- bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/handler/SatelEventLogHandler.java
- bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/handler/SatelShutterHandler.java
- bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/handler/SatelStateThingHandler.java
- bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/handler/SatelSystemHandler.java
- bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/protocol/SatelModule.java
This PR contains following changes:
- internal binding event system has been refactored: now each event has its own handler method; this way there is no need to check type of incoming event in handlers;
- basic response validation has been moved to base class `SatelCommandBase`;
- `handleResponse` has been splitted to avoid necessity of calling super class `handleResponse`;
- workaround for https://community.openhab.org/t/satel-zones-not-work/91620/15 in `SatelModule` has been added - it ignores responses that don't match sent command;
> [satel] Command and events refactoring, communication improvements

- bundles/org.openhab.binding.somfytahoma/README.md
- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/SomfyTahomaBindingConstants.java
- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/discovery/SomfyTahomaItemDiscoveryService.java
- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaAdjustableSlatsRollerShutterHandler.java
- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaBaseThingHandler.java
- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaBridgeHandler.java
- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaContactSensorHandler.java
- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaGatewayHandler.java
- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaLightSensorHandler.java
- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaMyfoxCameraHandler.java
- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaOccupancySensorHandler.java
- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaSmokeSensorHandler.java
- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaThermostatHandler.java
- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaUnoRollerShutterHandler.java
- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaWaterSensorHandler.java
- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/model/SomfyTahomaAction.java
- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/model/SomfyTahomaActionGroup.java
- bundles/org.openhab.binding.somfytahoma/src/main/resources/ESH-INF/thing/channels.xml
- bundles/org.openhab.binding.somfytahoma/src/main/resources/ESH-INF/thing/contactsensor.xml
- bundles/org.openhab.binding.somfytahoma/src/main/resources/ESH-INF/thing/lightsensor.xml
- bundles/org.openhab.binding.somfytahoma/src/main/resources/ESH-INF/thing/occupancysensor.xml
- bundles/org.openhab.binding.somfytahoma/src/main/resources/ESH-INF/thing/smokesensor.xml
- bundles/org.openhab.binding.somfytahoma/src/main/resources/ESH-INF/thing/watersensor.xml
This PR contains:
- automatic adding of a RSSI channel to all things where applicable
- added _sensor_defect_ channel for getting the health state of sensors
- added extra channels _radio_battery_, _sensor_battery_ for the smoke sensor thing (getting battery health)
> [somfytahoma] added dynamic RSSI channel

- bundles/org.openhab.binding.bluetooth.am43/pom.xml
This currently breaks our CI build...
> fixed version in pom.xml

- bundles/org.openhab.binding.mcp23017/README.md
- bundles/org.openhab.binding.mcp23017/src/main/resources/ESH-INF/thing/thing-types.xml
[MCP23017] Allow choosing I2C bus numbers other than 0 and 1
If additional I2C busses have to be used because of a limitation of 8 MCP23017 on the same bus (8 available addresses) those additional bus numbers should be chooseable. It is only nescessary to add further options in the GUI
> [MCP23017] Allow choosing I2C bus numbers other than 0 and 1

- bundles/org.openhab.binding.volvooncall/README.md
- bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/VolvoOnCallBindingConstants.java
- bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/dto/Heater.java
- bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/dto/HvBattery.java
- bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/dto/Status.java
- bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/handler/VehicleHandler.java
- bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/handler/VolvoOnCallBridgeHandler.java
- bundles/org.openhab.binding.volvooncall/src/main/resources/ESH-INF/thing/vehicle.xml
Added to the VolvoOnCall binding:
Tyre pressure
Plugin Hybrid (PHEV) / Twin engine data
Preclimatization next to Remote heater
Average speed
Brake fluid level
Also updated the readme file
> [volvooncall] Add missing channels and update documentation (#6880)

- bundles/org.openhab.binding.exec/src/main/feature/feature.xml
- bundles/org.openhab.binding.exec/src/main/java/org/openhab/binding/exec/internal/ExecWhitelistWatchService.java
- bundles/org.openhab.transform.exec/src/main/feature/feature.xml
- bundles/org.openhab.transform.exec/src/main/java/org/openhab/transform/exec/internal/ExecTransformationWhitelistWatchService.java
- features/openhab-addons-external/pom.xml
- features/openhab-addons-external/src/main/resources/conf/exec.whitelist
fixes https://github.com/openhab/openhab-addons/issues/7108
> [exec] create exec.whitelist file when exec binding or transformation is installed

- bundles/org.openhab.binding.lgwebos/README.md
> [lgwebos] Fix items example

- bundles/org.openhab.binding.nuki/src/main/resources/ESH-INF/thing/thing-types.xml
Syncs the Thing description with the docs.
Fixes #7061
Is this OK @mkatter?
> [nuki] Improve Nuki ID description

- bundles/org.openhab.binding.avmfritz/README.md
Add clarification to  enable "login with FRITZ!Box user name and password" setting in the FRITZ!Box. Add instructions on how to do so.
> [avmfritz] Update README.md | login w/ password setting

- bundles/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/internal/SenseBoxAPIConnection.java
- bundles/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/internal/handler/SenseBoxHandler.java
- Fixed NPE by adding callback to cache before starting refresh job
- Parse pressure data for sensors returning unit "Pa" properly
- Minor clean-ups to harden lifecycle of handler (stop refresh job, use local vars)
```
at org.openhab.binding.sensebox.internal.handler.SenseBoxHandler.lambda$1(SenseBoxHandler.java:143) ~[?:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_242]
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[?:1.8.0_242]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_242]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) …
```
> [sensebox] Fixed NPE by adding callback to cache before starting refresh job

- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/Message.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoBindingConstants.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoCommand.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoCrypto.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoCryptoException.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoDevices.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoMessageListener.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoSendCommand.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/Utils.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/CommandParameterType.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/Conversions.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/DeviceMapping.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoAbstractHandler.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoUnsupportedHandler.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/robot/ConsumablesType.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/robot/FanModeType.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/robot/StatusType.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/robot/VacuumErrorType.java
Eliminating several of the @NonNullByDefault warnings for miio binding
> [miio] add @NonNullByDefault to cleanup some warnings

- bundles/org.openhab.binding.lgwebos/README.md
- bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/LGWebOSHandlerFactory.java
- bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/LGWebOSStateDescriptionOptionProvider.java
- bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/LauncherApplication.java
- bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/TVControlChannel.java
- bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/handler/LGWebOSHandler.java
> [lgwebos] Add dynamic options providers for application and channel

- bundles/org.openhab.binding.groheondus/pom.xml
- bundles/org.openhab.binding.groheondus/src/main/java/org/openhab/binding/groheondus/internal/discovery/GroheOndusDiscoveryService.java
- bundles/org.openhab.binding.groheondus/src/main/java/org/openhab/binding/groheondus/internal/handler/GroheOndusAccountHandler.java
- bundles/org.openhab.binding.groheondus/src/main/java/org/openhab/binding/groheondus/internal/handler/GroheOndusSenseGuardHandler.java
- bundles/org.openhab.binding.groheondus/src/main/java/org/openhab/binding/groheondus/internal/handler/GroheOndusSenseHandler.java
This is a pre-step for supporting more GROHE devices, see #4550 for
that. It also enables us to use a more reliable way to login with
username/password (even given it relies on the web-based form :P).
> [groheondus] Upgrade java API to latest version

- CODEOWNERS
- bom/openhab-addons/pom.xml
- bundles/org.openhab.binding.bluetooth.airthings/.classpath
- bundles/org.openhab.binding.bluetooth.airthings/.project
- bundles/org.openhab.binding.bluetooth.airthings/NOTICE
- bundles/org.openhab.binding.bluetooth.airthings/README.md
- bundles/org.openhab.binding.bluetooth.airthings/pom.xml
- bundles/org.openhab.binding.bluetooth.airthings/src/main/feature/feature.xml
- bundles/org.openhab.binding.bluetooth.airthings/src/main/java/org/openhab/binding/bluetooth/airthings/internal/AirthingsBindingConstants.java
- bundles/org.openhab.binding.bluetooth.airthings/src/main/java/org/openhab/binding/bluetooth/airthings/internal/AirthingsConfiguration.java
- bundles/org.openhab.binding.bluetooth.airthings/src/main/java/org/openhab/binding/bluetooth/airthings/internal/AirthingsDiscoveryParticipant.java
- bundles/org.openhab.binding.bluetooth.airthings/src/main/java/org/openhab/binding/bluetooth/airthings/internal/AirthingsHandler.java
- bundles/org.openhab.binding.bluetooth.airthings/src/main/java/org/openhab/binding/bluetooth/airthings/internal/AirthingsHandlerFactory.java
- bundles/org.openhab.binding.bluetooth.airthings/src/main/java/org/openhab/binding/bluetooth/airthings/internal/AirthingsParserException.java
- bundles/org.openhab.binding.bluetooth.airthings/src/main/java/org/openhab/binding/bluetooth/airthings/internal/AirthingsWavePlusDataParser.java
- bundles/org.openhab.binding.bluetooth.airthings/src/main/java/org/openhab/binding/bluetooth/airthings/internal/AirthingsWavePlusHandler.java
- bundles/org.openhab.binding.bluetooth.airthings/src/main/resources/ESH-INF/thing/airthings.xml
- bundles/org.openhab.binding.bluetooth.airthings/src/test/java/org/openhab/binding/bluetooth/airthings/AirthingsWavePlusParserTest.java
- bundles/pom.xml
> [airthings] Airthings bluetooth binding initial contribution

- bundles/org.openhab.binding.bluetooth.am43/src/main/java/org/openhab/binding/bluetooth/am43/internal/AM43DiscoveryParticipant.java
- bundles/org.openhab.binding.bluetooth.am43/src/main/java/org/openhab/binding/bluetooth/am43/internal/AM43Handler.java
Fixes: #7105 
Also properly discovers device by utilizing the previously unavailable bluetooth connection discovery feature.
> [bluetooth.am43] Fixed startup issue and implemented proper discovery

- bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/BluetoothDevice.java
- bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/discovery/internal/BluetoothDiscoveryProcess.java
> [bluetooth] Read device information during discovery process

- bundles/org.openhab.binding.bluetooth.airthings/src/main/java/org/openhab/binding/bluetooth/airthings/internal/AirthingsDiscoveryParticipant.java
> [bluetooth.airthing] Use connection based discovery

- bundles/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/handler/AdvancedMultisensorThingHandler.java
> [onewire] fix non-refreshing digital channels on AMS sensors

- bundles/org.openhab.binding.lghombot/src/main/java/org/openhab/binding/lghombot/internal/LGHomBotHandler.java
Just a small fix for when there is no response from the HomBot camera & stopping of timer when removing binding.
> [lghombot] Fixed NPE in camera handling.

- bundles/org.openhab.binding.lgwebos/README.md
> [lgwebos] Enhance README for appLauncher channel

- bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/TeslaBindingConstants.java
- bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaVehicleHandler.java
I don't own a Tesla, but I can help their owners to open their trunk/frunk. :wink: 
Fixes #7158
> [tesla] Use correct command for opening trunk/frunk

- bundles/org.openhab.binding.bluetooth.bluegiga/src/main/java/org/openhab/binding/bluetooth/bluegiga/BlueGigaBluetoothDevice.java
Split massive event handling procedure to dedicated event handlers. No
logic changes.
> [bluetooth.bluegiga] refactoring event handling

- buildci.sh
- itests/org.openhab.binding.mqtt.homeassistant.tests/itest.bndrun
- itests/org.openhab.binding.mqtt.homeassistant.tests/pom.xml
- itests/org.openhab.binding.mqtt.homeassistant.tests/src/main/java/org/openhab/binding/mqtt/HomeAssistantMQTTImplementationTest.java
- itests/org.openhab.binding.mqtt.homie.tests/pom.xml
- itests/org.openhab.io.mqttembeddedbroker.tests/pom.xml
- itests/pom.xml
- pom.xml
Reverts openhab/openhab-addons#7140
Upgrading bnd was unintended and obviously causes problems on Jenkins
> Revert "[itests mqtt.homeassistant] Fixed itests for mqtt.homeassistant"

- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/SomfyTahomaHandlerFactory.java
- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/discovery/SomfyTahomaItemDiscoveryService.java
- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaActionGroupHandler.java
- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaBridgeHandler.java
This is a bugfix version:
- fixed leakage of a scheduler during discovery
- fixed 2+ concurrent bridges malfunction because of one HttpClient sharing 
- fixed non working action groups
> [somfytahoma] bug fixes

- features/openhab-addons/pom.xml
Related to https://github.com/openhab/openhab-addons/pull/7109
> include configfiles in feature aggregation

- bundles/org.openhab.binding.insteon/pom.xml
> updated version for Insteon binding

- bundles/org.openhab.binding.doorbird/README.md
- bundles/org.openhab.binding.doorbird/pom.xml
- bundles/org.openhab.binding.doorbird/src/main/feature/feature.xml
- bundles/org.openhab.binding.doorbird/src/main/java/org/openhab/binding/doorbird/action/DoorbirdActions.java
- bundles/org.openhab.binding.doorbird/src/main/java/org/openhab/binding/doorbird/internal/DoorbirdBindingConstants.java
- bundles/org.openhab.binding.doorbird/src/main/java/org/openhab/binding/doorbird/internal/DoorbirdHandlerFactory.java
- bundles/org.openhab.binding.doorbird/src/main/java/org/openhab/binding/doorbird/internal/api/Authorization.java
- bundles/org.openhab.binding.doorbird/src/main/java/org/openhab/binding/doorbird/internal/api/DoorbirdAPI.java
- bundles/org.openhab.binding.doorbird/src/main/java/org/openhab/binding/doorbird/internal/api/DoorbirdImage.java
- bundles/org.openhab.binding.doorbird/src/main/java/org/openhab/binding/doorbird/internal/api/DoorbirdInfo.java
- bundles/org.openhab.binding.doorbird/src/main/java/org/openhab/binding/doorbird/internal/api/DoorbirdUnauthorizedException.java
- bundles/org.openhab.binding.doorbird/src/main/java/org/openhab/binding/doorbird/internal/api/SipStatus.java
- bundles/org.openhab.binding.doorbird/src/main/java/org/openhab/binding/doorbird/internal/config/ControllerConfiguration.java
- bundles/org.openhab.binding.doorbird/src/main/java/org/openhab/binding/doorbird/internal/config/DoorbellConfiguration.java
- bundles/org.openhab.binding.doorbird/src/main/java/org/openhab/binding/doorbird/internal/handler/ControllerHandler.java
- bundles/org.openhab.binding.doorbird/src/main/java/org/openhab/binding/doorbird/internal/handler/DoorbellHandler.java
- bundles/org.openhab.binding.doorbird/src/main/java/org/openhab/binding/doorbird/internal/listener/DoorbirdEvent.java
- bundles/org.openhab.binding.doorbird/src/main/java/org/openhab/binding/doorbird/internal/listener/DoorbirdUdpListener.java
- bundles/org.openhab.binding.doorbird/src/main/java/org/openhab/binding/doorbird/internal/model/DoorbirdInfoDTO.java
- bundles/org.openhab.binding.doorbird/src/main/java/org/openhab/binding/doorbird/internal/model/DoorbirdInfoJson.java
- bundles/org.openhab.binding.doorbird/src/main/java/org/openhab/binding/doorbird/internal/model/SipStatusDTO.java
- bundles/org.openhab.binding.doorbird/src/main/java/org/openhab/binding/doorbird/internal/model/SipStatusJson.java
- bundles/org.openhab.binding.doorbird/src/main/resources/ESH-INF/config/config.xml
- bundles/org.openhab.binding.doorbird/src/main/resources/ESH-INF/thing/thing-types.xml
- bundles/org.openhab.binding.doorbird/src/test/java/org/openhab/binding/doorbird/internal/DoorbirdInfoTest.java
- bundles/org.openhab.binding.doorbird/src/test/java/org/openhab/binding/doorbird/internal/SipStatusTest.java
- Added support for the A1081 Controller
- Added additional thing actions
- Refactored API out of handler into it's own classes)
Signed-off-by: Mark Hilbush mark@hilbush.com
> [doorbird] Add model A1081 controller and new actions

- bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/A5_30/A5_30_03.java
- bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/A5_30/A5_30_03_ELTAKO.java
This PR fixes two bugs for the EEP A5-30-03. Please see #7212
> [enocean] Fix EEP A5-30-03

- bundles/org.openhab.binding.denonmarantz/README.md
- bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/DenonMarantzBindingConstants.java
- bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/DenonMarantzState.java
- bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/connector/DenonMarantzConnector.java
- bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/connector/http/DenonMarantzHttpConnector.java
- bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/connector/telnet/DenonMarantzTelnetConnector.java
- bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/handler/DenonMarantzHandler.java
- bundles/org.openhab.binding.denonmarantz/src/main/resources/ESH-INF/thing/thing-types.xml
Fixes #7197
Signed-off-by: Jan-Willem Veldhuis <jwveldhuis@gmail.com>
> [denonmarantz] Add support for an optional Zone4.

- bundles/org.openhab.binding.neohub/src/main/java/org/openhab/binding/neohub/internal/NeoBaseHandler.java
- bundles/org.openhab.binding.neohub/src/main/java/org/openhab/binding/neohub/internal/NeoHubBindingConstants.java
- bundles/org.openhab.binding.neohub/src/main/java/org/openhab/binding/neohub/internal/NeoHubHandler.java
- bundles/org.openhab.binding.neohub/src/main/java/org/openhab/binding/neohub/internal/NeoHubSocket.java
Bug fix and cosmetic improvements:
- Fix blocking bug on socket read; a) using socket read timeout, and b) allowing socket calls in parallel
- Improved error handling
- Improved logger messages
> [neohub] fix blocking bug on socket read; improved error handling & logging

- bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/internal/DigiplexBindingConstants.java
> [digiplex] Update bridge channel names (#7225)

- bundles/org.openhab.binding.insteon/README.md
- bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/CommandHandler.java
- bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/DeviceFeature.java
- bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/DeviceFeatureListener.java
This PR fixes https://github.com/openhab/openhab-addons/issues/7089.
> [insteon] support the related parameter with broadcastOnOff channel

- bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java
> [rrd4j] Fixed database files location

- itests/org.openhab.persistence.mapdb.tests/.classpath
- itests/org.openhab.persistence.mapdb.tests/.project
- itests/org.openhab.persistence.mapdb.tests/NOTICE
- itests/org.openhab.persistence.mapdb.tests/itest.bndrun
- itests/org.openhab.persistence.mapdb.tests/pom.xml
- itests/org.openhab.persistence.mapdb.tests/src/main/java/org/openhab/persistence/mapdb/MapDbPersistenceServiceOSGiTest.java
- itests/pom.xml
> added missed mapdb itests

- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoBindingConfiguration.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoHandlerFactory.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoMessageListener.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/DeviceMapping.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/MiIoBasicChannel.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/MiIoBasicDevice.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/MiIoDatabaseWatchService.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/MiIoDeviceAction.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/discovery/MiIoDiscovery.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/discovery/MiIoDiscoveryParticipant.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoAbstractHandler.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoBasicHandler.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoGenericHandler.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoUnsupportedHandler.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoVacuumHandler.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/transport/MiIoAsyncCommunication.java
- bundles/org.openhab.binding.miio/src/test/java/org/openhab/binding/miio/internal/ReadmeHelper.java
no new functionality, just eliminating many warnings
> [miio] compiler warnings & spotbugs cleanup

- bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/handler/LGWebOSTVSocket.java
Also subscribe to "mastervolume_ext_speaker_lg_optical" volume change
events, which addresses #7207.
> [lgwebos] Fix mastervolume_ext_speaker_lg_optical volume subscription

- bundles/org.openhab.binding.openuv/README.md
- bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/OpenUVBindingConstants.java
- bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/OpenUVHandlerFactory.java
- bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/handler/OpenUVReportHandler.java
- bundles/org.openhab.binding.openuv/src/main/resources/ESH-INF/thing/thing-types.xml
This optional feature aims to address topic discussed [here](https://community.openhab.org/t/openuv-free-account-changes/65568/6)
Added a channel to follow sun elevation as provided by eg astro binding. If sun is below the horizon, no queries as pushed. If the channel is not feeded with data, existing behaviour remains the same.
I also made some code improvments while being on it.
> [OpenUV] Adding feature to suspend API queries at night

- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoBasicHandler.java
my last minute update to ,lowercase() went wrong in my PR...
> [miio] fix updating basic devices

- bundles/org.openhab.binding.sensibo/src/main/java/org/openhab/binding/sensibo/internal/CallbackChannelsTypeProvider.java
Signed-off-by: Arne Seime <arne.seime@gmail.com>
> [sensibo] Make code compile under openhab 3 as well

- bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/BaseChannelHandler.java
- bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/handler/LGWebOSTVSocket.java
> [lgwebos] Handle volume update whatever the audio output

- bundles/org.openhab.binding.gardena/README.md
This PR adapts the GARDENA readme file to the official wording.
> [gardena] Adapt to the official wording

- bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java
- features/openhab-addons-external/src/main/resources/conf/rrd4j.cfg
> [rrd4j] use a more fine granular default configuration for persistence

- bundles/org.openhab.binding.boschindego/pom.xml
> [boschindego] Fix dependency version for indego library

- bundles/org.openhab.binding.mail/README.md
- bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/action/SendMailActions.java
- bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/internal/SMTPHandler.java
- bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/internal/ServerSecurity.java
- bundles/org.openhab.binding.mail/src/main/resources/ESH-INF/binding/binding.xml
- bundles/org.openhab.binding.mail/src/main/resources/ESH-INF/i18n/mail_de.properties
- bundles/org.openhab.binding.mail/src/main/resources/ESH-INF/thing/thing-types.xml
> [mail] Correctly named STARTTLS and a few small improvements

- bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/handler/LGWebOSHandler.java
> [lgwebos] Fix initialize and dispose

- bundles/org.openhab.binding.nikohomecontrol/README.md
> [nikohomecontrol] Small README updates.

- itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/discovery/test/WemoDiscoveryOSGiTest.java
Related to https://github.com/openhab/openhab-core/issues/1408
> [wemo] Fix InboxFilterCriteria deprecation

- bundles/org.openhab.binding.nikohomecontrol/README.md
Signed-off-by: Dries Vandenneucker <dries.vandenneucker@yahoo.com>
> [nikohomecontrol] Small README update.

- bundles/org.openhab.binding.miio/README.md
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoDevices.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoBasicHandler.java
- bundles/org.openhab.binding.miio/src/main/resources/database/philips.light.bulb.json
- bundles/org.openhab.binding.miio/src/main/resources/database/philips.light.candle.json
- bundles/org.openhab.binding.miio/src/main/resources/database/philips.light.ceiling.json
- bundles/org.openhab.binding.miio/src/main/resources/database/philips.light.mono.json
- bundles/org.openhab.binding.miio/src/main/resources/database/philips.light.moonlight.json
- bundles/org.openhab.binding.miio/src/main/resources/database/philips.light.sread1.json
add s6 vacuum
https://community.openhab.org/t/xiaomi-robot-vacuum-binding/31317/1387
https://community.openhab.org/t/xiaomi-philips-wifi-bulb-binding/36571/10
> [miio] change brightness for Philips bulbs

- bundles/org.openhab.binding.weathercompany/README.md
Fix thing example in README to use the correct language specification.
> [weathercompany] Fix language in thing example

- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/WeatherUtils.java
This fixes https://github.com/openhab/openhab-addons/issues/7351.
Implemented the algorithm at https://www.wpc.ncep.noaa.gov/html/heatindex_equation.shtml.
> [netatmo] fix calculation for heat index

- bundles/org.openhab.binding.netatmo/README.md
- Fixed example Thing in README.md
> [netatmo] Fixed example Thing in README.md

- bundles/org.openhab.binding.minecraft/README.md
Added additional information specifically for defining 'things' via configuration files
Minor formatting changes
There's very little documentation for this plugin and very little information on the forums for how to use the Minecraft plugin. This information should help someone setting up the plugin for the first time.
> [minecraft] Added information for defining things for Minecraft plugin

- bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/KM200ChannelTypeProvider.java
- bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/handler/KM200ThingHandler.java
- bundles/org.openhab.binding.sensibo/src/main/java/org/openhab/binding/sensibo/internal/CallbackChannelsTypeProvider.java
- bundles/org.openhab.binding.vitotronic/src/main/java/org/openhab/binding/vitotronic/internal/discovery/VitotronicDiscoveryService.java
- itests/org.openhab.binding.ntp.tests/src/main/java/org/openhab/binding/ntp/test/NtpOSGiTest.java
- itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/test/GenericWemoOSGiTest.java
- Replaced deprecated constructors and methods from Thing API
- Implement `ChannelGroupTypeProvider` interface in addition to `ChannelTypeProvider` interface
Related to https://github.com/openhab/openhab-core/pull/1414
> Replaced deprecated constructors and methods from Thing API

- bundles/org.openhab.binding.gardena/src/main/resources/ESH-INF/thing/thing-types.xml
- bundles/org.openhab.binding.miio/src/main/resources/ESH-INF/thing/commonChannels.xml
- bundles/org.openhab.binding.nest/src/main/resources/ESH-INF/thing/channels.xml
- bundles/org.openhab.binding.phc/src/main/resources/ESH-INF/thing/channel-types.xml
- bundles/org.openhab.binding.shelly/src/main/resources/ESH-INF/thing/device.xml
- bundles/org.openhab.binding.systeminfo/src/main/resources/ESH-INF/thing/channels.xml
- Removed `advanced` attribute from channel-group-types
See https://github.com/openhab/openhab-core/pull/1410
> Removed 'advanced' attribute from channel-group-types

- bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/AbstractBluetoothBridgeHandler.java
> [bluetooth] Fix for concurrent modification exception during shutdown.

- bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/PioneerAvrBindingConstants.java
- bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/discovery/PioneerAvrDiscoveryParticipant.java
- bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/handler/AvrHandlerFactory.java
- bundles/org.openhab.binding.pioneeravr/src/main/resources/ESH-INF/thing/thing-types.xml
This improvement of the PioneerAVR binding adds support for the models @mstormi provided under the assumption that
the features remained the same since 2015.
The models' functionality remains split and is
easy to enhance with model-year-specific properties later on.
closes #7315
Also-by: Markus Storm <markus.storm@gmx.net>
Signed-off-by: Leroy Foerster <gersilex@gmail.com>
> [pioneeravr] Add models up until year 2020

- bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/discovery/LGWebOSUpnpDiscoveryParticipant.java
> [lgwebos] Fix property modelName

- bundles/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/SpotifyBindingConstants.java
- bundles/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/api/model/Item.java
- bundles/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/handler/SpotifyBridgeHandler.java
- bundles/org.openhab.binding.spotify/src/main/resources/ESH-INF/thing/thing-types.xml
> [Spotify] Added channel to display if track is explicit

- bundles/org.openhab.binding.spotify/README.md
Forgotten readme update of #7388
> [spotify] Updated readme related to new explicit channel

- bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/LauncherApplication.java
- bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/PowerControlPower.java
- bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/handler/LGWebOSHandler.java
- bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/handler/LGWebOSTVSocket.java
> [lgwebos] Fix missing update of power channel state

- CODEOWNERS
- bom/openhab-addons/pom.xml
- bundles/org.openhab.binding.linky/.classpath
- bundles/org.openhab.binding.linky/.project
- bundles/org.openhab.binding.linky/NOTICE
- bundles/org.openhab.binding.linky/README.md
- bundles/org.openhab.binding.linky/pom.xml
- bundles/org.openhab.binding.linky/src/main/feature/feature.xml
- bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/ExpiringDayCache.java
- bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/LinkyBindingConstants.java
- bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/LinkyConfiguration.java
- bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/LinkyHandlerFactory.java
- bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/console/LinkyCommandExtension.java
- bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/handler/LinkyCookieJar.java
- bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/handler/LinkyHandler.java
- bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/model/LinkyConsumptionData.java
- bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/model/LinkyTimeScale.java
- bundles/org.openhab.binding.linky/src/main/resources/ESH-INF/binding/binding.xml
- bundles/org.openhab.binding.linky/src/main/resources/ESH-INF/thing/thing-types.xml
- bundles/pom.xml
> [linky] Linky binding

- bundles/org.openhab.binding.sensebox/src/main/resources/ESH-INF/binding/binding.xml
- bundles/org.openhab.binding.sensebox/src/main/resources/ESH-INF/config/config-description.xml
- bundles/org.openhab.binding.sensebox/src/main/resources/ESH-INF/i18n/sensebox_de.properties
- bundles/org.openhab.binding.sensebox/src/main/resources/ESH-INF/thing/box.xml
- bundles/org.openhab.binding.sensebox/src/main/resources/ESH-INF/thing/channels.xml
- Added German translations
- Switch to [default system channel-types](https://www.openhab.org/docs/developer/bindings/thing-xml.html#system-state-channel-types)
> [sensebox] Added German translations

- bundles/org.openhab.binding.nikohomecontrol/README.md
Update some text on thermostat configuration and constraints.
> [nikohomecontrol] Update to README.

- bundles/org.openhab.binding.bosesoundtouch/src/main/java/org/openhab/binding/bosesoundtouch/internal/discovery/SoundTouchDiscoveryParticipant.java
- bundles/org.openhab.binding.vitotronic/src/main/java/org/openhab/binding/vitotronic/internal/discovery/VitotronicDiscoveryService.java
- Replaced deprecated methods from Thing API
Related to openhab/openhab-core#1414
> Replaced deprecated methods from Thing API

- bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/LGWebOSBindingConstants.java
- bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/discovery/LGWebOSUpnpDiscoveryParticipant.java
- bundles/org.openhab.binding.lgwebos/src/main/resources/ESH-INF/thing/thing-types.xml
> [lgwebos] Use system properties when available

- bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/KM200BindingConstants.java
- bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/KM200Comm.java
- bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/KM200Cryption.java
- bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/KM200Device.java
- bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/KM200HandlerFactory.java
- bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/KM200ServiceObject.java
- bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/KM200Utils.java
- bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/discovery/KM200GatewayDiscoveryParticipant.java
- bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/discovery/KM200GatewayDiscoveryService.java
- bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/handler/KM200DataHandler.java
- bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/handler/KM200ErrorServiceHandler.java
- bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/handler/KM200GatewayHandler.java
- bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/handler/KM200GatewayStatusListener.java
- bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/handler/KM200ServiceHandler.java
- bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/handler/KM200SwitchProgramServiceHandler.java
- bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/handler/KM200ThingHandler.java
- bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/handler/KM200VirtualServiceHandler.java
Bugfixing and optimizations for the km200 binding.
- Replaced depreced Date/Time code
- Fixed problem with fraction of numbers
- Added @NonNullByDefault annotation to classes
- Fixed problems on dispose
- Removed almost all warnings
- Small bugfixes
> [km200] bugfixing and optimization

- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoCommand.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/ActionConditions.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoBasicHandler.java
- bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.light.color1.json
- bundles/org.openhab.binding.miio/src/test/java/org/openhab/binding/miio/internal/ActionConditionTest.java
* fix yeelight delay channel
* allow better control for Color item
* Allow for google home  support without rules
* make yeelight dimmer more intuitive
https://community.openhab.org/t/xiaomi-robot-vacuum-binding/31317/1418
> [miio] Improve Yeelight Color channel

- bundles/create_openhab_binding_skeleton.cmd
- bundles/create_openhab_binding_skeleton.sh
- itests/org.openhab.binding.astro.tests/itest.bndrun
- itests/org.openhab.binding.avmfritz.tests/itest.bndrun
- itests/org.openhab.binding.feed.tests/itest.bndrun
- itests/org.openhab.binding.hue.tests/itest.bndrun
- itests/org.openhab.binding.max.tests/itest.bndrun
- itests/org.openhab.binding.modbus.tests/itest.bndrun
- itests/org.openhab.binding.nest.tests/itest.bndrun
- itests/org.openhab.binding.ntp.tests/itest.bndrun
- itests/org.openhab.binding.systeminfo.tests/itest.bndrun
- itests/org.openhab.binding.tradfri.tests/itest.bndrun
- itests/org.openhab.binding.wemo.tests/itest.bndrun
- itests/org.openhab.io.hueemulation.tests/itest.bndrun
- Fix missing 2.5.5-SNAPSHOT changes
> Fix missing 2.5.5-SNAPSHOT changes

- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/discovery/HueLightDiscoveryService.java
> [hue] Remove older discovery results from the current bridge only

- bundles/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/discovery/XiaomiBridgeDiscoveryService.java
- bundles/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/handler/XiaomiBridgeHandler.java
- bundles/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/socket/XiaomiBridgeSocket.java
- bundles/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/socket/XiaomiDiscoverySocket.java
- bundles/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/socket/XiaomiSocket.java
- bundles/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/socket/XiaomiSocketListener.java
> [mihome] Fix NPE, add null annotations and name threads

- bundles/org.openhab.io.openhabcloud/README.md
Make it more clear that users do not need to expose Items for integration with Alexa or Google Assistant, only IFTTT. Also mention that the feature is turned off anyway.
Signed off by Richard Koshak: rlkoshak@gmail.com
> [openhabcloud] Clarify exposing Items

- bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/handler/ZonePlayerHandler.java
Optimize the UPnP calls in the polling job
> [sonos] Avoid concurrent execution of the polling job

- bundles/org.openhab.binding.samsungtv/README.md
- bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/WakeOnLanUtility.java
- bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/handler/SamsungTvHandler.java
- bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/service/MainTVServerService.java
- bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/service/MediaRendererService.java
- bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/service/RemoteControllerService.java
- bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/service/ServiceFactory.java
WOL utility enhanced to work on different OS (enhancement coming form the LG webOS binding)
Existent polling jobs in services classes replaced by one unique polling job in the thing handler. Execute UPnP actions to refresh channels only if the channel is linked.
> [samsungtv] Few improvements

- bundles/org.openhab.binding.coolmasternet/src/main/java/org/openhab/binding/coolmasternet/internal/ControllerHandler.java
A more detailed discussion is in the [bug report](https://github.com/openhab/openhab-addons/issues/7333), but in summary:
* Gracefully handle unsolicited socket opening prompt
* Sink existing socket buffers in a deterministic manner
* Prevent socket close due to try-with-resources cleanup
* Send LF (nor CRLF) as per [CoolMasterNet PRM](https://coolautomation.com/wp-content/uploads/sites/2/2019/11/CMN5-PRM.pdf)
Tested locally including monitoring air conditioner state changes (using the manual control panel and also the CoolRemote mobile application) and sending commands (ie power, fan speed, mode, set temperature).
> [coolmasternet] Fix buffer handling (fixes #7333)

- bundles/org.openhab.binding.astro/README.md
- bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/handler/AstroThingHandler.java
- bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/model/Season.java
- bundles/org.openhab.binding.astro/src/main/resources/ESH-INF/thing/channels.xml
> [Astro] Adding next season

- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueLightHandler.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueSensorHandler.java
> [hue] Little optimization in light and sensor handlers

- bundles/org.openhab.binding.hue/src/main/resources/ESH-INF/thing/ColorLight.xml
- bundles/org.openhab.binding.hue/src/main/resources/ESH-INF/thing/ColorTemperatureLight.xml
- bundles/org.openhab.binding.hue/src/main/resources/ESH-INF/thing/DimmableLight.xml
- bundles/org.openhab.binding.hue/src/main/resources/ESH-INF/thing/DimmablePlug.xml
- bundles/org.openhab.binding.hue/src/main/resources/ESH-INF/thing/ExtendedColorLight.xml
> [hue] Add unit to the fadetime configuration setting

- bundles/org.openhab.binding.netatmo/src/main/resources/ESH-INF/config/config.xml
> [netatmo] Add unit to few configuration settings

- bundles/org.openhab.binding.astro/src/main/resources/ESH-INF/config/config.xml
> [astro] Add unit to few configuration settings

- bundles/org.openhab.binding.freebox/src/main/resources/ESH-INF/thing/thing-types.xml
> [freebox] Add unit to few configuration settings

- bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaVehicleHandler.java
Related to https://github.com/openhab/openhab-core/pull/1443
> [tesla] removed glassfish dependencies

- bundles/org.openhab.binding.neeo/.classpath
- bundles/org.openhab.binding.neeo/NOTICE
- bundles/org.openhab.binding.neeo/pom.xml
- bundles/org.openhab.binding.neeo/src/3rdparty/java/org/glassfish/jersey/filter/LoggingFilter.java
- bundles/org.openhab.io.neeo/.classpath
- bundles/org.openhab.io.neeo/NOTICE
- bundles/org.openhab.io.neeo/pom.xml
- bundles/org.openhab.io.neeo/src/3rdparty/java/org/glassfish/jersey/filter/LoggingFilter.java
related to openhab/openhab-core#1443
> [neeo] removed dependencies to Jersey

- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/HueBridge.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueBridgeHandler.java
> [hue] Command for group sent asynchronously

- bundles/org.openhab.binding.telegram/README.md
Update readme with multiple chat ids example
Signed-off-by: Holger Eisold kugelsicha@gmail.com
> [telegram] Update readme with multiple chat ids example

- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/robot/RRMapDraw.java
avoiding  java.lang.Error: Probable fatal error:No fonts found
as reported in
https://community.openhab.org/t/xiaomi-robot-vacuum-binding/31317/1435
> [miio] avoid font error

- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoHandlerFactory.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/Utils.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/cloud/CloudConnector.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/discovery/MiIoDiscoveryParticipant.java
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/transport/MiIoAsyncCommunication.java
- bundles/org.openhab.binding.miio/src/test/java/org/openhab/binding/miio/internal/UtilsTest.java
resolves some less common issues
* Startup sequence issue
* Loglevel cloud
* Some token length giving errors
* did > maxInt
> [miio] Resolve minor issues

- bundles/org.openhab.binding.homematic/src/main/resources/homematic/extra-descriptions.properties
- bundles/org.openhab.binding.homematic/src/main/resources/homematic/extra-descriptions_de.properties
I added more HomeMatic IP devices to the descriptions
> [homematic] more HomeMatic IP devices

- bundles/org.openhab.binding.insteon/README.md
- bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/MessageHandler.java
- bundles/org.openhab.binding.insteon/src/main/resources/ESH-INF/thing/thing-types.xml
Also fixed a couple of typos in the example.
> [insteon] use correct units of measure for watts and kWh

- bundles/org.openhab.binding.lametrictime/src/main/java/org/openhab/binding/lametrictime/internal/GsonProvider.java
Outch, this fix took me almost 2 hours to figure out... But at least I did @wborn!
Fixes https://github.com/openhab/openhab-addons/issues/7566
> [lametrictime] fixed json parsing of specific types

- bundles/org.openhab.binding.coolmasternet/src/main/java/org/openhab/binding/coolmasternet/internal/ControllerHandler.java
- bundles/org.openhab.binding.coolmasternet/src/main/java/org/openhab/binding/coolmasternet/internal/CoolMasterNetBindingConstants.java
- bundles/org.openhab.binding.coolmasternet/src/main/java/org/openhab/binding/coolmasternet/internal/CoolMasterNetHandlerFactory.java
- bundles/org.openhab.binding.coolmasternet/src/main/java/org/openhab/binding/coolmasternet/internal/handler/HVACHandler.java
- bundles/org.openhab.binding.coolmasternet/src/main/resources/ESH-INF/thing/thing-types.xml
Please refer to the Git commit message for details.
The only functional improvement in this commit is the polling is much faster, as it now differentiates between an existing connection and a new connection.
> [coolmasternet] General tidy up of addon

- bundles/org.openhab.persistence.dynamodb/src/main/java/org/openhab/persistence/dynamodb/internal/DynamoDBConfig.java
- bundles/org.openhab.persistence.dynamodb/src/main/java/org/openhab/persistence/dynamodb/internal/DynamoDBPersistenceService.java
- bundles/org.openhab.persistence.dynamodb/src/test/java/org/openhab/persistence/dynamodb/internal/DynamoDBConfigTest.java
This will make it nice and quiet initially, see https://github.com/openhab/openhab-addons/pull/7594#issuecomment-626388795.
> [dynamodb] Tune logging for initial configuration

- bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/EcobeeBindingConstants.java
- bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/discovery/SensorDiscoveryService.java
- bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/discovery/ThermostatDiscoveryService.java
- bundles/org.openhab.binding.ecobee/src/main/resources/ESH-INF/thing/thing-types.xml
Add `representaion-property` in thing XML.
Also run spotless.
> [ecobee] Add representation-property to thing XML

- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoAbstractHandler.java
> [miio] Kill created thread when connection is failing

- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoAbstractHandler.java
> [miio] Check configuration settings to avoid NPE

- bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosBindingConstants.java
- bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/handler/ZonePlayerHandler.java
- bundles/org.openhab.binding.sonos/src/main/resources/ESH-INF/thing/Amp.xml
> [sonos] Support for Sonos Amp device

- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoBasicHandler.java
> [miio] Use dispose() from the abstract class

- bundles/org.openhab.binding.volvooncall/README.md
- bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/VolvoOnCallBindingConstants.java
- bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/VolvoOnCallException.java
- bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/VolvoOnCallHandlerFactory.java
- bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/action/VolvoOnCallActions.java
- bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/config/VehicleConfiguration.java
- bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/config/VolvoOnCallBridgeConfiguration.java
- bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/discovery/VolvoOnCallDiscoveryService.java
- bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/dto/AccountVehicleRelation.java
- bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/dto/Attributes.java
- bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/dto/Heater.java
- bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/dto/Position.java
- bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/dto/PositionData.java
- bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/dto/PostResponse.java
- bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/dto/Status.java
- bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/dto/TripDetail.java
- bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/dto/Trips.java
- bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/dto/Vehicles.java
- bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/dto/VocAnswer.java
- bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/handler/VehicleHandler.java
- bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/handler/VolvoOnCallBridgeHandler.java
- bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/wrapper/VehiclePositionWrapper.java
> [VolvoOnCall] Correcting NPE on certain models

- bundles/org.openhab.binding.digiplex/pom.xml
- bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/internal/DigiplexHandlerFactory.java
- bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/internal/handler/DigiplexBridgeHandler.java
- bundles/org.openhab.binding.lutron/pom.xml
Related to #7573
Also removes the gnu.io import from the lutron POM, related to #7609.
> [digiplex] Use serial transport

- bundles/org.openhab.binding.elerotransmitterstick/pom.xml
- bundles/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/EleroTransmitterStickHandlerFactory.java
- bundles/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/handler/EleroTransmitterStickHandler.java
- bundles/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/stick/SerialConnection.java
- bundles/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/stick/TransmitterStick.java
> [elerotransmitterstick] Use serial transport

- bundles/org.openhab.binding.opengarage/src/main/java/org/openhab/binding/opengarage/internal/OpenGarageBindingConstants.java
- bundles/org.openhab.binding.opengarage/src/main/java/org/openhab/binding/opengarage/internal/OpenGarageHandler.java
- bundles/org.openhab.binding.opengarage/src/main/resources/ESH-INF/thing/thing-types.xml
> [opengarage] Use option states for vehicle status, small formatting improvements.

- bundles/org.openhab.binding.lgtvserial/pom.xml
- bundles/org.openhab.binding.lgtvserial/src/main/java/org/openhab/binding/lgtvserial/internal/LgTvSerialHandlerFactory.java
- bundles/org.openhab.binding.lgtvserial/src/main/java/org/openhab/binding/lgtvserial/internal/handler/LgTvSerialHandler.java
- bundles/org.openhab.binding.lgtvserial/src/main/java/org/openhab/binding/lgtvserial/internal/protocol/serial/LGSerialCommunicator.java
- bundles/org.openhab.binding.lgtvserial/src/main/java/org/openhab/binding/lgtvserial/internal/protocol/serial/SerialCommunicatorFactory.java
> [lgtvserial] Use serial transport

- bundles/org.openhab.binding.rme/pom.xml
- bundles/org.openhab.binding.rme/src/main/java/org/openhab/binding/rme/internal/RMEHandlerFactory.java
- bundles/org.openhab.binding.rme/src/main/java/org/openhab/binding/rme/internal/handler/RMEThingHandler.java
- bundles/org.openhab.binding.rme/src/main/java/org/openhab/binding/rme/internal/handler/SerialThingHandler.java
> [rme] Use serial transport

- bundles/org.openhab.binding.urtsi/pom.xml
- bundles/org.openhab.binding.urtsi/src/main/java/org/openhab/binding/urtsi/internal/UrtsiHandlerFactory.java
- bundles/org.openhab.binding.urtsi/src/main/java/org/openhab/binding/urtsi/internal/handler/UrtsiDeviceHandler.java
> [urtsi] Use serial transport

- bundles/org.openhab.binding.shelly/README.md
It seems like the documentation of the Shelly-RGBW2 seems to be incorrect.
Imho the channels described here are the correct ones:
https://github.com/openhab/openhab-addons/blob/7628135323df6f07e3c2993d7b816a16e334d849/bundles/org.openhab.binding.shelly/src/main/resources/ESH-INF/thing/lights.xml#L118-L131
- [shelly] fixes documentation of shellyrgbw2 channels
> [shelly] fixes documentation for shellyrgbw2 channels

- bundles/org.openhab.binding.velbus/pom.xml
- bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/VelbusHandlerFactory.java
- bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusBridgeHandler.java
> [velbus] Use serial transport

- bundles/org.openhab.binding.sonos/README.md
- bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosBindingConstants.java
- bundles/org.openhab.binding.sonos/src/main/resources/ESH-INF/thing/Port.xml
> [sonos] Support for Sonos Port device

- bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusBridgeHandler.java
See: https://github.com/openhab/openhab-addons/pull/7641#discussion_r425352408
> [velbus] Remove removeEventListener on dispose

- bundles/org.openhab.binding.weathercompany/README.md
- bundles/org.openhab.binding.weathercompany/src/main/java/org/openhab/binding/weathercompany/internal/discovery/WeatherCompanyDiscoveryService.java
Correct errors in the .things file example and add BridgeUID to the thing discovery.
> [weathercompany] Fix things file example

- bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/AVMFritzBaseBridgeHandler.java
- bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/AVMFritzBaseThingHandler.java
- bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/GroupHandler.java
- bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/Powerline546EHandler.java
- bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/hardware/FritzAhaContentExchange.java
- bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/hardware/FritzAhaWebInterface.java
- Structural code improvements
> [avmfritz] Structural code improvements

- bundles/org.openhab.binding.volvooncall/README.md
- bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/VolvoOnCallBindingConstants.java
- bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/dto/Status.java
- bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/handler/VehicleHandler.java
- bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/handler/VolvoOnCallBridgeHandler.java
- bundles/org.openhab.binding.volvooncall/src/main/resources/ESH-INF/thing/vehicle.xml
> [VoC] carLocked never gets updated

- bundles/org.openhab.binding.lgwebos/README.md
- bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/LauncherApplication.java
- bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/TVControlChannel.java
- bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/console/LGWebOSCommandExtension.java
- bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/handler/LGWebOSHandler.java
> [lgwebos] Console commands to list applications and channels

- bundles/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/handler/GardenaAccountHandler.java
- bundles/org.openhab.binding.heos/src/main/java/org/openhab/binding/heos/handler/HeosBridgeHandler.java
- bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/handler/HomematicBridgeHandler.java
- bundles/org.openhab.binding.phc/src/main/java/org/openhab/binding/phc/internal/handler/PHCBridgeHandler.java
- bundles/org.openhab.binding.sleepiq/src/main/java/org/openhab/binding/sleepiq/internal/discovery/SleepIQBedDiscoveryService.java
- bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/discovery/SqueezeBoxPlayerDiscoveryParticipant.java
- bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/handler/utils/ThingConfiguration.java
- bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/handler/utils/ThingProperty.java
- bundles/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/internal/discovery/ZoneMinderDiscoveryService.java
- Removed `getThingByUID()` method from `BaseBridgeHandler`
Related to https://github.com/openhab/openhab-core/pull/1465
> Removed 'getThingByUID()' method from 'BaseBridgeHandler'

- bundles/org.openhab.binding.lgwebos/README.md
> [lgwebos] Fix documentation

- bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/InsteonBinding.java
- bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/DeviceFeature.java
- bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/InsteonDevice.java
- bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/MessageDispatcher.java
- bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/MessageHandler.java
- bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/ModemDBBuilder.java
- bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/driver/Driver.java
- bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/driver/Port.java
- bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/message/MsgListener.java
Multiple ports was implemented but never supported in the original insteonplm binding nor the current binding. This PR remove the unnecessary code for multiple ports.
> [insteon] remove support for multiple ports

- bundles/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/FreeboxHandlerFactory.java
> [freebox] Handler factory activation simplified

- bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/RFXComHandlerFactory.java
> [rfxcom] Handler factory activation simplified

- bundles/org.openhab.binding.weatherunderground/src/main/java/org/openhab/binding/weatherunderground/internal/WeatherUndergroundBindingConstants.java
- bundles/org.openhab.binding.weatherunderground/src/main/java/org/openhab/binding/weatherunderground/internal/WeatherUndergroundHandlerFactory.java
> [weatherunderground] Handler factory activation simplified

- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/NetatmoHandlerFactory.java
> [netatmo] Handler factory activation simplified

- bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/RotelHandlerFactory.java
> [rotel] Handler factory activation simplified

- bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/SonyProjectorHandlerFactory.java
> [sonyprojector] Handler factory activation simplified

- bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/PowermaxBindingConstants.java
- bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/PowermaxHandlerFactory.java
> [powermax] Handler factory activation simplified

- bundles/org.openhab.binding.bigassfan/src/main/java/org/openhab/binding/bigassfan/internal/BigAssFanHandlerFactory.java
> [bigassfan] Use constructor injection

- bundles/org.openhab.binding.globalcache/src/main/java/org/openhab/binding/globalcache/internal/GlobalCacheHandlerFactory.java
> [globalcache] Use constructor injection

- bundles/create_openhab_binding_skeleton.cmd
- bundles/create_openhab_binding_skeleton.sh
- itests/org.openhab.binding.astro.tests/itest.bndrun
- itests/org.openhab.binding.avmfritz.tests/itest.bndrun
- itests/org.openhab.binding.feed.tests/itest.bndrun
- itests/org.openhab.binding.hue.tests/itest.bndrun
- itests/org.openhab.binding.max.tests/itest.bndrun
- itests/org.openhab.binding.modbus.tests/itest.bndrun
- itests/org.openhab.binding.nest.tests/itest.bndrun
- itests/org.openhab.binding.ntp.tests/itest.bndrun
- itests/org.openhab.binding.systeminfo.tests/itest.bndrun
- itests/org.openhab.binding.tradfri.tests/itest.bndrun
- itests/org.openhab.binding.wemo.tests/itest.bndrun
- itests/org.openhab.io.hueemulation.tests/itest.bndrun
Fixes https://github.com/openhab/openhab-addons/issues/7683
> Fix missing 2.5.6-SNAPSHOT changes

- bundles/org.openhab.binding.ntp/src/main/java/org/openhab/binding/ntp/internal/NtpBindingConstants.java
- bundles/org.openhab.binding.ntp/src/main/java/org/openhab/binding/ntp/internal/NtpHandlerFactory.java
> [ntp] Handler factory activation simplified

- bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/handler/RFXComHandler.java
> [rfxcom] OFFLINE status detail

- bundles/org.openhab.binding.weatherunderground/src/main/java/org/openhab/binding/weatherunderground/internal/handler/WeatherUndergroundHandler.java
> [weatherunderground] OFFLINE status detail

- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueBridgeHandler.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueGroupHandler.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueLightHandler.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueSensorHandler.java
> [hue] OFFLINE status detail

- bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/PowermaxBindingConstants.java
- bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/PowermaxHandlerFactory.java
- bundles/org.openhab.binding.yeelight/README.md
- bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/YeelightHandlerFactory.java
- bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/discovery/YeelightDiscoveryService.java
- bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/handler/YeelightCeilingWithNightHandler.java
- bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/handler/YeelightHandlerBase.java
- bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/device/CeilingDeviceWithNightDevice.java
- bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/device/DeviceFactory.java
- bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/device/MethodFactory.java
- bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/services/DeviceManager.java
- bundles/org.openhab.binding.yeelight/src/main/resources/ESH-INF/thing/ceiling1.xml
- bundles/org.openhab.binding.yeelight/src/test/java/org/openhab/binding/yeelight/internal/YeelightHandlerFactoryTest.java
Signed-off-by: Nikita Pogudalov <dragonnp@ya.ru>
Support Yeelight Ceiling Light 1 with night mode
- [yeelight] Added Ceiling 1 support
- Add support for Yeelight Ceiling Light with night mode
- In this update, you can add Yeelight Ceiling 1 devices with night mode. Updated README
You can download the JAR file from this link: https://drive.google.com/open?id=1dtmXRw_gESHKkrOTgbh-lQzMZnflhU0w
> [yeelight] Added support Ceiling 1 with Night Mode

- bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/handler/AbstractOpenWeatherMapHandler.java
- bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/handler/OpenWeatherMapUVIndexHandler.java
- bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/handler/OpenWeatherMapWeatherAndForecastHandler.java
> [openweathermap] bridge / thing handling

- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/AbstractNetatmoThingHandler.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/NetatmoDeviceHandler.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/NetatmoModuleHandler.java
> [netatmo] bridge / thing handling

- bundles/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/handler/YamahaBridgeHandler.java
- bundles/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/handler/YamahaZoneThingHandler.java
> [yamahareceiver] Let the framework call bridgeStatusChanged

- bundles/org.openhab.io.mqttembeddedbroker/README.md
> [mqttembeddedbroker] add deprecation note

- bundles/org.openhab.binding.darksky/src/main/java/org/openhab/binding/darksky/internal/config/DarkSkyChannelConfiguration.java
- bundles/org.openhab.binding.darksky/src/main/java/org/openhab/binding/darksky/internal/connection/DarkSkyConnection.java
- bundles/org.openhab.binding.darksky/src/main/java/org/openhab/binding/darksky/internal/handler/DarkSkyAPIHandler.java
- bundles/org.openhab.binding.darksky/src/main/java/org/openhab/binding/darksky/internal/handler/DarkSkyWeatherAndForecastHandler.java
- Removed dependency on `org.apache.commons.lang`
> [darksky] Removed dependency on 'org.apache.commons.lang'

- bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/connection/OpenWeatherMapConnection.java
- bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/handler/AbstractOpenWeatherMapHandler.java
- bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/handler/OpenWeatherMapAPIHandler.java
- Removed dependency on `org.apache.commons.lang`
> [openweathermap] Removed dependency on 'org.apache.commons.lang'

- bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/AstroBindingConstants.java
- bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/AstroHandlerFactory.java
> [astro] Handler factory activation simplified

- bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/handler/SamsungTvHandler.java
- bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/protocol/WebSocketV2.java
> [samsungtv] Removed dependency on 'org.apache.commons.lang'

- bundles/org.openhab.binding.alarmdecoder/README.md
Fixes some errors in the README.md file.
> [alarmdecoder] Documentation update

- bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/handler/PowermaxThingHandler.java
> [powermax] Move the check of configuration settings

- bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/connector/RFXComJD2XXConnector.java
- bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/connector/RFXComSerialConnector.java
- bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/connector/RFXComTcpConnector.java
> [rfxcom] Removed dependency on 'org.apache.commons.io.IOUtils'

- bundles/org.openhab.voice.pollytts/README.md
Signed-off-by: Breland Miley <breland@bdawg.org>
> [pollytts] Add text based configuration instructions to docs

- bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/discovery/KodiUpnpDiscoveryParticipant.java
- bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/handler/KodiHandler.java
- bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/protocol/KodiConnection.java
- Removed dependency on `org.apache.commons.lang`
> [kodi] Removed dependency on 'org.apache.commons.lang'

- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaAdjustableSlatsRollerShutterHandler.java
- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaAwningHandler.java
- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaBaseThingHandler.java
- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaRollerShutterHandler.java
- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaSilentRollerShutterHandler.java
- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaVenetianBlindHandler.java
- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaWindowHandler.java
This PR fixes bug 
https://github.com/openhab/openhab-addons/issues/7584
it is confirmed working
> [somfytahoma] fixed error when dimmer sends decimal values

- bundles/org.openhab.binding.allplay/src/main/java/org/openhab/binding/allplay/internal/handler/AllPlayHandler.java
- Fixed usage of deprecated constructor for `RawType`
Related to https://github.com/openhab/openhab-core/issues/1408
> [allplay] Fixed usage of deprecated constructor for 'RawType'

- bundles/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/ws/services/IhcAirlinkManagementService.java
- bundles/org.openhab.binding.ihc/src/test/java/org/openhab/binding/ihc/internal/ws/services/IhcAirlinkManagementServiceTest.java
- bundles/org.openhab.binding.ihc/src/test/resources/GetEmptyDetectedDeviceListResponse.xml
> [ihc] Fixed empty RF device list parsing

- bundles/org.openhab.persistence.dynamodb/src/main/java/org/openhab/persistence/dynamodb/internal/DynamoDBPersistenceService.java
- bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/InfluxDBPersistenceService.java
- bundles/org.openhab.voice.googletts/src/main/java/org/openhab/voice/googletts/internal/GoogleTTSService.java
Related to: openhab/openhab-core#1491
> Fix ConfigurableService deprecations

- bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/transceiver/EnOceanTransceiver.java
> [enocean] Removed dependency on 'org.apache.commons.io.IOUtils'

- bundles/org.openhab.binding.oceanic/src/main/java/org/openhab/binding/oceanic/internal/handler/NetworkOceanicThingHandler.java
- bundles/org.openhab.binding.oceanic/src/main/java/org/openhab/binding/oceanic/internal/handler/SerialOceanicThingHandler.java
> [oceanic] Removed dependency on 'org.apache.commons.io.IOUtils'

- bundles/org.openhab.binding.rme/src/main/java/org/openhab/binding/rme/internal/handler/SerialThingHandler.java
> [rme] Removed dependency on 'org.apache.commons.io.IOUtils'

- bundles/org.openhab.binding.urtsi/src/main/java/org/openhab/binding/urtsi/internal/handler/UrtsiDeviceHandler.java
> [urtsi] Removed dependency on 'org.apache.commons.io.IOUtils'

- bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/connector/RFXComTcpConnector.java
> [rfxcom] In/out streams closed when the socket is closed

- bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/handler/ZonePlayerHandler.java
> [sonos] Removed usage of org.apache.commons.lang.StringUtils

- bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/TeslaHandlerFactory.java
- bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaAccountHandler.java
- bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaVehicleHandler.java
Fixes https://github.com/openhab/openhab-addons/issues/7775
> [tesla] Use CXF JAX-RS client builder, if available.

- bundles/org.openhab.binding.lametrictime/src/main/java/org/openhab/binding/lametrictime/internal/LaMetricTimeHandlerFactory.java
- bundles/org.openhab.binding.lametrictime/src/main/java/org/openhab/binding/lametrictime/internal/handler/LaMetricTimeHandler.java
> [lametrictime] Use CXF JAX-RS client builder, if available

- bundles/org.openhab.io.mqttembeddedbroker/src/main/java/org/openhab/io/mqttembeddedbroker/internal/EmbeddedBrokerService.java
See: https://ci.openhab.org/job/openHAB-Addons-port/138/console
Related to: https://github.com/openhab/openhab-core/pull/1491
> Fix add-ons port

- bundles/org.openhab.binding.weatherunderground/src/main/java/org/openhab/binding/weatherunderground/internal/handler/WeatherUndergroundBridgeHandler.java
- bundles/org.openhab.binding.weatherunderground/src/main/java/org/openhab/binding/weatherunderground/internal/handler/WeatherUndergroundHandler.java
- bundles/org.openhab.binding.weatherunderground/src/main/java/org/openhab/binding/weatherunderground/internal/json/WeatherUndergroundJsonUtils.java
> [weatherunderground] Removed dependency on 'org.apache.commons.lang'

- bundles/org.openhab.binding.serialbutton/src/main/java/org/openhab/binding/serialbutton/internal/handler/SerialButtonHandler.java
> [serialbutton] Removed dependency on 'org.apache.commons.io.IOUtils'

- bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/handler/LGWebOSHandler.java
- bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/handler/LGWebOSTVSocket.java
- bundles/org.openhab.binding.lgwebos/src/main/resources/ESH-INF/config/config.xml
> [lgwebos] Mask access key

- bundles/org.openhab.binding.nibeheatpump/src/main/java/org/openhab/binding/nibeheatpump/internal/connection/SerialConnector.java
> [nibeheatpump] Removed dependency on 'org.apache.commons.io.IOUtils'

- bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/command/TeslaCommandExtension.java
Missing part of https://github.com/openhab/openhab-addons/pull/7789
> [tesla] Use CXF JAX-RS client builder, if available

- bundles/org.openhab.binding.avmfritz/README.md
I can verify that this sensor is working.
Signed-off-by: mueller-ma <mueller-ma@users.noreply.github.com>
> [avmfritz] Add link to Fensterkontakt (magnetisch) to docs

- bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/handler/DSCAlarmBaseBridgeHandler.java
- bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/handler/DSCAlarmBaseThingHandler.java
- bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/handler/EnvisalinkBridgeHandler.java
- bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/handler/IT100BridgeHandler.java
- bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/handler/PanelThingHandler.java
- bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/handler/PartitionThingHandler.java
- bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/handler/TCPServerBridgeHandler.java
- bundles/org.openhab.binding.dscalarm/src/main/resources/ESH-INF/thing/panel.xml
> [dscalarm] Bridge/things management refactored

- bundles/org.openhab.binding.siemensrds/src/main/java/org/openhab/binding/siemensrds/points/BasePoint.java
- bundles/org.openhab.binding.siemensrds/src/main/resources/ESH-INF/thing/thing-types.xml
- bundles/org.openhab.binding.siemensrds/src/test/java/org/openhab/binding/siemensrds/test/RdsTestData.java
Apply UoM QuantityType Percent for the relative humidity channel
> [siemensrds] apply UoM quantityType percent for relative humidity

- bundles/org.openhab.binding.seneye/src/main/java/org/openhab/binding/seneye/internal/SeneyeBindingConstants.java
- bundles/org.openhab.binding.seneye/src/main/java/org/openhab/binding/seneye/internal/SeneyeService.java
- bundles/org.openhab.binding.seneye/src/main/java/org/openhab/binding/seneye/internal/handler/SeneyeHandler.java
- bundles/org.openhab.binding.seneye/src/main/resources/ESH-INF/thing/thing-types.xml
This is a bug fix for Seneye binding when using Pond or Home Sensors.
Previously the binding would fail as it would try and pull readings for
Channels that didn't exist on these sensors.
Signed-off-by: MickUrsell  <bindings@mru-photography.co.uk>
> [Seneye] Bug fix for using Pond or Home sensors.

- bundles/org.openhab.binding.lametrictime/src/3rdparty/java/org/openhab/binding/lametrictime/api/common/impl/AbstractClient.java
- bundles/org.openhab.binding.lametrictime/src/3rdparty/java/org/openhab/binding/lametrictime/api/local/impl/LaMetricTimeLocalImpl.java
> [lametrictime] correctly parse response

- bundles/org.openhab.binding.siemensrds/README.md
Adjusted the ReadMe to match the minor change made in PR #7814 
> [siemensrds] readme adjusted to match #7814

- bundles/org.openhab.binding.telegram/README.md
- bundles/org.openhab.binding.telegram/pom.xml
- bundles/org.openhab.binding.telegram/src/main/java/org/openhab/binding/telegram/internal/TelegramBindingConstants.java
- bundles/org.openhab.binding.telegram/src/main/java/org/openhab/binding/telegram/internal/TelegramHandler.java
- bundles/org.openhab.binding.telegram/src/main/resources/ESH-INF/thing/thing-types.xml
This PR adds the possibility to retrieve file attachments (audio, documents, photo, video, voice)  send to the bot. The download URL is presented in a new channel lastMessageURL.
> [telegram] add attachment URL

- bundles/org.openhab.binding.lgwebos/README.md
- bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/console/LGWebOSCommandExtension.java
- bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/handler/LGWebOSHandler.java
> [lgwebos] Console command to show the access key

- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueBridgeHandler.java
- bundles/org.openhab.binding.hue/src/main/resources/ESH-INF/thing/bridge.xml
> [hue] Allow 0 for sensor polling interval to disable the polling

- bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/console/LGWebOSCommandExtension.java
- bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/console/LinkyCommandExtension.java
- bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/MaxConsoleCommandExtension.java
- bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/console/PowermaxCommandExtension.java
- bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/command/TeslaCommandExtension.java
> Console command: retrieve the thing handler

- bundles/org.openhab.binding.freebox/README.md
- bundles/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/api/FreeboxApiManager.java
- bundles/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/console/FreeboxCommandExtension.java
- bundles/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/handler/FreeboxHandler.java
Automatic update of the thing configuration with the application token
Console command to display the application token
> [freebox] Never log the application token

- bundles/org.openhab.binding.openweathermap/README.md
Signed-off-by: Holger Eisold holgereisold@gmx.de
> [openweathermap] minor documentation typo

- bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/config/OpenWeatherMapAPIConfiguration.java
- bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/config/OpenWeatherMapLocationConfiguration.java
- bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/config/OpenWeatherMapUVIndexConfiguration.java
- bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/config/OpenWeatherMapWeatherAndForecastConfiguration.java
- bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/connection/OpenWeatherMapConnection.java
- bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/handler/AbstractOpenWeatherMapHandler.java
- bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/handler/OpenWeatherMapAPIHandler.java
- bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/handler/OpenWeatherMapUVIndexHandler.java
- bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/handler/OpenWeatherMapWeatherAndForecastHandler.java
- Added warning if parsing of 'location' parameter throws exception
- Minor code improvements for config classes
> [openweathermap] Added warning if parsing of 'location' parameter throws exception

- bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/handler/AbstractOpenWeatherMapHandler.java
- bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/handler/OpenWeatherMapUVIndexHandler.java
- bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/handler/OpenWeatherMapWeatherAndForecastHandler.java
> [openweathermap] Undo PR #7692

- bundles/org.openhab.binding.hue/README.md
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/console/HueCommandExtension.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueBridgeHandler.java
Console command to display the user name
Related to #3990
> [hue] Never log the user name

- bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/factory/OpenWeatherMapHandlerFactory.java
- bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/handler/AbstractOpenWeatherMapHandler.java
> [openweathermap] Handler factory with constructor injection

- bundles/org.openhab.binding.nibeheatpump/README.md
Update of README.md according new registers
> [nibeheatpump] Update README.md

- bundles/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/console/FreeboxCommandExtension.java
- bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/console/LGWebOSCommandExtension.java
- bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/console/LinkyCommandExtension.java
- bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/console/PowermaxCommandExtension.java
> Console commands: enhanced parsing of bridge/thing UID

- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/GroupStatusListener.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueBridgeHandler.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueGroupHandler.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueLightHandler.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueSensorHandler.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/LightStatusListener.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/SensorStatusListener.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/sensors/ClipHandler.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/sensors/DimmerSwitchHandler.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/sensors/LightLevelHandler.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/sensors/PresenceHandler.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/sensors/TapSwitchHandler.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/sensors/TemperatureHandler.java
Fixed NPE reported by @andrewfg 
https://community.openhab.org/t/hue-binding-v2-5-6-snapshot-nullpointerexception-errors-on-startup/100027/5 and #7518
@lolodomo please have look
> [hue] Fix on startup NPE

- bundles/org.openhab.binding.goecharger/src/main/java/org/openhab/binding/goecharger/internal/handler/GoEChargerHandler.java
Power values were displayed as for example 4.1W but it should actually be 4.1kW, so i changed the calculation to return the value in W (4100 in this case).
> [goecharger] fixed calculation of power values

- bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/LightThingHandler.java
> [deconz] fix on-off issue with color lights

- bundles/org.openhab.binding.icalendar/README.md
Corrected description of Authorization_Code (moved the word 'not' to the correct line)
> [iCalendar] Update README.md

- bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosAlarm.java
- bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosAudioSink.java
- bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosBindingConstants.java
- bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosEntry.java
- bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosHandlerFactory.java
- bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosMetaData.java
- bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosMusicService.java
- bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosResourceMetaData.java
- bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosXMLParser.java
- bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosZoneGroup.java
- bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosZonePlayerState.java
- bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/config/ZonePlayerConfiguration.java
- bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/discovery/ZonePlayerDiscoveryParticipant.java
- bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/handler/ZonePlayerHandler.java
> [sonos] Add null annotations

- bundles/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/FreeboxHandlerFactory.java
- bundles/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/handler/FreeboxThingHandler.java
> [freebox] Consider TimeZoneProvider to get the timezone

- bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/PowermaxHandlerFactory.java
- bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/discovery/PowermaxDiscoveryService.java
- bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/handler/PowermaxThingHandler.java
Also fix few warnings about null check
> [powermax] Consider TimeZoneProvider to get the timezone

- bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/PowermaxHandlerFactory.java
- bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/handler/PowermaxThingHandler.java
> [powermax] TimeZoneProvider passed as parameter to the thing handler

- bundles/org.openhab.binding.homematic/README.md
> Misspelling Line 302

- bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/LightThingHandler.java
> [deconz] fix color temperature channel

- bundles/org.openhab.binding.astro/README.md
- bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/AstroHandlerFactory.java
- bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/calc/SeasonCalc.java
- bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/calc/SunCalc.java
- bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/config/AstroThingConfig.java
- bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/discovery/AstroDiscoveryService.java
- bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/handler/SunHandler.java
- bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/job/AbstractJob.java
- bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/job/CompositeJob.java
- bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/job/DailyJobMoon.java
- bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/job/DailyJobSun.java
- bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/job/EventJob.java
- bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/job/Job.java
- bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/job/PositionalJob.java
- bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/job/PublishPlanetJob.java
- bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/job/SunPhaseJob.java
- bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/model/RiseSet.java
- bundles/org.openhab.binding.astro/src/main/resources/ESH-INF/config/config.xml
- bundles/org.openhab.binding.astro/src/main/resources/ESH-INF/thing/sun.xml
- bundles/org.openhab.binding.astro/src/test/java/org/openhab/binding/astro/internal/calc/SunCalcTest.java
- itests/org.openhab.binding.astro.tests/src/main/java/org/openhab/binding/astro/test/AstroStateTest.java
> [astro] Adressing issue #5732

- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueGroupHandler.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueLightHandler.java
> [hue] Color command for group must turn on the lights

- bundles/org.openhab.binding.hpprinter/README.md
> [hpprinter] A couple of fixes and improvements to the README

- bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/AstroHandlerFactory.java
- bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/handler/AstroThingHandler.java
- bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/handler/MoonHandler.java
- bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/handler/SunHandler.java
- bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/util/PropertyUtils.java
- bundles/org.openhab.binding.astro/src/test/java/org/openhab/binding/astro/internal/model/SunTest.java
- itests/org.openhab.binding.astro.tests/src/main/java/org/openhab/binding/astro/handler/test/AstroCommandTest.java
- itests/org.openhab.binding.astro.tests/src/main/java/org/openhab/binding/astro/handler/test/AstroValidConfigurationTest.java
- itests/org.openhab.binding.astro.tests/src/main/java/org/openhab/binding/astro/test/AstroStateTest.java
> [astro] Suppress timeZoneProvider global variable

- bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaSilentRollerShutterHandler.java
This PR improves silent mode control of the Silent Roller Shutter thing.
Now it moves the roller shutter silently even if the UP or DOWN command received.
Confirmed to be working
https://community.openhab.org/t/re-tahoma-binding-compatible-with-oh2/100430/10
> [somfytahoma] improved silent mode control

- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueBridgeHandler.java
> [hue] Set bridge status to ONLINE only after a polling success

- bundles/org.openhab.binding.hyperion/src/main/java/org/openhab/binding/hyperion/internal/HyperionBindingConstants.java
- bundles/org.openhab.binding.hyperion/src/main/java/org/openhab/binding/hyperion/internal/handler/HyperionNgHandler.java
Incorporate changes to HyperionNG serverInfo API - alpha6.
HyperionEnabled state channel is now determined by special component
state "ALL". See: https://docs.hyperion-project.org/en/json/ServerInfo.html
Recent community discussion:
https://community.openhab.org/t/multiple-state-issues-with-hyperion-ng-binding/97747
Signed-off-by: Łukasz Serwicki <lserwicki@gmail.com>
> [hyperion] Fixes #6377 hyperion NPE

- bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/DanfossAirUnitHandler.java
> [danfossairunit] Fixed null warnings and errors

- bundles/org.openhab.binding.nikohomecontrol/README.md
> [nikohomecontrol] Correct README

- bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxPlayerHandler.java
> [squeezebox] Answer REFRESH command from cache if possible

- bundles/org.openhab.binding.rotel/README.md
- bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/RotelModel.java
- bundles/org.openhab.binding.rotel/src/main/resources/ESH-INF/thing/rc1590.xml
> [rotel] Add support for RC-1590 with firmware >= 1.40

- bundles/org.openhab.binding.bigassfan/src/main/java/org/openhab/binding/bigassfan/internal/handler/BigAssFanHandler.java
- bundles/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/handler/GardenaThingHandler.java
- bundles/org.openhab.binding.logreader/src/main/java/org/openhab/binding/logreader/internal/handler/LogHandler.java
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/grxprg/PrgProtocolHandler.java
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/TimeclockHandler.java
- bundles/org.openhab.binding.meteoblue/src/main/java/org/openhab/binding/meteoblue/internal/handler/MeteoBlueHandler.java
- bundles/org.openhab.binding.onebusaway/src/main/java/org/openhab/binding/onebusaway/internal/handler/RouteHandler.java
- bundles/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/internal/handler/TelldusDevicesHandler.java
- bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/handler/UniFiClientThingHandler.java
- Fixed usage of deprecated constructor for `DateTimeType(Calendar)`
This is a very rough replacement by just converting `Calendar` into `ZonedDateTime` values. I am pretty sure in most cases the logic behind it can be improved even more by doing a deeper refactoring of the code / the origin of theses values.
But it would be nice to get support by the binding developers because it is too error-prone without deeper knowledge.
Related to https://github.com/openhab/openhab-core/pull/1500
> Fixed usage of deprecated constructor for 'DateTimeType(Calendar)'

- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/NetatmoDeviceHandler.java
- bundles/org.openhab.binding.netatmo/src/main/resources/ESH-INF/config/config.xml
> [netatmo] Set the minimum refresh interval to 2s

- bundles/org.openhab.persistence.dynamodb/src/test/java/org/openhab/persistence/dynamodb/internal/AbstractDynamoDBItemSerializationTest.java
- bundles/org.openhab.persistence.dynamodb/src/test/java/org/openhab/persistence/dynamodb/internal/DateTimeItemIntegrationTest.java
- bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/InfluxDBConfiguration.java
- bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/ItemToStorePointCreator.java
- bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcBaseDAO.java
- bundles/org.openhab.persistence.jpa/src/main/java/org/openhab/persistence/jpa/internal/JpaHistoricItem.java
- bundles/org.openhab.persistence.jpa/src/main/java/org/openhab/persistence/jpa/internal/StateHelper.java
- bundles/org.openhab.persistence.mongodb/src/main/java/org/openhab/persistence/mongodb/internal/MongoDBPersistenceService.java
Fixes the OH3/master build and also fixes some null annotation errors showing in Eclipse.
Related to: https://github.com/openhab/openhab-core/pull/1500
> Fix DateTimeType deprecations

- bundles/create_openhab_binding_skeleton.cmd
- bundles/create_openhab_binding_skeleton.sh
- itests/org.openhab.binding.astro.tests/itest.bndrun
- itests/org.openhab.binding.avmfritz.tests/itest.bndrun
- itests/org.openhab.binding.feed.tests/itest.bndrun
- itests/org.openhab.binding.hue.tests/itest.bndrun
- itests/org.openhab.binding.max.tests/itest.bndrun
- itests/org.openhab.binding.modbus.tests/itest.bndrun
- itests/org.openhab.binding.nest.tests/itest.bndrun
- itests/org.openhab.binding.ntp.tests/itest.bndrun
- itests/org.openhab.binding.systeminfo.tests/itest.bndrun
- itests/org.openhab.binding.tradfri.tests/itest.bndrun
- itests/org.openhab.binding.wemo.tests/itest.bndrun
- itests/org.openhab.io.hueemulation.tests/itest.bndrun
- Fix missing 2.5.7-SNAPSHOT changes
> Fix missing 2.5.7-SNAPSHOT changes

- bundles/org.openhab.binding.lametrictime/src/3rdparty/test/org/openhab/binding/lametrictime/api/local/model/WidgetUpdatesTest.java
- bundles/org.openhab.binding.lametrictime/src/3rdparty/test/org/openhab/binding/lametrictime/api/test/AbstractTest.java
> [lametrictime] Fix the failing tests on Windows

- bundles/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/handler/NestBaseHandler.java
- bundles/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/handler/NestBridgeHandler.java
- bundles/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/handler/NestRedirectUrlSupplier.java
- bundles/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/rest/NestAuthorizer.java
- bundles/org.openhab.persistence.dynamodb/src/main/java/org/openhab/persistence/dynamodb/internal/DynamoDBConfig.java
- bundles/org.openhab.persistence.dynamodb/src/test/java/org/openhab/persistence/dynamodb/internal/AbstractDynamoDBItemSerializationTest.java
- bundles/org.openhab.persistence.dynamodb/src/test/java/org/openhab/persistence/dynamodb/internal/BaseIntegrationTest.java
- bundles/org.openhab.persistence.dynamodb/src/test/java/org/openhab/persistence/dynamodb/internal/DynamoDBConfigTest.java
- bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/InfluxDBConfiguration.java
- bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/InfluxDBStateConvertUtils.java
- bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/influx2/InfluxDB2RepositoryImpl.java
- bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcConfiguration.java
- bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/utils/MovingAverage.java
- bundles/org.openhab.persistence.jpa/src/main/java/org/openhab/persistence/jpa/internal/JpaConfiguration.java
- bundles/org.openhab.persistence.jpa/src/main/java/org/openhab/persistence/jpa/internal/JpaPersistenceService.java
- bundles/org.openhab.persistence.mongodb/src/main/java/org/openhab/persistence/mongodb/internal/MongoDBPersistenceService.java
- bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java
- itests/org.openhab.binding.nest.tests/itest.bndrun
- itests/org.openhab.persistence.mapdb.tests/itest.bndrun
- Removed dependency on `org.apache.commons.*`
Related to #7722 
> Removed dependency on 'org.apache.commons.*' 

- bundles/org.openhab.persistence.dynamodb/src/main/java/org/openhab/persistence/dynamodb/internal/DynamoDBPersistenceService.java
We ensure that errors are logged, and scheduled task is not halted.
I had a situation in my production installation (with 2.5.x) where the bundle had to be restarted in order to "fix" persistence bundle so that it writes the data again. I hope this would at least make errors more visible in the logs.
> [dynamodb] Catch all for any unexpected exceptions

- bundles/org.openhab.io.transport.modbus/src/main/java/org/openhab/io/transport/modbus/internal/ModbusManagerImpl.java
Using RuntimeException in the catch-all. 
Cc @Hilbrand, similar discussion with dynamodb bundle change https://github.com/openhab/openhab-addons/pull/8000#pullrequestreview-436563043
> [modbus] Use RuntimeException

- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/NetatmoHandlerFactory.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/channelhelper/BatteryHelper.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/channelhelper/RadioHelper.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/config/NetatmoBridgeConfiguration.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/discovery/NetatmoModuleDiscoveryService.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/NetatmoBridgeHandler.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/NetatmoDataListener.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/NetatmoDeviceHandler.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/thermostat/NATherm1Handler.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/welcome/NAWelcomePersonHandler.java
> [netatmo] Null annotations Part 1

- CODEOWNERS
- bom/openhab-addons/pom.xml
- bundles/org.openhab.binding.heliosventilation/.classpath
- bundles/org.openhab.binding.heliosventilation/.project
- bundles/org.openhab.binding.heliosventilation/NOTICE
- bundles/org.openhab.binding.heliosventilation/README.md
- bundles/org.openhab.binding.heliosventilation/pom.xml
- bundles/org.openhab.binding.heliosventilation/src/main/feature/feature.xml
- bundles/org.openhab.binding.heliosventilation/src/main/java/org/openhab/binding/heliosventilation/internal/HeliosPropertiesFormatException.java
- bundles/org.openhab.binding.heliosventilation/src/main/java/org/openhab/binding/heliosventilation/internal/HeliosVentilationBindingConstants.java
- bundles/org.openhab.binding.heliosventilation/src/main/java/org/openhab/binding/heliosventilation/internal/HeliosVentilationConfiguration.java
- bundles/org.openhab.binding.heliosventilation/src/main/java/org/openhab/binding/heliosventilation/internal/HeliosVentilationDataPoint.java
- bundles/org.openhab.binding.heliosventilation/src/main/java/org/openhab/binding/heliosventilation/internal/HeliosVentilationHandler.java
- bundles/org.openhab.binding.heliosventilation/src/main/java/org/openhab/binding/heliosventilation/internal/HeliosVentilationHandlerFactory.java
- bundles/org.openhab.binding.heliosventilation/src/main/resources/ESH-INF/binding/binding.xml
- bundles/org.openhab.binding.heliosventilation/src/main/resources/ESH-INF/i18n/heliosventilation_de.properties
- bundles/org.openhab.binding.heliosventilation/src/main/resources/ESH-INF/thing/thing-types.xml
- bundles/org.openhab.binding.heliosventilation/src/main/resources/datapoints.properties
- bundles/pom.xml
Add binding to access Helios Domestiic ventilation systems (KWL) via the Remote Control RS485 interface.
This is a rework of the previously abandoned #5831 which I messed up with merging the wrong branch.
Fixes #5752
> [heliosventilation] Helios Ventilation Binding Initial contribution

- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/WeatherUtils.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/AbstractNetatmoThingHandler.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/MeasurableChannels.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/NetatmoBridgeHandler.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/NetatmoDeviceHandler.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/homecoach/NAHealthyHomeCoachHandler.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/station/NAMainHandler.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/station/NAModule1Handler.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/station/NAModule2Handler.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/station/NAModule3Handler.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/station/NAModule4Handler.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/thermostat/NAPlugHandler.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/thermostat/NATherm1Handler.java
- bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/webhook/WelcomeWebHookServlet.java
> [netatmo] Null annotations Part 2 of 3

- bundles/org.openhab.binding.ntp/README.md
- bundles/org.openhab.binding.ntp/src/main/resources/ESH-INF/i18n/ntp.properties
- bundles/org.openhab.binding.ntp/src/main/resources/ESH-INF/i18n/ntp_de.properties
- bundles/org.openhab.binding.ntp/src/main/resources/ESH-INF/i18n/ntp_fr.properties
- bundles/org.openhab.binding.ntp/src/main/resources/ESH-INF/i18n/ntp_tr.properties
i18n entries that are no more used are removed
> [ntp] Updated documentation

- bundles/org.openhab.binding.bosesoundtouch/pom.xml
- bundles/org.openhab.binding.bosesoundtouch/src/main/java/org/openhab/binding/bosesoundtouch/internal/handler/BoseSoundTouchHandler.java
> [bosesoundtouch] fix possible resource leak

- bundles/org.openhab.binding.tibber/pom.xml
- bundles/org.openhab.binding.tibber/src/main/java/org/openhab/binding/tibber/internal/handler/TibberHandler.java
> [tibber] fix possible resource leak

- bundles/org.openhab.binding.samsungtv/pom.xml
- bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/protocol/RemoteControllerWebSocket.java
- bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/protocol/WebSocketBase.java
Related to #7978 
Currently there is no proof that this really fixes all problems, but useres report stability improvements. I therefore suggest to merge it, as no negative side-effects are expected.
> [samsungtv] cleanup websocket shutdown

- bundles/org.openhab.binding.insteon/README.md
- bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/InsteonBinding.java
- bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/InsteonBindingConstants.java
- bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/CommandHandler.java
- bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/MessageHandler.java
- bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/driver/Port.java
- bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/handler/InsteonDeviceHandler.java
- bundles/org.openhab.binding.insteon/src/main/resources/ESH-INF/thing/thing-types.xml
- bundles/org.openhab.binding.insteon/src/main/resources/device_features.xml
- bundles/org.openhab.binding.insteon/src/main/resources/device_types.xml
In addition to the features from the original motion sensor, this device supports tamper switch and battery percentage.
> [insteon] added support for motion sensor II (2844-222)

- bundles/org.openhab.binding.miio/README.base.md
- bundles/org.openhab.binding.miio/README.md
- bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/cloud/CloudConnector.java
Minor improvement docu & lower loglevel
> [miio] minor docu & log update

- bundles/org.openhab.binding.modbus/DEVELOPERS.md
- bundles/org.openhab.io.transport.modbus/pom.xml
See https://github.com/openhab/jamod/pull/4 and https://github.com/openhab/jamod/pull/4#issuecomment-651979210
cc @kaikreuzer 
> [modbus] Update jamod to 1.2.4.OH

- bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/LcnModuleActions.java
Reference to EcobeeActions corrected.
> [LCN] Naming corrected.

- bundles/org.openhab.binding.lcn/README.md
- bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/ILcnModuleActions.java
- bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/LcnModuleActions.java
- bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/common/PckGenerator.java
This pull request adds an action for an lcn relay timer.
> [lcn] Add action for lcn relay timer

- bundles/org.openhab.binding.verisure/src/main/java/org/openhab/binding/verisure/internal/handler/VerisureThingHandler.java
[verisure] Replaced Joda time.
> [verisure] Replaced Joda time.

- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/config/BlindConfig.java
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/config/DimmerConfig.java
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/DimmerHandler.java
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/VcrxHandler.java
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/keypadconfig/KeypadConfigTabletopSeetouch.java
- bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/xml/DbXmlInfoReader.java
Adds null annotations to a few more classes, and performs some other minor code clean-up. 
This has been sitting in a dev branch for a while, and I want to get it out of the way before some major code changes that are coming for LEAP protocol support.
> [lutron] Add null annotations and minor clean-up

- bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/protocol/RemoteControllerWebSocket.java
> [samsungtv] Partial revert of PR 8025

- bundles/org.openhab.persistence.dynamodb/src/main/java/org/openhab/persistence/dynamodb/internal/AbstractDynamoDBItem.java
- bundles/org.openhab.persistence.dynamodb/src/test/java/org/openhab/persistence/dynamodb/internal/AbstractDynamoDBItemGetDynamoItemClassTest.java
- bundles/org.openhab.persistence.dynamodb/src/test/java/org/openhab/persistence/dynamodb/internal/BaseIntegrationTest.java
- bundles/org.openhab.persistence.dynamodb/src/test/java/org/openhab/persistence/dynamodb/internal/PlayerItemPlayPauseIntegrationTest.java
- bundles/org.openhab.persistence.dynamodb/src/test/java/org/openhab/persistence/dynamodb/internal/PlayerItemRewindFastForwardIntegrationTest.java
> [dynamodb] Dynamodb additional items supported (PlayerItem)

- bundles/org.openhab.persistence.dynamodb/src/test/java/org/openhab/persistence/dynamodb/internal/BaseIntegrationTest.java
- bundles/org.openhab.persistence.dynamodb/src/test/java/org/openhab/persistence/dynamodb/internal/PagingIntegrationTest.java
> [dynamodb] tests for paging

- bundles/org.openhab.binding.bosesoundtouch/src/main/java/org/openhab/binding/bosesoundtouch/internal/handler/BoseSoundTouchHandler.java
> [bosesoundtouch] Partial revert of PR 8031

- bundles/org.openhab.binding.mail/pom.xml
- bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/action/ISendMailActions.java
- bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/action/SendMailActions.java
> [mail] ensure thing actions work all the time

- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/action/ILightActions.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/action/LightActions.java
Related to openhab/openhab-core#1265
> [hue] Thing actions still working after a bundle restart

- bundles/org.openhab.binding.hue/README.md
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/FullGroup.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/Group.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/HueBindingConstants.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/HueBridge.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/HueObject.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/HueThingHandlerFactory.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/Scene.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/StateUpdate.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/console/HueCommandExtension.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/discovery/HueLightDiscoveryService.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/GroupStatusListener.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueBridgeHandler.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueClient.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueGroupHandler.java
- bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueStateDescriptionOptionProvider.java
- bundles/org.openhab.binding.hue/src/main/resources/ESH-INF/thing/Group.xml
- bundles/org.openhab.binding.hue/src/main/resources/ESH-INF/thing/bridge.xml
- bundles/org.openhab.binding.hue/src/main/resources/ESH-INF/thing/channels.xml
- bundles/org.openhab.binding.hue/src/test/java/org/openhab/binding/hue/internal/HueBridgeTest.java
- bundles/org.openhab.binding.hue/src/test/java/org/openhab/binding/hue/internal/SceneTest.java
- bundles/org.openhab.binding.hue/src/test/java/org/openhab/binding/hue/internal/handler/HueLightHandlerTest.java
Closes #6043
This is the continuation of the PR #7540
95% of credits go to leluna
Also-by: leluna <hengrui.jiang@googlemail.com>
> [hue] Add support for hue scene activation

- bundles/org.openhab.binding.doorbird/src/main/java/org/openhab/binding/doorbird/action/DoorbirdActions.java
- bundles/org.openhab.binding.doorbird/src/main/java/org/openhab/binding/doorbird/action/IDoorbirdActions.java
> [doorbird] Implement actions fix

- bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/action/ISatelEventLogActions.java
- bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/action/SatelEventLogActions.java
A workaround for https://github.com/openhab/openhab-core/issues/1265
See also #8116
> [satel] Thing actions restart fix
