bundles/org.openhab.binding.insteon/README.md, bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/InsteonBinding.java, bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/InsteonHandlerFactory.java, bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/command/InsteonCommandExtension.java, bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/driver/Port.java, bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/handler/InsteonDeviceHandler.java, bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/handler/InsteonNetworkHandler.java
The commands provide information that is logged by the oh1 binding insteonplm. This is helpful when configuring the binding and supporting people who run into issues.
=> [insteon] add console commands to help with troubleshooting

bundles/org.openhab.binding.jeelink/README.md
The Documentation of the Jeelink Binding contained the error, that the Bridges have been defined as "Thing" instead of "Bridge". This Merge fixes this issue.
Signed-off-by: Dominik Schön <dominik@familie-schoen.com>
=> [Jeelink] Declaration of Bridges in Items Files

bundles/org.openhab.binding.fronius/README.md, bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/FroniusBindingConstants.java, bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/handler/FroniusSymoInverterHandler.java, bundles/org.openhab.binding.fronius/src/main/resources/ESH-INF/thing/thing-types.xml
- Added a new channel to retrieve the device status error code property.
- Added a new channel to retrieve the device status status code property.
- Fixed incorrect channel and parameters ids in documentation.
=> [fronius] Add new channels and fix documentation

bundles/org.openhab.voice.marytts/pom.xml
It throws the exception for example using:
```
smarthome:voice say "washer is done. dryer is done."
```
See: [MaryTTS gives Jama/Matrix errors for only some rules](https://community.openhab.org/t/marytts-gives-jama-matrix-errors-for-only-some-rules/95739?u=wborn)
=> [marytts] Fix java.lang.NoClassDefFoundError: Jama/Matrix

bundles/org.openhab.binding.doorbird/README.md, bundles/org.openhab.binding.doorbird/src/main/resources/ESH-INF/thing/thing-types.xml
Minor changes/fixes to documentation and thing-types.xml
=> [doorbird] Minor documentation updates

bundles/org.openhab.binding.bluetooth/src/test/java/org/openhab/binding/bluetooth/discovery/internal/BluetoothDiscoveryServiceTest.java
The first test to run has to deal with JIT compilation of the discovery service code, so it will always take substantially longer than the other tests.
This PR doubles the timeout waiting for an asynchronous task to complete before marking the test as failed. Hopefully doubling it will be enough for the first test to still pass even with JIT compiling slowness.
Hopefully resolves #7286.
=> [bluetooth] Increase timeout to account for slower machines.

bundles/org.openhab.binding.tradfri/src/main/resources/ESH-INF/thing/thing-types.xml
Caused by: Discovery finds `gateway` that already has been defined in a thing file.
=> [tradfri] Add missing representation property 'host' in in gateway definition

bundles/org.openhab.binding.mihome/README.md
Update the way to enable the developer mode
The "Xiaomi Mi Smart Home Binding" documentation decribes the old way of entering the developer mode. Updated to new process.
Signed-off-by: Stefan Schmidhammer <byteterra@hotmail.com>
=> [mihome] Update README.md

bundles/org.openhab.binding.pjlinkdevice/src/main/java/org/openhab/binding/pjlinkdevice/internal/device/PJLinkDevice.java, bundles/org.openhab.binding.pjlinkdevice/src/main/java/org/openhab/binding/pjlinkdevice/internal/device/command/AcknowledgeResponseValue.java, bundles/org.openhab.binding.pjlinkdevice/src/main/java/org/openhab/binding/pjlinkdevice/internal/device/command/PrefixedResponse.java, bundles/org.openhab.binding.pjlinkdevice/src/main/java/org/openhab/binding/pjlinkdevice/internal/device/command/errorstatus/ErrorStatusQueryResponse.java, bundles/org.openhab.binding.pjlinkdevice/src/main/java/org/openhab/binding/pjlinkdevice/internal/device/command/mute/MuteQueryResponse.java, bundles/org.openhab.binding.pjlinkdevice/src/main/java/org/openhab/binding/pjlinkdevice/internal/device/command/power/PowerQueryResponse.java
This improvement enables logging of responses from the device as byte arrays. This could help to resolve some remaining issues reported by the [community](https://community.openhab.org/t/new-pjlink-binding-for-controlling-multiple-projector-brands-models/56608/40).
=> [pjlink] enhanced logging (show byte array in addition to string)

bundles/org.openhab.binding.satel/README.md, bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/action/SatelEventLogActions.java, bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/handler/SatelEventLogHandler.java, bundles/org.openhab.binding.satel/src/main/resources/ESH-INF/i18n/satel.properties
This PR add a rule action for reading records from the event log. It replaces current way of reading the log using items linked to channels of `event-log` thing. This is still available but marked as deprecated.
It also contains minor changes in README file.
=> [satel] Action for reading the event log added

bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/ConfigStore.java
With the changes in #6967 the `HueEmulationServiceOSGiTest` always fails for me.
The reason is that if the `discoveryIps` are not configured, it is no longer guaranteed it will use the primary IPv4 host address as fallback.
In my case the iterator on the `HashSet` would return an IPv6 address as first address.
By using a `LinkedHashSet` the order is preserved and it will again use the primary IPv4 host address as fallback.
=> [hueemulation] Fix broken fallback address

bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/PowerControlPower.java
Signed-off-by: Laurent Garnier <lg.hc@free/fr>
=> [lgwebos] Ignore power off command when the TV is already off

bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/handler/LGWebOSHandler.java
=> [lgwebos] Update the thing configuration only if the key is different

CODEOWNERS
The team got renamed after the repo got renamed to openhab-addons.
---
See: https://github.com/openhab/openhab-addons/pull/7298#issuecomment-610261949
=> Update maintainers team in CODEOWNERS (2.5.x)

CODEOWNERS
The team got renamed after the repo got renamed to openhab-addons.
---
Same as https://github.com/openhab/openhab-addons/pull/7317 but for master.
=> Update maintainers team in CODEOWNERS (master)

bundles/org.openhab.extensionservice.marketplace.automation/src/main/java/org/openhab/extensionservice/marketplace/automation/internal/MarketplaceRuleTemplateProvider.java
Without these annotations the OH3 Add-ons port build will fail when https://github.com/openhab/openhab-core/pull/1412 gets merged.
=> Add null annotations to MarketplaceRuleTemplateProvider

bundles/org.openhab.binding.chromecast/pom.xml
Fixes:
* Jackson version range resolution issues, so https://github.com/openhab/openhab-addons/pull/7258 can be undone (https://github.com/vitalidze/chromecast-java-api-v2/issues/124)
* Logs IOE on debug instead of warning when disconnecting ("Got IOException while reading due to stream being closed (stop=true)")
=> [chromecast] Update API lib to 0.11.3

bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/handler/LGWebOSHandler.java, bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/handler/LGWebOSTVSocket.java
=> [lgwebos] Avoid thing updates when the thing handler is already disposed

bundles/org.openhab.binding.daikin/README.md, bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/airbase/AirbaseEnums.java, bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/handler/DaikinAirbaseUnitHandler.java
Airbase supports AUTO fan mode as reported in https://community.openhab.org/t/daikin-binding-fan-error/96129
This is done by setting f_rate=0,f_airside=0,f_auto=0
It appears that this is also allowed in other Airbase compatible systems that don't otherwise allow such setting via the wall controller.
=> [daikin] Support AUTO fan mode with Airbase

bundles/org.openhab.binding.daikin/README.md
The fandir channel exists in the code but wasn't included in the documentation. This PR remedies that. This solved https://github.com/openhab/openhab-addons/issues/6308
=> [daikin] Update doc to include fandir channel previously omitted

bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/type/HomematicTypeGeneratorImpl.java
The binding used some deprecated constructors. These usages have been replaced to allow the removal of these constructors. See also: https://github.com/openhab/openhab-core/pull/1414
=> [homematic] Replaced deprecated constructors

bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/driver/Port.java, bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/driver/hub/HubIOStream.java, bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/message/MsgFactory.java, bundles/org.openhab.binding.insteon/src/main/resources/msg_definitions.xml
* Improved message processing in draining the current buffer fully when a bad error message exception is triggered. Currently, when multiple messages are received at the same time and, in the event the first one has corrupted data, the subsequent messages aren't processed until new data is available in the modem buffer. This can lead to a few seconds up to a minute delay in processing these messages.
* Improved hub cleared and wrap around buffer messages parsing, reducing further the amount of potential bad data received errors, based on the [python module](https://github.com/nugget/python-insteonplm) implementation.
* Removed the unnecessary buffer clear request on each write calls, since sending a command to the hub implies the buffer will be cleared at that time.
* Added an …
=> [insteon] Improve hub message processing

bundles/org.openhab.extensionservice.marketplace/src/main/java/org/openhab/extensionservice/marketplace/MarketplaceExtension.java, bundles/org.openhab.extensionservice.marketplace/src/main/java/org/openhab/extensionservice/marketplace/MarketplaceExtensionHandler.java, bundles/org.openhab.extensionservice.marketplace/src/main/java/org/openhab/extensionservice/marketplace/MarketplaceHandlerException.java, bundles/org.openhab.extensionservice.marketplace/src/main/java/org/openhab/extensionservice/marketplace/internal/MarketplaceProxy.java, bundles/org.openhab.extensionservice.marketplace/src/main/java/org/openhab/extensionservice/marketplace/internal/MarketplaceXMLReader.java, bundles/org.openhab.extensionservice.marketplace/src/main/java/org/openhab/extensionservice/marketplace/internal/model/Category.java, bundles/org.openhab.extensionservice.marketplace/src/main/java/org/openhab/extensionservice/marketplace/internal/model/Marketplace.java
The add-ons port would break without these annotations when https://github.com/openhab/openhab-core/pull/1421 gets merged.
=> [extensionservice] Add more null annotations

bundles/org.openhab.binding.lutron/README.md, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/discovery/LutronMdnsBridgeDiscoveryService.java
This is a small update that adds discovery support for RA2 Select main repeaters to the mDNS bridge discovery service.
=> [lutron] Add discovery support for RA2 Select repeater

bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc2/NhcThermostat2.java, bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc2/NikoHomeControlCommunication2.java
Bugfix for thermostat setpoint using wrong rounding on NHC II.
=> [nikohomecontrol] Fix thermostat setpoint.

bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/discovery/AirVisualNodeDiscoveryService.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/discovery/AmazonEchoDiscovery.java, bundles/org.openhab.binding.lirc/src/main/java/org/openhab/binding/lirc/internal/discovery/LIRCRemoteDiscoveryService.java, bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/discovery/RFXComDeviceDiscoveryService.java, bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/discovery/SomfyTahomaItemDiscoveryService.java, bundles/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/internal/discovery/ZoneMinderDiscoveryService.java
Because of the deprecation each `DiscoveryServiceCallback` method will always return null so it's better to remove all usages.
Related to openhab/openhab-core#1408, https://github.com/openhab/openhab-core/pull/1424
=> Remove deprecated DiscoveryServiceCallback, ExtendedDiscoveryService usages

bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitAccessoryUpdater.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitAuthInfoImpl.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitChangeListener.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitCommandExtension.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitImpl.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitTaggedItem.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/AbstractHomekitLightbulbImpl.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitAccessoryFactory.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitTemperatureSensorImpl.java
In the HomeKit binding there are many different forms of the noun
"HomeKit" used. This changes the instances of "HomeKit" in comments and
logs to use the style of "HomeKit" consistently.
=> [homekit] Use consistent styling of "HomeKit"

bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/handler/VeluxBridgeHandler.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/handler/utils/Thing2VeluxActuator.java
especially during startup phase of the binding.
=> [velux] Avoiding warning about (yet) unrecognized actuators 

bundles/org.openhab.binding.dwdpollenflug/README.md, bundles/org.openhab.binding.dwdpollenflug/src/main/java/org/openhab/binding/dwdpollenflug/internal/DWDPollenflugBindingConstants.java, bundles/org.openhab.binding.dwdpollenflug/src/main/java/org/openhab/binding/dwdpollenflug/internal/DWDPollenflugHandlerFactory.java, bundles/org.openhab.binding.dwdpollenflug/src/main/java/org/openhab/binding/dwdpollenflug/internal/discovery/DWDPollenflugDiscoveryService.java, bundles/org.openhab.binding.dwdpollenflug/src/main/java/org/openhab/binding/dwdpollenflug/internal/handler/DWDPollenflugBridgeHandler.java, bundles/org.openhab.binding.dwdpollenflug/src/main/java/org/openhab/binding/dwdpollenflug/internal/handler/DWDPollenflugRegionHandler.java, bundles/org.openhab.binding.dwdpollenflug/src/main/resources/ESH-INF/i18n/dwdpollenflug_de.properties, bundles/org.openhab.binding.dwdpollenflug/src/main/resources/ESH-INF/thing/bridge.xml, bundles/org.openhab.binding.dwdpollenflug/src/main/resources/ESH-INF/thing/region.xml
Did some small improvements I have learned, while transfering to new CoronaStats binding (see #7358) 
Biggest change is the new DiscoveryService for bridge thing
=> [DWDPollenflug] Small code improvments

bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/handler/LGWebOSHandler.java
Addresses issue #7243.
without the delay it can happen, that we request a subscription, but livetv is not yet ready to respond. Instead we get this error:
```
2020-04-17 18:11:11.767 [DEBUG] [.lgwebos.internal.BaseChannelHandler] - Subscribed org.openhab.binding.lgwebos.internal.TVControlChannel on Thing: lgwebos:WebOSTV:6da62662-1369-a82d-95c7-353c235ed503
2020-04-17 18:11:11.816 [DEBUG] [bos.internal.handler.LGWebOSTVSocket] - Error: {"type":"error","id":9,"error":"500 Application error","payload":{"returnValue":false,"errorCode":"BROADCAST_ERROR_1003","errorText":"No information"}}
2020-04-17 18:11:11.817 [DEBUG] [ng.lgwebos.internal.TVControlChannel] - Error in retrieving channel: 500 Application error.
```
the delay fixes the issue
=> [lgwebos] Delay subscription of channel

CODEOWNERS, bom/openhab-addons/pom.xml, bundles/org.openhab.binding.modbus.sunspec/.classpath, bundles/org.openhab.binding.modbus.sunspec/.project, bundles/org.openhab.binding.modbus.sunspec/NOTICE, bundles/org.openhab.binding.modbus.sunspec/README.md, bundles/org.openhab.binding.modbus.sunspec/pom.xml, bundles/org.openhab.binding.modbus.sunspec/src/main/feature/feature.xml, bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/InverterStatus.java, bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/SunSpecConfiguration.java, bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/SunSpecConstants.java, bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/SunSpecHandlerFactory.java, bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/dto/InverterModelBlock.java, bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/dto/ModelBlock.java, bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/handler/AbstractSunSpecHandler.java, bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/handler/InverterHandler.java, bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/parser/AbstractBaseParser.java, bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/parser/InverterModelParser.java, bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/parser/SunspecParser.java, bundles/org.openhab.binding.modbus.sunspec/src/main/resources/ESH-INF/config/config-descriptions.xml, bundles/org.openhab.binding.modbus.sunspec/src/main/resources/ESH-INF/thing/inverter-channel-groups.xml, bundles/org.openhab.binding.modbus.sunspec/src/main/resources/ESH-INF/thing/inverter-channel-types.xml, bundles/org.openhab.binding.modbus.sunspec/src/main/resources/ESH-INF/thing/inverter-types.xml, bundles/pom.xml
SunSpec is an open standard for solar inverters and other related devices to share data about their internal state. The standard is implemented by several vendors like ABB, Fronius, SMA, Schneider Electric, Solaredge, etc.
The goal of this work is to add user friendly support of these devices to openHAB.
The standard is built on the Modbus protocol, so this work is heavily based on the Modbus binding. Also the Bluetooth binding and several of it's solutions were taken as an example how to extend an already existing binding with a new bundle.
Related issue: #3216
This is a stripped down version of a SunSpec bundle aimed to ease reviewing as requested by @davidgraeff 
Original PR with all the features can be found here: #4220 
This version contains only a limited support for single phase …
=> [sunspec] Modbus: SunSpec bundle basic version initial contribution

bundles/org.openhab.binding.bluetooth/src/test/java/org/openhab/binding/bluetooth/discovery/internal/BluetoothDiscoveryServiceTest.java
=> [bluetooth] Removed usage of deprecated method in tests

bundles/org.openhab.binding.chromecast/pom.xml, bundles/org.openhab.binding.chromecast/src/main/feature/feature.xml, bundles/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromecastAudioSink.java, bundles/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromecastBindingConstants.java, bundles/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromecastCommander.java, bundles/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromecastEventReceiver.java, bundles/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromecastScheduler.java, bundles/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromecastStatusUpdater.java, bundles/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/config/ChromecastConfig.java, bundles/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/discovery/ChromecastDiscoveryParticipant.java, bundles/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/factory/ChromecastHandlerFactory.java, bundles/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/handler/ChromecastHandler.java, bundles/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/utils/ByteArrayFileCache.java, bundles/org.openhab.binding.chromecast/src/main/resources/ESH-INF/i18n/chromecast_de.properties
- Refactoring of binding
Some stuff lying around in my branches.
=> [chromecast] Refactoring of binding

bundles/org.openhab.binding.fsinternetradio/README.md, bundles/org.openhab.binding.fsinternetradio/src/main/java/org/openhab/binding/fsinternetradio/internal/FSInternetRadioDiscoveryParticipant.java, bundles/org.openhab.binding.fsinternetradio/src/test/java/org/openhab/binding/fsinternetradio/internal/handler/HandlerUtils.java, bundles/org.openhab.binding.fsinternetradio/src/test/java/org/openhab/binding/fsinternetradio/test/FSInternetRadioDiscoveryParticipantJavaTest.java, bundles/org.openhab.binding.fsinternetradio/src/test/java/org/openhab/binding/fsinternetradio/test/MockedRadioHandler.java, bundles/org.openhab.binding.fsinternetradio/src/test/java/org/openhab/binding/fsinternetradio/test/RadioServiceDummy.java
This PR integrates the Teufel 3sixty into the device discovery.
The 3sixty is not confirming the UPnP standard and returns empty manufacturer and model. However the friendly name is field is filled. Another detection has been implemented to identify a model by friendlyName containing manufacturer and/or model ID.
=> [fsinternetradio] Auto discovery for Teufel 3sixty

bundles/org.openhab.binding.modbus.sunspec/README.md
Those seem to make the website build fail, since the yaml frontmatter is parsed wrong this way.
cc: @kaikreuzer
=> [Modbus][Sunspec] Removed colons in Headline

bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/SunSpecConstants.java, bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/discovery/SunspecDiscoveryParticipant.java, bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/discovery/SunspecDiscoveryProcess.java, bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/dto/CommonModelBlock.java, bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/handler/AbstractSunSpecHandler.java, bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/parser/CommonModelParser.java
This pull request is the follow up of PR #6331 and adds the auto discovery feature to that.
Until PR #6331 is not merged this contains commits from that PR as well, so when reviewing please check the last commit only.
SunSpec splits the data of the devices into blocks that have a type and a length. So what the auto discovery does is that it will iterate over all these blocks and add the supported types as new things.
I didn't add more device types yet to keep the commit clean as much as possible
=> [sunspec] Modbus: sunspec bundle auto discovery

bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyHttpApi.java, bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyBaseHandler.java
Depending on timing it could happen that an incoming CoAP message trigges an auto-initialization while a thing is removing or has status REMOVED.
=> [shelly] Don't auto-initialize when thing is removing

bundles/org.openhab.binding.ambientweather/src/main/java/org/openhab/binding/ambientweather/internal/processor/Ws8482Processor.java
The processor for the WS8482 weather station was using the wrong data elements for the indoor temperature and humidity sensors.
=> [ambientweather] Fix ws8482 indoor sensor

bundles/org.openhab.binding.modbus.sunspec/DEVELOPERS.md, bundles/org.openhab.binding.modbus.sunspec/README.md, bundles/org.openhab.binding.modbus.sunspec/src/main/feature/feature.xml, bundles/org.openhab.binding.modbus/README.md, bundles/org.openhab.binding.modbus/src/main/feature/feature.xml, features/openhab-addons/pom.xml, features/openhab-addons/src/main/resources/footer.xml
=> [modbus] Cleaned modbus binding + extension docs

bundles/org.openhab.binding.samsungtv/README.md
Improvement 
Tested with device that was not listed as supported model:
Model: UE46F6510SS
Type No.: UE46F6510
Added supported channels: Mute, Volume and Channel. Others did not work.
=> [samsungtv] Update README.md with supported model UE46F6510SS

bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/internal/POP3IMAPHandler.java
See https://community.openhab.org/t/problem-refreshing-imap-pop3/95637
=> [mail] Fix protocol selection for SSL in POP3IMAPHandler

bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/SunSpecConstants.java, bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/SunSpecHandlerFactory.java, bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/dto/InverterModelBlock.java, bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/handler/AbstractSunSpecHandler.java, bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/handler/InverterHandler.java, bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/parser/InverterModelParser.java, bundles/org.openhab.binding.modbus.sunspec/src/main/resources/ESH-INF/thing/inverter-channel-groups.xml, bundles/org.openhab.binding.modbus.sunspec/src/main/resources/ESH-INF/thing/inverter-channel-types.xml, bundles/org.openhab.binding.modbus.sunspec/src/main/resources/ESH-INF/thing/inverter-types.xml
This pull request is the follow up of PR #6331, this is the complete support for single phase inverters as well support for two and three phase inverters. This is the 3rd of the 4 PR I've split my original PR into.
While it seems to be large at first, it does not change any of the main logic, just extends the parser and handler with the remaining fields of the incoming data. Also adds support for two and three phase inverters, but they are technically the same as the single phase inverter, only that have more channels than the single phase ones.
=> [modbus][sunspec] full inverter support

bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/discovery/LutronMdnsBridgeDiscoveryService.java
A small update to ignore mDNS discovery result from Lutron Connect Bridge devices, as they are not currently supported by the binding.
=> [lutron] Ignore Connect Bridge mDNS discovery

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoInfoDTO.java
As we don't really know the data types of these variables.
https://community.openhab.org/t/uid-thats-higher-than-max-int32-causes-exception/97333
=> [miio] fix parsing issue

bundles/org.openhab.binding.lutron/README.md, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/VirtualKeypadHandler.java, bundles/org.openhab.binding.lutron/src/main/resources/ESH-INF/thing/thing-types.xml
This is a small update which contains the following changes:
* Allows the virtualkeypad thing to control Caseta Smart Hub scene buttons using a new model="Caseta" option.
* Related doc update plus minor doc fixes
=> [lutron] Add Caseta model option to virtualkeypad

bundles/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/api/FreeboxApiManager.java, bundles/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/security/LxWsSecurity.java, bundles/org.openhab.binding.millheat/src/main/java/org/openhab/binding/millheat/internal/handler/MillheatAccountHandler.java, itests/org.openhab.binding.mqtt.homeassistant.tests/itest.bndrun, itests/org.openhab.binding.mqtt.homie.tests/itest.bndrun, itests/org.openhab.io.mqttembeddedbroker.tests/itest.bndrun
- Removed dependency on 'org.apache.commons.codec' to fix OH3 add-ons build: https://ci.openhab.org/job/openHAB-Addons-port/108/
Related to https://github.com/openhab/openhab-core/pull/1436 
=> Removed dependency on 'org.apache.commons.codec'

bundles/org.openhab.binding.pjlinkdevice/src/main/java/org/openhab/binding/pjlinkdevice/internal/device/PJLinkDevice.java
This at least improves the situation reported in issue #6725. 
Some PJLink devices seem to be not fully compliant, and send \0 bytes in front of messages.
The device does seem to have other issues, but this one is rather easy to fix by removing leading \0 bytes and also does not have negative impact on compliant devices.
=> [pjlink] Null characters fix

bundles/org.openhab.binding.innogysmarthome/src/main/java/org/openhab/binding/innogysmarthome/internal/client/InnogyClient.java, bundles/org.openhab.binding.innogysmarthome/src/main/java/org/openhab/binding/innogysmarthome/internal/client/entity/action/ActionParams.java, bundles/org.openhab.binding.innogysmarthome/src/main/java/org/openhab/binding/innogysmarthome/internal/client/entity/action/ShutterAction.java, bundles/org.openhab.binding.innogysmarthome/src/main/java/org/openhab/binding/innogysmarthome/internal/handler/InnogyBridgeHandler.java, bundles/org.openhab.binding.innogysmarthome/src/main/java/org/openhab/binding/innogysmarthome/internal/handler/InnogyDeviceHandler.java
[innogysmarthome] Optimizes the control of Shutters (ISR2) by using the correct api-calls. Adding the possibility to use the "STOP" command when the shutters are moving.
In the current release the binding uses the "SetState" command to move the shutters (When user clicks on arrow buttons of the default sitemap-widget). So in fact it sets the position variable to 0% or 100%. The stop button was not working. In this PR I use the same API-call as Innogy uses in their app to start moving the shutters (RampStart). I also added support for the STOP-button by using the "RampStop" API-call. This was a missing feature.
=> [innogysmarthome] Fix isr2stop

bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComBlinds1Message.java
Added Cherubini blinds for the Blinds1 (support for Cherubini was added in RFXCom in Version 5.68 - 26/02/2020 ).
I have Cherubini blinds and this very simple addon to the enum does the trick.
The deviceId can be found in RFXMgr when sending a command
   id1-3         = 103000 decimal:1060864
it's the decimal part to which you add .0
Thing blinds1 Salon "Volet Salon" [ deviceId="1060864.0", subType="18" ]
Please note that there is also T14, T15, T16, T17, maybe support for them is also as easy as completing the enum ... since I cannot test, I didn't add them.
Fixes #7417 
Signed-off-by: Fabien Le Bars <github@bleizig.net>
=> [rfxcom] Added Cherubini blinds support

bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcBaseDAO.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcMapper.java
When the setting is removed instead of set to false, tables will continue to be rebuild every startup causing an exception:
```
2020-04-18 15:54:17.852 [ERROR] [org.knowm.yank.Yank                 ] - Error in SQL query!!!
java.sql.SQLException: Error preparing query: Query was empty Query:  Parameters: []
at org.apache.commons.dbutils.AbstractQueryRunner.rethrow(AbstractQueryRunner.java:392) ~[commons-dbutils-1.6.jar:1.6]
at org.apache.commons.dbutils.QueryRunner.update(QueryRunner.java:491) ~[commons-dbutils-1.6.jar:1.6]
at org.apache.commons.dbutils.QueryRunner.update(QueryRunner.java:457) ~[commons-dbutils-1.6.jar:1.6]
at org.knowm.yank.Yank.execute(Yank.java:194) [yank-3.2.0.jar:?]
at org.knowm.yank.Yank.execute(Yank.java:177) [yank-3.2.0.jar:?]
at …
```
=> [jdbc] Improve rebuildTableNames behavior

bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/client/RpcClient.java, bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/client/XmlRpcClient.java
Solves #6963
For HM installations with a large number of devices the maximum buffer size used by sync HTTP request was too small. Async requests allow larger buffers.
=> [homematic] Use async Jetty http request to support larger buffers

bundles/org.openhab.binding.coronastats/src/main/java/org/openhab/binding/coronastats/internal/dto/CoronaStatsCases.java, bundles/org.openhab.binding.coronastats/src/main/resources/ESH-INF/thing/channel-type.xml
=> [coronastats] Use QuantityType instead of plain DecimalType

bundles/org.openhab.io.hueemulation/README.md, bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/ConfigStore.java, bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/HueEmulationConfig.java, bundles/org.openhab.io.hueemulation/src/main/resources/ESH-INF/config/config.xml
Non uniform parameter naming prevented config param from being saved
and used for discovery.
[hueemulation] Fixes discovery IP not saved/used
This is a fix for the issue opened by me: https://github.com/openhab/openhab-addons/issues/7410
=> [hueemulation] Fixes HueEmulation DiscoveryIp not used

bundles/org.openhab.binding.pjlinkdevice/src/main/resources/ESH-INF/thing/thing-types.xml
This PR adds parameter groups to the pjlinkdevice thing for a better visual structure. No new features or parameters have been introduced.
=> [pjlink] use parameter-groups for better structure of thing parameters

bundles/org.openhab.binding.insteon/src/main/resources/ESH-INF/thing/thing-types.xml, bundles/org.openhab.binding.insteon/src/main/resources/device_types.xml
Recently bought one of these and these features were not supported by OH.
Interesting note, I suspected this would act just like a 2477D dimmer and it mostly does, but it does not respond to local on-level changes so I left that feature out. You can set the local on-level and reading the Status, you can see it takes the change, but pressing the hardware button still goes to full brightness - disregarding the OL setting.
This is for Feature Request: https://github.com/openhab/openhab-addons/issues/7469
=> [insteon] Added support to 2472D OutletLinc Dimmer for LED On/Off, LED Brightness, Local Ramp Rate and Beep

bundles/org.openhab.binding.ecobee/README.md
Improve the initial setup instructions to explain how to get an API key.
=> [ecobee] Improve initial setup instructions

bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/api/EcobeeApi.java
There have been cases where the call to the Ecobee API has resulted in a response indicating that the token has expired. It happens very rarely, typically once every 2-4 weeks. Generally, this should not happen, since the OAuthClientService in OHC uses an expire time buffer (default is 10 seconds) to refresh the token before it expires.
I wanted to change the expire time buffer to a longer amount, but the API currently doesn't support that. See [here](https://github.com/openhab/openhab-core/issues/1438).
Therefore, in this PR, the binding will check for expiration using a custom expire time buffer (using `AccessTokenResponse.isExpired()`, then refresh the access token if `isExpired()` returns true.
Also, the access token expired response from the Ecobee API will be handled less harshly. …
=> [ecobee] Improve handling of access token expiration

bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueBridgeHandler.java
=> [hue] Improved code (notify status listener)

bundles/org.openhab.binding.avmfritz/README.md
I just added an example for **FRITZ_DECT_Repeater_100** which was not provided beforehand. I had to look up the code in the repository to find out the correct Thing definition, so I added it for all those who just want to look it up in the docs.
=> [avmfritz] documentation example for FRITZ DECT Repeater 100

bundles/org.openhab.binding.hue/README.md, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/FullGroup.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/Group.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/HueBindingConstants.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/HueBridge.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/HueThingHandlerFactory.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/State.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/discovery/HueLightDiscoveryService.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/GroupStatusListener.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueBridgeHandler.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueClient.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueGroupHandler.java, bundles/org.openhab.binding.hue/src/main/resources/ESH-INF/i18n/hue.properties, bundles/org.openhab.binding.hue/src/main/resources/ESH-INF/i18n/hue_fr.properties, bundles/org.openhab.binding.hue/src/main/resources/ESH-INF/thing/Group.xml
=> [hue] Add support for groups/rooms

bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueBridgeHandler.java
Due registration of discovery service as listeners for lights, groups and sensors the checked lists are never empty. So start polling can although be started right away on initialization of bridge handler and must not be stopped before dispose of this handler.
=> [hue] Refactored start, stop polling

bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/handler/AbstractAvrHandler.java, bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/protocol/StreamAvrConnection.java, bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/protocol/avr/AvrConnection.java
This PR adds support for REFRESH commands on Pioneer AVR channels where this makes sense.
This way the REFRESH caused by BaseThingHandler.channelLinked() is properly handled.
Signed-off-by: Nils Schnabel <github@to.nilsschnabel.de>
=> [pioneeravr] support REFRESH command type where applicable

bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/EcobeeBindingConstants.java, bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/handler/EcobeeSensorThingHandler.java, bundles/org.openhab.binding.ecobee/src/main/resources/ESH-INF/thing/thing-types.xml
Fixes NPE in thing update REST API caused by a missing ChannelTypeUID on dynamically created channels on sensor thing.
See [here](https://community.openhab.org/t/ecobee-binding-v2/97733/7?u=mhilbush) and [here](https://github.com/openhab/openhab-core/issues/1457).
=> [ecobee] Add ChannelTypeUID for dynamic channels

bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/handler/RFXComBridgeHandler.java
We currently get a message every 60 seconds if we turn on rfxcom debug logging. As its useful to turn on debug logging for this binding for checking messages are being detected and working out undecoded/raw strings, having a repeated message is not great.
=> [rfxcom] Move connection check to trace logging

bundles/org.openhab.transform.jinja/pom.xml, bundles/org.openhab.transform.jinja/src/main/feature/feature.xml
It will fail to compile when jersey-all is removed because that artifact also contains the jackson and javassist packages.
Related to openhab/openhab-core#1443
=> [jinja] Remove dependency on jersey-all

bundles/org.openhab.binding.sonyaudio/README.md, bundles/org.openhab.binding.sonyaudio/src/main/java/org/openhab/binding/sonyaudio/internal/SonyAudioBindingConstants.java, bundles/org.openhab.binding.sonyaudio/src/main/java/org/openhab/binding/sonyaudio/internal/handler/SonyAudioHandler.java, bundles/org.openhab.binding.sonyaudio/src/main/resources/ESH-INF/thing/ht-z9f-zf9.xml
Sony Soundbars, or at least the HT-ZF9, have a boolean setting
called Night Mode. This limits the maximum loudness, AFAICT doing
dynamic range compression.
This commit adds support for enabling/disabling Night Mode to the
handler and the definition to the ThingType for the ZF9.
It's actually a setting in the "Soundsettings" JSON but I think
exposing it as a boolean at the top level is the most sensible way
of presenting the interface.
Signed-off-by: Jack Challen <jackchallen@gmail.com>
=> [sonyaudio] Add Night Mode (volume limiting) for Soundbars/AV receivers

bundles/org.openhab.binding.cm11a/pom.xml, bundles/org.openhab.binding.digiplex/pom.xml, bundles/org.openhab.binding.dscalarm/pom.xml, bundles/org.openhab.binding.elerotransmitterstick/pom.xml, bundles/org.openhab.binding.jeelink/pom.xml, bundles/org.openhab.binding.knx/pom.xml, bundles/org.openhab.binding.lgtvserial/pom.xml, bundles/org.openhab.binding.lutron/pom.xml, bundles/org.openhab.binding.meteostick/pom.xml, bundles/org.openhab.binding.nibeheatpump/pom.xml, bundles/org.openhab.binding.oceanic/pom.xml, bundles/org.openhab.binding.pentair/pom.xml, bundles/org.openhab.binding.phc/pom.xml, bundles/org.openhab.binding.regoheatpump/pom.xml, bundles/org.openhab.binding.rme/pom.xml, bundles/org.openhab.binding.smartmeter/pom.xml, bundles/org.openhab.binding.urtsi/pom.xml, bundles/org.openhab.binding.velbus/pom.xml
The first version of nrjavaserial with OSGi manifest entries is 3.12.0.
The interface has not changed and is still the same with nrjavaserial 5.x.
So defining a [3.12,6) version range allows for maximum flexibility.
Related to: openhab/openhab-core#1464
---
When the serial transport is used for these add-ons (#7573) we should remove these imports again. Though it can still take a while for all add-ons to be updated. Especially if we also need to add extra functionality to the transport which cannot be used on the 2.5.x branch.
=> Use gnu.io [3.12,6) version range in package imports

bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/handler/AvrHandlerFactory.java, bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/handler/SerialAvrHandler.java, bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/protocol/serial/SerialAvrConnection.java
=> [pioneeravr] Use serial transport

bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/discovery/SqueezeBoxPlayerDiscoveryParticipant.java, bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/discovery/SqueezeBoxServerDiscoveryParticipant.java, bundles/org.openhab.binding.squeezebox/src/main/resources/ESH-INF/thing/thing-types.xml
Setting this property to the required fields of the bridge and things
will make the discovery skip adding the result to the inbox if a bridge or
thing with such a property already exists, i.e. due to a .things file.
=> [squeezebox] Discovery: make use of representation property

CODEOWNERS, bom/openhab-addons/pom.xml, bundles/org.openhab.binding.danfossairunit/.classpath, bundles/org.openhab.binding.danfossairunit/.project, bundles/org.openhab.binding.danfossairunit/NOTICE, bundles/org.openhab.binding.danfossairunit/README.md, bundles/org.openhab.binding.danfossairunit/pom.xml, bundles/org.openhab.binding.danfossairunit/src/main/feature/feature.xml, bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/Channel.java, bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/ChannelGroup.java, bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/Commands.java, bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/DanfossAirUnit.java, bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/DanfossAirUnitBindingConstants.java, bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/DanfossAirUnitCommunicationController.java, bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/DanfossAirUnitConfiguration.java, bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/DanfossAirUnitHandler.java, bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/DanfossAirUnitHandlerFactory.java, bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/DanfossAirUnitReadAccessor.java, bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/DanfossAirUnitWriteAccessor.java, bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/Mode.java, bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/UnexpectedResponseValueException.java, bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/ValueCache.java, bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/discovery/DanfossAirUnitDiscoveryService.java, bundles/org.openhab.binding.danfossairunit/src/main/resources/ESH-INF/binding/binding.xml, bundles/org.openhab.binding.danfossairunit/src/main/resources/ESH-INF/thing/thing-types.xml, bundles/org.openhab.binding.danfossairunit/src/test/java/org/openhab/binding/danfossairunit/internal/ValueCacheTest.java, bundles/pom.xml
Signed-off-by: Robert Bach <openhab@mortalsilence.net>
[danfossairunit] Initial contribution
This initial contribution of the danfoss air unit binding is the result of an ongoing discussion which can be found here: https://community.openhab.org/t/danfoss-air-unit-ethernet-connection/17844
It will allow to connect to the air units via ethernet and poll for monitoring values (temperatures and ventilation speed and so on). It furthermore allows to set several parameters (bypass mode, fan speed override, ...). 
The air unit is detected via autodiscovery (broadcast on a well known port). It is queried for the monitoring values (polling) in a configurable refresh interval. 
A pre-built binary can be downloaded here:
https://github.com/pravussum/openhab2-addons/releases/tag/2.5.1-danfossair_alpha …
=> [danfossairunit] Danfoss AirUnit binding - initial commit

bundles/org.openhab.binding.opensprinkler/README.md
fixed typo in first example (password was missing an 's')
=> [opensprinkler] Fixed typo in README.md

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/discovery/MiIoDiscovery.java, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/discovery/MiIoDiscoveryParticipant.java
The property has to be set to the property name and not to its value.
=> [miio] Fix representation property in discovery

bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitCharacteristicFactory.java
fix the issue reported here
https://community.openhab.org/t/homekit-addon-2-5-5-lightbulb-brightness-dimmer-not-working/98604/11
=> [homekit] fix support of DimmerItem for Brightness

bundles/org.openhab.binding.mcp23017/README.md
```
living_room_led_switch.state != ON ? ON : OFF
```
This is a JavaScript ternary operator and invalid syntax for Rules DSL Rules.
I replaced it with the Rules DSL correct syntax
Signed-off-by Richard Koshak <rlkoshak@gmail.com>
=> [mcp23017] Fixed invalid ternary operator in example Rule

bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/handler/TradfriGatewayHandler.java
This PR tries to resolve the issue with the TRADFRI binding lossing contact with IKEA GW reported in many community threads. 
The binding had implementation for some reconnect attempt but that was not sufficient. This PR instead perfroms a dispod/initialize of the binding when this communication error occurs.
I have tested in successfully in my production environment, here are logs for when the binding re-initialized during a communication error:
```
2020-03-31 19:30:37.791 [DEBUG] [internal.handler.TradfriLightHandler] - Setting state to OFF
2020-03-31 19:31:00.696 [DEBUG] [g.tradfri.internal.TradfriCoapClient] - CoAP GET request
uri: coaps://192.168.1.134:5684/15011/15012
2020-03-31 19:31:57.045 [DEBUG] [iscovery.TradfriDiscoveryParticipant] - Discovered Tradfri gateway: …
```
=> [tradfri] Do a dispose() and initialize() when loosing contact with GW.

bundles/org.openhab.binding.kostalinverter/README.md
[kostal-inverter] added troubleshooting information to the README file for authentication issues with 3rd gen kostal-inverter binding
I've added a little section to the README file of the kostal-inverter binding indicating that the third generation devices (SCB) require Java's strong cryptography to be enabled for successfully establishing connections. Moreover I've added some lines that describe how to enable strong cryptography (including legal law restrictions for some countries).
Maybe you could re-arrange the positioning of my text and put it into a troubleshooting section. The content should be fine.
There were no changes made to the source code, just to the documentation. And I've also tested my fix instructions with the latest official docker image of openHAB.
=> [kostal-inverter] added troubleshooting information for authentication issues with 3rd gen kostal-inverter binding

bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/AbstractKNXThingHandler.java, bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/DeviceThingHandler.java
On disposal of the DeviceThingHandler several scheduled futures were not
canceled and internal datastructures were not reset.
This leads to a problem if one changes the thing configuration, for example
via editing the .things file. Then `dispose()` and `initialize()` will be
called and the datastructures will still also contain the old values.
This is nasty in cases where one wants to change the group addresses for
channels.
Also the `address` field from the `AbstractKNXThingHandler` was redefined
in the `DeviceThingHandler` but never ever set there.
=> [knx] Fix disposal of DeviceThingHandler

bundles/org.openhab.binding.somfytahoma/README.md, bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/SomfyTahomaBindingConstants.java, bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaAdjustableSlatsRollerShutterHandler.java, bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaVenetianBlindHandler.java, bundles/org.openhab.binding.somfytahoma/src/main/resources/ESH-INF/thing/adjustableslatsrollershutter.xml, bundles/org.openhab.binding.somfytahoma/src/main/resources/ESH-INF/thing/channels.xml, bundles/org.openhab.binding.somfytahoma/src/main/resources/ESH-INF/thing/exteriorvenetianblind.xml, bundles/org.openhab.binding.somfytahoma/src/main/resources/ESH-INF/thing/venetianblind.xml
This PR just adds a special channel for setting the closure and orientation at once for blinds and adjustable roller shutters.
It was requested in the forum
https://community.openhab.org/t/tahoma-binding-compatible-with-oh2/27004/465?u=ondrej_pecta
Regard.
Ondrej
=> [somfytahoma] added channel for setting closure and orientation at once

bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/handler/DaikinAcUnitHandler.java, bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/handler/DaikinAirbaseUnitHandler.java, bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/handler/DaikinBaseHandler.java
Currently the binding doesn't catch IllegalArgumentExceptions for invalid channel values. This small PR deals with that and prevents the Thing from going offline.
Reported here: https://community.openhab.org/t/daikin-airbase-binding/77179/193
=> [daikin] Improve handling of illegal commands

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoVacuumHandler.java
=> [miio] Establish connection in initialize() rather than the constructor

bundles/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/handler/SerialBridgeHandler.java
Remove check for no serial ports, as it seems to be no longer necessary and keeps RFC2217 connections from working. See #7609 and openhab/openhab-core#1462 for details.
=> [alarmdecoder] Remove check for no serial ports

bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/LutronHandlerFactory.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/hw/HwSerialBridgeHandler.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/radiora/RS232Connection.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/radiora/handler/RS232Handler.java
This update contains changes which replace direct use of the gnu.io serial library (aka RXTX) with calls to OH serial transport. It impacts the bridge handlers for the original RadioRA system (ra-rs232), and the original HomeWorks system (hwserialbridge).
The need for this is discussed in issue #7573.
Note that **I have no way to test these changes** so I would appreciate it if the original authors, @jjlauterbach and @andrewshilliday could review and test this code!
A jar file containing the binding with these changes is available here:
https://github.com/bobadair/openhab2-addons/releases/tag/serial-beta-1
=> [lutron] Replace gnu.io with OH serial transport

bundles/org.openhab.persistence.dynamodb/src/main/java/org/openhab/persistence/dynamodb/internal/AbstractDynamoDBItem.java, bundles/org.openhab.persistence.dynamodb/src/main/java/org/openhab/persistence/dynamodb/internal/DynamoDBPersistenceService.java, bundles/org.openhab.persistence.dynamodb/src/main/java/org/openhab/persistence/dynamodb/internal/DynamoDBQueryUtils.java, bundles/org.openhab.persistence.dynamodb/src/test/java/org/openhab/persistence/dynamodb/internal/AbstractTwoItemIntegrationTest.java, bundles/org.openhab.persistence.dynamodb/src/test/java/org/openhab/persistence/dynamodb/internal/CallItemIntegrationTest.java, bundles/org.openhab.persistence.dynamodb/src/test/java/org/openhab/persistence/dynamodb/internal/ColorItemIntegrationTest.java, bundles/org.openhab.persistence.dynamodb/src/test/java/org/openhab/persistence/dynamodb/internal/ContactItemIntegrationTest.java, bundles/org.openhab.persistence.dynamodb/src/test/java/org/openhab/persistence/dynamodb/internal/DateTimeItemIntegrationTest.java, bundles/org.openhab.persistence.dynamodb/src/test/java/org/openhab/persistence/dynamodb/internal/DimmerItemIntegrationTest.java, bundles/org.openhab.persistence.dynamodb/src/test/java/org/openhab/persistence/dynamodb/internal/LocationItemIntegrationTest.java, bundles/org.openhab.persistence.dynamodb/src/test/java/org/openhab/persistence/dynamodb/internal/NumberItemIntegrationTest.java, bundles/org.openhab.persistence.dynamodb/src/test/java/org/openhab/persistence/dynamodb/internal/RollershutterItemIntegrationTest.java, bundles/org.openhab.persistence.dynamodb/src/test/java/org/openhab/persistence/dynamodb/internal/StringItemIntegrationTest.java, bundles/org.openhab.persistence.dynamodb/src/test/java/org/openhab/persistence/dynamodb/internal/SwitchItemIntegrationTest.java
=> [dynamodb] Fix CallItem IT, ZonedDateTime into wide use

bundles/org.openhab.binding.alarmdecoder/src/main/resources/ESH-INF/thing/thing-types.xml, bundles/org.openhab.binding.bluetooth.bluegiga/src/main/resources/ESH-INF/thing/bluegiga.xml, bundles/org.openhab.binding.cm11a/src/main/resources/ESH-INF/thing/thing-types.xml, bundles/org.openhab.binding.digiplex/src/main/resources/ESH-INF/thing/bridge.xml, bundles/org.openhab.binding.dscalarm/src/main/resources/ESH-INF/thing/it100bridge.xml, bundles/org.openhab.binding.dsmr/src/main/resources/ESH-INF/config/configuration_parameters.xml, bundles/org.openhab.binding.elerotransmitterstick/src/main/resources/ESH-INF/thing/thing-types.xml, bundles/org.openhab.binding.jeelink/src/main/resources/ESH-INF/thing/thing-types.xml, bundles/org.openhab.binding.lgtvserial/src/main/resources/ESH-INF/config/config.xml, bundles/org.openhab.binding.lutron/src/main/resources/ESH-INF/thing/thing-types.xml, bundles/org.openhab.binding.meteostick/src/main/resources/ESH-INF/thing/thing-types.xml, bundles/org.openhab.binding.modbus/src/main/resources/ESH-INF/thing/bridge-serial.xml, bundles/org.openhab.binding.nikobus/src/main/resources/ESH-INF/thing/thing-types.xml, bundles/org.openhab.binding.oceanic/src/main/resources/ESH-INF/thing/serial.xml, bundles/org.openhab.binding.phc/src/main/resources/ESH-INF/thing/thing-types.xml, bundles/org.openhab.binding.pioneeravr/src/main/resources/ESH-INF/thing/thing-types.xml, bundles/org.openhab.binding.plugwise/src/main/resources/ESH-INF/config/config.xml, bundles/org.openhab.binding.powermax/src/main/resources/ESH-INF/thing/serial.xml, bundles/org.openhab.binding.regoheatpump/src/main/resources/ESH-INF/thing/thing-types.xml, bundles/org.openhab.binding.rfxcom/src/main/resources/ESH-INF/thing/bridge.xml, bundles/org.openhab.binding.rme/src/main/resources/ESH-INF/thing/rme.xml, bundles/org.openhab.binding.rotel/src/main/resources/ESH-INF/config/config.xml, bundles/org.openhab.binding.satel/src/main/resources/ESH-INF/thing/int-rs.xml, bundles/org.openhab.binding.serialbutton/src/main/resources/ESH-INF/thing/thing-types.xml, bundles/org.openhab.binding.sonyprojector/src/main/resources/ESH-INF/thing/serial.xml, bundles/org.openhab.binding.urtsi/src/main/resources/ESH-INF/thing/thing-types.xml, bundles/org.openhab.binding.velbus/src/main/resources/ESH-INF/config/config.xml
When serial port options are limited it is only possible to configure discovered ports.
RXTX discovery only detects standard serial ports.
The serial transport adds undiscovered ports to 'gnu.io.rxtx.SerialPorts' so this way users do not need to manually configure it.
RFC2217 ports cannot be detected so if the ports are limited it is not possible to configure these using UIs.
Related to:
* https://github.com/openhab/openhab-core/issues/1029
* https://github.com/openhab/openhab-core/issues/1462
=> Don't limit serial port options

bundles/org.openhab.binding.jeelink/pom.xml, bundles/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/JeeLinkHandler.java, bundles/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/JeeLinkHandlerFactory.java, bundles/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/connection/AbstractJeeLinkConnection.java, bundles/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/connection/JeeLinkSerialConnection.java
=> [jeelink] Use serial transport

bundles/org.openhab.io.transport.modbus/pom.xml
The gnu.io package is not only used in tests but is also a transitive dependency of net.wimpi:jamod
Related to #7589
---
This should also fix the failing add-ons port build:
https://ci.openhab.org/job/openHAB-Addons-port/125/console
=> [modbus] Use gnu.io [3.12,6) version range

bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc2/NhcAction2.java, bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc2/NikoHomeControlCommunication2.java
- Fix energy meter behaviour at reconnection and reduce log level to avoid logs every 2s.
- Fix rollershutter position status feedback and pass on intermediate position info when moving to OH.
=> [nikohomecontrol] Fixes to rollershutter and energy meter.

bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/command/IntegraStatusCommand.java, bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/event/IntegraStatusEvent.java, bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/handler/SatelSystemHandler.java
This PR contais a fix for incorrect date and time set on the alarm system. 
Instead of restarting communication the binding logs a message and ignores received value.
Issue described here: https://community.openhab.org/t/solved-satel-disconnections-after-integra-mainboard-upgrade/79227
=> [satel] Fix for incorrect date/time set in the alarm system

bundles/org.openhab.binding.meteostick/pom.xml, bundles/org.openhab.binding.meteostick/src/main/java/org/openhab/binding/meteostick/internal/MeteostickHandlerFactory.java, bundles/org.openhab.binding.meteostick/src/main/java/org/openhab/binding/meteostick/internal/handler/MeteostickBridgeHandler.java
=> [meteostick] Use serial transport

bundles/org.openhab.binding.smartmeter/pom.xml
It only has a reference to gnu.io in a JavaDoc so it shouldn't have been added in #7589.
=> [smartmeter] Remove unused gnu.io import package

bundles/org.openhab.binding.hpprinter/README.md, bundles/org.openhab.binding.hpprinter/src/main/java/org/openhab/binding/hpprinter/internal/HPPrinterBindingConstants.java, bundles/org.openhab.binding.hpprinter/src/main/java/org/openhab/binding/hpprinter/internal/api/HPStatus.java, bundles/org.openhab.binding.hpprinter/src/main/java/org/openhab/binding/hpprinter/internal/binder/HPPrinterBinder.java
This PR fixes a bug introduced in a previous PR which caused the Status Channel to no longer display the Status from the Printer.
This also fixes a bug in the Colour Ink Levels - they were supposed to be of type `Number:Dimensionless` like the Black Ink Level channel but were of type `Number`
This improves the Ink Marking channels by changing the channel type to `Number:Volume`. This means that you can use the built in openHAB functionality to display in the unit you want (these channels were intended to be this type).
There is also an update to the Readme with some sample channels based on a stale PR #6717 that the original user opened but then went AWOL.
=> [hpprinter] Status Bugfix and Channel Improvements

bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/TVControlChannel.java
=> [lgwebos] Use channel id as state for the channel channel

bundles/org.openhab.binding.coolmasternet/src/main/java/org/openhab/binding/coolmasternet/internal/handler/HVACHandler.java
This commit corrects a regression introduced in #7546 where the `set_temp` channel was changed to a `QuantityType`.
This has been tested on a CoolMasterNet deployment using a `Setpoint` element in the sitemap.
=> [coolmasternet] Fix set_temp channel bug

bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/discovery/LutronDeviceDiscoveryService.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/discovery/project/OutputType.java
This is a very small commit that adds the RELAY_LIGHTING output type to discovery.
=> [lutron] Add an additional output type to discovery

bundles/org.openhab.binding.robonect/src/main/java/org/openhab/binding/robonect/internal/model/MowerStatus.java
This modification allows the binding to recognize when the door needs to be opened.
=> [robonect] Added status 18, Doordelay

bundles/org.openhab.binding.opengarage/README.md, bundles/org.openhab.binding.opengarage/src/main/java/org/openhab/binding/opengarage/internal/OpenGarageChannelConfiguration.java, bundles/org.openhab.binding.opengarage/src/main/java/org/openhab/binding/opengarage/internal/OpenGarageHandler.java, bundles/org.openhab.binding.opengarage/src/main/resources/ESH-INF/thing/thing-types.xml
This adds the ability to invert the switch state so that OFF=OPEN and ON=Closed.  This allows the state to be more aligned with other close/locking things like Z-wave locks, while maintaining backwards compatibility for existing users.
=> [opengarage] Adds invert option to switch

bundles/org.openhab.binding.onewire/pom.xml, bundles/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/device/DS2406_DS2413.java, bundles/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/owserver/OwserverConnectionState.java
* Fixed that DS2406_DS2413 are reading uncached (like other IODevices) - issue: https://github.com/openhab/openhab-addons/issues/7148
* Fixed spotless formatter issue introduced by jenkins prep job on 17th of May in pom.xml (see https://github.com/Urmel/openhab-addons/commit/b6edbac44965ec5ed3e32425217c14683b5685a9#diff-3450cdb8b77d7a8d583d3374d14a6676)
* Removed unused import in OwserverConnectionState as it produced a warning
Maybe the jenkins job should be fixed....?
=> [onewire] Fix that DS2406_DS2413 are reading uncached like other IODevices (#7148) + spotless

bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitAccessoryRegistry.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitChangeListener.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitImpl.java
HomeKit uses configuration revision number to indicate changes in the configuration of accessories and bridges. 
Bridge (in our case openHAB) communicates the revision number to all clients (home apps) and  should increase it with every change in configuration (in our case items config). This is supported by HomeKit addon. However, on HomeKit bundle restart the revision was set to 1.  
e.g. before bundle restart the revision was 34. after bundle restart the revision was set to 1.
This could lead in some cases to a configuration reset in home app so that all changes done in home app (e.g. room assignment, scenes, renaming) will get lost. See #7701 
This PR ensures that the configuration revision is set correctly on the bundle start.
=> [homekit] bugfix #7701. set correct configuration revision on bundle start. 

bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/discovery/MQTTTopicDiscoveryService.java, bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/internal/MqttBrokerHandlerFactory.java
[mqtt] Add publish capability to MQTTTopicDiscoveryService
This patch adds publish capability to MQTTTopicDiscoveryService exposed by the org.openhab.binding.mqtt to allow other bindnigs to do an "active" scan.
Certain MQTT devices respond as a result to a certain message published on a discovery topic, and now other bindings can use the infrastructure laid out by the mqtt binding to do this type of discovery.
A discussion regarding this topic was held here:
https://community.openhab.org/t/adding-mqtttopicdiscoveryservice-publish-method/84713
=> [mqtt] Added publish method to MQTTTopicDiscoveryService

bundles/org.openhab.binding.daikin/README.md
Added BRP069B41 as a compatible Wifi device. I tested all channels but homekitmode of the non-airbase section. I'm running BRP069B41 on 3 devices. Let me know if you need any additional details or proof.
Side note. The Thing Configuration section refers to a refresh option but it is not used in the Full Example section. Is it still a valid option? Then it should probably be used in the full example. If it's not longer of use then it might be removed from the section above.
Signed-off-by: Andreas Liewen github.andreas@liewen.net
=> [daikin] Add BRP069B41 to documentation

bundles/org.openhab.binding.satel/README.md, bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/config/SatelBridgeConfig.java, bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/handler/Ethm1BridgeHandler.java, bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/handler/IntRSBridgeHandler.java, bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/protocol/Ethm1Module.java, bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/protocol/IntRSModule.java, bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/protocol/SatelModule.java, bundles/org.openhab.binding.satel/src/main/resources/ESH-INF/thing/ethm-1.xml, bundles/org.openhab.binding.satel/src/main/resources/ESH-INF/thing/int-rs.xml
This PR introduces new configuration option "extCommands" for both bridge things. This option replaces existing way of checking whether a bridge supports extended commands.
It turned out that older firmware versions does not respond to command that gives information about features of the bridge.
Relevant discussion starts here: https://community.openhab.org/t/satel-binding-support-announcements-and-feature-requests/56135/158
=> [satel] Fix for older ETHM-1/INT-RS firmware version

bundles/org.openhab.binding.samsungtv/README.md
Added UE50MU6179 as I was able to use a number of channels. Let me know if any additional details or proof are needed.
Added a table with valid values for some common apps for users' convenience as well as a reference to the log file to find any additionally installed apps.
Side note: Key codes for remote control simulation might be useful as well since online documentation seems rather weak. I'm happy to contribute as I learn more - just unsure how this should be structured, by TV type or remote type.
Signed-off-by: Andreas Liewen github.andreas@liewen.net
=> [samsungtv] Add UE50MU6179 and additional documentation

bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/handler/PowermaxBridgeHandler.java, bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/message/PowermaxCommManager.java
=> [powermax] Removed dependency on 'org.apache.commons.lang'

bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitChangeListener.java
HomeKit integration was expecting that root accessories (e.g. group or single accessories) are tagged only with accessory type without any characteristics, e.g.
`Number humidity "Humidity Sensor" {homekit = "HumiditySensor"}`
however, following is also a valid definition but it was ignored as characteristic was not empty. 
`Number humidity "Humidity Sensor" {homekit = "HumiditySensor.RelativeHumidity"}`
this PR removes the filter on the "empty characteristic" for root accessories. 
Closes #7695 
=> [homekit] bugfix for #7695. allow root accessory have characteristics

bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitTaggedItem.java
remove dependency on org.apache.commons. (#7722)
the only usage was the HashCodeBuilder that can be easily replaced. the change is backwards compatible as it generates the same hash codes.
=> [homekit] remove dependency on org.apache.commons

bundles/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/discovery/FreeboxDiscoveryService.java, bundles/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/handler/FreeboxHandler.java
=> [freebox] Removed dependency on 'org.apache.commons.lang'

bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/tools/WaitForTopicValue.java, bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/internal/discovery/Homie300Discovery.java
The ```future``` attribute was overwritten in the constructor and, as a consequence, the ```whenComplete``` lambda method was not called. This made it impossible to re-subscribe to the same topic from the same connection. This fix is critical for Homie users, as the extensions uses this function in the discovery process.
A couple of typos are also fixed.
Closes #6975 
Closes #7252
Reviewers: @jochen314, @J-N-K, @cpmeister 
=> [mqtt] Correctly unsubscribe after message is received

bundles/org.openhab.persistence.jdbc/pom.xml, bundles/org.openhab.persistence.mapdb/pom.xml
The javassist dependency previously provided by the jetty-all bundle is no longer available causing the openhab-persistence-jdbc-derby feature verification to fail. It is unknown to me if it is really required so I've made it an optional import for now:
`[ERROR] Message: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=openhab-persistence-jdbc-derby; type=karaf.feature; version=3.0.0.SNAPSHOT; filter:="(&(osgi.identity=openhab-persistence-jdbc-derby)(type=karaf.feature)(version>=3.0.0.SNAPSHOT))" [caused by: Unable to resolve openhab-persistence-jdbc-derby/3.0.0.SNAPSHOT: missing requirement [openhab-persistence-jdbc-derby/3.0.0.SNAPSHOT] osgi.identity; osgi.identity=org.openhab.persistence.jdbc; type=osgi.bundle; …
=> Fix jdbc and mapdb persistence build errors

bundles/org.openhab.binding.sensibo/src/main/java/org/openhab/binding/sensibo/internal/handler/SensiboSkyHandler.java
Sensibo API always report measured temperature as celsius and not the user chosen unit
Signed-off-by: Arne Seime <arne.seime@gmail.com>
=> [sensibo] Temperature measurements are always celsius despite chosen unit

bundles/org.openhab.persistence.jdbc/pom.xml
This reduces the bundle size from 16MB to just 300kB by not embedding the feature bundle dependencies into the bundle itself.
Related to #5275
=> [jdbc] Reduce bundle size from 16MB to 300kB

bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/internal/homie300/Property.java
https://github.com/openhab/openhab-addons/pull/6845 added Dimmer functionallity to the Homie extension, but it was incomplete. As a consequence, now any attribute with the ```%``` unit is linked to a Dimmer item. This PR addresses that.
Fixes #7711
=> [mqtt.homie] Create PercentageValue only if attribute is settable

bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/AbstractHomekitAccessoryImpl.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitTemperatureSensorImpl.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitThermostatImpl.java
Temperature values are often not reported correctly in HomeKit
especially when they are in Fahrenheit this also has the side effect of
having no decimal when using Fahrenheit temperatures.
This intends to fix this and allows for accurate rounding and reporting
of temperatures.
=> [homekit] Use BigDecimal to ensure accurate rounding

bundles/org.openhab.binding.weatherunderground/src/main/java/org/openhab/binding/weatherunderground/internal/handler/WeatherUndergroundHandler.java
=> [weatherunderground] Log URL with masked API key

bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/connector/PowermaxConnector.java, bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/connector/PowermaxSerialConnector.java, bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/connector/PowermaxTcpConnector.java
=> [powermax] Removed dependency on 'org.apache.commons.io.IOUtils'

bundles/org.openhab.binding.lirc/src/main/java/org/openhab/binding/lirc/internal/connector/LIRCConnector.java, bundles/org.openhab.binding.lirc/src/main/java/org/openhab/binding/lirc/internal/connector/LIRCStreamReader.java
=> [lirc] Removed dependency on 'org.apache.commons.io.IOUtils'

bundles/org.openhab.binding.netatmo/src/main/resources/ESH-INF/config/config.xml
=> [netatmo] Mark the client secret configuration setting as a password

bundles/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/PlugwiseCommunicationContext.java
=> [plugwise] Removed dependency on 'org.apache.commons.io.IOUtils'

bundles/org.openhab.binding.keba/src/main/java/org/openhab/binding/keba/internal/handler/KeContactTransceiver.java
On bundle shutdown, I have seen errors like:
```
Exception in thread "openHAB-Keba-Transceiver" java.nio.channels.ClosedSelectorException
at java.base/sun.nio.ch.SelectorImpl.ensureOpen(SelectorImpl.java:75)
at java.base/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:118)
at java.base/sun.nio.ch.SelectorImpl.selectNow(SelectorImpl.java:146)
at org.openhab.binding.keba.internal.handler.KeContactTransceiver.lambda$0(KeContactTransceiver.java:223)
at java.base/java.lang.Thread.run(Thread.java:834)
```
We hence must make sure to only use the selector if it hasn't yet been closed.
=> [keba] Don't use selector if it has been closed

bundles/org.openhab.binding.solaredge/src/main/resources/ESH-INF/thing/generic-channel-types.xml
fixed percent channels. Number:Percent is not valid, Number:Dimensionless must be used.
=> [solaredge] fixed percent channels

bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/handler/EnvisalinkBridgeHandler.java, bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/handler/IT100BridgeHandler.java, bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/handler/TCPServerBridgeHandler.java
Signed-off-by: Laurent Garnier <lg.hc@free.fr
=> [dscalarm] Removed dependency on 'org.apache.commons.io.IOUtils'

bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/tools/DelayedBatchProcessing.java, bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/generic/internal/MqttThingHandlerFactory.java
As expressed in https://github.com/openhab/openhab-addons/pull/5963#issuecomment-523585015, the best way to improve the Homie discovery time was to decrease the timeout values, while also resetting the timer everytime a new value is received. This are the changes done:
- Reschedule the batch processing service when a new value is added. This makes the service more reliable, because the ```run``` function will only be called after the last message is received, and it doesn't matter how long it takes, as long as there is a constant flow of messages.
- Make the ```accept``` function synchronized, so that no new schedules are created when multiple threads are involved.
- Decrease Homie device timeout values to smaller ones. I am 'ok' if you want to increase them, but in my tests they have …
=> [mqtt.homie] Improve Homie discovery time

bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/FullGroup.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/State.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueBridgeHandler.java
=> [hue] Keep compatibility with hue emulation for groups

bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueGroupHandler.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueLightHandler.java, bundles/org.openhab.binding.hue/src/main/resources/ESH-INF/thing/Group.xml
=> [hue] Channel alert added for groups

bundles/org.openhab.binding.alarmdecoder/README.md, bundles/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/AlarmDecoderBindingConstants.java, bundles/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/AlarmDecoderHandlerFactory.java, bundles/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/config/VZoneConfig.java, bundles/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/handler/ADBridgeHandler.java, bundles/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/handler/VZoneHandler.java, bundles/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/protocol/ADCommand.java, bundles/org.openhab.binding.alarmdecoder/src/main/resources/ESH-INF/thing/thing-types.xml
This PR adds support for a new vzone thing for control of AD virtual zones. This allows users to open and close the virtual zones from openHAB.
=> [alarmdecoder] Add vzone thing for virtual zone control

bundles/org.openhab.binding.hue/.classpath, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/StateUpdate.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/discovery/HueLightDiscoveryService.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/GroupStatusListener.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueBridgeHandler.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueClient.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueGroupHandler.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueLightHandler.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueSensorHandler.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/LightStatusListener.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/SensorStatusListener.java, bundles/org.openhab.binding.hue/src/test/java/org/openhab/binding/hue/internal/handler/HueLightHandlerTest.java, itests/org.openhab.binding.hue.tests/src/main/java/org/openhab/binding/hue/internal/HueLightDiscoveryServiceOSGiTest.java
Complete refactoring of state handling inside bridge handler to light and sensor handlers, for alternative to PR #7493 fix for issue #7039 
Open points:
- Think polling jobs can be started at initialize of bridge handler and stopped on dispose, because while refactoring I noticed that the lists of light and senor listeners will be never empty because of registered discovery service
- In light and sensor handler there are several checks for IDs (marked with TODOs) which I think they are obsolete now, because bridge only notifies the single handler now.
- Didn't check the tests right now
=> [hue] Refactored state handling and fix polling after command

CODEOWNERS, bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/handler/AbstractSunSpecHandler.java, bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/parser/AbstractBaseParser.java
This PR fixes some scaling errors in the modbus.sunspec bundle:
- ACC32 fields were mistakenly parsed as unsigned int instead of signed
- default scale value changed to 1
- scaling was missing for 10^1 fields
=> [modbus][sunspec] Fixed type and scale errors on acc32 fields

bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaBaseThingHandler.java
Fixed a bug reported by the community https://community.openhab.org/t/tahoma-binding-compatible-with-oh2/27004/467
In some cases an invalid percent value is received from the Tahoma cloud (greater than 100 in this particular case, which cannot be converted to the PercentType)
=> [somfytahoma] fixed bug when invalid percent value state received

bundles/org.openhab.binding.darksky/src/main/java/org/openhab/binding/darksky/internal/handler/DarkSkyWeatherAndForecastHandler.java
- Added warning if parsing of 'location' parameter throws exception
=> [darksky] Added warning if parsing of 'location' parameter throws exception

bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/config/AstroChannelConfig.java, bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/config/AstroThingConfig.java, bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/handler/AstroThingHandler.java, bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/handler/MoonHandler.java, bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/handler/SunHandler.java, bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/util/DateTimeUtils.java
=> [astro] Add null annotations on main classes

bundles/org.openhab.binding.telegram/README.md, bundles/org.openhab.binding.telegram/src/main/java/org/openhab/binding/telegram/bot/TelegramActions.java, bundles/org.openhab.binding.telegram/src/main/java/org/openhab/binding/telegram/internal/TelegramHandler.java, bundles/org.openhab.binding.telegram/src/main/resources/ESH-INF/thing/thing-types.xml
Adds the ability to use access modifiers on chat is. Use-case: Some chat ids (e.g. children) should receive notifications but should not be allowed to send commands. 
Fully backward compatible, no modifier = sending and receiving
=> [telegram] allow access restrictions on chat ids

bundles/org.openhab.binding.xmppclient/README.md
If Bridge example at top uses (two) ## then split command further down needs to, also.
I was trying to get this working on my own machine but could not until making that small change. So in that sense, it has been (lightly) "tested."
=> [xmppclient] fix typo in doc example

bundles/org.openhab.binding.nest/src/main/java/org/openhab/binding/nest/internal/rest/NestStreamingRequestFilter.java
It is possible the `NestStreamingRequestFilter` adds multiple of the same headers which may result in a memory leak and communication problems.
This is the same fix as added in #7811 for OH3 with CXF.
=> [nest] Fix possible memory leak and communication problems

CODEOWNERS, bundles/org.openhab.io.homekit/README.md, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitChangeListener.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitCommandType.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitDimmerMode.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitOHItemProxy.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitTaggedItem.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/AbstractHomekitAccessoryImpl.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitAccessoryFactory.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitCharacteristicFactory.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitLightbulbImpl.java
Issue:
complex openHAB items like Dimmer and Color have several characteristic. in case of Color all 3 characteristics are updated with one command/state - HSBType. 
in the same time, HomeKit home app sends updates for the characteristics independently of each other, e.g. update for hue, update for saturation and update for brightness. 
as results, characteristics can be get overwritten. 
see #7491 and https://community.openhab.org/t/coloritem-hue-and-saturation-updates/99468/4 
for more details. 
Solution:
as propose in https://community.openhab.org/t/coloritem-hue-and-saturation-updates/99468/4 this PR introduce a proxy for openHAB item, that collects commands/update first and then sends merged update - either wenn all relevant updates received or after 50ms after first update. 
in …
=> [homekit] bugfix 7491 / add support for merging several updates to one command

bundles/org.openhab.binding.netatmo/NOTICE, bundles/org.openhab.binding.netatmo/README.md, bundles/org.openhab.binding.netatmo/pom.xml, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/NetatmoBindingConstants.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/camera/CameraHandler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/AbstractNetatmoThingHandler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/NetatmoDeviceHandler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/NetatmoModuleHandler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/homecoach/NAHealthyHomeCoachHandler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/station/NAMainHandler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/station/NAModule1Handler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/station/NAModule2Handler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/station/NAModule3Handler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/station/NAModule4Handler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/thermostat/NAPlugHandler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/thermostat/NATherm1Handler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/welcome/NAWelcomeCameraHandler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/welcome/NAWelcomeHomeHandler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/welcome/NAWelcomePersonHandler.java, bundles/org.openhab.binding.netatmo/src/main/resources/ESH-INF/thing/welcomehome.xml
This pull-request adds support for the events of the Netatmo Presence camera.
It ...
- uses the updated Netatmo API (to support the sub-event structure which is used by the Presence events)
- delivers all information of the Presence events to the home thing (the message and snapshot is now available/set)
- adds new channels to the home thing to report if a human, animal or vehicle was detected
- simplifies the process of updating the Netatmo API (the retrofit code generation is now embedded within the Maven build)
Please see issue 3059 for more information: #3059
=> [netatmo] Add support for Presence camera events (#3059)

bundles/org.openhab.binding.weatherunderground/src/main/java/org/openhab/binding/weatherunderground/internal/WeatherUndergroundHandlerFactory.java, bundles/org.openhab.binding.weatherunderground/src/main/java/org/openhab/binding/weatherunderground/internal/handler/WeatherUndergroundHandler.java, bundles/org.openhab.binding.weatherunderground/src/main/java/org/openhab/binding/weatherunderground/internal/json/WeatherUndergroundJsonCurrent.java, bundles/org.openhab.binding.weatherunderground/src/main/java/org/openhab/binding/weatherunderground/internal/json/WeatherUndergroundJsonForecastDay.java, bundles/org.openhab.binding.weatherunderground/src/main/java/org/openhab/binding/weatherunderground/internal/json/WeatherUndergroundJsonUtils.java
Also fix few warnings about null check
=> [weatherunderground] Consider TimeZoneProvider to get the timezone

bundles/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/FreeboxHandlerFactory.java, bundles/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/handler/FreeboxThingHandler.java
=> [freebox] TimeZoneProvider passed as parameter to the thing handler

bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoHandler.java
When the wemo changes its service port, it sometimes doesn't close the old one. The wemo binding relied on a simple connect() to figure out if the service was available.  Since the wemo tends to increase the port number upon changing, the first port that the binding would hit was inactive, and this would never correct itself even when the binding was restarted since the problem is on the wemo side (the lower numbered port would still not be valid)
This changes the logic to use a real http request that forces the wemo to respond with something. The bad port will not reply with anything other than just accepting.
Old behavior would look something like the following:
```
07-Jun-2020 21:27:04.210 [TRACE] [.openhab.binding.wemo.internal.handler.WemoHandler] - Ping WeMo device at …
```
=> [wemo] Do http (not port) ping to determine if wemo port is alive

bundles/org.openhab.binding.icalendar/README.md
- Fixed some spellings and linter errors
=> [icalendar] Fixed some spellings and linter errors

bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/AstroHandlerFactory.java, bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/config/AstroThingConfig.java, bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/util/PropertyUtils.java, itests/org.openhab.binding.astro.tests/src/main/java/org/openhab/binding/astro/handler/test/AstroValidConfigurationTest.java, itests/org.openhab.binding.astro.tests/src/main/java/org/openhab/binding/astro/test/AstroStateTest.java
=> [astro] Method renamed (relative to TimeZoneProvider)

bundles/org.openhab.binding.hue/README.md
TemperatureSensorTemperature hue channel definition missing :1 after hue:0302 in the full example.  The item therefore didn't report the temperature and even after fixing it still did not work until I renamed the item.
=> [hue] Fix documentation - TemperatureSensorTemperature example item

bundles/org.openhab.binding.hue/README.md
Siogned-off-by: Laurent Garnier <lg.hc@free.fr>
=> [hue] Fix description of setting sensorPollingInterval

bundles/org.openhab.binding.netatmo/.classpath, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/ChannelTypeUtils.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/NetatmoHandlerFactory.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/RefreshStrategy.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/camera/CameraHandler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/AbstractNetatmoThingHandler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/NetatmoDeviceHandler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/NetatmoModuleHandler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/homecoach/NAHealthyHomeCoachHandler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/station/NAMainHandler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/station/NAModule1Handler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/station/NAModule2Handler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/station/NAModule3Handler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/station/NAModule4Handler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/thermostat/NAPlugHandler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/thermostat/NATherm1Handler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/welcome/NAWelcomeCameraHandler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/welcome/NAWelcomeHomeHandler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/welcome/NAWelcomePersonHandler.java
=> [netatmo] Consider TimeZoneProvider

bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/client/RpcClient.java, bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/client/XmlRpcClient.java
The CCU gets unresponsive if several HmIP devices are installed and
always "non-blocking" requests are used. By reducing the use to what is
absolutely necessary, the problem can be avoided.
Fixes #7762
=> [homematic] Solves stability issues with HmIP devices

bundles/org.openhab.binding.samsungtv/README.md
Added another supported Samsung TV to README.md.
Tested on https://www.amazon.de/gp/product/B07PMDF69G/
=> Added supported SamsungTV UE58RU7179UXZG

bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/WebSocketConnection.java
Fixes #7910 
This fixes the memory/thread leak resulting from incorrect shutdown handling. Because of the high re-connect rate of 60s this resulted in an OOM after some time. 
The requests failed because some headers were added twice which caused the server to discard the message.
=> [amazonechocontrol] fix memory/thread leak and failing connection

bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitOHItemProxy.java
with PR https://github.com/openhab/openhab-addons/pull/7825 a new logic for dimmer handling was introduced. 
the new logic suppress either ON state or brightness update depending on the dimmer state and selected dimmer mode. e.g. do not sends "brightness=100%" update on "ON" event. this helps to handle different dimmers behaviours, e.g. soft launch
however, it is not possible anymore to increase brightness to 100%. see https://community.openhab.org/t/homekit-homekit-sending-on-and-100-command/99485/28?u=yfre
This PR adapt logic as follow:
the rule 
`IF  "target state=ON" AND "target brightness=100" THEN do not update brightness
`
is changed to
`IF  "target state=ON" AND "target brightness=100" AND "current state = OFF" THEN do not update brightness
`
this means, if dimmer is already ON …
=> [homekit] fix 100% brightness for dimmer

bundles/org.openhab.binding.plclogo/README.md
Missing some " at the end of items' line
=> [plclogo] Update README.md

bundles/org.openhab.binding.robonect/README.md, bundles/org.openhab.binding.robonect/src/main/java/org/openhab/binding/robonect/internal/RobonectHandlerFactory.java, bundles/org.openhab.binding.robonect/src/main/java/org/openhab/binding/robonect/internal/config/RobonectConfig.java, bundles/org.openhab.binding.robonect/src/main/java/org/openhab/binding/robonect/internal/handler/RobonectHandler.java, bundles/org.openhab.binding.robonect/src/main/resources/ESH-INF/thing/thing-types.xml, bundles/org.openhab.binding.robonect/src/test/java/org/openhab/binding/robonect/internal/handler/RobonectHandlerTest.java
Use the timezone that has been configured by the user in openHAB settings
for all robonect messages instead of UTC.
Fixes #7848
=> [Robonect] Use global openHAB timezone for DateTime objects

bundles/org.openhab.binding.squeezebox/README.md
As I struggled to sort out exactly how to set up the .items file for the item type 'image' and define the album art channel I though the documentation could be clarified with an example or 3.").
ADD SOME EXAMPLES TO THE .ITEMS FILE
Improvement to documentation
https://community.openhab.org/t/squeezebox-display-coverart/12072/19?u=leec77
=> [squeezebox] Add some examples to the .items file example

bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/discovery/SamsungTvDiscoveryParticipant.java, bundles/org.openhab.binding.samsungtv/src/main/resources/ESH-INF/thing/thing-types.xml
Contributes to #6317 and should hide a result if there is already a thing
defined which does not have the same ThingUID but points to the same TV.
=> [samsungtv] Make use of representation property in discovery

bundles/org.openhab.binding.deconz/README.md, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/BindingConstants.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/Util.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/discovery/ThingDiscoveryService.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/LightThingHandler.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/SensorThingHandler.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/types/LightType.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/types/ThermostatModeGsonTypeAdapter.java, bundles/org.openhab.binding.deconz/src/main/resources/ESH-INF/thing/light-thing-types.xml, bundles/org.openhab.binding.deconz/src/main/resources/ESH-INF/thing/sensor-thing-types.xml, bundles/org.openhab.binding.deconz/src/test/java/org/openhab/binding/deconz/LightsTest.java, bundles/org.openhab.binding.deconz/src/test/resources/org/openhab/binding/deconz/colortemperature.json
Add scaling of upper\lower level for ct values
Add IKEA CWS bulb support
Signed-off-by: Benjamin Hahn <benjamin@pikas-page.de>
=> [deconz] Adjust color-temperature handling, Extend bulb support

bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/GroupMessageStateMachine.java, bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/InsteonDevice.java, bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/MessageHandler.java
An insteon device has multiple features associated with it and each one potentially had a group state machine. The state machine applies to the device not the feature. This simplifies the design by associating the state machine to the device instead of including on with each feature.
=> [insteon] keep track of group state at the device level

bundles/org.openhab.binding.lametrictime/src/main/java/org/openhab/binding/lametrictime/internal/handler/ClockAppHandler.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/grxprg/PrgBridgeHandler.java, bundles/org.openhab.binding.robonect/src/test/java/org/openhab/binding/robonect/internal/handler/RobonectHandlerTest.java
There were still some usages of `getCalendar()` causing the [add-ons port to fail](https://ci.openhab.org/job/openHAB-Addons-port/165/console):
`[ERROR] /home/jenkins/jenkins-agent1/workspace/openHAB-Addons-port/bundles/org.openhab.binding.lametrictime/src/main/java/org/openhab/binding/lametrictime/internal/handler/ClockAppHandler.java:[55,1984] The method getCalendar() is undefined for the type DateTimeType`
Related to:
* https://github.com/openhab/openhab-core/pull/1500
* https://github.com/openhab/openhab-addons/pull/7918
=> Fix DateTimeType deprecations

bundles/org.openhab.binding.darksky/README.md
See also: https://www.openhab.org/addons/bindings/darksky/
Sorry, for the DCO, yes I agree to the DCO
=> [dark-sky] Fixed rendering of table in readme

bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/Homekit.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/Debouncer.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitAuthInfoImpl.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitChangeListener.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitCommandExtension.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitImpl.java
there are regular reports about "lost mac address" issue. 
https://community.openhab.org/t/homekit-could-not-find-existing-mac/100845/8
https://community.openhab.org/t/need-to-reset-homekit-pairing-at-every-launch/13542/32
sometimes the mac address disappears from homekit.json and one need to repair home clients with openhab. 
this issue is difficult to reproduce. there is no place in the source code where mac address gets removed from storage. there are only 2 places related to mac address: one is writing new mac to storage, another one is reading the mac from storage. 
so, must be something like race condition and inconsistent state of the storage object
this PR reduces number of class which have references to storage object. it also stops a runnable that could potential try to update …
=> [homekit] fix corrupt storage 

bundles/org.openhab.binding.innogysmarthome/src/main/java/org/openhab/binding/innogysmarthome/internal/client/InnogyClient.java, bundles/org.openhab.binding.innogysmarthome/src/main/java/org/openhab/binding/innogysmarthome/internal/client/entity/message/Message.java, bundles/org.openhab.binding.innogysmarthome/src/main/java/org/openhab/binding/innogysmarthome/internal/handler/InnogyBridgeHandler.java
This PR fixes low battery messages.
Closes: #6932 
Root cause: Json field "DeviceLinkList" of a "Message" is renamed (by Innogy) to "Devices".
=> [innogysmarthome] Fix Battery Warnings (Bug 

bundles/org.openhab.binding.sleepiq/src/3rdparty/test/org/openhab/binding/sleepiq/api/test/AbstractTest.java
=> [sleepiq] Fix the failing tests on Windows

bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitAuthInfoImpl.java
there is a critical bug in the last release. if homekit.json is empty, e.g. new installation, then it will not be able to initialise property due this
`salt = new BigInteger(storage.get("salt"));`
if salt is empty then it throw an exception and stop initialisation. 
reported here
https://community.openhab.org/t/homekit-console-commands-not-working-in-2-5-6/101187/12
=> [homekit] fix storage initialisation / critical

bundles/org.openhab.binding.network/src/test/java/org/openhab/binding/network/internal/toberemoved/cache/ExpiringCacheAsyncTest.java
=> [network] Fix the failing test

bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/handler/MaxCubeBridgeHandler.java
This prevents excessive updates for temperature changes and restores the
old behaviour
Fixes issue in:
https://community.openhab.org/t/basic-ui-setpoint-issue/101167
=> [max] increase delay

bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/SensorThingHandler.java
Fixes #7920 
The battery channel was accidentally removed during the refactoring in #7828.
=> [deconz] re-add battery channel

bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitChangeListener.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitTaggedItem.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitAccessoryFactory.java
as discussed here 
https://community.openhab.org/t/problems-with-homekit-switchable-feature-on-switch-groups/100702
and here
https://community.openhab.org/t/homekit-could-not-find-existing-mac/100845/26
current HomeKit binding does not support groups with a base item, eg.
```
Group:Switch:OR(ON,OFF) gLights "ALL Lights [%s]"	{homekit="Lighting"}
Switch Light_1 "Light 1 [%s]"  (gLights,) {homekit="Lighting"}
Switch Light_2 "Light 2 [%s]"  (gLights,) {homekit="Lighting"}
```
it would create only one accessory - for the group but not for light_1 and light_2. the logic is following: if an item is part of bigger group with homekit tag, then the item is a characteristic of this homekit accessory/group. 
this PR fix this issue by ignoring groups with base item.
Signed-off-by: Eugen Freiter …
=> [homekit] add support for group switches

bundles/org.openhab.binding.astro/README.md
Noticed the first two bullets under "The Astro binding is used for calculating" were not rendering properly. Added crlf.
Doc fix - markdown renders properly.
=> [astro] - Fix tiny markdown syntax with bullets at top

bundles/org.openhab.binding.tplinksmarthome/README.md, bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/TPLinkSmartHomeThingType.java, bundles/org.openhab.binding.tplinksmarthome/src/main/resources/ESH-INF/thing/KP105.xml
This adds support for the [KP105 slim smart plug](https://www.tp-link.com/uk/home-networking/smart-plug/kp105/#overview) (tested with the UK edition v1.0.5 Build 191209 Rel.094735).
=> [tplinksmarthome] Added support for KP105

bundles/org.openhab.binding.kodi/pom.xml, bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/protocol/KodiClientSocket.java
=> [kodi] fix possible resource leak

bundles/org.openhab.binding.innogysmarthome/README.md, bundles/org.openhab.binding.innogysmarthome/src/main/java/org/openhab/binding/innogysmarthome/internal/client/entity/message/Message.java, bundles/org.openhab.binding.innogysmarthome/src/main/resources/ESH-INF/i18n/innogysmarthome_de_DE.properties, bundles/org.openhab.binding.innogysmarthome/src/main/resources/ESH-INF/thing/bridge.xml
Since the last backend-update the auth-links of Innogy are changed.
=> [innogysmarthome] Updated Auth-links in docs

bundles/org.openhab.binding.lcn/README.md, bundles/org.openhab.binding.lcn/pom.xml, bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/LcnModuleHandler.java, bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/subhandler/AbstractLcnModuleSubHandler.java, bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/subhandler/ILcnModuleSubHandler.java, bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/subhandler/LcnModuleRollershutterOutputSubHandler.java, bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/subhandler/LcnModuleRollershutterRelaySubHandler.java, bundles/org.openhab.binding.lcn/src/main/resources/ESH-INF/thing/thing-types.xml, bundles/org.openhab.binding.lcn/src/test/java/org/openhab/binding/lcn/internal/subhandler/LcnModuleRollershutterOutputSubHandlerTest.java, bundles/org.openhab.binding.lcn/src/test/java/org/openhab/binding/lcn/internal/subhandler/LcnModuleRollershutterRelaySubHandlerTest.java
=> [lcn] Add ability to invert Rollershutter Up/Down

bundles/org.openhab.binding.opensprinkler/README.md
*Fix channel link in example items*
The example items in the README refers to `station` where it should be `device`.
=> [opensprinkler] Fix channel names in README example items.

bundles/org.openhab.binding.deconz/.classpath, bundles/org.openhab.binding.deconz/README.md, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/BindingConstants.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/dto/DeconzBaseMessage.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/DeconzBaseThingHandler.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/SensorBaseThingHandler.java, bundles/org.openhab.binding.deconz/src/main/resources/ESH-INF/thing/sensor-thing-types.xml
The current binding provides support for "last_update" channel but not "last_seen". Last_update is updated when a device changes his state (battery status, or in my case of a smoke detector - when then is fire!).
Because I want to monitor if my smoke detectors are still alive, I need to check the "last_seen" value.
As last_seen is not in the WebSocket messages, it needs a refresh of the sensor:
=> [Deconz] add support for "last_seen" channel

bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/KodiHandlerFactory.java
=> [kodi] Thing handler factory with null annotations and constructor injection

bundles/org.openhab.binding.mqtt/README.md
Added section with a small info in README.md for help users not running into "install-errors" when still using the old but popular mqtt1-binding.
=> [mqtt] Installation hint for mqtt1-users in README.md

bundles/org.openhab.binding.lutron/src/main/resources/ESH-INF/thing/thing-types.xml
Small update that adds representation-property tag to thing definitions. The appropriate representation properties were already being set in the discovery services, but were not defined in thing-types.xml.
=> [lutron] Fix auto-ignore for discovered devices

bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueBridgeHandler.java
=> [hue] Avoid updating the inbox at each poll

bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/discovery/OpenWeatherMapDiscoveryService.java
=> [openweathermap] Do not update the discovery inbox while the location is unchanged

bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/config/HueBridgeConfig.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueBridgeHandler.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueGroupHandler.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueLightHandler.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueSensorHandler.java
=> [hue] Reduce the number of warnings

bundles/org.openhab.binding.deconz/pom.xml, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/DeconzHandlerFactory.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/StateDescriptionProvider.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/Util.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/discovery/ThingDiscoveryService.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/DeconzBaseThingHandler.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/LightThingHandler.java, bundles/org.openhab.binding.deconz/src/test/java/org/openhab/binding/deconz/LightsTest.java
This fixes the wrong ctmin/ctmax values for manually added things (both managed and unmanaged) and provides proper state descriptions for the color temperature.
=> [deconz] Add dynamic state descriptions and fix property updates

bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueBridgeHandler.java
=> [hue] Reduce log level in refresh jobs

bundles/org.openhab.binding.innogysmarthome/src/main/java/org/openhab/binding/innogysmarthome/internal/InnogyWebSocket.java
=> [innogysmarthome] Fix possible resource leak

bundles/org.openhab.binding.squeezebox/README.md, bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/SqueezeBoxBindingConstants.java, bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/SqueezeBoxHandlerFactory.java, bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/SqueezeBoxStateDescriptionOptionsProvider.java, bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/discovery/SqueezeBoxPlayerDiscoveryParticipant.java, bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/dto/ButtonDTO.java, bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/dto/ButtonDTODeserializer.java, bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/dto/ButtonsDTO.java, bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/dto/RemoteMetaDTO.java, bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/dto/StatusResponseDTO.java, bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/dto/StatusResultDTO.java, bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxNotificationListener.java, bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxPlayerEventListener.java, bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxPlayerHandler.java, bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxServerHandler.java, bundles/org.openhab.binding.squeezebox/src/main/resources/ESH-INF/thing/thing-types.xml
Some streaming services, such as Pandora and Slacker, support "liking" or "unliking" the currently playing song. *Liking* a song causes the streaming service to play more songs like the currently playing song. *Unliking* the song skips the currently playing song, and won't play it again. As each streaming service has a different way to accomplish this, the LMS jsonrpc service supplies the specific like/unlike commands based on the service that's streaming the song. It does this by overriding the functionality of the `repeat` and `shuffle` buttons
This change adds two new channels to the player thing - `like` and `unlike`. If a streaming service doesn't support the like/unlike functionality, sending a command to the `like` or `unlike` channel does nothing.
Unfortunately, the current …
=> [squeezebox] Implement like/unlike for remote streaming services

bundles/org.openhab.binding.amazondashbutton/src/main/java/org/openhab/binding/amazondashbutton/internal/config/AmazonDashButtonConfigOptionProvider.java, bundles/org.openhab.binding.gpstracker/src/main/java/org/openhab/binding/gpstracker/internal/GPSTrackerHandlerFactory.java, bundles/org.openhab.binding.gpstracker/src/main/java/org/openhab/binding/gpstracker/internal/provider/TrackerRegistry.java, bundles/org.openhab.binding.smartmeter/src/main/java/org/openhab/binding/smartmeter/internal/SmartMeterConfigProvider.java
- Remove deprecated method of `ConfigOptionProvider` - preparations
Related to https://github.com/openhab/openhab-core/pull/1541
=> Remove deprecated method of 'ConfigOptionProvider' - preparations

bundles/org.openhab.binding.netatmo/README.md, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/NetatmoHandlerFactory.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/camera/CameraAddress.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/camera/CameraHandler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/discovery/NetatmoModuleDiscoveryService.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/AbstractNetatmoThingHandler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/NetatmoBridgeHandler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/NetatmoDeviceHandler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/NetatmoModuleHandler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/homecoach/NAHealthyHomeCoachHandler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/presence/NAPresenceCameraHandler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/station/NAMainHandler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/station/NAModule1Handler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/station/NAModule2Handler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/station/NAModule3Handler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/station/NAModule4Handler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/thermostat/NAPlugHandler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/thermostat/NATherm1Handler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/welcome/NAWelcomeCameraHandler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/welcome/NAWelcomeHomeHandler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/welcome/NAWelcomePersonHandler.java, bundles/org.openhab.binding.netatmo/src/main/resources/ESH-INF/binding/binding.xml, bundles/org.openhab.binding.netatmo/src/test/java/org/openhab/binding/netatmo/internal/presence/NAPresenceCameraHandlerTest.java, bundles/org.openhab.binding.netatmo/src/test/java/org/openhab/binding/netatmo/internal/welcome/NAWelcomeHomeHandlerTest.java
=> [netatmo] Null annotations Part 3 of 3

bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/grxprg/GrafikEyeHandler.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/grxprg/PrgBridgeHandler.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/grxprg/PrgProtocolHandler.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/grxprg/SocketSession.java
This commit consists entirely of changes to field names made in order to eliminate warnings from the code analysis tool. Mainly it involved removing leading underscores and de-conflicting the results. It's been an on-going project to try to eliminate all SCA warnings, although there is still a long way to go when it comes to null annotations.
@tmrobert8 - It looks like you are the original contributor of the modified files (for GRX-PRG), so I'd appreciate it if you could review and/or test it out. I don't have the hardware to test it myself.
=> [lutron] Code clean-up to eliminate SCA warnings

bundles/org.openhab.binding.adorne/README.md
Legrand website was just used as name, however in Markup syntax. This results in an invalid link:
```
https://www.openhab.org/addons/bindings/adorne/legrand.com
```
=> [adorne] Add https for website (otherwise the link is not recognized)

bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/discovery/AmazonEchoDiscovery.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/discovery/SmartHomeDevicesDiscovery.java
See https://github.com/openhab/openhab-addons/pull/7969#issuecomment-655912453
=> [amazonechocontrol] remove deprecated discovery interfaces

bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/RefreshStrategy.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/NetatmoDeviceHandler.java
=> [netatmo] Avoid multiple device data reading at startup

bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/api/MelCloudConnection.java
We weren't listing devices that where added to an Area which was not added to a Floor.
Now it lists all devices.
Signed-off-by: Wietse van Buitenen <thewiep@gmail.com>
=> [melcloud] List devices on all levels

bundles/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/Util.java
Adjust log level to coding guidelines
=> [onewire] adjust loglevel

bundles/org.openhab.binding.valloxmv/pom.xml, bundles/org.openhab.binding.valloxmv/src/main/java/org/openhab/binding/valloxmv/internal/ValloxMVWebSocket.java
Related to #8027 
This is an interesting one. It closes the websocket immediately after each request.
=> [valloxmv] fix possible resource leak

bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/action/IVolvoOnCallActions.java, bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/action/VolvoOnCallActions.java
=> [VolvoOnCall] Reliable implementation of thing actions

bundles/org.openhab.binding.shelly/README.md
corrected the Product name in the docu, perhaps we should also rename the page name itself...
=> it is called "Shelly 3EM" not "Shelly EM3"

bundles/org.openhab.transform.scale/conf/transform/scale/humidex.scale, bundles/org.openhab.transform.scale/src/main/java/org/openhab/transform/scale/internal/ScaleTransformationService.java, bundles/org.openhab.transform.scale/src/test/java/org/openhab/transform/scale/internal/ScaleTransformServiceTest.java
Fix #8011 and #8123  
Signed-off-by: Johannes DerOetzi Ott <info@johannes-ott.net>
=> [scale] NPE in ScaleTransformationService

bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/LGWebOSHandlerFactory.java, bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/handler/LGWebOSHandler.java, bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/handler/LGWebOSTVSocket.java
=> [lgwebos] Improved WebSocket reconnect/disconnect

bundles/org.openhab.binding.hyperion/README.md
Currently the ruleset example of the hyperion add-on README contains only two of the effects that are existing by default. Unfortunately it is a real pain, to collect the exact names of all the items, so i guess it would be good, to have it in the readme.
The list is based upon the effects of hyperionV1: https://github.com/hyperion-project/hyperion/tree/master/effects
The values itself could be found in the json files in the `name` property.
As hyperion.ng is currently more or less in alpha state, i'm not sure whether new effects of this version should already be considered...
Maybe it would be useful as well, to add a more detailed description about the effects itself?
=> [hyperion] add hyperion effects to readme

bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/action/IMQTTActions.java, bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/action/MQTTActions.java
=> [MQTT] Workaround for thing actions bug

bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/Connection.java
Fixed: Work around Amazon Security changes and make proxy working again
=> [amazonechocontrol] LoginFix - Enter a valid mail or password

bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/NetatmoBridgeHandler.java
=> [netatmo] Make safe the execution of the refresh token job

bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/WebSocketConnection.java
=> [amazonechocontrol] Partial revert of PR 7919

bundles/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/internal/SenseBoxAPIConnection.java
- Fixed potential NPE introduced in PR #8171
=> [sensebox] Fixed potential NPE introduced in PR 8171

bundles/org.openhab.binding.mqtt/README.md, bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/discovery/TopicSubscribe.java, bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/handler/AbstractBrokerHandler.java, bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/handler/BrokerHandler.java, bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/handler/BrokerHandlerConfig.java, bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/handler/SystemBrokerHandler.java, bundles/org.openhab.binding.mqtt/src/main/resources/ESH-INF/thing/thing-types.xml, bundles/org.openhab.binding.mqtt/src/test/java/org/openhab/binding/mqtt/internal/MQTTTopicDiscoveryServiceTest.java
Fixes #8056 
This adds a parameter to the broker to disable discovery. By default this is set to false (so discovery is enabled), which is the same behaviour like before.
=> [mqtt] allow disabling discovery

bundles/org.openhab.io.transport.modbus/src/main/java/org/openhab/io/transport/modbus/internal/pooling/ModbusSlaveConnectionFactoryImpl.java
Fixes #8205
When connection is invalidated (e.g. after I/O error), we have apache pool creating a new (unconnected) connection object (if there are others waiting for a connection), and instantly passivates it. In this corner case we will have null `endpoint` in PooledObject wrapper, resulting in NPE.
=> [modbus] Fix for NullPointerException

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoVacuumHandler.java
Delay sending charge command to avoid action locked response.
`2020-07-23 11:42:32.531 [DEBUG] [internal.handler.MiIoAbstractHandler] - Received response for 070A579C type: CHARGE, result: {}, fullresponse: {“error”:{“code”:-10003,“message”:“action locked”},“id”:1771}`
closes #7832
See also see also https://community.openhab.org/t/xiaomi-robot-vacuum-binding/31317/1612
=> [miio] delayed sending of charge command

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/discovery/MiIoDiscovery.java, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/transport/MiIoAsyncCommunication.java
[miio] fix port leak
Fix Max Datagram connections reached issue
Possibly also addressing openhab#8091 as exception during closing would prevent thread closing
=> [miio] fix port leak - max datagram sockets reached

bundles/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/handler/KeypadHandler.java, bundles/org.openhab.binding.alarmdecoder/src/main/resources/ESH-INF/thing/thing-types.xml
An additional keypad message needs to be checked for the sendStar option to work in some cases.
Default the keypad thing mask to 0 and clarify what it actually is.
Signed-off-by: bill <git@billforsyth.net>
=> [alarmdecoder] additional message parsing for zone faults, and default the keypad mask

bundles/org.openhab.binding.phc/src/main/resources/ESH-INF/thing/channel-types.xml, bundles/org.openhab.binding.phc/src/main/resources/ESH-INF/thing/thing-types.xml
Fix a bug in the thing type definition, that has crept in #6447.
While I removed the channel groups for JRM and DIM thing types I forgot that goup id is used in the Binding.
Aditionally I didn't change the channel ids so we have duplicate ids in the JRM type definition.
So we have to use the channel-groups for all thing-types again.
The bug was found in this thread: https://community.openhab.org/t/switch-from-peha-phc-to-new-automation-with-openhab2/61154/36 
Signed-off-by: Jonas Hohaus <jh@gnlpf.net>
=> [phc] Fix duplicate id in JRM channel definition

bundles/org.openhab.binding.lgwebos/README.md
Simple fix in Readme for previously removed action method getApplications.
=> [lgwebos] Updated Readme for removed action getApplications.

bundles/org.openhab.binding.amazonechocontrol/README.md, bundles/org.openhab.binding.amazonechocontrol/pom.xml, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/AccountServlet.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/AmazonEchoControlHandlerFactory.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/Connection.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/ConsoleCommandExtension.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/discovery/AmazonEchoDiscovery.java
An issue has been found where the login to the amazon account fails. Device-ids generated by bindings-versions before #8139 may have problems to login if they do not conform to the specification. The binding was not properly detecting this and further logins re-used the device-id which failed again. 
This PR adds a check for the correct format of the device-id and also adds a console command to fore renewal of all connection settings.
=> [amazonechocontrol] improve login handling

bundles/org.openhab.binding.lutron/README.md, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/LutronBindingConstants.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/LutronHandlerFactory.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/discovery/LutronDeviceDiscoveryService.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/CcoHandler.java, bundles/org.openhab.binding.lutron/src/main/resources/ESH-INF/thing/thing-types.xml
This commit deprecates the ccopulsed and ccomaintained things. Users should use the cco thing instead. There is no loss or change in functionality.
* Discovery will now create cco instead of ccopulsed and ccomaintained things.
* The ccopulsed and ccomaintained thing types are now defined with listed=false.
* The thing descriptions are marked with "Deprecated".
* Docs have been updates with the change.
Looking back, I should not have created separate cco, ccopulsed, and ccomaintained things. I did it based on some mistaken assumptions about discovery. So now is as good a time as any to clean this up. The deprecated things will continue to work for now, but I would like to remove them in or after the OH 3.0 release.
=> [lutron] Deprecate ccopulsed and ccomaintained things

bundles/org.openhab.binding.lutron/README.md, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/LutronBindingConstants.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/LutronHandlerFactory.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/config/SysvarConfig.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/IPBridgeHandler.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/LutronHandler.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/SysvarHandler.java, bundles/org.openhab.binding.lutron/src/main/resources/ESH-INF/thing/thing-types.xml
This PR adds support for HomeWorks QS system state variables. 
From the updated README file:
HomeWorks QS systems allow for conditional programming logic based on state variables. The **sysvar** thing allows state variable values to be read and set from openHAB. This makes sophisticated integration schemes possible.
Each **sysvar** thing represents one system state variable. It has a single channel *varstate* with type Number and category Number. Automatic discovery of state variables is not yet supported. They must be manually configured.
Signed-off-by: Bob Adair <bob.github@att.net>
=> [lutron] Add system state variable support for HomeWorks QS

bundles/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/handler/AbstractModbusEndpointThingHandler.java, bundles/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/handler/ModbusSerialThingHandler.java, bundles/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/handler/ModbusTcpThingHandler.java, itests/org.openhab.binding.modbus.tests/src/main/java/org/openhab/binding/modbus/tests/ModbusDataHandlerTest.java, itests/org.openhab.binding.modbus.tests/src/main/java/org/openhab/binding/modbus/tests/ModbusTcpThingHandlerTest.java
Implementation was raising `IllegalStateException` while `interface` was throwing `EndpointNotInitializedException`.
This is issue in theory -- all consumers check corresponding thing status first (e.g. in initialize), and only call the method, thus the endpoint is always initialized.
No changes to interface -> no changes to bindings relying on the API.
=> [modbus] Correct exception type in implementation.

bundles/org.openhab.binding.lutron/README.md, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/action/DimmerActions.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/action/IDimmerActions.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/DimmerHandler.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/protocol/LutronDuration.java
This update adds a setLevel(level, fadeTime, delayTime) thing action to the dimmer thing. This allows a level command to be sent with associated fade and delay times.
As discussed previously in openhab/openhab-core#1298, I think it is unfortunate that there isn't a more standard way to add this functionality. Even some attempt at defining a standard set of thing actions might be useful here, so that common actions across different things could be somewhat consistent. In the absence of that, I just picked an action name that I thought logical.
This update also includes a new LutronDuration class for time durations, which will eventually be useful for other coming improvements to the binding.
Signed-off-by: Bob Adair <bob.github@att.net>
Also-by: Austin Guiswite
=> [lutron] Add setLevel thing action to dimmer

bundles/org.openhab.binding.telegram/README.md, bundles/org.openhab.binding.telegram/pom.xml, bundles/org.openhab.binding.telegram/src/main/java/org/openhab/binding/telegram/internal/TelegramBindingConstants.java, bundles/org.openhab.binding.telegram/src/main/java/org/openhab/binding/telegram/internal/TelegramConfiguration.java, bundles/org.openhab.binding.telegram/src/main/java/org/openhab/binding/telegram/internal/TelegramHandler.java, bundles/org.openhab.binding.telegram/src/main/resources/ESH-INF/thing/thing-types.xml
This PL closes #7043
I added a new parameter for long polling. There is a new parameter with default value 25 seconds. The Telegram WebApp uses 25 seconds. Maximal value is 50 seconds. After this time the telegram api interups the connection.
Additional i fixed some warnings.
=> [telegram] Added support for long polling

bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/generic/internal/MqttBindingConstants.java, bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/generic/internal/MqttThingHandlerFactory.java, bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/internal/discovery/Homie300Discovery.java, bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/internal/handler/HomieThingHandler.java, bundles/org.openhab.binding.mqtt.homie/src/test/java/org/openhab/binding/mqtt/homie/internal/handler/HomieThingHandlerTests.java
Context:
Although we thought that https://github.com/openhab/openhab-addons/pull/7723 would solve #7252, the truth is that after the release of openHAB 2.5.6, new users started complaining that their Homie devices were not behaving correctly ($name message does not arrive). Taking into account that there are some problems with subscriptions and retained messages (in some circumstances the binding does not receive all the messages it should), it has been decided to remove the subscription to the "homie/xxx/$name" topic in the Homie300Discovery class. The only problem with this solution is that the name of the thing will be the same as the device id of Homie, but I think that this small loss of functionality will compensate for the advantage of fixing the bug. Also, the transport.io.mqtt …
=> [mqtt][homie] Delete '$name' subscription in discovery service

bundles/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/controls/LxControlJalousie.java, bundles/org.openhab.binding.loxone/src/test/java/org/openhab/binding/loxone/internal/controls/LxControlJalousieTest.java
This PR fixes the bug report [#8157](https://github.com/openhab/openhab-addons/issues/8157)
=> [loxone] fix rollershutter behaviour with alexa integration

bundles/org.openhab.binding.lcn/README.md, bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/LcnModuleDiscoveryService.java, bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/LcnModuleHandler.java, bundles/org.openhab.binding.lcn/src/main/resources/ESH-INF/thing/thing-types.xml
When using auto discovery modules are now identified by a combination of segment id and module id in the format `S<segmentID>M<moduleID>` instead by serial number. Serial number is used as representation property (e.g. to identify identical modules when using auto-ignore option in PaperUI). Closes #8097.
=> [lcn] Make auto discovery use segment id and module id for ThingID

bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/RFXComBindingConstants.java, bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/connector/RFXComJD2XXConnector.java, bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/connector/RFXComSerialConnector.java, bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/connector/RFXComStreamReader.java, bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/connector/RFXComTcpConnector.java, bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/handler/RFXComBridgeHandler.java
=> [rfxcom] Thread naming

bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/discovery/LutronDeviceDiscoveryService.java
Fixes a potential error in the XML discovery service if the bridge is not initialized.
=> [lutron] Fix potential NPE if bridge not initialized

bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/RotelBindingConstants.java, bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/communication/RotelReaderThread.java, bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/handler/RotelHandler.java
=> [rotel] Thread name format updated

bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/connector/PowermaxConnector.java, bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/connector/PowermaxReaderThread.java, bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/connector/PowermaxSerialConnector.java, bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/connector/PowermaxTcpConnector.java, bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/handler/PowermaxBridgeHandler.java, bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/message/PowermaxCommManager.java
=> [powermax] Thread naming

bundles/org.openhab.binding.lametrictime/pom.xml
Fixes https://ci.openhab.org/job/openHAB-Addons-port/209/
=> [lametrictime] ignore javax.activation as it is not required

bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/AbstractHomematicGateway.java, bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/client/XmlRpcClient.java, bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/message/BinRpcMessage.java, bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/parser/GetParamsetParser.java, bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/converter/type/PercentTypeConverter.java, bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/handler/HomematicBridgeHandler.java, bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/misc/HomematicConstants.java, bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/type/MetadataUtils.java
This PR contains solutions for a number of issues. Most of them have been successfully tested by several users.
=> [homematic] Better support for rollershutters + several smaller fixes

bundles/org.openhab.binding.lutron/README.md, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/config/DimmerConfig.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/DimmerHandler.java, bundles/org.openhab.binding.lutron/src/main/resources/ESH-INF/thing/thing-types.xml
This update adds two new configuration parameters to the dimmer thing:
* The `onLevel` parameter specifies the level to which the dimmer will go when sent an ON command. It defaults to 100.
* The `onToLast` parameter is a boolean that defaults to false. If set to "true", the dimmer will go to its last non-zero level when sent an ON command. If the last non-zero level cannot be determined, the value of `onLevel` will be used instead.
If these parameters are left at their defaults, there will be no change in behavior from the current dimmer handler.
=> [lutron] Dimmer enhancements

bundles/org.openhab.io.transport.modbus/src/main/java/org/openhab/io/transport/modbus/ModbusCommunicationInterface.java, bundles/org.openhab.io.transport.modbus/src/main/java/org/openhab/io/transport/modbus/internal/ModbusManagerImpl.java
If communication interface is closed, you cannot naturally interact with the device anymore. `IllegalArgumentException` is raised with all methods that would need to interact with the device.
In this commit, `close` and `unregisterRegularPoll` methods are not raising the exception anymore since they are essentially no-ops with closed communication interface. After all, close automatically unregisters all registered regular polls. Thus, it should be considered harmless to call these methods again on a closed instance, making them mostly idempotent.
This change was motivated by seeing the `IllegalStateException` in the wild (when disposing modbus `poller` thing), possibly triggered by certain dispose/initialize/reload of things: https://community.openhab.org/t/snip/102809/43
=> [modbus] Avoid unnecessary IllegalArgumentException on dispose

bundles/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/handler/ModbusDataThingHandler.java, itests/org.openhab.binding.modbus.tests/src/main/java/org/openhab/binding/modbus/tests/ModbusDataHandlerTest.java
=> [modbus] Off-by-one fixes for data thing read index validation

bundles/org.openhab.binding.rfxcom/README.md, bundles/org.openhab.binding.rfxcom/src/main/resources/ESH-INF/thing/blinds1.xml
Right - apologies for all the confusion on the last PR. This is a clean branch with a clean update.
This PR adds support for T11 blinds into the Blind1 actuator for the RFXCOM Binding. I've been using this built on my local instance for about 2 months on new Louvolite blinds which are reporting as ASP in the RFXMGR.
Signed-off-by: Michael Hazelden <michael@hazelden.me>
=> [RFXCOM] Adding support for T11 Blinds

bundles/org.openhab.binding.insteon/README.md, bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/InsteonBinding.java, bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/config/InsteonDeviceConfiguration.java, bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/InsteonDevice.java, bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/MessageHandler.java, bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/handler/InsteonDeviceHandler.java, bundles/org.openhab.binding.insteon/src/main/resources/ESH-INF/thing/thing-types.xml
Initial support includes broadcast channels for PLM and disabling heartbeat for motion sensor II
=> [insteon] Added the ability to configure devices from the UI

bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/LcnBindingConstants.java, bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/LcnGroupHandler.java, bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/LcnModuleDiscoveryService.java, bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/LcnModuleHandler.java, bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/subhandler/LcnModuleMetaFirmwareSubHandler.java
The previous implementation sent serial number requests without throttling and without retrying, which lead to unresolved serial numbers. This occurs if more than a couple of modules have no serial number property set, yet.
=> [lcn] Make requesting module serial numbers more reliable

bundles/org.openhab.binding.neato/README.md, bundles/org.openhab.binding.neato/src/main/java/org/openhab/binding/neato/internal/NeatoRobot.java, bundles/org.openhab.binding.neato/src/main/java/org/openhab/binding/neato/internal/classes/Category.java, bundles/org.openhab.binding.neato/src/main/java/org/openhab/binding/neato/internal/classes/Mode.java, bundles/org.openhab.binding.neato/src/main/java/org/openhab/binding/neato/internal/classes/NavigationMode.java, bundles/org.openhab.binding.neato/src/main/java/org/openhab/binding/neato/internal/classes/NeatoState.java, bundles/org.openhab.binding.neato/src/main/resources/ESH-INF/thing/vacuumcleaner.xml
[NEATO] add option to clean house with map and no-go lines
Improvements to Add option Clean with map to binding neato to launch clean with no-go line activated.
I don't remove the old clean option because of legacy and I don't know if this code work on a Neato D5
Tested only on neato D7.
see issue for more info #5761
=> [NEATO] add option to clean house with map and no-go lines

bundles/org.openhab.binding.heos/src/main/java/org/openhab/binding/heos/internal/handler/HeosBridgeHandler.java, bundles/org.openhab.binding.heos/src/main/java/org/openhab/binding/heos/internal/handler/HeosGroupHandler.java
Remove group-mapping when marking group OFFLINE
Bail out in group-handler if the pid matches but the members do not match.
See: https://community.openhab.org/t/heos-denon-support/3449/360?u=martinvw / https://community.openhab.org/t/heos-denon-support/3449/355?u=martinvw
=> [HEOS] Update handling of groups

bundles/org.openhab.binding.lcn/src/main/resources/ESH-INF/thing/thing-types.xml
As LCN groups don't send any status messages, it makes no sense to have status Channels for LCN groups. They will never be updated.
=> [lcn] Remove status-only Channels from LCN Group Thing

bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/AbstractMQTTThingHandler.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/handler/GenericMQTTThingHandler.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/handler/HomeAssistantThingHandler.java, bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/internal/handler/HomieThingHandler.java
When Home Assistant and MQTT generic things were disposed (and stopped), parent class (AbstractMQTTThingHandler) ```stop()``` method was not called and, thus, availability subscriptions were not removed. This made the Thing stay offline in some cases, as described in #8316. 
The AbstractMQTTThingHandler's ```stop()``` method has also been simplified calling ```clearAllAvailabilityTopics();```. @jochen314, what do you think about this last change? I don't see any problem emptying the availabilityStates map of AbstractMQTTThingHandler, because the ```initialize()``` method of both GenericThingHandler and HomeAssistantThingHandler takes care of creating the map again.
Fixes #8316
Review request: @jochen314, @J-N-K, @fwolter, @cpmeister, @Hilbrand.
Signed-off-by: Aitor Iturrioz …
=> [mqtt.generic] Clear availability subscriptions on stop

bundles/org.openhab.binding.tellstick/pom.xml
Updates related to snyk bot security suggestions.
Replaces #6391 and #6431 because those are based on old master branch.
I didn't update asynchttpclient because the new version has some additional dependencies.
=> [tellstick] Updates versions of libraries

bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/parser/GetParamsetParser.java
Only the string value contains the complete name that is necessary for
the check.
Additional fix for #5048
Fix has already been successfully tested.
=> [homematic] Checking of full datapoint name is necessary

bundles/org.openhab.binding.hpprinter/src/main/java/org/openhab/binding/hpprinter/internal/HPPrinterDiscoveryParticipant.java
While trying the hpprinter binding I got the following NPE, which is fixed with this patch:
```
11:36:21.825 [ERROR] [ry.mdns.internal.MDNSDiscoveryService] - Participant 'org.openhab.binding.hpprinter.internal.HPPrinterDiscoveryParticipant' threw an exception java.lang.NullPointerException: null
at org.openhab.binding.hpprinter.internal.HPPrinterDiscoveryParticipant.createResult(HPPrinterDiscoveryParticipant.java:55) ~[?:?]
```
=> [hpprinter] Fixed NPE in discovery

bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/handler/BridgeHandler.java, bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/lib/listener/ConnectionListener.java, bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/lib/manager/ConnectionManager.java, bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/lib/manager/impl/ConnectionManagerImpl.java, bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/lib/manager/impl/SceneManagerImpl.java, bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/lib/sensorjobexecutor/AbstractSensorJobExecutor.java, bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/lib/serverconnection/impl/HttpTransportImpl.java, bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/lib/structure/scene/InternalScene.java
This PR addresses several issues/probems:
1. This fixes issue #8214 
2. There was no specific handling of SSLHandshakeExecptions, which resulted in a default handling a lots of stacktraces printed to the logs
3. The default connection error handling was faulty, because the bridge was not set to "offline"
4. There was some kind of "loop" in the reconnect process which resulted in stack overflows.
5. Sometimes scene calls get "lost" which ends up in scenes being not updated anymore. Fix: Any scene activation will now be sent to the core even if the status in the binding is already "active".
=> [Digitalstrom] Bugfixes/Improvements

bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/CChannel.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/ComponentSensor.java
This PR creates trigger channels (and not state channels) for HA sensor components that send stateless information (action and button press events, mainly). The implementation is not device specific and it should be generic enough to be accepted. We can also add more objectIDs if they are used to send this type of information, but, in theory, this list should be short.
What do you think? @jochen314? 
Closes: #6878
=> [mqtt.homeassistant] Create trigger channels for stateless sensors

bundles/org.openhab.binding.modbus/src/main/resources/ESH-INF/thing/thing-data.xml
=> [modbus] Fix indentation in thing-data.xml breaking the build

bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/OnOffValue.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/TextValue.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/Value.java, bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/internal/homie300/Property.java
This PR makes non-retained and non-settable properties usable, because right now they not fully supported as described in #8164.
With the proposed changes, this type of properties are modeled as state channels and as such are able to receive commands, but they don't update their states, as they are meant to be "stateless" (non-retained -> we don't want to store the value). That's why I have defined the VETO option for the AutoUpdatePolicy. At the same time, I have extended the generic Value class so that its children classes can implement the createCommandDescription() method. Usually this type of properties will be used with the "enum" data type, so providing a list of command options makes sense.
Feedback from @jochen314, @J-N-K, @cpmeister, @Hilbrand and @fwolter would be highly …
=> [mqtt][homie] Implement non-retained and non-settable properties

bundles/org.openhab.binding.openwebnet/README.md, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/discovery/OpenWebNetDeviceDiscoveryService.java
Fixes #8327 Compilation errors on openHAB 3 adding annotation to getThingHandler().
Fixes a typo in README.
=> [openwebnet] Fixes #8327 Compilation errors on openHAB 3

bundles/org.openhab.binding.bosesoundtouch/src/main/resources/ESH-INF/config/config.xml, bundles/org.openhab.binding.bticinosmarther/src/main/resources/ESH-INF/config/config.xml, bundles/org.openhab.binding.deconz/src/main/resources/ESH-INF/binding/binding.xml, bundles/org.openhab.binding.feed/src/main/resources/ESH-INF/binding/binding.xml, bundles/org.openhab.binding.feed/src/main/resources/ESH-INF/thing/thing-types.xml, bundles/org.openhab.binding.innogysmarthome/src/main/resources/ESH-INF/thing/bridge.xml, bundles/org.openhab.binding.lirc/src/main/resources/ESH-INF/binding/binding.xml, bundles/org.openhab.binding.lutron/src/main/resources/ESH-INF/thing/thing-types.xml, bundles/org.openhab.binding.max/src/main/resources/ESH-INF/thing/thing-types.xml, bundles/org.openhab.binding.mihome/src/main/resources/ESH-INF/binding/binding.xml, bundles/org.openhab.binding.mqtt/src/main/resources/ESH-INF/thing/thing-types.xml, bundles/org.openhab.binding.nibeheatpump/src/main/resources/ESH-INF/thing/f1x55-types.xml, bundles/org.openhab.binding.systeminfo/src/main/resources/ESH-INF/config/channelConfig.xml, bundles/org.openhab.binding.tesla/src/main/resources/ESH-INF/thing/channels.xml, bundles/org.openhab.io.mqttembeddedbroker/src/main/resources/ESH-INF/config/config.xml
The spotless:apply command sometimes has issues properly wrapping lines.
=> Improve XML line wrapping

bundles/org.openhab.binding.phc/README.md
Corrects the parameters of the JRM and DIM thing definition, especially in the example.
Link to the community: https://community.openhab.org/t/switch-from-peha-phc-to-new-automation-with-openhab2/61154/46
Signed-off-by: Jonas Hohaus jh@gnlpf.net
=> [phc] Correct README

itests/org.openhab.binding.mqtt.homeassistant.tests/pom.xml, itests/org.openhab.binding.mqtt.homie.tests/pom.xml, itests/org.openhab.io.mqttembeddedbroker.tests/pom.xml
As requested in https://github.com/openhab/openhab-addons/pull/7206#issuecomment-682730688, I have created this PR to update the version number of the MQTT itests, so that @jochen314 doesn't need to do it. I can close the PR if he prefers to change them :+1: 
=> [mqtt] Fix itests version number

bundles/org.openhab.binding.openwebnet/pom.xml, bundles/org.openhab.binding.openwebnet/src/main/feature/feature.xml
This allows for more easily debugging the add-on in Eclipse and with the updated gnu.io version range it can also be used with OH3.
See also https://github.com/openhab/openhab-addons/pull/7589
=> [openwebnet] Embed dependency and update gnu.io version range

bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/command/MCommand.java, bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/command/SCommand.java, bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/command/SConfigCommand.java, bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/command/TCommand.java, bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/message/CMessage.java, bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/message/LMessage.java, bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/message/MMessage.java, bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/message/NMessage.java
Replace org.apache.commons.net.util.Base64 with java.util.Base64
eliminating several warning messages
[WARNING] org.openhab.binding.max.internal.command.MCommand.java:[23]                                                                                                                                                                  **The package org.apache.commons.net.utils should not be used.**       
=> [max] remove dependency on org.apache.commons.net.util

bundles/org.openhab.binding.dsmr/src/main/java/org/openhab/binding/dsmr/internal/device/connector/DSMRSerialConnector.java
I did some testing with RFC2217 and the DSMR Binding some time ago and I didn't run into any issues after catching these `UnsupportedCommOperationException` exceptions.
A similar approach was used for ZWave in https://github.com/openhab/org.openhab.binding.zwave/pull/1337.
Related to https://github.com/openhab/openhab-core/issues/1462.
=> [dsmr] Catch exceptions for RFC2217 compatibility

CODEOWNERS, bom/openhab-addons/pom.xml, bundles/org.openhab.binding.nzwateralerts/.classpath, bundles/org.openhab.binding.nzwateralerts/.project, bundles/org.openhab.binding.nzwateralerts/NOTICE, bundles/org.openhab.binding.nzwateralerts/README.md, bundles/org.openhab.binding.nzwateralerts/pom.xml, bundles/org.openhab.binding.nzwateralerts/src/main/feature/feature.xml, bundles/org.openhab.binding.nzwateralerts/src/main/java/org/openhab/binding/nzwateralerts/internal/NZWaterAlertsBindingConstants.java, bundles/org.openhab.binding.nzwateralerts/src/main/java/org/openhab/binding/nzwateralerts/internal/NZWaterAlertsConfiguration.java, bundles/org.openhab.binding.nzwateralerts/src/main/java/org/openhab/binding/nzwateralerts/internal/api/BeWaterWise.java, bundles/org.openhab.binding.nzwateralerts/src/main/java/org/openhab/binding/nzwateralerts/internal/api/NapierCityCouncil.java, bundles/org.openhab.binding.nzwateralerts/src/main/java/org/openhab/binding/nzwateralerts/internal/api/SmartWater.java, bundles/org.openhab.binding.nzwateralerts/src/main/java/org/openhab/binding/nzwateralerts/internal/api/TaupoDistrictCouncil.java, bundles/org.openhab.binding.nzwateralerts/src/main/java/org/openhab/binding/nzwateralerts/internal/api/WaterAlertWebClient.java, bundles/org.openhab.binding.nzwateralerts/src/main/java/org/openhab/binding/nzwateralerts/internal/api/WaterWebService.java, bundles/org.openhab.binding.nzwateralerts/src/main/java/org/openhab/binding/nzwateralerts/internal/binder/NZWaterAlertsBinder.java, bundles/org.openhab.binding.nzwateralerts/src/main/java/org/openhab/binding/nzwateralerts/internal/binder/NZWaterAlertsBinderListener.java, bundles/org.openhab.binding.nzwateralerts/src/main/java/org/openhab/binding/nzwateralerts/internal/handler/NZWaterAlertsHandler.java, bundles/org.openhab.binding.nzwateralerts/src/main/java/org/openhab/binding/nzwateralerts/internal/handler/NZWaterAlertsHandlerFactory.java, bundles/org.openhab.binding.nzwateralerts/src/main/resources/ESH-INF/binding/binding.xml, bundles/org.openhab.binding.nzwateralerts/src/main/resources/ESH-INF/thing/thing-types.xml, bundles/pom.xml
New Zealand Water Alerts Binding
__*New Pull Request due to the original being open for 693 commits and unable to rebase.*__
This is a new binding which gives the Water Alert Level in some regions in New Zealand.
There is only a single channel which returns the water alert level, a range of `0-4` or `1-4` depending on region. This is intended to be used with automated sprinkler systems in openHAB as restriction levels usually dictate the days where you are allowed to use sprinklers, if at all.
Works by page scraping associated regional council websites. Unfortunately cannot use a Web API as none exists.
=> [nzwateralerts] New Zealand Water Alerts Binding initial contribution

bundles/org.openhab.binding.max/src/main/resources/ESH-INF/thing/thing-types.xml
As paperUI only gives whole numbers now instead of the .5 values
=> [max] improve setchannel definition

features/openhab-addons/src/main/resources/footer.xml, pom.xml
The footer doesn't use tabs or proper indentation so after the aggregated feature file was generated a subsequent build would fail.
Related to https://github.com/openhab/openhab-addons/pull/8401
=> Improve feature file aggregation

bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/command/ACommand.java, bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/command/CCommand.java, bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/command/CubeCommand.java, bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/command/FCommand.java, bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/command/LCommand.java, bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/command/MCommand.java, bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/command/NCommand.java, bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/command/QCommand.java, bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/command/SCommand.java, bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/command/SConfigCommand.java, bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/command/TCommand.java, bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/command/UdpCubeCommand.java, bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/command/ZCommand.java, bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/handler/MaxCubeBridgeHandler.java, bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/handler/SendCommand.java
* add @notnullbydefault to classes in command
* replace org.apache.commons.lang.builder.ToStringBuilder with
StringBuilder (#7722)
=> [max] add @notnullbydefault to eliminate warnings from commands classes

bundles/org.openhab.binding.smhi/src/main/java/org/openhab/binding/smhi/internal/SmhiConnector.java
Noticed when testing on OH3 that `String.format` used the wrong decimal separator (might just be that I used a different locale setting for that instance) which caused the binding to stop working. This is a small fix to correct that.
=> [smhi][OH3] Fix bug running on OH3

bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/handler/NikoHomeControlActionHandler.java, bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/handler/NikoHomeControlEnergyMeterHandler.java, bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/handler/NikoHomeControlThermostatHandler.java
I had a report of a badly configured thing going online when the bridge went online, thereafter leading to a NPE on refresh. This should prevent this from happening.
=> [nikohomecontrol] Check bridge status when thing ready to go online.

bundles/org.openhab.binding.openwebnet/README.md, bundles/org.openhab.binding.openwebnet/pom.xml, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/OpenWebNetBindingConstants.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/handler/OpenWebNetAutomationHandler.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/handler/OpenWebNetBridgeHandler.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/handler/OpenWebNetThingHandler.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/OpenWebNetHandlerFactory.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/discovery/BusGatewayUpnpDiscovery.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/discovery/OpenWebNetDeviceDiscoveryService.java, bundles/org.openhab.binding.openwebnet/src/main/resources/ESH-INF/thing/BusAutomation.xml, bundles/org.openhab.binding.openwebnet/src/main/resources/ESH-INF/thing/ZBAutomation.xml, bundles/org.openhab.binding.openwebnet/src/main/resources/ESH-INF/thing/channels.xml
Add support for WHO=2 Automation.
Updated openwebnet4j to 0.3.0. 
Fixes #8436
Signed-off-by: Massimo Valla <mvcode00@gmail.com>
=> [openwebnet] add support for WHO=2 Automation

.travis.yml
Upgrades the Travis CI build environment to Ubuntu 18.04 (Bionic Beaver).
The openjdk8 package is unsupported in newer Ubuntu versions.
Also fixes the following Travis configuration validation warnings:
* deprecated key sudo (The key `sudo` has no effect anymore.)
* missing os, using the default linux
Removes $HOME/.bnd/cache which does not exist after builds.
It's also no longer necessary to disable IPv6 with builds.
This was an actual issue in the hueemulation add-on which was fixed by #7305.
=> Upgrade Travis CI to use Ubuntu 18.04 and fix warnings/caching (2.5.x)

bundles/org.openhab.binding.satel/README.md, bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/handler/SatelEventLogHandler.java
This PR adds support for additional event log event type. Related community discussion is here: https://community.openhab.org/t/satel-binding-support-announcements-and-feature-requests/56135/209
Besides that there are some minor changes in the examples section od README file.
=> [satel] Add support for event type 32

bundles/org.openhab.binding.gree/README.md, bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/GreeBindingConstants.java, bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/GreeConfiguration.java, bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/handler/GreeAirDevice.java, bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/handler/GreeHandler.java, bundles/org.openhab.binding.gree/src/main/resources/ESH-INF/i18n/gree.properties, bundles/org.openhab.binding.gree/src/main/resources/ESH-INF/i18n/gree_DE.properties, bundles/org.openhab.binding.gree/src/main/resources/ESH-INF/thing/thing-types.xml
Added a new channel called "currentTemperature" which maps to the temperature sensor which is present on GREE AC devices. This should allow for the addition of rules which are based on the actual room temperature, Eg: switch on AC in heating/cooling mode if room temperature is higher/lower than X. This temperature sensing channel can also be used to control other features like ventilation, etc by comparing the indoor and outdoor temperature. This usually requires a dedicated temperature sensor for reading the indoor temperature and such temperature is readily available in GREE AC devices and readable over this binding with the help of this PR.
~### Breaking Change!
This binding which was only recently introduced already contained a temperature channel called "temperature". This was meant …
=> [gree] Add channel for temperature sensor

bundles/org.openhab.binding.dsmr/src/main/java/org/openhab/binding/dsmr/internal/discovery/DSMRDiscoveryService.java, bundles/org.openhab.binding.dsmr/src/test/java/org/openhab/binding/dsmr/internal/discovery/DSMRMeterDiscoveryServiceTest.java
Additional validation got added in OH3 to make sure that the bridgeUID is added to Things with bridges (openhab/openhab-core#1481).
The `DSMRBridgeDiscoveryService` did not add the bridgeUID so it would cause the following exceptions during discovery:
```
java.lang.IllegalArgumentException: Thing UID 'dsmr:device_v4:default' does not match bridge UID 'dsmr:dsmrBridge:22e5393c'
at org.openhab.core.config.discovery.DiscoveryResultBuilder.validateThingUID(DiscoveryResultBuilder.java:166) ~[bundleFile:?]
at org.openhab.core.config.discovery.DiscoveryResultBuilder.withBridge(DiscoveryResultBuilder.java:120) ~[bundleFile:?]
at org.openhab.binding.dsmr.internal.discovery.DSMRDiscoveryService.meterDiscovered(DSMRDiscoveryService.java:81) ~[bundleFile:?]
at …
```
=> [dsmr] Add bridgeUID to thingUID during discovery

bundles/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/PlugwiseThingDiscoveryService.java
Additional validation got added in OH3 to make sure that the bridgeUID is added to Things with bridges (https://github.com/openhab/openhab-core/pull/1481).
The `PlugwiseThingDiscoveryService` did not add the bridgeUID so it would cause the following exceptions during discovery:
```
java.lang.IllegalArgumentException: Thing UID 'plugwise:circleplus:abc' does not match bridge UID 'plugwise:stick:xyz'
at org.openhab.core.config.discovery.DiscoveryResultBuilder.validateThingUID(DiscoveryResultBuilder.java:166) ~[bundleFile:?]
at org.openhab.core.config.discovery.DiscoveryResultBuilder.withBridge(DiscoveryResultBuilder.java:120) ~[bundleFile:?]
at org.openhab.binding.plugwise.internal.PlugwiseThingDiscoveryService.createDiscoveryResult(PlugwiseThingDiscoveryService.java:130) ~[bundleFile:?]
at …
```
=> [plugwise] Add bridgeUID to thingUID during discovery

bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/discovery/AmazonEchoDiscovery.java, bundles/org.openhab.binding.foobot/src/main/java/org/openhab/binding/foobot/internal/discovery/FoobotAccountDiscoveryService.java, bundles/org.openhab.binding.groheondus/src/main/java/org/openhab/binding/groheondus/internal/discovery/GroheOndusDiscoveryService.java, bundles/org.openhab.binding.heos/src/main/java/org/openhab/binding/heos/internal/discovery/HeosPlayerDiscovery.java, bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/discovery/InsteonDeviceDiscoveryService.java, bundles/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/discovery/SensorDiscoveryService.java, bundles/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/discovery/XiaomiItemDiscoveryService.java, bundles/org.openhab.binding.neato/src/main/java/org/openhab/binding/neato/internal/discovery/NeatoAccountDiscoveryService.java, bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/discovery/OpenUVDiscoveryService.java, bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/discovery/VolvoOnCallDiscoveryService.java, bundles/org.openhab.binding.weatherunderground/src/main/java/org/openhab/binding/weatherunderground/internal/discovery/WeatherUndergroundDiscoveryService.java
Fixes exceptions thrown in OH3 when building discovery results for things with bridges where the thing UID is missing the bridge UID.
Related to openhab/openhab-core#1481
=> Fix missing bridge UID in thing UID during discovery

bundles/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/PlugwiseCommunicationContext.java, bundles/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/PlugwiseCommunicationHandler.java, bundles/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/PlugwiseMessageProcessor.java, bundles/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/PlugwiseMessageSender.java, bundles/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/handler/PlugwiseStickHandler.java
By using the OH thread naming scheme it will be easier to find the Plugwise Binding threads. Because the bridge UID is added in the thread names, the thread names will be unique and it will be easier to identify threads when using multiple Sticks. I also used some more construction injection and final to prevent null values.
=> [plugwise] Use OH thread naming scheme and constructor injection

bundles/org.openhab.binding.modbus/pom.xml, bundles/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/handler/ModbusPollerThingHandler.java, bundles/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/handler/ModbusDataThingHandler.java, bundles/org.openhab.binding.modbus/src/main/resources/ESH-INF/thing/bridge-poller.xml, bundles/org.openhab.io.transport.modbus/src/main/java/org/openhab/io/transport/modbus/ModbusConstants.java, bundles/org.openhab.io.transport.modbus/src/main/java/org/openhab/io/transport/modbus/json/WriteRequestJsonUtilities.java, bundles/org.openhab.io.transport.modbus/src/test/java/org/openhab/io/transport/modbus/test/WriteRequestJsonUtilitiesTest.java, itests/org.openhab.binding.modbus.tests/src/main/java/org/openhab/binding/modbus/tests/ModbusPollerThingHandlerTest.java
Related to discussion in #8228
=> [modbus] Validate poller count and write count according to modbus spec

bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/TPLinkSmartHomeDiscoveryService.java
a recent change to core (https://github.com/openhab/openhab-core/pull/1573) is now checking that this is correct, my logs are constantly filling up with this message :-)
=> [tplinksmarthome] Use the representation property correctly 

bundles/org.openhab.io.transport.modbus/src/main/java/org/openhab/io/transport/modbus/internal/ModbusPoolConfig.java
Resolves #8460
To my understanding, this is really a workaround for a hard-to-reproduce bug in Apache Pool2 2.8.1. I have not been able to find out detailed sequence-of-events that leads to the deadlock.
As explained in #8460, the borrow sometimes waits for idle connection to appear in the pool but there is no one to return any connection. With this PR the eviction thread (run every 10s) will ensure that there is at least one idle connection in the pool, resolving the deadlock.
Based on PR #8411. 8411 Should be merged first, marking this as "awaiting other PR".
=> [modbus] Fix for polling that stops

bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/lib/config/Config.java
While moving from eclipse smarthome, we should change the name of our application to identify against the digitalSTROM installation.
=> [digitalSTROM] Change application Name for creating access token

bundles/org.openhab.binding.nuki/README.md, bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/NukiBindingConstants.java, bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/dataexchange/BridgeLockStateResponse.java, bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/dataexchange/NukiApiServlet.java, bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/dto/BridgeApiLockStateDto.java, bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/dto/BridgeApiLockStateRequestDto.java, bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/handler/NukiSmartLockHandler.java, bundles/org.openhab.binding.nuki/src/main/resources/ESH-INF/thing/thing-types.xml
After one of the latest updates, the API of the Nuki smart lock device 2.0 includes the state of the door sensor. 
This improvement adds a new channel to the Nuki SmartLock device in OpenHab which displays the door sensor state. 
This PR includes the code changes, updated documentation and is already tested in my local demo and production environment. 
This PR is related to [issue #8438](https://github.com/openhab/openhab-addons/issues/8438). 
Link to the JAR file: 
[https://cloud.seeage.com/s/N3bZ7MpgRaoaMrZ](https://cloud.seeage.com/s/N3bZ7MpgRaoaMrZ)
=> [nuki] Add smart lock door sensor state as new channel (#8438)

bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/handler/KaleidescapeMessageHandler.java
This deprecated constructor was removed in OH3.
See build: https://ci.openhab.org/job/openHAB-Addons-port/265/console
=> Fix add-ons port

bundles/org.openhab.binding.gree/README.md, bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/GreeBindingConstants.java, bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/handler/GreeAirDevice.java, bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/handler/GreeHandler.java, bundles/org.openhab.binding.gree/src/main/resources/ESH-INF/i18n/gree.properties, bundles/org.openhab.binding.gree/src/main/resources/ESH-INF/i18n/gree_DE.properties
This PR adds some improvements
- Improved timeout handling on temporary networks issues
- currentTemperature is updated with NaN when no value is available (device returns -40)
- channel swingUpDown now accepts values 0-11
=> [gree] Minor improvements

bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/handler/GreeHandler.java
@Hilbrand This is a hotfix for the release. Due to a missing "return" it could get into an endless loop in the command handler. Shame on me :-)
=> [gree] Fix endless loop in command handler (previous PR)

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/discovery/MiIoDiscoveryParticipant.java, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoBasicHandler.java
* get tokens from cloud if possible and add them during discovery.
(similar to the other discovery method)
Note to reviewer: 
for some reason the @Reference CloudConnector cloudConnector did not want to work with final. Ugly framework errors as result.  Having it with a @Nullable did work fine.
=> [miio] add automatic tokens to miio MDNSDiscoveryParticipant

bundles/org.openhab.binding.teleinfo/src/main/java/org/openhab/binding/teleinfo/internal/serial/TeleinfoSerialControllerHandler.java
This PR adds support for rfc2217 serial port in teleinfo binding.
=> [teleinfo] Add rfc2217 support

bundles/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/protocol/ADMsgType.java, bundles/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/protocol/KeypadMessage.java
[alarmdecoder] allow keypad messages with !KPM:
This PR updates the alarmdecoder binding to accept KeyPad messages with the `!KPM` prefix.  
Logs from my serial AD2USB, which indicate the prefix.
```
10:41:44.219 [TRACE] [oder.internal.handler.ADBridgeHandler] - Received msg: !KPM:[10000001100000003A--],008,[f70000051008001c28020000000000]," DISARMED CHIME   Ready to Arm  "
10:41:48.178 [TRACE] [oder.internal.handler.ADBridgeHandler] - Received msg: !KPM:[10000001100100000A--],011,[f70000051011005028020000000000],"LOBAT 11                        "
```
I was able to verify the changes here enable the KeyPad.
Thread started.
https://community.openhab.org/t/alarmdecoder-2-5-7-binding-serial-keypad/103242
=> [alarmdecoder] allow keypad messages with !KPM:

bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/HikvisionHandler.java, bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/handler/IpCameraHandler.java
Fixed an issue and hopefully it is not too late.
MAP<> can return null which was not getting checked for and causes issues.
Minor log fixes from massive find replaces done yesterday.
=> [ipcamera] Fix not handling null on MAP<>, and log messages had find/replace issue.

bundles/org.openhab.binding.smhi/src/main/resources/OH-INF/config/forecast-config.xml
PaperUI in OH2 didn't respect the order of the elements in the config-description, so I had to prefix them with numbering to get the correct sort-order. This is no longer an issue in the new OH3 UI, so it can be cleaned up.
=> [smhi] Remove paperui sorting workaround

bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/jsons/JsonPlaylists.java
Fixes #8491
As far as I can see the "version" field in the playlist is parsed, but never used.
=> [amazonechocontrol] Remove unused version which no longer parses due to type change

features/openhab-addons-external/pom.xml, features/openhab-addons/pom.xml, features/openhab-addons/src/main/resources/footer.xml
Reverts https://github.com/openhab/openhab-addons/pull/6710 as we no longer inherit those features from the 2.5.x build.
=> Reintroduced aggregated features and restored the standard feature name

features/openhab-addons/src/main/resources/footer.xml, pom.xml
Not ideal, but it fixes the build.
I am not aware of an easy way to disable spotless on a given file/project.
=> do not apply spotless to footer.xml

bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/discovery/SomfyTahomaItemDiscoveryService.java, bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaBaseThingHandler.java
Due to changes in Somfy API responses I need to slightly update the detection mechanism, so the roller shutters are again detected OK.
So this is a bugfix PR...
I have rebased it to the main branch as mentioned here #8512 
Replaces #8545
=> [somfytahoma] fixed detection of roller shutters

bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/StateUtils.java
My hue emulation had some problems which I narrowed down to the following:
GET /api/testuser/lights would fail.
In the openhab log, I could read:
2020-09-23 19:34:07.447 [WARN ] [org.eclipse.jetty.server.HttpChannel] - /api/testuser/lights
javax.servlet.ServletException: javax.servlet.ServletException: java.lang.NullPointerException
at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:88) ~[bundleFile:?]
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[bundleFile:9.4.20.v20190813]
at org.eclipse.jetty.server.Server.handle(Server.java:494) ~[bundleFile:9.4.20.v20190813]
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:374) [bundleFile:9.4.20.v20190813]
at …
=> [hueemulation] Listing hue lights fails

bundles/org.openhab.binding.amazondashbutton/src/main/java/org/openhab/binding/amazondashbutton/internal/config/AmazonDashButtonConfigOptionProvider.java, bundles/org.openhab.binding.gpstracker/src/main/java/org/openhab/binding/gpstracker/internal/GPSTrackerHandlerFactory.java, bundles/org.openhab.binding.smartmeter/src/main/java/org/openhab/binding/smartmeter/internal/SmartMeterConfigProvider.java
Related to openhab/openhab-core#1667
=> Remove deprecated ConfigOptionProvider.getParameterOptions method

itests/org.openhab.binding.feed.tests/itest.bndrun, itests/pom.xml
With these changes and working channelLink events (openhab/openhab-core#1634) the feed itest works again.
Related to #8537
=> [feed] Reenable itest

itests/org.openhab.binding.ntp.tests/src/main/java/org/openhab/binding/ntp/test/NtpOSGiTest.java, itests/pom.xml
With these changes and working channelLink events (openhab/openhab-core#1634) the ntp itest works again.
In #7834 the command handling was changed to only refresh when REFRESH commands are received instead of every command.
Related to #8537
=> [ntp] Reenable itest

bundles/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/internal/handler/Cm11aBridgeHandler.java, bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/KNXBridgeBaseThingHandler.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/radiora/handler/DimmerHandler.java, bundles/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/handler/XiaomiActorGatewayHandler.java, bundles/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/handler/XiaomiSensorBaseHandlerWithTimer.java, bundles/org.openhab.binding.phc/src/main/java/org/openhab/binding/phc/internal/handler/PHCHandler.java, bundles/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/internal/live/TelldusLiveBridgeHandler.java, bundles/org.openhab.transform.exec/src/main/java/org/openhab/transform/exec/internal/profiles/ExecTransformationProfile.java, bundles/org.openhab.transform.javascript/src/main/java/org/openhab/transform/javascript/internal/profiles/JavascriptTransformationProfile.java, bundles/org.openhab.transform.jinja/src/main/java/org/openhab/transform/jinja/internal/profiles/JinjaTransformationProfile.java, bundles/org.openhab.transform.jsonpath/src/main/java/org/openhab/transform/jsonpath/internal/profiles/JSonPathTransformationProfile.java, bundles/org.openhab.transform.map/src/main/java/org/openhab/transform/map/internal/profiles/MapTransformationProfile.java, bundles/org.openhab.transform.regex/src/main/java/org/openhab/transform/regex/internal/profiles/RegexTransformationProfile.java, bundles/org.openhab.transform.scale/src/main/java/org/openhab/transform/scale/internal/profiles/ScaleTransformationProfile.java, bundles/org.openhab.transform.xpath/src/main/java/org/openhab/transform/xpath/internal/profiles/XPathTransformationProfile.java, bundles/org.openhab.transform.xslt/src/main/java/org/openhab/transform/xslt/internal/profiles/XSLTTransformationProfile.java
The handleUpdate method was deprecated when profiles were introduced (see eclipse-archived/smarthome#4108).
Instead the [follow profile](https://www.openhab.org/docs/developer/transformations/#followprofile) can be used which forwards item updates as commands to handlers.
This profile works with any binding instead of only those that implement the handleUpdate method.
Related to openhab/openhab-core#1669
=> Remove deprecated handleUpdate from ThingHandler

features/openhab-addons/pom.xml
=> exclude bundles that are not yet included in the build from the aggregated feature

bundles/org.openhab.binding.insteon/README.md, bundles/org.openhab.binding.insteon/src/main/resources/OH-INF/thing/thing-types.xml
Fixed documentation to match functionality.
=> [insteon] remove optional from the description of network parameters

bundles/org.openhab.binding.modbus.e3dc/README.md, bundles/org.openhab.binding.modbus.helioseasycontrols/README.md, bundles/org.openhab.binding.modbus.stiebeleltron/README.md, features/openhab-addons/src/main/resources/footer.xml
Applied #8549 against main. Fixes #8538 (modbus extensions missing)
=> [modbus] Fixes #8538 (modbus extensions missing)

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoBasicHandler.java
In case of the parameters & response are not equal avoid the
java.lang.IndexOutOfBoundsException:
=> [miio] avoid IndexOutOfBoundsException exception

bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusBridgeHandler.java, bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusNetworkBridgeHandler.java, bundles/org.openhab.binding.velbus/src/main/resources/OH-INF/thing/thing-types.xml
This PR fixes 2 bugs:
1.) The network bridge wasn't correctly listening on the bus, because the listening thread was never started
2.) The reconnection handler kept trying to reconnect, even after a successful reconnection, because it had a wrong (always null) reference to the scheduled action and wasn't able to cancel itself.
3.) Minor typo in alarm 1 wakeup time channels
=> [velbus] Fixed 3 bugs

bundles/org.openhab.binding.velux/README.md, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/VeluxBinding.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/VeluxBridgeActuators.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/VeluxBridgeDeviceStatus.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/VeluxBridgeGetFirmware.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/VeluxBridgeLANConfig.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/VeluxBridgeScenes.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/VeluxBridgeWLANConfig.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/json/JCgetDeviceStatus.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/json/JCgetFirmware.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/json/JCgetLANConfig.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/json/JCgetProducts.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/json/JCgetScenes.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/json/JCgetWLANConfig.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/json/JClogin.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/json/JClogout.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/json/JCrunProductDiscovery.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/json/JCrunProductIdentification.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/json/JCrunProductSearch.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/json/JCrunScene.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/json/JCsetSceneVelocity.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/json/JsonVeluxBridge.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/slip/utils/SlipEncoding.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/factory/VeluxHandlerFactory.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/handler/VeluxBridgeHandler.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/things/VeluxKLFAPI.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/things/VeluxProduct.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/things/VeluxProductState.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/things/VeluxScene.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/utils/Localization.java
In PR #8520 maven would produce about fifty non fatal compiler warnings (below), and this PR eliminates them..
- redundant NonNullByDefault code style warnings
- spurious potential null check warnings
- deprecated Java 11 method call warnings
- dependency on forbidden package warnings
=> [velux] eliminate mvn compiler warnings

bundles/org.openhab.binding.mqtt.homie/src/test/java/org/openhab/binding/mqtt/homie/internal/handler/HomieThingHandlerTests.java, itests/org.openhab.binding.mqtt.homeassistant.tests/itest.bndrun, itests/org.openhab.binding.mqtt.homeassistant.tests/pom.xml, itests/org.openhab.binding.mqtt.homeassistant.tests/src/main/java/org/openhab/binding/mqtt/DiscoverComponentsTest.java, itests/org.openhab.binding.mqtt.homeassistant.tests/src/main/java/org/openhab/binding/mqtt/EmbeddedBrokerTools.java, itests/org.openhab.binding.mqtt.homeassistant.tests/src/main/java/org/openhab/binding/mqtt/HomeAssistantMQTTImplementationTest.java, itests/org.openhab.binding.mqtt.homeassistant.tests/src/main/java/org/openhab/binding/mqtt/ThingChannelConstants.java, itests/org.openhab.binding.mqtt.homie.tests/itest.bndrun, itests/org.openhab.binding.mqtt.homie.tests/src/main/java/org/openhab/binding/mqtt/EmbeddedBrokerTools.java, itests/org.openhab.binding.mqtt.homie.tests/src/main/java/org/openhab/binding/mqtt/HomieImplementationTest.java, itests/org.openhab.binding.mqtt.homie.tests/src/main/java/org/openhab/binding/mqtt/ThingChannelConstants.java, itests/org.openhab.io.mqttembeddedbroker.tests/itest.bndrun, itests/org.openhab.io.mqttembeddedbroker.tests/src/main/java/org/openhab/io/mqttembeddedbroker/EmbeddedBrokerTools.java, itests/org.openhab.io.mqttembeddedbroker.tests/src/main/java/org/openhab/io/mqttembeddedbroker/MoquetteTest.java, itests/pom.xml
Fixes and enables:
* org.openhab.binding.mqtt.homeassistant.tests
* org.openhab.binding.mqtt.homie.tests
* org.openhab.io.mqttembeddedbroker.tests
Fixes #8537
=> Fix disabled integration tests

bundles/org.openhab.io.mqttembeddedbroker/pom.xml, bundles/org.openhab.io.mqttembeddedbroker/src/main/java/org/openhab/io/mqttembeddedbroker/Constants.java, bundles/org.openhab.io.mqttembeddedbroker/src/main/java/org/openhab/io/mqttembeddedbroker/internal/EmbeddedBrokerService.java, itests/org.openhab.binding.mqtt.homeassistant.tests/itest.bndrun, itests/org.openhab.binding.mqtt.homeassistant.tests/pom.xml, itests/org.openhab.binding.mqtt.homeassistant.tests/src/main/java/org/openhab/binding/mqtt/EmbeddedBrokerTools.java, itests/org.openhab.binding.mqtt.homeassistant.tests/src/main/java/org/openhab/binding/mqtt/HomeAssistantMQTTImplementationTest.java, itests/org.openhab.binding.mqtt.homie.tests/itest.bndrun, itests/org.openhab.binding.mqtt.homie.tests/pom.xml, itests/org.openhab.binding.mqtt.homie.tests/src/main/java/org/openhab/binding/mqtt/EmbeddedBrokerTools.java, itests/org.openhab.binding.mqtt.homie.tests/src/main/java/org/openhab/binding/mqtt/HomieImplementationTest.java, itests/org.openhab.io.mqttembeddedbroker.tests/itest.bndrun, itests/org.openhab.io.mqttembeddedbroker.tests/pom.xml, itests/org.openhab.io.mqttembeddedbroker.tests/src/main/java/org/openhab/io/mqttembeddedbroker/EmbeddedBrokerTools.java, itests/org.openhab.io.mqttembeddedbroker.tests/src/main/java/org/openhab/io/mqttembeddedbroker/MoquetteTest.java
* Improve exception handling of the embedded MQTT broker so the port can be reconfigured when it is already bound and it properly unlocks files
* Rework MQTT integration tests so they each run the embedded broker on their own reserved port
See: https://github.com/openhab/openhab-addons/pull/8609#issuecomment-701192332
=> Fix parallel MQTT itests execution

itests/org.openhab.binding.hue.tests/itest.bndrun, itests/org.openhab.binding.hue.tests/src/main/java/org/openhab/binding/hue/internal/handler/HueBridgeHandlerOSGiTest.java
The ThingStatus is updated asynchronously so the test is unstable when the status is not updated immediately.
See also https://ci.openhab.org/job/openHAB-Addons/69/ :
```
TEST org.openhab.binding.hue.internal.handler.HueBridgeHandlerOSGiTest#verifyStatusIfLinkButtonIsNotPressed() <<< ERROR: expected: <CONFIGURATION_ERROR> but was: <NONE>
org.opentest4j.AssertionFailedError: expected: <CONFIGURATION_ERROR> but was: <NONE>
at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1124)
at …
```
=> [hue] Improve HueBridgeHandlerOSGiTest stability

bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/VeluxBinding.java
Removed one further dependency on `org.apache.commons.lang.StringUtils` that had been overlooked before
=> [velux] eliminate dependency on org.apache.commons.lang.StringUtils

bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/AbstractMQTTThingHandler.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/handler/GenericMQTTThingHandler.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/CFactory.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/ComponentAlarmControlPanel.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/ComponentBinarySensor.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/ComponentCamera.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/ComponentCover.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/ComponentFan.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/ComponentLight.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/ComponentLock.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/ComponentSensor.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/ComponentSwitch.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/DiscoverComponents.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/handler/HomeAssistantThingHandler.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/listener/ChannelStateUpdateListenerProxy.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/listener/ExpireUpdateStateListener.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/listener/OffDelayUpdateStateListener.java, bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/internal/handler/HomieThingHandler.java
This make homeassistant sensor/binary_sensor compliant.
expire_after and off_delay are handled.
expire_after needs to reset the availablity. If there is a availablity topic, this is ignored. If no avalablity topic is set, then the nessage rescceived flag is reset, which makes the thing go offline.
Closes #7063
Migration of #7206
=> [mqtt, homeassistant]Make sensors compliant

bundles/org.openhab.binding.smartthings/doc/SmartthingsInstallation.md
[smartthings] updated url in SmartthingsInstallation.md to correctly point to the openhab repo
The SmartthingsInstallation.md file provides instruction for installing code onto the Smartthings hub. That code is located in the openhab-addons repo. The URL to the repo was wrong. I tested the change by viewing the file in preview mode and clicking on link. It now opens to the correct location.
I have not rebuilt the jar file as the changes did not include any code changes.
=> Updated smartthings code URL in SmartthingsInstallation.md

bundles/org.openhab.binding.ipcamera/README.md, bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/handler/IpCameraHandler.java, bundles/org.openhab.binding.ipcamera/src/main/resources/OH-INF/thing/thing-types.xml
+ Bug fix: Recording to GIF would only record for 5 seconds.
+ Clean up readme to remove channels and configs that don't exist after
moving to actions.
+ Compatibility fix for http headers that stopped a camera from working.
=> [ipcamera] bug fix, readme cleanup and http header change.

bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/CcuGateway.java, bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/pchkdiscovery/LcnPchkDiscoveryService.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/xml/DbXmlInfoReader.java, itests/org.openhab.binding.feed.tests/itest.bndrun, itests/org.openhab.binding.hue.tests/itest.bndrun, itests/org.openhab.binding.max.tests/itest.bndrun, itests/org.openhab.binding.modbus.tests/itest.bndrun, itests/org.openhab.binding.nest.tests/itest.bndrun, itests/org.openhab.binding.ntp.tests/itest.bndrun, itests/org.openhab.binding.systeminfo.tests/itest.bndrun, itests/org.openhab.binding.tradfri.tests/itest.bndrun, itests/org.openhab.binding.wemo.tests/itest.bndrun
* Configures XStream security to prevent "Security framework of XStream not initialized, XStream is probably vulnerable" warnings.
* Resolves the itest bundles for the upgrade to XStream 1.4.13
Depends on openhab/openhab-core#1688
=> Configure XStream security and resolve itest bundles

bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/factory/VeluxHandlerFactory.java
Silly errors:  
- the variable `this.discoveryService` was not being initialized..
- the discoveryServiceRegistration was not being destroyed and recreated after de- and re-registration
=> [velux] fix discovery service de- and re- registration

bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/WakeOnLanUtility.java, bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/utils/NetworkUtils.java, bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/WakeOnLanUtility.java, bundles/org.openhab.transform.exec/src/main/java/org/openhab/transform/exec/internal/ExecTransformationService.java
=> Adapt to changes in ExecUtil

bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java
According the comments DEFAULT_NUMERIC, DEFAULT_QUANTIFIABLE config should have 5 archives, the 4th was missing. Additionally the ConsolFunction changed in the DEFAULT_QUANTIFIABLE.
The DEFAULT_OTHER config had false computed archives.
Signed-off-by: Jürgen Baginski opus42@gmx.de
=> [rrd4j] Corrected the default configurations

bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/SnmpTargetHandler.java, bundles/org.openhab.binding.snmp/src/test/java/org/openhab/binding/snmp/internal/SnmpTargetHandlerTest.java
When receiving an async request it is placed in a pending request queue. Not canceling it leads to infinty life cycle for those requests, filling up memory.
=> [snmp] Fix memory leak in SNMP

bundles/org.openhab.binding.miio/src/test/java/org/openhab/binding/miio/internal/ReadmeHelper.java
Eliminate
[WARNING] org.openhab.binding.miio.internal.ReadmeHelper.java:[25]
The package org.apache.commons.io.FileUtils should not be used.
=> [miio] eliminate warning org.apache.commons.io.FileUtils in readmemaker

bundles/org.openhab.binding.mqtt.generic/README.md
Simply fixes interchanged values in `Format before Publish` section.
=> [mqtt] fixed Hex/Oct formatting, resulting values were interchanged

bundles/org.openhab.binding.icalendar/pom.xml
Fixes #8647 by just updating the dependency version, which is now released.
=> [icalendar] Updated biweekly to 0.6.4

bundles/org.openhab.binding.innogysmarthome/src/main/java/org/openhab/binding/innogysmarthome/internal/client/InnogyClient.java
This pull-request fixes issue #8734 (No commands can get executed after a few minutes) for OpenHAB 2.5.x.
See issue #8734 for more information.
=> [innogysmarthome] Fix - No commands can get executed after a few minutes (#8734)

bundles/pom.xml
The `shrink` profile has never been used and can be removed.
=> [infrastructure] remove unused profile

bundles/org.openhab.persistence.mapdb/pom.xml, bundles/org.openhab.persistence.mapdb/src/main/java/org/openhab/persistence/mapdb/internal/MapDbPersistenceService.java
Fixes #8659 
Additionally, terminating the common thread pool upon deactivation of the mapdb bundle has been removed.
=> [mapdb] Fixed deserialization of values in mapDB database

CODEOWNERS
While I was at fixing the sort of the CODEWONERS file in 2.5.x I stumpled upon this whitespace and also add a PR even if its a minor change.
=> CODEOWNERS remove whitespace

bundles/org.openhab.binding.telegram/README.md
Changed the README.md file to include more information as in #8733:
Specified that the chatId in the APIs must be followed by an "L" or it won't work (at least, not for group chats).
=> [Telegram] Improved sending to a particular chat

bundles/org.openhab.binding.telegram/README.md
Changed the README.md file to include more information:
Specified that the chatId in the APIs must be followed by an "L" or it won't work (at least, not for group chats).
Also mentioned that you can store the chatId inside a variable so that you can write it only once for the entire rules file.
=> [Telegram] Improved sending to a particular chat section

bundles/org.openhab.binding.hue/README.md, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/HueBindingConstants.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueSensorHandler.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/sensors/PresenceHandler.java, bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/PresenceSensor.xml
Added channel to enable / disable a motion sensor
Closes #8389 
=> [hue] Added channel to enable / disable a motion sensor

bundles/org.openhab.binding.ambientweather/src/main/java/org/openhab/binding/ambientweather/internal/handler/AmbientWeatherEventListener.java
MAC address comparison needs to use `equalsIgnoreCase`
=> [ambientweather] Fixed MAC comparison

README.md
* Add/explain more command line options
* Structure options in a table
* Explain when to use -DwithResolver
=> Improve "Command line build" section

CODEOWNERS, bom/openhab-addons/pom.xml, bundles/org.openhab.automation.groovyscripting/NOTICE, bundles/org.openhab.automation.groovyscripting/README.md, bundles/org.openhab.automation.groovyscripting/pom.xml, bundles/org.openhab.automation.groovyscripting/src/main/feature/feature.xml, bundles/org.openhab.automation.groovyscripting/src/main/java/org/openhab/automation/groovyscripting/internal/GroovyScriptEngineFactory.java, bundles/org.openhab.automation.groovyscripting/src/main/java/org/openhab/automation/groovyscripting/internal/package-info.java, bundles/pom.xml
This makes it really easy to start using [Groovy](https://groovy-lang.org/) 3.x scripts with openHAB!
---
```shell
openhab> log:set info jsr223.groovy
openhab> log:tail
20:05:00.470 [INFO ] [jsr223.groovy                        ] - Hello World!
```
=> [groovyscripting] Add Groovy scripting support

itests/org.openhab.binding.tradfri.tests/itest.bndrun
Related to openhab/openhab-core#1721
It causes the build to fail, see: https://ci.openhab.org/job/openHAB-Addons/100/
=> Fix Tradfri itest

bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/discovery/HomeAssistantDiscovery.java
In OH3 HA discovery correctly gives a warning about an incorrect usage of the representationProperty in the DiscoveryResult.
This PR fixes that.
=> [mqtt] Fixed wrong usage of representationProperty

bundles/org.openhab.persistence.mapdb/src/main/java/org/openhab/persistence/mapdb/internal/StateTypeAdapter.java
Related to https://github.com/openhab/openhab-addons/issues/8790
While it does not fix #8790, this PR will suppress the exception being thrown and instead do a warn logging with the state that cannot be deserialized.
=> [mapdb] Avoid ArrayIndexOutOfBoundsExceptions being thrown

bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/discovery/HDPowerViewHubDiscoveryParticipant.java
=> [hdpowerview] discovery could wrongly return a ThingUID based on a hub's Ipv6 address instead of its Ipv4 address

bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/LcnModuleHandler.java
The status of RollerShutter was not inverted when invertUpDown=true. Fixes #8680
=> [lcn] Fix status message of RollerShutter inverting

bundles/org.openhab.binding.bluetooth.daikinmadoka/src/main/resources/OH-INF/thing/daikinmadoka.xml
This PR fixes a minor bug, where a duplicate RSSI channel was created, in addition to the one provided by the BlueZ binding.
=> [daikinmadoka] removed duplicate channel RSSI

bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/handler/InsteonDeviceHandler.java, bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/handler/InsteonNetworkHandler.java
This addresses changes in behavior from OH2 to OH3 as described at https://github.com/openhab/openhab-core/issues/1707.
=> [insteon] handle cases when channelLinked is not called after initialization

bundles/org.openhab.binding.ambientweather/src/main/java/org/openhab/binding/ambientweather/internal/handler/AmbientWeatherEventListener.java
Apply 3.0 fix to 2.5.x
Fixed MAC address comparison to use `equalsIgnoreCase`
=> [ambientweather] Fixed MAC address comparison

bundles/org.openhab.persistence.influxdb/README.md, bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/InfluxDBStateConvertUtils.java, bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/InfluxPoint.java, bundles/org.openhab.persistence.influxdb/src/main/resources/OH-INF/config/config.xml, bundles/org.openhab.persistence.influxdb/src/test/java/org/openhab/persistence/influxdb/internal/ConfigurationTestHelper.java, bundles/org.openhab.persistence.influxdb/src/test/java/org/openhab/persistence/influxdb/internal/InfluxDBStateConvertUtilsTest.java, bundles/org.openhab.persistence.influxdb/src/test/java/org/openhab/persistence/influxdb/internal/ItemTestHelper.java, bundles/org.openhab.persistence.influxdb/src/test/java/org/openhab/persistence/influxdb/internal/ItemToStorePointCreatorTest.java
This PR mainly solves issue #8798 that was detected with OH 3.0 milestone 1 testing.
The issue has a long discussion/explanation on the problem, but summing up this PR ensures that always doubles are used to store numerical values. That is the safe way to store them due to the combination that OH doesn't have an IntegerType and Influx doesn't support different field types in the same series and shard.
This is compatible with old behavior because the old addon had the intent to use different types for integers but in the end it doesn't.
It also solves #8697 reflecting that with Influx2 RC version the port is the same as Influx1
And changes toString for `InfluxPoint`  because some trace logs that logged the point were unuseful without this.
I attach the build addon for more easy testing: …
=> [influxdb] Fixes issue 8798 and 8697 problems storing integer types

bundles/org.openhab.binding.hpprinter/src/main/java/org/openhab/binding/hpprinter/internal/HPPrinterConfiguration.java, bundles/org.openhab.binding.hpprinter/src/main/java/org/openhab/binding/hpprinter/internal/HPPrinterDiscoveryParticipant.java, bundles/org.openhab.binding.hpprinter/src/main/java/org/openhab/binding/hpprinter/internal/api/HPProperties.java, bundles/org.openhab.binding.hpprinter/src/main/resources/OH-INF/thing/thing-printer.xml
Changed the `representation property` from `serialNumber` to `uuid` to eliminate auto discovery duplicates.
Background: the `serialNumber` property, although discovered in the Bridge manual creation process, is not discovered in the mDNS auto- discovery process. Whereas, on the other hand, `uuid` is discovered in both processes.
=> [hpprinter] eliminate auto discovery duplicates

bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/action/EcobeeActions.java
Applying 3.0 fix to 2.5.x
Fixed an issue when the hold time is not properly handled when setting a temperature hold for a defined number of hours.
=> [ecobee] Fixed setHold action when using holdHours

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoDevices.java, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoBasicHandler.java
Delay refresh after command is send as some devices are not ready yet
with the execution and will report wrong status.
This is confusing to the users.
Related forum topic:
https://community.openhab.org/t/xiaomi-mi-air-purifier-xiaomi-mi-io/34840/300
=> [miio] delay refresh to avoid devices not ready yet

bundles/org.openhab.binding.icalendar/src/main/java/org/openhab/binding/icalendar/internal/handler/PullJob.java
Fixes #8846 by just adding a human readable description of the exception and moves details into debug log.
Just a small change.
=> [icalendar] Describe download exceptions a bit more detailed.

bundles/org.openhab.binding.mpd/src/main/java/org/openhab/binding/mpd/internal/protocol/MPDConnection.java
Details of the issue are described here #8817
This PR update current song on player events (song changes). 
Original log in issue, updated log below showing current song is requested on player change events:
```
2020-10-20 23:33:35.853 [TRACE] [nternal.protocol.MPDConnectionThread] - received line 'changed: player'
2020-10-20 23:33:35.853 [TRACE] [nternal.protocol.MPDConnectionThread] - received line 'OK'
2020-10-20 23:33:35.854 [DEBUG] [nternal.protocol.MPDConnectionThread] - insert command 'status' at position -1
2020-10-20 23:33:35.854 [DEBUG] [nternal.protocol.MPDConnectionThread] - insert command 'currentsong' at position -1
2020-10-20 23:33:35.854 [TRACE] [nternal.protocol.MPDConnectionThread] - send command 'status'
2020-10-20 23:33:35.854 [TRACE] …
```
=> [MPD] Fix MPD not updating current song on player events

bundles/org.openhab.persistence.mapdb/src/main/java/org/openhab/persistence/mapdb/internal/MapDbPersistenceService.java, bundles/org.openhab.persistence.mapdb/src/main/java/org/openhab/persistence/mapdb/internal/StateTypeAdapter.java, bundles/org.openhab.persistence.mapdb/src/test/java/org/openhab/persistence/mapdb/StateTypeAdapterTest.java
* Fix index out of bounds when persisting empty StringType values
* Fix deserialization when strings contain type separator
* Improve debug logging
* Improve test coverage
Fixes #8790
=> [mapdb] Fixes and improvements

bundles/org.openhab.binding.gpstracker/README.md
The app is not available in the PlayStore anymore, see https://github.com/mendhak/gpslogger/issues/849
=> [gpstracker] Updated download url

bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/SnmpTargetHandler.java, bundles/org.openhab.binding.snmp/src/test/java/org/openhab/binding/snmp/internal/AbstractSnmpTargetHandlerTest.java, bundles/org.openhab.binding.snmp/src/test/java/org/openhab/binding/snmp/internal/SnmpTargetHandlerTest.java, bundles/org.openhab.binding.snmp/src/test/java/org/openhab/binding/snmp/internal/StringChannelTest.java, bundles/org.openhab.binding.snmp/src/test/java/org/openhab/binding/snmp/internal/SwitchChannelTest.java
Otherwise it will toggles between online and offline when the call always times-out, which can happen when the device is unreachable (or a wrong ip address configured).
=> [snmp] Set thing only online on valid response

bundles/org.openhab.binding.intesis/README.md, bundles/org.openhab.binding.intesis/src/main/java/org/openhab/binding/intesis/internal/handler/IntesisBoxHandler.java, bundles/org.openhab.binding.intesis/src/main/resources/OH-INF/thing/thing-types.xml
The newly introduced channels "errorStatus" and errorCode" did not receive updates, as the had still been populated as properties.
The "readOnly" pattern was also missing and has been added.
Missing examples have been added to the readme as well.
=> [intesis] [Bug] Fixed error channels not being updated

bundles/org.openhab.binding.tankerkoenig/src/main/resources/OH-INF/thing/webservice.xml
- Set context 'password' for API-Key configuration
=> [tankerkoenig] Set context 'password' for API-Key configuration

bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java
The persistence service will now use the defined unit of Number items with dimensions (which is derived from the unit given in its state description or - if not set - from the defaults of the used measurement system) for both writing and reading values from the database.
Fixes #8809
Fixes #8856
=> [rrd4j] Correctly identify Number items with dimensions and persist them in the defined unit

bundles/org.openhab.persistence.jdbc/pom.xml, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcBaseDAO.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcConfiguration.java
- Fixed ClassCastException
- Update mariadb-java-client to version 1.4.6 (according to README this version is tested)
Closes #8839
=> [jdbc] Fixed ClassCastException; Update mariadb-java-client to version 1.4.6

bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/AVMFritzTlsTrustManagerProvider.java, bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/SamsungTvTlsTrustManagerProvider.java
Changed references from TrustAllTrustMananger to TrustAllTrustManager to reflect openhab-core PR 1773
=> Fixed typo in class name TrustAllTrustMananger

bundles/org.openhab.binding.tado/README.md, bundles/org.openhab.binding.tado/pom.xml, bundles/org.openhab.binding.tado/src/main/api/pom.xml, bundles/org.openhab.binding.tado/src/main/api/tado-api.yaml, bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/internal/TadoBindingConstants.java, bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/internal/handler/TadoHomeHandler.java, bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/internal/handler/TadoZoneHandler.java, bundles/org.openhab.binding.tado/src/main/resources/OH-INF/thing/thing-types.xml
[tado] Add channel for PresenceState and support setting HOME/AWAY
This PR adds the support for reading the Tado Home Presence State (HOME/AWAY) and adds support for changing the HOME/AWAY state through OpenHAB.
Closes #8826 
Rebase of #8854 onto main branch.
@wborn I'm not the original author of this bundle. Therefore, I'm not sure how to get the additional api-client artifact to be built. Also I'm not a Maven expert... The pom.xml is in the `src/main/api` dir and I could only test the new bundle version when manually compiling the api. Can you push it to the openhab maven repo?
=> [tado] Add channel for PresenceState and support setting HOME/AWAY

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoAbstractHandler.java
=> [miio] Fix handling commands with curly brackets

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoAbstractHandler.java
=> [miio] Fix handling commands with curly brackets (#8897)

itests/org.openhab.binding.modbus.tests/src/main/java/org/openhab/binding/modbus/tests/ModbusDataHandlerTest.java
Reverts openhab/openhab-addons#8884
Closes #8880 (see https://github.com/openhab/openhab-core/pull/1774)
=> Revert "[modbus] Disable failing test"

bundles/org.openhab.binding.bluetooth.bluegiga/src/main/java/org/openhab/binding/bluetooth/bluegiga/BlueGigaBluetoothDevice.java, bundles/org.openhab.binding.bluetooth.bluegiga/src/main/java/org/openhab/binding/bluetooth/bluegiga/handler/BlueGigaBridgeHandler.java
During testing I noticed that I couldn't get any bluetooth devices to appear in the inbox during a manual scan through my BlueGiga dongle. Turns out the bluegiga bridge wasn't using the AbstractBluetoothBridgeHandler's device cache.
=> [bluetooth.bluegiga] Fix broken device discovery

bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/ChannelState.java
Generic things would not resubscribe to a a new connection.
see https://github.com/openhab/openhab-addons/issues/6243#issuecomment-719887436
I still see a problem as the changed stateTopic is not seen in the thing. It subscribes to the old value again :-(
=> [mqtt.generic] Fix re-subscribing on new connection

bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jItem.java, bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java
The call of `getUnit()` on a NumberItem is very expensive as it scans all StateDescriptionProviders.
With this PR, this call is only done once and not for every record in the query result set.
This builds on top of the work in https://github.com/openhab/openhab-addons/pull/8929 and completes it without introducing the regression of #8809.
Fixes #8928
=> [rrd4j] Return QuantityTypes for number items with dimension

bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/util/LifxSelectorUtil.java
* Properly handle datagrams that are not immediately available so no NPEs are logged on debug
* Properly handle sockets channels that are not connected so no NPEs are logged on debug
* Prevent load/garbage by reusing ByteBuffer and not allocating trace logging strings
Fixes #8932
=> [lifx] Improve selector logic

bundles/org.openhab.binding.weathercompany/src/main/java/org/openhab/binding/weathercompany/internal/handler/WeatherCompanyAbstractHandler.java
The Weather Company API returns the wind speed in meters/sec not kilometers/hour. This fixes the state update to use the correct units.
=> [weathercompany] Fix wind speed units

bundles/org.openhab.binding.tankerkoenig/src/main/java/org/openhab/binding/tankerkoenig/internal/handler/StationHandler.java, bundles/org.openhab.binding.tankerkoenig/src/main/java/org/openhab/binding/tankerkoenig/internal/handler/WebserviceHandler.java
Fixes #8876 
Fixes the problem caused by stations reporting "null" instead of "false"
Fixed faulty parsing of opening times in case of daily times ("täglich").
=> [Tankerkoenig] Fixes #8876

CODEOWNERS, bom/openhab-addons/pom.xml, bundles/org.openhab.binding.wled/NOTICE, bundles/org.openhab.binding.wled/README.md, bundles/org.openhab.binding.wled/pom.xml, bundles/org.openhab.binding.wled/src/main/feature/feature.xml, bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/WLedActions.java, bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/WLedBindingConstants.java, bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/WLedConfiguration.java, bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/WLedDiscoveryService.java, bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/WLedHandler.java, bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/WLedHandlerFactory.java, bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/WLedHelper.java, bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/WledDynamicStateDescriptionProvider.java, bundles/org.openhab.binding.wled/src/main/resources/OH-INF/binding/binding.xml, bundles/org.openhab.binding.wled/src/main/resources/OH-INF/thing/thing-types.xml, bundles/pom.xml
This new openHAB binding allows you to auto discover (using mDNS) and control LED strings based on the opensource WLED project:
https://github.com/Aircoookie/WLED
It uses a Jetty HttpClientFactory instance and needs no dependencies and a number of users are reporting the 2.5.9 version is working here on the forum:
https://community.openhab.org/t/wled-a-binding-for-controlling-led-strips-and-strings-from-an-opensource-esp8266-project/87286
Precompiled jar for 2.5.9
https://github.com/Skinah/wled/releases/download/2020-10-05/wled-2.5.9.zip
Precompiled jar for 3.0.0
http://www.pcmus.com/openhab/wled/org.openhab.binding.wled-3.0.0-SNAPSHOT.zip
=> [WLed]  Initial contribution - Binding for LED strings with a large range of built in FX.

bundles/org.openhab.binding.deconz/README.md, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/discovery/ThingDiscoveryService.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/DeconzBaseThingHandler.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/GroupThingHandler.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/LightThingHandler.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/SensorBaseThingHandler.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/SensorThermostatThingHandler.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/SensorThingHandler.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/ThingConfig.java, bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/config/config.xml
Finally fixes the lastSeenPolling feature (used to update the thing on each poll cycle). Also fixes compiler warnings.
=> [deconz] fix lastSeenPolling and compile warnings

bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/BindingConstants.java
Don't know why this has not been discovered. There is a test that fails if the factor is wrong.
=> [deconz] fix brightness factor

bom/openhab-addons/pom.xml
Binding is missing from addons-bom
=> [touchwand] add to BOM

bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/BeaconBluetoothHandler.java
This fixes a major bug in the current bluetooth binding that prevents the initialization of bluetooth handlers for existing bluetooth things.
=> [bluetooth] Fix duplicate channel bug

bundles/org.openhab.binding.telegram/README.md, bundles/org.openhab.binding.telegram/pom.xml, bundles/org.openhab.binding.telegram/src/main/java/org/openhab/binding/telegram/internal/TelegramBindingConstants.java, bundles/org.openhab.binding.telegram/src/main/java/org/openhab/binding/telegram/internal/TelegramHandler.java, bundles/org.openhab.binding.telegram/src/main/java/org/openhab/binding/telegram/internal/action/TelegramActions.java
Closed #7971 
+ Improvement: Add support for sendVideo and sendAnimation so you can now send GIF and MP4 recordings.
+ Improvement: Increase the 2MB limit to now allow 10MB jpg files as per the API's limit.
+ Refactor: Remove the use of org.apache.commons.io.IOUtils and instead use a Java 9 method.
+ Improvement: Add support for absolute paths and not just file:// URLs
Precompiled jar for testing under openHAB 3 is here:
http://www.pcmus.com/openhab/telegramBinding/org.openhab.binding.telegram-3.0.0-SNAPSHOT.zip
Inside a rule I test using this:
```
getActions("telegram", "telegram:telegramBot:MyBot").sendTelegramVideo(1111111111, "http://192.168.1.2:54321/ipcamera.mp4", "Video from Doorbell camera")
```
=> [telegram] Add support for sendVideo (MP4) and sendAnimation (GIF)

bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewHubHandler.java
The JAX_RS client was being instantiated in the handler as a class static final field; which would cause OH to crash (see [ISSUE 8881](https://github.com/openhab/openhab-addons/issues/8881)). It is now instantiated dynamically in the handler's `initialize()` method.
=> [hdpowerview] deferred instantiation of JAX-RS client

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoBasicHandler.java, bundles/org.openhab.binding.miio/src/main/resources/OH-INF/thing/commonChannels.xml
To prevent channels not showing up in OH3 main UI
https://github.com/openhab/openhab-webui/issues/406
=> [miio] Use generic channeltypes if none provided

bundles/org.openhab.binding.neeo/src/main/java/org/openhab/binding/neeo/internal/NeeoBrainApi.java, bundles/org.openhab.binding.neeo/src/main/java/org/openhab/binding/neeo/internal/handler/NeeoBrainHandler.java, bundles/org.openhab.binding.neeo/src/main/java/org/openhab/binding/neeo/internal/handler/NeeoForwardActionsServlet.java, bundles/org.openhab.binding.neeo/src/main/java/org/openhab/binding/neeo/internal/handler/NeeoHandlerFactory.java, bundles/org.openhab.binding.neeo/src/main/java/org/openhab/binding/neeo/internal/net/HttpRequest.java, bundles/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/NeeoService.java, bundles/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/internal/NeeoApi.java, bundles/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/internal/NeeoBrainServlet.java, bundles/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/internal/NeeoDeviceKeys.java, bundles/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/internal/discovery/MdnsBrainDiscovery.java, bundles/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/internal/net/HttpRequest.java, bundles/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/internal/servletservices/NeeoBrainService.java
=> [neeo] fix ClassNotFoundException and switch to constructor injection

bundles/org.openhab.binding.remoteopenhab/src/main/resources/OH-INF/thing/thing-types.xml
=> [remoteopenhab] Deprecated tag "required" for configuration parameter

bundles/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/PlugwiseBindingConstants.java, bundles/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/PlugwiseHandlerFactory.java, bundles/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/PlugwiseThingDiscoveryService.java, bundles/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/PlugwiseUtils.java, bundles/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/handler/PlugwiseRelayDeviceHandler.java, bundles/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/handler/PlugwiseStickHandler.java
This simplifies the PlugwiseHandlerFactory code so it no longer needs to register and keep track of a discovery service for each bridge.
Also contains a few other improvements:
* fix lastRequest timestamp not updated when sending messages to discover node properties
* use java.time Duration and Instant
* use List.of, Set.of
* remove redundant null suppression because of EEAs
=> [plugwise] Use ThingHandlerService for discovery

bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/AVMFritzBaseBridgeHandler.java, bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/AVMFritzBaseThingHandler.java, bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/Powerline546EHandler.java
- Avoid a hidden NPE when `getIdentifier()` of an uninitialized `ThingHandler` is called
=> [avmfritz] Avoid a hidden NPE when getIdentifier() of an uninitialized ThingHandler is called

bundles/org.openhab.binding.enocean/src/main/resources/OH-INF/thing/channels.xml
Fixes #9046 
`humidity` calculates the state via `new DecimalType(value*100.0/250.0)` which oviously is a floating point number.
=> [enocean] fix wrong formatting in state description

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoBasicHandler.java
* [miio] send miot actions parameter as jsonObject
* [miio] avoid maven error
Backport - cherryp icked from OH3
=> [miio] send miot actions parameter as jsonObject (#9056)

bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/discovery/MieleMDNSDiscoveryParticipant.java
This fixes the warning in the log:
```
17:12:56.365 [WARN ] [nfig.discovery.DiscoveryResultBuilder] - Representation property 'Miele_XGW3000' of discovery result for thing 'miele:xgw3000:Miele_XGW3000' is missing in properties map. It has to be fixed by the bindings developer.
```
=> [miele] Fixed declaration of representation property

bundles/org.openhab.binding.homematic/README.md
https://community.openhab.org/t/solved-homematic-channel-type-couldn-t-be-resolved/47950/6 shows the solution with UPPERCASE channel name and fixing a typo in this paragraph.
Signed-off-by: Philip Reimann <github@qimp.org>
=> [homematic] Docs on channel types: UPPERCASE and typo

bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/protocol/IntRSModule.java, bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/protocol/SatelModule.java
This PR fixes communication problems when using INT-RS bridge.
Issue is described here: https://community.openhab.org/t/satel-binding-support-announcements-and-feature-requests/56135/234
After several disconnections one of the binding threads hangs and communistion is stopped. The main change is to rely on receive timeout that can be setup for serial port instead of thread based watchdog.
=> [satel] Fixes for INT-RS module

bundles/org.openhab.persistence.rrd4j/README.md, bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java
Fixes #9013
Add support for storing the brightness component of a Color item which used to work with OH 2.5.
Also add support for storing the state of a Group item.
=> [rrd4j] Support Colour item and Group item with a state

bundles/org.openhab.binding.openwebnet/README.md, bundles/org.openhab.binding.openwebnet/pom.xml, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/handler/OpenWebNetAutomationHandler.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/handler/OpenWebNetBridgeHandler.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/handler/OpenWebNetThingHandler.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/discovery/OpenWebNetDeviceDiscoveryService.java, bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusAutomation.xml, bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusDimmer.xml, bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusOnOffSwitch.xml, bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/GenericDevice.xml, bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/ZBAutomation.xml, bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/ZBDimmer.xml, bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/ZBOnOffSwitch.xml, bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/ZBOnOffSwitch2Units.xml, bundles/org.openhab.binding.openwebnet/src/test/java/org/openhab/binding/openwebnet/handler/OwnIdTest.java
For [openwebnet] binding: fixed config, discovery and handling of ZigBee devices and USB gateway (fixes #8915, fixes #8917, fixes #8962). Improved handling of wrong 'where' parameter. Improved discoveryByActivation to distinguish dimmers from lights. Updated README. Improved logging. Added test for ownID calculation. Now uses openwebnet4j lib v0.3.2-1.
**BREAKING CHANGE**
Configuration for OpenWebNet ZigBee devices has changed, see the binding README for the current configuration of the 'where' parameter for Zigbee (radio) devices and examples. Existing things configuration should be updated.
**NOTE** This PR should be backported to branch 2.5.x to be included in next release (2.5.11)
=> [openwebnet] Fixed handling of ZigBee USB gateway and devices (fixes #8915 #8917 #8962)

bundles/org.openhab.binding.modbus/DEVELOPERS.md, bundles/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/handler/BaseModbusThingHandler.java
The bindings extending the modbus binding have some redundant code in their handlers. In particular:
- Retrieve the ModbusCommunicationInterface
- Check if a parent bridge is configured
- Check if the parent bridge is a modbus bridge
- Check if the ModbusCommunicationInterface is not null
- Take care that each regular poller is unregistered when the handler is disposed
- Take care that each one time poller is cancelled when the handler is disposed
The abstract class introduced in this PR handles the above points. It would reduce complexity in the extending bindings of dozens of lines. An example of how simple a handler could become, can be found in [this](https://github.com/fwolter/openhab-addons/blob/sbc/bundles/org.openhab.binding.modbus.sbc/src/main/java/org/openhab/binding/modbus/sbc/i …
=> [modbus] Add convenience class for ThingHandlers

bundles/org.openhab.binding.bluetooth.generic/src/main/java/org/openhab/binding/bluetooth/generic/internal/GenericBluetoothHandler.java
=> [bluetooth.generic] Fix build

bundles/org.openhab.binding.ecobee/README.md, bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/api/EcobeeApi.java, bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/api/EcobeeAuth.java
On 1 December 2020, Ecobee will make changes to their authorization process. Users who authorized the binding prior to December 1 will continue to work using the old process, however, Ecobee recommends that users reauthorize using the new process. In addition, any new installations of the binding after 1 Dec will use the new process.
The changes included in this PR support the new process, as well as include several small fixes that will help ensure the reauthorization process runs smoothly.
Also related to #9039
A similar set of changes will be pushed for 2.5.x.
=> [ecobee] Updates in prep for Dec 1 changes to Ecobee authorization process

bundles/org.openhab.binding.ecobee/README.md, bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/api/EcobeeApi.java, bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/api/EcobeeAuth.java
I was hoping to get the 3.0 PR merged before submitting this, but it's getting too close to the December 1 deadline.
Related to #9065
On 1 December 2020, Ecobee will make changes to their authorization process. Users who authorized the binding prior to December 1 will continue to work using the old process, however, Ecobee recommends that users reauthorize using the new process. In addition, any new installations of the binding after 1 Dec will use the new process.
The changes included in this PR support the new process, as well as include several small fixes that will help ensure the reauthorization process runs smoothly.
Also related to #9039
Also includes changes from #8857
=> [ecobee] Changes for Dec 1 Ecobee auth changes (2.5.x)

bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/handler/FroniusSymoInverterHandler.java
Fix https://github.com/openhab/openhab-addons/issues/9053
Backporting PR https://github.com/openhab/openhab-addons/pull/9077 to 2.5.x branch
=> [fronius] Accept null value as zero for inverterdatachannelpac channel (backported to 2.5.x)

bundles/org.openhab.binding.caddx/src/test/java/org/openhab/binding/caddx/internal/CaddxMessageReaderUtil.java
Small change on a test class for correctly closing streams and readers in case of an exception.
Requested by @fwolter in #9070
=> [caddx] Corrected try with resources on a test class

bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/HueEmulationService.java
Revert the change made by #8615 which prevents the Hue Emulation service from starting.
=> [hueemulation] Fix to make sure the service starts

bundles/org.openhab.binding.nikobus/src/main/java/org/openhab/binding/nikobus/internal/handler/NikobusModuleHandler.java, bundles/org.openhab.binding.nikobus/src/main/java/org/openhab/binding/nikobus/internal/handler/NikobusPushButtonHandler.java, bundles/org.openhab.binding.nikobus/src/main/java/org/openhab/binding/nikobus/internal/utils/CRCUtil.java, bundles/org.openhab.binding.nikobus/src/main/java/org/openhab/binding/nikobus/internal/utils/Utils.java, bundles/org.openhab.binding.nikobus/src/main/resources/OH-INF/thing/thing-types.xml
* fixed refresh handing due `channelLinked` not called anymore on startup for example (similar to https://github.com/openhab/openhab-core/issues/1707),
* "Impacted Modules" can be empty if button is configured as "standalone" and does not impact modules,
* minor doc fix
=> [nikobus] fixed refresh handling

bundles/org.openhab.binding.openwebnet/README.md, bundles/org.openhab.binding.openwebnet/pom.xml, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/handler/OpenWebNetAutomationHandler.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/handler/OpenWebNetBridgeHandler.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/handler/OpenWebNetThingHandler.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/discovery/BusGatewayUpnpDiscovery.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/discovery/OpenWebNetDeviceDiscoveryService.java, bundles/org.openhab.binding.openwebnet/src/main/resources/ESH-INF/thing/BusAutomation.xml, bundles/org.openhab.binding.openwebnet/src/main/resources/ESH-INF/thing/BusDimmer.xml, bundles/org.openhab.binding.openwebnet/src/main/resources/ESH-INF/thing/BusOnOffSwitch.xml, bundles/org.openhab.binding.openwebnet/src/main/resources/ESH-INF/thing/GenericDevice.xml, bundles/org.openhab.binding.openwebnet/src/main/resources/ESH-INF/thing/ZBAutomation.xml, bundles/org.openhab.binding.openwebnet/src/main/resources/ESH-INF/thing/ZBDimmer.xml, bundles/org.openhab.binding.openwebnet/src/main/resources/ESH-INF/thing/ZBOnOffSwitch.xml, bundles/org.openhab.binding.openwebnet/src/main/resources/ESH-INF/thing/ZBOnOffSwitch2Units.xml, bundles/org.openhab.binding.openwebnet/src/test/java/org/openhab/binding/openwebnet/handler/OwnIdTest.java
**BREAKING CHANGE** Configuration for OpenWebNet ZigBee devices has changed, see the binding README for the current configuration of the 'where' parameter for Zigbee (radio) devices and examples. Existing things configuration should be updated.
---
This PR is a backport of main-#9076 (already merged) to 2.5.x.
* [openwebnet] Fixed config, handling and discovery of ZigBee devices (fixes #8915 and fixes #8917). Added test for ownID. Now uses openwebnet4j v0.3.2
* [openwebnet] ZigBee: improved handling of wrong 'where' parameter. Updated README. Improved logging.
* [openwebnet] Improved discoveryByActivation to distinguish dimmers from lights. Now using openwebnet4j 0.3.2-1
=> [openwebnet] Fixed handling of ZigBee USB gateway and devices (fixes #8915 #8917 #8962) (2.5.x)

bundles/org.openhab.binding.bluetooth.bluez/src/main/java/org/openhab/binding/bluetooth/bluez/internal/BlueZBluetoothDevice.java, bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/ConnectedBluetoothHandler.java
The block removed was causing the unpairing of all devices when the binding was disposed (shutdown, reload...).
Signed-off-by: Benjamin Lafois <benjamin.lafois@gmail.com>
=> [bluetooth.bluez] Fix the unpairing of all devices on binding disposal

bundles/org.openhab.io.hueemulation/README.md, bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/ConfigStore.java, bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/HueEmulationService.java, bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/upnp/HueEmulationConfigWithRuntime.java, bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/upnp/UpnpServer.java, bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/rest/ItemUIDtoHueIDMappingTests.java, bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/upnp/UpnpTests.java
Fixes #9147
Enabling pairing would stop the UPNP server until paring was automatically disabled, Alexa would refuse to talk to OH without the UPNP server running and would not start the pairing process.
Alexa requests an API key using the `/api` URL, OH needs to receive `/api/` or else it responds with a 302. Updated the documentation to use a reverse proxy to workaround this.
Alexa no longer seems to like the large `uniqueid` which was previously generated and would fail to discover any devices, this has now been changed to follow the Hue API example.
Tested with Alexa, Logitech Harmony and Hue Control Android app.
=> [hueemulation] Changes to fix pairing and device discovery with Alexa

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoBasicHandler.java
With introduction of miot devices with enormous amount of channels
refreshes can become slow. With this change only relevant updates are
done.
=> [miio] Update channels only if they are linked

CODEOWNERS, bom/openhab-addons/pom.xml, bundles/org.openhab.binding.pushover/NOTICE, bundles/org.openhab.binding.pushover/README.md, bundles/org.openhab.binding.pushover/pom.xml, bundles/org.openhab.binding.pushover/src/main/feature/feature.xml, bundles/org.openhab.binding.pushover/src/main/java/org/openhab/binding/pushover/internal/PushoverBindingConstants.java, bundles/org.openhab.binding.pushover/src/main/java/org/openhab/binding/pushover/internal/actions/PushoverActions.java, bundles/org.openhab.binding.pushover/src/main/java/org/openhab/binding/pushover/internal/config/PushoverAccountConfiguration.java, bundles/org.openhab.binding.pushover/src/main/java/org/openhab/binding/pushover/internal/config/PushoverConfigOptionProvider.java, bundles/org.openhab.binding.pushover/src/main/java/org/openhab/binding/pushover/internal/connection/PushoverAPIConnection.java, bundles/org.openhab.binding.pushover/src/main/java/org/openhab/binding/pushover/internal/connection/PushoverCommunicationException.java, bundles/org.openhab.binding.pushover/src/main/java/org/openhab/binding/pushover/internal/connection/PushoverConfigurationException.java, bundles/org.openhab.binding.pushover/src/main/java/org/openhab/binding/pushover/internal/connection/PushoverMessageBuilder.java, bundles/org.openhab.binding.pushover/src/main/java/org/openhab/binding/pushover/internal/dto/Sound.java, bundles/org.openhab.binding.pushover/src/main/java/org/openhab/binding/pushover/internal/factory/PushoverHandlerFactory.java, bundles/org.openhab.binding.pushover/src/main/java/org/openhab/binding/pushover/internal/handler/PushoverAccountHandler.java, bundles/org.openhab.binding.pushover/src/main/resources/OH-INF/binding/binding.xml, bundles/org.openhab.binding.pushover/src/main/resources/OH-INF/config/config.xml, bundles/org.openhab.binding.pushover/src/main/resources/OH-INF/i18n/pushover.properties, bundles/org.openhab.binding.pushover/src/main/resources/OH-INF/i18n/pushover_de.properties, bundles/org.openhab.binding.pushover/src/main/resources/OH-INF/thing/thing-types.xml, bundles/org.openhab.binding.pushover/src/test/java/org/openhab/binding/pushover/internal/actions/PushoverActionsTest.java, bundles/pom.xml
- Migration of Pushover action to OH3 binding
Replaces #6798
=> [pushover] Migration of Pushover OH1 action to OH3 binding

bundles/org.openhab.binding.squeezebox/README.md
I kept searching for "Logitech" in PaperUI but couldn't find it. Until I saw that it's actually called "Squeezebox Binding"
=> [squeezebox] Match the name of the binding with the name it has in the UI

bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/callmonitor/CallMonitor.java
=> [avmfritz] Properly interrupt monitor thread upon dispose

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoBasicHandler.java
* [miio] Update channels only if they are linked
With introduction of miot devices with enormous amount of channels
refreshes can become slow. With this change only relevant updates are
done.
backport from OH3
=> [miio] Update channels only if they are linked (#9163)

bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/handler/CircuitHandler.java
=> [digitalstrom] fix ClassCastException

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoQuantiyTypes.java, bundles/org.openhab.binding.miio/src/test/java/org/openhab/binding/miio/internal/MiIoQuantityTypesTest.java
* Improved way avoiding multiple entries for Unit
* Test cases for the MiIoQuantityTypes class
=> [miio] Implement alternative MiIoQuantityTypes

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoHandlerFactory.java, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/BasicChannelTypeProvider.java, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/MiIoBasicChannel.java, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/OptionsValueListDTO.java, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/StateDescriptionDTO.java, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoBasicHandler.java
- Simplify the json database creation for new models and less chance for errors 
- Drive statedescription from Json
- drive options from Json 
Related to #7276
=> [miio] dynamically generate channelTypes

bundles/org.openhab.binding.amazonechocontrol/README.md
Fixes #8590 
State in the documentation that redirect/refresh issues during login are solved by enabling 2FA.
=> [amazonechocontrol] improve documentation

bundles/org.openhab.binding.bluetooth.bluez/README.md
@cpmeister According to your statement here https://github.com/openhab/openhab-addons/pull/9223#discussion_r536371591, this hint from the docs should be obsolete, correct? With which version of Bluez did you test?
=> [bluetooth.bluez] Remove tinyB reference from BlueZ Binding docs

bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/discovery/DiscoveryServiceManager.java
Related to #9048 
This Bugfix catches any exception that could occurs when a device is added. 
I hesitate with specifically checking for the string length and silently ignore if the hardware info is not here, but I think it's best to log an error when something is wrong on digitalstrom side. This log could help us identify the root cause.
This try and catch will also avoid that the module crashes on open hab side.
=> [digitalstrom] fixes StringIndexOutOfBoundsException

bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/LcnModuleActions.java, bundles/org.openhab.binding.lcn/src/test/java/org/openhab/binding/lcn/internal/ModuleActionsTest.java
Some LCN-GTxD don't display the text if it fits exactly in one chunk (12 bytes). Observed with GT10D 8.0.
Closes #9208
=> [lcn] add workaround for dynamic text firmware bug

bundles/org.openhab.binding.icalendar/src/main/java/org/openhab/binding/icalendar/internal/handler/EventFilterHandler.java, bundles/org.openhab.binding.icalendar/src/main/java/org/openhab/binding/icalendar/internal/handler/ICalendarHandler.java
Should fix #9029. The channels do not get updated as the known channels by the binding where only updated if Bridge was already online while initializing EventFilterHandler. Even if it does not fix the issue, the race condition is is fixed.
Also added a bit more output.
Signed-off-by: Michael Wodniok <michi@noorganization.org>
=> [icalendar] Fix race condition while initialization of EventFilterHandler

bundles/org.openhab.binding.tr064/README.md, bundles/org.openhab.binding.tr064/src/main/resources/channels.xml
Fixes #9173 
DSL Fritzboxes use different service-names on the same device for external ip, uptime and connectionstatus.
=> [tr064] Add support for PPP connections

bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/Connection.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/smarthome/Constants.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/smarthome/HandlerThermostatController.java
=> [amazonechocontrol] HandlerThermostatController

bundles/org.openhab.binding.bticinosmarther/src/main/java/org/openhab/binding/bticinosmarther/internal/api/dto/Measure.java, bundles/org.openhab.binding.coronastats/src/main/java/org/openhab/binding/coronastats/internal/dto/CoronaStatsCases.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/NumberValue.java, bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/PercentageValue.java, bundles/org.openhab.binding.neohub/src/main/java/org/openhab/binding/neohub/internal/NeoHubHandler.java, bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/handler/OpenSprinklerStationHandler.java, bundles/org.openhab.binding.sensibo/src/main/java/org/openhab/binding/sensibo/internal/handler/SensiboSkyHandler.java, bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyHttpApi.java, bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/coap/ShellyCoIoTVersion1.java, bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyComponents.java, bundles/org.openhab.binding.siemensrds/src/main/java/org/openhab/binding/siemensrds/points/BasePoint.java, bundles/org.openhab.binding.siemensrds/src/test/java/org/openhab/binding/siemensrds/test/RdsTestData.java, bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/TeslaChannelSelectorProxy.java, tools/static-code-analysis/checkstyle/ruleset.properties
Add-ons should not depend on `tec.uom.se` classes but use core unit classes instead so they are less impacted when this library is replaced or upgraded.
* Fixes many occurences (but not all)
* Adds `tec.uom.se` to the forbidden packages
See : https://github.com/openhab/openhab-core/issues/1589#issuecomment-739491526
=> Use core unit classes

bundles/org.openhab.binding.comfoair/README.md
As the ComfoairControl item changed from Number to Switch in the new binding also the sitemap mapping should OFF=CC and ON=APP instead of 0 and 1. I found this out today when running some tests together with Hans Boehm.
Refer to: https://community.openhab.org/t/comfoair-new-comfoair-binding/92891/81
=> [comfoair] Update README.md to refelect recent change.

bundles/org.openhab.binding.powermax/README.md
Added some comments on how to enable bypass switching
=> [powermax] Update README.md

bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/AmcrestHandler.java, bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/DahuaHandler.java, bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/DoorBirdHandler.java, bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/Ffmpeg.java, bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/FoscamHandler.java, bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/HikvisionHandler.java, bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/InstarHandler.java, bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/IpCameraDiscoveryService.java, bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/handler/IpCameraHandler.java, bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/onvif/OnvifDiscovery.java, bundles/org.openhab.binding.ipcamera/src/main/resources/OH-INF/thing/thing-types.xml
Closed #9167
Closed #9023
Closed #9022
This PR changes the following:
- Fix Offline detection. Would not detect the camera was offline when not polling a snapshot.
- Improve ONVIF discovery. Now scans on all NICs instead of only the first interface the binding would find.
- Fix motion alarm FFmpeg options. Config was not working correctly if the user supplied options was '-vf xxxxxx' due to binding already providing this argument already.
- Improve log by removing password from logged FFmpeg commands.
- Refactor some code to make it slightly faster and consistent between similar classes.
=> [ipcamera] Improve ONVIF discovery and bug fixes.

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoBindingConstants.java, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoBasicHandler.java
This ensures channels are removed if you switch between various models, while preserving the standard channels available to all models
=> [miio] channels removal

bundles/org.openhab.binding.fronius/src/main/resources/OH-INF/thing/bridge.xml
`hostname`  can't be configured with `groupName` set (probably due to missing parameter group definition). There is no benefit in adding parameter groups anyway if there is only one paramaeter.
=> [fronius] fix thing definition

bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/Connection.java
Failed command should be logged as WARN since they either result from coding errors or a blocked account. In both cases user interaction is required.
Also reduces to one log-line per error which is favorbale on high-load-machines.
=> [amazonechocontrol] improve logging

bundles/org.openhab.binding.exec/README.md, bundles/org.openhab.binding.exec/src/main/java/org/openhab/binding/exec/internal/handler/ExecHandler.java
After investigating all available information it seems that all issues arise from the fact that
- a non `StringType` command is sent ad this is ignore. (rant:This is an issue of textual configuration, linking an incompatible item type is not possible in UI).
- the item's state is updated instead of sending a command
This PR makes it more clear in the documentation what needs to be done and improves the logging to make the error more obvious.
Closes #2605
=> [exec] improve logging and documentation

bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/handler/BridgeHandler.java, bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/handler/CircuitHandler.java, bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/handler/DeviceHandler.java, bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/handler/SceneHandler.java, bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/handler/ZoneTemperatureControlHandler.java
Fixes #7704
The bridge handler is disposed before the thing is removed. Before disposing the bridge handler all of it's child handlers are diposed, so it's wrong to set the child's thing status to offline on removal of the bridge handler.
=> [digitalstrom] remove unnecessary call to bridgeStatusChanged

bundles/org.openhab.binding.kostalinverter/src/main/resources/OH-INF/thing/Channels.xml
Fixes #8738 
Channels for power should use item-type `Number:Power` instead of `Number:Energy`
=> [kostalinverter] Fix channel item-type definition

bundles/org.openhab.binding.openthermgateway/README.md, bundles/org.openhab.binding.openthermgateway/src/main/java/org/openhab/binding/openthermgateway/OpenThermGatewayBindingConstants.java, bundles/org.openhab.binding.openthermgateway/src/main/java/org/openhab/binding/openthermgateway/handler/OpenThermGatewayHandler.java, bundles/org.openhab.binding.openthermgateway/src/main/java/org/openhab/binding/openthermgateway/internal/CodeType.java, bundles/org.openhab.binding.openthermgateway/src/main/java/org/openhab/binding/openthermgateway/internal/DataItem.java, bundles/org.openhab.binding.openthermgateway/src/main/java/org/openhab/binding/openthermgateway/internal/DataItemGroup.java, bundles/org.openhab.binding.openthermgateway/src/main/java/org/openhab/binding/openthermgateway/internal/Message.java, bundles/org.openhab.binding.openthermgateway/src/main/java/org/openhab/binding/openthermgateway/internal/OpenThermGatewaySocketConnector.java, bundles/org.openhab.binding.openthermgateway/src/main/resources/OH-INF/thing/channels.xml, bundles/org.openhab.binding.openthermgateway/src/main/resources/OH-INF/thing/otgw.xml
Bugfix and improvement for issue reported in #9205.
Goal is to accurately report control setpoint at boiler, and enable access to requested and overridden values to allow intelligent rules to be implemented.
This has been discussed with the initial implementer of this binding @ArjenKorevaar in this community thread https://community.openhab.org/t/opentherm-gateway-binding/39160
Readme has been updated, changes are believed to follow guidelines, no new static analysis issues have been introduced, and work has been signed off.
=> [openthermgateway] Fix for #9205 incorrect control setpoint override

bundles/org.openhab.binding.velux/README.md, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/VeluxBindingConstants.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/handler/ChannelActuatorPosition.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/handler/VeluxBridgeHandler.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/handler/utils/Thing2VeluxActuator.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/things/VeluxExistingProducts.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/things/VeluxProduct.java, bundles/org.openhab.binding.velux/src/main/resources/OH-INF/config/config.xml
Note: these changes have already been tested with @gs4711
The following issues have been resolved..
The binding identifies devices in the bridge by means of a unique id. Normally this is the serial number, but in the case of binding v1 devices or Somfy devices without a serial number, the binding would fall back to use the clear text name. However the fall back unique id code was not consistent across different device configurations / versions.
This issue has been fixed.
When commanding the status of a switch, the OpenHAB values `ON` resp. `OFF` would be sent as `100%` resp. `0%` respectively; but when reading the status the values `100%` resp. `0%` would be mapped inversely to `OFF` and `ON`.
This issue has been fixed.
The ReadMe file has been updated to correct minor errors and improve …
=> [velux] fix bugs with Somfy devices, and switch devices

bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitTaggedItem.java
this PR fixes the issue #9089 
the main reason for the issue is different handling of numbers in meta data created via mainUI and via .items file configuration. MainUI creates values of type Double. .items results in values of type BigDecimal
this issue is reported here https://github.com/openhab/openhab-core/issues/1904
=> [homekit] fix for minValue/maxValue

bundles/org.openhab.binding.bluetooth/src/test/java/org/openhab/binding/bluetooth/util/RetryFutureTest.java
See https://ci.openhab.org/view/Pull%20Request%20Builds/job/PR-openHAB-Addons/org.openhab.addons.bundles$org.openhab.binding.bluetooth/1293/testReport/junit/org.openhab.binding.bluetooth.util/RetryFutureTest/composeWithRetry1Cancel/
=> [bluetooth] Try to make tests more stable No.2

bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/Util.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/discovery/ThingDiscoveryService.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/dto/BridgeFullState.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/DeconzBaseThingHandler.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/DeconzBridgeHandler.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/GroupThingHandler.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/LightThingHandler.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/SensorBaseThingHandler.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/netutils/WebSocketConnection.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/types/ResourceType.java, bundles/org.openhab.binding.deconz/src/test/java/org/openhab/binding/deconz/DeconzTest.java
Fixes #9264 
The reason for the high CPU load with a lot of things is that during binding initialization each thing handler executes a seperate request request to the deconz REST API and runs into timeouts. This refactoring caches the response for 1s which allows faster processing and reduces network load.  
=> [deconz] improve initialization

bundles/org.openhab.binding.nikobus/README.md, bundles/org.openhab.binding.nikobus/src/main/java/org/openhab/binding/nikobus/internal/handler/NikobusPushButtonHandler.java, bundles/org.openhab.binding.nikobus/src/main/java/org/openhab/binding/nikobus/internal/handler/NikobusRollershutterModuleHandler.java, bundles/org.openhab.binding.nikobus/src/main/resources/OH-INF/config/config.xml, bundles/org.openhab.binding.nikobus/src/main/resources/OH-INF/thing/rollershutter-module.xml
Nikobus rollershuter module does not provide information about rollershutter's position - to make this play better in OH, an additional parameter per channel was introduced to allow estimation of rollershutter's position.
Signed-off-by: Boris Krivonog <boris.krivonog@inova.si>
=> [nikobus] rollershutter position estimator added

bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/handler/LGWebOSTVSocket.java
This fix addresses issue: #9000
Volume Change response in API on newer LGWebOS TVs has changed.
It can be encapsulated in volumeStatus element in JSON response. See description on issue.
@shmilgan has successfully validated the fix on new OS.
I have validated legacy api still works with this fix.
Nothing to change for mute channel
Was already discussed on PR #9079, but closed in order to re-request the PR on main branch.
@fwolter please backport it to 2.5.x branch as well
=> [lgwebos] Fix Volume Subscription on newer LGWebOS TVs which report volumeStatus

bundles/org.openhab.binding.deconz/README.md, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/BindingConstants.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/dto/SensorState.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/SensorThermostatThingHandler.java
=> [deconz] support for thermostat windowopen

bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcBaseDAO.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcDerbyDAO.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcPostgresqlDAO.java
The jdbc binding generates a warning in the log for Image and Player item types, but it stores the values in the database as VARCHARs anyway.
This PR adds those items types so that they are stored as they are today, but without the warning.
See discussion [here](https://community.openhab.org/t/jdbc-mysql-persistence-in-oh3/109922/13).
Fixes #2819
=> [jdbc] Add missing item types

bundles/org.openhab.binding.milight/src/main/resources/OH-INF/thing/channels.xml
<category>DimmableLight</category>
The above category does not exist here <https://www.openhab.org/docs/concepts/categories.html> and the new UI does not have this as a valid option to select when creating an item.
=> [milight] Refactor: change category to one that exist

bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/channels.xml
<category>DimmableLight</category>
The above category does not exist here <https://www.openhab.org/docs/concepts/categories.html> and the new UI does not have this as a valid option to select when creating an item.
=> [hue] Refactor: change category to one that exists

bundles/org.openhab.persistence.mapdb/src/main/java/org/openhab/persistence/mapdb/internal/MapDbPersistenceService.java
The only way to recover from an incompatible OH2 database is to create a new database.
With these changes the add-on will create a new database automatically and archive the incompatible database files in a backup directory.
Fixes #8794
---
It will for instance log:
```
21:07:36.351 [WARN ] [apdb.internal.MapDbPersistenceService] - The MapDB in /openhab/userdata/persistence/mapdb/storage.mapdb is incompatible with openHAB 3.0.0: org.openhab.persistence.mapdb.internal.MapDBitemSerializer cannot be found by org.openhab.persistence.mapdb_3.0.0.202012082007. A new and empty MapDB will be used instead.
21:07:36.353 [INFO ] [apdb.internal.MapDbPersistenceService] - Moved incompatible MapDB file '/openhab/userdata/persistence/mapdb/storage.mapdb.p' to …
```
=> [mapdb] Recreate DB when incompatible OH2 DB is used

itests/org.openhab.binding.feed.tests/src/main/java/org/openhab/binding/feed/test/FeedHandlerTest.java
I don't know if this is the solution. The Jenkins logs show a lot of:
```
Components implementing org.osgi.service.http.HttpService:
No component implementing org.osgi.service.http.HttpService is currently registered.
Make sure to add the appropriate bundle and set 'Default Auto-Start=true' in the launch config.
```
=> [feed] Try to make tests more stable

bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/influx2/Influx2FilterCriteriaQueryCreatorImpl.java, bundles/org.openhab.persistence.influxdb/src/main/resources/OH-INF/config/config.xml
Fixes two small issues for the InfluxDB persistence addon that affect only InfluxDB 2.0
Solved issues are:
#9247 Problems with criteria queries without before filter
#8960 Problems with retention policy configuration parameter
=> [influxdb] Fixes issues #9247 and #8960 with InfluxDB 2.0

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/Utils.java, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/MiIoDatabaseWatchService.java, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/cloud/MiCloudConnector.java, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoBasicHandler.java, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/robot/RRMapDraw.java, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/robot/RRMapFileParser.java
eliminating sat warnings and minor improvements in the miloudconnector for failed attempts
=> [miio] Elimate several SAT warnings

bundles/org.openhab.binding.icalendar/src/main/java/org/openhab/binding/icalendar/internal/handler/EventFilterHandler.java, bundles/org.openhab.binding.icalendar/src/main/java/org/openhab/binding/icalendar/internal/handler/ICalendarHandler.java
- Ensure Bridge is initialized and calendar is available to update child Things
Related to #9029 and #9230
=> [icalendar] Ensure Bridge is initialized and calendar is available to update child Things

bom/openhab-addons/pom.xml
This fixes our broken release build: https://ci.openhab.org/view/Sandbox/job/sandbox-openhab3-release/
=> Removed remaining outdated reference to modbus transport bundle

bundles/org.openhab.binding.yioremote/src/main/java/org/openhab/binding/yioremote/internal/YIOremoteDockHandler.java
Signed-off-by: Michael Loercher<michaelloercher@web.de>
Bug fix during websocket error by disposing pollingjob
=> [yioremote] Bug fix during websocket error by disposing pollingjob

bundles/org.openhab.binding.deconz/README.md, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/LightThingHandler.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/ThingConfig.java, bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/config/config.xml, bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/thing/light-thing-types.xml
In some cases auto-detection of the color mode (hsb, xy) is not working properly. This allows to optionally set a fixed color mode.
=> [deconz] fix colorlight not updating color channel

bundles/org.openhab.binding.gardena/README.md
=> [gardena] fix typo in documentation

bundles/org.openhab.binding.enocean/README.md, bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/config/EnOceanChannelTariffInfoConfig.java, bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/A5_12/A5_12.java, bundles/org.openhab.binding.enocean/src/main/resources/OH-INF/thing/AutomatedMeterSensor.xml, bundles/org.openhab.binding.enocean/src/main/resources/OH-INF/thing/channels.xml
* Added new channel parameter tariff to channels instantpower, totalusage, currentFlow, cumulativeValue, counter and currentNumber
* Parameter is currently just read by EEP A5_12, which is used by AutomatedMeterSensor ThingType
* AutomatedMeterSensor ThingType has extensible channels now to support more than one tariff channel
Fixes #9333
=> [enocean] Added tariff info for AutomatedMeterSensor ThingType channels

itests/org.openhab.binding.hue.tests/src/main/java/org/openhab/binding/hue/internal/handler/HueBridgeHandlerOSGiTest.java
See https://ci.openhab.org/job/PR-openHAB-Addons/1415/consoleText
```
TEST org.openhab.binding.hue.internal.handler.HueBridgeHandlerOSGiTest#verifyStatusIfNewUserCannotBeCreated() <<< ERROR: expected: <CONFIGURATION_ERROR> but was: <NONE>
org.opentest4j.AssertionFailedError: expected: <CONFIGURATION_ERROR> but was: <NONE>
at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1124)
at org.openhab.binding.hue.internal.handler.HueBridgeHandlerOSGiTest.verifyStatusIfNewUserCannotBeCreated(HueBr …
```
=> [hue] Try to make tests more stable

CODEOWNERS, bom/openhab-addons/pom.xml, bundles/org.openhab.automation.jythonscripting/NOTICE, bundles/org.openhab.automation.jythonscripting/README.md, bundles/org.openhab.automation.jythonscripting/pom.xml, bundles/org.openhab.automation.jythonscripting/src/main/feature/feature.xml, bundles/org.openhab.automation.jythonscripting/src/main/java/org/openhab/automation/jythonscripting/JythonScriptEngineFactory.java, bundles/org.openhab.automation.jythonscripting/src/main/java/org/openhab/automation/jythonscripting/package-info.java, bundles/pom.xml, pom.xml
Ports #7208 to OH3 and addresses review comments like removing the bnd.bnd file and using an annotation for the dynamic import.
I'm not a Jython expert but some Hello World examples seemed to work in rules so at least something is functional.
Perhaps some seasoned Jython users can further test and improve it?
As expected it is also a pretty big add-on with a size of 42 MB, so it will have a big impact on the add-ons KAR file.
See also https://github.com/openhab/openhab-addons/issues/4801#issuecomment-743980328
=> Add Jython Scripting

bundles/org.openhab.binding.miio/README.md, bundles/org.openhab.binding.miio/src/main/resources/database/dreame.vacuum.mc1808-miot.json, bundles/org.openhab.binding.miio/src/main/resources/database/dreame.vacuum.p2008-miot.json, bundles/org.openhab.binding.miio/src/main/resources/database/huayi.light.fanwy-miot.json, bundles/org.openhab.binding.miio/src/main/resources/database/huayi.light.fanwy2-miot.json, bundles/org.openhab.binding.miio/src/main/resources/database/huayi.light.wyheat-miot.json, bundles/org.openhab.binding.miio/src/main/resources/database/lumi.curtain.hagl05-miot.json, bundles/org.openhab.binding.miio/src/main/resources/database/mijia.vacuum.v2-miot.json, bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.switch.sw1-miot.json, bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.heater.zb1-miot.json
As me & regex are not best friends it seems I actually created yet another readme problem with the last PR.
Hopefully it is now fixed once and for all. In in the separate PR the readme maker is now highlighting these problems (discrepancy between the options text and the mapping)
=> [miio] fix readme mapping string

bundles/org.openhab.binding.magentatv/src/main/java/org/openhab/binding/magentatv/internal/discovery/MagentaTVDiscoveryParticipant.java
The MR400 reports a port 49153 on discovery, which is wrong. Therefore the connect fails and the Thing stays OFFLINE.
This fix makes sure that 49152 is written to the thing config.
=> [magentatv] Fix "MR400 doesn't get online after discovery"

bundles/org.openhab.voice.mactts/src/main/java/org/openhab/voice/mactts/internal/MacTTSAudioStream.java
The additional quotes in the command line made the process to only create an empty file, since the voice could not be found - this completely broke this TTS service.
Additionally, I have added some logging and sanity checks.
=> [mactts] Fixed MacTTS producing empty files

bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/Connection.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/handler/AccountHandler.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/jsons/JsonDevices.java
Fixes #9416 
There should be no duplicate serial numbers, but it seems that in some circumstances Amazon's servers return them. Since we use the serial numbers for device-identification, we need to filter duplicates.
=> [amazonechocontrol] Fixed duplicate serialNumbers

bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/NetatmoBridgeHandler.java, bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudClient.java
This fixes https://github.com/openhab/openhab-addons/issues/9405 and https://github.com/openhab/openhab-addons/issues/9406
=> [netatmo] Only log stack traces to openhab.log if debug is enabled

bundles/org.openhab.binding.dwdunwetter/src/main/java/org/openhab/binding/dwdunwetter/internal/handler/DwdUnwetterHandler.java
- Fixed Channel suffix for newly created Things
Channels for new Things are created starting with suffix 2. The new way to create Channels introduced in https://github.com/openhab/openhab-addons/pull/9229 takes care of a correct count.
=> [dwdunwetter] Fixed Channel suffix for newly created Things

bundles/org.openhab.binding.icalendar/README.md
Users of the icalender OH 1 binding might wonder how to get the url for the
ical file for their calenders. It took me a couple of hours to find this, so
I think it might be useful to have it as an example in the documentation.
=> [icalendar] Provide example for Nextcloud usage

bundles/org.openhab.binding.deconz/README.md, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/GroupThingHandler.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/LightThingHandler.java, bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/thing/group-thing-types.xml, bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/thing/light-thing-types.xml
Fixes #9440 
This includes a breaking change (item-type chnged for alert channel), But since it could never have worked, I doubt someone is using it.
=> [deconz] fix alert channel

bundles/org.openhab.automation.jythonscripting/README.md
Moved the relevant content from https://github.com/openhab/openhab-docs/blob/main/configuration/jsr223-jython.md
=> Improved README for Jython scripting

bundles/org.openhab.automation.groovyscripting/pom.xml
Fixes these warnings:
```
[WARNING] /openhab-addons/bundles/org.openhab.automation.groovyscripting/pom.xml [10:52]: Invalid property key: `groovy.runtime.metaclass;resolution`: <<      groovy.runtime.metaclass;resolution:=optional,>>
[WARNING] /openhab-addons/bundles/org.openhab.automation.groovyscripting/pom.xml [11:61]: Invalid property key: `groovyjarjarantlr4.stringtemplate;resolution`: <<      groovyjarjarantlr4.stringtemplate;resolution:=optional,>>
[WARNING] /openhab-addons/bundles/org.openhab.automation.groovyscripting/pom.xml [12:50]: Invalid property key: `org.abego.treelayout.*;resolution`: <<      org.abego.treelayout.*;resolution:=optional,>>
[WARNING] /openhab-addons/bundles/org.openhab.automation.groovyscripting/pom.xml [13:44]: Invalid property key: …
```
=> [groovyscripting] Fix build warnings

bundles/org.openhab.binding.danfossairunit/src/test/java/org/openhab/binding/danfossairunit/internal/ValueCacheTest.java
See https://ci.openhab.org/job/PR-openHAB-Addons/1539/
```
org.opentest4j.AssertionFailedError: expected: <false> but was: <true>
at org.openhab.binding.danfossairunit.internal.ValueCacheTest.updateValueMultipleCacheUpdatesButNotReportedAsToUpdate(ValueCacheTest.java:60)
```
=> [danfossairunit] Try to make tests more stable

bundles/org.openhab.binding.teleinfo/pom.xml, bundles/org.openhab.binding.teleinfo/src/main/java/org/openhab/binding/teleinfo/internal/handler/cbemm/evoicc/TeleinfoAbstractCbemmEvoIccElectricityMeterHandler.java, bundles/org.openhab.binding.teleinfo/src/main/java/org/openhab/binding/teleinfo/internal/handler/cbetm/TeleinfoAbstractCbetmElectricityMeterHandler.java
Since OH3 provides a new apparent power unit, this PR replace `WATT` by `VOLT_AMPERE` when needed.
=> [teleinfo] Use new apparent power unit

bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/ConfigStore.java, bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/rest/LightsAndGroups.java, bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/rest/ItemUIDtoHueIDMappingTests.java
Fixes #9452
A previous change to fix Alexa device discovery inadvertently changed the format of the UDN and serialNumber fields in the description.xml response.
The UDN should be a UUID string. 
The serialNumber is used by the OH Hue binding directly as the ThingUID and will throw an exception if it contains invalid characters such as `:`. Some users are using both Hue Emulation and the Hue Binding, so the serialNumber has been reverted back to its previous format.
Also the previous change resulted in the id used for lights and groups changing to hexadecimal. Although this doesn't seem to cause any issues with Alexa or Logitech Harmony, it may break other implementations. The id has been reverted back which will mean users will have to refresh their hue devices to pick up the new ids and …
=> [hueemulation] Correct format of UDN and serialNumber fields in description.xml

bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcBaseDAO.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcDerbyDAO.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcPostgresqlDAO.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcConfiguration.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcMapper.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcPersistenceService.java
- Consider local timezone to create time filter
Fixes #8502
Fixes #9308
Fixes https://github.com/openhab/openhab-addons/issues/9446
This is the easy way. Alternatively we can use the `LocaleProvider` to use the user defined timezone.
=> [jdbc] Consider local timezone to create time filter

bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/discovery/HueBridgeDiscoveryParticipant.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/discovery/HueBridgeNupnpDiscovery.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueBridgeHandler.java
Necessary for the auto-ignore discovery feature with the representation property.
Fix #9364
=> [hue] Make sure the serial number will be in lowercase

bundles/org.openhab.binding.openweathermap/README.md, bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/thing/channel-types.xml
* Fix typos in example code
* One Call API: add channe dew-point for daily forecast
* One Call API: remove channel visibility in daily forecast as not included
in data
=> [openweathermap] adapt channels dew-point and visibility in daily forecast

bundles/org.openhab.binding.opensprinkler/NOTICE
Support was removed in https://github.com/openhab/openhab2-addons/commit/8aeeb49c693db7f64b5672c80a1dff484b49effe#diff-b6edf78e29afc34859018f4e11ec53bded97a615b62040712227b883ba5c13f8
=> [opensprinkler] Cleanup NOTICE. pi4j library not used anymore

bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/discovery/ThingDiscoveryService.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/SensorBaseThingHandler.java, bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/thing/sensor-thing-types.xml
- Pimp properties and channel types with proper categories
=> [deconz] Pimp properties and channel types with proper categories

bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/HueBridge.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueBridgeHandler.java
- Catch exception if 'AllGroup' does not exist
Fixes #9175
// CC @olemr
=> [hue] Catch exception if 'AllGroup' does not exist

bundles/org.openhab.binding.epsonprojector/README.md, bundles/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/internal/EpsonProjectorBindingConstants.java, bundles/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/internal/EpsonProjectorDevice.java, bundles/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/internal/EpsonProjectorHandlerFactory.java, bundles/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/internal/connector/EpsonProjectorTcpConnector.java, bundles/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/internal/discovery/EpsonProjectorDiscoveryService.java, bundles/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/internal/discovery/MulticastListener.java, bundles/org.openhab.binding.epsonprojector/src/main/resources/OH-INF/thing/thing-types.xml
Some newer projectors have a built-in Ethernet port that listens for a connection on port 3629. This change sends a special string to initialize the connection. After the initialization string is sent, the normal serial commands can be used. Without the string being sent, the projector would terminate the connection. A discovery service was also added to automatically locate the projector on the network and add the discovered thing to the inbox.
Previously raised in this issue: https://github.com/openhab/openhab1-addons/issues/5604
Test build:
https://github.com/mlobstein/mlobstein-beta-test/raw/master/org.openhab.binding.epsonprojector-3.0.0-SNAPSHOT.jar
https://github.com/mlobstein/mlobstein-beta-test/raw/master/org.openhab.binding.epsonprojector-3.0.0-SNAPSHOT-sources.jar
=> [epsonprojector] Add ESC/VP.net handshake for projectors with built-in ethernet

bundles/org.openhab.binding.icalendar/src/main/java/org/openhab/binding/icalendar/internal/handler/ICalendarHandler.java, bundles/org.openhab.binding.icalendar/src/main/java/org/openhab/binding/icalendar/internal/logic/BiweeklyPresentableCalendar.java, bundles/org.openhab.binding.icalendar/src/test/java/org/openhab/binding/icalendar/internal/logic/BiweeklyPresentableCalendarTest.java
I've limited search of filtered events as it does not make a difference in the result set whether only the requested count or all events in a time frame get retrieved. If the filter is not limited with a start or end date and the events recur with very short intervals (e.g. a day) it's possible the searching for events takes longer than necessary.
Added also a bit more output for debugging/tracing if scheduling seems not to work.
Fixes #9498.
=> [icalendar] optimization of eventfilter-search and more debug output

bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/type/HomematicTypeGeneratorImpl.java
This patch corrects issue #8799 also for older, non HmIP dimmers.
=> [homematic] For non HmIP dimmers stateDescription values must be corrected too

bundles/org.openhab.binding.tr064/README.md, bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/soap/SOAPValueConverter.java, bundles/org.openhab.binding.tr064/src/main/resources/channels.xml
This PR adds the following new channels to the wan subdevice of tr064 binding
| channel                    | item-type                 | description                                                    |
|----------------------------|---------------------------|----------------------------------------------------------------|
| `dslDownstreamMaxRate`     | `Number:DataTransferRate` | DSL Max Downstream Rate                                      |
| `dslDownstreamCurrRate`    | `Number:DataTransferRate` | DSL Curr. Downstream Rate                                      |
| `dslUpstreamMaxRate`       | `Number:DataTransferRate` | DSL Max Upstream Rate                                        |
| `dslUpstreamCurrRate`      | `Number:DataTransferRate` | DSL Curr. Upstream Rate …
=> [tr064] Adds new channels for DSL Max & Current Down-/Upstream Rate

bundles/org.openhab.binding.senechome/src/main/resources/OH-INF/thing/thing-types.xml
Hello,
in the [OpenHAB Community](https://community.openhab.org/t/senechome-binding/108152/2?u=kobip) I got feedback that the BatteryState is not working as expected in OH3. I figured out that the channel "batteryState" was of the type system.battery-level. This is wrong, batteryFuelCharge could be system.battery-level. batteryState is something like "CHARGING" or "BATTERY EMPTY". A simple String with a human readable description.
To fix the problem I changed batteryState to a item-type string.
Here my self compiled jar:
[org.openhab.binding.senechome-3.1.0-SNAPSHOT.jar.zip](https://github.com/openhab/openhab-addons/files/5742457/org.openhab.binding.senechome-3.1.0-SNAPSHOT.jar.zip)
Cheers
=> [senechome] Bugfix BatteryState, should be a String

bundles/org.openhab.binding.squeezebox/README.md
=> [squeezebox] Clarify the process of adding/discovering the server

bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/connector/DenonMarantzConnectorFactory.java, bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/connector/telnet/DenonMarantzTelnetClientThread.java, bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/connector/telnet/DenonMarantzTelnetConnector.java, bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/handler/DenonMarantzHandler.java
=> [denonmarantz] Run the Telnet socket in a dedicated thread

bundles/org.openhab.binding.knx/src/main/resources/OH-INF/thing/device.xml
Small fix for a wrong labeled channel.
Reference: https://github.com/openhab/openhab-addons/issues/9462#issuecomment-751388840
=> [KNX] Fixed DateTime Control channel label

bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/MieleBridgeHandler.java
Currently, the binding blocks a thread from the thing handler thread pool. In situations where a thread is kept busy, a dedicated one must be spawned, tough.
=> [miele] Use dedicated thread for event listening

bundles/org.openhab.binding.netatmo/src/main/resources/OH-INF/thing/channels.xml
- Pimp channel types with proper categories
=> [netatmo] Pimp channel types with proper categories

bundles/org.openhab.binding.mqtt/README.md
Remove the reference to moquette and the legacy mqtt1 binding (not installable on OH3 systems).
=> [mqtt] improve documentation

bundles/org.openhab.binding.nikohomecontrol/README.md
fix typo
While searching why I can't get my electricity working, I think I spotted this typo.
@mherwege
=> [nikohomecontrol] Fix typo in readme

bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/LeapBridgeHandler.java
Adds some additional debug logging in leapbridge.
=> [lutron] Add debug logging in leapbridge

bundles/org.openhab.binding.tr064/README.md, bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/Tr064RootHandler.java, bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/phonebook/PhonebookActions.java, bundles/org.openhab.binding.tr064/src/main/resources/OH-INF/i18n/tr064.properties, bundles/org.openhab.binding.tr064/src/main/resources/OH-INF/i18n/tr064_de.properties
=> [tr064] add rule action for phonebook

CODEOWNERS, bom/openhab-addons/pom.xml, bundles/org.openhab.automation.pidcontroller/NOTICE, bundles/org.openhab.automation.pidcontroller/README.md, bundles/org.openhab.automation.pidcontroller/pom.xml, bundles/org.openhab.automation.pidcontroller/src/main/feature/feature.xml, bundles/org.openhab.automation.pidcontroller/src/main/java/org/openhab/automation/pidcontroller/internal/LowpassFilter.java, bundles/org.openhab.automation.pidcontroller/src/main/java/org/openhab/automation/pidcontroller/internal/PIDControllerConstants.java, bundles/org.openhab.automation.pidcontroller/src/main/java/org/openhab/automation/pidcontroller/internal/PIDException.java, bundles/org.openhab.automation.pidcontroller/src/main/java/org/openhab/automation/pidcontroller/internal/factory/PIDControllerModuleHandlerFactory.java, bundles/org.openhab.automation.pidcontroller/src/main/java/org/openhab/automation/pidcontroller/internal/handler/PIDController.java, bundles/org.openhab.automation.pidcontroller/src/main/java/org/openhab/automation/pidcontroller/internal/handler/PIDControllerActionHandler.java, bundles/org.openhab.automation.pidcontroller/src/main/java/org/openhab/automation/pidcontroller/internal/handler/PIDControllerTriggerHandler.java, bundles/org.openhab.automation.pidcontroller/src/main/java/org/openhab/automation/pidcontroller/internal/handler/PIDOutputDTO.java, bundles/org.openhab.automation.pidcontroller/src/main/java/org/openhab/automation/pidcontroller/internal/template/PIDControllerRuleTemplate.java, bundles/org.openhab.automation.pidcontroller/src/main/java/org/openhab/automation/pidcontroller/internal/template/PIDControllerTemplateProvider.java, bundles/org.openhab.automation.pidcontroller/src/main/java/org/openhab/automation/pidcontroller/internal/type/PIDControllerActionType.java, bundles/org.openhab.automation.pidcontroller/src/main/java/org/openhab/automation/pidcontroller/internal/type/PIDControllerModuleTypeProvider.java, bundles/org.openhab.automation.pidcontroller/src/main/java/org/openhab/automation/pidcontroller/internal/type/PIDControllerTriggerType.java, bundles/org.openhab.automation.pidcontroller/src/test/java/org/openhab/automation/pidcontroller/internal/LowpassFilterTest.java, bundles/pom.xml
This is a PID controller for openHAB.
The implementation is based on the work of @george.erhan (forum) and @hilbrand.
See https://community.openhab.org/t/new-automation-pid-controller/111229
=> [pidcontroller] Initial Contribution

bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/InfluxDBStateConvertUtils.java, bundles/org.openhab.persistence.influxdb/src/test/java/org/openhab/persistence/influxdb/internal/InfluxDBStateConvertUtilsTest.java
=> [influxdb] Treat a stored 1 AND 1.0 as true

bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/api/EnedisHttpApi.java, bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/console/LinkyCommandExtension.java, bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/dto/ConsumptionReport.java, bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/handler/LinkyHandler.java
=> [linky] Handle case when data from yesterday is still NaN

bundles/org.openhab.voice.googletts/README.md
No "Other" option in Google-Cloud-TTS OAuth2 Client Type options. Choose "TV and Limited Input" instead. Rest of readme works as expected.
=> [chromecast] Update README.md

bundles/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/stick/CommandPacket.java, bundles/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/stick/Response.java, bundles/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/stick/ResponseUtil.java, bundles/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/stick/SerialConnection.java, bundles/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/stick/TransmitterStick.java
From time to time, my transmitter stick send invalid responses which do not fit the command that has been sent.
For example, if I send an EASY_INFO for channel 15 (which has more than one shutter), the stick answers with status
NO_INFORMATION (which is expected), but the response does not have channel 15 in it, but channel 1.
This then overwrote the actual status of channel 1 with NO_INFORMATION.
This change skips all responses that do not have the same channels as the command.
=> [Elero Transmitter Stick] drop responses that do not fit the command that was sent.

bundles/org.openhab.binding.yioremote/src/main/java/org/openhab/binding/yioremote/internal/YIOremoteDockHandler.java
if the action sendIRCode is used in a rule it should send out an IR code
action sendIRCode is not sending out any IR code
Correct implementation of sendIR action routine
In addition:
Updating IR receiver switch handler so it's running now
Solved issue during triggering channel while it was disposed
=> [yioremote] BugFix sendIRCode action

bundles/org.openhab.binding.http/README.md, bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/HttpThingHandler.java, bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/config/HttpAuthMode.java, bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/config/HttpThingConfig.java, bundles/org.openhab.binding.http/src/main/resources/OH-INF/thing/thing-types.xml
Fixes #9567 
In some cases HTTP servers  respond with 400/Bad Request (and a message saying "unauthorized" in the content) instead of 401/Unauthorized if they require authentication. Since Jetty sends auth-headers only if the are requested by the server via 401, connections to these servers fail. This allows to force sending the Basic-Auth header in the initial request.
Also made sure that empty additional header entries are removed before headers are processed.
=> [http] add pre-emptive basic authentication and fix header handling

bundles/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/internal/ZmHandlerFactory.java, bundles/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/internal/config/ZmBridgeConfig.java, bundles/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/internal/discovery/MonitorDiscoveryService.java, bundles/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/internal/handler/ZmBridgeHandler.java, bundles/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/internal/handler/ZmMonitorHandler.java, bundles/org.openhab.binding.zoneminder/src/main/resources/OH-INF/config/config.xml, bundles/org.openhab.binding.zoneminder/src/main/resources/OH-INF/thing/thing-types.xml
This is related to #9496 because Zoneminder discovery worked similarly to Ecobee discovery.
=> [zoneminder] Rework discovery to not use the thing handler thread

bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/DeconzBaseThingHandler.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/DeconzBridgeHandler.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/netutils/WebSocketConnection.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/netutils/WebSocketConnectionListener.java
Fixes #9604 
Maybe related to #9517 
Follow-Up to #9307 
The root cause seems to be that the websocket-connection was restarted even if it was not closed before (`onError` does not necessarily close the session, but the code triggered a (delayed) restart of the connection). In some cases the `onError` was followed by ?`onClose` which triggered an (immediate) restart of the connection, running two concurrent restart-attempts.
=> [deconz] refactoring and fix connection issues

bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/HttpThingHandler.java, bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/Util.java, bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/http/RefreshingUrlCache.java
=> [http] fix missing escaping of URLs

bundles/org.openhab.binding.dwdunwetter/README.md
=> [dwdunwetter] documentation for binding updated 

bundles/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/StatefulHandlerCallback.java, bundles/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/pro3/AtlonaPro3Handler.java, bundles/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/pro3/AtlonaPro3PortocolHandler.java
This PR fixes a bug with setting the volume level on Atlona Matrix switches. The API expects the volume to be a whole number but the binding was using double to hold the volume resulting in the number being sent having the format 'NN.0'. I also removed the dependency on Apache StringUtils.
=> [atlona] Volume level should be a whole number

bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/handler/EcobeeThermostatBridgeHandler.java
Mistakenly removed the entire `getServices` method. 😦 
Fixes #9630 
=> [ecobee] Fixed actions broken by recent PR

bundles/org.openhab.binding.draytonwiser/src/main/java/org/openhab/binding/draytonwiser/internal/discovery/DraytonWiserDiscoveryService.java, bundles/org.openhab.binding.draytonwiser/src/main/java/org/openhab/binding/draytonwiser/internal/handler/DraytonWiserThingHandler.java, bundles/org.openhab.binding.draytonwiser/src/main/java/org/openhab/binding/draytonwiser/internal/handler/HeatHubHandler.java, bundles/org.openhab.binding.draytonwiser/src/main/java/org/openhab/binding/draytonwiser/internal/handler/RoomHandler.java
In some cases "DraytonWiser" was mis-spelled as "DraytonWise"
=> [draytonwiser] Fix typos in log messages and class names

bundles/org.openhab.binding.tr064/README.md
I propose to expand a few paragraphs of the existing documentation based on what was described in several forum threads. Given that several users ask for textual configuration I added an initial paragraph stating that it is discouraged but also adding at the end a working example that was proposed by some user in the forum.
I also split the description of the channels by subdevice. It is not clear what is the meaning of advanced parameters for the subdevices, as there is no Show advanced option for these devices in the main UI.
=> [tr064] improve documentation and add textual config example

bundles/org.openhab.io.hueemulation/README.md
Just a little fix in an example configuration. Nginx won't start with the previous example what confused me when I tried to set up a reverse proxy.
Also please consider highlighting the following part:
```
server {
listen 80;
location /api {
proxy_pass http://localhost:8080/api/;
}
}
```
I struggled a lot since I didn't read this and my Alexa couldn't find my emulated devices.
=> [hueemulation] Fix nginx example configuration

bundles/org.openhab.binding.remoteopenhab/src/main/java/org/openhab/binding/remoteopenhab/internal/handler/RemoteopenhabBridgeHandler.java
This PR fixes the failing of the binding reported by a user on the forum because he has several items with the same name on his remote server. I don't know how it is possible to define several items with the same name (I was not able to do it) but by the way, this PR makes sure to catch this exception (IllegalArgumentException), log a message that should help the user, and put the thing to OFFLINE in case the creation of the channels is failing due to this exception.
=> [remoteopenhab] Handle IllegalArgumentException when building channels

bundles/org.openhab.binding.tr064/README.md, bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/config/Tr064RootConfiguration.java, bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/phonebook/PhonebookProfileFactory.java, bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/soap/SOAPValueConverter.java, bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/util/Util.java
- fix wanBlockByIP channel
- allow comments in parameter lists
- fix compiler warnings
=> [tr064] fix wanBlockByIP channel and improvements to paramater handling

bundles/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/LxServerHandler.java
This is a fix for defect #8693 - a deadlock between websocket message receive and keepalive sending was eliminated by introduction of a blocking queue instead of unblocking queue with semaphore.
2.5.x branch fix: #9622
Signed-off-by: Pawel Pieczul <pieczul@gmail.com>
=> [loxone] Fix for #8693 - removed deadlock

bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/http/RefreshingUrlCache.java
As reported in the community forum the first refresh occured after the refreshTime, not immediately after the channel was configured. Especially for channels with a long refreshTime this was very inconvenient. 
=> [http] fix initial refresh

bundles/org.openhab.transform.map/src/main/java/org/openhab/transform/map/internal/MapTransformationService.java, bundles/org.openhab.transform.map/src/main/java/org/openhab/transform/map/internal/profiles/MapTransformationProfile.java, bundles/org.openhab.transform.map/src/main/java/org/openhab/transform/map/internal/profiles/MapTransformationProfileFactory.java, bundles/org.openhab.transform.map/src/main/resources/OH-INF/config/mapProfile.xml, bundles/org.openhab.transform.map/src/main/resources/readme.txt
- Added 'ConfigOptionProvider' to provide filenames ending with '.map' in Profile configuration
Depends on openhab/openhab-core#2052
=> [map] Added 'ConfigOptionProvider' to provide filenames ending with '.map' in Profile configuration

bundles/org.openhab.binding.max/src/main/resources/OH-INF/thing/thing-types.xml
- Removed 'advanced' flag for room and name config params as they are not advanced for other thing types
=> [max] Removed 'advanced' flag for room and name config params

bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcBaseDAO.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcDerbyDAO.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcMariadbDAO.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcMysqlDAO.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcPostgresqlDAO.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcMapper.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcPersistenceService.java
- Return `QuantityType`s for number items with dimension
This implementation uses the same approach like introduces for RRD4J in https://github.com/openhab/openhab-addons/pull/8866 and https://github.com/openhab/openhab-addons/pull/8938. But I am seeing some issue with Items of type `Number:Dimensionless`.
In general it would be possible to extend the database structure by adding a column for the unit for number items. This will need a little bit more effort.
@mhilbush May I ask you to chime in and help testing?
Related to https://github.com/openhab/openhab-core/issues/1954
---
Depends on #9445
=> [jdbc] Return QuantityTypes for number items with dimension

bundles/org.openhab.binding.zoneminder/README.md, bundles/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/internal/handler/Monitor.java, bundles/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/internal/handler/ZmBridgeHandler.java, bundles/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/internal/handler/ZmMonitorHandler.java
The method of getting the most recent event was not working correctly when Zoneminder monitors were configured for Mocord and Record. The Zoneminder query now excludes events with the name "New Event".
=> [zoneminder] Fixed most recent event query

bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/LcnHandlerFactory.java, bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/LcnModuleDiscoveryService.java, bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/LcnModuleHandler.java, bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/connection/AbstractStateMachine.java, bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/connection/Connection.java, bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/pchkdiscovery/LcnPchkDiscoveryService.java, bundles/org.openhab.binding.lcn/src/test/java/org/openhab/binding/lcn/internal/subhandler/AbstractTestLcnModuleSubHandler.java
=> [lcn] Refactor and fix null warnings

bundles/org.openhab.binding.daikin/deploy.sh, bundles/org.openhab.binding.nikobus/src/main/java/org/openhab/binding/nikobus/internal/handler/NikobusPcLinkHandler.java
Signed-off-by: Wouter Denayer <wouter@denayer.com>
open connection on refresh even if no modules exist
currently, when no modules are defined the connection to nikobus is not opened and therefore the button presses are not detected.
=> [nikobus] open connection on refresh even if no modules exist

bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/sensors/PresenceHandler.java
- Fixed configuration update for parameter 'ledindication'
=> [hue] Fixed configuration update for parameter 'ledindication'

bundles/org.openhab.transform.javascript/README.md, bundles/org.openhab.transform.javascript/src/main/java/org/openhab/transform/javascript/internal/JavaScriptEngineManager.java, bundles/org.openhab.transform.javascript/src/main/java/org/openhab/transform/javascript/internal/JavaScriptTransformationService.java, bundles/org.openhab.transform.javascript/src/main/java/org/openhab/transform/javascript/internal/TransformationScriptWatcher.java, bundles/org.openhab.transform.javascript/src/main/java/org/openhab/transform/javascript/internal/profiles/JavaScriptTransformationProfile.java, bundles/org.openhab.transform.javascript/src/main/java/org/openhab/transform/javascript/internal/profiles/JavaScriptTransformationProfileFactory.java, bundles/org.openhab.transform.javascript/src/main/resources/OH-INF/config/javascriptProfile.xml, bundles/org.openhab.transform.javascript/src/main/resources/readme.txt
- Added 'ConfigOptionProvider' to provide filenames ending with '.js' in Profile configuration
=> [js] Added 'ConfigOptionProvider' to provide filenames ending with '.js' in Profile configuration

bundles/org.openhab.binding.robonect/src/main/java/org/openhab/binding/robonect/internal/handler/RobonectHandler.java
Fix for #9428 for branch 2.5.x
This is not my own work. It is simply a cherry pick from the pull request https://github.com/openhab/openhab-addons/pull/9429 (commit ca574a943db6e77b5ecd61739cfc1814c75b897b) from the main branch to the branch 2.5.x. So I left the "signed-off-by" from the original commit.
**Reason:** 
In my opinion, the bug #9428 is critical, because if the Robonect binding is not able to communicate with the Robonect module (which is most likely the case in winter, when the mower is turned off), it will tear down all other bindings that make use of `httpClientFactory.getCommonHttpClient()`.
In my setup Robonect causes the OpenWeatherMap binding, the Denon/Marantz binding and the Tankerkoenig binding to go into an …
=> [robonect] Fix breaking common HttpClient on shutdown (#9429)

bundles/org.openhab.io.homekit/README.md
This will introduce a Tip-Box on the documentation website with a reference to the cloud connector docs.
We introduced a redirect with a dummy link for a proper long-term usage.
(Also includes some whitespace removals.)
Reference: openhab/openhab-docs#1408
Signed-off-by: Jerome Luckenbach github@luckenba.ch
=> [homekit] Introduce Info box with redirect url

bundles/org.openhab.binding.icalendar/src/main/java/org/openhab/binding/icalendar/internal/handler/ICalendarHandler.java
Uses now also the `ThingHandlerCallback`'s factory of `ChannelBuilder`s for creating the channel on old instances.
Closes #9674
=> [icalendar] Change migration of last_update to use ThingHandlerCallback

bundles/org.openhab.binding.logreader/README.md
The original example references to the old telegram action, which is no longer supported. The updated example uses the (new) telegram binding.
=> [logreader] Correct example for telegram binding

bundles/org.openhab.binding.nikobus/src/main/java/org/openhab/binding/nikobus/internal/handler/NikobusPushButtonHandler.java
In case of simulated Nikobus push button event refresh impacted modules too, so binding fetches the updated state from affected modules.
=> [nikobus] refresh impacted modules on simulated button press

bundles/org.openhab.binding.remoteopenhab/README.md
Fix Remote openHAB Readme typos and introduce non-breaking spaces in 'openHAB v' for readability
=> [remoteopenhab] Fix Remote openHAB Readme typos

bundles/org.openhab.binding.xmppclient/README.md
While trying to get the `xmppclient`'s example rules to work with OH3, I found out what needs to be changed and would like to contribute my findings:
- Renamed parameter 1 of `getActions` from "_xmpp_" to "_xmppclient_".
- Removed `getEvent()` call as "receivedEvent" automatically contains the String since OH3.
=> [xmppclient] Update README.md's example rules for OH3

itests/org.openhab.binding.modbus.tests/src/main/java/org/openhab/binding/modbus/tests/ModbusDataHandlerTest.java
=> [modbus] itests: Fix testRefreshOnData

bundles/org.openhab.binding.draytonwiser/README.md, bundles/org.openhab.binding.draytonwiser/src/main/java/org/openhab/binding/draytonwiser/internal/DraytonWiserBindingConstants.java, bundles/org.openhab.binding.draytonwiser/src/main/java/org/openhab/binding/draytonwiser/internal/handler/RoomStatHandler.java, bundles/org.openhab.binding.draytonwiser/src/main/java/org/openhab/binding/draytonwiser/internal/handler/SmartPlugHandler.java, bundles/org.openhab.binding.draytonwiser/src/main/java/org/openhab/binding/draytonwiser/internal/handler/TRVHandler.java, bundles/org.openhab.binding.draytonwiser/src/main/java/org/openhab/binding/draytonwiser/internal/model/DeviceDTO.java, bundles/org.openhab.binding.draytonwiser/src/main/java/org/openhab/binding/draytonwiser/internal/model/SmartPlugDTO.java, bundles/org.openhab.binding.draytonwiser/src/main/resources/OH-INF/thing/thing-types.xml
Expose Smart Plug Power Metering, Improve null handling
The Drayton Wiser API now exposes instantaneous power metering and cumulative energy usage for Wiser Smart Plug devices through the API. This PR adds channels to report this data. Capability mentioned by @andrew-schofield in this [post ](https://community.openhab.org/t/drayton-wiser-thermostat-binding/35640/402)- sorry I couldn't wait so thought I should share!
Additionally, when Wiser wireless devices are offline some properties in the API response are nulled and the binding would fail to fully update all the device's channels. Added checks to update all channels, tested with registered Smart Plug / TRV / RoomStat with power removed.
=> [draytonwiser] Expose Smart Plug Power Metering, Improve null handling

bundles/org.openhab.binding.tr064/README.md, bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/phonebook/Tr064PhonebookImpl.java
Phone book numbers and numbers to be looked up might be formatted differently. A real world example from my setup: '+49 (12345) 67890' (phonebook formatting) vs. '01234567890' (format used by avmfritz binding, taken straight from Fritz!Box response).
Make sure such formatting differences do not cause lookup mismatches.
=> [tr064] Normalize numbers in phone book entries.

bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/AbstractHomekitAccessoryImpl.java
fixes the issue with controller app by using item name as accessory serial
#9746 
=> [homekit] fix for 9746: use item name as accessory serial

bundles/org.openhab.binding.epsonprojector/README.md, bundles/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/internal/EpsonProjectorCommandType.java, bundles/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/internal/EpsonProjectorDevice.java, bundles/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/internal/enums/ColorMode.java, bundles/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/internal/enums/PowerStatus.java, bundles/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/internal/handler/EpsonProjectorHandler.java, bundles/org.openhab.binding.epsonprojector/src/main/resources/OH-INF/thing/thing-types.xml
Upon reviewing the documentation for different projectors, I discovered that the keycode channel for the epsonprojector binding needs to be modified to allow non-numeric characters to be sent. I changed the channel type from Number to String and updated the documentation to include an example of using the keycode channel.
=> [epsonprojector] Fix keycode channel to allow non-numeric characters

bundles/org.openhab.binding.tr064/src/main/resources/channels.xml
=> [tr064] fix parameter patterns

bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/phonebook/Tr064PhonebookImpl.java
=> [tr064] Merge duplicate phone book entries

bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/Tr064RootHandler.java, bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/soap/SOAPConnector.java, bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/soap/SOAPRequest.java, bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/util/Util.java
=> [tr064] reduce network load and improve XML handling

bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/handler/SamsungTvHandler.java
Fixes #9673 
@kaikreuzer @paulianttila Requesting you review and approve.
=> [samsungtv] Fixes device.getIdentity().getDescriptorURL() comparison

bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitImpl.java
as described here https://github.com/openhab/openhab-core/issues/2098
homekit addon does not set pairing status correctly after an update. this PR fix it - on bridge start it will check whether a pairing/user exists and set the discoverability at HAP level accordantly.
=> [homekit] fix pairing after addon update

bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/discovery/TopicSubscribe.java
Fixes #9730
During subscription a <code>TopicSubscribe</code> is created (see <code>AbstractBrokerHandler</code>)
But when <code>discoveryEnabled == false</code> the <code>TopicSubscribe</code> is never started.
During tear down, unsubscribe should only be tried, if the subsribe was started before.
=> [mqtt] Only unsubscribe if we subscribed before

bundles/org.openhab.binding.smartmeter/src/main/java/org/openhab/binding/smartmeter/internal/MeterDevice.java
=> [smartmeter] Fixed flooding logs with warnings if serial port is not accessible

bundles/org.openhab.automation.pidcontroller/README.md, bundles/org.openhab.automation.pidcontroller/src/main/java/org/openhab/automation/pidcontroller/internal/PIDControllerConstants.java, bundles/org.openhab.automation.pidcontroller/src/main/java/org/openhab/automation/pidcontroller/internal/handler/PIDController.java, bundles/org.openhab.automation.pidcontroller/src/main/java/org/openhab/automation/pidcontroller/internal/handler/PIDControllerTriggerHandler.java, bundles/org.openhab.automation.pidcontroller/src/main/java/org/openhab/automation/pidcontroller/internal/type/PIDControllerTriggerType.java
Also fix naming of thread and shutdown executor.
=> [pidcontroller] Remove limits, make Ki dependent from the loop time, add reset command

bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/connection/AbstractConnectionState.java, bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/connection/AbstractConnectionStateSendCredentials.java, bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/connection/ConnectionStateConnecting.java, bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/connection/ConnectionStateGracePeriodBeforeReconnect.java, bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/connection/ConnectionStateMachine.java, bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/connection/ConnectionStateShutdown.java, bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/connection/ConnectionStateWaitForLcnBusConnected.java
=> [lcn] Fix displaying of "not enough licenses" message

bundles/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/handler/ADBridgeHandler.java, bundles/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/net/SocketChannelSession.java, bundles/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/pro3/AtlonaPro3Handler.java, bundles/org.openhab.binding.bluetooth.bluegiga/src/main/java/org/openhab/binding/bluetooth/bluegiga/handler/BlueGigaBridgeHandler.java, bundles/org.openhab.binding.bluetooth.bluegiga/src/main/java/org/openhab/binding/bluetooth/bluegiga/internal/BlueGigaSerialHandler.java, bundles/org.openhab.binding.caddx/src/main/java/org/openhab/binding/caddx/internal/CaddxCommunicator.java, bundles/org.openhab.binding.caddx/src/main/java/org/openhab/binding/caddx/internal/handler/CaddxBridgeHandler.java, bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/handler/EnvisalinkBridgeHandler.java, bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/handler/TCPServerBridgeHandler.java, bundles/org.openhab.binding.harmonyhub/src/main/java/org/openhab/binding/harmonyhub/internal/discovery/HarmonyHubDiscoveryService.java, bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/AbstractHomematicGateway.java, bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/server/BinRpcServer.java, bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/RequestQueueManager.java, bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/driver/Poller.java, bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/driver/Port.java, bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/driver/hub/HubIOStream.java, bundles/org.openhab.binding.keba/src/main/java/org/openhab/binding/keba/internal/KebaHandlerFactory.java, bundles/org.openhab.binding.keba/src/main/java/org/openhab/binding/keba/internal/handler/KeContactHandler.java, bundles/org.openhab.binding.keba/src/main/java/org/openhab/binding/keba/internal/handler/KeContactTransceiver.java, bundles/org.openhab.binding.linuxinput/src/main/java/org/openhab/binding/linuxinput/internal/Utils.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/grxprg/PrgBridgeHandler.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/grxprg/SocketSession.java
=> Improved a number of the thread names

bundles/org.openhab.binding.homematic/README.md, bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/common/HomematicConfig.java, bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/AbstractHomematicGateway.java, bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/client/RpcClient.java, bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/client/XmlRpcClient.java, bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/message/BinRpcMessage.java, bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/message/XmlRpcResponse.java, bundles/org.openhab.binding.homematic/src/main/resources/OH-INF/thing/bridge.xml
This PR focusses primarily on the solution of two connection problems:
1. An additional fix for #6963 that allows the set a buffer size in case the buffer is too small
2. By simplifying the coding and removing some additional requests to the gateway an issue with the re-connection was solved (fixes #8808)
Two additional commits are removing deprecations from the doc and replaced deprecated Java constructors.
=> [homematic] Fix for two (re)connection problems

bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/kostalinverter/internal/KostalInverterFactory.java, bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/kostalinverter/internal/firstgeneration/ChannelConfig.java, bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/kostalinverter/internal/firstgeneration/SourceConfig.java, bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/kostalinverter/internal/firstgeneration/WebscrapeHandler.java, bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/kostalinverter/internal/thirdgeneration/ThirdGenerationBindingConstants.java, bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/kostalinverter/internal/thirdgeneration/ThirdGenerationChannelDatatypes.java, bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/kostalinverter/internal/thirdgeneration/ThirdGenerationChannelMappingToWebApi.java, bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/kostalinverter/internal/thirdgeneration/ThirdGenerationConfiguration.java, bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/kostalinverter/internal/thirdgeneration/ThirdGenerationEncryptionHelper.java, bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/kostalinverter/internal/thirdgeneration/ThirdGenerationHandler.java, bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/kostalinverter/internal/thirdgeneration/ThirdGenerationHttpHelper.java, bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/kostalinverter/internal/thirdgeneration/ThirdGenerationInverterTypes.java, bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/kostalinverter/internal/thirdgeneration/ThirdGenerationMappingInverterToChannel.java
The internal package was placed before the binding specific package, and it should be the other way around.
=> [kostalinverter] Fixed package structure

bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/handler/LinkyHandler.java
=> [linky] Set channel to UNDEF when data not yet available

bundles/org.openhab.binding.draytonwiser/src/main/java/org/openhab/binding/draytonwiser/internal/discovery/DraytonWiserMDNSDiscoveryParticipant.java
Small bugfixes for MDNS discovery functionality:
1. Fixes #8786 invalid uid on discovered hub
2. Resolve issue on startup in OH3 for discovery result without address, reported here https://community.openhab.org/t/drayton-wiser-thermostat-binding/35640/402
=> [draytonwiser] MDNS Fixes

bundles/org.openhab.binding.tplinksmarthome/README.md, bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/TPLinkSmartHomeHandlerFactory.java, bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/TPLinkSmartHomeThingType.java, bundles/org.openhab.binding.tplinksmarthome/src/main/resources/OH-INF/thing/KP115.xml
[tplinksmarthome] Add suppport for the TP-Link Kasa KP115 Smart WiFi Plug with Energy Monitoring
The KP115 plug is a WiFi smart plug with energy monitoring support. It uses the same API as existing TP-Link smart home devices. This change adds support in the binding for the KP115. All functionality was tested and verified working using OpenHAB 3.0.0 and a retail purchased KP115.
=> [tplinksmarthome] Add suppport for the TP-Link Kasa KP115 Smart WiFi Plug with Energy Monitoring

bundles/org.openhab.binding.teleinfo/src/main/java/org/openhab/binding/teleinfo/internal/handler/TeleinfoAbstractControllerHandler.java, bundles/org.openhab.binding.teleinfo/src/main/java/org/openhab/binding/teleinfo/internal/handler/TeleinfoAbstractElectricityMeterHandler.java
Resolve #9546.
This PR prevents the `ThingHandler` from registering more than once to the bridge event when a `bridgeStatusChanged` is triggered.
=> [teleinfo] Fix memory leak

bundles/org.openhab.binding.tesla/src/main/resources/OH-INF/thing/channels.xml
Fixes https://github.com/openhab/openhab-addons/issues/9636
=> [tesla] Correctly handle floating point numbers for estimatedbatteryrange channel

bundles/org.openhab.binding.siemensrds/src/main/java/org/openhab/binding/siemensrds/internal/RdsDataPoints.java, bundles/org.openhab.binding.siemensrds/src/main/resources/OH-INF/thing/thing-types.xml
Signed-off-by: Andrew Fiddian-Green software@whitebear.ch
Added Representation Property so that already instantiated Things will be hidden in the InBox.
Also fixed a potential null pointer issue.
=> [siemensrds]  Hide already instantiated Things in the InBox

bundles/org.openhab.binding.satel/README.md, bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/SatelHandlerFactory.java, bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/discovery/SatelDeviceDiscoveryService.java
This PR fixes discovery of event-log and system things in OH3. 
The issue is related to thing UID validation introduced in OH3 and both things did not pass this validation (missing bridge segment). The fix changes the way UID are created and now they are correct for both of things.
Related discussion is here: https://community.openhab.org/t/satel-binding-support-announcements-and-feature-requests/56135/245
=> [satel] Thing discovery fix

bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/AVMFritzBaseThingHandler.java
- Added warning if temperature command cannot be converted to Celsius
Related to #9771
=> [avmfritz] Added warning if temperature command cannot be converted to Celsius

bundles/org.openhab.binding.mqtt.homeassistant/README.md
cfr. forum post: https://community.openhab.org/t/mqtt-homeassistant-thing-detected-no-channel/111775/
=> [mqtt-homeassistant] Add JOSNPath and JINJA as requirements for MQTT HA

bundles/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/internal/EpsonProjectorDevice.java
**Issue description:**
When beamer is switched on and gets the "off" command the binding sets a "ready" flag to false. This should prevent sending further commands for 10 seconds. To reset this flag a scheduled task gets fired.
Some how (couldn't figure out why until now) one more command is executed, which shouldn't happen at this moment. This command cannot be executed as expected and predicted in comment of code:
```
EpsonProjectorDevice.java (line: 126)
...
// When PWR OFF command is sent, next command can be sent 10 seconds after the colon is received
...
```
This command raises an error "Couldn't execute command 'Power', No response received" and resets the connection. The `disconnect()-method (EpsonProjectorDevice.java (line: 205)) `deletes the running timeout-job. in this …
=> [epsonprojector] Fix "projector-tcp"-Thing gets stuck after Power-off via TCP

bundles/org.openhab.binding.onewire/src/main/resources/OH-INF/thing/common.xml
The channel is added dynamically with a channel-type `abshumidity`, but the channel-type definition was names `absolutehumidity`
=> [onewire] fix absolute humidity channel type

bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/DigitalSTROMHandlerFactory.java, bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/lib/manager/impl/DeviceStatusManagerImpl.java, bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/lib/manager/impl/SceneManagerImpl.java
Fixes #9830 
Unfortunately can't be backported easily to 2.5.x
Also fixes two other null issues
=> [digitalstrom] fix concurrency issue

bundles/org.openhab.binding.icalendar/src/main/java/org/openhab/binding/icalendar/internal/logic/CommandTag.java, bundles/org.openhab.binding.icalendar/src/test/java/org/openhab/binding/icalendar/internal/logic/BiweeklyPresentableCalendarTest.java
This PR should fix https://github.com/openhab/openhab-addons/issues/9820 by adding `DecimalType` as the first entry in the list of evaluated target command types for calendar events of the icalendar binding.
It has to be an entry before `QuantityType`, because `QuantityType` also returns a valid object for raw decimal types without any unit-of-measurement.
=> [icalendar] Ensure DecimalType will be used if no unit given

bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/callmonitor/CallEvent.java, bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/callmonitor/CallMonitor.java, bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/AVMFritzBaseBridgeHandler.java, bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/BoxHandler.java
- Added initial refresh of Call Monitor channels
- Improved `CallMonitorThread` handling
Fixes #9712
=> [avmfritz] Added initial refresh of Call Monitor channels and improved thread handling

bundles/org.openhab.binding.buienradar/src/main/java/org/openhab/binding/buienradar/internal/BuienradarHandler.java, bundles/org.openhab.binding.buienradar/src/main/java/org/openhab/binding/buienradar/internal/buienradarapi/BuienradarPredictionAPI.java, bundles/org.openhab.binding.buienradar/src/main/resources/OH-INF/thing/thing-types.xml
Buienradar is not the most stable source so the retries create a lot of warn and time outs even provoke (quite regular) stack traces. 
Fixes:  #6698
Signed-off-by: Björn Brings <bjoernbrings@web.de>
=> [buienradar] Avoid to much log noise

bundles/org.openhab.binding.miio/src/test/java/org/openhab/binding/miio/internal/RoboMapViewer.java
as per https://community.openhab.org/t/xiaomi-vacuum-map-viewer-to-find-coordinates-for-zone-cleaning/103500/47
=> [miio] fix printed zone clean command

bundles/org.openhab.binding.bluetooth.bluegiga/NOTICE, bundles/org.openhab.binding.fsinternetradio/README.md, bundles/org.openhab.binding.miele/README.md, bundles/org.openhab.binding.mqtt.generic/NOTICE, bundles/org.openhab.binding.mqtt.homeassistant/NOTICE, bundles/org.openhab.binding.mqtt.homie/NOTICE, bundles/org.openhab.binding.nibeheatpump/README.md, bundles/org.openhab.voice.mactts/NOTICE
* Updates links to target the openhab-addons 'main' branch instead of the 'master' branch
* Updates some NOTICE files to indicate content is maintained by openHAB instead of Eclipse SmartHome
=> Fix links and NOTICE files

bundles/org.openhab.binding.hue/src/main/resources/OH-INF/i18n/hue_de.properties, bundles/org.openhab.binding.hue/src/main/resources/OH-INF/i18n/hue_fr.properties, bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/ColorLight.xml, bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/ColorTemperatureLight.xml, bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/DimmableLight.xml, bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/DimmablePlug.xml, bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/ExtendedColorLight.xml, bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/Group.xml, bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/OnOffLight.xml, bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/OnOffPlug.xml, bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/channels.xml
- Use system default channel types for lights
=> [hue] Use system default channel types for lights

bundles/org.openhab.binding.modbus/README.md
As a result of #9268 the logger is now in core.
=> [modbus] update verbose logging guide in README

bundles/org.openhab.binding.tr064/README.md
Improve the documentation for the case that the sub-devices are not detected automatically.
Happened to me and some other users.
See https://community.openhab.org/t/issues-with-the-new-oh3-tr-064-binding/113926
=> [tr064] Update docs: Manual scan

bundles/org.openhab.binding.dsmr/src/test/java/org/openhab/binding/dsmr/internal/device/DSMRSerialAutoDeviceTest.java
PortInUseException interface changed in openhab/openhab-core#2126
This breaks the build (not the fix :wink:).
=> [dsmr] Fix test after openhab-core change #2126

bundles/org.openhab.binding.amazonechocontrol/README.md, bundles/org.openhab.binding.dsmr/README.md, bundles/org.openhab.binding.dwdpollenflug/README.md, bundles/org.openhab.binding.enocean/README.md, bundles/org.openhab.binding.fmiweather/README.md, bundles/org.openhab.binding.homematic/README.md, bundles/org.openhab.binding.hue/README.md, bundles/org.openhab.binding.knx/README.md, bundles/org.openhab.binding.magentatv/src/main/java/org/openhab/binding/magentatv/internal/handler/MagentaTVHandler.java, bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/handler/MaxDevicesHandler.java, bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/handler/NikoHomeControlBridgeHandler.java, bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyBaseHandler.java, bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyRelayHandler.java, bundles/org.openhab.binding.smartthings/doc/Troubleshooting.md, bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/handler/TradfriLightHandler.java, bundles/org.openhab.binding.velux/src/main/resources/OH-INF/i18n/velux_de.properties, bundles/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/internal/serialization/NeeoDeviceSerializer.java
Related to #8607.
In some cases removed information that is actually generic information and should not be in binding readme.
=> Removal of reference to PaperUI

bundles/org.openhab.binding.mqtt.generic/src/main/resources/OH-INF/config/switch-channel-config.xml
There is already a default for this : 'ON'/'OFF', 'Open'/'Close'
Why do we need another default?
The code does not honor the default, so the best is, to remove the default from the UI.
Fix for #9710
=> [mqtt] Remove default for contact/switch alternate on/off message

bundles/org.openhab.transform.map/README.md
[MAP transformation] Update README.md
Added a note with regards to map file name requirements. Without the .map extension the transformation throws a rather unrelated error into the openhab.log while the transformation fails. See this [post](https://community.openhab.org/t/oh3-rule-and-map-file-name-requirements/114532/2?u=hugob).
Signed-off-by: Stefan Reiner <reiner.stefan@gmx.at>
=> [MAP transformation] Update README.md

bundles/org.openhab.binding.openwebnet/pom.xml, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/handler/OpenWebNetAutomationHandler.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/handler/OpenWebNetBridgeHandler.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/handler/OpenWebNetGenericHandler.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/handler/OpenWebNetLightingHandler.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/handler/OpenWebNetThingHandler.java, bundles/org.openhab.binding.openwebnet/src/test/java/org/openhab/binding/openwebnet/handler/OwnIdTest.java
Backport of some fixes from OH 3.1.0 to 2.5.x branch (see PR #9662)
* fixed reconnect of gateway from USB port
* fixed up/down inverted automation messages for old firmwares (fixes #9651)
* removed warn logs when reconnecting BUS command connection
* fixed dimmers creating loop when lowered from 20 to 10% (fixes #9317)
* now using openwebnet4j 0.3.4
=> [openwebnet] Backport of some fixes from OH 3.1.0 to 2.5.x branch

bundles/org.openhab.binding.tr064/README.md, bundles/org.openhab.binding.tr064/src/main/resources/channels.xml
The change to GB war forgotten before the binding was merged. Also clarify why counters are different from what is shown in the online counter in fritzbox devices.
=> [tr064] fix wrong unit in TotalBytes

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoBasicHandler.java
Allow all quantitytypes and units even if not in the conversion table.
=> [miio] allow all quantitytypes and units

bundles/org.openhab.binding.irobot/README.md, bundles/org.openhab.binding.irobot/src/main/java/org/openhab/binding/irobot/internal/IRobotBindingConstants.java, bundles/org.openhab.binding.irobot/src/main/java/org/openhab/binding/irobot/internal/dto/MQTTProtocol.java, bundles/org.openhab.binding.irobot/src/main/java/org/openhab/binding/irobot/internal/handler/RoombaHandler.java, bundles/org.openhab.binding.irobot/src/main/resources/OH-INF/thing/thing-types.xml, bundles/org.openhab.binding.irobot/src/test/java/org/openhab/binding/irobot/internal/handler/RoombaHandlerTest.java
- add command: "cleanRegions:\<pmapId\>;<region_id1>,<region_id2>" to clean only specific regions of a specific map
- change initiator in the requests from "localApp" to "openhab"
- add channel last_command to determine the required pmapId and region_ids 
- I also added the RoombaHandlerTest: It is not an origin JUnit-Test, but it was very helpful to test the protocol without openhab. Feel free to remove it, if it does not fulfill your requirements
Signed-off-by: Florian Binder <fb@java4.info>
=> [irobot] Add command "cleanRegions" to clean specific regions only

bundles/org.openhab.binding.tivo/README.md, bundles/org.openhab.binding.tivo/src/main/java/org/openhab/binding/tivo/internal/handler/TiVoHandler.java, bundles/org.openhab.binding.tivo/src/main/java/org/openhab/binding/tivo/internal/service/TivoStatusProvider.java
This PR fixes 3 bugs with the tivo binding:
1. Channel parsing fails for non-OTA channels
2. The thing status is OFFLINE if openHAB is started while the Tivo is running a streaming app or is in standby mode
3. Waking the device from standby mode does not work
Some minor documentation updates were also included.
Thanks to @AndyXMB for finding these issues.
=> [tivo] fix bugs with standby mode and channel parsing

bundles/org.openhab.binding.sonos/README.md, bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosBindingConstants.java, bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/Move.xml
=> [sonos] Add support for Sonos Move

bundles/org.openhab.binding.openthermgateway/src/main/java/org/openhab/binding/openthermgateway/handler/OpenThermGatewayHandler.java, bundles/org.openhab.binding.openthermgateway/src/main/java/org/openhab/binding/openthermgateway/internal/OpenThermGatewaySocketConnector.java, bundles/org.openhab.binding.openthermgateway/src/main/resources/OH-INF/thing/otgw.xml
Fixes #9903
Also see previously closed PR #9925
Signed-off-by: Arjen Korevaar a.korevaar@mephix.com
=> [openthermgateway] fix automatic reconnect after connection attempt fails

bundles/org.openhab.binding.heos/src/main/java/org/openhab/binding/heos/internal/discovery/HeosDiscoveryParticipant.java, bundles/org.openhab.binding.heos/src/main/java/org/openhab/binding/heos/internal/handler/HeosPlayerHandler.java
- This pull request fixes an runtime issue if no serial number is provided by the HEOS speaker. 
- It also adds the support to use the Denon "Home" speaker series as bridge
The runtime bug was reported within OpenHab [community](https://community.openhab.org/t/heos-denon-support/3449/380).
=> [heos] Fix runtime error; Support for new  Denon "Home" speaker added

bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/converter/PlayerItemConverter.java
=> [http] fix duplicate commands on PlayerItemConverter

bundles/org.openhab.binding.miio/README.md, bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.light.ceiling.json, bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.light.ceiling2.json, bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.light.ceiling4.json, bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.light.color1.json, bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.light.lamp1.json
remove the qtyunit from the colortemperature as it is not desirable that OH automatically converts it to C/F and average it together with the room temperatures
=> [miio] remove unit from color temperature

CODEOWNERS, bom/openhab-addons/pom.xml, bundles/org.openhab.binding.mqtt.espmilighthub/NOTICE, bundles/org.openhab.binding.mqtt.espmilighthub/README.md, bundles/org.openhab.binding.mqtt.espmilighthub/pom.xml, bundles/org.openhab.binding.mqtt.espmilighthub/src/main/feature/feature.xml, bundles/org.openhab.binding.mqtt.espmilighthub/src/main/java/org/openhab/binding/mqtt/espmilighthub/internal/ConfigOptions.java, bundles/org.openhab.binding.mqtt.espmilighthub/src/main/java/org/openhab/binding/mqtt/espmilighthub/internal/EspMilightHubBindingConstants.java, bundles/org.openhab.binding.mqtt.espmilighthub/src/main/java/org/openhab/binding/mqtt/espmilighthub/internal/EspMilightHubHandlerFactory.java, bundles/org.openhab.binding.mqtt.espmilighthub/src/main/java/org/openhab/binding/mqtt/espmilighthub/internal/Helper.java, bundles/org.openhab.binding.mqtt.espmilighthub/src/main/java/org/openhab/binding/mqtt/espmilighthub/internal/discovery/EspMilightHubDiscoveryService.java, bundles/org.openhab.binding.mqtt.espmilighthub/src/main/java/org/openhab/binding/mqtt/espmilighthub/internal/handler/EspMilightHubHandler.java, bundles/org.openhab.binding.mqtt.espmilighthub/src/main/resources/OH-INF/config/config.xml, bundles/org.openhab.binding.mqtt.espmilighthub/src/main/resources/OH-INF/thing/thing-types.xml, bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/MqttBindingConstants.java, bundles/pom.xml, features/openhab-addons/src/main/resources/footer.xml
A binding that allows an esp8266 based opensource hub to bridge openHAB to Milight globes.
Binding is used by more than 50 users as it has been around since Feb 2018 but I only just updated it to now no longer use the Paho lib and instead use the openHAB MQTT transport. Forum thread on this binding is found here:
https://community.openhab.org/t/espmilighthub-new-binding-for-milight-limitlessled-and-easybulb/39720
The hardware hub has a github project here:
https://github.com/sidoh/esp8266_milight_hub/releases101
A precompiled JAR for V3.0 can be downloaded here:
https://openhab.jfrog.io/artifactory/libs-pullrequest-local/org/openhab/addons/bundles/org.openhab.binding.mqtt.espmilighthub/3.1.0-SNAPSHOT/org.openhab.binding.mqtt.espmilighthub-3.1.0-SNAPSHOT.jar
Signed-off-by: Matthew Skinner …
=> [espmilighthub] Initial contribution

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/transport/MiIoAsyncCommunication.java
This PR prevents out of sync issues in case devices are too slow to
respond or the timeout is set too short.
closes #9896
=> [miio] validate response id matching command id

bundles/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/handler/ModbusPollerThingHandler.java, bundles/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/handler/ModbusDataThingHandler.java, itests/org.openhab.binding.modbus.tests/src/main/java/org/openhab/binding/modbus/tests/ModbusDataHandlerTest.java
Related: https://github.com/openhab/openhab-addons/issues/7722
After this PR, only Transformation class in modbus uses apache commons lang. I will remove the final references in https://github.com/openhab/openhab-addons/pull/9945: https://github.com/openhab/openhab-addons/pull/9945/commits/36b45ed3af33fbaeac1f12eae019e9e8248b2dcf
=> [modbus] Replace apache commons lang usage with plain java

bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/handler/LinkyHandler.java
Also check data availability for the peak consumption of yesterday
Also log power peak data
=> [linky] One unique method to update daily and weekly data channels

bundles/org.openhab.binding.smartthings/contrib/smartthings/SmartApps/OpenHabAppV2.groovy, bundles/org.openhab.binding.smartthings/src/main/java/org/openhab/binding/smartthings/internal/SmartthingsHandlerFactory.java, bundles/org.openhab.binding.smartthings/src/main/java/org/openhab/binding/smartthings/internal/SmartthingsHubCommand.java, bundles/org.openhab.binding.smartthings/src/main/java/org/openhab/binding/smartthings/internal/discovery/SmartthingsDiscoveryService.java
Signed-off-by: Bob Raker <rjraker@gmail.com>
Most importantly this fixes a bug that caused the discovery service to fail. 
The problem was that I needed a reference to the SmartthingsThingHandlerFactory and I incorrectly created an @Reference to ThingHandlerFactory. At runtime frequently the ThingHandlerFactory from a different bundle would be passed in and I would ignore it. I didn't quite understand how that OSGI mechanism worked. I corrected the problem by creating a new Service interface (named SmartthingsHubCommand that included the methods needed by the discovery service.
Secondly a user opened an issue in my Smartthings github repo [#102 in BobRak/OpenHAB-Smartthings](https://github.com/BobRak/OpenHAB-Smartthings/issues/102) stating the the SmartApp that needs to be loaded onto the …
=> [smartthings] Fix discovery service bug and enhancement to SmartApp for OH3

bundles/org.openhab.binding.miio/README.md, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoDevices.java, bundles/org.openhab.binding.miio/src/main/resources/database/viomi.vacuum.v18-miot.json, bundles/org.openhab.binding.miio/src/test/java/org/openhab/binding/miio/internal/ReadmeHelper.java
@jonasbark would you mind testing the json file with OH3
=> [miio] Add support for viomi S9 vacuum (v18)

bundles/org.openhab.binding.novafinedust/src/main/java/org/openhab/binding/novafinedust/internal/SDS011Handler.java, bundles/org.openhab.binding.novafinedust/src/main/java/org/openhab/binding/novafinedust/internal/sds011protocol/SDS011Communicator.java
- retry logic if port does not yet exist on startup
- do not write sleep command on shutdown if port has issues
- no not register data listener on port but wait for data instead to be
compatible with RFC2217 serial over network implementation (see https://github.com/openhab/openhab-core/issues/2170)
- ignore all buffered data from device during initialization to get the
device into a defined state
=> [novafinedust] Optimizations on access to the serial port

bundles/org.openhab.binding.tivo/README.md, bundles/org.openhab.binding.tivo/src/main/resources/OH-INF/thing/thing-types.xml
Additional refinement to the revamped Tivo binding. All available IR commands were added to the default drop down for the irCommand channel and to the README. Previously the user was directed to find this info in the protocol PDF which has become harder to find as of late.
@AndyXMB
=> [tivo] Add IR code commands to dropdown and documentation

bundles/org.openhab.io.homekit/README.md, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/AbstractHomekitPositionAccessoryImpl.java
add support for dimmer and number item types for current and target position of a window covering accessory as requested in #9972 
=> [homekit] add support for number and dimmer item types to window covering

bundles/org.openhab.binding.nikobus/README.md, bundles/org.openhab.binding.nikobus/src/main/java/org/openhab/binding/nikobus/internal/handler/NikobusDimmerModuleHandler.java, bundles/org.openhab.binding.nikobus/src/main/java/org/openhab/binding/nikobus/internal/handler/NikobusModuleHandler.java, bundles/org.openhab.binding.nikobus/src/main/java/org/openhab/binding/nikobus/internal/handler/NikobusRollershutterModuleHandler.java, bundles/org.openhab.binding.nikobus/src/main/java/org/openhab/binding/nikobus/internal/handler/NikobusSwitchModuleHandler.java, bundles/org.openhab.binding.nikobus/src/main/resources/OH-INF/config/config.xml
New option introduced - reverses command UP -> DOWN and DOWN -> UP for rollershutter - might happen if rollershuter module's output is wired differently, reported by user.
Signed-off-by: Boris Krivonog <boris.krivonog@inova.si>
=> [nikobus] added option to reverse rollershutter commands

bundles/org.openhab.binding.remoteopenhab/src/main/java/org/openhab/binding/remoteopenhab/internal/handler/RemoteopenhabBridgeHandler.java, bundles/org.openhab.binding.remoteopenhab/src/main/java/org/openhab/binding/remoteopenhab/internal/listener/RemoteopenhabStreamingDataListener.java, bundles/org.openhab.binding.remoteopenhab/src/main/java/org/openhab/binding/remoteopenhab/internal/rest/RemoteopenhabRestClient.java
when the remote server is alive again
Related to #9680
=> [remoteopenhab] Detect a remote server shutdown and reconnect properly

bundles/org.openhab.binding.remoteopenhab/src/main/java/org/openhab/binding/remoteopenhab/internal/handler/RemoteopenhabBridgeHandler.java
=> [remoteopenhab] Suppress the IP check

bundles/org.openhab.binding.epsonprojector/README.md, bundles/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/internal/EpsonProjectorDevice.java
Implement the review change from #9770 to always set ready=true on disconnect. Also improved the README to mention projectors with built-in Wi-Fi.
=> [epsonprojector] Always set ready=true on disconnect and improve documentation

bundles/org.openhab.io.homekit/README.md, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitTemperatureSensorImpl.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitThermostatImpl.java
make min/max values for current and target temperatures according to useFahrenheitTemperature settings.
HomeKit protocol works internally always with Celsius. So that we need to convert all temperatures to Celsius as well. 
convertToCelsius method considers the useFahrenheitTemperature and if it is set to true, it converts from Fahrenheit to Celsius
this PR partially fixes #9538.
the missing part is HeatingThresholdTemperature and CoolingThresholdTemperature. A fix for them requires some refactoring of HomekitCharacteristicFactory as it has no access to settings. It will done in a separate PR.
=> [homekit] min and max temperature units according to  useFahrenheitTemperature

bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/connector/PowermaxConnector.java, bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/connector/PowermaxConnectorInterface.java, bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/connector/PowermaxReaderThread.java, bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/connector/PowermaxSerialConnector.java, bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/connector/PowermaxTcpConnector.java, bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/discovery/PowermaxDiscoveryService.java, bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/handler/PowermaxBridgeHandler.java, bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/handler/PowermaxThingHandler.java, bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/message/PowermaxCommManager.java, bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/message/PowermaxMessageEventListener.java, bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/state/PowermaxPanelSettings.java, bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/state/PowermaxState.java, bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/state/PowermaxStateEventListener.java
Catch all exceptions, and take all Powermax things offline in the event
of a communication failure. Also adds a 5-minute watchdog for
connections in Standard (non-Powerlink) mode.
Signed-off-by: Ron Isaacson <isaacson.ron@gmail.com>
Closes #9688
=> [powermax] Improved error handling for Powermax binding

bundles/org.openhab.binding.pushover/README.md
Pushover: Use "html" for format values in README.md
Using "HTML" seems to have no affect when using sendPriorityMessage, but with "html" used in thing definition, it seems that formatting works as expected.
=> Minor README.md update - HTML param formatting value

bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.light.ceiling4.json
The ceiling10 Yeelight lamp has 2 dimmer for brightness:
"bright" for the main light and bg_bright for the ambient light.
Both are of type dimmer and accept percentage values between 1 and 100.
This fix changes the datatype of the bg_bright property from Number
to Dimmer in the device mapping database file ceiling4, which is also
the one that is used for the ceiling10 lamp.
=> [miio] GH-9936 Fixed datatype for brightness of the ambient light

bundles/org.openhab.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/AndroidDebugBridgeBindingConstants.java, bundles/org.openhab.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/AndroidDebugBridgeDevice.java, bundles/org.openhab.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/AndroidDebugBridgeHandler.java, bundles/org.openhab.binding.androiddebugbridge/src/main/resources/OH-INF/thing/thing-types.xml
Signed-off-by: Miguel <miguelwork92@gmail.com>
The binding logs a lot of timeout warnings because it keeps trying to refresh the channels when the android device is not awake, as far as I saw some services stop working when the device go to sleep. This pr aims to fix this by checking that the device is awake before refreshing other channels and also fixes the screen-state channel which was not working correctly.
=> [androiddebugbridge] check device awake state and minor fixes

bundles/org.openhab.binding.hue/README.md, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/HueBindingConstants.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/discovery/HueBridgeDiscoveryParticipant.java, bundles/org.openhab.binding.hue/src/main/resources/OH-INF/binding/binding.xml
**BACKGROUND**
The JUPnP library strictly follows the UPnP specification insofar as if a device fails to send its next 'ssdp:alive' notification within its declared 'maxAge' period, it is immediately considered to be gone. The Philips Hue can sometimes be late in sending its 'ssdp:alive' notifications even though it has not really gone offline. This means that the Hue Bridge is repeatedly removed from, and (re)added to, the InBox. There may be up to fifty such removals and (re)addings per day. This leads to confusion in the UI, and repeated logger messages.
**SOLUTION PART A - CORE**
I have made a Pull Request for a change in [discovery.upnp](https://github.com/openhab/openhab-core/pull/2144) that allows bindings to specify an additional grace period that the core UPnP discovery service …
=> [hue] Implementing "[discovery.upnp] Devices may apply a grace period"

bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/config/SomfyTahomaConfig.java, bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaBridgeHandler.java, bundles/org.openhab.binding.somfytahoma/src/main/resources/OH-INF/config/config.xml
Currently, the Tahoma gateway only accepts at most 10 commands. When sending additional commands, the following error message is logged:
2020-10-01 18:02:44.892 [WARN ] [nal.handler.SomfyTahomaBridgeHandler] - Apply command response: {"errorCode":"EXEC_QUEUE_FULL","error":"Execution queue is full on gateway: # 1223-6154-5758 (soft limit: 10)"}
the command will not be carried out by the Tahoma gateway.
This PR is an improvement of the Somfy Tahoma binding. When the gateway responds with an error, the command is retried after a configurable time for a configurable number of retries.
=> [somfytahoma] Retry command submission when tahoma gateway is busy.

bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/i18n/deconz_de.properties, bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/thing/group-thing-types.xml, bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/thing/light-thing-types.xml, bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/thing/sensor-thing-types.xml
- Use system default channel types for lights
=> [deconz] Use system default channel types for lights

bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/thing/light-thing-types.xml
- Fixed wrong channel type for extended color light
Unfortunately I missed to revert one Color Temperature channel type in #10126 because it was written in a wrong way anyways.
```
2021-02-13 10:33:31.133 [ERROR] [ng.xml.internal.ThingTypeXmlProvider] - Could not register ThingType: deconz:extendedcolorlight
java.lang.IllegalArgumentException: ID segment 'system.color-temperature-abs' contains invalid characters. Each segment of the ID must match the pattern [\w-]*.
at org.openhab.core.common.AbstractUID.validateSegment(AbstractUID.java:98) ~[bundleFile:?]
at org.openhab.core.common.AbstractUID.<init>(AbstractUID.java:76) ~[bundleFile:?]
at org.openhab.core.common.AbstractUID.<init>(AbstractUID.java:49) ~[bundleFile:?]
at org.openhab.core.thing.UID.<init>(UID.java:48) ~[bundleFile:?]
at …
```
=> [deconz] Fixed wrong channel type for extended color light

bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/console/HueCommandExtension.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueGroupHandler.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueLightHandler.java, bundles/org.openhab.binding.hue/src/main/resources/OH-INF/i18n/hue_de.properties, bundles/org.openhab.binding.hue/src/test/java/org/openhab/binding/hue/internal/handler/HueLightHandlerTest.java, bundles/org.openhab.binding.hue/src/test/java/org/openhab/binding/hue/internal/handler/HueLightState.java
- Removed internal vendor Map as the vendor is exposed by the API. We additionally not only support Philips (or Signify Netherlands B.V.) and OSRAM but a lot others too
- Minor improvements of console command messages
- Added "members" property for groups
- Added German translation for scene Channel
=> [hue] Removed internal vendor Map and minor additional improvements

bundles/org.openhab.binding.bluetooth.generic/src/main/resources/OH-INF/thing/generic.xml
Without this, it is not possible to manually define a generic BT thing in the UI as it is not possible to assign a bridge to it.
=> [bluetooth] Define supported bridge types for generic BT devices

bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/HDPowerViewHandlerFactory.java, bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/HDPowerViewWebTargets.java, bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/HubProcessingException.java, bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/discovery/HDPowerViewShadeDiscoveryService.java, bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewHubHandler.java, bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewShadeHandler.java, bundles/org.openhab.binding.hdpowerview/src/test/java/org/openhab/binding/hdpowerview/HDPowerViewJUnitTests.java
**Background**
The HDPowerView hub goes briefly offline every night in the small hours for house-keeping. The binding detects this behaviour and (since it is by design) does not log this as an error.
In OH2, the binding used its own Jersey JAX-RS client, so the binding could detect and handle this offline state fully within its own code. But in OH3 the binding was migrated [via PR 9224](https://github.com/openhab/openhab-addons/pull/9224) to use the Apache CXF JAX-RS client of the OH core instead. This means that the OH core sees the offline condition before the binding can handle it; so the Apache CXF code of the core writes a crash dump into the log every night.
This was reported as an issue here https://github.com/openhab/openhab-addons/issues/10057
**Solution**
This PR migrates the …
=> [hdpowerview] Eliminate nightly crash dump in OH3

bundles/org.openhab.binding.bluetooth.bluegiga/src/main/java/org/openhab/binding/bluetooth/bluegiga/BlueGigaBluetoothCharacteristic.java, bundles/org.openhab.binding.bluetooth.bluegiga/src/main/java/org/openhab/binding/bluetooth/bluegiga/BlueGigaBluetoothDevice.java, bundles/org.openhab.binding.bluetooth.bluez/src/main/java/org/openhab/binding/bluetooth/bluez/internal/BlueZBluetoothDevice.java, bundles/org.openhab.binding.bluetooth.generic/src/main/java/org/openhab/binding/bluetooth/generic/internal/GenericBluetoothHandler.java, bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/BluetoothCharacteristic.java, bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/BluetoothDevice.java, bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/DelegateBluetoothDevice.java, bundles/org.openhab.binding.bluetooth/src/test/java/org/openhab/binding/bluetooth/CharacteristicPropertiesTest.java, bundles/org.openhab.binding.bluetooth/src/test/java/org/openhab/binding/bluetooth/MockBluetoothDevice.java
Bluetooth low energy (BLE) allows central devices (like openHAB) to subscribe for changes. Whenever a subscribed value changes, the central devices is notified immediately so we don't need to wait until the value is polled next time.
Such a behaviour is useful for applications like push buttons or other devices where immediate action is required.
Changes
- Add Characteristics properties to `BluetoothCharacteristic` to make them accessible
- Add `BluetoothDevice.canNotify()` and `BluetoothDevice.isNotifying()`
- Enabled notifications on linked channels where notifications are supported
This is my first pull request to openHAB, feedback is very welcome.
=> [bluetooth.generic] Enable BLE notification for linked channels

bundles/org.openhab.binding.omnilink/pom.xml, bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/HumiditySensorHandler.java, bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/TempSensorHandler.java, bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/TemperatureFormat.java, bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/ThermostatHandler.java
The upstream code the allows connection to the OmniPro uses float values to convert into Omni values, therefore this change was necessary to allow for proper execution of setting temperature commands. 
=> [OmniLink] Fix OmniLink temperature/humidity sensors

bundles/org.openhab.binding.homematic/README.md
Fixes https://github.com/openhab/openhab-addons/issues/10114
Signed-off-by: Eiko Wagenknecht <eiko.wagenknecht@web.de>
=> [homematic] [doc] Usage of custom ID not supported

bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/communication/RotelCommand.java, bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/handler/RotelHandler.java
=> [rotel] Fix command to select PC USB source (ASCII v2 mode)

bundles/org.openhab.binding.modbus/README.md, bundles/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/config/ModbusSerialConfiguration.java, bundles/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/config/ModbusTcpConfiguration.java, bundles/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/handler/AbstractModbusEndpointThingHandler.java, itests/org.openhab.binding.modbus.tests/itest.bndrun, itests/org.openhab.binding.modbus.tests/src/main/java/org/openhab/binding/modbus/tests/AbstractModbusOSGiTest.java, itests/org.openhab.binding.modbus.tests/src/main/java/org/openhab/binding/modbus/tests/ModbusTcpThingHandlerTest.java
Small improvements and fixes:
- Resolve modbus itests to remove dependency to apache commons (was removed in https://github.com/openhab/openhab-addons/pull/10002)
- `AbstractModbusEndpointThingHandler` `poolConfiguration` is never null in practice with properly configured `tcp`/`serial` endpoints. Therefore marking with `@NonNullByDefault({})`
- One of the itests did used mocked ModbusManager, leading to no-op test. Fixed now (test still passes)
More significant finding:
- Now utilizing the defaults documented for `tcp` and `serial` configurations. Presumably wrong values were used if one did not explicitly specify the values, e.g. slave id of zero was used instead of 1, or default delay of zero was used between transactions (`timeBetweenTransactionsMillis`) instead something more robust …
=> [modbus] fix defaults for tcp and serial things and some other minor cleanup

bundles/org.openhab.binding.gpio/README.md
Added instructions in case raspi-config is not available.
=> [gpio] Update README.md

bundles/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/internal/VoiceRSSTTSService.java, bundles/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/internal/VoiceRSSVoice.java, bundles/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/internal/cloudapi/CachedVoiceRSSCloudImpl.java, bundles/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/internal/cloudapi/VoiceRSSCloudAPI.java, bundles/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/internal/cloudapi/VoiceRSSCloudImpl.java, bundles/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/tool/CreateTTSCache.java
=> [voicerss] Add support for voices

bundles/org.openhab.binding.novafinedust/src/main/java/org/openhab/binding/novafinedust/internal/SDS011Handler.java, bundles/org.openhab.binding.novafinedust/src/main/java/org/openhab/binding/novafinedust/internal/sds011protocol/SDS011Communicator.java
Since the device does not follow its own protocol, we do not evaluate its
replies to our configuration commands but rather do a fire and forget.
=> [novafinedust] Use fire and forget commands to configure device

bundles/org.openhab.binding.ipcamera/README.md, bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/DahuaHandler.java, bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/DoorBirdHandler.java, bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/FoscamHandler.java, bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/IpCameraBindingConstants.java, bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/MyNettyAuthHandler.java, bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/handler/IpCameraGroupHandler.java, bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/handler/IpCameraHandler.java, bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/onvif/OnvifDiscovery.java, bundles/org.openhab.binding.ipcamera/src/main/resources/OH-INF/thing/thing-types.xml
These changes will:
+ Add a number of new alarm channels for Dahua and has cleaned up the handling of alarms to make them easier to maintain and extend. #9129 
+ Change scheduleAtFixedRate() to scheduleWithFixedDelay() as requested by @fwolter .
+ Slight change to Digest auths to bring it closer to how CURL handles a digest string. Does not fix any known issues but may help with compatibility.
+ Fix: HLS was not using new output folders and other options until a restart of binding was done. Reported by user on forum.
+ Fix: Some Foscam cameras were not getting detected as Foscam and would get added to inbox as generic onvif.
=> [ipcamera] Improve Dahua alarms

bundles/org.openhab.binding.keba/README.md, bundles/org.openhab.binding.keba/src/main/java/org/openhab/binding/keba/internal/KebaBindingConstants.java, bundles/org.openhab.binding.keba/src/main/java/org/openhab/binding/keba/internal/handler/KeContactHandler.java, bundles/org.openhab.binding.keba/src/main/java/org/openhab/binding/keba/internal/handler/KeContactTransceiver.java, bundles/org.openhab.binding.keba/src/main/resources/OH-INF/thing/kecontact.xml
Signed-off-by: Michael Weger <weger.michael@gmx.net>
My second try of a pull request for the changes discussed in #6347 (comment)
I had some troubles with my first pull requst #10151 and therefore deleted it.
I still have the problem, that parts of this pull request have been developed by @Raketenschnitzel  and I do not know how to reach out to him in order to ask for his approval.
He might reply to this conversation, as he is mentioned ...
All other problems from the first PR should be resolved.
**[keba] Improve connection establishment and stability**
- Connection establishment no longer requires root permissions under Linux.
- Added support of additional P30 x-series stations 'E', 'G' & 'H'
- Extended add-on README
- introduced QuantityTypes (incompatible change)
- removed redundant …
=> [keba] Improve connection establishment and stability

bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/discovery/internal/BluetoothDiscoveryService.java
Since https://github.com/openhab/openhab-webui/pull/920 has been merged, we can return to standard labels for Bluetooth results, see https://github.com/openhab/openhab-addons/pull/10154#issuecomment-779422785.
=> [bluetooth] Adapt labels of discovery results to standard

bundles/org.openhab.binding.loxone/README.md, bundles/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/LxBindingConfiguration.java, bundles/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/LxServerHandler.java, bundles/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/LxWebSocket.java, bundles/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/controls/LxControl.java, bundles/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/types/LxResponse.java, bundles/org.openhab.binding.loxone/src/main/resources/OH-INF/thing/thing-types.xml
With generation 2 of Loxone Miniserver, it is possible to use HTTPS websocket connection to the Miniserver. This PR adds support for it. HTTP connections are still used for some of the commands which receive insensitive data during connection process. The possibility to connect to GEN2 Miniservers over HTTP can be removed in the near future.
What is added:
- new parameter to pass HTTPS port
- new parameter to force HTTP or HTTPS connection (the method to determine what is supported by Miniserver is adviced by the API document, but it is not confirmed that it works in all cases)
- reading new remote configuration parameter to determine if HTTPS is supported
- using HTTPS websocket if possible - all certificates are accepted, it is often the case the Miniservers use locally generated …
=> [loxone] Support for HTTPS websocket connections.

bundles/org.openhab.binding.squeezebox/README.md, bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/SqueezeBoxBindingConstants.java, bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxPlayerHandler.java, bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxServerHandler.java, bundles/org.openhab.binding.squeezebox/src/main/resources/OH-INF/thing/thing-types.xml
Add a sleep channel to the player thing that powers off the player after the specified number of minutes.
=> [squeezebox] Add sleep channel

bundles/org.openhab.binding.alarmdecoder/README.md
This PR mainly fixes a broken link in the README.md file. It used to reference the OH1 binding docs at:
https://www.openhab.org/v2.5/addons/bindings/alarmdecoder1/
But the OH1 binding docs don't appear to be available there anymore for some reason, and I was unable to find anywhere they could be accessed on www.openhab.org. I've changed the link to point to the openhab1-addons repo on github instead. If there is a better location to use, please let me know.
=> [alarmdecoder] Doc update

bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxServerHandler.java
Fixed handling of favorites so that Spotify and Tidal favorites show up in openHAB.
=> [squeezebox] Fixed Spotify and Tidal favorites

bundles/org.openhab.binding.ftpupload/README.md, bundles/org.openhab.binding.ftpupload/src/main/java/org/openhab/binding/ftpupload/internal/FtpUploadHandlerFactory.java, bundles/org.openhab.binding.ftpupload/src/main/java/org/openhab/binding/ftpupload/internal/ftp/FtpServer.java, bundles/org.openhab.binding.ftpupload/src/main/resources/OH-INF/binding/binding.xml
The PR adds the functionality to optionally configure the passive FTP port range according to org.apache.ftpserver (https://mina.apache.org/ftpserver-project/configuration_passive_ports.html).
This is useful when you want to reduce the attack surface and reduce the number of ports to be allowed in your firewall.
Be aware:
I tried several hours to setup the dev environment with intellij (yes, I followed the docs ;)) - but all I got was building a single binding (this one) with mvn in the console. Testing was also hard because openhab debug always pulled the online version of the binding instead my version from the addon directory. 
So for testing there is help needed. Thanks in advance!
=> [ftpupload] Add configurable passive port

CODEOWNERS, bundles/org.openhab.binding.myq/NOTICE, bundles/org.openhab.binding.myq/README.md, bundles/org.openhab.binding.myq/pom.xml, bundles/org.openhab.binding.myq/src/main/feature/feature.xml, bundles/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/MyQBindingConstants.java, bundles/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/MyQDiscoveryService.java, bundles/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/MyQHandlerFactory.java, bundles/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/config/MyQAccountConfiguration.java, bundles/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/config/MyQDeviceConfiguration.java, bundles/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/dto/AccountDTO.java, bundles/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/dto/AccountInfoDTO.java, bundles/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/dto/ActionDTO.java, bundles/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/dto/AddressDTO.java, bundles/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/dto/CountryDTO.java, bundles/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/dto/DeviceDTO.java, bundles/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/dto/DeviceStateDTO.java, bundles/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/dto/DevicesDTO.java, bundles/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/dto/LoginRequestDTO.java, bundles/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/dto/LoginResponseDTO.java, bundles/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/dto/TimeZoneDTO.java, bundles/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/dto/UsersDTO.java, bundles/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/handler/MyQAccountHandler.java, bundles/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/handler/MyQDeviceHandler.java, bundles/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/handler/MyQGarageDoorHandler.java, bundles/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/handler/MyQLampHandler.java, bundles/org.openhab.binding.myq/src/main/resources/OH-INF/binding/binding.xml, bundles/org.openhab.binding.myq/src/main/resources/OH-INF/config/config.xml, bundles/org.openhab.binding.myq/src/main/resources/OH-INF/thing/thing-types.xml, bundles/pom.xml
This introduces a new MyQ binding for openHAB to replace the 1.x version.   Feedback welcome. 
This will replace the 1.x myq binding referenced in #6179
=> [MyQ] Initial commit of the MyQ binding for OH3

bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/parser/CcuVariablesAndScriptsParser.java
In the homematic ccu I can create system variables of type enum.
In method parse() of class CcuVariablesAndScriptsParser the attributes entry.minValue and entry.maxValue contains in this case "" and "" can't be converted to a double. So an exception was raise.
With this additional check the exception doesn't occurs anymore.
=> [homematic] Additional check for convert to double

bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/api/EcobeeApi.java
Fixes https://github.com/openhab/openhab-addons/issues/10235
=> [ecobee] Fix logging levels

bundles/org.openhab.binding.http/src/main/resources/OH-INF/config/config.xml
Added the  mathematical intersection character "∩" to the descriptions for each of the transformation fields; stateTransformation and commandTransformation. This makes it easier to enter this obscure character when building up chained transformations, as opposed to going back and forth to the documentation to find and copy/paste the character. Now it can be copy/pasted from the same page as the form fields.
Signed-off-by: Justin Wilczek <justinwilczek@gmail.com>
=> [http] Add intersection character to descriptions.

bundles/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/internal/handler/EpsonProjectorHandler.java
Fix issue with the Epson projector binding reporting the thing status as ONLINE even when no valid responses were being received. When connecting the binding to a serial port that generated any response, the thing would show as being ONLINE. The fix checks for valid responses and will only switch the thing to ONLINE when a valid response is received.
=> [epsonprojector] Fix ONLINE status reporting

bundles/org.openhab.binding.chromecast/pom.xml, bundles/org.openhab.binding.icalendar/pom.xml, bundles/org.openhab.persistence.dynamodb/pom.xml, bundles/org.openhab.persistence.dynamodb/src/main/feature/feature.xml, bundles/org.openhab.transform.jinja/pom.xml, bundles/org.openhab.voice.pollytts/src/main/feature/feature.xml, pom.xml
* Adds a jackson.version property to simplify managing the version
* Make sure the specified version is used as add-on dependency by excluding Jackson from transitive dependencies
* Use openhab.tp-jackson feature with dynamodb
* Remove jackson-dataformat-cbor dependency from features which is now also provided by the openhab.tp-jackson feature
---
Depends on https://github.com/openhab/openhab-core/pull/2226
=> Upgrade Jackson to 2.12.2

bundles/org.openhab.binding.mcp23017/pom.xml
Fixes #9503. The Pi4j version 1.4 introduces Java 11 compatibility 
by implementing a missing function as native code and thus dropping 
the dependency to the function jdk.internal.misc.SharedSecrets.
See https://github.com/Pi4J/pi4j/issues/442 for details.
Signed-off-by: Michael Rumpf <michael@rumpfonline.de>
=> [mcp32017] Fixes #9503 by updating Pi4j to the recently released version 1.4.

bundles/org.openhab.io.homekit/README.md, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitImpl.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitSettings.java, bundles/org.openhab.io.homekit/src/main/resources/OH-INF/config/config.xml
one of the recent PR has introduced the logic to re-use mDNS service of openHAB instead of creation of a new mDNS instance just for HomeKit. this should reduce the memory footprint. 
however, this change led to some connection issues, especially if openHAB runs in a docker container. 
https://community.openhab.org/t/homekit-no-response-error-on-all-openhab-items/118200/22
this PR 
- makes this mDNS re-use logic configurable and disable by default. 
- fix inconsistency between README and settings. some settings are not available anymore, other like bridge name were missing, the default value were different
- fix some wording as requested in #10227 
=> [homekit] make usage of mDNS configurable

bundles/org.openhab.persistence.mongodb/README.md, bundles/org.openhab.persistence.mongodb/src/main/java/org/openhab/persistence/mongodb/internal/MongoDBPersistenceService.java
Put Item in separate Collections
=> [mongodb] Collection per Item

bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/WLedHandler.java
When you are using WLED with an RGBW strip every time you set a color the white channel is set to maximum brightness.
The source of the problem is the conversion from HSB to RGB that sets the MSB of the resulting int to 0xFF. This is then interpreted as white channel value by WLED.
This PR fixes this problem by zeroing the MSB.
=> [wled] Fix: White LED turns on to max brightness for any RGB changes.

bundles/org.openhab.io.openhabcloud/README.md
Triggered by a question in the  [community ](https://community.openhab.org/t/cannot-delete-things-or-rules-from-myopenhab/117957) I looked into the code think an additional note like:
`In order to use an openHAB UI via the Cloud Connector exposing items is not neccessary. Administrative actions are limited to creating things, items and rules, deleting them is inhibited via the Cloud Connector.`
would help.
=> [openhabcloud] Add note about missing ability to delete things/items/rules.

bundles/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/pro3/AtlonaPro3PortocolHandler.java
Fix bug caused by #9385. When used with the UHD models, the version number in the Thing properties was displaying an incorrect value.
=> [atlona] Fix PROPERTY_VERSION not displaying correct value on UHD models

bundles/org.openhab.binding.oppo/README.md, bundles/org.openhab.binding.oppo/src/main/java/org/openhab/binding/oppo/internal/communication/OppoConnector.java, bundles/org.openhab.binding.oppo/src/main/java/org/openhab/binding/oppo/internal/discovery/OppoDiscoveryService.java, bundles/org.openhab.binding.oppo/src/main/java/org/openhab/binding/oppo/internal/handler/OppoHandler.java
Fix the bug identified in issue #10282. These changes improve the polling routine to properly detect when the player power is on or off. If the connection is interrupted the verbose mode will be set again in case the power to the player was interrupted.
Test build here:
https://github.com/mlobstein/mlobstein-beta-test/raw/master/org.openhab.binding.oppo-3.1.0-SNAPSHOT.jar
https://github.com/mlobstein/mlobstein-beta-test/raw/master/org.openhab.binding.oppo-3.1.0-SNAPSHOT-sources.jar
=> [oppo] Fix setting verbose mode at startup

bundles/org.openhab.binding.mqtt.espmilighthub/src/main/java/org/openhab/binding/mqtt/espmilighthub/internal/handler/EspMilightHubHandler.java
Fixed bug caused by asking a bridge thing for its bridge's UID instead of just the UID.
=> [espmilighthub] Fix things stay initializing

bundles/org.openhab.binding.androiddebugbridge/README.md, bundles/org.openhab.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/AndroidDebugBridgeDevice.java
Signed-off-by: Miguel <miguelwork92@gmail.com>
Try to avoid possible parse errors on the power wake lock channel, improve error messages and fix a typo in the readme.
Based on the feedback I got by email from @Trinitus01.
=> [androiddebugbridge] fix power wake lock and minor fixes

bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaBaseThingHandler.java, bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaBridgeHandler.java, bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/model/SomfyTahomaDevice.java
=> [somfytahoma] Setting of channels at init + UoM for channels

bundles/org.openhab.binding.chromecast/README.md, bundles/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromecastCommander.java, bundles/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/action/ChromecastActions.java, bundles/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/handler/ChromecastHandler.java, bundles/org.openhab.binding.chromecast/src/main/resources/OH-INF/i18n/chromecast.properties
Added play URL actions to chromecast binding. URL and mimeType can be passed to the chromecast binding.
Signed-off-by: Scott Hanson <scooter_seh@yahoo.com> (github: computergeek1507)
=> [chromecast] Added play URL actions to chromecast binding

bundles/org.openhab.binding.airvisualnode/pom.xml, bundles/org.openhab.binding.airvisualnode/src/main/feature/feature.xml
...and also included dependency in the binding.
Related to https://github.com/openhab/openhab-distro/issues/1256
Fixes sandbox release build https://ci.openhab.org/view/Sandbox/job/sandbox-openhab3-release/170/
=> [airvisualnode] Change dependency group id to version available on Maven Central

bundles/org.openhab.binding.caddx/src/main/java/org/openhab/binding/caddx/internal/handler/CaddxBridgeHandler.java, bundles/org.openhab.binding.caddx/src/main/java/org/openhab/binding/caddx/internal/handler/LogEventMessage.java, bundles/org.openhab.binding.caddx/src/main/java/org/openhab/binding/caddx/internal/handler/ThingHandlerPanel.java, bundles/org.openhab.binding.caddx/src/main/java/org/openhab/binding/caddx/internal/handler/ThingHandlerZone.java
On openhab start/restart the things stayed offline until a message arrived from the alarm panel. Changed the behavior by requesting from the panel the state of the things on bridge initialization. 
Also improved the alarm panel messages in case of unknown events.
=> [caddx] Correct thing status on bridge initialization
