bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/discovery/NetatmoModuleDiscoveryService.java
=> [netatmo] Discovery: remove older results

bundles/org.openhab.binding.alarmdecoder/README.md, bundles/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/actions/BridgeActions.java, bundles/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/actions/IBridgeActions.java
This update applies a workaround for issue openhab/openhab-core#1265 as suggested in #8116.
=> [alarmdecoder] Workaround for thing actions bug

bundles/org.openhab.binding.tibber/src/main/java/org/openhab/binding/tibber/internal/handler/TibberHandler.java
=> [tibber] Partial revert of PR 8033

bundles/org.openhab.binding.heos/src/main/java/org/openhab/binding/heos/internal/action/HeosActions.java, bundles/org.openhab.binding.heos/src/main/java/org/openhab/binding/heos/internal/action/IHeosActions.java
=> [heos] Workaround for thing actions bug

bundles/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/automation/modules/OnkyoThingActions.java, bundles/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/automation/modules/OnkyoThingActionsService.java
=> [onkyo] Workaround for thing actions bug

bundles/org.openhab.binding.telegram/src/main/java/org/openhab/binding/telegram/bot/ITelegramActions.java, bundles/org.openhab.binding.telegram/src/main/java/org/openhab/binding/telegram/bot/TelegramActions.java
=> [telegram] Workaround for thing actions bug

bundles/org.openhab.binding.pushbullet/src/main/java/org/openhab/binding/pushbullet/internal/action/IPushbulletActions.java, bundles/org.openhab.binding.pushbullet/src/main/java/org/openhab/binding/pushbullet/internal/action/PushbulletActions.java
=> [pushbullet] Workaround for thing actions bug

bundles/org.openhab.binding.gree/README.md
Just a mini fix to the Doc
Signed-off-by: Markus Michels <markus7017@gmail.com>
=> [gree] Fix item type for mode (String, not Number)

bundles/org.openhab.binding.dmx/src/main/java/org/openhab/binding/dmx/action/DmxActions.java, bundles/org.openhab.binding.dmx/src/main/java/org/openhab/binding/dmx/action/IDmxActions.java
=> [dmx] Workaround for thing actions bug

bundles/org.openhab.binding.sensebox/pom.xml, bundles/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/internal/SenseBoxAPIConnection.java, bundles/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/internal/SenseBoxHandlerFactory.java, bundles/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/internal/config/SenseBoxConfiguration.java, bundles/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/internal/dto/SenseBoxData.java, bundles/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/internal/dto/SenseBoxDescriptor.java, bundles/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/internal/dto/SenseBoxGeometry.java, bundles/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/internal/dto/SenseBoxLoc.java, bundles/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/internal/dto/SenseBoxLocation.java, bundles/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/internal/dto/SenseBoxMeasurement.java, bundles/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/internal/dto/SenseBoxSensor.java, bundles/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/internal/handler/SenseBoxHandler.java, bundles/org.openhab.binding.sensebox/src/main/resources/ESH-INF/thing/box.xml, bundles/org.openhab.binding.sensebox/src/main/resources/ESH-INF/thing/channels.xml
- Removed dependency on `org.apache.commons`
- Added nullness annotations
- Moved model classes into dto folder
- Minor improvements / SAT findings
=> [sensebox] Refactoring of SenseBox Binding

bundles/org.openhab.binding.astro/README.md, bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/action/AstroActions.java, bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/action/IAstroActions.java, bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/config/AstroThingConfig.java, bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/handler/AstroThingHandler.java, bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/handler/MoonHandler.java, bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/handler/SunHandler.java
=> [Astro] Introducing AstroActions service.

bundles/create_openhab_binding_skeleton.cmd, bundles/create_openhab_binding_skeleton.sh, itests/org.openhab.binding.astro.tests/itest.bndrun, itests/org.openhab.binding.avmfritz.tests/itest.bndrun, itests/org.openhab.binding.feed.tests/itest.bndrun, itests/org.openhab.binding.hue.tests/itest.bndrun, itests/org.openhab.binding.max.tests/itest.bndrun, itests/org.openhab.binding.modbus.tests/itest.bndrun, itests/org.openhab.binding.nest.tests/itest.bndrun, itests/org.openhab.binding.ntp.tests/itest.bndrun, itests/org.openhab.binding.systeminfo.tests/itest.bndrun, itests/org.openhab.binding.tradfri.tests/itest.bndrun, itests/org.openhab.binding.wemo.tests/itest.bndrun, itests/org.openhab.io.hueemulation.tests/itest.bndrun
=> Fix missing 2.5.8-SNAPSHOT changes

bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/AVMFritzDynamicCommandDescriptionProvider.java, bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/AVMFritzHandlerFactory.java, bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/dto/templates/TemplateModel.java, bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/AVMFritzBaseBridgeHandler.java, bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/BoxHandler.java, bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/Powerline546EHandler.java, itests/org.openhab.binding.avmfritz.tests/src/main/java/org/openhab/binding/avmfritz/internal/handler/AVMFritzThingHandlerOSGiTest.java
- Changed `apply_template` channel to command options
Testing for https://github.com/openhab/openhab-core/pull/1422 and https://github.com/openhab/openhab-webui/pull/217
=> [avmfritz] Changed 'apply_template' channel to command options

bundles/org.openhab.binding.xmppclient/src/main/java/org/openhab/binding/xmppclient/action/IXMPPActions.java, bundles/org.openhab.binding.xmppclient/src/main/java/org/openhab/binding/xmppclient/action/XMPPActions.java
=> [xmppclient] Workaround for thing actions bug

bundles/org.openhab.binding.dlinksmarthome/pom.xml
Fixes #8194 
Tested with both java 8 and java 11
=> [dlinksmarthome] Fix issue with running on java 11

bundles/org.openhab.binding.astro/README.md
=> [astro] Update README.md

bundles/org.openhab.binding.deconz/README.md, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/BindingConstants.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/discovery/ThingDiscoveryService.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/LightThingHandler.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/types/LightType.java, bundles/org.openhab.binding.deconz/src/main/resources/ESH-INF/thing/light-thing-types.xml
see https://community.openhab.org/t/http-binding-put-request-to-deconz/101888/
=> [deconz] add support for warning device

bundles/org.openhab.binding.deconz/README.md, bundles/org.openhab.binding.deconz/pom.xml, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/dto/SensorConfig.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/dto/SensorMessage.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/DeconzBaseThingHandler.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/LightThingHandler.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/SensorBaseThingHandler.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/ThingConfig.java, bundles/org.openhab.binding.deconz/src/main/resources/ESH-INF/config/config.xml, bundles/org.openhab.binding.deconz/src/main/resources/ESH-INF/thing/sensor-thing-types.xml
- add missing debug messages and remove unnecessary debugging
- allow disabling of lastseen polling (see #7992)
- add reachable status to light things (fixes #8181)
=> [deconz] improve lastSeen channel, add reachable status, fixes

bundles/org.openhab.binding.netatmo/src/main/resources/ESH-INF/config/config.xml
=> [netatmo] Remove unused configuration setting (thermostat)

bundles/org.openhab.binding.robonect/README.md
Improves current documentation. I've successfully connected a Robonect Hx with firmware version 1.2 on a Gardena SILENO city 250 and was able to use all channels. So i'd like to add this device to the tested mowers section.
=> [robonect] Add tested mower and firmware to README.md

bundles/org.openhab.binding.hdpowerview/README.md, bundles/org.openhab.binding.hdpowerview/pom.xml, bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/HDPowerViewBindingConstants.java, bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/HDPowerViewHandlerFactory.java, bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/HDPowerViewWebTargets.java, bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/ActuatorClass.java, bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/CoordinateSystem.java, bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/PosKind.java, bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/PosSeq.java, bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/ShadePosition.java, bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/requests/ShadeIdPosition.java, bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/requests/ShadeIdStop.java, bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/requests/ShadeMove.java, bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/requests/ShadeStop.java, bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/responses/Scenes.java, bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/responses/Shade.java, bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/responses/Shades.java, bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/config/HDPowerViewHubConfiguration.java, bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/config/HDPowerViewSceneConfiguration.java, bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/config/HDPowerViewShadeConfiguration.java, bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/discovery/HDPowerViewHubDiscoveryParticipant.java, bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/discovery/HDPowerViewHubDiscoveryService.java, bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/discovery/HDPowerViewShadeDiscoveryService.java, bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/AbstractHubbedThingHandler.java, bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewHubHandler.java, bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewShadeHandler.java, bundles/org.openhab.binding.hdpowerview/src/main/resources/ESH-INF/thing/thing-types.xml, bundles/org.openhab.binding.hdpowerview/src/test/java/org/openhab/binding/hdpowerview/HDPowerViewJUnitTests.java
This PR resolves Addons Issue #4351, its closed duplicate Issue #4836, and Addons Issue #6910.
It also resolves issues discovered by myself, and adds new features -- as listed below.
However our testing also revealed a UI bug, which has been reported as UI Issue [#290](https://github.com/openhab/openhab-webui/issues/290).
New: Support for dual action shades with a shade secondary position
New: Full rewrite of shade coordinate system to support all types of shades
New: Support for mDNS zero-conf auto discovery
New: Hub data cache hard refresh command (after remote control / manual commands)
New: Refresh Switch channel in hub (can be used to initiate a hard refresh)
New: Support for RefreshType.REFRESH command in hub and shades (initiates a hard refresh)
New: Support for StopMove.Stop …
=> [hdpowerview] extensions, improvements, bug-fixes

bundles/org.openhab.binding.mail/README.md
=> [mail] documentation enhancement.

bundles/org.openhab.binding.tankerkoenig/pom.xml, bundles/org.openhab.binding.tankerkoenig/src/main/java/org/openhab/binding/tankerkoenig/internal/TankerkoenigHandlerFactory.java, bundles/org.openhab.binding.tankerkoenig/src/main/java/org/openhab/binding/tankerkoenig/internal/data/TankerkoenigService.java, bundles/org.openhab.binding.tankerkoenig/src/main/java/org/openhab/binding/tankerkoenig/internal/dto/LittleStation.java, bundles/org.openhab.binding.tankerkoenig/src/main/java/org/openhab/binding/tankerkoenig/internal/dto/OpeningTime.java, bundles/org.openhab.binding.tankerkoenig/src/main/java/org/openhab/binding/tankerkoenig/internal/dto/OpeningTimes.java, bundles/org.openhab.binding.tankerkoenig/src/main/java/org/openhab/binding/tankerkoenig/internal/dto/Prices.java, bundles/org.openhab.binding.tankerkoenig/src/main/java/org/openhab/binding/tankerkoenig/internal/dto/Station.java, bundles/org.openhab.binding.tankerkoenig/src/main/java/org/openhab/binding/tankerkoenig/internal/dto/TankerkoenigDetailResult.java, bundles/org.openhab.binding.tankerkoenig/src/main/java/org/openhab/binding/tankerkoenig/internal/dto/TankerkoenigListResult.java, bundles/org.openhab.binding.tankerkoenig/src/main/java/org/openhab/binding/tankerkoenig/internal/handler/StationHandler.java, bundles/org.openhab.binding.tankerkoenig/src/main/java/org/openhab/binding/tankerkoenig/internal/handler/WebserviceHandler.java, bundles/org.openhab.binding.tankerkoenig/src/main/java/org/openhab/binding/tankerkoenig/internal/serializer/CustomTankerkoenigDetailResultDeserializer.java, bundles/org.openhab.binding.tankerkoenig/src/main/java/org/openhab/binding/tankerkoenig/internal/serializer/CustomTankerkoenigListResultDeserializer.java
- Removed dependency on `org.apache.commons`
- Added nullness annotations
- Moved model classes into dto folder
- Minor improvements / SAT findings
=> [tankerkoenig] Refactoring of Tankerkönig Binding

bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/RotelBindingConstants.java, bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/communication/RotelConnector.java, bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/communication/RotelIpConnector.java, bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/communication/RotelReaderThread.java, bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/communication/RotelSerialConnector.java, bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/communication/RotelSimuConnector.java, bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/handler/RotelHandler.java
=> [rotel] Thread naming

bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/RFXComBindingConstants.java, bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/handler/RFXComBridgeHandler.java
=> [rfxcom] Thread name format updated

bundles/org.openhab.binding.mqtt.generic/xtend_examples.md
[MQTT.GenericThing]  Added Availabilty-Topic Example as it is not covered in the Documentation yet; As suggested in Community-Forum [mqtt-lwt-things-definition-availability-topic](https://community.openhab.org/t/mqtt-lwt-things-definition-availability-topic/103065/11
)
=> [mqtt.generic] Updated Examples of a classic Tasmota-Device incl. undocumented Availability-Topic-Usage

bundles/org.openhab.binding.weathercompany/README.md
- Removed 'apiKey' on thing 'weather-forecast' in examples
=> [weathercompany] Removed 'apiKey' on thing 'weather-forecast' in examples

bundles/org.openhab.binding.astro/src/main/resources/ESH-INF/config/config.xml, bundles/org.openhab.binding.astro/src/main/resources/ESH-INF/i18n/astro_de.properties, bundles/org.openhab.binding.astro/src/main/resources/ESH-INF/thing/moon.xml, bundles/org.openhab.binding.astro/src/main/resources/ESH-INF/thing/sun.xml
- Added missing German translations for config params
=> [astro] Added missing German translations for config params

bundles/org.openhab.binding.lcn/README.md, bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/subhandler/LcnModuleCodeSubHandler.java, bundles/org.openhab.binding.lcn/src/main/resources/ESH-INF/i18n/lcn_de.properties, bundles/org.openhab.binding.lcn/src/main/resources/ESH-INF/thing/thing-types.xml
Added support for PCK-messages of LCN-GFPS fingerprint sensors.
=> [lcn] Implement PCK messages for LCN-GFPS fingerprint sensors

CONTRIBUTING.md, bundles/org.openhab.binding.adorne/README.md, bundles/org.openhab.binding.amazonechocontrol/README.md, bundles/org.openhab.binding.bluetooth.daikinmadoka/README.md, bundles/org.openhab.binding.enocean/src/main/resources/ESH-INF/binding/binding.xml, bundles/org.openhab.binding.etherrain/src/main/resources/ESH-INF/thing/thing-types.xml, bundles/org.openhab.binding.exec/README.md, bundles/org.openhab.binding.ihc/src/main/resources/ESH-INF/thing/channels.xml, bundles/org.openhab.binding.insteon/README.md, bundles/org.openhab.binding.lcn/README.md, bundles/org.openhab.binding.lgwebos/README.md, bundles/org.openhab.binding.mihome/src/main/resources/ESH-INF/thing/basic.xml, bundles/org.openhab.binding.miio/README.base.md, bundles/org.openhab.binding.miio/README.md, bundles/org.openhab.binding.nanoleaf/README.md, bundles/org.openhab.binding.neohub/README.md, bundles/org.openhab.binding.network/README.md, bundles/org.openhab.binding.nuki/src/main/resources/ESH-INF/binding/binding.xml, bundles/org.openhab.binding.opengarage/README.md, bundles/org.openhab.binding.paradoxalarm/README.md, bundles/org.openhab.binding.systeminfo/README.md, bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/model/OSHISysteminfo.java, bundles/org.openhab.binding.tellstick/README.md, bundles/org.openhab.io.homekit/README.md
=> Fix GitHub and openHAB spelling

bundles/org.openhab.binding.heos/README.md
Should be American spelling "Favorites"
=> [heos] Update README.md

.github/ISSUE_TEMPLATE/documentation_issue.md
=> Add documentation issue template

bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/LcnModuleHandler.java
=> [lcn] Fix NullPointerException when updating the binding

bundles/org.openhab.persistence.dynamodb/src/main/java/org/openhab/persistence/dynamodb/internal/AbstractBufferedPersistenceService.java, bundles/org.openhab.persistence.dynamodb/src/main/java/org/openhab/persistence/dynamodb/internal/AbstractDynamoDBItem.java, bundles/org.openhab.persistence.dynamodb/src/main/java/org/openhab/persistence/dynamodb/internal/DynamoDBBigDecimalItem.java, bundles/org.openhab.persistence.dynamodb/src/main/java/org/openhab/persistence/dynamodb/internal/DynamoDBHistoricItem.java, bundles/org.openhab.persistence.dynamodb/src/main/java/org/openhab/persistence/dynamodb/internal/DynamoDBItem.java, bundles/org.openhab.persistence.dynamodb/src/main/java/org/openhab/persistence/dynamodb/internal/DynamoDBPersistenceService.java, bundles/org.openhab.persistence.dynamodb/src/main/java/org/openhab/persistence/dynamodb/internal/DynamoDBQueryUtils.java, bundles/org.openhab.persistence.dynamodb/src/main/java/org/openhab/persistence/dynamodb/internal/DynamoDBStringItem.java, bundles/org.openhab.persistence.dynamodb/src/test/java/org/openhab/persistence/dynamodb/internal/AbstractDynamoDBItemSerializationTest.java, bundles/org.openhab.persistence.dynamodb/src/test/java/org/openhab/persistence/dynamodb/internal/AbstractTwoItemIntegrationTest.java, bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/InfluxDBPersistenceService.java, bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/InfluxDBHistoricItem.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcBaseDAO.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/model/JdbcHistoricItem.java, bundles/org.openhab.persistence.jpa/src/main/java/org/openhab/persistence/jpa/internal/JpaHistoricItem.java, bundles/org.openhab.persistence.jpa/src/main/java/org/openhab/persistence/jpa/internal/JpaPersistenceService.java, bundles/org.openhab.persistence.jpa/src/main/java/org/openhab/persistence/jpa/internal/model/JpaPersistentItem.java, bundles/org.openhab.persistence.mapdb/src/main/java/org/openhab/persistence/mapdb/internal/MapDbItem.java, bundles/org.openhab.persistence.mongodb/src/main/java/org/openhab/persistence/mongodb/internal/MongoDBItem.java, bundles/org.openhab.persistence.mongodb/src/main/java/org/openhab/persistence/mongodb/internal/MongoDBPersistenceService.java, bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jItem.java, bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java
Related to https://github.com/openhab/openhab-core/pull/1588
=> Switched persistence services from Date to ZonedDateTime

bundles/org.openhab.binding.lcn/README.md
=> [lcn] Remove non-openHAB related information, minor improvements

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoVacuumHandler.java
=> [miio] fix timestamp for safefiles

bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/handler/NikoHomeControlThermostatHandler.java, bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/NhcThermostat.java, bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc2/NhcDevice2.java, bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc2/NhcService2.java, bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc2/NikoHomeControlCommunication2.java, bundles/org.openhab.binding.nikohomecontrol/src/main/resources/ESH-INF/thing/thing-types.xml
Fixes #8099 
Includes some further code improvements to make the binding more resilient to unexpected data from the Niko Home Control system.
Signed-off-by: Mark Herwege mark.herwege@telenet.be
=> [nikohomecontrol] fix Digital Black Thermostat NPE

bundles/org.openhab.persistence.mapdb/src/main/java/org/openhab/persistence/mapdb/internal/MapDbPersistenceService.java
=> Fix ConfigConstants deprecation

CODEOWNERS
Update to CODEOWNERS file as requested by @berndpfrommer in #8261.
=> [alarmdecoder] Update codeowners file

bundles/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/handler/ModbusPollerThingHandler.java
=> [modbus] poller logs PollResult correctly

bundles/org.openhab.binding.opensprinkler/.classpath, bundles/org.openhab.binding.opensprinkler/README.md, bundles/org.openhab.binding.opensprinkler/pom.xml, bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/OpenSprinklerBindingConstants.java, bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/api/OpenSprinklerApi.java, bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/api/OpenSprinklerHttpApiV100.java, bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/handler/OpenSprinklerDeviceHandler.java, bundles/org.openhab.binding.opensprinkler/src/main/resources/ESH-INF/thing/thing-types.xml
This PR adds the water level channel to the opensprinkler device. This channel is calculated based on weather data and influences how long the watering will last
=> [opensprinkler] Add water level channel

bundles/create_openhab_binding_skeleton.cmd, bundles/create_openhab_binding_skeleton.sh, itests/org.openhab.binding.astro.tests/itest.bndrun, itests/org.openhab.binding.avmfritz.tests/itest.bndrun, itests/org.openhab.binding.feed.tests/itest.bndrun, itests/org.openhab.binding.hue.tests/itest.bndrun, itests/org.openhab.binding.max.tests/itest.bndrun, itests/org.openhab.binding.modbus.tests/itest.bndrun, itests/org.openhab.binding.nest.tests/itest.bndrun, itests/org.openhab.binding.ntp.tests/itest.bndrun, itests/org.openhab.binding.systeminfo.tests/itest.bndrun, itests/org.openhab.binding.tradfri.tests/itest.bndrun, itests/org.openhab.binding.wemo.tests/itest.bndrun, itests/org.openhab.io.hueemulation.tests/itest.bndrun
=> Fix missing 2.5.9-SNAPSHOT changes

bundles/org.openhab.binding.verisure/src/main/java/org/openhab/binding/verisure/internal/VerisureSession.java
=> [verisure] Fix for #8315

bundles/org.openhab.binding.network/README.md, bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/NetworkHandlerConfiguration.java, bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/WakeOnLanPacketSender.java, bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/action/INetworkActions.java, bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/action/NetworkActions.java, bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/handler/NetworkHandler.java, bundles/org.openhab.binding.network/src/main/resources/ESH-INF/thing/thing-types.xml, bundles/org.openhab.binding.network/src/test/java/org/openhab/binding/network/internal/WakeOnLanPacketSenderTest.java
Fixes #3799
---
Adds an optional MAC address to existing devices which can be used to use WoL using Thing actions.
=> [network] Add support for Wake-on-LAN thing action

pom.xml
Related to openhab/openhab-core#1576
=> Update optional Swagger annotations import package name

bundles/org.openhab.binding.fsinternetradio/README.md
=> [fsinternetradio] Add Silvercrest SIRD 14 C1 radio modes to documentation

bundles/org.openhab.binding.samsungtv/README.md
And ordered models alphabetically.
Replaces #6634
=> [samsungtv] Added KU6519 as supported model

bundles/org.openhab.persistence.rrd4j/README.md, features/openhab-addons-external/src/main/resources/conf/rrd4j.cfg
Added changes to OpenHAB v3 as requested by @kaikreuzer
=> [rrd4j] documentation improvements and extensions

bundles/org.openhab.persistence.dynamodb/src/main/java/org/openhab/persistence/dynamodb/internal/DynamoDBQueryUtils.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcBaseDAO.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcDerbyDAO.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcPostgresqlDAO.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/utils/StringUtilsExt.java, bundles/org.openhab.persistence.jpa/src/main/java/org/openhab/persistence/jpa/internal/JpaPersistenceService.java, bundles/org.openhab.persistence.jpa/src/main/java/org/openhab/persistence/jpa/internal/model/JpaPersistentItem.java
=> [persistence] addressed deprecation warnings

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/MiIoDatabaseWatchService.java
Provide a message with path to facilitate users to find the right path
to store the json db files (avoiding many questions on the community)
=> [miio] Start watchservice message with path

bundles/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/handler/ModbusDataThingHandler.java
Resolves #6113
Also adjusted some error level logging lower since the thing status
will be updated in any case, no need to repeat it in the logs.
Ping @Rossko57 , please review
=> [modbus] Some logging adjustments for data thing

bundles/org.openhab.binding.modbus/src/main/resources/ESH-INF/thing/thing-data.xml, bundles/org.openhab.io.transport.modbus/src/test/java/org/openhab/io/transport/modbus/test/BitUtilitiesCommandToRegistersTest.java
Resolves #4148
I also added some more tests to cover the relevant range of the value types.
Ping @Rossko57 , please review when you have a moment
=> [modbus] Modbus write types explanation

bundles/org.openhab.binding.pentair/README.md
Fixed syntax error in the example items, added USB Serial example and expanded the sitemap to be a complete example.
Signed-off-by: Mark Carbonaro <mark.carbonaro@gmail.com>
=> [pentair] Some improvements to the pentair documentation.

bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc2/NikoHomeControlCommunication2.java
Issue [#8099](https://github.com/openhab/openhab-addons/issues/8099) was not resolved with PR [#8275](https://github.com/openhab/openhab-addons/pull/8275). This PR fixes it and has been tested by a user owning Digital Black thermostats.
=> [nikohomecontrol] Fix Digital Black thermostat.

bundles/org.openhab.binding.modbus/README.md
Signed-Off-By: Markus Storm <markus.storm@gmx.net>
=> [modbus] Add hints to potential problems on Modbus readout

bundles/org.openhab.binding.dsmr/src/main/java/org/openhab/binding/dsmr/internal/device/SmartyDecrypter.java
PR #8383 was created before Spotless was enforced.
=> Fix broken build

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/ActionConditions.java, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/MiIoDeviceAction.java, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoBasicHandler.java, bundles/org.openhab.binding.miio/src/main/resources/database/dreame.vacuum.mc1808-miot.json
* support for miot action commands
* new conditional action
* Implement start/stop vacuum for dreame.vacuum.mc1808
=> [miio] support for miot action commands

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoBasicHandler.java
=> [miio] Fix for $value$ wrong at 2nd time

bundles/org.openhab.binding.onkyo/README.md, bundles/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/OnkyoModel.java, bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-rz900.xml
=> [onkyo] Add support for TX-RZ900 

bundles/org.openhab.binding.amazonechocontrol/README.md
=> [amazonechocontrlol] Update README.md

bundles/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/discovery/XiaomiBridgeDiscoveryService.java
=> [mihome] Workaround for wrong serial number returned by the gateway

bundles/org.openhab.io.imperihome/src/main/java/org/openhab/io/imperihome/internal/handler/DeviceHistoryHandler.java
Related to https://github.com/openhab/openhab-core/pull/1623
=> [imperihome] Fix FilterCriteria deprecations

bundles/org.openhab.persistence.dynamodb/src/main/java/org/openhab/persistence/dynamodb/internal/DynamoDBQueryUtils.java, bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/InfluxDBPersistenceService.java, bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/influx1/Influx1FilterCriteriaQueryCreatorImpl.java, bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/influx2/Influx2FilterCriteriaQueryCreatorImpl.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcBaseDAO.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcDerbyDAO.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcPostgresqlDAO.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/utils/StringUtilsExt.java, bundles/org.openhab.persistence.jpa/src/main/java/org/openhab/persistence/jpa/internal/JpaPersistenceService.java, bundles/org.openhab.persistence.mongodb/src/main/java/org/openhab/persistence/mongodb/internal/MongoDBPersistenceService.java, bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java
Depends on https://github.com/openhab/openhab-core/pull/1623
=> Use renamed FilterCriteria methods

bundles/org.openhab.binding.sensibo/src/main/java/org/openhab/binding/sensibo/internal/client/RequestLogger.java, bundles/org.openhab.binding.sensibo/src/main/java/org/openhab/binding/sensibo/internal/handler/SensiboAccountHandler.java, bundles/org.openhab.binding.sensibo/src/main/java/org/openhab/binding/sensibo/internal/handler/SensiboSkyHandler.java
=> [sensibo] Fix for dynamic channels disappearing when device goes intermittent offline

bundles/org.openhab.binding.hpprinter/src/main/java/org/openhab/binding/hpprinter/internal/HPPrinterBinder.java, bundles/org.openhab.binding.hpprinter/src/main/java/org/openhab/binding/hpprinter/internal/HPPrinterHandler.java, bundles/org.openhab.binding.hpprinter/src/main/java/org/openhab/binding/hpprinter/internal/api/HPServerResult.java, bundles/org.openhab.binding.hpprinter/src/main/java/org/openhab/binding/hpprinter/internal/api/HPUsage.java
Signed-off-by: Stewart Cossey <stewart.cossey@gmail.com>
Small changes to stop showing null warnings in the compiler.
There is one SuppressWarnings on a function which I felt was appropriate. However if there is a more "proper" way to do this then please suggest.
=> [hpprinter] Fix null check compiler warnings

bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/protocol/RemoteControllerLegacy.java
- Removed dependency on `org.apache.commons.net`
Related to #7722 
=> [samsungtv] Removed dependency on 'org.apache.commons.net'

bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudService.java
Don't follow 302 redirects (jetty default),  these should be forwarded back to the cloud service.  This is required for authentication to work in OH 3.0
=> [openhabcloud] Don't follow 302 redirects

bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/SomfyTahomaHandlerFactory.java, bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/discovery/SomfyTahomaItemDiscoveryService.java, bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaBaseThingHandler.java, bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaBridgeHandler.java
this PR improves and simplyfies the discovery service registration
=> [somfytahoma] improved discovery service registration

CODEOWNERS, bundles/org.openhab.io.transport.modbus/pom.xml, bundles/org.openhab.io.transport.modbus/src/main/feature/feature.xml, bundles/org.openhab.io.transport.modbus/src/main/java/org/openhab/io/transport/modbus/internal/ModbusConnectionPool.java, bundles/org.openhab.io.transport.modbus/src/main/java/org/openhab/io/transport/modbus/internal/ModbusPoolConfig.java, itests/org.openhab.binding.modbus.tests/itest.bndrun
Resolves many bugs present in the old version. Despite the large bump in version, seems to run just fine based on quick testing.
Marking as WIP -- more extended testing ongoing in community forum.
=> [modbus] Update apache commons pool2 to latest version

bundles/org.openhab.binding.evohome/README.md
Added units to the refresh rate
=> [evohome] Minor clarification to the README.md

bundles/org.openhab.binding.bticinosmarther/src/main/java/org/openhab/binding/bticinosmarther/internal/discovery/SmartherModuleDiscoveryService.java, bundles/org.openhab.binding.draytonwiser/src/main/java/org/openhab/binding/draytonwiser/internal/discovery/DraytonWiserDiscoveryService.java, bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/discovery/EnOceanUsbSerialDiscoveryParticipant.java, bundles/org.openhab.binding.neeo/src/main/java/org/openhab/binding/neeo/internal/UidUtils.java, bundles/org.openhab.binding.neeo/src/main/java/org/openhab/binding/neeo/internal/discovery/NeeoDeviceDiscoveryService.java, bundles/org.openhab.binding.neeo/src/main/java/org/openhab/binding/neeo/internal/discovery/NeeoRoomDiscoveryService.java, bundles/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/discovery/OwDiscoveryService.java, bundles/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/PlugwiseThingDiscoveryService.java, bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyBaseHandler.java
- Fixed OH3 add-ons port build by adding additional null checks
See https://github.com/openhab/openhab-core/pull/1414#issuecomment-691948514
//CC @wborn
=> Fixed OH3 add-ons port build

bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/handler/GreeAirDevice.java, bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/handler/GreeHandler.java
@Hilbrand For whatever reason the last PR didn't included the fix for the endless loop, so I need to bother with another one
=> [gree] Fix endless loop in command handler (previous PR)

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/discovery/MiIoDiscoveryParticipant.java, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoBasicHandler.java
Reverts openhab/openhab-addons#8463
=> Revert "[miio] add automatic tokens to miio MDNSDiscoveryParticipant"

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/discovery/MiIoDiscoveryParticipant.java, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoBasicHandler.java
resubmit of #8463 as that was somehow reverted
=> [miio] add automatic tokens to miio MDNSDiscoveryParticipant

bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/SomfyTahomaHandlerFactory.java, bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/discovery/SomfyTahomaItemDiscoveryService.java, bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaBaseThingHandler.java, bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaBridgeHandler.java
this PR brings code cleanup and getting rid of most compile warnings for the SomfyTahoma binding
=> [somfytahoma] code cleanup

bundles/org.openhab.binding.miio/src/test/java/org/openhab/binding/miio/internal/RoboMapViewer.java
Improve the printing of the command based on feedback on forum
https://community.openhab.org/t/xiaomi-vacuum-map-viewer-to-find-coordinates-for-zone-cleaning/103500/25
=> [miio] Offline mapviewer fix command formatting

bundles/org.openhab.binding.miio/README.md, bundles/org.openhab.binding.miio/src/main/resources/ESH-INF/thing/vacuumThing.xml, bundles/org.openhab.binding.miio/src/main/resources/database/dreame.vacuum.mc1808-miot.json
=> [miio] Fix maven warning for dynamic channel

bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/ChannelTypeUtils.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/camera/CameraHandler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/AbstractNetatmoThingHandler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/NetatmoDeviceHandler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/NetatmoModuleHandler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/station/NAMainHandler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/station/NAModule1Handler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/station/NAModule2Handler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/station/NAModule3Handler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/station/NAModule4Handler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/welcome/NAWelcomeHomeHandler.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/welcome/NAWelcomePersonHandler.java
=> [netatmo] Make thing offline if API returns unreachable

CODEOWNERS, bundles/org.openhab.binding.venstarthermostat/README.md, bundles/org.openhab.binding.venstarthermostat/pom.xml, bundles/org.openhab.binding.venstarthermostat/src/main/java/org/openhab/binding/venstarthermostat/internal/discovery/VenstarThermostatDiscoveryService.java, bundles/org.openhab.binding.venstarthermostat/src/main/java/org/openhab/binding/venstarthermostat/internal/handler/VenstarThermostatHandler.java, bundles/org.openhab.binding.venstarthermostat/src/main/java/org/openhab/binding/venstarthermostat/internal/model/VenstarResponse.java, bundles/org.openhab.binding.venstarthermostat/src/main/java/org/openhab/binding/venstarthermostat/internal/model/VenstarSensor.java, bundles/org.openhab.binding.venstarthermostat/src/main/java/org/openhab/binding/venstarthermostat/internal/model/VenstarSensorData.java, bundles/org.openhab.binding.venstarthermostat/src/main/java/org/openhab/binding/venstarthermostat/internal/model/VenstarSystemState.java, bundles/org.openhab.binding.venstarthermostat/src/main/resources/ESH-INF/thing/thing-types.xml
fixes representation property key in discovery, adds thing documentation, removes some blank lines, adds author to CODEOWNERS, runs spotless formatter.
=> [venstarthermostat] PR related fixes

bundles/org.openhab.binding.venstarthermostat/README.md, bundles/org.openhab.binding.venstarthermostat/src/main/java/org/openhab/binding/venstarthermostat/internal/VenstarThermostatConfiguration.java, bundles/org.openhab.binding.venstarthermostat/src/main/java/org/openhab/binding/venstarthermostat/internal/handler/VenstarThermostatHandler.java, bundles/org.openhab.binding.venstarthermostat/src/main/resources/ESH-INF/thing/thing-types.xml
=> [venstarthermostat] Moves 'url' from a thing property to a configuration option. 

bundles/org.openhab.binding.venstarthermostat/README.md
=> [venstarthermostat] Updates README

itests/org.openhab.binding.nest.tests/itest.bndrun
Related to openhab/openhab-core#1656
=> [nest] Resolve itest.bndrun runbundles

bundles/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/utils/ByteArrayFileCache.java, bundles/org.openhab.binding.darksky/src/main/java/org/openhab/binding/darksky/internal/utils/ByteArrayFileCache.java, bundles/org.openhab.binding.darksky/src/test/java/org/openhab/binding/darksky/internal/utils/ByteArrayFileCacheTest.java, bundles/org.openhab.binding.exec/src/main/java/org/openhab/binding/exec/internal/ExecWhitelistWatchService.java, bundles/org.openhab.binding.icalendar/src/main/java/org/openhab/binding/icalendar/internal/handler/ICalendarHandler.java, bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/utils/ByteArrayFileCache.java, bundles/org.openhab.binding.kodi/src/test/java/org/openhab/binding/kodi/internal/utils/ByteArrayFileCacheTest.java, bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/MaxBackupUtils.java, bundles/org.openhab.binding.meteoblue/src/main/java/org/openhab/binding/meteoblue/internal/Forecast.java, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/MiIoDatabaseWatchService.java, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/cloud/CloudUtil.java, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoVacuumHandler.java, bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/utils/ByteArrayFileCache.java, bundles/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/protocol/AbstractConnection.java, bundles/org.openhab.io.mqttembeddedbroker/src/main/java/org/openhab/io/mqttembeddedbroker/internal/EmbeddedBrokerService.java, bundles/org.openhab.io.mqttembeddedbroker/src/test/java/org/openhab/io/mqttembeddedbroker/internal/MqttEmbeddedBrokerServiceTest.java, bundles/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/internal/NeeoConstants.java, bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudService.java, bundles/org.openhab.transform.exec/src/main/java/org/openhab/transform/exec/internal/ExecTransformationWhitelistWatchService.java, bundles/org.openhab.transform.javascript/src/main/java/org/openhab/transform/javascript/internal/TransformationScriptWatcher.java, bundles/org.openhab.transform.xslt/src/main/java/org/openhab/transform/xslt/internal/XsltTransformationService.java, bundles/org.openhab.voice.pollytts/src/main/java/org/openhab/voice/pollytts/internal/PollyTTSService.java, bundles/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/internal/VoiceRSSTTSService.java
Related to https://github.com/openhab/openhab-core/pull/1659
=> Fix ConfigConstants deprecations

bundles/org.openhab.io.imperihome/src/main/java/org/openhab/io/imperihome/internal/handler/DeviceHistoryHandler.java, bundles/pom.xml
=> [imperihome] Adapt call to ZDT in Persistence API

bundles/org.openhab.transform.map/src/test/java/org/openhab/transform/map/internal/MapTransformationServiceTest.java
Depends on openhab/openhab-core#1661
=> Reenable MapTransformationServiceTest

bom/openhab-addons/pom.xml, bundles/org.openhab.binding.venstarthermostat/src/main/feature/feature.xml
=> [venstarthermostat] Fix venstarthermostat feature.xml

bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/radiora/handler/LutronHandler.java, bundles/org.openhab.binding.neato/src/main/java/org/openhab/binding/neato/internal/handler/NeatoAccountHandler.java, bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/handler/OpenSprinklerDeviceHandler.java, bundles/org.openhab.binding.seneye/src/main/java/org/openhab/binding/seneye/internal/handler/SeneyeHandler.java
Related to https://github.com/openhab/openhab-core/pull/1665
=> Fix BaseThingHandler.initialize() deprecations

CODEOWNERS, bom/openhab-addons/pom.xml
See https://github.com/openhab/openhab-addons/pull/8394#issuecomment-696648523
=> [yioremote] added missing entries in bom and CODEOWNERS

itests/org.openhab.binding.avmfritz.tests/itest.bndrun, itests/pom.xml
Depends on https://github.com/openhab/openhab-core/pull/1670
Related to #8537
=> [avmfritz] Reenable itest

bundles/org.openhab.binding.lametrictime/src/main/java/org/openhab/binding/lametrictime/internal/LaMetricTimeHandlerFactory.java, bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/TeslaHandlerFactory.java
=> Remove Jersey ClientBuilder compatibility

bundles/org.openhab.binding.bluetooth.blukii/src/main/feature/feature.xml, bundles/org.openhab.binding.linky/src/main/feature/feature.xml, bundles/org.openhab.binding.melcloud/src/main/feature/feature.xml, bundles/org.openhab.binding.modbus.helioseasycontrols/src/main/feature/feature.xml, bundles/org.openhab.binding.modbus.studer/src/main/feature/feature.xml, bundles/org.openhab.binding.nzwateralerts/src/main/feature/feature.xml, bundles/org.openhab.binding.rotel/src/main/feature/feature.xml, bundles/org.openhab.binding.siemensrds/src/main/feature/feature.xml, bundles/org.openhab.binding.sonyprojector/src/main/feature/feature.xml, bundles/org.openhab.binding.volvooncall/src/main/feature/feature.xml, bundles/org.openhab.persistence.influxdb/src/main/feature/feature.xml
Found thanks to a new check: https://github.com/openhab/static-code-analysis/pull/395
=> Fix feature names in feature.xml files

bundles/org.openhab.binding.comfoair/src/main/java/org/openhab/binding/comfoair/internal/ComfoAirHandler.java
Channel states are not updated on commands, including additional channels affected by the change.
This should fix the bug and probably be backported to 2.5.10.
=> [comfoair] fix channel updates

bundles/org.openhab.persistence.dynamodb/src/main/feature/feature.xml, bundles/org.openhab.persistence.influxdb/src/main/feature/feature.xml, bundles/org.openhab.persistence.jdbc/src/main/feature/feature.xml, bundles/org.openhab.persistence.jpa/src/main/feature/feature.xml, bundles/org.openhab.persistence.rrd4j/src/main/feature/feature.xml
Related to https://github.com/openhab/openhab-addons/pull/8532
=> Fixed mvn reference for config files

bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/ChannelStateTests.java, bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/internal/handler/GenericThingHandlerTests.java, bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/action/MQTTActions.java, bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/discovery/MQTTTopicDiscoveryService.java, bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/handler/BrokerHandler.java, bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/handler/SystemBrokerHandler.java, bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/internal/MqttBrokerHandlerFactory.java, bundles/org.openhab.io.mqttembeddedbroker/src/test/java/org/openhab/io/mqttembeddedbroker/internal/MqttEmbeddedBrokerServiceTest.java
Related to https://github.com/openhab/openhab-core/pull/1671
=> Fix MQTT transport deprecations

bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc2/NhcMqttConnection2.java
See https://github.com/openhab/openhab-addons/pull/8570#issuecomment-698813909
=> [nikohomecontrol] Fix deprecated MQTT transport call

bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/handler/AirVisualNodeHandler.java, bundles/org.openhab.binding.deconz/src/test/java/org/openhab/binding/deconz/DeconzTest.java, bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/lib/serverconnection/impl/HttpTransportImpl.java, bundles/org.openhab.binding.foobot/src/test/java/org/openhab/binding/foobot/internal/handler/FoobotAccountHandlerTest.java, bundles/org.openhab.binding.foobot/src/test/java/org/openhab/binding/foobot/internal/handler/FoobotDeviceHandlerTest.java, bundles/org.openhab.binding.fsinternetradio/src/test/java/org/openhab/binding/fsinternetradio/test/RadioServiceDummy.java, bundles/org.openhab.binding.millheat/src/test/java/org/openhab/binding/millheat/internal/MillHeatAccountHandlerTest.java, bundles/org.openhab.binding.sensibo/src/test/java/org/openhab/binding/sensibo/internal/WireHelper.java, bundles/org.openhab.binding.sensibo/src/test/java/org/openhab/binding/sensibo/internal/handler/SensiboAccountHandlerTest.java, bundles/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/SpotifyAuthService.java, bundles/org.openhab.binding.tplinksmarthome/src/test/java/org/openhab/binding/tplinksmarthome/internal/model/ModelTestUtil.java, bundles/org.openhab.binding.yamahareceiver/src/test/java/org/openhab/binding/yamahareceiver/internal/ResponseLoader.java, itests/org.openhab.binding.feed.tests/src/main/java/org/openhab/binding/feed/test/FeedHandlerTest.java
Specifically the toString reading from inputstream.
Related to #7722
=> Removed (most) usage to IOUtils.toString

.github/PULL_REQUEST_TEMPLATE.md
=> Fixed urls in template that resulted in a 404

bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/action/DimmerActions.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/config/DimmerConfig.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/GreenModeHandler.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/TimeclockHandler.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/protocol/LutronDuration.java
Replaces calls to methods deprecated in Java 11.
=> [lutron] Replace calls to methods deprecated in Java 11

bundles/org.openhab.binding.yioremote/README.md, bundles/org.openhab.binding.yioremote/src/main/java/org/openhab/binding/yioremote/internal/YIOremoteBindingConstants.java, bundles/org.openhab.binding.yioremote/src/main/java/org/openhab/binding/yioremote/internal/YIOremoteDockHandler.java, bundles/org.openhab.binding.yioremote/src/main/java/org/openhab/binding/yioremote/internal/utils/Websocket.java, bundles/org.openhab.binding.yioremote/src/main/java/org/openhab/binding/yioremote/internal/utils/WebsocketInterface.java
Fixes #8593
Changed of reconnection issue
Changed of thing-type.xml
Changed readme
=> [yioremote] Fixed reconnection and thing creation issues

bundles/org.openhab.io.hueemulation/pom.xml, bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/ConfigStore.java, bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/HueEmulationService.java, bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/dto/HueAuthorizedConfig.java, bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/dto/HueStateBulb.java, bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/dto/HueStateColorBulb.java, bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/dto/changerequest/HueStateChange.java, bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/rest/ConfigurationAccess.java, bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/rest/LightsAndGroups.java, bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/rest/Rules.java, bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/rest/Scenes.java, bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/rest/Schedules.java, bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/rest/Sensors.java, bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/rest/StatusResource.java, bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/rest/UserManagement.java, bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/upnp/UpnpServer.java, bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/rest/CommonSetup.java, bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/rest/ItemUIDtoHueIDMappingTests.java, bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/rest/LightsAndGroupsTests.java, bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/rest/RulesTests.java, bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/rest/SceneTests.java, bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/rest/ScheduleTests.java, bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/rest/SensorTests.java, bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/rest/UsersAndConfigTests.java, bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/rest/mocks/ConfigStoreWithoutMetadata.java, bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/rest/mocks/DummyRuleRegistry.java, bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/upnp/UpnpTests.java, bundles/pom.xml, features/openhab-addons/pom.xml
=> [hueemulation] Replace Jersey dependency with JAX-RS Whiteboard

bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/discovery/internal/BluetoothDiscoveryService.java, bundles/org.openhab.binding.bluetooth/src/test/java/org/openhab/binding/bluetooth/TestUtils.java, bundles/org.openhab.binding.bluetooth/src/test/java/org/openhab/binding/bluetooth/discovery/internal/BluetoothDiscoveryServiceTest.java
=> [bluetooth] Fix bluetooth unit tests

bundles/org.openhab.binding.nuvo/README.md, bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/NuvoBindingConstants.java, bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/communication/NuvoCommand.java, bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/handler/NuvoHandler.java, bundles/org.openhab.binding.nuvo/src/main/resources/OH-INF/thing/channels.xml
=> [nuvo] Add favorites selection channel and fix a few bugs

bundles/org.openhab.binding.comfoair/src/main/java/org/openhab/binding/comfoair/internal/datatypes/DataTypeTemperature.java
Signed-off-by: Hans Böhm <h.boehm@gmx.at>
fixes #8600
=> [comfoair] fix ewt temperatures

bundles/org.openhab.binding.tradfri/README.md
Minor updates to the tradfri README:
- Adding blinds to list of supported devices
- Minor grammar and syntax fixes
=>  [tradfri] Doc update: add blinds to list of supported devices and minor grammar fixes

itests/org.openhab.binding.avmfritz.tests/itest.bndrun, itests/org.openhab.binding.feed.tests/itest.bndrun, itests/org.openhab.binding.hue.tests/itest.bndrun, itests/org.openhab.binding.nest.tests/itest.bndrun, itests/org.openhab.binding.wemo.tests/itest.bndrun
Depends on openhab/openhab-core#1685
=> Resolve itest bundles for Xtext upgrade

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/robot/RRMapDraw.java, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/robot/RRMapFileParser.java
Add newly found mapelements for obstacles
=> [miio] add new map elements

bundles/org.openhab.binding.magentatv/src/main/resources/OH-INF/i18n/magentatv_de.properties, bundles/org.openhab.binding.magentatv/src/main/resources/OH-INF/thing/thing-types.xml
a quick one: added representationProperty to thing definition
=> [magentatv] Adapted to OH 3.0

bundles/org.openhab.binding.gree/src/main/resources/OH-INF/thing/thing-types.xml
representationProperty added to thing definition
=> [gree] Adaption to OH 3

bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/VolvoOnCallHandlerFactory.java, bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/dto/Trip.java, bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/handler/VehicleHandler.java, bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/handler/VolvoOnCallBridgeHandler.java, bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/http/HttpClientProvider_VOC.java, bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/http/HttpUtil_VOC.java
- Fixes issues #8554 and #8518 in **2.5.x branch** as well as backports request cache functionality (already fixed by @clinique on main)
- Note #8554 is a critical fix for the binding - without which it is completely defunct (on all 2.5.x versions).  The fix needs to be accompanied by cache addition, as the binding creates way too much traffic otherwise
--
The intent of the PR was to minimize changes and to *avoid* changing code structure wherever possible, so that any negative system-wide effects can be, hopefully, contained. Individual changes are in separate commits, for possibly cherry-picking.
_Since this is a backport, all the changes herein are already in mainline branch (conceptually), so if there's ever a need to merge back, conflict resolution strategy should be to take all the …
=> [VolvoOnCall] Backports of fixes for #8554 and #8518 to 2.5.x branch

bundles/org.openhab.binding.miio/README.md, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/MiIoBasicChannel.java, bundles/org.openhab.binding.miio/src/main/resources/database/lumi.gateway.json, bundles/org.openhab.binding.miio/src/test/java/org/openhab/binding/miio/internal/ReadmeHelper.java
=> [miio] allow for comments to channels in json db

bundles/org.openhab.binding.openwebnet/README.md, bundles/org.openhab.binding.openwebnet/pom.xml, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/handler/OpenWebNetBridgeHandler.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/discovery/OpenWebNetDeviceDiscoveryService.java
Fixes #8524 and fixes #8547, updated openwebnet4j lib to 0.3.1. Updated README
=> [openwebnet] Fixes #8524 and #8547, updated openwebnet4j lib to 0.3.1. Updated README

bundles/org.openhab.binding.comfoair/src/main/java/org/openhab/binding/comfoair/internal/ComfoAirHandler.java
Partly reverting #8563 since `updateState` is apparently not needed on `handleCommand` and therefore causing issues with state changes.
=> [comfoair] fix updateState

bundles/org.openhab.binding.miio/README.md, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/DeviceMapping.java, bundles/org.openhab.binding.miio/src/main/resources/database/lumi.gateway.json, bundles/org.openhab.binding.miio/src/main/resources/database/yunmi.waterpurifier.json, bundles/org.openhab.binding.miio/src/test/java/org/openhab/binding/miio/internal/ReadmeHelper.java
=> [miio] allow for device remarks in the readme from json db

bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java
Applied the changes found by spotless.
According the comments DEFAULT_NUMERIC, DEFAULT_QUANTIFIABLE config should have 5 archives, the 4th was missing. Additionally the ConsolFunction changed in the DEFAULT_QUANTIFIABLE.
The DEFAULT_OTHER config had false computed archives.
=> [rrd4j] Corrected the default configurations (third try)

bundles/org.openhab.binding.velux/README.md, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/VeluxBindingConstants.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/json/JClogin.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/json/JsonBridgeAPI.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/slip/SlipBridgeAPI.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/slip/SlipVeluxBridge.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/slip/io/Connection.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/slip/io/SSLconnection.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/slip/utils/KLF200Response.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/slip/utils/SlipEncoding.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/discovery/VeluxDiscoveryService.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/factory/VeluxHandlerFactory.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/handler/ChannelBridgeWLANconfig.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/handler/VeluxBindingHandler.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/handler/VeluxBridgeHandler.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/things/VeluxKLFAPI.java, bundles/org.openhab.binding.velux/src/main/resources/ESH-INF/i18n/velux.properties, bundles/org.openhab.binding.velux/src/main/resources/ESH-INF/i18n/velux_de.properties, bundles/org.openhab.binding.velux/src/main/resources/ESH-INF/i18n/velux_dk.properties, bundles/org.openhab.binding.velux/src/main/resources/ESH-INF/i18n/velux_nl.properties
This is a back port of the bug fixes in PR #8520 and PR #8673 from OH v3.0.0 back to the v2.5.x bug fix branch
=> [velux] back port of #8520 & #8673 bug fixes from OH3 to OH2.5.x

bundles/org.openhab.binding.nuvo/README.md, bundles/org.openhab.binding.nuvo/src/main/resources/OH-INF/thing/channels.xml
Signed-off-by: Michael Lobstein <michael.lobstein@gmail.com>
=> [nuvo] update README.md for additional connection option

bundles/org.openhab.binding.nuvo/src/main/resources/OH-INF/thing/channels.xml
Related to https://github.com/openhab/openhab-addons/pull/8691
=> [nuvo] fixed spotless error

bundles/org.openhab.binding.deconz/README.md
=> [deconz] add missing thing type to documentation

bundles/org.openhab.io.hueemulation/src/main/feature/feature.xml
Related to openhab/openhab-core#1709
=> [hueemulation] Update feature

bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/discovery/ThingDiscoveryService.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/DeconzBridgeHandler.java
=> [deconz] retry full state request if initial request failed

bundles/org.openhab.binding.dwdpollenflug/README.md, bundles/org.openhab.binding.dwdpollenflug/pom.xml, bundles/org.openhab.binding.dwdpollenflug/src/main/resources/OH-INF/binding/binding.xml, bundles/org.openhab.binding.dwdunwetter/README.md, bundles/org.openhab.binding.dwdunwetter/pom.xml, bundles/org.openhab.binding.dwdunwetter/src/main/feature/feature.xml
- Aligned spelling of DWD bindings
=> [dwd] Aligned spelling of DWD bindings

bundles/org.openhab.voice.googletts/src/main/java/org/openhab/voice/googletts/internal/GoogleTTSService.java
=> [googletts] Reduced logging

bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/AirVisualNodeBindingConstants.java, bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/config/AirVisualNodeConfig.java, bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/handler/AirVisualNodeHandler.java, bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/json/MeasurementsInterface.java, bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/json/NodeDataInterface.java, bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/json/airvisual/Measurements.java, bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/json/airvisual/NodeData.java, bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/json/airvisual/PowerSaving.java, bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/json/airvisual/Settings.java, bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/json/airvisual/Status.java, bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/json/airvisualpro/Measurements.java, bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/json/airvisualpro/PowerSaving.java, bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/json/airvisualpro/ProNodeData.java, bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/json/airvisualpro/SensorLife.java, bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/json/airvisualpro/SensorMode.java, bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/json/airvisualpro/Settings.java, bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/json/airvisualpro/Status.java, bundles/org.openhab.binding.airvisualnode/src/main/resources/OH-INF/thing/thing-types.xml
Support **AirVisual Pro** version
=> [airvisualnode] Support AirVisual Pro version

bundles/org.openhab.voice.googletts/src/main/resources/OH-INF/config/config.xml
- Changed capitalization of config context
Closes https://github.com/openhab/openhab-webui/issues/387
=> [googletts] Changed capitalization of config context

bundles/org.openhab.binding.avmfritz/README.md, bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/dto/AVMFritzBaseModel.java, bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/dto/DeviceModel.java
- Improved documentation and logging
=> [avmfritz] Improved documentation and logging

bundles/org.openhab.binding.hue/README.md, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/HueBindingConstants.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/HueThingHandlerFactory.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/discovery/HueLightDiscoveryService.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/sensors/GeofencePresenceHandler.java, bundles/org.openhab.binding.hue/src/main/resources/OH-INF/config/config.xml, bundles/org.openhab.binding.hue/src/main/resources/OH-INF/i18n/hue_de.properties, bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/GeofenceSensor.xml
- Added support for Geofence sensor
Closes #7635
=> [hue] Added support for Geofence sensor

bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/handler/OpenSprinklerStationHandler.java, bundles/org.openhab.binding.opensprinkler/src/main/resources/OH-INF/thing/thing-types.xml
Fixes #8541 
@Hilbrand i hope i got this right... if not... please let me know what need to be changed...
I tested this in Eclipse IDE with OH3 and it worked...
How do we proceed if we want to have this in 2.5.10 too? Do i need to create another PR to the 2.5.x branch?
=> fixed nextDuration UoM transformation fixes #8541

bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/handler/OpenSprinklerStationHandler.java, bundles/org.openhab.binding.opensprinkler/src/main/resources/ESH-INF/thing/thing-types.xml
=> [opensprinkler] fix nextDuration UoM transformation Fixes #8541

bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/FullHueObject.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/FullLight.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/FullSensor.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/HueThingHandlerFactory.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/discovery/HueDeviceDiscoveryService.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueBridgeHandler.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueClient.java, itests/org.openhab.binding.hue.tests/src/main/java/org/openhab/binding/hue/internal/HueDeviceDiscoveryServiceOSGiTest.java
- Refactored discovery service to `ThingHandlerService`
=> [hue] Refactored discovery service to 'ThingHandlerService'

CODEOWNERS
=> sort CODEOWNERS alphabetical

bundles/org.openhab.binding.hue/src/main/resources/OH-INF/config/config.xml
- Fixed typo in Geofence Sensor config
Introduced in #8731
=> [hue] Fixed typo in Geofence Sensor config

bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/discovery/NetworkDiscoveryService.java, bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/utils/LatencyParser.java, bundles/org.openhab.binding.network/src/test/java/org/openhab/binding/network/internal/utils/LatencyParserTest.java
Fixes #8776
Also fixes another concurrency bug I found in the discovery service.
=> [network] Fix latency parsing on windows 10

bundles/org.openhab.binding.network/src/test/java/org/openhab/binding/network/internal/utils/LatencyParserTest.java
=> [network] Fix build

bom/openhab-addons/pom.xml
=> sort pom.xml alphabetical

bundles/org.openhab.persistence.rrd4j/README.md, bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java
Additionally:
- documentation has been updated and improved
- logging has been improved for better debugging
Fixes #8806
Fixes #8771 
=> [rrd4j] Ignore item types that are not supported

bundles/org.openhab.binding.neohub/src/main/java/org/openhab/binding/neohub/internal/NeoHubConfiguration.java, bundles/org.openhab.binding.neohub/src/main/java/org/openhab/binding/neohub/internal/NeoHubDiscoveryParticipant.java, bundles/org.openhab.binding.neohub/src/main/resources/OH-INF/thing/thing-types.xml
This PR adds an mDNS auto discovery service participant to discover NeoHubs
=> [neohub] added automatic discovery of NeoHubs

bundles/org.openhab.binding.feed/README.md, bundles/org.openhab.binding.feed/src/main/java/org/openhab/binding/feed/internal/FeedBindingConstants.java, bundles/org.openhab.binding.feed/src/main/java/org/openhab/binding/feed/internal/FeedHandlerFactory.java, bundles/org.openhab.binding.feed/src/main/java/org/openhab/binding/feed/internal/handler/FeedHandler.java, bundles/org.openhab.binding.feed/src/main/resources/OH-INF/thing/thing-types.xml, itests/org.openhab.binding.feed.tests/src/main/java/org/openhab/binding/feed/test/FeedHandlerTest.java, itests/org.openhab.binding.feed.tests/src/main/java/org/openhab/binding/feed/test/SlowTests.java
- Minor improvements for Feed Binding (nullness annotations, SAT findings)
=> [feed] Minor improvements for Feed Binding

bundles/org.openhab.binding.lutron/README.md, bundles/org.openhab.binding.lutron/doc/leapnotes.md, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/StringUtils.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/config/IPBridgeConfig.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/grxprg/GrafikEyeHandler.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/grxprg/PrgProtocolHandler.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/CcoHandler.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/IPBridgeHandler.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/LeapBridgeHandler.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/protocol/DeviceCommand.java, bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/protocol/leap/LeapMessageParser.java, bundles/org.openhab.binding.lutron/src/main/resources/OH-INF/thing/thing-types.xml
This is a minor update which contains the following:
* Removes most uses of Apache Commons (except for Apache Commons Net)
* Other minor code changes with no functional impact
* Rationalizes thing labels and descriptions
* Adds some roughly appropriate categories to things
* Doc updates
=> [lutron] Minor code and doc updates

bundles/org.openhab.binding.loxone/README.md
=> [loxone] Update README.md

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/MiIoDatabaseWatchService.java, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/cloud/CloudUtil.java, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoVacuumHandler.java
=> [miio] cleanup duplicate paths

bundles/org.openhab.binding.miio/README.base.md, bundles/org.openhab.binding.miio/README.md
Add FAQ + fix some formatting issues
=> [miio] add FAQ to readme

bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/action/EcobeeActions.java
Fixed an issue when the hold time is not properly handled when setting a temperature hold for a defined number of hours.
I this is approved, I also plan to submit for 2.5.10.
=> [ecobee] Fixed setHold action when using holdHours

bundles/org.openhab.binding.modbus.helioseasycontrols/README.md
Signed-off-by: Bernhard Bauer <bern77@gmail.com>
Update of documentation:
- corrected error in thing definition (thing type)
- corrected error in item example (thing type in channel)
- added rule example
=> [modbus.helioseasycontrols] Corrected channel in items example, added rule example

bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/PulseaudioClient.java
Signed-off-by: Robert von Könemann <lordtaifleh@gmail.com>
This PR addresses an issue where an offline pulseaudio device is being contacted periodically by the binding when configured by text files.
The issue arises when the binding tries to read data from the socket representing the offline pulseaudio device. This PR addresses the issue by making sure that the socket is not equal to null before returning its value or before writing to it.
It also catches a NoRouteToHostException that occurs when the binding tries to connect to an offline device, which removes the strack-traces from the logs and instead displays an error line.
=> [pulseaudio] Fix #8843. Stop spamming logs when pulseaudio device is offline

bundles/org.openhab.persistence.jdbc/README.md, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcPersistenceService.java, bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/model/JdbcHistoricItem.java
- Use 'everyChange' as default strategy for JDBC persistence
=> [jdbc] Use 'everyChange' as default strategy for JDBC persistence

.travis.yml
See https://github.com/openhab/openhab-addons/pull/8848#issuecomment-716052315
=> Deactivated Travis on the main branch

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/cloud/CloudConnector.java, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/cloud/MiCloudConnector.java
Avoid nasty error in case of strange / unexpected cloud response
Related forum topic
https://community.openhab.org/t/xiaomi-robot-vacuum-binding/31317/1722
=> [miio] avoid Invalid URI host: null error

bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/api/EcobeeApi.java
Ecobee will return an `invalid_grant` response if the refresh token is invalid. In that case, the user will need to reauthorize the application with Ecobee. This change will force the reauthorization by deleting the OAuth store.
Fixes #8720
=> [ecobee] Improve handling of invalid_grant error

itests/org.openhab.binding.modbus.tests/src/main/java/org/openhab/binding/modbus/tests/ModbusDataHandlerTest.java
=> [modbus] Disable failing test

bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/BindingConstants.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/discovery/BridgeDiscoveryParticipant.java, bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/thing/thing-types.xml
- Added representation property for deCONZ Gateway
=> [deconz] Added representation property for deCONZ Gateway

bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/smarthome/DynamicStateDescriptionSmartHome.java
=> [amazonechocontrol] fix NPE

bundles/org.openhab.binding.intesis/src/main/resources/OH-INF/thing/dynamic-channels.xml, bundles/org.openhab.binding.intesis/src/main/resources/OH-INF/thing/thing-types.xml
=> [intesis] Changed default pattern for temperature channels

bundles/org.openhab.binding.amazonechocontrol/pom.xml, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/smarthome/DynamicStateDescriptionSmartHome.java
[AmazonEchoControl] Fix NPE #8885 
Fixed obviously wrong boolean condition & ran mvn spotless apply
Binding is starting successfully again, Alexa control in terms of TTS, etc. is working.
Due to limited possibilities, controlling SmartHome devices connected to Alexa has not been tested.
However, the previous boolean condition did not make sense this way either, so I do not expect a regression...
=> [AmazonEchoControl] Fix NPE #8885 

bundles/org.openhab.binding.samsungtv/README.md
=> Tiny tiny typo :)

bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/AmazonEchoDynamicStateDescriptionProvider.java
https://community.openhab.org/t/openhab-3-snapshot-1993-amazon-echo-control-state-description/107308
=> [amazonechocontrol] fix dynamic DynamicStateDescriptionProvider

bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/OpenUVBindingConstants.java, bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/OpenUVException.java, bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/OpenUVHandlerFactory.java, bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/config/BridgeConfiguration.java, bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/config/ReportConfiguration.java, bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/config/SafeExposureConfiguration.java, bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/discovery/OpenUVDiscoveryService.java, bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/handler/OpenUVBridgeHandler.java, bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/handler/OpenUVReportHandler.java
Removing org.apache.commons.stringutils usage and a bit of code cleansing
=> [OpenUV] Correcting representation property

bundles/org.openhab.persistence.rrd4j/README.md
Changed some wordings.
-Kept "DataSource" as the term for the way data is stored in a .rrd file. Such is more inline with the used "Default Datasources" (-numeric, ...).
-Removed the requirement for an everyMinute Strategy, inserted an explanation for relationship between Sample Intervall and Strategy instead.
=> [rrd4j] Updated readme

CODEOWNERS, bundles/org.openhab.binding.deconz/README.md, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/BindingConstants.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/DeconzHandlerFactory.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/Util.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/discovery/ThingDiscoveryService.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/dto/BridgeFullState.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/dto/DeconzBaseMessage.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/dto/GroupAction.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/dto/GroupMessage.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/dto/GroupState.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/dto/Scene.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/DeconzBaseThingHandler.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/GroupThingHandler.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/LightThingHandler.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/SensorBaseThingHandler.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/SensorThermostatThingHandler.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/SensorThingHandler.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/netutils/WebSocketConnection.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/netutils/WebSocketMessageListener.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/types/GroupType.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/types/GroupTypeDeserializer.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/types/LightTypeDeserializer.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/types/ResourceType.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/types/ResourceTypeDeserializer.java, bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/thing/group-thing-types.xml, bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/thing/light-thing-types.xml, bundles/org.openhab.binding.deconz/src/test/java/org/openhab/binding/deconz/DeconzTest.java
=> [deconz] add group support

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoAbstractHandler.java
remove left over debug message
=> [miio] remove unneeded debug msg

bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/handler/LinkyHandler.java
=> [linky] Fixed IndexOutOfBoundsException on startup

bundles/org.openhab.binding.netatmo/README.md
=> [netatmo] Mention supported thermostats in the documentation

bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java
* Cache item to improve performance
* Also return DecimalType for QuantityType values
Related to #8928
Reintroduces #8809
=> [rrd4j] Improve performance

bundles/org.openhab.binding.neato/src/main/java/org/openhab/binding/neato/internal/classes/Robot.java, bundles/org.openhab.binding.neato/src/main/java/org/openhab/binding/neato/internal/discovery/NeatoAccountDiscoveryService.java
=> [neato] Fixed NPE in discovery

bundles/org.openhab.binding.miio/README.base.md, bundles/org.openhab.binding.miio/README.md
As per  https://community.openhab.org/t/xiaomi-robot-vacuum-binding/31317/1729
=> [miio] update readme with Roborock app info

bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/handler/KodiHandler.java, bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/protocol/KodiConnection.java
- Reduce polling by checking linkage first
=> [kodi] Reduce polling by checking linkage first

bundles/org.openhab.binding.mqtt/src/test/java/org/openhab/binding/mqtt/handler/AbstractBrokerHandlerTest.java, bundles/org.openhab.binding.mqtt/src/test/java/org/openhab/binding/mqtt/handler/BrokerHandlerTest.java, bundles/org.openhab.binding.mqtt/src/test/java/org/openhab/binding/mqtt/handler/MqttAsyncClientWrapperEx.java, bundles/org.openhab.binding.mqtt/src/test/java/org/openhab/binding/mqtt/handler/MqttBrokerConnectionEx.java, bundles/org.openhab.binding.mqtt/src/test/java/org/openhab/binding/mqtt/internal/MQTTTopicDiscoveryServiceTest.java, bundles/org.openhab.binding.mqtt/src/test/java/org/openhab/binding/mqtt/internal/discovery/ServiceDiscoveryServiceTest.java
=> [mqtt.generic] Fix JUnit tests

bundles/org.openhab.binding.miio/README.md, bundles/org.openhab.binding.miio/src/main/resources/database/zimi.powerstrip.v2.json
=> [miio] add poweroff properties to zhimi powerstrip

bundles/org.openhab.binding.miio/README.base.md, bundles/org.openhab.binding.miio/README.md, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoDevices.java, bundles/org.openhab.binding.miio/src/main/resources/database/chuangmi.plug.v3fw.json, bundles/org.openhab.binding.miio/src/main/resources/database/mrbond.airer.m1pro.json, bundles/org.openhab.binding.miio/src/main/resources/database/philips.light.sread1.json
Sync readme & devices with 3.0
=> [miio] fix readme & sync devices

itests/org.openhab.binding.astro.tests/itest.bndrun, itests/org.openhab.binding.avmfritz.tests/itest.bndrun, itests/org.openhab.binding.feed.tests/itest.bndrun, itests/org.openhab.binding.hue.tests/itest.bndrun, itests/org.openhab.binding.max.tests/itest.bndrun, itests/org.openhab.binding.modbus.tests/itest.bndrun, itests/org.openhab.binding.nest.tests/itest.bndrun, itests/org.openhab.binding.ntp.tests/itest.bndrun, itests/org.openhab.binding.systeminfo.tests/itest.bndrun, itests/org.openhab.binding.tradfri.tests/itest.bndrun, itests/org.openhab.binding.wemo.tests/itest.bndrun, itests/org.openhab.io.hueemulation.tests/itest.bndrun
Another attempt to fix the build for 2.5
=> fix itests for 2.5

bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/BindingConstants.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/Util.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/LightThingHandler.java
=> [deconz] support for IncreaseDecreaseType commands

bundles/org.openhab.binding.intesis/src/main/java/org/openhab/binding/intesis/internal/handler/IntesisBoxHandler.java, bundles/org.openhab.binding.intesis/src/main/java/org/openhab/binding/intesis/internal/handler/IntesisHomeHandler.java
=> [intesis] Fix channel state options not set when channel exists

bundles/org.openhab.binding.fmiweather/src/main/feature/feature.xml
=> [fmiweather] Binding description stylized

bundles/org.openhab.binding.fmiweather/src/main/resources/OH-INF/thing/thing-types.xml
Fixes #8971  
Related to https://github.com/openhab/openhab-core/pull/1410
=> [fmiweather] fix thing definition XML error

bundles/org.openhab.binding.deconz/README.md, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/BindingConstants.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/discovery/ThingDiscoveryService.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/LightThingHandler.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/types/LightType.java, bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/thing/light-thing-types.xml
=> [deconz] add doorlock support

bundles/org.openhab.binding.fmiweather/src/main/java/org/openhab/binding/fmiweather/internal/HandlerFactory.java, bundles/org.openhab.binding.fmiweather/src/main/java/org/openhab/binding/fmiweather/internal/discovery/CitiesOfFinland.java, bundles/org.openhab.binding.fmiweather/src/main/java/org/openhab/binding/fmiweather/internal/discovery/FMIWeatherDiscoveryService.java
As discussed in https://github.com/openhab/openhab-addons/issues/8971#issuecomment-723420761
=> [fmiweather] Discovery: advertising all discovered thing types

bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/calc/MoonCalc.java, bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/calc/SunZodiacCalc.java, bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/handler/SunHandler.java, bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/util/PropertyUtils.java
=> [astro] Correcting some SAT findings, deprecated variables and a blocking point

bundles/org.openhab.voice.mactts/src/main/java/org/openhab/voice/mactts/internal/MacTTSAudioStream.java
=> [mactts] Allow spaces within voice name

bundles/org.openhab.binding.miio/README.base.md, bundles/org.openhab.binding.miio/README.md
=> [miio] update readme with db location details

bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/OpenUVBindingConstants.java, bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/OpenUVException.java, bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/OpenUVHandlerFactory.java, bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/handler/OpenUVReportHandler.java, bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/json/OpenUVResult.java, bundles/org.openhab.binding.openuv/src/main/resources/OH-INF/thing/thing-types.xml
Adding alert levels consistent with MeteoAlarm and Vigicrues
=> [OpenUV] Correcting a SAT finding.

bundles/org.openhab.binding.ambientweather/README.md, bundles/org.openhab.binding.ambientweather/src/main/java/org/openhab/binding/ambientweather/internal/AmbientWeatherBindingConstants.java, bundles/org.openhab.binding.ambientweather/src/main/java/org/openhab/binding/ambientweather/internal/processor/ProcessorFactory.java, bundles/org.openhab.binding.ambientweather/src/main/java/org/openhab/binding/ambientweather/internal/processor/Ws2902bProcessor.java, bundles/org.openhab.binding.ambientweather/src/main/resources/OH-INF/thing/ws2902b.xml
Add support for WS-2902B weather station.
=> [ambientweather] Add WS-2902B weather station

bundles/org.openhab.binding.meteoalerte/README.md, bundles/org.openhab.binding.meteoalerte/src/main/java/org/openhab/binding/meteoalerte/internal/handler/MeteoAlerteHandler.java, bundles/org.openhab.binding.meteoalerte/src/main/java/org/openhab/binding/meteoalerte/internal/json/ApiResponse.java, bundles/org.openhab.binding.meteoalerte/src/main/resources/OH-INF/thing/thing-types.xml
=> [meteoalerte] Adressing Issue #8543

bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/WakeOnLanUtility.java
=> [samsungtv] fix NPE

bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/WakeOnLanUtility.java
=> [lgwebos]  fix NPE

bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/lib/event/EventListener.java
=> [digitalstrom] fix NPE

bundles/org.openhab.binding.vigicrues/src/main/java/org/openhab/binding/vigicrues/internal/dto/hubeau/HubEauResponse.java
=> [VigiCrues] Adding missing header to HubEauResponse

bundles/org.openhab.binding.miio/README.md, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoDevices.java, bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.fan.za4.json
=> [miio] Add zhimi.fan.za1

bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/DeconzBridgeHandler.java
=> [deconz] fix websocketId creation

bundles/org.openhab.binding.bluetooth.bluegiga/src/main/resources/OH-INF/thing/bluegiga.xml
=> [bluetooth.bluegiga] Fix scan interval descriptions

bundles/org.openhab.binding.bluetooth.bluegiga/src/main/resources/OH-INF/thing/bluegiga.xml
=> [bluetooth.bluegiga] Fix / concretize bluegiga parameter descriptions

bundles/org.openhab.binding.omnikinverter/src/main/java/org/openhab/binding/omnikinverter/internal/OmnikInverter.java, bundles/org.openhab.binding.omnikinverter/src/main/java/org/openhab/binding/omnikinverter/internal/handler/OmnikInverterHandler.java
=> [omnikinverter]fix missing dispose

bundles/org.openhab.binding.hue/src/main/resources/OH-INF/config/config.xml, bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/CLIPGenericFlagSensor.xml, bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/CLIPGenericStatusSensor.xml, bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/ColorLight.xml, bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/ColorTemperatureLight.xml, bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/DimmableLight.xml, bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/DimmablePlug.xml, bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/DimmerSwitch.xml, bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/ExtendedColorLight.xml, bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/Group.xml, bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/LightLevelSensor.xml, bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/OnOffLight.xml, bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/OnOffPlug.xml, bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/TapSwitch.xml, bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/TemperatureSensor.xml, bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/bridge.xml
=> [hue] Deprecated tag "required" for configuration parameter

bundles/org.openhab.binding.netatmo/src/main/resources/OH-INF/config/config.xml
=> [netatmo] Deprecated tag "required" for configuration parameter

bundles/org.openhab.binding.lcn/README.md
=> [lcn] doc: add .things example

bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/SnmpServiceImpl.java, bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/SnmpTargetHandler.java, bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/config/SnmpChannelConfiguration.java, bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/config/SnmpServiceConfiguration.java, bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/config/SnmpTargetConfiguration.java
I discovered a NPE when setting up a new thing. This was due to missing null-annotation on the config classes.
=> [snmp] nullness improvements

bundles/org.openhab.binding.volvooncall/README.md, bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/dto/Status.java, bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/dto/TyrePressure.java, bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/handler/VehicleHandler.java, bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/handler/VolvoOnCallBridgeHandler.java, bundles/org.openhab.binding.volvooncall/src/main/resources/OH-INF/i18n/volvooncall_fr.properties, bundles/org.openhab.binding.volvooncall/src/main/resources/OH-INF/thing/vehicle.xml
=> [VolvoOnCall] SAT corrections and some channels enhancements

bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/handler/JablotronAlarmHandler.java, bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/handler/JablotronBridgeHandler.java, bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/handler/JablotronJa100Handler.java
This is a bug fix PR fixing these bugs:
- the bridge stays forever offline when an error occurs
- the JA100 programmable gates are not updated
It would be great, if we can cherry-pick it to the 2.5.x  branch as well.
Thanks.
=> [jablotron] fixed updating of JA100 PG channels

bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/discovery/KM200GatewayDiscoveryParticipant.java, bundles/org.openhab.binding.km200/src/main/resources/OH-INF/thing/device.xml
- Fixed representation-property for discovery result
See https://community.openhab.org/t/fig-discovery-discoveryresultbuilder-discovery-result-for-thing-km200453092xxx-is-missing-in-properties-map-it-has-to-be-fixed-by-the-developer/108354
=> [km200] Fixed representation-property for discovery result

bundles/org.openhab.binding.touchwand/README.md, bundles/org.openhab.binding.touchwand/src/main/java/org/openhab/binding/touchwand/internal/TouchWandAlarmSensorHandler.java, bundles/org.openhab.binding.touchwand/src/main/java/org/openhab/binding/touchwand/internal/TouchWandBaseUnitHandler.java, bundles/org.openhab.binding.touchwand/src/main/java/org/openhab/binding/touchwand/internal/TouchWandBindingConstants.java, bundles/org.openhab.binding.touchwand/src/main/java/org/openhab/binding/touchwand/internal/TouchWandBridgeHandler.java, bundles/org.openhab.binding.touchwand/src/main/java/org/openhab/binding/touchwand/internal/TouchWandHandlerFactory.java, bundles/org.openhab.binding.touchwand/src/main/java/org/openhab/binding/touchwand/internal/TouchWandRestClient.java, bundles/org.openhab.binding.touchwand/src/main/java/org/openhab/binding/touchwand/internal/TouchWandWallControllerHandler.java, bundles/org.openhab.binding.touchwand/src/main/java/org/openhab/binding/touchwand/internal/TouchWandWebSockets.java, bundles/org.openhab.binding.touchwand/src/main/java/org/openhab/binding/touchwand/internal/discovery/TouchWandControllerDiscoveryService.java, bundles/org.openhab.binding.touchwand/src/main/java/org/openhab/binding/touchwand/internal/discovery/TouchWandUnitDiscoveryService.java, bundles/org.openhab.binding.touchwand/src/main/java/org/openhab/binding/touchwand/internal/dto/AlarmSensorUnitDataDeserializer.java, bundles/org.openhab.binding.touchwand/src/main/java/org/openhab/binding/touchwand/internal/dto/CurrStatus.java, bundles/org.openhab.binding.touchwand/src/main/java/org/openhab/binding/touchwand/internal/dto/TouchWandAlarmSensorCurrentStatus.java, bundles/org.openhab.binding.touchwand/src/main/java/org/openhab/binding/touchwand/internal/dto/TouchWandUnitData.java, bundles/org.openhab.binding.touchwand/src/main/java/org/openhab/binding/touchwand/internal/dto/TouchWandUnitDataAlarmSensor.java, bundles/org.openhab.binding.touchwand/src/main/java/org/openhab/binding/touchwand/internal/dto/TouchWandUnitDataWallController.java, bundles/org.openhab.binding.touchwand/src/main/java/org/openhab/binding/touchwand/internal/dto/TouchWandUnitFromJson.java, bundles/org.openhab.binding.touchwand/src/main/java/org/openhab/binding/touchwand/internal/dto/TouchWandUnknownTypeUnitData.java, bundles/org.openhab.binding.touchwand/src/main/resources/OH-INF/thing/alarmsensor.xml
Added support for AlarmSensor and WallController
Many fixes and stability improvements 
Added support for two new "things"
**AlarmSensor** - and abstraction of various z wave sensors include leak detection , door/window  , motion 
**WallController** - support virtual Zwave Long/Short pressed button in the wall controller.
Stability improvements
* fixed websocket timeout which caused disconnections in some systems
* better check if the json response is can be parsed .
* reduce build "warnings" to minimum
=> [touchwand]- Added support for AlarmSensor and WallController

bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/schema/ApiPageParser.java, bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/schema/TACmiSchemaHandler.java
TA-CMI: Fixed some issues when percent values are received or updated
I initially had to situation to handle %-values. There have been some issues with it. This PR fixes the problems.
This fix would also apply to 2.5.x - should I also make a PR to 2.5?
=> [tacmi] TA-CMI: Fixed some issues when percent values are received or updated

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoBasicHandler.java
=> [miio] send miot actions parameter as jsonObject

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoVacuumHandler.java, bundles/org.openhab.binding.miio/src/main/resources/OH-INF/thing/vacuumThing.xml
=> [miio] Use QuantityTypes for time & area in the vacuumhandler

bundles/org.openhab.binding.neeo/src/main/java/org/openhab/binding/neeo/internal/NeeoBrainApi.java, bundles/org.openhab.binding.neeo/src/main/java/org/openhab/binding/neeo/internal/NeeoBrainConfig.java, bundles/org.openhab.binding.neeo/src/main/java/org/openhab/binding/neeo/internal/NeeoRoomProtocol.java, bundles/org.openhab.binding.neeo/src/main/java/org/openhab/binding/neeo/internal/NeeoUtil.java, bundles/org.openhab.binding.neeo/src/main/java/org/openhab/binding/neeo/internal/UidUtils.java, bundles/org.openhab.binding.neeo/src/main/java/org/openhab/binding/neeo/internal/discovery/NeeoBrainDiscovery.java, bundles/org.openhab.binding.neeo/src/main/java/org/openhab/binding/neeo/internal/discovery/NeeoDeviceDiscoveryService.java, bundles/org.openhab.binding.neeo/src/main/java/org/openhab/binding/neeo/internal/discovery/NeeoRoomDiscoveryService.java, bundles/org.openhab.binding.neeo/src/main/java/org/openhab/binding/neeo/internal/handler/ChannelUtils.java, bundles/org.openhab.binding.neeo/src/main/java/org/openhab/binding/neeo/internal/handler/NeeoBrainHandler.java, bundles/org.openhab.binding.neeo/src/main/java/org/openhab/binding/neeo/internal/handler/NeeoDeviceHandler.java, bundles/org.openhab.binding.neeo/src/main/java/org/openhab/binding/neeo/internal/handler/NeeoForwardActionsServlet.java, bundles/org.openhab.binding.neeo/src/main/java/org/openhab/binding/neeo/internal/handler/NeeoRoomHandler.java, bundles/org.openhab.binding.neeo/src/main/java/org/openhab/binding/neeo/internal/models/NeeoDeviceDetails.java, bundles/org.openhab.binding.neeo/src/main/java/org/openhab/binding/neeo/internal/models/NeeoDevices.java, bundles/org.openhab.binding.neeo/src/main/java/org/openhab/binding/neeo/internal/models/NeeoMacros.java, bundles/org.openhab.binding.neeo/src/main/java/org/openhab/binding/neeo/internal/models/NeeoRecipes.java, bundles/org.openhab.binding.neeo/src/main/java/org/openhab/binding/neeo/internal/models/NeeoRooms.java, bundles/org.openhab.binding.neeo/src/main/java/org/openhab/binding/neeo/internal/models/NeeoScenarios.java, bundles/org.openhab.binding.neeo/src/main/java/org/openhab/binding/neeo/internal/net/HttpResponse.java, bundles/org.openhab.binding.neeo/src/main/resources/OH-INF/thing/thing-types.xml
- create forwardactionsservlet only if forwardchain is not empty
- remove dependency on apache commons
- fix #9027 (wrong thing XML)
=> [neeo] improve code

bundles/org.openhab.binding.tr064/README.md, bundles/org.openhab.binding.tr064/src/main/resources/channels.xml
=> [tr064] Fixed minor spelling

bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/DeviceMessageListener.java, bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/RFXComHandlerFactory.java, bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/discovery/RFXComDeviceDiscoveryService.java, bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/handler/RFXComBridgeHandler.java
=> [rfxcom) Use ThingHandlerService for discovery

bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/PowermaxHandlerFactory.java, bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/discovery/PowermaxDiscoveryService.java, bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/handler/PowermaxBridgeHandler.java, bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/handler/PowermaxThingHandler.java, bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/state/PowermaxPanelSettingsListener.java
=> [powermax] Use ThingHandlerService for discovery

bundles/org.openhab.binding.http/src/main/resources/OH-INF/thing/thing-types.xml
=> [http] fix thing-definition

bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/protocol/IntRSModule.java, bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/protocol/SatelModule.java
This PR fixes communication problems when using INT-RS bridge.
Issue is described here: https://community.openhab.org/t/satel-binding-support-announcements-and-feature-requests/56135/234
After several disconnections one of the binding threads hangs and communistion is stopped. The main change is to rely on receive timeout that can be setup for serial port instead of thread based watchdog.
=> [satel] Fixes for INT-RS module

bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/AVMFritzTlsTrustManagerProvider.java, bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/phonebook/PhonebookProfile.java, bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/phonebook/PhonebookProfileFactory.java, bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/phonebook/Tr064PhonebookImpl.java, bundles/org.openhab.binding.tr064/src/main/resources/OH-INF/config/phonebookProfile.xml, bundles/org.openhab.binding.tr064/src/main/resources/OH-INF/i18n/tr064_de.properties, bundles/org.openhab.binding.tr064/src/test/java/org/openhab/binding/tr064/internal/phonebook/PhonebookProfileTest.java
- Improvements of Phonebook Profile
=> [tr064] Improvements of Phonebook Profile

bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/LcnModuleHandler.java
Fixes #9086
Relates to openhab/openhab-core#1707
=> [lcn] Fix initial polling of linked Channels

bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/HomematicBindingConstants.java, bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/handler/HomematicThingHandler.java, bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/type/HomematicTypeGeneratorImpl.java, bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/type/MetadataUtils.java
The PR solves some compatibility issues with OH3.
=> [Homematic] Better OH3 compatibility

bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/InsteonDevice.java
This is a regression introduced with https://github.com/openhab/openhab-addons/pull/8937
=> [insteon] Fixed status updates not getting published for some polled devices

bundles/org.openhab.binding.modbus.helioseasycontrols/README.md, bundles/org.openhab.binding.modbus.helioseasycontrols/src/main/java/org/openhab/binding/modbus/helioseasycontrols/internal/HeliosEasyControlsActions.java, bundles/org.openhab.binding.modbus.helioseasycontrols/src/main/java/org/openhab/binding/modbus/helioseasycontrols/internal/HeliosEasyControlsHandler.java
Signed-off-by: Bernhard Bauer <bern77@gmail.com>
=> [helioseasycontrols] Range checks for bypass dates + documentation fixes

bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/handler/FroniusBridgeHandler.java
Fix https://github.com/openhab/openhab-addons/issues/8633
=> [fronius] Fix connection check with Gen24 inverters

bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/handler/AccountHandler.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/smarthome/HandlerColorController.java
Backport of simple bugfixes from #9057
=> [amazonechocontrol] bugfixes

bundles/org.openhab.binding.denonmarantz/README.md
Added note for later models >= 2016.
=> [denonmarantz] Update README.md

bundles/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/FreeboxDataListener.java, bundles/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/FreeboxHandlerFactory.java, bundles/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/discovery/FreeboxDiscoveryService.java, bundles/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/handler/FreeboxHandler.java
=> [freebox] Use ThingHandlerService for discovery

bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/internal/action/SendMailActions.java, bundles/org.openhab.binding.mail/src/main/resources/OH-INF/i18n/mail.properties, bundles/org.openhab.binding.mail/src/main/resources/OH-INF/i18n/mail_de.properties
- Added translations for `ThingActions`
- Renamed action methods to be resolved correctly. The `AnnotatedThingActionModuleTypeProvider` uses the method name to create a unique id for action modules.
=> [mail] Added translations for ThingActions

bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/AccountHandlerConfig.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/AccountServlet.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/AmazonEchoControlHandlerFactory.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/AmazonEchoDynamicStateDescriptionProvider.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/BindingServlet.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/Connection.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/WebSocketConnection.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/channelhandler/ChannelHandler.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/channelhandler/ChannelHandlerSendMessage.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/discovery/SmartHomeDevicesDiscovery.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/handler/AccountHandler.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/handler/EchoHandler.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/handler/FlashBriefingProfileHandler.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/handler/SmartHomeDeviceHandler.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/jsons/JsonBluetoothStates.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/jsons/JsonSmartHomeDevices.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/jsons/JsonSmartHomeGroups.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/smarthome/HandlerBase.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/smarthome/HandlerBrightnessController.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/smarthome/HandlerColorController.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/smarthome/HandlerColorTemperatureController.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/smarthome/HandlerPercentageController.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/smarthome/HandlerPowerController.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/smarthome/HandlerPowerLevelController.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/smarthome/HandlerSecurityPanelController.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/smarthome/SmartHomeDeviceStateGroupUpdateCalculator.java
- improvements to queue handling
- remove StringUtils (see #7722)
- fix (nearly) all warning (what stays are limitations of the null-checker and false positives)
- fix smarthome devices not updating state  
- fix color channel command for smarthome devices
Also-By: Tom Blum <trinitus01@googlemail.com>
Signed-Off-By: Jan N. Klug <jan.n.klug@rub.de>
=> [amazonechocontrol] improvements and bug fixes

bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcPersistenceService.java, bundles/org.openhab.persistence.jdbc/src/main/resources/OH-INF/config/config.xml
- Added OSGi configurable service declarations
=> [jdbc] Added OSGi configurable service declarations

CODEOWNERS, bom/openhab-addons/pom.xml, bundles/org.openhab.binding.playstation/NOTICE, bundles/org.openhab.binding.playstation/README.md, bundles/org.openhab.binding.playstation/pom.xml, bundles/org.openhab.binding.playstation/src/main/feature/feature.xml, bundles/org.openhab.binding.playstation/src/main/java/org/openhab/binding/playstation/internal/PS3Configuration.java, bundles/org.openhab.binding.playstation/src/main/java/org/openhab/binding/playstation/internal/PS3Handler.java, bundles/org.openhab.binding.playstation/src/main/java/org/openhab/binding/playstation/internal/PS4ArtworkHandler.java, bundles/org.openhab.binding.playstation/src/main/java/org/openhab/binding/playstation/internal/PS4Command.java, bundles/org.openhab.binding.playstation/src/main/java/org/openhab/binding/playstation/internal/PS4Configuration.java, bundles/org.openhab.binding.playstation/src/main/java/org/openhab/binding/playstation/internal/PS4Crypto.java, bundles/org.openhab.binding.playstation/src/main/java/org/openhab/binding/playstation/internal/PS4ErrorStatus.java, bundles/org.openhab.binding.playstation/src/main/java/org/openhab/binding/playstation/internal/PS4Handler.java, bundles/org.openhab.binding.playstation/src/main/java/org/openhab/binding/playstation/internal/PS4PacketHandler.java, bundles/org.openhab.binding.playstation/src/main/java/org/openhab/binding/playstation/internal/PlayStationBindingConstants.java, bundles/org.openhab.binding.playstation/src/main/java/org/openhab/binding/playstation/internal/PlayStationHandlerFactory.java, bundles/org.openhab.binding.playstation/src/main/java/org/openhab/binding/playstation/internal/discovery/PlayStationDiscovery.java, bundles/org.openhab.binding.playstation/src/main/resources/OH-INF/binding/binding.xml, bundles/org.openhab.binding.playstation/src/main/resources/OH-INF/config/config.xml, bundles/org.openhab.binding.playstation/src/main/resources/OH-INF/i18n/playstation_en.properties, bundles/org.openhab.binding.playstation/src/main/resources/OH-INF/i18n/playstation_sv.properties, bundles/org.openhab.binding.playstation/src/main/resources/OH-INF/thing/thing-types.xml, bundles/pom.xml
[playstation] Initial contribution
A new binding for mainly PlayStation 4 consoles.
Its main goals are to be able to change power and current game.
You can also control the PS4 UI and send/receive text from the On-Screen-Keyboard from the binding.
To read power and game you don't need any credentials but to control them you need user-credentials for your PSN user.
Here is a discussion on the forum:
https://community.openhab.org/t/playstation-binding/93789/13
=> [playstation] Initial contribution

bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/handler/OpenWebNetAutomationHandler.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/handler/OpenWebNetBridgeHandler.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/handler/OpenWebNetLightingHandler.java
For [openwebnet] binding: improved and corrected lights/dimmers handling in OpenWebNetLightingHandler (fixes #8830).
**NOTE** This PR should be backported to branch 2.5.x to be included in next release (2.5.11).
=> [openwebnet] Fixed lights/dimmers handling #8830

bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/NotificationAction.java, bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudClient.java, bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudClientListener.java, bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudService.java
- Removed dependency on `org.apache.commons`
- Use constructor injection
- Added nullness annotations
- Fixed SAT findings an more
=> [openhabcloud] Code improvements

bundles/org.openhab.binding.miio/README.md, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoDevices.java, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/Conversions.java, bundles/org.openhab.binding.miio/src/main/resources/OH-INF/thing/commonChannels.xml, bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.humidifier.ca4.json
This change adds support for Xiaomi Smartmi Evaporation Air Humidifier 2.
The device uses MIOT protocol, exact spec is available at:
http://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:humidifier:0000A00E:zhimi-ca4:2
I was able to test that it works on my device:
This PR is opened in place of #9084 which was for the wrong (2.5.x branch). 
Signed-off-by: Marek Skrobacki <skrobul@skrobul.com>
=> [miio] add support for zhimi.humidifier.ca4 (Smartmi Evaporative Air Humidifier 2)

bundles/org.openhab.binding.dwdunwetter/src/main/java/org/openhab/binding/dwdunwetter/internal/config/DwdUnwetterConfiguration.java, bundles/org.openhab.binding.dwdunwetter/src/main/java/org/openhab/binding/dwdunwetter/internal/data/DwdWarningData.java, bundles/org.openhab.binding.dwdunwetter/src/main/java/org/openhab/binding/dwdunwetter/internal/data/DwdWarningDataAccess.java, bundles/org.openhab.binding.dwdunwetter/src/main/java/org/openhab/binding/dwdunwetter/internal/data/DwdXmlTag.java, bundles/org.openhab.binding.dwdunwetter/src/main/java/org/openhab/binding/dwdunwetter/internal/data/Severity.java, bundles/org.openhab.binding.dwdunwetter/src/main/java/org/openhab/binding/dwdunwetter/internal/data/SeverityComparator.java, bundles/org.openhab.binding.dwdunwetter/src/main/java/org/openhab/binding/dwdunwetter/internal/data/Urgency.java, bundles/org.openhab.binding.dwdunwetter/src/test/java/org/openhab/binding/dwdunwetter/DwdUnwetterHandlerTest.java
- Removed dependency on `org.apache.commons`
=> [dwdunwetter] Removed dependency on org.apache.commons

bundles/org.openhab.binding.amazonechocontrol/README.md, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/Connection.java
=> [amazonechocontrol] fix display in announcement

itests/org.openhab.binding.systeminfo.tests/src/main/java/org/openhab/binding/systeminfo/test/SysteminfoOSGiTest.java, itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/discovery/test/WemoDiscoveryOSGiTest.java
Related to openhab/openhab-core#1848
=> [itests] Fix after changing Inbox interface

bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/handler/OpenWebNetBridgeHandler.java
=> [openwebnet] Improved logging

bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudService.java, bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/actions/BaseNotificationActionHandler.java, bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/actions/NotificationActionTypeProvider.java, bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/actions/NotificationModuleHandlerFactory.java, bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/actions/SendBroadcastNotificationActionHandler.java, bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/actions/SendLogNotificationActionHandler.java, bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/actions/SendNotificationActionHandler.java
- Added Actions for sending notifications
This PR adds a bunch of actions to be used in NGRE:
=> [openhabcloud] Added Actions for sending notifications

bundles/org.openhab.binding.lcn/README.md, bundles/org.openhab.binding.lcn/src/main/resources/OH-INF/config/config.xml, bundles/org.openhab.binding.lcn/src/main/resources/OH-INF/i18n/lcn_de.properties
=> [lcn] doc: make dimmer output resolution more clearer, fix i18n error

bundles/org.openhab.persistence.dynamodb/src/main/java/org/openhab/persistence/dynamodb/internal/AbstractDynamoDBItem.java, bundles/org.openhab.persistence.dynamodb/src/main/java/org/openhab/persistence/dynamodb/internal/DynamoDBBigDecimalItem.java, bundles/org.openhab.persistence.dynamodb/src/main/java/org/openhab/persistence/dynamodb/internal/DynamoDBHistoricItem.java, bundles/org.openhab.persistence.dynamodb/src/main/java/org/openhab/persistence/dynamodb/internal/DynamoDBStringItem.java, bundles/org.openhab.persistence.dynamodb/src/test/java/org/openhab/persistence/dynamodb/internal/DateTimeItemIntegrationTest.java
=> [dynamodb] Fixed persistence issues with zoneddatetime

bundles/org.openhab.binding.modbus.stiebeleltron/README.md
sorry i missed to change the IP of my own config. Thing Configuration was not accepted bei Visual Studio Code, curly brakets were missed and the definition of ThingID<>Thing was not accepted.
=> [modbus.stiebeleltron] Update README.md

bundles/org.openhab.binding.pushover/README.md
- Improved format of README.md
=> [pushover] Improved format of README.md

bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/AbstractNetatmoThingHandler.java
- Only update the channel for which REFRESH is being sent
=> [netatmo] Only update the channel for which REFRESH is being sent

bundles/org.openhab.binding.yioremote/src/main/java/org/openhab/binding/yioremote/internal/YIOremoteDockHandler.java
Signed-off-by: Michael Loercher <michaelloercher@web.de>
Update of ir code match pattern
=> [yioremote] Update ir code match pattern

bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/DeconzBaseThingHandler.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/types/ResourceType.java
- Fix setting target temperature for Thermostat
- Improve logging on sending commands by checking http response status code
Signed-off-by: Lukas Agethen <lukas83@gmx.de>
=> [deconz] Fix Thermostat setting target temperature

bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/handler/OpenWebNetAutomationHandler.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/handler/OpenWebNetBridgeHandler.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/handler/OpenWebNetLightingHandler.java
This is a backport to 2.5.x of 3.0 PR #9100
=> [openwebnet] Fixed lights/dimmers handling (#8830) and codestyle checks (2.5.x)

bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/MieleBridgeHandler.java
=> [miele] Properly shut down event listener job upon dispose

bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/PowermaxBindingConstants.java, bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/handler/PowermaxBridgeHandler.java, bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/handler/PowermaxThingHandler.java, bundles/org.openhab.binding.powermax/src/main/resources/OH-INF/thing/channels.xml, bundles/org.openhab.binding.powermax/src/main/resources/OH-INF/thing/zone.xml
Allow using lock icon from the classic iconset
Allow displaying the "Locks" badge in MainUI
=> [powermax] New channel of type Contact to show the zone arm status

bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/Connection.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/channelhandler/ChannelHandlerAnnouncement.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/channelhandler/IAmazonThingHandler.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/channelhandler/IEchoThingHandler.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/handler/AccountHandler.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/handler/EchoHandler.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/jsons/JsonAnnouncementContent.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/jsons/JsonAnnouncementTarget.java
Fixes #8726 
Supersedes #9200 
=> [amazonechoontrol] fix announcement without speak

bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/HDPowerViewHandlerFactory.java, bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewHubHandler.java
Fixes #9107 
Similar to the issue fixed in #9006 
=> [hdpowerview] fix ClassNotFoundException

bundles/org.openhab.binding.mihome/README.md
The general description of how Xiaomi works with OpenHAB is out of date.
Development mode is not supported in new Gateways.
=> [mihome] Update README.md, addresses  #9160

bundles/org.openhab.binding.modbus/DEVELOPERS.md, bundles/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/handler/BaseModbusThingHandler.java
I think all features of ModbusEndpointThingHandler are now covered by BaseModbusThingHandler. That is why I made the getter to the ModbusEndpointThingHandler private again. Do you agree @ssalonen?
=> [modbus] BaseModbusThingHandler: Add ability to retrieve slave address

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/Utils.java, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/discovery/MiIoDiscovery.java, bundles/org.openhab.binding.miio/src/main/resources/OH-INF/binding/binding.xml, bundles/org.openhab.binding.miio/src/test/java/org/openhab/binding/miio/internal/UtilsTest.java
This allows to discover things that are not directly on the same subnet
Implements feature of #7276
=> [miio] Add discovery from cloud feature.

bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/smarthome/HandlerTemperatureSensor.java
At least the SmartHome Heizkörperthermostat by Eurotronic reports the temperature with ~½℃ resolution.
=> [amazonechocontrol] HandlerTemperatureSensor: increased resolution

bundles/org.openhab.binding.intesis/README.md, bundles/org.openhab.binding.intesis/src/main/java/org/openhab/binding/intesis/internal/handler/IntesisHomeHandler.java, bundles/org.openhab.binding.intesis/src/main/resources/OH-INF/thing/dynamic-channels.xml, bundles/org.openhab.binding.intesis/src/main/resources/OH-INF/thing/thing-types.xml
=> [intesis] Add error channels to intesisHome thing

bundles/org.openhab.io.homekit/README.md, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitAccessoryType.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitCharacteristicType.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitCommandExtension.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitImpl.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitSettings.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitAccessoryFactory.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitCharacteristicFactory.java
some clean up for OH3
remove support for legacy tagging with "tags"
remove deprecated  methods
update documentation
Fixes #9126
=> [homekit] clean up for OH3

bundles/org.openhab.binding.remoteopenhab/src/main/java/org/openhab/binding/remoteopenhab/internal/handler/RemoteopenhabBridgeHandler.java, bundles/org.openhab.binding.remoteopenhab/src/main/java/org/openhab/binding/remoteopenhab/internal/rest/RemoteopenhabRestClient.java
=> [remoteopenhab] Reduced response size from REST API items

bundles/org.openhab.binding.modbus.helioseasycontrols/README.md, bundles/org.openhab.binding.modbus.helioseasycontrols/src/main/java/org/openhab/binding/modbus/helioseasycontrols/internal/HeliosVariable.java
Fixes #9723
Signed-off-by: Bernhard Bauer <bern77@gmail.com>
=> [helioseasycontrols] Fix heat exchanger type

bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/handler/EchoHandler.java
=> [amazonechocontrol] proper handling of null values in reminders

bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/thing/group-thing-types.xml, bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/thing/light-thing-types.xml
=> [deconz] add categories and tags to lights (where applicable)

bundles/org.openhab.binding.ojelectronics/README.md, bundles/org.openhab.binding.ojelectronics/src/main/java/org/openhab/binding/ojelectronics/internal/BindingConstants.java, bundles/org.openhab.binding.ojelectronics/src/main/java/org/openhab/binding/ojelectronics/internal/OJCloudHandler.java, bundles/org.openhab.binding.ojelectronics/src/main/java/org/openhab/binding/ojelectronics/internal/OJCloudHandlerFactory.java, bundles/org.openhab.binding.ojelectronics/src/main/java/org/openhab/binding/ojelectronics/internal/ThermostatHandler.java, bundles/org.openhab.binding.ojelectronics/src/main/java/org/openhab/binding/ojelectronics/internal/ThermostatHandlerFactory.java, bundles/org.openhab.binding.ojelectronics/src/main/java/org/openhab/binding/ojelectronics/internal/common/OJGSonBuilder.java, bundles/org.openhab.binding.ojelectronics/src/main/java/org/openhab/binding/ojelectronics/internal/models/RequestModelBase.java, bundles/org.openhab.binding.ojelectronics/src/main/java/org/openhab/binding/ojelectronics/internal/models/ResponseModelBase.java, bundles/org.openhab.binding.ojelectronics/src/main/java/org/openhab/binding/ojelectronics/internal/models/SimpleResponseModel.java, bundles/org.openhab.binding.ojelectronics/src/main/java/org/openhab/binding/ojelectronics/internal/models/Thermostat.java, bundles/org.openhab.binding.ojelectronics/src/main/java/org/openhab/binding/ojelectronics/internal/models/groups/GroupContent.java, bundles/org.openhab.binding.ojelectronics/src/main/java/org/openhab/binding/ojelectronics/internal/models/thermostat/UpdateThermostatRequestModel.java, bundles/org.openhab.binding.ojelectronics/src/main/java/org/openhab/binding/ojelectronics/internal/models/userprofile/PostSignInQueryModel.java, bundles/org.openhab.binding.ojelectronics/src/main/java/org/openhab/binding/ojelectronics/internal/services/OJDiscoveryService.java, bundles/org.openhab.binding.ojelectronics/src/main/java/org/openhab/binding/ojelectronics/internal/services/RefreshGroupContentService.java, bundles/org.openhab.binding.ojelectronics/src/main/java/org/openhab/binding/ojelectronics/internal/services/RefreshService.java, bundles/org.openhab.binding.ojelectronics/src/main/java/org/openhab/binding/ojelectronics/internal/services/SignInService.java, bundles/org.openhab.binding.ojelectronics/src/main/java/org/openhab/binding/ojelectronics/internal/services/UpdateService.java, bundles/org.openhab.binding.ojelectronics/src/main/resources/OH-INF/i18n/ojelectronics_de_DE.properties, bundles/org.openhab.binding.ojelectronics/src/main/resources/OH-INF/thing/thing-types.xml
I added some new features.
- Added writable properties
- Added discovery of thermostats
I will enjoy your code review.
Please let me know if further information are needed.
=> [ojelectronics] Add discovery; enable writable properties

bundles/org.openhab.binding.dwdunwetter/src/main/java/org/openhab/binding/dwdunwetter/internal/config/DwdUnwetterConfiguration.java, bundles/org.openhab.binding.dwdunwetter/src/main/java/org/openhab/binding/dwdunwetter/internal/handler/DwdUnwetterHandler.java, bundles/org.openhab.binding.dwdunwetter/src/main/resources/OH-INF/thing/thing-types.xml, bundles/org.openhab.binding.dwdunwetter/src/test/java/org/openhab/binding/dwdunwetter/internal/handler/DwdUnwetterHandlerTest.java
- Rework channel creation to avoid slow initialization
```
2020-12-04 08:28:01.591 [WARN ] [core.thing.internal.ThingManagerImpl] - Initializing handler for thing 'dwdunwetter:dwdwarnings:71aaaeef' takes more than 5000ms.
```
=> [dwdunwetter] Rework channel creation

bundles/org.openhab.binding.remoteopenhab/src/main/java/org/openhab/binding/remoteopenhab/internal/handler/RemoteopenhabBridgeHandler.java
=> [remoteopenhab] Avoid going OFFLINE when request of items states fails

bundles/org.openhab.binding.icalendar/src/main/java/org/openhab/binding/icalendar/internal/handler/ICalendarHandler.java
- Reload calendar file asynchronously to avoid slow initialization
```
2020-12-04 08:34:08.896 [WARN ] [core.thing.internal.ThingManagerImpl] - Initializing handler for thing 'icalendar:calendar:calendar' takes more than 5000ms.
```
=> [icalendar] Reload calendar file asynchronously

bundles/org.openhab.binding.mqtt/src/test/java/org/openhab/binding/mqtt/handler/BrokerHandlerTest.java
=> [mqtt] Try to make tests more stable

bundles/org.openhab.binding.bluetooth/src/test/java/org/openhab/binding/bluetooth/util/RetryFutureTest.java
=> [bluetooth] Try to make tests more stable

bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcBaseDAO.java
- Fixed ClassCastException
See https://community.openhab.org/t/problem-with-persistence-in-oh3/109611
=> [jdbc] Fixed ClassCastException

bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/DeconzBridgeHandler.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/netutils/WebSocketConnection.java
Related to #9264 (hopefully fixes it)
In rare situations (when the connection was not established before the thing was updated) it could happen that the websocket connection tried to re-connect even though it should not.
=> [deconz] improve websocket connection process

bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/DeconzBridgeHandler.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/netutils/WebSocketConnection.java
=> [deconz] beackport of websocket connections improvements

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoAbstractHandler.java
=> [miio] only change the name if it is the default one

bundles/org.openhab.binding.deconz/README.md, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/BindingConstants.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/CommandDescriptionProvider.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/DeconzHandlerFactory.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/dto/LightState.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/DeconzBaseThingHandler.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/DeconzBridgeHandler.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/LightThingHandler.java, bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/thing/light-thing-types.xml, bundles/org.openhab.binding.deconz/src/test/java/org/openhab/binding/deconz/LightsTest.java
cf. https://community.openhab.org/t/deconz-which-thing-type-is-needed-for-lidl-melinera-led-wire/109462
=> [deconz] add support for effects on color lights

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoQuantiyTypes.java
=> [miio] extend units for miot types

bundles/org.openhab.binding.lgwebos/README.md, bundles/org.openhab.binding.linky/README.md, bundles/org.openhab.binding.powermax/README.md
=> [linky/powermax/lgwebos] Adapt README to OH3

bundles/org.openhab.binding.remoteopenhab/src/main/java/org/openhab/binding/remoteopenhab/internal/handler/RemoteopenhabBridgeHandler.java, bundles/org.openhab.binding.remoteopenhab/src/main/java/org/openhab/binding/remoteopenhab/internal/rest/RemoteopenhabRestClient.java
=> [remoteopenhab] Asynchronous reading of big API response

bundles/org.openhab.binding.amazonechocontrol/README.md, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/AmazonEchoControlBindingConstants.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/Connection.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/handler/AccountHandler.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/handler/EchoHandler.java, bundles/org.openhab.binding.amazonechocontrol/src/main/resources/OH-INF/i18n/amazonechocontrol_de.properties, bundles/org.openhab.binding.amazonechocontrol/src/main/resources/OH-INF/thing/thing-types.xml
This fixes an issue with lagging announcements due to traffic caused by unnecessary refreshes and also adds a new feature: text commands. With text commands openhab can execute commands on alexas as if they were spoken by the user. It would be really helpful to have this in OH3.
=> [amazonechocontrol] fix unnecessary refresh and add text commands

bundles/org.openhab.binding.smartthings/README.md
Signed-off-by: Jerome Luckenbach <github@luckenba.ch>
=> [Smartthings] Fixed some minor readme issue

bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/Connection.java
=> [amazonechocontrol] fix text commands stopping TTS

bundles/org.openhab.binding.miio/README.md, bundles/org.openhab.binding.miio/src/main/resources/database/dreame.vacuum.mc1808-miot.json, bundles/org.openhab.binding.miio/src/main/resources/database/dreame.vacuum.p2008-miot.json, bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.bhf1.json, bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.light.ceiling.json, bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.light.ceiling2.json, bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.light.ceiling4.json, bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.light.color1.json, bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.light.lamp1.json
Improve the yeelight with options and ranges, icons and tags
=> [miio] improve yeelight json

bundles/org.openhab.binding.deconz/README.md, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/BindingConstants.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/DeconzHandlerFactory.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/dto/GroupMessage.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/DeconzBaseThingHandler.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/DeconzBridgeHandler.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/GroupThingHandler.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/LightThingHandler.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/SensorThermostatThingHandler.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/netutils/AsyncHttpClient.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/netutils/WebSocketConnection.java, bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/thing/group-thing-types.xml, bundles/org.openhab.binding.deconz/src/test/java/org/openhab/binding/deconz/DeconzTest.java
=> [deconz] initial support for scenes

bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/providers/DsChannelTypeProvider.java, bundles/org.openhab.binding.harmonyhub/src/main/java/org/openhab/binding/harmonyhub/internal/handler/HarmonyDeviceHandler.java, bundles/org.openhab.binding.harmonyhub/src/main/java/org/openhab/binding/harmonyhub/internal/handler/HarmonyHubHandler.java, bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/handler/KM200ThingHandler.java, bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/CChannel.java, bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/internal/homie300/Property.java, bundles/org.openhab.binding.networkupstools/src/main/java/org/openhab/binding/networkupstools/internal/NUTDynamicChannelFactory.java, bundles/org.openhab.binding.sensibo/src/main/java/org/openhab/binding/sensibo/internal/handler/SensiboSkyHandler.java, bundles/org.openhab.binding.smartmeter/src/main/java/org/openhab/binding/smartmeter/internal/SmartMeterChannelTypeProvider.java, bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/schema/ApiPageParser.java, bundles/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/ChannelsTypeProviderAvailableInputs.java, bundles/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/ChannelsTypeProviderPreset.java
Related to openhab/openhab-core#1408
=> Fix StateDescription deprecations

bundles/org.openhab.binding.digitalstrom/README.md, bundles/org.openhab.binding.gardena/README.md, bundles/org.openhab.binding.homematic/README.md, bundles/org.openhab.binding.magentatv/README.md, bundles/org.openhab.binding.miio/README.base.md, bundles/org.openhab.binding.miio/README.md, bundles/org.openhab.binding.tesla/README.md, bundles/org.openhab.io.homekit/README.md
=> fix console command documentation

bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/discovery/BridgeDiscoveryParticipant.java
newer firmware revisions report "Royal Philips" as manufacturer to ensure compatibility with hue gateways. The manufacturer URL still points to "www.dresden-elektronik.de".
=> [deconz] fix gateway discovery

bundles/org.openhab.binding.teleinfo/src/test/java/org/openhab/binding/teleinfo/internal/reader/io/TeleinfoInputStreamTest.java
Timeout was 33 ms. Increased to 5 sec.
=> [teleinfo] Try to make tests more stable

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoUnsupportedHandler.java, bundles/org.openhab.binding.miio/src/main/resources/OH-INF/thing/unsupportedThing.xml
Some devices respond differently to unknown parameters and minor improvement in printed text to ease finding the files
=> [miio] improve unsupported handler

bundles/org.openhab.binding.energenie/README.md
=> [energenie] Remove PaperUI reference from README

bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/api/EnedisHttpApi.java, bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/handler/LinkyHandler.java
=> [linky] Fix data refresh (login / logout)

bundles/org.openhab.binding.tr064/src/main/resources/channels.xml
cf. https://community.openhab.org/t/oh3-fritz-box-tr064-add-on-binding/108299/13
=> [tr064] fix DSL channel definition

bundles/org.openhab.binding.http/README.md, bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/HttpThingHandler.java, bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/config/HttpThingConfig.java, bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/http/HttpResponseListener.java, bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/http/RefreshingUrlCache.java, bundles/org.openhab.binding.http/src/main/resources/OH-INF/thing/thing-types.xml
=> [http] make size of the response buffer configurable

bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcMariadbDAO.java
- Reduce size for VARCHAR columns
Fixes https://community.openhab.org/t/jdbc-creating-too-wide-columns/110252/8
```
2020-12-15 20:46:24.258 [ERROR] [org.knowm.yank.Yank                 ] - Error in SQL query!!!
java.sql.SQLException: Column length too big for column 'value' (max = 16383); use BLOB or TEXT instead Query: CREATE TABLE IF NOT EXISTS astrotimeofday_0070 (time TIMESTAMP(3) NOT NULL, value VARCHAR(65500), PRIMARY KEY(time)) Parameters: []
at org.apache.commons.dbutils.AbstractQueryRunner.rethrow(AbstractQueryRunner.java:392) ~[bundleFile:?]
at org.apache.commons.dbutils.QueryRunner.update(QueryRunner.java:491) ~[bundleFile:?]
at org.apache.commons.dbutils.QueryRunner.update(QueryRunner.java:457) ~[bundleFile:?]
at org.knowm.yank.Yank.execute(Yank.java:194) [bundleFile:?]
at …
```
=> [jdbc] Reduce size for VARCHAR columns

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/MiIoBasicChannel.java
=> [miio] fix annotation for mibasicChannel

bundles/org.openhab.binding.miio/README.md, bundles/org.openhab.binding.miio/src/main/resources/database/dreame.vacuum.mc1808-miot.json, bundles/org.openhab.binding.miio/src/main/resources/database/dreame.vacuum.p2008-miot.json, bundles/org.openhab.binding.miio/src/main/resources/database/huayi.light.fanwy-miot.json, bundles/org.openhab.binding.miio/src/main/resources/database/huayi.light.fanwy2-miot.json, bundles/org.openhab.binding.miio/src/main/resources/database/huayi.light.pis123-miot.json, bundles/org.openhab.binding.miio/src/main/resources/database/huayi.light.wy200-miot.json, bundles/org.openhab.binding.miio/src/main/resources/database/huayi.light.wyheat-miot.json, bundles/org.openhab.binding.miio/src/main/resources/database/lumi.curtain.hagl05-miot.json, bundles/org.openhab.binding.miio/src/main/resources/database/mijia.vacuum.v2-miot.json, bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.switch.sw1-miot.json, bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.heater.zb1-miot.json
=> [miio] fix wrong mappings in readme

bundles/org.openhab.binding.mqtt.generic/src/main/resources/OH-INF/thing/generic-thing.xml
=> [mqtt] Correct Typo (availabe) and propose clearer naming

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/discovery/MiIoDiscovery.java
=> [miio] Fixed NPE in discovery

bundles/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/GardenaSmartWebSocket.java
See https://community.openhab.org/t/oh3-0-0-rc1-gardena-binding/110419
=> [gardena] Fixed illegal character in consumerName

bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/GroupThingHandler.java
=> [deconz] fix scene recall

bundles/org.openhab.binding.gree/README.md
Removed the reference to PaperUI
=> [gree] README updated

bundles/org.openhab.binding.robonect/src/main/java/org/openhab/binding/robonect/internal/handler/RobonectHandler.java
=> [robonect] Fix breaking common HttpClient on shutdown

bundles/org.openhab.binding.http/src/main/resources/OH-INF/thing/thing-types.xml
=> [http] Fixed missing player channel-type

bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/AccountServlet.java
Servlet linked to PaperUI thing view
=> [amazonechocontrol] Fixed link to UI

bundles/org.openhab.automation.groovyscripting/pom.xml, bundles/org.openhab.automation.jythonscripting/pom.xml
=> Add "Bundles" to automation project names

bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/model/Season.java, bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/util/DateTimeUtils.java, bundles/org.openhab.binding.astro/src/test/java/org/openhab/binding/astro/internal/util/DateTimeUtilsTest.java
Closes https://github.com/openhab/openhab-distro/issues/1220
=> [astro] Fix for incorrect calculation of next season

bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/handler/EcobeeThermostatBridgeHandler.java
=> [ecobee] Fixed weather forecast pressure units

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoVacuumHandler.java
To support alexa integration.
closing #9172
=> [miio] change vacuum segment channel from undef to -

bundles/org.openhab.binding.globalcache/src/main/java/org/openhab/binding/globalcache/internal/discovery/GlobalCacheDiscoveryService.java, bundles/org.openhab.binding.globalcache/src/main/resources/OH-INF/thing/gc-100-06.xml, bundles/org.openhab.binding.globalcache/src/main/resources/OH-INF/thing/gc-100-12.xml, bundles/org.openhab.binding.globalcache/src/main/resources/OH-INF/thing/itach-cc.xml, bundles/org.openhab.binding.globalcache/src/main/resources/OH-INF/thing/itach-flex.xml, bundles/org.openhab.binding.globalcache/src/main/resources/OH-INF/thing/itach-ir.xml, bundles/org.openhab.binding.globalcache/src/main/resources/OH-INF/thing/itach-sl.xml, bundles/org.openhab.binding.globalcache/src/main/resources/OH-INF/thing/zmote.xml
Add representation property to all thing types.
=> [globalcache] Add representation property

bundles/org.openhab.binding.bigassfan/src/main/java/org/openhab/binding/bigassfan/internal/discovery/BigAssFanDiscoveryService.java, bundles/org.openhab.binding.bigassfan/src/main/resources/OH-INF/thing/thing-types.xml
Add representation property for all thing types
=> [bigassfan] Add representation property

bundles/org.openhab.binding.bluetooth.bluegiga/src/main/java/org/openhab/binding/bluetooth/bluegiga/internal/BlueGigaSerialHandler.java
=> [bluegiga] Improved illegal frame receiving handling

bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/SensorBaseThingHandler.java, bundles/org.openhab.binding.deconz/src/test/java/org/openhab/binding/deconz/SensorsTest.java, bundles/org.openhab.binding.deconz/src/test/resources/org/openhab/binding/deconz/fire.json
=> [deconz] improve sensor thing initialization

tools/static-code-analysis/checkstyle/suppressions.xml
Cherry-picking this change to main-branch (#7257)
* Treat packages containing .dto. the same way as java classes ending in DTO
Also-by: Arne Seime <arne.seime@gmail.com>
=> [checkstyle] Treat packages containing .dto. the same way as java classes ending in DTO (#7257)

bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/Tr064HandlerFactory.java, bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/Tr064RootHandler.java
=> [tr064] fix fritz.box lookup

bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/Tr064RootHandler.java
=> [tr064] fix missing SOAP connector initialization

bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitChangeListener.java
this PR fix the #9478 bug. 
adding listener to metadata changes. 
=> [homekit] fix for #9478. add listener to metadata changes

itests/org.openhab.binding.feed.tests/itest.bndrun, itests/org.openhab.binding.hue.tests/itest.bndrun, itests/org.openhab.binding.max.tests/itest.bndrun, itests/org.openhab.binding.modbus.tests/itest.bndrun, itests/org.openhab.binding.nest.tests/itest.bndrun, itests/org.openhab.binding.ntp.tests/itest.bndrun, itests/org.openhab.binding.systeminfo.tests/itest.bndrun, itests/org.openhab.binding.tradfri.tests/itest.bndrun, itests/org.openhab.binding.wemo.tests/itest.bndrun
Depends on https://github.com/openhab/openhab-core/pull/1997
=> Resolve itest runbundles for XStream 1.4.15

bundles/org.openhab.binding.tr064/README.md
Failure in list, two channel names were listed two times
=> [tr064]Update README.md

bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/AVMFritzBindingConstants.java, bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/discovery/AVMFritzDiscoveryService.java, bundles/org.openhab.binding.avmfritz/src/main/resources/OH-INF/thing/channel-types.xml, itests/org.openhab.binding.avmfritz.tests/src/main/java/org/openhab/binding/avmfritz/internal/discovery/AVMFritzDiscoveryServiceOSGiTest.java
- Pimp properties and channel types with proper categories
=> [avmfritz] Pimp properties and channel types with proper categories

bundles/org.openhab.binding.tr064/src/main/resources/channels.xml
=> [tr064] Fix CRCErrors channel

bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/Tr064CommunicationException.java, bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/soap/SOAPConnector.java
=> [tr064] Improved error handling

bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/discovery/VeluxBridgeFinder.java, bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/discovery/VeluxDiscoveryService.java
Enable background discovery of Bridges
=> [velux] Enabled background discovery

bundles/org.openhab.binding.alarmdecoder/src/main/feature/feature.xml
Fix description string in feature.xml
=> [alarmdecoder] Fix description in feature.xml

bundles/org.openhab.binding.comfoair/src/main/java/org/openhab/binding/comfoair/internal/ComfoAirCommandType.java, bundles/org.openhab.binding.comfoair/src/main/java/org/openhab/binding/comfoair/internal/ComfoAirHandler.java, bundles/org.openhab.binding.comfoair/src/main/java/org/openhab/binding/comfoair/internal/ComfoAirSerialConnector.java, bundles/org.openhab.binding.comfoair/src/main/java/org/openhab/binding/comfoair/internal/datatypes/DataTypeBoolean.java
Some improvements for ComfoAir binding:
- Removed non-existent read command from RS232 activation
- Better handling of control suspend
- Disable item/channel update on suspend (omit `UNDEF` values during suspend)
- Ensure `activate` channel is set correctly when linked
- Improve handling of data if non-requested commands are included in response
- fix logging of maximum retries
=> [comfoair] improve data handling

bundles/org.openhab.binding.http/README.md, bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/HttpHandlerFactory.java, bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/HttpThingHandler.java, bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/config/HttpThingConfig.java, bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/http/RateLimitedHttpClient.java, bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/http/RefreshingUrlCache.java, bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/transform/CascadedValueTransformationImpl.java, bundles/org.openhab.binding.http/src/main/resources/OH-INF/thing/thing-types.xml
cf. https://community.openhab.org/t/http-binding-limit-of-requests-per-time/110956
=> [http] Add rate-limiting to channel refresh

bundles/org.openhab.binding.ojelectronics/README.md
fix configuration sample in README
=> [ojelectronics] fix configuration sample

bundles/org.openhab.binding.http/xtend_examples.md
=> [http] Add examples

bundles/org.openhab.binding.http/README.md
Based on https://github.com/openhab/openhab-addons/blob/8de5652ed19775900ae1ee4c9e59686590112db9/bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/config/HttpChannelMode.java#L23 and some experimenting, the correct values are WRITEONLY and READONLY
=> [http]Update README.md

bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/config/Tr064SubConfiguration.java, bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/util/Util.java
=> [tr064] log warning if config invalid

bundles/org.openhab.binding.dwdunwetter/src/main/java/org/openhab/binding/dwdunwetter/internal/handler/DwdUnwetterHandler.java
- Fixed channel updates
Channel were updated with wrong suffix since my refactoring in #9229.
=> [dwdunwetter] Fixed channel updates

bundles/org.openhab.binding.kodi/src/main/resources/OH-INF/thing/thing-types.xml
- Prevent exception when formatting value
=> [kodi] Prevent exception when formatting value

bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/LightThingHandler.java
=> [deconz] properly initialize colorMode

bundles/org.openhab.binding.pioneeravr/README.md
Fixes #1594.
Signed-off-by: Chris Carman <namraccr@gmail.com>
=> [pioneeravr] Update README with correct examples for port configuration.

bundles/org.openhab.binding.chromecast/src/main/resources/OH-INF/thing/thing-types.xml
- Prevent exception when formatting value
```
2020-12-30 14:23:12.733 [WARN ] [e.internal.SseItemStatesEventBuilder] - Exception while formatting value '154.566369 s' of item chromecastKitchenCurrentTime with format '%d %unit%': d != java.math.BigDecimal
```
=> [chromecast] Prevent exception when formatting value

bundles/org.openhab.binding.modbus.helioseasycontrols/README.md
Minor changes to the item examples to reflect the correct QuantityTypes where applicable.
Signed-off-by: Bernhard Bauer <bern77@gmail.com>
=> [modbus.helioseasycontrols] Corrected some item types in the documentation.

bundles/org.openhab.binding.zoneminder/README.md
leftover after renaming of zm -> zoneminder
=> [zoneminder] Fix Item example in README.md

bundles/org.openhab.binding.icalendar/src/main/java/org/openhab/binding/icalendar/internal/ICalendarBindingConstants.java, bundles/org.openhab.binding.icalendar/src/main/java/org/openhab/binding/icalendar/internal/handler/ICalendarHandler.java
Also add migration for older things as compatible.
Fixes #9613
Signed-off-by: Michael Wodniok <michi@noorganization.org>
=> [icalendar] Add relevant handling of last_update channel

bundles/org.openhab.binding.http/README.md
=> [http] Correct typo

bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/handler/TradfriThingHandler.java
=> [tradfri] Fix NPE if gateway is unreachable

itests/org.openhab.binding.modbus.tests/src/main/java/org/openhab/binding/modbus/tests/ModbusDataHandlerTest.java
=> [modbus] Disable unstable ModbusDataHandlerTest#testRefreshOnData itest

bundles/org.openhab.binding.draytonwiser/README.md, bundles/org.openhab.binding.draytonwiser/src/main/java/org/openhab/binding/draytonwiser/internal/DraytonWiserBindingConstants.java, bundles/org.openhab.binding.draytonwiser/src/main/java/org/openhab/binding/draytonwiser/internal/api/DraytonWiserApi.java, bundles/org.openhab.binding.draytonwiser/src/main/java/org/openhab/binding/draytonwiser/internal/handler/ControllerHandler.java, bundles/org.openhab.binding.draytonwiser/src/main/java/org/openhab/binding/draytonwiser/internal/model/SystemDTO.java, bundles/org.openhab.binding.draytonwiser/src/main/resources/OH-INF/thing/thing-types.xml
This PR adds an extra option to the boiler controller thing to allow changing of the "Comfort Mode" state of the heating system.
=> [draytonwiser] Add comfort mode option to boiler controller

bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/SamsungTvHandlerFactory.java, bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/handler/SamsungTvHandler.java, bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/service/RemoteControllerService.java
Ported https://github.com/openhab/openhab-addons/pull/7499 to openHAB 3.
Fixes https://github.com/openhab/openhab-addons/issues/2916
Fixes https://github.com/openhab/openhab-addons/issues/8419
Fixes https://github.com/openhab/openhab-addons/issues/9495
=> [samsungtv] UPnP devices discovery refactored

bundles/org.openhab.binding.onewire/README.md
=> [onewire] update documentation

bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/Connection.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/handler/AccountHandler.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/jsons/JsonSmartHomeDevices.java, bundles/org.openhab.binding.amazonechocontrol/src/main/resources/OH-INF/thing/thing-types.xml
Without this changes SmartHomeDevice channels are not working correctly for my on OH-3.X. 
The problem is explained in the following issue #9639.
=> [Amazonechocontrol] fix SmartHomeDevice channels

bundles/org.openhab.binding.linuxinput/src/main/java/org/openhab/binding/linuxinput/internal/DeviceReadingHandler.java, bundles/org.openhab.binding.linuxinput/src/main/java/org/openhab/binding/linuxinput/internal/LinuxInputDiscoveryService.java, bundles/org.openhab.binding.linuxinput/src/main/java/org/openhab/binding/linuxinput/internal/Utils.java
This PR improves on  #9581 for my linux input binding.
=> [linuxinput] improve thread names

bundles/org.openhab.transform.scale/src/main/java/org/openhab/transform/scale/internal/ScaleTransformationService.java, bundles/org.openhab.transform.scale/src/main/java/org/openhab/transform/scale/internal/profiles/ScaleTransformationProfile.java, bundles/org.openhab.transform.scale/src/main/java/org/openhab/transform/scale/internal/profiles/ScaleTransformationProfileFactory.java, bundles/org.openhab.transform.scale/src/main/resources/OH-INF/config/scaleProfile.xml, bundles/org.openhab.transform.scale/src/main/resources/readme.txt
- Added `ConfigOptionProvider` to provide filenames ending with `.scale`  in Profile configuration
Depends on https://github.com/openhab/openhab-core/pull/2052
=> [scale] Added 'ConfigOptionProvider' to provide filenames ending with '.scale'  in Profile configuration

bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/util/Util.java, bundles/org.openhab.binding.tr064/src/main/resources/channels.xml
=> [tr064] fix comment in SOAP request

bundles/org.openhab.io.openhabcloud/README.md
path has changed for uuid since openhab3
/var/lib/openhab/openhabcloud/secret for secret since openhab3
=> [openhabcloud] APT Installation path update for openHAB 3

bundles/org.openhab.binding.lcn/src/main/feature/feature.xml, bundles/org.openhab.binding.lcn/src/main/resources/OH-INF/config/config.xml, bundles/org.openhab.binding.lcn/src/main/resources/OH-INF/thing/thing-types.xml
=> [lcn] Set advanced flags more reasonably

bundles/org.openhab.binding.remoteopenhab/src/main/java/org/openhab/binding/remoteopenhab/internal/handler/RemoteopenhabBridgeHandler.java
=> [remoteopenhab] Catch exception when parsing item state

bundles/org.openhab.binding.lgwebos/README.md
Replacing one line from the Readme file, which was outdated.
=> [lgwebos] Remove outdated statement from README.md

bundles/org.openhab.automation.groovyscripting/README.md, bundles/org.openhab.automation.groovyscripting/pom.xml
For the changelog see: http://groovy-lang.org/changelogs/changelog-3.0.7.html
Fixes #8951
=> [groovyscripting] Update Groovy to 3.0.7 and add more docs

bundles/org.openhab.binding.tr064/README.md
=> [tr064] improve documentation

bundles/org.openhab.binding.wifiled/README.md
[WiFi LED] Expanded example
Added a detailed example
=>  [WiFi LED] Expanded example

bundles/org.openhab.binding.http/README.md, bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/HttpThingHandler.java, bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/config/HttpChannelConfig.java, bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/converter/NumberItemConverter.java, bundles/org.openhab.binding.http/src/main/resources/OH-INF/config/config.xml, bundles/org.openhab.binding.http/src/main/resources/OH-INF/thing/thing-types.xml, bundles/org.openhab.binding.http/src/test/java/org/openhab/binding/http/internal/converter/ConverterTest.java
=> [http] enable UoM for number channels

bundles/org.openhab.binding.tibber/README.md
=> [tibber] Fix typos in README.md

bundles/org.openhab.binding.openwebnet/README.md, bundles/org.openhab.binding.openwebnet/pom.xml, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/OpenWebNetBindingConstants.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/handler/OpenWebNetAutomationHandler.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/handler/OpenWebNetBridgeHandler.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/handler/OpenWebNetGenericHandler.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/handler/OpenWebNetLightingHandler.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/handler/OpenWebNetThingHandler.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/discovery/OpenWebNetDeviceDiscoveryService.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/discovery/UsbGatewayDiscoveryService.java, bundles/org.openhab.binding.openwebnet/src/test/java/org/openhab/binding/openwebnet/handler/OwnIdTest.java
* added ZigBee USB Gateway auto discovery (fixes #9171)
* added management of disconnect/reconnect of gateway from USB port (fixes #9170)
* fixed up/down inverted automation messages for old firmwares (fixes #9651)
* removed warn logs when reconnecting BUS command connection
* fixed dimmers creating loop when lowered from 20 to 10% (fixes #9317)
* now using openwebnet4j 0.3.4 (nrjavaserial 5.2.1)
=> [openwebnet] Improvements for ZigBee USB and Dimmers

bundles/org.openhab.binding.neato/src/main/java/org/openhab/binding/neato/internal/discovery/NeatoAccountDiscoveryService.java
Signed-off-by: Jeff Lauterbach <jjlauterbach@gmail.com>
=> [neato] Fixed NPE in discovery service

bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/handler/NanoleafControllerHandler.java
Color temperature channels are supposed to be cold at 0% and warm at 100% - this PR fixes the behavior for nanoleaf.
=> [nanoleaf] Fixed color temperature setting

bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/internal/discovery/TadoDiscoveryService.java, bundles/org.openhab.binding.tado/src/main/resources/OH-INF/thing/thing-types.xml
Added Representation Properties so that already instantiated Things will be hidden in the InBox
=> [tado] Hide already instantiated Things in the InBox

bundles/org.openhab.persistence.jdbc/pom.xml
- Bump mysql-connector-java to version 8.0.22
Superseedes #8511
=> [jdbc] Bump mysql-connector-java to version 8.0.22

bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/AVMFritzBindingConstants.java, bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/dto/DeviceModel.java, bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/AVMFritzBaseThingHandler.java, bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/AVMFritzButtonHandler.java
- Fixed channel update for DECT440 rocker
Fixes #9731
=> [avmfritz] Fixed channel update for DECT440 rocker

bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/smarthome/Constants.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/smarthome/HandlerThermostatController.java
cf.: https://community.openhab.org/t/amazon-echo-control-binding-oh3-no-channels-in-ui/113460/13
=> [amazonechocontrol] fix thermostat handler

bundles/org.openhab.binding.tibber/README.md, bundles/org.openhab.binding.tibber/src/main/java/org/openhab/binding/tibber/internal/TibberBindingConstants.java, bundles/org.openhab.binding.tibber/src/main/java/org/openhab/binding/tibber/internal/handler/TibberHandler.java, bundles/org.openhab.binding.tibber/src/main/java/org/openhab/binding/tibber/internal/handler/TibberPriceConsumptionHandler.java, bundles/org.openhab.binding.tibber/src/main/resources/OH-INF/thing/thing-types.xml
Binding adjustments/enhancement, added channel and channel corrections due to API changes.
[https://community.openhab.org/t/tibber-binding/67019/120?u=kjoglums](https://community.openhab.org/t/tibber-binding/67019/120?u=kjoglums) 
Closes #9796
Signed-off-by: Stian Kjoglum <stiankj@online.no>
=> [tibber] Enhancement, added channel and channel corrections due to API changes

bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/handler/NanoleafControllerHandler.java
- Removed dependency on org.apache.commons
Related to #7722
=> [nanoleaf] Removed dependency on org.apache.commons

bundles/org.openhab.persistence.influxdb/README.md
Improvement: Knowing exactly where to put the configuration parameters is useful for noobs like myself.
=> [influxdb] Add path of the configuration file to Readme

bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/command/ControlCommand.java, bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/command/ControlObjectCommand.java, bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/command/SetClockCommand.java, bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/handler/Ethm1BridgeHandler.java, bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/handler/IntRSBridgeHandler.java, bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/handler/SatelBridgeHandler.java, bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/handler/SatelStateThingHandler.java, bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/protocol/Ethm1Module.java, bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/util/StringUtils.java, bundles/org.openhab.binding.satel/src/test/java/org/openhab/binding/satel/internal/util/StringUtilsTest.java
=> [satel] Removed dependency on 'org.apache.commons.lang'

itests/org.openhab.binding.astro.tests/itest.bndrun, itests/org.openhab.binding.avmfritz.tests/itest.bndrun, itests/org.openhab.binding.feed.tests/itest.bndrun, itests/org.openhab.binding.hue.tests/itest.bndrun, itests/org.openhab.binding.max.tests/itest.bndrun, itests/org.openhab.binding.modbus.tests/itest.bndrun, itests/org.openhab.binding.nest.tests/itest.bndrun, itests/org.openhab.binding.ntp.tests/itest.bndrun, itests/org.openhab.binding.systeminfo.tests/itest.bndrun, itests/org.openhab.binding.tradfri.tests/itest.bndrun, itests/org.openhab.binding.wemo.tests/itest.bndrun, itests/org.openhab.persistence.mapdb.tests/itest.bndrun
Depends on https://github.com/openhab/openhab-core/pull/2120
=> Resolve itests for BOM changes

bundles/org.openhab.binding.miio/README.md, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoQuantiyTypes.java, bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.airpurifier.m1.json, bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.airpurifier.ma4-miot.json, bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.airpurifier.mb3-miot.json
as per https://community.openhab.org/t/binding-request-philips-air-purifier/66304/50
=> [miio] Improve Airpurifiers

bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaAccountHandler.java, bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaVehicleHandler.java
- Removed dependency on org.apache.commons
Related to #7722
=> [tesla] Removed dependency on org.apache.commons

bundles/org.openhab.binding.amazonechocontrol/pom.xml, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/AccountServlet.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/BindingServlet.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/Connection.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/channelhandler/ChannelHandlerAnnouncement.java
Related to #7722 
Replace dependency on o.a.c.l.* with unbescape (as discussed in linked issue).cwe
StringUtils.escapeHtml -> HtmlEscape.escapeHtml4
StringUtils.escapeXml -> XmlEscape.escapeXml10
=> [amazonechocontrol] remove dependency on o.a.c.l

bundles/org.openhab.binding.miio/README.md, bundles/org.openhab.binding.miio/src/main/resources/database/yunmi.waterpurifier.lx8.json
As per https://community.openhab.org/t/xiaomi-robot-vacuum-binding/31317/1764
=> [miio] improve Mi Water Purifier 600G yunmi.waterpuri.lx8.

bundles/org.openhab.binding.miio/README.md, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoDevices.java, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoQuantiyTypes.java, bundles/org.openhab.binding.miio/src/main/resources/database/dreame.vacuum.mc1808-miot.json, bundles/org.openhab.binding.miio/src/main/resources/database/dreame.vacuum.p2009-miot.json
Closing: #9558
add support dreame vacuum d9
Minor fixes mc1808-miot
=> [miio] add support for dreame vacuum d9

bundles/org.openhab.binding.satel/README.md, bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/SatelHandlerFactory.java, bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/discovery/SatelDeviceDiscoveryService.java
=> [satel] Thing discovery fix

bundles/org.openhab.binding.tr064/README.md
=> [tr064] Improve PHONEBOOK profile documentation

bundles/org.openhab.binding.miio/src/main/resources/database/yunmi.waterpurifier.json, bundles/org.openhab.binding.miio/src/main/resources/database/yunmi.waterpurifier.lx8.json, bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.airpurifier.ma4-miot.json, bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.airpurifier.mb3-miot.json
note: some misc sorting changes in the purifier done by my validator as well
=> [miio] fix channels with invalid names

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoBasicHandler.java
=> [miio] Fix double status update

bundles/org.openhab.persistence.jdbc/src/main/feature/feature.xml, features/pom.xml
- Do not define bundle related versions in OH feature file
See https://github.com/openhab/openhab-addons/pull/9810#issuecomment-760533170
Related to #8883
Related to #9810
=> [jdbc] Do not define bundle related versions in OH feature file

bundles/org.openhab.binding.miio/README.md, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoDevices.java, bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.airpurifier.mb4-miot.json
=> [miio] add support for zhimi airpurifier 3C (mb4)

bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/LightThingHandler.java
Related to https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4248
=> [deconz] fix loglevel

bundles/org.openhab.binding.mqtt.generic/src/main/resources/OH-INF/thing/channels.xml
=> [mqtt.generic] Fix trigger channel definition

bundles/org.openhab.binding.http/README.md
=> [http] add note on escaping URLs

bundles/org.openhab.binding.heos/src/main/feature/feature.xml, bundles/org.openhab.binding.network/pom.xml, bundles/org.openhab.binding.network/src/main/feature/feature.xml, itests/org.openhab.binding.ntp.tests/itest.bndrun
See discussion https://github.com/openhab/openhab-core/pull/2141#issuecomment-764938965
Nrjavaserial needs it and we want the latest version
=> Bump Apache Commons Net to 3.7.2

bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/OpenWeatherMapBindingConstants.java, bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/handler/OpenWeatherMapUVIndexHandler.java
- Fixed UV-Index Channel Group 
=> [openweathermap] Fixed UV-Index Channel Group Creation

bundles/org.openhab.binding.tradfri/src/main/resources/OH-INF/i18n/tradfri_de.properties, bundles/org.openhab.binding.tradfri/src/main/resources/OH-INF/thing/thing-types.xml
- Use system default channel types for lights
=> [tradfri] Use system default channel types for lights

bundles/org.openhab.binding.mqtt.generic/README.md
Correct grammar in troubleshooting section
=> [mqtt.generic] Update README.md

bundles/org.openhab.binding.deconz/README.md, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/BindingConstants.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/dto/LightState.java, bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/LightThingHandler.java, bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/thing/light-thing-types.xml
=> [deconz] add ontime feature

bundles/org.openhab.binding.neeo/src/main/java/org/openhab/binding/neeo/internal/NeeoBrainConfig.java, bundles/org.openhab.binding.neeo/src/main/java/org/openhab/binding/neeo/internal/NeeoDeviceConfig.java, bundles/org.openhab.binding.neeo/src/main/java/org/openhab/binding/neeo/internal/NeeoHandlerCallback.java, bundles/org.openhab.binding.neeo/src/main/java/org/openhab/binding/neeo/internal/NeeoRoomConfig.java, bundles/org.openhab.binding.neeo/src/main/java/org/openhab/binding/neeo/internal/handler/NeeoBrainHandler.java, bundles/org.openhab.binding.neeo/src/main/java/org/openhab/binding/neeo/internal/handler/NeeoForwardActionsServlet.java
=> [neeo] fix forwardActionServlet and code improvements

bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/api/MeterRealtimeBodyDataDTO.java, bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/handler/FroniusBaseThingHandler.java
Fix invalid json data error reported here https://community.openhab.org/t/fronius-how-to-get-the-daily-total-energy-consumption-and-grid-import-export/109332/6
=> [fronius] fix invalid json error on meter data

bundles/org.openhab.binding.icalendar/src/main/java/org/openhab/binding/icalendar/internal/handler/ICalendarHandler.java
- Use cache folder to store calendar file
=> [icalendar] Use cache folder to store calendar file

bundles/org.openhab.binding.dscalarm/pom.xml, bundles/org.openhab.binding.heos/pom.xml, bundles/org.openhab.binding.heos/src/main/feature/feature.xml, bundles/org.openhab.binding.kaleidescape/pom.xml, bundles/org.openhab.binding.lutron/pom.xml, bundles/org.openhab.binding.magentatv/pom.xml, bundles/org.openhab.binding.magentatv/src/main/feature/feature.xml, bundles/org.openhab.binding.network/pom.xml, bundles/org.openhab.binding.network/src/main/feature/feature.xml, bundles/org.openhab.binding.ntp/pom.xml, bundles/org.openhab.binding.ntp/src/main/feature/feature.xml, bundles/org.openhab.binding.opensprinkler/pom.xml, bundles/org.openhab.binding.opensprinkler/src/main/feature/feature.xml, bundles/org.openhab.binding.pjlinkdevice/pom.xml, bundles/org.openhab.binding.pjlinkdevice/src/main/feature/feature.xml, bundles/org.openhab.binding.plclogo/pom.xml, bundles/org.openhab.binding.plclogo/src/main/feature/feature.xml, bundles/org.openhab.binding.russound/pom.xml, bundles/org.openhab.binding.russound/src/main/feature/feature.xml, bundles/org.openhab.binding.zway/pom.xml, bundles/org.openhab.binding.zway/src/main/feature/feature.xml, bundles/pom.xml, pom.xml
Adapts the add-ons for the changes in https://github.com/openhab/openhab-core/pull/2151
=> Add POM and feature dependencies for commons-net

bundles/org.openhab.binding.serial/README.md
Corrections to the config examples.
=> [serial] Correct config examples

bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/Beam.xml, bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/PLAYBAR.xml, bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/PLAYBASE.xml
=> [sonos] Add sub/surround controls to Beam, Playbar and Playbase

bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/DeconzBridgeHandler.java
=> [deconz] fix missing re-connect if first request timed out

bundles/org.openhab.binding.heos/src/main/java/org/openhab/binding/heos/internal/handler/HeosBridgeHandler.java, bundles/org.openhab.binding.heos/src/main/java/org/openhab/binding/heos/internal/handler/HeosChannelHandlerControl.java, bundles/org.openhab.binding.heos/src/main/java/org/openhab/binding/heos/internal/json/payload/Media.java, bundles/org.openhab.binding.heos/src/main/java/org/openhab/binding/heos/internal/resources/HeosEventListener.java, bundles/org.openhab.binding.heos/src/main/java/org/openhab/binding/heos/internal/resources/HeosMediaEventListener.java, bundles/org.openhab.binding.heos/src/main/java/org/openhab/binding/heos/internal/resources/HeosSystemEventListener.java
Update PAUSE/STOP handling depending on the item that is currently playing.
As discussed in https://community.openhab.org/t/heos-denon-support/3449/379?u=martinvw
I must admit I did not test in my OH3 install, will try that later today
The default handling of pause vs stop does not work consistently between online-radio and music from your network, this PR aims to improve that handling.
You can download a test-version at: https://download.martinvw.nl/org.openhab.binding.heos-3.1.0-SNAPSHOT-stop-pause.jar
=> [HEOS] Update pause/stop handling

bundles/org.openhab.binding.miio/src/main/resources/database/cgllc.airmonitor.s1.json, bundles/org.openhab.binding.miio/src/main/resources/database/chuangmi.plug.m1.json, bundles/org.openhab.binding.miio/src/main/resources/database/chuangmi.plug.v3.json, bundles/org.openhab.binding.miio/src/main/resources/database/chuangmi.plug.v3fw.json, bundles/org.openhab.binding.miio/src/main/resources/database/yunmi.waterpurifier.json, bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.airpurifier.m1.json, bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.airpurifier.v6.json, bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.airpurifier.v7.json, bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.heater.za1.json, bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.heater.za2-miot.json, bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.heater.zb1-miot.json, bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.humidifier.ca4.json, bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.humidifier.cb1.json, bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.humidifier.v1.json, bundles/org.openhab.binding.miio/src/main/resources/database/zimi.powerstrip.v2.json
=> [miio] use json db to drive temperature channel definitions

bundles/org.openhab.binding.ihc/src/main/resources/OH-INF/thing/controller.xml
=> [ihc] Fixed extensible channel names

bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosXMLParser.java, bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/handler/ZonePlayerHandler.java
=> [sonos] Fix sub/surround controls

bundles/org.openhab.binding.openuv/README.md, bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/OpenUVBindingConstants.java, bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/handler/OpenUVReportHandler.java, bundles/org.openhab.binding.openuv/src/main/resources/OH-INF/thing/thing-types.xml
=> [OpenUV] Marked the SafeExposure channel as extensible so user can add it via UI.

bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/Connection.java
=> [amazonechocontrol] fix routines

bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/Connection.java
=> [amazonechocontrol] fix routines (backport)

bundles/org.openhab.persistence.influxdb/README.md
=> [influxdb] FIX: Documentation Grammar

bundles/org.openhab.binding.amazondashbutton/src/main/java/org/openhab/binding/amazondashbutton/internal/AmazonDashButtonBindingConstants.java, bundles/org.openhab.binding.amazondashbutton/src/main/java/org/openhab/binding/amazondashbutton/internal/discovery/AmazonDashButtonDiscoveryService.java
=> [amazondashbutton] fix representation property

bundles/org.openhab.binding.remoteopenhab/src/main/java/org/openhab/binding/remoteopenhab/internal/rest/RemoteopenhabRestClient.java
=> [remoteopenhab] Prefer StringContentProvider

bundles/org.openhab.binding.smartmeter/src/main/java/org/openhab/binding/smartmeter/internal/SmartMeterChannelTypeProvider.java
=> [smartmeter] Fix NPE while trying to get ChannelType

bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/handler/EchoHandler.java
=> [amazonechocontrol] fix missing time (backport from 3.0)

bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/LcnBindingConstants.java, bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/LcnModuleHandler.java, bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/connection/Connection.java, bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/connection/ConnectionStateSegmentScan.java, bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/connection/ModInfo.java, bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/connection/RequestStatus.java, bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/subhandler/AbstractLcnModuleSubHandler.java, bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/subhandler/AbstractLcnModuleVariableSubHandler.java, bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/subhandler/LcnModuleMetaFirmwareSubHandler.java, bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/subhandler/LcnModuleOutputSubHandler.java, bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/subhandler/LcnModuleRvarLockSubHandler.java, bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/subhandler/LcnModuleRvarSetpointSubHandler.java, bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/subhandler/LcnModuleThresholdSubHandler.java, bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/subhandler/LcnModuleVariableSubHandler.java
=> [lcn] Fix several bugs in measurement processing with firmware before 2013

bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/handler/EchoHandler.java
=> [amazonechocontrol] Fix requireNonNullElse: it is java 9 and beyond.

bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/handler/ZonePlayerHandler.java
=> [sonos] Fix battery level (Move)

bundles/org.openhab.binding.exec/src/main/java/org/openhab/binding/exec/internal/handler/ExecHandler.java
Trivial change to add support for FreeBSD and the other BSDs.
Signed-off-by: Juergen Weber <weberjn@gmail.com>
=> [exec] add support for *BSD OSes

bundles/org.openhab.binding.miio/README.base.md, bundles/org.openhab.binding.miio/README.md, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoVacuumHandler.java, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/robot/RobotCababilities.java, bundles/org.openhab.binding.miio/src/main/resources/OH-INF/thing/vacuumThing.xml
=> [miio] add channel for is_locating

bundles/org.openhab.binding.http/README.md, bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/HttpThingHandler.java, bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/config/HttpChannelConfig.java, bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/config/HttpThingConfig.java, bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/http/RateLimitedHttpClient.java, bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/http/RefreshingUrlCache.java, bundles/org.openhab.binding.http/src/main/resources/OH-INF/config/config.xml, bundles/org.openhab.binding.http/src/main/resources/OH-INF/thing/thing-types.xml
=> [http] add POST/PUT support for state requests

bundles/org.openhab.binding.irobot/README.md, bundles/org.openhab.binding.irobot/src/main/java/org/openhab/binding/irobot/internal/IRobotBindingConstants.java, bundles/org.openhab.binding.irobot/src/main/java/org/openhab/binding/irobot/internal/discovery/IRobotDiscoveryService.java, bundles/org.openhab.binding.irobot/src/main/java/org/openhab/binding/irobot/internal/dto/IdentProtocol.java, bundles/org.openhab.binding.irobot/src/main/java/org/openhab/binding/irobot/internal/dto/MQTTProtocol.java, bundles/org.openhab.binding.irobot/src/main/java/org/openhab/binding/irobot/internal/handler/RoombaHandler.java, bundles/org.openhab.binding.irobot/src/main/resources/OH-INF/thing/thing-types.xml
Ehnancements according to users' requests:
- Add upload_map channel to control map uploading
- Add support for i7-specific properties
=> [irobot] Some enhancements

CODEOWNERS, bundles/org.openhab.binding.nanoleaf/README.md, bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/NanoleafBindingConstants.java, bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/OpenAPIUtils.java, bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/discovery/NanoleafMDNSDiscoveryParticipant.java, bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/handler/NanoleafControllerHandler.java, bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/handler/NanoleafPanelHandler.java, bundles/org.openhab.binding.nanoleaf/src/main/resources/OH-INF/i18n/nanoleaf.properties, bundles/org.openhab.binding.nanoleaf/src/main/resources/OH-INF/i18n/nanoleaf_de.properties, bundles/org.openhab.binding.nanoleaf/src/test/java/org/openhab/binding/nanoleaf/internal/OpenAPUUtilsTest.java
New Nanoleaf Shapes support and small fixes
- New Nanoleaf shapes support for touch
- Added even more info to readme
- Small log changes (less noisy logs)
- beta firmware version number fix
https://openhab.jfrog.io/openhab/libs-pullrequest-local/org/openhab/addons/bundles/org.openhab.binding.nanoleaf/3.1.0-SNAPSHOT/
=> [nanoleaf] CODEOWNERs, add Shapes Support, beta-firmware support

bundles/org.openhab.binding.smartmeter/src/main/java/org/openhab/binding/smartmeter/SmartMeterBindingConstants.java, bundles/org.openhab.binding.smartmeter/src/main/java/org/openhab/binding/smartmeter/internal/iec62056/Iec62056_21SerialConnector.java
=> [smartmeter] Fix trying to create channels from invalid data

bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/WLedBindingConstants.java, bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/WLedHandler.java
[WLED] Fix brightness handling for HSBType (#9836)
- Brightness was calculated into color as well as into master brightness when command was HSBType
=> [WLED] Fix brightness handling for HSBType (Fixes #9836)

CODEOWNERS, bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/UniFiBindingConstants.java, bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/UniFiControllerThingConfig.java, bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/model/UniFiController.java, bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/model/UniFiControllerRequest.java, bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/handler/UniFiControllerThingHandler.java, bundles/org.openhab.binding.unifi/src/main/resources/OH-INF/thing/thing-types.xml
This should fix: #9001
Took inspiration from: [Pull 8724](https://github.com/openhab/openhab-addons/pull/8724)
=> [unifi] Added support for UniFi OS

bundles/org.openhab.binding.denonmarantz/README.md
Replaces #8603 which was made against the wrong branch. Also incorporated review comments.
=> [denonmarantz] Update protocol reference in readme

bundles/org.openhab.binding.mqtt.homie/src/test/java/org/openhab/binding/mqtt/homie/internal/handler/HomieThingHandlerTests.java, bundles/org.openhab.binding.oceanic/src/main/java/org/openhab/binding/oceanic/internal/handler/NetworkOceanicThingHandler.java, bundles/org.openhab.binding.oceanic/src/main/java/org/openhab/binding/oceanic/internal/handler/OceanicThingHandler.java, bundles/org.openhab.binding.smartmeter/src/main/java/org/openhab/binding/smartmeter/internal/SmartMeterHandler.java
- Adjustments for nullness annotated TypeParser
Depends on https://github.com/openhab/openhab-core/pull/2181
=> Adjustments for nullness annotated TypeParser

bundles/org.openhab.binding.networkupstools/src/test/java/org/openhab/binding/networkupstools/internal/NutNameChannelsTest.java
fixes #10059 introduced by #10017 
=> [networkupstools] fix tests

bundles/org.openhab.voice.googletts/README.md
- Remove references to Paper UI
=> [googletts] Remove references to Paper UI

bundles/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/LxDiscoveryParticipant.java
=> [loxone] fix representation property

bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/discovery/SmartHomeDevicesDiscovery.java, bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/jsons/JsonSmartHomeCapabilities.java
=> [amazonechocontrol] fix smarthome device naming

bundles/org.openhab.binding.smartmeter/src/main/java/org/openhab/binding/smartmeter/internal/iec62056/Iec62056_21SerialConnector.java
=> [smartmeter] Fix Thing OFFLINE Communication Error due Exception in last PR

bundles/org.openhab.binding.modbus.sunspec/README.md
Signed-off-by: Markus Storm <markus.storm@gmx.net>
=> [modbus] fix wrong unit in binding docs

bundles/org.openhab.binding.folderwatcher/README.md
Update readme to use dummy parameters
=> [folderwatcher] Update README.md

bundles/org.openhab.binding.bluetooth.enoceanble/src/main/java/org/openhab/binding/bluetooth/enoceanble/internal/EnoceanBleDiscoveryParticipant.java
=> [bluetooth.enoceanble] Changed logging level for discovered devices

bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/discovery/MelCloudDiscoveryService.java, bundles/org.openhab.binding.melcloud/src/main/resources/OH-INF/thing/acDevice.xml, bundles/org.openhab.binding.melcloud/src/main/resources/OH-INF/thing/heatpumpDevice.xml
-  Fixed representation property
Closes #10128
=> [melcloud] Fixed representation property

bundles/org.openhab.binding.nibeheatpump/contrib/NibeGW/RasPi/nibegw.c
=> [nibeheatpump] Fixed compile error in RasPi

bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/subhandler/LcnModuleRvarSetpointSubHandler.java, bundles/org.openhab.binding.lcn/src/test/java/org/openhab/binding/lcn/internal/subhandler/LcnModuleRvarSetpointSubHandlerTest.java
=> [lcn] Fix RVar setpoint modification for modules before 2006

bundles/org.openhab.binding.http/README.md
=> [http] Added example and explanation how to provide multiple headers

bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/discovery/internal/BluetoothDiscoveryService.java
Many times a device might not get discovered correctly due to a variety of real world issues. Currently devices can only get discovered once, so a device that is discovered incorrectly would never have a chance get discovered correctly.
The PR adds an expiration to discovered devices so an attempt can be made to rediscover them after a minute has passed.
=> [bluetooth] Expire discovery snapshots so that devices can be rediscovered

bundles/org.openhab.binding.bluetooth.bluegiga/src/main/java/org/openhab/binding/bluetooth/bluegiga/handler/BlueGigaBridgeHandler.java, bundles/org.openhab.binding.bluetooth.bluegiga/src/main/java/org/openhab/binding/bluetooth/bluegiga/internal/BlueGigaResponsePackets.java, bundles/org.openhab.binding.bluetooth.bluegiga/src/main/java/org/openhab/binding/bluetooth/bluegiga/internal/BlueGigaSerialHandler.java
=> [bluetooth.bluegiga] Introduced better initialization functionality

bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/AbstractAreaHandler.java, bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/AbstractOmnilinkStatusHandler.java, bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/AudioZoneHandler.java, bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/HumiditySensorHandler.java, bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/LockHandler.java, bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/TempSensorHandler.java, bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/ThermostatHandler.java, bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/UnitHandler.java, bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/ZoneHandler.java, bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/units/FlagHandler.java, bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/units/UpbRoomHandler.java
=> [OmniLink] Fix spelling of status

bundles/org.openhab.binding.pixometer/README.md
=> [pixometer] Update README.md

bundles/org.openhab.binding.mpd/src/main/java/org/openhab/binding/mpd/internal/handler/MPDHandler.java
Fixes #10142.
Signed-off-by: Stefan Roellin <stefan@roellin-baumann.ch>
=> [mpd] fix invalid volume

bundles/org.openhab.binding.modbus.sunspec/src/main/resources/OH-INF/thing/inverter-channel-types.xml
Signed-off-by: Jan Philipp Giel <mail@philsown.de>
Follow-Up to #10175 where some inverter-channel-types were still missing
=> [modbus.sunspec] Fix decimal number handling for inverter channel types

bundles/org.openhab.binding.icloud/src/main/resources/OH-INF/i18n/iCloud_de.properties
Signed-off-by: Panagiotis Doulgeris <panagiotis.doulgeris@outlook.com>
=> [icloud] Add german translation

CODEOWNERS
=> remove @J-N-K from CODEOWNERS

bundles/org.openhab.binding.miio/README.md, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoDevices.java, bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.fan.za5-miot.json
=> [miio] add support for Smartmi Standing Fan 3 zhimi.fan.za5

bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/thing/sensor-thing-types.xml
- Pimp properties and channel types with proper categories
=> [deconz] Pimp properties and channel types with proper categories

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoHandlerFactory.java
Fix error that sometimes occurs during bundle restart
=> [miio] fix bundle restart error

bundles/org.openhab.binding.amazonechocontrol/README.md
fix typo (cannels to channels)
=> Update README.md to fix typo

bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/converter/PlayerItemConverter.java
=> [http] Fix Player Converter State Issue

itests/org.openhab.binding.astro.tests/itest.bndrun, itests/org.openhab.binding.avmfritz.tests/itest.bndrun, itests/org.openhab.binding.feed.tests/itest.bndrun, itests/org.openhab.binding.hue.tests/itest.bndrun, itests/org.openhab.binding.max.tests/itest.bndrun, itests/org.openhab.binding.modbus.tests/itest.bndrun, itests/org.openhab.binding.nest.tests/itest.bndrun, itests/org.openhab.binding.ntp.tests/itest.bndrun, itests/org.openhab.binding.systeminfo.tests/itest.bndrun, itests/org.openhab.binding.tradfri.tests/itest.bndrun, itests/org.openhab.binding.wemo.tests/itest.bndrun, itests/org.openhab.persistence.mapdb.tests/itest.bndrun, pom.xml
See: https://github.com/bndtools/bnd/wiki/Changes-in-5.3.0
Related to https://github.com/openhab/openhab-core/pull/2217
=> Update bnd to 5.3.0

CODEOWNERS
* Fix wrong username
* Remove modbus transport
=> Improve CODEOWNERS

bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/enums/DeviceType.java
Adding additional models to deviceType enum - "mono4" and "strip6" (please note this is not a typo in "strip6" - six is at the end and without 'e')   - based on the analysis of the debug info those new models are not being recognised by Yeelight binding in OH3 and as a result the bulb or the led stripe is constantly showing offline despite correct device id.
=> [yeelight] Update DeviceType.java

bundles/org.openhab.binding.icalendar/README.md
Just corrects documentation bugs.
=> [icalendar] Fixes #10303: small changes to docs

bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/discovery/ZonePlayerDiscoveryParticipant.java
=> [sonos] Fix discovery of Ikea SYYMFONISK models

bundles/org.openhab.binding.heos/src/main/java/org/openhab/binding/heos/internal/api/HeosFacade.java, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/cloud/CloudLoginDTO.java, bundles/org.openhab.binding.revogi/src/main/java/org/openhab/binding/revogi/internal/api/StatusService.java, bundles/org.openhab.binding.revogi/src/main/java/org/openhab/binding/revogi/internal/api/SwitchService.java
Only Eclipse JDT annotations should be used, see:
https://www.openhab.org/docs/developer/guidelines.html#null-annotations
=> Remove org.jetbrains.annotations.NotNull

bundles/org.openhab.binding.openweathermap/README.md, bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/discovery/OpenWeatherMapDiscoveryService.java
- Added hint about deprecation of UV Index API and removes Thing from discovery
See https://openweather.co.uk/blog/post/uv-index-now-part-one-call-api
The [Ultraviolet Index API](https://openweathermap.org/api/uvi) has been deprecated due to a low data granularity and will no longer be supported after the 1st of April, 2021. However, those who are currently using this API and not willing to switch to the newer version, will still be able to access the deprecated product. 
=> [openweathermap] Added hint about deprecation of UV Index API

bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/SystemType.java, bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/TemperatureFormat.java, bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/discovery/ObjectPropertyRequest.java, bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/discovery/OmnilinkDiscoveryService.java, bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/exceptions/BridgeOfflineException.java, bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/AbstractAreaHandler.java, bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/AbstractOmnilinkHandler.java, bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/AudioSourceHandler.java, bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/AudioZoneHandler.java, bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/HumiditySensorHandler.java, bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/LockHandler.java, bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/OmnilinkBridgeHandler.java, bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/TempSensorHandler.java, bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/ThermostatHandler.java, bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/UnitHandler.java, bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/ZoneHandler.java
=> [OmniLink] Minor restructuring of binding code

bundles/org.openhab.binding.onewire/src/main/resources/OH-INF/config/config.xml, bundles/org.openhab.binding.onewire/src/main/resources/OH-INF/thing/bae09x.xml, bundles/org.openhab.binding.onewire/src/main/resources/OH-INF/thing/bridge.xml, bundles/org.openhab.binding.onewire/src/main/resources/OH-INF/thing/common.xml, bundles/org.openhab.binding.onewire/src/main/resources/OH-INF/thing/multisensor.xml
=> [onewire] Fix deprecated tag "required"

bundles/org.openhab.binding.somfytahoma/src/main/resources/OH-INF/config/config.xml
=> [somfytahoma] Fix deprecated tag "required"

bundles/org.openhab.binding.knx/src/main/resources/OH-INF/config/channelConfig.xml, bundles/org.openhab.binding.knx/src/main/resources/OH-INF/thing/ip.xml, bundles/org.openhab.binding.knx/src/main/resources/OH-INF/thing/serial.xml
=> [knx] Fix deprecated tag "required"

bundles/org.openhab.binding.velux/src/main/resources/OH-INF/config/config.xml
=> [velux] Fix deprecated tag "required"

bundles/org.openhab.binding.digitalstrom/src/main/resources/OH-INF/config/bridgeConfig.xml, bundles/org.openhab.binding.digitalstrom/src/main/resources/OH-INF/config/deviceConfig.xml, bundles/org.openhab.binding.digitalstrom/src/main/resources/OH-INF/thing/AppartmentScene.xml, bundles/org.openhab.binding.digitalstrom/src/main/resources/OH-INF/thing/GroupScene.xml, bundles/org.openhab.binding.digitalstrom/src/main/resources/OH-INF/thing/NamedScene.xml, bundles/org.openhab.binding.digitalstrom/src/main/resources/OH-INF/thing/ZoneScene.xml, bundles/org.openhab.binding.digitalstrom/src/main/resources/OH-INF/thing/ZoneTemperatureControl.xml
=> [digitalstrom] Fix deprecated tag "required"

bundles/org.openhab.binding.wemo/src/main/resources/OH-INF/thing/bridge.xml, bundles/org.openhab.binding.wemo/src/main/resources/OH-INF/thing/thing-types.xml
=> [wemo] Fix deprecated tag "required"

bundles/org.openhab.binding.tellstick/src/main/resources/OH-INF/config/config.xml, bundles/org.openhab.binding.tellstick/src/main/resources/OH-INF/thing/devices.xml
=> [tellstick] Fix deprecated tag "required"

bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/coffeemachine.xml, bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/dishwasher.xml, bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/fridge.xml, bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/fridgefreezer.xml, bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/hob.xml, bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/hood.xml, bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/oven.xml, bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/tumbledryer.xml, bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/washingmachine.xml, bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/xgw3000.xml
=> [miele] Fix deprecated tag "required"

bundles/org.openhab.binding.dmx/src/main/resources/OH-INF/thing/artnet-bridge.xml, bundles/org.openhab.binding.dmx/src/main/resources/OH-INF/thing/chaser-thing.xml, bundles/org.openhab.binding.dmx/src/main/resources/OH-INF/thing/color-thing.xml, bundles/org.openhab.binding.dmx/src/main/resources/OH-INF/thing/dimmer-thing.xml, bundles/org.openhab.binding.dmx/src/main/resources/OH-INF/thing/lib485-bridge.xml, bundles/org.openhab.binding.dmx/src/main/resources/OH-INF/thing/sacn-bridge.xml, bundles/org.openhab.binding.dmx/src/main/resources/OH-INF/thing/tunablewhite-thing.xml
=> [dmx] Fix deprecated tag "required"

bundles/org.openhab.binding.plclogo/src/main/resources/OH-INF/config/analog.xml, bundles/org.openhab.binding.plclogo/src/main/resources/OH-INF/config/bridge.xml, bundles/org.openhab.binding.plclogo/src/main/resources/OH-INF/config/datetime.xml, bundles/org.openhab.binding.plclogo/src/main/resources/OH-INF/config/digital.xml, bundles/org.openhab.binding.plclogo/src/main/resources/OH-INF/config/memory.xml, bundles/org.openhab.binding.plclogo/src/main/resources/OH-INF/config/pulse.xml
=> [plclogo] Fix deprecated tag "required"

bundles/org.openhab.binding.bticinosmarther/src/main/resources/OH-INF/config/config.xml
=> [bticinosmarther] Fix deprecated tag "required"

bundles/org.openhab.binding.pulseaudio/src/main/resources/OH-INF/thing/bridge.xml, bundles/org.openhab.binding.pulseaudio/src/main/resources/OH-INF/thing/combined-sink.xml, bundles/org.openhab.binding.pulseaudio/src/main/resources/OH-INF/thing/sink-input.xml, bundles/org.openhab.binding.pulseaudio/src/main/resources/OH-INF/thing/sink.xml, bundles/org.openhab.binding.pulseaudio/src/main/resources/OH-INF/thing/source-output.xml, bundles/org.openhab.binding.pulseaudio/src/main/resources/OH-INF/thing/source.xml
=> [pulseaudio] Fix deprecated tag "required"

bundles/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/internal/live/TelldusLiveBridgeHandler.java, bundles/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/internal/local/TelldusLocalBridgeHandler.java
Fix for NPE.
Latest jar-file is present in the [community thread](https://community.openhab.org/t/tellstick-local-api/90204/6).
=> [tellstick] Fix for NPE (#10377)

bundles/org.openhab.binding.intesis/README.md
Signed-off-by: Hans-Jörg Merk github@hmerk.de
=> [intesis] Fix Typo in ReadMe

bundles/org.openhab.binding.openweathermap/README.md, bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/OpenWeatherMapBindingConstants.java, bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/config/OpenWeatherMapAirPollutionConfiguration.java, bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/connection/OpenWeatherMapConnection.java, bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/discovery/OpenWeatherMapDiscoveryService.java, bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/dto/OpenWeatherMapJsonAirPollutionData.java, bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/dto/airpollution/Components.java, bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/dto/airpollution/List.java, bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/dto/airpollution/Main.java, bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/dto/forecast/daily/List.java, bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/factory/OpenWeatherMapHandlerFactory.java, bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/handler/AbstractOpenWeatherMapHandler.java, bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/handler/OpenWeatherMapAPIHandler.java, bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/handler/OpenWeatherMapAirPollutionHandler.java, bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/handler/OpenWeatherMapWeatherAndForecastHandler.java, bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/config/config.xml, bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/i18n/openweathermap_de.properties, bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/thing/channel-types.xml, bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/thing/thing-types.xml
- Added support for Air Pollution API
- Added Channels `precip-probability`, `sunrise` and `sunset` to legacy daily forecast
=> [openweathermap] Added support for Air Pollution API

bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaActionGroupHandler.java, bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaBaseThingHandler.java, bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaGatewayHandler.java
This PR fixes bug causing Gateway and Actiongroups never get ONLINE introduced by #10300
might relate to #10346
=> [somfytahoma] Fixed bug causing Gateway and Actiongroup never get ONLINE

bundles/org.openhab.binding.allplay/src/main/resources/OH-INF/binding/binding.xml, bundles/org.openhab.binding.allplay/src/main/resources/OH-INF/thing/thing-types.xml, bundles/org.openhab.binding.atlona/src/main/resources/OH-INF/config/config.xml, bundles/org.openhab.binding.chromecast/src/main/resources/OH-INF/binding/binding.xml, bundles/org.openhab.binding.chromecast/src/main/resources/OH-INF/config/config.xml, bundles/org.openhab.binding.coolmasternet/src/main/resources/OH-INF/thing/thing-types.xml, bundles/org.openhab.binding.elerotransmitterstick/src/main/resources/OH-INF/thing/thing-types.xml, bundles/org.openhab.binding.hdanywhere/src/main/resources/OH-INF/thing/mhub4k431.xml, bundles/org.openhab.binding.hdanywhere/src/main/resources/OH-INF/thing/multiroomplus.xml, bundles/org.openhab.binding.heos/src/main/resources/OH-INF/thing/HeosGroup.xml, bundles/org.openhab.binding.heos/src/main/resources/OH-INF/thing/HeosPlayer.xml, bundles/org.openhab.binding.heos/src/main/resources/OH-INF/thing/HeosSystem.xml, bundles/org.openhab.binding.hyperion/src/main/resources/OH-INF/thing/thing-types.xml, bundles/org.openhab.binding.icalendar/src/main/resources/OH-INF/thing/thing-types.xml, bundles/org.openhab.binding.innogysmarthome/src/main/resources/OH-INF/config/config.xml, bundles/org.openhab.binding.innogysmarthome/src/main/resources/OH-INF/thing/bridge.xml, bundles/org.openhab.binding.kodi/src/main/resources/OH-INF/binding/binding.xml, bundles/org.openhab.binding.kvv/src/main/resources/OH-INF/thing/stop.xml
=> [bindings a-k] Fix deprecated tag "required"

bundles/org.openhab.binding.daikin/README.md, bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/DaikinBindingConstants.java, bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/DaikinWebTargets.java, bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/ControlInfo.java, bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/EnergyInfoDayAndWeek.java, bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/EnergyInfoYear.java, bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/InfoParser.java, bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/SensorInfo.java, bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/airbase/AirbaseZoneInfo.java, bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/discovery/DaikinACUnitDiscoveryService.java, bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/handler/DaikinAcUnitHandler.java, bundles/org.openhab.binding.daikin/src/main/resources/OH-INF/thing/thing-types.xml
Signed-off-by: Wouter Denayer <wouter@denayer.com>
=> [daikin] add energy usage day & week

bundles/org.openhab.binding.upnpcontrol/README.md
In the Thing Configuration section starting at Line 40, the code example had parameters transposed versus the preceding description and the true operation of the binding.  The correction puts the parameters included in the original example in the thing that they belong with in Lines 80 and 81.  The optional notification parameters of the renderer were not included originally and I have left it like that.
=> [upnpcontrol] Small correction to UpnpControl Binding README.md

bundles/org.openhab.binding.lcn/src/main/resources/OH-INF/config/config.xml
=> [lcn] Add dimmer profile parameter to be accessible via UI

bundles/org.openhab.binding.tacmi/README.md, bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/TACmiBindingConstants.java, bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/coe/TACmiHandler.java, bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/schema/ApiPageEntry.java, bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/schema/ApiPageParser.java, bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/schema/TACmiSchemaHandler.java, bundles/org.openhab.binding.tacmi/src/main/resources/OH-INF/config/config.xml, bundles/org.openhab.binding.tacmi/src/main/resources/OH-INF/thing/thing-types.xml
This PR provides some improvements for the tacmi plugin. There are several small commits fixing issues. The most noteworthy changes are:
Schema-page handler:
* Debounce unintended toggeling when status-polling overlaps with new commands.
* channels now have a 'updatePolicy' configuration parameter to specify the update behaviour (related to the toggling)
CoE-Handler:
* added SI-Units for known data types
The improvements have been made based on user expiriences and already have been tested.
Might also be related to #9873 but I'm waiting for feedback on this. Would be really great if the changes would make it into 3.1.0.
=> [tacmi] Fix unintended toggleing and add update policy

bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaBridgeHandler.java
=> [somfytahoma] Faster feedback for commands initiated by the binding

bundles/org.openhab.binding.oceanic/src/main/resources/OH-INF/thing/network.xml, bundles/org.openhab.binding.onewiregpio/src/main/resources/OH-INF/thing/thing-types.xml, bundles/org.openhab.binding.onkyo/src/main/resources/OH-INF/binding/binding.xml, bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/ZBAutomation.xml, bundles/org.openhab.binding.orvibo/src/main/resources/OH-INF/thing/thing-types.xml, bundles/org.openhab.binding.paradoxalarm/src/main/resources/OH-INF/thing/ip150connector.xml, bundles/org.openhab.binding.phc/src/main/resources/OH-INF/thing/thing-types.xml, bundles/org.openhab.binding.pilight/src/main/resources/OH-INF/thing/devices.xml, bundles/org.openhab.binding.rme/src/main/resources/OH-INF/thing/rme.xml
=> [bindings o-r] Fix deprecated tag "required"

bundles/org.openhab.binding.serial/src/main/resources/OH-INF/thing/thing-types.xml, bundles/org.openhab.binding.serialbutton/src/main/resources/OH-INF/thing/thing-types.xml, bundles/org.openhab.binding.sinope/src/main/resources/OH-INF/thing/thing-types.xml, bundles/org.openhab.binding.sleepiq/src/main/resources/OH-INF/thing/thing-types.xml, bundles/org.openhab.binding.smartmeter/src/main/resources/OH-INF/thing/thing-types.xml, bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/binding/binding.xml, bundles/org.openhab.binding.spotify/src/main/resources/OH-INF/thing/thing-types.xml, bundles/org.openhab.binding.squeezebox/src/main/resources/OH-INF/binding/binding.xml, bundles/org.openhab.binding.synopanalyzer/src/main/resources/OH-INF/thing/thing-types.xml, bundles/org.openhab.binding.valloxmv/src/main/resources/OH-INF/thing/thing-types.xml, bundles/org.openhab.binding.velbus/src/main/resources/OH-INF/config/config.xml, bundles/org.openhab.binding.volvooncall/src/main/resources/OH-INF/config/config.xml
=> [bindings s-z] Fix deprecated tag "required"

bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaBridgeHandler.java
=> [somfytahoma] Fix code analysis warnings

bundles/org.openhab.binding.remoteopenhab/src/main/java/org/openhab/binding/remoteopenhab/internal/rest/RemoteopenhabRestClient.java
=> [remoteopenhab] Avoid catching Exception

bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/connector/PowermaxSerialConnector.java
=> [powermax] Fix handling of InterruptedException (Thread.sleep)

bundles/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/api/FreeboxApiManager.java, bundles/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/handler/FreeboxHandler.java
=> [freebox] Fix handling of InterruptedException (Thread.sleep)

bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosXMLParser.java, bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/handler/ZonePlayerHandler.java
=> [sonos] Fix handling of InterruptedException (Thread.sleep)

bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/SonyProjectorConnector.java, bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/serial/SonyProjectorSerialConnector.java
=> [sonyprojector] Fix handling of InterruptedException (Thread.sleep)

bundles/org.openhab.binding.autelis/src/main/java/org/openhab/binding/autelis/internal/handler/AutelisHandler.java, bundles/org.openhab.binding.automower/src/main/java/org/openhab/binding/automower/internal/rest/api/automowerconnect/AutomowerConnectApi.java, bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/hardware/FritzAhaWebInterface.java, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/BoschSHCHandler.java, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/BoschSHCBridgeHandler.java, bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/LongPolling.java
=> [bindings a-c] Fix exception handling (Jetty HTTP client)

bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/DaikinWebTargets.java, bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/BasicInfo.java, bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/EnergyInfoDayAndWeek.java, bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/EnergyInfoYear.java, bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/airbase/AirbaseBasicInfo.java, bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/handler/DaikinAcUnitHandler.java, bundles/org.openhab.binding.darksky/src/main/java/org/openhab/binding/darksky/internal/config/DarkSkyChannelConfiguration.java, bundles/org.openhab.binding.darksky/src/main/java/org/openhab/binding/darksky/internal/connection/DarkSkyConnection.java, bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/connector/telnet/DenonMarantzTelnetClientThread.java, bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/connector/telnet/DenonMarantzTelnetConnector.java, bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/handler/DenonMarantzHandler.java, bundles/org.openhab.binding.dlinksmarthome/src/main/java/org/openhab/binding/dlinksmarthome/internal/DLinkHNAPCommunication.java, bundles/org.openhab.binding.dlinksmarthome/src/main/java/org/openhab/binding/dlinksmarthome/internal/motionsensor/DLinkMotionSensorCommunication.java, bundles/org.openhab.binding.ecobee/README.md, bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/api/EcobeeAuth.java, bundles/org.openhab.binding.enturno/src/main/java/org/openhab/binding/enturno/internal/connection/EnturNoConnection.java, bundles/org.openhab.binding.etherrain/src/main/java/org/openhab/binding/etherrain/internal/api/EtherRainCommunication.java, bundles/org.openhab.binding.evohome/src/main/java/org/openhab/binding/evohome/internal/api/ApiAccess.java, bundles/org.openhab.binding.evohome/src/main/java/org/openhab/binding/evohome/internal/api/EvohomeApiClient.java, bundles/org.openhab.binding.evohome/src/main/java/org/openhab/binding/evohome/internal/handler/EvohomeAccountBridgeHandler.java
=> [bindings d-e] Fix exception handling (Jetty HTTP client)

bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaActionGroupHandler.java, bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaBaseThingHandler.java
This PR fixes the non working action groups initialization and execution introduced by the latest PRs.
=> [somfytahoma] fixed action groups execution

bundles/org.openhab.binding.bluetooth.bluez/src/main/java/org/openhab/binding/bluetooth/bluez/internal/DeviceManagerFactory.java, bundles/org.openhab.binding.bluetooth.bluez/src/main/java/org/openhab/binding/bluetooth/bluez/internal/DeviceManagerWrapper.java
Fixes https://github.com/openhab/openhab-addons/issues/10136
=> [bluetooth] Graciously handle systems without DBus

bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/thing/sensor-thing-types.xml
- Prevent exception when formatting value
Fixes #10295 
=> [deconz] Prevent exception when formatting value

bundles/org.openhab.binding.zoneminder/README.md
I updated the README examples to match the binding source code.
=> [zoneminder] Fix binding action examples

bundles/org.openhab.binding.modbus.studer/README.md
As i spent hours to figure out the correct document to read about the address scheme, this might help others to avoid this and get this plugin to the same "copy and paste" use  as the others, even if the existing scheme already is enough to get it working.
=> [modbus.studer] Update README.md

bundles/org.openhab.binding.openweathermap/README.md, bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/OpenWeatherMapBindingConstants.java, bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/config/OpenWeatherMapOneCallConfiguration.java, bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/connection/OpenWeatherMapConnection.java, bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/dto/onecall/Alert.java, bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/dto/onecall/OpenWeatherMapOneCallAPIData.java, bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/handler/OpenWeatherMapOneCallHandler.java, bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/config/config.xml, bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/i18n/openweathermap.properties, bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/i18n/openweathermap_de.properties, bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/thing/channel-types.xml, bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/thing/thing-types.xml
- Added One Call API weather warnings
- Added German translations for One Call API
=> [openweathermap] Added One Call API weather warnings

bundles/org.openhab.binding.yioremote/src/main/java/org/openhab/binding/yioremote/internal/YIOremoteDockHandler.java, bundles/org.openhab.binding.yioremote/src/main/java/org/openhab/binding/yioremote/internal/utils/Websocket.java
Update and improve of the reconnection of the plugin
=> [yioremote]Update and improve of the reconnection of the plugin

bundles/org.openhab.persistence.dynamodb/pom.xml
No need to list transitive test dependencies, they are pulled in
automatically. Exception with sqlite4java shared libraries which are
needed for runtime.
With the update of DynamoDBLocal, tests require newer version of jetty
(9.4.18.v20190429), resolving #10502
=> [dynamodb] Update test dependency DynamoDBLocal

bundles/org.openhab.binding.nibeheatpump/contrib/NibeGW/Arduino/NibeGW/NibeGW.ino
**enhanced #9857** 
- added STM32-nucleo-F429ZI support to nibegw
**fixed #9846**
- added missing socket-start-function for udp (using Ethernet-Shield W5100 with arduino uno r3).
=> [nibeheatpump] Add STM32 support to nibegw AND ETH-W5100 not sending UDP-Packets 

bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcBaseDAO.java
- Use `TypeParser` to get matching Item State
Fixes #10494 
=> [jdbc] Use TypeParser to get matching Item State

bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/soap/CallListEntry.java
- Fixed wrong time parsing
- Replaced `SimpleDateFormat` by `DateTimeFormatter` for multi threading safety
Closes #10162 
=> [tr064] Fixed wrong time parsing

bundles/org.openhab.binding.nibeheatpump/contrib/NibeGW/Arduino/NibeGW/NibeGW.ino
- Fixed ProDiNo UDP issue with latest Arduino  libraries.
- Debug improvements
=> [nibeheatpump] Fixed ProDiNo UDP issue

bundles/org.openhab.binding.teleinfo/README.md, bundles/org.openhab.binding.teleinfo/src/main/resources/OH-INF/thing/common-cbemm-evo-icc-channel-types.xml, bundles/org.openhab.binding.teleinfo/src/main/resources/OH-INF/thing/common-cbetm-channel-types.xml
This PR adds the right dimension/unit to apparent power channels (PAPP).
=> [teleinfo] Add power dimension to apparent power channels

bundles/org.openhab.binding.bluetooth.daikinmadoka/src/test/java/org/openhab/binding/bluetooth/daikinmadoka/internal/MadokaMessageTest.java, bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/handler/DaikinBaseHandler.java, bundles/org.openhab.binding.fsinternetradio/src/main/java/org/openhab/binding/fsinternetradio/internal/FSInternetRadioDiscoveryParticipant.java, bundles/org.openhab.binding.hdanywhere/src/main/java/org/openhab/binding/hdanywhere/internal/handler/Mhub4K431Handler.java, bundles/org.openhab.binding.helios/src/main/java/org/openhab/binding/helios/internal/handler/HeliosHandler27.java, bundles/org.openhab.binding.innogysmarthome/src/main/java/org/openhab/binding/innogysmarthome/internal/manager/DeviceStructureManager.java, bundles/org.openhab.binding.irtrans/src/main/java/org/openhab/binding/irtrans/internal/handler/EthernetBridgeHandler.java, bundles/org.openhab.binding.keba/src/main/java/org/openhab/binding/keba/internal/handler/KeContactTransceiver.java, bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/MieleApplianceHandler.java, bundles/org.openhab.binding.modbus/src/test/java/org/openhab/binding/modbus/internal/AtomicStampedKeyValueTest.java, bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/handler/AbstractBrokerHandler.java, bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyComponents.java, bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/manager/ShellyManagerActionPage.java, bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/manager/ShellyManagerCache.java, bundles/org.openhab.binding.valloxmv/src/main/java/org/openhab/binding/valloxmv/internal/ValloxMVWebSocket.java, bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/rest/mocks/DummyItemRegistry.java, bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/rest/mocks/DummyMetadataRegistry.java, bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/rest/mocks/DummyRuleRegistry.java, itests/org.openhab.binding.modbus.tests/src/main/java/org/openhab/binding/modbus/tests/ModbusDataHandlerTest.java, itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/test/GenericWemoLightOSGiTestParent.java
Fixes 26 SAT UnusedLocalVariable findings
=> Remove unused local variables

bundles/org.openhab.binding.touchwand/src/main/java/org/openhab/binding/touchwand/internal/TouchWandDimmerHandler.java, bundles/org.openhab.binding.touchwand/src/main/java/org/openhab/binding/touchwand/internal/TouchWandShutterHandler.java, bundles/org.openhab.binding.touchwand/src/main/java/org/openhab/binding/touchwand/internal/TouchWandSwitchHandler.java, bundles/org.openhab.binding.touchwand/src/main/java/org/openhab/binding/touchwand/internal/TouchWandWallControllerHandler.java, bundles/org.openhab.binding.touchwand/src/main/java/org/openhab/binding/touchwand/internal/discovery/TouchWandControllerDiscoveryService.java, bundles/org.openhab.binding.touchwand/src/main/java/org/openhab/binding/touchwand/internal/discovery/TouchWandUnitDiscoveryService.java, bundles/org.openhab.binding.touchwand/src/main/java/org/openhab/binding/touchwand/internal/dto/TouchWandShutterSwitchUnitData.java, bundles/org.openhab.binding.touchwand/src/main/java/org/openhab/binding/touchwand/internal/dto/TouchWandUnitDataWallController.java, bundles/org.openhab.binding.touchwand/src/main/java/org/openhab/binding/touchwand/internal/dto/TouchWandUnitFromJson.java
Bugfix - better handle unit update when currStatus key is null solve exception when json does not include currStatus key 
improvement - support new string format in bridge discovery 
cleanups - move some logs to debug level from warning/info
=> [touchwand] - better handle unit update when currStatus key is null

CODEOWNERS, bom/openhab-addons/pom.xml, bundles/org.openhab.binding.dali/NOTICE, bundles/org.openhab.binding.dali/README.md, bundles/org.openhab.binding.dali/pom.xml, bundles/org.openhab.binding.dali/src/main/feature/feature.xml, bundles/org.openhab.binding.dali/src/main/java/org/openhab/binding/dali/internal/DaliBindingConstants.java, bundles/org.openhab.binding.dali/src/main/java/org/openhab/binding/dali/internal/DaliHandlerFactory.java, bundles/org.openhab.binding.dali/src/main/java/org/openhab/binding/dali/internal/handler/DaliDeviceHandler.java, bundles/org.openhab.binding.dali/src/main/java/org/openhab/binding/dali/internal/handler/DaliException.java, bundles/org.openhab.binding.dali/src/main/java/org/openhab/binding/dali/internal/handler/DaliRgbHandler.java, bundles/org.openhab.binding.dali/src/main/java/org/openhab/binding/dali/internal/handler/DaliserverBridgeHandler.java, bundles/org.openhab.binding.dali/src/main/java/org/openhab/binding/dali/internal/handler/DaliserverConfig.java, bundles/org.openhab.binding.dali/src/main/java/org/openhab/binding/dali/internal/protocol/DaliAddress.java, bundles/org.openhab.binding.dali/src/main/java/org/openhab/binding/dali/internal/protocol/DaliBackwardFrame.java, bundles/org.openhab.binding.dali/src/main/java/org/openhab/binding/dali/internal/protocol/DaliCommandBase.java, bundles/org.openhab.binding.dali/src/main/java/org/openhab/binding/dali/internal/protocol/DaliDAPCCommand.java, bundles/org.openhab.binding.dali/src/main/java/org/openhab/binding/dali/internal/protocol/DaliForwardFrame.java, bundles/org.openhab.binding.dali/src/main/java/org/openhab/binding/dali/internal/protocol/DaliFrame.java, bundles/org.openhab.binding.dali/src/main/java/org/openhab/binding/dali/internal/protocol/DaliGearCommandBase.java, bundles/org.openhab.binding.dali/src/main/java/org/openhab/binding/dali/internal/protocol/DaliResponse.java, bundles/org.openhab.binding.dali/src/main/java/org/openhab/binding/dali/internal/protocol/DaliStandardCommand.java, bundles/org.openhab.binding.dali/src/main/resources/OH-INF/binding/binding.xml, bundles/org.openhab.binding.dali/src/main/resources/OH-INF/config/config.xml, bundles/org.openhab.binding.dali/src/main/resources/OH-INF/thing/thing-types.xml, bundles/pom.xml
This PR includes initial support for controlling DALI lighting devices over a Tridonic/Lunatone [DALI USB](https://www.lunatone.com/en/product/dali-usb/) interface with an intermediary [daliserver](https://github.com/onitake/daliserver) that turns the USB HID interface of the adapter into a TCP server.
The binding can be used to control the dimming level of individual devices as well as device groups.
Furthermore, I've added an 'rgb' thing that consists of three individual DALI addresses representing r/g/b LED channels in order to be able to set the composite lighting color in OpenHAB.
This is my first time contributing to this project, so please let me know if somewhere I didn't follow the conventions and coding standards of the project.
There is a forum thread about DALI: …
=> [dali] Initial contribution

bundles/org.openhab.binding.valloxmv/src/main/java/org/openhab/binding/valloxmv/internal/ValloxMVWebSocket.java
I sincerely hope this fixes all the issues with commits and DCOs... I sincerely appologize for all the spam.
=> [valloxmv] Fix co2 channel, hopefully working this time.

bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/handler/OpenWebNetAutomationHandler.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/handler/OpenWebNetBridgeHandler.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/handler/OpenWebNetEnergyHandler.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/handler/OpenWebNetGenericHandler.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/handler/OpenWebNetLightingHandler.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/handler/OpenWebNetThingHandler.java, bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/i18n/openwebnet.properties, bundles/org.openhab.binding.openwebnet/src/test/java/org/openhab/binding/openwebnet/handler/OwnIdTest.java
This improvement adds a mechanism to refresh all devices after OH reboot or disconnect from gateway
Fixes #9703
=> [openwebnet] Added refresh of devices after reboot or disconnect

bundles/org.openhab.binding.dwdunwetter/src/main/resources/OH-INF/thing/thing-types.xml
- Prevent exception when formatting value
Requested in https://community.openhab.org/t/dwd-unwetter-binding-oh3-no-warnings/111489/16
=> [dwdunwetter] Prevent exception when formatting valuevalue

bundles/org.openhab.binding.nibeheatpump/src/main/java/org/openhab/binding/nibeheatpump/internal/connection/SerialConnector.java, bundles/org.openhab.binding.nibeheatpump/src/main/java/org/openhab/binding/nibeheatpump/internal/message/ModbusDataReadOutMessage.java, bundles/org.openhab.binding.nibeheatpump/src/main/java/org/openhab/binding/nibeheatpump/internal/message/ModbusReadRequestMessage.java, bundles/org.openhab.binding.nibeheatpump/src/main/java/org/openhab/binding/nibeheatpump/internal/message/ModbusReadResponseMessage.java, bundles/org.openhab.binding.nibeheatpump/src/main/java/org/openhab/binding/nibeheatpump/internal/message/ModbusWriteRequestMessage.java, bundles/org.openhab.binding.nibeheatpump/src/main/java/org/openhab/binding/nibeheatpump/internal/message/ModbusWriteResponseMessage.java, bundles/org.openhab.binding.nibeheatpump/src/main/java/org/openhab/binding/nibeheatpump/internal/message/NibeHeatPumpBaseMessage.java, bundles/org.openhab.binding.nibeheatpump/src/main/java/org/openhab/binding/nibeheatpump/internal/protocol/NibeHeatPumpProtocol.java, bundles/org.openhab.binding.nibeheatpump/src/main/java/org/openhab/binding/nibeheatpump/internal/protocol/NibeHeatPumpProtocolStates.java, bundles/org.openhab.binding.nibeheatpump/src/test/java/org/openhab/binding/nibeheatpump/internal/message/ModbusDataReadOutMessageTest.java, bundles/org.openhab.binding.nibeheatpump/src/test/java/org/openhab/binding/nibeheatpump/internal/message/ModbusReadResponseMessageTest.java
Fixed heavily escaped read response parsing. During investigations also made some generic improvements and removed Apache commons dependency.
=> [nibeheatpump] data parsing fix

bundles/org.openhab.binding.omnilink/README.md
=> [OmniLink] Update README.md

bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/discovery/OpenWeatherMapDiscoveryService.java, bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/i18n/openweathermap.properties, bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/i18n/openweathermap_de.properties, bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/i18n/openweathermap_fr.properties
- Added missing properties for translations
- Changed file encoding to UTF-8
=> [openweathermap] Added missing properties for translations, Changed file encoding to UTF-8

bundles/org.openhab.binding.harmonyhub/README.md
Propose adding a note on the fact that there is no way to detect buttons pressed on the remote.
I spent a few hours before realizing this fact.
=> [harmonyhub] Update README.md

README.md
=> Added Crowdin badge

itests/org.openhab.binding.nest.tests/itest.bndrun
Depends on https://github.com/openhab/openhab-core/pull/2316
=> Resolve runbundles for Aries JAX-RS Whiteboard upgrade

bundles/org.openhab.binding.luxtronikheatpump/src/main/java/org/openhab/binding/luxtronikheatpump/internal/enums/HeatpumpType.java
See #10558 Add Support for HeatpumpType 81 - "LW 8 "
=> [luxtronikheatpump] Add Support for HeatpumpType 81 - "LW 8 "

bundles/org.openhab.binding.miio/src/main/resources/database/dreame.vacuum.p2009-miot.json
fixed typo for starting sequence
added support for "find me" & "test sound" function
added clear names for faults
=> [miio] added functions for Vacuums P2009/2036/2157

bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosBindingConstants.java, bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/Roam.xml
=> [sonos] Add support for Sonos Roam

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoInfoApDTO.java, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoInfoDTO.java, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoAbstractHandler.java
addresses bug reported in #10590
=> [miio] handle invalid rssi response

bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/Move.xml, bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/One.xml, bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/OneSL.xml, bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/PLAY1.xml, bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/PLAY3.xml
=> [sonos] Suppress the channel publicaddress from models without any line input

bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudClient.java
This fixes a number of open issues due to the fact that we were only accepting a limited number of http method types.  The effect of this was some functionality like DELETE or HEAD requests would just not work when using the cloud service, which made our UI look broken in different ways,  also it polluted the user's log with a lot of messages.  
https://github.com/openhab/openhab-core/issues/2312
https://github.com/openhab/openhab-cloud/issues/328
=> [openhab-cloud] Accept all Jetty supported http method types

bundles/org.openhab.binding.ipcamera/pom.xml, bundles/org.openhab.binding.tellstick/pom.xml, bundles/org.openhab.binding.tellstick/src/main/feature/feature.xml, bundles/org.openhab.io.homekit/pom.xml, bundles/org.openhab.persistence.dynamodb/pom.xml, itests/org.openhab.binding.mqtt.homeassistant.tests/pom.xml, itests/org.openhab.binding.mqtt.homie.tests/pom.xml, pom.xml
Depends on https://github.com/openhab/openhab-core/pull/2327
=> Update Netty dependencies to 4.1.63.Final

bundles/org.openhab.binding.neohub/src/main/resources/OH-INF/thing/thing-types.xml
=> [neohub] Thermostats now support setpoint changes in steps of 0.5 Celsius

bundles/org.openhab.binding.velux/src/main/resources/OH-INF/i18n/velux.properties, bundles/org.openhab.binding.velux/src/main/resources/OH-INF/i18n/velux_de.properties, bundles/org.openhab.binding.velux/src/main/resources/OH-INF/i18n/velux_dk.properties, bundles/org.openhab.binding.velux/src/main/resources/OH-INF/i18n/velux_nl.properties
- Removed license header from properties files
=> [velux] Removed license header from properties files

crowdin.yml
- Only upload properties files from i18n folder to Crowdin
Add-ons should place files for translations in `OH-INF/i18n/`. This change should exclude properties files containing configuration or mappings used in bindings (e.g. [Helios Ventilation](https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.heliosventilation/src/main/resources/datapoints.properties) or [SagerCaster](https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.sagercaster/src/main/resources/sagerForecaster.properties)).
=> Only upload properties files from i18n folder to Crowdin

bundles/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/StatefulHandlerCallback.java, bundles/org.openhab.binding.bluetooth.bluegiga/src/main/java/org/openhab/binding/bluetooth/bluegiga/BlueGigaBluetoothDevice.java, bundles/org.openhab.binding.bluetooth.roaming/src/main/java/org/openhab/binding/bluetooth/roaming/internal/RoamingBluetoothDevice.java, bundles/org.openhab.binding.bosesoundtouch/src/main/java/org/openhab/binding/bosesoundtouch/internal/ContentItem.java, bundles/org.openhab.binding.fmiweather/src/main/java/org/openhab/binding/fmiweather/internal/AbstractWeatherHandler.java, bundles/org.openhab.binding.irtrans/src/main/java/org/openhab/binding/irtrans/internal/handler/EthernetBridgeHandler.java, bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/connection/AbstractStateMachine.java, bundles/org.openhab.binding.powermax/src/main/java/org/openhab/binding/powermax/internal/message/PowermaxCommManager.java, bundles/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/rio/StatefulHandlerCallback.java, bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/util/ShellyChannelCache.java, bundles/org.openhab.binding.smartthings/src/main/java/org/openhab/binding/smartthings/internal/discovery/SmartthingsDiscoveryService.java, bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/phonebook/PhonebookProfile.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/AbstractHomekitAccessoryImpl.java, bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitLockImpl.java
They are errors in SAT 0.12.0.
=> Fix or suppress SAT CompareObjectsWithEquals findings

bundles/org.openhab.binding.verisure/README.md, bundles/org.openhab.binding.verisure/src/main/java/org/openhab/binding/verisure/internal/VerisureBindingConstants.java, bundles/org.openhab.binding.verisure/src/main/java/org/openhab/binding/verisure/internal/VerisureSession.java, bundles/org.openhab.binding.verisure/src/main/java/org/openhab/binding/verisure/internal/dto/VerisureBaseThingDTO.java, bundles/org.openhab.binding.verisure/src/main/java/org/openhab/binding/verisure/internal/dto/VerisureBatteryStatusDTO.java, bundles/org.openhab.binding.verisure/src/main/java/org/openhab/binding/verisure/internal/dto/VerisureClimatesDTO.java, bundles/org.openhab.binding.verisure/src/main/java/org/openhab/binding/verisure/internal/dto/VerisureDoorWindowsDTO.java, bundles/org.openhab.binding.verisure/src/main/java/org/openhab/binding/verisure/internal/handler/VerisureClimateDeviceThingHandler.java, bundles/org.openhab.binding.verisure/src/main/java/org/openhab/binding/verisure/internal/handler/VerisureDoorWindowThingHandler.java, bundles/org.openhab.binding.verisure/src/main/resources/OH-INF/thing/thing-types.xml
[verisure] Add channel for low battery warning for supported thing types (#10406)
Fixes #10406.
=> [verisure] Add channel for low battery warning for supported thing types

bundles/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/internal/models/NeeoDeviceChannel.java, bundles/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/internal/servletservices/NeeoBrainService.java
- Fixed event nullness
Related to https://github.com/openhab/openhab-core/pull/2341
=> [neeo] Fixed event nullness

bom/openhab-addons/pom.xml, bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/DebuggingGraalScriptEngine.java, bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/OpenhabGraalJSScriptEngine.java, bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/ScriptExtensionModuleProvider.java, bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/fs/PrefixedSeekableByteChannel.java, bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/scriptengine/InvocationInterceptingScriptEngineWithInvocable.java, bundles/pom.xml
=> [jsscripting] Fix build and cleanup

bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/ApiVersion.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/Config.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/Group.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/HueBridge.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/State.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueBridgeHandler.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueGroupHandler.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueLightHandler.java, bundles/org.openhab.binding.hue/src/test/java/org/openhab/binding/hue/internal/handler/HueLightHandlerTest.java
- Fixed ColorTemperature is set to `UNDEF`
- Fixed SAT findings
- Fixed warnings because of missing `ThingHandlerCcallback` during unit tests
See https://community.openhab.org/t/hue-binding-color-temp-undef-and-slow-updates/121032
=> [hue] Fixed ColorTemperature set to UNDEF 

bundles/org.openhab.binding.somfytahoma/README.md, bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/SomfyTahomaBindingConstants.java, bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/config/SomfyTahomaConfig.java, bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaBridgeHandler.java, bundles/org.openhab.binding.somfytahoma/src/main/resources/OH-INF/binding/binding.xml, bundles/org.openhab.binding.somfytahoma/src/main/resources/OH-INF/config/config.xml, bundles/org.openhab.binding.somfytahoma/src/main/resources/OH-INF/thing/bridge.xml
=> [somfytahoma] Open to other portals

bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/callmonitor/CallMonitor.java
- Fixed wrong dial code in status info
Fixes #10658 
=> [avmfritz] Fixed wrong dial code in status info

bundles/org.openhab.binding.lcn/src/main/resources/OH-INF/thing/thing-types.xml
=> [lcn] shorten labels

bundles/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/handler/ModbusPollerThingHandler.java, bundles/org.openhab.binding.modbus/src/test/java/org/openhab/binding/modbus/internal/AtomicStampedKeyValueTest.java, bundles/org.openhab.binding.modbus/src/test/java/org/openhab/binding/modbus/internal/CascadedValueTransformationImplTest.java, bundles/org.openhab.binding.modbus/src/test/java/org/openhab/binding/modbus/internal/SingleValueTransformationTest.java, bundles/org.openhab.binding.modbus/src/test/java/org/openhab/binding/modbus/internal/profiles/ModbusGainOffsetProfileTest.java
See https://github.com/openhab/openhab-addons/pull/10583#discussion_r629814797
=> [modbus] Cleanup workaround leftovers and fix a few SAT findings

bundles/org.openhab.voice.pollytts/README.md
added *voice* to the settings path to make it work.
=> [voice-pollytts] Update README.md

bundles/org.openhab.binding.logreader/src/main/java/org/openhab/binding/logreader/internal/LogReaderHandlerFactory.java, bundles/org.openhab.binding.logreader/src/main/java/org/openhab/binding/logreader/internal/config/LogReaderConfiguration.java, bundles/org.openhab.binding.logreader/src/main/java/org/openhab/binding/logreader/internal/filereader/AbstractLogFileReader.java, bundles/org.openhab.binding.logreader/src/main/java/org/openhab/binding/logreader/internal/filereader/FileTailer.java, bundles/org.openhab.binding.logreader/src/main/java/org/openhab/binding/logreader/internal/filereader/api/FileReaderException.java, bundles/org.openhab.binding.logreader/src/main/java/org/openhab/binding/logreader/internal/filereader/api/FileReaderListener.java, bundles/org.openhab.binding.logreader/src/main/java/org/openhab/binding/logreader/internal/filereader/api/LogFileReader.java, bundles/org.openhab.binding.logreader/src/main/java/org/openhab/binding/logreader/internal/handler/LogHandler.java, bundles/org.openhab.binding.logreader/src/main/java/org/openhab/binding/logreader/internal/searchengine/SearchEngine.java, bundles/org.openhab.binding.logreader/src/main/resources/OH-INF/thing/reader.xml
=> [logreader] Fixed SAT findings

bundles/org.openhab.automation.groovyscripting/README.md, bundles/org.openhab.automation.groovyscripting/pom.xml
For all bugfixes and improvements, see:
http://groovy-lang.org/changelogs/changelog-3.0.8.html
=> [groovyscripting] Update Groovy to 3.0.8

bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/hardware/callbacks/FritzAhaUpdateCallback.java, bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/hardware/callbacks/FritzAhaUpdateTemplatesCallback.java, bundles/org.openhab.binding.avmfritz/src/test/java/org/openhab/binding/avmfritz/internal/dto/AVMFritzDeviceListModelTest.java, bundles/org.openhab.binding.avmfritz/src/test/java/org/openhab/binding/avmfritz/internal/dto/AVMFritzTemplateListModelTest.java, itests/org.openhab.binding.avmfritz.tests/src/main/java/org/openhab/binding/avmfritz/internal/discovery/AVMFritzDiscoveryServiceOSGiTest.java, itests/org.openhab.binding.avmfritz.tests/src/main/java/org/openhab/binding/avmfritz/internal/handler/AVMFritzThingHandlerOSGiTest.java
- Added less reporting handling for `UnmarshalException`
- Changed unit / integration test to use the same unmarshal logic like the original code
=> [avmfritz] Added less reporting handling for UnmarshalException

bundles/org.openhab.binding.qbus/README.md
Corrected some mistkes in the readme
=> [Qbus] Update README.md

itests/org.openhab.binding.feed.tests/itest.bndrun, itests/org.openhab.binding.hue.tests/itest.bndrun, itests/org.openhab.binding.max.tests/itest.bndrun, itests/org.openhab.binding.modbus.tests/itest.bndrun, itests/org.openhab.binding.nest.tests/itest.bndrun, itests/org.openhab.binding.ntp.tests/itest.bndrun, itests/org.openhab.binding.systeminfo.tests/itest.bndrun, itests/org.openhab.binding.tradfri.tests/itest.bndrun, itests/org.openhab.binding.wemo.tests/itest.bndrun
Depends on https://github.com/openhab/openhab-core/pull/2369
=> Resolve itest runbundles for XStream upgrade

bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/client/HomeConnectApiClient.java, bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/HomeConnectHoodHandler.java
=> [homeconnect] Returns an empty list of options for an unsupported program

bundles/org.openhab.binding.comfoair/README.md, bundles/org.openhab.binding.comfoair/src/main/java/org/openhab/binding/comfoair/internal/ComfoAirBindingConstants.java, bundles/org.openhab.binding.comfoair/src/main/java/org/openhab/binding/comfoair/internal/ComfoAirHandler.java, bundles/org.openhab.binding.comfoair/src/main/java/org/openhab/binding/comfoair/internal/ComfoAirHandlerFactory.java, bundles/org.openhab.binding.comfoair/src/main/java/org/openhab/binding/comfoair/internal/ComfoAirSerialConnector.java, bundles/org.openhab.binding.comfoair/src/main/java/org/openhab/binding/comfoair/internal/datatypes/DataTypeMessage.java, bundles/org.openhab.binding.comfoair/src/main/resources/OH-INF/config/config.xml, bundles/org.openhab.binding.comfoair/src/main/resources/OH-INF/thing/thing-types.xml
This fixes the data handling for devices with restricted datapoints compared to the generic type.
Addtionally a new thing type for the StorkAir WHR930 was added to limit the available channels to the datapoints potentially available from this device.
See also: https://community.openhab.org/t/comfoair-change-fan-speed-on-whr930/118621
=> [comfoair] fix data handling for restricted devices

bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/AbstractHomeConnectThingHandler.java, bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/HomeConnectCoffeeMakerHandler.java, bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/HomeConnectCooktopHandler.java, bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/HomeConnectDishwasherHandler.java, bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/HomeConnectHoodHandler.java, bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/HomeConnectOvenHandler.java
=> [homeconnect] Factorize handling of power command

bundles/org.openhab.binding.lcn/README.md, bundles/org.openhab.binding.lcn/src/main/resources/OH-INF/config/config.xml
=> [lcn] Improve readme; Allow special module IDs <5

bundles/org.openhab.binding.fmiweather/src/main/java/org/openhab/binding/fmiweather/internal/client/Client.java, bundles/org.openhab.binding.fmiweather/src/test/java/org/openhab/binding/fmiweather/AbstractFMIResponseParsingTest.java, bundles/org.openhab.binding.fmiweather/src/test/java/org/openhab/binding/fmiweather/FMIResponseParsingExceptionReportTest.java, bundles/org.openhab.binding.fmiweather/src/test/java/org/openhab/binding/fmiweather/FMIResponseParsingMultiplePlacesTest.java, bundles/org.openhab.binding.fmiweather/src/test/java/org/openhab/binding/fmiweather/ParsingStationsTest.java, bundles/org.openhab.binding.fmiweather/src/test/resources/org/openhab/binding/fmiweather/error1.xml, bundles/org.openhab.binding.fmiweather/src/test/resources/org/openhab/binding/fmiweather/forecast_multiple_places.xml, bundles/org.openhab.binding.fmiweather/src/test/resources/org/openhab/binding/fmiweather/observations_empty.xml, bundles/org.openhab.binding.fmiweather/src/test/resources/org/openhab/binding/fmiweather/observations_multiple_places.xml, bundles/org.openhab.binding.fmiweather/src/test/resources/org/openhab/binding/fmiweather/observations_single_place.xml, bundles/org.openhab.binding.fmiweather/src/test/resources/org/openhab/binding/fmiweather/stations.xml
Updated code to work with FMI Weather API changes
XML namespace `target` namespace changed from
`http://xml.fmi.fi/namespace/om/atmosphericfeatures/1.0` to `http://xml.fmi.fi/namespace/om/atmosphericfeatures/1.1`
=> [fmiweather] Fixed to work with new API

bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/client/HomeConnectApiClient.java, bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/AbstractHomeConnectThingHandler.java
Cache the list of programs for an appliance
Fix #10771
=> [homeconnect] Retrieve list of programs when an appliance becomes available

itests/org.openhab.binding.tradfri.tests/itest.bndrun
Related to https://github.com/openhab/openhab-core/pull/2391
=> updated JmDNS dependency version

itests/org.openhab.binding.avmfritz.tests/itest.bndrun, itests/org.openhab.binding.hue.tests/itest.bndrun, itests/org.openhab.binding.wemo.tests/itest.bndrun
Related to https://github.com/openhab/openhab-core/pull/2396
=> upgrade to JUPnP 2.6.0

bundles/org.openhab.binding.smhi/README.md
Should preferably also be backported to the stable docs
=> [smhi][documentation] Add channel IDs to documentation

bundles/org.openhab.binding.etherrain/README.md
[etherrain] Fix typo
Fix typo in etherrain docs
=> [etherrain] Fix typo in docs

bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/kostalinverter/internal/thirdgeneration/ThirdGenerationBindingConstants.java, bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/kostalinverter/internal/thirdgeneration/ThirdGenerationChannelDatatypes.java, bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/kostalinverter/internal/thirdgeneration/ThirdGenerationHandler.java, bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/kostalinverter/internal/thirdgeneration/ThirdGenerationMappingInverterToChannel.java, bundles/org.openhab.binding.kostalinverter/src/main/resources/OH-INF/thing/Channels.xml, bundles/org.openhab.binding.kostalinverter/src/main/resources/OH-INF/thing/PLENTICOREPLUS100WITHBATTERY.xml, bundles/org.openhab.binding.kostalinverter/src/main/resources/OH-INF/thing/PLENTICOREPLUS100WITHOUTBATTERY.xml, bundles/org.openhab.binding.kostalinverter/src/main/resources/OH-INF/thing/PLENTICOREPLUS42WITHBATTERY.xml, bundles/org.openhab.binding.kostalinverter/src/main/resources/OH-INF/thing/PLENTICOREPLUS42WITHOUTBATTERY.xml, bundles/org.openhab.binding.kostalinverter/src/main/resources/OH-INF/thing/PLENTICOREPLUS55WITHBATTERY.xml, bundles/org.openhab.binding.kostalinverter/src/main/resources/OH-INF/thing/PLENTICOREPLUS55WITHOUTBATTERY.xml, bundles/org.openhab.binding.kostalinverter/src/main/resources/OH-INF/thing/PLENTICOREPLUS70WITHBATTERY.xml, bundles/org.openhab.binding.kostalinverter/src/main/resources/OH-INF/thing/PLENTICOREPLUS70WITHOUTBATTERY.xml, bundles/org.openhab.binding.kostalinverter/src/main/resources/OH-INF/thing/PLENTICOREPLUS85WITHBATTERY.xml, bundles/org.openhab.binding.kostalinverter/src/main/resources/OH-INF/thing/PLENTICOREPLUS85WITHOUTBATTERY.xml
This pull request adds the new channels (AC) frequency and cosphi to third generation inverters.
Tested with my Kostal Plenticore plus 10 with battery.
=> [kostalinverter] Added new channels frequency and cosphi

bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/client/HomeConnectApiClient.java, bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/AbstractHomeConnectThingHandler.java, bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/HomeConnectDryerHandler.java, bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/HomeConnectWasherDryerHandler.java, bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/HomeConnectWasherHandler.java
=> [homeconnect] Delay update of state options when not accessible

bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/AbstractHomeConnectThingHandler.java, bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/HomeConnectDryerHandler.java, bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/HomeConnectOvenHandler.java, bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/HomeConnectWasherDryerHandler.java, bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/HomeConnectWasherHandler.java
Related to dryer, washer and washer/dryer appliances
=> [homeconnect] Add missing channel update handler configuration

bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/AbstractHomeConnectThingHandler.java
=> [homeconnect] Undo PR 10754

bundles/org.openhab.binding.venstarthermostat/src/main/java/org/openhab/binding/venstarthermostat/internal/VenstarThermostatBindingConstants.java, bundles/org.openhab.binding.venstarthermostat/src/main/java/org/openhab/binding/venstarthermostat/internal/VenstarThermostatConfiguration.java, bundles/org.openhab.binding.venstarthermostat/src/main/java/org/openhab/binding/venstarthermostat/internal/VenstarThermostatHandlerFactory.java, bundles/org.openhab.binding.venstarthermostat/src/main/java/org/openhab/binding/venstarthermostat/internal/discovery/VenstarThermostatDiscoveryService.java, bundles/org.openhab.binding.venstarthermostat/src/main/java/org/openhab/binding/venstarthermostat/internal/dto/VenstarAwayMode.java, bundles/org.openhab.binding.venstarthermostat/src/main/java/org/openhab/binding/venstarthermostat/internal/dto/VenstarAwayModeSerializer.java, bundles/org.openhab.binding.venstarthermostat/src/main/java/org/openhab/binding/venstarthermostat/internal/dto/VenstarInfoData.java, bundles/org.openhab.binding.venstarthermostat/src/main/java/org/openhab/binding/venstarthermostat/internal/dto/VenstarResponse.java, bundles/org.openhab.binding.venstarthermostat/src/main/java/org/openhab/binding/venstarthermostat/internal/dto/VenstarSensor.java, bundles/org.openhab.binding.venstarthermostat/src/main/java/org/openhab/binding/venstarthermostat/internal/dto/VenstarSensorData.java, bundles/org.openhab.binding.venstarthermostat/src/main/java/org/openhab/binding/venstarthermostat/internal/dto/VenstarSystemMode.java, bundles/org.openhab.binding.venstarthermostat/src/main/java/org/openhab/binding/venstarthermostat/internal/dto/VenstarSystemModeSerializer.java, bundles/org.openhab.binding.venstarthermostat/src/main/java/org/openhab/binding/venstarthermostat/internal/dto/VenstarSystemState.java, bundles/org.openhab.binding.venstarthermostat/src/main/java/org/openhab/binding/venstarthermostat/internal/dto/VenstarSystemStateSerializer.java, bundles/org.openhab.binding.venstarthermostat/src/main/java/org/openhab/binding/venstarthermostat/internal/handler/VenstarThermostatHandler.java, bundles/org.openhab.binding.venstarthermostat/src/main/java/org/openhab/binding/venstarthermostat/internal/model/VenstarSensor.java
Converting everything to a int made it difficult for Celsius users and dealing with half step values.   The code had been using double, float and int types for temperatures, this standardizes on just using doubles.   Tested with both F and C configured thermostats. 
=> [venstarthermostat] Use doubles over Int or float types when processing temperatures, fix Checkstyle Warnings

bundles/org.openhab.binding.mielecloud/src/main/resources/OH-INF/i18n/mielecloud.properties, bundles/org.openhab.binding.mielecloud/src/main/resources/org/openhab/binding/mielecloud/internal/config/pairing.html
Fixes a typo and localization resolution problems reported in the community. See #10820 for details.
=> [mielecloud] Fix typo and localization key resolution

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoInfoApDTO.java
=> [miio] avoid NPE when rssi is missing

bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/RFXComBindingConstants.java, bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/connector/RFXComSerialConnector.java, bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/connector/RFXComStreamReader.java
There's no reason not to read multiple bytes at a time (that I could find) so
for best practice, set the read limit to be the maximum size of an rfxcom
message. Tested fine on my system.
=> [rfxcom] Read multiple bytes at a time over serial connection

bundles/org.openhab.binding.airquality/README.md
=> [air quality] fixed typo in samples

bundles/org.openhab.binding.semsportal/README.md, bundles/org.openhab.binding.semsportal/src/main/java/org/openhab/binding/semsportal/internal/PortalHandler.java, bundles/org.openhab.binding.semsportal/src/main/java/org/openhab/binding/semsportal/internal/SEMSPortalConfiguration.java, bundles/org.openhab.binding.semsportal/src/main/java/org/openhab/binding/semsportal/internal/StationHandler.java
- Allow configuration by thing file
- Add example of thing file configuration
- Fix parameter naming
=> [semsportal] Allow confiuration with thing file

bundles/org.openhab.binding.rfxcom/RESPONSES.md, bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/handler/RFXComBridgeHandler.java, bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComInterfaceControlMessage.java, bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComInterfaceMessage.java, bundles/org.openhab.binding.rfxcom/src/test/java/org/openhab/binding/rfxcom/internal/messages/RFXComInterfaceMessageTest.java
Based on both the SDK and experimentation, this commit correctly identifies the
firmware and hardware version. A warning has been added for people with really
old firmware that may be different, but we didn't handle those different cases
well anyway.
Also includes updated firmware types and device types and support for pretty-
printing of the device and firmware type.
=> [rfxcom] Update interface message support

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoQuantiyTypes.java, bundles/org.openhab.binding.miio/src/main/resources/database/cgllc.airmonitor.b1.json, bundles/org.openhab.binding.miio/src/main/resources/database/cgllc.airmonitor.s1.json, bundles/org.openhab.binding.miio/src/main/resources/database/chuangmi.plug.m1.json, bundles/org.openhab.binding.miio/src/main/resources/database/chuangmi.plug.v1.json, bundles/org.openhab.binding.miio/src/main/resources/database/chuangmi.plug.v3.json, bundles/org.openhab.binding.miio/src/main/resources/database/nwt.derh.wdh318efw1.json, bundles/org.openhab.binding.miio/src/main/resources/database/viomi.waterheater.e1.json, bundles/org.openhab.binding.miio/src/main/resources/database/xjx.toilet.json, bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.bhf1.json, bundles/org.openhab.binding.miio/src/main/resources/database/yunmi.waterpurifier.json, bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.airpurifier.m1.json, bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.airpurifier.v6.json, bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.airpurifier.v7.json, bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.airpurifier.vb2-miot.json, bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.fan.v3.json, bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.heater.za1.json, bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.heater.za2-miot.json, bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.heater.zb1-miot.json, bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.humidifier.ca4.json, bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.humidifier.cb1.json, bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.humidifier.v1.json, bundles/org.openhab.binding.miio/src/main/resources/database/zimi.powerstrip.v2.json
=> [miio] fix typo in temperatue unit

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoHandlerFactory.java, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/MiIoBasicChannel.java, bundles/org.openhab.binding.miio/src/test/java/org/openhab/binding/miio/internal/MiIoQuantityTypesTest.java, bundles/org.openhab.binding.miio/src/test/java/org/openhab/binding/miio/internal/RoboMapViewer.java
=> [miio] cleanup several SAT warnings

bundles/org.openhab.binding.rfxcom/README.md, bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComBlinds1Message.java, bundles/org.openhab.binding.rfxcom/src/main/resources/OH-INF/thing/blinds1.xml
Based on the RFXtrx SDK, new blind types. They mostly seem to match existing logic,
so this shouldn't break existing things.
=> [rfxcom] Add support for additional blinds

bundles/org.openhab.binding.icloud/README.md
It took me a while to find the locationAccuracy Channel.  Eventually I figured out that it was an Advanced Option on the User Interface.  I thought showing that in the document might make it easier for others in the future.
=> [iCloud] Update README.md to note that locationAccuracy is an Advanced Option on the UI

bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/TemperatureFormat.java, bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/AudioSourceHandler.java, bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/AudioZoneHandler.java, bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/LockHandler.java
=> [OmniLink] Simplify updating properties

bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/lib/listener/ConnectionListener.java
=> Added missing </li> attributes in last comment section

bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/influx2/InfluxDB2RepositoryImpl.java
Was missing in https://github.com/openhab/openhab-addons/pull/10680
Fixes #10887
=> [influxdb] v2: Fix history queries if items are not tagged

bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/AVMFritzDynamicCommandDescriptionProvider.java
- Added service references to `DynamicCommandDescriptionProvider` to support publishing `ChannelDescriptionChangedEvent`s
Depends on https://github.com/openhab/openhab-core/pull/1505
=> [avmfritz] Added support for publishing ChannelDescriptionChangedEvents

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/MiIoBasicChannel.java, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoBasicHandler.java
=> [miio] fix typo

bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/type/HomeConnectDynamicStateDescriptionProvider.java, bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/LGWebOSStateDescriptionOptionProvider.java, bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/NATherm1StateDescriptionProvider.java, bundles/org.openhab.binding.remoteopenhab/src/main/java/org/openhab/binding/remoteopenhab/internal/RemoteopenhabStateDescriptionOptionProvider.java, bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/RotelStateDescriptionOptionProvider.java, bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/SomfyTahomaStateDescriptionOptionProvider.java, bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosStateDescriptionOptionProvider.java, bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/SonyProjectorStateDescriptionOptionProvider.java
For the bindings homeconnect, lgwebos, netatmo, remoteopenhab, rotel,
somfytahoma, sonos and sonyprojector
Depends on openhab/openhab-core#1505
=> Added support for publishing ChannelDescriptionChangedEvents

bundles/org.openhab.binding.enocean/README.md, bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/A5_3F/A5_3F_7F_EltakoFRM.java, bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/EEPType.java, bundles/org.openhab.binding.enocean/src/main/resources/OH-INF/thing/Rollershutter.xml
#10816 
* implementation of new `A5_3F_7F_EltakoFRM` is based on `A5_3F_7F_EltakoFSB`
* updated Readme.md
* updated dropdown in UI
Signed-off-by: hofingerandi <andreas.hofinger@gmx.net>
=> [enocean] Add support for eltako rollershutter frm60

bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/HueThingHandlerFactory.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueBridgeHandler.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueGroupHandler.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueLightHandler.java, bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueStateDescriptionProvider.java, bundles/org.openhab.binding.hue/src/test/java/org/openhab/binding/hue/internal/handler/HueLightHandlerTest.java
- Added service references to `DynamicStateDescriptionProvider` to support publishing `ChannelDescriptionChangedEvent`s
Depends on https://github.com/openhab/openhab-core/pull/1505 and https://github.com/openhab/openhab-core/pull/2410
=> [hue] Added support for publishing ChannelDescriptionChangedEvents

bundles/create_openhab_binding_skeleton.cmd, bundles/create_openhab_binding_skeleton.sh
This will make it easier to add even more add-ons!
=> Update OH version in skeleton scripts

bundles/org.openhab.binding.telegram/README.md
Add design of token for better understanding
=> [telegram] Update README.md

bundles/org.openhab.binding.insteon/README.md
Fix repeated word. Signed-off-by: Ryan Johnston <github@shopandlearn.net>
=> [insteon] Update README.md remove doubled can't

bundles/org.openhab.binding.homematic/src/test/java/org/openhab/binding/homematic/internal/communicator/virtual/ButtonDatapointTest.java, bundles/org.openhab.binding.irobot/src/test/java/org/openhab/binding/irobot/internal/handler/RoombaHandlerTest.java
=> Disable unstable tests

bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/client/HomeConnectApiClient.java, bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/AbstractHomeConnectThingHandler.java, bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/HomeConnectHoodHandler.java
=> [homeconnect] Catch exception when appropriate

bundles/org.openhab.binding.volvooncall/README.md
=> [volvooncall] Clean up readme.

bundles/org.openhab.binding.lgwebos/src/main/resources/OH-INF/thing/thing-types.xml
=> [lgwebos] Switch to default system channel types

bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/discovery/ZonePlayerDiscoveryParticipant.java
=> [sonos] Filter Sonos Sub from discovery

bundles/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/GardenaSmartImpl.java
=> [gardena] Fixed OutOfMemory error if initializing fails

bundles/org.openhab.binding.vigicrues/src/main/java/org/openhab/binding/vigicrues/internal/VigiCruesBindingConstants.java, bundles/org.openhab.binding.vigicrues/src/main/java/org/openhab/binding/vigicrues/internal/api/ApiHandler.java, bundles/org.openhab.binding.vigicrues/src/main/java/org/openhab/binding/vigicrues/internal/api/VigiCruesException.java, bundles/org.openhab.binding.vigicrues/src/main/java/org/openhab/binding/vigicrues/internal/dto/opendatasoft/VigiCruesFields.java, bundles/org.openhab.binding.vigicrues/src/main/java/org/openhab/binding/vigicrues/internal/dto/vigicrues/CdStationHydro.java, bundles/org.openhab.binding.vigicrues/src/main/java/org/openhab/binding/vigicrues/internal/handler/VigiCruesHandler.java, bundles/org.openhab.binding.vigicrues/src/main/resources/OH-INF/binding/binding.xml, bundles/org.openhab.binding.vigicrues/src/main/resources/OH-INF/i18n/vigicrues_fr.properties, bundles/org.openhab.binding.vigicrues/src/main/resources/OH-INF/thing/thing-types.xml
=> [VigiCrues] Adding localization and a bit of code cleansing.

bundles/org.openhab.binding.meteoalerte/src/main/java/org/openhab/binding/meteoalerte/internal/MeteoAlerteBindingConstants.java, bundles/org.openhab.binding.meteoalerte/src/main/java/org/openhab/binding/meteoalerte/internal/handler/MeteoAlerteHandler.java, bundles/org.openhab.binding.meteoalerte/src/main/java/org/openhab/binding/meteoalerte/internal/json/ResponseFieldDTO.java
=> [MeteoAlerte] Small code enhancements

bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/OpenWebNetBindingConstants.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/OpenWebNetHandlerFactory.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/discovery/BusGatewayUpnpDiscovery.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/discovery/OpenWebNetDeviceDiscoveryService.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/discovery/UsbGatewayDiscoveryService.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetAutomationHandler.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetBridgeHandler.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetEnergyHandler.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetGenericHandler.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetLightingHandler.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetThermoregulationHandler.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetThingHandler.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/config/OpenWebNetBusBridgeConfig.java, bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/config/OpenWebNetZigBeeBridgeConfig.java, bundles/org.openhab.binding.openwebnet/src/test/java/org/openhab/binding/openwebnet/internal/handler/OwnIdTest.java
This PR does not include any change to the code, it only refactors classes to be under the `internal `package, as requested in a previous review.
Signed-off-by: Massimo Valla <mvcode00@gmail.com>
=> [openwebnet] refactoring to internal package

bundles/org.openhab.binding.mcp23017/src/main/resources/OH-INF/config/config.xml, bundles/org.openhab.binding.mcp23017/src/main/resources/OH-INF/thing/channels.xml
=> [mcp23017] Standardize config URI

bundles/org.openhab.binding.nikobus/src/main/resources/OH-INF/config/config.xml, bundles/org.openhab.binding.nikobus/src/main/resources/OH-INF/thing/dimmer-module.xml, bundles/org.openhab.binding.nikobus/src/main/resources/OH-INF/thing/push-button.xml, bundles/org.openhab.binding.nikobus/src/main/resources/OH-INF/thing/rollershutter-module.xml, bundles/org.openhab.binding.nikobus/src/main/resources/OH-INF/thing/switch-module.xml
=> [nikobus] Standardize config URI

bundles/org.openhab.binding.upb/src/main/resources/OH-INF/config/config.xml, bundles/org.openhab.binding.upb/src/main/resources/OH-INF/thing/leviton/38A00-1.xml, bundles/org.openhab.binding.upb/src/main/resources/OH-INF/thing/thing-types.xml, bundles/org.openhab.binding.upb/src/main/resources/OH-INF/thing/virtual.xml
=> [upb] Standardize config URI

bundles/org.openhab.binding.yeelight/src/main/resources/OH-INF/config/config.xml, bundles/org.openhab.binding.yeelight/src/main/resources/OH-INF/thing/ceiling.xml, bundles/org.openhab.binding.yeelight/src/main/resources/OH-INF/thing/ceiling1.xml, bundles/org.openhab.binding.yeelight/src/main/resources/OH-INF/thing/ceiling4.xml, bundles/org.openhab.binding.yeelight/src/main/resources/OH-INF/thing/ct_bulb.xml, bundles/org.openhab.binding.yeelight/src/main/resources/OH-INF/thing/desklamp.xml, bundles/org.openhab.binding.yeelight/src/main/resources/OH-INF/thing/dolphin.xml, bundles/org.openhab.binding.yeelight/src/main/resources/OH-INF/thing/stripe.xml, bundles/org.openhab.binding.yeelight/src/main/resources/OH-INF/thing/wonder.xml
=> [yeelight] Standardize config URI

bundles/org.openhab.binding.robonect/src/main/resources/OH-INF/config/config.xml, bundles/org.openhab.binding.robonect/src/main/resources/OH-INF/thing/thing-types.xml
=> [robonect] Standardize config URI

bundles/org.openhab.binding.systeminfo/src/main/resources/OH-INF/config/channelConfig.xml, bundles/org.openhab.binding.systeminfo/src/main/resources/OH-INF/thing/channels.xml
=> [systeminfo] Standardize config URI

bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/DigitalSTROMBindingConstants.java, bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/providers/DsDeviceThingTypeProvider.java, bundles/org.openhab.binding.digitalstrom/src/main/resources/OH-INF/config/bridgeConfig.xml, bundles/org.openhab.binding.digitalstrom/src/main/resources/OH-INF/config/deviceConfig.xml, bundles/org.openhab.binding.digitalstrom/src/main/resources/OH-INF/thing/dssBridge.xml
=> [digitalstrom] Standardize config URI

bundles/org.openhab.binding.zway/src/main/resources/OH-INF/config/bridge-config.xml, bundles/org.openhab.binding.zway/src/main/resources/OH-INF/thing/bridge.xml
=> [zway] Standardize config URI

bundles/org.openhab.binding.teleinfo/src/main/resources/OH-INF/config/config-description.xml, bundles/org.openhab.binding.teleinfo/src/main/resources/OH-INF/thing/cbemmBaseOptionElectricityMeter.xml, bundles/org.openhab.binding.teleinfo/src/main/resources/OH-INF/thing/cbemmEjpElectricityMeter.xml, bundles/org.openhab.binding.teleinfo/src/main/resources/OH-INF/thing/cbemmEvolutionIccBaseOptionElectricityMeter.xml, bundles/org.openhab.binding.teleinfo/src/main/resources/OH-INF/thing/cbemmEvolutionIccEjpElectricityMeter.xml, bundles/org.openhab.binding.teleinfo/src/main/resources/OH-INF/thing/cbemmEvolutionIccHcElectricityMeter.xml, bundles/org.openhab.binding.teleinfo/src/main/resources/OH-INF/thing/cbemmEvolutionIccTempoElectricityMeter.xml, bundles/org.openhab.binding.teleinfo/src/main/resources/OH-INF/thing/cbemmHcElectricityMeter.xml, bundles/org.openhab.binding.teleinfo/src/main/resources/OH-INF/thing/cbemmTempoElectricityMeter.xml, bundles/org.openhab.binding.teleinfo/src/main/resources/OH-INF/thing/cbetmBaseOptionElectricityMeter.xml, bundles/org.openhab.binding.teleinfo/src/main/resources/OH-INF/thing/cbetmEjpOptionElectricityMeter.xml, bundles/org.openhab.binding.teleinfo/src/main/resources/OH-INF/thing/cbetmHcOptionElectricityMeter.xml, bundles/org.openhab.binding.teleinfo/src/main/resources/OH-INF/thing/cbetmTempoOptionElectricityMeter.xml
=> [teleinfo] Standardize config URI

bundles/org.openhab.binding.ecotouch/src/main/java/org/openhab/binding/ecotouch/internal/EcoTouchHandler.java
=> [ecotouch] Fix decimal values being truncated

bundles/org.openhab.binding.miio/README.base.md, bundles/org.openhab.binding.miio/README.md, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/ActionConditions.java, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoAbstractHandler.java, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoVacuumHandler.java, bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.light.color1.json
Minor improvements 
* readme
* deviceId update message
* yeelight flowing start command
* Fix 2 minor SAT issues
=> [miio] Minor improvement documentation & deviceId update message

bundles/org.openhab.binding.fsinternetradio/README.md
Add binding for Hama IR100, Hama DIR3100 and Auna Connect CD
=> [fsinternetradio] Add further supported devices

bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/channels.xml
=> [sonos] Fix error in channels.xml file

bundles/org.openhab.binding.bluetooth.airthings/src/main/java/org/openhab/binding/bluetooth/airthings/internal/AirthingsWaveGen1Handler.java, bundles/org.openhab.binding.bluetooth.airthings/src/main/resources/OH-INF/thing/airthings.xml
Related to https://github.com/openhab/openhab-addons/pull/11052
=> [airthings] Fix spotless errors

bundles/org.openhab.binding.orbitbhyve/src/main/java/org/openhab/binding/orbitbhyve/internal/OrbitBhyveHandlerFactory.java
Related to #10426
Fixes the build.
=> [orbitbhyve] Apply spotless

bundles/org.openhab.binding.bluetooth.airthings/src/main/java/org/openhab/binding/bluetooth/airthings/internal/AirthingsWaveGen1Handler.java
Related to #11052
Fixes build.
=> [airthings] Fix SAT error

bundles/org.openhab.binding.oppo/README.md, bundles/org.openhab.binding.oppo/src/main/resources/OH-INF/thing/channels.xml
Just a bunch of small documentation changes that I have accumulated. No functional code changes.
=> [oppo] update README

bundles/org.openhab.binding.homeconnect/README.md
=> [homeconnect] New how-to entry in doc about OAuth files

.gitignore
Related to https://github.com/openhab/openhab-addons/pull/10983#issuecomment-890565680
=> [amplipi] Ignore files from openapi-generator

bundles/org.openhab.binding.fsinternetradio/README.md
=> [fsinternetradio] Fix DIR3100 and Auna Connect CD mode

bundles/org.openhab.binding.networkupstools/src/main/resources/OH-INF/thing/channels.xml
=> [networkupstools] Missing status added

bundles/org.openhab.binding.mqtt.espmilighthub/src/main/resources/OH-INF/thing/thing-types.xml
=> [mqtt.espmilighthub] Sematic Tags added.

bundles/org.openhab.persistence.dynamodb/README.md
=> [dynamodb] AWS setup guidance updated in docs

bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/dto/airpollution/Components.java
- Fix ozone mapping in DTO
See https://community.openhab.org/t/openweathermap-not-updating-ozone/125195
=> [openweathermap] Fix ozone mapping in DTO

bundles/org.openhab.binding.nuvo/README.md
Fix broken sitemap example and several other minor edits.
=> [nuvo] Update Nuvo README

bundles/org.openhab.binding.miio/README.md, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoDevices.java, bundles/org.openhab.binding.miio/src/main/resources/database/dmaker.fan.p18-miot.json
=> [miio] Add support for  Mi Smart Standing Fan 2 (dmaker.fan.p18)

bundles/org.openhab.binding.miio/README.md, bundles/org.openhab.binding.miio/src/main/resources/database/dmaker.fan.p18-miot.json, bundles/org.openhab.binding.miio/src/main/resources/database/mijia.vacuum.v2-miot.json, bundles/org.openhab.binding.miio/src/main/resources/database/qmi.powerstrip.v1.json
improve mija vacuum channels
Closes #11056
=> [miio] improve/add properties for qmi powerstrip

bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoVacuumHandler.java, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/robot/RRMapDraw.java, bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/robot/RRMapDrawOptions.java
Allow to customize all the mapdrawing parameters
Allows to crop the blue borders to the actual map 
closing: #10112
=> [miio] map improvement cropping and customizable colors/parameters

bundles/org.openhab.binding.smhi/README.md, bundles/org.openhab.binding.smhi/src/main/java/org/openhab/binding/smhi/internal/ForecastAggregator.java, bundles/org.openhab.binding.smhi/src/main/java/org/openhab/binding/smhi/internal/SmhiHandler.java
Fixes an exception thrown by ForeastAggregator.total(), when there's only one hour left of the day.
Reported [here](https://community.openhab.org/t/smhi-weather-binding/65728/55).
=> [smhi] Fix IndexOutOfBoundsException in aggregator function

bundles/org.openhab.binding.telegram/pom.xml, bundles/org.openhab.binding.telegram/src/main/java/org/openhab/binding/telegram/internal/TelegramBindingConstants.java, bundles/org.openhab.binding.telegram/src/main/java/org/openhab/binding/telegram/internal/TelegramHandler.java, bundles/org.openhab.binding.telegram/src/main/java/org/openhab/binding/telegram/internal/action/TelegramActions.java
Contains bug fixes and also updates the library that is needed to implement a requested feature in #7279
Possible fix for #9792 where basic auth is not working for some (?) people.
closes #10807 Sends message when downloading of a file occurs.
=> [telegram] Send message if a file download fails and bug fixes.

bundles/org.openhab.binding.wemo/README.md
Corrected the humidifier mode label.
=> [wemo] Update README.md

bundles/org.openhab.binding.benqprojector/README.md, bundles/org.openhab.binding.benqprojector/src/main/java/org/openhab/binding/benqprojector/internal/BenqProjectorCommandType.java, bundles/org.openhab.binding.benqprojector/src/main/java/org/openhab/binding/benqprojector/internal/handler/BenqProjectorHandler.java
Should fix #11126. Change from equalsIgnoreCase() to equals() to avoid locale specific issues with equalsIgnoreCase().
=> [benqprojector] Fix equalsIgnoreCase issue

bom/openhab-addons/pom.xml
Added Twitter binding to Addon Bundles POM File
Signed-off-by: Scott Hanson <scooter_seh@yahoo.com> (github: computergeek1507)
=> Added Twitter binding to Addon POM

bundles/org.openhab.binding.doorbird/README.md, bundles/org.openhab.binding.doorbird/src/main/java/org/openhab/binding/doorbird/internal/api/DoorbirdInfo.java, bundles/org.openhab.binding.doorbird/src/main/java/org/openhab/binding/doorbird/internal/config/ControllerConfiguration.java, bundles/org.openhab.binding.doorbird/src/main/java/org/openhab/binding/doorbird/internal/handler/ControllerHandler.java, bundles/org.openhab.binding.doorbird/src/test/java/org/openhab/binding/doorbird/internal/DoorbirdInfoTest.java
Signed-off-by: True Random <rantruedom@gmail.com>
Fixes https://github.com/openhab/openhab-addons/issues/11184
=> [doorbird] fix controller id

bom/openhab-addons/pom.xml, bundles/pom.xml
=> [linky] Removed from the distribution until it is fixed

bundles/org.openhab.binding.remoteopenhab/README.md
Signed-off-by: Laurent Garnier <lg.hc@ree.fr>
=> [remoteopenhab] Example with a connection to myopenhab.org
